### ISSUE TITLE
HTML Artifacts 

### ISSUE THREAD

**Issue by limx0** [PrefectHQ/prefect#10011]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Artifacts currently only support links/markdown/tables. 

### Describe the proposed behavior

It would be great from a formatting perspective if HTML was supported - this would open the door to much more complex and powerful formatting.

### Example Use

Building more powerful tables by formatting with pandas styles and publishing the HTML.

### Additional context

This old issue exists but never got any comment: https://github.com/PrefectHQ/prefect/issues/4033

**Comment by WillRaphaelson** [comment]
Hey @limx0 - thanks for the issue. This is actually already supported via markdown artifacts - basic html should render just fine in the UI.

**Comment by eiko4** [comment]
@WillRaphaelson I tried creating html - it didn't work. do you have an example of a function call?

**Comment by eiko4** [comment]
#4033 it was ignored
