### ISSUE TITLE
SQLite section repeats twice the same sentence

### ISSUE THREAD

**Issue by georgedouzas** [PrefectHQ/prefect#10028]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The installation instructions include  the same [sentence](https://github.com/PrefectHQ/prefect/blob/b616dd7f6c6c31a7464d6d15bc6488371d387258/docs/getting-started/installation.md?plain=1#L183) twice.

### Describe the proposed change

Keep only one sentence.

**Comment by serinamarie** [comment]
Thanks for the issue @georgedouzas!
