### ISSUE TITLE
Prefect creates a new database in working directory inappropriately

### ISSUE THREAD

**Issue by 1beb** [PrefectHQ/prefect#10024]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm using the following to create a deployment that relies on code in src/
```
import os
import sys

parent_dir = os.path.abspath(os.path.join(os.getcwd()))
sys.path.append(parent_dir)

from etl.group.flows import x, y, z # y, z not shown here
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule


x_deployment = Deployment.build_from_flow(
    flow=x, # the function x in flows.py module has @flow(name="...")
    name="x",
    version=1,
    path="/home/me/repo",
    schedule=CronSchedule(cron="30 7 * * *"),
)

if __name__ == "__main__":
    x_deployment.apply()
```

This structure works for other folders, but for this etl.group when I call: 

```
python3 etl/group/_deployments.py
```

It does something strange. 

1. Instead of using the root ~/.prefect folder, it creates a new prefect.db inside the directory I ran the deployment. 
2. It spits out a warning: 

```
/usr/lib/python3.8/contextlib.py:120: SAWarning: Skipped unsupported reflection of expression-based index ix_flow_run__coalesce_start_time_expected_start_time_desc
  next(self.gen)
/usr/lib/python3.8/contextlib.py:120: SAWarning: Skipped unsupported reflection of expression-based index ix_flow_run__coalesce_start_time_expected_start_time_asc
  next(self.gen)
```

This is strange because I am using the exact same deployment structure for 2 other groups (etl/group/module, where group varies). 

### Reproduction

```python3
I can't reproduce it.
```

### Error

```python3
There are no errors. Over many iterations I have tried, I received an attribute error, but I'm unable to fix it. 

`AttributeError: 'State' object has no attribute 'services'`
```

### Versions

```Text
Version:             2.10.11
API version:         0.8.4
Python version:      3.8.10
Git commit:          8c651ffc
Built:               Thu, May 25, 2023 2:59 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```
```


### Additional context

_No response_

**Comment by desertaxle** [comment]
Thanks for opening an issue @1beb! I wonder if there's something changing your configuration and causing this behavior. Could you share the output of `prefect config view` from your machine? Could you also try upgrading the latest version and see if this still happens?

**Comment by desertaxle** [comment]
Upon a second look, your call to `sys.path.append` could be causing some strange behavior. Do you have that call in your other modules?

**Comment by 1beb** [comment]
```
$ prefect config view
PREFECT_PROFILE='default'
```

re: `sys.path.append` yes, it's everywhere because we are trying to separate our flows from reusable code. I'll give it a show putting the etl folder under src/ see if it still happens.

**Comment by 1beb** [comment]
Tinkered with this a bit more, removed the sys.path.appends and it didn't fix it. The problem was related to having a bunch of flows in the same file. It's unclear what triggered it as I tried a lot of variations. But splitting them out into separate files worked. I'm going to close this.
