### ISSUE TITLE
Allow for disabling logging configuration

### ISSUE THREAD

**Issue by Cassy343** [PrefectHQ/prefect#10051]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, prefect overwrites the logger configuration when the root module is first loaded.

### Describe the proposed behavior

An environment variable along the lines of `PREFECT_LOGGING_SKIP_CONFIG` would be introduced which would bypass the above behavior and not modify the logger configuration at all. Perhaps this could also be accomplished by setting `PREFECT_LOGGING_SETTINGS_PATH` to a sentinel value like the empty string.

### Example Use

This problem came up because, in our current set up, our config is configured during django startup and a number of the configuration fields are determined at run time, meaning that setting `PREFECT_LOGGING_SETTINGS_PATH` is insufficient because that configuration is static. In essence our configuration is handled by an entirely different app and it makes the most sense to have prefect not modify it at all.

**Comment by desertaxle** [comment]
Thanks for the issue @Cassy343! Could you share a code example of how you configure your logging setup? An example will help us determine if the behavior you're looking for is currently possible with Prefect or what changes would be necessary to make it possible.

**Comment by Cassy343** [comment]
Hello, thanks for taking a look at this. For the time being we think we have found a work-around using the logging settings path and the server log level. We'll let you know if this doesn't end up suiting our needs.
