### ISSUE TITLE
High memory consumption when sending events

### ISSUE THREAD

**Issue by nibrag** [PrefectHQ/prefect#10063]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a RabbitMQ block in my project with a `publish` method. I run my flows in k8s job with memory limitations (1gb).
My flow called `publish` 500k times and k8s job was killed by OOM.
I started to dig and faced that all public methods of block emit events, so `publish` generated 500k events and prefect `EventsWorker` could not consume them fast and flow run got OOM.

I saw `PREFECT_EXPERIMENTAL_ENABLE_EVENTS_CLIENT` option in prefect and I tried to disable it, but looks like it does nothing.

I use own local prefect server. Is it possible to turn off events completely?

### Reproduction

```python3
Call block methods 500k times.
```

### Versions

```Text
2.10.11
```

**Comment by desertaxle** [comment]
Thanks for the issue, @nibrag! If you use your Prefect server, each block method call will trigger an `emit_event` call, but events will be discarded and never sent to an `EventsWorker`. Can you consistently reproduce this issue, and if so, can you share any tracebacks or logs printed by your flow run?

**Comment by zanieb** [comment]
@desertaxle that change was made in 2.10.12 https://github.com/PrefectHQ/prefect/pull/9684/commits/1f8d972865856e0660b77e44d997f2555d219d5c

@nibrag this should be resolved by upgrading your Prefect library.

**Comment by nibrag** [comment]
@zanieb ok, I see.

@desertaxle @zanieb thanks for the help
