### ISSUE TITLE
FlowRunContext.task_run_states is empty whereas I can see tasks in the UI

### ISSUE THREAD

**Issue by PierrePernot** [PrefectHQ/prefect#10080]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi,
I am trying to list the states of my flow's tasks. But when using `FlowRunContext.task_run_states`, it is always an empty list (I checked in between tasks, thanks to the debugger) . I can see in the UI that tasks are created and run.

PS: I'm refreshing the context everytime I check with get_run_context().

### Reproduction

```python3
@task(name="my_task")
def sample_task():
    print ("Hello World!")

@flow(name="my_flow")
def sample_flow():
    sample_task.submit()
    context = get_run_context()
    print(context.task_run_states)
```

### Versions

```Text
2.10.17
```

**Comment by WillRaphaelson** [comment]
Thanks @PierrePernot, we'll get this in the queue

**Comment by zanieb** [comment]
I believe that task run would be saved in `task_run_futures` since it is submitted.

**Comment by PierrePernot** [comment]
Thanks for the answer @zanieb. Unfortunately, all the tasks in `task_run_futures` remain in the PENDING state. Even if I can see in the UI that they are completed.
Could you please have a look ?

**Comment by zanieb** [comment]
@PierrePernot see #9317 for that issue.

You can call `future.wait()` to get the final state of a future.

FWIW the flow run context is used for internal tracking and I would not necessarily recommend building on it. 

@WillRaphaelson maybe there should be a `get_task_runs` utility that returns all of the task run objects in a flow run?
