### ISSUE TITLE
Add code block to blocks core load function doc string.

### ISSUE THREAD

**Issue by jeanluciano** [PrefectHQ/prefect#10095]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Function `load` in blocks.core has MD formatting issues, making the one of the examples not be in code blocks.

### Describe the proposed change

Add an additional code block

**Comment by desertaxle** [comment]
Thanks for the issue @jeanluciano! Can you share a link to the page where you're seeing the incorrect formatting?

**Comment by jeanluciano** [comment]
https://docs.prefect.io/2.10.17/api-ref/prefect/blocks/core/#prefect.blocks.core.Block.load
