### ISSUE TITLE
Server stops immediately after running the start command

### ISSUE THREAD

**Issue by edcalderin** [PrefectHQ/prefect#10117]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The server suprensigly is stopping immediately after running `prefect server start`.

Here is the current output:
```
$ prefect server start

 ___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |
|_| |_|_\___|_| |___\___| |_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



Server stopped!
```
Here is my evidence:
https://github.com/PrefectHQ/prefect/assets/4134771/55ac7c65-b708-4d06-88bb-0325e0d303b7

So, I have not still got this solved. Anyone has an idea?

### Reproduction

```python3
conda create --name my-env python=3.9
source activate my-env
pip install prefect
prefect init
prefect server start
```

### Versions

```Text
Version:             2.10.18
API version:         0.8.4
Python version:      3.9.16
Git commit:          cf177852
Built:               Thu, Jun 29, 2023 2:34 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.41.2
```

### Additional context

I also tried with prefect 2.10.16 and failed too, the same with python 3.10.

**Comment by serinamarie** [comment]
Hi @edcalderin, thanks for the issue! Do you know which version you were last using where `prefect server start` worked successfully?

**Comment by edcalderin** [comment]
Hi @serinamarie I had used `prefect==2.10.12` a few weeks ago. Nowaday, this one doesn't work either.
