### ISSUE TITLE
Sendgrid email prefect notifications

### ISSUE THREAD

**Issue by Ishankoradia** [PrefectHQ/prefect#10119]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently there is no option to create a sendgrid email notification block.

### Describe the proposed behavior

User will be able to select a `Sendgrid email` notification block and add the respective details to trigger emails on selective/all flow run states & tags

**Comment by zhen0** [comment]
@Ishankoradia - with your PR (**thank you**!) can we consider this one closed?

**Comment by zhen0** [comment]
Marking as closed by #10118 Please let us know if you still consider this an issue
