### ISSUE TITLE
Trigger AWS Step Function Workflow

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1012]
We should add a Task to our Task Library (in `src/prefect/tasks/aws`) for triggering the execution of AWS Step Function workflows.  Presumably this can be done from the Step Function API (e.g., https://docs.aws.amazon.com/step-functions/latest/apireference/API_StartExecution.html) with some authentication parameters that can be stored as Prefect Secrets.

**Comment by jhagege** [comment]
Hi, is it possible to fetch a result at the end of the execution of the step function ? 
I was thinking doing so with a PubSub / SNS message sent from the Step function job, but then how to fetch the result back in the Prefect pipeline ? 
Thanks for any insight.

**Comment by cicdw** [comment]
Hi @jhagege - yes, it is possible using the [`describe_execution` call from boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.describe_execution) which will return the JSON output from the step function.

It's not immediately clear to me whether `boto3` has [a `Waiter`](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#waiters) for step functions, but if it did then it would be fairly easy to wait for job completion and return that result back into your Prefect Flow
