### ISSUE TITLE
Audit Log: Include Deletion Events

### ISSUE THREAD

**Issue by trahloff** [PrefectHQ/prefect#10142]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Deployments that are deleted will not show up as an event in the audit log.

### Describe the proposed behavior

Deployments that are deleted show up as an event in the audit log.

### Example Use

Accidental deletion of production flows could either be the result of a CI/CD pipeline showing a non-expected behavior, or someone deleted the deployment. 
Having the audit log, this would be something that everybody could easily check.

**Comment by WillRaphaelson** [comment]
Thanks for the issue @trahloff - audit log is primary at this time for "account-level" events, for example, the creation of users, changes to access, deletion of workspaces. Deployments fall into workspace level objects, which at this time we are not adding to the audit log.

**Comment by WillRaphaelson** [comment]
Thanks @trahloff - deleted my old comment closing this out. We will be adding audit events for workspace level objects in the next quarter. I may change up the requirements here as we get closer to design, but we will tackle this problem.

**Comment by zangell44** [comment]
@trahloff Prefect Cloud will begin recording deployment create/update/delete events later today. We'll be expanding the set of workspace level audit events going forward.

Thanks for the feature request!

**Comment by trahloff** [comment]
Thanks for the quick implementation @zangell44! This will make our life much easier going forward and will improve the debugging UX tremendously.
