### ISSUE TITLE
Unable to select correct date/time for deployment flow run parameters

### ISSUE THREAD

**Issue by apolisskaya** [PrefectHQ/prefect#10158]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

My team is attempting to use the date selection tool to set deployment flow run parameters. The selection is not behaving as expected - the date/time being clicked isn't always what is selected, and attempting to retry by clicking the correct value is causing the other date in our params to decrement by a single day each time. The desired selected times are a week apart.

### Reproduction

https://github.com/PrefectHQ/prefect/assets/19937265/f0aef1ea-115f-4c0a-94e4-89a2b9f8b484

### Error

^ See recording in reproduction section.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by pleek91** [comment]
@apolisskaya thanks for reporting! Would you be able to provide the schema from your deployment? Or a minimum reproduction flow. Thanks!

**Comment by apolisskaya** [comment]
> @apolisskaya thanks for reporting! Would you be able to provide the schema from your deployment? Or a minimum reproduction flow. Thanks!

Not sure what you mean by the schema from the deployment -- if you can give me an example of what that'd look like or where I might find it, I'd appreciate it!

To reproduce:
Given some deployment taking `start_dt` and `end_dt` as two input parameters, use the menu at the top right to edit the deployment. When clicking the param value, a datetime picker window appears, but the desired values cannot be reliably selected as seen in the recording. We are also seeing selected values not persisting on refresh, even when they are "saved", and trying to enter the intended datetimes as JSON rather than using the date picker results in incorrect/missing param values on refresh.

**Comment by apolisskaya** [comment]
Update: I was able to set the desired values for our run by using the JSON tab and entering datetime strings 14 hours ahead of our actual desired run times, then saving. On refresh, the times appeared as the original intended times (not the strings I entered). Not sure if that's helpful 😄

**Comment by apolisskaya** [comment]
@acookin

**Comment by acookin** [comment]
this is the output of `prefect deployment inspect` for this flow, is this sufficient? @pleek91 
```
{
    'id': 'ad58c1c8-e167-4ff8-a86a-73a7bb17bd4f',
    'created': '2022-10-13T17:49:19.462742+00:00',
    'updated': '2023-07-05T22:20:45.287195+00:00',
    'name': 'trigger_measures_week_emails',
    'version': 'f4546258d1950fb97c09c06a8a172f8a',
    'description': '',
    'flow_id': '6b872ddd-545b-4d8c-a036-90390e13f4fc',
    'schedule': {'interval': 3600.0, 'anchor_date': '2023-07-06T05:30:00+00:00', 'timezone': 'UTC'},
    'is_schedule_active': True,
    'infra_overrides': {},
    'parameters': {'measures_week_end_dt': '2023-07-16T14:00:00.000Z', 'measures_week_start_dt': '2023-07-09T14:00:00.000Z'},
    'tags': ['agent:octave-core', 'deployment:trigger_measures_week_emails', 'flowgroup:welkin_measures', 'schedule:enabled'],
    'work_queue_name': 'trigger_measures_week_emails',
    'parameter_openapi_schema': {
        'type': 'object',
        'title': 'Parameters',
        'required': ['measures_week_start_dt', 'measures_week_end_dt'],
        'properties': {
            'measures_week_end_dt': {'type': 'string', 'title': 'measures_week_end_dt', 'format': 'date-time', 'position': 1},
            'measures_week_start_dt': {'type': 'string', 'title': 'measures_week_start_dt', 'format': 'date-time', 'position': 0}
        }
    },
    'path': None,
    'pull_steps': [],
    'entrypoint': 'REDACTED.py:trigger_measures_week_emails',
    'manifest_path': None,
    'storage_document_id': 'c28cb2e3-15f9-4b65-8da4-dcf49ff665d6',
    'infrastructure_document_id': '18caa07f-804b-4a04-ab80-abacfaea9bbe',
    'created_by': None,
    'updated_by': {"id":"REDACTED"},
    'work_pool_name': 'default-agent-pool',
    'infrastructure': {'type': 'process', 'env': {}, 'labels': {}, 'name': None, 'command': None, 'stream_output': True, 'working_dir': None, 'block_type_slug': 'process'},
    'automations': []
}
```

**Comment by pleek91** [comment]
@apolisskaya this fix will go out with the next release. Thanks again for reporting!
