### ISSUE TITLE
Option to stream flow run logs

### ISSUE THREAD

**Issue by rmorshea** [PrefectHQ/prefect#10183]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently there is  stream logs from a flow run. This is useful if users are programmatically kicking off flow runs, but don't necessarily want to check the Prefect Server's UI to find the logs.

### Describe the proposed behavior

An extremely simple log streaming implementation given the current API would look like:

```python
logger = logging.getLogger()
flow_run_id = (await run_deployment(..., timeout=0)).id

client = get_client()
log_filter = LogFilter(flow_run_id=LogFilterFlowRunId(any_=[flow_run_id]))

log_query_offset = 0
while True:
    await asyncio.sleep(1)

    flow_run = await client.read_flow_run(flow_run_id)
    for log in flow_logs:
        logger.log(log.level, log.message)
    log_query_offset += len(flow_logs)

    if flow_run.state.is_final():
        break
```

This does not account for logs produced by subflows, though that could potentially be remedied in follow-up work.

### Example Use

The simplest way usage would be to integrate streaming into `run_deployment`:

```python
my_logger = getLogger()
await run_deployment(..., stream_logs_to=my_logger)
```

Under the hood `run_deployment` would logic similar to the code snippet above to send logs from the flow run to the user's logger.

### Additional context

We have a `run_flow` function that wraps Prefect in order to allow users to seamlessly run flows locally or remotely simply by switching an environment variable. We'd like the ability to stream logs so that the user's experience is no different than if they'd been running the flow locally.

**Comment by zanieb** [comment]
For reference, there's a relatively comprehensive implementation of this in Prefect 1 at https://github.com/PrefectHQ/prefect/blob/2b859e5c75401850579598986a6c9a52d23cc5ff/src/prefect/backend/flow_run.py#L22-L178

**Comment by AmanSal1** [comment]
@rmorshea @zanieb  Can I work on this ?

**Comment by serinamarie** [comment]
@AmanSal1, I can assign you to this.

**Comment by zanieb** [comment]
@AmanSal1 you'll want to talk to an employee e.g. @serinamarie

**Comment by AmanSal1** [comment]
@zanieb Okay will coordinate.

**Comment by rmorshea** [comment]
@AmanSal1 @serinamarie, as a note, it does not seem like the original implementation had a way to stream logs from subflows. It would be great if that could be achieve in whatever you all decide to build.

**Comment by rmorshea** [comment]
Here's an implementation that will stream sub-flow logs:

```python
import asyncio
from prefect import get_client
from uuid import UUID
from logging import Logger
from typing import Sequence
from prefect.client.schemas import FlowRun
from prefect.server.schemas.filters import (
    LogFilter,
    LogFilterFlowRunId,
    FlowRunFilter,
    FlowRunFilterId,
    FlowRunFilterParentTaskRunId,
    TaskRunFilter,
    TaskRunFilterSubFlowRuns,
)
from prefect.server.schemas.core import Log

async def stream_flow_run_logs(root_flow_run_id: UUID, logger: Logger) -> None:
    client = get_client()
    log_query_offsets: dict[UUID, int] = {}
    while True:
        await asyncio.sleep(3)

        root_flow_run = await client.read_flow_run(root_flow_run_id)
        flow_runs = [root_flow_run, *(await _read_sub_flows(root_flow_run))]
        flow_run_log_offsets = [log_query_offsets.setdefault(flow_run.id, 0) for flow_run in flow_runs]
        flow_run_log_lists = await asyncio.gather(*[_read_flow_run_logs(*args) for args in zip(flow_runs, flow_run_log_offsets)])

        for flow_run, log_list in zip(flow_runs, flow_run_log_lists):
            for log in log_list:
                logger.log(log.level, log.message)
            log_query_offsets[flow_run.id] += len(log_list)

        if root_flow_run.state.is_final():
            break


async def _read_sub_flows(flow_run: FlowRun) -> Sequence[FlowRun]:
    client = get_client()
    flow_run_filter = FlowRunFilter(id=FlowRunFilterId(any_=[flow_run.id]))
    task_run_filter = TaskRunFilter(subflow_runs=TaskRunFilterSubFlowRuns(exists_=True))
    flow_task_runs = await client.read_task_runs(flow_run_filter=flow_run_filter, task_run_filter=task_run_filter)

    task_run_ids = [task_run.id for task_run in flow_task_runs]
    sub_flow_run_filter = FlowRunFilter(parent_task_run_id=FlowRunFilterParentTaskRunId(any_=task_run_ids))
    sub_flow_runs = await client.read_flow_runs(flow_run_filter=sub_flow_run_filter)

    sub_sub_flow_runs = await asyncio.gather(*[_read_sub_flows(r) for r in sub_flow_runs])
    return list(sub_flow_runs) + [r for runs in sub_sub_flow_runs for r in runs]


async def _read_flow_run_logs(flow_run: FlowRun, offset: int) -> Sequence[Log]:
    log_filter = LogFilter(flow_run_id=LogFilterFlowRunId(any_=[flow_run.id]))
    return await get_client().read_logs(log_filter, offset=offset)  # type: ignore  (prefect is mistyped)
```

**Comment by AmanSal1** [comment]
@serinamarie Hi, can you guide me on how to implement this in Prefect 2?

**Comment by rmorshea** [comment]
@AmanSal1, the solution above works in Prefect 2.

**Comment by rmorshea** [comment]
With that said, it would be nice if there were a flag on `run_deployment` that could do this for you automatically. Not sure if that's something @serinamarie is willing to consider though.

**Comment by AmanSal1** [comment]
@rmorsheaI have a doubt. Currently, in Prefect 2, you can view the logs of a flow run, but I believe they are not in real-time. Therefore, we need to implement real-time streaming of logs. Additionally, we also need to add logs for the subflows.
Right ?

**Comment by rmorshea** [comment]
> I believe they are not in real-time

Correct. That's why, in the implementation above, I poll the server and offset the query whenever getting new logs

```python
async def stream_flow_run_logs(root_flow_run_id: UUID) -> AsyncIterator[Log]:
    client = get_client()
    log_query_offsets: dict[UUID, int] = {}
    while True:
        await asyncio.sleep(3)
        ...
```

Obviously it would be nice if there was a way to _truly_ stream the logs from the server, but I suspect that would require a lot more work since, even in Prefect 1 they took the same approach. It seems better to get something working first and then improve it later.

**Comment by AmanSal1** [comment]
@rmorshea  Yes, it's true. One more thing b based on my understanding, real-time streaming should involve the immediate printing of logs in the command line as they are generated. However, currently, the logs are only printed in the command line after some time when all the tasks are finished. This means that it doesn't qualify as a real-time stream for the logs.

**Comment by rmorshea** [comment]
I don't know what the current behavior is, but the implementation I wrote above will yield new logs each time it checks the server for them (in this case 3 seconds). Increasing the polling rate will increase how "real-time" the yielded logs are.

**Comment by zhen0** [comment]
Thanks for the issue @rmorshea!  I'm adding to our backlog.  @AmanSal1 - this one could get a little complex as we'd need special handling for how we do this in Prefect Cloud.  It might make sense to have a look for another issue. Thank you though for your excitement about adding to Prefect.

**Comment by rmorshea** [comment]
@zhen0, I've been using [this implementation](https://github.com/PrefectHQ/prefect/issues/10183#issuecomment-1629915369) at my company which is currently using Prefect cloud. Is there something missing there or are you talking about backend changes?

**Comment by zhen0** [comment]
Hey @rmorshea - thanks for the follow up!  I don't think you're missing anything in your suggestion.  It was more that we hope that we could make use of events in Prefect Cloud for this.

**Comment by rmorshea** [comment]
I've discovered that [my polling implementation](https://github.com/PrefectHQ/prefect/issues/10183#issuecomment-1629915369) is unreliable. I suspect that this might have to do with race conditions on the server with respect to `offset` when logs are actively being added to a flow.
