### ISSUE TITLE
prefect profile get in docs is not a command

### ISSUE THREAD

**Issue by SomethingUseful** [PrefectHQ/prefect#10186]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

prefect profile get in docs is not a command. docs need updated.
https://docs.prefect.io/2.10.18/concepts/settings/#configuration-profiles

### Describe the proposed change

.

### Additional context

.

**Comment by serinamarie** [comment]
@SomethingUseful, thank you for raising this issue!
