### ISSUE TITLE
Intermittent errors in hourly processes 500 Internal with link to ephemeral server

### ISSUE THREAD

**Issue by 1beb** [PrefectHQ/prefect#10230]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running prefect server and prefect agent on the same machine. I see a lot of lockouts but on my hourly tasks I see 3-4 of these crashes on a daily basis. It happens right after code has been copied. 

```
Crash detected! Execution was interrupted by an unexpected exception: PrefectHTTPStatusError: Server error '500 Internal Server Error' for url 'http://ephemeral-prefect/api/block_documents/'
Response: {'exception_message': 'Internal Server Error'}
For more information check: https://httpstatuses.com/500
```

### Reproduction

It happens intermittently to all my flows. I don't know of a way to explicitly recreate it. If you have recommendations for debugging I'm happy to assist. Here is how I start my server and agent: 

```{shell}
$ source venv/bin/activate
$ screen -S prefect
> $ prefect server start
# ctrl a + d
$ screen -S agent
> $ prefect agent start -p "default-agent-ppol
# ctrl a + d
```

### Error

```
Crash detected! Execution was interrupted by an unexpected exception: PrefectHTTPStatusError: Server error '500 Internal Server Error' for url 'http://ephemeral-prefect/api/block_documents/'
Response: {'exception_message': 'Internal Server Error'}
For more information check: https://httpstatuses.com/500
```

### Versions

```Text
Version:             2.10.16
API version:         0.8.4
Python version:      3.8.10
Git commit:          6cd7c3ee
Built:               Tue, Jun 20, 2023 2:59 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

**Comment by zzstoatzz** [comment]
Hi @1beb - do you happen to have the server logs from when this crashed?

**Comment by 1beb** [comment]
@zzstoatzz server logs are a bit tricky I have it in a screen: 


I see a lot of database locks happening: 

```
File "/home/user/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
self.await_(_cursor.execute(operation, parameters))
File "/home/user/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
return current.driver.switch(awaitable)  # type: ignore[no-any-return]
File "/home/user/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
value = await result
File "/home/user/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 48, in execute
await self._execute(self._cursor.execute, sql, parameters)
File "/home/user/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 40, in _execute
return await self._conn._execute(fn, *args, **kwargs)
File "/home/user/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 133, in _execute
return await future
File "/home/user/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 106, in run
result = function()
  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM flow_run_notification_queue WHERE flow_run_notification_queue.id IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)]
```

**Comment by OptimeeringBigya** [comment]
We have been facing similar issues after moving to 2.10.20 from 2.10.12.

**Comment by 1beb** [comment]
Hi @zzstoatzz is there anything else that I can provide you with for debug?

**Comment by zzstoatzz** [comment]
hi @1beb - are you still on 2.10.x while encountering these errors?

also, are you typically using the ephemeral server? do you have a sense for whether these locking issues occur locally / with the ephemeral app only?

**Comment by 1beb** [comment]
Hi @zzstoatzz I'm not sure I understand your terminology here. I've provided an explicit example of how I started the server. I often work on the remote server that is running prefect directly to debug. These crashes are persistent on the remote.

**Comment by zzstoatzz** [comment]
if you look at your `prefect version` output above, there's this line
```
Server type:         ephemeral
```

which means your `PREFECT_API_URL` isn't pointing at a running server, so prefect will ephemerally run an instance of the server as needed.

If I wanted to run against a server myself, I would do
```
❯ prefect profile create local

Created profile with properties:
    name - 'local'
    from name - None

Use created profile for future, subsequent commands:
    prefect profile use 'local'

Use created profile temporarily for a single command:
    prefect -p 'local' config view

❯ prefect profile use local
⠧ Checking API connectivity...
No Prefect server specified using profile 'local' - the API will run in ephemeral mode.

❯ prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
Set 'PREFECT_API_URL' to 'http://127.0.0.1:4200/api'.
Updated profile 'local'.
```

and then I would see
```
❯ prefect version
Version:             2.11.4
API version:         0.8.4
Python version:      3.11.0
Git commit:          7d2a9103
Built:               Thu, Aug 17, 2023 3:41 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server # not ephemeral
```

**Comment by 1beb** [comment]
Oh ok, let me check this, I actually set the URL recently so I could click error notifications from slack while I had the port forwarded.

**Comment by 1beb** [comment]
I set the api url and this issue appears to have cleared. I'll look again tomorrow to be sure.

**Comment by 1beb** [comment]
Confirming that this was resolved after setting the PREFECT_API_URL.
