### ISSUE TITLE
RESIZE the columns in the deployment page using a Separator like in excel 

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10266]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

From User:
We have a scenario where we have large flow and deployment names.  Because of this Deployment tab in prefect UI not showing all other columns like schedule , Tags etc in a single view.

It will be great if we have an option to RESIZE the columns using Separator like we have in excel ( refer to screenshot below), with Auto wrap of text. It’s a UI look and field enhancement.

![image](https://github.com/PrefectHQ/prefect/assets/68969861/cbebabf6-0491-41d3-80d1-dbc831a624c6)

### Describe the proposed behavior

see above

**Comment by billpalombi** [comment]
We'll resolve this problem in a different way.
