### ISSUE TITLE
Server sent an abort signal: This run is in a PENDING state and cannot transition to a PENDING state

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#10263]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When an agent submits a flow run, it proposes a `Pending` state. During this request, it's possible for the client to timeout but for the server to still succeed*. In this case, the flow run enters a `Pending` state on the server, but the client raises a retry-able `httpx.ReadTimeout` error. When the request is then retried, the server denies the state transition leaving the flow run stuck in the `Pending` state.

*Not confirmed, but seems to fit all the evidence

This issue is very similar to #8084, but the outcome is different. As suggested in the issue, the behavior can be mitigated by increasing the client-side timeout by setting `PREFECT_API_REQUEST_TIMEOUT`.

### Reproduction

```python3
# Has been observed in the wild but is difficult to reproduce
```

### Error

```python3
# The agent logs will contain something like the following

INFO | prefect.agent - Submitting flow run '<FLOW-RUN-ID>'"

...

DEBUG | prefect.client - Encountered retryable exception during request. Another attempt will be made in <FLOAT>s. This is attempt <ATTEMPT>/6.

Traceback (most recent call last):
...
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2576)
...
The above exception was the direct cause of the following exception:
...
httpx.ReadTimeout

...

INFO | prefect.agent - Aborted submission of flow run '<FLOW-RUN-ID>'. Server sent an abort signal: This run is in a PENDING state and cannot transition to a PENDING state.
```

### Versions

```Text
2.10.12
```

**Comment by zangell44** [comment]
As a first step, I think we should mitigate the `ReadTimeout` issue by increasing the default value of `PREFECT_API_REQUEST_TIMEOUT`.

**Comment by EmilRex** [comment]
Saw another instance of this. The user was on version 2.10.13 and was getting the same `Server sent an abort signal: This run is in a PENDING state and cannot transition to a PENDING state`, however there was no `httpx.ReadTimeout`. The only other error in the agent logs was `GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed to process item` but it occurred frequently at other times when everything worked correctly, leading me to believe it is unrelated.

**Comment by jakekaplan** [comment]
@EmilRex in the instance you saw recently, they're seeing this when only running a single worker/agent?

**Comment by EmilRex** [comment]
Yep! Can't fully confirm that there's only one agent, but I saw the "Submitting flow" log and then the error in the same log, a few seconds apart. Still waiting on flow run IDs for the most recent occurrence. Same thing previously happened on August 17th with flow run `afdcb471-d50c-472d-b85a-2cf3cd54d36b`.

**Comment by jakekaplan** [comment]
Thanks! Do you also have the workspace_id for that flow run per chance?

**Comment by EmilRex** [comment]
@jakekaplan I believe it is `322ddc32-0695-4bd9-8629-233d960bd1db`.

**Comment by jakekaplan** [comment]
Some relevant logs:
https://console.cloud.google.com/logs/query;query=%22afdcb471-d50c-472d-b85a-2cf3cd54d36b%22;pinnedLogId=2023-05-04T16:47:11.803363Z%2Fs%3D9d338c7ab7de49e989ce4f597ec160e3%3Bi%3D81ac584%3Bb%3Da9398d92bce64c13bbe2290672b12629%3Bm%3D20761daf488%3Bt%3D5fae0ec8c83e3%3Bx%3D47c69533be960aa1-0-0@a1;summaryFields=:false:32:beginning;cursorTimestamp=2023-08-17T06:46:40.736354Z;startTime=2023-08-16T15:30:32.161Z;endTime=2023-08-19T15:30:32.161Z?project=prefect-prd-cloud2

**Comment by jakekaplan** [comment]
The default request timeout was increased to 60s here: https://github.com/PrefectHQ/prefect/pull/10543/files

If this persists after upgrading we can re-open this issue

**Comment by lxndrlst** [comment]
I'm currently having this issue as well. Is this something that can be looked more into? 

From what I can gather from the logs of the agent service, the sequence of events is: 1) the flow run is scheduled in advance, 2) just before the scheduled runtime, the flow is submitted successfully, and 3) the flow run is aborted with a message: `Server sent an abort signal: This run is in a PENDING state and cannot transition to a PENDING state.`

**Comment by IrynaKitoraha** [comment]
The issue with the scheduled deploymnet is still there.  I have exactly the same problem as @lxndrlst. 
Can you fix it @EmilRex? thanks

> I'm currently having this issue as well. Is this something that can be looked more into?
> 
> From what I can gather from the logs of the agent service, the sequence of events is: 1) the flow run is scheduled in advance, 2) just before the scheduled runtime, the flow is submitted successfully, and 3) the flow run is aborted with a message: `Server sent an abort signal: This run is in a PENDING state and cannot transition to a PENDING state.`

**Comment by zhen0** [comment]
Possibly connected to #11499

**Comment by vkrot-innio** [comment]
I'm still experiencing this a lot with on-premise prefect `2.20.15`, using 2 kubernetes workers, 2 prefect servers. could it be some concurrency issue due to 2 replicas of workers and servers?
