### ISSUE TITLE
Toggle to show/hide subflows in the UI

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#10272]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Parent and child flows are displayed the same way on the flow runs page. When a workspace has many child flows (i.e. subflows), it can be hard to find the parent flows, especially when there are multiple levels of subflows.

### Describe the proposed behavior

It would be wonderful if there was a toggle to show/hide child flows on the flow runs page. This would also be helpful in the dashboard. Ideally it would be savable in a flow run saved page view.

**Comment by billpalombi** [comment]
I fully agree that this is a problem. I doesn't have a straightforward solution, but we must find a way to address it.

**Comment by EmilRex** [comment]
I believe there's a field called `parent_task_run_id` on the flow run, which when `null` indicates that the flow run is not a child flow. Is it possible to add a checkbox near the top of the flow runs page that filters on that field?

**Comment by billpalombi** [comment]
I think we explored that and it wasn't feasible for some reason, but I may be mistaken. Regardless, I've added this to the UI backlog.

**Comment by brandonreid** [comment]
This is headed to staging. Will add to OSS tomorrow. Great solution @EmilRex! For some reason my mind could only think of nesting sub flows under parent flows. This was way easier and gets the job done possibly better.

**Comment by EmilRex** [comment]
@brandonreid This makes me so unreasonably happy! Thank you for implementing and shipping this 🚀 :shipit:

**Comment by BenSeimon** [comment]
Sorry for dragging up an old closed issue.

But it seems like the ability to toggle show/hide subflows in the UI was not carried over into v3. Is it possible to add this feature?

**Comment by brandonreid** [comment]
@BenSeimon some of us (myself included) are no longer at Prefect. Could be worth creating a new issue.
