### ISSUE TITLE
Show CLI warning if worker is polling a paused work pool or queue

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#10308]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Users can start up a worker polling a paused work queue thinking work will start submitting, but there is no indication that the work pool is paused.

### Describe the proposed behavior

If a worker is polling a paused work pool or queue, display a message such as 

The work queue {name} is paused, flows will not be submitted for execution.

**Comment by zhen0** [comment]
I think you're meaning for this message to be in the cli? I believe we used to have something like this for agents and love this suggestion - I'm going to bump to priority medium because I think it would save users a few headaches.

**Comment by WillRaphaelson** [comment]
correct @zhen0 and I've edited for clarity. thank nyou
