### ISSUE TITLE
Custom Webhook Notification for Prefect Cloud Users

### ISSUE THREAD

**Issue by dmigl-craneww** [PrefectHQ/prefect#10307]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently whenever using Prefect `Automations` to send a Notification your options are to choose from a limited set of 3rd party webhooks (i.e, Teams, Slack, pagerDuty) or a default email. 
![image](https://github.com/PrefectHQ/prefect/assets/124075900/b60bfa41-151d-43f8-b19f-d498091deec3)

A 3rd option is to call a generic webhook that  sends a un-customizable payload: `"message": <"body-text-here">`:

![image](https://github.com/PrefectHQ/prefect/assets/124075900/2721abf9-dfc1-41bb-a800-02d99c68dd65)

### Describe the proposed behavior

The proposed behavior is to allow for a customizable payload similar to what already exists for self-hosted users - [achieved in this PR](https://github.com/PrefectHQ/prefect/pull/9547)

![image](https://github.com/PrefectHQ/prefect/assets/124075900/921a8bd4-d624-49c7-98c9-f25b6be1b8e5)

### Example Use

would be able to send a custom payload using a generic webhook as opposed to the set described previously.

### Additional context

https://prefect-community.slack.com/archives/C0192RWGJQH/p1689199823518919

**Comment by zhen0** [comment]
This looks like a solid suggestion to me but I'm adding the product feedback label in case there was a deliberate decision around this that I'm not remembering.

**Comment by WillRaphaelson** [comment]
thanks @dmigl-craneww - this is a good suggestion. I'm closing in favor of https://github.com/PrefectHQ/prefect/issues/10443 just because it has a few more details on implementation.
