### ISSUE TITLE
When using a callable for custom flow_run_name and task_run_name the parameters should be passed to the callable

### ISSUE THREAD

**Issue by NicholasFiorentini** [PrefectHQ/prefect#10319]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, one can use a format string or a callable without parameters to customize the flow run name (or task) at runtime.

### Describe the proposed behavior

To allow much more flexibility, using a callable with the flow's parameter should be possible. This would allow a flow run name with both a dynamic part (ex: current timestamp) and the current run parameters.

### Example Use

```python
def custom_flow_name(parameters: dict[str, Any]) -> str:
	now = datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')
	other_value = parameters["param"]
	return f"{now}-myflow-{other_value}"

@flow(
	flow_run_name=custom_flow_name,
)
def example(param: str, another_param: int):
  ...
```

**Comment by cicdw** [comment]
Hi @NicholasFiorentini ! While this isn't as explicit as what you wrote, you can do this today via `prefect.runtime` as follows:

```python
from prefect.runtime import flow_run

def custom_flow_name() -> str:
    now = datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')
    other_value = flow_run.parameters["param"]
    return f"{now}-myflow-{other_value}"
```

We opted for this more implicit approach as it is more general for other use cases (e.g., configuring a task runner at runtime based on flow run parameters) and easier to maintain forwards and backwards compatibility with.  

I'm going to close this issue as resolved but please let me know if there is a use case we aren't covering!

**Comment by NicholasFiorentini** [comment]
@cicdw Thanks! Didn't know it.
