### ISSUE TITLE
Add `--ci` deprecation warning to `prefect deploy --help`

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#10326]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The description for the `--ci` flag does not include a deprecation warning.

### Describe the proposed behavior

Recommend using `--no-flag` instead

### Example Use

Disables interactive prompts and will error if any required arguments are not provided. DEPRECATED: Please use the global `--no-prompt` flag instead: `prefect --no-prompt deploy`

**Comment by AmanSal1** [comment]
@billpalombi can I work on this ?

**Comment by serinamarie** [comment]
@AmanSal1 that looks right to me! 👍

**Comment by AmanSal1** [comment]
@serinamarie I have published a PR can you review 

Link : https://github.com/PrefectHQ/prefect/pull/10347
