### ISSUE TITLE
Emit events for flow run deletion action

### ISSUE THREAD

**Issue by ttq186** [PrefectHQ/prefect#10325]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When a flow run is deleted, there is no corresponding event showing up in the event feed.

### Describe the proposed behavior

When a flow run is deleted, there should be an event created for this action.

### Example Use

Some members of the team can accidentally delete some flow runs. We need this action to be recorded as an event so that we can create the corresponding automation to have a better understanding of this deletion.

**Comment by WillRaphaelson** [comment]
Thanks for the issue @ttq186 - we're going to work on filling out the inventory of orchestration events some time in the next quarter. I am placing this in deferred for now!
