### ISSUE TITLE
Move docs page on using the API to guides

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10333]
### First check

- [x] I added a descriptive title to this issue.
- [x] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The how-to guide for using the Prefect API probably fits best under guides. 
This issue splits off half of an issue created by @gabcoyne 

Add more about and consider elevating the PrefectClient.

### Describe the proposed change

Move the how-to use the API document to guides

**Comment by WillRaphaelson** [comment]
thanks, i think this is super useful!

**Comment by discdiver** [comment]
Closing as resolved in 3.x docs.
