### ISSUE TITLE
Task Runs list of a Flow Run: Show Number of Tasks

### ISSUE THREAD

**Issue by toro-berlin** [PrefectHQ/prefect#10342]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I can't tell how many tasks there are from the (filtered) task runs list of a flow run. The only option is to scroll down and count by eye and finger. This manual workaround is only suitable for flow runs with only a few tasks.

### Describe the proposed behavior

Display the number of tasks shown in the list. The displayed number should reflect all tasks for a flow run currently know of and not only the displayed (lazy loading).

See the screenshot below for a mock.
![image](https://github.com/PrefectHQ/prefect/assets/120258756/3f132cc3-e0cd-4ba4-b218-9b4f005676ee)

### Example Use

A typical question I am currently not getting an answer for is: How many tasks are in a failed state?

### Additional context

There is a similar issue regarding the number of subflows for a flow: https://github.com/PrefectHQ/prefect/issues/9099

**Comment by zhen0** [comment]
I've gone back and forth a bit on whether this is medium or high priority.  Given the impact of the enhancement and the fact that it seems lowish lift I've landed on high priority.

**Comment by toro-berlin** [comment]
Thanks, @pleek91, for this enhancement! I just checked it out in the new shiny Prefect UI. It is really beneficial for us and our operators!
