### ISSUE TITLE
Prefect's StepActivate task doesn't allow parameterization

### ISSUE THREAD

**Issue by ybressler** [PrefectHQ/prefect#10349]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a flow where I am trying to run an AWS Step function. My flow first retrieves credentials, then passes those credentials to a StepActivate task. However, when I pass these creds as a task, it fails.

### Reproduction

```python3
from prefect import task, Flow
from prefect.tasks.aws.step_function import StepActivate

# Instantiate step function
run_step_function = StepActivate()


@task()
def retrieve_aws_credentials() -> dict:
    return {"aws_access_key_id":"FOO", "aws_secret_access_key": "BAR"}


with Flow("step_func_test") as flow:

    # Get credentials
    credentials_dict = retrieve_aws_credentials()

    # Call the step function task (eq to task.run)
    run_step_function(
        execution_name="step_function_test",
        state_machine_arn="FOO_BAR",
        boto_kwargs=credentials_dict
    )
```

### Error

```python3
TypeError: prefect.utilities.aws.get_boto_client() argument after ** must be a mapping, not FunctionTask
```

### Versions

```Text
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-13.4-arm64-arm-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "1.1.0",
    "python_version": "3.9.16"
  }
}
```

### Additional context

I've tried a few changes / iterations to address, without success.

Setting the `execution_name` on the `StepActivate` class results in the following error:
```
AttributeError: 'StepActivate' object has no attribute 'logger'
```

**Comment by WillRaphaelson** [comment]
Hi @ybressler and thanks for your issue. We are not currently accepting enhancement proposals for Prefect 1. for information on how to migrate to Prefect 2, check out our [guide](https://docs.prefect.io/latest/guides/migration-guide/).
