### ISSUE TITLE
Allow prefect to work in air-gapped environments

### ISSUE THREAD

**Issue by sticreations** [PrefectHQ/prefect#10343]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

We are encountering an issue with running Prefect in our cluster environment where internet access is restricted due to company security policies. Prefect pulls configurations from the URL https://raw.githubusercontent.com/, which is causing our cluster deployments to fail.

https://github.com/PrefectHQ/prefect/blob/1d611266959de2f146dfc05a5e3e402a7e3cd1bb/src/prefect/server/api/collections.py#L29

Steps to Reproduce:

Deploy Prefect in a cluster environment with restricted internet access.
Attempt to run a Prefect workflow that requires configurations from https://raw.githubusercontent.com/PrefectHQ/prefect/view/(view).json

Expected Behavior:
Prefect should provide a mechanism to configure a mirror for the https://raw.githubusercontent.com/ URL, allowing the cluster to access necessary configurations without requiring direct internet access. In Our example this would be a mirrored githubusercontent Repository in Artifactory.

Actual Behavior:
Without internet access, Prefect is unable to pull configurations from https://raw.githubusercontent.com/, leading the Frontend isnt working.

### Describe the proposed behavior

A possibility to configure a Repository MIrror, either via configuration or Environment Variable.

```PREFECT_GITHUB_MIRROR_URL="http://internal-mirror/githubusercontent/"```

**Comment by WillRaphaelson** [comment]
thanks for the issue @sticreations - you're correct that this currently precludes air-gapped deployments. I'm going to rephrase the issue slightly to be less prescriptive - while configuring a mirror is one route, we could also bake this content into the image or facilitate more graceful failures.

**Comment by desertaxle** [comment]
Closing this as resolved via https://github.com/PrefectHQ/prefect/pull/11503
