### ISSUE TITLE
Facilitate seperation of environment specific deployment config

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#10352]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, I cannot have more than one `prefect.yaml` file in the same directory. Prefect's recommendation is that I workspaces and repositories are 1 to 1. To adhere to that, I would effectively duplicate an entire project.

### Describe the proposed behavior

I want to be able to have multiple `prefect.yaml` files such that each file can be specific to an environment. I would love to be able to optionally specify a deployment file with the `deploy` CLI command. 

This is not the only potential solution. We should explore others.

### Example Use

For example, I could have three files -`prefect-dev.yaml`, `prefect-stage.yaml`, and `prefect-prod.yaml`- in the same directory, then update the deployments in my staging file with:

`prefect deploy --file prefect-stage.yaml`

**Comment by taylor-curran** [comment]
Just noting that the ability to have multiple prefect.yaml files in the same repo has been requested for a variety of different reasons.
