### ISSUE TITLE
log table is growing

### ISSUE THREAD

**Issue by hillbun** [PrefectHQ/prefect#10356]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

log table is growing

how to define log level or max log days?

### Describe the proposed behavior

log table is growing

how to define log level or max log days?

**Comment by OptimeeringBigya** [comment]
Also related : https://github.com/PrefectHQ/prefect/issues/5813

Related conversation in Community channel: https://prefect-community.slack.com/archives/CL09KU1K7/p1690880480700819

So far, it seems like the users of OSS should manage it on their own. One of the blobs linked in the conversation suggests using `pg_cron` to run delete sql which is not a bad idea if you do not want complex logic governing deletion of logs.

Thanks for creating the ticket. I was going to create one myself.

**Comment by WillRaphaelson** [comment]
Thanks @hillbun. We'll be accepting #10000 to remove logs of flow runs that are deleted, but for general log table management, OSS users are expected to manage this themselves.
