### ISSUE TITLE
Cancellation behavior differs when flow cancelled during submitted task vs a regular task

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#10367]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Please see this comment: https://github.com/PrefectHQ/prefect/issues/10195#issuecomment-1665775286

### Reproduction (modified from user issue #10195)

```python3
import time
from prefect import flow, get_run_logger, task
from prefect.deployments import Deployment

@task
def submitted_task():
    logger = get_run_logger()
    logger.info('Submitted task running!')
    for i in range(100):
        logger.info(f'Iteration {i}')
        time.sleep(1)

@task
def regular_task():
    logger = get_run_logger()
    logger.info('Regular task running!')
    for i in range(100):
        logger.info(f'Iteration {i}')
        time.sleep(1)

# running this flow, crash is detected
# @flow
# def sample_flow():
#    regular_task() 

# running this flow, no crash is detected
# @flow
# def sample_flow():
#     submitted_task.submit() 

if __name__ == '__main__':
    deployment = Deployment.build_from_flow(
        flow=sample_flow,
        name="example-deployment", 
        version=1, 
        work_pool_name="local-pool",
        work_queue_name="default"
    )
    deployment.apply()
```

### Error
Cancelling a flow during a submitted task:

```bash
10:41:20.485 | INFO    | prefect.worker.process.processworker 6733b328-fb8e-4a91-b417-ebf9f6eec566 - Found 1 flow runs awaiting cancellation.
10:41:20.646 | ERROR   | prefect.flow_runs.worker - Process 2175 exited with status code: -15; This indicates that the process exited due to a SIGTERM signal. Typically, this is caused by manual cancellation.
10:41:23.767 | INFO    | prefect.flow_runs.worker - Cancelled flow run '78f67a64-799c-47c9-8b59-ddddf81d145b'!
```

Cancelling a flow during on non-submitted task:
```bash
10:43:21.367 | INFO    | prefect.worker.process.processworker 8fe0f8e2-104e-46c1-b848-e27305dd19dd - Found 1 flow runs awaiting cancellation.
10:43:21.526 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
10:43:21.527 | ERROR   | Task run 'sample_task-0' - Crash detected! Execution was cancelled by the runtime environment.
10:43:21.527 | DEBUG   | Task run 'sample_task-0' - Crash details:
Traceback (most recent call last):
  File "/Users/bean/code/prefect/src/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
asyncio.exceptions.CancelledError
```

### Versions

```Text
Version:             2.10.17+167.gbeedb2eef0.dirty
API version:         0.8.4
Python version:      3.10.4
Git commit:          beedb2ee
Built:               Thu, Aug 3, 2023 10:58 AM
OS/Arch:             darwin/arm64
Profile:             cloud
Server type:         cloud
```

**Comment by AmanSal1** [comment]
@serinamarie Can I give it a shot ?

**Comment by serinamarie** [comment]
@AmanSal1 Sure! It needs some research.

**Comment by AmanSal1** [comment]
@serinamarie  oh okay .  I just wanted to ask that to reproduce this error first we have to run the above code which you have given and then cancel it using the UI in between . Additionally with this we just need to comment out the lines alternatively ?

**Comment by serinamarie** [comment]
Yes, you'd want to comment out one of the tasks. I've updated the description to clarify!

**Comment by AmanSal1** [comment]
@serinamarie  After conducting research, the issue occurs when an asynchronous operation is wrapped using asyncio.wrap_future(), and subsequently encounters a CancelledError. The wrapped future does not handle the cancellation gracefully. Therefore, we should either properly clean up the things associated with it, essentially the future, or we can set the associated future to None whenever a cancellation of a submitted task is performed. What do you think about this ?

**Comment by AmanSal1** [comment]
@serinamarie  One more point to note is that in asynchronous programming, the CancelledError exception is raised when a coroutine is cancelled either by explicitly calling the cancel() method on a Task, or when the associated Future object is cancelled using the cancel() method. Therefore, it's not something we can avoid; we can only handle this exception based on the requirements of our application.

**Comment by prefectcboyd** [comment]
I think this is related - https://github.com/PrefectHQ/prefect/issues/10826
@serinamarie already commented, so I do believe this is similar, however, I see the behavior occurring in tasks that are NOT submitted to the Task Runner, which doesn't seem in line with this issue? Not sure if they are separate or the same, just that the behavior in my case __is__ consistent between submitted or not.
