### ISSUE TITLE
project pull_steps output log to worker and prefect server for troubleshooting

### ISSUE THREAD

**Issue by coolbreeze2** [PrefectHQ/prefect#10376]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

project pull_steps output no log

### Describe the proposed behavior

project pull_steps output log to worker and prefect server for troubleshooting

**Comment by desertaxle** [comment]
Thanks for the issue @coolbreeze2! Could you please give a little more information or examples about what information you want to be able to see when troubleshooting deployment steps?
