### ISSUE TITLE
Extend container command functionality to optional arguments after prefect.engine

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#10400]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The current entrypoint command is `["python", "m", "prefect.engine"]`.
Any additional commands arguments supplied beyond this are treated as a flow run id.

### Describe the proposed behavior

Permit an extensible `command` that allows for customized behavior beyond the prefect.engine, such as:

`["python", "-m", "prefect.engine", ";", "<run some cleanup commands, like POSTing to an endpoint>"]`

### Example Use

Implications could be for some container / pod / cluster level hooks and commands that are not tied to the prefect.engine succeeding or failing.

For example, using sidecar containers would linger around without a cleanup signal.
In the event that a pod never fails, but never transitions to a running state either, the pod will continue to run until it's manually cleaned up. 
This would allow for cleanup behavior regardless of prefect actions.

### Additional context

Below is a good example that was raised in an internal slack of implications and use case.

https://stackoverflow.com/questions/74492858/kubernetes-cronjob-with-a-sidecar-container/74498023#74498023

Additionally, the following suggestion came up as a __possible__ mechanism to fix : 

i think it's a fairly trivial fix to change the following [try/except block](https://github.com/PrefectHQ/prefect/blob/16f46ca49838cbdb250d113bb149f13ca819302d/src/prefect/engine.py#L2464-L2472) in the prefect code to allow subsequent commands after ["python", "-m", "prefect.engine"], and I don't expect prefect team to repro our specific problem - I just want to confirm that adding subsequent commands will not impact prefect behavior (which it sounds like it wouldn't to me but :shrug: ), and we can try it out at our own discretion (edited) 
[engine.py](https://github.com/PrefectHQ/prefect/blob/16f46ca49838cbdb250d113bb149f13ca819302d/src/prefect/engine.py)
```
    try:
        flow_run_id = UUID(
            sys.argv[1] if len(sys.argv) > 1 else os.environ.get("PREFECT__FLOW_RUN_ID")
        )
    except Exception:
        engine_logger.error(
            f"Invalid flow run id. Recieved arguments: {sys.argv}", exc_info=True
        )
        exit(1)
```

**Comment by jawnsy** [comment]
At the moment, when we run a flow (the Prefect engine), we do so without spawning a shell, which is what normally handles features like running multiple semicolon-delimited commands, pipe redirection, etc.

I believe you should be able to customize the whole command using an infra override, to allow you to achieve this desired behavior. In that case, you would use something like:

```yaml
command:
  - /bin/sh
  - -c
  - |
    python -m prefect.engine
    cleanup_command
    other_shell command
```

More first-class lifecycle hooks or scripts like you describe could also make sense (we could implement this as part of a standard entrypoint script, with other scripts invoked prior to the engine starting and after the engine completes successfully). Users can then load these entrypoint scripts by mounting a ConfigMap at the appropriate location, or we could pass in small scripts as environment variables.

We might also want to consider how these would interact with [Kubernetes' built-in PostStart/PreStop hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)

Some code references that may be helpful:

* https://prefecthq.github.io/prefect-kubernetes/worker/#prefect_kubernetes.worker.KubernetesWorkerJobConfiguration
* https://github.com/PrefectHQ/prefect-kubernetes/blob/b14ad8f1fe9cc2df11b164d9490ab37fd0f27723/prefect_kubernetes/worker.py#L482-L533
* The default manifest sets `args` (the Dockerfile `CMD`) but not `command` (the Dockerfile `ENTRYPOINT`), which means that jobs would run with the default image entrypoint (which you can also override). This gives you a way to wrap the actual command that runs as you wish (i.e. the `args` will be passed in as arguments to the entrypoint, which you can override either by building a custom image with a different entrypoint, or by mounting your own entrypoint script using a ConfigMap); our [default entrypoint](https://github.com/PrefectHQ/prefect/blob/94316c59e895896f48672674a2eea43b1f09018a/Dockerfile#L126) should be `"/usr/bin/tini", "-g", "--", "/opt/prefect/entrypoint.sh"`

**Comment by rphamle** [comment]
I have tried the `infra_overrides` route but am getting an error, which I never get when I set `infra_overrides = {}`.

What seems to be happening is that when I set `infra_overrides` to a non-empty dict (or rather, the `"customizations"` field in it), then the rest of the manifest fails to be populated on runtime, even if I have it defined in my base job manifest. For example, `"spec.template.spec.containers[0].name"` is missing, even though I already define it in the `base_job_manifest` that I pass to `KubernetesJob(job=base_job_manifest)`.

If I go ahead and add in the 2 missing manifest fields into `infra_overrides` anyway, then I will get the same error but on `spec.template.spec.containers[1].name/spec.template.spec.containers[1].image` (one of my job's sidecars) - I do not want to have to duplicate all of these manifest fields into `infra_overrides`.

```python
COMMAND = [
    "/bin/sh", "-c", "|",
    "python", "-m", "prefect.engine", ";",
    "curl", "-sS", "-X", "POST", "<to-some-endpoint>",  ";",
]

infra_overrides = {
    "customizations": 
        [
            {
                # using "op": "replace" did not work, as the error log stated that "command" was non-existent
                "op": "add",
                "path": "/spec/template/spec/containers/0",
                "value": {
                    "command": COMMAND,
                },
            },
        ]
}

deployment = Deployment.build_from_flow(
   ...
   infra_overrides=infra_overrides,
)
```


```json
Submission failed. kubernetes.client.exceptions.ApiException: (422) Reason: Unprocessable Entity HTTP response 
headers: HTTPHeaderDict(
    {
        "Audit-Id": "d1e7ee48-e54c-414a-a74c-403467b41f4c",
        "Cache-Control": "no-cache, private",
        "Content-Type": "application/json",
        "X-Kubernetes-Pf-Flowschema-Uid": "0b4b3b13-77bb-4949-96fd-05d9dacc046d",
        "X-Kubernetes-Pf-Prioritylevel-Uid": "b1d00735-c066-4895-acb4-d401c7efef19",
        "Date": "Mon, 14 Aug 2023 21:29:50 GMT",
        "Content-Length": "569"
    }
) 
HTTP response body: 
    {
        "kind": "Status",
        "apiVersion": "v1",
        "metadata": {},
        "status": "Failure",
        "message": "Job.batch \"sqprefect-tests-2bpfc\" is invalid: [spec.template.spec.containers[0].name: Required value, spec.template.spec.containers[0].image: Required value]",
        "reason": "Invalid",
        "details": {
            "name": "sqprefect-tests-2bpfc",
            "group": "batch",
            "kind": "Job",
            "causes": [
            {
                "reason": "FieldValueRequired",
                "message": "Required value",
                "field": "spec.template.spec.containers[0].name"
            },
            {
                "reason": "FieldValueRequired",
                "message": "Required value",
                "field": "spec.template.spec.containers[0].image"
            }
            ]
        },
        "code": 422
    }
  
```

**Comment by rphamle** [comment]
(I talked about this comment with @prefectcboyd in Slack, pending response but will put info in this issue)

I think I misunderstood your initial suggestion of using infra overrides and used the literal `infra_overrides` option in my previous comment, which did not work. 

But following your intended suggestion by making the change to the kubernetes manifest file below seems to work?
```
# base job manifest yaml
...      
    containers: 
        - name: prefect-job
          # override the container entrypoint to clean up the sidecars after flow run
          command: 
            - /bin/sh
            - -c
            - |
              python -m prefect.engine
              curl -sS -X POST to-endpoint1
              curl -sS -X POST to-endpoint2
```

My 2 curl endpoints above are definitely executing after the Flow Run executes (whether the Flow Run is successful, unsuccessful, or never even starts (e.g. due to infra issues)). However, if I run `kubectl describe pod <my pod>` at runtime, 
I see `python -m prefect.engine` twice:

```
Containers:
  prefect-job:
    Command:
      /bin/sh
      -c
      python -m prefect.engine
      curl -sS -X POST to-endpoint1
      curl -sS -X POST to-endpoint2
      
    Args:
      python
      -m
      prefect.engine
```

It looks like prefect will [always override](https://github.com/PrefectHQ/prefect-kubernetes/blob/b14ad8f1fe9cc2df11b164d9490ab37fd0f27723/prefect_kubernetes/worker.py#L356-L384) `Args` at runtime with `python -m prefect.engine`.

FWIW I have a simple Flow (prints "hello world") that seems to be running fine despite the double `python -m prefect.engine`, but I haven't done any extensive testing on it, including:
-run a longer, more complicated Flow
- run Flow with sub-Flows
- retrying a Flow
- etc

**Comment by rphamle** [comment]
^ I want to add that I am using Agents in my most recent comment, and not Workers.

**Comment by EmilRex** [comment]
I believe this point may be moot now that the default command is `prefect flow-run execute` which has better argument validation.
