### ISSUE TITLE
Event-driven Deployment: Add a convenient way to register a trigger

### ISSUE THREAD

**Issue by toro-berlin** [PrefectHQ/prefect#10413]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

My current way of adding a trigger to a deployment is

1. Execute `prefect deployment build [...]`
2. Manually edit the generated `deployment.yaml` in the forbidden area (`### DO NOT EDIT BELOW THIS LINE`) to add the trigger

(also see https://docs.prefect.io/2.11.3/concepts/automations/#create-an-automation-via-deployment-triggers).

This is not a convenient way we want to include in our CI pipeline for flow repositories.

### Describe the proposed behavior

From my perspective, there are two ways to address this:

- The trigger is related to the deployment (would match the scheduling configuration options):
  - Add the option to the `Deployment.build_from_flow` method.
  - Add an option to the CLI `prefect deployment build [...]` that accepts trigger definitions.
  - Add the option to define triggers in the `prefect.yaml`.
- The trigger is part of the flow code (feature will be accessible more easily): Add a flow decorator for triggers

**Comment by WillRaphaelson** [comment]
Thanks for the issue @toro-berlin - these are good suggestions and I will address them in turn.

Add the option to the Deployment.build_from_flow method.
We currently have a team improving the python deployments experience more generally, they will be addressing the interface. ccing @cicdw.

Add an option to the CLI prefect deployment build [...] that accepts trigger definitions.
I'm open to a dedicated issue for this, honestly, my hesitancy has been the fact that the devex of passing in the trigger json to the CLI could be quite ugly. Cleaning it up could be via the ability to pass in a --trigger-spec-file value, but at that point why not just edit the prefect.yaml?

Add the option to define triggers in the prefect.yaml.
This is possible today! See [docs](https://docs.prefect.io/2.11.3/concepts/automations/?h=automation#create-an-automation-via-deployment-triggers)

The trigger is part of the flow code (feature will be accessible more easily): Add a flow decorator for triggers
Based on user feedback, the trigger is really at the deployment level. I'd like to keep it there for the time being to let the interfaces gel before considering porting it to other objects.

Lets keep this open for discussion but im going to place it in deferred as we decide whats worth tackling. Thanks again for the issue.

**Comment by toro-berlin** [comment]
Thanks for your reply, I will get back to you next week!

**Comment by toro-berlin** [comment]
Thanks @WillRaphaelson!

**Add the option to define triggers in the `prefect.yaml`**
Okay, I now found it there in the documentation (https://docs.prefect.io/2.11.4/concepts/deployments/#deployment-fields). Unfortunately, we are currently on a prefect-agent infrastructure and have not yet migrated to worker pools. `prefect.yaml` would be my preferred way if we have migrated.

**Add an option to the CLI `prefect deployment build [...]` that accepts trigger definitions**
Currently, we use the `prefect deployment build [...]` in our CI Pipeline (see also above). So, for me, the easiest way to onboard to the event trigger feature would be to have the option pass a simple `important-flow_trigger.yaml` to this command.
If this whole CLI command gets deprecated soonish, I would be happy to get a signal for us to migrate away.

**Deployment.build_from_flow method.**
This is a pre-requisite for making it available to the prefect deployment command, right?

**The trigger is part of the flow code**
I totally understand that. I understand triggers also as something deployment-related.

**Comment by WillRaphaelson** [comment]
> Deployment.build_from_flow method.
> This is a pre-requisite for making it available to the prefect deployment command, right?

Maybe, probably. I do know that the work being done on python deployments will facilitate this. 

I think the issue to pull out here is just to ensure CLI experiences for deploying flows elegantly incorporate trigger configuration options. If you agree I'm going to close this and create a dedicated issue for this use case.

**Comment by toro-berlin** [comment]
I agree, thanks for the discussion and for creating the new issue.
