### ISSUE TITLE
Subject and Body of PagerDuty Automation Appear Concatenated in the Incident Title

### ISSUE THREAD

**Issue by biancaines** [PrefectHQ/prefect#10427]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a PagerDuty block with an automation, the fields for the subject and body of the notification become concatenated and are both present in the title of the incident in PagerDuty. When using the default inputs for an automation (with all flow run metadata) it results in a lengthy incident title, which is difficult to interpret. 

The screenshots below show how the subject and body of the notification is set, and how the information is currently presented in PagerDuty.
<img width="1141" alt="automation_screenshot" src="https://github.com/PrefectHQ/prefect/assets/105657837/4afd0cd3-9a86-442a-8529-9d4b7085ebd9">
<img width="1335" alt="pagerduty_prefect_1_top" src="https://github.com/PrefectHQ/prefect/assets/105657837/a87f0002-d676-45e6-bfb3-7ac0b1a5e410">
<img width="1443" alt="pagerduty_prefect_2_bottom" src="https://github.com/PrefectHQ/prefect/assets/105657837/013e3520-ed8f-441e-88fd-a842ad3fe6e1">

Ideally, the title should only include the subject provided to the automation. The information in the body would be in the Custom Details section of the incident report. See the examples below for how Datadog notifications are presented in PagerDuty.
<img width="981" alt="pagerduty_datadog_1_top" src="https://github.com/PrefectHQ/prefect/assets/105657837/e0c417d2-4a7d-44eb-bca6-da1142411263">
<img width="947" alt="pagerduty_datadog_2_bottom" src="https://github.com/PrefectHQ/prefect/assets/105657837/8458a84f-ca98-43a0-9aa5-936906811f70">

 

### Reproduction

```python3
1. Create a PagerDuty notification block
2. Create an automation which, when triggered, fires off a notification using the block. Enter information into the fields for the subject and body of the notification.
3. Once the automation is triggered, preview the resulting incident report in PagerDuty.
```

### Error

```python3
No error provided.
```

### Versions

```Text
2.10.11
```

**Comment by ConstantinoSchillebeeckx** [comment]
Any updates on this?

**Comment by rphamle** [comment]
I noticed that if I send an alert to PagerDuty using an Automation -> Pager Duty Webhook Block, the message that is generated from the incident on PagerDuty's side looks like an [Events V1 payload](https://developer.pagerduty.com/api-reference/f0037990796c8-send-an-event-to-pager-duty), rather than an [Events V2 payload](https://developer.pagerduty.com/api-reference/368ae3d938c9e-send-an-event-to-pager-duty). Is this expected?

**Comment by thaparsahil** [comment]
> The way to work around this for now is to omit a title, and set only the body.
The subject is not optional though. At least not on the UI

**Comment by kevingrismore** [comment]
Not sure if this is an acceptable solution, but having a special case for PagerDuty in [act](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/events/actions.py#L1274) for the `SendNotification` action does the job:

```python
    async def act(self, triggered_action: "TriggeredAction") -> None:
        block = await self._get_notification_block(triggered_action=triggered_action)

        subject, body = await self.render(triggered_action)
        
        # Reshape the block a little bit for PagerDuty
        if block._block_type_slug == "pager-duty-webhook":
            if block.custom_details:
                block.custom_details.update({"body": body})
            else:
                block.custom_details = {"body": body}
            body = ""
            block.block_initialization()
                
        with block.raise_on_failure():
            try:
                await block.notify(subject=subject, body=body)
            except NotificationError as e:
                self._result_details["notification_log"] = e.log
                raise ActionFailed("Notification failed")

    async def render(self, triggered_action: "TriggeredAction") -> List[str]:
        return await self._render([self.subject, self.body], triggered_action)
```

**Comment by zzstoatzz** [comment]
just to surface some sync discussion with @kevingrismore, I think we need to handle this within the `PagerDutyWebhook` implementation, not in the automations code here as a special case. In particular, we will likely need to change how `block_initialization` works for this block (and perhaps in general post `pydantic>2`
