### ISSUE TITLE
Weight based task run concurrency limits

### ISSUE THREAD

**Issue by meggers** [PrefectHQ/prefect#10428]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Prefect current supports task run concurrency limits based on the number of tasks runs

### Describe the proposed behavior

Concurrency limits based on weights of task runs where some task runs could represent more "weight" than others. Could be an integer parameter of the task. Prefect would not schedule tasks until the task weight could be accommodated by the limit.

The current functionality could be modeled as weight based where the weight of each task run is 1.

### Example Use

```
@task(name="hello-task", tags=["test"], weight_param="weight")
def my_task(weight: int):
    print("Hello, I'm a task")
```

**Comment by serinamarie** [comment]
Hi @meggers, thanks for your first issue to prefect! Can you provide more details on a use case for this?

**Comment by meggers** [comment]
FWIW I think this is mostly solved with https://docs.prefect.io/latest/guides/global-concurrency-limits/#using-the-concurrency-context-manager and the occupy param
