### ISSUE TITLE
Remove "message" key from the call webhook automation action

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#10443]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, webhook bodies are sent out in the form of 

"message" {body}

### Describe the proposed behavior

The webhook action would send the materialized body directly with no message key for additional control of use in downstream applications.

### Additional context

Existing webhooks automations should get updated by prefect to contain "message": in the action spec to avoid a breaking change. Front end and backend changes will need to go out together.

**Comment by ndrplz** [comment]
Thanks for taking this. For bookkeeping, the context for this feature request is in [this thread](https://discourse.prefect.io/t/cant-make-a-rocketchat-webhook-work-from-prefect-cloud-how-should-i-compose-the-body/3454), i.e. the current wrapping under "message" breaks RocketChat notifications.
