### ISSUE TITLE
Allow users to set delay transition time for Secure Task Concurrency Slots

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#10460]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, the delay transition time for secure  task concurrency slots is hardcoded to 30 seconds.

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/orchestration/core_policy.py#L140-L143

### Describe the proposed behavior

Introduce a new prefect configuration/setting that allows the user to set the value for the transition delay.

### Example Use

Example usage similar as documented in https://docs.prefect.io/2.11.4/guides/settings/

### Additional context

Our flows are using mapped tasks that are limited by task concurrency tags. The task by themselves take roughly 1 seconds. However, because the transition delay is hard coded to 30, after each task is "completed", the worker is idle and waits for 30 seconds. It would be great if this delay could be configured by the user.

**Comment by OptimeeringBigya** [comment]
Hello @WillRaphaelson 
Any updates on this?

**Comment by WillRaphaelson** [comment]
Thanks @OptimeeringBigya ive upper our internal priority on this. When we pick it up, we can decide on the best implementation. I think this should be a setting on the worker. Thoughts?

**Comment by OptimeeringBigya** [comment]
@WillRaphaelson I am unsure about the internal working within Prefect. 

I would think that the value in the server is the default value for all the workers and the value in a specific worker works as an override for that worker.

If this is too complicated, I think it is fine to just have it in worker only.
We have several PRs on our end blocked by this feature request that I would rather have something than nothing. :)

**Comment by zangell44** [comment]
Quick update from the Prefect side: we're planning to take up this work early next week.
