### ISSUE TITLE
Page back issue to Flow runs page from a task run logs page.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10461]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

From a user:

In Flow run page of the UI, we are noticing that a page back issue.

 

### Reproduction

Steps to reproduce :

 

Go to Flow run page. Click on any flow run.  Click on task run tab.

![image](https://github.com/PrefectHQ/prefect/assets/68969861/415c61b4-acf9-4bc3-9188-d6a0d16e1963)

Click into any task to see its task run page with logs and artifacts

**Now click the back button**, it will give a blank screen instead of showing the flow run page for that flow run id

![image](https://github.com/PrefectHQ/prefect/assets/68969861/8ec4ad28-9472-4b25-92fc-6e768a974c86)

### Error

![image](https://github.com/PrefectHQ/prefect/assets/68969861/8ec4ad28-9472-4b25-92fc-6e768a974c86)

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by znicholasbrown** [comment]
Ah I'll close this manually when the fix is released

**Comment by bunchesofdonald** [comment]
I confirmed that this is no longer an issue. Clicking back when on the task run page now takes you back to the flow run page.

**Comment by znicholasbrown** [comment]
ah thank you @bunchesofdonald I forgot to come back 😬
