### ISSUE TITLE
Flow run result link missing from flow run page of UI when flow run result is persisted

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10470]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Persist the result of a flow to disk.

There is no link to the flow result location in the UI, although the flow result is persisted to disk.

If a task result is persisted to disk, then there is a link to the task result location in the UI.

### Reproduction

Run a script like this one. There is no link to the flow result in the UI, although the flow result is persisted to disk.

```
from prefect import flow, task
import pandas as pd


@task  # (persist_result=True)
def my_task():
    df = pd.DataFrame(dict(a=[2, 3], b=[4, 5]))
    return df


@flow(persist_result=True)
def my_flow():
    res = my_task()
    return "success"


if __name__ == "__main__":
    my_flow()
```

### Error

<img width="717" alt="Screenshot 2023-08-22 at 2 29 34 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/2ce0fc39-3983-439d-94d2-d3d9c2dcdc66">

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.11.4
API version:         0.8.4
Python version:      3.10.8
Git commit:          7d2a9103
Built:               Thu, Aug 17, 2023
3:41 PM
OS/Arch:             darwin/arm64
Profile:             storage-demo
Server type:         cloud
```

### Additional context

Same result in cloud and server. 

Perhaps this is more of a feature request than a bug, but he behavior was surprising and raised by PACC Aug 22-23 participants.

**Comment by pleek91** [comment]
@discdiver is this what you would expect to see? 

<img width="482" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/e12da37c-f5f1-41fe-9ff0-f8309a3033d8">
