### ISSUE TITLE
docs: Deployment `flow_name` incorrectly documented as optional if `entrypoint` porvided

### ISSUE THREAD

**Issue by jthetzel** [PrefectHQ/prefect#10475]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

For deployments, the documentation for  flow_name state:

> Deprecated: The name of a flow that has been registered in the .prefect[ directory](https://docs.prefect.io/2.11.4/concepts/deployments/#the-prefect-directory). Either flow_name or entrypoint is required.

( https://docs.prefect.io/2.11.4/concepts/deployments/#deployment-declaration-reference )

However, in the source code, a deployment without a flow_name always raises a ValueError:
```
        if not self.name or not self.flow_name:
            raise ValueError("Both a deployment name and flow name must be set.")
```
( https://github.com/PrefectHQ/prefect/blob/2.11.4/src/prefect/deployments/deployments.py#L686 )

### Describe the proposed change

Depending on the intended behavior, either update documentation to remove the deprecation warning for `flow_name`:
> The name of a flow that has been registered in the .prefect[ directory](https://docs.prefect.io/2.11.4/concepts/deployments/#the-prefect-directory).

Or update the deployment source code to throw an error only if `flow_name` _and_ `entrypoint` are `None`.

**Comment by serinamarie** [comment]
Thanks for opening your first issue with Prefect! As discussed in Prefect community slack, this is indeed a documentation issue.
