### ISSUE TITLE
Logs are not deleted when deleting a flow run (POSTGRES)

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect#10504]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When deleting a flow run the logs are still preserved in the database `log` table.

### Reproduction

Delete a flow run through Prefect UI 

OR

```python3
from prefect.client import get_client
import asyncio

client = get_client()
run_id = "c85e06fb-8b87-464b-9830-0464d5d37a5f" # enter flow run id here
asyncio.run(client.delete_flow_run(run_id))
```

after this select all the relevant tables (all of them are empty):
```sql
select * from flow_run where id = 'c85e06fb-8b87-464b-9830-0464d5d37a5f';
select * from flow_run_state where flow_run_id = 'c85e06fb-8b87-464b-9830-0464d5d37a5f';
select * from task_run where flow_run_id = 'c85e06fb-8b87-464b-9830-0464d5d37a5f';
select * from task_run_state where task_run_id  in (select id from task_run where flow_run_id = 'c85e06fb-8b87-464b-9830-0464d5d37a5f');
```

but the logs are still existing in `log`:
```sql
select * from log where flow_run_id = 'c85e06fb-8b87-464b-9830-0464d5d37a5f';
```

### Versions

```Text
2.11.4
```

**Comment by OptimeeringBigya** [comment]
Sub set of https://github.com/PrefectHQ/prefect/issues/10000

**Comment by WillRaphaelson** [comment]
Thanks, Closing in favor of #10000 which will cover postgres and sqlite.
