### ISSUE TITLE
Slack invitation link requires @prefect.io email address

### ISSUE THREAD

**Issue by mohamedawnallah** [PrefectHQ/prefect#10502]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The Slack channel invitation link requires a `@prefect.io` email address so we cannot join using an `@gmail.com` email address.

### Describe the proposed change

I propose replacing the slack invitation link `https://prefect-community.slack.com/` with `https://prefect.io/slack` I tried the latter and worked fine for me.

**Comment by billpalombi** [comment]
Thanks for the heads up @mohamedawnallah. Where did you find the `https://prefect-community.slack.com/` link?

**Comment by mohamedawnallah** [comment]
@billpalombi This one
![2023-08-25_16-12](https://github.com/PrefectHQ/prefect/assets/69568555/dc3bc0d4-fb98-4325-a148-147ed79ccb16)
