### ISSUE TITLE
add example of custom states in state concept doc

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10514]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

currently the ability to return a state, an further, to return a custom state is only showed in discourse:

https://discourse.prefect.io/t/how-to-return-a-state-as-well-as-data/3273

We should put this in the docs.

### Describe the proposed change

^

**Comment by discdiver** [comment]
@cicdw is planning to overhaul concept docs. Not sure how much this page might change. Might be best to put into a guide or recipe. I would vote guide.

**Comment by taylor-curran** [comment]
```python
from prefect import flow
from prefect.server.schemas.states import Completed, Failed

@flow()
def my_test():
    print('hi')

    state = Failed()

    return Failed(message="Ohh no!", name="Stale Data")

if __name__ == "__main__":
    my_test()
```
