### ISSUE TITLE
update code examples in cloud quickstart

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10513]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

[Cloud quickstart](https://docs.prefect.io/2.11.5/cloud/cloud-quickstart/) shows older screenshot photos.

### Describe the proposed change

[Cloud quickstart](https://docs.prefect.io/2.11.5/cloud/cloud-quickstart/) should use newer examples like what is found in the [welcome to prefect page](https://docs.prefect.io/2.11.5/#step-3-create-a-flow).

**Comment by discdiver** [comment]
Great call!

**Comment by discdiver** [comment]
Probably want to wait for UI refresh for the screen shots.

**Comment by discdiver** [comment]
Closing as there is now just one quickstart.
