### ISSUE TITLE
error in docker-git recipe

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#10518]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

docker-git recipe indentation is off and cli experience is breaking

### Reproduction

```python3
prefect init --recipe docker-git -f image_name=image -f tag=latest -f repository=git_repo_url -f branch=master
prefect deploy flow_path:flow_function_name -n deploy_name -p pool
```

### Versions

```Text
(orion) ➜  prefect git:(fix-docker-git-recipe) ✗ prefect version
Version:             2.11.5
API version:         0.8.4
Python version:      3.11.4
Git commit:          a597971f
Built:               Thu, Aug 24, 2023 2:14 PM
OS/Arch:             darwin/x86_64
Profile:             staging
Server type:         cloud
```

**Comment by desertaxle** [comment]
Resolved in https://github.com/PrefectHQ/prefect/pull/10519
