### ISSUE TITLE
Allow to save & use "views" in the UI of certain dashboards (e.g. flow runs) of previously predefined filters

### ISSUE THREAD

**Issue by klayhb** [PrefectHQ/prefect#10540]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

A very common use-case is that we want to see all flow-runs that are either running or experiencing (currently or previously) some kind of trouble. 
For that purpose - we don't need to see scheduled or even completed runs.
This filtering is so common that we have to repeat it almost whenever we go into the UI, instead of it being our default for example.

### Describe the proposed behavior

It would be great if one could save a "view" of chosen filters - which could then either be loaded when desired - AND - set as the default if needed.

### Example Use

As described in my problem

**Comment by WillRaphaelson** [comment]
Thanks for the issue @klayhb, with our new search features coming out this week, we'll have natural surface area to build out saved searches.

**Comment by klayhb** [comment]
@WillRaphaelson  thanks, a global search is great but this doesn't exactly help with the case where we want a saved VIEW rather than a saved SEARCH (since we're not necessarily searching for anything specific - maybe we just wanna see all latest runs that aren't scheduled - but are running or completed/failed/crashed etc.)

**Comment by WillRaphaelson** [comment]
Yeah thanks @klayhb - i more mean that I think the search backend will provide some useful internals here. I'll put this issue on our backlog.

**Comment by zhen0** [comment]
I'm not exactly sure if it works for your use case @klayhb but you can save filters on the flow runs page 

https://github.com/PrefectHQ/prefect/assets/40272060/168e0b85-9225-416b-8728-4174b2fac0ac

**Comment by klayhb** [comment]
Was not aware of this, thanks - but, seems like it's just missing the
ability to set one as the new default?

**Comment by brandonreid** [comment]
@klayhb this is solid! I'm working on some design thinking for the flow runs page and looking into those filters a bit. I could see adding a new pattern where the settings button and selection input are combined visually, but we can worry about introducing that at a later implementation.

**Comment by collincchoy** [comment]
The ability to set your own default view for the Flow Runs dashboard was added in [2.13.3](https://github.com/PrefectHQ/prefect/releases/tag/2.13.3). 

As mentioned [previously](https://github.com/PrefectHQ/prefect/issues/10540#issuecomment-1710993283), you can create saved custom views which are named filters. From there, starting in >=2.13.3, you can set a saved filter view as your default. Be aware that this default configuration is saved _locally_.
