### ISSUE TITLE
Tuples in the UI have incorrect validation

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#10552]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If I create a flow with a tuple parameter then the input seems to check the length of the tuple rather than the number of entried. 

### Reproduction

```python3
from typing import Tuple

from prefect import flow


@flow(log_prints=True)
def tuple_flow(tuple:Tuple[str, int, float] = ("a", 1, 1.0)):
    print(tuple)
    return tuple

if __name__ == "__main__":
    tuple_flow.serve(parameters=dict(tuple=("b", 2, 2.0)))
```

### Error

```python3
See screenshot below -
```

### Versions

```Text
Latest/Cloud
```

### Additional context

<img width="906" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/c2572105-ae12-41cf-b434-6371bd601aa1">

I can workaround this by using the json tab

<img width="550" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/f9fc4a42-5acd-476a-aa80-3d9cd60b2813">

**Comment by pleek91** [comment]
This is still an issue with the enhanced deployment parameters ui because the schema being generated for this is incorrectly using `items` and not `prefixItems`. We're investigating if we can account for that when we do validation.
