### ISSUE TITLE
Error "Work pools starting with 'Prefect' are reserved for internal use." not floated to UI

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#10557]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I tried creating a workpool named "prefect-p" in the UI which kept saying "Failed to create worker pool" (see image). I then tried in the CLI where I got:

``` Response: {'detail': "Work pools starting with 'Prefect' are reserved for internal use."}```.

I think you want to float that error to the UI so the user can figure out why the work pool can not be created. Alternatively give a validation error in the UI.

![image](https://github.com/PrefectHQ/prefect/assets/44194839/694b70f0-d402-4298-ab7b-b6db8e37a109)

### Reproduction

1. Try creating a work pool in the UI callled `prefect-p`
2. Try in the CLI with `prefect work-pool create "prefect-d" --type kubernetes` 

### Error

See bug summary

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.11.5
API version:         0.8.4
Python version:      3.8.8
Git commit:          a597971f
Built:               Thu, Aug 24, 2023 2:14 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by zhen0** [comment]
Closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1712
