### ISSUE TITLE
Support trigger definitions via CLI with `prefect deploy`

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#10551]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, users must edit yaml to add trigger policies to deployments

### Describe the proposed behavior

Users should be able to pass in a reference to a trigger policy file or raw json of a trigger. The trigger should be validated on deploy.

### Example Use

prefect deploy --trigger trigger.yaml
prefect deploy --trigger '{after:...}'

**Comment by toro-berlin** [comment]
Hey @serinamarie,

I just tried out what this could look like. Please find the draft PR here: https://github.com/PrefectHQ/prefect/pull/10634/files
Happy for any feedback!

I have only tested it with the unit tests yet. I will make tests with the actual command tomorrow.

**Comment by serinamarie** [comment]
Hi @toro-berlin, thanks so much, we'll take a look! 

I have made a separate issue for the older style of deployments you're mentioning and any further discussion can be had on that issue :)
[Support trigger definitions via CLI with `prefect deployment build`](https://github.com/PrefectHQ/prefect/issues/10635)
