### ISSUE TITLE
`anyio 4.0.0` introduces breaking changes for prefect

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#10567]
changelog for `anyio` [here](https://github.com/agronholm/anyio/blob/master/docs/versionhistory.rst?plain=1#L10) detailing backwards incompatible changes to cancellation semantics

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`anyio==4.0.0` seems to include a breaking change that includes moving `start_blocking_portal`

### Reproduction

```python3
pip install -U prefect anyio
```

### Error

```python3
Successfully installed anyio-4.0.0 prefect-2.11.5
❯ prefect
Traceback (most recent call last):
  File "/Users/nate/micromamba/envs/bleeding-prefect/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/Users/nate/micromamba/envs/bleeding-prefect/lib/python3.11/site-packages/prefect/__init__.py", line 45, in <module>
    from prefect.engine import pause_flow_run, resume_flow_run
  File "/Users/nate/micromamba/envs/bleeding-prefect/lib/python3.11/site-packages/prefect/engine.py", line 98, in <module>
    from anyio import start_blocking_portal
ImportError: cannot import name 'start_blocking_portal' from 'anyio' (/Users/nate/micromamba/envs/bleeding-prefect/lib/python3.11/site-packages/anyio/__init__.py)
```

### Versions

```Text
# prefect version does not work with the problematic env due to the ImportError
❯ pip list | grep 'prefect\|anyio'
anyio                                        4.0.0
prefect                                      2.11.5
```

**Comment by cicdw** [comment]
The earlier we can get this in the better - @zzstoatzz can you figure out where that function moved to?

**Comment by zzstoatzz** [comment]
> The earlier we can get this in the better - @zzstoatzz can you figure out where that function moved to?

it moved to
```python
from anyio.from_thread import start_blocking_portal
```

but it seems the real issue might be the backwards imcompatable changes to cancellation [here](https://github.com/agronholm/anyio/blob/master/docs/versionhistory.rst?plain=1#L10)

**Comment by xarasco** [comment]
We're getting this same failure when running the below command in a CI context.  We haven't experienced this yet in our local machines and I will ask folks to avoid upgrading anything for now.  But we would like to be able to commit new code. :)
`prefect config set ...`

**Comment by abhishekm96** [comment]
Downgrading anyio to 3.7.1 temporarily solves the issue.

**Comment by ori-scala** [comment]
A question to the Prefect engineering team - Why aren't you pinning the requirements, or at least using `<` to avoid major version upgrades that breaks the product?

**Comment by Cediddi** [comment]
This is breaking `PrefectHQ/actions-prefect-auth@v1` and we can't provide a requirements.txt to fix `anyio==3.7.1` to that GitHub action, thus all GitHub actions are down.

**Comment by cicdw** [comment]
The `pydantic` v2 issue is a good second data point; I do see a few other references to folks wanting major version upper bounds in our issues, so I'll take this to the team and see where we land.

**Comment by peterbygrave** [comment]
> The `pydantic` v2 issue is a good second data point; I do see a few other references to folks wanting major version upper bounds in our issues, so I'll take this to the team and see where we land.

If you decide to major version upper bounds, please can you upstream this to conda-forge too: https://github.com/conda-forge/prefect-feedstock/blob/main/recipe/meta.yaml

**Comment by JustinGuese** [comment]
appeared again today

**Comment by cicdw** [comment]
@JustinGuese can you say more? Prefect [requires `anyio > 4.4.0` now](https://github.com/PrefectHQ/prefect/blob/main/requirements-client.txt#L1).

**Comment by JustinGuese** [comment]
python 3.12, prefect 3.1.1

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/__init__.py", line 37, in <module>
    from prefect.runner import Runner, serve
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/runner/__init__.py", line 1, in <module>
    from .runner import Runner, serve
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/runner/runner.py", line 69, in <module>
    from prefect.engine import propose_state
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/engine.py", line 98, in <module>
    from anyio import start_blocking_portal
ImportError: cannot import name 'start_blocking_portal' from 'anyio' (/opt/homebrew/lib/python3.11/site-packages/anyio/__init__.py)
```

**Comment by zzstoatzz** [comment]
hi @JustinGuese - which version of `anyio` do you have installed here?
