### ISSUE TITLE
Task runs with custom state name missing colours and inclusion in task run state filter drop-down

### ISSUE THREAD

**Issue by rebecca-liveeo** [PrefectHQ/prefect#10577]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When using a state type with a custom state name, the state is not displayed as expected in the flow run UI:
- It shows up in a black colour, instead of the colour of the state type.
- The state name is not available in the state drop down filter under "Task Runs".

### Reproduction

I followed the suggestion we were given in this issue comment: https://github.com/PrefectHQ/prefect/issues/10291#issuecomment-1682350743 

When appropriate, `State(type=StateType.CRASHED, name="Warning")` is returned from a task to give it the "Crashed" state type and "Warning" state name. 

The relevant task runs are then not displayed as expected in the flow run summary in Prefect Cloud, as described in the bug summary.

I have also tried with type "Completed" and a custom state name, getting the same results as with "Crashed" and a custom state name.

### Error

![prefect_ui_warning_state](https://github.com/PrefectHQ/prefect/assets/143079214/6578d46d-4ae6-4176-bc70-6f197d248bb6)
- In diagram the task is not orange
- In the drop down "warning" is not listed
- In the list of tasks "warning" is also not orange (though this is less important)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by billpalombi** [comment]
Thanks for letting us know @rebecca-liveeo! Custom state names are definitely something that we'd like to support better. We'll let you know if we make progress in this issue.

**Comment by zhen0** [comment]
This should be resolved by https://github.com/PrefectHQ/prefect-ui-library/pull/2210
