### ISSUE TITLE
Create a guide for priority queues.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10599]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Currently the available options for relationships between deployments work pools, queues, and workers is complex and not spelled out thoroughly. 

### Describe the proposed change

I can create a guide for this.

**Comment by discdiver** [comment]
Guide for work queues would be good.

**Comment by discdiver** [comment]
Work pools and workers are discussed a fair number of places, but work queues aren't much.

**Comment by discdiver** [comment]
Closing as work queues and work queue priority discussion has been expanded in [concepts->work-pools.md](https://docs.prefect.io/latest/concepts/work-pools/#work-queues) over the past few months. 

Feel free to reopen with any specific requests for for further documentation.
