### ISSUE TITLE
Include Prefect logo in top left corner of OSS UI

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#10604]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There is no Prefect logo in the top left corner of the UI

### Describe the proposed behavior

Add the logo. Make it link to the dashboard.

**Comment by miikkuu** [comment]
are you talking  about the website ? 
https://www.prefect.io/opensource
