### ISSUE TITLE
Add `client.rest.ApiException` handling to k8s tasks

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1060]
All of the Kubernetes tasks have the potential to raise a `client.rest.ApiException` on a client call and it should be documented, logged, and raised.

**Comment by zangell44** [comment]
@joshmeek I'll work on this. Do you want to use `Task.logger` for logging these exceptions?

**Comment by cicdw** [comment]
@zangell44 yea, I think you should use the task logger - thanks!!

**Comment by zangell44** [comment]
The one that got away 😢
