### ISSUE TITLE
Enhancing User Experience with Custom YAML Blocks in Prefect

### ISSUE THREAD

**Issue by Sohambutala** [PrefectHQ/prefect#10612]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In my project, I rely on multiple YAML configuration files that determine the stages to be executed in the pipeline. Currently, Prefect lacks the capability to create YAML blocks directly within its framework. As a result, I'm storing these configuration files either locally or remotely (e.g., on S3 or GitHub).

The challenge arises when these YAML files require occasional changes. While these changes aren't ultra-frequent, they are more common than the occurrence of a blue moon. Consequently, making modifications to a file and then executing the flow using Prefect introduces some friction into the process.

### Describe the proposed behavior

I propose implementing a feature to create YAML blocks within Prefect, which would greatly enhance the user experience, especially in scenarios like the one I've described. While it might not be an extensive undertaking, it could significantly streamline the workflow and make Prefect an even more versatile tool for handling configuration-driven pipelines.

I'm familiar with JSON blocks, and they can certainly be used in such scenarios. However, I believe that introducing YAML blocks would offer more flexibility and provide a superior approach for configurations due to its human-readable format.

### Example Use

The usage will resemble any typical block-loading logic, where the user-defined function loads the block as needed.

**Comment by desertaxle** [comment]
Thanks for the issue @Sohambutala! We could achieve the experience you're looking for by adding a YAML editor view in addition to our JSON editor view when creating and updating blocks in the Prefect UI. Would that satisfy your needs?

**Comment by Sohambutala** [comment]
Thank you for considering this improvement, @desertaxle! 
Adding a YAML editor view alongside the JSON editor view in the Prefect UI would definitely meet our needs. This flexibility in choosing between YAML and JSON for creating and updating blocks will definitely enhance the user experience. To clarify, on the back-end, the block will still produce a JSON object even if we use a YAML editor in the UI, right?

**Comment by desertaxle** [comment]
Yes, what I'm proposing would still produce a JSON block, which would be exposed in your Python code as a dictionary. The YAML editor would be a convenience for users that find YAML more ergonomic than JSON. If you are looking for additional YAML features that aren't available with JSON, we'd need to take a different approach.

**Comment by Sohambutala** [comment]
This solution is an excellent fit for my specific use-case. While I find it highly effective, it's hard to anticipate whether future scenarios might necessitate the use of YAML blocks instead of JSON. Nonetheless, I firmly advocate for the inclusion of YAML blocks in the near future.
