### ISSUE TITLE
Prefect Deployment Bug: Union Type with Dict Input Detected as Object on Prefect UI

### ISSUE THREAD

**Issue by Sohambutala** [PrefectHQ/prefect#10611]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When deploying flows on Prefect, we encountered a bug related to the detection of input types. Specifically, when using a `Union` from the `typing` library to allow for multiple input types, and one of those types is a dictionary (`dict`), the Prefect UI incorrectly detects it as an `object` type.

This issue impacts the accuracy of type detection during deployment. Interestingly, when using `Optional` for the dict type, the Prefect UI correctly identifies it as a `dict` type.

The issue can be observed on both prefect local / ephemeral mode and prefect cloud. We would appreciate it if this bug could be investigated and addressed, as it affects the usability and reliability of Prefect deployments in scenarios where Union types are used to specify input types.

### Reproduction

1. Create a new Python environment.
2. Install Prefect using pip: `pip install prefect`.
3. Log in to Prefect Cloud using your Prefect API key: `prefect cloud login -k <PREFECT_KEY>` 
Note : Skip the step and use `prefect profiles create prefect-local`  for local or ephemeral mode.
4. Create a simple Prefect flow with the following code:

```python
from typing import Any, Dict, Optional, Union
from prefect import flow, task

@task
def demo_task():
    print("Demo Task")

@flow
def demo_flow_union(input_dict: Union[Dict[str, Any], str]):
    print("Demo Flow")
    demo_task()

@flow
def demo_flow_optional(input_dict: Optional[Dict[str, Any]]):
    print("Demo Flow")
    demo_task()
```

5. Deploy both flows to your Prefect account using the `prefect deploy` command.
6. Navigate to the Prefect UI, go to the "Deployments" section, and select the `demo_flow_union` deployment.
7. Click on "Quick Run."
8. Observe that the Prefect UI indicates that either an "object" or "str" is expected as input, which is unexpected behavior.

### Error

![image](https://github.com/PrefectHQ/prefect/assets/38330817/0a8dcb1d-42e9-4ed7-ae9b-6f518efc695f)

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.12.1
API version:         0.8.4
Python version:      3.9.6
Git commit:          f5eed67c
Built:               Fri, Sep 1, 2023 4:01 PM
OS/Arch:             darwin/x86_64
Profile:             echoflow-local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.5
```

**Comment by WillRaphaelson** [comment]
Thanks @Sohambutala - we're refactoring and improving how we handle parameter schemas in the coming weeks and we'll take this up then.

**Comment by pleek91** [comment]
@Sohambutala this appears to be rendering correctly as `dict` or `str` in the new enhanced deployment parameters ui which is available in cloud and will soon be available in open source

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/e730805a-b914-40fc-b0b3-5d5310e098f6)

**Comment by pleek91** [comment]
I'm going to close this issue now that enhanced deployment parameters are available in oss and cloud. But please let us know if you're still having issues with this. Thank you for reporting!
