### ISSUE TITLE
Prefect UI flow run digram with large number of tasks is unresponsive

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#10610]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The current implementation of the Prefect UI flow run diagrams is causing performance issues when dealing with a large amount of data. As the diagram loads, it slows down the browser and may even cause it to become unresponsive or freeze. 

### Describe the proposed behavior

Requiring the user to click a button before displaying the flow run diagram if it has maybe over N number of tasks.

**Comment by pleek91** [comment]
@BitTheByte are you still having issues with this? I believe we had a regression go out on the day before with the redesign'd UI which was fixed. So the flow run timeline should be working for any flows it was working for previously.

**Comment by BitTheByte** [comment]
Yes, this general issue unrelated to the mentioned issue

**Comment by brandonreid** [comment]
Thanks @BitTheByte 

I actually like the idea of asking the user when over N number of nodes. I could see that being nice if you are revisiting a large run for logs or other details, don't need that graph right now, etc. Especially if it's causing the browser to lock up for you.

I'll take this on.
