### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by psmoros** [PrefectHQ/prefect#10657]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@jbonnett) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jawnsy** [comment]
Hey @psmoros - thanks so much for creating this issue! This is a great suggestion and I'll look into adding a README.

In the meantime, we have an [active bug bounty program](https://www.prefect.io/bug-bounty), so you can send reports there.

**Comment by psmoros** [comment]
Just filed the report, apologies for the delay we were evaluating it internally... Let me know if you need anything :))

**Comment by psmoros** [comment]
Hey @jawnsy! Have you received our report from huntr.com?
