### ISSUE TITLE
Email notifications example form input needs adjusted

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10668]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Here's the default example in a Prefect server UI.
<img width="1185" alt="Screenshot 2023-09-07 at 1 51 05 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/270dcce8-c9f8-484f-aeab-11dfebdabb92">

But this doesn't work. 
<img width="1187" alt="Screenshot 2023-09-07 at 1 51 24 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/d4e38e4f-9aa3-4c04-8615-3c5cf2144e50">

Quotes are required around the address.

### Reproduction

```python3
see above
```

### Versions

```Text
Version:             2.12.1
API version:         0.8.4
Python version:      3.10.8
Git commit:          f5eed67c
Built:               Fri, Sep 1, 2023 
4:01 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

**Comment by WillRaphaelson** [comment]
Note that this does not need a corresponding cloud PR, the block is different and the example is correct.
