### ISSUE TITLE
RRuleSchedule does not generate correct number of Flow Run as expected

### ISSUE THREAD

**Issue by hoangquochung1110** [PrefectHQ/prefect#10672]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

**Prefect Cloud generates only at most 3 flow runs if I set schedule with RRuleSchedule with `count` parameter >= 3**

I'd like to apply a Deployment with a schedule configuration:
> DTSTART:20230908T150000
> RRULE:FREQ=HOURLY;INTERVAL=2;**`COUNT=3`**

Result: Prefect Cloud spawns at most 3 flow run if I set `n` >= 3

### Reproduction

Step to reproduce:

1. Define a flow and a deployment with given schedule

```python3


# foo.py

from prefect import flow
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import RRuleSchedule


@flow
def foo():
    assert 1 == 1


if __name__ == "__main__":

    rrule_str = """
        DTSTART:20230908T150000
        RRULE:FREQ=HOURLY;INTERVAL=1;COUNT=3
    """
    
    Deployment.build_from_flow(
        flow=foo,
        name="foo-deployment",
        apply=True,
        schedule=RRuleSchedule(rrule=rrule_str),
    )

```

2. Apply Deployment to Prefect Cloud by executing `foo` module
3. Investigate Flow Run on Prefect Cloud: we have 3 flow run (as we expected)

<img width="1488" alt="rrule_count_3" src="https://github.com/PrefectHQ/prefect/assets/40592382/f740da2b-4a04-4467-a5bc-40e89f793b40">

5. Update deployment's schedule configuration
> DTSTART:20230908T150000
> RRULE:FREQ=HOURLY;INTERVAL=2;**`COUNT=4`**
6. Investigate Flow Run on Prefect Cloud: still 3 flow run (should have 4 instead)
<img width="1378" alt="rrule_4" src="https://github.com/PrefectHQ/prefect/assets/40592382/bc134728-dfa5-4b48-a0a9-f646fae1a7ac">

### Error

Prefect Cloud does not generate correct number of Flow Run when compared with RRule Schedule configuration

### More evidence

<img width="1210" alt="rrule_2" src="https://github.com/PrefectHQ/prefect/assets/40592382/8a2b5988-95ec-49b7-bf28-be63b811c745">
<img width="1389" alt="rrule_6" src="https://github.com/PrefectHQ/prefect/assets/40592382/a71f1e04-0f92-45a1-8830-de4f9c1c68f8">

### Versions

```Text
2.12.1
```

**Comment by serinamarie** [comment]
Hi @hoangquochung1110, thanks for contributing your first issue to Prefect! We're glad to have you in our community :) Thank you for providing an MRE and great screenshots (hence the `great writeup` label). I haven't had a chance to reproduce the issue, but I'm guessing that when we update the deployment, the new schedule isn't being registered as different than what it was previously for that specific schedule. We will look into this :)

**Comment by serinamarie** [comment]
Hi @hoangquochung1110, I was able to reproduce this issue! 

Then I wanted to rule out other sections of the RRule string so I tested updates to `DTSTART`, `FREQ` and `INTERVAL` and had no issues. I'll look into a fix. See further details below.

Updates to `DTSTART` portion of the RRule works properly:
<img width="1088" alt="Screenshot 2023-09-11 at 11 35 37 AM" src="https://github.com/PrefectHQ/prefect/assets/42048900/27bb8937-8b2b-4d9a-81e8-bd1f9f1d5184">

Updates to `FREQ` also works as expected:
<img width="1066" alt="Screenshot 2023-09-11 at 11 34 55 AM" src="https://github.com/PrefectHQ/prefect/assets/42048900/ee4eb967-1730-44b6-b149-dbc0fd37bcdf">

Finally, `INTERVAL` updates work:
<img width="1071" alt="Screenshot 2023-09-11 at 11 39 19 AM" src="https://github.com/PrefectHQ/prefect/assets/42048900/d7c8b575-180d-4484-b293-9b14a9b264a9">

**Comment by serinamarie** [comment]
Hi @hoangquochung1110, it seems that we aren't actually supporting the `COUNT` param at all right now so I'm adding validation enforce this on the Deployment object.

**Comment by hoangquochung1110** [comment]
Hi @serinamarie thanks for your PR with detailed documentation.
