### ISSUE TITLE
Prefect flow schedule trigger's twice

### ISSUE THREAD

**Issue by MdRafiyudeen946** [PrefectHQ/prefect#10677]
### First check

- [x] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I found the bug in the prefect 2.0, In Prefect we scheduled the prefect scripts flows to trigger every hour, that flow triggered twice on 26’th August 2023 2:00 AM IST, scheduled the prefect script flow in Prefect UI Cron. It's affected my production. Checked for other flows which had a same issue and found a another flow triggered twice on 25’th August 2023 10:00 PM IST. Currently I using Prefect version is 2.8.3 I did not upgraded the version because everything is working perfectly in 2.8.3 version but 1 week before I occurs the flows trigger's twice.

I attached example code below, this code works fine on my side on the particular time it's flow triggered twice no issue in the code.

Raised the complaint in the prefect community regarding the scheduled flow issue. 

https://prefect-community.slack.com/archives/CL09KU1K7/p1694104193372349

### Reproduction

```python3
import os
import sys
import prefect
from prefect.context import get_run_context
from prefect import flow, task, get_run_logger
from prefect.futures import PrefectFuture
from prefect_shell import ShellOperation

@task
def test():
    os.chdir('/home/ubuntu')
    ShellOperation(commands=["/venv/prefect/bin/python test.py"]).run()

@flow(name=project_flow_name,flow_run_name="test_flow",log_prints=True)
def test_flow():
    a = test.submit()
```

### Error

```python3
No error
```

### Versions

```Text
Prefect version is 2.8.3
```

**Comment by serinamarie** [comment]
Hi @MdRafiyudeen946, thanks for submitting your first issue to our community!

On Aug 25, 2023, we had an incident related to cron scheduling that resulted in duplicate flow runs being scheduled. I believe this is related to your issue and we expect that this was a one off that should not reoccur. If it does occur again, please feel free to reopen this issue with further details, such as the output of your `prefect version`, which would look something like:

```bash
❯ prefect version
Version:             2.13.0
API version:         0.8.4
Python version:      3.10.4
Git commit:          66577cc6
Built:               Thu, Sep 7, 2023 3:52 PM
OS/Arch:             darwin/arm64
Profile:             local_sqlite
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.5
```
