### ISSUE TITLE
Disambiguate language in `prefect cloud login` 

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10689]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

This applies when you have multiple profiles, one of which has previously authenticated with Prefect Cloud.

```
t $ prefect cloud login
It looks like you're already authenticated with another profile.
? Would you like to reauthenticate with this profile? [y/N]: y
```

I find `Would you like to reauthenticate with this profile?` confusing because it's not clear what `this` refers to.

I want to authenticate with the current profile, for the first time. I read the above message as asking "do I want to reauthenticate with another profile that I was previously already authenticated with."

### Describe the proposed behavior

To disambiguate, I propose changing the language to the following:

"Would you like to authenticate with the currently active profile?"

### Additional context

I can make the PR to change the langauge if this language is acceptable.

**Comment by serinamarie** [comment]
> "Would you like to authenticate with the currently active profile?"

What about "It looks like you're already authenticated with another profile. Would you like to authenticate to it?" We could retrieve the name but it could actually be a list of profiles. The currently active profile would differ from the one the user is trying to login with in this case.

**Comment by discdiver** [comment]
I'm still a little confused @serinamarie 

I created a new profile and want to use it to authenticate.

I want to use the current profile to authenticate to an org and workspace. 

```
prefect cloud login
It looks like you're already authenticated with another 
profile.
? Would you like to reauthenticate with this profile? [y/N]: n
? Would you like to switch to an authenticated profile? [Y/n]: n
(base) jeffhale demos/code-for-docs $
```


If the question were:

"It looks like you're already authenticated with another profile. Would you like to authenticate to it?"

My answer would still be no and then I still wouldn't get authenticated.

I think the question should be something like "Do you want to authenticate with the currently active profile? 

Apologies if I'm not thining about this clearly.
