### ISSUE TITLE
docs unclear on "file" artifacts

### ISSUE THREAD

**Issue by odoublewen** [PrefectHQ/prefect#10699]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The [docs](https://docs.prefect.io/latest/concepts/artifacts/) and the [blog post](https://discourse.prefect.io/t/prefect-2-9-0-is-here-with-artifacts-configurable-result-storage-keys-and-runtime-enhancements/2644) about artifacts make it sound like any old file can be considered an "artifact."

docs:
> Artifacts are persisted outputs such as tables, files, or links...

blog post:
> Most workflows produce or update an artifact of some kind, whether it’s a table, a file, or a model. With Prefect Artifacts, you can track changes to these outputs...

But further reading makes it pretty clear that only "links, markdown, or tables" are allowed as artifacts.

### Describe the proposed change

If generic file artifacts are not supported, then the wording might be changed from:
> Artifacts are persisted outputs such as tables, files, or links.

to something like:
> Prefect currently supports three kinds of Artifacts: tables, markdown, and links.

**Comment by serinamarie** [comment]
@odoublewen, thanks for the issue. Clarifying the language makes sense to me!

**Comment by odoublewen** [comment]
Thanks!  I'm happy to PR this simple one-sentence change, if that helps.

Kudos, by the way, this project seems super neat and useful.

**Comment by serinamarie** [comment]
Thanks, that would be great :)
