### ISSUE TITLE
Retry Cloning Of Remote Repository Upon Failure

### ISSUE THREAD

**Issue by KalebKing** [PrefectHQ/prefect#10725]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There are times when a scheduled flow run fails to clone from GitHub (or other repository) and returns the following error:
```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "C:\path-to-virtual-env\lib\site-packages\prefect\engine.py", line 294, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "C:\path-to-virtual-env\lib\site-packages\prefect\client\utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\path-to-virtual-env\lib\site-packages\prefect\deployments.py", line 197, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "C:\path-to-virtual-env\lib\site-packages\prefect\filesystems.py", line 966, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 Cloning into 'C:\path-to-temporary-folder\tmpnr_8wc0iprefect'...
fatal: unable to access 'https://github.com/org-name/repo-name.git/': Recv failure: Connection was reset
```
The flow run goes into a `Failed` state and has to be manually retried.

### Describe the proposed behavior

It would be helpful to have the ability to specify the number of retries and delay between retries. Similar to how we can specify `retries` and `retry_delay_seconds` on flows and tasks.

**Comment by billpalombi** [comment]
@KalebKing this is a very cool idea. Thinking of the process of preparing to run a flow is a flow itself is pretty "meta." There's definitely a problem to be solved here. There are some non trivial design decision that we'll have to make, but I've added this to our internal backlog for future consideration. Thank you!

**Comment by serinamarie** [comment]
I think a targeted solution would be to retry in certain cases (such as reset connection) here before raising the error:

https://github.com/PrefectHQ/prefect/blob/ced90309a776eaf8610be8c6a4dace4b7af33220/src/prefect/filesystems.py#L966-L975

**Comment by billpalombi** [comment]
That sounds like low hanging fruit @serinamarie. Feel free to go for it!

**Comment by serinamarie** [comment]
Hi @KalebKing, after considering this a bit more, I am unsure that retrying will help in these cases. You say:

> There are times when a scheduled flow run fails to clone from GitHub (or other repository) 

when are these times? Using BitBucket? or just GitHub?

From some quick research on this issue, there was recommendation on [using SSH instead of HTTPS](https://community.atlassian.com/t5/Bitbucket-questions/BitBucket-Disconnects-During-Long-Upload-Downloads/qaq-p/1170485), while others recommended [adjusting the git config](https://stackoverflow.com/questions/62590492/recv-failure-connection-was-reset-git).

I'm not condoning either of these options per say, just that it does not seem the case here that retrying will help at all, based on my findings for this error: `Recv failure: Connection was reset`. If you believe differently, please feel free to provide more details!

**Comment by KalebKing** [comment]
Hey @serinamarie. I guess I can only speak to the issue as it relates to GitHub. I made a post on [Discourse](https://discourse.prefect.io/t/flow-could-not-be-retrieved-from-deployment/3296?u=kalebking) a while ago with a little more detail.

Currently, I'm using an automation to alert me when the failure happens. Then I go into the UI, click `Retry`, and it usually completes successfully. Sometimes I need to do multiple retries, but it eventually completes successfully.

**Comment by serinamarie** [comment]
Ah, thanks, that Discourse post helps a lot! Unfortunately, our Discourse isn't constantly monitored anymore. 

Is there a reason you would be opposed to using that automation to, instead of alerting you to failure (or in addition to), also [triggering a run of a deployment](https://docs.prefect.io/latest/concepts/automations/?h=automa#actions), rather than clicking "retry"? That way you wouldn't need to take manual action, although in this case it would be a different flow run, rather than the same one.

**Comment by KalebKing** [comment]
The main issue for me is the original flow run reporting as failed with no link between that flow run and the new one. Seeing a failed flow run tells me that something is wrong and needs to be fixed. That's not exactly true in this case because it's simply failing to reach GitHub.

**Comment by serinamarie** [comment]
I'm not really advising it, but depending on how important it is to you, this will allow you to retry blindly upon failure. And maybe you could modify it to suit your needs.
```python

from prefect import flow
from prefect import get_client

async def run_retry(flow, flow_run, state):
   """A state change hook to propose an `AwaitingRetry` state for a flow run"""
    client = get_client()
    await client.set_flow_run_state(
        flow_run_id=flow_run.id,
        state=states.AwaitingRetry(),
    )

@flow(on_failure=[run_retry])
def my_flow():
    """This flow will always fail, triggering the `on_failure` flow run state change hook"""
    raise ValueError("This is a failure")
```

**Comment by KalebKing** [comment]
Thanks for providing the code! There's probably a more elegant way to do this, but I modified it to retry `N` times with a delay between each retry. I couldn't figure out how to get the flow run count using the `prefect` module, so I used `re` and `subprocess` modules. Here's what I came up with:

```
import asyncio
from prefect import flow, states, get_client
import re
import subprocess

async def run_retry(flow, flow_run, state):
    """A state change hook to propose an `AwaitingRetry` state for a flow run"""
    # Get run count from flow run
    run_count = subprocess.run(['prefect', 'flow-run', 'inspect', str(flow_run.id)], stdout = subprocess.PIPE)
    run_count = run_count.stdout.decode('utf-8')
    run_count = re.search(pattern = r'run_count=(\d+),', string = run_count)
    run_count = int(run_count.group(1)) if run_count else 0
    # Retry flow run if run count is less than 3
    if run_count in range(1, 3):
        await asyncio.sleep(5)  # Wait for 5 seconds
        client = get_client()
        await client.set_flow_run_state(
            flow_run_id=flow_run.id,
            state=states.AwaitingRetry()
        )

@flow(on_failure=[run_retry])
def my_flow():
    """This flow will always fail, triggering the `on_failure` flow run state change hook"""
    raise ValueError("This is a failure")

if __name__ == "__main__":
    my_flow.serve(name="retry-test")
```
