### ISSUE TITLE
Question: worker/work pools deployment 

### ISSUE THREAD

**Issue by hamedsa-78** [PrefectHQ/prefect#10737]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

hello everyone
![1](https://github.com/PrefectHQ/prefect/assets/48446084/c0a43d35-dd72-4685-b65a-bd3ad52078dc)

Based on the text and the arrow depicted in the provided picture, it appears that communication between the two servers initiates from the execution environment (workers) and goes towards the workflow (Prefect API). This raises the question of why the communication doesn’t start in the reverse direction, where it might be more intuitive for the Prefect API server to initiate communication and send requests to the resources.
One might naturally assume that the Prefect API server should be the one to begin communication and request resources.
thanks

### Describe the proposed change

I think it is better to clarify this misunderstanding in the document

**Comment by serinamarie** [comment]
Hi @hamedsa-78, thanks for opening your first issue in Prefect! We're glad to have you in our community. 

> I think it is better to clarify this misunderstanding in the document

I'm not quite certain what the misunderstanding is, but would it be more clear in the image if we replace
`polls` and `creates` with something like `polls for scheduled flows runs` and `submits flow runs for execution`?

> This raises the question of why the communication doesn’t start in the reverse direction, where it might be more intuitive for the Prefect API server to initiate communication and send requests to the resources.

I believe what you are describing is a push work pool, which pushes work to your infrastructure. Please see documentation here :) https://docs.prefect.io/latest/guides/deployment/push-work-pools/

**Comment by hamedsa-78** [comment]
> I'm not quite certain what the misunderstanding is, but would it be more clear in the image if we replace `polls` and `creates` with something like `polls for scheduled flows runs` and `submits flow runs for execution`?
>
Actually, I have some broader recommendations to offer. Firstly, I want to express my gratitude for the well-structured documentation. It's truly impressive in terms of its clarity and quality. Nevertheless, there's an opportunity for improvement by integrating more technical insights into the overall process. For example, enhancing the documentation by providing details about the communication protocols used with the execution environment or outlining the protocol governing how workers handle requests received from the Prefect API would significantly enhance its comprehensiveness.

**Comment by serinamarie** [comment]
Hi @hamedsa-78, do you mind writing up a separate issue for this with a good amount of information about the level of detail you'd like? That can include pointing to other resources/documentation :) I will close this one for now and we look forward to your [documentation request](https://github.com/PrefectHQ/prefect/issues/new?assignees=&labels=docs%2Cneeds%3Atriage&projects=&template=4_docs_change.yaml)!
