### ISSUE TITLE
Agent listens to all work pool types

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#10743]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When you start an agent listening to only a queue (e.g. `prefect agent start -q default`) it polls for flow runs across all work pools of all types (as opposed to only the `prefect-agent` type). This means it may attempt to execute deployments intended for workers which can cause confusing errors for users. For example, a deployment intended for a kubernetes worker that stores code in a Docker image will fail when picked up by an agent because the agent will assume it's a process infrastructure and won't be able to find the flow code.

### Describe the proposed behavior

In future versions, agents should only query work queues in `prefect-agent` typed work pools unless a different work pool is explicitly specified. This should prevent the agent from accidentally executing deployments intended for workers.

### Additional context

Although workers will supersede agents and this fix would only apply to future releases, this is still a pitfall that we could eliminate, especially for users new to Prefect who may be wondering whether they should use agents, workers, or both.

**Comment by serinamarie** [comment]
Hi @EmilRex, that makes sense to me! If I'm understanding you correctly, then I think someone could look to our `WorkPoolFilters` in our `agents.py` file to fix this, as well as add some regression tests for it.

[Potentially relevant PR](https://github.com/PrefectHQ/prefect/pull/9757)

**Comment by EmilRex** [comment]
@serinamarie yep, exactly! I think it this is a case of applying a filter in the default case.
