### ISSUE TITLE
Restart after modifying task state re-runs the failed task

### ISSUE THREAD

**Issue by sophiaponte** [PrefectHQ/prefect#10749]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Our team designs prefect flows in which tasks sometimes fail. When this happens, we perform some action (unrelated to prefect) and then set the state of the task to "completed", and continue running the flow. Our expectation is that the flow would continue from whichever task is after the failed task. However, we have noticed in Prefect 2 that retrying the flow after editing the failed tasks status to completed re-runs the failed task, and does not start from the next one. 

When we were using Prefect 1, I believe the behavior was what we expected, meaning that restarting a failed flow after manually editing the task's status in the UI would start the flow from the next task, and not re-run the failed task. So I am not sure if the different behavior we are experiencing with prefect 2 is a bug, or if there are other steps we need to take to replicate the behavior we expect. 

### Reproduction

1. Create a flow with three tasks, make the second task fail by always throwing an error or something. The flow should have persist_results=True. We also have remote_storage configured. 
```
from prefect import task, flow
from prefect.deployments.deployments import Deployment
from prefect.task_runners import SequentialTaskRunner
import asyncio

@task(persist_result=True)
def task_1():
    print("success!")

@task(persist_result=True)
def task_2():
    raise RuntimeError

@task(persist_result=True)
def task_3():
    print("success!")

@flow(task_runner=SequentialTaskRunner(), persist_result=True)
def demo_restart_issue():
    task_1()
    task_2()
    task_3()

async def deploy():
    local_deployment = await Deployment.build_from_flow(
        flow=demo_restart_issue,
        name=f"deployment_demo_restart_issue",
    )
    await local_deployment.apply()


if __name__ == "__main__": 
    asyncio.run(deploy())
```

3. Run the flow on the prefect UI. The flow will fail due to the second task failing.
4. Go to the second task in the UI, and manually set its status to "Completed". 
<img width="353" alt="Screen Shot 2023-09-18 at 9 09 31 AM" src="https://github.com/PrefectHQ/prefect/assets/29695959/4f99568e-c7ce-487c-827d-259b9c872aaf">

5. Restart the flow by clicking "Retry"
6. The flow will fail again because it will re-run the second task, even though we set its state to completed. 

### Error

Prefect UI displaying initial task and flow run failure: 
<img width="1070" alt="image" src="https://github.com/PrefectHQ/prefect/assets/29695959/e063829b-d9f1-4291-b0a3-082de3eae828">

This is how I modified the state of task run 2:
<img width="1075" alt="Screen Shot 2023-09-18 at 9 43 29 AM" src="https://github.com/PrefectHQ/prefect/assets/29695959/e8a362f2-fd32-4381-a8bf-d7a4e790e2ab">

The flow run after modifying the state of the task, but before retrying the flow:
<img width="1066" alt="Screen Shot 2023-09-18 at 9 44 01 AM" src="https://github.com/PrefectHQ/prefect/assets/29695959/298ebaa6-0bd6-4a0c-b79e-d577e03f71d6">

Prefect UI after clicking "Retry". I would have instead inspected the flow to restart from **after** task 2, and run task 3. Instead, it retries task 2, which fails again.
<img width="1069" alt="Screen Shot 2023-09-18 at 9 46 17 AM" src="https://github.com/PrefectHQ/prefect/assets/29695959/001b36e3-aa4d-4c12-a5d4-e6182e011d56">

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.13.0
API version:         0.8.4
Python version:      3.10.12
Git commit:          66577cc6
Built:               Thu, Sep 7, 2023 3:52 PM
OS/Arch:             darwin/arm64
Profile:             ephemeral
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.42.0
```
```


### Additional context

_No response_

**Comment by matankley** [comment]
+1 . I face the same issue. hope this can be fixed since its impossible to skip tasks in that case.

**Comment by jakekaplan** [comment]
Hey thanks for filing this issue and the great writeup! This behavior is not strictly a bug, however it is maybe a bit unexpected coming from Prefect1. We'll need to do some investigation into supporting this

**Comment by sophiaponte** [comment]
> Hey thanks for filing this issue and the great writeup! This behavior is not strictly a bug, however it is maybe a bit unexpected coming from Prefect1. We'll need to do some investigation into supporting this

Thanks! I'm confused about why this behavior is not classified as a bug though. When we retry a flow run, any tasks that already completed successfully are skipped, **except** for tasks that were marked completed manually. This distinction in behavior means that the ability to mark tasks as completed manually is essentially pointless. Unless the manual completed setting is intended to be used in a different way than I understand it?

**Comment by ACronje** [comment]
+1. Our use-case: sometimes a task fails and we might need to manually perform the task but still want the rest of the flow steps to continue _after_ the manual intervention

**Comment by cicdw** [comment]
Small update: I've looked into this and agree this is a use case we need to support.  It appears that we over-indexed to situations where data is exchanged between tasks, so anytime a completed state has an empty data payload Prefect decides to rerun the task.  I tried doing a few simple adjustments, but those caused other downstream errors so I'll need to be careful about modifying the result logic.

I think the ideal behavior would be to not rerun completed tasks and to only raise an error if a downstream task actually consumes the output of an upstream task with no persisted result payload.

**Comment by sophiaponte** [comment]
Thanks for the update @cicdw! Do I understand correctly that a way to get around this in the mean time would be 

> It appears that we over-indexed to situations where data is exchanged between tasks, so anytime a completed state has an empty data payload Prefect decides to rerun the task.

Does this mean that this behavior only happens when a task has an "empty data payload"? I'm not sure exactly what that means -- does it have to do with the task's `Result`? If that's the case, then can we ensure completed tasks get properly skipped during flow run restarts by ensuring that all tasks return a value that is consumed by a downstream task?

**Comment by abrookins** [comment]
@sophiaponte You pretty much nailed it, yeah! Manually changing the task's state creates a new Completed state for the task run, but the state has no result data. During normal operation, the client includes that result data when it proposes a Completed state, but here, our API is creating the Completed state directly.

This creates problems because currently, the engine/client code only knows that a task either returned nothing or returned something, but in both cases, we have "result data" for the task run, even if it's a container for the value None if the task returned None. Our approach to solving the problem is to elevate the fact that _we know we don't know_ and represent that with a sentinel value, so the engine/client can react more appropriately.

We also want to set that Unknown result whenever we know we don't know, like in your use case, manually changing a state, and we also want to set it reactively if the engine/client code encounters a state missing result data.

I'm working on both of these changes now!
