### ISSUE TITLE
Allow for env variables to be passed into deployment variables

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect#10751]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

```
This deployment configuration references work pool '{{ $WORKPOOL }}' which
does not exist. This means no worker will be able to pick up its runs. You
can create a work pool in the Prefect UI.
```

Attempting to pass in an env variable for a work pool name, it outputs the above error

![Screenshot 2023-09-18 at 3 41 43 PM](https://github.com/PrefectHQ/prefect/assets/69161193/12692d28-aeda-4296-8c36-d645b2e2684f)

### Describe the proposed behavior

It is currently possible to pass in env variables for the deployment steps(build, push, pull steps). It would be nice if the same could be used for values under the deployments section

### Example Use

An example would be setting an env variable for work pool and it could be different based on where the flow runs.

**Comment by jakekaplan** [comment]
Just want to clarify if the idea is to support env variables where `prefect deploy` is being run (as opposed to where the flow runs?)

**Comment by serinamarie** [comment]
Hi @Bada-S, it is already the case that you can set env vars in the `prefect.yaml` file, during `build`, `push`, and `pull` actions. You can also pass them during interactive `prefect deploy` and the env var value is saved under the `deployments` section.

For example, with the following `prefect.yaml`:
```yaml
build: ...

push: ...

pull: ...

deployments:
- name: test-deployment
  version:
  tags: []
  description:
  entrypoint: bar_flow.py:foo
  parameters: {}
  work_pool:
    name: local-work
    work_queue_name:
    job_variables: {}
```
Set the env var:
```bash
❯ WORKPOOL=local-pool
```

Run `prefect deploy`:
```
❯ prefect deploy -n test-deployment -p $WORKPOOL
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Deployment 'foo/test-deployment' successfully created with id '28dbb13a-7154-49ed-bb70-2d0d572d78f1'.                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
? Would you like to save configuration for this deployment for faster deployments in the future? [y/n]: y
? Found existing deployment configuration with name: test-deployment and entrypoint: bar_flow.py:foo in the prefect.yaml file. Would you like to 
overwrite that entry? [y/n]: y

Deployment configuration saved to prefect.yaml! You can now deploy using this deployment configuration with:

        $ prefect deploy -n test-deployment

You can also make changes to this deployment configuration by making changes to the prefect.yaml file.

To execute flow runs from this deployment, start a worker in a separate terminal that pulls work from the 'local-pool' work pool:

        $ prefect worker start --pool 'local-pool'

To schedule a run for this deployment, use the following command:

        $ prefect deployment run 'foo/test-deployment'

**Comment by Bada-S** [comment]
Hi @serinamarie, thanks for the suggestion. The client that was requesting this was specifically using python based deployments so passing the env vars through the cli command wouldn't work. However, it would be possible to pass the workpool as an env var through those python based deployments, so I'll suggest that to them and close out this issue
