### ISSUE TITLE
Task feature timeout_seconds seizing to function as intended after update

### ISSUE THREAD

**Issue by DC-vhl** [PrefectHQ/prefect#10766]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I just updated from Prefect 2.8.2 to 2.13.1 (apologies for the span of versions this leave on the table), and since then the timeout_seconds feature on my @tasks have stopped working.

### Reproduction

```python3
from prefect import task, get_run_logger, flow
import time

@task(timeout_seconds=1)
def show_timeouts():
    logger = get_run_logger()
    logger.info("I will execute")
    time.sleep(5)
    logger.info("I will not execute")

@flow
def my_flow():
   show_timeouts()

my_flow()
```

### Error

```python3
No error, which is the issue in a nut shell :-)

I would expect the code example to return an error before the "I will no execute" is run.

EDIT: The logger output I'm experiencing:
16:17:39.268 | INFO    | prefect.engine - Created flow run 'funny-kangaroo' for flow 'my-flow'
16:17:39.335 | INFO    | Flow run 'funny-kangaroo' - Created task run 'show_timeouts-0' for task 'show_timeouts'
16:17:39.336 | INFO    | Flow run 'funny-kangaroo' - Executing 'show_timeouts-0' immediately...
16:17:39.387 | INFO    | Task run 'show_timeouts-0' - I will execute
16:17:44.391 | INFO    | Task run 'show_timeouts-0' - I will not execute
16:17:44.433 | INFO    | Task run 'show_timeouts-0' - Finished in state Completed()
16:17:44.461 | INFO    | Flow run 'funny-kangaroo' - Finished in state Completed('All states completed.')
```

### Versions

```Text
This issue is encountered on 2.13.1, and was working on 2.8.2
```

**Comment by desertaxle** [comment]
Thanks for the issue @DC-vhl! I'm not able to replicate this issue. Can you share some more info about your setup by sharing the output of `prefect version`?

**Comment by DC-vhl** [comment]
@desertaxle thanks for the swift reply!
Surely, the output is:
```
Version:             2.13.1
API version:         0.8.4
Python version:      3.10.8
Git commit:          d147b180
Built:               Thu, Sep 14, 2023 2:54 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

Again, just make sure I've explained the issue well enough, the problem is that I am **not** thrown an error/exception, and that the attached sample code runs to completion :-) 

I have added the log-messages in the description of the ticket, in case this helps.

**Comment by desertaxle** [comment]
Thanks @DC-vhl! It looks like you're on Windows, which might explain why you aren't seeing a timeout exception as expected. I will try reproducing this on a Windows machine.

**Comment by DC-vhl** [comment]
Hey @desertaxle , thanks for looking into it! Do you have an update on reproduction of the issue? 😄
