### ISSUE TITLE
Rotate API Keys via API

### ISSUE THREAD

**Issue by trahloff** [PrefectHQ/prefect#10765]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

API keys can only be rotated via a webGUI user: 
~~~curl
curl 'https://api.prefect.cloud/api/accounts/{account_id}/bots/{svc_acc_id}/rotate_api_key' \
        -H 'authority: api.prefect.cloud' \
        -H 'accept: application/json, text/plain, */*' \
        -H 'accept-language: en-US,en;q=0.9,de;q=0.8' \
        -H 'authorization: bearer ey...' \
        -H 'content-type: application/json' \
        -H 'origin: https://app.prefect.cloud' \
        -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
        -H 'sec-ch-ua-mobile: ?0' \
        -H 'sec-ch-ua-platform: "Linux"' \
        -H 'sec-fetch-dest: empty' \
        -H 'sec-fetch-mode: cors' \
        -H 'sec-fetch-site: same-site' \
        -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
        -H 'x-prefect-ui: true' \
        --data-raw '{"api_key_expiration":"2023-10-25T22:00:00.000Z"}' \
        --compressed
~~~

### Describe the proposed behavior

API keys can be rotated via CLI/API and/or Python SDK.

### Example Use

To comply with regulations, we need to rotate our API keys regularly. Doing so manually is very error-prone and tedious.

**Comment by meggers** [comment]
We'd like this enhancement (and the linked enhancement) in order to comply with our security requirements that require frequent key rotations. We normally automate these processes to reduce burden and potential for error.

**Comment by WillRaphaelson** [comment]
Hi @trahloff - this is supported via API [here](https://app.prefect.cloud/api/docs#tag/Bots/operation/rotate_api_key_api_accounts__account_id__bots__id__rotate_api_key_post) - is there something I'm missing?  Thanks
