### ISSUE TITLE
Global Concurrency Limits not displayed in UI

### ISSUE THREAD

**Issue by rebecca-liveeo** [PrefectHQ/prefect#10779]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

No existing Global Concurrency Limits are listed in the UI, even if they are newly created.

### Reproduction

In a Prefect cloud workspace, go to Settings > Concurrency. No Global Concurrency Limits will be listed.
Create a new Global Concurrency Limit and see that still nothing will be listed.
If you then try to recreate a limit with the same name, it will not be possible, implying the limits have been created, they are just not visible.

### Error

![image](https://github.com/PrefectHQ/prefect/assets/143079214/a3f3ced8-1512-4468-a5fa-6af2dc94b778)
We had existing limits and they are not displayed, I have also made new ones to double check and they are not showing up after creation.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment]
Hi @rebecca-liveeo - can you give some more information about how you are creating the concurrency limits? Are you using the ui/api/something else?

**Comment by zhen0** [comment]
Thanks for reporting!  We're taking a look into this.

**Comment by bunchesofdonald** [comment]
Thanks for the report @rebecca-liveeo, it looks like you were running into a data validation issue on one of your limits. I fixed the data so you should be able to see your concurrency limits now. We'll also put in a fix to make sure limits can't get into that state again.
