### ISSUE TITLE
Add "url_for" utilities to help users build workflows that involve API calls

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#108]
Similar to `url_for` in Flask, that automatically generates the appropriate URL. In a given flow_run, we should have all the information we need to build an API call on the fly. This would make #88 easier.

**Comment by lauralorenz** [comment]
@jlowin can you expand some more on what the "appropriate URL" is a URL of?

**Comment by cicdw** [comment]
Closing due to lack of clarity / lack of clear problem this solves.
