### ISSUE TITLE
UI Enhancement: Easily Visible Automation Configurations

### ISSUE THREAD

**Issue by TaliaSRTR** [PrefectHQ/prefect#10800]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Right now, when you navigate to the Automations tab of the Prefect UI and select an automation that you've created, it displays a very limited amount of information about the Automation. It only displays the following:

- The description
- The trigger type
- The action

It would be very helpful it displayed some of the more granular data that you can only otherwise see if you go to edit the Automation. This would include:
1. The list of run states that can trigger the automation (assuming you've chosen "Flow run state" as your trigger type)
2. The list of flow run tags that can trigger the automation (assuming you've chosen "Flow run state" as your trigger type)
3. Links to any blocks (e.g. Webhook block) attached to the automation

### Reproduction

Navigate to the "Automations" tab of a workspace and select any Automation you've created that uses the "Flow run state" trigger.

### Error

<img width="398" alt="Screenshot 2023-09-22 at 12 35 49 PM" src="https://github.com/PrefectHQ/prefect/assets/23459294/671df143-f7f4-4b09-b092-e3f79462d87b">

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Additional context

This isn't a bug per se, just a proposed enhancement!

**Comment by taylor-curran** [comment]
plus one to this, have heard many users request this
