### ISSUE TITLE
Page appears blank when refreshing at a deep level.

### ISSUE THREAD

**Issue by rogerogers** [PrefectHQ/prefect#10807]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Refreshing the page on the details page, for example `/deployments/deployment/7a3b97fa-3300-45f9-8dbf-xxxxxxxxxx`

![image](https://github.com/PrefectHQ/prefect/assets/40619032/fdd95e76-ffb1-4f04-8c60-ccc523e80a18)
The static resource address is incorrect.

It could be caused by this line of code, and I'm not sure how you built it.
https://github.com/PrefectHQ/prefect/blob/d739f53f4ae7cbea8ca2f42e42881d4a80481abc/src/prefect/cli/dev.py#L163

### Reproduction

Open link eg deployments detail `http://localhost:4200/deployments/deployment/7a3b97fa-3300-45f9-8dbf-xxxxxxxxxx`, then refresh.

### Error

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

resource link is error, so default `index.html` is return.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.13.2
API version:         0.8.4
Python version:      3.11.4
Git commit:          dcd8a58f
Built:               Thu, Sep 21, 2023 2:33 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.42.0
```

**Comment by zhen0** [comment]
Reproduced in the OSS UI - not an issue in the Cloud version.  Thanks for flagging @rogerogers

**Comment by voidel** [comment]
Lets get this fixed please. Currently this is preventing pages loading if you middle click/open in new tab, and also if you a link from another application that navigates to a specific flow run page - these don't work anymore either.

**Comment by taljaards** [comment]
I'm also getting these blank pages on a local Prefect server. Tested using Prefect v2.13.5 on Chrome, running on Windows 10.
This seems to happen for all pages opened in a new tab, except if for those spawned from the side menu.
![image](https://github.com/PrefectHQ/prefect/assets/6089256/d3e3ab86-9c14-4def-ad28-f1838c513810)

If you open other links (e.g. http://localhost:4200/flow-runs/flow-run/2afa08f9-da17-4370-b498-459ff8337784) via normal navigation (not as a new tab), they work fine. But as soon as you refresh that page, they turn blank as well.

**Comment by batuhanfaik** [comment]
Thanks for the clear presentation @taljaards! I am having the same problem

**Comment by bcatcho** [comment]
I'm having the same problem here. I have experienced it in Safari and Arc. This is a problem that almost deterred me from choosing Prefect for my team strangely enough, because it made OSS version *seem* buggy/uncared-for (which is definitely not the case).

**Comment by TheoBabilon** [comment]
It's also quite an important problem when you use Notifications through the apprise integration (Slack in our case).

Notifications includes the flow run URL:

```
Flow ID: 3c5f8046-9424-40a4-a9ce-71125ed36933
Flow run ID: c8e18225-969c-4571-82c2-99f275ae1f6f
Flow run URL: http://my-server/flow-runs/flow-run/c8e18225-969c-4571-82c2-99f275ae1f6f
```

But clicking the provided url will just display the blank page; which means that if we want to investigate a flow run we manually have to search for it by going through root url / and navigating the left menu

**Comment by philippjh** [comment]
The bug has been introduced in 2.13.2, which means that 2.13.1 does not exhibit this issue. Comparing the respective tags indeed shows, that commit 5dfcf4a208f1c95d0791084b460a40cfbc6298bd is the problem as already mentioned in the initial issue report. Reverting this change locally and building the UI resolves the issue for me. I propose to revert the change for the repository, if it is not affecting anything else.

**Comment by batuhanfaik** [comment]
> ... Reverting this change locally and building the UI resolves the issue for me.

Did you run tests? If everything works, would you care to open a PR?
