### ISSUE TITLE
Add log file download from Flow Run UI

### ISSUE THREAD

**Issue by trentshapiro** [PrefectHQ/prefect#10805]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently to retrieve logs from a flow run you have to query the Prefect API, or you can create a separate manual log file as a Flow Run happens.

### Describe the proposed behavior

Add a button to Flow Run>Logs submenu or added ellipses option to download the current log file. 

### Example Use

After a Flow Run, the log output may contain some information in a format not conducive to being viewed in the browser window, rather than pulling from the API and formatting the output, have a standard output available to be downloaded from the UI.

**Comment by Aokigahara23** [comment]
Helo guys. Is this going to be implemented? It will make our prefect usage so much better cuz we have very big logs. And browser search does not allow you to search all the way down because of some lazy loading (i suppose).

**Comment by WillRaphaelson** [comment]
We are not planning to take this up at this time, as the API is the best way to retrieve logs outside of the UI.
