### ISSUE TITLE
Confusing heirrarchy and terminology of "flows" "deployments" and "flow runs"

### ISSUE THREAD

**Issue by Ben-Epstein** [PrefectHQ/prefect#10811]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

I think the current layout of flows, deployments, and flow runs is more confusing than it needs to be, making onboarding a bit difficult.

One issue is that it's not clearly documented in the onboarding/quickstart guides how to think about these 3 concepts. This is then compounded by the way they are laid out in the UI, and then the interactions within the UI on each entity.

<img width="257" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22605641/ada8e967-2932-466d-997b-95bcda9177a7">

My understanding of the hierarchy is as such:
a **Flow** is the blueprint of a process that you want to run. It defines _what you want to get done_
a **Deployment** is akin to the instantiation of a Flow. This is a flow with particular configurations, such as 
* how frequently this flow will run
* what parameters we will run the flow with
* how to organize this instantiation, ie tags and such
a **Flow run** is the _execution_ of a given deployment. This is confusing because they are called _flow_ runs, not _deployment_ runs, or even just _runs_. 

Additionally, because the left-nav breaks things down as 
1. Flow runs
2. Flows
3. Deployments

You implicitly assume that deployments are the top-level entity of the system, not flows. This had me confused for a while. You think that 
* a deployment can have multiple flows
* a flow can have multiple runs

But in reality, the structure is that
* a flow can have multiple deployments
* you can have any number of runs that are really a deployment _of a flow_

### Describe the proposed change

I think a few things would go a long way

* Change `Flow Runs` to just `Runs` in the UI. I think this is critical because when you click into "Flow Runs", you can immediately filter by Deployments, which is a hard concept to internalize if you don't understand the hierarchy. And, I think the run really is of a deployment, not a flow (it could be both perhaps).

* Change the order of the left-nav to be either:
1. Runs
2. Deployments
3. Flows
or 
1. Flows
2. Deployments
3. Runs

* In the "Flows" tab, inside flow chip, there should be a small link that takes you right to the deployments of that flow. This would help explain to users implicitly why you _can't run a flow directly_

![image](https://github.com/PrefectHQ/prefect/assets/22605641/1f6e20a4-af90-4e1e-827b-306b13b377b4)

* In the quickstart guide, pretty quickly offer a short piece about "Flows, Deployments, and Runs"

### Additional context

If i'm missing anything here or got any concepts wrong please let me know!

I'm starting to use prefect in a prod environment and want to make sure I have everything down.

Thanks!

**Comment by N-Demir** [comment]
I've been thinking the same thing!!

**Comment by WillRaphaelson** [comment]
Thanks for this issue @Ben-Epstein. We'll continue to think critically about our information architecture, but for the time being will close this in favor of more discrete and actionable issues. cc @djsauble.
