### ISSUE TITLE
Missing word in storage-guide.md

### ISSUE THREAD

**Issue by mj0nez** [PrefectHQ/prefect#10824]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The warning for git-based storage misses a word and a sentence could be a bit more simple:

> !!! warning "Push your code"
>     When you make a change to your code, Prefect does push your code to your git-based version control platform. 
>     You need to do push your code manually or as part of your CI/CD pipeline. 
>     This design decision is an intentional one to avoid confusion about the git history and push process.

### Describe the proposed change

see PR

**Comment by serinamarie** [comment]
Hi @mj0nez, thanks for the issue! I've requested a small change in your PR, so we can continue any further discussion there if needed :)
