### ISSUE TITLE
Clarify Docs and Expand Testing for Map / Caching Behavior

### ISSUE THREAD

**Issue by jlewis91** [PrefectHQ/prefect#1082]
Following up on #1071, just wanted to suggest adding a test to capture current map/cache behavior and expanding map caching documentation.

As far as I understand prefect mapping & caching, output caching does not work (should not work ???) in the following situations:

1. Multiple elements in a given map have the same inputs and the mapped task is setup to cache.
2. If the position of an item in a mapped inputs changes, then the cache does not get triggered, e.g. cache retrieval is not only based on the function arguments, but the position of an item in the map.

This means that flows which want to take advantage of caching with mapped inputs need to treat the mapped inputs as ordered lists (effectively each ordered element in a mapped input has its own separate cache).

Any thoughts about changing the map/cache architecture so that the redundant computation within 1) and the duplicate cache elements within 2) are eliminated?

```python
class MockSchedule(prefect.schedules.Schedule):
    call_count = 0

    def next(self, n):
        if self.call_count < 3:
            self.call_count += 1
            return [pendulum.now("utc")]
        else:
            return []

class StatefulTask(Task):
    def __init__(self, returnit=False, **kwargs):
        self.returnit = returnit
        super().__init__(**kwargs)

    call_count = 0
    default = [0, 0, 0]
    
    def run(self):
        self.call_count += 1

        if self.returnit:
            return [self.call_count] * 3
        else:
            self.default[self.call_count - 1] = self.default[self.call_count - 1] + 1
            print(self.default)
            return self.default


    
@task(
    cache_for=datetime.timedelta(minutes=1),
    cache_validator=partial_inputs_only(validate_on=["x"]),
)
def return_x(x, y):
    return y

storage = {"y": []}

@task(trigger=prefect.triggers.always_run)
def store_y(y):
    storage["y"].append(y)

t1, t2 = StatefulTask(), StatefulTask(returnit=True)
schedule = MockSchedule()
with Flow(name="test", schedule=schedule) as f:
    res = store_y(return_x.map(x=t1, y=t2))

f.run()

first_run = storage["y"][0]
second_run = storage["y"][1]
third_run = storage["y"][2]

## first run: all elements return 1, e.g. updated in first run
## y: [1, 0, 0]
assert first_run == [1.0, 1.0, 1.0]

## second run: caching for first and third elements; no cross-element caching (e.g. second element not cached even though return_x(x=1) and return_x(x=0) is cached for other map elements)
## y: [1, 1, 0]
assert second_run == [1.0, 2.0, 1.0]

## third run: all tasks succeed, caching for first and second elements
## y: [1, 1, 1]
assert third_run == [1.0, 2.0, 3.0]
```

**Comment by cicdw** [comment]
Interesting, it took me a bit to understand your train of thought but I see what you're getting at now.  I don't have a reply quite yet, I'll need to chew on this a little to think through the implications / how we might design this to also be compatible with our Cloud API.

**Comment by cicdw** [comment]
Small update on this:  interestingly, caching across mapped tasks is already supported in Prefect Cloud; this is because in Cloud (which includes a database), `CachedState`s are stored and retrieved by `task_id` which is shared amongst all common mapped tasks.  The wrinkle is that in the `prefect` package alone there is no state management service that can be queried for all _potential_ valid caches of a task.  Consequently, the current no-Cloud implementation simply matches mapped tasks with their initial state ordering.

I definitely agree that this leads to undesirable behavior, but I haven't found a way around it (yet).

**Comment by cicdw** [comment]
Immediately after writing the above, I realized we _do_ have a storage option which is entirely contained within the open source engine - `prefect.context`!  I've opened a 90% complete PR here: https://github.com/PrefectHQ/prefect/pull/1100
