### ISSUE TITLE
Have all tasks automatically submitted to the `TaskRunner` without explicitly calling `.submit()`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [PrefectHQ/prefect#10839]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, if you want to submit a task to a `TaskRunner`, you have to call the `.submit()` attribute of the `Task` object. However, this relies on the user to modify their underlying Python code, which seems to go against the basic principle behind Prefect. 

Current approach:

```python
from prefect import task

@task
def add(a, b):
    return a + b

add.submit(add.submit(1, 2), 3)
```

Note how this is different than the typical `add(add(1, 2), 3)`. When making a `Flow`, this means that the workflow itself will have to be modified to make `.submit()` calls for each `Task`.

### Describe the proposed behavior

I was hoping there might be some way that I could have all tasks automatically submitted to the `TaskRunner` if specified via some kwarg in the `@flow` decorator. 

### Example Use

```python
from prefect import flow, task

@task
def add(a, b):
    return a + b

@task
def mult(a, b):
    return a * b

@flow(task_runner=MyTaskRunner, auto_submit=True)
def workflow(a, b, c):
    return mult(add(a, b), c)


workflow(1, 2, 3)
```

### Additional context

https://github.com/PrefectHQ/prefect/discussions/10810

**Comment by desertaxle** [comment]
Thanks for the enhancement idea @Andrew-S-Rosen! Can you share more about your use case where a flow option like `auto_submit` would be useful? I ask because having tasks within a flow auto-submit to a task runner will require a code change in many cases because the return type of those tasks will change from raw objects to futures. Since task runners are an advanced feature of Prefect that changes how your code executes, we expect there to be some code modification to use them.

**Comment by Andrew-S-Rosen** [comment]
@desertaxle: Thanks for the reply! Sure, I'd be happy to elaborate a bit.

If intelligently approached, this isn't necessarily the case. I am shipping a variety of compute tasks and workflows where the user can opt to use or not use Prefect. As such, I have my own dedicated decorator that, depending on the user's settings, will either ensure the `@task`/`@flow` calls run with Prefect or just do nothing at all. It's helpful to have the same syntax in this case for with and without Prefect to minimize friction.

Now, the reason why I say that the tasks often don't need to change is because there is rarely a need to resolve (i.e. call `.result()`) on intermediate `Task` objects, and this is in fact often undesirable to do anyway because it blocks. As shown in my toy example above, there is no need to call `.result()` on the intermediate `Task` objects --- only on the final `Flow`. What that means is, from a code design perspective, the individual compute tasks and workflows can be designed in such a way so that they don't need any code changes even though they are futures. It requires some forethought, sure, but it's certainly possible. The only change is the retrieval of the final result, which I leave to the user to do --- not as part of the workflow definition itself.

However, requiring calls to `.submit()` breaks this logic, as there is no way to avoid it. I would also argue that task runners aren't really an "advanced" feature --- after all, one would rarely need to use Prefect if they were running everything locally. 😉

Now that you've read this far, I'll actually be a bit more truthful. I am building a program that interfaces with not only Prefect but _several_ (5+) workflow engines that use a similar decorator-based approach. In all cases, whether I want to have the workflow run locally or deployed, the only thing that needs to change is some keyword argument or setting somewhere to indicate it --- except for Prefect, where I have to call `.submit()` in the deployed case. I can work around this, but it is a bit clunky, and I selfishly was looking for a way to not need to change the underlying workflow definitions to call `.submit()` just because I want to use a `TaskRunner`.

**Comment by Andrew-S-Rosen** [comment]
@desertaxle: A similar but related utility function might be the ability to directly query a `PrefectFuture` without invoking `.result()` explicitly. 

```python
import time
from prefect import task

@task
def task1(val: float) -> dict:
    """
    This task does some expensive calculation and produces a dictionary as the result.
    """
    time.sleep(2)
    return {"input": val, "result": val*100}

@task
def task2(val: float) -> dict:
    """
    This task does a different expensive calculation.
    """
    time.sleep(4)
    return {"input": val, "result": val*200}

@flow
def workflow(val):
    future1 = app1(val)
    return app2(app1.submit(val).result()["result"])
```

This is quite clunky. It would be nice to be able to do

```python
@flow
def workflow(val):
    future1 = app1(val)
    return app2(app1.submit(val)["result"])
```

where it implicitly knows to call `.result()` if indexing a `PrefectFuture`, such as by creating a `__getitem__` method on `AppFuture` that will do such a shortcut.

**Comment by desertaxle** [comment]
Thanks for the explanation @Andrew-S-Rosen! We are unlikely to add this functionality because a change in the proposed setting would require users to write their code differently, even if it wouldn't require a code change in all cases. We prefer a change in execution to require a change in your code to make the change explicit.

That being said, if you have custom decorators that you are already using to wrap `@task` and `@flow`, I recommend making this change in your custom decorators. If you have questions about how to do that with Prefect's API, let us know and we'll do what we can to help!

**Comment by Andrew-S-Rosen** [comment]
Thanks for the reply! Not a problem --- just wanted to make sure my rationale was laid out more clearly. Very much understood.
