### ISSUE TITLE
Standardize process work pool type name in the UI and CLI (process vs. subprocess)

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10842]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Local Subprocess is the term when creating a work pool in the UI
<img width="913" alt="Screenshot 2023-09-27 at 6 12 28 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/1b0fbba6-90b4-4305-99a2-7e4f833678e4">

After creation in the UI it is referred to as a Process work pool.
<img width="488" alt="Screenshot 2023-09-27 at 6 13 11 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/0ac0cb1e-eb30-40f6-b34d-2ed757cca051">

<img width="210" alt="Screenshot 2023-09-27 at 6 13 34 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/657aea2b-c13e-45af-978e-c48c4bf2463b">

The CLI also refers to it as a process work pool.
<img width="446" alt="Screenshot 2023-09-27 at 6 14 37 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/66fd13ca-ba1b-4540-bf2c-417db40a1ba9">

### Describe the proposed behavior

Standardizing on process or subprocess would be good for users.

**Comment by SudhanshuJoshi09** [comment]
Hey @jakekaplan, I would like to work on this can I get started ?

**Comment by AddoZhu** [comment]
Hi @jakekaplan  ,

I'm looking for some "good first issue" related to coding and would like to work on this.

Could you please assign it to me? Thanks.

**Comment by WillRaphaelson** [comment]
Hi @AddoZhu - sorry for the delay, sounds great! Reach out if you'd like to paid.

**Comment by discdiver** [comment]
I can take this. Would plan to standardize on "Process"
