### ISSUE TITLE
Alembic revision mismatch in version 2.13.4

### ISSUE THREAD

**Issue by m-steinhauer** [PrefectHQ/prefect#10887]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

After restarting an updated Prefect version from 2.13.3 to 2.13.4, Prefect does not start anymore due to an not found alembic version revision which boils down the following error message:
`alembic.util.exc.CommandError: Can't locate revision identified by '05ea6f882b1d'`

If looking at the current code and the alembic schemata on the tag 2.13.4 it can be easily identified that the specified revision id in the alembic document itself (`05ea6f882b1d`) is different from the file naming `2023_09_25_121806_8167af8df781_remove_flow_run_id_requirement_from_task_run.py`. This should be named `2023_09_25_121806_05ea6f882b1d_remove_flow_run_id_requirement_from_task_run.py`
[See file](https://github.com/PrefectHQ/prefect/blob/2.13.4/src/prefect/server/database/migrations/versions/postgresql/2023_09_25_121806_8167af8df781_remove_flow_run_id_requirement_from_task_run.py)

### Reproduction

```python3
- update to version 2.13.4
- Restart prefect
- Prefect fails to start due to revision mismatch
```

### Error

```python3
`alembic.util.exc.CommandError: Can't locate revision identified by '05ea6f882b1d'`
```

### Versions

```Text
2.13.4
```

**Comment by m-steinhauer** [comment]
Already suggesting a PR for that issue: https://github.com/PrefectHQ/prefect/pull/10888

**Comment by jakekaplan** [comment]
Hi @m-steinhauer just following up again before I look to close this issue.
