### ISSUE TITLE
Exclude venv folder from `prefect deploy` recursive flow search

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10880]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

A user with a `venv` folder with Prefect installed that runs `prefect deploy` with that folder present has it searched. This takes time and then leads to an error when a flow in `base.py` is found. The error is pretty tricky for a new user to resolve.

I observed this at least twice in remote PACC today.

### Describe the proposed behavior

Exclude the `venv` folder from the search by default, avoiding the error.

### Additional context

```
Version:             2.13.4
API version:         0.8.4
Python version:      3.10.12
Git commit:          48d9d9a2
Built:               Fri, Sep 29, 2023 
11:26 AM
OS/Arch:             darwin/arm64
Profile:             prod
Server type:         cloud
```

**Comment by jakekaplan** [comment]
We might solve this by ignoring prefect source in general. I think you get this same issue when trying to run `prefect deploy` inside of the cloned prefect repo

**Comment by discdiver** [comment]
I haven't seen this come up in quite a while. @jakekaplan, do you know if it was resolved? I expect it was.

**Comment by lucasdepetrisd** [comment]
I'm also having the same issue.

**Comment by lucasdepetrisd** [comment]
@discdiver I'm also having the same issue, did you manage to find a temporary workaround?

**Comment by discdiver** [comment]
@lucasdepetrisd just saw this. There are a few options. Two that come to mind:

1. Create deployment with `flow.deploy` in Python
2. Use a conda environment or some other virtual environment where the package isn't stored within the same folder

**Comment by lucasdepetrisd** [comment]
Thanks for the suggestions! I actually ended up using the second solution. It worked as a charm. However, I think it would be beneficial to include this recommendation at the docs to prevent creation of an env in the same directory as the prefect project.

**Comment by lucasdepetrisd** [comment]
Thanks for the suggestions! I actually ended up using the second solution. It worked like a charm. However, I think it would be beneficial to include this recommendation at the docs to prevent creation of an env in the same directory as the prefect project.

**Comment by discdiver** [comment]
Cool. Good thought. Using a `.prefectignore` is the third option I forgot to mention. That's discussed in the Flow Code Storage Guide [here](https://docs.prefect.io/latest/guides/deployment/storage-guide/#including-and-excluding-files-from-storage). 
As we have that resource I'll mark this issue as closed.
