### ISSUE TITLE
Dask Executor Task throttling

### ISSUE THREAD

**Issue by kforti** [PrefectHQ/prefect#1090]
Hello, I have been reading through some old issues and pull requests and it looks like task throttling by tags used to exist but was removed. I am really interested in the feature of task throttling. 

I subclassed the dask executor and rewrote the map method to add the passed iterable to a queue. The queue is then passed to the dask client's map method with the maxsize argument. This is one of the methods implemented in dask to handle task throttling.
https://stackoverflow.com/questions/38921531/how-to-throttle-a-large-number-of-tasks-without-using-all-workers/38921763#38921763

I am wondering if I missed the task throttling pattern used in Prefect? or if there are plans to implement task throttling in the near future?

**Comment by kforti** [comment]
Also, I found out that if a queue is passed to Dask's Client.map() method, data can be added to the queue even after the initial map() call has completed. You could add a queue_handler to the dask_executor that tracks the running queues for each task type.

**Comment by kforti** [comment]
I started reading more into the code and I noticed that the TaskRunner blocks on mapping. Doesn't this cause a lot of wasted system resources? For example, if you map 100 tasks across 100 workers and there is one task that is running particularly slow, 99 workers sit idle waiting for the task to complete. Is there another way that you overcome this issue?

**Comment by cicdw** [comment]
Hi @kforti ! You are correct, we used to have an implementation of throttling in Prefect.  We removed it in favor of a more global solution that would work across flows and mesh nicely with other throttling requirements our platform has.  That means that throttling on a per-task basis will be a feature only available in Prefect Cloud.

You might be able to implement this yourself _without_ editing Prefect's source code by using `state_handlers` on each Task.  The state handler you would implement would look something like:
```python
def queue_state_handler(task, old_state, new_state):
    if new_state.is_running():
        # wait for a "ticket" in the Queue to come available
    return new_state
```
and the `Queue` object itself you might attach directly to each individual `Task` as an attribute.

Here are some additional resources on state handlers that might help you get started:
- [concept docs on state handlers](https://docs.prefect.io/guide/core_concepts/notifications.html#state-handlers)
- [a simple worked example](https://docs.prefect.io/guide/examples/state_handler_logging.html)

**Comment by cicdw** [comment]
> I started reading more into the code and I noticed that the TaskRunner blocks on mapping. Doesn't this cause a lot of wasted system resources? For example, if you map 100 tasks across 100 workers and there is one task that is running particularly slow, 99 workers sit idle waiting for the task to complete. Is there another way that you overcome this issue?

Great question, and one that we've spent a _lot_ of time thinking about.  In short, allowing for asynchronous / non-blocking execution of the mapped tasks would require us to share futures between Dask Clients, as outlined in slightly more detail here: https://stories.dask.org/en/latest/prefect-workflows.html#pain-points-when-using-dask

We've spent some time exploring various solutions and so far most of them have been brittle and overly complex.  Always open to hearing new ideas on that front!

**Comment by kforti** [comment]
@cicdw thank you for the response. I was thinking that if the blocking is happening on the worker then it might not be as much of a problem, but then I guess that introduces the potential to deadlock the cluster. I found that depth-first can be achieved by using the submit method at the level of the dask client (instead of map) and collect results with the as_completed() function. Then as soon as a result is gathered it can be used to trigger the next task. New futures can be appended to the as_completed object that is returned from the function call, and this can be another method of throttling tasks per client.

I also keep going back to the idea of a cluster manager. All client requests could be routed through a manager that submits tasks the scheduler. The manager could act as a load balancer and could be used to start and terminate specific types of workers. Dask_jobqueue implements something like this https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/deploy/cluster_manager.py

You likely have a lot more flexibility with these things on your cloud platform, but my use case includes HPC environments for scientific computing.

Anyway, I am sure there is a lot I am still missing here but I am very interested in building a system that has flexibility in its distributed computational model.

**Comment by cicdw** [comment]
Hi @kforti - we now allow for Tasks to hook directly into Dask's [Worker Resource](https://distributed.dask.org/en/latest/resources.html) mechanism.  To do so, simply tag your relevant tasks like:
```python
from prefect import task

@task(tags=["dask-resource:MEMORY=70"])
def memory_intensive_task():
    pass
```

(and make sure you run them using the `DaskExecutor`).

I _believe_ this mechanism also allows you to implement a form of Task throttling wherein you specify the amount of a given abstract resource on your Dask workers, and then tag your Prefect Tasks appropriately based on how much of that resource they require / use.  

I'd be very interested to hear if this satisfies your particular use case or not!

**Comment by kforti** [comment]
Hi @cicdw - it's been a while since I have worked on this part of the system I am building. This is a very interesting feature and will certainly be helpful for submitting specific tasks to specific workers. 

My idea of task throttling was related to not overwhelming the dask cluster scheduler with too many tasks. I have since realized that prefect submits tasks from workers in some cases and not from a single client process, where this type of throttling is much easier. I am less concerned about task throttling now because I believe that there is some degree of throttling built into the prefect task dependency structure- tasks aren't submitted until all upstream tasks have been completed.

I do wonder if or when cluster deadlocking is a concern, and if there are best practices in flow construction to avoid deadlocking?

Also, I think that GetItem tasks are holding up workers in some cases, which is preventing my compute-intensive tasks from being submitted. It is not exactly deadlocked but I can see how it could deadlock

**Comment by kforti** [comment]
Actually, I made a mistake. The GetItem tasks were not holding up my cluster, I misread what was happening. I am still interested to hear your thoughts on cluster deadlock

**Comment by kforti** [comment]
I am running tests and I am experiencing cluster crashes.

I am building a system for bioinformatics data analysis where I am partitioning data (list of paths to files or directories), generating commands for that data and then executing those commands. Each step is a prefect task, and the partitioned data is a result that is indexed into (I do not want to use prefect mapping because I do not want to block at each task).

If I partition my data by a factor of 500, it results in about 10,000 tasks. Most of these tasks are GetItem or some other type of indexing. It would be really nice to combine GetItem into another task similar to #674.

Just to briefly summarize this thread:
I am trying to scale Prefect for managing large scale bioinformatics workflows, which I am partitioning and parallelizing across a distributed computing environment. I am trying to understand the execution model that prefect deploys in order to efficiently scale my flows. For my use case, I believe that coarse-grained tasks are more beneficial than fine-grained tasks, as I am dealing with 1,000 of tasks in the fine-grained model ([interesting comparison of coarse-grained vs fine-grained](http://ccl.cse.nd.edu/research/papers/lifemapper_pearc19.pdf)).

**Comment by cicdw** [comment]
Hi @kforti could you share some code to help me wrap my head around your use case?  In particular, I'm wondering if you could index into your result either _before_ returning from the upstream task or _within_ the task that requires the result.  Typically doing something like:
```python
with Flow("index") as f:
    res = my_task_returns_a_dict(param)
    downstream_task(res["key"])
```
is something of an anti-pattern, as indexing into a task is best reserved for situations in which the key itself is only known at run-time.

**Comment by kforti** [comment]
I am using the anti-pattern then. I felt like it was a good way to manage the partitioned data because the data produced within my flow only exists during run-time. I execute some bioinformatics tool on some input data and it generates some output data, which I then use in the execution of the next bioinformatics tool. There are definitely other ways I can do this that do not involve indexing.

This is an oversimplified version of what I am doing:
```python 
num_partitions = 20
with Flow("partition") as flow:
    data_partitions = partition_task([inputs])
    for i in range(num_partitions):
        cmd_result = execute_command_task(data_partitions[i])
```

**Comment by kforti** [comment]
I am going to close this issue after discovering that I was using an anti-pattern. I think I can significantly reduce the complexity of my code by tacking another approach.

**Comment by cicdw** [comment]
Thanks @kforti and feel free to revisit if something isn't working right!  Always happy to help.
