### ISSUE TITLE
Add setting to exclude "jit" option from connect_args server_settings

### ISSUE THREAD

**Issue by ADunigan** [PrefectHQ/prefect#10903]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I cannot find a way to exclude the jit option from server settings. This makes it impossible to connect to an RDS cluster through an RDS Proxy as the jit option is unsupported.

### Describe the proposed behavior

Add a setting so the "jit" option can be excluded from the connect_args server settings.

### Additional context

Need to be able to avoid including {"jit": "off"} below. connect_args will be truthy in all cases unless timeout and connection_timeout are None. Unable to set those settings to None via prefect.env - closest they can be is an empty string which returns as not a valid float.
`if connect_args:
                connect_args["server_settings"] = {"jit": "off"}
                kwargs["connect_args"] = connect_args`

**Comment by serinamarie** [comment]
Hi @ADunigan, thanks for creating your first issue here! I think we can accept this, and if someone were to implement this, they might do so by exposing a setting for `connect_args["server_settings"]`.
