### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by hyonaldo** [PrefectHQ/prefect#1091]
Isn't there any "Web UI" that shows all of DAGs like airflow?
How can I see all the scheduled job list?

The information below is not enough.
https://docs.prefect.io/guide/cloud_concepts/ui.html

**Comment by jlowin** [comment]
Hey @hyonaldo, great question -- we've got an awesome UI as part of our [Cloud platform](https://www.prefect.io/lighthouse-partners) that takes full advantage of Cloud's GraphQL API and stateful layers. We're getting ready to release that to Prefect's early partners now, and public (and free!) versions will follow.

**Comment by andres-lowrie** [comment]
Sorry to resurrect issue but will the code for UI be open source as well?

**Comment by jlowin** [comment]
This version of the UI will be maintained by our team as part of our Cloud platform, and not open-sourced.
