### ISSUE TITLE
typo in the tutorial on deployments

### ISSUE THREAD

**Issue by cruzzoe** [PrefectHQ/prefect#10929]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

https://docs.prefect.io/2.13.5/tutorial/deployments/

On this page the instructions are to attempt to run a deployment via: 

`prefect deployment run 'get_repo_info/my-first-deployment'`

This gives error:
Deployment 'get_repo_info/my-first-deployment' not found!

The correct cmd should be:
`prefect deployment run 'get-repo-info/my-first-deployment'`

### Describe the proposed change

Change the instruction to:

`prefect deployment run 'get-repo-info/my-first-deployment'`

**Comment by taljaards** [comment]
Hi @cruzzoe
I didn't check to confirm the typo, but if you're up for it, you can submit PRs to edit the docs.
This one is here: https://github.com/PrefectHQ/prefect/blob/0c57b832b2b5f8e770ee5447f87eaaff19302e22/docs/tutorial/deployments.md#L79
