### ISSUE TITLE
Fetch the result of a PrefectFuture implicitly when indexed

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [PrefectHQ/prefect#10922]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Related to #10839, a similar but distinct utility function that would be beneficial might be the ability to directly query a `PrefectFuture` without invoking `.result()` explicitly. 

```python
import time
from prefect import task

@task
def task1(val: float) -> dict:
    """
    This task does some expensive calculation and produces a dictionary as the result.
    """
    time.sleep(2)
    return {"input": val, "result": val*100}

@task
def task2(val: float) -> dict:
    """
    This task does a different expensive calculation.
    """
    time.sleep(4)
    return {"input": val, "result": val*200}

@flow
def workflow(val):
    future1 = task1(val)
    return task2(task1.submit(val).result()["result"])
```

This is quite clunky.

### Describe the proposed behavior

A `__getitem__` method on  `PrefectFuture` (and/or `State`?) that will automatically know to query `.result()` when indexed.

### Example Use

It would be nice to be able to do

```python
@flow
def workflow(val):
    future1 = task1(val)
    return task2(task1.submit(val)["result"])
```

where it implicitly knows to call `.result()` if indexing a `PrefectFuture`.

**Comment by jakekaplan** [comment]
Hey, thanks so much for the well written issue!

While I understand not wanting to call `.result()` if all of yours tasks are using `.submit()`, with tradeoffs between convenience and explicitness, explicitness takes priority here. When working with futures it's important for a user to know when a blocking method like `.result()` is called. Additionally implementing methods on the future that are meant to proxy to calling on the underlying result can get complicated and is likely not something we'd be looking to add at this time.

**Comment by Andrew-S-Rosen** [comment]
@jakekaplan: Thanks for your thoughtful reply. What you said makes sense, and I agree. I believe the way I was thinking about it was not ideal, and I'd like to re-motivate my explanation and motivation. Of course, you can still disagree!

Let's still consider the following example:

```python
import time
from prefect import task

@task
def task1(val: float) -> dict:
    """
    This task does some expensive calculation and produces a dictionary as the result.
    """
    time.sleep(2)
    return {"input": val, "result": val*100}

@task
def task2(val: float) -> dict:
    """
    This task does a different expensive calculation.
    """
    time.sleep(4)
    return {"input": val, "result": val*200}

@flow
def workflow(val):
    future1 = task1(val)
    return task2(task1.submit(val).result()["result"])
```

If I want to launch this workflow on several different inputs, it'd look something like:

```python
# Run two separate workflows, ideally concurrently
print("Launching workflow 1...")
future1 = workflow(1)
print("Launching workflow 2...")
future2 = workflow(2)
```

However, because of the call `.result()` in `workflow`, the two workflows will not be called concurrently, as there is a blocking action invoked. In Prefect, it is possible to pass `PrefectFuture` objects between `Task`s, and they will get resolved automatically without the need to call `.result()` because that would block. However, there is no way to pass an _index_ (or other attribute) of (what would be resolved from the) `PrefectFuture` without blocking.

The goal in this case is actually not what I originally suggested. The intended behavior should not be to call `.result()` but rather to enable Prefect to pass indexed `PrefectFuture` objects between `Task` objects without blocking.

Is something like this of interest/possible?

**Comment by Andrew-S-Rosen** [comment]
@jakekaplan: Thanks for your thoughtful reply! I agree with your comment. That said, one can pass `PrefectFuture` objects between `Task`s without calling `.result()`, which is the ideal mechanism. I am wondering if there might be a way we can modify the `PrefectFuture` such that one can pass something like `PrefectFuture["result"]` between `Task`s _without_ having to block and call `.result()`. This was actually more in line with what I meant, but I phrased it poorly.
