### ISSUE TITLE
Issue with ruamel.yaml dependency declared as ruamel-yaml in requirements with rez package system

### ISSUE THREAD

**Issue by lpequignot** [PrefectHQ/prefect#10954]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi,

We are using rez packages manager system https://github.com/AcademySoftwareFoundation/rez.
And we are using prefect to orchestrate flows. 

We're having an issue because ruamel.yaml dependency is declared as ruamel-yaml in prefect requirements.txt.
For the package management system to work to install packages and dependencies, a package need to declare its requirements with the same name as the pip package https://pypi.org/project/ruamel.yaml/

The full explanation can be found here : https://github.com/AcademySoftwareFoundation/rez/issues/1545

Would it be possible to change the requirements with ruamel.yaml >= 0.17.0 ?

Best Regards,

Louise

### Reproduction

```python3
1/ rez installation https://github.com/AcademySoftwareFoundation/rez/wiki/Installation
2/ rez pip -i prefect
```

### Error

```python3
Rez-pip creates a ruamel.yaml rez package on disk but it's adding "ruamel_yaml-0.17.0+" in prefect package.py requires.
rez-env prefect fails with 12:15:03 ERROR PackageFamilyNotFoundError: package family not found: ruamel_yaml, was required by: prefect
```

### Versions

```Text
Version:             2.13.6
API version:         0.8.4
Python version:      3.9.12
Git commit:          8996e4a4
Built:               Thu, Oct 12, 2023 3:54 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         <client error>
```

**Comment by serinamarie** [comment]
Hi @lpequignot, thanks for creating your first issue with Prefect! This does indeed look like an issue in our requirements.txt.
