### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10974]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

[Python 3.12](https://endoflife.date/python) was released to GA on Oct. 2, 2023.

### Describe the proposed behavior

Support Python 3.12. 

### Additional context

[GitHub Actions](https://github.com/actions/python-versions/releases) and [Conda](https://anaconda.org/anaconda/python) support Python 3.12. 

Local testing: installing Prefect 2.13.7 into a conda env with Python 3.12 fails on pendulum install (maybe other issues, too).

Pendulum has added Python 3.12 support on their [main branch](https://github.com/sdispater/pendulum/issues/696), but not cut a release yet as of Oct. 17, 2023. 

3.12 support for most common Python packages is tracked [here](https://pyreadiness.org/3.12/). As of this writing, requests, pydantic, fastapi, and many other popular packages are not yet showing support.

**Comment by oaustegard** [comment]
Arrived here after attempting to upgrade my local environment from 3.11 to 3.12 and found that prefect & marvin expect a version of pendulum <3.0, and pendulum only supports 3.12 from v 3.0.0.b1 onwards.  Could be good to have a list of dependencies and THEIR compatibility with 3.12 as an indicator of the progress of prefect and marvin towards 3.12 support?
