### ISSUE TITLE
Add support for ANSI escape codes in the flow run logs

### ISSUE THREAD

**Issue by gulivan** [PrefectHQ/prefect#10981]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, all the ANSI escape codes are not affecting the coloring in logs.
But they also leave their raw code in logs, which makes it harder to debug it.

<img width="937" alt="image" src="https://github.com/PrefectHQ/prefect/assets/34831957/276ea0d5-8cea-4403-b3a2-886a6b70d253">

### Describe the proposed behavior

Proposed:
- all the ANSI escape codes affect the coloring in the flow run logs
- all the raw text formatting codes are deleted, so they won't clutter the log appearance. 

<img width="1059" alt="image" src="https://github.com/PrefectHQ/prefect/assets/34831957/474ba238-2500-4a5e-bd32-c373b56a31aa">

**Comment by gulivan** [comment]
@mch-sb Sometimes, even CTRL+F won't help because if there are many log lines, parts outside the current window scope won't be rendered and cannot be highlighted or found 🥲

**Comment by mch-sb** [comment]
> @mch-sb Sometimes, even CTRL+F won't help because if there are many log lines, parts outside the current window scope won't be rendered and cannot be highlighted or found 🥲

Completely agree, color highlighting would be very helpfull, and browser CTRL+F is only a medium-minus workaround for my case

**Comment by rudeb0y** [comment]
It's possible to turn colours off.. thats what we do via a global dbt config setting. Still not as good as colours but at least cleans up the log abit.

To make diagnosis easier as well you could try setting the log output format as Json and having a task parse it and upload it as an artifact. Then when a flow fails you can get the summary from the artifact instead of trying to read the log

**Comment by mihasK** [comment]
would be very usefull

**Comment by znicholasbrown** [comment]
Hi all, this should be available on `main` now, see [this PR](https://github.com/PrefectHQ/prefect-ui-library/pull/2582) for details
