### ISSUE TITLE
Long running flow with subflows incorrectly displays as "crashed"

### ISSUE THREAD

**Issue by carlosjourdan** [PrefectHQ/prefect#10991]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a flow that spawns several subflows in parallel using asyincio. During some long runs, the parent flow is incorrectly flaged as crashed, although the subflows are still running. After all subflows complete successfully, the parent flow changes to a completed stage.

This is not only an ui/monitoring issue: the workpool where these incorrectly classified flows are served assumes that they're gone and start delivering new runs to agents, effectively bypassing the concurrency limit.

![image](https://github.com/PrefectHQ/prefect/assets/17554676/b86e9455-aae1-4dc2-ae49-9c9ae71b4c5e)

### Reproduction

```python3
#flow structure pseudo code below

@flow()
async def child_flow(i):
    # do something


@flow()
async def parent_flow():

    async with asyncio.TaskGroup() as tg:
        for i in range(5):
            tg.create_task(child_flow(i))
```

### Error

```python3
Flow status is "Crashed" when it should be "Running"
```

### Versions

```Text
Version:             2.13.7
API version:         0.8.4
Python version:      3.11.5
Git commit:          70f2d40d
Built:               Fri, Oct 13, 2023 8:20 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment]
Hi @carlosjourdan, thanks for the issue! How are you deploying this flow? Are you using the `serve` method? `serve` on its own doesn't incorporate work pools and workers. You can read more about that in [this section](https://docs.prefect.io/2.13.8/concepts/deployments/#two-approaches-to-deployments) of the docs. If you are using that method, you might want to try out the `deploy` method that was just released in 2.13.8 that will allow you to specify a work pool to deploy to. 

Example and details in our release notes here:
https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#introducing-flowdeploy

Are you able to replicate the issue locally?

Alternatively, if you aren't using the `serve` method, can you tell me more about your setup?

Thanks!

**Comment by carlosjourdan** [comment]
Hi Serina.

I'm actually using the rest api to create flow runs for an existing
deployment using PrefectApiClient's create_flow_run_from_deployment method.

I have a container running on kubernetes fetching the runs from the
workpool. Flows code is served from an azure storage block, and executed
using a k8s job infrastructure block.

Replicating this locally isn't trivial because I don't have direct access
to kubernetes credentials, all the infrastructure is created as code, and
deployments/flows are created as part of an azure devops pipeline.

Best regards,
Carlos Jourdan

**Comment by zzstoatzz** [comment]
hi @carlosjourdan - can you share about how long these flow runs you're talking about are?
> During some long runs

There have been issues in the past related to 
> All connections to the kubelet server have a maximum duration of 4 hours
so I'm curious if this may be related

**Comment by carlosjourdan** [comment]
Hi @zzstoatzz 

Some flows can take longer than 4 hours, due to exponential backoff policy settings. But this "false crashed" state tends to appear after only a few minutes of running...
