### ISSUE TITLE
Add a default work pool option to the prefect.yaml

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#11002]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently if I create multiple deployments in my prefect.yaml file, I need to specify the work_pool for every deployment. 

### Describe the proposed behavior

 It would be great to be able to set a default work_pool at the top of the yaml file, in a similar way to how we can currently set default pull, push and build steps.  

### Example Use

I run `prefect deploy --all` and instead of having to set a work pool for every deployment or choose a work pool using the wizard, I can set a default (probably at the top of the yaml) that is used for all of my deployments. 

### Additional context

Requested in the community slack: https://prefect-community.slack.com/archives/CL09KU1K7/p1697878054091829

**Comment by yaronlevi** [comment]
Just to illustrate the repetition better:

![image](https://github.com/PrefectHQ/prefect/assets/5398977/490ab23c-2522-415b-b131-35499603ee7b)

I also want to add that we can make that feature broader, and enable us to define any "default to any "path" in the yaml, not just the work pool.
