### ISSUE TITLE
Agent does not pick up late flow runs with "--pool" argument

### ISSUE THREAD

**Issue by LeeMendelowitz** [PrefectHQ/prefect#11003]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I explicitly provide the work pool name to our agent, it doesn't pick up any of the late flow runs:

```
prefect agent start --hide-welcome -q default -p default-agent-pool

18:08:21.514 | DEBUG   | prefect.profiles - Using profile 'default'
18:08:22.318 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/xxx
18:08:22.318 | DEBUG   | prefect.agent - Checking for scheduled flow runs...
18:08:22.319 | DEBUG   | prefect.agent - Checking for cancelled flow runs...
18:08:35.029 | DEBUG   | prefect.agent - Checking for scheduled flow runs...
18:08:47.521 | DEBUG   | prefect.agent - Checking for scheduled flow runs...
18:08:57.615 | DEBUG   | prefect.agent - Checking for cancelled flow runs...
18:09:03.775 | DEBUG   | prefect.agent - Checking for scheduled flow runs...
^CReceived SIGINT. Sending SIGINT to the Prefect agent (PID 1284374)...
Agent stopped!
```

If I remove the `-p` argument, and restart then the agent picks up late flow runs as expected:

```
prefect agent start --hide-welcome -q default
18:09:26.074 | DEBUG   | prefect.profiles - Using profile 'default'
18:09:26.884 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/xxx
18:09:26.885 | DEBUG   | prefect.agent - Checking for scheduled flow runs...
18:09:26.886 | DEBUG   | prefect.agent - Checking for cancelled flow runs...
18:09:27.560 | INFO    | prefect.agent - Submitting flow run 'f75a5a82-7608-4da9-af2f-8fe3055bb5a9'
18:09:27.560 | INFO    | prefect.agent - Submitting flow run '9b8cb08a-6200-4f9d-a33d-6cb41b62dc3b'
18:09:27.561 | INFO    | prefect.agent - Submitting flow run 'fc75b14b-fa85-4f99-b593-4590659414ce'
18:09:27.561 | INFO    | prefect.agent - Submitting flow run '4112585b-ab40-444a-959b-aa39b3ecaeb5'
18:09:27.561 | INFO    | prefect.agent - Submitting flow run 'bdd89e8e-9ce1-4683-92f0-94005f4c9ea2'
18:09:27.562 | INFO    | prefect.agent - Submitting flow run '18b1ecf7-27c4-434f-837f-47e8c6e05541'
18:09:27.562 | INFO    | prefect.agent - Submitting flow run 'a28eb10c-24a0-43e8-a5f0-447e964fc7b0'
18:09:27.562 | INFO    | prefect.agent - Submitting flow run 'b6c4c2f1-8a2b-493b-971d-6c439616ee56'
18:09:27.562 | INFO    | prefect.agent - Submitting flow run 'e83a5791-2707-4b2c-9e8c-af5a5e60ee50'
```

I ran into this issue while trying to find a workaround to https://github.com/PrefectHQ/prefect/issues/10771

Some additional details with our configuration that may help investigate:

The "default-agent-pool" work pool has concurrency 25. There are several work queues within the "default-agent-pool" work pool:

- "default" work queue is within "default-agent-pool" and has unlimited concurrency and priority 2
- Another work queue exists with unlimited concurrency and priority 1
- Additional work queues exist with limited concurrency,

### Reproduction

Cannot reproduce with a local prefect server, but observe this repeatedly with Prefect Cloud server.

### Versions

```Text
Version:             2.13.8
API version:         0.8.4
Python version:      3.10.12
Git commit:          1331bb3b
Built:               Thu, Oct 19, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by LeeMendelowitz** [comment]
I am not able to produce this behavior when running a `prefect server` locally, but I can reproduce it with our Prefect cloud server.

**Comment by jakekaplan** [comment]
Hi @LeeMendelowitz thanks for filing this issue! I looked up the flow run ids you provided and I believe this has to do with the concurrency limit you have set on the work pool. The work pool you provided has a concurrency limit of 25. 

Taking a look at your workspace it seems that you have ~80ish flow runs in a `PENDING` state. Any runs in a `RUNNING`, `PENDING` or `CANCELLING` state will count against your concurrency limit. If you remove the `PENDING` runs or change your concurrency limit (say dropping it) I would expect you to see the runs be picked up.

**Comment by jakekaplan** [comment]
Going to close this for now but please feel free to comment or open another issue if the above does not seem to be case!

**Comment by LeeMendelowitz** [comment]
@jakekaplan I am not following this explanation. Are you saying that the work pool concurrency is only respected when the pool argument is provided to the prefect agent? Why would withholding the the pool argument ignore the work pool concurrency when the work queue is within that same work pool?

**Comment by LeeMendelowitz** [comment]
Thanks for pointing out the PENDING flow runs, I was not aware those were there. Those have been in the PENDING state for 2 or 3 months somehow - I can go ahead and delete them manually because clearly they ended up in a weird state.

**Comment by LeeMendelowitz** [comment]
I deleted the PENDING flow runs, added the `--pool` argument to the agent, and the agent picked up the flow runs again. Thanks for the help!
