### ISSUE TITLE
Deleted notification blocks still in GUI

### ISSUE THREAD

**Issue by brks-rssll** [PrefectHQ/prefect#11032]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I made and saved some custom notification blocks. They showed up in the Notifications GUI page which is good.
But if I delete those blocks they still show up on the Notifications page.

Is this a bug or is it expected?

### Reproduction

```python3
No code as you can recreate this from the GUI
```

### Error

```python3
No error message. Just still can see the old deleted notification blocks
```

### Versions

```Text
2.13.8
```

### Additional context

It has been like this for at least six months

**Comment by jakekaplan** [comment]
Hi @brks-rssll thanks for filing this issue! Would be able to be provide any more information here?
- An MRE of your notification block
- How you are deleting the block
- Any screenshots
- The full output of the `prefect version` command

**Comment by brks-rssll** [comment]
I cannot share any code and (probably) screenshots, unless I go through several steps of company policy...

I deleted the blocks using the Prefect web gui.

I am using the same Postgres DB for some months and hence many versions/releases of Prefect. My working theory is that if I were to wipe that DB that the notification blocks might also go away. The DB is the only thing that has persisted inside of our kubernetes namespace.

I'm on Prefect version 2.13.8.  But really I've noticed this for some months and hence many releases now.

Maybe I'm the only one?

**Comment by jakekaplan** [comment]
Are you able to remove your `memo_store.toml` and reboot your server? Normally it would kept in somewhere like `~/.prefect/memo_store.toml`. If the blocks are not present in the database, that is the only other place that might have a reference to them.
