### ISSUE TITLE
`truncated_to` fails to limit the length of the string to the specified value

### ISSUE THREAD

**Issue by breid1313** [PrefectHQ/prefect#11045]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In `truncated_to`, there is logic that removes the middle of the string, shortening it to the desired value by retaining only the beginning and end of the string. However, the function then adds some helper text back into the middle of the string to indicate to users how many characters were omitted. The string then exceeds the desired length and the function returns the original string.

The result is that no truncation is actually being performed by this function when the desired value is less than the length of the string.

### Reproduction

```python3
In [1] from prefect.utilities.text import truncated_to

In [2] original_str = 'b' * 50

In [3] new_str = truncated_to(25, original_str)

In [4] new_str == original_str
Out [4] True
```

### Versions

```Text
Version:             0+untagged.14891.g1998adf
API version:         0.8.4
Python version:      3.10.10
Git commit:          1998adfd
Built:               Fri, Aug 4, 2023 1:14 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.5
```

**Comment by breid1313** [comment]
I will push a fix for this shortly, along with tests.

**Comment by jakekaplan** [comment]
Hi @breid1313 thanks for filing this issue and the subsequent contribution to fix! Looking forward to seeing it merged soon 🙌

**Comment by serinamarie** [comment]
I have reopened the associated PR

**Comment by breid1313** [comment]
@serinamarie & @jakekaplan I'm no longer using prefect during my day-to-day, so it's going to be a challenge for me to do anything further here. If either of you have the time, feel free to make modifications to my branch or start fresh with the suggestions in the PR. check out #11046 if you havent already
