### ISSUE TITLE
Keep server deployment property if deployment already exists and property is omitted from `prefect deploy`

### ISSUE THREAD

**Issue by ccueto36** [PrefectHQ/prefect#11042]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Right now, if you have a deployment definition stored in `prefect.yaml` that does not contain values for properties such as `schedule`, a null (empty) schedule gets pushed to the server, overriding any schedule that was set up in the UI for that deployment previously. 

### Describe the proposed behavior

If a property is omitted from the deployment definition, such as `schedule`, it should assume that it keeps whatever is on the server currently if the deployment already exists. It should not override a schedule that was set through the UI with an empty (null) schedule. This behavior should also apply for any other property, such as `description`, or `tags`.

### Example Use

```
- name: My-First-Deployment
  version: null
  tags:
  - finance
  description: Generates multiple CSVs for the finance department
  entrypoint: flows\Finance\my_csv_generator.py.py:generate_csvs
```

In the above example of a deployment definition in `prefect.yaml`, if `My-First-Deployment` deployment already exists in the server, and you run `prefect deploy -n My-First-Deployment`, the CLI asks: 

`? Would you like to configure a schedule for this deployment? [y/n] (y): `

It should not ask this, since you purposely did not include a `schedule`, because it was already set through the UI. If you select `n` as a response, it creates an empty schedule property ( `schedule: ` ) and whatever schedule was in the server gets overriden with no schedule at all. 

### Additional context

I assume this behavior should also apply to the normal parameters you pass to `prefect deploy` via the CLI, not just the ones set in `prefect.yaml`.

**Comment by WillRaphaelson** [comment]
Hey @ccueto36 thanks for the issue. We've had it this way before and folks got even more confused about "source of truth". The direction we've come to endorse is to not guess intention here and take everything as explicit instructions. For the time being we will not take this up but if we decide to change we will communicate on this issue, and thanks again for filing.
