### ISSUE TITLE
PREFECT_API_KEY exposed when using service account with google cloud run - push workpool

### ISSUE THREAD

**Issue by EldhoKSuresh** [PrefectHQ/prefect#11040]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

With Google Cloud run- push work pool using service account, the PREFECT_API_KEY variable needs to be passed as an environment variable and is exposed as plain text in google cloud run job configuration.
This is a security concern.

Tested the same approach using private prefect account and google cloud run-push workpool, didn't have to pass PREFECT_API_KEY and flow worked. Google cloud run job configuration has PREFECT_API_KEY environment variable which may be a JWT token.
When moved to enterprise prefect account, this didn't work out. And needed to pass in PREFECT_API_KEY as env variable through deployment yaml/workpool config,which gets exposed in cloud run job configuration as plain text.

If we do not pass in PREFECT_API_KEY we get the below error
> raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '403 Forbidden' for url 'https://api.prefect.cloud/api/accounts/xxxxxxx/workspaces/xxxxxxx/flow_runs/74275246-6328-464f-882f-925a6eb63406'

> Response: {'detail': {'reauth_needed': '7c41debb-fb39-4e40-97c0-846f9f1b9e93'}}

### Reproduction

```python3
snippet of deployment yaml below

deployments:
- name: dv-fetch
  version:
  tags: []
  description:
  entrypoint: flow.py:dv_fetch
  parameters: {}
  work_pool:
    name: gcr-dv
    work_queue_name:
    job_variables:
      image: '{{ build-image.image }}'
      env:
        PREFECT_API_KEY: xxxxxx
      service_account_name: yyyy@xxxx.iam.gserviceaccount.com
  schedule:
  build:
  - prefect_docker.deployments.steps.build_docker_image:
      requires: prefect-docker>=0.3.1
      id: build-image
      dockerfile: Dockerfile
      image_name:
        australia-southeast1-docker.pkg.dev/vcdi-np-svc/vcdi-dv/prefect2/dv-fetch
      tag: latest
      platform: amd64
  push:
  - prefect_docker.deployments.steps.push_docker_image:
      requires: prefect-docker>=0.3.1
      image_name: '{{ build-image.image_name }}'
      tag: '{{ build-image.tag }}'
```

### Versions

```Text
2.x
```

**Comment by jakekaplan** [comment]
Hi @EldhoKSuresh thanks for filing this issue! I'm having some trouble understanding the specific issue. You should be able to use a push work pool _without_ providing `PREFECT_API_KEY` in the job_variables at all. That value will be automatically configured for you and you won't need to expose it in your `prefect.yaml`.

**Comment by EldhoKSuresh** [comment]
Hi @jakekaplan - That's our expectations as well. We believe in our case, the prefect api key that gets added back to the GCR job configuration is invalid one. https://github.com/PrefectHQ/prefect-gcp/blob/main/prefect_gcp/cloud_run.py#L736

link to a sample flow run with the issue - https://app.prefect.cloud/account/7c41debb-fb39-4e40-97c0-846f9f1b9e93/workspace/29f44b59-004a-4e10-bc12-980faa3ae45d/flow-runs/flow-run/77738bf5-a1e7-4fb3-b526-6da33cb016c2

**Comment by jakekaplan** [comment]
Thanks for that link. Will take a look

**Comment by EldhoKSuresh** [comment]
hi @jakekaplan attaching the gcr logs here 
[gcr-logs-20231102-150740.json](https://github.com/PrefectHQ/prefect/files/13234156/gcr-logs-20231102-150740.json)

Let me know if you need any other info.

**Comment by jakekaplan** [comment]
Hi @EldhoKSuresh thanks for sharing those very helpful. We released a tweak that I think should prevent this from happening again. Please let me know if you're still seeing that error pop up in your push work pool runs.

**Comment by EldhoKSuresh** [comment]
hi @jakekaplan both the above mentioned issues are not there this morning and the tweak to fix PREFECT_API_KEY issue also works. Thanks for your support.
