### ISSUE TITLE
Page reload in 2.14.2 no longer works

### ISSUE THREAD

**Issue by coells** [PrefectHQ/prefect#11059]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

We have self-hosted Prefect and I have just upgraded to 2.14.2

When I open any UI sub-page (flow-run, worker queue, ...), e.g. HOST/flow-runs/flow-run/cd4ea9bb-5063-4f01-bc17-de30afbdffa6 and press reload, browser shows empty page.

It seems like every resource returned from server is just root html page.

I'm attaching network console showing behavior during reload page.
Notice that js (and every other resource) is just plain html of root page.

![Screenshot 2023-10-31 at 8 17 59](https://github.com/PrefectHQ/prefect/assets/10402316/f219307a-d038-4542-a42e-87415bf118d6)

### Reproduction

1. Open flow-run (work-pool, ...) to see the logs
2. Open Network console in browser
3. Reload page

The behavior occurs in Chrome and Firefox.

### Error

See the bug summary.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
root@prod:/home# prefect version
Version:             2.14.2
API version:         0.8.4
Python version:      3.8.18
Git commit:          3efa0219
Built:               Thu, Oct 26, 2023 5:12 PM
OS/Arch:             linux/x86_64
Profile:             prod
Server type:         server
```

**Comment by batuhanfaik** [comment]
Might be related to #10807

**Comment by coells** [comment]
Agree, based on #10807 thread it seems to be the same problem. I'll close this one as duplicate.
