### ISSUE TITLE
Conda recipe missing required dependencies

### ISSUE THREAD

**Issue by dan-blanchard** [PrefectHQ/prefect#11063]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

As noted in https://github.com/conda-forge/prefect-feedstock/issues/262#issuecomment-1787344303, if you run `conda install prefect` and then run `pip check`, you'll see that the current conda recipe dependencies do not match the pip version.

### Reproduction

```
conda create -n prefect prefect
conda activate prefect
pip check
```

### Error

```
prefect 2.14.2 requires ujson, which is not installed.
prefect 2.14.2 has requirement websockets<12.0,>=10.4, but you have websockets 12.0.
```

### Versions

```Text
Version:             2.14.2
API version:         0.8.4
Python version:      3.12.0
Git commit:          3efa0219
Built:               Thu, Oct 26, 2023 5:12 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

### Additional context

I put together a PR to update the dependencies to match what's in the requirements files in this repo https://github.com/conda-forge/prefect-feedstock/pull/267

**Comment by serinamarie** [comment]
Hi @dan-blanchard, thanks for the issue! I'll take a look at your PR very soon :)

**Comment by serinamarie** [comment]
Hi @dan-blanchard, I've merged in the PR. Can you do a `pip check` again to see if we should keep this issue open? :)

**Comment by dan-blanchard** [comment]
Looks like we're all good now!

```
$ pip check
No broken requirements found.
```
