### ISSUE TITLE
Flow run filters not working on prefect-cloud

### ISSUE THREAD

**Issue by davidschrooten** [PrefectHQ/prefect#11061]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When applying filters on the flow runs page nothing happens. Page remains as it was, no filters are applied.

### Reproduction

Just try to toggle any filters, nothing will happen.

### Error

There is no error, nothing happens

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Latest cloud version
```

### Additional context

None

**Comment by znicholasbrown** [comment]
Hi @davidschrooten - thanks for the report, I can confirm this is an issue; we'll look into getting this fixed as soon as possible.

**Comment by zhen0** [comment]
Thanks for flagging @davidschrooten we are looking into this now

**Comment by zhen0** [comment]
As a workaround while we fix the issue you should be able to apply filters and then refresh the page to see your filtered runs
