### ISSUE TITLE
Guide for dealing with big data

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#11071]
Include 

- using `quote` to avoid introspection of large function args in tasks.
- distributed task execution. e.g. you have a large data set and want to run it largely distributed with Dask, Ray, or Spark w/ Databricks?

**Comment by taylor-curran** [comment]
Another option besides quote is to use persisted result.get

https://github.com/PrefectHQ/marvin-recipes/blob/main/examples/flows/prefect_results.py

**Comment by discdiver** [comment]
Request for working with results in S3 bucket from Community Slack [here](https://linen.prefect.io/t/16054234).

**Comment by discdiver** [comment]
Planning mention Dask and Ray for compute. 
Will discuss generally not passing results around and how params require introspection.
