### ISSUE TITLE
Add example of custom trigger for work queue status.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#11088]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Currently in the Automations UI, you can only create a trigger based on work pool status and not work queue status. Since we see work queues as an advanced feature, it might align that those users are advanced enough to become custom event power users. I feel like an example of a custom trigger of work queue status would be interesting.

![image](https://github.com/PrefectHQ/prefect/assets/68969861/c14da807-4c93-4ba6-b2c0-3d1cc6589e1d)

### Describe the proposed change

--- see above

**Comment by WillRaphaelson** [comment]
I think this is best served by two other issues
1) the retrofit of work queue status, including automation preset described [here](https://github.com/PrefectHQ/nebula/issues/5523)
2) the general expansion of custom trigger docs [here](https://github.com/PrefectHQ/prefect/issues/10976)
