### ISSUE TITLE
Prefect deploy should have an option to not set paused deployments to active

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect#11107]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The current behavior when using prefect deploy and prefect.yml is to set schedule to active even if the current deployment has a paused schedule

### Describe the proposed behavior

Schedule should be configurable on the deployment level or through a flag in the cli command

### Example Use

Either `prefect deploy --some_flag` or a boolean field in the prefect yaml to set schedule active or not

### Additional context

Similar issue [here ](https://github.com/PrefectHQ/nebula/issues/5838)
Potentially [related](https://github.com/PrefectHQ/prefect/issues/11042)

**Comment by Bada-S** [comment]
cc: @Sahiler opened this as a public issue. Tagging you since you opened a similar issue

**Comment by serinamarie** [comment]
Hi @Bada-S, this issue sounds like the same one that you referenced. It seems like a reasonable request to me.

**Comment by Bada-S** [comment]
@serinamarie Yes, it is the same issue. I opened this as a public git issue since I've seen it crop up a couple times now and want to give visibility on the issue

**Comment by serinamarie** [comment]
We've added this to the backlog. I think whoever implements this would probably want it to look like:

```bash
prefect deploy -n foo --disable-schedule
```

but I'd defer to @desertaxle on that.

**Comment by Ishankoradia** [comment]
@serinamarie  want to take a shot at this. Can you please assign me this issue ?

**Comment by EnriqueG23** [comment]
Hi @serinamarie I am very keen to help solving the issue in matter. Could you please assign it to me?

**Comment by serinamarie** [comment]
Hi, sorry for the delayed response. @Ishankoradia I'll go ahead and assign you but let me know if you're no longer interested, in which case I'll assign to EnriqueG23.

**Comment by Ishankoradia** [comment]
> Hi, sorry for the delayed response. @Ishankoradia I'll go ahead and assign you but let me know if you're no longer interested, in which case I'll assign to EnriqueG23.

Thanks. I will be working on this over the weekend.

**Comment by Ishankoradia** [comment]
Hey @serinamarie , I think there is a PR for this issue in the works. https://github.com/PrefectHQ/prefect/pull/11353 
Correct me if I got it wrong.

**Comment by serinamarie** [comment]
Closing this as completed 👍
