### ISSUE TITLE
Snowflake Tasks

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1113]
We should have some tasks in the task library that interface with Snowflake using https://docs.snowflake.net/manuals/user-guide/python-connector.html

Opening this issue even thought I am unaware of the _exact_ tasks we want but we can track it here

cc @cicdw

**Comment by akravetz** [comment]
Hi.  We have a use case for this internally.  I'm happy to add the `SnowflakeQuery` and `SnowflakeScript` Tasks in `tasks/database` similar to the SQLite one if there's interest in having it upstream

**Comment by joshmeek** [comment]
@akravetz There is definitely interest! It would be awesome if you would like to contribute to the task library. Let us know if you have any questions along the way!

**Comment by jlowin** [comment]
Yup! We have a few Cloud customers that are working with Snowflake so I'm confident if you get the ball rolling you'll have some help building those tasks out very quickly.

**Comment by akravetz** [comment]
Pull request is open: https://github.com/PrefectHQ/prefect/pull/1343

**Comment by lauralorenz** [comment]
Looks like this is done, closing.
