### ISSUE TITLE
Allow customization of worker bind server addr

### ISSUE THREAD

**Issue by arthur-leclerc** [PrefectHQ/prefect#11158]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When we deploy a worker on Kubernetes, it is possible to activate [livenessProbe](https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/values.yaml#L116-L128), unfortunately, [the server responsible for listening](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/workers/server.py#L42) to requests on the `/health` endpoint only listens to requests coming from `IPV4` addresses because of the hardcoded bind to `0.0.0.0`.

This is problematic in the case of a deployment on an `IPV6` only EKS cluster because we have no way of modifying this default behavior to also allow listening on `IPV6` via customization of this value, therefore the `livenessProbe` fail.

### Describe the proposed behavior

Allow to modify the bind address of the worker's health server with an environment variable named for example `PREFECT_WORKER_SERVER_HOST` as is the case with [PREFECT_SERVER_API_HOST](https://docs.prefect.io/2.14.3/api-ref/prefect/settings/?h=prefect_worker_#prefect.settings.PREFECT_SERVER_API_HOST) or [PREFECT_RUNNER_SERVER_HOST](https://docs.prefect.io/2.14.3/api-ref/prefect/settings/?h=prefect_worker_#prefect.settings.PREFECT_RUNNER_SERVER_HOST).

**Comment by zzstoatzz** [comment]
hi @arthur-leclerc - thanks for the issue!

would something like #11175 be what you're looking for?

cc @desertaxle @cicdw (in case we intentionally configure the webserver this way for a reason)

**Comment by arthur-leclerc** [comment]
Hello, this looks perfect and should do the job. 👍🏻

**Comment by arthur-leclerc** [comment]
Hey, just to let you know that I rolled the change and it's fixed the issue for IPV6 only EKS cluster. Thank you.
