### ISSUE TITLE
ParameterBindError Security Vulnerability - error message logs sensitive credentials passed to task as `args`. Follow up to #10294

### ISSUE THREAD

**Issue by acaruso7** [PrefectHQ/prefect#11168]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

This is a followup to Issue #10294 and PR https://github.com/PrefectHQ/prefect/pull/10264. If an invalid set of arguments are passed to a `task`, which don't match the defined function signature, a `ParameterBindError` throws ([source](https://github.com/PrefectHQ/prefect/blob/610c09908329c28c78ddb472bb55d2fe3af65165/src/prefect/exceptions.py#L191-L209)). The accompanying error message includes the full set of `args`, as well as the keys for the provided `kwargs` (previously the message included the `kwargs` keys AND values, but this was updated in https://github.com/PrefectHQ/prefect/pull/10264)

If sensitive credentials are passed to a task as plaintext `args` and a `ParameterBindError` throws, these credentials will be logged in a stacktrace

EXAMPLE:

```python
from prefect import task, flow


@task
def my_task(arg1):
    pass


@flow
def my_flow():
    my_sensitive_credentials = {"username": "<username>", "password": "<password>"}
    another_arg = None

    # force ParameterBindError -- we know this task only takes one arg, but we 'accidentally' pass a second here
    my_task(my_sensitive_credentials, another_arg)


if __name__ == "__main__":
    my_flow()
```

Upon running the above example, the following error will throw and expose the sensitive credentials:

```
prefect.exceptions.ParameterBindError: Error binding parameters for function 'my_task': too many positional arguments.
Function 'my_task' has signature 'arg1' but received args: ({'username': '<username>', 'password': '<password>'}, None) and kwargs: [].
```

### Describe the proposed behavior

If a `ParameterBindError` throws for a task invocation that uses regular `args` (not `kwargs`), only the NUMBER of call args passed to the task are logged in the error message, not the actual args themselves

Desired error message for above example:

```
prefect.exceptions.ParameterBindError: Error binding parameters for function 'my_task': too many positional arguments.
Function 'my_task' has signature 'arg1' but received 2 args and kwargs: [].
```

**Comment by bunchesofdonald** [comment]
This was fixed by https://github.com/PrefectHQ/prefect/pull/10264
