### ISSUE TITLE
Labels not being applied to jobs on a kubernetes work-pool

### ISSUE THREAD

**Issue by carlosjourdan** [PrefectHQ/prefect#11172]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm trying to use a kubernets work pool to run flows in an environment that uses Azure Workload Identity. For this to work, every container created must have a "azure.workload.identity/use=true" label in the k8s cluster.

I have tried to create a work pool with the ui and set the "labels" form item as the screenshot below indicates:

![image](https://github.com/PrefectHQ/prefect/assets/17554676/53043ad8-f137-4c9e-9411-123d9a348751)

However, when the jobs are created the labels are not applied. This is a snippet from the output of a "kubectl describe pod" command:

![image](https://github.com/PrefectHQ/prefect/assets/17554676/268f2d4c-48dd-4b48-8189-634c3e82a02c)

I have also tried using the "advanced" tab for editing the job manifest directly, but the result is the same.

![image](https://github.com/PrefectHQ/prefect/assets/17554676/9b7b9fdd-d68e-41d2-84e9-1847ff0611e9)

For information, the azure workload identity is working on this cluster for a setup based on agents/infrastructure blocks, by adding the following customization to the k8s infrastructure block:

[{"op":"add","path":"/spec/template/metadata","value":{"labels":{"azure.workload.identity/use":"true"}}}]

You can see the desired label on the "kubectl describe pod" command.

![image](https://github.com/PrefectHQ/prefect/assets/17554676/97276264-bbb3-4ded-875f-9638ba136d84)

### Reproduction

```python3
Create a kubernetes work-pool through the UI, set the labels form, and run a pod on k8s with the command "prefect worker start -p pool-name --type kubernetes". Jobs scheduled on this pool through deployments do not have the expected label.
```

### Versions

```Text
Version:             2.14.2
API version:         0.8.4
Python version:      3.11.5
Git commit:          3efa0219
Built:               Thu, Oct 26, 2023 5:12 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
hi @carlosjourdan - thank you for the issue! we will look into this as soon as possible.

**Comment by kevingrismore** [comment]
I don't have an Azure Kubernetes cluster set up right now, but I was not able to reproduce this on Google Kubernetes Engine with a worker on Prefect version `2.13.5`.

**Comment by kevingrismore** [comment]
Actually, after looking at this more closely, the [Azure Workload Identity docs](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html) specify that the `{"azure.workload.identity/use": "true"}` label needs to be on the _Pod_, but the Labels field on a work pool configuration apply to the _Job_. That's why they don't appear when running `kubectl describe pod`.

**Comment by kevingrismore** [comment]
@carlosjourdan Give something like this in your work pool config a shot, where the `metadata` with your labels is inside the `template` part of the job manifest. That should apply the labels to the Pod, which it seems like is where Azure is looking.

```
"job_configuration": {
    "env": "{{ env }}",
    "name": "{{ name }}",
    "labels": "{{ labels }}",
    "command": "{{ command }}",
    "namespace": "{{ namespace }}",
    "job_manifest": {
      "kind": "Job",
      "spec": {
        "template": {
          "spec": {
            "containers": [
              {
                "env": "{{ env }}",
                "args": "{{ command }}",
                "name": "prefect-job",
                "image": "{{ image }}",
                "imagePullPolicy": "{{ image_pull_policy }}"
              }
            ],
            "completions": 1,
            "parallelism": 1,
            "restartPolicy": "Never",
            "serviceAccountName": "{{ service_account_name }}"
          },
          "metadata": {
            "labels": {
              "azure.workload.identity/use": "true"
            }
          }
        },
        "backoffLimit": 0,
        "ttlSecondsAfterFinished": "{{ finished_job_ttl }}"
      },
      "metadata": {
        "labels": "{{ labels }}",
        "namespace": "{{ namespace }}",
        "generateName": "{{ name }}-"
      },
      "apiVersion": "batch/v1"
    },
    "stream_output": "{{ stream_output }}",
    "cluster_config": "{{ cluster_config }}",
    "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
    "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}"
  }
```

**Comment by carlosjourdan** [comment]
Hi @kevingrismore, it worked, thanks for the help. I shoud've triple checked the path on the json, it was exactly the same one that I had on the configurations item for the infrastructure block before.

However, I really do think that you should consider adjusting either the ui or the default job manifest. It is very confusing that the "Environment Variables" form entry gets applied to the job level, whereas the "Labels" one doesn't. For me this still seems like a bug, in the sense that things are not working as you would expect based on the documentation.

In fact, for me it doesn't even make sense to manage anything other than the kubernetes jobs that will be created for flow runs through this templating. The long running pod that runs the worker has to be managed from the outset, before connecting to prefect cloud and actually having access to these configurations. Or am I missing something?

Cheers

**Comment by kevingrismore** [comment]
@carlosjourdan When we're talking about pods, there are typically two categories in the context of Prefect:

- pods managed under a kubernetes deployment, kept alive perpetually, such as a worker pod
- pods managed under a kubernetes job, which run to completion, such as flow run pods
 
The `template` field inside the job manifest is where the pod managed by the job is defined. That means a flow run creates a job, and that job is responsible for ensuring the successful creation, termination, and cleanup of the pod defined by the `template`.

Where this can get messy, and where I got caught up when looking at this too, is that all these different types of entities can have their own metadata - deployments, jobs, and pods can all have labels. Azure is specifically looking for pod metadata. There are numerous valid fields that aren't included in the job manifest in the work pool by default, but I agree it's probably a good idea to call out which entity's labels you're editing in the UI when using that default template.

**Comment by carlosjourdan** [comment]
@kevingrismore, I get the difference between the two types of pods. But in my understanding, the "perpetual" worker pod has nothing to do with the base job template defined in the workpool. It has to be created from the outset so that the "prefect worker start" command can run and only then will it fetch the template from prefect to create the flow run pods. At least that's how my environment is set up - I'm actually curious if there are other recommended architectures...

The description of the "Labels" field in the UI is "Labels applied to infrastructure created by a worker", so I would expect them to be applied to the flow run pods by default, without any special adjustments to the default template. If not on the flow run pods, where would they be applied?

Anyways, thanks for the help, we can now move forward with our migragtion. But I do believe that you guys should think about adjusting this behaviour, or making it more explicit on the UI, in benefit of future users.

Cheers
