### ISSUE TITLE
client.wait_for_flow_run function proposal

### ISSUE THREAD

**Issue by Fizzizist** [PrefectHQ/prefect#11177]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

- I can use `prefect.deployments.run_deployment` to create a flow run and wait for it to finish, and get the results.
- I cannot (afaik) get a flow run from `client.create_flow_run_from_deployment` and then use some another function to later wait for that deployment and get the results

### Describe the proposed behavior

A function that lets me wait for a flow_run to finish and get the results when it is done, just like `prefect.deployments.run_deployment` but with an existing flow_run ID that I instantiated in a separate call.

### Example Use

A REST API where someone tells my API to kick off a prefect flow, i kick it off, and hand them back an ID. My endpoint then starts a background task to wait for the results of that flow to come in so it can write them to it's own database.

### Additional context

I am happy to put this feature in myself. Opening this issue first because IDK if this is a duplicate request or not, or maybe the feature exists and I couldn't find it. I looked through the docs and github issues and I haven't seen this. Thanks

**Comment by billpalombi** [comment]
Thanks for opening this issue @Fizzizist!

As you said, there is presently no such method. Do I understand correctly that you are looking for something like the `wait()` method for task futures, but for flows?

**Comment by Fizzizist** [comment]
@billpalombi I am thinking something that can be done with just the prefect client and a flow run ID. Here is how I've done it in my repo (taking most inspiration from `prefect.deployments.run_deployment`:
```
async def wait_for_flow_run(
    flow_run: FlowRun, timeout: int = 10800, poll_interval: int = 5
) -> None:
    """Waits for the prefect flow to finish and return the results. If anything fails, an error is logged.

    Parameters
    ----------
    flow_run : FlowRun
        The flow run.
    timeout : int, optional
        The timeout in seconds, by default 10800 (3 hours).
    poll_interval : int, optional
        The poll interval in seconds, by default 5.
    """
    flow_running = True
    async with get_client() as client:
        with anyio.move_on_after(timeout):
            while flow_running:
                flow_run = await client.read_flow_run(flow_run.id)
                flow_state = flow_run.state
                if flow_state and flow_state.is_final():
                    flow_running = False
                await anyio.sleep(poll_interval)

    if flow_state is None or flow_state.type != StateType.COMPLETED:
        slogger.error(
            "flow run did not succeed.",
            flow_run_id=flow_run.id,
            state=flow_state.type if flow_state is not None else None,
            output=flow_run.json(),
        )
        return

    return await flow_state.result().get()
```

**Comment by Fizzizist** [comment]
awesome. I'll put a PR together
