### ISSUE TITLE
`definititions.work_pools.work_pool.work_pool_name` in `prefect.yaml` defined as an env var variable does not read from env vars

### ISSUE THREAD

**Issue by nzojy** [PrefectHQ/prefect#11189]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Defining work pool name in the `definitions` section as an env var variable does not work. Instead of reading env vars, it reads the variable as a string.

### Reproduction

```python3
`prefect --no-prompt deploy --all`



name: my_project
prefect-version: 2.14.3

pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /app

definitions:
  work_pools:
    work_pool: &work_pool
      name: "{{ $WORK_POOL_NAME }}" # fails to be read
      job_variables:
        image: "{{ $REGISTRY }}/{{ $IMAGE_NAME }}:{{ $TAG }}" # these read just fine

deployments:
  - name: my_flow
    entrypoint: /test_flow.py:my_flow
    work_pool: *work_pool
```

### Error

```python3
This deployment configuration references work pool '{{ $WORK_POOL_NAME }}' which does not exist. This
means no worker will be able to pick up its runs. You can create a work pool in the Prefect UI.
```

### Versions

```Text
2.14.3
```

### Additional context

This same issue seemed to have been raised before: https://github.com/PrefectHQ/prefect/issues/10751#issuecomment-1801757475

**Comment by serinamarie** [comment]
Hi @nzojy, thanks for making your first issue in Prefect! This is probably a bug, and we've added it to our backlog to fix :)

**Comment by nzojy** [comment]
amazing @serinamarie, thank you!

**Comment by serinamarie** [comment]
Update: I'll be working on this this week

**Comment by nzojy** [comment]
amazing, thank you!
