### ISSUE TITLE
Display API Version More Prominently in Docs

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1119]
I searched `Docker` in the docs and it brought me to a page from the `0.5.0` api reference without telling me that those were older docs. Would be nice if the API version was displayed at either the top or next to the search results

![image](https://user-images.githubusercontent.com/40716964/59105762-ab656680-8902-11e9-9c65-7a1feb4c19a8.png)

**Comment by itsngansense** [comment]
![Screen Shot 2019-07-19 at 1 50 12 PM](https://user-images.githubusercontent.com/1928148/61567322-1e5b1480-aa4d-11e9-805c-3029cb250db3.png)

in addition to josh's note, when you're using search, the results are hard to distinguish. each of the results listed are for various versions of prefect but a user has no idea which one they're clicking into and are further confused by not getting any sort of confirmation on the page they clicked other than looking at the URL to see which version of the docs they're reading. we should think about including the version number as a badge / callout or label next to the search result...

or... depending which version the user chooses from the dropdown menu, the search results should be scoped to that version.

**Comment by dylanbhughes** [comment]
We should consider using a new search index entirely. Let's look at something like https://vuepress.vuejs.org/default-theme-config/#algolia-search.

**Comment by lauralorenz** [comment]
Still think this issue could be picked up, the work would be to add the API version in a badge somewhere more prominently while browsing a given API page.
