### ISSUE TITLE
Hello world example in core tutorial is slightly broken (Flow is missing a name)

### ISSUE THREAD

**Issue by maxalbert** [PrefectHQ/prefect#1120]
Not sure if this is the right place to report this, but on the [Core Tutorial](https://www.prefect.io/core-tutorial) page, the "Hello world" example is slightly broken.

It lists the following snippet:
```python
with Flow() as flow:
    say_hello()
```
However, this raises `TypeError: __init__() missing 1 required positional argument: 'name'`. Easily fixed of course by passing a `name` argument to the Flow.

**Comment by cicdw** [comment]
Definitely the right place - thanks @maxalbert ! I'll PR a fix shortly.

**Comment by jlowin** [comment]
😅 Thanks @maxalbert! Got overlooked as we ready some new stuff. Fixed now!
