### ISSUE TITLE
Add `concurrency` to `prefect-client` package

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/prefect#11202]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, the `concurrency` submodule is removed during the `prefect-client` packaging process so (when using only prefect-client) imports like `from prefect.concurrency.sync import rate_limit` do not work when using the `prefect-client` package.

### Describe the proposed behavior

If possible, the concurrency submodule should be included in the `prefect-client` package.

### Example Use

`from prefect.concurrency.sync import rate_limit` when only prefect-client is installed.

**Comment by serinamarie** [comment]
Hi @majikman111, thanks for the issue! @urimandujano might have thoughts on that
