### ISSUE TITLE
Unable to save work pool config after removing json from any `object` field with an existing value

### ISSUE THREAD

**Issue by kevingrismore** [PrefectHQ/prefect#11221]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When editing a work pool with an existing value in an `object` type field, removing all the text from that value causes a 422 error. The `default` value in that field in the json view of the work pool is changed to an empty string.

```json
"labels": {
  "type": "object",
  "title": "Labels",
  "default": "",
  "description": "Labels applied to infrastructure created by a worker.",
  "additionalProperties": {
      "type": "string"
  }
}
```

### Reproduction

1. Go to the edit page for any work pool
2. Add some values for a field that's of type object
3. Save the work pool config
4. Edit the work pool again
5. Delete the values you added in the field
6. Save again

### Error

"Validation failed for field 'labels'. Failure reason: '' is not of type 'object'"

### Browsers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

**Comment by serinamarie** [comment]
Just wanted to clarify for UI that is strictly using the guided/form view of the `base_job_template`, not the Advanced tab. The issue can be reproduced by saving valid json in the Labels field, then removing it and attempting to save.
