### ISSUE TITLE
Allow Automations to change states of Flow Runs

### ISSUE THREAD

**Issue by rphamle** [PrefectHQ/prefect#11285]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Automations are currently able to cancel Flow Runs based on a set of triggers (i.e. put their state into `Canceled`). However:
- Automations are not able to change the states of those canceled Flow Runs (e.g. to `Completed` or `Failed`).
- We cannot change the default state message (`Canceled by Automation <automation id>`) when this Automation cancels a Flow Run

### Describe the proposed behavior

When configuring an Automation to cancel Flow Runs, I'd like to also:
- have the Automation change the states of those canceled Flow Runs to some other state (e.g. `Completed`, `Failed`)
- customize the state message for when Automations cancel Flow Runs

These features would be useful for the robustness of these Automations - for example, it can be difficult to tell whether a flow run was canceled because the Automation canceled it due to some trigger, or canceled because someone manually canceled it.

### Example Use

I want an Automation to cancel all flow runs that are stuck in pending for longer than 10 minutes (which is already supported).

But in addition to canceling, I’d like the Automation to also:
- change that canceled flow run to `Failed`
- use my own custom state message, e.g. `Canceled by Automation <automation id>  due to being stuck in Pending for over 10 minutes. Marking as Failed.`

### Additional context

See [thread](https://sq-block.slack.com/archives/C0284UFFUDU/p1701275674382389).

**Comment by WillRaphaelson** [comment]
Thanks. Notes to implementers

- This action can only ever act on an inferred flow run, since these are created at runtime. The UI should reflect that.
- This will be something of a footgun, in that users will likely propose invalid transitions, this is fine, as long as we log it in the automation action failed event.
- Ideally, we'd remove the cancel flow run automation action and edit them to use the change state action with a state of cancelled.

**Comment by serinamarie** [comment]
If I'm understanding correctly, users would then be able to create an automation like: 
Trigger: `Flow Run State` (Cancelled, Crashed)
Actions: `Change flow run state` (AwaitingRetry)

after this is implemented.

**Comment by WillRaphaelson** [comment]
Yes that's correct, I'll close the retry issue in favor of this one and accept. Thanks.

**Comment by rphamle** [comment]
Thanks @bunchesofdonald ! That caveat is fine to me.

I did some testing with this new Automation, and am seeing a weird issue. Details below:
- I set up the Automation to change Flow Runs from Pending to Failed if they remain in Pending for longer than 30 seconds (just as a contrived test, as 30 seconds is the lowest I can set it to)
- tThe Automation successfully changed my Flow Run from Pending to Failed, and I can see my custom Automation message  in the `State Message` as well. As expected, the Flow Run remained in Pending longer than 30 seconds just because of the time that it takes for the underlying infra (Vertex) to start up.
- However, the Flow Run would then change from Failed to Running and then Success. The Automation's message would then disappear from the `State Message`. 
- This doesn't seem like a "retry" to me. Even if it was, would retries be expected if the Automation changed the state to Failed?

**Comment by bunchesofdonald** [comment]
> This doesn't seem like a Flow retry to me. Even if it was, would retries be expected if the Automation changed the state to Failed?

I agree, that doesn't sound like a flow retry, and nothing about the automation should cause it to be retried. Can you tell me more about how you set up the test so I can try to reproduce?

**Comment by rphamle** [comment]
@bunchesofdonald Sure thing:
- the Flow just prints "hello world"
- the Flow is run on Vertex infrastructure, on an `n2-standard-4` node
- the Flow is manually triggered
- the Automation's trigger is for all Flow Runs that stay in `Pending` for longer than 30 seconds
- the Automation's action is to change the Flow Run's state to `Failed`
- the Automation's state message is `Failed by Automation due to being stuck in Pending for over 10 min`
