### ISSUE TITLE
Allow Creation of Prefect Variables through the Python SDK

### ISSUE THREAD

**Issue by biancaines** [PrefectHQ/prefect#11286]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In order to create and save new variables, users need to do so using the CLI, UI, or REST API ([see documentation here](https://docs.prefect.io/2.14.8/guides/variables/?h=variab#managing-variables)). 

### Describe the proposed behavior

For teams that make heavy use of this feature, having the ability to create and save variables via the python SDK could be a more convenient option. 

### Example Use

Blocks can be created/saved/deleted via the python SDK. Variables could be handled in a similar fashion.

Example of variable creation/saving:
```
from prefect import variables

my_variable = variables(42)
my_variable.save(name="the_answer")
answer = variables.get("the_answer")
print(answer)
#42
```

Example of variable deletion:

```
from prefect import variables

variables.delete("the_answer")
```

### Additional context

All the current limitations of variables would still apply:

>- Have no more than 255 characters.
>- Only contain lowercase alphanumeric characters ([a-z], [0-9]) or underscores (_). Spaces are not allowed.
>- be unique.

For storing larger values, blocks should be used in lieu of variables.

**Comment by discdiver** [comment]
This is now possible: https://github.com/PrefectHQ/prefect/blob/1ef79ce46de354c2c8c03c3c6d6c5991a77bdb4c/src/prefect/variables.py#L26
