### ISSUE TITLE
Ability to add dynamic jinja templating to Automation action form field 

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#11321]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

You have to use JSON for dynamic values in automation **Run a deployment** actions, but then the templated values appear in the form field once the action is created and can be edited.

It would be a nicer UX for automation creation to be able to use jinja templating when creating the automation.

### Describe the proposed behavior

Allow jinja templating in the form field.

### Example Use

See screenshot of editing an existing action:
![Screenshot 2023-12-04 at 5 54 52 PM](https://github.com/PrefectHQ/prefect/assets/7703961/852d10f0-92fb-453a-80e6-225fca0c4f0d)

From the edit screen, you can add a new **Run a deployment**  action that allows the jinja syntax.

**Comment by WillRaphaelson** [comment]
hey @discdiver, what type is the issue number? if its a text field you should be able to just type jinja syntax into it. i have some other thoughts too maybe lets take a look at this sync?

**Comment by discdiver** [comment]
Yeah, string text. Sounds good re: sync. Will send an invite.
