### ISSUE TITLE
Broken Notifications Docs link

### ISSUE THREAD

**Issue by digitalghost-dev** [PrefectHQ/prefect#11361]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When in the UI and in the Notifications section, clicking on the link to the docs is broken. `404 Page Not Found`.

### Reproduction

Use Prefect 2.14.9, load the UI with `prefect server start`, click in the notifications section, and then click on the docs link.

### Error

`404 Page Not Found`

### Browsers

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.14.9
```

**Comment by zzstoatzz** [comment]
hi @digitalghost-dev - thanks for the issue. it would be helpful if you could share where in the docs you've encountered broken links

**Comment by digitalghost-dev** [comment]
Thank you!
