### ISSUE TITLE
UI: Add checkbox to Block overview to allow multi-selection/-deletion

### ISSUE THREAD

**Issue by quassy** [PrefectHQ/prefect#11372]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If you want to delete many blocks, you have to click one by one on "..." -> "Delete" -> "Delete" (confirmation).

### Describe the proposed behavior

Add checkboxes to the left of the list entries so multiple entries can be selected easily and deleted at once, with a checkbox in the header row to select all currently displayed entries, just like in the views "Flows" and "Deployments".

### Example Use

Deleting multiple blocks, especially KubernetesJob blocks, which we have in various configurations and quickly get outdated (from feature branches etc).

**Comment by zzstoatzz** [comment]
hi @quassy - thanks for the issue, your request makes a lot of sense! we'll get on this as soon as we can

@zhen0 - would you consider this a duplicate of #7006, or would bulk deletes be distinct for each list page?

**Comment by RayanFar** [comment]
I need it too.

**Comment by zhen0** [comment]
Let's keep this open. #7006 is pretty broad in its scope and this is nicely specific.
