### ISSUE TITLE
Flow run could not be submitted to infrastructure: list index out of range

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#11383]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are using Prefect cloud + ECS Push work pools.
Some flows are at CRASH state with the error:
`Flow run could not be submitted to infrastructure: list index out of range`

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/50328127-8eaa-4705-8962-0f2ed6752506

![CleanShot 2023-12-12 at 11 40 11@2x](https://github.com/PrefectHQ/prefect/assets/5398977/33aae810-0a70-4935-9ec6-e5d53ef5eb58)

### Reproduction

```python3
Happens in Prefect Cloud
```

### Versions

```Text
Prefect Cloud
```

**Comment by jakekaplan** [comment]
Hi @yaronlevi thanks for filing. I think we're masking some error with submission here. Let me investigate and will follow up here
