### ISSUE TITLE
Allow for two API keys per service account

### ISSUE THREAD

**Issue by meggers** [PrefectHQ/prefect#11384]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Right now, it appears there is only one API key per Service Account. When the key is rotated, the old key can no longer be used.

### Describe the proposed behavior

Allow for two keys that can be rotated independently.

### Example Use

This will allow for a seamless key rotation where I can rotate Key 1 while existing consumers are using Key 2, and then I can switch consumers to Key 1, and then rotate Key 2.

### Additional context

This change would be more valuable in conjunction with support for https://github.com/PrefectHQ/prefect/issues/10765

**Comment by WillRaphaelson** [comment]
Thanks @meggers, accepting this onto our backlog

**Comment by dylanbhughes** [comment]
Hey @meggers, looking at potential implementations for this and I like the way Stripe handles their key rotation. Essentially, they let you set a short expiration on the old key while you're creating the new one. Screenshot below:
![Image](https://github.com/PrefectHQ/prefect/assets/2325367/cf6badb4-eba8-4522-9755-17a554332fb8)

I think we'd probably want to enforce a 2-key limit per Service Account to allow for rotation best practices without letting a ton of keys out into the world. What do you think?

**Comment by meggers** [comment]
Hey @dylanbhughes I think a two key limit makes sense. The key expiration makes sense - but don't we already have key expirations? If you just add the option for another key, that would give users the option to manage key lifetime without needing to track another expiration.

**Comment by meggers** [comment]
I could see it! My only point is I think you give users the greatest flexibility and yourself the simplest solution by just allowing two keys and treating them the same
