### ISSUE TITLE
Unnecessary scrollbar in deployment overview

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#11418]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The new deployment overview page layout reduces usability compared to previous releases.
This is because the deployment name column uses a div with fixed with that is just wide enough to display the `Created ...` info but not wide enough for the deployment name including the red or green dot to the right of the name that indicates if the deployment is actively polled.

![image](https://github.com/PrefectHQ/prefect/assets/11021147/f295cd58-71cd-4477-a45f-6a6c2f014b4a)

Having to scroll on each deployment to see the full name and status is very inconvenient, especially if the total width of the table would allow to display of the name column without any scrollbar.

### Reproduction

Create a deployment with a name with more than 30 characers.

### Error

see screenshot

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.14.10
API version:         0.8.4
Python version:      3.8.15
Git commit:          70888afe
Built:               Thu, Dec 7, 2023 7:27 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

### Additional context

Using Prefect Cloud

**Comment by zhen0** [comment]
Thanks @j-tr - https://github.com/PrefectHQ/prefect-ui-library/pull/1944 should address this.
