### ISSUE TITLE
Allow creation and management of global concurrency limits using a prefect client

### ISSUE THREAD

**Issue by Zyntogz** [PrefectHQ/prefect#11416]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, you can only set/delete/modify global concurrency limits via the UI

### Describe the proposed behavior

You can set/delete/modify global concurrency limits using the prefect client object 

### Example Use

During deployment time we plan to set concurrency limits for different use cases based on configuration

### Additional context

This may be the first step before implementing https://github.com/PrefectHQ/prefect/issues/10865

Already proposed a solution in https://github.com/PrefectHQ/prefect/pull/11415

**Comment by serinamarie** [comment]
Hi @Zyntogz, thanks for the issue and for making a corresponding PR! :)
