### ISSUE TITLE
failing subflow from run_deployment doesn't fail parent

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#11435]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I have a parent flow and one of the subflows started through `run_deployment` fails it doesn't fail the parent flow as expected.

### Reproduction

```python3
from prefect.deployments import run_deployment
from prefect import task, flow, serve

@flow
def my_sub_flow(my_int: int = 1):
    print(my_int)
    if my_int == 2:
        raise Exception

@flow
def my_flow():
    my_deploy1 = run_deployment(f"{my_sub_flow.name}/standard", parameters={"my_int":1})
    my_deploy2 = run_deployment(f"{my_sub_flow.name}/standard", parameters={"my_int":2})
    my_deploy3 = run_deployment(f"{my_sub_flow.name}/standard", parameters={"my_int":3})

if __name__ == "__main__":
    serve(
        my_flow.to_deployment("standard"),
        my_sub_flow.to_deployment("standard")
        )
```

### Versions

```Text
Version:             2.14.9
API version:         0.8.4
Python version:      3.8.17
Git commit:          4fba882c
Built:               Thu, Nov 30, 2023 2:55 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment]
Hi @thomasfrederikhoeck, you're basically creating new parent flow runs so there's nothing truly dependent between the two of them in terms of halting the rest of the code from running. If you want to check that the status of the flow run from `run_deployment` is completed, the returned `my_deploy1` is a [flow run object and you can return the id](https://docs.prefect.io/latest/api-ref/prefect/runtime/flow_run/) and other fields from it, using that to check the status of the flow run.

I'm going to close this issue for now as I don't see this as a bug but feel free to reopen.

**Comment by thomasfrederikhoeck** [comment]
@serinamarie Yeah, but given that the flow run is linked as a subflow (I think this is done under the hood by creating a dummy task) I would expect the flow to fail. Also given that the you can se the subflow run failed in the UI. So I don't think this should be closed. 

![image](https://github.com/PrefectHQ/prefect/assets/44194839/04147b6f-57a3-4082-8d98-bf173a6d13e8)

**Comment by thomasfrederikhoeck** [comment]
I don't think I have the rights to re-open :-)

**Comment by thomasfrederikhoeck** [comment]
I also noticed a strange behavior in #11436 where if the the `run_depolyment` happens from a sub flow the parent flow fails but the subflow doesn't ?
