### ISSUE TITLE
Add an Automations action to Retry a flow run

### ISSUE THREAD

**Issue by meggers** [PrefectHQ/prefect#11431]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The Automations actions as described [here](https://docs.prefect.io/latest/concepts/automations/#actions) allow you to take some actions on flow runs such as pause or cancel, and allows you to create a new flow run via "Run a deployment".

### Describe the proposed behavior

Add an action that lets you retry a flow run. This way any tasks with persisted results will not be run again, and external consumers of the flow run do not need a different flow run ID.

### Example Use

An automation for "On Crashed (or pod evicted event), retry the Crashed flow run".

### Additional context

Given https://github.com/PrefectHQ/prefect/issues/10211 where the flow retries don't apply to the Crashed state, Automations seems to be the best alternative. When we submit a flow we have an external process that monitors it. If we were to use the existing "Run a deployment" action for retry, we would not get the task persistence on retry behavior and external monitors would not be aware of the new flow run.

**Comment by serinamarie** [comment]
HI @meggers, thanks for the issue! If we implement #11285 then we would be able to move a flow run to an `AwaitingRetry` state from `Cancelled` or `Crashed`. I think that I would look to that issue to see first movement on this.

**Comment by meggers** [comment]
Hey @serinamarie thanks for linking that! If I can use "Infer flow run" and then set the state of the flow run to AwaitingRetry, that would solve my issue. Apologies this might be a duplicate in that case, I did see that other issue.

**Comment by serinamarie** [comment]
Hi @meggers, I'll close this as a duplicate :)
