### ISSUE TITLE
Configuring through live object does not work

### ISSUE THREAD

**Issue by occoder** [PrefectHQ/prefect#1143]
According to the [guide](https://docs.prefect.io/guide/core_concepts/configuration.html#environment-variables) 
`The configuration file is parsed when Prefect is first imported and is available as a live object in prefect.config. To access any value, simply use dot-notation (for example, prefect.config.tasks.defaults.checkpoint).`
But after putting these lines before the flow.run(),
```
prefect.config.debug = 'True'
prefect.config.logging.level = 'DEBUG'
```
it does not take any effect on the logging message generation. The default INFO logging level persists.

**Comment by jlowin** [comment]
Hi @occoder, the config object is made available for ease of reading the configuration, not writing it. Most configuration steps must take place on import, including logging. If you want to set the logging level, create a custom config at `~/.prefect/config.toml` or set `PREFECT__LOGGING__LEVEL=debug` in your environment.

**Comment by fkaleo** [comment]
Using `prefect.context.config` instead of `prefect.config` seems to work.
See https://github.com/PrefectHQ/prefect/pull/1481
