### ISSUE TITLE
Prefect API "flow_runs/filter-minimal" limit fails sporadically, appears related to when count is less than limit

### ISSUE THREAD

**Issue by cluffja** [PrefectHQ/prefect#11442]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The Prefect API on the flow_runs query fails if the count of flow_runs/filter-minimal in the filter is less than the limit set in the query. For example for this query:
`https://api.prefect.cloud/api/accounts/<account_id>/workspaces/<workspace_id>/flow_runs/filter-minimal`

With this body:
`{
    "offset": 0,
    "limit": 200,
    "flow_runs":{
        "start_time": {
            "after_": "2023-12-14T17:00:00"
        }
    }
}`

### Reproduction

```python3
`https://api.prefect.cloud/api/accounts/<account_id>/workspaces/<workspace_id>/flow_runs/filter-minimal`

With this body:
`{
    "offset": 0,
    "limit": 200,
    "flow_runs":{
        "start_time": {
            "after_": "2023-12-14T17:00:00"
        }
    }
}`

Depending on your account you might have to change the offsets to higher counts to get it to fail.
```

### Error

```python3
exeption_message": "Service Unavailable"
```

### Versions

```Text
0.8.4
```

### Additional context

I tested this yesterday with a time window like the following:
`{
    "offset": 100,
    "flow_runs": {
        "start_time": {
            "after_": "2023-12-12T14:15:22Z"
        }
    },
    "limit":70
}`

But I found that when I ran this today (which should have included more flow_runs) is now failing. SO I'm not convinced that my summation matches perfect. Bottom line - the flow_runs/filter-minimal is either not intuitive or doesn't work.

**Comment by serinamarie** [comment]
Hi @cluffja, thanks for creating your first issue with Prefect! I am not able to replicate the issue you are facing with the following code despite adjusting the offset and limit, and despite having few flow runs.
```python
import requests

PREFECT_API_URL="https://api.prefect.cloud/api/accounts/abc/workspaces/xyz"
PREFECT_API_KEY="pnu_123"
data = {
    "offset": 100,
    "limit": 70,
    "flow_runs": {
        "start_time": {
            "after_": "2023-12-14T17:00:00"
        }
    }
}

headers = {"Authorization": f"Bearer {PREFECT_API_KEY}"}
endpoint = f"{PREFECT_API_URL}/flow_runs/filter-minimal"

response = requests.post(
    endpoint, 
    headers=headers, 
    json=data)
assert response.status_code == 200, f"{response.status_code}"
minimal_flow_run_json = response.json()
for flow_run in flow_run_json:
    print(flow_run)
```

Are you able to replicate the limi issue on other endpoints?

**Comment by cluffja** [comment]
Hi @serinamarie, this issue is really hard to pin down. This morning, very early, I woke up and tried hitting this endpoint. It had no issues. I was able to query with the full limit of 200 and I was able to adjust the offset up to 3000 until the results it gave back to me were the expected empty set "[]". However, now that it's 8:00 MST I tried hitting the exact same query and it fails with "Service unavailable". I have not seen this issue with the "deployments/filter" endpoint that I also use. I haven't tried other endpoints other than that at the moment.

**Comment by cluffja** [comment]
I'm doing some more testing right now. This body works:
```
{
    "offset": 3000,
    "flow_runs": {
        "start_time": {
            "after_": "2023-12-12T00:00:00Z"
        }
    },
    "limit":10
}
```

Changing the limit to 200 results in Service unavailable. But it is sporadic. I just tried hitting it with 10, 20, 50, 100, and eventually 200 as the limit and ALL of them worked. It's not reliable and consistent.

**Comment by cluffja** [comment]
Offset: 0
Limit: 1
It works.

Offset: 1
Limit: 1
It fails.

**Comment by cluffja** [comment]
I don't know what else I can give you. I don't completely understand how you all deploy the endpoint but maybe there is somewhere we can look at additional logs?

**Comment by cluffja** [comment]
I try the same queries 10-20 minutes later and they work.
