### ISSUE TITLE
This flow run is missing infrastructure tracking information and cancellation cannot be guaranteed

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#11447]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect cloud + ECS push work pool

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/63dd478c-da7c-415d-b689-8f84b95c4601?tab=Details

![CleanShot 2023-12-17 at 11 30 30@2x](https://github.com/PrefectHQ/prefect/assets/5398977/899c4300-e88d-435c-bb6c-619ff934aa57)

### Reproduction

```python3
Happens in Prefect cloud.
```

### Versions

```Text
Prefect cloud
```

**Comment by yaronlevi** [comment]
Here is another case:

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/65fb9911-5d36-4eba-b22f-a0935e8993b3?tab=Details

![CleanShot 2023-12-18 at 09 29 25@2x](https://github.com/PrefectHQ/prefect/assets/5398977/23e1b094-c697-41d1-94c3-ceb1ef726209)

**Comment by jakekaplan** [comment]
Hi thanks for filing this issue!

From what I can see both the runs you reported here did something like the following:
```
SCHEDULED	2023-12-17 16:38:24.295012+00
PENDING	2023-12-17 18:39:56.087452+00 <--never finished creating the task run so no ecs task run id was saved
CANCELLING	2023-12-17 18:54:57.226709+00 
CANCELLED	2023-12-17 18:55:04.51634+00 <-- there was no ecs task run id stored to delete
```

Do you see see any evidence of these task runs being created on the AWS side? It seems like the run might have been stuck in `PENDING`.

**Comment by yaronlevi** [comment]
@jakekaplan Quite hard to know since I don't have a history of all tasks, or even try to some how correlate it by id...

**Comment by jakekaplan** [comment]
@yaronlevi Understood. If you happen to see a run stuck in `PENDING` again would you be able to take a look int ECS before cancelling to see any evidence of task run request? I will dig deeper if I can determine why these runs were seemingly stuck in `PENDING

**Comment by jakekaplan** [comment]
@yaronlevi it looks like flow run is not being used for a push pool and is instead part of a `default-agent-pool`.

Flow Run id: `65fb9911-5d36-4eba-b22f-a0935e8993b3` has
Work Queue id: `efccc118-c46b-48e2-8ee5-014d12c04d3d` which belongs to 
Work Pool id: `8b151ada-5c15-447e-a2b5-91550637f11c` (`default-agent-pool`)

You should see anything going on from the agent logs. The cancellation behavior is working as expected when the agent (or push pool for that matter) is not able to finish creating an ECS task run, so it cannot garuntee a reference for deletion.

**Comment by yaronlevi** [comment]
@jakekaplan Ok, let met check this...

**Comment by yaronlevi** [comment]
@jakekaplan @WillRaphaelson I'm seeing again spike of ECS tasks that are just stuck in PENDING.

They are use the same ECS push work pull.

Here is an example of of [stuck run](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/10ab1e06-2db0-479a-a1b4-9b393f209e01) that happened 10 hours:

![CleanShot 2024-07-06 at 17 51 15@2x](https://github.com/PrefectHQ/prefect/assets/5398977/d7a03337-9367-4702-88bd-d6f0be3bd62d)

Also, while this "outage" is happening it's not only that single deployment above that is stuck in PENDING. Many other that have the CRON are also stuck.

For example, the "spike of PENDING stuck" that happened 10 hours ago:

![CleanShot 2024-07-06 at 17 53 54@2x](https://github.com/PrefectHQ/prefect/assets/5398977/aaf39f19-7211-431c-9991-5303970198f9)

The only way to workaround this issue is an automation I've defined that cancels a flow it it stuck in PENDING for more than 15 min, and rerun it:

![CleanShot 2024-07-06 at 17 57 07@2x](https://github.com/PrefectHQ/prefect/assets/5398977/1704e4b5-1039-47a2-8bc3-f5bdd0cf22f1)

This this feels wrong.
Maybe there is a way to make Prefect handle those flaky cases internally?
