### ISSUE TITLE
:memo: feedback on documentation for new comers

### ISSUE THREAD

**Issue by thomasleveil** [PrefectHQ/prefect#11445]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Hi, Prefect has a nice and well written documentation, however it still let me confused regarding the concepts behind "serve", "agent", "worker", ...

### Describe the proposed change

It would help newcomers if the documentation would present the different architectures prefect can be deployed as.
Also, preparing the deployment with our network team, I couldn't find anywhere in the documentation what ports are to be opened on firewalls. Adding network diagrams for the different architectures would be very helpful (for cases like pull, push for instance)

**Comment by serinamarie** [comment]
Hi @thomasleveil, thanks for creating your first issue with Prefect! 

I'm wondering if @discdiver has some thoughts or plans in motion around this.

**Comment by discdiver** [comment]
Thank you for the feedback. An overview document introducing key concepts is something we've been thinking about, that's helpful.

Curious if a diagram like this one would be helpful toward that end - it's for work-pool based deployments that use a worker, so doesn't include `.serve`:
<img width="1826" alt="How Prefect Works_ Work pool-based deployments created in Python" src="https://github.com/PrefectHQ/prefect/assets/7703961/b2956d03-9bcd-4f46-b15c-71c15ff9c618">

Information on ports sounds like it would be good to have somewhere in docs - and made more discoverable if it's there already.

**Comment by thomasleveil** [comment]
Hi @discdiver, this document is indeed helpful. 
I noticed that in this document the word "_Prefect_" is sometimes used to refer to "_Prefect server_", and some to refer to "_Prefect - the solution/product_" as a whole. This is very confusing when a newcomer does not yet grasp all the concepts/components which are part of the "Prefect solution".

I've also read in the documentation about the "Prefect API", and I assumed it also another term to refer to "Prefect server". Am I right here ?

Anyway, I guess it would help newcomers if terms were carefully used and also that all components which are part of the Prefect solution were presented in the [Welcome to Prefect](https://docs.prefect.io/latest/#welcome-to-prefect) page.

**Comment by discdiver** [comment]
Thank you, @thomasleveil. 

The documentation should differentiate a self-hosted Prefect server instance from Prefect Cloud, the Prefect API used for interfacing with those two options, and Prefect the package/product. I'll make an issue for that.

**Comment by thomasleveil** [comment]
If that can help, I compile a list of [terms found](https://sourcegraph.com/search?q=context:global+repo:github.com/PrefectHQ/prefect+file:%5Edocs/+prefect+count:all&patternType=standard&sm=1&groupBy=repo) in the documentation : 

```
API server
Prefect 1
Prefect 1 client
Prefect 2
Prefect 2 client
Prefect agent
Prefect API
Prefect built-in blocks
Prefect CLI
Prefect client library
Prefect Cloud
Prefect Cloud 1
Prefect Cloud 2
Prefect Cloud account
Prefect Cloud API
Prefect Cloud platform
Prefect Cloud REST API
Prefect Cloud tenant
Prefect Cloud UI
Prefect database
Prefect Deployments
Prefect engine
Prefect flows
Prefect Integrations
Prefect logger
Prefect open source library
Prefect Orchestration Engine
Prefect Orion UI
Prefect processes
Prefect products
Prefect profiles
Prefect Python Client
Prefect REST API
Prefect server
Prefect server instance
Prefect server UI
Prefect task
Prefect UI
Prefect v1 Cloud
Prefect v2 Cloud
Prefect worker
Prefect workflows
Prefect workspace

```
