### ISSUE TITLE
Agent does not continue working on pool after keyboard interrupt if there are pending tasks

### ISSUE THREAD

**Issue by 1beb** [PrefectHQ/prefect#11459]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If you keyboard interrupt the prefect agent then try to start it again, any tasks that were pending will block the pool's queue until you clear them. 

### Reproduction

```python3
1. Stop an agent working on a pool with a keyboard interrupt
2. Have some pending tasks on the agent
3. Restart the agent
4. No profit....
```

### Error

```python3
The pool will not continue to be worked and the agent will sit idle
```

### Versions

```Text
Version:             2.14.11
API version:         0.8.4
Python version:      3.11.7
Git commit:          e6d7d76d
Built:               Thu, Dec 14, 2023 5:45 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

This is not exactly a bug, but rather something that needs to be documented with the right vocabulary for people to find it if it happens to them. Adding here for prosperity.

**Comment by zhen0** [comment]
Thanks @1beb
