### ISSUE TITLE
prefect deploy with prefect.yaml copies flows multiple times

### ISSUE THREAD

**Issue by OliverKleinBST** [PrefectHQ/prefect#11464]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a folder with 3 files which define flows: ingest.py, cleanse.py, curate,py.
In the same folder I have a prefect.yaml which defines push, pull and deployments steps.
In the deployments section I have 3 deployments defined, one for each of ingest, cleanse, curate.
I deploy my 3 flows by running "prefect --no-prompt deploy --all" and all of then get deployed - but all 3 files are deployed for each of the 3 deployments.

My push step is configured to push to azure blob storage. On Azure I have versioning enabled, and I can see that for every deploy event I get 3 versions for each file (basically 1 version for each of my 3 deployment steps).

I have not found any possibility to configure what files to ignore or to copy to blob storage per deployment in the prefect.yaml, so I am wondering how mutiple deployments are to be supported by a single prefect.yaml file

### Reproduction

```python3
# the deployments section allows you to provide configuration for deploying flows
deployments:
- # base metadata
  name: bst-workflow-management
  version:
  tags: ["ingest"]
  # description: "BST ingestion function"
  schedule:

  # flow-specific fields
  entrypoint: bst_ingestion.py:bst_ingestion
  parameters: {}
  
  # infra-specific fields  
  work_pool:
    name: default-workpool
    work_queue_name:
    job_variables:
      image: "{{ prefect.blocks.string.wfm-image }}"
- # base metadata
  name: bst-workflow-management
  version:
  tags: ["cleanse"]
  schedule:

  # flow-specific fields
  entrypoint: bst_cleanse.py:bst_cleanse
  parameters: {}
  
  # infra-specific fields  
  work_pool:
    name: default-workpool
    work_queue_name:
    job_variables:
      image: "{{ prefect.blocks.string.wfm-image }}"
- # base metadata
  name: bst-workflow-management
  version:
  tags: ["curate"]
  schedule:

  # flow-specific fields
  entrypoint: bst_curate.py:bst_curate
  parameters: {}
  
  # infra-specific fields  
  work_pool:
    name: default-workpool
    work_queue_name:
    job_variables:
      image: "{{ prefect.blocks.string.wfm-image }}"
```

### Error

```python3
-
```

### Versions

```Text
2.14.5
```

**Comment by WillRaphaelson** [comment]
Thanks for the issue @OliverKleinBST, each push step can take a different .prefectignore file to configure what files to ignore when pushing.
