### ISSUE TITLE
Display timezone in UI

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#11467]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Timestamps in the UI do not include the timezone component.

### Describe the proposed behavior

It would be helpful if timestamps in the UI included the timezone, either outright, or on hover.

### Additional context

Note that the desired timezone can be set by each user in their profile.

**Comment by MattDelac** [comment]
Example of how this is done in GH
<img width="540" alt="image" src="https://github.com/PrefectHQ/prefect/assets/18557047/c917a887-8526-4fdc-a904-c9c91c13b10b">
