### ISSUE TITLE
Docs example for imperative API is broken (wrong kwarg in call to `say_hello`)

### ISSUE THREAD

**Issue by maxalbert** [PrefectHQ/prefect#1147]
In the [Imperative API](https://docs.prefect.io/guide/getting_started/first-steps.html#imperative-api) example in the docs, the last line is broken. It reads:
```python
say_hello.bind(name=name, flow=flow)
```
but previously `say_hello` was defined with the kwarg `person`, so it should read:
```python
say_hello.bind(person=name, flow=flow)
```

**Comment by maxalbert** [comment]
Out of curiosity, are there any plans to run the docs through CI to avoid having to check the code snippets manually when things change? (I appreciate, however, that this may not be easily possible given how the docs are are structured, with small code snippets interspersed with longer text.)

**Comment by cicdw** [comment]
Yea, it's a good question; we've considered it in the past.  There are a few big friction points to implementing it:
- as you mention, the smaller snippets would need to be parsed
- sometimes, code snippets are meant to [demonstrate an error](https://docs.prefect.io/guide/tutorials/local-debugging.html#raising-exceptions-in-realtime), so we'd have to think about how to handle these
- our examples require lots of external package installations, and some of them even hit external APIs if run (e.g., https://docs.prefect.io/guide/examples/twitter_to_airtable.html)

For the reasons above, we've decided to deprioritize it for now.

**Comment by maxalbert** [comment]
Yes that makes a lot of sense. Thanks for the context and information @cicdw. 👍
