### ISSUE TITLE
feedback on documentation for new comers (work pools)

### ISSUE THREAD

**Issue by ThisIsANiceName** [PrefectHQ/prefect#11482]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Hi,

The prefect documentation looks really great and well written. 

Sadly it was no easily to evaluate them, as the docker pool (which seems like the easiest to test containerized approaches) didn't work out of the box and I was not able to find out what the error message `Docker worker cannot be used with an ephemeral server` expects from me. 

EDIT: it was referring to the prefect server (not config inside docker) :/

### Describe the proposed change

Add some common issues solutions that will happen on a system with no previous/special config, to the documentation.
-> add a hint in `tutorials -> Workers and Work Pools`

Add a "How To" Entry for configuring a work pool with simple common steps (i.e. custom image, volume mount, ...)

### Additional context

I tried my best to see if something in the docs/open issues refer to this. (Without investing too much time into checking the exact code of the `get_client` method in the `orchestration.py`

**Comment by desertaxle** [comment]
Thanks for the issue @ThisIsANiceName! I've opened https://github.com/PrefectHQ/prefect-docker/pull/96 to improve this error message and help guide the user when getting started with a Docker worker. If you can give it a look and provide feedback, it would be much appreciated!

**Comment by ThisIsANiceName** [comment]
Thanks! That look great <3

**Comment by discdiver** [comment]
Closing as https://github.com/PrefectHQ/prefect-docker/pull/96 error message improvements took care of the primary issue and adding docs suggestion elsewhere.
