### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [PrefectHQ/prefect#11517]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@mik0w) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by psmoros** [comment]
Sorry about that, we already have an email

**Comment by chrisguidry** [comment]
Hi @psmoros, we have just updated our SECURITY.md to have the correct email address `bugbounty@prefect.io`, sorry, the wrong folks were getting the emails before.
