### ISSUE TITLE
Inconsistent task run bar coloring

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#11530]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Task run bars at times display with gradients, at times with opacity, and at times with translucence.

![image](https://github.com/PrefectHQ/prefect/assets/26799928/b7254f9a-6f8f-4ae6-819f-123ebca570c0)

![image](https://github.com/PrefectHQ/prefect/assets/26799928/4ea71aca-7be8-43ec-be55-28c39c414f39)

### Reproduction

This script will produce gradients 

```
from time import sleep
import random
from prefect import flow, task


@task
def tree(time=0.5, dependencies=None):
    sleep(time)
    return random.random()


@flow
def my_flow():
    layers = 6
    trunk = tree.submit(time=1)
    for l in range(layers):
        t = trunk
        size = 10 * (layers - l)
        layer_tasks = []
        for _ in range(size):
            time = 8
            t = tree.submit(time=time - l, dependencies=trunk)
            layer_tasks.append(t)
        trunk = tree.submit(dependencies=layer_tasks)


my_flow()
```

### Error

see summary

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by markbaas** [comment]
Happens in all browsers in all my flows as well.
