### ISSUE TITLE
Make search in Deployment tab also search flow names

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#11542]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the serach function under the Deployment tab only search for Deployment names and not for flow names.

![image](https://github.com/PrefectHQ/prefect/assets/44194839/e134ee6e-c9a9-4317-b75d-b2e13f8a3f16)

### Describe the proposed behavior

When using the search under the Deployment tab it would be useful if the search didn't only search in the deployment name column but also in the flow name column. I often go to deployments and want to find all deployments for flows starting with some prefix. I don't really see any downside to this.

![image](https://github.com/PrefectHQ/prefect/assets/44194839/e134ee6e-c9a9-4317-b75d-b2e13f8a3f16)

**Comment by serinamarie** [comment]
This sounds reasonable to me! We've added it to our backlog :)

**Comment by pleek91** [comment]
This was address as part of https://github.com/PrefectHQ/prefect-ui-library/pull/2339
