### ISSUE TITLE
Code for the "fixed" flow in debugging tutorial is slightly misleading

### ISSUE THREAD

**Issue by maxalbert** [PrefectHQ/prefect#1154]
Disclaimer: this is a complete nitpick. ;)

The example [Fixing your broken Flows](https://docs.prefect.io/guide/tutorials/local-debugging.html#fixing-your-broken-flows) in the Debugging tutorial contains a minor bug which makes the flow pass for slightly misleading reasons.

The broken "Gotcha" example in the section before contains a mutable list inside a tuple, which causes the error. This is supposedly fixed by the following code snippet:
```python
@task
def fixed():
    tup = ('a', ('b'))
    try:
        tup[1] += ('c')
    except TypeError:
        assert len(tup[1]) == 1
```
However, the second element in the `tup` variable is just the string 'b' (rather than a tuple with the single element `b`) because the parentheses have no effect (and the same is true for `('c')` in the assignment). To illustrate:
```python
>>> tup = ('a', ('b'))
>>> print(tup)
('a', 'b')
```

The flow passes nonetheless, but not quite for the reason this example suggests.

It can be fixed by adding trailing commas inside the parentheses:
```python
@task
def fixed():
    tup = ('a', ('b',))
    try:
        tup[1] += ('c',)
    except TypeError:
        assert len(tup[1]) == 1
```

Alternatively, one could of course just use the plain strings to get the TypeError (but then we lose the parallel with the broken "gotcha" example):
```python
@task
def fixed():
    tup = ('a', 'b')
    try:
        tup[1] += 'c'
    except TypeError:
        assert len(tup[1]) == 1
```

**Comment by cicdw** [comment]
Haha super great catch @maxalbert!!  PR'ing an update now.
