### ISSUE TITLE
Prefect Cloud returning 403 when Automations are being set

### ISSUE THREAD

**Issue by akmukherjee** [PrefectHQ/prefect#11556]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are getting an error when setting up Automations in our Account. It looks like Automations is not enabled from the Chrome Dev Tools response which returns a 403 with an error message when Automations are being set. Screenshots are attached.
<img width="1920" alt="Screenshot 2024-01-04 at 1 23 42 PM" src="https://github.com/PrefectHQ/prefect/assets/6787494/24351cb9-8d7f-456d-b406-09e2b1e83b3d">
<img width="1920" alt="Screenshot 2024-01-04 at 1 23 57 PM" src="https://github.com/PrefectHQ/prefect/assets/6787494/3c45e3b0-ecf7-4751-b336-f36ba494434e">

### Reproduction

```python3
We are getting an error when setting up Automations in our Account. It looks like Automations is not enabled from the Chrome Dev Tools response which returns a 403 with an error message when Automations are being set. Screenshots are attached.
```

### Error

```python3
Screenshots are attached
```

### Versions

```Text
Prefect Cloud 2.
```

**Comment by zangell44** [comment]
Hey @akmukherjee! Thanks for the thorough write up.

It looks like your account had a license from before the release of automations that wasn't updated correctly. I just gave you access to the feature.

Could you try again now?

**Comment by akmukherjee** [comment]
Thanks a bunch Zach. It does work now!
Very Respectfully,
Amit
