### ISSUE TITLE
Deployment steps continue when script in `run_shell_script` fails

### ISSUE THREAD

**Issue by kevingrismore** [PrefectHQ/prefect#11555]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Errors that occur during the execution of valid commands in `run_shell_script` do not interrupt the deployment process. Attempting to run invalid commands like `script: asdf` does interrupt the deployment process with a `No such file or directory` error.

My expectation is that deployment would fail similarly in both cases, or there should be a param for `run_shell_script` that allows me to choose whether I want an error in my script to cause deployment to fail.

### Reproduction

```python3
prefect.yaml

build:
  - prefect.deployments.steps.run_shell_script:
      script: cat nothing

push: null


pull: null


deployments:
  - name: my-deployment
    entrypoint: flow.py:my_flow
    work_pool:
      name: my-pool
```

### Error

```python3
prefect deploy -n my-deployment

Running deployment build steps...
 > Running run_shell_script step...
cat: nothing: No such file or directory

│ Deployment 'my-flow/my-deployment' successfully created with id '-'.
```

### Versions

```Text
Version:             2.14.10
API version:         0.8.4
Python version:      3.11.5
Git commit:          70888afe
Built:               Thu, Dec 7, 2023 7:27 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment]
Thanks for creating an issue as we discussed in the [Slack thread](https://prefecthq.slack.com/archives/CQTTM2M0D/p1704382046332649)!
