### ISSUE TITLE
No extra argument could be passed to state_handlers function

### ISSUE THREAD

**Issue by occoder** [PrefectHQ/prefect#1156]
I'd like to use the argument other than the default, i.e. fr, old_state, new_state.
I tried following assignment within the task creation
`state_handlers=[polling_on_pause(idx=df_idx)]`
But got following error
`TypeError: polling_on_pause() missing 3 required positional arguments: 'task', 'old_state', and 'new_state'`
The idea was got from  [prefect/src/prefect/utilities/notifications.py ](https://github.com/PrefectHQ/prefect/blob/b04773b97cebda3a12a19f7cdfe2b62bfa8f2c18/src/prefect/utilities/notifications.py) where the similar example is
`@task(state_handlers=[gmail_notifier(ignore_states=[Running])])`

**Comment by cicdw** [comment]
Hi @occoder -- it sounds like all you need is some form of currying / wrapping:
```python
def polling_on_pause(idx):
    def _polling_on_pause(obj, old_state, new_state):
        ... # your custom logic
        return state # whatever state object you want to return

    return _polling_on_pause
```
and then your pattern would work!

**Comment by occoder** [comment]
Hi @cicdw , thanks for the quick response.
I figured out that I should have converted the function call into a function definition like
`state_handlers=[lambda: polling_on_pause(idx=df_idx)]`
Then it seems to work.

**Comment by cicdw** [comment]
Closing as this isn't a bug; we do in fact require state handlers to have a certain signature.  How you create the state handler function is up to you, but eventually it does need to have the appropriate signature to work properly.
