### ISSUE TITLE
Allow setting currency limits at flow level

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#11567]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently concurrency at flow level can only be achieved by having a sepearte worker queue for the flow..

### Describe the proposed behavior

Have flow concurrency similar to task concurrency based on tags.

**Comment by serinamarie** [comment]
Hi, @thomasfrederikhoeck, thanks for your request.

> Currently concurrency at flow level can only be achieved by having a sepearte worker queue for the flow..

Can you please provide an example case for why flow run concurrency limits configured on the work pool / work queue do not suffice? This would allow us to better assess the request.

> Have flow concurrency similar to task concurrency based on tags.

Flows no longer have tags, but flow runs inherit the tag from their deployment.
