### ISSUE TITLE
Correction to Pipenv install instructions?

### ISSUE THREAD

**Issue by crawftv** [PrefectHQ/prefect#1158]
Hi, 
I noticed the instructions to install with pipenv on the [website ](https://docs.prefect.io/guide/getting_started/installation.html#requirements) were `pipenv install -pre prefect`

However, `pipenv install --pre prefect` worked for me.

**Comment by joshmeek** [comment]
Thanks for opening an issue @crawftv! Looks like a documentation typo :)
