### ISSUE TITLE
Optional Flow Parameters cause ValidationError

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#11607]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

This bug appeared on Prefect Cloud right after https://github.com/PrefectHQ/prefect-ui-library/pull/1952 was merged.
It cannot be reproduced (yet) with a local installation of Prefect 2.14.13

When submitting a flow for any deployment that uses an optional parameter and has parameter schema validation enforced, a ValueError pops up and the flow won't be submitted.

Possibly related to https://github.com/PrefectHQ/prefect/issues/11462 and https://github.com/PrefectHQ/prefect/issues/10781

### Reproduction

flow.py
```
from typing import Optional

from prefect import flow

@flow()
def main(
    param: Optional[int] = None
) -> None:
    pass


if __name__ == "__main__":
    main()
```

prefect.yaml
```
deployments:
- name: OptionalTest
  entrypoint: ./flow.py:main
  enforce_parameter_schema: true
```

- Execute `prefect deploy`
- On the deployment page in Prefect Cloud click, Run -> Custom Run -> Submit

### Error

Wrong Validation Error. None should be allowed as value for Optional parameters.
![image](https://github.com/PrefectHQ/prefect/assets/11021147/167d7b9f-cd3f-441e-b987-0db01d3f8538)

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Only reproducible in Prefect Cloud
```

### Additional context

When using Quick Run, or using different datatypes (e.g. Optional[str] or Optional[Any]) this works fine.

**Comment by trymzet** [comment]
Probably related: we've noticed that flow parameters with `None` as the default value are now treated differently by Prefect UI.

Namely, the Parameters tab now shows these values as empty strings in the flow run (before, it simply didn't show these parameters there):

Before:
```json
{
  "param_i_specified": "value"
}
```

Now
```json
{
  "param_i_specified": "value",
  "my_optional_param": ""
}
```

This is a major issue, as now when executing flows manually with the Run button, Prefect is sending `""` instead of `None` to the flow, which causes random errors within the flow code in blocks that depend on the fields being none, eg.

```python
# my_flow.py

# The behavior of this block changed today/yesterday, since `my_optional_param` is now `""` instead of `None`
# (but only when running the flow from Prefect UI)
if my_optional_param is not None:
    do_x()
```

**Comment by znicholasbrown** [comment]
Fix for this has been released

**Comment by zero-element** [comment]
So in version 2.19.1, is there a method to ignore an optional string parameter? I've attempted to modify the parameter JSON to `{}`, but the incoming runs continue to utilize the default value. Additionally, it appears that the parameter remains an empty string `""` even when the content is deleted in the UI. Could you please advise on how to properly handle this situation?
