### ISSUE TITLE
Deprecate `pendulum` 2.X support

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#11619]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

At the time of this writing, `pendulum` 3.X is required to work with Python 3.12 and later. `pendulum` 2.X does not work with Python 3.12.

To minimize user facing impact, pendulum 2.X is installed alongside any `prefect` version using Python 3.11 or earlier and pendulum 3.X is installed alongside any `prefect` version using Python 3.12 or later.

### Impact

Forcing users to upgrade `pendulum` may break their code. When adoption of `pendulum` 3.X is sufficient, we should upgrade.

Alternatively, we may choose to vendor `pendulum` to avoid this issue going forward.

**Comment by egeres** [comment]
I also had a bug on termux with pendulum 2.X which fixed by installing pendulum 3.X

**Comment by cicdw** [comment]
We now depend [exclusively on `pendulum >= 3.0.0`](https://github.com/PrefectHQ/prefect/blob/2e72bacdae444ac4c194efa9b32b9080666f3ef0/requirements-client.txt#L20). Closing as resolved.

**Comment by ecalifornica** [comment]
Heads up for anyone still on Prefect v2, this is only for Prefect v3. Prefect v2 still pins `pendulum < 3.0; python_version < '3.12'`

**Comment by cicdw** [comment]
Specifically on versions of python 3.12 and above [we support `pendulum>=3.0.0` on 2.x.](https://github.com/PrefectHQ/prefect/blob/b8c27aa06d9d3892cbb1d1d69e78e604a527adae/requirements-client.txt#L22)
