### ISSUE TITLE
PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS environment variable does not accept a list

### ISSUE THREAD

**Issue by beornf** [PrefectHQ/prefect#11618]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When passing a list to the environment variable PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS the server is unable to start up.

### Reproduction

```python3
PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS=[10, 20, 40]
```

### Error

```python3
Error loading ASGI app factory: unhashable type: 'list'
Server stopped!
```

### Versions

```Text
Version:             2.14.13
API version:         0.8.4
Python version:      3.11.7
Git commit:          9df5ba72
Built:               Thu, Jan 4, 2024 5:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

### Additional context

https://github.com/PrefectHQ/prefect/blob/cbd8b8f0f80b505077da927094eb6f9b44f6ba30/src/prefect/settings.py#L755-L757

**Comment by clefelhocz2** [comment]
I proposed a PR which may be useful in the short term to @beornf even if fixed/addressed differently long t. rm.

**Comment by beornf** [comment]
@clefelhocz2 Thanks 🎉 Should I test this PR?

**Comment by clefelhocz2** [comment]
> @clefelhocz2 Thanks 🎉 Should I test this PR?

If you have time.   We may want to see if we receive any feedback from project maintainers.
