### ISSUE TITLE
Add a `deployment_version` to prefect.runtime.

### ISSUE THREAD

**Issue by Ben-Epstein** [PrefectHQ/prefect#11642]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

relates to https://github.com/PrefectHQ/prefect/issues/10494 in part. The cache in perfect is a little tricky, because it's not clear how to invalidate it. One pretty helpful way around this would be to incorporate a deployment version, such that, any time you run `prefect deploy` on a deployment, the version gets bumped. 

Then, in your prefect task that you are caching, you can either manually include the deployment version in the hash function, or prefect add an option to include the deployment version in the cache hash function, and then include that in the best practices guide. 

Without this kind of functionality, it's pretty difficult, as a prefect cloud user, to effectively manage cache invalidation (i've manually implemented the above design)

**Comment by WillRaphaelson** [comment]
Thanks for the issue @Ben-Epstein  - this makes sense. We actually already have a deployment version number on the table itself - what would be most useful IMO in terms of using it in the cache is to add the deployment version to the prefect.runtime module - then you can easily pass it into the cache key function and get where you're trying to go. Im going to update this issue to reflect that prescription.

**Comment by WillRaphaelson** [comment]
hey @Ben-Epstein - cracked this open to contribute to find that it already exists! this code does the trick.

```
from prefect import flow, task
from prefect import runtime

@flow(log_prints=True)
def my_runtime_flow(x):
    print("My name is", runtime.flow_run.name)
    print("I belong to version", runtime.deployment.version)
    my_task(2)

@task
def my_task(y):
    print("My name is", runtime.task_run.name)
    print("Flow run parameters:", runtime.flow_run.parameters)

if __name__ == "__main__":
    my_runtime_flow(1)

```
