### ISSUE TITLE
Frequent unit test errors with flow timeouts

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#11646]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

I believe this was first seen here:
https://github.com/PrefectHQ/prefect/actions/runs/7463375936/job/20307914242

Failing tests in `test_flow_timeouts.py`

### Impact

Failing PR CI checks

**Comment by chrisguidry** [comment]
Addressed in https://github.com/PrefectHQ/prefect/pull/11846
