### ISSUE TITLE
No line break in display of flow run tags list

### ISSUE THREAD

**Issue by rebecca-liveeo** [PrefectHQ/prefect#11659]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

If a flow run has lots of tags, there is no line break in their display in the main flow run UI, instead they just run off the screen. 
(In the Details tab, they display with appropriate line breaks).
![image](https://github.com/PrefectHQ/prefect/assets/143079214/0aa91688-9624-46f8-bf67-22ff9a0ebb96)

### Reproduction

Make a flow run and update it to have more tags that will fit on one line on screen.

### Error

Please see bug summary for screenshots.

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by znicholasbrown** [comment]
Hi @rebecca-liveeo - thanks for the report - this'll be fixed in the next release
