### ISSUE TITLE
UI tweaks around presentation of Artifacts

### ISSUE THREAD

**Issue by tjgalvin** [PrefectHQ/prefect#11657]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In regards to the artifacts, would it be possible for two (or three) tweaks on the UI side of things?

When looking at the raw markdown, would it be possible to enable text wrapping? I have a single, very very long line of text. Having a 'copy raw text' button would be pretty awesome as well

![Screen Shot 2024-01-16 at 17 22 17](https://github.com/PrefectHQ/prefect/assets/10543142/2891a4b1-e3b4-4ae9-b963-f4b32be8deb2)

Second query, when multiple artifacts are generated would it be possible to list their description (if it exists) in the list view?

![Screen Shot 2024-01-16 at 17 23 31](https://github.com/PrefectHQ/prefect/assets/10543142/a2ef20e8-cc15-41a7-a7d0-d3f4b697477e)

### Describe the proposed behavior

See above

### Additional context

These are changes on the Prefect UI side of things.

**Comment by desertaxle** [comment]
Thanks for the enhancement request @tjgalvin! I've added this to our backlog and our UI team will take a look at this!

**Comment by znicholasbrown** [comment]
@tjgalvin nice suggestions~! This'll go out with the next release 👍🏻
