### ISSUE TITLE
All run states dropdown does not update listed flows

### ISSUE THREAD

**Issue by BobTorgerson** [PrefectHQ/prefect#11653]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

In the Prefect UI, when looking at a flow in the Flows section, the dropdown menu for "All run states" does not update the list of flows shown. If you select "Failed", the successful runs continue to be shown until you change the flow ordering via the next drop down list, or if you click on the Deployments tab and back to the Runs tab. 

### Reproduction

1. Go to Flows from the left hand menu options in the UI
2. Click on a flow with multiple runs with differing results
3. Change the "All run states" dropdown to "Failed"

Expected: Only the flows that are in the failed state are shown
Actual: All of the flows remain

### Error

<img width="1452" alt="failed_flow_dropdown" src="https://github.com/PrefectHQ/prefect/assets/563260/363eab83-c3d5-4868-8350-f34b41fd0b3a">

### Browsers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.14.13
API version:         0.8.4
Python version:      3.9.16
Git commit:          9df5ba72
Built:               Thu, Jan 4, 2024 5:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

**Comment by WillRaphaelson** [comment]
hey @BobTorgerson - sorry to ask you to do this but I cant reproduce this on cloud or OSS - mind giving this a hard refresh and trying again?

**Comment by BobTorgerson** [comment]
Good afternoon @WillRaphaelson, I just tried a fresh install with `pip install -U prefect` and am still seeing the refresh not happening immediately. However, I noticed that if I wait around 15-20 seconds after picking one of the run states, that the shown flows do update correctly. 

If this is not reproducible by the dev team, I don't want to cause a wild goose chase. It's not affecting my flow runs, so it's just a UI quirk that I wanted to bring to the dev team's attention and doesn't need prompt resolution.

Thank you for getting back to me!

**Comment by BobTorgerson** [comment]
I am not seeing a network request when I switch between the run states beyond the favicon.ico being requested. After a few seconds, I see the filter and count calls in the network tab which coincides with the correct flow runs being shown. I'd say you can close this, as it does work on my end eventually, so it is likely a configuration that I have in my browser. 

Thanks for your time!

**Comment by WillRaphaelson** [comment]
Okay, thanks @BobTorgerson - let me know if anything else comes up.
