### ISSUE TITLE
Add a `gather()`-type operation to resolve a `list[PrefectFuture]` into a `list[Result]`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [PrefectHQ/prefect#11694]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When running a subflow in Prefect that returns a `list[PrefectFuture]`, the user has to iterate through each entry in the list and manually resolve each future to retrieve the desired `list[Result]`. Consider the following toy example:

```python
from prefect import flow, task


@task
def add(a, b):
    return a + b


@flow
def add_distributed(vals, b):
    outputs = []
    for val in vals:
        output = add.submit(val, b)
        outputs.append(output)
    return outputs


@flow
def workflow(vals, b):
    return add_distributed(vals, b)

futures = add_distributed([1, 2], 3)  # list[PrefectFuture]
results = [future.result() for future in futures]  # list[int]
```

As seen above, the only way to resolve the futures is by iterating through each entry and manually resolving each one.

This has two notable downsides: 1) It is not intuitive to all end-users of the Prefect flow; 2) It requires blocking `.result()` calls to be used if this kind of pattern is part of a larger workflow.

### Describe the proposed behavior

Inspired by options like Dask's [`Client.gather()` operation](https://docs.dask.org/en/latest/futures.html#distributed.Client.gather), Prefect should consider adding a similar gather-type operation that would allow for a single function to be called on the `list[PrefectFuture]` to resolve the items in the iterable.

**Comment by zzstoatzz** [comment]
hi @Andrew-S-Rosen - I could see convenience in having a `gather_futures` util that handles `asyncio.gather`ing the `.result()` calls for you.

Would you be interested in contributing this?

**Comment by Andrew-S-Rosen** [comment]
Glad to hear you also could aww the value in a utility like this!

Unfortunately, I don't have a great grasp of asyncio so don't know that this is one I'll be able to tackle personally.

**Comment by zzstoatzz** [comment]
@Andrew-S-Rosen no worries! we'll put this on the backlog and get to it when we can

just as a note if its helpful, you can simplify your example above using `.map`
```python
from prefect import flow, task

@task
def add(a, b):
    return a + b

@flow
def workflow(vals: list, b: int):
    return [future.result() for future in add.map(vals, b)]

print(workflow([1, 2], 3))
```

**Comment by eladm26** [comment]
@zzstoatzz can you assign it to me please?

**Comment by Andrew-S-Rosen** [comment]
@eladm26 I don't think you need to be assigned on it. You can simply submit a PR.

**Comment by eladm26** [comment]
@Andrew-S-Rosen I just stumbled upon [resolve_futures_to_data](https://docs.prefect.io/latest/api-ref/prefect/futures/#prefect.futures.resolve_futures_to_states) I think this util function should address your needs.
@zzstoatzz what do you think?

**Comment by Andrew-S-Rosen** [comment]
@eladm26 good find! That _seems_ like it would be it, although I'm having some trouble confirming this.

```python
from prefect import flow, task
from prefect.futures import resolve_futures_to_data


@task
def add(a, b):
    return a + b


@flow
def add_distributed(vals, b):
    outputs = []
    for val in vals:
        output = add.submit(val, b)
        outputs.append(output)
    return outputs


@flow
def workflow(vals, b):
    return add_distributed(vals, b)

futures = add_distributed([1, 2], 3)  # list[PrefectFuture]
results = await resolve_futures_to_data(futures)
assert futures != results # this fails
```

Any ideas?

**Comment by kevingrismore** [comment]
When you return a `PrefectFuture` from a flow, you get a `State` and you can call `.result()` on it.

```python
@task
def add(a, b):
    return a + b


@flow
def add_distributed(vals, b):
    outputs = []
    for val in vals:
        output = add.submit(val, b)
        outputs.append(output)
    return outputs


@flow
def workflow(vals, b):
    states = add_distributed(vals, b)
    for state in states:
        print(type(state))
        print(state.result())

workflow([1, 2], 3)
```

```bash
<class 'prefect.client.schemas.objects.State'>
4
<class 'prefect.client.schemas.objects.State'>
5
```

`resolve_futures_to_data` works fine if you call it inside `add_distributed` where the `PrefectFuture`s are still present.

**Comment by Andrew-S-Rosen** [comment]
I see. Thanks, @kevingrismore! In my scenario, I was hoping to be able to call the gather-type operation afterwards so as to not inject Prefect-specific logic inside the `@flow` definition itself.

**Comment by eladm26** [comment]
So, is this issue solved? @Andrew-S-Rosen @zzstoatzz ?

**Comment by Andrew-S-Rosen** [comment]
@eladm26 I suppose it can be closed, as my title does have a corresponding function.

**Comment by eladm26** [comment]
Thank you dude
