### ISSUE TITLE
Update Client requests to use sessions

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1171]

**Comment by cicdw** [comment]
I think we should be careful with this (e.g., https://toolbelt.readthedocs.io/en/latest/threading.html).

Dask sometimes uses multi-threading and so do we (directly) via heartbeats.  I vote we hold off on implementing this until we're sure it provides non-trivial value.

**Comment by joshmeek** [comment]
@cicdw Okay good call. Will keep this open and in mind in case it comes up again.
