### ISSUE TITLE
Async flows with JDBC connections (jaydebeapi package) do not close the JVM preventing the python process from terminating

### ISSUE THREAD

**Issue by GeorgeBark** [PrefectHQ/prefect#11745]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using the package [jaydebeapi](https://github.com/baztian/jaydebeapi) to connect to a database via JDBC the python process keeps hanging there until killed externally. This happens when creating a JDBC connection in an `async` task and running it within an `async` flow.

If the task is synchronous or if it is run as a function with the `.fn()` method, it works as expected.

It is worth noting that the flow completes correctly, but the process does not finish, so in both the logs and the UI you get a "Successful" flow run.

### Reproduction

```python3
from prefect import flow, task
import jaydebeapi
import asyncio

@task
async def jdbc_async_task():
    connection = jaydebeapi.connect(
        jclassname=JAVA_CLASS_NAME,
        url=CONNECTION_URL,
        driver_args=[DB_USER, DB_PASSWORD],
        jars=JAR_FILE
    )

    cursor = connection.cursor()
    cursor.execute("SELECT 'jdbc_async_task' as method")
    
    data = cursor.fetchall()
    print('result: ', data)
    
    cursor.close()
    connection.close()

@flow 
async def jdbc_async_flow():
    await jdbc_async_task()

if __name__ == "__main__":
   asyncio.run(jdbc_async_flow())
```

### Error

```python3
There is no error, it just hangs:

$ python main.py
11:31:14.407 | INFO    | prefect.engine - Created flow run 'hallowed-copperhead' for flow 'jdbc-async-flow'
11:31:14.591 | INFO    | Flow run 'hallowed-copperhead' - Created task run 'jdbc_async_task-0' for task 'jdbc_async_task'
11:31:14.592 | INFO    | Flow run 'hallowed-copperhead' - Executing 'jdbc_async_task-0' immediately...
result:  [('jdbc_async_task',)]
11:31:18.066 | INFO    | Task run 'jdbc_async_task-0' - Finished in state Completed()
11:31:18.106 | INFO    | Flow run 'hallowed-copperhead' - Finished in state Completed('All states completed.')
```

### Versions

```Text
Version:             2.14.15
API version:         0.8.4
Python version:      3.11.3
Git commit:          e585e980
Built:               Thu, Jan 11, 2024 6:18 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.42.0
```

### Additional context

If at the end of main.py I force the shutdown of the jvm, then the process finishes:

```python
import jpype as jp

# ... code

if __name__ == "__main__":
    asyncio.run(jdbc_async_flow())
    jp.shutdownJVM() 
```
This forces the shutdown but can only be executed in the main thread. I tried to run it in the `on_completion=` hook of the flow but it fails as it is executed in an inner thread.

**Comment by zzstoatzz** [comment]
hi @GeorgeBark
> can only be executed in the main thread

since tasks are indeed run in worker threads, I would recommend creating and closing the connection object within the flow context (not in a task) and then passing the connection object into your task as needed

**Comment by GeorgeBark** [comment]
Hi @zzstoatzz 

>  I would recommend creating and closing the connection object within the flow context (not in a task) and then passing the connection object into your task as needed 

My understanding is that this is not a very good practice as the connection is not serializable and therefore if trying to run it in parallel it will not work correctly.

Despite that, I tried and it seems to work. Also, I tried to add the `jp.shutdownJVM()` instruction at the end of the flow and it also works. This way I let the tasks open and close connections but at the end I shut down the JVM manually. I still need to see how it behaves with subflows to make sure I don't kill the JVM too early.

In any case, I would consider this a workaround, I think there should be a way for pefect to kill the process if the flow has finished, specially if completed successfully.

Thanks!

**Comment by zzstoatzz** [comment]
@GeorgeBark

👍🏼 

> My understanding is that this is not a very good practice as the connection is not serializable and therefore if trying to run it in parallel it will not work correctly.

It should work fine if you use the default (`ConcurrentTaskRunner`) as task parameters don't need to be serializable there, but yeah if you wanted to use dask / ray or something then you're right you might need a different approach.

I am not so familiar with the specifics of JVM as far as its threading rules - do you think there's an outstanding issue specifically related to the prefect SDK here?

**Comment by GeorgeBark** [comment]
Hi @zzstoatzz 

I didn't like the idea of moving the connection around so I finally solved the issue in a different way, I added an "atexit" listener to close the JVM. Because of the main thread issue, I couldn't use the provided method `jpype.shutdownJVM()`so I got creative and used the java native `java.lang.System.exit(0)` function.

For future reference, here are the functions I am using:
```python
import atexit
import jpype
from time import sleep

def close_jvm_at_exit():
    print('Attempting to close JVM')
    try: 
        print('trying: JVM is started?')
        sleep(5)
        is_started = jpype.isJVMStarted()
        print('JVM is started?', is_started)
        if is_started:
            print('JVM is started, closing...')
            jpype.java.lang.System.exit(0)
            #jpype.shutdownJVM()
            print('JVM closed')
        else:
            print('else: JVM is not started')
    except:
        print('catch: JVM is not started')

def register_close_jvm_at_exit():
    atexit.register(close_jvm_at_exit)
    print('registered close_jvm_at_exit')
````

And when creating the connection:

```python
def get_connection(self):
    
    CLASS_NAME=self.class_name
    CONNECTION_URL=f"jdbc:sqlserver://{self.host}:{self.port};databaseName={self.database};trustservercertificate=true"

    register_close_jvm_at_exit()

    connection = jaydebeapi.connect(
        jclassname=CLASS_NAME,
        url=CONNECTION_URL,
        driver_args=[self.username, self.password.get_secret_value()],
        jars=self.jar_file
    )

    return connection
```

It seems to be working fine, let's hope it doesn't break something else in the process....

> do you think there's an outstanding issue specifically related to the prefect SDK here? if so, could we update the title and the body to reflect what about Prefect should change?

To answer your question, no I don't think there is an outstanding issue; however, I noticed the flow hook `on_completion` is not executed in the main thread and I believe it should be so you have more control about what you need to clean up when the flow completes. 

Having said that, I will close the issue as my comment above is more of a suggestion rather than an actual issue.

Many thanks!
