### ISSUE TITLE
Kubernetes worker will randomly stop polling - no errors in logs

### ISSUE THREAD

**Issue by walter-cavinaw** [PrefectHQ/prefect#11747]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We just migrated our flows from using the prefect agent on k8 (with a pinned earlier version of prefect), to using the prefect worker on k8.

Tried using the latest version of prefect (2.14.17), but there is a bug with flows completing (all tasks green), but the worker would randomly mark flows as failed with "Pod could not start".

We downgraded to the previous version, but there was an issue with completed flows marked as "Backoff limit reached". our backoff limit was 0 (and all pods are created successful). Increasing the backoff limit fixed that issue. It seems the worker will check the backoff limit value before the flow is marked as completed successful - some kind of race condition.

Our whole setup will work for a few hours, but then the worker will randomly stop polling for flows.

It's frustrating because we have a Pro account and everything worked fine using the prefect agent.

It would be great if someone from prefect or the community can advise how to debug this. There are no error logs in the prefect worker pod, and the pod keeps running, but the worker is not polling.

### Reproduction

```python3
It's a random error. If I could reproduce it, I would.
```

### Versions

```Text
2.14.16
```

**Comment by zzstoatzz** [comment]
hi @walter-cavinaw - I think this issue should be opened on PrefectHQ/prefect-kubernetes

does [this](https://github.com/PrefectHQ/prefect-kubernetes/issues/106) look related to your issue?
