### ISSUE TITLE
Bump pytest to 8.0

### ISSUE THREAD

**Issue by bunchesofdonald** [PrefectHQ/prefect#11750]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

pytest 8.0 was just released and added some deprecations that affect the Prefect test suite. We should bump pytest to 8.0, fix any deprecation warnings, and ensure the test suite runs as expected.

**Comment by serinamarie** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/11821

**Comment by bunchesofdonald** [comment]
We actually had to revert this due to compatibility issue with ddtrace. We should bump pytest to 8 when that compatibility is fixed.

**Comment by cicdw** [comment]
`ddtrace` has been removed and we're now successfully running `pytest >= 8.0`
