### ISSUE TITLE
Deployment list not showing up on the Deployments Page

### ISSUE THREAD

**Issue by Sahiler** [PrefectHQ/prefect#11760]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When accessing the deployments page, the deployments count is being shown, but not the deployments list
![Screenshot 2024-01-29 at 2 20 14 PM](https://github.com/PrefectHQ/prefect/assets/24235898/3ffa5370-2f48-4cb7-aa35-5a1796173b08)

### Reproduction

Have atleast 10 deployments, the count of deployments are displayed top left, and the deployments are not shown

### Error

Throwing a few JS errors revolving around 500s         
        
POST https://api.prefect.cloud/api/accounts/account_id/workspaces/workspace_id/deployments/filter net::ERR_FAILED 500 (Internal Server Error)

### Browsers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

**Comment by zangell44** [comment]
There was an edge case with null schedules that was causing 500s on the backend that has since been fixed.

UI fix in this PR https://github.com/PrefectHQ/prefect-ui-library/pull/2033
