### ISSUE TITLE
Update Docker Tutorial for clarity around prefect-docker-guide directory

### ISSUE THREAD

**Issue by preynacc** [PrefectHQ/prefect#11809]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

In the `Writing a Dockerfile` section, the first two code blocks include a `cd`, and you could feasibly just copy/paste straight from the blocks.

```
mkdir prefect-docker-guide
cd prefect-docker-guide
```

and

```
mkdir flows
cd flows
touch prefect-docker-guide-flow.py
```

The next sections that create a `requirements.txt` and `Dockerfile` should be run in `prefect-docker-guide-directory`, which requires `cd`ing back into the `prefect-docker-guide` directory from the `flows` directory.  However, if you were just to copy/paste straight from the code blocks, you'd be creating the requirements/Dockerfile/attempting to create the Docker image in `flows`

```
touch requirements.txt
```

https://docs.prefect.io/latest/guides/docker/#writing-a-dockerfile

### Describe the proposed change

This block could include a `cd ..` prior to creating the requirements/Dockerfile/Docker image.

Current
```
touch requirements.txt
```

Proposed
```
cd ..
touch requirements.txt
```

### Additional context

This is super minor, but while skimming through the Docker tutorial I got tripped up for a couple minutes + figured I'd open an issue.  I could also see how including the `cd ..` could be undesired, given the note right above the block 

```
The next file we'll add to the prefect-docker-guide directory is a requirements.txt. We'll include all dependencies required for our prefect-docker-guide-flow.py script in the Docker image we'll build.
```

**Comment by serinamarie** [comment]
Hi @preynacc, thanks for the issue! Hopefully the linked PR will help to clarify this for you :)
