### ISSUE TITLE
Deploy Prefect flow on local server

### ISSUE THREAD

**Issue by shankisg** [PrefectHQ/prefect#1180]
Hello Team,

I am exploring multiple workflow engines.  While  exploring Airflow, I came across Prefect. I am trying to find out recommended steps to deploy **Flow** on local server .  Could you please share steps to do so or point me to the document having required information. Basically I didn't found anything equivalent to Airflow Scheduler. Sample **flow**  below

Thanks
-Shanki

```
import datetime
import random

from prefect import Flow, task
from prefect.schedules import IntervalSchedule


@task(cache_for=datetime.timedelta(minutes=1, seconds=30))
def return_random_number():
        return random.random()


@task
def print_number(num):
    print("=" * 50)
    print("Value: {}".format(num))
    print("=" * 50)

schedule = IntervalSchedule(
    start_date=datetime.datetime.utcnow(), interval=datetime.timedelta(minutes=1)
)

with Flow("cached-task", schedule=schedule) as flow:
    result = print_number(return_random_number)

flow.run()
```

**Comment by cicdw** [comment]
Hi @shankisg - our recommended deployment solution is going to be our [Prefect Cloud Platform](https://www.prefect.io/lighthouse-partners).  In the meantime, it's a hard question to answer without understanding your use case / needs.  As a first step, you could place the above code inside a docker container and run that in your favorite location.

**Comment by shankisg** [comment]
Hi @cicdw, basically requirement is to run workflow engine in my datacenter, where existing system is processing more than a million **Flow** per day. Docker solution might not work for me, since number container running will be huge.

**Comment by jlowin** [comment]
@shankisg are you running a million different workflows each day, or a million different tasks contained in a relatively small number of workflows?

**Comment by shankisg** [comment]
@jlowin I am running a million different workflows each day. And depending on load, number of corresponding worker required is decided.
