### ISSUE TITLE
Workflow patterns from workflowpatterns.com

### ISSUE THREAD

**Issue by pikhovkin** [PrefectHQ/prefect#1183]
Can you describe which workflow patterns (described on [workflowpatterns.com](http://www.workflowpatterns.com/patterns/control/index.php)) support by Prefect?

**Comment by cicdw** [comment]
Hi @pikhovkin - I'm afraid I don't have the time to read that document and properly answer your question.  Is there a particular pattern you require?  I'd recommend [reading our documentation](https://docs.prefect.io/guide/) to get a sense of Prefect's features and supported patterns.

**Comment by pikhovkin** [comment]
It seems to me that you can just look at the images of the pattern and say if we can implement such a pattern on the Prefect :)
I think it might help new users of the Prefect.

**Comment by jlowin** [comment]
Prefect is a tool for modeling acyclic DAGs in which steps are executed sequentially (no step starts until its upstream steps finish). At a glance, that captures nearly every pattern on the page. If there's a specific pattern you are having trouble implementing, we'd be happy to help you with it.
