### ISSUE TITLE
WARNING - Task run '...' finished in state Completed()

### ISSUE THREAD

**Issue by OliverKleinBST** [PrefectHQ/prefect#11841]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

After migration from prefect 2.14.5 to 2.14.20 we see unexpected warnings in the task_runs logs.

### Reproduction

```python3
Just call any @task from a @flow
```

### Error

```python3
Go to your logs and you will find that a task ends as expected with 
INFO: Finished in state Completed().

But then we get an unexpected additional line:
WARNING: Task run '...' finished in state Completed().
```

### Versions

```Text
Version:             2.14.20
API version:         0.8.4
Python version:      3.9.18
Git commit:          8ceb0962
Built:               Thu, Feb 1, 2024 6:30 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by zzstoatzz** [comment]
hi @OliverKleinBST - thanks for the issue. this has already been addressed by https://github.com/PrefectHQ/prefect/pull/11810 and will go out with the next release
