### ISSUE TITLE
Flow parameter validation fails with Pydantic 2 when it uses generic type

### ISSUE THREAD

**Issue by ka7eh** [PrefectHQ/prefect#11842]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm using Prefect 2.14, and I am in the process of upgrading my flows to use Pydantic v2.

I have some flows that their parameters use Pydantic schemas with Generics. This used to work fine with Pydantic 1, but now I'm getting validation issues.

### Reproduction

```python3
from typing import TypeVar, Generic

from pydantic import BaseModel
from prefect import flow, task


ResultType = TypeVar("ResultType")


class Result(BaseModel, Generic[ResultType]):
    result: list[ResultType]

@task
def query() -> Result[int]:
    return Result(result=[1, 2, 3])


@flow
def process_query(result: Result[int]) -> Result[str]:
    return Result(result=[str(i) for i in result.result])


@flow
def main() -> None:
    result = query.submit()
    process_query(result)


if __name__ == "__main__":
    main()
```

### Error

```python3
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - result: Input should be a valid dictionary or instance of Result[int]
```

### Versions

```Text
Version:             2.14.20
API version:         0.8.4
Python version:      3.11.7
Git commit:          8ceb0962
Built:               Thu, Feb 1, 2024 6:30 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by ka7eh** [comment]
I found a workaround for this by explicitly specifying the type in `query` function like this:

```
@task
def query() -> Result[int]:
    return Result[int](result=[1, 2, 3])
```

Still, it'd be great if there was a way to infer that from the return type specified for this function.

**Comment by ka7eh** [comment]
Thanks, @zzstoatzz.

Looking at the examples and how pydantic works, I also started thinking that the error makes sense.
The solution, as you mentioned in your example, is simple enough, and I started to annotate my return values.

I was thinking of the inference solution as a nice-to-have feature, but considering there's an easy way to fix this, we can ignore it. :)

I don't know if there's a migration page from Pydantic 1 to 2 in Prefect, but it'd be great to note this there because for me, it was confusing at first that the code that validated before and looked correct, broke after switching to pydantic 2.

**Comment by zzstoatzz** [comment]
I think adding some guide in the docs on how to leverage pydantic 2 would be a good enhancement! perhaps we could open a separate `docs` issue to track that, or an `enhancement` specifically about inferring things from return types (though that might be a tricky ask)

how do you feel about closing this issue as is for now?

**Comment by ka7eh** [comment]
Sounds good! I'll close this one.
