### ISSUE TITLE
Eliminate tedious release notes process for collections repos

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#11936]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

Currently our collections repos maintain a CHANGELOG that's updated on every PR and then manually updated for each release. There is no need for this process.

We should
1. Get rid of CHANGELOG.md and any references to it (e.g. the PR checklist item)
2. Update internal Notion doc with instructions to use GitHub's autogenerated release notes

### Impact

Toil.

**Comment by zzstoatzz** [comment]
completed via:
- `./scripts/collection-manager clone`
- `./scripts/collection-manager branch "rm-changelog"`
- `./scripts/collections-manager run-function functions:thursday_feb_8_2024_update_pr_template`
- `./scripts/collection-manager commit "rm changelog and update PR template"`
- `./scripts/collections-manager pull-request`

```python
def thursday_feb_8_2024_update_pr_template(repo: Path) -> None:
    
    changelog_path = repo / "CHANGELOG.md"
    if changelog_path.exists():
        changelog_path.unlink()
    
    pr_template_path = repo / ".github" / "PULL_REQUEST_TEMPLATE.md"
    if pr_template_path.exists():
        with open(pr_template_path, "r") as file:
            lines = file.readlines()
        with open(pr_template_path, "w") as file:
            file.writelines(lines[:-1])
```
