### ISSUE TITLE
Bug for historical plot of Flow Runs

### ISSUE THREAD

**Issue by trinebrockhoff** [PrefectHQ/prefect#11977]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Hey prefect,

It does not have expected behavior when choosing historical data in below:
![image](https://github.com/PrefectHQ/prefect/assets/61736696/adca3c7d-aa26-4ca6-b31e-e61551e1b4db)

### Reproduction

I have a flow running every half hour, and it always fails at night (in a time period). 
 
So I would like to plot the flow runs over a time period. So I pick the timeperiod (**orange**) and the total number of flow runs are updated (**purple**).
But the plot is not updated (**yellow**), it looks like the “Past 1 day” view.
And when I hover over the first flow run (**red**), it shows me the “past 1 day”- first flow run. 
![image](https://github.com/PrefectHQ/prefect/assets/61736696/d3679308-46a9-4513-a31d-37869f800390)

### Error

I can’t collect the information about: what typical time at night does my flow fail, because I am not able to see the historical flow runs. 

It is showing only the last day plot.

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

**Comment by brandonreid** [comment]
Thanks so much for reporting this @trinebrockhoff. This did surface at least two bugs that have resolution PR's being reviewed.

In general for this graph, please note that it is designed to show "recent activity". So if viewing one day of time, if there were 500 runs, you would only see the latest `n` number of runs represented on the graph and no more. I realize this could be confusing and that having an easy way of viewing all runs within a time period would be useful. You could shorten the time length you're viewing even more to ensure all runs for the time period are visible on the graph. You may be able to achieve what you were aiming for on the Flow Runs page instead, filtering by flow, state, and time.
