### ISSUE TITLE
Parameters set in the UI are being ignored when deployment is being run

### ISSUE THREAD

**Issue by santiagomlorenzo** [PrefectHQ/prefect#11990]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I'm running a deployment with a specific parameter from the UI, it doesn't get sent, and it runs with the default parameter. When I hit the API, it works fine. The parameter is not being sent in the request the UI makes.

### Reproduction

Go to a deployment that has an optional parameter for which your flow sets a default, create a custom run with a different parameter that is not the default. Request is sent without parameters and your flow runs with the default parameter value.

### Error

https://github.com/PrefectHQ/prefect/assets/17880489/ce0f4c56-7b71-4a37-a8f4-b8f1327605d4

### Browsers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

**Comment by zzstoatzz** [comment]
hi @santiagomlorenzo - thank you for the issue!

hmm I'm yet to see this issue using the following flow to reproduce (based on your description)
```python
from prefect import flow

@flow(log_prints=True)
def foo(x: str | None = "oof") -> int:
    print(f"foo got {x=}")

if __name__ == "__main__":
    foo.serve("foo")
```

where I'm setting `x` to a new value in the "Create Custom Run" of the UI on Chrome.

Would you be able to share an MRE for this?

**Comment by pleek91** [comment]
Now that enhanced deployment parameters are available in oss and cloud I'm going to go ahead and close this issue. But please let us know if you're still having issues with this. Thank you for reporting!
