### ISSUE TITLE
faild job run is gone - 404

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#11993]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A faild job run is missing and showing 404:

![CleanShot 2024-02-15 at 16 48 28@2x](https://github.com/PrefectHQ/prefect/assets/5398977/dfb08c09-0e7b-4d21-9b0a-f693290611a4)

[job url](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/e279a126-8006-4a9d-9224-65437e3303af)

![CleanShot 2024-02-15 at 16 49 05@2x](https://github.com/PrefectHQ/prefect/assets/5398977/1ebdd1f4-8c57-4db0-b3ee-f45113264fe3)

### Reproduction

```python3
Prefect cloud
```

### Versions

```Text
Prefect cloud
```

**Comment by urimandujano** [comment]
Hey @yaronlevi - it looks like that flow run was deleted by an automation and after a flow-runs gets deleted, any attempts to visit in the UI will result in a 404. Do you have any automations that would be doing this?

**Comment by yaronlevi** [comment]
@urimandujano which automation are you referring to? We have only 3 automations and none of them has a "delete" run action:

![CleanShot 2024-02-16 at 11 55 34@2x](https://github.com/PrefectHQ/prefect/assets/5398977/372c006f-f40c-489f-84a0-1cdd07882e4e)

**Comment by urimandujano** [comment]
Let me follow up with more details via DM/
