### ISSUE TITLE
no import statement for wait_for_flow_run

### ISSUE THREAD

**Issue by SeereouslyDrewNichols** [PrefectHQ/prefect#11992]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

There is no import statement for wait_for_flow_run so typing this code into pycharm shows wait_for_flow_run as an error.  Searching the internets, the import statement used to be

_from prefect.tasks.prefect import wait_for_flow_run_

yeah, that doesn't work anymore.

### Describe the proposed change

put the correct import statement in the docs which is 

_from prefect.flow_runs import wait_for_flow_run_

**Comment by urimandujano** [comment]
Thank you for the suggestion! The proper import statement would be:

```python
from prefect.flow_runs import wait_for_flow_run
```

We'll get this detail added to the docs.
