### ISSUE TITLE
Pydantic model attribute used for flow argument is not editable in Prefect UI

### ISSUE THREAD

**Issue by ka7eh** [PrefectHQ/prefect#12024]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a pydantic model used for my flow arguments. One of the attributes on this model has type of `dict[str, Any]`.

This works fine when run from the command line, but when deployed, I cannot edit this attribute.
If I set the value for this attribute in Parameters JSON, it is not accepted and gets dropped.

### Reproduction

```python3
from typing import Any

from prefect import flow
from pydantic import BaseModel


class Params(BaseModel):
    id: str
    data: dict[str, Any] | None = None


@flow(log_prints=True)
def main(params: Params) -> None:
    print(params.id)
    print(params.data)

if __name__ == "__main__":
    # This works fine
    main(Params(id="1", data={"a": 1}))
```

### Error

If you deploy the simple flow above, and try to run it via Prefect UI, I can only enter a value for `id`, but not `data`.

![Screenshot from 2024-02-20 13-27-10](https://github.com/PrefectHQ/prefect/assets/4112646/8b29a01c-8220-4a09-b2d7-394461dc2bed)

### Versions

```Text
Version:             2.15.0
API version:         0.8.4
Python version:      3.11.7
Git commit:          e90804b8
Built:               Thu, Feb 15, 2024 2:54 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by pleek91** [comment]
@ka7eh this is happening because the json schema produced by `dict[string, Any]` has no properties that we can generate a form for. For now you'll have to switch to the json tab and enter your values that way. But we're working on a bunch of deployment parameter form improvements that should make this experience much better. Should start seeing things about that in the next week or so.

**Comment by ka7eh** [comment]
Thanks, @pleek91. I already tried using the json tab. The problem is that it doesn't accept my values in that tab.

If I enter a value like this, it simply drops `data` from the submitted params:
```{json}
{
  "id": 1,
  "data": {
    "a": 1
  }
}
```.

**Comment by pleek91** [comment]
@ka7eh from my testing this is working in our enhanced deployment parameters ui which is available in cloud and will soon be available in open source. I'm able to enter values as json and see that the run is created with the parameters I specified

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/d682d615-f758-49d0-9027-5e23d16cdf29)

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/700fc9c6-b233-4f71-80e7-916bfc0a7b0e)

**Comment by pleek91** [comment]
Now that enhanced deployment parameters are available in oss and cloud I'm going to close this issue. But please let us know if you're still having issues.
