### ISSUE TITLE
Rerun Flow After Failure

### ISSUE THREAD

**Issue by kforti** [PrefectHQ/prefect#1202]
If I run a flow that fails, can I serialize that flow, fix my code, and then rerun the flow using the serialized state (I guess I am also asking if the state is even serialized)?

I am using prefect for large-scale bioinformatics analysis. The first task could take 8 hrs. I do not want to rerun that if task 2 fails.

Thanks,
Kevin

**Comment by cicdw** [comment]
Hi @kforti - in short, yes this is possible.  There are a few different ways you can achieve this.  Let me offer up a few suggestions and you can let me know which one fits your pattern best:

- if you had some way of _automatically_ determining whether the first task had already run (e.g., by checking a database or some external flag), you could perform that check and then raise a Prefect [SUCCESS signal](https://docs.prefect.io/api/unreleased/engine/signals.html#success) within the first task's `run` method to avoid repeating the computation
- if not, you could serialize the `Success` state from the first flow run (this can be accessed from the `result` of the flow state itself), and then pass that state in for the first task using the `task_states` keyword argument to `flow.run`.  Some documentation for this keyword can be found [here](https://docs.prefect.io/api/unreleased/engine/flow_runner.html#prefect-engine-flow-runner-flowrunner-run).

**Comment by kforti** [comment]
Thank you, @cicdw. This was very helpful.
