### ISSUE TITLE
`test_batched_queue_service_min_interval` test is flaky

### ISSUE THREAD

**Issue by bunchesofdonald** [PrefectHQ/prefect#12052]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

The `test_batched_queue_service_min_interval` uses a 10 second window for the test to pass, and under high load in our CI environment that might not always be enough: https://github.com/PrefectHQ/prefect/actions/runs/8006604038/job/21868748585?pr=12020

**Comment by cicdw** [comment]
Closing as I haven't seen this test flake in a long time - can revisit if it crops back up again though.
