### ISSUE TITLE
The "run tasks on the main thread" changes in 2.15.0 can lead to hangs when awaiting task futures' results

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect#12053]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

The commit: [3d4281f989d84aca67f1d27e069826387e99ea8a](https://github.com/PrefectHQ/prefect/commit/3d4281f989d84aca67f1d27e069826387e99ea8a)

We discovered this through a few avenues:

* Customer complaints that converge around issues starting with the 2.15.0 release
* The [`prefect-dbt` nightly tests](https://github.com/PrefectHQ/prefect-dbt/actions/workflows/nightly-dev-tests.yml) started timing out the night we merged this change
* We can reproduce this locally in the `prefect-dbt` repo by testing against this commit and the prior one:

```bash
pip install "prefect @ git+https://github.com/PrefectHQ/prefect.git@0d1934f5fa616d6675b6643b842cb99f09328a64"
pytest tests/cloud/test_jobs.py::TestTriggerDbtCloudJobRunAndWaitForCompletion::test_run_in_sync_flow -vvvv -s
```

will pass, while:

```bash
pip install "prefect @ git+https://github.com/PrefectHQ/prefect.git@3d4281f989d84aca67f1d27e069826387e99ea8a"
pytest tests/cloud/test_jobs.py::TestTriggerDbtCloudJobRunAndWaitForCompletion::test_run_in_sync_flow -vvvv -s
```

will hang.

* @zzstoatzz was able to build a MRE:

```python
from prefect import flow, task

@task
async def some_async_task():
    pass

@flow
async def integrations_flow():
    future = await some_async_task.submit()
    await future.result() # <--- HERE

def main():
    @flow
    def sync_flow():
        integrations_flow()
    
    sync_flow()

if __name__ == "__main__":
    main()
```

Our plan is to revert these changes for a 2.15.1 release to get users back up and running, and then debug this issue offline.

**Comment by zanieb** [comment]
👀 weird. Sorry about that. I'm surprised this fails, but there's of course a lot of complexity with nesting here. I noticed there wasn't great coverage of nested flows with mixed sync/async code when I was working on this. Let me know if you have any questions, I hope the fix isn't too wild we're probably just sending something to the wrong thread?

**Comment by chrisguidry** [comment]
No worries, @zanieb!  It does seem like it's just a nesting issue and we were able to distill down a regression test that reproduces it.  Pretty sure we'll be able to bring this back soonly.

**Comment by discdiver** [comment]
The [2.16.0 release](https://github.com/PrefectHQ/prefect/releases/tag/2.16.0) reverted the change.

Do we want to close this issue or keep it open?

**Comment by zhen0** [comment]
Since the changes in 2.15.0 are now reverted I am closing this in favor of [Allow for Tasks to run the on the Main Thread](https://github.com/PrefectHQ/prefect/issues/10627) so we can keep everything in the same issue.
