### ISSUE TITLE
Regression in UI: Missing JSON Input Option for Flow Parameters in New Release

### ISSUE THREAD

**Issue by Molaverdi** [PrefectHQ/prefect#12068]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The latest update to the Prefect UI has removed the ability to input flow parameters as JSON directly, a feature critical to our deployment pipelines. Previously, our workflows utilized the JSON input method extensively for specifying various parameters, but this option is no longer available in the updated UI.

### Reproduction

1.     Navigate to the "Deployments" section for a specific flow.
2.     Attempt to run a flow with parameters that were typically inputted via JSON in the "Parameters" section.
3.     Observe that the option to input parameters as JSON is missing, replaced by individual fields without the ability to add complex JSON objects directly.

### Error

-     The main issue is the absence of the JSON input option in the "Parameters" section of the flow run configuration.
-     No direct console errors related to this issue, but the functionality gap prevents the execution of flows that depend on JSON parameter input.

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by pleek91** [comment]
@Molaverdi you're referring to entering the entire parameters value as a single json object? We can add that. You are able to use json for each individual parameter in the new ui if that helps. There's a little menu to the right of each parameters label where you can select "use json". 

But if you want to enter the entire parameters value you'll wanna use the old ui until this issue is closed. You can click the link in the blue banner at the top to switch back on a per run basis. Or you can turn off the feature preview in user settings. 

Thanks for letting us know that is important to you!

**Comment by Molaverdi** [comment]
Indeed, I meant entering the entire parameters value as a single json object. Yes adding that would be greatly appreciated! In the meanwhile we are using the old UI :)

**Comment by AMontgomerie** [comment]
I would really like to have this feature in the new UI too. When testing and debugging I often want to rerun flows with minor parameter changes, and having to re-enter all of the parameters one at a time takes significantly longer than pasting the JSON from the previous run and modifying the parameter I want to change.

**Comment by pleek91** [comment]
@Molaverdi and @AMontgomerie you should be able to do this again in the enhanced deployment parameters ui. There's a menu to the right of the Parameters heading where you can switch between the form and json input methods. 

<img width="734" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/ea76764e-3c0b-4f7e-b40e-9d4e73f5af0b">

**Comment by quassy** [comment]
It would be more helpful if the JSON input was pre-filled with a json of the required parameters and also the optional parameters that have a default.
