### ISSUE TITLE
On the new UI, an Enum with two values is displayed as a text box, instead of a drop-down.

### ISSUE THREAD

**Issue by jruere** [PrefectHQ/prefect#12069]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

On the new UI, an Enum with two values is displayed as a text box, instead of a dropdown.

The default value is also not displayed.

The Enum is:

```python
from enum import Enum
import icontract

class OutputFileFormat(Enum):
    JSONLINES_GZIPPED = "jsonl.gz"
    XLSX = "xlsx"

    @icontract.require(lambda number_of_domains: number_of_domains > 0)
    def can_handle(self, number_of_domains: int) -> bool:
        match self:
            case OutputFileFormat.XLSX:
                max_domains = 1e6  # Slightly under Excel limit.
            case _:
                max_domains = 100e6  # Let's have some ansolute maximum.

        return number_of_domains <= max_domains
```

(I didn't actually check on a different browser, I lied on the checkbox.)

### Reproduction

Use this Flow:

```python
@flow(retries=0)
def main_flow(export_file_format: OutputFileFormat = OutputFileFormat.JSONLINES_GZIPPED) -> None:
    pass
```

Try to run it.

The default will not be shown.
The control will be a text box, instead of a dropdown.

### Error

![Quick Run screenshot](https://github.com/PrefectHQ/prefect/assets/1299142/2d203c3c-9b3d-4707-ab5c-1c61bceb12b1).

![Custom Run screenshot](https://github.com/PrefectHQ/prefect/assets/1299142/6443d83d-51d3-4309-8ae0-4d3720171861).

### Browsers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by pleek91** [comment]
@jruere thank you for the detailed issue (and for admitting you lied about the browsers checkbox 😂)

We definitely have enum support so I'll try and figure out what's going on with this specific example. 

If this is blocking you, the old ui is still available by clicking the link in the blue banner. Will update once I have more details here.

**Comment by jruere** [comment]
Yep, it used to work. I'll warn internal users. Thanks!

**Comment by pleek91** [comment]
@jruere I just released that fix out. Can you confirm for me that your enums are showing up correctly in the new ui?

**Comment by jruere** [comment]
@pleek91 it works! Thanks!
