### ISSUE TITLE
Doubtful about passing **kwargs as param

### ISSUE THREAD

**Issue by Joselinejamy** [PrefectHQ/prefect#1209]
Can i pass **kwargs to the overridden run() of a class extending prefect's Task class?. If so how to bind them with tasks ?. It's mentioned that *args cannot be passed. Is it the same for **kwargs also ?

Thanks in Advance

**Comment by cicdw** [comment]
Hi @Joselinejamy - yes you can use `**kwargs`; to bind a keyword with an upstream task, either call the task under a keyword argument as you normally would with the functional API, or use a `key` with the appropriate imperative method.  In the following example I use both patterns:

```python
from prefect import Task, Flow, Parameter

class ExampleKwargs(Task):
    def run(self, **kwargs):
        number = kwargs.get("number")
        word = kwargs.get("word")

        print("number is: {}".format(number))
        print("word is: {}".format(word))

kwargs = ExampleKwargs()
number = Parameter("number", default=42)
word = Parameter("word", default="towel")

with Flow("example") as flow:
    kwargs_copy = kwargs(number=number) # calling a task creates a copy that we need to capture
    kwargs_copy.set_upstream(word, key="word")

flow.run()
# number is: 42
# word is: towel
```

Also, in the future you can post questions such as this to our [new slack channel](https://t.co/UyS12hy3mO), and you'll probably get quicker responses.
