### ISSUE TITLE
A Pythonic way to publish Work Pool

### ISSUE THREAD

**Issue by mattiamatrix** [PrefectHQ/prefect#12091]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Infrastructure blocks can be published using `publish_as_work_pool`. Creating `Work Pool` is only possible in the UI or via the CLI, not in Python.

### Describe the proposed behavior

Define `Work Pool` with a pattern similar to that used to create Infrastructure blocks

### Example Use

```python
ECSWorkPool(...).save("...")
```

**Comment by serinamarie** [comment]
Hi @mattiamatrix, can you talk more about a use case for this?
