### ISSUE TITLE
Missing prefect deployment schedule set to replace prefect deployment set-schedule 

### ISSUE THREAD

**Issue by ddresslerlegalplans** [PrefectHQ/prefect#12104]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I've been using ```prefect deployment set-schedule ``` to change the schedule of an existing flow.  The code https://github.com/PrefectHQ/prefect/blob/b79891f68591901e960a774add3b6d1ec83962a4/src/prefect/cli/deployment.py#L636 mentions on line 636 in src/prefect/cli/deployment.py for the _set_schedule function to use ```prefect deployment schedule set``` , but when running help on that command it says there is no command for that

```bash
prefect deployment schedule set --help
Usage: prefect deployment schedule [OPTIONS] COMMAND [ARGS]...
Try 'prefect deployment schedule --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'set'.                                                                                                                         │
╰───────────────────────────────────
```

### Reproduction

```python3
prefect deployment schedule set --help
Usage: prefect deployment schedule [OPTIONS] COMMAND [ARGS]...
Try 'prefect deployment schedule --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'set'.                                                                                                                         │
╰───────────────────────────────────
```

### Versions

```Text
latest
```

**Comment by abrookins** [comment]
Let’s start with this: #12123 

It’s wordier than “set-schedule,” so perhaps we’ll find a better command over time that still makes sense in a multiple schedule world.
