### ISSUE TITLE
Deployment object in python sdk docs says all fields are required when they are not.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#12112]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

[Python SDK Deployment Docs](https://docs.prefect.io/latest/api-ref/prefect/deployments/deployments/#prefect.deployments.deployments.Deployment)

Schedule and tags are not required but they are listed as required in the defaults column:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/45b0191b-b347-46f9-bf35-70d771981b78)

### Describe the proposed change

^

**Comment by discdiver** [comment]
Closing as not planned because this Class is now deprecated. 
![Screenshot 2024-04-09 at 12 20 11 PM](https://github.com/PrefectHQ/prefect/assets/7703961/c760ebdc-b58c-4701-aa15-c02ff66c7b63)
