### ISSUE TITLE
Error when calling task.bind() with a dict, list, tuple or set as input

### ISSUE THREAD

**Issue by AnesBenmerzoug** [PrefectHQ/prefect#1211]
Given the following simple flow:

![image](https://user-images.githubusercontent.com/27914730/60793803-b3662f80-a168-11e9-8bcc-e787323314c5.png)

Creating it using the Functional and Imperative style results in an error in the second case:

```python
from prefect import Flow, task

@task
def print_dict(input_dict: dict):
    output = ""
    for key, value in input_dict.items():
        output += f"{key}, {value}; "
    print(output)

if __name__ == "__main__":
    with Flow("test flow") as flow:
        print_dict(dict(first_key="test1", second_key="test2"))
    state = flow.run()
    assert state.is_successful()
```
The functional style returns in the following: ```first_key, test1; second_key, test2;```

```python
from prefect import Flow, task

@task
def print_dict(input_dict: dict):
    output = ""
    for key, value in input_dict.items():
        output += f"{key}, {value}; "
    print(output)

if __name__ == "__main__":
    flow = Flow("test flow")
    flow.add_task(print_dict)
    print_dict.bind(dict(first_key="test1", second_key="test2"), flow=flow)

    state = flow.run()
    assert state.is_successful()
```
The imperative one fails on the call to bind with: ```ValueError: Could not infer an active Flow context.```

The same happens when using list, tuple or set.

The cause of it seems to be the  [```as_task()```](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/tasks.py#L44) function defined in [```prefect.utilities.tasks```](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/tasks.py).

It is called in the [```set_dependencies()```](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L745) method of the Flow class defined in [```prefect.core.flow```](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py).

The easiest way to fix this would be to add an optional ```flow``` keyword argument to the ```as_task()``` function.

I can work on that if that's alright.

**Comment by cicdw** [comment]
Hi @AnesBenmerzoug - thanks for the bug report!  Nice find.

After some consideration, I agree that adding an optional `flow` keyword to `as_task` is the best way forward - that'd be awesome if you want to submit a PR for it!  I'll leave this open for a while to give you some time to work on that if you'd like.
