### ISSUE TITLE
Count of running, failing or completed flows/deployments

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/prefect#12150]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the UI offers no easy way to see which flows or deployments are running smoothly or not. We show failed runs on the dashboard, but the failure may not be the latest run, so there's no indication if those are still relevant or not.

### Describe the proposed behavior

On the Flows and Deployments list, include counts of three general state buckets (hide if the count is zero) representing the state of the latest flow run:
- Running
- Failing
- Completed

Suggestion:
![image](https://github.com/PrefectHQ/prefect/assets/6776415/80e23155-32bd-4d50-b38b-878079a267b7)

These could be clicked to filter the list. The counts would adjust based on search or filter criteria on the right, just like the total count. I imagine if you had selected one, like "failing", then enter a search query, it's acceptable to clear the "failing" filter. After the query the user would see new counts and they could reapply one of the filters.

If this seems easy enough I'd be happy to mock something up for the dashboard as well, probably centered on flows.

### Example Use

Users could use the counts to quickly see if and which flows or deployments are currently failing. They could also deduce that a flow has recovered from failures if they have failed runs but no failing flows.

**Comment by yaronlevi** [comment]
@brandonreid This is great!

Would also be nice to put this information in the Dashboard:

![CleanShot 2024-03-04 at 17 27 21@2x](https://github.com/PrefectHQ/prefect/assets/5398977/9824ae0c-f5cc-4a9d-9a40-22b16dc3dc24)

Although this might a little bit tricky product-wise, since that currently the dashboard shows everything via a "time glasses" you pick at the top right corner.

And the this new widget is not time-bound.

**Comment by yaronlevi** [comment]
Also, maybe call the Failed (instead of Failing)? 🤔🙂

**Comment by WillRaphaelson** [comment]
I think we'd probably want to leverage the existing deployment status information for this unless im missing something. If we like that direction this could be a pretty quick win.

**Comment by yaronlevi** [comment]
Here is a fresh example of why it's important to show the "current" status of the job runs, WITHOUT choosing a time frame.

By mistake, I've picked "past week" in the filter and discovered that there is a run which is in a Canceling mode, for 6 days now:

![CleanShot 2024-03-17 at 14 55 09@2x](https://github.com/PrefectHQ/prefect/assets/5398977/62e3739f-49f3-490a-af29-b58e3419fe7e)

If, for example, this was a "running" state, we would be potentially paying for lots of compute hours and this would never be surfaced inside the orchestrator (Prefect).

So, to reiterate, there should be away to see all the runs/deployments that are currently running, regardless of time frame picked.

**Comment by WillRaphaelson** [comment]
We will satisfy this use case through a more flexible dashboard / analytical experience in the coming months.
