### ISSUE TITLE
Load environment off of flow attribute instead of querying for it

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1216]
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/execute.py#L32

**Comment by cicdw** [comment]
Now that I'm going to write some code ;) I see why this is tricky.  I don't necessarily know how to access the serialized flow here, it depends on the storage / environment.

**Comment by joshmeek** [comment]
@cicdw I see what you mean, let's sync back up and think this one through
