### ISSUE TITLE
Add optional flag in build_from_flow to remove files from S3 which are not included in flow code

### ISSUE THREAD

**Issue by voltaire-dta** [PrefectHQ/prefect#12180]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, when you create an S3 Storage Object for use in a Deployment creation (e.g. `build_from_flow`), Prefect overwrites files in S3 with the newest version of every file in the flow code, but if files are deleted from the flow code, it does not remove them in S3. 

### Describe the proposed behavior

The build_from_flow() function should have an optional parameter when you instantiate it which indicates it should delete any files which aren't included in the flow code from the underlying Storage object

### Example Use

When users are building an S3 Filesystem, they would specify a boolean flag called `del_outdated` or something along those lines, which would indicate that older files within all directories and subdirectories of the bucket path would be deleted when the flow code is pushed to that Filesystem. 

E.G. 
`storage = S3(bucket_path="path_to_bucket")
  Deployment.build_from_flow(
        flow=flow,
        name=f'{config.deployment_prefix}-{flow.name}',
        infrastructure=block,
        path="/",
        apply=True,
        schedule=schedule,
        storage=S3(bucket_path=f'{config.s3_base_path}/{env}/flow_code/'),
        del_outdated=True
    )`

### Additional context

This is really important for technologies like DBT (data-build-tool) whose inherent functionality is to loop through entire directories of code and run every file in the directory. With the current functionality, if files are removed in the flow code from a directory, Prefect does NOT remove them from S3 when the Deployment is created, meaning those files will continue to get run in the Prefect deployments. This is extremely problematic, and requires users to either write custom code to purge files from S3, or dynamically set the deployment code path to something different every time a Deployment is created. 

This would be problematic in ANY script which runs every file inside a given directory. 

More context here: 
https://prefect-community.slack.com/archives/C04DZJC94DC/p1709672369963199
https://prefect-community.slack.com/archives/CL09KU1K7/p1702659483529319

There are other relevant issues which are asking for this functionality in the `upload_to_storage()` function: 
https://github.com/PrefectHQ/prefect/issues/7486

**Comment by serinamarie** [comment]
Hi there @voltaire-dta, `build_from_flow` has been deprecated so we are going to close this issue as not planned. Thanks for your understanding!
