### ISSUE TITLE
Don't load all environment / storage classes eagerly

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1219]
Currently, the `__init__.py` files for environments and storage load all classes. By their nature, these classes come with heavy dependencies -- the `CloudEnvironment` alone adds one second to import time on my machine due to Docker-related dependencies. 

I'd like to propose that the `__init__.py` only loads the base `Environment` and `Storage` classes, and users can selectively import only the ones they need. This will improve performance (noticeably in import times) and also set a better precedent for future environments that have yet heavier dependencies. 

Taking this one step further, someone should be able to use Prefect without importing Docker to the point that maybe `Docker` should even move to `[extras]`?

**Comment by joshmeek** [comment]
#2046 addressed this by deferring imports of slower packages
