### ISSUE TITLE
Support hyperlinks in table artifact

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#12222]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Hyperlinks in table artifacts are currently rendered as text and are not highlighted or clickable. Using anchor tags also does not work, the anchor tags are also rendered directly as text.

For my use case I am trying to include links to subflow runs - I know this is already possible in the Subflows tab, but the artifacts I am creating are to group those subflows based on information useful to the user, so the raw list of Subflows isn't the solution. The current output looks like this, causing the table to overflow the page. I currently include `flow_run_id` only, as it's easier to copy that into any open flow run page's address bar than to copy the huge url and then paste it.

![image](https://github.com/PrefectHQ/prefect/assets/8505845/ade58ca4-a254-4103-bcec-79bb62f56f10)

### Describe the proposed behavior

I would love to see support for displaying hyperlinks properly, with the `p-link` css class and the actual URL hidden - ideally the user would be able to choose the text, but I'd also be okay with just a default value of "Link" or something.

![image](https://github.com/PrefectHQ/prefect/assets/8505845/a95002ee-316c-4c90-9dbd-773fbb91da95)

### Example Use

The simpler option would be to just set a default value for the UI to display and just use pattern matching to detect if it's a link, potentially with an optional argument to `create_table_artifact` that disables the new functionality. The other option I could see is requiring the user to pass in a properly formed anchor tag and only render those as hyperlinks.

```python
    async def create_by_overall_state_artifacts(self):
        self.logger.info("Creating 'by state' runs artifact")
        runs_dict = self.get_state_runs_dict()
        for state, runs in runs_dict.items():
            curr_state_name = state.value.lower()
            if curr_state_name == "no_runs":
                curr_state_name = "missing"
            curr_flow_runs_list: list[dict] = []
            for cm, flow_runs in runs.items():
                curr_flow_runs_list.extend(create_flow_run_records(cm, curr_state_name, flow_runs))

            description = f"Flow runs: {len(curr_flow_runs_list):,}"

            await create_table_artifact(
                curr_flow_runs_list, key=f"{self.integration}-monitor-{curr_state_name}-runs", description=description
            )

def create_flow_run_records(
    client_model: ClientModel, overall_state: ClientState | str, flow_runs: list[FlowRun]
) -> list[dict[str, str]]:
    # nesting this inside create_flow_run_records lets us use the outside values without having to pass them
    def _create_record(flow_run_state: StateType | None = None, flow_run_id: UUID | None = None) -> dict[str, str]:
        val = {
            "client_id": str(client_model.client_id),
            "client_db": client_model.db_name,
            "client_group_state": ensure_str(overall_state),
            "flow_run_state": ensure_str(flow_run_state),
            "flow_run_id": ensure_str(flow_run_id),
        }
        if flow_run_id:
            val["flow_run_url"] = get_flow_run_url(flow_run_id)

            # or perhaps
            # url = get_flow_run_url(flow_run_id)
            # val["flow_run_url"] = f'<a href="{url}">{flow_run_id}</a>'

        return val

    if not flow_runs:
        return [_create_record()]

    return [_create_record(fr.state_type, fr.id) for fr in flow_runs]
```

### Additional context

I have several "conductor" flows that run each day that pull a list of clients to execute a sub flow run for. Because these kick off some hundred flow runs and some of them may fail or may run long we have a second flow that runs every 15 minutes to check the status of them - the table artifacts I'm creating are used for troubleshooting, e.g. table artifact that shows all of the clients that are successful (e.g. they may have two failed flows but the last flow succeeded so they are successful, we don't care anymore about the failed flows). This is why the subflows tab doesn't work for us, because it just lists all of them without context.

For the artifact tables that show failed or incomplete flow runs, I want to be able to click directly to the flow run page to investigate it, but the table artifacts currently don't make that possible.

**Comment by znicholasbrown** [comment]
Hi @NodeJSmith - this is a great idea and is _technically_ possible today, but not with the table artifact, you'd need to convert your table to a markdown artifact (not tough but also not great for code quality, I'm sure). I'm going to look into the renderer and see if there's a way we can make this happen, will report back 👍🏻

**Comment by znicholasbrown** [comment]
Ok @NodeJSmith - this should be available shortly, with some additional features to boot 😄

**Comment by znicholasbrown** [comment]
This is now available in Prefect Cloud and will be available in the UI of the next release of this package as well!

**Comment by NodeJSmith** [comment]
Amazing, thank you!

**Comment by NodeJSmith** [comment]
@znicholasbrown I don't think this is working as I had expected, can you let me know if I'm doing something wrong? I am creating a markdown url in the table data, example of the raw data below, but the actual link in the table is being prepended with the artifact url. In dev tools it looks like the first part of the url is being stripped, so the frontend is prepending the parent of the current path?

Raw data example:
```json
  {
    "client_id": "1",
    "client_db": "ClientDBName",
    "client_group_state": "INCOMPLETE",
    "flow_run_state": "RUNNING",
    "flow_run_id": "[display value](https://app.prefect.cloud/account/<account>/workspace/<workspace>/flow-runs/flow-run/<flow-run-id>)"
  },
```

Inspector:
![image](https://github.com/PrefectHQ/prefect/assets/8505845/647f8243-4735-45fd-8cba-6752ad2f3a34)

Rendered url:
```txt
https://app.prefect.cloud/account/<account>/workspace/<workspace>/artifacts/artifact/https://app.prefect.cloud/account/<account>/workspace/<workspace>/flow-runs/flow-run/<flow-run-id>
```

**Comment by znicholasbrown** [comment]
hi @NodeJSmith - sorry you're running into that; i'm not able to reproduce, any chance you're in the slack community and you can DM me those URLs/unredacted screenshots?

**Comment by NodeJSmith** [comment]
@znicholasbrown Sorry for the delayed response, was stuck on something else for the last few days. Yeah I'm on the Slack, I can DM them - what's your username on there?

**Comment by znicholasbrown** [comment]
Hi @NodeJSmith - my name in the Slack community is `nicholas` - you'll see a little yellow Prefect logo by my name
