### ISSUE TITLE
Bug: Copy to new run doesn't preserve boolean value

### ISSUE THREAD

**Issue by quassy** [PrefectHQ/prefect#12264]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using the UI to copy a flow that was started with a boolean that is `True` to a new run, the parameter is set to `False` in the Prefect Cloud UI.

<img width="94" alt="image" src="https://github.com/PrefectHQ/prefect/assets/369996/f666e20f-2973-46e3-85e9-eec4be4767fc">

### Reproduction

```python3
@flow()
def pipeline(
    param: str | bool,
) -> None:
    print(param)
```

### Versions

```Text
Version:             2.15.0
API version:         0.8.4
Python version:      3.10.13
Git commit:          e90804b8
Built:               Thu, Feb 15, 2024 2:54 PM
OS/Arch:             darwin/arm64
Profile:             martin
Server type:         cloud
```

**Comment by zhen0** [comment]
Closing as a duplicate.  Please do let us know if you think this is still an issue (after tomorrow's release).

**Comment by quassy** [comment]
Confirmed to be fixed.
