### ISSUE TITLE
Investigate 3.5 test failure

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1230]
In https://github.com/PrefectHQ/prefect/pull/1228 I noticed there was a test that randomly and somewhat mysteriously fails in Python 3.5.  It's possibly due to the way mocking / mock state is implemented in 3.5, but I'd like to dig in a little and fully understand it.  The relevant test is:
```
tests/engine/cloud/test_cloud_flows.py::test_deep_map_with_a_retry
```

**Comment by lauralorenz** [comment]
We don't support 3.5 anymore, so closing.
