### ISSUE TITLE
different input while flow retry

### ISSUE THREAD

**Issue by 191220042** [PrefectHQ/prefect#12318]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

![image](https://github.com/PrefectHQ/prefect/assets/80091648/f314c778-618e-4775-ac25-45568069547a)
Hello, my code is as follows. When repeating this flow, I hope it will be processed as a new input, rather than repeating the same input twice.

### Describe the proposed behavior

I hope to be able to choose to modify the input in the first run as the second run.

**Comment by serinamarie** [comment]
Hi @191220042, thanks for creating your first issue with Prefect. This functionality exists by using the Prefect [runtime context](https://docs.prefect.io/latest/guides/runtime-context/):

```python
from prefect import flow, task

@task
def hello_world(name: str = "world"):
    print(f"hello {name}")

@flow(log_prints=True, retries=5)
def basic_flow():
    if flow_run.run_count == 1:
        print("This is the first run")
        raise ValueError("This is a failure")
    else:
        print("This is not the first run")
        hello_world()
```

Please feel free to join the [Prefect community slack channel](https://join.slack.com/t/prefect-community/shared_invite/zt-2ew8zcjt1-U4a72mLvo4qkbQWJCEt5Gg) :)
