### ISSUE TITLE
prefect client python sdk has the incorrect type for slot_decay_per_second in global concurrency controls

### ISSUE THREAD

**Issue by nkmst-altana** [PrefectHQ/prefect#12364]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

On the server, slot_decay_per_second is a `number` type. That means you can set a value to 0.1 via the UI, as shown in the docs here: https://docs.prefect.io/latest/guides/global-concurrency-limits/#slot-decay

The client side type is `int`, so when getting passed to the back end a number gets typecast to a float and you lose the thing you tried to set it to.

### Reproduction

```python3
await client.create_global_concurrency_limit(
  GlobalConcurrencyLimitCreate(
    name=RATE_LIMIT_NAME,
    limit=5,
    active=True,
    active_slots=0,
    slot_decay_per_second=0.1
  )
)

# Then verify in the UI that the set value was actually 0, not 0.1
```

### Versions

```Text
Version:             2.16.2
API version:         0.8.4
Python version:      3.12.1
Git commit:          e1c339db
Built:               Mon, Mar 4, 2024 4:55 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
```

**Comment by desertaxle** [comment]
Thanks for the issue @nkmst-altana! We've added this issue to our backlog and will fix it in a future release!

**Comment by hainenber** [comment]
hi folks, I've made a PR as an attempt to fix this. PTAL if you have time. Thanks!
