### ISSUE TITLE
Make default image tag `latest` (or None) for Docker storage

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1237]
Right now the image name and image tag are both random UUIDs. While this does mean that collisions are on the order of `(1 / the atoms in the universe) / the atoms in the universe`, having a random tag is probably redundant.

**Comment by cicdw** [comment]
Ideally we would auto-tag the image name with the flow ID itself, but there's a chicken / egg problem with that.

**Comment by jlowin** [comment]
Proposal:

`image:tag` -> `{flow.name}:{timestamp}`

**Comment by cicdw** [comment]
I love that.

**Comment by cicdw** [comment]
It looks like using `.isoformat()` or `str(timestamp)` violates the restrictions of docker tags, so we'll need to use something like `slugify.slugify(str(pendulum.now("utc")))`

**Comment by joshmeek** [comment]
Yeah I'm game for timestamp as default
