### ISSUE TITLE
update distributed to be < 3.0

### ISSUE THREAD

**Issue by knowsuchagency** [PrefectHQ/prefect#1238]
`distributed`'s `2.0` release was mostly deprecations. The current requirement prevents installs of `prefect` with projects that require more recent versions of the library i.e. those that use [`poetry`](https://poetry.eustace.io/) for version management

https://github.com/PrefectHQ/prefect/blob/4f56ceb492ddbc8ef91c1e9acd21d14f320d4cc3/requirements.txt#L5

**Comment by cicdw** [comment]
Hi @knowsuchagency - we're currently looking into this.  Right now we're finding that the newest version of distributed isn't compatible with [dask-kubernetes](https://github.com/dask/dask-kubernetes) which would cause some Flows to fail in Prefect Cloud.  Will update here when we've sorted it out!

**Comment by cicdw** [comment]
Other people have requested this, and we know of a work-around in Cloud to ensure `dask-kubernetes` still behaves correctly (and plan to open an issue there soon), so I've opened a PR to bump this version up!
