### ISSUE TITLE
error downloading flow code from storage

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#12409]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Happens in Prefect Cloud:

![CleanShot 2024-03-25 at 18 20 55@2x](https://github.com/PrefectHQ/prefect/assets/5398977/3afec831-1872-4dc2-8387-10c6e0f2ad8d)

![CleanShot 2024-03-25 at 18 22 03@2x](https://github.com/PrefectHQ/prefect/assets/5398977/cb78682c-825f-45f8-a0da-adf985dd65a2)

[[Link to Flow run](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/11e2ef44-c9b7-480a-96fe-a9451cba766b?tab=Details)](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/11e2ef44-c9b7-480a-96fe-a9451cba766b?tab=Details)

### Reproduction

```python3
Happens in Prefect Cloud
```

### Versions

```Text
Happens in Prefect Cloud
```

**Comment by yaronlevi** [comment]
Forgot to mention, we are using ECS push work pools.

**Comment by zhen0** [comment]
@yaronlevi - I believe this came from an [incident two weeks ago](https://prefect.status.io/pages/history/5f33ff702715c204c20d6da1) and is now resolved so I'm closing the issue.  Please feel free to re-open and tag me if you are still having issues.
