### ISSUE TITLE
attempting to run an image with a misspecified platform or architecture

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#12425]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Happens in Prefect Cloud.
Using ECS Push work pools.

![CleanShot 2024-03-26 at 10 47 11@2x](https://github.com/PrefectHQ/prefect/assets/5398977/1d18b228-416a-4d4d-9f0d-deda1c1bfd02)

![CleanShot 2024-03-26 at 10 56 25@2x](https://github.com/PrefectHQ/prefect/assets/5398977/b052f831-51c2-4b64-bbe2-ceb64582e9b4)

[Link to failed run](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/106c17e2-e1f7-4161-97b6-d40f5d372436?tab=Details)

Error:
```
Failed due to a ProcessFailed error in Prefect flow run infrastructure, possibly caused by attempting to run an image with a misspecified platform or architecture.
```

### Reproduction

```python3
Happens in Prefect Cloud.
Using ECS Push work pools.
```

### Versions

```Text
Happens in Prefect Cloud.
Using ECS Push work pools.
```

**Comment by yaronlevi** [comment]
@WillRaphaelson Just using ECS Push work pools with default setting. No dockers or anything like that.

**Comment by WillRaphaelson** [comment]
Thanks Yaron. Is this happening on all flows, one flow, or intermittently?

**Comment by yaronlevi** [comment]
@WillRaphaelson Happened just for this flow. One time (maybe two).

**Comment by WillRaphaelson** [comment]
Thanks Yaron, I'm unable to reproduce this at this time. If it happens again, we should dig into your ECS cluster, as I think the InfrastructureExitedNonZeroCode can happen for a few reasons.
