### ISSUE TITLE
Adjust SecretStr documentation to reflect pydantic v1 / v2 differences

### ISSUE THREAD

**Issue by 3XJuli** [PrefectHQ/prefect#12426]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The example of using a SecretStr at https://docs.prefect.io/latest/concepts/blocks/#secret-fields does not consider the usage of pydantic v2. If importing SecretStr as 
`from pydantic import SecretStr`
 One runs into the very obscure: 
``RuntimeError: no validator found for <class 'pydantic.types.SecretStr'>, see `arbitrary_types_allowed` in Config``

### Describe the proposed change

it should be 
`from pydantic.v1 import SecretStr` 
if and only if pydantic version >= 2.

**Comment by darrida** [comment]
I ran into this too, and only found the answer here after searching for a long time.
