### ISSUE TITLE
use `uv` for dependency installs in CI

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#12420]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

its significantly faster than pip

it does not offer `--upgrade-strategy eager` as a flag like we often use, but not sure if we absolutely need that exact resolution strategy for CI

if we do, we can wait and see what comes of [this](https://github.com/astral-sh/uv/issues/1419)

### Impact

cheaper, faster CI

**Comment by hainenber** [comment]
I think this was implemented in #12482. There were still `pip` usage in Windows and benchmark CI but they're not opened as frequent as `python-tests`. I think it's close-able?

**Comment by cicdw** [comment]
Yup I agree, this is closable now!
