### ISSUE TITLE
403 error in UI after upgrading to 2.16.6

### ISSUE THREAD

**Issue by z63** [PrefectHQ/prefect#12427]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

After upgrading from prefect 2.14.something to 2.16.6 :
- I first notice that UI was empty : no flow runs, no blocks, etc... No error message is provided 
- i then see that browser was receiving 403 response in POST request. Response for that request was "{"detail":"Missing CSRF token."}"
- emptying browser's cache was not a solution
- I noticed that upgrading prefect (with a simple pip -U prefect) does not upgrade the ui_build directory located in prefect's package path. I understand that this directory contains assets used in the UI

So as a workaround, I delete the ui_build directory, restart prefect server, clear cache and it was good.

Do you consider that behaviour as an expected behaviour ? How can I make prefect upgrade safer ?

### Reproduction

On a fresh virtual env :
```
pip install prefect==2.16.4
prefect server start
```
(stop server)
```
pip install -U prefect
prefect server start
```
Launch a web server and check network requests -> 403 response

### Error

"{"detail":"Missing CSRF token."}" in all post response in UI

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.16.6
API version:         0.8.4
Python version:      3.10.12
Git commit:          3fecd435
Built:               Sat, Mar 23, 2024 4:06 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by znicholasbrown** [comment]
Hi @z63 - thanks for the detailed report; I think you're correct we're not rebuilding the ui build directory on upgrade like we should. https://github.com/PrefectHQ/prefect/pull/12429 should resolve this for the next release. 

For anyone running into this in the meantime - @z63's workaround of clearing out the build folder is a good one.
