### ISSUE TITLE
Generate an event when a block value is updated via the UI.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#12448]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently when I update the values of a block from the UI it does not generate an event.

I _will_ however see events generated if I update a block through the Python SDK. This makes sense as all methods called on blocks generate events.

```python
from prefect.blocks.system import JSON
import time

my_new_block = JSON(value={"the_answer": 42})
my_new_block.save("my-wed-json-block", overwrite=True)
print('New block created!')

time.sleep(10)

updated_values = JSON(value={"the_answer": 43})
updated_values.save("my-wed-json-block", overwrite=True)
print('Block updated!')
```

![image](https://github.com/PrefectHQ/prefect/assets/68969861/ac3f58d2-6fd7-4331-a159-4e63e35eb728)

### Describe the proposed behavior

Ideally when I update the block via the UI, this should also generate an event.

![image](https://github.com/PrefectHQ/prefect/assets/68969861/4d8eb450-25d6-4354-af3b-5a69e2ca4b82)

### Example Use

Teams want to use a block being updated as a triggering event for a deployment. Updating block values through the UI is a way non-technical users can participate in work flow logic. We should support updates that come in from the UI.

**Comment by WillRaphaelson** [comment]
Per conversation with Taylor - we should explore other ways to accomplish the use case here, including human in the loop workflows and or kicking off flow runs from the UI.

**Comment by WillRaphaelson** [comment]
Per convo with user, going to use run deployment ui
