### ISSUE TITLE
The Notification Webhook is broken for a single Run State

### ISSUE THREAD

**Issue by kingabzpro** [PrefectHQ/prefect#12468]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When setting a notification on Prefect OSS Server, only "All run states" state can be used. Attempting to use any other state will result in an error "Error updating notification".

### Reproduction

When selecting Discord or Slack webhook option in notification, selecting any run states except "All run states" and pressing Save button results in an error: "Error updating notification".

### Here are my Notifications Settings

<img width="774" alt="Screenshot 2024-03-28 223525" src="https://github.com/PrefectHQ/prefect/assets/36753484/2b654e1d-f431-4957-bf80-2cf5a0c6eaa8">

### Here is the error

<img width="716" alt="image" src="https://github.com/PrefectHQ/prefect/assets/36753484/c19a9a99-c7b7-4704-b3c3-fb90532f5e0c">

### Here is the error on Slack Webhook

<img width="784" alt="image" src="https://github.com/PrefectHQ/prefect/assets/36753484/a0a7dd13-6ed0-4945-8760-3fcd0b68a14f">

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
Version:             2.16.3
API version:         0.8.4
Python version:      3.9.18
Git commit:          e3f02c00
Built:               Thu, Mar 7, 2024 4:56 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by zhen0** [comment]
This has already been resolved by https://github.com/PrefectHQ/prefect-ui-library/pull/2216 and is fixed in the latest version of Prefect.

**Comment by kingabzpro** [comment]
@zhen0 thank you. It is working for me.

![image](https://github.com/PrefectHQ/prefect/assets/36753484/8c3fd462-63f1-44fe-b678-3077ded694af)
