### ISSUE TITLE
Incompatible to import typing module with python prior to 3.5.2

### ISSUE THREAD

**Issue by gavincyi** [PrefectHQ/prefect#1247]
For example `TYPE_CHECKING` is not provided in module `typing` for python version == 3.5.0 or 3.5.1. Suggest to use MYPY to resolve the issue.

**Comment by cicdw** [comment]
So I've done some research on this and am unfortunately concluding that Prefect will only support version of Python >= 3.5.2 going forward.  Let me explain my reasoning:
- this issue alerted me to the fact that Prefect is not currently compatible with 3.5.1; this tells me not many people were trying to use Prefect with Python 3.5.1 or 3.5.0
- having to adhere to an older typing pattern has [maintainability issues moving forward](https://github.com/PrefectHQ/prefect/pull/1260#issuecomment-514211917)
- even with the change proposed in #1260, the Prefect library still isn't 3.5.1 compatible
- we currently use some additional typing patterns that aren't compatible with 3.5.1
- it appears that the `cloudpickle` library is not able to pickle some important objects in Prefect (specifically I noticed `triggers` were not pickling correctly); this is critical for dask execution + deploying to Prefect Cloud

I'm very sorry for any inconvenience this might cause you!

I'm going to leave this issue open until I've updated our documentation and requirements to reflect this decision.
