### ISSUE TITLE
prefect deployment with gcs-bucket storage block loading into bucket incorrectly

### ISSUE THREAD

**Issue by jhendricks-elevate** [PrefectHQ/prefect#12487]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I currently use prefect deployment build with the gcs storage block. I switched to using gcs-bucket because gcs is being deprecated. When I ran the deployment build without an input for the optional Bucket Folder, i got a NoneType error. When I added a bucket folder the files were loaded two levels down. For example, if i said Bucket Folder = scripts then the files would be loaded into bucket/scripts/scripts From there, if I tried to run the deployment I would get an error that prefect was unable to find the file to run

### Reproduction

```python3
prefect deployment build python_script.py:pythn_flow -n flow-example -sb gcs-bucket/prefect-example -ib docker-container/adaptive -p a-workpool -q default -a

without a Bucket Folder would cause the error TypeError: expected str, bytes or os.PathLike object, not NoneType

When I fill that Bucket Folder spot it would land the files prefect-example/scripts/scripts even though i just put "scripts"
 
From there, when i try to run the deployment prefect can't find the file.
prefect.exceptions.ScriptError: Script at 'duluth_adaptive_versions.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
```

### Versions

```Text
2.11.4
```

**Comment by desertaxle** [comment]
Thanks for the issue @jhendricks-elevate! Could you please provide some sample code for the blocks you used in the two scenarios where you encountered errors?

**Comment by jhendricks-elevate** [comment]
@desertaxle This code works when I use a gcs block instead of gcs-bucket. I tried again today with a different script and had the same issue. 
[script.txt](https://github.com/PrefectHQ/prefect/files/14964829/script.txt)
