### ISSUE TITLE
Rename `CloudEnvironment` -> `DaskKubernetesEnvironment`

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1250]
Couple of changes here:
1. Rename the environment
2. Allow it to be slightly more customizable. A good first step is allowing the # of min/max workers to be specified

**Comment by cicdw** [comment]
Just putting this here for lack of a better place: we should also remove the unnecessary layers from the environments/ submodule file structure.  For example, the remote environment should live in `src/prefect/environments/execution/remote.py`, not a deeper directory.
