### ISSUE TITLE
Bug: Override parameters not used in JSON view

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#12564]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When creating a new flow run via "Copy to new run", parameters from the previous run are preserved in the parameter input form.
However, when switching to the JSON input, they are reset to defaults.

### Reproduction

```
from prefect import flow

@flow
def main(
        param: str = "foo",
):
    pass


if __name__ == "__main__":
    main.serve(
        name='default',
    )
 ```
 
- Run the above script (and so create a new deployment)
- Navigate to the deployment page, click "Run" -> "Custom run"
- Change the param value (e.g. to "bar")
- Click run and navigate to the newly created run
- From the top-right context menu on the run page, click "Copy to new run"
- See changed value in input form (expected)
- Click on three-dot button at the top and switch to "Use JSON input"
- See original value "foo"

Same applies if parameters are passed to the deployment

```
from prefect import flow

@flow
def main(
        param: str = "foo",
):
    pass


if __name__ == "__main__":
    main.serve(
        name='default',
        parameters={"param": "bar"}
    )
 ```

When creating a custom run for this flow, the input form shows "bar" but the JSON input shows "foo".

### Error

![image](https://github.com/PrefectHQ/prefect/assets/11021147/ef225066-8072-45ec-a47d-2e711a01e9f1)
![image](https://github.com/PrefectHQ/prefect/assets/11021147/6e9b003a-5fa7-42f0-8cbc-94ca14604aee)

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.16.8
API version:         0.8.4
Python version:      3.10.12
Git commit:          11cb641c
Built:               Fri, Mar 29, 2024 11:01 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

possibly related to #12106

**Comment by pleek91** [comment]
@j-tr thanks for the feedback. I think the issue here is currently when switching from the form view to the json view it doesn't carry over the state of the form. Rather it just loads the default value for the parameters themselves (ignoring the deployment defaults). 

I'll look into this and report back.
