### ISSUE TITLE
Custom values of optional parameters not used in input form

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#12566]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When assigning a Pydantic model with custom values as default to a flow parameter, the default values of the model are displayed in the flow submission form instead of the custom values.

When switching to "JSON input", the correct custom values are displayed.

This is only happening with Pydantic 2 and optional parameters. With Pydantic 1 or non-optional parameters, everything works as expected.

### Reproduction

```
from prefect import flow
from pydantic import BaseModel, Field
from typing import Optional


class MyModel(BaseModel):
    param1: Optional[str] = Field(title="Param1", default="foo")


@flow
def main(
        param: MyModel = MyModel(param1="bar")
):
    pass


if __name__ == "__main__":
    main.serve(
        name='default',
    )
  ```
  
- Run the above script (and so create a new deployment)
- Navigate to the deployment page, click "Run" -> "Custom run"
- See "foo" (the model default) in input form
- Click on three-dot button and switch to "JSON input"
- See "bar" (the custom assigned default)

### Error

![image](https://github.com/PrefectHQ/prefect/assets/11021147/efdbaf31-b605-4c08-9a7d-943c263391bc)
![image](https://github.com/PrefectHQ/prefect/assets/11021147/c3429aa9-7e98-42ab-858e-a9badb15c4dc)

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.16.8
API version:         0.8.4
Python version:      3.10.12
Git commit:          11cb641c
Built:               Fri, Mar 29, 2024 11:01 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

possibly related to https://github.com/PrefectHQ/prefect/issues/12106 and #12564

**Comment by pleek91** [comment]
@j-tr thank you! I wrote a fix for this that will go out with our next release.

**Comment by j-tr** [comment]
@pleek91 thanks for the fix, but i think there's still something missing.

The JSON view on the lowest level is still not correct in Prefect 2.18.0

As expected :heavy_check_mark: 
![image](https://github.com/PrefectHQ/prefect/assets/11021147/b102787d-cd83-434c-92fe-9b69b9d8dd48)

As expected :heavy_check_mark: 
![image](https://github.com/PrefectHQ/prefect/assets/11021147/47f0b0af-a453-4c78-a25f-45212faab438)

As expected :heavy_check_mark: 
![image](https://github.com/PrefectHQ/prefect/assets/11021147/3eb2ba80-2cfd-4c74-ba82-f53a1e254bc8)

Not expected :x: 
![image](https://github.com/PrefectHQ/prefect/assets/11021147/d6e9f8dd-faa7-49f0-b93d-8abaedf6f9fe)


Also in some cases, toggling between JSON and form views on different levels changes the values in the form.
![output](https://github.com/PrefectHQ/prefect/assets/11021147/0907adc1-eba4-4182-b9a7-feacc123746f)
As illustrated in the screencast, we start with the field value "bar" and change it to "foo" just by toggling back and forth on different levels.

Please reopen.
