### ISSUE TITLE
flaky "ModuleNotFoundError caused by missing module" "no module named" in Prefect Cloud + ECS push work pools

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#12716]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using Prefect Cloud + ECS push work pools.

Suddenly we get this runtime error: `no module named infisical_client `

![image](https://github.com/PrefectHQ/prefect/assets/5398977/5db6c2ce-a5d7-408b-b243-dfa96d10a6f3)

There is nothing special about that module (infisical_client), it was just the first one to be imported during run time. It would happen to any library we would try to import.

The error started at around 2024/04/13 01:00 AM Israel Time. At that time all runs that started, failed immediately because of this error (about 50 fails). After about 1-2 hours, the error disappeared and everything was back to normal.

![image](https://github.com/PrefectHQ/prefect/assets/5398977/fdef2338-c50b-44e7-87a0-2c55f647f8d8)

We didn't touched any config in Prefect Cloud, or changed anything in our source code. This all happened by itself and then was back to normal (no changes to requirements.txt or anything. Nothing).

Here is one of the [failed runs](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/c6eedd5e-16ab-4f2c-9ff3-ec71d5fc471d).

   
 

### Reproduction

```python3
Prefect cloud + ECS push work pools
```

### Error

```python3
Failed due to a ModuleNotFoundError caused by missing module infisical_client

No module named 'infisical_client'
```

### Versions

```Text
Prefect cloud + ECS push work pools
```

**Comment by yaronlevi** [comment]
Just happened again:
![CleanShot 2024-04-15 at 17 33 34@2x](https://github.com/PrefectHQ/prefect/assets/5398977/4b39de6a-ed2c-4b69-a99e-1513e9959bb5)

**Comment by desertaxle** [comment]
Thanks for the issue @yaronlevi! How are you defining which packages should be installed for your deployment run(e.g. setting `EXTRA_PIP_PACKAGES`, using a pull step, building dependencies into an image)?

**Comment by yaronlevi** [comment]
@desertaxle So it turns out those errors happened because we had another agent that was "stealing" runs from the **default** work queue and causing all those flaky problems. Once we've deleted this agent, everything is back to normal.

This was solved by the help of Kevin Grismore who mentioned:

> "there is a bug I have seen a few times recently where that agent "steals" flow runs from a different work pool's default queue, causing intermittent failures"
