### ISSUE TITLE
Lists of integer parameters are not correctly copied to new runs of a deployment

### ISSUE THREAD

**Issue by jacobwhall** [PrefectHQ/prefect#12756]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

In the Prefect UI, lists of integers (and possibly other types?) do not copy correctly between runs when default parameters are set for that deployment.

### Reproduction

1. Create a work pool called "default" for the purposes of this test. I don't believe the type of pool matters to recreate this error, but I am using a Kubernetes work pool.
2. Run the following code to create a test deployment:
  ```python
  from prefect import flow
  from typing import List
  
  
  @flow
  def test_flow(numbers: List[int]):
      for n in numbers:
          print(n)
  
  
  test_flow.deploy(
      name="test deployment",
      work_pool_name="default",
      image="prefecthq/prefect:2-python3.10",
      parameters={
          "numbers": [1, 2, 3, 4, 5],
      },
      build=False,
  )
  ```
3. Visit [app.prefect.cloud](https://app.prefect.cloud), click on "Deployments" and then "test deployment", and then click on "Run" and "Custom Run"
4. Observe that the default parameters, the numbers 1 through 5, correctly display in the UI.
5. Delete the first couple of numbers from the list, and run the deployment.
6. Open that deployment run you just submitted, and click on the three dots on the top right of UI, and then click on "Copy to new run."
7. Observe that the copied list of integers is incorrect.

### Error

Here is what the list of default parameters for this deployment looks like when I **first open the deployment for a custom run:**
![Screenshot from 2024-04-16 13-46-54](https://github.com/PrefectHQ/prefect/assets/55111303/921312e4-9248-41f9-a15b-e564d92a5c7a)

Here is the list of parameters **as I submitted them, after deleting two from the list:**
![Screenshot from 2024-04-16 13-47-20](https://github.com/PrefectHQ/prefect/assets/55111303/d55feea3-422e-4cf8-9f70-804490d9f56f)

Here is the list of parameters **that appears when I copy that submitted run from before to a new run:**
![Screenshot from 2024-04-16 13-47-42](https://github.com/PrefectHQ/prefect/assets/55111303/bdab03bc-1844-4801-a930-8dcaa9447981)

As you can see, it does not make sense for there to be another 3 and 4 in this list.

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.14.21
API version:         0.8.4
Python version:      3.8.13
Git commit:          9a059bfe
Built:               Thu, Feb 8, 2024 5:35 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by jacobwhall** [comment]
I just confirmed that the erroneous list is indeed submitted to the new run if the user does not intervene:

![Screenshot from 2024-04-16 13-58-13](https://github.com/PrefectHQ/prefect/assets/55111303/b00683c1-a12d-4334-84fe-daf15c0849c8)

**Comment by pleek91** [comment]
@jacobwhall thank you for reporting this. I am able to reproduce. I'll figure out a fix for this and get it out with the next release.
