### ISSUE TITLE
Failed to generate job configuration Server error '500 Internal Server Error'

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#12809]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Got this error on Prefect Cloud + ECS Push work pools.

```
Failed to generate job configuration: Server error '500 Internal Server Error' for url '[http://orion-internal:4200/api/accounts/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspaces/8ff919f1-a2c3-4660-9ab5-66b57758d46d/block_documents/c262f11f-d09b-4d0f-a13b-cfdc05f10390?include_secrets=true'](http://orion-internal:4200/api/accounts/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspaces/8ff919f1-a2c3-4660-9ab5-66b57758d46d/block_documents/c262f11f-d09b-4d0f-a13b-cfdc05f10390?include_secrets=true%27)
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
```

`Failed due to a Server error '500 Internal Server Error' when attempting to generate job configuration. The error occurred during a call to a specific URL related to a Prefect flow.
`

![CleanShot 2024-04-20 at 09 16 59@2x](https://github.com/PrefectHQ/prefect/assets/5398977/dd7ea247-93a4-48bd-8f6c-2d482126b637)

Link to the crashed run:
[](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/19863a8b-0311-4609-9db3-c961cf7d8dac)

### Reproduction

```python3
Got this error on Prefect Cloud + ECS Push work pools.
```

### Error

```python3
Got this error on Prefect Cloud + ECS Push work pools.
```

### Versions

```Text
Got this error on Prefect Cloud + ECS Push work pools.
```

**Comment by jakekaplan** [comment]
Hi @yaronlevi thanks for filing this issue! I tracked down this failure to an intermittent issue with our cloud provider. It definitely shouldn't be leading to any run crashes. We'll get that patched up and I'll leave this issue open until that is resolved.
