### ISSUE TITLE
Create new SideCar Environment

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1281]
In addition to auditing our Docker tasks, we should create a new "Side Car Environment" (_or_ simply add appropriate kwargs to `RemoteEnvironment`, although this might have compatibility issues with non-k8s deployments) which spins up a side car for k8s jobs making it easier / more off-the-shelf to run Docker tasks in Cloud.

**cc:** @joshmeek

**Comment by joshmeek** [comment]
How specific is this sidecar environment? Static where we have (e.g.) a DockerSideCarEnvironment where it attaches a docker daemon or more generic where you can just specify a pod/container spec to use.

**Comment by cicdw** [comment]
Depends on what you think is reasonable; I think we could have a docker spec for specifically using our Docker tasks, but still leave the environment completely configurable for what the side car contains -- what do you think of that?

**Comment by joshmeek** [comment]
I'm down for that. So it can be specifiable but we have some documentation on commonly used sidecars?

**Comment by cicdw** [comment]
Yea! And even more, we might include some actual template files ¯\\\_(ツ)\_/¯

**Comment by joshmeek** [comment]
This was mostly addressed through documentation revolving around deployment patterns e.g. https://docs.prefect.io/cloud/recipes/k8s_docker_sidecar.html
