### ISSUE TITLE
JSON input / Form input mismatch

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#12817]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Under certain conditions, the parameter input form for flow runs does not contain the expected default parameters.
When toggling to JSON inputs and back to the input form, values are changed to model default parameters instead of flow run default parameters.``

### Reproduction

```python
import enum
from typing import Optional

from prefect import flow
from pydantic import BaseModel, Field

MyEnum = enum.Enum("MyEnum", {(k, k) for k in ["foo", "bar"]})

class MyModel(BaseModel):
    subparam1: str = Field(default="foo")
    subparam2: Optional[str] = Field(default="foo")
    subparam3: MyEnum = Field(default=MyEnum.foo)
    subparam4: Optional[MyEnum] = Field(default=MyEnum.foo)
    subparam5: Optional[int] = Field(default=None)  # Condition 1: we need an Optional parameter with default None here to trigger the bug

MyEnum2 = enum.Enum("MyEnum2", {(k, k) for k in ["foo", "bar"]})

class MyModel2(BaseModel):
    subparam1: MyEnum2 = MyEnum2.foo

@flow
def main(
    param1: MyModel2,  # Condition 2: we also need a second parameter here that has a field that is an enum to trigger the bug
    param2: MyModel = MyModel(subparam1="bar", subparam2="bar", subparam3="bar", subparam4="bar")
):
    print(param2)


if __name__ == "__main__":
    main.serve(
        name='default',
    )
```

- Run the above script to create a deployment
- Navigate to the Run deployment page
The input form presents like this
![image](https://github.com/PrefectHQ/prefect/assets/11021147/4fe0962f-1fd5-46fb-971a-8af534f4e64a)
- Required Param2->Subparam1 and Param2->Subparam3 are empty even though a default value "bar" was provided
- Optional Param2->Subparam2 and Param2->Subparam4, in contrast, are set to the expected default.

When toggling to JSON input and back to Form input the form presets like this
![image](https://github.com/PrefectHQ/prefect/assets/11021147/627fc0a6-305f-4e00-b088-9d9c6591de90)
- All values are set to the Model default "foo" instead of the expected default "bar"

This behavior could only be observed if there is at least one Optional parameter with default value "None" as part of the same model and another parameter that has an Enum field. If any of the two conditions are not met (try commenting out any of the two lines with comments), the bug won't appear.

### Error

This behavior has a high impact on our production systems as it frequently causes flow runs with unexpected parameters, resulting in unnecessary delays and cost.
Especially for flows with large numbers of parameters, operators rely on the correctness of the default parameters. Having to double-check each parameter before submitting, is a tedious and error-prone process.

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.18.0
API version:         0.8.4
Python version:      3.10.12
Git commit:          1006d2d8
Built:               Thu, Apr 18, 2024 4:47 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

related to #12564

**Comment by zzstoatzz** [comment]
hi @j-tr - thank you for the issue. I have reproduced this - we'll take a look at this

**Comment by pleek91** [comment]
@j-tr this is what I'm seeing with [this](https://github.com/PrefectHQ/prefect-ui-library/pull/2344) fix applied. Which looks correct to me. We'll get that merged and released in the next day or so. 

<img width="812" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/37e6fdcb-79b1-4891-96d7-01d8231f93c6">
