### ISSUE TITLE
Add tests for all prompt defaults in `prefect deploy`

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#12835]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

We should ensure that across the board, we ensure all of our defaults work in interactive `prefect deploy` for good practice and also so we don't stumble upon these types of issues in the future:
https://github.com/PrefectHQ/prefect/issues/12834

**Comment by Norman-Lee** [comment]
Hey @serinamarie mind if I pick up this ticket? Need some python development practice.
