### ISSUE TITLE
prefect login regression

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [PrefectHQ/prefect#12859]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Since https://github.com/PrefectHQ/prefect/pull/12717 when we login to Prefect (in CircleCI), the wrong workspace is actually used:
![image](https://github.com/PrefectHQ/prefect/assets/8518288/8e955910-58be-405e-bff6-1e8be99934ae)

notice how I select the workspace `headspace/staging`, however `headspace/prod` is logged into.

### Reproduction

```python3
prefect cloud login --key ${PREFECT_SERVICE_ACCOUNT_KEY} --workspace headspace/staging
```

### Versions

```Text
Version:             2.17.1+25.g7eadf91cbc
API version:         0.8.4
Python version:      3.11.6
Git commit:          7eadf91c
Built:               Mon, Apr 15, 2024 9:47 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
hi @ConstantinoSchillebeeckx - i have reproduced this, thanks for raising. will take a look
