### ISSUE TITLE
prefect-aws v0.4.15 does not bundle a LICENSE file

### ISSUE THREAD

**Issue by peterbygrave** [PrefectHQ/prefect#12916]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

With the move of prefect-aws to the core repo the pypi package no longer includes a LICENSE file.

One can compare the source distributions:
- https://pypi.org/project/prefect-aws/0.4.14/#files
- https://pypi.org/project/prefect-aws/0.4.15/#files

I suspect the same issue might be present in the other integrations recently moved to core repo.

Many thanks

### Reproduction

```python3
curl -s -L  https://pypi.io/packages/source/p/prefect-aws/prefect_aws-0.4.15.tar.gz | tar -tv \*LICENSE
```

### Error

```python3
tar: *LICENSE: Not found in archive
tar: Error exit delayed from previous errors.
```

### Versions

```Text
% prefect version
Version:             2.17.1
API version:         0.8.4
Python version:      3.10.14
Git commit:          d6bdb075
Built:               Thu, Apr 11, 2024 6:58 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         cloud
```

### Additional context

Showing that previous version worked:
```
% curl -s -L  https://pypi.io/packages/source/p/prefect-aws/prefect_aws-0.4.14.tar.gz | tar -tv \*LICENSE
-rw-r--r--  0 runner docker  11356 17 Apr 15:59 prefect_aws-0.4.14/LICENSE
```

**Comment by desertaxle** [comment]
Thanks for the issue @peterbygrave! You are correct that this is due to our code migration. We will resolve this as soon as possible.
