### ISSUE TITLE
TypeError: type 'State' is not subscriptable in prefect-dask task_runner

### ISSUE THREAD

**Issue by jaceiverson** [PrefectHQ/prefect#12963]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When attempting to import the DaskTaskRunner we get the following error:

MacOS with Python 3.10 and 3.11
```
venv/lib/python3.11/site-packages/prefect_dask/task_runners.py:256: in DaskTaskRunner
    call: Callable[..., Awaitable[State[R]]],
E   TypeError: type 'State' is not subscriptable
```

Inside GitHub actions ubuntu 2-core with Python3.10
```
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect_dask/task_runners.py:257: in DaskTaskRunner
    call: Callable[..., Awaitable[State[R]]],
E   TypeError: 'ModelMetaclass' object is not subscriptable
```

### Reproduction

```python3
from prefect_dask.task_runners import DaskTaskRunner
```

### Error

```python3
from prefect_dask.task_runners import DaskTaskRunner
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect_dask/__init__.py:2: in <module>
    from .task_runners import DaskTaskRunner  # noqa
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect_dask/task_runners.py:90: in <module>
    class DaskTaskRunner(BaseTaskRunner):
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/prefect_dask/task_runners.py:257: in DaskTaskRunner
    call: Callable[..., Awaitable[State[R]]],
E   TypeError: 'ModelMetaclass' object is not subscriptable
```

### Versions

```Text
Prefect Version 2.18.1
```

### Additional context

These errors aren't happening on Prefect 2.18.0.

**Comment by zzstoatzz** [comment]
hi @jaceiverson - thank you for the issue!

this should be fixed in the newest version of `prefect-dask`, released about a half hour ago

**Comment by jaceiverson** [comment]
Confirmed on my side. After updating to prefect-dask==0.2.8 the issue was resolved. Thanks for the quick update.
