### ISSUE TITLE
Kubernetes jobs' log couldn't print in prefect UI

### ISSUE THREAD

**Issue by nextvirus** [PrefectHQ/prefect#12993]
# Expectation / Proposal
I  run a Kubernetes job useing  func run_namespaced_job, but my prefect-ui couldn't show the job's log.
# Traceback / Example
I saw the code of the jobs.py. I found this code. If my job interval_seconds is 5s , my pod successed in 10s,  pending time is 2s and the pod log  output in 7s, the first phase of   interval_seconds  my pod will jion the pod_logs.keys, but it didn't have the log, it will show like this `{'bidding-hunter-test-tc6xs': ''}` ,then the second phase of interval_seconds ,the pod has log, but it couldn't add the log to the dict.

 ```
for pod in v1_pod_list.items:
                pod_name = pod.metadata.name

                if pod.status.phase == "Pending" or pod_name in self.pod_logs.keys():
                    continue
```
- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-kubernetes/#contributing) a pull request to resolve this!

**Comment by netanelm-upstream** [comment]
@nextvirus 
Is there any workaround for that?
I am also facing it.
