### ISSUE TITLE
DaskExecutor

### ISSUE THREAD

**Issue by elypma** [PrefectHQ/prefect#1299]
Hi,

I am trying to get a grip on environments and the way they are used with a flow.
```
   _env = prefect.environments.RemoteEnvironment(
        executor="prefect.engine.executors.DaskExecutor",
        executor_kwargs={"address": "tcp://10.0.0.53:8786"},
    )
    #
    # Define the flow
    with prefect.Flow(name, environment=_env) as _flow:    
        _r0 = inc.map(range(1000))
        _r1 = dec.map(range(1000))
        _r2 = add(_r1, _r0)

    _flow.run()
```
I started a local dask cluster but somehow the flow is not trying to use this local cluster.
Can you provide a simple example showing how to use a DaskExecutor together with an environment and a local dask-scheduler (with a few dask-workers)

Thx in advance.

**Comment by cicdw** [comment]
Hi @elypma - great question; environments are only really required / used when executing your Flow on Prefect Cloud.  To run your above example locally on a Dask cluster, you have two options:

#### Create an Executor directly

```python
from prefect.engine.executors import DaskExecutor

executor = DaskExecutor(address="tcp://10.0.0.53:8786")

...

flow.run(executor=executor)
```

#### Set environment variables prior to your python session
Before opening your python / ipython session, you can also set the following environment variables to make _all_ Flows run on your Dask cluster:
```
export PREFECT__ENGINE__EXECUTOR__DEFAULT_CLASS="prefect.engine.executors.DaskExecutor"
export PREFECT__ENGINE__EXECUTOR__DASK__ADDRESS="tcp://10.0.0.53:8786"
```
and then `flow.run()` will do what you want.

Some of this is detailed in [this dask tutorial](https://docs.prefect.io/guide/tutorials/dask-cluster.html).

Your environment definition would be correct for deploying this Flow to Cloud and then having it run next to a Dask cluster with the provided address.
