### ISSUE TITLE
Feature: support sparse checkout

### ISSUE THREAD

**Issue by rudeb0y** [PrefectHQ/prefect#13017]
On large mono repos, it may not be desirable to checkout the entire repo.

Using sparse checkout it's possible to just do a partial clone.

```
 command = f"""git clone \
                --depth 1 --sparse \
                --no-checkout \
                https://{secret_block.get()}@github.com/{ORG}/{REPO}.git; \
                cd {REPO} && \
                git checkout master && \
                git sparse-checkout set {sub_directory}
                """
 ```
 
 I would imagine there would be an option to supply a `sub-directory` and if supplied the clone would work like the above

**Comment by cicdw** [comment]
Closing in favor of the newly opened #15185 (both are identical requests, just trying to keep things tidy 👍 )
