### ISSUE TITLE
Feature Request: Create Worker pull step compatible with GitLab repositories

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/prefect#13115]
Currently GitLab repositories and repository blocks configured with access credentials are not compatible with Prefect Worker pull steps, because a GitLab repo url with credentials is formatted differently than what is generated during the generic `prefect.projects.steps.git_cone_repository` action. An custom step which handles `GitLabRepository` blocks and/or GitLab URLs is likely necessary for GitLab access with Workers.

**Comment by discdiver** [comment]
Closing as projects are no longer the preferred way to create a deployment and the Python `.from_source` and prefect.yaml options work with `GitLabCredentials` blocks. 

`GitLabRepository` blocks are for interacting with a repository. 

See the [docs](https://docs.prefect.io/latest/integrations/prefect-gitlab/) for more info.
