### ISSUE TITLE
Refreshing Work Pools page displays blank page

### ISSUE THREAD

**Issue by jbw-vtl** [PrefectHQ/prefect#13150]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

On the latest version of prefect (2.18.1), opening i.e. the /work-pools page works fine.
However as soon as the page is refreshed (i.e. by pressing F5), the content is lost and a blank page is displayed.

This was not an issue in the earlier version I was using (2.16.1).

The issue seesm to be limited to
`/flows`  
`/deployments`  
`/work-pools`  
`/notifications`

### Reproduction

Open the /work-pools page and refresh manually via F5

### Error

![image](https://github.com/PrefectHQ/prefect/assets/141396508/55e1ee3b-8536-4ed8-84a3-c23a676d2fbd)
After manually refreshing
![image](https://github.com/PrefectHQ/prefect/assets/141396508/a62c15fd-12e2-461d-b43f-7700562d9d2e)

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
2.18.1
```

**Comment by jakekaplan** [comment]
Hi @jbw-vtl, thanks for filing this issue. I can reproduce what you're seeing on the work pool page and have added it to the backlog.
