### ISSUE TITLE
Windows - Prefect GitHub `get_directory` does not clone any files to the `local_path`

### ISSUE THREAD

**Issue by tylerjthomas9** [PrefectHQ/prefect#13180]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to clone a GitHub repo inside of a flow, but when I run it on Windows, the repo is not cloned, and the destination folder is empty. 

I have tested my git installs, and both of them are able to clone the repo. 

### Reproduction
This code works on Ubuntu, but not windows.

```python3
from prefect_github import GitHubCredentials, GitHubRepository
repo_url = "https://github.com/PrefectHQ/prefect"
local_path = "./prefect"
repo = GitHubRepository(repository_url=repo_url)
repo.get_directory(local_path=local_path)
```

### Error

```python3
The `local_path` is an empty folder on Windows, and Ubuntu has a clone of the repo.
```

### Versions

```Text
Version:             2.18.1
API version:         0.8.4
Python version:      3.12.2
Git commit:          8cff545a
Built:               Thu, Apr 25, 2024 3:40 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql



Version:             2.18.1
API version:         0.8.4
Python version:      3.12.3
Git commit:          8cff545a
Built:               Thu, Apr 25, 2024 3:40 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

**Comment by AliaksandrTsurkoExtEF** [comment]
Adding quotes in the line 149 `cmd += f' "{tmp_path_str}"'` of `/prefect/src/integrations/prefect-github/prefect_github/repository.py` module `GitHubRepository` class `get_directory` method  should solve this issue (checked by me on windows). I've tried to push the fix PR here but has no permissions to do it.
