### ISSUE TITLE
Parameters appear and then disappear when clicking them

### ISSUE THREAD

**Issue by dadasilva** [PrefectHQ/prefect#13219]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Parameters disappear when selecting them in UI (using Chrome)

### Reproduction

click on flow deployment, click create run, edit parameter under 'Parameters'

### Error

https://github.com/PrefectHQ/prefect/assets/17056811/6889907a-db00-4f4a-b129-d0aee45bc9bf

### Browsers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version
Cloud Latest

_No response_

### Additional context

I use Pydantic Parameters for this flow, as shown below
```python
class AggregateParameters(BaseModel):
    partners: Optional[List[str]] = None
    channels: Optional[List[str]] = None
    all_partners: Optional[bool] = None
    start: Optional[datetime] = None
    end: Optional[datetime] = None
    prefilter: Optional[bool] = None

```

**Comment by pleek91** [comment]
@dadasilva thanks for reporting, I am able to reproduce. Will get out a fix asap

**Comment by dadasilva** [comment]
@pleek91 thank you for the quick fix, its back to normal on my end as well. 👍 👍
