### ISSUE TITLE
Release local agent as part of Prefect Core

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1321]
Rather than a separate repo, the local Agent should ship with Prefect Core, in order to minimize frictions to getting started with Prefect Cloud.

For a user who had already set an auth token, connecting to the Prefect Cloud platform could be as easy as:

```bash
prefect agent start
```

(or something)

**Comment by joshmeek** [comment]
So since the agent will be pip installable I think the agent code shouldn’t live in core but become an optional dependency which this function will use

**Comment by jlowin** [comment]
It's a good point @joshmeek, I think it could be advantageous to have the shared Agent code in its own repo. The main gist of this issue is that we should ship that code with Core, so that every single user of the open source can instantly and seamlessly run their code on the Cloud platform

**Comment by joshmeek** [comment]
@jlowin Okay cool, I'm on the side of having it still live elsewhere but be pip installable / a requirement. Since it doesn't really _feel_ like a part of core but a separate mechanism.

@cicdw what do you think?

**Comment by joshmeek** [comment]
As per offline discussion w/ @cicdw and @jlowin the code will be moved into core under `src/prefect/agent` for all platforms
