### ISSUE TITLE
Apprise 1.8 breaks imports

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [PrefectHQ/prefect#13314]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The [apprise 1.8 release](https://github.com/caronc/apprise/releases) breaks imports in the [source code](https://github.com/PrefectHQ/prefect/blob/0401b481ee748be59bfe7543ea4d0dc3ef5bfa9b/src/prefect/blocks/notifications.py#L238):
```
>>> from apprise.plugins.NotifyPagerDuty import NotifyPagerDuty
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'apprise.plugins.NotifyPagerDuty'
```

> PR https://github.com/caronc/apprise/pull/1119 involved the refactoring of all the internal file/module structure of the Apprise library. The hope is I didn't break anything in your source code 🙏 . The change was required in order to remain compatible with Python v3.11+ in conjunction with library importing and how it works under the hood. More details on the specific issue can be [found here](https://github.com/caronc/117860-cpython-issue) demonstrating it. The https://github.com/python/cpython/issues/117860 and conform to a better file based structure.
>
> The side effect of this massive change developers may see (if any at all) is just the way your import calls are made. If you always followed the examples provided on this GitHub project, you'll have no issues at all. However, if you got clever and leveraged some of the under-the-hood compontents Apprise is built upon, then you may have an issue

You're requirements allow for this new version:
https://github.com/PrefectHQ/prefect/blob/0401b481ee748be59bfe7543ea4d0dc3ef5bfa9b/requirements.txt#L5

### Reproduction

```python3
import any code that uses apprise :)
```

### Versions

```Text
Version:             2.18.1
API version:         0.8.4
Python version:      3.9.18
Git commit:          8cff545a
Built:               Thu, Apr 25, 2024 3:40 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
this was solved by https://github.com/PrefectHQ/prefect/pull/13311 - let me know if any problem persists

**Comment by nikhiljain12** [comment]
What are the plans for releasing this fix? This PR was merged into main but downstream projects are importing prefect at a particular version, so not sure how this fix will help us.
