### ISSUE TITLE
Slack Invite Expired

### ISSUE THREAD

**Issue by MessedUpHare** [PrefectHQ/prefect#1332]
The slack invite in README.md has expired. link [here](https://join.slack.com/t/prefect-public/shared_invite/enQtNjgwMzI5MjgwNTc2LWUzOGVkZTVkODcwNWNhZTNmMzM0YWMzZjBmZGI4YTNhMzUyM2E0YTIyZDE3NDI1YTYyMTQ1NGM0ZmFjNmRjNDQ)

**Comment by joshmeek** [comment]
Thanks for raising this issue @MessedUpHare!
