### ISSUE TITLE
SynchronousExecutor for other dask schedulers

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#1336]
For running many lightweight IO-bound tasks, I've been using a custom threaded executor I hacked together:
```
class ThreadedExecutor(SynchronousExecutor):
    """Variant of built-in SynchronousExecutor that uses dask threaded scheduler."""

    @contextmanager
    def start(self) -> Iterator:
        """
        Context manager for initializing execution.

        Configures `dask` and yields the `dask.config` contextmanager.
        """
        with dask.config.set(scheduler="threads") as cfg:
            yield cfg

    def wait(self, futures: Any) -> Any:
        """
        Resolves a `dask.delayed` object to its values. Blocks until the computation is complete.

        Args:
            - futures (Any): iterable of `dask.delayed` objects to compute

        Returns:
            - Any: an iterable of resolved futures
        """
        with dask.config.set(scheduler="threads"):
            return dask.compute(futures)[0]
```
I'm not sure this warrants its own executor in Prefect, but perhaps it could be a configurable parameter? Being able to easily swap out the sync/threaded/multiprocess/distributed schedulers is a huge plus of dask, and right now Prefect supports is capitalizing on some but not all of that flexibility.

My own needs are already met by this little hack, just thought I'd contribute my $0.02.

**Comment by cicdw** [comment]
This is a great idea, and simple enough to put together!  I have a branch ready to go on this, but I'm wondering if this justifies a name change for the executor... I could easily preserve backwards compatibility by keeping the `SynchronousExecutor` (which is hard to type anyway) but introduce a "new" executor with an appropriate name.

**Comment by cicdw** [comment]
Proposal to rename `SynchronousExecutor` -> `LocalDaskExecutor` (with dask config kwargs) and deprecate the `SynchronousExecutor` name. @jlowin you're usually good with naming -> 👍/ 👎?
