### ISSUE TITLE
Proposal: Paused should subclass Scheduled

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1342]
Right now, a `Paused` state is a subclass of `Pending`.  This means that when running a flow locally with a `manual_only` trigger, the flow loops indefinitely.  Ideally the "pausing" would occur in a visible way.

Moreover, I can imagine a use case of [task pausing](https://docs.prefect.io/api/unreleased/utilities/tasks.html#prefect-utilities-tasks-pause-task) that actually pauses for a pre-specified amount of time as a fail-safe.

Both of these things combined make me think we could let `Paused` be a subclass of `Scheduled`, and a `manual_only` trigger sets a scheduled start time of 10 years in the future (or something to that effect).

**Comment by jlowin** [comment]
Makes sense. In this implementation, we would remove the explicit check for whether a task is paused in the `TaskRunner.check_task_is_ready()` method and instead simply allow the `TaskRunner.check_task_reached_start_time()` method to prevent the running of `Paused` tasks. Putting it in a `Resume` state would work as expected.
