### ISSUE TITLE
Is there a way to get python objects returned from tasks after the flow has been run?

### ISSUE THREAD

**Issue by govindKAG** [PrefectHQ/prefect#1357]
```python3
 with Flow("cal_match") as f:
     input_data = Parameter("input_data")
     step_1        = func1(input_data)
     step_2        = func2(step_1)
     step_3        = func3(step_2)
 

flow_state = f.run(input_data = input_data_frame)
```

at this point is it possible to get any of the python objects (not FunctionTask) returned by the various task functions ?

**Comment by cicdw** [comment]
Hi @govindKAG - absolutely; the return values from your tasks are stored within their corresponding states.  For example, to get the return value of `step_3`:
```python
flow_state.result[step_3].result
```
Breaking this down:
- `flow_state.result`: `flow_state` is the final state the flow is in post-run, and it's result is a dictionary of tasks -> states
- `flow_state.result[step_3]`: keying into this dictionary returns the individual state associated with the `step_3` task
- `flow_state.result[step_3].result`: the `result` attributes of states almost always stores the return value of the task (and if the task failed for some reason, the `result` will be the exception that was caught)
