### ISSUE TITLE
IntervalSchedule with start_date=now starts at now+interval

### ISSUE THREAD

**Issue by BENR0** [PrefectHQ/prefect#1358]
When initializing a IntervalSchedule with `start_date=datetime.now()` argument I would expect that the flow the schedule is attached to starts immediately but instead the first run is scheduled at now + interval.

I think the problem results from the fact that between initializing the schedule and running the flow (when the `next` function of the schedule is called) the time difference between `after` and `start_date` for calculating the skip here https://github.com/PrefectHQ/prefect/blob/3d2a26f1f147ce8a613493dd60de4b4e451300d3/src/prefect/schedules/clocks.py#L104 becomes positive.

Maybe this is intended but I think it is confusing behavior.

**Comment by jlowin** [comment]
Hi @BENR0, that behavior is indeed expected -- Prefect schedules will never create runs in the past. (This is a common frustration with the Airflow scheduler, which will create all past runs and attempt to run them instantly and clog up instances -- it's why I once introduced a utility to hack all example Airflow DAGs to start `two_days_ago`).

**Comment by BENR0** [comment]
@jlowin yes I am perfectly in line with not running tasks in the past. I think it is not clear what my Problem is. When I start the script with the flow and specified the `start_date` dynamically  as `datetime.now()` then I would expect the the first run to be now (or maybe one or two seconds in the future) but not now + interval. The problem that the first run is in the past with the `start_date` specified as now is that the `after` parameter in the `events` function is called when the flow is run but the `start_date` is initialized with the schedule call. So the minimal time needed for the interpreter to execute the code between those two events makes the `start_date` to be in the past.

I still think it would be nice if a script with a flow with a interval schedule gets executed the first run of the flow should be immediately except when the user explicitly sets a `start_date` in the future.
This could probably be accomplished by changing the default `start_date` to `pendulum.now()` instead of `pendulum.datetime(2019, 1, 1)` if no `start_date` is specified by the user in https://github.com/PrefectHQ/prefect/blob/3d2a26f1f147ce8a613493dd60de4b4e451300d3/src/prefect/schedules/clocks.py#L95

**Comment by jlowin** [comment]
@BENR0 to solve your problem, you could either set your schedule's start time as `pendulum.now().add(seconds=1)`, which would give you enough time to call `flow.run()` before the start time was reached, or call `flow.run(run_on_schedule=False)` to run the flow immediately followed by `flow.run(run_on_schedule=True)` to resume it on the specified interval.

The reason the schedule has a "round" start time of January 1 at midnight is so that minutely, hourly, and daily schedules work "as expected" -- running, for example, on the top of the hour without users having to specify a start time at all.

**Comment by johalnes** [comment]
@jlowin is there a way to trigger Airflow's way of trigger schedules in the past? I understand the frustration when it comes to this being default behavior. But for instance when changing some ETL processes, one would often like to truncate everything and apply improved logic. How would you solve this with Prefect?

**Comment by jlowin** [comment]
@johalnes Prefect doesn't share Airflow's strict conflation of "execution date" and "run date", so there's a few ways to achieve this. The most straightforward is just to trigger multiple runs of your flow, appropriately parameterized for the period you want the flow to act on.

For example, if your flow bases its logic on the `scheduled_start_time`, just create flow runs that are scheduled in the past:

```python
client.create_flow_run(flow_id, scheduled_start_time=past_dt)
```

Alternatively, if you're parameterized, you could do something like:

```python
client.create_flow_run(flow_id, parameters=dict(execution_date=past_dt)
```

(You can also do this via the UI or GraphQL API).

We have facilities for kicking off the scheduler logic via API but they only start from now, not from a past date... perhaps we could look at adding that parameter logic.
