### ISSUE TITLE
How to access the Prefect Slack Community?

### ISSUE THREAD

**Issue by twopirllc** [PrefectHQ/prefect#1362]
How to access the Slack Community?  The link is broken.
<img width="958" alt="Screen Shot 2019-08-15 at 10 50 10 AM" src="https://user-images.githubusercontent.com/18198392/63114851-bf54c680-bf4a-11e9-9c4e-a88392387457.png">

Thanks!
KJ

**Comment by dylanbhughes** [comment]
Thanks, @twopirllc! We're looking into this and will get back to you momentarily.

**Comment by dylanbhughes** [comment]
The invite link does appear to be broken. @twopirllc For the moment, I invited your public github email to the slack. 

We'll update this issue when we've added a new link.

**Comment by twopirllc** [comment]
Great!  Thank you!

**Comment by paulmattheww** [comment]
I may be missing something here, but I am also unable to find the prefect slack community

**Comment by cicdw** [comment]
Hi @paulmattheww - there are a few links to the community in our README; [in the meantime, I'm linking here as well](https://join.slack.com/t/prefect-community/shared_invite/enQtODQ3MTA2MjI4OTgyLTliYjEyYzljNTc2OThlMDE4YmViYzk3NDU4Y2EzMWZiODM0NmU3NjM0NjIyNWY0MGIxOGQzODMxNDMxYWYyOTE)

**Comment by paulmattheww** [comment]
I appreciate it, thank you!  Was able to find and join.  Thanks for the great work you all are doing.

**Comment by RichardMM** [comment]
> Hi @paulmattheww - there are a few links to the community in our README; [in the meantime, I'm linking here as well](https://join.slack.com/t/prefect-community/shared_invite/enQtODQ3MTA2MjI4OTgyLTliYjEyYzljNTc2OThlMDE4YmViYzk3NDU4Y2EzMWZiODM0NmU3NjM0NjIyNWY0MGIxOGQzODMxNDMxYWYyOTE)

This link is dead too at the moment🤔

**Comment by cicdw** [comment]
@RichardMM this is a persistent link that should always work: [https://prefect.io/slack](https://prefect.io/slack)

**Comment by james-tisato** [comment]
> @RichardMM this is a persistent link that should always work: https://prefect.io/slack

This link doesn't seem to work anymore either.
![image](https://user-images.githubusercontent.com/2549847/203891403-91b43a8d-af34-45ff-b7b1-c288ea5a05b7.png)

**Comment by madkinsz** [comment]
Hi @james-tisato that link works for me. cc @anna-geller / @cicdw can you investigate?

**Comment by anna-geller** [comment]
yup we did, @znicholasbrown submitted a PR to fix this, thx for tagging me Michael

**Comment by james-tisato** [comment]
Thanks all, it's working again now

**Comment by MinuraPunchihewa** [comment]
Hey guys,
I am looking to join the Slack community as well, but I am asked for a @prefect.io email address? How exactly do I join the community?

**Comment by dvirginz** [comment]
This link doesn't work for me either.
![Image](https://github.com/user-attachments/assets/cfd06572-6641-4031-8b58-15a42f192a56)

**Comment by cicdw** [comment]
@dvirginz interesting, it's working for me; the redirect currently takes me to https://communityinviter.com/apps/prefect-community/prefect-community so maybe try starting there (note to future visitors of this issue: the https://prefect.io/slack link is the stable one and is recommended).

**Comment by dvirginz** [comment]
> [@dvirginz](https://github.com/dvirginz) interesting, it's working for me; the redirect currently takes me to https://communityinviter.com/apps/prefect-community/prefect-community so maybe try starting there (note to future visitors of this issue: the https://prefect.io/slack link is the stable one and is recommended).


Hi cicdw!
Very interesting. It works now; same link.

**Comment by williamjacksn** [comment]
https://prefect.io/slack

This link redirects to a page that says "This link is no longer active"

**Comment by bdalpe** [comment]
Hi @williamjacksn, this should be fixed now.
