### ISSUE TITLE
Verify Docker storage registry URL doesn't need trailing slash

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1363]
e.g. does `gcr.io/my-images` work as well as `gcr.io/my-images/`

**Comment by cicdw** [comment]
It definitely doesn't; we use [`os.path.join`](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/docker.py#L168) which has the intended behavior:
```python
import os

os.path.join("my-registry", "my-name")
# 'my-registry/my-name'
```

**Comment by joshmeek** [comment]
```
>>> import os
>>> os.path.join("aaa", "bbb")
'aaa/bbb'
>>> os.path.join("aaa/", "bbb")
'aaa/bbb'
>>> os.path.join("aaa/", "/bbb")
'/bbb'
>>> os.path.join("aaa", "/bbb")
'/bbb'
```

@cicdw Any reason to think of a potential case where options 3 and 4 would happen?

**Comment by cicdw** [comment]
Nah I can't imagine anyone would begin their image name with a forward slash.

**Comment by joshmeek** [comment]
/remindme 6 months "@cicdw Nah I can't imagine anyone would begin their image name with a forward slash."
