### ISSUE TITLE
Tasks with persisted results are running again on retry after Prefect 2.16.4

### ISSUE THREAD

**Issue by mthatt** [PrefectHQ/prefect#13735]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

On Prefect versions > 2.16.4, tasks which have persisted results are always re-run on re-try, regardless of if they were successful or not. When using Prefect v2.16.4, successful tasks will not re-run if their results are persisted.

#### To reproduce the error:
1. Run a flow with multiple tasks, and create an error so that one task will break in the initial run

2. Retry the flow run after fixing the error. 

#### Observe the following behavior:

When using v2.16.4, only the failed tasks will re-run. If you upgrade your version past v2.16.4, you will see that all of the tasks re-run, regardless of whether their results are persisted or not.

#### Here is some demo code you can deploy to easily reproduce this error:

```python3
import random
from prefect import flow, task
from prefect.task_runners import SequentialTaskRunner
import logging
import time
logger = logging.getLogger('bia.flows.prefect_testing')

@task(persist_result=True, log_prints=True)
def print_random_statement_1():
    time.sleep(2)
    statements = [
        "The sky is blue.",
        "Today is a great day.",
        "Python is an awesome programming language."
    ]
    
    statement = random.choice(statements)
    logger.info(statement)
    print(statement)


@task(persist_result=True, log_prints=True)
def print_random_statement_2():
    time.sleep(2)
    """
    Prints a random statement from a list of predefined statements.
    """
    statements = [
        "The sky is green.",
        "Today is a bad day.",
        "Python is an ok programming language."
    ]
    
    statement = random.choice(statements)
    ###logger.info(statementi)### --> This statement can be used to break the code, since there is no "statementi" variable. You can use this logging command, the flow will fail, fix the code, and then hit "retry" in the UI
    logger.info(statement)
    print(statement)


@flow(name="print_random_statements", task_runner=SequentialTaskRunner())
def print_random_statements():
    print_random_statement_1()
    print_random_statement_2()

if __name__ == "__main__":
    print_random_statements()
```

### Versions

```Text
Version:             2.19.3
API version:         0.8.4
Python version:      3.11.8
Git commit:          ce378efe
Built:               Thu, May 30, 2024 11:59 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
technically, #14704 doesn't close this issue, the 2.x backport will close this issue - opening momentarily...

**Comment by zzstoatzz** [comment]
closing with #14707

@mthatt feel free to post back here if you're seeing something unexpected!
