### ISSUE TITLE
Prefect Cloud automation fires by mistake

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#13749]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are seeing a surge of automations that fired when they shouldn't have:

![CleanShot 2024-06-03 at 09 41 22@2x](https://github.com/PrefectHQ/prefect/assets/5398977/53259de4-ff4f-4004-9cff-0ad04825d48b)

The [automation](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/automations/automation/1b516904-0142-41c9-9890-636819299db9) we are talking about:

![CleanShot 2024-06-03 at 09 42 59@2x](https://github.com/PrefectHQ/prefect/assets/5398977/779d5655-3b7e-4fc2-b706-e966c71e5d8d)

As you can see the automation should fire when a run stays in RUNNING mode for 1 day, but all the runs that we got alert for looks perfectly normal, and shows a regular run time. For example this [run](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/runs/flow-run/4dd252be-b47e-4c2f-aa48-aca0af8312fb):

![CleanShot 2024-06-03 at 09 45 09@2x](https://github.com/PrefectHQ/prefect/assets/5398977/4f5cd405-e016-4b3d-ab0f-50acaeef788a)

### Reproduction

```python3
Happens in Prefect Cloud.
```

### Error

```python3
Happens in Prefect Cloud.
```

### Versions

```Text
Happens in Prefect Cloud.
```

**Comment by chrisguidry** [comment]
We believe this issue is resolved now, thanks for the report, Yaron!
