### ISSUE TITLE
3.x QA: Task Scheduling Feature Testing

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13798]
### Description

Run through the manual test cases for task scheduling, noting failures and frictions. https://www.notion.so/prefect/Task-Scheduling-Manual-Test-Cases-1945c02bea514607acd907e9b42fb7c5?pvs=4

**Comment by jakekaplan** [comment]
No bugs to report, primarily some changes from `task_server` -> `task_worker`

- One UX issue fixed here: https://github.com/PrefectHQ/prefect/pull/13848
- Updated the example repo to support the updated naming: https://github.com/PrefectHQ/prefect-background-task-examples/pull/38

**Comment by jakekaplan** [comment]
https://github.com/PrefectHQ/prefect/issues/13911

**Comment by jakekaplan** [comment]
@chrisguidry observed some potential hanging behavior which is preventing us from running tasks at scale: https://github.com/PrefectHQ/nebula/pull/7962

**Comment by chrisguidry** [comment]
https://github.com/PrefectHQ/prefect/issues/14092
https://github.com/PrefectHQ/prefect/issues/14098

All of the features of task-scheduling work well, but we are still hunting down some last-mile reliability issues with it.
