### ISSUE TITLE
3.x QA: Core Flow/Task User Journey

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13801]
### Description

Run through the following user journeys, noting failures and frictions:
- [x] rerun a flow run that failed via the API
- [x] run a flow with subflows
- [x] cancel a running flow
- [x] run a flow with retries
- [x] run a flow with tasks that retry
- [x] run a flow with cached tasks

**Comment by bunchesofdonald** [comment]
When serving a sync flow via `flow.serve` the 'right' way is met by red squiggles in the editor:

![Screenshot 2024-06-06 at 4 55 55 PM](https://github.com/PrefectHQ/prefect/assets/354286/bf5069eb-c083-4b20-a067-949faf0db10c)

**Comment by bunchesofdonald** [comment]
Retries do not appear to work at all. This flow:

```python
from prefect import flow


@flow(retries=5, retry_delay_seconds=3)
async def flaky_mcfail():
    import random

    if random.random() < 0.5:
        raise ValueError("I'm a random failure!")
    return "I'm a success!"


if __name__ == "__main__":
    flaky_mcfail.serve()
```

Does not retry when the ValueError is raised, the UI shows `retries` as being `None` and `Retry Delay` as `0s`.

![Screenshot 2024-06-06 at 4 52 47 PM](https://github.com/PrefectHQ/prefect/assets/354286/b1594436-0464-428e-8192-dff256611cf6)

**Comment by bunchesofdonald** [comment]
I QA'ed locally against a SQLite database as well as against staging, I've created four issues for what I found:

- Improve DevX when serving a sync flow: https://github.com/PrefectHQ/prefect/issues/13856
- Flows are not retried after they fail when given a `retries kwarg: https://github.com/PrefectHQ/prefect/issues/13858
- Tasks should log when they’re retrying: https://github.com/PrefectHQ/prefect/issues/13864
- Task cache expiration doesn’t seem to function: https://github.com/PrefectHQ/prefect/issues/13865
