### ISSUE TITLE
3.x QA: RAG Pipeline

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13805]
### Description

Create a RAG pipeline that satisfies the following, noting failures and frictions along the way:

> I am building [RAG pipeline](https://www.databricks.com/glossary/retrieval-augmented-generation-rag) for a customer support chatbot that answers questions based on our documentation and customer conversation history. When my model has low confidence in its answer to a question, I want to invite a customer support agent to review and potentially modify the answer. I need to handle up to 10 conversations a minute at peak hours, but as few as 1 conversation an hour in the off hours. I want the chatbot’s initial response to be as quick as possible.

**Comment by bunchesofdonald** [comment]
I built a RAG pipeline that takes stores some of our documentation in Pinecone (vector database) and uses relevant documents as context when invoking GPT2. Confidence is calculated as how closely documents match. If confidence is low the flow is paused and a human is asked for intervention, the human's intervention is the relayed to the user.

I didn't really find any failures or frictions in this, most of the friction was in the learning side of this task. As far as incorporating this type of project into prefect it worked fine. Pausing/resuming worked as expected, I was able to use flow run inputs to communicate between processes for user interaction, etc. 

[rag.zip](https://github.com/user-attachments/files/15794220/rag.zip)
