### ISSUE TITLE
'on_cancellation' Hook Not Triggered in Prefect 2.16.4

### ISSUE THREAD

**Issue by CoffeeMark2** [PrefectHQ/prefect#13834]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The on_cancellation hook in a Prefect flow is not being triggered when the flow is canceled. 
Although the workflow appears as canceled in the Prefect UI and client, the log message from the on_cancellation hook is not displayed, indicating that the hook is not being executed.

### Reproduction

```python3
from prefect import flow, get_run_logger
from prefect.deployments import Deployment
import time

def hook_cancellantion(flow, flow_run, state):
    logger = get_run_logger()
    logger.info("here is hook cancellation")

@flow(
    name="cancellation_hook_test",
    on_cancellation=[hook_cancellantion],
)
def cancellation_hook_test():
    logger = get_run_logger()
    for i in range(10):
        logger.info(f"flow is running {i}")
        time.sleep(10)

deployment = Deployment.build_from_flow(
    flow=cancellation_hook_test,
    name="weekday",
    tags=['data-engineering'],
    work_queue_name="default",
)

deployment.apply()
```

After running the code above for a little while, I cancel the flow execution using the Prefect UI.

![issue](https://github.com/PrefectHQ/prefect/assets/108973448/4bed5322-c081-4273-8715-cc03c4176f6d)

The flow has been canceled. The expected log message "here is hook cancellation" from the on_cancellation hook should appear, but it does not.

### Versions

```Text
Version:             2.16.4
API version:         0.8.4
Python version:      3.11.8
Git commit:          e3e7df9d
Built:               Thu, Mar 14, 2024 5:11 PM
OS/Arch:             win32/AMD64
Profile:             test
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.45.2
```

### Additional context

I am using the Agent instead of the Worker to run the code deployment. Could this be the cause of the issue?

**Comment by desertaxle** [comment]
Thanks for the issue @CoffeeMark2! These hooks will fire more reliably in the more recent versions of `perfect`. Can you upgrade to the latest version and see if this behavior persists?

**Comment by CoffeeMark2** [comment]
Thank you for your prompt response!
Sadly, our company might take some time to complete the Prefect upgrade. Once we have updated to the latest version, I will get back to you with the results.

**Comment by zhen0** [comment]
Hi @CoffeeMark2 - I'm going to close this issue since we believe upgrading should fix your issue.  If you encounter new issues once you upgrade, please open a new issue to let us know.  Thanks!

**Comment by callmimaybe** [comment]
I'm running version `2.19.8`, and can confirm the `on_cancellation` hook still isn't being called.

Attaching screenshots to show comparison of logs on same deployment where `on_completion` hook works, but `on_cancellation` doesn't. I have tried cancelling by triggering it by the "Cancel" button in the UI and by `/set_state` to `CANCELLING` in the API, result is the same.

![Screenshot from 2024-07-12 17-59-25](https://github.com/user-attachments/assets/75561994-37b5-44c7-a49c-115a3d958e0d)
![Screenshot from 2024-07-12 17-59-13](https://github.com/user-attachments/assets/4edd5c80-1f93-4835-9799-59b11698f9ac)

**Comment by CoffeeMark2** [comment]
Hi,  thanks for the feedback! The issue we're encountering is due to an outdated deployment method. 

[deployment](https://docs.prefect.io/latest/api-ref/prefect/deployments/deployments/?h=build_from#prefect.deployments.deployments.Deployment.build_from_flow)

The new deployment method has two options: [flow.serve()](https://docs.prefect.io/latest/tutorial/deployments/) and [flow.deployment()](https://github.com/PrefectHQ/prefect/pull/13981) with work pools. 

We found that the on_cancellation hook can be correctly activated in `flow.serve()`, but it is not stable in `flow.deployment()` with the work-pool Process. QAQ

**Comment by callmimaybe** [comment]
That's good to know that you've found out more details.

We're using `prefect.yaml` file to deploy, and I've been recreating/testing this bug with just the following:

**prefect.yaml**
```
deployments:
    - name: plans
      version:
      tags: []
      description:
      entrypoint: ./test_work_pool/flows/count_flow.py:count_flow
      work_pool:
          name: test-work-pool
          work_queue_name:
          job_variables: {}
      schedule:
      parameters: {}
```

**count_flow.py**
```
import time

from pydantic import BaseModel
from prefect import flow
from prefect.states import Failed
from prefect.logging.loggers import flow_run_logger


class TimerModel(BaseModel):
    sec: int


def handle_success(flow, flow_run, state) -> None:
    logger = flow_run_logger(flow_run, flow)
    logger.info("Flow run SUCCEEDED!")


def handle_failure(flow, flow_run, state) -> None:
    logger = flow_run_logger(flow_run, flow)
    logger.info("Flow run FAILED!")


def handle_cancel(flow, flow_run, state) -> None:
    logger = flow_run_logger(flow_run, flow)
    logger.info("Flow run CANCELLED!")


def handle_crash(flow, flow_run, state) -> None:
    logger = flow_run_logger(flow_run, flow)
    logger.info("Flow run CRASHED!")


@flow(
    log_prints=True,
    on_completion=[handle_success],
    on_failure=[handle_failure],
    on_cancellation=[handle_cancel],
    on_crashed=[handle_crash],
)
def count_flow(params: TimerModel) -> None:
    print(f"Sleeping for {params.sec} seconds...")

    try:
        time.sleep(params.sec)
    except ValueError as error:
        return Failed(message=f"Sleep has failed: {error}")

    print("Sleep completed")

    return
```

I wonder if perhaps the `prefect.yaml` deploy method also suffers from the same issue as whatever `flow.deployment()` is facing.
