### ISSUE TITLE
Task cache expiration doesn't seem to function

### ISSUE THREAD

**Issue by bunchesofdonald** [PrefectHQ/prefect#13865]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a cache key on a task setting an expiration doesn't seem to function and caches are never expired. Running the flow below should have the cache expiring every 1s, however running the flow again many minutes later results in the task not running and instead returning the cached result.

### Reproduction

```python3
import datetime
from prefect import flow, task
from prefect.tasks import task_input_hash


@flow(log_prints=True)
def fibonacci(n):
    for step in range(n, n + 1):
        fib = nth_fib(step)
        print(fib)
    return fib


@task(
    cache_key_fn=task_input_hash,
    cache_expiration=datetime.timedelta(seconds=1),
)
def nth_fib(n):
    if n <= 0:
        return "Input should be a positive integer."
    elif n == 1:
        return 1
    elif n == 2:
        return 1
    else:
        return nth_fib(n - 1) + nth_fib(n - 2)


if __name__ == "__main__":
    fibonacci.serve()
```

### Versions

```Text
3.0rc2
```

**Comment by bunchesofdonald** [comment]
Additionally the cache key and expiration in the UI display as `None`.
![Screenshot 2024-06-07 at 11 36 43 AM](https://github.com/PrefectHQ/prefect/assets/354286/8581522e-cde3-4b81-bd09-4d999a9ab1a2)

**Comment by cicdw** [comment]
I'll take this one - this is a known state as of [the latest transaction/cache policy PR](https://github.com/PrefectHQ/prefect/pull/13821).
