### ISSUE TITLE
Confusing deployment status in the UI

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#13869]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I created a new deployment using `prefect deploy`. It has a worker polling it and runs that I kick off are picked up and complete.  However, the deployment's status is shown as Not Ready.  Given how prominently we show deployment status in the UI, this is pretty confusing. 

<img width="1000" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/63cf69ea-5258-4006-bcc9-e414d607f6fe">

<img width="619" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/eb47966c-47e3-4924-8484-4d8172fa9f0b">

<img width="933" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/0b7a9d25-cdb6-47b6-88a8-4f20fb07d091">

### Reproduction

```python3
So far I have seen this on OSS - I'll check against cloud and report back.
```

### Versions

```Text
⇒  prefect version
Version:             3.0.0rc2
API version:         0.8.4
Python version:      3.12.3
Git commit:          4d70aefb
Built:               Thu, Jun 6, 2024 2:53 PM
OS/Arch:             darwin/x86_64
Profile:             orion
Server type:         ephemeral
Pydantic version:    2.7.3
Server:
  Database:          sqlite
  SQLite version:    3.45.3
```

**Comment by serinamarie** [comment]
Hi @zhen0,

On my first try I wasn't able to replicate this issue with:
```bash
❯ prefect version
Version:             3.0.0rc2
API version:         0.8.4
Python version:      3.11.1
Git commit:          4d70aefb
Built:               Thu, Jun 6, 2024 2:53 PM
OS/Arch:             darwin/arm64
Profile:             local_sqlite
Server type:         ephemeral
Pydantic version:    2.7.3
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

I'll try and sync with you on it

**Comment by jmesterh** [comment]
FWIW I often see this with 2.19.1 as well, I have workers running, polling & accepting flows but the deployments on the deployments page all have red lights. They usually go green after an hour or so(?). This is in OSS with the default helm charts for server and worker, with a fresh installation of all including Postgres running in K3D as a prototype environment. What exactly are these lights suppose to indicate?

**Comment by serinamarie** [comment]
@jmesterh Thanks for your comment. It got me digging in a little more just now and I think I may see the issue, which is a possibly mistaken [deviation](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/api/workers.py#L388) from the Cloud implementation. I'll make a fix tomorrow morning and see how that looks. I can see now why I couldn't reproduce the error.

As Prefect deployments can be scheduled and executed without a work pool or a work queue. It is impossible to determine from the UI if a deployment created by `flow.serve()` will have its scheduled flow runs picked up for execution.

The work pool status concept provides a clear, minimal indicator of whether or not scheduled work in a work pool will be picked up for execution by a worker. 

Hopefully the tooltip expresses this when you hover over it! If not, perhaps it could be improved.

**Comment by zhen0** [comment]
Steps to reproduce. 
1.  Install Prefect - `pip install prefect==3.0.0rc`
2. Start the server - `prefect server start`
3. Create and start a local process work pool 
4. Run `prefect deploy` and create a deployment using the local process work pool 
5. Go to the UI and check the deployment status. It will say 'Not Ready' 
6. Use the run button and see your run complete even though the UI says the deployment is not ready.
