### ISSUE TITLE
Feature: Support NOT filtering for FlowRun States

### ISSUE THREAD

**Issue by aaazzam** [PrefectHQ/prefect#13898]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

In the Prefect UI, filtering flow run states to find every run that's not currently Scheduled (say) requires one to _explicitly_ search for every other state by name. But this search only unions over _Prefect_ states, and so this approach breaks down with user-defined states. 

### Describe the proposed behavior

Allow explicit NOT filtering.

**Comment by jakekaplan** [comment]
done in:

https://github.com/PrefectHQ/nebula/pull/7939
https://github.com/PrefectHQ/prefect/pull/13920
