### ISSUE TITLE
prefect server is not sending scheduled flow to the right work-pool (k8-worker)

### ISSUE THREAD

**Issue by ytl-liva** [PrefectHQ/prefect#13896]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect flow that is scheduled and deployed to run on kubernetes worker is running on prefect agent randomly (roughly 50% of the time, and sometimes one retry will fix it, if not 2). 

### Reproduction
I have both prefect agent and prefect worker running, and the flow is deployed on both agent and worker on different deployments. However, the scheduled flows on prefect worker is often failing because it is running on prefect agent instead (confirmed this because prefect agent had a spike and went oom, and also the prefect logs on the ui)

a thread in slack if it helps: https://prefect-community.slack.com/archives/C048SVCEFF0/p1707893608997569

### Error

example of the prefect logs can be seen:
errored out flows:
```
Created task run 'get_database_engine-0' for task 'get_database_engine'
03:00:00 PM
prefect.flow_runs
Executing 'get_database_engine-0' immediately...
03:00:00 PM
prefect.flow_runs
Finished in state Completed()
```

succeeded flows:
```
Worker 'KubernetesWorker 16143cd3-84c1-45e0-88b3-5d15f8533e1e' submitting flow run '97007bed-97bc-4db4-b311-fe843ef45ecf'
04:15:21 PM
prefect.flow_runs.worker
Creating Kubernetes job...
04:15:21 PM
prefect.flow_runs.worker
Completed submission of flow run '97007bed-97bc-4db4-b311-fe843ef45ecf'
04:15:21 PM
prefect.flow_runs.worker
Job 'vivacious-coyote-vqjt4': Pod has status 'Pending'.
04:15:21 PM
prefect.flow_runs.worker
Job 'vivacious-coyote-vqjt4': Pod has status 'Running'.
04:15:23 PM
prefect.flow_runs.worker
Opening process...
04:15:26 PM
prefect.flow_runs.runner
Running 1 deployment pull steps
04:15:29 PM
prefect.flow_runs
Changing working directory to 'data-science-main'
04:15:31 PM
prefect.flow_runs
Importing flow code from 'flows/ndpp/mds_flow.py:ndpp_mds'
04:15:31 PM
prefect.flow_runs
Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
04:15:36 PM
prefect.flow_runs
Executing flow 'ndpp-mds' for flow run 'vivacious-coyote'...
04:15:36 PM
prefect.flow_runs
Beginning execution...
04:15:36 PM
prefect.flow_runs
Created task run 'get_database_engine-0' for task 'get_database_engine'
04:15:36 PM
prefect.flow_runs
Executing 'get_database_engine-0' immediately...
04:15:36 PM
prefect.flow_runs
Beginning execution...
04:15:36 PM
get_database_engine-0
prefect.task_runs
Finished in state Completed()
```

### Versions
```
prefect-server: 
Version:             2.14.21
API version:         0.8.4
Python version:      3.11.8

prefect-agent: 
Version:             2.14.14
API version:         0.8.4
Python version:      3.11.9


prefect-worker
Version:             2.14.21
API version:         0.8.4
Python version:      3.11.8
```

### Additional context
a thread in slack if it helps: https://prefect-community.slack.com/archives/C048SVCEFF0/p1707893608997569

**Comment by ytl-liva** [comment]
let me know if this can be easily fixed if i just upgrade the version. and which version do i need to update to

**Comment by jakekaplan** [comment]
Hi @ytl-liva. does the _work queue_ for both the agent pool and the k8s pool share a name? If so can you try updating one and see if this behavior persists?

**Comment by ytl-liva** [comment]
hi @jakekaplan thanks for the prompt reply. the agent pool and the k8 pool dont share the same name. 
<img width="1163" alt="image" src="https://github.com/PrefectHQ/prefect/assets/113404285/eddbe9b7-caef-4e50-8c34-3e88ffb21df1">

**Comment by ytl-liva** [comment]
hi @jakekaplan I have changed the name of the work queue of the default k8 pool into another name yet this is still happening.

**Comment by jakekaplan** [comment]
@ytl-liva ah sorry, each work pool has an underlying set of work queues (at least 1). Can you click on the work queue tab and try change the 
e.x.
![Screenshot 2024-06-12 at 8 21 51 AM](https://github.com/PrefectHQ/prefect/assets/40362401/20d3e091-c971-4ab0-b110-9506396a2212)
underlying work queue's name to something else?

**Comment by ytl-liva** [comment]
@jakekaplan yeah i have changed the work queue name the day before yesterday, yet it still happens yesterday. but i didnt change the deployment. I changed the deployment yesterday. today seems to be fine but i guess it needs a longer observation time since it is happening randomly
![image](https://github.com/PrefectHQ/prefect/assets/113404285/d6bae879-e98e-48b8-9aa4-bf1d0e5e4f4e)

**Comment by ytl-liva** [comment]
I think your suggestion  may have fixed the long time issue that i had. havent had any random failures in 2 weeks. closing this ticket, but might want to write this in documentation somewhere
