### ISSUE TITLE
Highlight annotations are misinterpreted as tab names in 3.0 code snippets

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13900]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Highlight annotations are being misinterpreted as tab names for code snippet

### Describe the proposed change

Highlight the lines and remove the tab names as expected

### Additional context

![image](https://github.com/PrefectHQ/prefect/assets/42625717/35d6ab2a-b0dd-450e-8f33-cea2b55a07cd)

**Comment by discdiver** [comment]
Closing in favor of #13976, which includes a few additional formatting items to update.
