### ISSUE TITLE
Composite (fan-in) triggers not available in OSS UI

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#13936]
### First check

- [x] I added a descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I refreshed the page and this issue still occurred.
- [x] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

After chatting with Craig, we think that composite triggers never became available in the OSS UI. 

### Reproduction

https://www.loom.com/share/84572a09be6745f8bb62197d47463437?sid=0edb3ac5-ab9f-4082-a4e0-d88b802188f8

### Error

Composite trigger template from the Prefect docs raises as invalid (it doesn't raise in Cloud)

![Image](https://github.com/PrefectHQ/prefect/assets/42048900/e48015b6-a12e-49fd-be34-f13b1ece3982)

### Browsers

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version
```
Version:             3.0.0rc2
API version:         0.8.4
Python version:      3.11.1
Git commit:          4d70aefb
Built:               Thu, Jun 6, 2024 2:53 PM
OS/Arch:             darwin/arm64
Profile:             local_sqlite
Server type:         ephemeral
Pydantic version:    2.7.3
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

**Comment by serinamarie** [comment]
![Screenshot 2024-06-11 at 6 19 42 PM](https://github.com/PrefectHQ/prefect/assets/42048900/0be01b9e-0161-47bd-a6fc-e3ef2d6c7498)
Creating via `prefect deploy -n my-deployment --trigger my_triggers.yaml` did not populate as expected (which makes sense as this isn't implemented, just something to test).

**Comment by pleek91** [comment]
Opening this while I test the fix

**Comment by pleek91** [comment]
@serinamarie I can create and view now but editing still doesn't work, looking into that

**Comment by pleek91** [comment]
Okay this is g2g from my tests. It still shows up as just a "custom" trigger. But things are working now.
