### ISSUE TITLE
Remove references to `SequentialTaskRunner` in 3.0 docs

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13955]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

`SequentialTaskRunner` no longer exists

### Describe the proposed change

Remove references from the docs

**Comment by discdiver** [comment]
One step in this direction: 
https://github.com/PrefectHQ/prefect/pull/13996
