### ISSUE TITLE
Add default local storage persistence for transactions

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#13952]
Setting up a transaction store is difficult because it requires creating a result store, which requires creating a block. Without a store, transaction results are not persisted. We should be able to set up a default transaction store for users that uses local storage. We should not create an anonymous block for this case, but instead create and reuse a default transaction store block. Transaction results should be isolated by default to ensure no result reuse between runs unless the user specifically enables it via their transaction key.

**Comment by cicdw** [comment]
Just a thought: we could allow configuring the directory where results are stored along with its structure via a setting for easy testing and local dev.

**Comment by desertaxle** [comment]
I like that idea! Can you elaborate on configuring the structure via a setting? What are some examples of structures that we might offer?

**Comment by cicdw** [comment]
I might be a one trick pony on templating, but I was imagining things like:
```
PREFECT_LOCAL_STORAGE_PATH="~/.prefect/{flow_run_id}/"
```
as an example.

**Comment by desertaxle** [comment]
Related to https://github.com/PrefectHQ/prefect/issues/13800
