### ISSUE TITLE
Show task runs that are called from other tasks as nested on the flow run graph, just as we do for sub-flow runs.

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#13970]

**Comment by pleek91** [comment]
To do this I'm recommending we do the following

1. Write a new endpoint to get the graph data for a task run. This should be pretty straight forward and mostly copy paste from the existing flow run graph endpoint.
2. Update the flow run graph endpoint to only return a single level of depth for task runs. Basically if a task has dependent tasks, mark it in some way and don't return its children tasks. Currently we're returning all tasks at any depth. This should actually be a decent simplification of that endpoint.
3. Update the graph itself to detect these "tasks with tasks" and render them similarly (identically?) to how we're currently rendering sub flows

**Comment by zhen0** [comment]
Closing in favor of [Enable exploration of run graphs with many nested tasks](https://github.com/PrefectHQ/prefect/issues/14120)

**Comment by zhen0** [comment]
Reopening after discussion with @pleek91 around next steps

**Comment by pleek91** [comment]
Related PRs
https://github.com/PrefectHQ/graphs/pull/525
https://github.com/PrefectHQ/prefect-ui-library/pull/2553
https://github.com/PrefectHQ/prefect/pull/14271

**Comment by pleek91** [comment]
What we ended up doing here is tracking the nested tasks in the api response by including an `encapsulating` property on nodes that includes the ids of any nodes that called/spawned the current node. 

The ui then preprocesses the graph data into a shape that the graph can understand and render the nested task runs properly. This was all done in a backwards compatible way. So if the `encapsulating` property is missing the graph will render in the previous manor where all tasks were rendered on the root graph.
