### ISSUE TITLE
Automations: deployment.parameters have empty values when passed to action.

### ISSUE THREAD

**Issue by jfloodnet** [PrefectHQ/prefect#14023]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have created an automation to notify slack when a flow run enters "crashed" state. Flow run that triggers the automation has a single parameter "url". I need this url in the notification to slack. However, it appears the value for url is always an empty string.

![image](https://github.com/PrefectHQ/prefect/assets/1077749/003e9326-51df-4246-9585-b12322745111)

![image](https://github.com/PrefectHQ/prefect/assets/1077749/571f234f-89aa-4cb7-a82d-cee5978bb262)

```
Flow run {{ flow.name }}/{{ flow_run.name }} observed in state `{{ flow_run.state.name }}` at {{ flow_run.state.timestamp }}.
Flow ID: {{ flow_run.flow_id }}
Flow run ID: {{ flow_run.id }}
Flow run URL: {{ flow_run|ui_url }}
State message: {{ flow_run.state.message }}
Parameters : {{ deployment.parameters }}
```

![image](https://github.com/PrefectHQ/prefect/assets/1077749/991c4ff2-bc6b-4b2a-94b7-8eef2e8e6fd4)

### Reproduction

```python3
@flow(name="Test Automation from Failed Flow")
async def failed_flow(url: str):
    print(f'{url}')
    async with get_client() as client:
        state = Failed(message="Requeued due to infrastructure issues")
        await client.set_flow_run_state(get_run_context().flow_run_id, state, force=True)
```

### Versions

```Text
2.x
```

**Comment by jfloodnet** [comment]
Ok more testing made me realise that the parameters I need are on the flow_run. I think I got misdirected by the documentation which gives an example of accessing the deployment parameters:

https://docs.prefect.io/latest/concepts/automations/

![image](https://github.com/PrefectHQ/prefect/assets/1077749/07559f52-b02f-4d69-ba5c-3418d77f1eb4)

**Comment by jakekaplan** [comment]
I see how that would be confusing. Deployment parameters are layered onto flow run parameters, I will look to update the example. Glad you were able to figure it out!
