### ISSUE TITLE
Support 2nd level retries on flow runs

### ISSUE THREAD

**Issue by jfloodnet** [PrefectHQ/prefect#14022]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, when a flow has retries configured, it will only retry on the current worker. 

Some errors may require the worker node to be removed from the workpool and restarted. 

In this scenario, retrying is futile.

### Describe the proposed behavior

Enable some way to indicate that the worker is unstable and to retry any current flows by requeuing them into the work queue.

2nd level retries would then have a retry count for how many times it can be requeued.

### Additional context

I am using prefect to schedule web scraping jobs. Sometimes the nodes will start having persistent issues and require restarts.  In this case the flow retries 3 times and then is marked as failed. This means I need to manually restart the flow to kick it off again.

**Comment by jakekaplan** [comment]
Hi @jfloodnet thanks for filing this issue. 

That's one of the primary use cases for [automations](https://docs.prefect.io/latest/concepts/automations/?h=automations). If a flow run fails you can trigger it's deployment to run again. Automations are availibile in cloud and are in pre-release in open source (current `3.0.0rc2`).

**Comment by jfloodnet** [comment]
Thanks for your response @jakekaplan - the current problem with using automations for this is that you cannot implement a "max_retries". Same issue is described here: https://github.com/PrefectHQ/prefect/issues/10211

As this is a fairly common pattern, I think the best implementation would be native support for 2nd level retries, rather than custom automation configuration.
