### ISSUE TITLE
Missing overload for `get_client()`

### ISSUE THREAD

**Issue by hikariatama** [PrefectHQ/prefect#14104]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

Due to missing overload, pyright reports
```
async with get_client(sync_client=False) as client:
    ...
```
as error, since `get_client` returns `Union["PrefectClient", "SyncPrefectClient"]`.

### Describe the proposed behavior

Add typing overloads for client to get rid of error at least with the explicit argument `sync_client`

**Comment by desertaxle** [comment]
Thanks for the issue @hikariatama! This was fixed in https://github.com/PrefectHQ/prefect/pull/13763 and the fix is available in 3.0.0rc3. I'm going to close this, but feel free to reply if you encounter any other issues with `get_client` typing!
