### ISSUE TITLE
`prefect server start` should prompt you to create a local profile and switch to it automatically

### ISSUE THREAD

**Issue by djsauble** [PrefectHQ/prefect#14127]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

When you start a local API server, you have to manually tell Prefect that you want to interact with that server.

The `prefect server start` includes the command you need to manually run:

```
% prefect server start

 ___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _| 
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| |___\___| |_|  

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200
```

### Describe the proposed behavior

Most people don't read, instead of assuming that people will see the `prefect config set` command, let's prompt them to create a new local profile if one doesn't already exist and switch to it automatically.

### Example Use

Whenever you start a local server, we should make it seamless to start interacting with that server. In general, switching between cloud and OSS shouldn't require much effort.

**Comment by serinamarie** [comment]
> Example Use
> Whenever you start a local server, we should make it seamless to start interacting with that server. In general, switching between cloud and OSS shouldn’t require much effort.

Hey @djsauble, would you mind telling me more about the actual friction you hit here so that I can understand a bit more about what you’re looking for? I believe there should always be a `default` profile that gets created.
