### ISSUE TITLE
`prefect worker start` resets Prefect from 3.x to 2.x if you let it install dependencies

### ISSUE THREAD

**Issue by djsauble** [PrefectHQ/prefect#14123]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm testing the 3.0 RC. I cannot add a worker to a Docker type work pool in an local API server.

### Reproduction

```python3
1. Install Docker and the Prefect client (`pip install -U prefect==3.0.0rc2`)
2. Start a local API server (`prefect server start`)
3. Create a Docker type work pool (`prefect work-pool create --type docker my-work-pool`)
4. Start a worker (`prefect worker start --pool my-work-pool`)
5. The command will ask if you want to install dependencies. Enter 'y' to install dependencies.

The last command will reset your `prefect` package to `2.19.5` !!!
```

### Error

```python3
Initial output from `prefect worker start`:
https://gist.github.com/djsauble/aa57f367ae18b0e2c319444960953b15

Subsequent output:
https://gist.github.com/djsauble/dd8c23583e3db3de4e3a77c68ea57076
```

### Versions

```Text
% prefect version
Version:             3.0.0rc2
API version:         0.8.4
Python version:      3.11.9
Git commit:          4d70aefb
Built:               Thu, Jun 6, 2024 2:53 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Pydantic version:    2.7.4
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

**Comment by lilyTokens** [comment]
The flow run concurrency limits here address a real orchestration pain point. One pattern that has worked well for agentic pipelines: using a separate concurrency limit per client or per project scope, so an agent running tasks for one client cannot starve another. It's a simple isolation mechanism but effective when running multi-tenant agent workflows.
