### ISSUE TITLE
Creating a `Pause an automation` automation action and selecting an automation doesn't persist

### ISSUE THREAD

**Issue by collincchoy** [PrefectHQ/prefect#14132]
Issue seems to be in Cloud also.

Steps to reproduce:
1. Go to automations page in UI
2. Create a new automation
3. Pick a trigger
4. Select `Pause an automation` as your action
5. Select an automation to pause (change it from inferred)
6. Save
7. See that the automation's description says "Pause automation inferred from the triggering event"
8. Edit the automation, go to actions, and see that it's set to "inferred"

Notes:
Seems like it persists correctly into the DB - might just be a UI issue

**Comment by zhen0** [comment]
Closed by [Fix: Add missing pause/resume automation actions response mapper PrefectHQ/prefect-ui-library#2539](https://github.com/PrefectHQ/prefect-ui-library/pull/2539)

**Comment by collincchoy** [comment]
Fixed by https://github.com/PrefectHQ/nebula-ui/pull/4835
