### ISSUE TITLE
Scope documentation searches to the current version and/or display version dropdown correctly

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#14145]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Search functionality in 3.x docs does not scope your search to your current version, resulting in confusion if you're suddenly dropped onto a 2.x page. Further, the version dropdown tab does not update with the version of the page you're viewing.

When searching for “task runners” for example, I click on the first result and it brings me to this page. There’s no hint I’m looking at 2.x docs besides the url

![image](https://github.com/PrefectHQ/prefect/assets/42625717/af71608e-4375-45aa-b34f-afc249dbba02)

### Describe the proposed change

One or both of:
1. Restrict search on the docs to your currently selected version
2. Dynamically update the version at the top of the page when it changes

**Comment by discdiver** [comment]
In the short term, I can remove the few 2.19.x pages in the docs. 
In the longer term, this has been raised with Mintlify and I'll raise again later this week. Implementing improved behavior is largely out of our hands.
