### ISSUE TITLE
Prefect 3.0 flows don't handle SIGTERM

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#14219]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Flows in Prefect 3.0 don't seem to respect or respond to SIGTERM. When running the script below (`crash.py`), neither `kill -SIGTERM pid` nor `crtl-c` have any effect.

### Reproduction

```python3
import asyncio
import os

from prefect import flow, task


@task
async def my_task():
    results = await asyncio.sleep(300)
    return


@flow
def main():
    print(os.getpid())
    return [my_task.submit() for i in range(10)]


if __name__ == "__main__":
    main()
```

### Error

```python3
N/A
```

### Versions

```Text
Version:             3.0.0rc7
API version:         0.8.4
Python version:      3.12.3
Git commit:          ed41da9d
Built:               Thu, Jun 20, 2024 4:59 PM
OS/Arch:             darwin/arm64
Profile:             sandbox
Server type:         cloud
Pydantic version:    2.7.4
```

**Comment by zhen0** [comment]
I think this says the same as [sync_compatible interrupts clean KeyboardInterrupt handling](https://github.com/PrefectHQ/prefect/issues/14013) in slightly different words?

**Comment by cicdw** [comment]
CTRL-C does interrupt this script now and correctly sets the run to `CRASHED` - closing as resolved.
