### ISSUE TITLE
Add `3-latest` tag to Docker Hub

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#14228]
We have a `2-latest` tag that points to the latest `2.x` image version. We should have the same for `3.x` images.

**Comment by discdiver** [comment]
Relatedly, we should tell users about the existence of this image once it's been created in the docs at https://docs-3.prefect.io/3.0rc/deploy/dynamic-infra/deploy-docker#prefect-maintained-docker-images
