### ISSUE TITLE
Input field type switches when clearing value in optional field

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#14265]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

An optional int input field switches to None whenever the integer value is cleared.
This is a minor inconvenience when updating values as at least one digit of the old value needs to remain in the field and can only be removed when the new value is entered.

### Reproduction

Any deployment with optional int parameters

### Error

See screencast

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Prefect Cloud
```

### Additional context

See example:
Field has value `7`. User wants to change it. As soon as the value is removed the field jumps to `None`. New value can only be entered by appending it to the old value and then removing the old value.
![output](https://github.com/PrefectHQ/prefect/assets/11021147/515790cc-5cf6-4d1f-8735-7d5fecaeb9e8)

**Comment by j-tr** [comment]
@pleek91 @kevingrismore sorry for submitting an incomplete issue. I thought this would be the case for all optional fields but is actually only the case if we use a pydantic field with default=None.
This makes the expected behavior a bit less clear as it makes sense to set the field to None (default type) if the user provides no input, however entering a new value should still work without having to enter the new value first and then delete the old value.

Hope this MRE helps.

```
from prefect import flow
from pydantic import BaseModel, Field


class ParamModel(BaseModel):
    param: int | None = Field(default=None)


@flow()
def main(param: ParamModel):
    pass


if __name__ == "__main__":
    main.serve()
```

**Comment by pleek91** [comment]
@j-tr thank you! I can reproduce the switching using that MRE. I'll figure out what's going on here
