### ISSUE TITLE
Unify on- and off- schedule run pipelines

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1430]
Currently, `flow.run()` has two logic branches:
- if a flow doesn't have a schedule, we create a flowrunner and call it's run() method.
- if a flow does have a schedule, we call the `_run_on_schedule` method which does a number of additional logic.

I would like to combine these into a single branch, because having two different pipelines leads to the potential for different behaviors depending on how you're running a flow (an issue that plagues Airflow). For example in #1429 I realized that tasks results are returned when running on schedule, but not returned when running off schedule.

A solution would be to simply create a "one-off" schedule and call `_run_on_schedule()` no matter what, with the caveat that the schedule would need to be removed so it didn't overwrite the original flow schedule.

**Comment by cicdw** [comment]
> For example in #1429 I realized that tasks results are returned when running on schedule, but not returned when running off schedule.

Something about this is strange to me, as I have been using `flow.run()` for schedule-less flows and getting task results back (see, for example, my most recent PR'ed tutorial).  But I see in the code you changed how it could occur 🤔

**Comment by lauralorenz** [comment]
The PR for this was released in 0.11.0, looks like the issue didn't get closed for some reason so closing now.
