### ISSUE TITLE
Improve terminal output layout  

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#14331]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

3.0rc/manage/cloud/troubleshoot-cloud

### Describe the proposed change

Move some lines so output lines up better.
<img width="630" alt="Screenshot 2024-06-25 at 11 46 15 AM" src="https://github.com/PrefectHQ/prefect/assets/7703961/4ddd7910-28a0-46a1-8ee9-ccdbbb689a46">

**Comment by zzstoatzz** [comment]
@discdiver can you provide more details about how you're getting this?

I can't quite replicate this with just `prefect cloud workspace ls`

**Comment by discdiver** [comment]
@zzstoatzz just trying to improve the formatting in the docs
