### ISSUE TITLE
Move global pause/resume toggle to schedule section of the deployment page

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#14388]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

The toggle in the top right corner of the deployment page could be interpreted as though it will globally control whether or not runs will be created, but it is in fact specific to _scheduled_ runs.

### Describe the proposed behavior

The toggle should be moved to the top of the "Schedules" section on the deployment page and only be displayed if there are multiple schedules.

![Screenshot 2024-06-27 at 4 38 35 PM](https://github.com/PrefectHQ/prefect/assets/3407835/bef757fc-514a-44ac-9ae2-1c50237dc5e9)

**Comment by pleek91** [comment]
It might be a good idea to add a tooltip to the toggle so when hovering the user sees something like "disable all schedules"/"enable all schedules". We'll also probably want to disable all of the individual schedule toggles when this main toggle is disabled.

**Comment by billpalombi** [comment]
@pleek91 yes, we definitely want to do both of those things.
