### ISSUE TITLE
Every code example in the Deploy docs should include a companion YAML example

### ISSUE THREAD

**Issue by daniel-prefect** [PrefectHQ/prefect#14386]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

YAML is how teams often want to define deploys in production. We should support this by updating our docs to show this approach alongside the traditional Python approach. The less people have to do the translation in their heads, the more successful they'll be.

### Describe the proposed change

We've got a section of a page dedicated to showing how to define deployments in YAML: https://docs-3.prefect.io/3.0rc/deploy/control-runs/prefect-deploy#create-work-pool-based-deployments-with-prefect-yaml

Let's replace this with inline examples next to each code block in the Deploy docs that show the equivalent YAML for every Python example. We can use the tabs component to add YAML examples without making the pages any longer.

**Comment by discdiver** [comment]
We now have separate pages for for creating deployments with .deploy and with prefect.yaml. 

We also have a flow code storage doc that shows how to deploy code with both options.

Closing the issue and if there are specific examples that are needed for either deployment creation method, let's open those as their own issue.
