### ISSUE TITLE
Docker Image for 3.0 in Tutorial Missing Tag

### ISSUE THREAD

**Issue by AaronWGoh** [PrefectHQ/prefect#14384]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`gcloud run deploy prefect-worker --image=prefecthq/prefect:3-latest \`
in https://docs-3.prefect.io/integrations/prefect-gcp/gcp-worker-guide does not work

Noticed in https://hub.docker.com/r/prefecthq/prefect/tags that there is no 3-latest tag

### Reproduction

```python3
gcloud run deploy prefect-worker --image=prefecthq/prefect:3-latest \
--set-env-vars PREFECT_API_URL=$PREFECT_API_URL,PREFECT_API_KEY=$PREFECT_API_KEY \
--service-account <YOUR-SERVICE-ACCOUNT-NAME> \
--no-cpu-throttling \
--min-instances 1 \
--args "prefect","worker","start","--install-policy","always","--with-healthcheck","-p","<WORK-POOL-NAME>","-t","cloud-run"
```

### Error

```python3
ERROR: (gcloud.run.deploy) Revision 'prefect-worker-00001-kjv' is not ready and cannot serve traffic. Image 'docker.io/prefecthq/prefect:3-latest' does not exist or it is not publicly accessible

Error response from daemon: manifest for prefecthq/prefect:3-latest not found: manifest unknown: manifest unknown
```

### Versions (`prefect version` output)

```Text
Version:             3.0.0rc9
API version:         0.8.4
Python version:      3.11.0
Git commit:          b75631a7
Built:               Mon, Jun 24, 2024 5:50 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.7.4
```

**Comment by zhen0** [comment]
Thanks for flagging @AaronWGoh - we'll take a look into this one.

**Comment by zhen0** [comment]
Actually I'm going to close in favor of the more specific https://github.com/PrefectHQ/prefect/issues/14228
