### ISSUE TITLE
Enforce PR Labeling

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#14399]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

To generate quality release notes, PRs must be tagged with their purpose (e.g. fix, enhancement, maintenance, etc.). Sometimes, PR submitters forget to tag their PRs, which leads to a large ‘Uncategorized’ section in our generated release notes. We should add a workflow that checks for tags on a PR and fails if a PR is not tagged.

**Comment by zhen0** [comment]
Possibly related - https://github.com/PrefectHQ/prefect/pull/14482
