### ISSUE TITLE
Artifact Sorting by Update Time

### ISSUE THREAD

**Issue by brnguyen** [PrefectHQ/prefect#14434]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

3.x

### Describe the current behavior

Prefect currently allows filtering of the Artifacts page by artifact type (markdown or table) but does not allow for sorting of any kind (alphabetical, update time, etc.).

### Describe the proposed behavior

I would like to have an additional sort button along the top of the screen that allows for an ordered view of the artifacts, ideally sortable using common Artifact qualities like alphabetical order or most recent update time.

### Example Use

Checking the most recently updated artifacts for new changes/alerts, ordering the artifact list for easier perusal.

### Additional context

I'm not sure how the current artifacts page is sorted, and I understand there's a push to remove the use of the Artifacts page entirely, but I'd like it to be a bit more functional than it is currently (and also eventually see it in the navbar again).

**Comment by WillRaphaelson** [comment]
Thanks for the issue @brnguyen, at this time we're not bringing the artifacts page back and are prioritizing feature requests related to their display on the flow run page.
