### ISSUE TITLE
Image override in `job_variables` not applied for custom flow runs for GCP Cloud Run Push work pool

### ISSUE THREAD

**Issue by MartijnvanElferen** [PrefectHQ/prefect#14442]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When creating a custom flow run for a deployment using a GCP Cloud Run Push work pool, the 'image' value specified in job_variables is not being applied to override the default image. While Prefect correctly acknowledges the custom image in the flow run creation response and UI, the actual execution on Google Cloud Run still uses the default image from the deployment, ignoring the override attempt.

### Reproduction

I Created a GCP Cloud Run Push V2 work pool with the default job template, and left the image variable empty. Then, I deployed a flow using the .deploy method.
```python3
if __name__ == "__main__":
    process_pricing_xx_files.deploy(
        parameters={"host": 'sysmgr.xxx.com', "username": 'FTP-Agent'},
        work_pool_name="cloud-run-push-pricing",
        image="eu.gcr.io/xxx/prefect/prefect-pricing:production",
        build=False
    )
```
I attempted to run the deployment with a custom image (note the image tag!) using the CLI:
```
prefect deployment run \
--id "de27fd5c-eab1-4f40-8bbc-7a6684e1ceb2" \
--job-variable image="eu.gcr.io/xxx/prefect/prefect-pricing:development"
```
I observed that Prefect correctly acknowledged the custom image in the flow run creation response:
```
Created flow run 'dramatic-swan'.
└── UUID: 8eb04784-b910-43b9-8e94-48c91fc93ac1
└── Parameters: {'host': 'sysmgr.xx.com', 'username': 'FTP-Agent'}
└── Job Variables: {'image': 'eu.gcr.io/xxx/prefect/prefect-pricing:development'}
└── Scheduled start time: ...
└── URL: ...
```
I also verified in the Prefect UI the flow run page showing the correct overriden image under Job Variables.
Then I checked Google Cloud Run and found that the job was still using the production image instead of the development image specified in the custom run.

This reproduction demonstrates that while Prefect acknowledges the custom image in its responses and UI, the actual execution on Google Cloud Run does not use the overridden image value.

### Versions (`prefect version` output)

```Text
Version:             2.19.7
API version:         0.8.4
Python version:      3.12.3
Git commit:          60f05122
Built:               Fri, Jun 28, 2024 11:27 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

### Additional context

Thread in Slack regarding this issue can be found [here](https://prefect-community.slack.com/archives/CM28LL405/p1718641246531769).

**Comment by zzstoatzz** [comment]
hi @MartijnvanElferen - thanks for the issue!

we've identified that this is specific to push pools and are working on a fix now - update to come!

**Comment by zzstoatzz** [comment]
hi @MartijnvanElferen !

This was a problem related to all push pools (something we take care of on the Prefect Cloud side) and the fix should now be rolled out into Prefect Cloud.

Can you confirm that job variables overrides are respected for runs against your push work pool now?

**Comment by MartijnvanElferen** [comment]
Hi @zzstoatzz ,

I can confirm that the job variable override now works as expected. 

Thank you for resolving this issue!

**Comment by zhen0** [comment]
Thanks @MartijnvanElferen - closing as completed!
