### ISSUE TITLE
How should environments be loaded in Cloud?

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1445]
Currently, environments are loaded via marshmallow deserialization here: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/execute.py#L66-L67

This works great, except that it prevents users from implementing custom execution environments.  Because this CLI typically runs inside a docker container containing the Flow bytecode, we could load that, etc. but then we're taking over the responsibilities of `environment.execute()`, which IMO means we have a leaky abstraction somewhere.

Our ideal solution to this problem should support:
- custom user environments
- the (future) ability to specify environments on a per-flow-run basis
- labels on custom environments should be readable on the Cloud-side through the marshmallow deserialization process

**Comment by joshmeek** [comment]
What do you mean when you say _we're taking over the responsibilities of `environment.execute()`_?

**Comment by cicdw** [comment]
`environment.execute` currently accepts a flow location string (which is typically the filesystem location of the flow in the docker container), and loads the flow, etc.

If the CLI starts doing that loading from disk, they now share mixed responsibilities - so we'd either have to break the environment interface or redundantly reload the flow.

**Comment by cicdw** [comment]
As discussed with @joshmeek we could:
- load the storage from the Cloud serialization protocol
- call `get_flow` to retrieve the actual flow object
- use `flow.environment` directly, which would allow for user-written environments

The interface becomes a little redundant (loading the flow twice...) but we could work around that by introducing a new keyword argument to `environment.execute` which accepts an _actual_ flow object and bypasses the load.  This would allow for environments which need to load the flow themselves, or environments which can accept flow objects directly.
