### ISSUE TITLE
Backporting Added print_func to run_namespaced_job flow to Prefect 2.x

### ISSUE THREAD

**Issue by netanel246** [PrefectHQ/prefect#14462]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I run a Kubernetes job using func run_namespaced_job, but my prefect-ui couldn't show the job's log.

### Reproduction

```python3
https://github.com/PrefectHQ/prefect/issues/12993
```

### Versions (`prefect version` output)

```Text
Version:             2.18.3
API version:         0.8.4
Python version:      3.10.12
Git commit:          c449aee8
Built:               Thu, May 2, 2024 5:47 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

Backporting this PR to Prefect 2.x:
https://github.com/PrefectHQ/prefect/pull/14103

**Comment by zhen0** [comment]
Thanks for the issue @netanel246!  Would you be up for backporting this by opening a PR against the 2.x branch in the Prefect repo?  (No pressure I can add to our backlog to do for 2.x but since you created the original PR it would be great to have you take it on.)

**Comment by zhen0** [comment]
(I'm adding the waiting for user label just to remind me to check back on it next week and see if you'd like to contribute!)

**Comment by netanel246** [comment]
PR created:
https://github.com/PrefectHQ/prefect/pull/14463
Thanks.

**Comment by zhen0** [comment]
Thank you!

**Comment by WillRaphaelson** [comment]
Thanks @netanel246
