### ISSUE TITLE
Prefect UI logging interprets any tag like strings as HTML

### ISSUE THREAD

**Issue by MikeZ77** [PrefectHQ/prefect#14498]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When logging a markup language (such as XML) or format that uses tags , the Prefect UI seems to interpret this logging as HTML. As a result, the logs do not show the original string that is retrieved from the API.

While in the case of an XML it makes more sense for it to be saved as an artifact, you should still be able to log it without using HTML character entities like &lt and &gt. Furthermore even something as simple as `"Token: <abc>"` will not render correctly. 

### Reproduction

```python
from prefect import task, flow, get_run_logger


@task
def log_my_tags():
    simple_xml = """
    <?xml version="1.0" encoding="UTF-8"?>
        <book>
        <title>Example Book Title</title>
        <author>John Doe</author>
        <publisher>Example Publisher</publisher>
        <year>2024</year>
        <isbn>123-4567890123</isbn>
    </book>
    """
    logger = get_run_logger()
    logger.info(simple_xml)


@flow
def my_flow():
    log_my_tags()


if __name__ == "__main__":
    my_flow()
```

### Error

![image](https://github.com/PrefectHQ/prefect/assets/25214720/48a0a6e5-50ab-4f4e-bac9-9a815a2e8007)

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
2.19.7
```

**Comment by pleek91** [comment]
@MikeZ77 thanks for the issue. This is [fixed](https://github.com/PrefectHQ/prefect-ui-library/pull/2569) in 3.0 which is currently in RC status. There are also some other enhancements to logs like [supporting ANSI colors](https://github.com/PrefectHQ/prefect-ui-library/pull/2582) in logs. Going to close this issue for now but if more people want this and are unable to migrate we'll revisit backporting this into 2.x
