### ISSUE TITLE
host.md intro paragraph has faulty list rendering

### ISSUE THREAD

**Issue by oaustegard** [PrefectHQ/prefect#14506]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

The intro paragraph renders as 
```
<p>After installing Prefect, you have:
- a Python SDK client that can communicate with <a href="https://app.prefect.cloud/">Prefect Cloud</a>
- an <a href="[/api-ref/](https://docs.prefect.io/api-ref/)">API server</a> instance backed by a database and a UI</p>
```
rather than the list as intended

### Describe the proposed change

Add a blank line before the first list element

**Comment by discdiver** [comment]
Completed in #14505
