### ISSUE TITLE
The `generate-release-notes.py` script should output the sections in the correct order.

### ISSUE THREAD

**Issue by bunchesofdonald** [PrefectHQ/prefect#14564]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Describe the current behavior

When we use the `generate-release-notes.py` script to generate release notes we don't re-order the sections as we want them in the final notes.

### Describe the proposed behavior

The script should output the sections in the order we want in the final notes. Namely the "New Contributors" section should come last, but we should review the ordering of all the sections.

**Comment by cicdw** [comment]
We no longer use this script
