### ISSUE TITLE
Prefect Teams Notification Block Broken Due to Transition to 'Workflows'

### ISSUE THREAD

**Issue by JI-Michael** [PrefectHQ/prefect#14575]
### First check

- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I added a descriptive title to this issue.
- [x] I searched the Prefect documentation for this issue.
- [x] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are currently using the Prefect Teams Notification Block, which relies on the Teams Webhook for notifications. However, since the transition of Teams to 'Workflows,' this functionality appears to be broken. For more details on the transition, please refer to this [blog post](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/).

**Steps to Reproduce**

1. Set up a Prefect Teams Notification Block with the Teams Webhook.
2. Trigger a workflow that should send a notification.
3. Observe that the notification is not sent due to the transition to 'Workflows.'

**Expected Behavior**
The Prefect Teams Notification Block should send notifications through the Teams Webhook without issues.

**Actual Behavior**
No notifications are being sent because the integration with the Teams Webhook is broken due to the recent changes in Teams.

Would it be possible to look into updating the Prefect Teams Notification Block to be compatible with the new Teams 'Workflows' functionality?

### Reproduction

```python3
**Steps to Reproduce**

1. Set up a Prefect Teams Notification Block with the Teams Webhook.
2. Trigger a workflow that should send a notification.
3. Observe that the notification is not sent due to the transition to 'Workflows.'
```

### Versions (`prefect version` output)

```Text
2.19.8
```

**Comment by toby-coleman** [comment]
Another vote for this. As a workaround I've been able to get flow run notifications working again via Workflows with the following steps:
1. Create a workflow in Teams using [this template](https://make.powerautomate.com/environments/Default-34d75f81-2748-425c-b290-d6c44ff6c053/galleries/public/templates/d271a6f01c2545a28348d8f2cddf4c8f);
2. Add a standard `Webhook` block (of type `POST`) in the Prefect workspace, pointing to the URL from step (1);
3. In the automation, set the `Body` to look like the example below, customising as appropriate.

```json
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "wrap": true,
            "text": "Flow run [**{{ flow.name }}/{{ flow_run.name }}**]({{ flow_run|ui_url }}) observed in state **{{ flow_run.state.name }}** at {{ flow_run.state.timestamp }}.\n\n*{{ flow_run.state.message }}*"
          }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.2",
        "msteams": { "width": "full" }
      }
    }
  ]
}
```

**Comment by caronc** [comment]
I would love to add support, but i will need time.  Since you see more traffic on your project then i do in mine, maybe I could ask for help with a PR if anyone is intersted or reading.  I can take it on, but just not right away (to many projects at work on the go).
