### ISSUE TITLE
Cache collections after loading from disk

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#14574]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Describe the current behavior

Whenever we load a Block using the type string like `string/myblock`, we also load all collections from disk, even if we've already loaded them. So this code runs repeatedly: https://github.com/PrefectHQ/prefect/blob/main/src/prefect/plugins.py#L41

### Describe the proposed behavior

We should cache collections after the first load. It seems unlikely that the collections will change on disk during the life of the Python process.

**Comment by zzstoatzz** [comment]
It appears that `safe_load_entrypoints` already effectively "caches" this work via python module caching. as in, `safe_load_entrypoints` happens each time you load a block (from a type string) but it doesnt take any time at all after the first time you do, which is effectively the same as having an lru_cache on `load_prefect_collections`
