### ISSUE TITLE
Include prefect version as part of the event

### ISSUE THREAD

**Issue by jakekaplan** [PrefectHQ/prefect#14580]
- All events from the `EventWorker` should include the label `prefect.version` on resources and related resources
- ~~On the task.run resource for task run events include a label of `"prefect.orchestration": "client"` indicating that this event was orchestrated client side (which is conditional on the feature flag)~~ <- done in https://github.com/PrefectHQ/prefect/pull/14627

**Comment by chrisguidry** [comment]
I'd also include some indicator of whether the new feature flag is enabled

**Comment by jakekaplan** [comment]
@chrisguidry sounds good. Added! 

Should all this information be in the payload? I thought it would be helpful to have `prefect.version` on all events, but not sure the natural spot for it.

**Comment by chrisguidry** [comment]
OOO interesting, we could add that as a label to all resources and related resources coming from the client, that's an awesome idea.  I think the `EventsWorker` queue service could add that in generically.

I think we could also include a label on the task run resource for these events that indicates whether it's client-side orchestrated or not.  Maybe `"prefect.orchestration": "client"`?
