### ISSUE TITLE
Prefect 2: Migrate to AnyIo 4

### ISSUE THREAD

**Issue by aaazzam** [PrefectHQ/prefect#14671]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Describe the current behavior

AnyIO < 4.4.0 has a CVE (https://security.snyk.io/vuln/SNYK-PYTHON-ANYIO-7361842). 

### Describe the proposed behavior

Prefect pins it's AnyIO dependency to ~<4, out of respect for their breaking API changes.

**Comment by zhen0** [comment]
Related PR - https://github.com/PrefectHQ/prefect/pull/14599

**Comment by abrookins** [comment]
I'm continuing to work on this migration, which we're targeting for this week's release. The biggest change affecting us is that AnyIO 4 changed the way that `TaskGroup` propagates exceptions, such that if an async task within the group raises an exception, the outside scope receives a `BaseExceptionGroup`, not the exception itself, and groups can be nested if the exception happened within nested `TaskGroup`s.
