### ISSUE TITLE
Deployment run steps clobbering with two custom steps and the second with set id

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#14689]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have two the same, or with the similar output, steps in my deployment pull section. If i give an ID to my second step, i would expect that the output from my first step would be protected from clobbering, but instead the second one still rewrites that.

From the code i can see in `prefect.deployments.steps.core:r184:r187`:
```python
            # store step output under step id to prevent clobbering
            if inputs.get("id"):
                upstream_outputs[inputs.get("id")] = step_output
            upstream_outputs.update(step_output)
```
The upstream outputs update is not in `else` section, thus always clobbering. Is this indented?

### Reproduction

```python3
# test_steps.py

from prefect.deployments.steps.core import run_steps
import asyncio


def my_step(value: int):
    return {"result": value * 2}


if __name__ == "__main__":
    outputs = {}
    outputs = asyncio.run(
        run_steps([
            {"test_steps.my_step": {"value": 1}},
            {"test_steps.my_step": {"value": 2, "id": "step2"}},
        ], upstream_outputs=outputs)
    )
    print(outputs)  # {'result': 4, 'step2': {'result': 4}}
```

### Versions (`prefect version` output)

```Text
Version:             3.0.0rc10
API version:         0.8.4
Python version:      3.11.9
Git commit:          200cf212
Built:               Wed, Jul 3, 2024 1:39 PM
OS/Arch:             linux/x86_64
Profile:             client
Server type:         server
Pydantic version:    2.8.2
```

**Comment by zzstoatzz** [comment]
hi @GalLadislav - it is intended that top-level keys can be overwritten by subsequent steps. You can use an id for the upstream step to avoid this, like

```python
# test_steps.py

from prefect.deployments.steps.core import run_steps
import asyncio


def my_step(value: int):
    return {"result": value * 2}


if __name__ == "__main__":
    outputs = {}
    outputs = asyncio.run(
        run_steps([
            {"test_steps.my_step": {"value": 1, "id": "step1"}},
            {"test_steps.my_step": {"value": 2, "id": "step2"}},
        ], upstream_outputs=outputs)
    )
    print(outputs)  # {'result': 4, 'step2': {'result': 4}}
```

**Comment by zzstoatzz** [comment]
feel free to let us know if this recommendation does not work for you!

**Comment by GalLadislav** [comment]
Thank you for clarification. Could be useful to mention it in the docs. Nwm if i just did not noticed it.
