### ISSUE TITLE
CannotPullContainerError 504 Gateway Time-out (Prefect Cloud + ECS Push)

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#14730]
### Bug summary

Using Prefect Cloud + ECS push work pools.
Got this error:
```
Flow run could not be submitted to infrastructure: TaskFailedToStart - CannotPullContainerError: ref pull has been retried 1 time(s): failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/yaronlevi/prefect/blobs/sha256:69e520adb67b68085b2dd29b69cba037002d8f53234a3e9676c2969fc3099e86: 504 Gateway Time-out
```

Happened at:
2024/07/24 13:01:38 UTC

Notice that it's a 504 Gateway Time-out, and NOT a 429 too many requests error (which is in a similar issue I've opened in the past).

[link run](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/runs/flow-run/098c9d3b-ca35-49f4-864a-19d11b579a30)

![CleanShot 2024-07-24 at 16 53 29@2x](https://github.com/user-attachments/assets/bb43336b-aad5-4b30-aaee-43ecf561fa74)

Docker hub looks ok:
![CleanShot 2024-07-24 at 16 54 25@2x](https://github.com/user-attachments/assets/e240152f-1fee-4d43-a21f-3f5f0a4e12dc)

### Version info (`prefect version` output)

```Text
Prefect Cloud + prefect == 2.16.6 in req.txt
```

**Comment by yaronlevi** [comment]
We two other runs that failed with the same error at that specific time.

**Comment by cicdw** [comment]
Hi @yaronlevi - a 504 means docker's API refused the request due to an issue on their end; what is your expected outcome here / what are you hoping for Prefect to change?  It looks like ECS retried the request but still got the 504 response.

**Comment by yaronlevi** [comment]
@cicdw I think Prefect backend should also implement a retry of it's own in such case. I think there is no way to solve this by Prefect's automation feature because the trigger of "flow entered state crashed" is too general. Meaning, it might crashed because of other reasons.

**Comment by yaronlevi** [comment]
Here is another fresh example:

[run url](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/runs/flow-run/03a420c7-797e-42b9-a509-9019b02b32d7)

We are seeing more and more of these in the last few days.

![CleanShot 2024-07-25 at 14 40 33@2x](https://github.com/user-attachments/assets/7a5f878c-ee40-4065-92f0-26a34657f38d)

**Comment by cicdw** [comment]
We plan to implement crash based retries soon (see https://github.com/PrefectHQ/prefect/issues/10211 for tracking the status of that work).

Prefect can only meaningfully retry operations that occur in the interface between Prefect <-> external system.  The error you are showing here is an error between ECS <-> DockerHub, which is a place Prefect doesn't have control (other than through the configuration of the job).  Hopefully the crash-based retries will help you here.

If this continues occurring for you I recommend reaching out to both [DockerHub support](https://hub.docker.com/support/contact) and ECS support.

Closing in favor of #10211
