### ISSUE TITLE
GitRepository Submodule Clone Issue

### ISSUE THREAD

**Issue by Punit-Solanki** [PrefectHQ/prefect#14731]
### Bug summary

We are currently working with Prefect and encountered a bug related to the GitRepository class, specifically regarding the inclusion of submodules during the repository pull process. Our GitHub repository is structured in a way that it has one submodule (a repository embedded in the main repository). However, when we create a deployment on Prefect Cloud, it is unable to pull the submodule. We tried using the syntax highlighted in the code snippet below, but it doesn't work as expected and we are seeing 'ModuleNotFoundError' on Prefect.

```python
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret 


if __name__ == "__main__":
    process_data.from_source(
        source=GitRepository(
            url="https://github.com/xyz/abc.git",
            include_submodules=True,
            credentials={"access_token": Secret.load("github-access-token")}
        )
    )
```
 
 We have configured the secret block in Prefect which has our GitHub PAT (personal access token). 
 
 
![submodule error](https://github.com/user-attachments/assets/5ed8d980-ca2d-4c9e-8351-edc09efb8e40)

"git_quicksilver_hol" being referred here is the submodule in our case and it looks something like this:

![image](https://github.com/user-attachments/assets/561aaea8-22dd-4821-8751-b5bb10d65ea5)

Would like to get more insights on how to use submodules here.

### Version info (`prefect version` output)

```Text
prefect==2.19.4
```

**Comment by Punit-Solanki** [comment]
Hi @cicdw - Thank you for your prompt response!

I can confirm that we have an `__init__.py` in our submodule. Additionally, I can confirm that when I perform a `git clone` locally with the `--recurse-submodules` flag, the submodule is pulled successfully. The PAT used for authentication in both cases (local and on Prefect) remains the same.

**Comment by cicdw** [comment]
@Punit-Solanki could you share the entrypoint that you are passing to `from_source`?  I tried to replicate something similar locally but wasn't able to yet, but it's possible that my directory structure is significantly different from yours.

Here's what I tried: I made a directory that looks like
```
repo/
  flows.py
  submodule/
    __init__.py # contains `AN_OBJECT=42`
```
and `flows.py` looks like:
```python
from submodule import AN_OBJECT
from prefect import flow

@flow 
def my_flow():
    return AN_OBJECT
```

Then, from one directory _above_ the `repo/`, I ran:
```python
from prefect.flows import load_flow_from_entrypoint

flow = load_flow_from_entrypoint(entrypoint="repo/my_flows.py")
```

**Comment by Punit-Solanki** [comment]
Hi @cicdw

This is what our repository structure looks like. 

```
repo/
├── test.py
├── deployments.py
└── git-quicksilver-hol (submodule)/
    ├── blocktypes/
    │   ├── ftp-block.py
    │   └── dremio-block.py
    └── __init__.py
```

We have a `test.py` with the following content. This runs fine because we are running it locally (not creating any **deployment** on Prefect).

```python
from prefect import flow, task
from git_quicksilver_hol.blocktypes.dremio_block import DremioBlock


@flow(log_prints=True)
def process_function():
    print("I'm here")
```

Then we have a `deployments.py` as follows. However, here we are creating a deployment on Prefect using the .deploy function. This fails with the error "Failed due to a ModuleNotFoundError when trying to retrieve a flow from deployment because the module 'git_quicksilver_hol.blocktypes' could not be found."

```python
from test import process_function
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret

if __name__ == "__main__":
    process_function.from_source(
        source=GitRepository(
            url="https://github.com/xyz/abc.git",
            include_submodules=True,
            credentials={"access_token": Secret.load("github-access-token")}
        ),
        entrypoint="test.py:process_function"
    ).deploy(
        name="test-deployment",
        work_pool_name="demo-pool",
        tags=["abc", "xyz"],
        interval=300 # every 5 minutes
    )
```

Does this give you more clarity on the repo structure?

**Comment by cicdw** [comment]
Yup that's perfect thank you @Punit-Solanki - I should be able to recreate from here; the one last thought I have is to try adding an `__init__.py` to `blocktypes/` and the root `repo/` just in case.

**Comment by Punit-Solanki** [comment]
Hi @cicdw 

```
repo/
├── __init__.py  # Added
├── test.py
├── deployments.py
└── git-quicksilver-hol (submodule)/
    ├── __init__.py  # Added
    ├── blocktypes/
    │   ├── __init__.py  # Added
    │   ├── ftp-block.py
    │   └── dremio-block.py
    └── __init__.py  # Added
```

Tried it with this structure. Still the same.

**Comment by Punit-Solanki** [comment]
Hi @cicdw 

Were you able to replicate the scenario?

**Comment by cicdw** [comment]
Hey @Punit-Solanki apologies for the delay - this week has been busy for me but I'll be able to work on this issue this weekend / early next week and I'll report back 👍

**Comment by cicdw** [comment]
Hey @Punit-Solanki -- good news: I've got a working MRE [here](https://github.com/cicdw/mre-14731). It appears that we are not persisting the `include_submodules` flag when the worker pulls the repo.  I should be able to get a fix out for this week's release!

**Comment by Punit-Solanki** [comment]
That sounds great. Thanks a ton for the prompt responses and dedicated support @cicdw

**Comment by Punit-Solanki** [comment]
Thank you @cicdw for getting the fix out! I can see the bug fix under the release notes.

https://github.com/PrefectHQ/prefect/releases/tag/3.0.0rc15

Just a quick question, do I need to update my prefect-cli or prefect version to test the fix?

**Comment by cicdw** [comment]
Hey @Punit-Solanki ! Yes, you'll need to update the `prefect` package in order to get this fix - we included the fix in both `3.0.0rc15` as well as `2.20.1` (which is being released imminently).  I recommend upgrading to `2.20.1` and managing the upgrade to 3.x separately.

**Comment by Punit-Solanki** [comment]
Hi @cicdw 

We have successfully upgraded our Prefect version to '2.20.1'. As a part of our initial testing, the fix implemented with this release seems to partially work with our use case. While working with the created [MRE](https://github.com/cicdw/mre-14731), it works just fine. However, we run into an issue when we use our private repositories with PAT-based authentication.

The code we are using remains the same:

```python
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret 


if __name__ == "__main__":
    process_data.from_source(
        source=GitRepository(
            url="https://github.com/xyz/abc.git",
            include_submodules=True,
            credentials={"access_token": Secret.load("github-access-token")}
        )
    )

```
The error that we are getting is this:

![image](https://github.com/user-attachments/assets/033f032b-49fc-4c70-a40d-87f9388e0028)


What we have tried so far:

- Adding username along with access token for authentication as follows:

```python
credentials={"username": "my-username", "access_token": Secret.load("github-access-token")}
```

- Adding `'oauth2'` as the username

How we know the personal access token is working and there is no issue with the runner:

**On the runner, we manually tried cloning the repository using the same username and PAT. It works fine.**

Would you be able to provide additional insights here? Also, please advice if we can continue the discussion in this thread or should I create a separate issue?

**Comment by cicdw** [comment]
Hey @Punit-Solanki - I have a theory: many Prefect methods / utilities are compatible with both asynchronous and synchronous execution.  This can be useful occasionally but often results in quiet failure modes.  In this case, I have a hypothesis that `Secret.load(...)` is trying to run asynchronously and therefore is _not_ actually loading your secret.

To try and fix it, use this:

```python
## note the _sync=True kwarg on Secret.load
credentials={"username": "my-username", "access_token": Secret.load("github-access-token", _sync=True)}
```

Let me know if that resolves the issue for you, and apologies for the friction!!

**Comment by Punit-Solanki** [comment]
Hi @cicdw 

Thank you for the prompt response.

I tried this:

```python
credentials={"access_token": Secret.load("github-access-token", _sync=True)}
```

Seems like the issue still persists as we are getting the same error.

**Comment by cicdw** [comment]
You could try to recreate the error this way:
```python
storage = GitRepository(
            url="https://github.com/xyz/abc.git",
            include_submodules=True,
            credentials={"access_token": Secret.load("github-access-token", _sync=True)}
        )

await storage.pull_code()
```

**Comment by Punit-Solanki** [comment]
Hi @cicdw 

Apologies for the delayed response.

We modified our code as follows to await the method as follows:

```python
import asyncio
from test import process_function
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret

async def main():
    # Initialize GitRepository and pull code
    storage = GitRepository(
        url="https://github.com/xyz/abc.git",
        include_submodules=True,
        credentials={"access_token": Secret.load("github-access-token", _sync=True)}
    )
    await storage.pull_code()

    # Await the from_source function
    deployment = await process_function.from_source(
        source=storage,
        entrypoint="test.py:process_function"
    )
    
    # Now deploy
    await deployment.deploy(  # Await the deploy method
        name="test-deployment",
        work_pool_name="demo-pool",
        tags=["abc", "xyz"],
        interval=300 # every 5 minutes
    )

if __name__ == "__main__":
    asyncio.run(main())

```

We see no errors on the CLI:

![image](https://github.com/user-attachments/assets/082f822b-8ffd-46de-b07e-539dd1a27eb4)


The flow logs look like this:

![image](https://github.com/user-attachments/assets/a94f86dc-14f7-493a-a6f7-671b54e01ffb)

![image](https://github.com/user-attachments/assets/5fe4fb86-c909-455c-9f8b-9ef0f68030c1)

Once again, thank you for your patience!

**Comment by kevingrismore** [comment]
Hi @Punit-Solanki, so if you cut your example down to just this:

```python
import asyncio
from test import process_function
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret

async def main():
    # Initialize GitRepository and pull code
    storage = GitRepository(
        url="https://github.com/xyz/abc.git",
        include_submodules=True,
        credentials={"access_token": Secret.load("github-access-token", _sync=True)}
    )
    await storage.pull_code()

if __name__ == "__main__":
    asyncio.run(main())
``` 

Is the repository successfully cloned to your local machine? If so that may indicate some issue with how that source configuration is converted to a pull step.

**Comment by Punit-Solanki** [comment]
Hi @kevingrismore 

Yes, the repository was successfully cloned to my local machine. Also, I can perform a git clone on my runner manually which removes the possibility of any issues with the PAT (personal access token) being used to clone the repository.

Any way we can troubleshoot this further on our end?

**Comment by kevingrismore** [comment]
I was able to repro this with a pair of private repos where one is a submodule in the other.

The pull step on the deployment fails to pull the `outer` repo with
```
15:40:13.632 | ERROR   | prefect.runner.storage.git-repository.outer - Failed to pull latest changes with exit code Command '['git', 'pull', 'origin', '--recurse-submodules', '--depth', '1']' returned non-zero exit status 1.
```

Calling `.pull_code()` works fine locally, and if I switch the submodule repo to public but leave the outer repo private, the pull step works fine.
