### ISSUE TITLE
@task(retry_condition_fn=...) unable to catch Exceptions (3.0rc11)

### ISSUE THREAD

**Issue by jameswu1991** [PrefectHQ/prefect#14745]
### Bug summary

I'm following the tutorial here on [the prefect 3.0rc docs regarding custom retry behavior](https://docs-3.prefect.io/3.0rc/develop/write-tasks#custom-retry-behavior), and wish to add a custom retry_condition_fn for my task. I'd like to be able to catch a custom Exception `MyException` and retry.

Minimal reproducible example:
```
import traceback

from prefect import task


class MyException(Exception):
    pass

def retry_handler(task, task_run, state) -> bool:
    try:
        state.result()
    except MyException as e:
        print(f'MyException was caught: {e}')
        return True
    except Exception as e:
        print(f'Non-custom Exception caught: {e}')
        traceback.print_exc()
    return False

_globals = {}

@task(retries=10, retry_condition_fn=retry_handler)
def fail():
    _globals['call_counter'] = _globals.get('call_counter', 0) + 1
    raise MyException(f'This task failed, call_counter={_globals['call_counter']}')

if __name__ == '__main__':
    fail()
```

I expected this call to fail 11 times (with 10 retries), but observed that it only failed once.

Turns out, `MyException` was never caught, instead, the generic `Exception` was caught, and the exception is thus:

<details>
<summary>Traceback</summary>

```
Non-custom Exception caught: Run is in RUNNING state, its result is not available.
...
Traceback (most recent call last):
  File "/Users/james/exp/prefect-test/fail.py", line 11, in retry_handler
    state.result()
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/client/schemas/objects.py", line 261, in result
    return get_state_result(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/states.py", line 68, in get_state_result
    return _get_state_result(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 395, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 249, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 231, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 385, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/prefect-test/lib/python3.12/site-packages/prefect/states.py", line 120, in _get_state_result
    raise UnfinishedRun(
prefect.exceptions.UnfinishedRun: Run is in RUNNING state, its result is not available.
```

</details>

I added a Python debugger and it seems that the `state` variable is still stuck in the RUNNING state:
```
Running(message=None, type=RUNNING, result=None)
```

I ran a debugger on the exact code in the [Prefect 3 docs](https://docs-3.prefect.io/3.0rc/develop/write-tasks#custom-retry-behavior), turns out, its execution path also continued into the generic `except: return True` block with the same `UnfinishedRun` Exception.

I believe this code is still [relatively new (?)](https://github.com/PrefectHQ/prefect/pull/12856) and perhaps the `retry_condition_fn` hasn't had a full test written out for it yet. Apologies that I'm relatively new to prefect and don't have the capability to make a proposed fix via a PR, but thought I'd seek help and report the issue for the community for anyone else facing this.

### Version info (`prefect version` output)

```Text
(prefect-test) JamesMPB:prefect-test james$ prefect version
Version:             3.0.0rc11
API version:         0.8.4
Python version:      3.12.4
Git commit:          6604ec94
Built:               Wed, Jul 17, 2024 4:17 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-dask:      0.3.0rc2
```

**Comment by jameswu1991** [comment]
It seems that another use has encountered this problem as reported in the [Slack #marvin-in-the-wild thread](https://prefect-community.slack.com/archives/C03D12TE9HQ/p1717750633885309).

**Comment by cicdw** [comment]
Thanks for the thorough issue writeup @jameswu1991 ! I'll give this a look and let you know what I uncover - in the meantime I have a question for you: would it be better for you to configure this behavior through something like:

```python
@task(retry_on=[MyException])
def ...
```

so that you don't have to write a function with custom logic or anything?

**Comment by jameswu1991** [comment]
Hey @cicdw , thanks for the quick response! Having a `retry_on=[...ExceptionClasses]` argument would totally solve my use case. Our needs are relatively simple and we just want a general catch-all mechanism to retry all ChildExceptions that subclass a ParentException. 

However, I did appreciate the flexibility described in the documentation that allows me to, for example, examine custom attributes of the Exception (such as response status codes) to make the retry decision. We don't have such a use case right now, but I would imagine other users would still request for this feature.

**Comment by cicdw** [comment]
Makes sense, I'll still investigate the core bug but I'll also plan on exposing a new kwarg in 3.0 👍
