### ISSUE TITLE
Vertex AI worker does not persist service account name

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [PrefectHQ/prefect#14742]
### Bug summary

When submitting a job to Vertex AI, the `service_account_name` field in the worker is not provided to Vertex. 

### Version info (`prefect version` output)

```Text
Version:             2.16.5
API version:         0.8.4
Python version:      3.10.14
Git commit:          6d0ad745
Built:               Thu, Mar 21, 2024 3:41 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

This is blocking to using workers for Vertex for our team, and is a regression from agents. We are unable to query any other Google service from within the container, meaning it is essentially useless.

**Comment by jeremy-thomas-roc** [comment]
@desertaxle any chance I can get some one to take a look at this? with agents going EOL soon, this is a problem for us.

**Comment by desertaxle** [comment]
Yep, I can take a look at this today! I'll request you as a reviewer on the PR I submit so you can verify the fix.

**Comment by jeremy-thomas-roc** [comment]
> Yep, I can take a look at this today! I'll request you as a reviewer on the PR I submit so you can verify the fix.

Thank you so much!
