### ISSUE TITLE
RemoteEnvironment doesn't use storage.get_flow() in execute()

### ISSUE THREAD

**Issue by roveo** [PrefectHQ/prefect#1476]
Basically, this:

https://github.com/PrefectHQ/prefect/blob/6fe3fc31ce7023403ef0048e7ea1318501391111/src/prefect/environments/execution/remote.py#L68

I thought that an environment would use storage.get_flow() method to retrieve the flow to ensure universal compatibility of different envs/storages.

Not opened as a bug because I'm not sure it is, maybe I'm missing something.

**Comment by cicdw** [comment]
Hi @roveo - interesting catch!  The fix is simple enough, but we also need to implement `get_flow` on the Docker storage object.  This method call would only make sense when called _inside the Docker container itself_.
