### ISSUE TITLE
Documentation Request: ResultHandler

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#1478]
## Use Case
*Please provide a use case to help us understand your request in context*

I'm trying to create a custom ResultHandler for use with Prefect Cloud. I've noticed that the API Docs for the result handler ([here](https://docs.prefect.io/api/unreleased/engine/result_handlers.html#jsonresulthandler)) don't describe the interface of the ResultHandler class in sufficient detail for me to understand what I need to implement in a child class.

## Solution
*Please describe your ideal solution*

Please add more detail to the docs =]

**Comment by dylanbhughes** [comment]
It would be great if this documentation also provided best practices for secrets in result handlers

**Comment by UPetit** [comment]
> It would be great if this documentation also provided best practices for secrets in result handlers

Hi @dylanbhughes,
Your message has been sent a long time ago but maybe there is a chance that we could use secrets in result handlers (in my case I'm looking for using the secrets in the custom state handler)?

Thanks
