### ISSUE TITLE
After the session is expired, the Prefect Dashboard gets stuck in a session loop

### ISSUE THREAD

**Issue by ZhiWei-Kagr** [PrefectHQ/prefect#14780]
### Bug summary

With multiple tabs of Prefect Dashboard open, and using SSO, when the session expires, the dashboard gets into a state where it flips between the dialog that tells me the session is expired and the actual dashboard page. See attached video capture.

[https://github.com/user-attachments/assets/85d3134b-2f35-4be4-8649-5clc63c0d4d8b](https://github.com/user-attachments/assets/85d3134b-2f35-4be4-8649-5cc63c0d4d8b)

To resolve this, I have to clear my cookies. Closing the tab and starting a new tab, even from the Sign in link on [https://prefect.io](https://prefect.io) doesn't reset this behavior

### Version info (`prefect version` output)

```Text
Prefect Dashboard
```

### Additional context

I'm using Microsoft Edge for Business version 126.0.2592.113
I also have the dashboard installed as a web app using Edge's "Install site as app" feature.

**Comment by znicholasbrown** [comment]
Hi @ZhiWei-Kagr - thank you for opening an issue; we believe this has been addressed..

If you're still stuck, try closing _all_ Prefect Cloud tabs/windows (don't leave any in the background), clearing your cache, and trying again. 

Please feel free to re-open if you continue to experience the behavior.
