### ISSUE TITLE
How to get original task return value from AsyncCompatProxy after using submit() in Prefect 3.

### ISSUE THREAD

**Issue by zsio** [PrefectHQ/prefect#14832]
### Bug summary

I encountered an issue when using submit to trigger tasks in Prefect 3.0.0rc13. The result() method returns an object that appears to be a string, but its type is not str, which leads to a TypeError when trying to join the results.

```python
from prefect import task, flow

@task
def say_hello(name):
    return f"Hello {name}!"

@flow(name="hello-flow")
def hello_flow():
    one = say_hello.submit("one")
    two = say_hello.submit("two")
    results = "\n".join([i.result() for i in [one, two]])
    
    print(results, type(results[0]))

hello_flow()
```

When I run this code, I receive the following error:
```
TypeError: sequence item 0: expected str instance, AsyncCompatProxy found
```

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc13
API version:         0.8.4
Python version:      3.11.7
Git commit:          530521dd
Built:               Fri, Jul 26, 2024 1:24 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Pydantic version:    2.8.2
Server:
  Database:          sqlite
  SQLite version:    3.41.2
```

### Additional context

I need to use the submit() method to execute tasks concurrently, which is why I'm using result() to retrieve the values. However, result() returns an AsyncCompatProxy object instead of the original return value of the task.

I'm looking for a way to obtain the original value returned by the task function, even when using submit() for parallel execution. Ideally, there would be a method to unwrap or resolve the AsyncCompatProxy to get the actual string (or whatever type the task returns) without losing the benefits of concurrent execution provided by submit().

This issue is particularly important when working with tasks that return simple data types like strings, as in my example, where I'm trying to join the results of multiple tasks.

**Comment by desertaxle** [comment]
Thanks for the issue @zsio!

As you've discovered, 3.0 uses [`wrapt`](https://wrapt.readthedocs.io/en/master/index.html) to provide compatibility and warnings when using `await` with previously awaitable methods. I learned from the wrapt docs that there are some caveats when using their [`ObjectProxy` with primitive types](https://wrapt.readthedocs.io/en/master/index.html).

The workaround for this is to access the `__wrapped__` attribute on the return value from `.result()`. With that workaround, your code would look like this:
```
from prefect import task, flow

@task
def say_hello(name):
    return f"Hello {name}!"

@flow(name="hello-flow")
def hello_flow():
    one = say_hello.submit("one")
    two = say_hello.submit("two")
    results = "\n".join([i.result().__wrapped__ for i in [one, two]])
    
    print(results, type(results[0]))

hello_flow()
```

Now, that isn't great, and a better long-term solution needs to be found. One possible solution is to remove the compatibility proxy and fail hard when using `await` with `.result()`. There might be a more elegant solution that could make this work, so I'll keep thinking. If anyone who comes across this issue has any ideas, please leave a comment!
