### ISSUE TITLE
BUG: Task trigger name serializes the function instead of the name

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#1486]
**Why**
Queries for task triggers return something like:
`<function all_successful at 0x7fbfdd288c20>`
instead of the qualified serialization.

**What**
- [ ] a query for a task trigger returns the correct reference to the serialized name instead of the trigger function

**Comment by jlowin** [comment]
Note: this is actually a bug in a Cloud renderer, not a Core serializer. Fixed there.
