### ISSUE TITLE
Add json serializer for tasks that return a pydantic model

### ISSUE THREAD

**Issue by j-carson** [PrefectHQ/prefect#14938]
### Describe the current behavior

When a task wants to persist results, and those results are a pydantic model, the model must first be converted to a dictionary in order to use the JSONSerializer 

Pydantic models can be serialized directly to JSON without that intermediate step but Prefect's JSONSerializer does not support that at the moment

### Describe the proposed behavior

JSONSerializer accepts a pydantic model and serializes it, or an alternative PydanticSerializer exists for this use case

### Example Use

Rather than having
```
from prefect.serializers import JSONSerializer


@task(result_storage_key="~/filename.json", result_serializer=JSONSerializer)
def my_json_task(**kwargs):
    ...
    return my_obj.model_dump()
```

The task could return "my_obj" directly and it would be handled efficiently. 

### Additional context

This is an enhancement request from the community slack thread https://prefect-community.slack.com/archives/CL09KU1K7/p1723657276780109

**Comment by cicdw** [comment]
Confirmed that this is working as expected with 3.0, and sharing my example for others' reference

Saved this file in `issue-14938.py`:
```python
from pydantic import BaseModel, Field
from prefect import task, flow


class MyStuff(BaseModel):
    number: int
    string: str
    other: dict = Field(default_factory=dict)


@task(result_storage_key="my-json-task-output.json", result_serializer="json")
def my_json_task():
    my_obj = MyStuff(number=42, string="hello", other={"key": "value"})
    return my_obj


@flow
def main():
    my_json_task()


if __name__ == "__main__":
    main()
```

And ran it like this:
```
PREFECT_RESULTS_PERSIST_BY_DEFAULT='true' PREFECT_LOCAL_STORAGE_PATH="." python issue-14938.py
```

Everything ran smoothly, and had a new file in the present working directory called `my-json-task-output.json` that looked like this:

```
cat my-json-task-output.json
{"metadata":{"storage_key":"/Users/chris/dev/prefect/my-json-task-output.json","expiration":null,"serializer":{"type":"json","jsonlib":"json","object_encoder":"prefect.serializers.prefect_json_object_encoder","object_decoder":"prefect.serializers.prefect_json_object_decoder","dumps_kwargs":{},"loads_kwargs":{}},"prefect_version":"3.0.0rc20+11.gd215366b2c.dirty"},"result":"{\"__class__\": \"__main__.MyStuff\", \"data\": {\"number\": 42, \"string\": \"hello\", \"other\": {\"key\": \"value\"}}}"}%
```
