### ISSUE TITLE
Local server randomly not working with `prefect-ray`

### ISSUE THREAD

**Issue by dqueruel-fy** [PrefectHQ/prefect#14955]
### Bug summary

I've been using the local server (with `prefect server start` and using the default API: `127.0.0.1:4200`) for a couple of days and it was working fine. But this is the second time I have been facing an apparent dysfunction of the local server.

The first time I saw this issue is after upgrading my macbook pro (M2 Pro) to `14.6.1` but I can't say if this issue is related to the OS upgrade or not.

I'm using Chrome 127.0.6533.120 (Official Build) (arm64).

## Attempts
Here's what I've tried to make it work again, but that didn't work:
- Stoping and restarting the local server in the same terminal or other terminal. 
- Restarting my computer
- Cleared the data directory at `~/.prefect`
- Removed prefect and reinstalled it (also tried version 3.0.0rc16)
- Tried to reach the dashboard from Safari but I faced the same issue.

## Potential solution and current status
When facing this issue for the first time, it worked again after removing all python package relative to prefect (prefect + prefect-ray + prefect-docker), deleting the prefect folder (`~/.prefect`) and reinstalled prefect `3.0.0rc14` (and prefect-ray + prefect-docker).

It worked for the day but 'crashed' again later in the same day.
The second time I faced this issue, I've uninstalled / reinstalled only the `prefect` package and removed  `~/.prefect` folder that didn't solved the issue. I've also restarted my computer multiple times. **This is currently unsolved.**

## Questions
- Where can I have more logs or info about the local server that is running ? 
- Is there a more verbose mode for the local server ? 
- How can I ensure that local server is up and serving ? 

Thanks for your help !

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc14
API version:         0.8.4
Python version:      3.11.5
Git commit:          ad86991a
Built:               Thu, Aug 1, 2024 12:38 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-docker:    0.6.0rc4
  prefect-ray:       0.4.0rc2
```

## Detailed Issue
At some point during an local server execution the dashboard is no longer reachable `http://127.0.0.1:4200`. There was a bunch of different usual logs in the server but I unfortunately haven't saved those logs. If this happen again, I'll save it.
<img width="825" alt="image" src="https://github.com/user-attachments/assets/cd2ca72a-c331-42d6-b6dc-f0ad1f6f3d36">

When I start the local server I don't see any logs or issues in the terminal, but the dashboard is not reachable.
```
prefect server start

 ___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _| 
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| |___\___| |_|  

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200
```

**Comment by desertaxle** [comment]
Hey @dqueruel-fy! 

If you want to get more logging from your local server, you can set `PREFECT_LOGGING_SERVER_LEVEL` to `DEBUG` either as an environment variable or in your Prefect profile with `prefect config set PREFECT_LOGGING_SERVER_LEVEL=DEBUG`. The output from that increased log level will hopefully give us more info about why you aren't able to access the UI of your local server.

**Comment by desertaxle** [comment]
Interesting! I can also reproduce with the most recent RC versions of `prefect` and `prefect-ray`. I suspect this has something to do with `prefect-ray` misbehaving when we load integrations.

**Comment by captnced** [comment]
hello, I do confirm this issue; still persists with prefect 3.0.0rc20,
any idea what could be the root cause inside prefect-ray package ? 
what is it that the prefect server is doing when 'loading integrations' ? what is the entry point in the prefect-ray package ?

**Comment by kistenic-fy** [comment]
Hi,

I can confirm that the issue appears with the `rc11`. Up to `rc10` I did not see this issue.

**Comment by equidna** [comment]
Hi.
I can confirm the same problem with current prefect version 3.0.2 and prefect-ray integration 0.4.0.
Here are the details:

Version: 3.0.2
API version: 0.8.4
Python version: 3.10.12
Git commit: c846de02
Built: Fri, Sep 13, 2024 10:48 AM
OS/Arch: linux/x86_64
Profile: local
Server type: server
Pydantic version: 2.9.1
Integrations:
  prefect-ray: 0.4.0

Any idea of what might be the problem or any workarounds?

**Comment by ka7eh** [comment]
I'm still seeing this issue, even after the above PR.

```
Version:             3.0.3
API version:         0.8.4
Python version:      3.11.10
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-ray:       0.4.0
```

**Comment by desertaxle** [comment]
Hey @ka7eh! You'll need to upgrade to the version `0.4.1` of `prefect-ray` to get the fix.

**Comment by ka7eh** [comment]
> Hey @ka7eh! You'll need to upgrade to the version `0.4.1` of `prefect-ray` to get the fix.

Thanks! That was a quick release. :)
0.4.1 worked.

**Comment by udupa-varun** [comment]
Hi, just wanted to add on to this topic. I'm facing a very similar issue:
- no clues in the server log, with `PREFECT_LOGGING_SERVER_LEVEL` set to `DEBUG`
- tried deleting `~/.prefect` and reinstalling the python packages
- one of the differences is that I'm not using `prefect-ray`, but am using `prefect-email`

```
Version:             3.0.3
API version:         0.8.4
Python version:      3.10.11
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             win32/AMD64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-email:     0.4.0
```

**Comment by desertaxle** [comment]
Hey @udupa-varun! I wasn't able to reproduce the issue in an environment matching yours (Windows, Python 3.10, `prefect-email` installed). Would you be able to open a new issue if you're still seeing this issue?

**Comment by udupa-varun** [comment]
@desertaxle sure, I can do that!
