### ISSUE TITLE
ModuleNotFoundError: No module named 'griffe.dataclasses'

### ISSUE THREAD

**Issue by JieyuZhang-enverus** [PrefectHQ/prefect#14978]
### Bug summary

Recently changes are made towards the module names in griffe (version 1.0.0), which resulted in an error when importing prefect. 
The import line that causes the error
https://github.com/PrefectHQ/prefect/blob/2a797a710bff2e1c37c1485b59cd6d067931f5d1/src/prefect/utilities/callables.py#L15 
Prefect allows griffe version >= 0.20.0. https://github.com/PrefectHQ/prefect/blob/2a797a710bff2e1c37c1485b59cd6d067931f5d1/requirements.txt#L12C1-L12C17

The prefect version is 2.20.1

### Version info (`prefect version` output)

```Text
prefect version
Traceback (most recent call last):
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/__init__.py", line 37, in <module>
    from prefect.runner import Runner, serve
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/runner/__init__.py", line 1, in <module>
    from .runner import Runner, serve
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/runner/runner.py", line 59, in <module>
    from prefect.client.orchestration import PrefectClient, get_client
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/client/orchestration.py", line 32, in <module>
    import prefect.settings
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/settings.py", line 93, in <module>
    from prefect._internal.compatibility.deprecated import generate_deprecation_message
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/_internal/compatibility/deprecated.py", line 26, in <module>
    from prefect.utilities.callables import get_call_parameters
  File "/Users/jieyuz.hang/miniforge3/envs/placebo_env_prefect/lib/python3.8/site-packages/prefect/utilities/callables.py", line 17, in <module>
    from griffe.dataclasses import Docstring
ModuleNotFoundError: No module named 'griffe.dataclasses'
```

**Comment by cicdw** [comment]
The [client requirements correctly bound griffe](https://github.com/PrefectHQ/prefect/blob/main/requirements-client.txt#L11), but I think our `setup.py` doesn't account for duplicate requirement specs across `requirements.txt` and `requirements-client.txt`

**Comment by hongbo-miao** [comment]
Our pipelines are crashed with this error as well.

**Comment by cicdw** [comment]
@hongbo-miao pinning `griffe` in your Poetry lock file will resolve the issue

**Comment by hongbo-miao** [comment]
Thanks @cicdw that is our current workaround way.

**Comment by cicdw** [comment]
Closed by #14998

**Comment by andrew-said** [comment]
Is there any update on when v2.20.3 will be made available to fix this issue?

**Comment by cicdw** [comment]
@andrew-said [2.20.3 was just released](https://github.com/PrefectHQ/prefect/releases/tag/2.20.3) minutes ago!

And for future reference we track our releases - both target dates as well as critical issues within each release - via [GitHub Milestones](https://github.com/PrefectHQ/prefect/milestones) so that's always a good place to look for info like this.

**Comment by andrew-said** [comment]
@cicdw Thanks for the update and I'll keep an eye on the milestones in the future. 

I've updated my version to v2.20.3 but I am still seeing the same griffe error. Can you confirm if there are any other errors related to this bug that will need to be resolved on the Prefect side?

> @andrew-said [2.20.3 was just released](https://github.com/PrefectHQ/prefect/releases/tag/2.20.3) minutes ago!
> 
> And for future reference we track our releases - both target dates as well as critical issues within each release - via [GitHub Milestones](https://github.com/PrefectHQ/prefect/milestones) so that's always a good place to look for info like this.

**Comment by cicdw** [comment]
@andrew-said hmmm that sounds suspicious - we don't import from `griffe.dataclasses` at all anymore; are you sure your update was successful?

**Comment by andrew-said** [comment]
@cicdw It may be a caching issue on my end then. Thank you!

**Comment by cicdw** [comment]
Sounds good! If you do find another issue though just let us know!
