### ISSUE TITLE
Running flows from serve fails on windows when python installation path has spaces.

### ISSUE THREAD

**Issue by guy-sch** [PrefectHQ/prefect#15014]
### First Check
- [x]  I added a descriptive title to this issue.
- [ ]  I used the GitHub search to find a similar issue and didn't find it.

I found an old very similar issue [#9769](https://github.com/PrefectHQ/prefect/issues/9769), which was already fixed.
- [x]  I searched the Prefect documentation for this issue.
- [x]  I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary
Running flows from serve always fail with the following error:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Process for flow run '8dff52a4-5210-4276-8f23-1157cb409775' exited with status code: 1
```
_the flow run id of course changes every time._
this error (or any error) is seen only on the console where serve was run, the server UI only show the status as **Crashed**.

My python is installation location is this _C:\Program Files\Python311\python.exe_.
Running flows from worker is working as expected.

### Version info (`prefect version` output)

```Text
Version:             2.20.2
API version:         0.8.4
Python version:      3.11.8
Git commit:          51c3f290
Built:               Wed, Aug 14, 2024 11:27 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

### Additional context
This is the code used to serve the flow.
```python
if __name__ == "__main__":
    fse_full_flow.serve(name="FSE_full_flow", tags=["deployment", "fast_spin_echo", "test"],
                              description="fast spin echo flow")
```

**Comment by desertaxle** [comment]
Hey @guy-sch! I have a potential fix for this in https://github.com/PrefectHQ/prefect/pull/15015. Would you be able to give it a test? I need to get my Windows environment up and running, so I bet you'll be faster at testing it than I will!

**Comment by guy-sch** [comment]
Hey @desertaxle, sorry for my lack of knowledge. But how to test it?
How to download your changes?

**Comment by desertaxle** [comment]
Great question! If you have `git` installed, you can use `pip` to install a package from a `git` repository. 

To install the branch with the fix, you can run:
```bash
pip install git+https://github.com/prefecthq/prefect.git@quote-runner-command
```

Let me know if you have any other questions!

**Comment by guy-sch** [comment]
It is working with the new changes.

**Comment by desertaxle** [comment]
Awesome! Thanks for verifying!

**Comment by cicdw** [comment]
Closing this issue as the fix will go out in the next release!
