### ISSUE TITLE
prefect deploy command for prefect 3 incompatible with prefect 2 server

### ISSUE THREAD

**Issue by tjader** [PrefectHQ/prefect#15049]
### Bug summary

Hi, there is an incompatibility between prefect server 2 (2.20.2 as tested) and the prefect 3 python package, which makes it not possible to create deployments.

I know you state that Prefect cloud will remain compatible with Prefect 2 and 3 going forward, but is a locally deployed prefect-server v2 expected to be compatible with prefect 3?
If that is the case, there is the below issue.

To reproduce, run the command `prefect deploy` and select the 
1. deployment-name: some name
2. schedule: no
3. custom docker image: no
4. pull from remote stgorage: yes
5. git repo
6-9: this was dependent on my setup (a private gitlab repo)

Once above has been selected, an 422 Unprocessable Entity is received from the prefect server as below.

Error message (gitlab url obfuscated)
```
{
  'exception_message': 'Invalid request received.',
  'exception_detail': [
    {
      'loc': [
        'body',
        'concurrency_limit'
      ],
      'msg': 'extra fields not permitted',
      'type': 'value_error.extra'
    }
  ],
  'request_body': {
    'name': 'test-stream',
    'flow_id': 'c5fcd42a-4384-45a5-8554-1b5b857ca7fc',
    'schedules': [],
    'concurrency_limit': None,
    'enforce_parameter_schema': True,
    'parameter_openapi_schema': {
      'title': 'Parameters',
      'type': 'object',
      'properties': {
        'ids': {
          'items': {
            'anyOf': [
              {
                'format': 'binary',
                'type': 'string'
              },
              {
                'type': 'string'
              },
              {
                'type': 'integer'
              }
            ]
          },
          'position': 0,
          'title': 'ids',
          'type': 'array'
        }
      },
      'required': [
        'ids'
      ],
      'definitions': {}
    },
    'parameters': {},
    'tags': [],
    'pull_steps': [
      {
        'prefect.deployments.steps.git_clone': {
          'repository': 'https://gitlab.com/<project>/<repo>.git',
          'branch': 'master',
          'access_token': '{{ prefect.blocks.secret.deployment-test-stream-test-stream-repo-token }}'
        }
      }
    ],
    'work_queue_name': None,
    'work_pool_name': 'k8s-pool',
    'storage_document_id': None,
    'infrastructure_document_id': None,
    'description': 'None',
    'path': None,
    'version': None,
    'entrypoint': 'src/prefect_flows/test_stream.py:test_stream',
    'job_variables': {}
  }
}

```

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc18
API version:         0.8.4
Python version:      3.11.0rc1
Git commit:          99428dea
Built:               Thu, Aug 15, 2024 1:17 PM
OS/Arch:             linux/x86_64
Profile:             microk8s
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-sqlalchemy: 0.5.0rc2
  prefect-kubernetes: 0.5.0rc2
```

### Additional context

prefect-server was installed with the latest helm chart (prefect-server-2024-8-15182057). This one contains prefect 2.20.2. There is no prefect 3 helm chart (but the prefect 3 docs point to these helm charts).

**Comment by tjader** [comment]
An alternative way to reproduce this is to run the example from here: https://docs-3.prefect.io/3.0rc/get-started/quickstart#deploy-and-schedule-your-flow using a local prefect 3 client and a prefect 2.20 server.

**Comment by cicdw** [comment]
Hey @tjader thank you for the issue; we should have made this more clear in our announcements but Prefect 2.0 servers will not be compatible with 3.0 clients - there were a few changes to API mechanics that basically took backwards compatibility off the shelf. 

For the helm chart, we haven't made the 3.0 helm chart yet only because it's still a release candidate, but thanks for the docs callout - we'll make sure those charts and docs are updated in the next week!

**Comment by tjader** [comment]
Thanks. I did find a workaround by changing my own values.yaml file to contain an rc version of the  prefect image
```
  server:
    image:
      prefectTag: 3.0.0rc18-python3.11
```
I'm not sure if this value is documented though...

**Comment by cicdw** [comment]
Yea the tag format follows our schema for all versions but I don't think we have explicitly documented the 3.0 versions with the `rc` suffix. We're rounding out the core work for 3.0 this week and will be turning our attention to going back through all the documentation next week, so will make sure to get these kinks worked out then.

Closing this issue but thank you for the report and feedback!
