### ISSUE TITLE
Users with `Worker` role in v2 Cloud can see Flow Delete button

### ISSUE THREAD

**Issue by bkkkk** [PrefectHQ/prefect#15069]
### Bug summary

We've assigned some users the default _Worker_ role in our workspace. According to the permissions page, the role doesn't have the ability to Delete flows or deployments. One of our users confirmed that they can still see the Delete button in the Flow context menu. This is not the case of the Deployment's Delete button which they cannot see. I assume one or the other is unexpected.

### Version info (`prefect version` output)

```Text
Version:             2.18.3
API version:         0.8.4
Python version:      3.11.4
Git commit:          c449aee8
Built:               Thu, May 2, 2024 5:47 PM
OS/Arch:             darwin/arm64
Profile:             my_profile
Server type:         cloud
```

### Additional context

Taken by the user in question:

<img width="1515" alt="Screenshot 2024-08-26 at 10 21 07" src="https://github.com/user-attachments/assets/96ebc0a1-c455-4bd9-812e-2b107f8ce112">

**Comment by pleek91** [comment]
Thank you for reporting!
