### ISSUE TITLE
documentation - fix embedded tables

### ISSUE THREAD

**Issue by j-carson** [PrefectHQ/prefect#15089]
### Describe the current behavior

When I go to the prefect 3.0 SDK website and look at tables, they have horizontal scrollbars at the bottom. If there are a lot of parameters, sometimes waaaay at the bottom, making for awkward up-down and side-to-side scrolling. 

Even on a wider monitor, expanding the browser window size just makes the margins larger and does not expand the table so that it can be easily read

![image](https://github.com/user-attachments/assets/251a3188-9633-4ded-897a-3c5bebdc1dba)

### Describe the proposed behavior

When the window gets wider, make the table wider, not the margins, until the table has enough room to be easily read

**Comment by discdiver** [comment]
Thank you for raising @j-carson. We plan to move the 3.x SDK docs to another system as soon as that system is ready. Mkdocs is used for the current SDK docs and doesn't allow for easy widening without losing the TOC.
