### ISSUE TITLE
Add an index page to the 3.0 docs to better support editors like Cursor

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#15121]
### Describe the current behavior

Our docs page currently lacks a comprehensive index page, such as [SQLAlchemy's](https://docs.sqlalchemy.org/en/20/genindex.html).

### Describe the proposed behavior

Our docs page has a comprehensive index page that lists every page in the documentation. This could better support AI-based text editor features that can index documentation, such as [Cursor's custom docs feature](https://docs.cursor.com/context/@-symbols/@-docs#manage-custom-docs).

### Example Use

Adding a page such as `https://docs-3.prefect.io/3.0rc/index` to Cursor's custom docs feature would allow the editor to easily scrape every page of our documentation.

### Additional context

This is not only interesting from a text editor perspective. Any RAG workflow that wanted to expose context around how Prefect works could scrape our docs easier with a comprehensive index page.

**Comment by zzstoatzz** [comment]
just for visibility, we discovered you can do this using this [URL](https://docs-3.prefect.io/sitemap.xml)

may be worth writing this in the docs with cursors trajectory

**Comment by discdiver** [comment]
Now you can just use docs.prefect.io and cursor will crawl the site. Closing this issue as we have that, plus a standard sitemap. Happy to reopen if folks think more is needed.
