### ISSUE TITLE
Awaiting an async task does not apply to the task runner

### ISSUE THREAD

**Issue by fyrestone** [PrefectHQ/prefect#15156]
### Bug summary

Awaiting the async task should apply the task runner as `task.submit()`. Here is an example to reproduce this issue:

```python
import asyncio
import os

from prefect import flow, task
from prefect_ray import RayTaskRunner


@task
async def test_task():
    import os
    return os.getpid()


@flow(task_runner=RayTaskRunner(address="auto"))
async def test_flow():
    pid = os.getpid()
    fut = test_task.submit()
    pid_submit = fut.result()
    pid_await = await test_task()
    assert pid != pid_submit
    assert pid != pid_await  # Here await `test_task()` runs the task in current process, it is not correct.


asyncio.run(test_flow())

```

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc20
API version:         0.8.4
Python version:      3.9.6
Git commit:          6dd34dc6
Built:               Thu, Aug 29, 2024 12:06 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.7.4
Integrations:
  prefect-ray:       0.4.0rc2
```

**Comment by cicdw** [comment]
Hi @fyrestone - this is intentional; we require that tasks be _explicitly_ submitted to task runners.  Calling a task directly will always run that task in the local process.

**Comment by fyrestone** [comment]
Then, how to async wait the test_task? `test_task.submit()` returns a future which has no async method on it.

**Comment by cicdw** [comment]
We plan to make futures natively awaitable so that:
```python
# async wait - no currently possible but planned
await fut

# sync wait
fut.wait()
```

**Comment by fyrestone** [comment]
> We plan to make futures natively awaitable so that:
> 
> ```python
> # async wait - no currently possible but planned
> await fut
> 
> # sync wait
> fut.wait()
> ```

I can't block my event loop. So, currently I have no way to submit my task to a task runner and await the result.

**Comment by cicdw** [comment]
Yup I totally understand - that's the motivation for making futures natively awaitable.
