### ISSUE TITLE
Make docstring inheritance more natural

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1519]
## Use Case
Many Prefect users document their tasks using something like Sphinx.  Currently, _every_ Prefect Task either falls back on the main class-level docstring or the docstring of the `__call__` method leading to generic and uninformative documentation of actual custom tasks.

## Solution
The solution is to do some metaprogramming on the base Task class which:
- displays the class docstring when uninitialized
- displays the `run` method docstring when initialized
- has the same behavior with `inspect.getdoc(mytask)` as with `mytask?`

Note that `mytask?` looks at the docstring for the `__call__` method, whereas `inspect.getdoc` simply references the main `__doc__` attribute.

**Comment by lauralorenz** [comment]
Closing; if you are documenting your custom Task subclasses with internal Sphinx documentation and have more info on how this could be better, please comment and/or reopen.
