### ISSUE TITLE
`.from_source` pull step is duplicated

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#15206]
### Bug summary

#13981 introduced LocalStorage to 2.x, allowing one to skip pull step in `.from_source` for process deployments.
This was ported to 3.x in #14186, but instead of preventing pull for LocalStorage it introduced an extra pull step for all storage types.

Compare [this](https://github.com/PrefectHQ/prefect/blob/a4ec319c211113312afc1e62f1457a59277d25c9/src/prefect/flows.py#L984) in 3.x to [this](https://github.com/PrefectHQ/prefect/blob/e8c00c9e6d7ff5bc4445309f4ac1cbff4ffc0c63/src/prefect/flows.py#L926) in 2.x.

Not every storage block can pull to the same folder twice. I stumbled onto this because git is unable to clone into a repo folder ('cause some .git index files are unwritable after pull), so my `.from_source` calls started failing.

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc19
API version:         0.8.4
Python version:      3.10.7
Git commit:          eac7892e
Built:               Thu, Aug 22, 2024 10:02 AM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-aws:       0.5.0rc2
```

**Comment by zzstoatzz** [comment]
thank you for the report @hateyouinfinity - this looks like a bug / transcription error. will get a PR up for this asap
