### ISSUE TITLE
Tests for prefect-ray and prefect-dask are failing

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15226]
### Bug summary

Integration tests in CI for prefect-ray and prefect-dask are failing. 

This PR touched docstrings, but not code:
https://github.com/PrefectHQ/prefect/actions/runs/10708984794/job/29692600730?pr=15224

### Version info (`prefect version` output)

```Text
Prefect 3.0 tests on the main branch.
```

**Comment by zzstoatzz** [comment]
likely related to #14955
