### ISSUE TITLE
UI Release Target

### ISSUE THREAD

**Issue by dskoda1** [PrefectHQ/prefect#1522]
## Use Case

Hello, I was reading through [this medium article](https://medium.com/the-prefect-blog/why-not-airflow-4cfa423299c4) on Prefect vs Airflow, and saw near the bottom that the UI was in progress but not yet released. The article was released on May 1st, is there any update on when the UI would be available to run alongside the already opensource Core?

Thanks!

**Comment by jlowin** [comment]
Hi @dskoda1 - the UI and Cloud platform are currently available to our lighthouse partners and we're working through our waitlist as we gear up for a larger public release. You can write us to apply for early access (hello@prefect.io) or we will be opening the waitlist to the public in the near future!

**Comment by dskoda1** [comment]
Sure, I may do that soon thanks. Just speculating but is the plan to eventually open source the UI? Or would it remain closed source as part of the paid platform.

**Comment by jlowin** [comment]
The initial UI release will be closed source, but will not require payment.

**Comment by elypma** [comment]
Hi there,
I am having a similar question. I'm evaluating luigi against prefect and easy monitoring the workflow status (as in luigi) is an important requirement. Can you give a time frame for this functionality?

Thanks in advance.

**Comment by cicdw** [comment]
Hi @elypma - we have opened up a waitlist for our free Scheduler service which includes our UI, as described in this blog post:  https://medium.com/the-prefect-blog/a-scheduler-for-the-internet-fd706336e2fe

If you sign up, you should receive access in a matter of weeks (and quite possibly sooner than that).
