### ISSUE TITLE
on_completion hook not running when task is cached in Prefect 2.x

### ISSUE THREAD

**Issue by derekahuang** [PrefectHQ/prefect#15223]
### Bug summary

Issue has been repro'd by @zzstoatzz [here](https://prefect-community.slack.com/archives/C04DZJC94DC/p1725475967743759)

Essentially, the `on_completion` hook doesn't run in Prefect 2.x However, this seems to be the default behavior in Prefect 3.0 ([docs](https://docs.prefect.io/3.0/develop/manage-states#execute-code-on-state-changes)) leading us to believe that this is a bug with Prefect 2.x 

### Version info (`prefect version` output)

```Text
2.20.0
```

**Comment by zzstoatzz** [comment]
hi @derekahuang - thank you for making the issue! (copying message from slack for visibility)

> do you have capacity/interest to contribute a PR for this?
in 2.x, we'll need to add a new setting in settings.py like PREFECT_RUN_ON_COMPLETION_HOOKS_ON_CACHED or something and then find the place in engine.py (or code the engine calls) to put the new behavior behind the flag
