### ISSUE TITLE
Permission denied while creating temp folder for Gitlab refs (MacOs)

### ISSUE THREAD

**Issue by fletanoux** [PrefectHQ/prefect#15236]
### Bug summary

Hello,

I'm trying to deploy my flows using the GitlabRepository storage, the from_source, to_deployment and deploy_flow methods. But while doing so i'm getting a permission denied error.  As of right now, i'm not entirely certain if its a bug, or i'm doing this wrong...

Here is the exact error :

> Error setting up deployment : preprod:bi:fact:bridge:conversion: [('/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpmkt1uejhprefect/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.pack', '/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpuybl_7g2/gitlab-repository-gitlab-fix-hasoffer-payout/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.pack', "[Errno 13] Permission denied: '/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpuybl_7g2/gitlab-repository-gitlab-fix-hasoffer-payout/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.pack'"), ('/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpmkt1uejhprefect/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.idx', '/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpuybl_7g2/gitlab-repository-gitlab-fix-hasoffer-payout/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.idx', "[Errno 13] Permission denied: '/var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T/tmpuybl_7g2/gitlab-repository-gitlab-fix-hasoffer-payout/.git/objects/pack/pack-16e4b4bce020e60b850ef3ae35f747f865fade7b.idx'")] 

My understanding is that `var/folders/1v/j8s_6z4d2jzbfpb_mxfwj4bw0000gp/T` is the value of the $TMPDIR env variable, and prefect is trying to create everything else after that, but doesn't have the permission to do so.  Checking for the permission in that folder, it is owned by my user, and the group seems alright as well. The permission themselves are : drwx------. So 700 

I'm on MacOs, and the problem happens to myself, and all my coworkers that also tried, but we're on all macOs. Sadly I haven't been able to try on Windows or Linux to confirm the problem on those. 

Right now we're able to circumvent those problems by using sudo, but it doesn't feel right to have to do this.

For the code leading to that problem here is a simplified version, removing the extra logic that isn't directly related to prefect

```
from prefect import deploy as deploy_flow
from prefect_gitlab import GitLabCredentials, GitLabRepository

 gitlab_credentials_block = GitLabCredentials.load("gitlab-credentials")
 storage = GitLabRepository(
        repository="https://gitlab.easyflirt.com/bi/orion.git",
        reference=ref,
        credentials=gitlab_credentials_block,
        git_depth=1,
)
    
deployments = []
 try:
                deployments.append(
                    flow.from_source(
                        source=storage,
                        entrypoint=entrypoint,
                    ).to_deployment(
                        name=deployment_name
                    )
                )

  except Exception as e:
                print_error(f"Error setting up deployment : {deployment_name}: {e}")
                
 deploy_flow(
            *deployments,
            work_pool_name=env,
            print_next_steps_message=False,
        )
 ```
 
 The error being triggered inside the try.
 
 As always, thanks for reading the issue as well as your awesome job on prefect.
 

### Version info (`prefect version` output)

```Text
prefect --version
3.0.0

I've tried almost every rc release, and the problem has always been happening. Before that it seemed to work in 2.*, but i've modified the way i'm setting up my deployments while switching to prefect 3, so it's not a 1 to 1 equivalence a,d i'm not certain it's a regression or not.
```

**Comment by WWM-jschuba** [comment]
I think this was fixed in [PR 15215](https://github.com/PrefectHQ/prefect/pull/15215)

**Comment by desertaxle** [comment]
Good call @WWM-jschuba! It's quite possible that the error is caused by trying to create the same directory twice.

@fletanoux would you be able to install `prefect` from the main branch and see if the issue persists? You can use this command to install from the main branch:
```
pip install "git+https://github.com/PrefectHQ/prefect.git@main#egg=prefect"
```

**Comment by fletanoux** [comment]
I'm not at work anymore, but I can definitely do this tomorrow. Thanks for the quick answers.

**Comment by fletanoux** [comment]
Hello again,

I can confirm that with the latest version on the git repository the problem is fixed. I'm closing the issue with that comment. Thanks again, you definitely rock, keep up the good work :)
