### ISSUE TITLE
prefect-databricks: missing RuntimeEngine in models.jobs (regression)

### ISSUE THREAD

**Issue by srsapient** [PrefectHQ/prefect#15308]
### Bug summary

This https://github.com/PrefectHQ/prefect-databricks/blob/main/prefect_databricks/models/jobs.py#L815C1-L821C22 is missing in the new releases https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-databricks/prefect_databricks/models/jobs.py

Is this expected?

### Version info (`prefect version` output)

```Text
2.20.4
```

**Comment by zzstoatzz** [comment]
thank you for the issue @srsapient - the PRs linked above will close this for 3.x and 2.x lineages respectively and I will cut a new release of each as soon as possible
