### ISSUE TITLE
Task results are not persisted until flow is completed if generator is used

### ISSUE THREAD

**Issue by DGolubets** [PrefectHQ/prefect#15337]
### Bug summary

When I inspect the storage directory while running this code l see no files until the run completes.

```
from prefect import flow, task

@task
def generate_values():
    for i in range(100):
        yield i


@task
def format_value(i: int) -> str:
    return f"Value: {i}"


@flow(
    persist_result=True
)
def flow1():
    for i in generate_values():
        res1 = format_value(i)
        sleep(1)


if __name__ == "__main__":
    flow1()
```

But if I replace `generate_values()` with `list(generate_values())` it starts saving results task by task properly.  

### Version info (`prefect version` output)

```Text
Version:             3.0.1
API version:         0.8.4
Python version:      3.10.12
Git commit:          c6b2ffe1
Built:               Fri, Sep 6, 2024 10:05 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Pydantic version:    2.9.1
Integrations:
  prefect-kubernetes: 0.5.0
  prefect-aws:       0.5.0
  prefect-dask:      0.3.0
  prefect-ray:       0.4.0
```

**Comment by cicdw** [comment]
Hey @DGolubets - thank you for raising this issue, this is a really interesting one!! This is _technically_ working as intended, and I can offer you a solution.

First, let me explain: 
- Fact 1: every task now opens up a "transaction" in Prefect that governs _when_ that task persists its result.  Task results get persisted whenever their governing transaction _commits_.  
- Fact 2: nested tasks therefore operate with nested transactions; generator tasks don't commit their transactions until they are exhausted
- Fact 3: transactions by default operate in "LAZY" commit mode, meaning nested transactions wait for their parent to commit

So in this situation, the generator task opens a transaction, the `format_value` tasks all open subtransactions, and they _all_ commit simultaneously at the very end after the generator task is exhausted.

To change this, you can change the `commit_mode` of the transactions to `EAGER`:

```python
from time import sleep
from prefect import flow, task
from prefect.transactions import transaction, CommitMode

@task
def generate_values():
    for i in range(5):
        yield i


@task
def format_value(i: int) -> str:
    return f"Value: {i}"


@flow(
    persist_result=True
)
def flow1():
    with transaction(commit_mode=CommitMode.EAGER):
        for i in generate_values():
            res1 = format_value(i)
            sleep(1)


if __name__ == "__main__":
    flow1()
```

This example will now persist results one-by-one as you were originally expecting.

**Comment by DGolubets** [comment]
I understand now, thanks for the detailed answer @cicdw
