### ISSUE TITLE
 prefect server start  root - An error occurred: unhandled errors in a TaskGroup (1 sub-exception) in windows

### ISSUE THREAD

**Issue by Bingrenbit** [PrefectHQ/prefect#15351]
### Bug summary

 prefect server start  root - An error occurred: unhandled errors in a TaskGroup (1 sub-exception) in windows
i meet the question of people can solve the problem? The framework if not support windows?

### Version info (`prefect version` output)

```Text
prefect==3.0.1
python 3.9.0
```

**Comment by Bingrenbit** [comment]
![1726125861792](https://github.com/user-attachments/assets/a3dd7e62-97df-453b-bead-2939681d6ba4)

**Comment by cicdw** [comment]
Hm seems like we need to improve error logging on the server to get more insight into what may be happening here.

**Comment by Bingrenbit** [comment]
> 嗯，看来我们需要改进服务器上的错误日志记录，以便更深入地了解这里可能发生的情况。

Hello, I seem to have found the problem. Incomplete support for all versions of python3.9. I ran fine in python 3.9.6 but got this error in python3.9.0.
