### ISSUE TITLE
Add remote cluster option to Kubernetes Agent

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1539]
## Current behavior
Currently the k8s agent only supports in-cluster (on a pod) and out of cluster (using a cluster set in .kubeconfig)

## Proposed behavior
Have a configuration option for the k8s agent to specify a remote cluster.

## Example
Having the ability to specify a remote cluster w/ the IP and API key would allow the k8s agent to run anywhere without direct access to the cluster's API server.

**Comment by cicdw** [comment]
Not sure when this was resolved but it's definitely a supported pattern now
