### ISSUE TITLE
Defined but unused parameter raises exception

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#1541]
On `prefect==0.6.5`, the following flow succeeds if you uncomment the second task but fails as written:
```
from prefect import Flow, task
from prefect.core.task import Parameter


@task
def double(x):
    return 2 * x

with Flow('param_test') as flow:
    i = Parameter('i')
    j = Parameter('j')
    double(i)
    # double(j)

flow.run(parameters={'i': 1, 'j': 2})
```
Result:
```
~/venvs/model/lib/python3.7/site-packages/prefect/core/flow.py in run(self, parameters, run_on_schedule, runner_cls, **kwargs)
    984             raise ValueError(
    985                 "Flow.run received the following unexpected parameters: {}".format(
--> 986                     fmt_params
    987                 )
    988             )

ValueError: Flow.run received the following unexpected parameters: j
```
Seems like the flow runner shouldn't care about which parameters are actually used downstream as long as they're all properly defined?

**Comment by cicdw** [comment]
Hi @bnaul - instantiating a Parameter won't actually add it to the flow; you need to either:
- call the parameter to register it (e.g., `j = Parameter('j')()`)
- use it in a downstream task (like your second `double` call)
- use an imperative method like `flow.add_task(j)`

There's a blurb at the end of [this section](https://docs.prefect.io/core/tutorials/task-guide.html#adding-tasks-to-flows) that might provide some additional clarity.

If you do any one of those things, your `flow.run` command will begin working again (regardless of whether `j` has any downstream dependencies).

**Comment by bnaul** [comment]
Makes sense; still kind of counterintuitive to me but I can see why it works the way it does. Thanks for the response.
