### ISSUE TITLE
UI: Flow run graph rendering not showing or expanding infinitely

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#15449]
### Bug summary

On prefect cloud, flow runs either show no flow run graph at all or the graph canvas expands infinitely as the user scrolls down, making it impossible to retrieve any information from the flow run page.

### Version info (`prefect version` output)

```Text
prefect cloud
```

### Additional context

tested with chrome on multiple machines, showing the same issue.

**Comment by zhen0** [comment]
Thank you for bringing this to our attention @j-tr!  We are looking into it.

**Comment by pleek91** [comment]
@j-tr thanks for reporting this. The graph should be working properly again.
