### ISSUE TITLE
`cache_expiration` doesn't expire the cache

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15470]
### Bug summary

In the example below, the cache should expire in one minute and then the task should rerun at 1 minute, 40 seconds. Instead the task goes directly to `Finished in state Cached(type=COMPLETED)`. 

I tested this with very short amounts of time, too. Same result.

```python
from datetime import timedelta
from time import sleep
from prefect import flow, task
from prefect.cache_policies import INPUTS


@task(cache_policy=INPUTS, cache_expiration=timedelta(minutes=1))
def hello_task(name_input: str):
    print(f"Hello {name_input}")


@flow(log_prints=True)
def hello_flow(name_input: str):
    hello_task(name_input)


if __name__ == "__main__":
    hello_flow(name_input="world")
    sleep(100)
    hello_flow(name_input="world")
```

### Version info (`prefect version` output)

```Text
Version:             3.0.3
API version:         0.8.4
Python version:      3.12.2
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             darwin/arm64
Profile:             sandbox-jeff
Server type:         cloud
Pydantic version:    2.8.2
```
```


### Additional context

_No response_

**Comment by discdiver** [comment]
Appears the cache expiration intermittently behaves as expected.

**Comment by cicdw** [comment]
Hmmmmm that's really surprising, thanks for raising. I can't seem to identify any place where there might be a race condition except if it's somehow a race condition happening in-memory.

Could you try running these two flows in two separate processes and see if the bug continues in that scenario?

**Comment by discdiver** [comment]
Running it with `ThreadPoolTaskRunner` works as expected. 

I then tried it out some more.

It's now working as expected in the same thread. Maybe an update was made to Cloud? 

I'm going to close as I'm not observing this, and will reopen if I can reproduce.

**Comment by cicdw** [comment]
Nah this feature is client-side only / doesn't involve the API so it can't depend on Cloud
