### ISSUE TITLE
When using `prefect deploy` to build a Docker image as part of a deployment, don't prompt for pulling for flow code from remote storage

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15507]
### Bug summary

`using `prefect deploy` - if the user selects to build a Docker image as part of a deployment and then not to push it, don't prompt for pulling for flow code from remote storage

`? Your Prefect workers will need access to this flow's code in order to run it. Would you like 
your workers to pull your flow code from a remote storage location when running this flow? [y/n] 
(y):`

### Version info (`prefect version` output)

```Text
Version:             3.0.3
API version:         0.8.4
Python version:      3.12.2
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             darwin/arm64
Profile:             sandbox-jeff
Server type:         cloud
Pydantic version:    2.8.2
```
```


### Additional context

_No response_

**Comment by zzstoatzz** [comment]
@discdiver does building a docker image necessarily mean that you don't want remote storage for flow code?

for example, its totally valid to have a `build` step that makes an image with deps from your project, but not your flow code. then you could keep that image around locally (not pushing it), but keep your code in github. then you'd have a docker build step, but also need remote storage for code

**Comment by discdiver** [comment]
Gotcha. Thanks for the scenario. Closing.
