### ISSUE TITLE
Stable Version

### ISSUE THREAD

**Issue by kingZthefirst-cypher** [PrefectHQ/prefect#1550]
When are you releasing the stable version of prefect?

**Comment by cicdw** [comment]
Hi @kingZthefirst-cypher - if you're asking about our 1.0 release, I think that depends on too many factors to provide an answer to.  Scipy took 16 years to get there ;) We’re aiming for considerably less time.

**Comment by kingZthefirst-cypher** [comment]
Thanks for the quick reply, Chris. I really like your framework, the way to
create computation graph and just run it, makes a lot of sense. Keep up the
good work.

Regards,

**Comment by cicdw** [comment]
Thanks @kingZthefirst-cypher!
