### ISSUE TITLE
Need to Gracefully Complete All Concurrent Tasks Upon First Task Completion in Prefect 3.x Flow

### ISSUE THREAD

**Issue by Yesurajup** [PrefectHQ/prefect#15536]
### Bug summary

```python
import asyncio
from prefect import flow, task
from prefect.task_runners import ConcurrentTaskRunner
from prefect.exceptions import CancelledRun

@task
async def end_event():
    #here i need to write a code to make all running or ongoing subflows or subtasks or tasks into complete success status and we need to return the success of tasks or  subflows or subtasks.

@flow
async def subflow_1():
    await asyncio.sleep(60)  # Simulate work
    await end_event()
    print("Subflow 1 completed")
    return "Result from subflow 1"

@flow
async def subflow_2():
    await asyncio.sleep(120)  # Simulate work
    await end_event()
    print("Subflow 2 completed")
    return "Result from subflow 2"

@flow
async def subflow_3():
    await asyncio.sleep(180)  # Simulate work
    await end_event()
    print("Subflow 3 completed")
    return "Result from subflow 3"

@task
async def task1():
    return await subflow_1() 
     # Run the subflow and return the result

@task
async def task2():
    return await subflow_2()

@task
async def task3():
    return await subflow_3()
    
@flow(task_runner=ConcurrentTaskRunner())
async def main_flow():
    # Submit tasks without awaiting them individually to ensure parallel execution
    task_1 = await task1.submit()
    task_2 = await task2.submit()
    task_3 = await task3.submit()
    
if __name__ == "__main__":
    asyncio.run(main_flow())
```

In my Prefect 3.x flow, I have multiple subflows running concurrently, and I need to ensure that when the first subflow calls an end_event task, all other ongoing subflows or tasks are immediately marked as "completed" with a success status, even if they haven't finished their full execution.

Specifically, once one of the subflows finishes and triggers end_event, I want all other concurrently running subflows to halt their execution gracefully, mark them as successfully completed, and return a success status.

One of these subflows is recursive, so I need to account for that behavior as well.

### Version info (`prefect version` output)

```Text
.
```

**Comment by desertaxle** [comment]
Hey @Yesurajup! I'm going to close this issue since we're already discussing this in https://github.com/PrefectHQ/prefect/discussions/15500. Feel free to post questions in that discussion or a new one and we work together there.
