### ISSUE TITLE
Allow recent versions of Pydantic in v2 branch

### ISSUE THREAD

**Issue by williamjamir** [PrefectHQ/prefect#15586]
### Describe the current behavior

Currently, there is an upper bound version to pydantic < 2.9.0 on requirements-client.txt
https://github.com/PrefectHQ/prefect/blob/2.x/requirements-client.txt#L24

### Describe the proposed behavior

Can we change it to < 3.0.0 ? 

The PR that downgraded this requirement seems unrelated to the pydantic version:
https://github.com/PrefectHQ/prefect/commit/d67e9ffa9e67cf231ce803f101a9e4c46b3227c8#diff-687ab6611127b5455724a2a1c3d8faf0128af1a57cd14427007584c4028cfa4dR24

**Comment by zzstoatzz** [comment]
thanks for the issue @williamjamir ! we had pinned that temporarily because of [this](https://github.com/pydantic/pydantic/pull/10029) change in 2.9.0, but the PR linked above should make that unnecessary.
