### ISSUE TITLE
Error while executing 'Access data within transactions' exemple code

### ISSUE THREAD

**Issue by VinhTan** [PrefectHQ/prefect#15593]
### Bug summary

I'm trying to execute the exact code snippet shown on this page https://docs.prefect.io/3.0/develop/transactions#access-data-within-transactions and got these errors (cf. attached file)
[greedy-auk.csv](https://github.com/user-attachments/files/17278707/greedy-auk.csv)

### Version info (`prefect version` output)

```Text
Version:             3.0.4
API version:         0.8.4
Python version:      3.10.12
Git commit:          c068d7e2
Built:               Tue, Oct 1, 2024 11:54 AM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
```

**Comment by discdiver** [comment]
Thank you. I can confirm that the file sticks around when it should be deleted. 
I'm running 3.0.4 with Prefect Cloud.

@desertaxle, your PR #15342 got this working I believe, not sure of the cause of the reversion.
