### ISSUE TITLE
prefect-client has unknown prefect.__version__

### ISSUE THREAD

**Issue by ikseek** [PrefectHQ/prefect#15620]
### Bug summary

Attempt to run deployed flow via prefect-client==3.0.5 produces this error:
`RuntimeError: Found incompatible versions: client: 0+unknown, server: 3.0.5. Major versions must match.`

```
python -m pip install prefect-client==3.0.5
python -c 'import prefect; print(prefect.__version__)'
```
outputs `0+unknown` which might be the problem.

### Version info (`prefect version` output)

```Text
There is no `prefect` cli in `prefect-client`
3.0.5 / 0+unknown
```

**Comment by desertaxle** [comment]
Thanks for the bug report, @ikseek! It looks like a version check was introduced in 3.0.1 via [#15252](https://github.com/PrefectHQ/prefect/pull/15252), which is where this error is coming from. The missing version on `prefect-client` looks like a long-standing issue that wasn't discovered until now. I will investigate and implement a fix!
