### ISSUE TITLE
Remove `max-active-runs` and `catchup`

### ISSUE THREAD

**Issue by aaazzam** [PrefectHQ/prefect#15661]
### Bug summary

The deployment keywords `max_active_runs: int` and `catchup: bool` were part of an old API design for deployment concurrency that was never implemented. We have since opted for a different design, but these kwargs still exist throughout the codebase. This is causing several issues:

- Polluting the API surface
- Creating confusion in the documentation
- Potentially misleading developers about available functionality

### Version info (`prefect version` output)

```Text
Version:             3.0.9.dev1
API version:         0.8.4
Python version:      3.12.4
Git commit:          e8cd03b3
Built:               Thu, Oct 10, 2024 4:35 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
Pydantic version:    2.8.2
```

**Comment by AnVuTrong** [comment]
Noooo, I really need the catchup function
