### ISSUE TITLE
Pre-commit fails in CI with incorrect version number

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15664]
### Bug summary

Fails with: 
`packaging.version.InvalidVersion: Invalid version: '3.0.9.dev1.post0.dev2'`

For example see this recent PR: 
https://github.com/PrefectHQ/prefect/actions/runs/11296383924/job/31421135620?pr=15662

### Version info (`prefect version` output)

```Text
n/a
```

### Additional context

Markdown tests fail, too.

**Comment by desertaxle** [comment]
This has been fixed via https://github.com/PrefectHQ/prefect/pull/15672
