### ISSUE TITLE
Add `Pip Packages` field to all Docker-based work pools

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15705]
### Describe the current behavior

Prefect Managed work pools have an option to directly add Pip Packages without wrapping them in an environment variable. This is a nice convenience.

### Describe the proposed behavior

Add the same field to other Docker-based work pools

### Example Use

This would make it easier for users to add required package dependencies. It would also make it easier to provide guidance to users in the docs.

**Comment by zzstoatzz** [comment]
hi @discdiver - I think we don't necessarily want to encourage this by promoting `EXTRA_PIP_PACKAGES` to a field on work pools

by _this_, I mean installing deps at runtime which are often not bounded. We should encourage static dependencies in custom docker images for more predictable behavior

for this reason, my vote would be to not accept this enhancement proposal

**Comment by discdiver** [comment]
Thanks @zzstoatzz. Makes sense to "encourage static dependencies in custom docker images for more predictable behavior".

I will close this issue and make a to do for the docs to make that recommendation in a few places where it makes sense.
