### ISSUE TITLE
Parent flow completes despite subflow still running

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#15716]
### Bug summary

Not sure if this is as designed, but I found it to be counter to my expectations. Suppose you have a `parent` flow and a `child` flow. If we submit the `child` flow to a task runner, the `parent` flow enters a `Completed` state even if the `child` flow is still `Running`. I wouldn't expect that the `child` flow could continue executing if the `parent` flow finished.

```python
import time
from prefect import flow, task

@task
@flow
def child():
    time.sleep(10)

@flow
def parent():
    child.submit()

if __name__ == "__main__":
    parent()
```

```
11:10:26.751 | INFO    | prefect.engine - Created flow run 'axiomatic-kingfisher' for flow 'parent'
11:10:26.754 | INFO    | prefect.engine - View at https://app.prefect.cloud/account/ACCOUNT/workspace/WORKSPACE/runs/flow-run/4b9f1f67-a439-41fe-b93f-31af012dd7a0
11:10:26.989 | WARNING | Flow run 'axiomatic-kingfisher' - A future was garbage collected before it resolved. Please call `.wait()` or `.result()` on futures to ensure they resolve.
See https://docs.prefect.io/latest/develop/task-runners for more details.
11:10:27.428 | INFO    | Task run 'child-a19' - Created subflow run 'thoughtful-koala' for flow 'child'
11:10:27.432 | INFO    | prefect.engine - View at https://app.prefect.cloud/account/ACCOUNT/workspace/WORKSPACE/runs/flow-run/4f55aec9-d105-4484-a5f5-ed8376cdd9c8
11:10:37.814 | INFO    | Flow run 'thoughtful-koala' - Finished in state Completed()
11:10:37.827 | INFO    | Task run 'child-a19' - Finished in state Completed()
11:10:37.834 | INFO    | Flow run 'axiomatic-kingfisher' - Finished in state Completed()
```

### Version info (`prefect version` output)

```Text
Version:             3.0.10
API version:         0.8.4
Python version:      3.12.7
Git commit:          3aa2d893
Built:               Tue, Oct 15, 2024 1:31 PM
OS/Arch:             darwin/arm64
Profile:             sandbox
Server type:         cloud
Pydantic version:    2.9.2
```

**Comment by desertaxle** [comment]
Thanks for opening an issue @EmilRex! When submitting a task to the runner, like in this example, you need to wait for the completion of the returned future if you want the submitted task to complete before the parent flow run completes.

Here's an updated version:
```python
import time
from prefect import flow, task

@task
@flow
def child():
    time.sleep(10)

@flow
def parent():
    future = child.submit()
    future.wait()

if __name__ == "__main__":
    parent()
```

Can you elaborate on the use case for decorating a function with `@flow` and `@task` and then submitting it? That's a usage I haven't seen before.

**Comment by EmilRex** [comment]
If anything it's just a bit of a gotcha... the user should add the `wait`, but will only know to do so if they're paying particular attention to their logs. Despite the warning, the flow works and runs to completion.

**Comment by desertaxle** [comment]
I think the important thing to understand is that flows don't keep track of the state of any of their child tasks or flows. They follow the same rules that vanilla Python functions follow. If you are submitting execution to a thread (which `.submit()` is doing here) it will not block the parent function from returning.

In general, I wouldn't recommend wrapping flows in tasks solely to execute flows in a non-blocking manner. I think it obfuscates where execution is happening and adds unnecessary task runs to the flow run graph in the UI.

Instead, I recommend using a `ThreadPoolExecutor` from the Python standard library like so:
```python
from prefect import flow

from concurrent.futures import ThreadPoolExecutor

from 
@flow
def run_dbt(config):
    """Subflow for running a dbt project"""
    initialize_config_task()
    install_deps_task()
    run_command_task()
    ...


@flow
def main(configs: list):
    with ThreadPoolExecutor() as pool:
        pool.map(run_dbt, configs)
```

**Comment by EmilRex** [comment]
> I recommend using a ThreadPoolExecutor from the Python standard library

🤯 I had no idea you could do that... so this is essentially what users should do to run flows concurrently? Is it safe to use `ProcessPoolExecutor` as well?

**Comment by desertaxle** [comment]
There's a caveat with that example where the subflow runs won't be linked to the parent flow run, which might prevent using that pattern. I think it'd be poosbile to extend `ThreadPoolExecutor` to propagate the necessary context to correctly link execution for display in the UI.

Unfortunately, a `ProcessPoolExecutor` won't work with flows due to pickling errors like this: `_pickle.PicklingError: Can't pickle <function run_dbt at 0x102e84c20>: it's not the same object as __main__.run_dbt`, but I think it'd also be possible to extend `ProcessPoolExecutor` to create a version compatible with flows.

**Comment by EmilRex** [comment]
Gotcha, that all makes sense. This creates a parent/child flow:
```py
@flow
def child():
    time.sleep(10)

@flow
def parent():
    child()
```

While this does not:
```py
from concurrent.futures import ThreadPoolExecutor
...

@flow
def child():
    time.sleep(10)

@flow
def parent():
    with ThreadPoolExecutor() as pool:
        pool.submit(child)
```

**Comment by EmilRex** [comment]
In this particular instance Prefect seems to behave as designed.

**Comment by simenvikane** [comment]
For managing database connections in a synchronous setting, how does the ThreadPoolExecutor approach compare to using the `concurrency` context manager (ref. the [Prefect docs](https://docs.prefect.io/3.0/develop/global-concurrency-limits#manage-database-connections))? 

Consider the example below where the goal is to have at most one Run of `trigger_dbt_cli_command_flow()` interact with a given database at the same time. A global concurrency limit of 1 is set on each database (for example prod).

```python
from prefect import flow, task
from prefect.concurrency.sync import concurrency
from prefect_dbt.cli.commands import trigger_dbt_cli_command

def run_dbt_deps_task():
    trigger_dbt_cli_command(command="dbt deps")

@task
def trigger_dbt_cli_command_task(database, dbt_command):
    with concurrency(f"{database}", occupy=1):
        result = trigger_dbt_cli_command(command=dbt_command)

@flow(log_prints=True, description="Run dbt CLI command.")
def trigger_dbt_cli_command_flow(database, dbt_command):

    init_env_and_connections()

    run_dbt_deps_task()

    # Run dbt build
    trigger_dbt_cli_command_task(database="prod", dbt_command="dbt build")
```

**Comment by desertaxle** [comment]
@simenvikane using a `ThreadPoolExecutor` will allow you to control the amount of in-flight work via the `max_workers` argument. This is similar to the `concurrency` context manager in the context of a single flow, but the `concurrency` context manager will work across other processes and instances. If your goal is to limit access to a database to one flow at a time, I think using the `concurrency` context manager with a global concurrency limit is the way to go.
