### ISSUE TITLE
Add mention of Windows Subsystem for Linux to Windows install documentation

### ISSUE THREAD

**Issue by sirredbeard** [PrefectHQ/prefect#15769]
### Describe the current behavior

The current installation documentation includes a [Windows installation section](https://docs.prefect.io/3.0/get-started/install#windows-installation) that references PowerShell, CMD, and conda.

I think it would also be useful to mention that users can leverage Prefect on Windows using Windows Subsystem for Linux (WSL).

However, simply listing Windows Subsystem for Linux alongside PowerShell, CMD, and conda as the documentation is currently written wouldn't flow well with the subsequent section about ensuring the `Scripts` path is in the PATH envar, because that section is irrelevant to WSL.

![image](https://github.com/user-attachments/assets/f439ecca-b66c-42a4-81d0-0c56d377a34a)

Before I propose a PR, I wanted to open some discussion with the Prefect team on;

1. Would Prefect welcome mentioning WSL in this section?
2. Would Prefect be open to tweaking this section of the documentation to allow the inclusion of WSL to flow naturally?

### Describe the proposed behavior

I propose that WSL be included because while Prefect is supported on Windows (which is amazing, thank you for doing that work in Prefect 2.0), a fair number of other Python libraries users may leverage are not, which makes WSL useful.

I additionally propose a tweaked Windows installation section to cover installing Prefect on both Windows native and on Windows Subsystem for Linux.

Before I propose an actual PR, I want to make sure this would be welcome by the maintainers. Thank you.

**Comment by discdiver** [comment]
Thank you @sirredbeard! That contribution would be welcome.
