### ISSUE TITLE
Logs no longer automatically refresh in the UI

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [PrefectHQ/prefect#15779]
### Bug summary

When viewing the logs of an ongoing flow run, I have to continuously refresh the page to see updated logging. This is a regression with the new UI.

### Version info (`prefect version` output)

```Text
Cloud UI, no version applicable
```

**Comment by pleek91** [comment]
@jeremy-thomas-roc logs can show up in a few different places in the new ui. Are your logs not streaming in on the main list of flow activity or maybe in the side panel for the run?

**Comment by jeremy-thomas-roc** [comment]
I'll be honest, I don't know that I fully understand your question, this new UI is incredibly overwhelming and confusing. I'd like to be able to switch back to the old one, but I don't appear to have that option.

When I click into a flow run, there is logging shown. It does not update automatically as it used to.

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/a429eb28-1fc6-46fb-830a-206f12fd5f57">

The `+3634` continues to increment, and when I refresh, the logs appear there as expected, but then that counter just resets and begins to increment again. That is with whatever defaults are set in the new UI, I reset them all to be sure.

**Comment by jeremy-thomas-roc** [comment]
@pleek91 @aaazzam 

Ok, this is seemingly working all of a sudden. I'm not sure what happened overnight, but my logs are updating automatically. 

I renew my opinion that I should be able to revert UI and opt-in to this newer version for the time being. The only improvement I feel like I need from this new UI is the ability to filter loggers and remove all the `httpx` logs generated.

**Comment by pleek91** [comment]
@jeremy-thomas-roc glad the logs are updating for you! As we're releasing this feature we're guiding more users into using it to get feedback just like this! So thank you for creating an issue.

**Comment by znicholasbrown** [comment]
@jeremy-thomas-roc thanks for the feedback! It looks like you've opted into the beta; if you navigate to: https://app.prefect.cloud/my/previews you should be able to turn this off. If that's already off you may need to clear your cache and refresh the page, at which point you should see a banner to opt out

**Comment by jeremy-thomas-roc** [comment]
@znicholasbrown I have the feature turned off, and a cleared cache and refreshed, no change.

**Comment by znicholasbrown** [comment]
Hm ok it's possible your browser isn't quite clearing local storage correctly; if you open your browser's developer tools (option + shift + i on chrome/mac, might be slightly different for other browsers/operating systems) and type `sessionStorage.clear()` and refresh? here's a small demo of what I mean:

https://github.com/user-attachments/assets/79f64eb6-d760-4ab7-af5c-f3f4b68bd9ed


That should cause the banner to show up again after a refresh.

**Comment by jeremy-thomas-roc** [comment]
Clearing sessionStorage fixed it, thank you!
