### ISSUE TITLE
pydantic_core._pydantic_core.SchemaError: Invalid Schema

### ISSUE THREAD

**Issue by Pixel-Minions** [PrefectHQ/prefect#15777]
### Bug summary

Raises an exception when running this command:

```
from prefect import flow, task;from prefect.tasks import task_input_hash;from prefect.orion.schemas.schedules import IntervalSchedule
```

### Version info (`prefect version` output)

```Text
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.config.ser_json_timedelta
  Input should be 'iso8601', 'seconds_float' or 'milliseconds_float' [type=literal_error, input_value='float', input_type=str]```
```

### Additional context

Using prefect: 3.0.10 and Pydantic 2.9.2

**Comment by zzstoatzz** [comment]
hi @Pixel-Minions - the `orion` module does not exist in prefect 3, all references to "orion" have been replaced with "server"

can you confirm the version of prefect you're using with `pip list | grep prefect`?

**Comment by Pixel-Minions** [comment]
@zzstoatzz Confirmed it is the 3.0.10, the import was from a test unit that loads Prefect, I have updated it to use

```from prefect import flow, task;from prefect.tasks import task_input_hash;from prefect.client.schemas.schedules import IntervalSchedule``` But still getting the same error, This import is found in your docs.

https://docs.prefect.io/3.0/automate/add-schedules

**Comment by zzstoatzz** [comment]
hi @Pixel-Minions - can you share the output of `prefect version`, which includes more information than just your prefect version that may be helpful

I cannot reproduce this in a fresh environment on 3.0.10
```python
» docker run -it --rm prefecthq/prefect:3.0.10-python3.12 -- python

>>> from prefect import flow, task;from prefect.tasks import task_input_hash;from prefect.client.schemas.schedules import IntervalSchedule
>>> locals()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 'flow': <function flow at 0xffff888ba8e0>, 'task': <function task at 0xffff888f1440>, 'task_input_hash': <function task_input_hash at 0xffff888d9a80>, 'IntervalSchedule': <class 'prefect.client.schemas.schedules.IntervalSchedule'>}
```

**Comment by Pixel-Minions** [comment]
![image](https://github.com/user-attachments/assets/7e5198b3-d445-46e3-acda-25ccfa90eec4)

This is the whole traceback.

**Comment by zzstoatzz** [comment]
hi @Pixel-Minions - sorry to repeat myself, but 

can you share the output of `prefect version`? this includes more information than just your prefect version that may be helpful

**Comment by Pixel-Minions** [comment]
I see what you meant, but it is odd, that it cant find pydantic... It is in the Python path as you can see in the image.

![image](https://github.com/user-attachments/assets/920dfce4-cc31-4550-863c-54c241b229e9)

**Comment by Pixel-Minions** [comment]
I wonder if the issue is then related to the way Prefect looks for the libraries, not in the path or python path but relative or something.

**Comment by zzstoatzz** [comment]
I suspect there might be some form of corruption in your virtual environment - can you try recreating it?

and just to clarify, there is a CLI command `prefect version` (not `prefect --version`) which you should be able to run if you have a valid installation of prefect

**Comment by Pixel-Minions** [comment]
Let me try, I wonder if it might be related to the version of Pydantic, using 2.9.2 might be a breaking change.

Thank you

**Comment by Pixel-Minions** [comment]
@zzstoatzz I found the issue, a mismatch between the pydantic-core and pydantic 2.9.2 that required a specific version of the core one.

Thank you for you help and apologies for the inconvenience

Best,
