### ISSUE TITLE
Use __qualname__ for auto-naming in @task

### ISSUE THREAD

**Issue by hottwaj** [PrefectHQ/prefect#15796]
### Describe the current behavior

Hi there, current behaviour of the `@task` decorator on methods/classmethods etc is to use the method name (`__name__` attribute of the function) so MyClass.foo is given the task name "foo"

### Describe the proposed behavior

My proposal is to replace this behaviour with using fn.__qualname__ so that the task name becomes "MyClass.foo"

### Example Use

This will help to better differentiate similarly named tasks in different classes.  Thanks!

**Comment by zzstoatzz** [comment]
hi @hottwaj - just to clarify, are you asking about the name of the task itself or the name of the run?

```python
from typing import cast

from prefect import task
from prefect.context import TaskRunContext, get_run_context


class MyClass:
    def __init__(self, a: int):
        self.a = a

    @task
    def foo(self):
        ctx: TaskRunContext = cast(TaskRunContext, get_run_context())
        assert ctx is not None and ctx.task is not None and ctx.task_run is not None
        assert ctx.task_run.name == "foo", ctx.task_run.name
        assert ctx.task.name == "foo", ctx.task.name
        return self.a


if __name__ == "__main__":
    MyClass(1).foo()
```

**Comment by hottwaj** [comment]
Hi thanks for the example, I didn't realise you could access self in the way shown in your example - I saw other args accessed this way and that made sense, but I realise now self is not special in any way and is just another arg

This will definitely cover what I was after, thanks a lot for coming back so quickly!
