### ISSUE TITLE
run_shell_process should support passing the current working directory or environment

### ISSUE THREAD

**Issue by Jared314** [PrefectHQ/prefect#15816]
### Describe the current behavior

The `run_shell_process` flow currently assumes it is running from within the current working directory and with the default environment variables. When the `run_shell_process` flow is either run outside the target working directory, or as a child flow, those values cannot be passed as arguments.

### Describe the proposed behavior

The `run_shell_process` flow should accept additional optional arguments for `cwd` and `env` that are passed to the subprocess.Popen call.

```python
@flow
def run_shell_process(
    command: str,
    log_output: bool = True,
    stream_stdout: bool = False,
    log_stderr: bool = False,
    cwd: str = None,
    env: Dict[str, str] = None,
):
```

### Example Use

```python
run_shell_process(
    command="touch test.txt",
    cwd="/tmp/test",
    env=os.environ.copy(),
    stream_stdout=True,
    return_state=True,
)
```

### Additional context

`run_shell_process` is being run as a child flow within a Prefect (v3) flow.

**Comment by zzstoatzz** [comment]
hi @Jared314 - thanks for the issue! the PR linked above should allow this - let me know if you have any concerns!
