### ISSUE TITLE
Have Tasks and/or Flows specify the secrets they require at init

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1587]
## Current behavior
Currently, the Prefect Secrets API is very explicit:
```python
@task
def my_task():
    api_secret = Secret("api_secret").get()
```
this means that, for example, if I map this task over some large collection of items, I'm going to pull this Secret value for every mapped instance.  This is clearly redundant.  

## Proposed behavior
Instead, we could:
```python
@task(secrets=["api_secret"])
def my_task():
    api_secret = prefect.context['secrets']['api_secret']
```
which would trigger the TaskRunner to auto-populate context with the secret values.  We could also specify this instead at the Flow level, but my bias is to keep this is as "local" as possible (open to push-back here of course).  A third option would be to specify it on the task, but have the FlowRunner call the Secrets API (instead of the TaskRunner).  This way, if the same secret is specified across multiple tasks, the FlowRunner can track that and not make redundant calls.  We'd want to think about how to raise the error if a Secret doesn't exist (this implementation would result in a "global" Flow failure instead of a local task failure).

Either way, this new pattern would allow us to pull the secret _one time_ (prior to mapping or prior to task runner execution) and provide it within context to every mapped child.

Note that open-source users would see absolutely 0 difference, as `Secret('key').get()` is a wrapper to `prefect.context['secrets']['key']` anyway.

**cc:** @TylerWanner @zdhughes @joshmeek

**Comment by joshmeek** [comment]
I am all for this! I think the best medium between the options is specifying it at the task level and then having the TaskRunner auto-populate context. One thing is we would need to do is make sure to add documentation on _why_ this is more efficient to do for mapped tasks and in which situations you would do this over calling `Secret.get()`.

**Comment by cicdw** [comment]
@joshmeek excellent idea! We could just make sure to document that using the initialization kwarg will "prime" context.  So ultimately this is very specifically a feature enhancement for using secrets within mapped flows.
