### ISSUE TITLE
Flow run header extends horizontally with many tags 

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#15889]
### Bug summary

when using lots of tags, the flow run header extends to the right, pushing important information out of the window and messing with the page layout

see example flow run with lots of tags
![image](https://github.com/user-attachments/assets/234f72f4-8168-427e-8bec-ad8d81a16866)

### Version info

```Text
prefect cloud
```

**Comment by znicholasbrown** [comment]
Thanks @j-tr - we're looking into this
