### ISSUE TITLE
Add a test against a minimum sqlite version

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15903]
### Describe the current behavior

Our test Matrix doesn't cover older sqlite versions. Users might have an older sqlite version and have the test harness or Prefect server functionality fail due to an old sqlite version.

### Describe the proposed behavior

Add a test that specifies the oldest sqlite version we want to test against to the nightly release or CI/CD workflow.

We could then provide helpful information if the version is incompatible. We could also then document this minimum version.

### Additional context

cc: @j-carson

**Comment by j-carson** [comment]
If sqlite version are the reason for the issues I've seen, I'd like to have a docs update with clear instructions on how to update your sqlite version (it appears to be tricky if you're not rebuilding your own python)

**Comment by j-carson** [comment]
Here's the problem - I'm using python3.10 from a pretty standard source (deadsnakes) and `prefect_test_harness` does not work with that version. If I'm going to go through the hoops to build my own python (still considering my options, but dependencies provided by another team in the company are on python 3.10), I'd like to know which version of sqlite I need to use.

**Comment by cicdw** [comment]
There's some context missing from this issue so I'm not really sure what we are discussing exactly - what issue are you seeing and why do you think it's related to SQLite versions?

**Comment by cicdw** [comment]
Fixed in #15917
