### ISSUE TITLE
Fully functional “Cloud Flow” example

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#1594]
## Proposed behavior
*Please describe your proposed change to the current behavior*
* Welcome flow example
* More complex example with retries

## Example
*Please give an example of how the enhancement would be useful*
This would be useful for users new to Prefect Cloud. These would be some good flows to deploy to their Team for testing.

**Comment by cicdw** [comment]
I think we could even take this to the level of a Tutorial which walks a user through deploying a small sqlite3 database in kubernetes, and then a corresponding "real" ETL workflow.

**Comment by dylanbhughes** [comment]
Tutorial meaning it's in Cloud UI? Or documentation with more detailed instructions?

**Comment by cicdw** [comment]
https://docs.prefect.io/core/tutorials/ vs. https://docs.prefect.io/core/examples/

Examples are just code with minimal comments, tutorials are fleshed out content with explanation.
