### ISSUE TITLE
Configure algolia to show more context in the search preview

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1595]
Currently Algolia shows the headers in the search bar, which are oftentimes duplicated across our documentation. 
<img width="1395" alt="Screen Shot 2020-04-06 at 1 30 57 PM" src="https://user-images.githubusercontent.com/5643703/78587412-e5e1ad80-780a-11ea-859c-225ebbec7408.png">
For this issue we should configure algolia to show more context in the search preview so it is easier to use the search bar.

**Comment by lauralorenz** [comment]
FYI the algolia config is at https://github.com/algolia/docsearch-configs/blob/3b95f80205cc69421884710dbc10bfeae69a8b65/configs/prefect.json
