### ISSUE TITLE
Worker concurrency count getting stuck when aborting flow run submission 

### ISSUE THREAD

**Issue by jdjfisher** [PrefectHQ/prefect#15952]
### Bug summary

Workers aborting flow run submissions is incorrectly setting the local concurrency count.

I've got a few workers setup to process the same pool, each of which have `--limit=1` to ensure that concurrent runs don't happen on the same machine, this is because our flow depends on some software which cannot be dual run on a given compute instance. Outside of this constraint, global concurrency between workers is desirable, so no limit has been set on the pool or on task tags.
 
At some point, one of my workers had the following arise  ```Aborted submission of flow run ... Server sent an abort signal: this run is in a PENDING state and cannot transition to a PENDING state```
 
This suggests multiple free workers raced to claim the same run that entered the work pool and one of them had to back off. While Prefect Cloud and the other worker dealt with this situation as expected, the worker which aborted the submission thinks it is running that flow run and didn't decrement its local concurrently count. Given the --limit=1 setup, it is now forever stuck in the following state ```Flow run limit reached; 1 flow runs in progress.```

This means that over time as race conditions are met, all of our workers except from 1 are locking up and unable to process flows unless rebooted.

### Version info

```Text
Version:             3.1.0
API version:         0.8.4
Python version:      3.12.6
Git commit:          a83ba39b
Built:               Thu, Oct 31, 2024 12:43 PM
OS/Arch:             win32/AMD64
Profile:             ephemeral
Server type:         cloud
Pydantic version:    2.9.2

Also observed on Prefect 3.0.10 (Windows)

And using OSS in a local Docker setup
```

### Additional context
<img width="1702" alt="Screenshot 2024-11-08 at 12 00 23" src="https://github.com/user-attachments/assets/e8a41a4e-3c03-4209-a2dd-09d235026910">

**Comment by desertaxle** [comment]
Thanks for the bug report @jdjfisher!

I think we're missing some error handling in the `BaseWorker` to release the occupied slot in the local concurrency limiter when the worker fails to submit a flow run for execution. I'll investigate and let you know when I have a potential fix.

**Comment by jdjfisher** [comment]
I've just had a quick dig through the source and I think you're right, it looks like theres a missing case to release the slot when `ready_to_submit` is `false` https://github.com/PrefectHQ/prefect/blob/8758666101ce96d4f7ce098563a41ea81db8d5ef/src/prefect/workers/base.py#L955
