### ISSUE TITLE
Issue with settings when `profiles.toml` is absent

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#15981]
### Bug summary

Context: I have no other Prefect environment variables set, no `~/.prefect/profiles.toml` file, and no other settings source file.

In this scenario, I cannot turn ephemeral mode off:

```
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE='false' python -c "from prefect.settings import PREFECT_SERVER_ALLOW_EPHEMERAL_MODE; print(PREFECT_SERVER_ALLOW_EPHEMERAL_MODE.value())"

# True
```

Tried with `PREFECT_SERVER_ALLOW_EPHEMERAL_MODE=0`, etc. It seems that the order of sources is being messed up whenever there is no `profiles.toml` set.

Running `PREFECT_SERVER_ALLOW_EPHEMERAL_MODE=0 prefect profile inspect` gives:

```
No name provided, defaulting to 'ephemeral'
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE='true'
```

### Version info

```Text
Version:             3.1.2.dev1+7.g4f2fc5add0
API version:         0.8.4
Python version:      3.10.13
Git commit:          4f2fc5ad
Built:               Mon, Nov 11, 2024 1:07 PM
OS/Arch:             darwin/arm64
Profile:             ephemeral
Server type:         ephemeral
Pydantic version:    2.7.1
Server:
  Database:          sqlite
  SQLite version:    3.41.2
Integrations:
  prefect-aws:       0.5.0
```

**Comment by j-carson** [comment]
Related? #15984

**Comment by desertaxle** [comment]
After digging into this, it looks like there are some scenarios more broadly where profiles can unexpectedly override environment variables. Seems to be related to the ordering of the validation aliases for some fields, but I think we'll be able to fix this with a tweak to the `ProfileSettingsTomlLoader`.
