### ISSUE TITLE
PREFECT_LOGGING_EXTRA_LOGGERS can be set in environment, but not from a file

### ISSUE THREAD

**Issue by j-carson** [PrefectHQ/prefect#15984]
### Bug summary

When I set PREFECT_LOGGING_EXTRA_LOGGERS=my_logger in my environment, everything works as expected
When I try to get it from my profile or any file it seems, my extra logs do not show up in the prefect ui

To reproduce: Download this repo: https://github.com/j-carson/prefect_log_question

Use: `make env_bug_env` to run the test program with settings in the environment. Logs show up in prefect UI for me.
Use: `make env_bug_file` to run the test program with settings from a .env file. Logs do NOT show up in prefect UI for me.

### Version info

```Text
Version:             3.1.1
API version:         0.8.4
Python version:      3.10.15
Git commit:          6b50a2b9
Built:               Fri, Nov 8, 2024 12:38 PM
OS/Arch:             linux/x86_64
Profile:             cloud
Server type:         cloud
Pydantic version:    2.9.2
```

### Additional context

I really don't want to rewrite my whole library to use Prefect's loggers. I just want to use the logging calls in my existing code.

**Comment by desertaxle** [comment]
Thanks for the bug report @j-carson! I have a sneaking suspicion that https://github.com/PrefectHQ/prefect/pull/15979 will fix this issue. Would you be willing to try out the changes in that PR and see if it fixes the issue?

**Comment by desertaxle** [comment]
@j-carson I'm fairly confident that https://github.com/PrefectHQ/prefect/pull/15979 fixed this issue.

When I run your `make env_bug_file` with the latest published version of `prefect` I see this:
![Screenshot 2024-11-12 at 10 23 58 AM](https://github.com/user-attachments/assets/e4393756-9151-4efa-af61-38062cc67917)

When I run the same thing from `main`, I see this:
![Screenshot 2024-11-12 at 10 24 30 AM](https://github.com/user-attachments/assets/7bc599ed-cae4-4693-b6d3-88aea2ee9938)
which matches the output when I run `make env_bug_env`.

The root issue was that when we were marshaling the `logging.extra_loggers` setting to an environment variable, it was in a form that was not correctly parsed by the environment running the flow.

The fix will be going out in the next release, so I'm going to close this issue as completed, but let me know if I've assumed incorrectly that this is resolved!

**Comment by j-carson** [comment]
Yes, confirmed it worked on my end as well
