### ISSUE TITLE
Storybook for UI V2?

### ISSUE THREAD

**Issue by evan-liu** [PrefectHQ/prefect#15998]
### Describe the current behavior

The "Replatform the UI" plan doesn't include Storybook in the toolset. 

### Describe the proposed behavior

Use Storybook for UI V2 development. 

### Example Use

The example Storybook with stories for `TagsInput`: 

- Preview: https://evan-liu.github.io/prefect
- Setup and stories code: https://github.com/evan-liu/prefect/pull/1

### Additional context

The [Replatform the UI](https://github.com/PrefectHQ/prefect/issues/15512) plan didn't include Storybook, which could help reduce "Barriers to contributions" by providing isolated development environments for UI development.

Please let me know if the team is interested and would like me to create a PR for the example setup.

**Comment by desertaxle** [comment]
Hey @evan-liu! I think it'd be great to include Storybook for the v2 UI! We're using pre-built components from `shadcn/ui`, so I don't think we'd host Storybook anywhere, but it'd be quite valuable for local development!
