### ISSUE TITLE
Metadata files generated with RayTaskRunner

### ISSUE THREAD

**Issue by dqueruel-fy** [PrefectHQ/prefect#16009]
## Issue description
I don't know if it's a bug or a desired behavior but some metadata files are generated each time I run my flows locally. That's annoying because the files are generated in my source directory (or from where I run the flows/tasks). I'd like to have more info, please, on what these files are and if we can generate it somewhere else or, ideally, not generate them at all.

It generates files with filenames like `89e55eaee58e8ce3567e87801196d9d5` in the same folder that I call the python script (see below) with the following content:
``` json
{
    "metadata": {
        "storage_key": "/Users/<path to my local source dir>/89e55eaee58e8ce3567e87801196d9d5",
        "expiration": null,
        "serializer": {
            "type": "pickle",
            "picklelib": "cloudpickle",
            "picklelib_version": null
        },
        "prefect_version": "3.1.2",
        "storage_block_id": null
    },
    "result": "gAVLAS4=\n"
}
```

The minimal reproducible python script is 
``` python
from prefect import flow, task
from prefect_ray import RayTaskRunner

@task(log_prints=True, persist_result=True)
def taskA():
    print("Task A")
    return 1

@flow(log_prints=True, persist_result=True, task_runner=RayTaskRunner)
def myFlow():
    print("In my flow")
    taskA.submit().wait()
    return 0

myFlow()
```

### Version info

```Text
Version:             3.1.2
API version:         0.8.4
Python version:      3.11.9
Git commit:          02b99f0a
Built:               Tue, Nov 12, 2024 1:38 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-ray:       0.4.2
```

### Additional context

Some notes:
- These files are not generated when I remove the RayTaskRunner **or** when I set `persist_result` to `False` .
- I saw this files being generated when I upgraded prefect from `3.0.0rc14` to` 3.1.1` in my code base, and I reproduced it in this minimal example.
- I've tried to change the server config's `PREFECT_LOCAL_STORAGE_PATH` to `/tmp/result` but it didn't help
- Screenshot of the flow and task ran from the minimal python code
![image](https://github.com/user-attachments/assets/9aee7cdf-5615-43a3-a6f4-7a892d3c6151)

**Comment by cicdw** [comment]
Hey @dqueruel-fy - those files are a consequence of persisting task and flow results. 

> I've tried to change the server config's PREFECT_LOCAL_STORAGE_PATH to /tmp/result but it didn't help

This setting has an effect at _workflow runtime_ and therefore setting it on the server will have no effect (all server configuration is prefixed with `PREFECT_SERVER_`). If you set this setting within the process that your workflows execute you should see the desired behavior.

For more information, check out the documentation on results and settings:
- [results](https://docs.prefect.io/3.0/develop/results)
- [settings](https://docs.prefect.io/3.0/develop/settings-and-profiles)

**Comment by cicdw** [comment]
Ah I think I have a suspicion for what's going on! A few details (some of which are repetitive just for completeness sake):
- whenever `PREFECT_LOCAL_STORAGE_PATH` is not set (and when there is no default storage block either), the default storage location for results is the present working directory as you've seen
- this setting must be set on the _client_ that executes the workflow to take affect
- Ray uses multiple processes (or machines, but it sounds like you are running Ray locally on one machine) for distributing work
- setting this as an environment variable in one runtime but not in the runtime of the Ray workers will cause any tasks executed on the workers to not pick up the setting

If my suspicion is correct that you are only setting this setting on the "parent" process that executes the flow and not on the Ray workers, the easiest solution is probably to use a `.env` file or `prefect.toml` file to persist this setting across all processes started in that directory.

**Comment by zzstoatzz** [comment]
hi @dqueruel-fy - I am looking into this now (this seems like a bug).

it looks like when in ray, the task is unable to discover the parent context's result storage base path and falling back to a relative path

will update hopefully soon!

I don't think `prefect.toml` helps here in the context of this issue, but if you're generally curious I'd check [this](https://www.youtube.com/watch?v=aeWCT_fqdEY) out.
