### ISSUE TITLE
Add option to use Prefect secrets for AWS creds in FargateTaskEnvironment

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1603]
## Current behavior
The `FargateTaskEnvironment` requires `aws_access_key_id`, `aws_secret_access_key`, and `region_name` to be provided at initialization.

## Proposed behavior
Allow for AWS credentials to be optionally retrieved from Prefect Secrets that way they can be loaded at runtime.

## Example
N/A

**Comment by shrmnk** [comment]
Is this being worked on? I am thinking of writing a notification task for AWS SES, which will also require the use of AWS credentials. Would help greatly if there is existing code that pulls AWS creds from Prefect Secrets to reference.

**Comment by joshmeek** [comment]
@shrmnk As far as I am aware this has not been started yet but that shouldn't stop you from writing your task for AWS SES! There are some AWS tasks which already exist that use some form of AWS credentials

e.g. https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/aws/lambda_function.py#L132

**Comment by joshmeek** [comment]
Closing, the FargateTaskEnvironment has been deprecated and an [ECSRun](https://docs.prefect.io/orchestration/flow_config/run_configs.html#ecsrun) should be used instead
