### ISSUE TITLE
PDB (pdbpp) disrupted by prefect logs

### ISSUE THREAD

**Issue by teocns** [PrefectHQ/prefect#16062]
### Bug summary

I use [pdbpp](https://github.com/pdbpp/pdbpp) for debugging and its meant to provide enhanced debugging experience especially text rendering side. 

Somehow prefect disrupts text rendering of the `pdb` display:

1. Hit `n` which leads you to the next call in the stack
2. Prefect's logger will flush logs and render text on screen
3. The whole screen is cleared (!!)
4. At this point the debugger screen is completely cleared and only shows an empty prompt

<img width="378" alt="image" src="https://github.com/user-attachments/assets/6ab7e15c-cf71-4c07-81a1-5bdf47d650c4">

... which results in me having to run PDB's `ll` command to display code context of where I am (which shouldn't be happening)
<img width="534" alt="image" src="https://github.com/user-attachments/assets/557794ac-a383-4790-84d1-80ab6032106a">

---

My follow up question would be if we can disable prefect run logs globally? 
As a side thought we can write a hook to interop with pdb and have better timing in flushing and rendering when PDB context is active

**Comment by teocns** [comment]
cc @zzstoatzz in case my issue gets buried

**Comment by zzstoatzz** [comment]
hi @teocns - can you give an MRE for this? that will help us understand if there's a non-disruptive change we can make to be compatible with this 3rd party

**Comment by teocns** [comment]
Ok further investigation and this is actually an issue belonging to `pdbpp`s side, it occurs in many other circumstances whereas logging handlers are overridden which it is very sensitive to changes. Closing, thanks for jumping in @zzstoatzz !
