### ISSUE TITLE
cache_key_fn not used in the redis integration

### ISSUE THREAD

**Issue by gigaverse-oz** [PrefectHQ/prefect#16078]
### Bug summary

When using result_storage with `RedisDatabase` the `cache_key_fn` is not being used.

Usage example
```python
@task(
    result_storage=persistance_block_redis,
    cache_expiration=timedelta(minutes=10),
    cache_key_fn=define_cache_key,
)
```
Redis key example for that implementation:
`flow_name='test_2_flow_81' flow_run_time=10 flow_expected_output='output2'_sub_1`

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.11.6
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.10.0b2
Integrations:
  prefect-redis:     0.2.1
  prefect-kubernetes: 0.5.0
```

### Additional context

Used local redis-stack in docker and local prefect server.

**Comment by gigaverse-oz** [comment]
Hi @zzstoatzz 
Did you check the key in the redis is identical to what you set? I got the default key in redis.
Your example doesn't work for me - I do get your prints but the key is not used in redis.

Each run of the flow creates new keys for the tasks in redis instead of getting the cache from the ones that were already created.

Here are the key names from redis:
![image](https://github.com/user-attachments/assets/4fdf3328-e8b7-4e4b-a50f-4a84b12c71e0)

**Comment by gigaverse-oz** [comment]
@zzstoatzz

I'm sorry, I had a mistake and it works fine. Passed the wrong object as key which confused me a lot.

**Comment by zzstoatzz** [comment]
all good @gigaverse-oz, thanks for the update!
