### ISSUE TITLE
Avoid redundant image builds with prefect.yaml

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#16191]
### Describe the current behavior

When deploying multiple flows with prefect.yaml users want the ability to build a single common Docker image as opposed to one per flow. Managing and building 10s or 100s of images becomes burdensome when you are building a single Docker container with all your code.

Consider the following Dockerfile:

```
FROM prefecthq/prefect:3-latest

COPY . .

RUN pip install -r requirements.txt
```

This image will identical for all deployments, but will be built once for each deployment.

### Describe the proposed behavior

When running prefect deploy with multiple deployments in a prefect.yaml file that share a common image, the image should be built only once.

**Comment by zzstoatzz** [comment]
hi @EmilRex - hmm can you clarify if this is not solved by https://github.com/PrefectHQ/prefect/pull/13286?

I opened https://github.com/PrefectHQ/prefect/issues/12928 a while ago, which should be closed by the above

if not, what version of `prefect-docker` is being used?

**Comment by EmilRex** [comment]
@zzstoatzz hmm that definitely looks like it solves it. I must have been using an older version. I'll close this issue and can always re-open if necessary. Apologies for the confusion!
