### ISSUE TITLE
No module named 'prefect_ray.task_runners' when Serving RayTaskRunner

### ISSUE THREAD

**Issue by joreeves** [PrefectHQ/prefect#16206]
### Bug summary

Possible I'm going about this wrong but, when serving a `flow` that has uses a `RayTaskRunner` and running it I get:
```
prefect.exceptions.ScriptError: Script at 'workflows/prefect_bug_2.py' encountered an exception: ModuleNotFoundError("No module named 'prefect_ray.task_runners'; 'prefect_ray' is not a package")
```

Running the flow directly works ok.

```python
from prefect import task, flow
from prefect_ray.task_runners import RayTaskRunner

import ray

if not ray.is_initialized():
    ray.init()


@task
def echo():
    return "Hello"


@flow(log_prints=True, task_runner=RayTaskRunner())
def ray_serve_test():
    echo_result = echo()
    return echo_result


# Run the flow
if __name__ == "__main__":
    from prefect import serve as prefect_serve

    ray_test = ray_serve_test.to_deployment("Test")

    prefect_serve(ray_test)
```

## Steps to reproduce:
1. Start the prefect server `python sample_script.py`
2. Call `prefect deployment run  ray-serve-test/Test` from the CLI
3. Get error `No module named 'prefect_ray.task_runners`

### Version info

```Text
Version:             3.1.5
API version:         0.8.4
Python version:      3.11.10
Git commit:          3c06654e
Built:               Mon, Dec 2, 2024 6:57 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-dask:      0.3.2
  prefect-ray:       0.4.3
```

**Comment by zzstoatzz** [comment]
hi @joreeves - thanks for the issue!

a couple things:

- I am not currently able to reproduce your error with your exact code above / on the same versions
```python
» prefect version
Version:             3.1.5
API version:         0.8.4
Python version:      3.11.9
Git commit:          3c06654e
Built:               Mon, Dec 2, 2024 6:57 PM
OS/Arch:             darwin/arm64
Profile:             pong
Server type:         cloud
Pydantic version:    2.10.3
Integrations:
  prefect-ray:       0.4.3
```

- you should't need to `ray.init()` unless you have a cluster that you need special handling for, but in your example since you don't connect to a cluster (by passing kwargs into `RayTaskRunner()`), in fact you might run into a conflict since the task runner will generally handle starting / connecting to the cluster

- you can just call the serve method on flows, like this example

```python
from prefect_ray.task_runners import RayTaskRunner

from prefect import flow, task


@task
def echo(message: str):
    return message


@flow(log_prints=True, task_runner=RayTaskRunner())
def ray_serve_test():
    print(echo.map(message=["Hello", "World"]).result())


# Run the flow
if __name__ == "__main__":
    ray_serve_test.serve()
```

let me know if you're still running into trouble!

**Comment by joreeves** [comment]
Thanks for the quick reply @zzstoatzz. In a moment of brilliance, i realize why it was giving that error... I had named my script `prefect_ray.py` 😆 One mystery solved. 

Question though regarding the `ray.init()`: I am using a local ray instance and if I pass "http://127.0.0.1:10001" to the RayTaskRunner address I get `httpx.ConnectError: All connection attempts failed` i've also tried port `8265` and `6379`. If I leave this blank will it use the local ray cluster?

**Comment by zzstoatzz** [comment]
> If I leave this blank will it use the local ray cluster?

Yes, ray (within the task runner) will spin up an ephemeral cluster unless you specify an existing cluster

**Comment by zzstoatzz** [comment]
please feel free to open a discussion around best practices on connecting to ray clusters!
