### ISSUE TITLE
Add Tests for task tag client methods

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1630]

**Comment by alexisprince1994** [comment]
Hi there! Is this referencing the `get_task_tag_limit` and the `update_task_tag_limit` methods? Are there any others?

**Comment by cicdw** [comment]
Hi @alexisprince1994 ! Yes, this is referring to adding some basic mocked unit tests for those two client methods.  

All of the Prefect Cloud GraphQL schema is exposed with documentation through any GraphQL client. For example, using GraphQL Playground we can see the following schema docs for `task_tag_limit` and `updateTaskTagLimit` respectively:

![image](https://user-images.githubusercontent.com/13255838/68556038-6f6c8b00-03e5-11ea-871c-c2659bd63632.png)

![image](https://user-images.githubusercontent.com/13255838/68556090-a5117400-03e5-11ea-8a2a-3db1a562e54e.png)

(Sorry for the extra large images here).  So, to directly answer your question, querying `task_tag_limit` can return any of the fields listed above depending on what you specifically request, and `updateTaskTagLimit` always returns the `id` of the task tag.

To access this schema requires authenticating with Prefect Cloud.  We try to keep https://docs.prefect.io/cloud/concepts/api.html#api-token-scopes updated with various popular queries / mutations, but it's not exhaustive.

**Comment by cicdw** [comment]
Closing as stale
