### ISSUE TITLE
Resuming from checkpointed state?

### ISSUE THREAD

**Issue by FaizShah** [PrefectHQ/prefect#1635]
Hi,

I'm just getting started with prefect. 

I'm wondering: if I set checkpointing to true and the flow ends in a partially completed failed state. How do I resume from a checkpoint after I have resolved the issue?

**Comment by cicdw** [comment]
Hi @FaizShah - this is a great question.  Currently, checkpointing is intended as a means to persist the outputs of your tasks, and nothing more.  To resume from a checkpoint you can either:

- use [Prefect caching](https://docs.prefect.io/core/concepts/persistence.html#output-caching) instead (note that when running with Core alone, the cache only lives in memory, so if you need to make code changes to your flow they'll need to be done in the same process you ran the flow in)
- OR construct a `Success` state object manually, and then use the `task_states` keyword argument to "assert" that your upstreams have been successful (note that in the example below I am ignoring [result handlers](https://docs.prefect.io/core/concepts/results.html#result-handlers))

To illustrate:
```python
from prefect import task, Flow
from prefect.engine.state import Success

@task
def return_num():
    return 0

@task
def compute(x):
   return 1 / x

with Flow("example") as flow:
    output = compute(return_num)


flow_state = flow.run() # fails

@task
def compute_fixed(x):
    return 1 / (x + 1)

flow.replace(output, compute_fixed)

# succeeds without recomputing the `return_num` task because
# it is already considered successful, with output value 0
flow_state = flow.run(task_states={return_num: Success(result=0)})
```

**Comment by FaizShah** [comment]
Thanks! I'm gonna try this out this weekend :+1:
