### ISSUE TITLE
Build matrix of docker images

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1636]
We should build prefect for all supported python versions and all prefect versions, including latest.

The naming convention we would use could be:

`prefecthq/prefect:0.6.7_3.6`, `prefecthq/prefect:latest_3.7`, etc. and we could still have a single `prefecthq/prefect:latest`, etc. with a fixed version of Python (currently we do 3.6, that seems reasonable to me?).

Once we do this, we can start using them as base images for our flow deploys, which should speed up Cloud deploys!

**cc:** @joshmeek @wagoodman

**Comment by joshmeek** [comment]
I fully support this idea for quicker off-the-shelf deploys and I'm down with `latest` being 3.6 👍

**Comment by cicdw** [comment]
Closed in #1648
