### ISSUE TITLE
Update contributions docs and ruff checks out of sync.

### ISSUE THREAD

**Issue by williamjamir** [PrefectHQ/prefect#16375]
### Describe the current behavior

I recently opened a PR to the repo and would like to share some issues that I found that would be helpful to address.

### Issue 1: Update the contributor's guide.
---

The pre-commit requires the environment to be created by UV, but the docs only mention `python -m venv.` 
It would be beneficial to update the documentation related to this.

I just figured out this because of this comment: https://github.com/PrefectHQ/prefect/pull/15502#issuecomment-2377360741

### Issue 2: Inconsistencies with the ruff format and ruff check
---

When running ruff format, many files are changed, indicating they are out of sync. Similarly, ruff check displays many issues.

It is necessary to run ruff format on the entire codebase at least once to sync everything and run a ruff check to resolve all issues (currently, there are 31 errors).

This would ensure clarity for new contributors who might make changes that conflict with these checks and think it was a mistake on their part.

**Comment by zzstoatzz** [comment]
hi @williamjamir - thanks for the issue!

I agree we should update the contributor's guide


on the `ruff` thing, we use `pre-commit` to invoke `ruff`

```
» pre-commit run --all-files
ruff.....................................................................Passed
ruff-format..............................................................Passed
...
```

are you seeing errors when invoking the pre-commit?

**Comment by williamjamir** [comment]
When running from pre-commit, indeed, everything is fine.
 
The issue is when calling Ruff directly as stated over the docs :)
<img width="780" alt="image" src="https://github.com/user-attachments/assets/7bc6a81c-576e-45b6-8aee-0ff2c839a8cb" />

And just know I realized that the first command had failed 😅 
```
(prefect-fork) ➜  prefect git:(williamjamir/add_connect_args) uv pip install $(./scripts/precommit-versions.py)
Traceback (most recent call last):
  File "/opt/opensource/prefect/./scripts/precommit-versions.py", line 36, in <module>
    rev_by_id = {item["hooks"][0]["id"]: item["rev"] for item in precommit_config["repos"]}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opensource/prefect/./scripts/precommit-versions.py", line 36, in <dictcomp>
    rev_by_id = {item["hooks"][0]["id"]: item["rev"] for item in precommit_config["repos"]}
                                         ~~~~^^^^^^^
KeyError: 'rev'
error: the following required arguments were not provided:
  <PACKAGE|--requirement <REQUIREMENT>|--editable <EDITABLE>>

Usage: uv pip install <PACKAGE|--requirement <REQUIREMENT>|--editable <EDITABLE>>

```

But after executing ruff check and ruff format 

```
(prefect-fork) ➜  prefect git:(williamjamir/add_connect_args) ruff format
69 files reformatted, 1246 files left unchanged
```

```
(prefect-fork) ➜  prefect git:(williamjamir/add_connect_args) ruff check
Found 31 errors.

```
