### ISSUE TITLE
Modal Pool workers crashing

### ISSUE THREAD

**Issue by lsscodes** [PrefectHQ/prefect#16395]
### Bug summary

All flows running on Prefect cloud with Modal Push pools failed since UTC 00:00 today

`Flow run could not be submitted to infrastructure: (<Status.INVALID_ARGUMENT: 3>, 'Version 0.62.203 of `modal` will be deprecated soon, and cannot be used to create new apps.', None)`

![image](https://github.com/user-attachments/assets/24e4ab05-4530-4472-a958-096b7ac17951)
![image](https://github.com/user-attachments/assets/35af7e4f-9c76-4790-b4bf-a59a4743d983)
![image](https://github.com/user-attachments/assets/8d0a3e2b-727b-4d31-93ef-05b245bf5c65)

### Version info

```Text
The problems seem to be related to Prefect cloud, Prefect version is irrelevant I guess
```

**Comment by lsscodes** [comment]
my flows are still failing, any help is much appreciated

**Comment by pbechet** [comment]
Hi, I have the same issue

**Comment by lsscodes** [comment]
@zzstoatzz, do you know what is causing the flow to crash?

**Comment by lsscodes** [comment]
it looks like the flows are running and Modal work pools are working again

![image](https://github.com/user-attachments/assets/ebf46408-0226-4316-be51-aa7ef821c51d)

**Comment by zhen0** [comment]
Yes!  Was just about to add an update that this should now be working. Thanks for confirming.  I'll close this issue but please open a new issue if you run into further problems!

**Comment by lsscodes** [comment]
@zhen0 what caused the issue? our pipelines were down for over 2days
would this happen again in the future? can we do something about it?

**Comment by zhen0** [comment]
Thanks for ask lsscodes!  I looked into it because my work pool also had an issue. My understanding is that Modal (the company) deprecated the version of Modal (the product) that the Prefect Modal work pool was using.  I'm going to check with the team to see if there's anything we could put in place to avoid this in future.

**Comment by lsscodes** [comment]
@zhen0 thanks. if you have any more info please post it here. otherwise it is all working fine now
