### ISSUE TITLE
Include other local python files within the flow Docker image

### ISSUE THREAD

**Issue by wagoodman** [PrefectHQ/prefect#1639]
## Current behavior
Assume a project layout like so:
```
.
├── app.py
├── opensky.py
└── position.py
```

There is an option for including other python files when deploying a flow to cloud:
```
flow.deploy(…, files={'abs-file-path': 'container-path',…}…)
```
which in this case would be:
```
flow.deploy(..., files={
  '/the/path/to/opensky.py': 'opensky.py',
  '/the/path/to/position.py': 'position.py',
})
```
This approach requires the user to know where the flow is execute from and ensure there are no clashes in file names that already exist within the image.

Most importantly this appears not to work when deploying the flow to cloud:
```
Failed to load and execute Flow's environment: ModuleNotFoundError("No module named 'position'")
```

## Proposed behavior
At a high-level it should be easier to include python files that are not part of a pip-installable python package. There are several ways to solve this problem... this issue can be a starting point for discussion in finding the desired behavior.

**Comment by cicdw** [comment]
I argue this is closed by https://github.com/PrefectHQ/prefect/pull/1740 which allows for you to specify a local Dockerfile for your base image.  This allows for easily adding custom scripts to your image + updating your PATH / PYTHONPATH.  Feel free to reopen if you disagree @wagoodman
