### ISSUE TITLE
Server command exits with exit code 0 even when failing due to database connectivity

### ISSUE THREAD

**Issue by martimors** [PrefectHQ/prefect#16474]
### Bug summary

I noticed this when deploying via helm: The pod reaches status `Completed` when an exception is thrown. It should exit with non-0 such that kubernetes will restart the pod.

### Version info

```Text
2024.12.19222717 (helm)
```

### Additional context

I can potentially fix the issue myself if you'll accept a contribution

**Comment by cicdw** [comment]
@martimors we'd love a contribution, either to the main prefect library or https://github.com/PrefectHQ/prefect-helm! We have [some contribution docs here](https://docs.prefect.io/contribute/dev-contribute) if that's helpful to get setup. Let us know if we can help

**Comment by martimors** [comment]
> @martimors we'd love a contribution, either to the main prefect library or https://github.com/PrefectHQ/prefect-helm! We have [some contribution docs here](https://docs.prefect.io/contribute/dev-contribute) if that's helpful to get setup. Let us know if we can help

I gave it a stab https://github.com/PrefectHQ/prefect/pull/16476

Let me know what you think
