### ISSUE TITLE
ModuleNotFoundError: No module named 'dbt.cli'; 'dbt' is not a package

### ISSUE THREAD

**Issue by diego-infostrux** [PrefectHQ/prefect#16484]
### Bug summary

Created a Python 3.11.9 virtual environment on Windows Server 2019
Activated it
Installed prefect dbt:  `pip install "prefect[dbt]" -U --force-reinstall`

Running a basic example fails saying it cannot resolve dbt

```python
from prefect import flow
from prefect_dbt.cloud import DbtCloudJob
from prefect_dbt.cloud.jobs import run_dbt_cloud_job
import asyncio


@flow
async def run_dbt_job_flow():
    result = await run_dbt_cloud_job(
        dbt_cloud_job = await DbtCloudJob.load("dbt-cloud-job"),
        targeted_retries = 0,
    )
    return await result

if __name__ == "__main__":
    asyncio.run(run_dbt_job_flow())
```

It fails with this error message:
```
python flows/dbt2.py
Traceback (most recent call last):
  File "C:\Users\xx\workspace\prefect_demo\flows\dbt2.py", line 2, in <module>
    from prefect_dbt.cloud import DbtCloudJob
  File "C:\Users\xx\workspace\prefect_demo\venv-prefect\Lib\site-packages\prefect_dbt\__init__.py", line 4, in <module>
    from .cli import (  # noqa
  File "C:\Users\xx\workspace\prefect_demo\venv-prefect\Lib\site-packages\prefect_dbt\cli\__init__.py", line 2, in <module>
    from .commands import DbtCoreOperation  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\workspace\prefect_demo\venv-prefect\Lib\site-packages\prefect_dbt\cli\commands.py", line 8, in <module>
    from dbt.cli.main import dbtRunner, dbtRunnerResult
ModuleNotFoundError: No module named 'dbt.cli'; 'dbt' is not a package
(venv-prefect)
```

### Version info

```Text
Version:             3.1.9
API version:         0.8.4
Python version:      3.11.9
Git commit:          e1fe7943
Built:               Fri, Dec 20, 2024 4:33 PM
OS/Arch:             win32/AMD64
Profile:             local
Server type:         server
Pydantic version:    2.10.4
Integrations:
  prefect-dbt:       0.6.4
  prefect-shell:     0.3.1
```

**Comment by diego-infostrux** [comment]
Also tried installing dbt and dbt-core manually, but I got the same error:

pip install dbt -U --force-reinstal --no-cache
pip install dbt-core -U --force-reinstal --no-cache

**Comment by zzstoatzz** [comment]
hi @diego-infostrux - that's odd

```
» uv run -p 3.11.9 --with 'prefect[dbt]' python -c 'import dbt;print(dbt.__name__)'
dbt
```

I would suspect that something is amiss with your python environment. do you have a file called `dbt.py` that may be shadowing the `dbt` module? asking as I notice this filename
```
  File "C:\Users\xx\workspace\prefect_demo\flows\dbt2.py", line 2, in <module>
```

if not, steps to reproduce from a fresh environment would be helpful! it's possible (although unlikely in my mind) that this is a Windows specific issue but I suspect a virtual environment issue first

**Comment by diego-infostrux** [comment]
> hi @diego-infostrux - that's odd
> 
> ```
> » uv run -p 3.11.9 --with 'prefect[dbt]' python -c 'import dbt;print(dbt.__name__)'
> dbt
> ```
> 
> I would suspect that something is amiss with your python environment. do you have a file called `dbt.py` that may be shadowing the `dbt` module? asking as I notice this filename
> 
> ```
>   File "C:\Users\xx\workspace\prefect_demo\flows\dbt2.py", line 2, in <module>
> ```
> 
> if not, steps to reproduce from a fresh environment would be helpful! it's possible (although unlikely in my mind) that this is a Windows specific issue but I suspect a virtual environment issue first

You're right!
That was the issue.
I had a file called dbt.py, after renaming it, it started working.
Thank you so much!

**Comment by diego-infostrux** [comment]
You're absolutely right!
that was the issue, I had a flow called dbt.py

**Comment by zzstoatzz** [comment]
thanks for following up 🙂 - glad you got things working!
