### ISSUE TITLE
Add new build step for agent images

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1670]
## Current behavior
Currently the agents work off of `prefecthq:prefect` which does not have agent-specific dependencies.

## Proposed behavior
Add a new build step for the agents
`prefecthq/k8s-agent`
`prefecthq/fargate-agent`
Local will still be served off of the base prefect image since it does not have any extra dependencies

## Example
N/A

**Comment by lauralorenz** [comment]
Willing to reopen if someone needs this, but think that separate agent images may not be necessary (and would greatly expand the image build triggers a commit to Core would cause). Closing
