### ISSUE TITLE
Prefect + Dask-Kubernetes Deployment on Cloud Provider Example (GCP)

### ISSUE THREAD

**Issue by digitaltopo** [PrefectHQ/prefect#1692]
## Use Case
*Please provide a use case to help us understand your request in context*

In @cicdw's Dask Storiea article [Prefect: Production Workflows](https://stories.dask.org/en/latest/prefect-workflows.html), he mentions that:

"Our preferred deployment of Prefect Flows uses dask-kubernetes to spin up a short-lived Dask Cluster in Kubernetes."

It wasn't entirely clear to me how Dask (on Kubernetes) deployments are configured in relation to Prefect.

## Solution
*Please describe your ideal solution*

It would be very helpful to have a detailed tutorial on how to set this up (preferably on a cloud provider like GCP) or a Helm chart that achieves Dask-Kubernetes powered Prefect deployment on cloud provider Kubernetes like GKE (Google Kubernetes Engine) etc.

Thank you and looking forward to exploring Prefect!

**Comment by cicdw** [comment]
Hi @digitaltopo - the reference in that story is to how deployments work on Prefect Cloud.  Prefect Core (this repo) is a stateless engine, so "deploying" it just means running a Python process.

That being said, to deploy a Cloud workflow using dask-kubernetes requires a [kubernetes agent](https://docs.prefect.io/cloud/agent/kubernetes.html) with the appropriate permissions, and then attaching an appropriately configured [Dask Kubernetes environment](https://docs.prefect.io/api/unreleased/environments/execution.html#daskkubernetesenvironment) to your Flow via the `environment` attribute.  Whenever this flow is submitted for execution, the environment will spawn a Dask cluster with the appropriate settings, and tear it down whenever the flow has completed its run.
