### ISSUE TITLE
Flow Run fails with "unknown opcode" error when prefect_version="0.7.0" is set with no base image

### ISSUE THREAD

**Issue by nanseay** [PrefectHQ/prefect#1706]
## Description
Task 'Promote Reminder': Calling task.run() method...
prefect.CloudTaskRunner | ERROR | Unexpected error: SystemError('unknown opcode',) Traceback (most recent call last):   File "/usr/local/lib/python3.6/site-packages/prefect/engine/runner.py", line 48, in inner     new_state = method(self, state, *args, **kwargs)   File "/usr/local/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 869, in get_task_run_state     self.task.run, timeout=self.task.timeout, **raw_inputs   File "/usr/local/lib/python3.6/site-packages/prefect/utilities/executors.py", line 79, in timeout_handler     return fn(*args, **kwargs)   File "/Users/nanseay/prepo/Core_Flows/promote_reminder.py", line 12, in reminder SystemError: unknown opcode

## Expected Behavior
My flow to run and complete successfully
(Note: flow ran successfully when run locally)

## Reproduction
Don't set a base image
Include kwarg prefect_version="0.7.0"

## Environment
Core 0.7.0
Python 3.7.3

**Comment by cicdw** [comment]
This suggests your docker image is being built with a python version which is different from the one you wrote the flow in.

**Comment by cicdw** [comment]
Yup, I can see it in your info actually: you built your flow using 3.7.3 but it is being executed using 3.6

**Comment by cicdw** [comment]
@nanseay when did you deploy this?

**Comment by nanseay** [comment]
That error is from this morning, but I saw it yesterday too

**Comment by cicdw** [comment]
Could you redeploy the flow off master and see if it happens again? I think I know what caused this and it should be fixed now.

**Comment by nanseay** [comment]
Ok, I'm going to remove both ```base_image="python:3.7", prefect_version="0.7.0"``` leaving just my registry_url and will redeploy off of master

**Comment by nanseay** [comment]
@cicdw yep, it works when I deploy off master

**Comment by cicdw** [comment]
Ok excellent!
