### ISSUE TITLE
Support docker image for raspberry pi (arm)

### ISSUE THREAD

**Issue by wagoodman** [PrefectHQ/prefect#1722]
## Use Case
Looking to support prefect Kubernetes agent in an arm environment (for a raspberry pi) .

## Solution
This would require building the prefect core docker image on arm hardware. Luckily the python-* images already have arm image built and ready for use.

**Comment by cicdw** [comment]
@wagoodman is the bottleneck here actually running the k8s agent in an appropriate image, as I'm assuming you can already configure your Flow's docker image to be ARM-compatible?

If so, you might try taking the output of `prefect agent install kubernetes` and altering the base image to point to a custom Prefect / ARM-compatible image.

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if needed.

**Comment by deeplook** [comment]
Any chance to see that happen?

**Comment by dylandoamaral** [comment]
Did it work on ARM now ?

**Comment by madkinsz** [comment]
Yes we publish ARM images now.

**Comment by madkinsz** [comment]
See #7740
