### ISSUE TITLE
Refactor Client to mimic Cloud's API structure

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1723]
## Current behavior
Change top level access to follow a more nested approach.
Current (example): `client.delete_flow(), client.set_task_run_state(), client.create_project()`

## Proposed behavior
Proposed (example): `client.flow.delete(), client.task_run.set_state(), client.project.create()`

This would now follow the approach we take in the GraphQL API (and somewhat similarly, the CLI)

**Comment by cicdw** [comment]
Let's not go too far on this quite yet, as it would represent a large breaking change

**Comment by lauralorenz** [comment]
Closing in favor of a PIN draft on the same topic: https://github.com/PrefectHQ/prefect/issues/1905
