### ISSUE TITLE
Add wait for completion option to CreateNamespacedJob task

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1724]
## Current behavior
Currently the `CreateNamespacedJob` k8s task creates the job but a custom task is needed in order to wait for a status from that job

https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/kubernetes/job.py#L11

## Proposed behavior
Add a kwarg `wait_for_completion` which would (on an interval) read the job's status and once it reaches Failed or Complete the status will be returned.

This would also warrant a slight refactor in what is currently returned from the task. Right now the task has no return and in cases where `wait_for_completion` is not specified we can return the Job's status at creation

**Comment by lauralorenz** [comment]
Closing in favor of different direction that prioritizes capstone tasks instead of configurable behavior on the granular task: https://github.com/PrefectHQ/prefect/issues/2281
