### ISSUE TITLE
Add wait for completion option to StartContainer task

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1725]
## Current behavior
Currently the `StartContainer` Docker task starts the container but a custom task is needed in order to wait for a status from that container

https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/docker/containers.py#L222

## Proposed behavior
Add a kwarg `wait_for_completion` which would (on an interval) [wait](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.wait) until the container stops, then return its exit code.

This would also warrant a slight refactor in what is currently returned from the task. Right now the task has no return and in cases where `wait_for_completion` is not specified we can return `None` since there is no exit code

**Comment by jcrist** [comment]
I think having a large task for running a command in a docker container, and waiting for completion (with optionally streaming logs) would be a good capstone task. This would be similar to the `ShellTask`, except the shell command is run inside a docker container with the image specified. This would box around the container creation, execution, waiting, and optional logs/cleanup. I'd probably want this to support all the args to `CreateContainer` (except for maybe `detach`), as well as:

- `remove_on_exit`: should the container be removed when execution is completed, defaults to true
- `stream_logs`: whether to stream the logs to prefect cloud (defaults to False).
- `log_level`: If `stream_logs` is true, the log level at which to log output at.

Not fully sure about the kwarg names here, but I think that's the general level of flexibility we'd want.

**Comment by cicdw** [comment]
Closing as stale
