### ISSUE TITLE
Remote FlowRunner

### ISSUE THREAD

**Issue by kforti** [PrefectHQ/prefect#1743]
I am curious if this has ever come up as a potential feature.

## Use Case
*Please provide a use case to help us understand your request in context*

Prefect Core for interactive use, where a flow is created and run, and new tasks can be added to the flow run.

## Solution
*Please describe your ideal solution*

I think the best place to implement this interactive feature is in a Remote FlowRunner. 

Creating and running a flow would look like this:

```python
from prefect import task, Flow

@task
def say_hello():
    print("Hello, world!")

@task
def say_hello_again():
    print("Hello, world!")

with Flow("My First Flow") as flow:
    say_hello()


flow_runner = flow.remote_run(addr="http://localhost:5000/")

new_task = say_hello_again()

flow_runner.add_task(new_task)

```

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

In general, I wish there was a way to add additional logic to the flowRunner- something similar to dask scheduler plugins. Then I could add a plugin for the flowRunner to check a queue for new tasks, update the flow and continue executing. I could also add a throttle plugin for the flowrunner to check the number of workers available and tasks submitted and decide to submit the next task or wait for a task to complete (using dask completed_futures()).

**Comment by joshmeek** [comment]
Hey @kforti thanks for the feature request! This is definitely a unique option 😄and I have not heard this appear as a feature during any discussions before. I don't have any immediate answers as to the technical requirements for this but I would like to point out that I am a fan of the idea where the flow runner could have something similar to dask scheduler plugins 🤔

**Comment by lauralorenz** [comment]
Closing this for now since it's a bit stale, but if anyone is interested in thinking on this we are interested in hearing more specific use cases (for example, can a flow replace a task in the middle of it on the fly? Append only? How does it work with dependencies/how do you specify a task's dependencies when you add it on the fly? etc etc)
