### ISSUE TITLE
Prefect User Config not working with Prefect cloud

### ISSUE THREAD

**Issue by mhmcdonald** [PrefectHQ/prefect#1754]
## Description
*A clear description of the bug*
Working with user config files locally works great, as described in this [document](https://docs.prefect.io/core/concepts/configuration.html#user-configuration)

However, I've tried exporting a user config file (.toml) to prefect cloud (we're running the Fargate agent). I do this by copying the file into docker storage using the `files` arg. I then set the environment variable `PREFECT__USER_CONFIG_PATH` to the path of this .toml file. 

The flows get deployed successfully, the file gets copied over and the envar gets set. However, 
when the flow is executed on cloud, and we call `prefect.config.SFK_USER` we get the following error:
`DEBUG | Task 'execute_snowflake_query[0]': Calling task.run() method...
-- | --
2019-11-9 3:38pm | prefect.CloudTaskRunner | ERROR | Unexpected error: BoxKeyError("'Config' object has no attribute 'SFK_USER'") Traceback (most recent call last):   File "/usr/local/bin/box.py", line 424, in __getitem__     value = super(Box, self).__getitem__(item) KeyError: 'SFK_USER'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/bin/box.py", line 506, in __getattr__     value = self.__getitem__(item, _ignore_default=True)   File "/usr/local/bin/box.py", line 431, in __getitem__     raise BoxKeyError(str(err)) box.BoxKeyError: "'SFK_USER'"  During handling of the above exception, another exception occurred:`

As an alternative way of deploying the config, rather than setting `PREFECT__USER_CONFIG_PATH`, I tried parsing the .toml file during the deployment and prefixing every envar with `PREFECT__` and just adding these envars to the env_vars arg in docker storage. This produced the same error (above). 

## Expected Behavior
*What did you expect to happen instead?*
I would expect the value of prefect.config.SFK_USER to get returned, just as it does when I run this locally. 

## Reproduction
*A minimal example that exhibits the behavior.*
1. create a file called uat.toml. Inside of this file put SFK_USER = PREFECT_READ_ONLY
2. in your flow code, call prefect.config.SFK_USER within one of your tasks

Deploy Flow
3. when deploying your flow to docker storage, in the `files` arg, use the source and destination of this file to copy the file into the docker container
4. in the env_vars arg, set PREFECT__USER_CONFIG_PATH to the destination file path of uat.toml

Run the Flow
5. From prefect cloud trigger the newly deployed flow

## Environment
*Any additional information about your environment*
We're running the Fargate Agent

**Comment by joshmeek** [comment]
Quick Q: Are you using `0.7.2`? This PR that was merged for the most recent release seems related https://github.com/PrefectHQ/prefect/pull/1719

**Comment by mhmcdonald** [comment]
Yea, I've tested this on 0.7.2 and still got this behavior.

**Comment by joshmeek** [comment]
If you run the image you built and call `prefect.config.SFK_USER` from inside does it still throw the same error?

**Comment by mhmcdonald** [comment]
I've confirmed that the file location in the docker container is where I expected it to be, and matches the location given to PREFECT__USER_CONFIG_PATH.

I've also, tested providing an envar with 'PREFECT__' prepended to it in the env_vars arg of the docker storage. I can confirm that when inside the docker container, running echo $PREFECT__SFK_USER returns the expected envar. Also, from inside the docker container, I've opened a python interpreter, and checked for the existence of prefect.config.sfk_user - the value also gets returned as expected. However it still fails when called within the flow.

**Comment by joshmeek** [comment]
@mhmcdonald Just wondering (for troubleshooting reasons), which [environment](https://docs.prefect.io/cloud/execution/overview.html#environments) and executor are you using for this deployment?

Also, does the error still occur in your Flow if you use:
```
import prefect
prefect.context.config.SFK_USER
```

**Comment by mhmcdonald** [comment]
@joshmeek So good news: calling `prefect.context.config.sfk_user` works! 
However calling: `prefect.context.config.SFK_USER` does not work. 

It seems the things in the config need to be lowercase, even though the envar is specified as PREFECT__SFK_USER.

We are using RemoteEnvironment. We don't specify the executor in our deployment. So, I believe we're using the default one, which is LocalExecutor, yes?

**Comment by joshmeek** [comment]
Ah yes I believe it makes them lowercase by default https://github.com/PrefectHQ/prefect/blob/master/src/prefect/configuration.py#L224

Yeah remote environment defaults to LocalExecutor. I'll run a test on this and see if I can recreate

**Comment by joshmeek** [comment]
@mhmcdonald I just deployed the following flow:
```
from prefect import task, Flow
from prefect.environments.storage import Docker


@task
def test():
    import prefect

    logger = prefect.context.get("logger")
    logger.info(prefect.config.MY_VAR)
    return prefect.config.MY_VAR


with Flow(
    "config-test",
    storage=Docker(
        files={
            "..abs_path../user_config.toml": "/root/.prefect/user_config.toml"
        },
        env_vars={"PREFECT__USER_CONFIG_PATH": "/root/.prefect/user_config.toml"},
    ),
) as flow:
    test()

flow.deploy(project_name="Demo")

```

where my user_config.toml looks like:
```
MY_VAR = "variable_here"
```

And in my Flow it had no issue finding the variable (log is from Cloud)
```
2019-11-21 1:55pm | prefect.Task: test | INFO | variable_here
```

**Comment by mhmcdonald** [comment]
@joshmeek I think the issue is that I was doing:

```
from prefect import task, Flow, config

@task
def test():
    return config.MY_VAR
```

While you are doing:
```
import prefect
from prefect import task, Flow

@task
def test():
    return prefect.config.MY_VAR
```

If I call prefect.config (as you are) this resolves the issue. Any idea why I can call config.MY_VAR successfully when I'm developing locally, but this fails when deployed?

**Comment by cicdw** [comment]
Hi @mhmcdonald !  I've been lurking and I think I know what's going on.  It's a little complicated, but ultimately boils down to how Flows are serialized and stored (using `cloudpickle`).  

Whenever you use the 

```python
from prefect import task, Flow, config

@task
def test():
    return config.MY_VAR
```

pattern, `cloudpickle` freezes the `config` object as-is.  However, whenever you use

```python
import prefect
from prefect import task, Flow

@task
def test():
    return prefect.config.MY_VAR
```

`cloudpickle` recognizes `config` as something it can access as a module attribute, and therefore at runtime it dynamically loads the configuration object (as you were expecting).  In general we recommend the `prefect.*` pattern for both config and context for this reason.

You can see this in action if you call `cloudpickle.dumps(...)` on each of the above tasks -- you'll notice that one of them produces a large output with your entire config file, whereas the other one is very minimal.

**Comment by mhmcdonald** [comment]
Thanks, @cicdw. This makes sense. We will definitely use the `prefect.*` pattern going forward. 

I'll go ahead and close this issue.
