### ISSUE TITLE
Handle Large State Messages

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#1761]
## Current behavior
*Please describe how the feature works today*
https://prefect-community.slack.com/archives/CM28LL405/p1574267406372700
Currently, there's a limit on state message sizes. As the thread above discusses, it would be helpful for us to truncate the messages before they're shipped to Cloud so that the user still receives some utility from the message.

## Proposed behavior
*Please describe your proposed change to the current behavior*
Let's truncate messages so that users can pass larger state message payloads & still receive some utility.

CC @cicdw

**Comment by cicdw** [comment]
Closing as the cap here would need to be on the order of 2-3 million characters which seems like an unnecessary thing to cap - IMO the Cloud error message is informative enough.
