### ISSUE TITLE
incompatible versions of package requirements (of requirements) of prefect[snowflake,aws] 

### ISSUE THREAD

**Issue by lukeorland** [PrefectHQ/prefect#1781]
## Description

`pip install prefect[snowflake,aws]==0.7.3`

yields following the errors.

```
botocore 1.13.28 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
snowflake-connector-python 1.9.1 has requirement boto3<1.10.0,>=1.4.4, but you'll have boto3 1.10.28 which is incompatible.
snowflake-connector-python 1.9.1 has requirement botocore<1.13.0,>=1.5.0, but you'll have botocore 1.13.28 which is incompatible.
```

## Expected Behavior

A version of `python-dateutil` and `botocore` is found that 

## Reproduction

```
pip install pip-tools
echo 'prefect[aws,snowflake]==0.7.3' > requirements.in | pip-compile
```

EDIT:

The output is:

```
...
There are incompatible versions in the resolved dependencies:
  botocore<1.13.0,>=1.5.0 (from snowflake-connector-python==1.9.1->prefect[aws,snowflake]==0.7.3->-r requirements.in (line 1))
  botocore<1.14.0,>=1.13.28 (from boto3==1.10.28->prefect[aws,snowflake]==0.7.3->-r requirements.in (line 1))
```

## Environment

A fresh 3.7.2 virtualenv

## Ideas

Does `prefect[snowflake]` _need_ to pin `snowflake-connector-python` to version `1.9.1`, or can the version range be relaxed? Same question applies to the `boto3==1.10.28` pinned version.

**Comment by lukeorland** [comment]
I think the test suite should have an assertion that `pip install prefect[*]` succeeds.

**Comment by lukeorland** [comment]
I've found that https://github.com/jazzband/pip-tools can be useful for navigating Python dependency hell.

**Comment by lukeorland** [comment]
Strangely, the package ranges defined in `setup.py` work fine:

```
echo -n "snowflake-connector-python>=1.8.2<2.0\nboto3>=1.9<2.0" > requirements.in | pip-compile
```

I'm not sure how the version pinning is happening.

**Comment by lukeorland** [comment]
This works fine too:

```
echo -n "snowflake-connector-python>=1.8.2<2.0\nboto3>=1.9<2.0\nprefect" > requirements.in | pip-compile -U
```

**Comment by cicdw** [comment]
Thanks for the issue @lukeorland ! This might be a controversial opinion, but this is one of the issues with using pip, as it does not do any package dependency resolution whatsoever (and why I personally prefer / recommend using `conda` instead).  

That being said, I'm not sure where the version pin comes from as the requirements you last mentioned appear to match Prefect's `setup.py` perfectly.

I'm usually hesitant to walk down this path too far, as its logical conclusion results in Prefect's requirements specification having to manage all third party dependency graphs which isn't really sustainable, but if we can figure out an easy update that would fix this for you I'm certainly open to it!

**Comment by lauralorenz** [comment]
Closing this, we think this ideally is solved upstream by a user to take into account their specific environment dependencies and leave the Prefect dependencies general so that individual users can fit into them as needed.
