### ISSUE TITLE
Support ellipses in GraphQL DSL

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1788]
Currently, we support GraphQL syntax similar to:

```python
{
  'query': {
    'abc': True
    'xyz': {
        id
    }
  }
}
```

Notice how 'abc' must supply `True` in order to comply with Python syntax. We could consider also making `...` a valid argument, for aesthetic reasons.

```python
{
  'query': {
    'abc': ...
    'xyz': {
        id
    }
  }
}
```

Note these are both equivalent to:

```python
{
  'query': [
    'abc',
    {'xyz': {
        id
    }}
  ]
}
```

**Comment by ashmeet13** [comment]
Hi, I was looking to start with contributing to open source.
Went through Prefect issues and saw this unpicked.

Would it be possible for me to pick this up?
I have gone through the code and I believe this parer would be needed to be updated for the asked support?

https://github.com/PrefectHQ/prefect/blob/e1b2a585c6d11b85090a936655b29f1337ae5548/src/prefect/utilities/graphql.py#L169-L198
