### ISSUE TITLE
Visualizations with mapping is not represented correctly

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#1793]
## Description
Below is a `flow` with `mapping`  The results of the `map` are read into another function `munge_dfs`  That `edge` is not defined in the visualization when using `flow_state` to visualize-- It is represented as some id.  It makes reading the visualization confusing.  And even more so with multiple maps in a flow

![image](https://user-images.githubusercontent.com/16763201/70157305-f3c7cc00-167a-11ea-843e-db75476c7b99.png)

**However** visualizing the flow without running it outputs the expected visualization
![image](https://user-images.githubusercontent.com/16763201/70157690-a009b280-167b-11ea-9d0e-2de32cc959d7.png)

## Reproduction
```
from prefect import Flow, Parameter, Task, task, unmapped
from prefect.tasks.control_flow import ifelse, merge



@task
def sum_list(num_list):
    return sum(num_list)
@task
def add_some_num(x, y):
    return x + y

@task
def multiply_num(x):
    return x*2

@task
def handle_value_error(some_param):
    return some_param

with Flow("map viz") as map_viz:
    input_num = Parameter("input_num", default=5)
    
    multiplied_num = multiply_num(input_num)

    is_ten = multiplied_num.is_equal(10)
    
    # Nums to map if input value equals 10
    numbers = [1, 2, 3]
    
    added_nums = add_some_num.map(
        x = unmapped(input_num),
        y = numbers
    )

    final_num = handle_value_error(input_num)
    ifelse(
        is_ten,
        added_nums,
        final_num
    )
    summed_nums = sum_list(added_nums)
    final_num = merge(summed_nums, final_num)

flow_state = map_viz.run()
map_viz.visualize(flow_state=flow_state)
```

## Environment
*Any additional information about your environment*

**Comment by cicdw** [comment]
Thank you for the very clear and reproducible example!
