### ISSUE TITLE
Deprecated Secrets Page Should Link to the New Page 

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#1798]
## Current behavior
*Please describe how the feature works today*
Currently https://docs.prefect.io/api/unreleased/client/secrets.html#secret explains that this secrets api is deprecated but doesn't link to the new class.

## Proposed behavior
*Please describe your proposed change to the current behavior*
It should link to the new class.

**Comment by dylanbhughes** [comment]
FYI it looks like there _is_ a link but it’s _really_ hard to see. We should bold the text or make the link more distinct in some other way

**Comment by lauralorenz** [comment]
On discussion in backlog grooming we think the warning box and current link is sufficient, so closing this for now!
