### ISSUE TITLE
What is the purpose of the empty "prefect.flows" module?

### ISSUE THREAD

**Issue by pombredanne** [PrefectHQ/prefect#1800]
What is the purpose of the empty "prefect.flows" module?
It is also imported here https://github.com/PrefectHQ/prefect/blob/6f1015957019a86bb86a0504555c354cd8f4af6e/src/prefect/__init__.py#L14

**Comment by joshmeek** [comment]
AFAIK this does not serve any purpose and can be deleted. It was added by @jlowin so maybe he knows if it is needed

**Comment by jlowin** [comment]
Ah, definitely not needed now. Originally this was to contain some composable “mini flows” before we adopted the pattern of using a function to generate tasks (like with ifelse). One day it might hold examples or something but it’s just a vestige now.
