### ISSUE TITLE
Documentation: Dynamic DAGs: Task Looping

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#1833]
Hi - The Dynamic DAGs: Task Looping example is difficult to understand if you are unfamiliar with all the concepts in the example.. Besides the concept of dynamic looping with prefect, two **new** concepts are potentially being introduced to the user.  
-  A task with an API (?)
- Fibonacci numbers (It's been a while)
Perhaps an introductory example with add numbers?

Lastly, A visualization for the `flow` result.
 
![image](https://user-images.githubusercontent.com/16763201/70648384-90a4df00-1c10-11ea-81d4-2e322d87521a.png)

Page reference: https://docs.prefect.io/core/tutorials/task-looping.html

**Comment by joshmeek** [comment]
Hey @gryBox we are currently in the process of refactoring these tutorials (now called "advanced" tutorials). Thanks for making it known that this needs some clearer direction!

**Comment by lauralorenz** [comment]
@gryBox We talked a bit about this and agree that the example for this one is probably best totally changed out from Fibonacci numbers to something else (one idea that was floated was paging through github commit history with the github API, though in practice this runs into rate limiting drama). We can think of a few more but do you have any ideas of some more user-friendly examples we could switch it out to?

**Comment by gryBox** [comment]
@lauralorenz  Maybe something related to the "Episodes" tutorial for the more advanced. (There are both sides of the argument to be made for continuity in the examples).  But for an introduction to the concept -- something really trivial with no packages.  Thinking about this word guessing  [word guessing ](https://www.geeksforgeeks.org/python-program-for-word-guessing-game/) example -- but the letter guessing would be random also.

**Comment by utapyngo** [comment]
> @gryBox We talked a bit about this and agree that the example for this one is probably best totally changed out from Fibonacci numbers to something else (one idea that was floated was paging through github commit history with the github API, though in practice this runs into rate limiting drama). We can think of a few more but do you have any ideas of some more user-friendly examples we could switch it out to?

I would like to see a paging example that runs not only locally but also using the prefect server.
