### ISSUE TITLE
Ability to create sub-graph like networkx library

### ISSUE THREAD

**Issue by kingZthefirst-cypher** [PrefectHQ/prefect#1858]
## Ability to create sub-graph like networkx library
Let's say you have a very big, complex flow. Depending on the parameters, you want to remove some nodes (in this case tasks) from your dag (in this case flow). Ability to do so have several advantages, 1. You will only see logs for the tasks that ran, 2. Makes flow graph much like a networkx graph, etc.

## Solution
Have a method like "remove_task", or something. Also if possible make is seamless to go back and forth between networkx graph and prefect flow.

**Comment by joshmeek** [comment]
Hey @kingZthefirst-cypher updating you to let you know that this feature is similar to something that we internally have been referring to as "sub flows" is currently on the roadmap! Thanks for your request. I have not heard of networkx before and will take a look at the library!

**Comment by lauralorenz** [comment]
Closing this in favor of subflows for now since it sounds like this use case (parameter control of whether some task trees in a graph run or not) will be covered by it. Feel free to let me know if I'm missing some nuance!
