### ISSUE TITLE
[Question] Conda install prefect[viz] with requirements.txt

### ISSUE THREAD

**Issue by ponggung** [PrefectHQ/prefect#1873]
## Description
I am trying to use Conda to install prefect[viz] with requirements.txt in docker environment,
but not works.

Is `pip install prefect[viz]` the only way to install optional dependencies?

## Expected Behavior
Conda install prefect[viz] with requirements.txt

## Reproduction
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/prefect/core/flow.py", line 1067, in visualize
    import graphviz
ModuleNotFoundError: No module named 'graphviz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-perfect.py", line 30, in <module>
    flow.visualize(filename="etl")
  File "/opt/conda/lib/python3.7/site-packages/prefect/core/flow.py", line 1073, in visualize
    raise ImportError(msg)
ImportError: This feature requires graphviz.
Try re-installing prefect with `pip install 'prefect[viz]'
```

after `pip install 'prefect[viz]'`
and it works

## Environment
python 3.7
docker
miniconda3

requirements.txt
`prefect[viz]==0.8.1`

Thanks for your help!

**Comment by cicdw** [comment]
Hi @ponggung - apologies for the delay in response; I don't believe this is currently achievable via the standard `pip` syntax for installing extras, as outlined [in this issue](https://github.com/conda/conda/issues/2984).  

In this particular case, an additional `conda install graphviz` should do the trick.

**Comment by camraynor** [comment]
In case anyone runs into this issue, you have to use `conda install python-graphviz` after `conda install graphviz`
