### ISSUE TITLE
Subflow won't map over a `list` parameter

### ISSUE THREAD

**Issue by JakeTheWise** [PrefectHQ/prefect#1874]
## Description
*A clear description of the bug*
I have a flow that maps a task to a list. Each list item itself is a list. The task runs a subflow that has a task mapped to each element of that nested list _that runs conditionally_. This prevents me from simply flattening the nested list and doing a single map. The subflow receives each nested list as a `pf.Parameter`. The apparent bug is that inside this subflow, the `Task` mapped to the inner list receives the entire inner list instead of just an element, and the `Task` is called `len(list)` times with this argument.

## Expected Behavior
*What did you expect to happen instead?*
I expected my inner map to receive a single element of the nested list.

## Reproduction
*A minimal example that exhibits the behavior.*
```python
import prefect as pf


@pf.task
def process_list_element(element):
    print('ELEMENT:', element)


@pf.task
def run_map_flow(inner_list, nested_flow):
    print('LIST:', inner_list)
    if is_valid(inner_list):
        nested_flow.run(inner_list=inner_list)


@pf.task
def make_nested_list(i):
    nested_list = [list(range(i)) for _ in range(i)]
    print('NESTED LIST: ', nested_list)
    return nested_list


if __name__ == '__main__':

    with pf.Flow('nested_flow') as nested_flow:
        inner_list = pf.Parameter('inner_list')
        process_list_element.map(inner_list)

    with pf.Flow('outer_flow') as outer_flow:
        nested_list = make_nested_list(3)
        run_map_flow.map(nested_list, nested_flow=pf.unmapped(nested_flow))

    nested_flow.run(inner_list=range(10)) # runs as expected
    outer_flow.run() # not what I expected

```

## Environment
python 3.6.8
prefect 0.8.1

**Comment by cicdw** [comment]
Hi @JakeTheWise - Prefect tries to avoid assuming user intent, so will only map over the iterable you provide without changing its contents.  If you'd like to unpack your list into a single list, you can always introduce a task to do that manipulation.

That being said, we've had a few other users desire this behavior off-the-shelf so we might consider implementing a `flatmap` operation which will do both the flattening and the mapping simultaneously.   I'll leave this issue open in case anyone else wants to chime in with support for such an API!

**Comment by JakeTheWise** [comment]
Understood! Unfortunately, flattening won't work in my case because there is some conditional logic on the outer list that determines the execution of the nested list. I'll update my code example to reflect what I mean.

**Comment by JakeTheWise** [comment]
Any update on this?

**Comment by cicdw** [comment]
Hi @JakeTheWise - so it appears that your issue is related more to your use of nested flows in Prefect Core than to mapping.  Prefect Core currently doesn't support the nested flow pattern that you have above.  

However, there are two paths forward.  

1.) Using Prefect Cloud, convert your `run_map_flow` to use a [Prefect Client](https://docs.prefect.io/api/unreleased/client/client.html) to create a new parameterized Flow Run using Cloud's API (see the `create_flow_run` method).  This will prevent any pollution of Prefect Context from having two flows running in the same process (which is ultimately what the issue boils down to).
2.) Combine two flows into a single flow; in this case, the following code will do what you expect:

```python
import prefect as pf

@pf.task
def process_list_element(element):
    print('ELEMENT:', element)


@pf.task
def validate_list(inner_list):
    print('LIST:', inner_list)
    if is_valid(inner_list):
        return inner_list


@pf.task
def make_nested_list(i):
    nested_list = [list(range(i)) for _ in range(i)]
    print('NESTED LIST: ', nested_list)
    return nested_list

@pf.task
def compile_lists(lists):
    return [x for y in lists for x in y]

with pf.Flow("working example") as flow:
    nested_list = make_nested_list(3)
    valid_lists = compile_lists(validate_list.map(nested_list))
    process_list_element.map(valid_lists)

flow.run() # has the expected output
```

**Comment by lauralorenz** [comment]
Closing, there was some offline chatter about this that we think means this issue is resolved, and on top of that, upcoming subflows feature may help make this paradigm a more first class experience.
