### ISSUE TITLE
cloud dashboard cuts off text

### ISSUE THREAD

**Issue by JakeTheWise** [PrefectHQ/prefect#1907]
![Screen Shot 2020-01-10 at 2 41 54 PM (3)](https://user-images.githubusercontent.com/13136287/72185038-713bd600-33b7-11ea-9f35-2cbae32bf140.png)
From Prefect Cloud, when I click on Project > Flow > Details, a drawer pops up from the right with a header called State Message, but the body of State Message seems to be right-justified and cut off on the right side of the page.

**Comment by domarp-j** [comment]
Hi @JakeTheWise - thanks for the heads up! We'll look into it and implement a better-styled fix there.

**Comment by znicholasbrown** [comment]
Hey @JakeTheWise, just wanted to follow up with you that we've patch this problem, let me know if you're still seeing issues!
