### ISSUE TITLE
Flow default result handler persists on incompatible storage option change

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1936]
## Description
If a Flow is initialized then has its storage option changed the default result handler still persists:
```python
@task
def task1():
    return "bad"

with Flow("my-flow") as flow:
    task1()

flow.storage = Docker(...)

flow.register(...)
```

The default result handler of the flow will remain as the `LocalResultHandler` because the default is only populated at initialization https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L165

I'm not 100% sure this is classified as a bug but it is definitely undesirable behavior. There is an incompatibility of the default result handler and this storage option. I think a simple check that would either change or raise a warning will suffice.

## Expected Behavior
I expect the default result handler to be removed since the Local Result Handler will not work with this storage type.

## Reproduction
Register the flow above from the Description section.

## Environment
`0.9.0`

**Comment by zdhughes** [comment]
Happy to take this one on since I found it-- should have it done by end of week.
