### ISSUE TITLE
Add Flow and Task identifying information to LogRecords

### ISSUE THREAD

**Issue by wagoodman** [PrefectHQ/prefect#1938]
## Current behavior
- All log entries have the default [LogRecord attributes](https://docs.python.org/3/library/logging.html#logrecord-objects)... 
- There is no universally identifiable flow slug

## Proposed behavior
...It would be useful to attach Core-specific information to log entries:
- `task_name` & `task_slug`: available only on entries emitted from Tasks and TaskRunners
- `flow_name` & `flow_slug`: available only on entries emitted from Flows and FlowRunners

The addition of the `flow_slug` makes is possible to uniquely identify flows other than by name.

## Example
One can now take a single stream of log entries during a local flow run and separate it by entity without parsing the `LogRecord.msg` field (which is unreliable). This makes is possible to build richer feedback interfaces for filtering, organizing, and otherwise selectively manipulating log entries.

Here is an example CLI interface that would be made possible by theses features:

![local-progress](https://user-images.githubusercontent.com/590471/72913913-dbd00880-3d0b-11ea-8c85-a0e74e1c9551.gif)

(Given the following flow):
```python
from utils import seed, random_data
import prefect

@prefect.task
def extract():
    return seed.get()

@prefect.task
def transform(seed):
    logger = prefect.context.get("logger")
    data = []
    for x in range(10):
        c_data = random_data(seed)
        logger.info("debug info: {}".format(c_data))
        data.append(c_data)
    return data

@prefect.task
def load(data):
    # do something with the data....
    pass

with prefect.Flow("ETL") as flow:
    e = extract()
    t = transform(e)
    load(t)
```

**Comment by wagoodman** [comment]
Here is a concept implementation: https://github.com/PrefectHQ/prefect/commit/b075f14151ec37352cc5bcc7ad104c56af473bdd

... though it has a few drawbacks:
- mypy doesn't like having either a `LoggerAdapter` or a `Logger`
- pulling the logger from within a `Task`s run body leads in a different `Task.slug` bring attached to the resulting LogRecord (if automatically generated) than what is observed by records from a TaskRunner. I have yet to explain this behavior.

**Comment by cicdw** [comment]
I think you might be able to do this much simpler through the use of a Logger Factor + extracting this information from context; we used to do something like this, I'll try to dig up the old code.

**Comment by wagoodman** [comment]
Simpler would be preferable --very interested in any old code dug up. 

I'm using the LogRecordFactory now, however, when I tried to pull this from the global `prefect.context` I wasn't successful. I also worried that if I were to add these values dynamically to context during the run that tasks were concurrently running would be in contention with the same context keys that log entries would be using.

The approach attempted here is to use an adapter as a sort of context: anything logging though these adapters will always append extra information to the proper logs with the supported `extras` field.

**Comment by cicdw** [comment]
@wagoodman here is the record factory we used to have: https://github.com/PrefectHQ/prefect/blob/99f5437ed21425461eb9b1dc58e27f7ac2afc028/src/prefect/utilities/logging.py#L44-L51

> I also worried that if I were to add these values dynamically to context during the run while tasks are running concurrently...

We actually modify context for all runs right now.  Because context is `thread.local` and because of how all our executors work, as long as you modify context within the `initialize_run` method of the relevant runner objects you should be good to go!
