### ISSUE TITLE
PIN: Extension Objects

### ISSUE THREAD

**Issue by wagoodman** [PrefectHQ/prefect#1950]
## Status

Proposed

## Context

Today there are two ways to express Flows: the imperative API and the functional API (see here). In reality there is a single Flow implementation reflected by the imperative API and the functional API leverages the imperative API internally. This is akin to “plumbing” vs “porcelain”  in git, where there are primary underlying git “plumbing” commands implement the core functionality of git and streamlined “porcelain” commands augment functionality by composing multiple plumbing commands together for user ease.

Additionally, Prefect Core is written very intentionally to be a generic workflow engine that can support a wide variety of use cases. By nature, this implies accepting that more specific or streamlined behaviors may not be implemented directly in the imperative API. This is to prevent overloading the API with too much functionality, potentially decreasing the maintainability of the API over time. 

## Proposal

Introducing “extensions” objects, wrappers for Prefect Core objects to add functionality without changing the underlying Flow/Task API. These objects would augment, extend, or otherwise amend functionality of Tasks and Flows.

Here are a few examples:

**1. An automatic CLI for Flow objects**

```python
# app.py
import prefect
from prefect.extensions import FlowCLI
 
with prefect.Flow("example") as flow:
   x = task1()
   y = task2(x=x)
   task3(y=y)
 
cli = FlowCLI(flow=flow)
cli.run()
```

Which attaches a CLI when you invoke `run()`

```shell
$ python app.py --help
Usage: app.py [OPTIONS] COMMAND [ARGS]...
 
  A CLI for the “pipeline” Prefect Flow 
 
Options:
  --help  Show this message and exit.
 
Commands:
  deploy    register and run your flow in Prefect Cloud via Universal Deploy
  register  register your flow with Prefect Cloud
  run       run your flow locally
```

**2. An automatic Flow object, where tasks define dependencies explicitly, and the Flow object is created for the user**

```python
from prefect.extensions import AutoFlow

autoflow = AutoFlow()

@autoflow.task()
def task1():
  print("task 1")

@autoflow.task()
def task2():
  print("task 2")
 
@autoflow.task()
def task3():
  print("task 3")

@autoflow.task(depends=["task1", "task2"])
def task4():
  print("task 4")
 
autoflow.run()
```

**3. An individual task-runner CLI:**

```shell
$ python pipeline.py run --help
Usage: pipeline.py run [OPTIONS] [TASK]...
 
  Run the “pipeline” Prefect Flow
 
Options:
  --help  Show this message and exit.
```

Based on the above flow in #2, execution would allow look like so:
```shell
$ python app.py run task1
# Executes task1 only
 
$ python app.py run task4
# Executes task1, task2, and task4 only
```

**4. Various terminal UIs for flow runs**

These are only examples to illustrate the existence of specific use cases that we traditionally would not pull into Prefect Core. It is important to note that these wrapper objects may not guarantee all of the flexibility of the underlying objects they are wrapping.

This proposal is introducing both the idea of extensions as well as a single place for them to reside. This could happen one of a couple ways:

- Host them directly in core under a new `prefect.extensions` module

- Create a new `PrefectHQ/extensions` repository for hosting extension objects and optionally make them accessible though the Prefect “extras” packages:

```
$ pip install prefect prefect-extensions
# or
$ pip install prefect[extensions]
 
...
 
# app.py
from prefect.extensions import AutoFlow
```

In both cases, the extensions are shared through a Prefect-moderated, centralized source. There is an added advantage of decoupling release planning, reviews, and development cadences if extensions were located in a separate repository. Given this assumption, Core changes that break extensions can be dealt with incrementally by restricting to an upper-bound/lower-bound supported Core versions in the extensions package.

## Consequences

This gives the user additional ways to express, interact with, and manipulate flows and tasks that may not fit within the vision of a prefect.Flow or prefect.Task. In doing so, we are allowing (and fostering!) the introduction of alternative streamlined syntax or specific additional behaviors while allowing the existing underlying Flow API to continue to stabilize.

Furthermore this provides a potential on-ramp for experimental features and behaviors into Core. Optionally, if a particular wrapper object shows usefulness in a general sense and there is a good reason for it to be added to the underlying API then it can graduate into Core.

The ultimate consequence of introducing these objects is to build on top of Prefect Core and safely expand the breadth of offered features in multiple directions.

## Actions

None

**Comment by joshmeek** [comment]
Closing, I don't think this is planned on being worked on
