### ISSUE TITLE
Update Snowflake tasks to not use credentials directly

### ISSUE THREAD

**Issue by lukeorland** [PrefectHQ/prefect#1965]
## Current behavior
Connection credentials must be passed to the `SnowflakeQuery` constructor.

This is a sister issue of #1345 
There was discussion of how to pass credentials into this Task here: https://github.com/PrefectHQ/prefect/pull/1343#pullrequestreview-273443093

## Proposed behavior
The name of a secret could be specified in the constructor.

## Example

I had to implement this in this way:

```
import prefect
from prefect.tasks.snowflake import SnowflakeQuery


class MySnowflakeQuery(SnowflakeQuery):
    def __init__(
        snowflake_credentials_secret='SNOWFLAKE',
        query=None,
        data=None,
        autocommit=None,
        **kwargs,
    ):
        snowflake_credentials = prefect.context.secrets.SNOWFLAKE

        account = snowflake_credentials.pop('account')
        user = snowflake_credentials.pop('user')
        password = snowflake_credentials.pop('password')

        super().__init__(
            account, user, password, **{**snowflake_credentials, **kwargs}
        )
```

**Comment by joshmeek** [comment]
I believe we should do a sweeping change to some of the tasks in the task library to take advantage of the [Secret](https://docs.prefect.io/api/latest/tasks/secrets.html#secret-tasks) task interface as a way of providing a safer, cleaner method of propagating secrets to downstream tasks. 👍

**Comment by kvnkho** [comment]
The [Snowflake](https://docs.prefect.io/api/latest/tasks/snowflake.html) task has since been updated to support this
