### ISSUE TITLE
CLI should be auto-documented with our API

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1971]
Right now our CLI is only documented via manually updated [Cloud concept doc](https://docs.prefect.io/cloud/concepts/cli.html).

We should begin auto-documenting the CLI as a part of the [Core API reference](https://docs.prefect.io/api/latest/) for better visibility and discoverability.

**Comment by wagoodman** [comment]
Lets do this as part of a larger CLI refactor

**Comment by lauralorenz** [comment]
FYI from core team discussion, we do get this for free with Sphinx because there is a `click` plugin for sphinx for CLI auto documentation if we consider moving to Sphinx as part of a larger docs tooling refactor

**Comment by joshmeek** [comment]
The CLI is now [auto documented](https://docs.prefect.io/api/latest/cli/agent.html), closing
