### ISSUE TITLE
Log behavior in vscode debug mode

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#1995]
## Description
 After the second `LOOP` in a task,  the logger stops displaying logs of the running flow in vscode debug mode. And displays the following:
`[2020-02-07 04:34:13,059] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded` , 

Them logging stops but the flow keeps on running with mo logs.  Two things changed on my system since this began happening.  a) I upgraded to 0.9.3 from 0.9.1 and b) registered to the flow to the cloud.

Everything works as expected from the terminal.

## Expected Behavior
 Logs from the flow

**Comment by cicdw** [comment]
Hi @gryBox - what executor are you using for this flow?  Also, are you using `flow.run_agent` to run an agent interactively?

**Comment by gryBox** [comment]
Hi - I am using the `LocalExecutor`.  I am not using an `agent` interactively.  Everything is being run locally.

**Comment by gryBox** [comment]
Hi @joshmeek I'm not seeing this behavior any more and no one else is complaining. So from my point of view this issue can be closed.

Thanks
