### ISSUE TITLE
Mssql Tasks

### ISSUE THREAD

**Issue by rej-jsa** [PrefectHQ/prefect#2021]
## Use Case
Similar to https://github.com/PrefectHQ/prefect/issues/1022 - A task for executing a query against an MSSQL database (and one that executes & returns fetched results).

## Solution
Most likely similar to https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/postgres/postgres.py - using pyodbc.

**Comment by pcieslinski** [comment]
I will create such a task. A very similar task has also been added recently, but allowing the prefect to work with the MySQL database, it should also go quite smoothly. :)

**Comment by lauralorenz** [comment]
Great @pcieslinski ! You might also be interested in the task library contributing guide here for some tips: https://coda.io/@laura-lorenz/contributing-to-the-task-library

**Comment by lonnv** [comment]
I would like to start working on this one.

**Comment by pcieslinski** [comment]
@lonnv Unfortunately, due to lack of time, I didn't create this Task, so I invite you to contribute. :)

**Comment by kvnkho** [comment]
Closing this because there is already a [task here](https://docs.prefect.io/api/latest/tasks/mysql.html)
