### ISSUE TITLE
AuthorizationError when watching logs from CLI

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#2024]
When running with `prefect run cloud --logs`, after a few minutes I see the following error:
```
prefect.utilities.exceptions.AuthorizationError: [{'message': 'AuthenticationError', 'locations': [], 'path': ['flow_run'], 'extensions': {'code': 'UNAUTHENTICATED'}}]
```
The run itself succeeds but the logs stop at that point, so I guess the token is initially valid but just expires...?

cc @joshmeek @cicdw

**Comment by joshmeek** [comment]
Thanks for opening! Will look into the refresh of tokens that are generated via the Personal Access Token 👍
