### ISSUE TITLE
Link to flow run in UI when running from command line

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#2028]
Currently `Flow Run ID: ............-............` prints when you `prefect run cloud`; this is nice since you can copy-paste that flow run ID into the toolbar if you already have a browser open to a different flow run.

What would be even nicer is having a string you can copy-paste directly (or just click depending on your terminal). Personally I don't really mind the copy-paste, but I think having a link to where you can see the results would be helpful for my other team members who are just getting into Prefect. I could probably throw something together but I don't know if relying on `https://cloud.prefect.io/{team}/flow-run/...` staying the same is safe or not.

**Comment by joshmeek** [comment]
This is already on our radar thanks for opening! It's pretty easy to accomplish all that would need to be done for the tenant slug is a query similar to:

```
query {
  user {
    default_membership {
      tenant {
        slug
      }
    }
  }
}
```

**Comment by bnaul** [comment]
Just realized this is a dupe of https://github.com/PrefectHQ/prefect/issues/899 which I also already commented on 😅
