### ISSUE TITLE
Add optional stdout logging for tasks

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2040]
## Current behavior
Currently, `print` statements or any other stdout is not treated in any special way.  This has two consequences:

- users who use `print` statements locally and can see the output are surprised when the output doesn't appear in the Cloud logs
- print statements from third-party libraries that might be useful are not surfaced in cloud execution

## Proposed behavior
We should introduce a new keyword argument on all Tasks `log_stdout` which defaults to `True`.  When `True`, all standard out is converted to a DEBUG level log.  When toggled to `False`, we will not redirect.

This will capture richer information from task runs, but also allow for incredibly simple logging for our less advanced users:

```python
@task
def example():
    print('hi')
    print('this is a test')
    print('of our emergency broadcast system')
```

will result in 3 debug logs.

## Example
This is actually very simple with Python builtins:

```python
import prefect
from contextlib import redirect_stdout

class RedirectToLog:
    def write(self, s):
        # avoids blank newlines
        if s.strip():
            prefect.utilities.logging.prefect_logger.debug(s)

to_debug_log = RedirectToLog()

with redirect_stdout(to_debug_log):
    print('hi')
    print('this is a test')
    print('of our emergency broadcast system')
```

results in :

```
[2020-02-17 00:02:13,642] 4-- DEBUG - prefect | hi
[2020-02-17 00:02:13,642] 4-- DEBUG - prefect | this is a test
[2020-02-17 00:02:13,643] 4-- DEBUG - prefect | of our emergency broadcast system
```

**NOTE:** In our case, we want want to generate the redirect class on the fly so that it uses the task run specific logger in each case.

**Comment by wagoodman** [comment]
I like where this is going, I think there should be discussion on a few points:
- Would we want this to be opt-in or opt-out behavior?
- Given that prefect is a lib, having global side-effects on stdout may be undesirable/unexpected. The docs also [call this out explicitly](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout). (Notable enough to discuss and acknowledge in advance.)
- Are we interested in also capturing stderr (perhaps under the ERROR logging level)?
- This [will not capture stdout from lower-level calls](https://bugs.python.org/issue24500) (e.g. prints from C extensions), is this something that we're interested in capturing?

**Comment by cicdw** [comment]
- as mentioned in the description, I vote opt-in because one of the main purposes would be ease of use and so far I've found that users have expected this already
- Hm I don't think our usage would fully classify as a global side effect, especially since we are acting as a manager of the task run; however, the callout about use in threaded applications is a little iffy - I agree this warrants further investigation / discussion
- this would cause weird recursive issues with logging that I'd rather avoid (since most logs go to stderr)
- that's fine, most of the output we want to capture is basic print statements
