### ISSUE TITLE
Expose more information about execution environment on the Cloud UI

### ISSUE THREAD

**Issue by joshjohnlowe** [PrefectHQ/prefect#2045]
## Use Case
At the moment with the way we're setting up our test / production environments, the AWS IAM roles required can get a bit messy and confusing. Basically - we're moving away from one account per environment, to having both test and prod live on our production account.

## Solution
*Please describe your ideal solution*
As part of the 'details' or 'overview' section of a flow, the ability to see any IAM oles attached!

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Even the ability to expose this information via the interactive API would be welcomed!

**Comment by joshmeek** [comment]
Closing this in favor of #2111 because they are related (and I already commented on the other issue 😄)
