### ISSUE TITLE
Logging from Flow does not get suppressed by changing default log level

### ISSUE THREAD

**Issue by mxlei01** [PrefectHQ/prefect#2049]
I'm running a mapping stage in a Flow, and there's a few hundred items, this will cause Flow to output a large amount of text in a jupyter notebook.

Setting:
```
os.environ['PREFECT__LOGGING__LEVEL'] = "ERROR"
prefect.config.logging.level = "ERROR"
```
Does not seem to suppress this behavior?

**Comment by jlowin** [comment]
Hi @mxlei01 - Prefect's loggers are configured on import, so you'll need to ensure the environment variable is set before you import prefect.

You can either export the environment variable prior to starting python, or set the variable explicitly prior to importing Prefect:

```python
import os
os.environ['PREFECT__LOGGING__LEVEL'] = "ERROR"

import prefect
prefect.utilities.logging.get_logger("test").info("Hello!") # no print!
```

**Comment by mxlei01** [comment]
@jlowin Thanks, setting the environmental variable first works.
