### ISSUE TITLE
Add system version logic to setup.py for 3.5 requirements

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#2073]
**Background**: Currently there is a discrepancy between msgpack and distributed where older versions of distributed have msgpack as an unbounded dependency. Meaning it would install the recently release 1.0.0 on incompatible versions. Attempting to alleviate this causes issues in our 3.5 builds because distributed no longer supports 3.5 and it installs msgpack 1.0.0 and distributed 2.6.0 (the last version prior to dropping 3.5 support).

**Comment by cicdw** [comment]
@joshmeek can you confirm that this is what we want:
- lower bound on msgpack >= 0.6.2
- upper bound of < 1.0 on msgpack _only_ when installing with Python 3.5

**Comment by joshmeek** [comment]
Collected my thoughts: we want msgpack < 1.0.0 _only_ when installing distributed < 2.11.0 (which is always the case with Python 3.5). Distributed now pins msgpack to `~=0.6.2`

**Comment by cicdw** [comment]
Interesting; I don't think I'll be able to infer what version of distributed a user has (or will have) but I can add the upper bound with Python 3.5.  I consider the case when users are on old versions of distributed to be between them and distributed and we don't need to get involved.

**Comment by joshmeek** [comment]
@cicdw Okay great yeah the upper bound for 3.5 would be enough! Maybe with [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers)
