### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2075]
Dask (and Dask Distributed) are core dependencies of Prefect and [have dropped Python 3.5](https://github.com/dask/dask/issues/5478) support.  This means that all Prefect users are effectively stuck on old versions of dask with Prefect.

Given that, and given the occasional frustration of supporting Python 3.5 (typing, dict ordering, etc.) I'd like to open up a discussion for whether we should continue supporting 3.5 or not.  To be clear, if users are not using dask executors or hooks, then they might not care.

If you are a user who requires 3.5 support please chime in here so we can assess this decision!

**Comment by joeschmid** [comment]
+1  We're in favor of dropping 3.5 support.

**Comment by joshmeek** [comment]
Update on this: what I would like to do is after the next minor release we remove "support" for Python 3.5 by taking out the CircleCI job that runs tests on 3.5 and add a deprecation warning on import. The for the minor release after we update the serializers to use a > 3.5 library such as [pydantic](https://pydantic-docs.helpmanual.io/) and officially remove compatibility.
