### ISSUE TITLE
Pipeline refactor proposal: remove intermittent `FAILED` state prior to `RETRYING`

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2084]
## Current behavior
*Please describe how the feature works today*

When a retry-able task encounters an error, it enters a `FAILED` state. A later step of the state pipeline investigates the `FAILED` state to see if the task should be placed in a `RETRYING` state, and updates the new state if so. 

## Proposed behavior
*Please describe your proposed change to the current behavior*

When a retry-able task encounters an error, it transitions directly to a `RETRYING` state (if applicable), and only enters a `FAILED` state when all allowed retries have been attempted.

## Rationale
*Please give an example of how the enhancement would be useful*

By entering a `FAILED` state prior to retrying, there is a brief window under ideal conditions where concurrent executions of the same flow could pull erroneous state information. If conditions are not ideal - for example, bad network connectivity allows the `FAILED` state to be serialized but not the `RETRYING`, or the node crashes after the `FAILED` update but prior to the `RETRYING` one - then the error will persist.

Historically, we entered the `FAILED` state as a matter of convenience, to facilitate the `RETRYING` check as a separate pipeline step. In order to ensure the retry check only ran when it was supposed to, we had to differentiate between a run that succeeded and a run that failed prior to checking for retries.

Over time, the "run" step of the pipeline (`TaskRunner.get_task_run_state()`) has become more complicated, and now directly handles a variety of `RUNNING` state transitions: 
- `SUCCESS` (via implicit lack of error)
- `FAILED` (via try/except capture)
- `LOOP` (via explicit trap)
- `CANCELLED` (via explicit trap)
- `TIMEDOUT` (via explicit trap)

The only transition NOT currently handled by this method is `RETRYING`, which must first go through the `FAILED` transition.

**Comment by NicolasCamenischQC** [comment]
Any progress on this? According to the documentation (second paragraph of [State types](https://docs.prefect.io/core/concepts/states.html#state-types)), a task that enters a `Finished` state never is rerun:

> At each stage of the execution pipeline, the current state determines what actions are taken. For example, if you attempt to run a task in a Success state it will exit the pipeline, because Finished states are never re-run.

But this isn't the case because with the current behaviour (`Running -> Failed -> Retrying`), tasks can be rerun even if they have entered a `Finished` state (`Failed` is a subclass of `Finished`).
