### ISSUE TITLE
Add Prefect SchedulerPlugin to Dask Kubernetes Environment

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2096]
We should add a custom Dask `SchedulerPlugin` to our Dask Kubernetes environment (see the relevant Dask docs here: https://distributed.dask.org/en/latest/plugins.html).  This plugin could log relevant events to the flow run:

- worker evictions
- worker additions
- scheduler restarts

Ideally we could do something similar for static dask clusters as well, but because multiple flows / non-prefect things can be running it's not as clear how to do that in a targeted / non-disruptive way.

**Comment by cicdw** [comment]
https://github.com/PrefectHQ/prefect/pull/2089 addresses most of these issues; however, I think we should still leave this issue open as a means to explore more first-class Dask integrations / hooks.

**Comment by lauralorenz** [comment]
There was some discussion by core team that this may be better suited not as a plugin but as part of the DaskExecutor. Food for thought :)

**Comment by joshmeek** [comment]
Now that the executor / dask cluster type can be set on the RunConfig is this still an open issue?
