### ISSUE TITLE
Expose safe opt-in option for serializable environment information

### ISSUE THREAD

**Issue by maikelpenz** [PrefectHQ/prefect#2111]
## Current behavior
Currently I cannot identify what memory and cpu configuration has been set to a Flow. 

## Proposed behavior
Under the "Environment" section of the Flow Overview besides the Type we can also see configured memory and cpu information.

## Example
Environment
Type > FargateTaskEnvironment
Memory > 8192
Cpu > 2048

**Comment by joshmeek** [comment]
I like this enhancement but the one thing I want to be cautious on is which information gets sent. There are subsets of information from environments (such as creds) that we do not want. 😄On that note I think that this functionality should be an opt-in addition where you may choose which aspects of the environment you want visible from Cloud. As the current environment landscape progresses it should be straightforward enough to reject specific information from being sent such as credentials.

We could serialize this as a generic `info` JSON blob in the environment serializers by using something like

```python
info = fields.Dict(key=fields.Str(), values=JSONCompatible(), allow_none=True)
```

**Comment by joshmeek** [comment]
After `0.12.0` is released the environment `metadata` field seems like a good place to elevate this information. cc @zhen0 for if this is something the UI would be willing to add in the near future

**Comment by zhen0** [comment]
This looks like info we could include in the flow details tile. Cloud UI ticket created in Cloud-web-ui #1624

**Comment by joshmeek** [comment]
Thanks @zhen0!

**Comment by joshmeek** [comment]
Closing as the `metadata` field on environments handles the core side of this 🙂
