### ISSUE TITLE
Add flow run information to Slack notification

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#2112]
The built-in [Slack notifier](https://docs.prefect.io/core/advanced_tutorials/slack-notifications.html#slack-notifications) is neat but doesn't convey quite enough information to be useful, especially in a "production" context where many users might be running flows simultaneously.

Including information about the specific flow *run* (for example, the run name or a link to the flow run in the Cloud UI) would go a long way towards making the notification more informative+actionable. It might also be nice to be able to pass some sort of formatter function to `slack_notifier` that could customize the message at run-time based on information about the task/flow, some variables in the context, things like that.

cc @cicdw who it sounds like thinks this would be pretty easy 😁

**Comment by joshmeek** [comment]
Full support for this customizability! We have a good amount of information available to us in context that the notifier could use and for the Cloud UI URL portion we already do something similar in the CLI when creating a run and it should be pretty straightforward to adopt here:

https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/cli/run.py#L171-L182
