### ISSUE TITLE
MySQL tasks

### ISSUE THREAD

**Issue by lauralorenz** [PrefectHQ/prefect#2124]
## Use Case
Users who are working with data in MySQL databases may want to add steps in their flows that execute queries or return results from a MySQL connection.

## Solution
A task or set of tasks that can configure a python client to MySQL and execute (and/or fetch) queries. This should be similar to the implementation of https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/postgres/postgres.py but using 
[mysqlclient](https://pypi.org/project/mysqlclient/) or [mysql-connector-python](https://pypi.org/project/mysql-connector-python/) (see [a debate about that on stackoverflow here](https://stackoverflow.com/questions/43102442/whats-the-difference-between-mysqldb-mysqlclient-and-mysql-connector-python)). The client should only be installed as an [extra, like psycopg is](https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/setup.py#L51).

## Alternatives
At some point as the collection of DB access tasks grows, we may consider abstracting them given their clients should all be following [PEP 249](https://www.python.org/dev/peps/pep-0249/).

**Comment by manesioz** [comment]
Hey, I opened up a WIP PR for this :) I'll try to wrap it up as soon as possible and ask for a review

**Comment by lauralorenz** [comment]
@manesioz awesome, thanks! Will be on the lookout :)

**Comment by manesioz** [comment]
Should this be closed now? :)

**Comment by joshmeek** [comment]
Not Laura but 👍

**Comment by lauralorenz** [comment]
Thanks @manesioz and @joshmeek ! Yay! :)
