### ISSUE TITLE
Prefect Cloud schedule display

### ISSUE THREAD

**Issue by maikelpenz** [PrefectHQ/prefect#2132]
## Current behavior
When a schedule is set to a flow a grey section shows up on the flow overview saying "CUSTOM SCHEDULE".

## Proposed behavior
It would be helpful to see the actual schedule.
In addition (nice to have) the next _n_ executions to happen (similar to what AWS Cloudwatch shows).

## Example

![image](https://user-images.githubusercontent.com/33239635/76179274-34595780-621f-11ea-903c-728d5003e1ae.png)

**Comment by znicholasbrown** [comment]
Hi @maikelpenz, this is a great suggestion and something we want to do very soon. I'll update this issue as soon as it goes live!
