### ISSUE TITLE
`manual_only`-trigger does lead to caching of upstream inputs

### ISSUE THREAD

**Issue by mbrner** [PrefectHQ/prefect#2137]
## Description
I tried to setup a flow with a 'manual_only' trigger. While failing to do so, I went trough the code trying to understand the logic behind the triggers. As shown in the example no inputs are cached despite running a task with a 'manual_only' trigger. 'cached_input' is set in [cache_result(..)](https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/engine/task_runner.py#L291) in the 'run' function of the task_runner
https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/engine/task_runner.py#L949
But 'cache_result' is never reached for unforfilled triggers, because in the [check_trigger function](https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/engine/task_runner.py#L441) a PrefectStateSignal is raised which is excepted and "transformed" to an ENDRUN exception:
https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/engine/task_runner.py#L454.

## Expected Behavior
A comment in the run functions states ["triggers can raise Pauses, which require task_inputs to be available for caching"](https://github.com/PrefectHQ/prefect/blob/b49db66c23132dea9471663026ada21e80b1b2dc/src/prefect/engine/task_runner.py#L278). As expected the inputs are collected in all cases. In cases of failed execution and raised Pauses the inputs should be added to the state's cached_inputs.

## Reproduction
```
import uuid

from prefect.engine import FlowRunner
from prefect.triggers import manual_only
from prefect import task, Flow


@task(name="Task A")
def task_a():
    return str(uuid.uuid1())

@task(name="Task B", trigger=manual_only)
def task_b(name):
    pass 

with Flow("Trigger example") as flow:
    task_b(task_a())

state = flow.run(run_on_schedule=False)
print(state.cached_inputs)
```

## Environment
{
  "config_overrides": {
    "logging": {
      "level": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid",
    "prefect_version": "0.9.7",
    "python_version": "3.7.5"
  }
}

**Comment by cicdw** [comment]
Hi @mbrner - you appear to be checking the Flow's final state, when you should be checking for `task_b`'s final state (which can be accessed as a value of the `result` attribute of the Flow's state).  Here is a slight change to your code that should print what you expect:

```python
with Flow("Trigger example") as flow:
    b = task_b(task_a())

state = flow.run(run_on_schedule=False)

print(state.result[b].cached_inputs)

# {'name': <Result: '68e15eba-6260-11ea-a4ae-8c85904fce81'>}
```
