### ISSUE TITLE
PIN 16: Implement `Result` subtype mimicking `ConstantResultHandler`

### ISSUE THREAD

**Issue by lauralorenz** [PrefectHQ/prefect#2145]
## Use Case
See PIN 16 (PR #2134) for background. This is a spin-off from #2141 for only one (special) handler, `ConstantResultHandler`, which has internal implications.

## Solution
Implement a `Result` subclass for `ConstantResultHandler` that knows how to `.read`, `write`, and check if it `.exists` and operates properly for the same internal purposes as the current `ConstantResultHandler` does.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by lauralorenz** [comment]
Not sure why I can't tag @alexisprince1994 as assigned to this issue (as they opened a PR); assigning to myself for now just so it's not confusing on the board.

**Comment by joshmeek** [comment]
@lauralorenz Hmm we must only be able to assign those in the Prefect org 🤔
