### ISSUE TITLE
Fix Schedules API documentation

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2153]
Currently, in our auto-generated Schedules API docs we see:
![image](https://user-images.githubusercontent.com/13255838/76579160-6a4d4480-6488-11ea-99b5-3af83025e892.png)

There are two things wrong with this:

- the formatting of the list looks bad
- the actual code is incorrect and therefore doesn't run

Note that this documentation comes directly from the following lines of code (which is the docstring for the base `Schedule` class): https://github.com/PrefectHQ/prefect/blob/master/src/prefect/schedules/schedules.py#L15-L37

To fix this, we'll need to do a few things:

### Fix the list formatting

To fix the list formatting, I recommend we remove the numbered items entirely and instead replace them with a more narrative style.  For example, "First, candidate events are..." "Next, ..." etc.

### Fix the code

To fix this code, we need to:

- include all the relevant imports in the example code block
- convert `IntervalSchedule` -> `IntervalClock`
- replace `time_between` with `filters.between_times`
- replace `Time` with `datetime.time`

**Comment by kmoonwright** [comment]
PR requested! The branch is doc_revisions.

**Comment by cicdw** [comment]
Closed via #2164
