### ISSUE TITLE
Having trouble using DatesClock...

### ISSUE THREAD

**Issue by kmoonwright** [PrefectHQ/prefect#2176]
```python
import datetime
from prefect import task, Flow
from prefect.schedules import clocks, Schedule

# Date Clock
clock = clocks.DatesClock(
    dates=[datetime.datetime.now()]
) 

schedule = Schedule(clocks=[clock])

flow = Flow("Hello", schedule=schedule)

flow.run()
```

When I run this code, I get the following error:
```
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by joshmeek** [comment]
Try using something that is timezone aware like:
```
import pendulum
pendulum.now()
```
or
```
import datetime
import pytz
datetime.datetime.now().replace(tzinfo=pytz.utc)
```

**Comment by cicdw** [comment]
@joshmeek I think we should either (I view these as mutually exclusive):
- fix the comparison operator in `flow.run` to not throw an error
- auto-convert `datetime` objects to timezone aware `pendulum` objects (this might be risky)
- improve our docs for clocks to specify when / why to use `datetime` vs `pendulum`

**Comment by jlowin** [comment]
@joshmeek @cicdw pendulum has a helper for this that assumes UTC unless specified:

```
pendulum.instance(datetime.datetime(2020, 3, 31))
# DateTime(2020, 3, 31, 0, 0, 0, tzinfo=Timezone('UTC'))
```
