### ISSUE TITLE
Custom Executor

### ISSUE THREAD

**Issue by kforti** [PrefectHQ/prefect#2182]
## Current behavior
*Please describe how the feature works today*
Executors are provided within Prefect core, and the documentation implies that it is possible to build a custom executor.

## Proposed behavior
*Please describe your proposed change to the current behavior*
I would really like some information about how to build a custom distributed executor. There is an abstract base executor class with the methods required. However, it is unclear how Prefect expects those methods to work. In particular, it seems that the executor is submitted to the worker along with the task, I believe that the DaskExecutor's map method submits the executor to the worker node in order to submit the mapped tasks to the scheduler. This is what I am trying to avoid. I would like my executor to be centralized.

Also, I would like to allow my executor to respond to external events and possibly update the flow while it is running. For this, it would be nice to know what Prefect expects with the map method. In this method, you are creating tasks on the fly- can this be done more generally? For example, can I add tasks to an already running flow in my executor? Maybe my executor checks a queue for new tasks and updates the flow between task submissions.

## Example
*Please give an example of how the enhancement would be useful*
I would like to build an executor that can contain logic about where to send tasks. The dask client will submit tasks to whatever worker has available threads, which means one worker could get the first ten tasks if each worker has 10 threads. I understand that there are ways of doing this when building the flow, but I want to determine which workers to send tasks to when that task is actually going to run.

Also, the right worker may not be available, in which case the executor could communicate with the scheduler, or underlying scheduling system, to ensure the right worker for the job is available before submitting the task.

**Comment by joshmeek** [comment]
Going to switch this to a documentation ticket because we should have some conceptual documentation on how this can be achieved. The closest thing right now is the README at https://github.com/PrefectHQ/prefect/tree/master/src/prefect/engine/executors

**Comment by ahirner** [comment]
Thanks for the pointer already @joshmeek.
Right now, `submit` and `wait` behaviour is defined by dask's implementation. By default, dask [traverses python collections](https://github.com/dask/dask/blob/master/dask/base.py#L392), even dataclasses. If I may, I'd propose to statically type the possible argument shapes. This would be very helpful for writing custom executors.
