### ISSUE TITLE
Question: Passing task output between runs

### ISSUE THREAD

**Issue by niviksha** [PrefectHQ/prefect#2186]
I have a flow where there's input conditioned on previous runs. That is, I want to cache the result of the task somewhere, and the _next_ scheduled run of the flow, I want to use that result as an input to the **same** task. i.e the first time around, it is a None input, but the subsequent times, I want this input to be the previous result of the same task

I've looked all around at the docs on State, Result Handlers and caching, but not quite sure how this can be done (can it?). With result handlers, let's say I use a LocalResultHandler, how do I know which result is the most recent previous one?

**Comment by joshmeek** [comment]
Conversation happen in slack thread #2187
