### ISSUE TITLE
S3ResultHandler fails during Cloud Flow Run

### ISSUE THREAD

**Issue by joeschmid** [PrefectHQ/prefect#2204]
## Description
Running on `0.9.8` we've observed the S3ResultHandler failing with `AttributeError: 'S3ResultHandler' object has no attribute '_client'`. This was also reported by another user in the Prefect Community Slack. (See thread: https://prefect-community.slack.com/archives/CL09KU1K7/p1584980231422300)

For now we are working around this by disabling checkpointing in all of our tasks, but this will obviously prevent tasks from being able to retry, etc.

## Expected Behavior
S3ResultHandler should correctly checkpoint tasks to store outputs in an S3 bucket.

## Reproduction
The following is a stub Flow that recreates the issue:

```
import prefect
from prefect import Flow
from prefect.tasks.shell import ShellTask
from prefect.environments.storage import S3
from prefect.engine.result_handlers import S3ResultHandler

env = <an environment, we use our own secure Dask environment for TLS by extending RemoteEnvironment>

BUCKET = "<redacted>"
s3_storage = S3(bucket=BUCKET)
rh = S3ResultHandler(BUCKET)

shell_task = ShellTask(name="shell", return_all=True)

with Flow("RecreateS3ResultHandlerIssue", environment=env, storage=s3_storage, result_handler=rh) as flow:
    final_cmd = ["ls","cd;ls"]
    embulk_results = shelltask.map(command=final_cmd)

s3_storage.build()
flow.register(project_name="Test Project 1")

# Now run Flow from Cloud either via UI or API
```

The Flow run will fail with this full stack trace:

```
Unexpected error: AttributeError("'S3ResultHandler' object has no attribute '_client'")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 925, in get_task_run_state
    state._result.store_safe_value()
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/result.py", line 121, in store_safe_value
    value = self.result_handler.write(self.value)
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/result_handlers/s3_result_handler.py", line 112, in write
    self.client.upload_fileobj(stream, Bucket=self.bucket, Key=uri)
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/result_handlers/s3_result_handler.py", line 77, in client
    return self._client
AttributeError: 'S3ResultHandler' object has no attribute '_client'
```

## Environment
We use a long-running Dask cluster on k8s via AWS EKS.

(Hat tip to @JLouSRM for identifying this issue.)

**Comment by lauralorenz** [comment]
Hi! I will take a look to reproduce this evening, I changed the S3ResultHandler in 0.9.8 re: trying to thread safe the boto3 client, so I'm the one who probably broke it.

**Comment by joshmeek** [comment]
Looking at it I think there's a chance the `client` property is retrieved without `self._client` being set prior. https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/result_handlers/s3_result_handler.py#L77

Possibly defining `self._client = None` in the `__init__` would do the trick
