### ISSUE TITLE
What are the OS dependencies required for a Docker base_image?

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#2212]
## Description
When specifying a `base_image` on Docker storage, if that image does not have `prefect` installed, it will print this warning:
```bash
Step 3/9 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.9.8#egg=prefect[kubernetes]
 ---> Running in 1ad6b43dbc24
WARNING: Package(s) not found: prefect
```

However, if the base image did not have `git` installed, this will fail. Assuming the base image does have `git` installed, it could still fail if it doesn't have `build-essential` or the header files installed to compile from source.
```bash
  /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
```

## Expected Behavior
Since Prefect is building a new Docker image, it'd be great if it could check for the `git` and `build-essential` dependencies before attempting to perform the `pip show prefect || pip install` layer. That one line could be changed to:
```bash
RUN apt-get update -yqq && apt-get install -yqq git build-essential && pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.9.8#egg=prefect[kubernetes] && apt-get purge --auto-remove -yqq git build-essential && apt-get autoremove -yqq --purge && apt-get clean && rm -rf /var/lib/apt/lists/* /usr/share/man
```

Although that could potentially remove `git` and `build-essential` if they were installed on the base image already, which gets complicated...

Really, it'd be great if we could document what must be in a `base_image` in order for a  Prefect Flow to consume it successfully:
https://docs.prefect.io/orchestration/recipes/configuring_storage.html#building-a-custom-base-image

In my testing, this seems to just be `prefect` python package OR `git` and `build-essential` from apt. But I don't know if there are others I missed.

## Reproduction
Specify `python:3.7.6` as the `base_image`, or any other Docker image that doesn't have `prefect`, `git`, or `build-essential` installed.

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-19.3.0-x86_64-i386-64bit",
    "prefect_version": "0.9.8",
    "python_version": "3.7.6"
  }
}
```

**Comment by szelenka** [comment]
Even when it would install prefect, it seemed to miss installing `gcloud`. I had a Flow run overnight, only to find out it failed because of a missing package:
```bash
March 29th 2020 at 5:03:11pm | prefect.GCSResultHandler
DEBUG 
Starting to upload result to 2020/3/29/ac850f1d-e0f6-4d6b-8c01-1ff2ae8e37a3.prefect_result...
March 29th 2020 at 5:03:11pm | prefect.CloudTaskRunner
ERROR 
Unexpected error: ModuleNotFoundError("No module named 'google.cloud'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 925, in get_task_run_state
    state._result.store_safe_value()
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result.py", line 121, in store_safe_value
    value = self.result_handler.write(self.value)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result_handlers/gcs_result_handler.py", line 84, in write
    self.gcs_bucket.blob(uri).upload_from_string(binary_data)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result_handlers/gcs_result_handler.py", line 53, in gcs_bucket
    self.initialize_client()
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result_handlers/gcs_result_handler.py", line 41, in initialize_client
    from prefect.utilities.gcp import get_storage_client
  File "/usr/local/lib/python3.7/site-packages/prefect/utilities/gcp.py", line 4, in <module>
    from google.cloud import bigquery, storage
ModuleNotFoundError: No module named 'google.cloud'
```

I guess I should start my `base_image` from the official prefect package, lesson learned.

**Comment by joshmeek** [comment]
Hey @szelenka yeah we can update the documentation to better specify which packages/libraries are needed if not using a base prefect image. 

For your `google.cloud` issue you could specify that library in the `python_dependencies` however I think there's a better enhancement to be had here. At build time we could look at the flow and if it's using any of the cloud-based result handlers (S3, GCS, etc...) tell the build step to install prefect with those dependencies (e.g. `prefect[aws]` or `prefect[gcp]`)
