### ISSUE TITLE
Running prefect without Docker ?

### ISSUE THREAD

**Issue by t3ndai** [PrefectHQ/prefect#2236]
Is there a way to run prefect, without docker ? like just straight via the CLI ? 

have a way to run prefect via cli without dealing with docker, docker-compose 

useful in terms of running up quick

**Comment by cicdw** [comment]
Hi @t3ndai there are ways of running the full stack without docker (see https://github.com/PrefectHQ/prefect/tree/master/server#development for some hints at how), but it is not easier or faster, in fact it's _much_ more difficult to do.

Running the full stack without docker requires setting up a database, setting up hasura, understanding how to create appropriate `npm` environments and creating a functioning Python 3.7 environment for the GraphQL layer.  All of these services need the ability to talk to each other as well, which is non-trivial to configure.

For running Flows without Docker I suggest using Core with or without [Prefect Cloud](https://cloud.prefect.io/) which manages these details for you.

**Comment by t3ndai** [comment]
@cicdw Thanks for the response. I ran a Core Flow using Dask. I understand, that Prefect sells the Cloud, product. I also think cases of running Core without signing up for Cloud should be thoroughly documented. this will definitely help in adoption of product, since it's a good product for task management. Eg for fast running tasks, that most people would've used Celery for etc or fast etl tasks, Prefect is well suited for this. And just being able to run core without ceremony, would be welcome.

**Comment by cicdw** [comment]
Hey @t3ndai for sure!  Note that you don't need any of the server backend to run your workflows.  Ultimately, once you've built your flow you can call `flow.run()` to run a flow on its schedule, or `flow.run(run_on_schedule=False)` for a one-off flow run.  All of this can be done without the new open source backend, and historically is how most users run their flows when not running on Prefect Cloud.
