### ISSUE TITLE
Allow kwargs to boto3 in S3ResultHandler

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#2240]
## Current behavior
`initialize_client` leverages the default parameters to make a connection to AWS S3 service. 

This prevents `boto3` from connecting to other S3 Compatible Object Stores (i.e. MinIO), because it's impossible for them to change the `endpoint_url` parameter to `boto3`

## Proposed behavior
Allow optional boto3 kwargs to be passed into `S3ResultHandler`, such that if present, will be used during the initialize_client method.

If not present, the same functionality will connect to AWS S3.

## Example
S3ResultHandler(..., boto3_kwargs={'endpoint_url': 'https://my-minio.local/'})

**Comment by joshmeek** [comment]
Closed in #2241
