### ISSUE TITLE
When Marvin archives an issue from the public Slack, add a link to the original conversation

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2245]
## Current behavior
*Please describe how the feature works today*
Marvin can archive Slack conversations as issues for public consumption, but there's no way to jump back to the original conversation, which means any further exchanges are lost.

## Proposed behavior
*Please describe your proposed change to the current behavior*
Add a link to the GitHub issue that opens the original conversation in Slack

**Comment by cicdw** [comment]
Closed - will manually test once it's live
