### ISSUE TITLE
Enforce input validation on Parameter Tasks and add descriptions

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#2254]
## Current behavior
`Parameters` are pretty simple entities that look for a key and take whatever value is presented at that key, to then forward off to the Tasks that consume it.

This makes troubleshooting invalid values passed into Parameters tricky, as the failure will happen at the downstream Task(s), rather than the Parameter. Which is essentially wasting compute time, because if the Parameter was bad, there's no chance the downstream tasks can succeed.

But to enforce input validation, we'd need to also have some basic documentation/description of what the provided `Parameter` is.

## Proposed behavior
[starlette](https://www.starlette.io/) has a slick wrapper for the way it handles [environment configuration](https://www.starlette.io/config/), where you can specify a `cast` type. The code for this is [pretty small](https://github.com/encode/starlette/blob/master/starlette/config.py).

Taking that a step further, I've gotten spoiled by the way [FastAPI](https://fastapi.tiangolo.com/) leverages the [pydantic](https://pydantic-docs.helpmanual.io/) library by using python type annotations to handle input validation of input parameters to endpoints, and think this would be a great feature to extend into the way Prefect takes in `Parameters`.

Where you'd be able to **optionally** specify an object type for the Parameter, and if set, when the Parameter Task is ran, it would perform basic datatype validation on what was passed in. If someone passed a datatype other than what that Parameter was expecting, it'd fail at that step before trying to run any downstream Tasks that consume the Parameter.

## Example
During `Parameter` initialization, it can evaluate the value passed into the Parameter and fail at that point if it is not the expected input type.
```python
with Flow("example") as flow:
    # basic types
    int_param = Parameter("int_param", default=100, cast=int, description="how many to pull")
    str_param = Parameter("str_param", default="string", cast=str, description="a string to search")
    
    # class types
    from enum import Enum
    
    
    class StrictValues(str, Enum):
        VALUE = 'one'
        EXAMPLE = 'two'
    
    enum_param = Parameter("enum_param", default=StrictValues.VALUE, cast=StrictValues, description="which value do you want?")
    ...
```

Or we could go all in with overloading pydantic.BaseModel to have a single validators (but this would break backwards compatibility):
```python
class MyCustomParameters(pydantic.BaseModel):
    int_param: int = pydantic.Field(
        default=100,
        description='how many to pull'
    )
    str_param: str = pydantic.Field(
        default="string",
        description='how many to pull'
    )
    enum_param: StrictValues = pydantic.Field(
        default=StrictValues.VALUE,
        description='which value do you want?'
    )

with Flow(
    name="example",
    parameters=MyCustomParameters
) as flow:
    ...
```

pydantic raises a specific exception with details on what input validation failed, which can aid in troubleshooting bad input parameters to the Parameter Tasks.

**Comment by jlowin** [comment]
I think this is a cool idea and want to tie it in to #733, which has an almost-complete WIP PR. 

We LOVE Pydantic, and in fact if you look at the server code you'll see it forms the basis of a lot of validation in server / Cloud. Unfortunately it is 3.6+, so until we formally drop 3.5 support (which I *think* is happening in either 0.11 or 0.12) we can't adopt it. But when we do  - full steam ahead.

**Comment by cicdw** [comment]
Two cents:
- 3.5 has been dropped with 0.10.0 
- validating output types across the board (parameters + arbitrary tasks) should become a first class API with the [PIN 16 work](https://docs.prefect.io/core/PINs/PIN-16-Results-and-Targets.html)

**Comment by szelenka** [comment]
output validation could make sense for Parameters, where it's asserting to be of a certain datatype by its completion.

For #733 can we add a blurb for adding optional `descriptions` to each Parameter? If so, I think the intent of this enhancement request could be satisfied in there or PIN 16.

With documentation of each Parameter, the Flows could be easier for others to read and gain an understanding of what value they should populate in them. Long term, those descriptions could bubble up to the UI where a simply HTML Form could give a user options and description of what to enter when triggering a Flow manually.

My immediate use case is a basic Enum, where only specific values are permitted; as well as a custom JSON object where we want to validate the structure of the object at input time. pydantic does this wonderfully, and it's easy for people to read. FastAPI has a wrapper around pydantic where it'll even produce the OpenAPI documentation for expected values of pydantic.

**Comment by cicdw** [comment]
We could go further than that and add descriptions on all tasks + Flows!  This actually came up in a conversation the other day, so I'd like to revisit it.  I'll bring this up internally and circle back; @szelenka if you want to open a new issue for descriptions that'd be great - I'll be following up on this either way.

**Comment by kylebarron** [comment]
Looking at how the `DateTimeParameter` was implemented, it seems you could already implement a `PydanticParameter` as a subclass of `Parameter`?

You could first implement a `PydanticSerializer`, something like

```py
from pydantic import BaseModel

class PydanticSerializer(Serializer):
    """A Serializer for working with Pydantic objects"""
	def __init__(self, model: BaseModel):
		self.model = model

    def serialize(self, value: BaseModel) -> bytes:
        """
        Serialize a Pydantic Model to human-readable bytes
        Args:
            - value (BaseModel): the value to serialize
        Returns:
            - bytes: the serialized value
        """
        return value.json().encode()

    def deserialize(self, value: bytes) -> BaseModel:
        """
        Deserialize a Pydantic Model from bytes
        Args:
            - value (bytes): the value to deserialize
        Returns:
            - Any: the deserialized value
        """
        return self.model(**json.loads(value.decode()))
		# Note: you could use `self.model.construct` if you didn't want to perform validation each time
```

Then a `PydanticParameter` like

```py
class PydanticParameter(Parameter):
    def __init__(
        self,
        name: str,
        model: BaseModel,
        required: bool = True,
        tags: Iterable[str] = None,
    ) -> None:
        default = no_default if required else None
        super().__init__(name=name, default=default, required=required, tags=tags)
        self.result = PrefectResult(serializer=PydanticSerializer(model))
        self.model = model

    def run(self) -> Any:
        value = super().run()
        if value is None:
            return value
        else:
            # Not sure what the valid return types of `value` can be
            return self.model(value)
```

**Comment by Julian-Brendel** [comment]
Hey guys, highly interest in prefect and wondering whether there had been any movement on this.

With the release coming up, this could be a fine addition to the core library.

**Comment by cicdw** [comment]
Hi @Julian-Brendel, good news: we have [already implemented Parameter type validation](https://orion-docs.prefect.io/concepts/flows/#parameters) in what will eventually become [Prefect 2.0](https://orion-docs.prefect.io/faq/)

**Comment by cicdw** [comment]
Complete with 2.0.
