### ISSUE TITLE
Cloud handler always sets level to DEBUG

### ISSUE THREAD

**Issue by kchaliki** [PrefectHQ/prefect#2256]
## Description
*A clear description of the bug*

It looks like when logging to cloud, the log level config is ignored and the level is fixed to debug in the code (prefect/utilities/logging.py:208). Not that upon construction of the hander it actually reads the config but the harcoding is done straight after.

## Expected Behavior
*What did you expect to happen instead?*

The log level config to be respected.

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

*Optionally run `prefect diagnostics` from the command line and paste the information here*

**Comment by joshmeek** [comment]
Thanks for opening the issue @kchaliki! I think we should update that line to respect the level set by `config.logging.level` similar to how the normal logger does 👍

**Comment by lauralorenz** [comment]
@kchaliki talking about this more with the core team this is not as trivial to implement for all distributed agents to honor from config; is there a specific use case that filtering the debug logs from the UI in cloud isn't good enough for?

**Comment by kchaliki** [comment]
Hi @lauralorenz I am sure we can get by with the UI filter. I just thought streaming debug logs, particularly from all sorts of libraries people use, might put unnecessary stress on the system, obviously having to click around every time to filter is also a minor nuisance but definitely not a priority.

**Comment by arlobryer** [comment]
Hi @lauralorenz - a good example of a use-case where it would be nice to have this is when trying to debug something where it's sensible to locally log potentially sensitive information that shouldn't be leaked through the logs when running through Cloud.

**Comment by cicdw** [comment]
@arlobryer - in that case it would be safer to use `--no-cloud-logs` on your agent so that _no_ logs get shipped to Cloud for the duration of the run instead of relying on logging levels.

**Comment by lauralorenz** [comment]
Thanks @arlobryer for the use case; RT on the `--no-cloud-logs` as the absolute safest route, and FWIW there is some work going on by a contributor you might be interested in at https://github.com/PrefectHQ/prefect/pull/2160 regarding the specific case of still wanting most cloud logs, just not the PII in them

**Comment by joshmeek** [comment]
The default of DEBUG is no longer the case, closing
