### ISSUE TITLE
I'd like to configure the network for the containers spawned by the docker agent

### ISSUE THREAD

**Issue by jloehel** [PrefectHQ/prefect#2257]
## Use Case
Apollo runs in a specific docker network. The docker agent spawns a new container for a flow but the new container can not reach Apollo because the service runs in a different network.

## Solution
It would be awesome if I could specify the network for the container which is spawned for the flow by the docker agent:

https://github.com/PrefectHQ/prefect/blob/f5ff9b614c1d600a253fb752b1f9d2aac3d2d376/src/prefect/agent/docker/agent.py#L335-L341

**Comment by joshmeek** [comment]
There are a couple ways I could see us implementing this:
- Allow for specifying a `network_config` dictionary which would be passed in to the `create_container` call
- Allow for a list of network IDs to auto connect each created container to using (`connect_container_to_network`)[https://docker-py.readthedocs.io/en/stable/api.html#docker.api.network.NetworkApiMixin.connect_container_to_network]

@jloehel On a somewhat related note how are you running Apollo? Right now the deployments created by the Docker agent are set to reach back out to the port mapped to the host machine's localhost. This means that if you are running `prefect server start` and the Docker agent on the same machine it _should_ by default be able to read Apollo

**Comment by joshmeek** [comment]
#2334 should allow for this behavior
