### ISSUE TITLE
Operator task behavior is unintuitive/misleading

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#2271]
The docstrings for the various logical `Operator` tasks suggest that they just call the corresponding Python operator. So I would expect `Or(x, y)` to return `x or y` instead of `bool(x or y)`: https://github.com/PrefectHQ/prefect/blob/07cb6c20342c4053a3eaaaf885670ae5dfd6e74d/src/prefect/tasks/core/operators.py#L233-L254.

If there's a specific reason why these have to return boolean results, then at least the docstrings should probably be updated to reflect that.

**Comment by jlowin** [comment]
To be completely honest, the reason for this is that when I put these together I only consider the logical operator case and not the more general case. 

Upon giving this some though, I think it is *nice* to have operators with a constant return type (`bool`) but I immediately see the benefit of supporting the generic `or` - for example, for merging two branches together. I'd support relaxing the `bool` cast.
