### ISSUE TITLE
[documentation] How to Register a Flow

### ISSUE THREAD

**Issue by hydrosquall** [PrefectHQ/prefect#2288]
## Description
*A clear description of the bug*

- Currently this link returns a `404`: https://docs.prefect.io/cloud/concepts/flows.html#registration . It's on the getting started page ( https://docs.prefect.io/core/getting_started/first-steps.html )

##  Expected Result

- Updated link with directions on how to register a flow. I think that https://docs.prefect.io/orchestration/tutorial/first.html#register-flow-with-the-prefect-api might work, but a description of how to register outside of the tutorial (as it seems to have originally been on the core concepts Flows page) would be useful.

**Comment by joshmeek** [comment]
Thanks for opening @hydrosquall! Will look into making the adjustment
