### ISSUE TITLE
`Flow.reference_tasks` should be a property

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#229]
We currently have a custom setter / getter for the `reference_tasks` of a flow, only difference is that
```python
flow.reference_tasks() # <-- you have to call it
```
whereas, if we implemented it as a property with getters / setters, we could have
```python
flow.reference_tasks
```
as valid.

Moreover, we could keep `set_reference_tasks` but 
```python
flow.reference_tasks = [t1, t2]
```
would also be valid syntax, equivalent (under the hood) to
```python
flow.set_reference_tasks([t1, t2])
```

**Comment by cicdw** [comment]
@itsngansense ?

**Comment by itsngansense** [comment]
@cicdw @jlowin i'm reopening this issue as i think it's probably important information for users to see on the UI whether or not a task in a flow is a 'reference task' and i wasn't able to get that from the graphQL query :/

this would be interesting to also automatically tag these tasks with `reference` display tags when being created or added to a flow.

**Comment by itsngansense** [comment]
and how many reference tasks are within a flow's structure is important info.

**Comment by jlowin** [comment]
Let's open in Cloud, this isn't where this will get exposed.
