### ISSUE TITLE
Workflows processing large files

### ISSUE THREAD

**Issue by max-sixty** [PrefectHQ/prefect#2321]
## Use Case
I have a fairly simple workflow involving large files and would like to ask the best approach in prefect; hope it's OK to use GH issues for this.

Workflow:
1. Start with a large tar file
2. Uncompress the tar file into lots of files, also large
3. Run a function over each uncompressed file
4. Write each result to a bucket

## Questions

- Should the files' contents be passed between tasks? Assuming that requires all the data in memory, that's not efficient.
- Should the files be written to a bucket, and the location passed between tasks? Presumably writing to local disk isn't feasible given the following task may not have access to the same disk?

Thanks!

**Comment by cicdw** [comment]
Hi @max-sixty ! There are a few options here depending on your desired execution environment.  To get the conversation started, I'd recommend starting with an implementation that does assume all tasks have access to the same underlying disk and doing something like:

```python
from prefect import task, Parameter, Flow

## initialize some tasks
filename = Parameter("filename", default="a-possible-default.tar.gz")

@task
def decompress_tar(filename) -> List[str]:
    "decompresses given filename and returns a list of absolute paths to the decompressed files"

@task
def some_function(fpath) -> str:
    "Processes a single uncompressed file and returns the new filepath"

@task
def upload_file_to_bucket(fpath) -> None:
    "Given a filepath, uploads to bucket"


with Flow("tar-process") as flow:
    files = decompress_tar(filename)
    upload_file_to_bucket.map(some_function.map(files))
```

Some ways to enhance this:
- use some of Prefect's built-in tasks to help remove boilerplate (e.g., `ShellTask`, `S3Upload`)
- run this using a `DaskExecutor()` (no scheduler address) to achieve some local parallelism 

Note that you _could_ choose to exchange the full file contents but if you're worried about your machine's memory usage then I wouldn't recommend that - the above design avoids _ever_ loading the files into Python's memory.

I'll leave this issue open for a bit in case you have follow-ups or if I misunderstood something in your question 👍

**Comment by max-sixty** [comment]
Perfect, that's very clear. Thanks @cicdw !

**Comment by hjurong** [comment]
Hi, 

I am facing a similar problem with substantial memory usage on a large ETL prefect flow. Since the `State` object holds onto the results/data till the end of the flow, when I have a multi-stage processing pipeline passing the raw data between tasks, the memory grows linearly. Is it possible to clear the upstream states results when they are no longer needed by downstream?
