### ISSUE TITLE
Cull unneeded dependencies

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2345]
Currently the `requirements.txt` file contains:

A few things that I don't think we actually use (or can't find their use):

- `supervisor`
- `typing_extensions`

A few things that are only used by specific functionality

- `docker`: docker tasks, environment, and agent.
- `pyyaml`: kubernetes agent and environment

Unfortunately all of these are imported by default, so moving them to an `extra` would require deprecation and some work.

Two action items:

- [ ] Are `supervisor` and `typing_extensions` unnecessary? If so, I'll open a PR to remove them.
- [ ] Should `prefect` be a "kitchen-sink" package, or should we move to more of a component architecture, moving docker and k8s integration to extras?

Related to #2339.

**Comment by cicdw** [comment]
Setting aside the larger discussion point:

- `supervisor` can be removed; the only place `supervisor` shows up is via the `prefect agent install local` command (which outputs a `supervisord` configuration file, but users can install that independently of prefect)
- `typing_extensions`: I believe this is legacy from when we supported python 3.5, so if tests pass without it then it can be removed

**Comment by jcrist** [comment]
Cool, I'll push up a PR for that shortly.

**Comment by jcrist** [comment]
Done in #2346. I'm not familiar with typing in Python, but I *think* we also don't need the `typing` module from PyPI, since it's all backports and the min version was set to 3.6.1 (and prefect only supports >3.6).

**Comment by cicdw** [comment]
@jcrist we already have a `"kubernetes"` extra so if it's possible to move `pyyaml` into that without disrupting other functionality that could be another win here.  

For `docker`: historically, this was the only way to run Prefect Agents and register Flows so it became a baked in part of the library.  My only hesitation in removing it would be that it's the preferred deployment tool for most Cloud users and so having it pre-installed removes a step but that's a flimsy argument.
