### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by GZangl** [PrefectHQ/prefect#2349]
Dear Team,
I have tried to install prefect, first, according to the instructions "pip install prefect".
Then I figured out, I need docker and docker-compose.
After installing the two, I get following error message when starting prefect:

georg@Lubuntu-VB:~/PycharmProjects/prefect$ prefect server start
/home/georg/.local/lib/python3.6/site-packages/prefect/cli/server.py:238: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  y = yaml.load(file)
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
Exception caught; killing services (press ctrl-C to force)
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

running "docker-machine ls" shows no docker machines.
 
Please be so kind and help,
thanks
Georg

**Comment by joshmeek** [comment]
Hey @GZangl did you try running the `docker-machine start default` that the error output says?

**Comment by GZangl** [comment]
Dear @joshmeek,
thanks for your fast reply. I think the problem was, that I ran out of disk space on my virtual machine.
I have created a new VM and succeeded with the installation.
Now I have a different problem, I will open a separate ticket.
Thanks for your help!
