### ISSUE TITLE
Role "postgres" does not exist.

### ISSUE THREAD

**Issue by hade94** [PrefectHQ/prefect#2350]
## Description
*A clear description of the bug*
After installing via pip install prefect and setting backend to server, the following output is repeating in the console.

Any ideas? Thanks in advance.

## Expected Behavior
A running environment.

## Reproduction
pip install prefect
prefect backend server
prefect server start

## Environment

 A postgres server is installed on the system but is not running.
`{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_version": "0.10.2",
    "python_version": "3.6.9"
  }
}
`
{

`postgres_1   | 2020-04-17 13:19:32.097 UTC [549] FATAL:  password authentication failed for user "postgres"
postgres_1   | 2020-04-17 13:19:32.097 UTC [549] DETAIL:  Role "postgres" does not exist.
postgres_1   |  Connection matched pg_hba.conf line 95: "host all all all md5"`

**Comment by zdhughes** [comment]
Hi @hade94! I'm having some trouble replicating this issue-- does it persist after you tear down prefect server and spin it back up again?
