### ISSUE TITLE
"server start" fails with error in container creation ( postgres, invalid IP address in add-host )

### ISSUE THREAD

**Issue by sittizen** [PrefectHQ/prefect#2351]
## Description
running 'prefect server start' fails after pulling needed images with:

    Creating network "prefect-server" with the default driver
    Creating tmp_postgres_1 ... error

    ERROR: for tmp_postgres_1  Cannot create container for service postgres: invalid IP address in add-host: ""

## Reproduction / Environment
running into an Ubuntu 18.04 with:
- Python 3.6.9
- Docker version 19.03.8  ( installed in rootless mode )
- docker-compose version 1.25.4
- prefect==0.10.2

prefect diagnostics :

    {
      "config_overrides": {},
      "env_vars": [],
      "system_information": {
          "platform": "Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic",
          "prefect_version": "0.10.2",
         "python_version": "3.6.9"
      }
    }

**Comment by zdhughes** [comment]
Hi @sittizen! Does this issue persist when you tear down prefect server and spin it back up again? Happy to help, but I'm unable to replicate the problem.

**Comment by sittizen** [comment]
> Hi @sittizen! Does this issue persist when you tear down prefect server and spin it back up again? Happy to help, but I'm unable to replicate the problem.

Hi! seems it's due to docker running in rootless mode, tried on my personal laptop with a "normal" docker install and it works.

**Comment by zdhughes** [comment]
Glad to hear it's working for you! I'll try and recreate using a rootless setup.

**Comment by lauralorenz** [comment]
Closing this issue since it seems from the conversation that the problem was resolved, but feel free to reopen as an enhancement if running `prefect server start` off of `prefect server start` for a docker install in rootless mode is a critical deployment path for you! cc @sittizen
