### ISSUE TITLE
Error while deploying flow: FileNotFoundError(2, "No such file or directory: 'ip'")

### ISSUE THREAD

**Issue by oleksandr** [PrefectHQ/prefect#2361]
## Description

Using code snippet from https://docs.prefect.io/orchestration/tutorial/docker.html#persisting-your-flow-with-docker-storage 

```python
import prefect
from prefect import task, Flow
from prefect.environments.storage import Docker

@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Hello, Docker!")

flow = Flow("hello-docker", tasks=[hello_task])

flow.storage = Docker()

flow.register()
```

running it in the container ends up building proper image and registering the flow in local server:

```
...
 ---> 3d851b191d56
Successfully built 3d851b191d56
Successfully tagged hello-docker:2020-04-20t08-03-01-759322-00-00
Flow: http://localhost:8080/flow/5af6b16e-cbd1-44f0-b855-80e3420f4860
```

Then I start the agent `prefect agent start docker` (inside the same container or different one, which joined the same docker network and has docker unix socket access via mounted volume).

The error I observe:

```
root@876bfe616714:~/flows# prefect agent start docker

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2020-04-20 08:09:06,297] INFO - agent | Starting DockerAgent with labels []
[2020-04-20 08:09:06,298] INFO - agent | Agent documentation can be found at https://docs.prefect.io/cloud/
[2020-04-20 08:09:06,299] INFO - agent | Waiting for flow runs...
[2020-04-20 08:09:42,514] INFO - agent | Found 1 flow run(s) to submit for execution.
[2020-04-20 08:09:42,589] INFO - agent | Deploying flow run b86a2022-4e17-49cb-b5d2-266c6adf3593
[2020-04-20 08:09:42,601] ERROR - agent | Logging platform error for flow run b86a2022-4e17-49cb-b5d2-266c6adf3593
[2020-04-20 08:09:42,702] ERROR - agent | Error while deploying flow: FileNotFoundError(2, "No such file or directory: 'ip'")
```

## Expected Behavior

Pick the flow and execute it.

## Reproduction

1. Start prefect stack locally (docker compose)
2. Start additional container and join the compose network, e.g. `docker run -it --rm -v $(pwd)/flows:/root/flows -v /var/run/docker.sock:/var/run/docker.sock --network "prefect-server" prefecthq/prefect:latest /bin/bash`
3. Init the env:
```
export PREFECT__BACKEND=server
export PREFECT__SERVER__HOST=http://docker.for.mac.host.internal
```
4. Register the flow (see above)
5. Run agent (see above)

## Environment

OSX, Docker Desktop Community 2.2.0.5

**Comment by joshmeek** [comment]
Thanks for opening @oleksandr! Since you're running the Docker agent inside a container my first thought is that it doesn't know where the daemon is in order to connect. You could try specifying the location of your Docker daemon through the agent's argument:

```python
- base_url (str, optional): URL for a Docker daemon server. Defaults to
            `unix:///var/run/docker.sock` however other hosts such as
            `tcp://0.0.0.0:2375` can be provided
```

Will need to do some more digging if that does not solve it. I have seen this `"No such file or directory: 'ip'"` issue before and IIRC it was due to someone attempting to run a container inside a container.

**Comment by oleksandr** [comment]
@joshmeek I've did further digging and traced this error to function call `get_docker_ip()`, which appears to call `ip` binary from `iproute2` package (at least on ubuntu). This command and corresponding package is not available in the official Prefect docker image.

I've installed it manually, but obviously it doesn't work as expected - there's no `docker0` inteface inside of a container: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/docker_util.py#L13

Ignoring this issue and trying still to run agent in DinD fashion (mounting docker socket via volume or using `socat` and exposing it via TCP in docker network) leads to a new issue:

1. I build flow with Docker storage (image is available)
2. Run docker agent (inside of container)
3. Run the flow
4. Observe how agent picks the task and fails at the creation of a container with an error: 

```
400 Client Error: Bad Request ("invalid IP address in add-host: """)
```
I'm looking into this issue now, but overall using current implementation of `get_docker_ip()` is limiting use-cases.

**Comment by joshmeek** [comment]
Ah I see what you are saying about `get_docker_ip`. Since the container base is linux it is always calling that even though the function is more for users running the Docker agent on their Linux machines and not container. For that we should allow an opt-out of that check.

The `add-host` error looks like there may be an issue with the exposed daemon endpoint. Any more context on the setup you did prior?

**Comment by oleksandr** [comment]
@joshmeek I will try to reset the environment today, reproduce the issue and share the details here to be able to move forward.

**Comment by oleksandr** [comment]
So here're details on the environment I'm running. This is local setup, but it reflects our production setup, which is Dockerized, but without an orchestrator (independent machines). This article shades some light: https://www.redhat.com/sysadmin/podman-shareable-systemd-services - pretty much each container is managed by systemd.

My local setup:

1. The latest Prefect stack is started as usually on OSX, no changes to that. 

2. The flow is basic with the following relevant parts (Docker for storage, S3 for results, Dask/Processes as env for parallelization withing the same container):

```python

    flow = ...

    flow.environment = RemoteEnvironment(
        executor="prefect.engine.executors.LocalDaskExecutor",
        executor_kwargs={"scheduler": "processes", "num_workers": 12},
    )

    flow.storage = Docker(image_name='hello-docker', image_tag='latest')
    flow.storage.build()

    flow.result_handler = S3ResultHandler(
        "flows",
        boto3_kwargs=dict(endpoint_url=os.getenv("AWS_S3_ENDPOINT"))
    )

```

3. I do task registration from within a container that joins prefect-server network, pass host system's docker socket via volume (`-v /var/run/docker.sock:/var/run/docker.sock`) and that works fine:
```bash
...
 ---> Running in 81497fa9350e
Beginning health checks...
System Version check: OK
Cloudpickle serialization check: OK
Result Handler check: OK
Environment dependency check: OK
All health checks passed.
Removing intermediate container 81497fa9350e
 ---> 39765d0ad452
Successfully built 39765d0ad452
Successfully tagged hello-docker:latest
Flow: http://localhost:8080/flow/b1c9dd6a-0716-4b1b-8f8f-ee14c8379cf1
```

4. I start separate container that also joins prefect-server network, also pass host system's docker socket (`-v /var/run/docker.sock:/var/run/docker.sock `) with the following entrypoint:
```
prefect agent start docker --base-url=unix:///var/run/docker.sock --network=prefect-server -l docker
```

5. I trigger the flow from UI and observe the following in agent's log:
```
[2020-04-24 13:20:22,909] INFO - agent | Found 1 flow run(s) to submit for execution.
[2020-04-24 13:20:22,993] INFO - agent | Deploying flow run a69fb0fe-41fb-4d4a-b91b-1530025d3d57
[2020-04-24 13:20:23,058] ERROR - agent | Logging platform error for flow run a69fb0fe-41fb-4d4a-b91b-1530025d3d57
[2020-04-24 13:20:23,129] ERROR - agent | Error while deploying flow: APIError(HTTPError('400 Client Error: Bad Request for url: http+docker://localhost/v1.40/containers/create'))
```

**Comment by oleksandr** [comment]
I also tried to switch to TCP socket for docker. 

1. Adding such services to docker network exposes socket as `tcp://docker:2375`:

```yaml
  docker:
    image: alpine/socat:latest
    networks:
    - prefect-server
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
```

2. I passed it to agent via `base_url` and observed the same error as above.

**Comment by joshmeek** [comment]
I wonder if this has something to do with the Docker client's `networking_config`. We do something like this:

```python
networking_config = None
if self.network:
    networking_config = self.docker_client.create_networking_config(
        {self.network: self.docker_client.create_endpoint_config()}
    )
```

Bad request (400) leads me to think something we're sending isn't correct or compatible and it seems that the only thing "out of the ordinary" would be the network. When you tried the switch to TCP did you also provide a network of `prefect-server`?

**Comment by oleksandr** [comment]
@joshmeek The lines above are fine, network is reachable (I do pass network name in both cases).

I think the error is still related to `get_docker_ip`. I've tried to comment out these lines:

```python
        if sys.platform.startswith("linux"):
            docker_internal_ip = get_docker_ip()
            host_config.update(extra_hosts={"host.docker.internal": docker_internal_ip})
```

and dockerized flow has been executed. Looks like in DinD cases specifying `extra_hosts` causes this 400 error.

**Comment by joshmeek** [comment]
@oleksandr Okay gotcha, I'm going to add a flag that you can set to disable that check 👍

**Comment by joshmeek** [comment]
@oleksandr Take a look at #2433

**Comment by oleksandr** [comment]
@joshmeek looks good to me! I hope it doesn't shoot back in other weird use-cases, but so far - exactly what would help us! thanks a lot!
