### ISSUE TITLE
Iron out steps for resolving serializer changes with Core's server

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#2375]
I am currently working on #2369 and in turn adding a new serializer effectively breaks its use with Core's server due to the version of prefect that the server has being behind (using the `latest` build).

```bash
In [14]: f = Flow('a', environment=RemoteDaskEnvironment(address="yes"))

In [15]: f.register()
Result Handler check: OK
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-15-11702a1d3250> in <module>
----> 1 f.register()

~/Desktop/code/prefect/src/prefect/core/flow.py in register(self, project_name, build, labels, set_schedule_active, version_group_id, no_url, **kwargs)
   1371             set_schedule_active=set_schedule_active,
   1372             version_group_id=version_group_id,
-> 1373             no_url=no_url,
   1374         )
   1375         return registered_flow

~/Desktop/code/prefect/src/prefect/client/client.py in register(self, flow, project_name, build, set_schedule_active, version_group_id, compressed, no_url)
    624                     serialized_flow=serialized_flow,
    625                     set_schedule_active=set_schedule_active,
--> 626                     version_group_id=version_group_id,
    627                 )
    628             ),

~/Desktop/code/prefect/src/prefect/client/client.py in graphql(self, query, raise_on_error, headers, variables, token)
    223             elif "Malformed Authorization header" in str(result["errors"]):
    224                 raise AuthorizationError(result["errors"])
--> 225             raise ClientError(result["errors"])
    226         else:
    227             return GraphQLResult(result)  # type: ignore

ClientError: [{'message': "Invalid flow: {'environment': {'type': ['Unsupported value: RemoteDaskEnvironment']}}", 'locations': [{'line': 2, 'column': 5}], 'path': ['create_flow_from_compressed_string'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'errors': [{'message': "Invalid flow: {'environment': {'type': ['Unsupported value: RemoteDaskEnvironment']}}", 'locations': [], 'path': ['create_flow_from_compressed_string']}]}}}]
```

This means that once #2369 (or any future serializers) are merged then when running the Core server images you would need to specify a `--version master` in order for it to work. I'm opening this issue as a discussion point on if this is the functionality we want or if there is a better way.

**Comment by cicdw** [comment]
@joshmeek I think we can use a form of our [prefect version logic for Docker storage](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/docker.py#L116-L120) and choose a versioned tag based on that.

We could then update the default setting here: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/server.py#L94

**Comment by joshmeek** [comment]
Good call I like that approach and it should cover almost all cases when using the master branch. The main issue though will be for local development when working with the serializer changes before merge. In those cases I will run the services directly

**Comment by cicdw** [comment]
Yea exactly, if you're truly developing at that level then you should install server directly
