### ISSUE TITLE
Run task functions individually for unit testing/experimentation

### ISSUE THREAD

**Issue by RowanMolony** [PrefectHQ/prefect#2393]
Prefect Version: 0.10.4

## Current behaviour
Currently running a task individually in returns:

```python
ValueError:  Could not infer an active Flow context
```

## Solution
Allow running of task functions individually

### Unit Testing

To allow unit testing of individual task functions in a flow.

There is likely a better way of testing data pipeline code than this which may make this feature unnecessary but I wasn't easily able to find information on this in the prefect documentation or elsewhere.  If this is the case is there any resources worth looking into further on prefect / dataflow testing best practices?  

### Experimentation

To allow for a quick look at data (via the iPython console) when calling the load_data() function individually

---

Thanks again for your work so far with the Prefect library

**Comment by joshmeek** [comment]
Hey @RowanMolony try calling the task's `run` method. e.g.
```
my_task(...).run()
```
