### ISSUE TITLE
SQLiteQuery in task library needs db as argument at run time

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#2405]
## Description
*A clear description of the bug*
The SQLiteQuery task in the database section of the task library has db as a required argument at init but not at run.  If a user wants to enter the db as a parameter at runtime, they can not. 

## Expected Behavior
*What did you expect to happen instead?*
Should be able to add the database as a parameter. 

Slack thread with details: https://prefect-community.slack.com/archives/CL09KU1K7/p1587751197136400

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

*Optionally run `prefect diagnostics` from the command line and paste the information here*

**Comment by joshmeek** [comment]
Closed by #2782
