### ISSUE TITLE
UPS & FedEx

### ISSUE THREAD

**Issue by raveslave** [PrefectHQ/prefect#2420]
## Use Case
Fetch shipping info and invoices from UPS & FedEx   
this is useful to 
- trigger events upon exceptions
- extract actual invoiced shipping costs based on tracking-no or meta-fields like "vendor order-id"

**Comment by joshmeek** [comment]
Hey @raveslave thanks for the request! Are you opening this as a request for tasks to be added to the task library or for a guide on how something like this would be completed?

**Comment by raveslave** [comment]
Mainly something that would be great to see for the task library as I believe many customers need it.

**Comment by lauralorenz** [comment]
Hi @raveslave! I've added the "task library" label so contributors interested in adding to the task library can easily find it. 

If you have any more you can flesh out on these use cases (for example what is a specific example for "trigger events upon exceptions"?) and suggest any specific parts of the UPS or FedEX APIs a contributor could focus on that would probably help them too! (PS: it looks like there is a [UPS REST API](https://www.ups.com/upsdeveloperkit?loc=en_US) and possibly the same for [FedEx though the docs are behind a login](https://www.fedex.com/en-us/developer/web-services.html); not sure if there are python packages that wrap these or not.)
