### ISSUE TITLE
API Documentation does not respect code-copy height changes

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#2427]
The change made in #1816 to reduce the padding height from the copy button on code blocks is not respected in the API documentation.

API Documentation:
![image](https://user-images.githubusercontent.com/40716964/80407532-c252d580-8893-11ea-9dd0-2f80ecc08fdd.png)

Concept Documentation:
![image](https://user-images.githubusercontent.com/40716964/80407550-c7b02000-8893-11ea-98f0-1b2c2fd229bf.png)

**Comment by cicdw** [comment]
**cc:** @znicholasbrown as you made the original change and might know what's up

**Comment by znicholasbrown** [comment]
@joshmeek can you provide some links to the docs in question? A quick glance at both shows no padding issues

**Comment by joshmeek** [comment]
With extra padding: https://docs.prefect.io/api/latest/environments/execution.html#remotedaskenvironment

Without extra padding: https://docs.prefect.io/core/concepts/engine.html#using-a-dask-executor
