### ISSUE TITLE
Add Telemetry to Prefect Sever

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#2439]
## Current behavior
*Please describe how the feature works today*

Prefect Server currently operates without sending any telemetry back to Prefect. Knowing some basic facts about how people are using Prefect Server would be extremely helpful to the development team.

## Proposed behavior
*Please describe your proposed change to the current behavior*

For now, let's track two events:
- [ ] Server start
- [ ] Server shutdown

In the future, we should make a best effort to track errors so that we can elevate common issues.

Server startup and shutdown should still succeed if sending telemetry fails. We don't want this to block users in any way.

We should also add a configuration option so that the user can opt-out of sending telemetry.

## Example
*Please give an example of how the enhancement would be useful*

These metrics would give us a rough idea of:

1. How many active Prefect Server instances there are in the world
2. What common errors they're experiencing

**Comment by lauralorenz** [comment]
Looks like the PR got merged, closing this issue unless it needs to be reopened for any other reason @dylanbhughes

**Comment by dylanbhughes** [comment]
For the record, we decided instead to record:
1. server start
2. a heartbeat every 10 minutes
