### ISSUE TITLE
Docs improvement to provide an example on how to migrate to server using dask executor

### ISSUE THREAD

**Issue by kingsleyb** [PrefectHQ/prefect#2446]
## Current behavior

This [doc](https://docs.prefect.io/core/advanced_tutorials/dask-cluster.html) has a great example of how to use dask executor locally and run flow directly from the flow. 

## Proposed behavior
Provide an example on the recommended approach to register the flow with server using the dask executor.

Also, on the same page, fix the link in the text "you can visit the Dask Web UI"

**Comment by lauralorenz** [comment]
From core meeting, might want to consider linking over to the Orchestration docs since as of now at least we try to reuse the orchestration docs between Server/Cloud instead of recreating them on the Core docs section side.

**Comment by cicdw** [comment]
This could also provide a good place to publicize our new `RemoteDaskEnvironment` as well

**Comment by kvnkho** [comment]
This issue is stale and likely not relevant anymore given that environments are deprecated.
