### ISSUE TITLE
Can't set custom log format for Tasks

### ISSUE THREAD

**Issue by jacques-** [PrefectHQ/prefect#2456]
## Description

I am trying to set a custom log format for messages logged using self.logger in a Task. 

I followed docs here: https://docs.prefect.io/core/advanced_tutorials/custom-logs.html#an-example but this did not work for me, instead the added handler seemed to be ignored.

## Expected Behavior

Expected to see task logs in the new format specified in the Formatter.

## Reproduction

This is the example from the docs slightly altered:

```
import logging
import prefect
from prefect import task, Flow
from prefect.utilities.logging import get_logger


@task(name="Task A")
def task_a():
    return 3


@task(name="Task B")
def task_b(x):
    logger = prefect.context.get("logger")
    logger.debug("Beginning to run Task B with input {}".format(x))
    y = 3 * x + 1
    logger.debug("Returning the value {}".format(y))
    return y


with Flow("logging-example") as flow:
    result = task_b(task_a)

task_logger = get_logger("Task")
test_handler = logging.StreamHandler()
formatter = logging.Formatter("######TEST FORMAT####### %(message)s")
test_handler.setFormatter(formatter)
task_logger.addHandler(test_handler)


if __name__ == "__main__":
    flow.run()
```

## Environment
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-19.4.0-x86_64-i386-64bit",
    "prefect_version": "0.10.5",
    "python_version": "3.7.4"
  }
}

**Comment by lauralorenz** [comment]
Hi @jacques- , it looks to me like the docs are out of date as of https://github.com/PrefectHQ/prefect/commit/66fdd6fde1cfcbf356961f5d53391342d1755184, as the logger name now also includes the task's name.

In your case, I edited your code to grab the task's logger like this, and saw the formatting take: `task_logger = get_logger("Task: Task B")`.
(I enclosed the full code and output below, which by the way I also threw in an extra critical log statement to see the logger name that is emitted by both the newly formatted handler and the root prefect logger).

All that being said, if you really wanted to specify a differently configured handler for logs from *all* of your tasks I imagine the change in https://github.com/PrefectHQ/prefect/commit/66fdd6fde1cfcbf356961f5d53391342d1755184 has now made that quite annoying, so it might be worth finding a way to reconcile that use case with the `get_logger` function. (Let me know if you agree on that!)


```
(prefect_dev) ➜  RandomFlows python taskloggingchange.py  
[2020-05-01 01:28:37] INFO - prefect.FlowRunner | Beginning Flow run for 'logging-example'
[2020-05-01 01:28:37] INFO - prefect.FlowRunner | Starting flow run.
[2020-05-01 01:28:37] DEBUG - prefect.FlowRunner | Flow 'logging-example': Handling state change from Scheduled to Running
[2020-05-01 01:28:37] INFO - prefect.TaskRunner | Task 'Task A': Starting task run...
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task A': Handling state change from Pending to Running
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task A': Calling task.run() method...
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task A': Handling state change from Running to Success
[2020-05-01 01:28:37] INFO - prefect.TaskRunner | Task 'Task A': finished task run for task with final state: 'Success'
[2020-05-01 01:28:37] INFO - prefect.TaskRunner | Task 'Task B': Starting task run...
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task B': Handling state change from Pending to Running
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task B': Calling task.run() method...
######TEST FORMAT####### prefect.Task: Task B
[2020-05-01 01:28:37] CRITICAL - prefect.Task: Task B | prefect.Task: Task B
######TEST FORMAT####### Beginning to run Task B with input 3
[2020-05-01 01:28:37] DEBUG - prefect.Task: Task B | Beginning to run Task B with input 3
######TEST FORMAT####### Returning the value 10
[2020-05-01 01:28:37] DEBUG - prefect.Task: Task B | Returning the value 10
[2020-05-01 01:28:37] DEBUG - prefect.TaskRunner | Task 'Task B': Handling state change from Running to Success
[2020-05-01 01:28:37] INFO - prefect.TaskRunner | Task 'Task B': finished task run for task with final state: 'Success'
[2020-05-01 01:28:37] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[2020-05-01 01:28:37] DEBUG - prefect.FlowRunner | Flow 'logging-example': Handling state change from Running to Success
```

```
import logging
import prefect
from prefect import task, Flow
from prefect.utilities.logging import get_logger


@task(name="Task A")
def task_a():
    return 3


@task(name="Task B")
def task_b(x):
    logger = prefect.context.get("logger")
    logger.critical(logger.name)
    logger.debug("Beginning to run Task B with input {}".format(x))
    y = 3 * x + 1
    logger.debug("Returning the value {}".format(y))
    return y


with Flow("logging-example") as flow:
    result = task_b(task_a)

task_logger = get_logger("Task: Task B")
test_handler = logging.StreamHandler()
formatter = logging.Formatter("######TEST FORMAT####### %(message)s")
test_handler.setFormatter(formatter)
task_logger.addHandler(test_handler)


if __name__ == "__main__":
    flow.run()
```

**Comment by jacques-** [comment]
Hi Laura, thanks for the quick response!

I just posted another issue which should provide a bit more context around why I'd like to do this:
#2462 

Essentially we are passing a `trace_id` value into context and want that value to appear in prefect logs. At the moment this is proving tricky because changing the prefect logger format globally (I'm currently doing this by `os.environ["PREFECT__LOGGING__FORMAT"] = "| %(levelname)-7s | %(asctime)-19s | %(trace_id)s | %(task_name)s | %(message)s"` but perhaps there is a better way? ) affects normal logs we generate before and after calling prefect functions. Those log events happen before we have received the message and can set the `trace_id` in `prefect.context` and so cause logging exceptions.

I was hoping to get around the issue by changing the log format for all tasks. However, looking at your example, even if we do this, we will get a duplicate log that includes the `trace_id`. 

Furthermore, it seems like if I found a way to separate our app logs from prefect logs, that still won't work because not all prefect logs seem to have access to the value injected from context either ( e.g. I get an exception from `prefect/engine/flow_runner.py", line 347, in set_flow_to_running
    self.logger.info("Starting flow run.")` that `trace_id` can't be found)

I think at a high-level what I'm looking for is a way to show the trace_id in logs when it exists in context, and not error out when it doesn't. Would appreciate any direction if setting a task log handler isn't the right way to go.

Sorry for the whole essay :) If this makes no sense, please let me know and I'll share some code.

**Comment by lauralorenz** [comment]
Hi @jacques- , checking in if the changes in https://github.com/PrefectHQ/prefect/pull/2472 against your other issue solves your source problem. They also revert the change to make task logger names include the task name, which I think brings the docs back into line with the code :)

I extended our running example a little bit to set `trace_id` in context in-task to simulate whatever it is you use to set the trace ID, and then ran with my global formatter configured in `~/.prefect/config.toml` to interpolate `trace_id` in the logs, against the latest version of Prefect (0.10.7) which has the changes from https://github.com/PrefectHQ/prefect/pull/2472; let me know if this looks like it meets all your needs:

```
#config.toml
[logging]
# The logging level: NOTSET, DEBUG, INFO, WARNING, ERROR, or CRITICAL
level = "DEBUG"

# The log format
format = "[trace id is %(trace_id)s] [%(asctime)s] %(levelname)s - %(name)s | %(message)s"
```

```
(prefect) ➜  RandomFlows python taskloggingchange.py
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.FlowRunner | Beginning Flow run for 'logging-example'
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.FlowRunner | Starting flow run.
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.FlowRunner | Flow 'logging-example': Handling state change from Scheduled to Running
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.TaskRunner | Task 'Task A': Starting task run...
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task A': Handling state change from Pending to Running
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task A': Calling task.run() method...
[trace id is A] [2020-05-06 18:35:22] CRITICAL - prefect.Task A | Hello from A
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task A': Handling state change from Running to Success
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.TaskRunner | Task 'Task A': finished task run for task with final state: 'Success'
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.TaskRunner | Task 'Task B': Starting task run...
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task B': Handling state change from Pending to Running
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task B': Calling task.run() method...
[trace id is B] [2020-05-06 18:35:22] CRITICAL - prefect.Task B | prefect.Task B
[trace id is B] [2020-05-06 18:35:22] CRITICAL - prefect.Task B | B
[trace id is B] [2020-05-06 18:35:22] DEBUG - prefect.Task B | Beginning to run Task B with input 3
[trace id is B] [2020-05-06 18:35:22] DEBUG - prefect.Task B | Returning the value 10
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.TaskRunner | Task 'Task B': Handling state change from Running to Success
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.TaskRunner | Task 'Task B': finished task run for task with final state: 'Success'
[trace id is None] [2020-05-06 18:35:22] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[trace id is None] [2020-05-06 18:35:22] DEBUG - prefect.FlowRunner | Flow 'logging-example': Handling state change from Running to Success
```

```
import logging
import prefect
from prefect import task, Flow
from prefect.utilities.logging import get_logger


@task(name="Task A")
def task_a():
    with prefect.context(trace_id="A"):
        logger = prefect.context.get("logger")
        logger.critical("Hello from A")
        return 3


@task(name="Task B")
def task_b(x):
    with prefect.context(trace_id="B"):
        logger = prefect.context.get("logger")
        logger.critical(logger.name)
        logger.critical(str(prefect.context.trace_id))
        logger.debug("Beginning to run Task B with input {}".format(x))
        y = 3 * x + 1
        logger.debug("Returning the value {}".format(y))
        return y


with Flow("logging-example") as flow:
    result = task_b(task_a)

if __name__ == "__main__":
    flow.run()
```

**Comment by jacques-** [comment]
Hi @lauralorenz, sorry for the slow response and thanks so much for this!

0.10.7 works exactly as we wanted, appreciate your efforts in supporting our use-case.

For others finding this later the example above just needs config.toml updated with the trace_id added to attributes like this:
```[logging]
# The logging level: NOTSET, DEBUG, INFO, WARNING, ERROR, or CRITICAL
level = "DEBUG"

# Inject additional attributes into logs
log_attributes = "['trace_id']"

# The log format
format = "| %(levelname)-7s | %(asctime)-19s | %(trace_id)s | %(message)s"
```
