### ISSUE TITLE
Change how we use mypy in CI

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2483]
Currently we use `mypy` as part of our CI process. This frequently leads to extra work trying to appease the type checker for code that is definitely correct (see e.g. https://github.com/PrefectHQ/prefect/pull/2406).

We *do* want mypy to check that the type signatures of public methods actually match their implementation, but we *don't* want mypy to error for internal type checking that it thinks is invalid (internal errors can be caught by tests, and frequently the type checker is more of a burden than an aid). Perhaps there's a mypy configuration setting we can change to get this behavior?

We also currently run the mypy tests in two locations:

- As part of the `Check code style and docs` build
- As part of a test in `tests/test_formatting.py`, in the `Run tests` build

These two CI builds have different environments (in particular, prefect (and dependencies) aren't installed in the former but are in the latter). This difference can lead to mypy tests passing in one environment and failing in the other.

**Comment by jcrist** [comment]
I'm starting to look at this. I'd like to not duplicate our mypy (and black) checks in two spots. This means we either:

- Remove the `Check code style and docs` build
- Remove the `py.test` run tests in `tests/test_formatting`

Most projects I've worked on run the code quality checks directly using the tools, rather than scripted as part of pytest, so removing the copies in the `tests` directory would be my vote. Getting in the practice of using these tools directly also makes it easier to check individual files when developing, rather than running the test suite which always checks the whole repo.

Thoughts @joshmeek, @cicdw?

**Comment by cicdw** [comment]
Yup, I like the clarity of having a named CI job for style / static analysis / formatting, and the red X on test failures just because of `black` or `mypy` I find annoying / misleading. 

I'm all for removing them from `py.test` and keeping the "true" CI job.

**Comment by joshmeek** [comment]
Yeah I am on board with removing them from `py.test` as well. It's very clear to have them in a separate named job!
