### ISSUE TITLE
Enhance EmailTask to allow html templates in message 

### ISSUE THREAD

**Issue by agoel92** [PrefectHQ/prefect#2487]
## Current behavior
Right now "EmailTask" casts the message portion of the email to "text/plain". Hence, any html passed in email message is not appropriately recognized.

`                              <html>
                                <body>
                                                <h3>Below are the details:</h3>

                                                <table width='100%' border="1">
                                                <tr>
                                                                <td>Filename: __main__</td>
                                                                <td>Type: Task</td>
                                                                <td>Name: <class '__main__.CreateSmsyncJob'></td>
                                                                <td>Error message: Unexpected error: abcd</td>
                                                </tr>
                                                </table>
                                </body>
                                </html>`

## Proposed behavior
It would be helpful if we could send html also in message.

**Comment by jcrist** [comment]
This seems like a fair use case. From reading up on email, it looks like in rare cases this might cause issues for email clients that don't support html, but I think those are probably rare enough that a default of `text/html` makes sense here. We should probably make the mimetype configurable though.

@agoel92, would you be interested in submitting a PR adding this functionality?

**Comment by joshmeek** [comment]
Closed with #2811
