### ISSUE TITLE
Can't combine flows that have the same parameter name

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2501]
## Description
*A clear description of the bug*
If two flows each have a parameter with the same name, they can not be combined via `flow.update()` due to the uniqueness constraint. This is frustrating for users. (Note this is tangentially related to conversations on subflows and other approaches to flow composition)

## Expected Behavior
*What did you expect to happen instead?*

## Reproduction
*A minimal example that exhibits the behavior.*

python
```
import prefect

@prefect.task
def generate1(limit):
    return list(range(10))[:limit]

@prefect.task
def generate2(limit):
    return list(range(100, 1000))[:limit]

@prefect.task
def echo(x):
    print('Got', x)

with prefect.Flow('flow1') as flow1:
    limit1 = prefect.Parameter('limit')
    data1 = generate1(limit=limit1)
    echo.map(x=data1)

with prefect.Flow('flow2') as flow2:
    limit2 = prefect.Parameter('limit')
    data2 = generate2(limit=limit2)
    echo.map(x=data2)

flow3 = prefect.Flow('flow3')

flow3.update(flow1)
flow3.update(flow2)

```

**Comment by cicdw** [comment]
Adding this reference for stackoverflow visibility: https://stackoverflow.com/questions/60679595/how-does-one-update-a-prefect-flow-with-duplicate-parameters/60685605#60685605
