### ISSUE TITLE
Support non-docker Storage for containerized Environments

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2517]
*This came out of some user conversations, and discussion with @cicdw.*

Currently any `Environment` class that uses a container, e.g.

- `KubernetesJobEnvironment`
- `FargateTaskEnvironment`
- `DaskKubernetesEnvironment`

require the corresponding `Storage` object be a `Docker` instance (note that `DaskCloudProviderEnvironment` doesn't for some reason). The same restriction occurs for agents (e.g. `KubernetesAgent` and `FargateAgent`).

This coupling can be a bit troublesome, as it requires every flow have a new docker image built for it containing the flow run. Sometimes you'd like to use the same image for all flows, and store the flow definition in an external filestore (e.g. S3).

The `Docker` storage is unique in that it includes both the software environment, and the serialized flow. Other `Storage` classes only store the serialized flow, the software environment is part of the `Environment` class.

*The goal here is to be able to mix e.g. `KubernetesJobEnvironment` and `S3` storage, where the storage stores the flow definition, and the environment stores the execution environment (with an image possibly shared between flows).*

A proposal to allow this:

- The `Docker` storage still exists as it works today, storing both a software environment and the serialized `flow`
- Environments that use containers (e.g. `KubernetesJobEnvironment`) are updated to support explicit docker image names (in the k8s case, it would be part of the `Job` spec) in the case that the corresponding storage type isn't `Docker`. If a `Docker` storage is provided, it will be used to template over the image name as is currently done (logic is override if `Docker` storage, otherwise fallback to configured in environment if provided, otherwise error). At `flow.register()` time these are merged together, and the `Environment` becomes the source of truth for what image to use when starting a flow run.
- Environments will need to support *some* deserialization in the agent to extract the image name. We could hardcode in `image_name` as an attribute that's serialized, but I'm leaning more towards a generic `environment.metadata` dict (with conventions between agents and environments on common key names). So the `KubernetesAgent` might have the convention of looking for `flow.environment.metadata["image_name"]` when kicking off the initial job. This is needed since we don't want to deserialize the full user environment inside the agent (since that may be private).
- Agents that use containers (e.g. `KubernetesAgent`) are updated to support pulling the image name from `environment.metadata` (instead of `storage.name`). We'll need to do this in a backwards compatible way so that flows serialized using the old conventions still work.

**Comment by jlowin** [comment]
This is a super exciting idea, I love the direction.

**Comment by joshmeek** [comment]
I'm thinking that for the backwards compatibility of this we could set the agents to perform a look at the `flow.environment.metadata` only if the storage type on the flow doesn't match the default expected type. e.g. If the k8s agent gets a flow with Docker storage it will use that storage option but if it's S3 it will look at the environment metadata.

The hooks for this appear to already be in place in the `execute cloud-flow` command that is called. We would just need to make sure it is clear that any provided images in the environment.metadata have prefect installed so the command will work.

The process for this is pretty straightforward and I'll take a stab at this (example):

- Build flow with S3 storage and docker image set in `environment.metadata`
- KubernetesAgent picks it up flow
- Storage type is S3 and not docker, uses image name in `environment.metadata` for prefect job
- Prefect job spins up w/ `prefect execute cloud-flow` command
- Storage is deserialized in that command and the flow is loaded / ran

**Comment by jcrist** [comment]
> I'm thinking that for the backwards compatibility of this we could set the agents to perform a look at the flow.environment.metadata only if the storage type on the flow doesn't match the default expected type. e.g. If the k8s agent gets a flow with Docker storage it will use that storage option but if it's S3 it will look at the environment metadata.

My thought was that for all flows packaged after the release containing these changes, the image will be on `environment.metadata` (including those with a `Docker` storage). If that field doesn't exist/is empty, then the flow must be built with an older version, and `Docker` storage type is required. This keeps the modern codepath clean and straightforward, and only special cases the backwards compatible path.
