### ISSUE TITLE
Write More Idioms

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2530]
We should write some more idioms:

- [x] how to define conditional logic using the [new conditional api](https://github.com/PrefectHQ/prefect/pull/2443) and the "old" way
- [x] how to use `target`s (0.11.0+)
- [x] how to configure notifications (three options: write a downstream task, state handler, cloud hook)

**Comment by joshmeek** [comment]
Related to #2580. Combining them here:

> Spin off from pycon 2020 sprints with some idioms that pycon contributors might like to try. These would be idioms added in the style of the other Prefect Idioms at https://docs.prefect.io/core/idioms/idioms.html:
> 
> * How do I perform a backfill?
> * What's available in context during a flow run?
> * How do I inspect the output from my tasks?
> * How do I use multiple schedules for a flow?
