### ISSUE TITLE
Make new conditional API compatible with the imperative API

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2538]
## Current behavior
*Please describe how the feature works today*
In #2443, @jcrist added a new conditional API to Prefect, which is 💯. However, at this moment, it can only be used with the functional API (as it [requires](https://github.com/PrefectHQ/prefect/blob/12662a3a821b52dca0c0d39ced1bbbbba0674a85/src/prefect/tasks/control_flow/case.py#L87) a `flow` in the Prefect context). 

## Proposed behavior
*Please describe your proposed change to the current behavior*

The check for `case` in context currently [takes place](https://github.com/PrefectHQ/prefect/blob/12662a3a821b52dca0c0d39ced1bbbbba0674a85/src/prefect/core/task.py#L463) in `Task.bind()`, which is called by the functional API but not common imperative patterns like `Task.set_upstream()`, `Task.set_downstream()`, `Task.set_dependencies()`, `Flow.add_task()`, or `Flow.set_dependencies()`. 

I believe `Flow.add_task()` is the lowest-level API (called by all the others mentioned above) and consequently might be an opportune place to move the check for `case` in context. This way, adding a task to a flow while in a conditional block would automatically add it to the `case` class as well. Since the flow is (obviously) available when `Flow.add_task()` is called, it can be used inside the `case` context manager when calling `bind()` and `set_upstream()`. 

I think this would enable the following imperative syntax, while still using the existing case context managers:

```
Switch = Task()
A = Task()
B = Task()
C = Task()
f = Flow('imperative flow')

switch = Switch()
f.add_task(switch)

with case(switch, 'foo'):
    f.add_task(A())

with case(switch, 'bar'):
    b = B()
    c = C()
    c.set_upstream(b, flow=f)
```

## Example
*Please give an example of how the enhancement would be useful*

**Comment by jcrist** [comment]
`case` needs a reference to the current flow to work properly, so I think this would have to be more like:

```python
with case(switch, 'bar', flow=f):
    ...
```

**Comment by jlowin** [comment]
I was playing with that, but since `Case.add_task()` is always called from a parent method that has a `flow` object available, I think we can actually hide that from the user. For example, in the current implementation, it's called from `Task.bind()` which has a flow object, so the signature could be `Case.add_task(task: Task, flow: Flow=None)`. We might want to validate that all passed flows are the same for a given case context manager, but by passing it to `add_task` we can probably hide it.

**Comment by jcrist** [comment]
See #2546.
