### ISSUE TITLE
Keep original docstring from @task decorated function

### ISSUE THREAD

**Issue by dkapitan** [PrefectHQ/prefect#2551]
## Current behavior
When decorating a function with `@task`, the original docstring of the function is lost.

## Proposed behavior
Original docstring is kept. Looking at the wrapper [`prefect.utilities.tasks.task`](https://github.com/PrefectHQ/prefect/blob/c1686091731144bbc0fab367e78b93221fccf28b/src/prefect/utilities/tasks.py#L152-L202), I thinks this should be do-able with [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps), although I am not exactly sure what change needs to be made.

**Comment by cicdw** [comment]
FYI @dkapitan you can recover the original docstring as follows:

```python
from prefect import task

@task
def my_doc_fun():
    """
    Custom docstring
    """
    pass

my_doc_fun.run.__doc__ # "Custom docstring"
```

Definitely open to elevating this more prominently though (maybe on `my_doc_fun.__doc__` in this case)

**Comment by rmax** [comment]
I thought this could be achieved by using `functools.update_wrapper`, like:
```
     task_wrapper = prefect.tasks.core.function.FunctionTask(fn=fn, **task_init_kwargs)
     return update_wrapper(task_wrapper, fn, updated=[])
```
But given `FunctionTask` is a class this doesn't work as expected :-/

**Comment by dkapitan** [comment]
@cicdw thanks for clarifying, good to know the original docstring is accessible in the run method.
My use case is that I want to generate documentation using sphinx, so I can deliver that as part of my code to clients to look up what processing steps are done within the ETL. See https://dkapitan.github.io/nimbletl/_build/html/index.html for a first rough setup.

As you can see, the module tasks is empty while it does have FunctionTasks in it.

Any ideas how to fix the (temporary and permanent) are welcome. If anyone can propose a solution I am happy to submit a PR.

**Comment by cicdw** [comment]
I can't promise this will work with Sphinx, but you might try:

```python
from prefect import task

@task
def my_doc_fun():
    """
    Custom docstring
    """
    pass

my_doc_fun.__doc__ = my_doc_run.run.__doc__

## test that this works as far as Python is concerned
import inspect

inspect.getdoc(my_doc_fun) # "Custom docstring"
```

It appears that IPython still considers the original class docstring to be the "true" docstring though, so this might not work.

**Comment by dkapitan** [comment]
@cicdw just tried exactly that, no joy ...

**Comment by dkapitan** [comment]
long-running issue in the Sphinx project: https://github.com/sphinx-doc/sphinx/issues/3783

**Comment by dkapitan** [comment]
easiest workaround for now:
* define non-decorated function in the library
* declare `task_from_function = task(function)` when writings tasks and flows

**Comment by jcrist** [comment]
The issue here is that prefect task objects aren't functions, they're objects. So for sphinx you'll want to document them as `data` (or `autodata`). Since `automodule` only finds `function` and `class` attributes (not data), you need to document these manually. For example:

```
.. autodata:: nimbletl.tasks.curl_cmd
```

This doesn't give a satisfying docstring though. Applying this diff to prefect fixes that:

```diff
diff --git a/src/prefect/tasks/core/function.py b/src/prefect/tasks/core/function.py
index ba0fa631d..dfa275bb1 100644
--- a/src/prefect/tasks/core/function.py
+++ b/src/prefect/tasks/core/function.py
@@ -10,9 +10,20 @@ from typing import Any, Callable
 import prefect
 
 
+class _DocProxy(object):
+    def __init__(self, source):
+        self._source = source
+
+    def __get__(self, obj, cls):
+        if obj is None:
+            return self._source
+        else:
+            return obj.run.__doc__
+
+
 class FunctionTask(prefect.Task):
-    """
-    A convenience Task for functionally creating Task instances with
+    __doc__ = _DocProxy(
+    """A convenience Task for functionally creating Task instances with
     arbitrary callable `run` methods.
 
     Args:
@@ -32,7 +43,7 @@ class FunctionTask(prefect.Task):
     with Flow("My Flow") as f:
         result = task(42)
     ```
-    """
+    """)
 
     def __init__(self, fn: Callable, name: str = None, **kwargs: Any):
         if not callable(fn):
```

This sets the docstring of any `@task` wrapped `Task` object to the docstring of the original task, but keeps the docstring for `FunctionTask` around when working with the raw method. I'm not sure if this is desirable though, as `@task` decorated functions are no longer functions (they're `Task` objects), so the docstring isn't 100% accurate. Perhaps we should add a prefix to the function docstring, something like:

```python
"""A prefect.Task wrapping the following function:

{original_docstring}
"""
```

:shrug:

Either way, with the above changes, I get the following for your docs:

<img width="729" alt="Screen Shot 2020-05-18 at 4 12 49 PM" src="https://user-images.githubusercontent.com/2783717/82260211-750dd500-9922-11ea-9883-40c8cfddd42b.png">

**Comment by jcrist** [comment]
I think I'm +0.5 on doing something like the above, just to make interactive development with prefect `@task` wrapped functions more pleasant. For documentation we may want to write a sphinx extension for documenting tasks (e.g. `autotask`) in a nice way. I did this for documenting `traitlet` configuration in `dask-gateway`, and the [required code was fairly short](https://github.com/dask/dask-gateway/blob/master/docs/sphinxext/autodoc_traitlets.py).

**Comment by jcrist** [comment]
I ended up submitting this in #2602, though I'm still not 100% sure it's worth it.

**Comment by ConstantinoSchillebeeckx** [comment]
I ended up [implementing](https://github.com/sphinx-contrib/prefecttask) a sphinx extension for this.
