### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by sebastianbertoli** [PrefectHQ/prefect#2556]
Hello!

I've found an issue here:`While the local agent is fully capable of executing flows in conjunction with the Prefect API, we using one of our other agents to help with modularity and scale.`

_While the local agent is fully capable of executing flows in conjunction with the Prefect API, we **prefer(?)** using one of our other agents to help with modularity and scale._

Page reference: https://docs.prefect.io/orchestration/agents/local.html

**Comment by joshmeek** [comment]
Thanks for catching this @sebastianbertoli!
