### ISSUE TITLE
Consider promoting `case` to the top level

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2568]
## Current behavior
*Please describe how the feature works today*
Currently, the `case` context manager must be imported from `prefect.tasks.control_flow.case`.

## Proposed behavior
*Please describe your proposed change to the current behavior*
I think we should consider promoting `case` to being importable as `prefect.case`, since it forms a fundamental part of the Python API. Other control flow utilities have "task-like" semantics (even if they are called as functions), and it's more appropriate for them to live in a `tasks` submodule. However, like `task`, `Flow`, `tags`, and `unmapped`, I believe `case` represents a significant component of Prefect's Python syntax and warrants top-level availability.

## Example
*Please give an example of how the enhancement would be useful*
```
from prefect import Flow, case

with Flow("example"):
    with case(is_this_easy, True):
        do_stuff()

    with prefect.tasks.control_flow.case(is_this_easy, False):
        do_other_stuff()
```

**Comment by jcrist** [comment]
I think this makes sense, along with maybe `merge`. Control flow is pretty common, but I don't think the other control flow constructs will get used as much as those two.

**Comment by jcrist** [comment]
Done in #2609.
