### ISSUE TITLE
Some more idiom ideas

### ISSUE THREAD

**Issue by lauralorenz** [PrefectHQ/prefect#2580]
Spin off from pycon 2020 sprints with some idioms that pycon contributors might like to try. These would be idioms added in the style of the other Prefect Idioms at https://docs.prefect.io/core/idioms/idioms.html:

- How do I perform a backfill?
- What's available in context during a flow run?
- How do I inspect the output from my tasks?
- How do I use multiple schedules for a flow?

**Comment by joshmeek** [comment]
Merging with #2530
