### ISSUE TITLE
Result location not set when passing target with task_args

### ISSUE THREAD

**Issue by nathan5280** [PrefectHQ/prefect#2588]
## Description
When `target` is passed to @task it is set on the `result` in the task.__init__() method.  If the target is passed through `task_args={"target"="a.data"}`. It is not set and the `result` falls back to the default_location.

## Expected Behavior
The location that the `result` uses should be the same regardless of the method used to set the `target`.

## Reproduction
```python
"""
Set in environment.

PREFECT__FLOWS__CHECKPOINTING=true
"""

from prefect import task, Flow
from prefect.engine.results import LocalResult


@task(
    target="decorator.data", result=LocalResult(dir="."),
)
def gen_decorator():
    return "gen-decorator"


@task
def gen_task_args():
    return "gen-task-args"


with Flow("Target") as flow:
    gen_decorator()
    gen_task_args(
        task_args={"target": "task-args.data", "result": LocalResult(dir="."),}
    )

    state = flow.run()
```

## Environment
Prefect 0.11.1

## Discussion
In `Task.__init__()`:

```python
        if target and result:
            self.result = result.copy()  # type: ignore
            self.result.location = target

            if getattr(result, "location", None):
                warnings.warn(
                    "Both `result.location` and `target` set on task. Task result will use target as location."
                )
```

This works fine if target is available through @task.  If it isn't set yet then `location` isn't set.

In `Task.__call__()` the task is copied.

```python
new = self.copy(**(task_args or {}))
```

In `Task.copy(self, **task_args)`. The `target` and `result` are added to the copy of the task, but location is not set on the result.

```python
        # check task_args
        for attr, val in task_args.items():
            if not hasattr(new, attr):
                raise AttributeError(
                    "{0} does not have {1} as an attribute".format(self, attr)
                )
            else:
                setattr(new, attr, val)
```

**Comment by jlowin** [comment]
That's a good call @nathan5280 - I think the best way to solve it is for us to move all task initialization logic to a new method (`Task.initialize`?) and call that method at the end of both `Task.__init__()` and `Task.copy()`. That way any time attributes are set (creation and copying), the same processing logic can be applied.
