### ISSUE TITLE
Make docker server fungible

### ISSUE THREAD

**Issue by cfdair** [PrefectHQ/prefect#2591]
## Use Case
I'd like to be able to keep data saved in the docker postgres database across docker restarts.

At the moment, a persistent docker volume is not created on the host and any data like ETL registrations and previous runs is lost when docker restarts.

## Solution
Either always create a docker volume in the docker-compose.yml, or add an option in the cli to create a docker volume.

## Alternatives
I've considered maybe a snapshot mechanism from within the prefect service but adding the docker volume seems like the easiest approach.

**Comment by cfdair** [comment]
Seems to already have a PR https://github.com/PrefectHQ/prefect/pull/2560.

Closing.

**Comment by cfdair** [comment]
I've also just realised the PR is not merged yet so I'll reopen it until its merged.

**Comment by joshmeek** [comment]
Thanks for opening @cfdair! Yep the volume mount is in progress and will be done sometime soon when I push some CLI configuration changes to the branch 😄
