### ISSUE TITLE
Potential dependency conflicts between prefect and marshmallow

### ISSUE THREAD

**Issue by NeolithEra** [PrefectHQ/prefect#2616]
Hi, as shown in the following full dependency graph of **_prefect_**, **_prefect_** requires **_marshmallow <3.5.2,>=3.0.0b19_**, **_prefect_** requires **_marshmallow-oneofschema >=2.0.0b2,<3.0_** (**_marshmallow-oneofschema 2.0.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_marshmallow-oneofschema 2.0.1_** transitively introduces **_marshmallow <4.0.0,>=3.0.0rc6_**.

Obviously, there are multiple version constraints set for **_marshmallow_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_marshmallow 3.5.1_** (i.e., the newest version satisfying constraint **_<3.5.2,>=3.0.0b19_**) is the actually installed version.

Although the first found package version **_marshmallow 3.5.1_** just satisfies the later dependency constraint （**_marshmallow <3.5.2,>=3.0.0b19_**), such installed version is very close to the upper bound of the version constraint of marshmallow specified by **_marshmallow-oneofschema 2.0.1_**. 

Once **_marshmallow-oneofschema_** upgrades，its newest version will be installed. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_marshmallow-oneofschema_** version introduces a higher version of **_marshmallow_**, violating its another version constraint **_<3.5.2,>=3.0.0b19_**.

According to the release history of marshmallow-oneofschema, it habitually upgrates Marshmallow in its recent releases. For instance, marshmallow-oneofschema 2.0.0.post0 upgrated Marshmallow’s constraint from **_>=3.0.0b9 to >=3.0.0b12,<=3.0.0b19_**,marshmallow-oneofschema 2.0.0.post0 upgrated Marshmallow’s constraint from **_>=3.0.0b12,<=3.0.0b19 to >=3.0.0b12,<4.0.0_** , and marshmallow-oneofschema 2.0.0.post0 upgrated Marshmallow’s constraint from **_>=3.0.0b12,<4.0.0 to >=3.0.0rc6,<4.0.0_**. 

As such, it is a warm warning of a potential dependency conflict issue for prefect.

### Dependency tree
```
prefect  - 0.11.2
| +- click (install version:7.1.2 version range:>=7.0,<8.0)
| +- click(install version:7.1.2 version range:<8.0,>=7.0)
| +- cloudpickle (install version:1.3.0 version range:>=0.6.0,<1.4)
| +- croniter (install version:0.3.31 version range:>=0.3.24,<1.0)
| +- dask(install version:2.16.0 version range:<3.0,>=0.19.3)
| +- distributed(install version:2.16.0 version range:>=1.26.1,<3.0)
| +- docker(install version:4.2.0 version range:>=3.4.1,<5.0)
| | +- requests (install version:2.23.0 version range:>=2.14.2)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.8 version range:>=1.21.1,<1.26)
| | +- six (install version:1.14.0 version range:>=1.4.0)
| | +- websocket-client (install version:0.57.0 version range:>=0.32.0)
| | | +- six(install version:1.14.0 version range:*)
| +- marshmallow(install version:3.5.1 version range:<3.5.2,>=3.0.0b19)
| +- marshmallow-oneofschema(install version:2.0.1 version range:>=2.0.0b2,<3.0)
| | +- marshmallow(install version:3.5.1 version range:<4.0.0,>=3.0.0rc6)
| +- msgpack(install version:0.6.2 version range:<1.0,>=0.6.0)
| +- mypy-extensions(install version:0.4.3 version range:<1.0,>=0.4.0)
| | +- typing (install version:3.7.4.1 version range:>=3.5.3)
| +- pendulum(install version:2.1.0 version range:<3.0,>=2.0.4)
| | +- python-dateutil(install version:2.8.1 version range:>=2.6,<3.0)
| | +- pytzdata(install version:2019.3 version range:>=2018.3)
| +- python-box(install version:4.2.3 version range:<5.0,>=3.4.4)
| +- python-dateutil(install version:2.8.1 version range:<3,>=2.7)
| +- python-slugify(install version:4.0.0 version range:>=1.2.6,<5.0)
| | +- text-unidecode(install version:1.3 version range:>=1.3)
| +- pytz(install version:2019.3 version range:>=2018.7)
| +- pyyaml(install version:5.3.1 version range:<5.4,>=3.13)
| +- requests(install version:2.23.0 version range:>=2.20,<3.0)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.8 version range:>=1.21.1,<1.26)
| +- supervisor(install version:4.2.0 version range:<5.0,>=4.0)
| +- tabulate(install version:0.8.7 version range:<1.0,>=0.8.0)
| +- toml(install version:0.10.1 version range:>=0.9.4,<1.0)
| +- typing(install version:3.7.4.1 version range:>=3.6.1,<4.0)
| +- typing-extensions(install version:3.7.4.2 version range:>=3.6.2,<4.0)
| +- urllib3(install version:1.25.8 version range:>=1.24.3)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_marshmallow_** to be **_>=3.0.0b19_**.
2.	Remove your direct dependency **_marshmallow_**, and use the **_marshmallow_** transitively introduced by **_marshmallow-oneofschema_**.
3.	Change your direct dependency **_marshmallow-oneofschema_** to be **_>=2.0.0b2,<=2.0.1_**.
@cicdw  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by cicdw** [comment]
Hi @NeolithEra !  

We get auto-created PRs anytime any of our dependencies has a release; we've experienced a lot of breaking changes with marshmallow releases and so prefer to be conservative with that package and keep a tight upper bound.

What you are describing is a failure of `pip` to correctly resolve package dependencies, not an inherent issue with the package constraints imposed by `prefect` and `marshmallow-oneofschema` which are entirely compatible.  I recommend using something like `conda` to manage your package versions, as that will correctly resolve package dependencies.
