### ISSUE TITLE
Unique hostname label is `docker-desktop` for Docker "host" networking type

### ISSUE THREAD

**Issue by joeschmid** [PrefectHQ/prefect#2618]
## Current behavior
The Local Agent (and Flow registration) typically generate a unique string (based on a call to `socket.gethostname()`) that gets used as a label to avoid collisions when multiple people are running Local Agents within an organization. If the Local Agent or Flow registration is running in a Docker container with the networking type set to "host" this unique string ends up as `"docker-desktop"`, negating the benefit of using this as a label that is unique to this particular Local Agent.

## Proposed behavior
If the hostname is detected as `"docker-desktop"`, generate a string of random characters (or some other approach). When docker is run without "host" networking type, docker automatically generates a random hostname. Mimicking the default docker behavior might be a good example to follow. Such a change would avoid engineers being confused when their Flow runs get picked up by someone else's local agent.

## Example
![image](https://user-images.githubusercontent.com/2823453/82497158-cd2c0f00-9abb-11ea-9168-2c1bdf88f897.png)

**Comment by joshmeek** [comment]
Ah great catch @joeschmid! In the meantime I would say add an extra label to your engineer-specific flows and agents to avoid this behavior.

**Comment by joeschmid** [comment]
@joshmeek That makes perfect sense on the requirement for the two labels needing to match. Maybe IP would is a decent alternative? (I'm sure there could be some `192.168.1.101` type duplicates, but at least far less likely.)

For our workaround, we already have engineering-specific config to have personal projects in Prefect Cloud so we ended up doing `prefect agent start local --label $PREFECT_PROJECT_NAME` in our docker-compose.yaml (Where PREFECT_PROJECT_NAME=Joe, etc.)
