### ISSUE TITLE
Add `--api` Flag Documentation to Prefect CLI and Docs

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#2633]
## Current behavior
*Please describe how the feature works today*
The `prefect agent start`/`prefect agent install` commands have an `--api` flag that a user can pass to specify the endpoint the agent should poll for Flow Runs. This flag used to be for internal use only, but now that Prefect Server has been open-sourced, our users find it useful as well!

## Proposed behavior
*Please describe your proposed change to the current behavior*

We should document this flag both in:

- [ ] Our Documentation
- [ ] The CLI help commands for `prefect agent start` and `prefect agent install`

## Example
*Please give an example of how the enhancement would be useful*
Addressed above.

**Comment by dylanbhughes** [comment]
Actually, looks like there’s an `--api` on the install but not on the start. Currently, start only reads from config. Should we consider updating the `start` command to respect this flag as well?

**Comment by joshmeek** [comment]
Yeah we should, I sometimes find myself updating the value in my config but the flag would be nice 👍
