### ISSUE TITLE
How to redirect the output of a subprocess to prefect UI Logs

### ISSUE THREAD

**Issue by alexsanjoseph** [PrefectHQ/prefect#2644]
I am trying to run orchestrate R processes using prefect. I have already lot of domain knowledge existing in R, so it doesn't make sense to rewrite them. So I've been trying to get the best of both world here.

When I run he code without prefect as a pure python program, I use the subprocess module and call the `subprocess.call` method to invoke the individual scripts. This works great and I can see the output in the console.

```
def run_analysis_for_device(run_config):
    current_date, device_uuid = run_config
    # logger = get_logger("logger")

    print(current_date, device_uuid)
    subprocess.check_call(["Rscript", "--vanilla",
                           "analysis.R",
                           device_uuid, current_date])
```

Adding the function which calls the subprocess as a Task in prefect also works well, and I can use this in prefect core while running locally.

```
@task
def run_analysis_for_device(run_config):
    current_date, device_uuid = run_config
    # logger = get_logger("logger")

    print(current_date, device_uuid)
    subprocess.check_call(["Rscript", "--vanilla",
                           "analysis.R",
                           device_uuid, current_date])
```

The issue that I'm facing is while running it on prefect cloud. I understand that to see the output in the prefect console, I need to redirect the stdout somehow, but I'm not able to do this. I've tried a couple of approaches

1. Using `@task(log_stdout=True)` - This logs the python messages, but not the logs from the subprocess itself.

2. Adding, `stdout=sys.stdout, stderr=sys.stderr` causes and error saying that 
```
AttributeError: 'RedirectToLog' object has no attribute 'fileno'
```

I tried using ShellTask, but the output of a shellTask is returned only after the entire task is completed, while I'd like to have a more live response

**Comment by joshmeek** [comment]
Hey @alexsanjoseph I think that if you want more of a live output you would do something closer to:

```python
@task
def something():
    from prefect import context
    logger = context.get("logger")

    process = Popen(cmd..., stdout=PIPE, ...)
    for line in iter(process.stdout.readline):
        logger.info(line)
```

**Comment by alexsanjoseph** [comment]
Thanks for pointing me in the right direction! What eventually worked for me was this:

```
@task
def something(shell_cmd):
    from prefect import context
    logger = get_logger("logger")

    process = Popen(shell_cmd, stdout=PIPE)
    for line in process.stdout:
        logger.info(line.decode())
    process.stdout.close()
    return_code = process.wait()
    if return_code:
        raise subprocess.CalledProcessError(return_code, shell_cmd)
```
source: https://stackoverflow.com/questions/4417546/constantly-print-subprocess-output-while-process-is-running

**Comment by joshmeek** [comment]
Glad you got it working!
