### ISSUE TITLE
Problems installing and operating Prefect (Docker)

### ISSUE THREAD

**Issue by HaiKju** [PrefectHQ/prefect#2649]
I am running on Windows 10. Question on installing Prefect. I installed and started the Docker version:

docker run -it -p 8080:8080 --name workflow-machine prefecthq/prefect:latest

The command line stopped in Python:
C:\Projekte\Lokal\software\develop\GitHub\NodeRed2Python>docker run -it -p 8080:8080 -v C:/Projekte/Lokal/software/develop/GitHub/NodeRed2Python/.prefect:/root/.prefect --name workflow-machine prefecthq/prefect:master
Python 3.7.7 (default, May 15 2020, 11:37:57)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

When I open Docker CLI and want to start the UI-Server I get the following error:

# prefect server start
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/server.py", line 279, in start
    docker_internal_ip = get_docker_ip()
  File "/usr/local/lib/python3.7/site-packages/prefect/utilities/docker_util.py", line 12, in get_docker_ip
    ip_route_proc = Popen(["ip", "route"], stdout=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip': 'ip'
#

Sorry if this is a dummy question but where is my fault? I tried to find something about this but could not find anything.

Thanks, Kai (bearbeitet)

**Comment by joshmeek** [comment]
Hey @HaiKju it looks like you're attempting to use docker inside of docker. Running `prefect server start` uses docker compose to create each service as a container. As a first step, instead of running inside a container, try starting the server from your machine's terminal instead of inside docker and let me know if any issues arise!

**Comment by HaiKju** [comment]
Hi Joshmeek, thank you for answering. Your are completely right. I start "prefect server start" from inside of the Prefect docker container. Starting the docker container from my windows terminal runs into a Python shell:
=============================================================
C:\Projekte\Lokal\software\develop\GitHub\NodeRed2Python>docker run -it -p 8080:8080 -v C:/Projekte/Lokal/software/develop/GitHub/NodeRed2Python/.prefect:/root/.prefect --name workflow-machine prefecthq/prefect:latest
Python 3.7.7 (default, Apr 23 2020, 14:54:40)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
=============================================================

Now I got stuck. I can't open http://localhost:8080. I get an "This page is not available."

**Comment by joshmeek** [comment]
I'm not sure if I follow. It doesn't look like you are running `prefect server start` from your terminal.  Judging by that output you are still running a docker container.

**Comment by HaiKju** [comment]
Ok maybe I am to stupid for docker. If I run 
=============================================================
"docker run -it -p 8080:8080 -v C:/Projekte/Lokal/software/develop/GitHub/NodeRed2Python/.prefect:/root/.prefect --name workflow-machine prefecthq/prefect:latest" 
=============================================================

I start the docker container. Next I open another cmd-shell and type in 
=============================================================
"docker exec workflow-machine prefect server start"
=============================================================

and I will get the error.

**Comment by HaiKju** [comment]
Btw sorry for the font size. I don't know why that happens. Maybe because of the "==="

**Comment by joshmeek** [comment]
Don't start any extra containers. Run `prefect server start` from a single terminal window on your machine.

**Comment by HaiKju** [comment]
Ok. If I run "docker run..." the Prefect container starts in docker dashboard and within my windows terminal CMD.exe stops in a Python shell. I can't start "prefect server start" from that Python shell. If I exit Python (with exit()) the Prefect server stops in the docker dashboard. And is not responsive anymore.

**Comment by joshmeek** [comment]
You don't need to start your own docker container or a python shell. Open CMD.exe and only type in `prefect server start`.

**Comment by HaiKju** [comment]
Now I am totally confused. If I open CMD.exe and type in "prefect server start" I get the error "The command "prefect" is either misspelled or could not be found." Of course since I didn't installed the software under Windows. I just pulled the docker container and ran "docker run...". 

Or should I append something like "docker run … **bash -c "prefect server start"**"?

**Comment by HaiKju** [comment]
but even then I get the same error...

**Comment by joshmeek** [comment]
The core server and UI are not intended to run inside of a docker container. You will need to install prefect in order to run the server https://docs.prefect.io/core/getting_started/installation.html#installation

**Comment by HaiKju** [comment]
:-) ok that makes sense. I will try tomorrow. But thank you for helping me with this beginners mistake.

**Comment by joshmeek** [comment]
Of course!
