### ISSUE TITLE
Issue passing in environment variables to kubernetes cluster

### ISSUE THREAD

**Issue by willTulcoLabs** [PrefectHQ/prefect#2652]
When running a kubernetes agent on prefect core version 0.11.1 passing in environment variables using the --env flag causes all flows to be unable to run.  Flows will fail to start with this message - 
```
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '05a5c5df-d28c-4c45-948c-fac39658b47d', 'Content-Type': 'application/json', 'Date': 'Tue, 26 May 2020 13:41:50 GMT', 'Content-Length': '548'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job in version \"v1\" cannot be handled as a Job: v1.Job.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects \" or n, but found {, error found in #10 byte of ...|\"value\": {\"aws_crede|..., bigger context ...|.CloudTaskRunner\"}, {\"name\": \"prefect\", \"value\": {\"aws_credentials\": {\"aws_secret\": \"Jq9oF0IOPihWZ9n|...","reason":"BadRequest","code":400}
```

The command i'm using to start the agent is - 
`prefect agent install --env PREFECT__AWS_CREDENTIALS__AWS_ACCESS_KEY="ACCESS_KEY" --env PREFECT__AWS_CREDENTIALS__AWS_SECRET="ACCESS_SECRET" kubernetes --rbac --backend server --api http://18.217.124.44/:4200 --image-pull-secrets my-secret | kubectl apply -f -`

It seems no matter how you pass in the environment variables they will always get transformed into a dictionary causing this error.

**Comment by joshmeek** [comment]
Thanks for opening @willTulcoLabs! I _think_ I know what's going on. The environment variables are coming through in the env var notation (`PREFECT__`) then loaded through config here:

https://github.com/PrefectHQ/prefect/blob/fce5eef50167f4d809ea24f76c7fa90509ad2848/src/prefect/agent/agent.py#L102

Then the Kubernetes agent is attaching these env vars to the jobs it creates _but_ it's using the notation from config:

https://github.com/PrefectHQ/prefect/blob/fce5eef50167f4d809ea24f76c7fa90509ad2848/src/prefect/agent/kubernetes/agent.py#L173-L175

This works fine when setting env vars that aren't Prefect configuration types like `AWS_ACCESS_KEY=MY_KEY` but will break when trying to set ones like `PREFECT__AWS_ACCESS_KEY`.

This should be investigated and fixed but in the meantime does your flow work if you set the environment variables without the Prefect configuration structure? e.g. setting `AWS_SECRET=YOUR_SECRET` and then having your task read that env var.

**Comment by willTulcoLabs** [comment]
Running my flow as AWS_ACCESS_KEY=KEY and AWS_SECRET=SECRET does work.  For more context, it looks like this bug happens whenever you access any shared namespace, i.e. AWS_CREDENTIALS_ACCESS_KEY=KEY and AWS_CREDENTIALS_SECRET_KEY=SECRET, therefore it is not possible to set any prefect configuration types since they all share the prefect namespace

**Comment by joshmeek** [comment]
This pattern is no longer recommended and instead using a default [custom job template](https://docs.prefect.io/orchestration/agents/kubernetes.html#custom-job-template) on your agent to use for all KubernetesRun objects is the way to go. That should solve this use case. Previously where the --env option was the only way to pass variables to all jobs they can not be automatically inherited from the user-set default job template.
