### ISSUE TITLE
Allow users to register local flows without autogenerated labels

### ISSUE THREAD

**Issue by zdhughes** [PrefectHQ/prefect#2653]
## Current behavior
*Please describe how the feature works today*

As it exists today, flows registered with local storage are auto-labeled with information related to their local machines, and there's no way to opt out.

## Proposed behavior
*Please describe your proposed change to the current behavior*

Auto-labeling provides a sensible default, but we should also provide a way to opt out of labels for local flows.

## Example
*Please give an example of how the enhancement would be useful*

As it stands today, it's cumbersome for users to run local flows registered on one machine on a different machine. While that's a pretty rare use case, we have had some folks opt to use Prefect in that way. Allowing users to toggle auto-generated labels would help remove some of that friction.

**Comment by flavienbwk** [comment]
@cicdw How this solves the problem ?
