### ISSUE TITLE
Allow passing version_group_id to CLI

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#2673]
Following up on #2005: it would be nice to have the same functionality from the command line (we pretty much exclusively launch flows with `prefect run cloud ... --watch` to get the logs+flow run URL in the console).

As a slight tangent: if there's concern about the CLI feature set getting too bloated, maybe a better approach would be to refactor some of the log tailing, etc. into separate helpers so it can be invoked directly w/o relying on the CLI at all...?

**Comment by joshmeek** [comment]
Hey @bnaul which command(s) are you referring to using the `version_group_id`? Something like `prefect run cloud version_group_id`?

And I actually don't see if being too bloated at all yet!

**Comment by JacobHayes** [comment]
Looks like this can be closed after https://github.com/PrefectHQ/prefect/pull/4100
