### ISSUE TITLE
Warning on `ifelse`/`merge` use

### ISSUE THREAD

**Issue by eric-czech** [PrefectHQ/prefect#2678]
## Description

I can't seem to find any combination of `ifelse`/`merge` usage that doesn't give me the `UserWarning: Tasks were created but not added to the flow` warning.  

## Expected Behavior

No warning

## Reproduction

```python
from prefect import Flow, task
from prefect.tasks.control_flow.conditional import ifelse, merge

@task
def a(x):
    return x + 1

@task
def b(x):
    return x * 2

with Flow('f') as flow:
    x = 2
    t1 = a(x)
    t2 = b(x)
    ifelse(x > 1, t1, t2)
    y = merge(t1, t2)
flow.run()
# UserWarning: Tasks were created but not added to the flow
```

Is there something going on in the example above I may be misunderstanding?

**Comment by jlowin** [comment]
I’m away from my computer but #2680 might solve this. If not I think it will be the basis for the solution.

**Comment by jlowin** [comment]
Yes, #2680 will solve this.
