### ISSUE TITLE
Missing edge in flow visualization for conditional branch 

### ISSUE THREAD

**Issue by eric-czech** [PrefectHQ/prefect#2679]
## Description

The flow visualization for merged branches appears to be incorrect for noop branches.

## Reproduction

The visualization in this case implies that the "False" branch doesn't get merged with the multiplication task at the end, but it does:

```python
@task
def a(x):
    return x + 1

with Flow('f') as flow:
    x = 1
    t = a(x)
    ifelse(x > 1, t, x)
    y = merge(t, x)
    z = y * 2

state = flow.run()
# `x` is returned as-is in the false branch and multiplied by 2 as expected
state.result[z].result
# > 2
# However, the visualization does not show that `x` would be multiplied
flow.visualize()
```
![Screen Shot 2020-05-31 at 10 50 56 AM](https://user-images.githubusercontent.com/6130352/83355328-df644380-a32c-11ea-9b7d-e57da6066ad1.png?v=4&s=200)

I would have expected the above to instead look like this, where the merge edge is incorporated if some mutation is applied to `x`:

```python

@task
def a(x):
    return x + 1

@task
def b(x):
    return x + 2

with Flow('f') as flow:
    x = 1
    t1 = a(x)
    # Now the false branch includes some change to `x` rather than `x` itself
    t2 = b(x)
    ifelse(x > 1, t1, t2)
    y = merge(t1, t2)
    z = y * 2
flow.visualize()
```
![Screen Shot 2020-05-31 at 10 52 31 AM](https://user-images.githubusercontent.com/6130352/83355492-c9a34e00-a32d-11ea-80b0-122d0335c37c.png)

## Environment

```bash
> conda list | grep prefect
prefect                   0.11.2                     py_0    conda-forge
```

**Comment by cicdw** [comment]
Hi @eric-czech - this is behaving strangely because `x = 1` is a constant.  Because of this, it is handled uniquely in each of the 3 calls involving `x`; in particular, each call creates a Task placeholder for the constant that is being referenced, and there is no de-duplication taking place.  To get the image you expect, you should create a task in place of `x` yourself:

```python
@task
def a(x):
    return x + 1

@task
def x():
    return 1

with Flow('f') as flow:
    t = a(x)
    ifelse(x > 1, t, x)
    y = merge(t, x)
    z = y * 2
```

Now each of these calls is guaranteed to reference the same `x` object in the `Flow`.

**Comment by eric-czech** [comment]
Makes sense.  But is the intent of the feature to maintain some kind of logical equivalence across operations regardless of the underlying references, or are visualizations essentially an approximation of what a workflow expresses?

I can understand why it would make some sense to not display constants that have no upstream dependencies, e.g.:

```python
@task
def a(x):
    return x + 1

def flow_1():
    x = 1
    t = a(x)
    c = x > 1
    ifelse(c, t, x)
    merge(t, x)

def flow_2():
    x = 1
    t = a(x)
    c = task(lambda: x > 1)
    c.name = 'condition'
    ifelse(c, t, x)
    y = merge(t, x)
    return y
```

<img width="847" alt="Screen Shot 2020-06-01 at 7 21 41 AM" src="https://user-images.githubusercontent.com/6130352/83404595-f06a8e80-a3d8-11ea-9033-8a8a00d8ada6.png">

But I think that breaks down as soon as constants have both downstream and upstream dependencies (like my OP).  I can also see why `ifelse/switch` my be the only way to make that happen, but the visualization is still incorrect right?

I don't personally care that much about the visualization so much as what is happening in the DAG.  I thought `.visualize` would be my window into that but I can't tell if it's supposed to literally be the DAG itself, some optimized version of the DAG (possibly with optimizations beyond showing/not showing constants to enhance readability), or something in between.

**Comment by cicdw** [comment]
The visualization is a direct, unaltered visualization of the underlying DAG.

> But I think that breaks down as soon as constants have both downstream and upstream dependencies (like my OP)

this is true but adding upstream dependencies to a constant is an anti-pattern (constants don't "run", they are hardcoded values).  All Prefect tasks should perform _some_ unit of work (the Flow should be a workflow in a true sense).  

If you want a DAG view of pure computation I suggest using dask and the visualization tools it includes.

**Comment by eric-czech** [comment]
> this is true but adding upstream dependencies to a constant is an anti-pattern (constants don't "run", they are hardcoded values). All Prefect tasks should perform some unit of work (the Flow should be a workflow in a true sense).

In this case, `ifelse` adds the upstream `as_bool` task ... how would one avoid that?

> The visualization is a direct, unaltered visualization of the underlying DAG

Good to know, but how do I get an unreachable result in that DAG like this then?  It makes perfect sense that Prefect knows nothing about constants like `x = 1`.  In that case though, what is the "1" task hanging off of the "Compare Value: 'False'" branch?  It would make sense that Prefect is wrapping it in a `Constant` instance or otherwise turning it into a task, but why is that task then not connected to the `merge` task?  It seems that the yet-to-be-wrapped constant is auto-magically making its way into the `merge` before the final multiplication .. how then do I see "1" anywhere in the DAG at all?  Perhaps, an exception is made to wrap constants like this in tasks purely for the sake of visualization.

> If you want a DAG view of pure computation I suggest using dask and the visualization tools it includes.

I'm not ultimately very interested in visualization as much as understanding how Prefect works internally.  We're pretty heavy dask users at our company already (you and I met at the DC workshop in Feb) and we're evaluating new workflow engines as we grow the infrastructure.

**Comment by cicdw** [comment]
Ah awesome - nice to "see you" again :D 

I can definitely explain the nitty gritty details here, but just want to caveat them by re-emphasizing that we're playing with an edge case (how Prefect handles constants) that rarely arises in practice.

That being said, let's dive in:

- **constants as standard inputs**: anytime a task references a non-Prefect constant as an input, Prefect stores the value on the Flow in the `constants` dictionary ([code here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L851-L854)).   At runtime these constants are unpacked and wrapped in a `Success` state by the Flow Runner ([code here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/flow_runner.py#L423-L424)).  
- **constants as mapped inputs**: There is one caveat: if the task is _mapping_ over a constant (e.g., `my_task.map([1, 2, 3])`), Prefect stores the constant as a proper Constant Task within the Flow (so you'll actually see this dependency in the DAG view).
- **constants as downstream dependencies**: there are some circumstances where a constant is being referenced as a _downstream_ dependency of a task.  This is very rare, but easily happens with the conditional API (e.g., when using `ifelse`, both conditional tasks are downstream of the condition).  In this case, Prefect creates a proper Constant Task within the Flow that is visible in the DAG.

In your code above, you have a mix of both situations.  Using `flow_1` as an example:

```python
def flow_1():
    x = 1
    t = a(x) # 1 as input, stored in `flow.constants` dictionary
    c = x > 1 # the value `False`
    ifelse(c, t, x) # `False` is added to `flow.constants`, and `1` is added downstream of the compare value task
    merge(t, x) # here again, the number 1 is being used a task input, and once again added to `flow.constants`

with Flow("flow 1") as flow:
    flow_1()

print(flow.constants) 
# defaultdict(dict,
#            {<Task: a>: {'x': 1},
#             <Task: as_bool>: {'x': False},
#             <Task: Merge>: {'task_2': 1}})
```

**Comment by eric-czech** [comment]
Thanks @cicdw.

Seems like that's in line with my guestimations.  Is it worth documenting or rethinking the non-Prefect constant to Prefect constant coercion for the sake of visualizing downstream constants if it doesn't end up being a true representation of what happens in the DAG?  I don't feel strongly about it, but I don't see how users with a use case like ours are likely to not go through the same process.  Feel free to close the issue if not.

By our use case, I mean I'm pushing back on the idea that:

> we're playing with an edge case (how Prefect handles constants) that rarely arises in practice

I say that because in our case a big configuration controls much of *how* the flow is built and what the tasks do, so it ends up being natural to introduce a lot data in the pipeline as constants.  I could alternatively pass the config as arguments to tasks but I'd rather not have to make it an argument to every task.  Giving tasks only the arguments necessary from the config is another option, but then they're still supplied as non-Prefect constants unless I wrap them every time (which isn't unreasonable).  I could also break up the config into individual Parameter instances, but I definitely don't want to go that route.  My point is that I've thought about how to get around this and I don't see an answer.  Perhaps bioinformatics, or more generally use cases where large numbers of parameters are necessary and some control flow construction, is one of those rare cases.

My emphasis on getting an accurate visual representation of what is going to happen in a flow before running it may also be unusual, but it is one of the main reasons it makes sense to use a workflow engine in the first place for us.

**Comment by cicdw** [comment]
> Is it worth documenting or rethinking the non-Prefect constant to Prefect constant coercion for the sake of visualizing downstream constants if it doesn't end up being a true representation of what happens in the DAG?

I actually think it might be worth raising an error if a constant is set as a _downstream_ dependency of a task.

If you're looking to see your constants in the DAG, you can definitely do that using one of two patterns:

```python
@task 
def return_constant():
    return MY_CONSTANT

return_constant = prefect.tasks.core.constants.Constant(MY_CONSTANT)
```
which explicitly tells Prefect you want this elevated.  In the first case with the `@task` decorator Prefect will actually manage the submission and execution of that Task (retries, logs, state handlers, etc.).  But in the latter case Prefect won't actually manage the execution but will display the task in your DAG.

Prefect used to treat every constant as a proper Task but this was particularly painful for our heavy dask users because it crowded their DAG visualizations and their logs.

**Comment by jcrist** [comment]
Checking up on this discussion - is there any action item left for us to do here?

**Comment by eric-czech** [comment]
Not from my perspective, thanks for the help.
