### ISSUE TITLE
LocalResult doesn't work with different drive (Windows 10)

### ISSUE THREAD

**Issue by claforte** [PrefectHQ/prefect#2683]
## Description
Just getting started with Prefect... looks very promising, thanks! I ran into this issue though:

On MS Windows 10, LocalResult seems to only work with a `dir` pointing to the C: drive. It doesn't work for the E: drive. See reproduction example.

This is a major issue on my PCs - they have a very small C: drive, and much larger SSDs on other drives.

## Expected Behavior
LocalResult instantiate without problem and saves results in E: path.

## Reproduction
The following works:
```
from prefect.engine.results.local_result import LocalResult
result = LocalResult(dir="c:/cl/amd/code/dl/mopt/tests/data/result/playground_prefect")
```
If I change the path to use the E: drive instead (`c:/cl/amd/code/dl/mopt/tests/data/result/playground_prefect`), I get this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-26b211f5d685> in <module>
----> 1 result = LocalResult(dir="e:/cl/amd/code/dl/mopt/tests/data/result/playground_prefect")

d:\Users\chris\Anaconda3\envs\miniopt\lib\site-packages\prefect\engine\results\local_result.py in __init__(self, dir, validate_dir, **kwargs)
     33         if (
     34             dir is None
---> 35             or os.path.commonpath([full_prefect_path, os.path.abspath(dir)])
     36             == full_prefect_path
     37         ):

d:\Users\chris\Anaconda3\envs\miniopt\lib\ntpath.py in commonpath(paths)
    619         # caught.
    620         if len(set(d for d, p in drivesplits)) != 1:
--> 621             raise ValueError("Paths don't have the same drive")
    622 
    623         drive, path = splitdrive(paths[0].replace(altsep, sep))

ValueError: Paths don't have the same drive
```

## Environment
Prefect 0.11.1 installed via pip
pwd was in E: drive

`prefect diagnostics`:
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.18362-SP0",
    "prefect_version": "0.11.1",
    "python_version": "3.7.7"
  }
}

**Comment by cicdw** [comment]
Thanks @claforte ! PR opened to fix this [here](https://github.com/PrefectHQ/prefect/pull/2685)

**Comment by claforte** [comment]
Thank you! Your responsiveness is impressive! :-)
