### ISSUE TITLE
Pause flow run output when run reaches a manual trigger

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#2693]
## Current behavior
*Please describe how the feature works today*
When a task with [a manual trigger](https://docs.prefect.io/core/concepts/execution.html#triggers) enters the `Paused` state, output from the execution isn't readable and there's no way to put the run into a `Resume` state locally. 

## Proposed behavior
*Please describe your proposed change to the current behavior*
It would be great if execution paused when it reached a task with a `manual_trigger` and waited for user input of some sort like this:
```
...
[2020-06-01 20:50:02] INFO - prefect.TaskRunner | Task 'ApproveTransfer': Starting task run...
[2020-06-01 20:50:02] INFO - prefect.TaskRunner | Task 'ApproveTransfer': finished task run for task with final state: 'Paused'
[2020-06-01 20:50:02] INFO - prefect.TaskRunner | Task 'ApproveTransfer' requires manual resuming to continue.

Resume task? [y/N]: 

```

## Example
*Please give an example of how the enhancement would be useful*
It would enable local development of flows with manually-triggered tasks.

**Comment by shaunc** [comment]
This is sometimes useful... but currently is getting in the way of local testing of programmatic restart... would be nice if there were a configuration option to turn off.

**Comment by cicdw** [comment]
@shaunc for local testing I recommend not using `flow.run` but instead instantiating a `FlowRunner` directly:
```python
from prefect.engine.flow_runner import FlowRunner

runner = FlowRunner(flow=my_flow)
runner.run() # won't perform any retries / pause input / etc
```

**Comment by shaunc** [comment]
Thanks!
