### ISSUE TITLE
"ImportError: This feature requires graphviz.", but already installed with conda

### ISSUE THREAD

**Issue by claforte** [PrefectHQ/prefect#2700]
## Description
On Windows 10, I created a simple flow and ran `f.visualize()`, I get this error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
d:\Users\chris\Anaconda3\envs\miniopt\lib\site-packages\prefect\core\flow.py in visualize(self, flow_state, filename, format)
   1137         try:
-> 1138             import graphviz
   1139         except ImportError:

ModuleNotFoundError: No module named 'graphviz'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-21-458ec31a105d> in <module>
----> 1 f.visualize()

d:\Users\chris\Anaconda3\envs\miniopt\lib\site-packages\prefect\core\flow.py in visualize(self, flow_state, filename, format)
   1142                 "Try re-installing prefect with `pip install 'prefect[viz]'`"
   1143             )
-> 1144             raise ImportError(msg)
   1145 
   1146         def get_color(task: Task, map_index: int = None) -> str:

ImportError: This feature requires graphviz.
Try re-installing prefect with `pip install 'prefect[viz]'`
```

My conda environment (miniopt.yml) already contains these lines:
```
- graphviz
- conda-forge::prefect
- conda-forge::prefect[viz
```

I just did a `conda env update -f miniopt.yml` and there were no errors.

**NOTE**: I also previously tried using this instead in my miniopt.yml...:
```
 - pip:
  - prefect
  - prefect[viz]
```
... it didn't work either.

## Expected Behavior
Display the graphviz diagram for the flow.

## Reproduction
The example in https://docs.prefect.io/core/examples/cached_task.html where I replaced `flow.run()` with `flow.visualize()`.

## Environment
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.18362-SP0",
    "prefect_version": "0.11.4",
    "python_version": "3.7.7"
  }
}

**Comment by jcrist** [comment]
This is a bit confusing. There's two libraries here:

- The `graphviz` cli, a native application
- The Python `graphviz` library, a python wrapper that requires the `graphviz` library also be installed

If you're using conda to manage dependencies, you need `graphviz` (the CLI) and `python-graphviz` (the python library, which depends on `graphviz`).

Note also that conda doesn't handle extras (the `[viz]` part of `prefect[viz]`) like pip - your conda dependency of 

```
conda-forge::prefect[viz]
```

is interpreted as

```
conda-forge::prefect
```

(I'm actually surprised that conda doesn't error with the `[viz]` bit).

---

So for prefect installed via conda, you'll want the following to enable viz support:

```
conda install -c conda-forge prefect python-graphviz
```

**Comment by claforte** [comment]
Thanks Jim! Adding `python-graphviz` did the trick! Have a great day!
