### ISSUE TITLE
Pass a State Handler to a Flow that also applies to all Tasks in the Flow

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#2701]
## Current behavior
*Please describe how the feature works today*
Today, you can pass a State Handler to a Flow and to each of its Tasks individually. However, if you want a State Handler to report on all states in a Flow and _all_ of its Tasks, you need to pass a state handler to each `@task` decorator or class.

If a user wants to add a state handler to push all state updates for a Flow to a monitoring service like Cloudwatch, they have to manually add state handlers to each `@task` and the `Flow()`

## Proposed behavior
*Please describe your proposed change to the current behavior*
We could expose some sort of configuration for state handlers on the flow level so that they'd also apply to all tasks in the flow. Something like:

`with Flow(state_handlers=[cloud_watch_handler], state_handler_run_on_tasks=True)`

## Example
*Please give an example of how the enhancement would be useful*
It allows users to more easily record state change events in a third party system.

**Comment by bnaul** [comment]
I'd be interest in contributing this; my first thought was just a separate argument rather than the boolean flag:
```
Flow(state_handlers=[flow_specific_handler], task_state_handlers=[something_different_that_applies_to_states])
```
Either way it's 1 new kwarg, but the separate arg is strictly more flexible compared to the boolean version. Anything I'm missing that might make this a bad idea....? cc @cicdw

**Comment by madkinsz** [comment]
I do not think the flow state handler should be reused for tasks, so I agree with you @bnaul. I think this may need to be `default_task_state_handlers` and ignored entirely if the task has any state handlers _or_ `task_state_handlers` and we always call the flow level task state handlers either _before_ or _after_ the given task's handlers. I think the second option is more complicated but probably more correct. I think they should probably be run after the task's handlers but I'm not sure.

**Comment by cicdw** [comment]
Yea, +1 for a new kwarg that accepts a list of state handlers.  I also agree that they should always be called along with the task's own state handlers, and I don't have a strong opinion about whether they should be called before or after.

**Comment by Kazmirchuk** [comment]
+1
does anyone have a workaround, until this is implemented? a custom decorator based on @ task?

**Comment by EmilRex** [comment]
@bnaul As a workaround, could you monkey-patch `task` with `partial` to achieve the desired behavior? Something like:

```py
from functools import partial
from prefect import flow, task


def state_handler(task, task_run, state):
    print("Running on_failure state handler")

task = partial(task, on_failure=[state_handler])


@task
def say_hello():
    raise ValueError("Goodbye")


@flow
def hello():
    try:
        say_hello()
    except ValueError:
        print("Caught an error")


if __name__ == "__main__":
    hello()
```
