### ISSUE TITLE
Visualization not represented correctly when adding task to amother flow

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#2723]
## Description
Hi - I am trying to join flows on a common parameters.  However in the visualization the `parameter` task is represented by an id.  

![image](https://user-images.githubusercontent.com/16763201/83828400-2d1eda00-a6a6-11ea-8a33-97596760a3a9.png)

@cicdw could this issue be similar to #1793 ?  

## Expected Behavior
An edge from the parameter to all the appropriate tasks.

### Flow1
```
@task
def add_one(a_number: int): 
    return a_number + 1

@task(log_stdout=True)
def print_result(the_result:int): 
    print(the_result)

with Flow("Add") as add_fl:
    a_number = Parameter("a_number", default=1)
    
    the_result = add_one(a_number)
    
    print_result(the_result)

add_fl.visualize()
```
![image](https://user-images.githubusercontent.com/16763201/83828557-90107100-a6a6-11ea-9a03-b453e73f5bd3.png)

### Flow2
```
@task
def sub_one(a_number: int):
    return a_number - 1


with Flow("Subtract") as subtract_fl:
    
    a_number = Parameter("a_number", default=1)
    
    the_result = sub_one(a_number)
    
    print_result(the_result)
    
subtract_fl.visualize()
```
![image](https://user-images.githubusercontent.com/16763201/83828872-45dbbf80-a6a7-11ea-92d1-0ce99b42b77a.png)

### Add Tasks and Edges
```
flow1 = add_fl.copy()
flow2 = subtract_fl.copy()

for task in flow2.tasks:
    task_lst = flow1.get_tasks(slug=task.slug)
    
    if len(task_lst)>0:
        print(f"Duped Tasks on Slug: {task_lst}")
    else:
        flow1.add_task(task)
        
for edge in flow2.edges:
    if edge not in flow1.edges:
        flow1.edges.add(edge)

flow1.visualize()
```
![image](https://user-images.githubusercontent.com/16763201/83828400-2d1eda00-a6a6-11ea-8a33-97596760a3a9.png)

## Environment
prefect version `0.11.5+75.g525fb25a6`

**Comment by cicdw** [comment]
Hi @gryBox - actually this is more subtle than that issue.  Here's what's happening:

- you create flow 1 with a Parameter named `a_number`, which becomes the `slug` (Parameter names must be unique within a Prefect Flow since they are identified by name through kwargs / the API)
- your merge logic _only_ adds tasks to `flow1` if a task with the same slug is not already present; this means that the `Parameter` object from `flow2` is _not_ added to `flow1`
- you now have a merged flow with an `Edge` that references an upstream task object that is _not_ present in the Flow (namely the `a_number` task from flow1)

To make this more precise / concise:
```python
for param in [e.upstream_task for e in flow1.edges if e.upstream_task.name == "a_number"]:
    print(param in flow1.tasks)
```
which will print one `True` and one `False`.  This means that one of the edges in your Flow references a Task object which is not actually present in the Flow.

I think the fundamental issue here is that you're identifying Python objects (the instantiated Parameter classes) with their slugs.

**Comment by gryBox** [comment]
@cicdw Thank you.  I renamed the issue and closed it.  What are your thoughts on adding this type of _optional_  functionality to `flow.update`?
![image](https://user-images.githubusercontent.com/16763201/83932176-6d459180-a766-11ea-807b-a1d96431e92d.png)


This is the monstrosity I came up with. 
- I am not sure what kind of conflicts can arise. .i.e. targets. task names vs slugs.
- I tried to incorporate `flow.replace` but was ultimately unsuccessful with that approach.
### Tasks
```
for task in flow2.tasks:
    task_lst = flow1.get_tasks(slug=task.slug)
    if len(task_lst)>0:
        print(f"Duped Tasks on Slug: {task_lst}")
    else:
        flow1.add_task(task)

flow1.visualize()
```
![image](https://user-images.githubusercontent.com/16763201/83932273-18564b00-a767-11ea-9f76-cb43d2de7767.png)

### Edges
```
for edge in flow2.edges:
    
    if any([e.upstream_task for e in flow1.edges if e.upstream_task.slug == edge.upstream_task.slug]):
        upstream = flow1.get_tasks(slug=edge.upstream_task.slug)[0]
    else:
        upstream = edge.upstream_task
    
    if any([e.downstream_task for e in flow1.edges if e.downstream_task.slug == edge.downstream_task.slug]):
        downstream = flow1.get_tasks(slug=edge.downstream_task.slug)[0]
    else:
        downstream = edge.downstream_task  

    flow1.add_edge(
        upstream_task=upstream,
        downstream_task=downstream,
        key=edge.key,
        mapped=edge.mapped,
        validate=True
    )
flow1.visualize()
```
![image](https://user-images.githubusercontent.com/16763201/83932176-6d459180-a766-11ea-807b-a1d96431e92d.png)

**Comment by cicdw** [comment]
Hey @gryBox just seeing this - I definitely think it could be appropriate to special-case Parameters  in `flow.update` so they are merged based on name.
