### ISSUE TITLE
Gracefully recover from version lock errors

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2731]
## Current behavior
*Please describe how the feature works today*

When setting a state results in a version-lock error, the attempt is aborted and progress stops.

## Proposed behavior
*Please describe your proposed change to the current behavior*

Related to #2730, whenever a version-lock error is encountered, the Client should instead query for the latest state and return it so process can continue. This will enable graceful fallbacks from the latest known state. The only exception is if the latest state is one that *requires* a version lock, like RUNNING or SUBMITTED, because version-locked states indicate run-once semantics.

## Example
*Please give an example of how the enhancement would be useful*

**Comment by joshmeek** [comment]
@jlowin How exactly are version-lock errors encountered for setting states that won't require a version (after #2370)?

**Comment by jlowin** [comment]
The most current proposal is actually that version-locking won't be required for any state (slightly different from what I wrote in this issue), and is entirely a client-side mechanism: pass a version, and a version lock will be enforced. By convention, we would always pass versions for `RUNNING` and `SUBMITTED` states from the client. For other states, without a passed version, there wouldn't be a version lock error because the version wouldn't be checked.

**Comment by joshmeek** [comment]
So this means that if the state you are setting isn't `RUNNING` or `SUBMITTED` and you are passing a version then it should be gracefully handled in the case of a version-lock error?
