### ISSUE TITLE
Add descriptions for tasks / flows

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2749]
Elevating this out of a related request: https://github.com/PrefectHQ/prefect/issues/2254#issuecomment-608055176

**Comment by madkinsz** [comment]
See https://github.com/PrefectHQ/ui/pull/563

**Comment by johnurbanik** [comment]
I'd love to be able to add these descriptions programmatically without interacting with the API. Is that possible now (via graphql maybe?) and could support for this be added to core? I assume something is on the roadmap given that this issue has not been closed.

**Comment by cicdw** [comment]
Hi @johnurbanik - you can programmatically update a Flow Group's README / description following the instructions here: https://github.com/PrefectHQ/prefect/issues/4154#issuecomment-785282344
