### ISSUE TITLE
DFE for downstream tasks

### ISSUE THREAD

**Issue by jacques-** [PrefectHQ/prefect#2753]
## Current behavior

I've just had a quick look at DFE in master #2646 and it works really awesome!

That said I've noticed something that is a bit odd, if I have a mapped task that is upstream from a task that doesn't take data from the mapped task it still does DFE. 

Is there / will there be a way to disable DFE or run a reduce task explicitly?

So in a situation like:
```
with Flow("dummy_flow") as flow:
    list_data = task_a()
    task_b_slug = task_b.map(data=list_data).slug
    task_run_me_once_after_task_b(upstream_tasks=[flow.get_tasks(slug=task_b_slug)])
```

task_run_me_once_after_task_b is run many times. This of course makes sense if it takes data from task_b, but if it jus sets a status after task_b has finished running of does clean-up then you'd want to be able to disable DFE.

## Proposed behavior

If there is a task downstream from a DFE mapped task that takes no output from the mapped task, the downstream task would default to not being "DFE" mapped as well.

## Example

In our use-cases we have clean-up functions that run at the end of mapped tasks that don't take data from the mapped output to work and they need to run only once.

**Comment by cicdw** [comment]
Hi @jacques- - I can't recreate this.  I tried with the `LocalExecutor`, `DaskExecutor`, and `LocalDaskExecutor` and each time I only saw one run of `task_run_me_once_after_task_b`.

How did you determine the task is running multiple times?

Here's the code I used:
```python
from prefect import Flow, task
from prefect.engine.executors import DaskExecutor
from prefect.engine.executors import LocalDaskExecutor

@task
def task_a():
    return [1, 2, 3, 4]

@task
def task_b(data):
    return data

@task
def task_run_me_once_after_task_b():
    print('im running')
    print('=' * 50)

with Flow("dummy_flow") as flow:
    list_data = task_a()
    task_b_slug = task_b.map(data=list_data).slug
    task_run_me_once_after_task_b(upstream_tasks=[flow.get_tasks(slug=task_b_slug)])

flow.run() # LocalExecutor

flow.run(executor=DaskExecutor())

flow.run(executor=LocalDaskExecutor())
```
All printed only once.

**Comment by cicdw** [comment]
Hi @jacques- yea see my comment https://github.com/PrefectHQ/prefect/issues/2752#issuecomment-642843760 on your use of `upstream_tasks`.

The `LocalDaskExecutor` is known to rerun tasks when using mapping

**Comment by jacques-** [comment]
I've re-written using the imperative API as in #2752 and using the DaskExecutor it all works as expected, thanks for all the help here - can't wait for DFE to land!
