### ISSUE TITLE
Add a --no-cache option to prefect server start command

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#2759]
## Description
I'm deploying the Prefect Server on a remote Docker Host. I therefore change the address for `server.ui.graphql_url` in `config.toml` to reflect this. However this isn't reflected in UI, which keeps referring to `localhost`. It does show in the deployment logs though.
![image](https://user-images.githubusercontent.com/44194839/84272999-764fad80-ab2e-11ea-9c38-0af2b2602cf6.png)
![image](https://user-images.githubusercontent.com/44194839/84273038-823b6f80-ab2e-11ea-9099-11ae8641e90c.png)

## Expected Behavior
I expected the address to be replaced.

## Reproduction
1) set `DOCKER_HOST` to use remote Docker. In my case I have called it` srvdocker01`
2) use the following `config.toml`

```
backend = "server"

[server]
host = "http://srvdocker01"
port = "4200"
host_port = "4200"
endpoint = "${server.host}:${server.port}"
	
   [server.graphql]
    host = "srvdocker01"

	[server.ui]
    host = "http://srvdocker01"
    port = "8081"
    host_port = "8081"
    endpoint = "${server.ui.host}:${server.ui.port}"
    graphql_url = "http://srvdocker01:4200/graphql"
```
3) run `prefect server start`
4) go to http://srvdocker01:8081

## Environment
```
>prefect diagnostics
{
  "config_overrides": {
    "backend": true,
    "server": {
      "endpoint": true,
      "graphql": {
        "host": true
      },
      "host": true,
      "host_port": true,
      "port": true,
      "ui": {
        "endpoint": true,
        "graphql_url": true,
        "host": true,
        "host_port": true,
        "port": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.18362-SP0",
    "prefect_version": "0.11.5",
    "python_version": "3.7.0"
  }
}
```

**Comment by thomasfrederikhoeck** [comment]
Does this means it is fixed, or that is deemed unnecessary to fix ? A simple fix would be to at a `--no-cache `  option to `prefect server start` that would be given to `docker-compose up` such that the user doesn't have to do the cleaning themselfs in Docker.

**Comment by cicdw** [comment]
Hi @thomasfrederikhoeck apologies I didn't see the possible action item lurking in your comment above - reopening to consider the `--no-cache` option

**Comment by thomasfrederikhoeck** [comment]
No worries @cicdw
