### ISSUE TITLE
Update configuration doc section about automatic type casting

### ISSUE THREAD

**Issue by Marlin-Na** [PrefectHQ/prefect#2788]
Hello!

This should be a minor doc issue.

```
Prefect will do its best to detect the type of your environment variable and cast it appropriately.

    "true" (with any capitalization) is converted to True
    "false" (with any capitalization) is converted to False
    strings that parse as integers are converted to integers
    strings that parse as floats are converted to floats
    all other values remain strings
```

Page reference: https://docs.prefect.io/core/concepts/configuration.html

It seems that 'None' is also converted to python's None? I do like this behavior but want to ensure this is intended.

**Comment by joshmeek** [comment]
Thanks for the callout @Marlin-Na! Yes this should be updated and actually needs to change a bit more. A few releases ago changed some configuration parsing/eval and there are other aspects which are converted to python types as well (such as lists).
