### ISSUE TITLE
Docker-based environments still assume docker storage

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2791]
In #2666 support was added for storing image names in environment metadata, to allow for non-docker storage with docker-based agents. However, not all (any?) of the corresponding environments were updated to allow for this. For example, `KubernetesJobEnvironment` still assumes a `.name` attribute on the corresponding storage.

https://github.com/PrefectHQ/prefect/blob/26518173cf722c742eefcae970260edb5e385f54/src/prefect/environments/execution/k8s/job.py#L114

The environments should be updated to check for either `self.metadata.image` or `storage.name`.

**Comment by jameslamb** [comment]
I _think_ that I just hit this issue, using a `KubernetesAgent` to run a flow stored with `S3` storage. I want to include this error message to help people coming from search engines find this issue

> [2020-06-18 17:55:21,643] ERROR - agent | Error while deploying flow: ValueError('Storage for flow run 1538c4c2-30a1-439a-b328-a1a40ec1e0dd is not of type Docker and environment has no `image` attribute in the metadata field.')            

If I'm wrong about that, I apologize and would be happy to delete this comment
