### ISSUE TITLE
"prefect auth login" without storing credentials on disk

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#2793]
## Current behavior

Following the [Authenticating with Prefect Cloud documentation](https://docs.prefect.io/orchestration/tutorial/configure.html#authenticating-with-prefect-cloud), one might get a [USER token](https://docs.prefect.io/orchestration/concepts/tokens.html#user) and pass it in to the CLI with code like this:

```shell
MY_USER_TOKEN="some-secret-stuff"
prefect auth login -t ${MY_USER_TOKEN}
```

I learned today if that login is successful, this command creates a directory at `${HOME}/.prefect`, with contents like the following:

```shell
.
└── client
    └── https-api.prefect.io-graphql-alpha
        └── settings.toml
```

`settings.toml` looks like this (but with real values with real values in plaintext, not the silly ones I used here)

```toml
active_tenant_id = "some-uuid"
api_token = "some-secret-stuff"
```

## Proposed behavior

I have two proposals:

### 1. Allow users to opt out of this behavior

I propose at least giving users the option to opt out of this behavior, by adding a flag like `--no-save`, `--do-not-store-credentials`, or something else which says "your token and other relevant environment variables recognized by `prefect` will be set, but once you close this shell that information will disappear".

### 2. Document the behavior 

I was surprised by this behavior, and I propose that https://docs.prefect.io/orchestration/tutorial/configure.html#authenticating-with-prefect-cloud should call out the fact that `prefect auth login` stores credentials in plaintext and that its effect is that you stay logged in indefinitely, between terminal sessions.

## Example

The current behavior was surprising to me. I expected that `prefect auth login` would log my session in *as long as that shell was active*, not that all `prefect` code I use on this machine would automatically auth however I did the first time I ran that command. Making this behavior more explicit and opt-in would reduce the risk of me running code in a Prefect account other than the one I intend to run in. That might, for example, prevent me from running code intended for a `staging` account while authenticated as a user in a `production` account.

I also think that having credentials stored in plaintext files is a security risk. I know that other CLIs do this and that `prefect` has users already depending on this behavior so I'm not proposing breaking it...but I think it would be good to explicitly document this at https://docs.prefect.io/orchestration/tutorial/configure.html#authenticating-with-prefect-cloud

If both my suggestions are accepted, that section in the documentation might have a warning like this:

> `prefect auth login` will store your credentials in `${HOME}/.prefect` and re-use them the next time you run any `prefect` code. To opt out of this behavior, use the `--do-not-store-credentials` flag.

--------------

Thanks for your time and consideration! If you agree, I'd be happy to submit PRs to help with one or both of the proposals.

**Comment by lauralorenz** [comment]
Hi @jameslamb! Talking to the other core peeps, we think your proposal to provide an opt-in flag to avoid saving the credentials is a good idea (which by extension should probably come with some extra docs anyways that explains the default behavior, so we kind of want both :) ). If you are interested in opening a PR, we would love to see it! :)

**Comment by jameslamb** [comment]
Ok sure! I would definitely like to contribute this.

**Comment by jameslamb** [comment]
I've been thinking about this issue, and now that I've read more of the `prefect` internals, I don't think the flag thing I proposed originally is the simplest way to accomplish the goal.

I think it would be better to:

* have the client recognize environment variable `PREFECT__CLOUD__AUTH_TOKEN` for the api token  (in https://github.com/PrefectHQ/prefect/blob/4a4acb5569697ed9c28518c00e7faaf5bf2a033e/src/prefect/client/client.py#L106-L120)
* have the client recognize environment variable `PREFECT__CLOUD__TENANT_ID` for the tenant ID
* change docs to reflect that `prefect auth login` is "the thing you use to login in once and have it persist across multiple shells", similar to [how `aws configure` works](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

I think this would allow users to achieve the goal of authenticating without every writing sensitive information to a local file in plaintext.

The experience I'm imagining is similar to what you can do with AWS CLI, for example:

```shell
export AWS_ACCESS_KEY_ID=some-key-id
export AWS_SECRET_ACCESS_KEY=some-key

aws s3 ls
```

What do you think? I'd be happy to propose a pull request with these changes if you agree.

**Comment by kingsleyb** [comment]
Hi @jameslamb, thank you for providing an update on this ticket. We have work that addresses authentication on our internal roadmap for this quarter, so it will be best to wait for these changes. I'll provide an update here as we have them.

**Comment by jameslamb** [comment]
Sure, I won't do anything on this until I hear back. Thanks.

**Comment by arogozhnikov** [comment]
Hi, is there any progress in this direction?

I'm interested in being able to define run from another machine (and would like other members of team to do the same), but it looks like we should put prefect keys to every machine, doesn't sound like a good idea.
