### ISSUE TITLE
Docs for Prefect Server

### ISSUE THREAD

**Issue by xiyelew** [PrefectHQ/prefect#2799]
## Current behavior
Currently we have tutorials for Prefect Core. Those are simple to run. However, I couldn't find the analogous examples for Prefect Server.

## Proposed behavior
Add tutorials for Prefect Server. I know I should start with `prefect server start` and `prefect backend server` to get Prefect Server running. But how do I get the Prefect Core tutorials to run on Prefect Server? There should be examples of this.

**Comment by joshmeek** [comment]
Thanks for the request @xiyelew! We do have some documentation in the [Orchestration Deployment Tutorial](https://docs.prefect.io/orchestration/tutorial/configure.html#configure-your-environment) around this for now. But I agree we should expand the tutorial to cover some concepts / getting started for the server. Marking this as a docs ticket

**Comment by xiyelew** [comment]
Actually that was already extremely helpful. From your link I was able to figure out that what I was missing was setting up an agent. I guess I didn't think of looking under "deployment", as I'm still learning the ropes.

**Comment by lauralorenz** [comment]
I am going to close this specific issue for now as more docs on server deployment is part of a larger initiative instead of representing it as this one-off issue. Glad you could get everything figured out @xiyelew :) welcome to Prefect!
