### ISSUE TITLE
Clarify the fact that client.Client's auth behavior depends on import order

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#2812]
## Current behavior

["Authenticating with Prefect Cloud"](https://docs.prefect.io/orchestration/concepts/api.html#authenticating-the-client-with-cloud) includes the following note:

> Note that a token can be provided by environment variable (`PREFECT__CLOUD__AUTH_TOKEN`) or in your Prefect config (under `cloud.auth_token`)

I've obvserved that this is only true _if you set that environment variable before importing prefect_.

Consider this example, run in an environment where `~/.prefect` does not exist (so `prefect auth login` has not been run yet) and where `PREFECT__CLOUD__AUTH_TOKEN` has not been defined.

```python
import prefect
import os
from prefect.client import Client
os.environ["PREFECT__CLOUD__AUTH_TOKEN"] = "some-token"

client = Client()
print(client._api_token)
```

> None

If I switch this around so that the variable is set before importing `prefect`, the behavior is as expected.

```python
os.environ["PREFECT__CLOUD__AUTH_TOKEN"] = "some-token"
import os

import prefect
from prefect.client import Client

client = Client()
print(client._api_token)
```

> some-token

<details><summary>details of my environment</summary>

`conda info`

```
     active environment : None
       user config file : /home/jlamb/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/jlamb/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jlamb/miniconda3/pkgs
                          /home/jlamb/.conda/pkgs
       envs directories : /home/jlamb/miniconda3/envs
                          /home/jlamb/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/5.3.0-7625-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

`prefect diagnostics`

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.3.0-7625-generic-x86_64-with-debian-buster-sid",
    "prefect_version": "0.12.0",
    "python_version": "3.7.6"
  }
}
```

</details>

## Proposed behavior

I'll leave it to maintainers to decide between these, because I'm unsure what the impact is and if I know I don't have all the context to understand the current behavior:

* explicitly document in https://docs.prefect.io/orchestration/concepts/api.html#authenticating-the-client-with-cloud that import order matters, since `import prefect` runs some code that updates a config, resulting in environment variables being ignored

* change the behavior of `Client` to get tokens with the following preference:
    1. passed in explicitly to `api_token` keyword arg
    2. `PREFECT__CLOUD__AUTH_TOKEN` environment variable
    3. stored in `config.cloud.auth_token` (which gets populated from reading in a file when `import prefect` is run)

## Example

I think that this is unexpected behavior. I can imagine a few situations where that environment variable might be set by code instead of already present in the environment, including:

* read in at run time from a secrets manager
* read in from a user-specified file

It's a common practice in Python to run all imports at the beginning of a module / script, so this behavior is something that I expect many users will run into.

Thanks for your time and consideration!

**Comment by jcrist** [comment]
> I've obvserved that this is only true if you set that environment variable before importing prefect.

Environment variables are generally assumed not to change once a process starts - they're for updating settings from outside a process, usually there's a better way once you're inside the process. This is not unique to Prefect, Dask (and many other libraries) also have config that works this way. FWIW we haven't noticed this being a confusing point for other users yet, but your issue has been noted.

> I think that this is unexpected behavior. I can imagine a few situations where that environment variable might be set by code instead of already present in the environment, including:
>
> - read in at run time from a secrets manager
> - read in from a user-specified file

Prefect's config (like dask's config) is a combination of:
- Things set in a file (usually at `~/.prefect/config.toml`
- Environment variables corresponding to key names in that config
- Things set at runtime by updating `prefect.config`

See our docs here for more information: https://docs.prefect.io/core/concepts/configuration.html

If you wanted to update the config after starting the process, you can do so by updating settings explicitly on `prefect.config`. For example:

```python
import prefect.config
prefect.config.cloud.auth_token = my_fancy_way_of_getting_the_token()
```

Does that help? Are the docs at https://docs.prefect.io/core/concepts/configuration.html sufficient, or is there a better way we could document this?

**Comment by jameslamb** [comment]
Thanks @jcrist . I had never seen that doc, this line would have helped me avoid this confusion

> The configuration file is parsed when Prefect is first imported and is available as a live object in prefect.config.

Since it sounds like the behavior I've documented here is expected, I think it would be useful to say that right under the line I've quoted above. Something like

>  Environment variables set after `import prefect` will not have any effect on this config.

I also think it would be valuable to be clearer in the documentation about the order of priority for these different options. What happens if I have a `config.toml` with one value for an environment variable and I set the same environment variable directly with a different value?

Thanks for you time and for the amazing docs!

**Comment by jcrist** [comment]
> I also think it would be valuable to be clearer in the documentation about the order of priority for these different options. What happens if I have a config.toml with one value for an environment variable and I set the same environment variable directly with a different value?

Is that not covered by https://docs.prefect.io/core/concepts/configuration.html#user-configuration? Is there a way we could make this clearer?

**Comment by jameslamb** [comment]
> Configuration values set via environment variable have the highest priority; they will be respected even if a user configuration exists. User configuration files, in turn, have precedence over the default values

yep, that's super clear!  I definitely missed that, sorry 😬 . This can be closed.
