### ISSUE TITLE
Non root prefect images

### ISSUE THREAD

**Issue by gardnerdev** [PrefectHQ/prefect#2824]
Hey! For deploying prefect I need to use non root images. It will be perfect to have all Prefect components/images running as nonsuperuser.

**Comment by jcrist** [comment]
Hi @rafal0502, thanks for the issue report, this is definitely solvable. A few questions:

- Are you talking about the images used to run [prefect server](https://docs.prefect.io/orchestration/#prefect-core-server), or images for other components like [agents](https://docs.prefect.io/orchestration/agents/overview.html) or [environments](https://docs.prefect.io/orchestration/execution/overview.html)?
- Do you care which uid/gid the images run as, or just that their not root? Some deployment backends (e.g. openshift) have restrictions on the uid used beyond being "not root".

**Comment by rafal0502** [comment]
Hi @jcrist . I meant - all of the prefect components -server, agents, ui.... Standard for gid and uid is 1000 I quess. Most of the services only care about the ID not name of the user to verify rootless

**Comment by saravanpa-aot** [comment]
Hi @gardnerdev @jcrist Any update on this? Looking for nonroot images as well

**Comment by madkinsz** [comment]
@saravanpa-aot Please don't ping people on an issue that is years old. I see you're already following https://github.com/PrefectHQ/prefect/issues/6888 — that will be the tracking issue for this request.
