### ISSUE TITLE
Register Lock Flow Version

### ISSUE THREAD

**Issue by VenturaFranklin** [PrefectHQ/prefect#2844]
## Current behavior
Running the basic example
```python
import prefect
from prefect import task, Flow

@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Hello, Cloud!")

flow = Flow("hello-flow", tasks=[hello_task])
```
When I go to register this flow using `flow.register()` it registers a new version of the flow with the prefect API. But then if I run `flow.register()` again. It registers a new version. Every call registers a new version, but the flow itself has not changed. I have tried setting the project_name and version_group_id parameters to lock the flow version but those do not work. eg. `flow.register(project_name="TEST", version_group_id="123456")`
## Proposed behavior
I would like a way to track the flow itself. A UUID to the register function that lets the prefect API know that the flow has not changed and do not change the version number
## Example
This would allow me to keep track of flows themselves. Between restarts of my application, the flow is not changing, I could see the runs that are for a specific flow version. If there is an error, I can fix the error, bump the flow version, and then run the flows. This would maybe be useful running flows on multiple computers talking back to prefect cloud?
## Setup
I am using:
prefect 0.12.0
Python 3.8

**Comment by joshmeek** [comment]
Hey @VenturaFranklin every registration of a flow will increment it's version in the backend. There are some changes coming soon which open up a different route into registration where code changes don't require registration but they may not be related.

> Every call registers a new version, but the flow itself has not changed.

You do not need to reregister your flow if you do not change any of the code. Once it is registered once then the backend can be used to run the flow as much as you want without registration.

> This would allow me to keep track of flows themselves. Between restarts of my application, the flow is not changing, I could see the runs that are for a specific flow version. If there is an error, I can fix the error, bump the flow version, and then run the flows.

This is how the current registration process works. You register once and only need to reregister if the code is changed.

**Comment by VenturaFranklin** [comment]
@joshmeek Got it, that makes perfect sense. It seems obvious now! 
After registering, save the id locally and when restarting the application grab the id and use that and do not register again.
Thanks for your help!
