### ISSUE TITLE
Executor submit and wait interfaces are asymmetrical

### ISSUE THREAD

**Issue by c-thain-code** [PrefectHQ/prefect#2847]
## Current behavior

The API docs and the comments in the code (src/prefect/engine/executors/base.py) suggest (to me) that `submit()` returns a `Future` and that the arguments subsequently provided to `wait()` will also be `Future` objects. This makes perfect sense; however, the default `FlowRunner` class treats `Executor.submit()` and `Executor.wait()` asymmetrically, specifically:

- `submit()` is called with a function to execute and is expected to return "a future-like object"
- `wait()` is called with the `futures` arg set to a `Dict[Task, Future]`.

This is a bit unexpected and not intuitive.

## Proposed behavior

Since the `FlowRunner` class is the one calling `submit()`, it therefore has access to the returned `Future` in full context and should perform the mapping from the `Task` to it's `Future` object. For each `final_task` it should be calling `executor.wait()` with the `Task`s `Future` object returned from `submit()`, not the `Dict[Task, Future]`.

The current implementation seems to complicate the `Executor` interface since the executor doesn't really need to know about tasks or states, just how to manage execution of a function.

## Example

Consider the following example using the `concurrent.futures.ThreadPoolExecutor` from the python stdlib as what I would expect the behavior to be (supporting code removed for brevity):

```python
import concurrent
import contextlib
import prefect
class MyExecutor(prefect.engine.executors.base.Executor):
    def __init__(self):
        super().__init__()
    @contextlib.contextmanager
    def start(self):
        self.exec = concurrent.futures.ThreadPoolExecutor()
        yield self.exec
    def submit(self, fn, *args, **kwargs):
        return self.exec.submit(fn, *args, **kwargs)
    def wait(self, futures):
        results = []
        for f in futures:
            results.append(f.result()) # block until future returns
        return results
```

**Comment by jcrist** [comment]
Hi @c-thain-code. You're correct that the documentation here is a bit off. Dask handles collections of futures just fine, so the code consuming the `Executor` interface in prefect evolved towards using that implicitly. In practice this hasn't caused any issues - the `Executor` interface isn't really user-facing (except in configuration) - we don't expect users to be calling `submit` or `wait` themselves.

We could amend the wait calls in the flow runner to unpack/repack the futures themselves, but a `concurrent.futures.ThreadPoolExecutor` still won't satisfy the interface itself - sometimes uncompleted futures are submitted as args with `submit` (which the `concurrent.futures` interface doesn't support). Dask handles this just fine, and supporting this unlocks performance benefits for us. With some work we might be able to rearrange things here as well, but as I said above - this hasn't been an issue in practice.

Do you have a use case here that would require these changes?

**Comment by c-thain-code** [comment]
Thanks for the response. After digging into this a bit more yesterday I would say that this issue is strictly a documentation request to clarify the inputs and outputs of the `Executor.submit` and `Executor.wait` signatures so that they are accurate for potential authors of custom `Executor` implementations. I understand why the interface has evolved to its current form and I don't think it needs to be changed. Please feel free to update the title of the issue to capture this as you see fit.

My use case is that we have an environment that requires a customized `Executor`, which happily the prefect API supports a la `flow.run(executor=MyCustomExecutor(...))`. My executor was failing due to my naive implementation of `wait`, which was based on my understanding of the documentation in the code and API docs. To be clear, I'm not calling `wait` or `submit` directly, simply passing my executor to `flow.run()` and these methods get called in due course by the `FlowRunner` (we're using the default `prefect.engine.FlowRunner`)

During my experimentation I did notice that `concurrent.futures.ThreadPoolExecutor` does not work in some cases with uncompleted futures; but as you mentioned, practically speaking this is not an issue since Dask handles this fine and I see no reason to need to deviate from Dask. My `ThreadPoolExecutor` example was contrived to demonstrate the interface I expected base on the docs.

It's worth adding here, though not relevant to this issue, that I have been thoroughly impressed with Prefect so far (we're migrating from Airflow).

**Comment by jcrist** [comment]
So the goal here is for you to implement a custom executor? If we wanted to support this, I think we'd want to make it simpler - right now the unpacking semantics of `wait` are "whatever dask does". Fixing our usage of wait would only require some bookkeeping on our end, so this is doable. We'd need to keep the same `submit` semantics - but an implementation that couldn't efficiently support futures as args could internal call `wait` to resolve those before finishing `submit`.

Out of curiosity, what kind of executor are you trying to write?

**Comment by c-thain-code** [comment]
> So the goal here is for you to implement a custom executor?

Yes, and I've got it working now.

> right now the unpacking semantics of wait are "whatever dask does", which is a bit complicated.

Understood. I don't think there's any value in having Prefect replicate/refactor the unpacking that Dask does to support some off-nominal edge case like we have. I've achieved what I need to by wrapping the `DaskExecutor`.

> Out of curiosity, what kind of executor are you trying to write?

There are some very specific (to us) things that we need to do pre/post execution. It may be possible to handle those elsewhere, in some other way but when I saw that I could simply provide a custom `Executor` for our flows it seemed like the right fit. Then I spent a few hours trying to understand why things weren't working as I expected and figured out that it was my misunderstanding of the `wait` interface, in particular.  I have everything working now the way that I want but thought it may be worth while to raise an issue in case others hit the same thing that I did while trying to provide a custom executor.

**Comment by jcrist** [comment]
> There are some very specific (to us) things that we need to do pre/post execution.

If you're using cloud or server, you can add a `on_start` and `on_exit` callbacks to the `Environment` - see https://docs.prefect.io/orchestration/execution/overview.html#environment-callbacks.

If you're running locally, would adding such callbacks to the `Executor` interface be sufficient for your use case?

**Comment by c-thain-code** [comment]
We're running Prefect locally.

It's a bit early in our journey to say whether the `on_start` and `on_exit` callbacks that you suggest above would work for everything we need to do, but it would be sufficient for what I'm doing now which is basically wrapping the `DaskExecutor`s `submit` (i.e., `on_start`) and `wait` (i.e., `on_exit`).

**Comment by ahirner** [comment]
Packed futures in `wait` are also discussed in #2182

**Comment by jcrist** [comment]
Closing in favor of #4213.
