### ISSUE TITLE
[Prefect Cloud] "Invalid date" when creating token that does not expire

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#2848]
## Description

In Prefect Cloud, when you create a `USER` token in the UI, help text says that you can leave the expiration date blank

![image](https://user-images.githubusercontent.com/7608904/85488800-85097c00-b594-11ea-9be3-42e9843009b0.png)

If you do leave it blank, in the table of tokens the `EXPIRES AT` column will have the value "Invalid date"

![image](https://user-images.githubusercontent.com/7608904/85488859-a702fe80-b594-11ea-8299-2036a86eb9b1.png)

## Expected Behavior

I expected that the `EXPIRES AT` value for a token created with the expiration date left blank would be `21 Dec 2099 6:00pm`.

## Reproduction

1. Log in to Prefect Cloud at https://cloud.prefect.io/
2. Navigate to **User** --> **Personal Access Tokens**
3. Create a token and leave the expiration blank

## Environment

browser I saw this in: `Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)`

Thanks for your time and consideration.

**Comment by joshmeek** [comment]
cc @zhen0

**Comment by zhen0** [comment]
Thank you for this - fix in https://github.com/PrefectHQ/cloud-web-ui/pull/1639

**Comment by jameslamb** [comment]
Thanks! Since `cloud-web-ui` is a private repo, is this the right place for me to create issues about the Prefect Cloud UI?

**Comment by joshmeek** [comment]
@jameslamb For now either opening the tickets here or raising them on the public slack channel are the best options

**Comment by jameslamb** [comment]
ok sounds good, thanks!
