### ISSUE TITLE
dask k8s spin up more workers

### ISSUE THREAD

**Issue by cometta** [PrefectHQ/prefect#2850]
I followed the guide on https://docs.prefect.io/orchestration/execution/dask_k8s_environment.html#overview to try dask k8s, i able to run the job in k8s. In my python code, i set ```DaskKubernetesEnvironment(min_workers=3, max_workers=3, worker_spec_file="worker_spec.yaml")``` and in worker_spec.yaml,  replicas is 2. But when i monitor number of pod running, there are only  1 pod running  prefect-job** , 1 pod running prefect-dask-job-*** ,  1 pod run dask-root-a***

I thought it should be 3 workers since i set it in my python? The job able to run succesfully as it shows in the UI

**Comment by joshmeek** [comment]
Hi @cometta I can reproduce this behavior, thanks for opening! I'm thinking that maybe the work happening on #2849 will resolve this issue

**Comment by jcrist** [comment]
Fixed by #2849. Thanks for reporting! This should be out in the next release.

**Comment by cometta** [comment]
issue resolved with code merged
