### ISSUE TITLE
Make prefect directory inside Docker storage configurable

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#2861]
## Current behavior

Today when you build a `Docker` storage, `prefect` creates a directory for itself called `/opt/prefect` inside the image.

https://github.com/PrefectHQ/prefect/blob/467bc5b1dcd83716bd896eff549f6bceb59da8cf/src/prefect/environments/storage/docker.py#L469

That directory is used to store configuration files and flows.

## Proposed behavior

I'd like to propose making `prefect`'s directory inside `Docker` storage configurable. Ideally I'd like to be able to do this or something similar:

```python
flow.storage = Docker(
    prefect_directory="/home/my-custom-user/prefect"
)
```

If this is picked up, I believe it would mean the following:

* add a new keyword argument to `Docker` (https://github.com/PrefectHQ/prefect/blob/467bc5b1dcd83716bd896eff549f6bceb59da8cf/src/prefect/environments/storage/docker.py#L81), which defaults to `/opt/prefect` for backwards compatibility
* replace all hard-coded `/opt/prefect` in https://github.com/PrefectHQ/prefect/blob/467bc5b1dcd83716bd896eff549f6bceb59da8cf/src/prefect/environments/storage/docker.py with a reference to that attribute, `self.prefect_directory`

## Example

The current state can lead to issues if the `base_image` you're using runs as a user that does not have permission to write to `/opt`. I just encountered this situation using a base_image where the default user cannot write to `/opt`

> Step 5/9 : RUN mkdir -p /opt/prefect/
 ---> Running in eb30b890ad2b
 mkdir: cannot create directory ‘/opt/prefect/’: Permission denied

Making this configurable could remove an existing limitation that might currently lead people to run the image build process as `root`.

## Notes for Reviewers

If the maintainers here are interested in this change, I'd be happy to contribute it.

Thanks for your time and consideration!

**Comment by jcrist** [comment]
> Making this configurable could remove an existing limitation that might currently lead people to run the image build process as root.

When I build images, I generally have the build run as root, and use a different uid at runtime. This avoids issues at build time, but still keeps you secure at runtime. I can't think of a security issue for using root at buildtime.

That said, I would be accept making this configurable.

**Comment by jameslamb** [comment]
@jcrist , makes sense to me! I agree with you, but I'm working with base images that I don't totally control that make use of [`USER`](https://docs.docker.com/engine/reference/builder/#user).

I'll submit a PR to make this configurable, thanks!
