### ISSUE TITLE
Button links in prefect docs sometimes aren't functional after page load in firefox

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2866]
On [this page](https://docs.prefect.io/) the button links (blue buttons) don't seem to work immediately on page load when running in firefox. I can reproduce maybe 50% of the time - there seems to be a variable lag period (in the 1 - 15 second range) when the buttons don't do anything, and then all of a sudden they start working again. I'm unable to reproduce on chrome.

Steps to reproduce:

- go to https://docs.prefect.io in firefox (and maybe other browsers?) - a full page refresh seems necessary to trigger the issue.
- immediately try to click the either the core or orchestration button
- nothing happens

**Comment by jcrist** [comment]
cc @znicholasbrown

**Comment by znicholasbrown** [comment]
Confirmed can intermittently reproduce across browsers
