### ISSUE TITLE
Malformed response received from Cloud - please ensure that you have an API token properly configured.

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#2871]
## Description
When running a flow locally using version `0.12.1` I received am `Unexpected error: ClientError('Malformed response received from Cloud - please ensure that you have an API token properly configured.')`.    

This occurred with a `PrefectSecret` stored in the Cloud.
`conn_str = PrefectSecret("moc_pgdb_conn")` in a flow.

The full traceback:

```
[2020-06-25 23:26:10] ERROR - prefect.TaskRunner | Unexpected error: ClientError('Malformed response received from Cloud - please ensure that you have an API token properly configured.')
Traceback (most recent call last):
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/client/client.py", line 334, in _request
    json_resp = response.json()
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/miniconda3/envs/py37moc/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/miniconda3/envs/py37moc/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/miniconda3/envs/py37moc/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

```
## Expected Behavior
return a string

**Comment by cicdw** [comment]
@gryBox it appears that your secret is incorrectly querying the Cloud API.  Can you confirm that you have `use_local_secrets=true` set in your configuration?

**Comment by gryBox** [comment]
@cicdw  I use:
```
[cloud]
use_local_secrets = false
```

**Comment by gryBox** [comment]
@cicdw  I take it that you don't think this is a bug?

**Comment by cicdw** [comment]
Hey @gryBox - that's really surprising, I think it's possible this is a bug so I'd like to get to the bottom of it; ultimately it seems like _for some reason_ your secret is attempting to query Prefect Cloud in 0.12.1 but I'm having a hard time figuring out what could have changed that would cause that.  

**cc:** @joshmeek anything come to your mind?

**Comment by joshmeek** [comment]
I am only able to reproduce this in an environment where I am not logged in / authenticated with Cloud. @gryBox How is this flow being deployed? Agent / environment / etc.

**Comment by gryBox** [comment]
Hi @joshmeek @cicdw:  Hopefully this is a better explanation of the issue.

1. The flow is executed in a local environment with a `LocalExecutor`.
2. Inside the flow, the `PrefectSecret` task is called.

` conn_str = PrefectSecret("moc_pgdb_conn")
`
Where it rightly makes a call to Cloud because of the prefect `config.toml` cloud setting.
```
[cloud]
use_local_secrets = false
```
And this is where @joshmeek might of hit upon the issue/change in behavior. My flow is not registered.  The task accesses the Cloud using:

![image](https://user-images.githubusercontent.com/16763201/85905138-36e0bc80-b7d0-11ea-855f-da8ca57f5ab5.png)

**Comment by cicdw** [comment]
Hey @gryBox - it seems you are conflating local flow runs w/ Cloud flow runs.   Based on what you've provided, I'm guessing that you want to use Prefect Cloud as a secret store for flows that you run yourself.  While I wouldn't call this a supported feature, to successfully pull it off you need to provide an auth token in:
```
[cloud]
auth_token = TOKEN_VALUE
```
instead of `cloud.agent`.

**Comment by gryBox** [comment]
@cicdw 
> I'm guessing that you want to use Prefect Cloud as a secret store for flows that you run yourself. 

That is exactly what I have been doing.  And my point is that I was doing that successfully until `0.12.0`.   Now I may have set an auth token with the `client` previously that I did not previously describe (unintentionally).

In any case i will try what you posted previously. 

FWIW:  I am trying to deploy this flow using Fargate and a remote agent -- But its been fraught with bumps.
