### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by dadvir** [PrefectHQ/prefect#2882]
Hello!

I've found an issue here:`
flow = Flow(
    "Dask Executor Example",
    environment=LocalEnvironment(executor=DaskExecutor())
)
`

The LocalEnvironment constructor doesn't accept an executor argument.
Page reference: https://docs.prefect.io/orchestration/execution/local_environment.html

**Comment by joshmeek** [comment]
Hi @dadvir as of `0.12.1` the environments have a new interface for instantiating executors https://docs.prefect.io/api/latest/environments/execution.html#localenvironment
