### ISSUE TITLE
Consider removing default storage labels for environments

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#2888]
## Current behavior
Now that [non-Docker storage options can be used with containerized environments](https://docs.prefect.io/orchestration/execution/storage_options.html#non-docker-storage-for-containerized-environments) and the default environment `metadata.image` is the `prefecthq/prefect:all_extras` image it feels unnecessary to have the default labels on environments.

## Proposed behavior
Keep the hostname default label but remove all of the others:

```
['azure-flow-storage', 'gcs-flow-storage', 's3-flow-storage', 'github-flow-storage']
```

This would need to be added in a way with the least amount of side effects because we would not want new agents from pulling old flows which were configured without labels.

**Comment by jcrist** [comment]
This has since been resolved. Closing.
