### ISSUE TITLE
Flow Runner: creation of Constants delegates name creation to repr which might be memory and compute inefficient

### ISSUE THREAD

**Issue by marwan116** [PrefectHQ/prefect#2897]
## Current behavior

In `flow_runner.py`, the FlowRunner's `get_flow_run_state` has the following snippet

```

                # augment edges with upstream constants
                for key, val in self.flow.constants[task].items():
                    edge = Edge(
                        upstream_task=prefect.tasks.core.constants.Constant(val),  # <- a Constant instance is created
                        downstream_task=task,
                        key=key,
                    )
                    upstream_states[edge] = Success(
                        "Auto-generated constant value",
                        result=ConstantResult(value=val),
                    )
```
 
and under constants.py one can see that initialization of a `Constant` makes a call to `repr(self.value)`; this call could be quite expensive (both in terms of compute and memory) in case the object is large and has an expensive repr method, for instance, a pandas DataFrame ... 
```
    def __init__(self, value: Any, name: str = None, **kwargs: Any):
        self.value = value

        # set the name from the value
        if name is None:
            name = repr(self.value)   # <- creates a name attribute by calling the repr
            if len(name) > 8:
                name = "Constant[{}]".format(type(self.value).__name__)

        super().__init__(name=name, **kwargs)
```

## Proposed behavior
Since the constant's name doesn't seem to be too important (i.e. doesn't show in any of the logs it seems, would it make more sense to just use a `uuid` generated name - which would be much more efficient than having to call on `repr` ? In essence the only needed code change would be the following in `flow_runner.py`

                # augment edges with upstream constants
                for key, val in self.flow.constants[task].items():
                    edge = Edge(
                        upstream_task=prefect.tasks.core.constants.Constant(val, name=str(uuid.uuid4()),
                        downstream_task=task,
                        key=key,
                    )
                    upstream_states[edge] = Success(
                        "Auto-generated constant value",
                        result=ConstantResult(value=val),
                    )

**Comment by joshmeek** [comment]
@marwan116 thanks for opening the issue! I don't see anything wrong with not using the `repr` for the constant name. It doesn't appear that the name is used anywhere I am aware of (I think it used to be in some visualizations). I think smaller names as opposed to the full UUID would be good. Something like `str(uuid.uuid4())[:8]` would probably work.

**Comment by cicdw** [comment]
Maybe we can use the `type` so that the name is still mildly informative?  Names don't need to be unique within a Flow so I think this should be safe + cheap to compute

**Comment by joshmeek** [comment]
I'm +1 on using the type!

**Comment by marwan116** [comment]
Hi @cicdw @joshmeek  - thanks for following up on this. I agree, using the `type` offers more context than a random uuid ...
