### ISSUE TITLE
Make agent handling of state update errors more robust

### ISSUE THREAD

**Issue by zdhughes** [PrefectHQ/prefect#2903]
## Current behavior

As it exists today, the agent's handling of state setting errors is fairly fragile; logic checks for the string `"State update failed"`. 

https://github.com/PrefectHQ/prefect/blob/ffe03678f39d585bdddbb8908a2ce57438fc0f02/src/prefect/agent/agent.py#L335

## Proposed behavior

We can make the agent's error check more robust in one of two (or more) ways: we can return the error as part of the state-setting payload, or we can designate a specific error code for state-setting errors and handle it in that manner. 

## Example

Checking for a specific three-word string is fairly fragile, and means that any API-side changes that intend to use this branch of the agent logic must match the exact verbiage and casing of this check. By adopting something a bit more standardized, we can likely save ourselves some heartache moving forward.

**Comment by joshmeek** [comment]
FWIW this is the same type of logic that the Client uses for determining error type returned from the API https://github.com/PrefectHQ/prefect/blob/ffe03678f39d585bdddbb8908a2ce57438fc0f02/src/prefect/client/client.py#L221-L228

**Comment by zdhughes** [comment]
Ah-- by "specific error code" I mean something like the `API_ERROR` code that gets returned for passing connectivity issues. Something along the lines of `STATE_SETTING_ERROR`. Not 100% sure that's the appropriate approach, but it's one way we could go.
