### ISSUE TITLE
merge_dicts is a slow recursive function, suggest replacing with a faster implementation

### ISSUE THREAD

**Issue by marwan116** [PrefectHQ/prefect#2909]
## Current behavior
In both `FlowRunner` and `TaskRunner`, there are statements where a context is entered. When a context is entered/called, `merge_dicts` is invoked to update the context which seems to be slow and recursive function especially that it is being called for every task run...

`with prefect.context(context):` is called in FlowRunner.run, run_task, TaskRunner.run, 

```
    @contextlib.contextmanager
    def __call__(self, *args: MutableMapping, **kwargs: Any) -> Iterator["Context"]:
        """
        A context manager for setting / resetting the Prefect context

        Example:
            import prefect.context
            with prefect.context(dict(a=1, b=2), c=3):
                print(prefect.context.a) # 1
        """
        previous_context = self.copy()
        try:
            new_context = dict(*args, **kwargs)
            if "config" in new_context:
                new_context["config"] = merge_dicts(   # <- new config is merged onto default config
                    self.get("config", {}), new_context["config"]
                )
            self.update(new_context)  # type: ignore
            yield self
        finally:
            self.clear()
            self.update(previous_context)
```

## Proposed behavior
Given prefect is using python >= 3.5, I suggest merge_dicts be replaced by a much simpler function 

```
def merge_dicts(d1, d2):
    return {**d1, **d2} 
```

**Comment by cicdw** [comment]
Hi @marwan116 - thanks for the issue; I wouldn't be surprised if there is room for some performance enhancement here but note that your solution won't work; Prefect context tends to have deeply nested structures so it's important to support things like:

```python
import prefect

print(prefect.context.config.logging.level) # DEBUG

with prefect.context({"config": {"logging": dict(level="INFO")}}):
    print(prefect.context.config.logging.level) # INFO
    print(prefect.context.config.to_dict()) # still all of the same original config
```

**Comment by marwan116** [comment]
@cicdw - you are right  ... sorry didn't get the chance to test out my solution ... Will try to think of an alternative implementation that works
