### ISSUE TITLE
remove version ceilings on prefect's dependencies?

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#2910]
## Current behavior

Today, `prefect` requires that you have a `cloudpickle` version older than v 1.5.0:

https://github.com/PrefectHQ/prefect/blob/214b2944c0b49eaac0117e06e7fc1d0dabe408fc/requirements.txt#L2

I noticed this through a CI failure today, because [`cloudpickle` did a 1.5.0 release yesterday](https://pypi.org/project/cloudpickle/1.5.0/)

![image](https://user-images.githubusercontent.com/7608904/86392415-0c27b580-bc61-11ea-8749-c99c8e0e62f0.png)

Why is this version ceiling in place? Is there a particular incompatibility that the maintainers here knew to anticipate in 1.5.0?

It looks like this was done automatically by a bot: https://github.com/PrefectHQ/prefect/commit/0ff0ce9f0700142dc2f4d8f875768d85d654fc48

## Proposed behavior

I think it would be a better user experience to only use a ceiling to catch new _major_ versions of *cloudpickle` (`cloudpickle<2.0`). I can't tell from [the repo](https://github.com/cloudpipe/cloudpickle) if `cloudpickle` follows semantic versioning, but if they do then there should only be breaking changes in major versions.

Thanks for your time and consideration!

**Comment by joshmeek** [comment]
@jameslamb I think it should be fine to bump up the upper version! We use dependabot for managing our dependencies and it hasn't caught the new version yet so we can bump manually.

**Comment by jameslamb** [comment]
Repurposing this issue, per https://github.com/PrefectHQ/prefect/pull/2911#discussion_r449216869.

The question:

> should `prefect` remove version ceilings in its `requirements.txt`?

**Comment by jameslamb** [comment]
blegh sorry, the `fixes()` in my commit message closed this. It should probably be re-opened since it's been repurposed for a broader discussion

**Comment by cicdw** [comment]
FWIW I'm cool with this.  As @joshmeek has pointed out in an offline convo we probably want to keep marshmallow and croniter bounded above due to being bit in the past, but otherwise we were probably being overly cautious with the upper bounds on everything.
