### ISSUE TITLE
Problem visualizing a Flow

### ISSUE THREAD

**Issue by rpitre** [PrefectHQ/prefect#2918]
When I call flow.visualize(), there is no graph created. Debugging this I found that the problem was the following code in flow.py, from line 1238
       if filename:
            graph.render(filename, view=False, format=format)
        else:
            try:
                from IPython import get_ipython
                
                assert get_ipython().config.get("IPKernelApp") is not None              <----------------- the problem
            except Exception:

Now in order to see if the value was really None I added this line of code:
        if filename:
            graph.render(filename, view=False, format=format)
        else:
            try:
                from IPython import get_ipython
                test = get_ipython().config.get("IPKernelApp")   <-----------------------line added
                assert get_ipython().config.get("IPKernelApp") is not None
            except Exception:

and it worked. I know can visualize the graph. Without the line  it does not work.
I have no idea why this worked.

**Comment by jcrist** [comment]
Hi @rpitre, were you running inside ipython or a jupyter notebook at the time? Can you provide steps to reproduce your error?

**Comment by rpitre** [comment]
No, not running inside ipython or jupyter note book. I am just creating a flow and calling flow.visualize(). I have created complex flow and flow.run() always works without problem. But flow.visialize() never works without my added line code.

**Comment by wingriderr** [comment]
Try specifying a filename 
`flow.visualize(/var/tmp/flow1)`
