### ISSUE TITLE
prefect describe CLI does not return JSON

### ISSUE THREAD

**Issue by ludwigm** [PrefectHQ/prefect#2926]
## Description
`prefect describe` calls seem to give back no valid JSON but just a printed Python Dict. To make it more useful in downstream commands to e.g. parse the output via jq it would be great if this is JSON. Maybe that was even intended, not sure if it is a bug or enhancement.

One example:
```
prefect describe flows --name TestRecoGenerationFlow_dev  | jq
parse error: Invalid numeric literal at line 1, column 8
```

Output of this looks like the following:
```
{'name': 'TestRecoGenerationFlow_dev', 'version': 17, 'created': '2020-07-07T12:43:44.554817+00:00', 'description': None, ...
```

With the `None` values instead of `null` it is clear that this is no JSON

## Expected Behavior
Proper returning of JSON so that it can be used in downstream tools or pipes.

## Reproduction
```
prefect describe flows --name <anyname>  | jq
```

## Environment
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.4-x86_64-i386-64bit",
    "prefect_version": "0.12.2",
    "python_version": "3.8.2"
  }
}
```

**Comment by jcrist** [comment]
Hi @ludwigm, makes sense to me. Would you be interested in contributing the above fix?

**Comment by joshmeek** [comment]
@ludwigm The `describe` CLI commands have an `--output` option which you can provide json to in order to get json output.

```bash
prefect describe flows -n ETL --output json
{"name": "ETL", "version": 15, "created": "2020-05-20T18:31:12.084788+00:00", "description": null, "parameters": [], "archived": false, "storage": {"key": null, "type": "S3", "flows": {"ETL": "etl/2020-05-20t18-31-09-936334-00-00"}, "bucket": "my-prefect-flows", "secrets": [], "__version__": "0.11.2+43.gac8639392", "client_options": null}, "environment": {"type": "RemoteEnvironment", "labels": ["s3-flow-storage"], "executor": "prefect.engine.executors.LocalExecutor", "__version__": "0.11.2+43.gac8639392", "executor_kwargs": {}}}
```

**Comment by jcrist** [comment]
Any reason not to make json output the default? I don't see why I'd ever want a printed dict version of the output, but could see uses for other common formats like json or yaml.

**Comment by joshmeek** [comment]
Yeah @jcrist JSON should be made the default

**Comment by jcrist** [comment]
Cool, I'll push up a quick fix for this.
