### ISSUE TITLE
Kubernetes agent stuck in processing feeback loop after ImagePullBackOff

### ISSUE THREAD

**Issue by CrispyCrafter** [PrefectHQ/prefect#2943]
## Description
When a prefect Kubernetes agent consumes flow with an invalid docker image url:  
```
flow.storage = S3(bucket="bucket", secrets=["AWS_CREDENTIALS"])
flow.environment = LocalEnvironment(
    metadata={
        "image": "wrong_registry_url/image:tag"
    },
    labels=['s3-flow-storage']
)
```
The k8s job goes into a `ImagePullBackOff` state. This is expected.
![image](https://user-images.githubusercontent.com/29259177/87165195-19304e80-c2ca-11ea-8136-c091fed51eb3.png)

Manually closing the job via kubectl/k9s puts the prefect agent in a feedback loop where no new flow-runs are being processed.
So far the agent was only freed up after deleting the entire cloud project, indicating a run state invalidation issue.
(alternatively changing the state from the cloud UI should be explored)

![image](https://user-images.githubusercontent.com/29259177/87166999-a379b200-c2cc-11ea-8cc3-9c2b241692bb.png)

## Expected Behavior
submit flow to run -> k8s agent consumes -> create job -> `ImagePullBackOff` -> fail run 

## Reproduction
s3_k8s_flow.py 
``` 
import prefect
from prefect import task, Flow
from prefect.environments import LocalEnvironment
from prefect.environments.storage import S3

@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Hello, Docker!")


flow = Flow("k8s_agent_S3_loop", tasks=[hello_task])

flow.storage = S3(bucket="bucket-path", secrets=["AWS_CREDENTIALS"])
flow.environment = LocalEnvironment(
    metadata={
        "image": "<wrong_registry>/prefect:latest"
    },
    labels=['s3-flow-storage']
)

flow.register('Bug')


flow_correct = Flow("k8s_agent_S3_correct", tasks=[hello_task])

flow_correct.storage = S3(bucket="bucket-path", secrets=["AWS_CREDENTIALS"])
flow_correct.environment = LocalEnvironment(
    metadata={
        "image": "prefecthq/prefect:latest"
    },
    labels=['s3-flow-storage']
)

flow_correct.register('Bug')
```

create and schedule:
```
python s3_k8s_flow.py
prefect run cloud --name "k8s_agent_S3_correct" --project "Bug"
prefect run cloud --name "k8s_agent_S3_loop" --project "Bug"

prefect get flow-runs --project Bug
```
![image](https://user-images.githubusercontent.com/29259177/87166286-a1632380-c2cb-11ea-9263-ebd5e8aea0f6.png)

## Environment
prefect version       => 0.12.3
kubernetes agent:  
```
prefect agent install kubernetes -t TOKEN \
  --resource-manager --rbac \
  --image-pull-secrets \
 | kubectl apply -f -
```

**Comment by CrispyCrafter** [comment]
Can confirm that invalidating the state from the cloud UI frees up the agent to consume new runs.

**Comment by CrispyCrafter** [comment]
Something like this should work:
https://stackoverflow.com/questions/58538756/what-is-the-right-way-to-free-up-kubernetes-resources-for-a-kubernetes-job-that

**Comment by cicdw** [comment]
Hi @CrispyCrafter - thanks for the issue; a piece of what you describe is related to concurrency limiting in the backend.  If you have a free developer account, only one Flow can be in a `Running` or `Submitted` state at any given time.  This is why you had to change the state of your stuck Flow run from the UI in order for your agent to process more work.

That being said, I agree with you that this experience would be much nicer if the agent had marked this Flow Run as `Failed` the moment the `ImagePullBackOff` began.  Right now all agents "fire and forget" jobs and don't check back on their status but @joshmeek thinks he knows a way of checking on job status after a slight delay so we'll look into that!

**Comment by CrispyCrafter** [comment]
ok. That's good to know.
We've been experiencing some issues with Gitlab's container registry recently where images fail to pull due to networking issues.
Have some form of state memory on the agent would be cool.

On a side note it seems the k8s agent running `DaskKubernetesEnvironment` seems to be a bit more resilient against these types of issues.

Should we close the issue for now, or keep it open for continuity ?

**Comment by cicdw** [comment]
Let's keep it open to track "Improving how agents handle `ImagePullBackOff` errors" (this presumably applies to all docker-based agents)
