### ISSUE TITLE
A few small API docs formatting issues

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2966]
I was just working on some API docs, and noticed a few small formatting issues that I think we could improve:

- There's no exposed anchor to link to functions in the api docs. Classes each have a link for an anchor, but the only clickable anchor link for functions is the `Functions` header. It appears an anchor link is already generated for each function, there's just no visible UI element for it. See https://docs.prefect.io/api/latest/tasks/control_flow.html#functions for example. One solution might be to not special-case functions from classes, since everything works fine for classes already.

- Excessive `<br>` lines are being inserted after code blocks for function api docs, leading to excess whitespace. See https://docs.prefect.io/api/latest/tasks/control_flow.html#functions for example.

- Code blocks in class-level docs need to have the language specified syntax highlighting to work
  
   ````
   ```python
   1 + 2
   ```
   ````

  whereas code blocks in function docs are always rendered with `language-python`, regardless what language is specified (including none). This isn't really an issue, I just found it surprising.

**Comment by lauralorenz** [comment]
Just tagging that I think your first bullet point is the same as https://github.com/PrefectHQ/prefect/issues/987, if we want to close one or the other!
