### ISSUE TITLE
Support templating flow run names in scheduled runs

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#3010]
Reported by a user on slack: https://app.slack.com/client/TL09B008Y/CL09KU1K7/thread/CL09KU1K7-1595353401.028000

> I am working on a flow that will have a schedule with up to 18 clocks. If you are wondering why that many, here is some background. This flow pulls data from a reporting API that is organized around data bundles and different granularities (daily, weekly, monthly). Not all combinations are valid but I have identified 18 valid ones so far.
>
> Since each combination is available at different times with different frequencies, we need different schedules for each combination of parameters. The flow structure/logic is the same for all the combinations so it makes sense to have a single flow.
>
> Is there a way to define flow run names based on a combination of parameters and `scheduled_start_time`? More generally it would be great to be able to use context + parameters to define the flow run name.

**Comment by madkinsz** [comment]
https://github.com/PrefectHQ/prefect/pull/3664
