### ISSUE TITLE
Caching targets generated by external processes

### ISSUE THREAD

**Issue by k4rt33k** [PrefectHQ/prefect#3014]
I am trying to use result targets to cache some of my results as suggested in https://docs.prefect.io/core/idioms/targets.html. However a lot of my heavyweight tasks are run in C++ and are invoked via Python. How can I use targets effectively in this case?

More specifically, the issue seems to be the implicit assumption that the target is always a cached representation of the data returned by the python function as opposed to a pointer that refers to the output of a non-Python process (a local filepath in my current cases, but it could very easily be a S3 bucket).

I'm working around this limitation by doing the following:

```
results_dir = "/tmp/results_cache"

@task(
    result=LocalResult(dir=results_dir, serializer=JSONSerializer()),
    target="{task_name}_{map_index}.json")
def dummy_task(name):
    logger = prefect.context.get("logger")
    map_index = prefect.context.map_index
    date = prefect.context.date
    outputpath = f"/tmp/dummy_task_{map_index}.txt"
    # this system cmd in reality is a heavyweight C++ call
    assert os.system(f"mkdir -p {os.path.dirname(outputpath)} && echo {name} > {outputpath}") == 0, "Failed to run command"
    return outputpath

# need to remove the file /tmp/results_cache/dummy_task_0.json for the task to be run a second time
# it'd be good if I could rather remove /tmp/dummy_task_0.txt for the task to be run again
with Flow("test_flow") as flow:
    dummy_task.map(["foo", "bar", "baz"])
```

It would be nice if I can avoid this indirection and directly be able to return a Result object that doesn't necessarily correspond to a serialized python object. All downstream processes that consume these results treat them as locations.

**Comment by joshmeek** [comment]
@k4rt33k Interesting use case! Not sure if this would solve what you're after but maybe updating your callable to use something more "unique" in a way like `{task_name}_{map_index}_{date}.json` so that each run will occur at a different timestamp and it would not need to be deleted. Otherwise at this time I would suggest maybe writing a task that has the responsibility for cleaning up that directory before/after a run. 🤔

**Comment by joshmeek** [comment]
Hi @k4rt33k is this still an open issue or were you able to make it work with your use case?

**Comment by k4rt33k** [comment]
> @k4rt33k Interesting use case! Not sure if this would solve what you're after but maybe updating your callable to use something more "unique" in a way like `{task_name}_{map_index}_{date}.json` so that each run will occur at a different timestamp and it would not need to be deleted. Otherwise at this time I would suggest maybe writing a task that has the responsibility for cleaning up that directory before/after a run. 🤔

I ended up doing some variation of this. It's not a blocker anymore. Feel free to close this one.
