### ISSUE TITLE
Doc about GitHubStorage

### ISSUE THREAD

**Issue by Marlin-Na** [PrefectHQ/prefect#3019]
Hello!

I've found a minor issue here:`As of Prefect version 0.9.0 every storage option except for Docker will automatically have a result handler attached that will write results to the corresponding platform.`

Page reference: https://docs.prefect.io/orchestration/execution/storage_options.html

I am guessing that as for now, both `Docker` and `GitHub` storage option won't have the corresponding result handler?

**Comment by cicdw** [comment]
Great catch @Marlin-Na - yes, you are correct. Will update shortly
