### ISSUE TITLE
Run Flows through Local code doesn't replicate in the UI 

### ISSUE THREAD

**Issue by FabioXN7** [PrefectHQ/prefect#3036]
Hi everyone, I'm not sure if the title is clear. But I'm trying to achieve something in Prefect and I don't know if it's possible, maybe someone can help me out. 

When running **flow.run()** on local python files, I only get the output in terminal which is fine, but I needed a way to whenever I use the **flow.run()** method locally, I also want these results to be shown on the UI, so every time I open Prefect UI I don't need to click on either **Run** or **Quick Run**, is it possible to achieve that? The only thing I can do is register the flow and schedule it in within a minute or so, but not replicate their local runs in terminal through console. Also my flows are in a loop sort of code so I create different flows dynamically and wanted to see their results already processed in the UI when I open it.

Thank you!

**Comment by thomasfrederikhoeck** [comment]
I think you can use `prefect.client.client.Client.create_flow_run` (see https://docs.prefect.io/api/latest/client/client.html#client-2) to connect to the cloud and start a flow. :-)
