### ISSUE TITLE
Use object-orientated Docker client instead of low-level API 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#3045]
## Current behavior

Right now the `docker.APIClient` is used
https://github.com/PrefectHQ/prefect/blob/38a983f24ae8065703817f7989e113fe86927d69/src/prefect/environments/storage/docker.py#L562

This leads to fail check like the following to see if build failed as `docker.APIClient().build()` simply returns text.:

https://github.com/PrefectHQ/prefect/blob/38a983f24ae8065703817f7989e113fe86927d69/src/prefect/environments/storage/docker.py#L390

This is fine in most cases (except if a build with same name and tag was successful previously).  

## Proposed behavior

If the Object-Orientated Docker Client (https://docker-py.readthedocs.io/en/stable/images.html) was used it would simply raise a `docker.errors.BuildError` which is easier to understand.

**Comment by joshmeek** [comment]
@thomasfrederikhoeck what is your use case where you are encountering an issue with this and could you provide a reproducible example?

**Comment by thomasfrederikhoeck** [comment]
An example could be:

First run the following which should succeed and build an image.
```python
from prefect.environments.storage import Docker
storage = Docker(image_name="my_image",image_tag="my_tag")
storage.build(push=False)
```

Then run the following where the build of the image fails but the code continues because there already exists an image with the tag:


```python
from prefect.environments.storage import Docker
from prefect import task, Flow
import pandas as pd

@task
def my_basic_task():
    return  pd.DataFrame([1,2])

with Flow("my_basic_flow") as my_basic_flow:
    my_basic_task()

storage = Docker(image_name="my_image",image_tag="my_tag")
storage.add_flow(my_basic_flow)
storage.build(push=False)
print("Code still running despite error...")

```

**Comment by thomasfrederikhoeck** [comment]
Can you replicate the error @joshmeek or is it on my end?

**Comment by joshmeek** [comment]
@thomasfrederikhoeck Looks like I am able to reproduce however I'm not fully sold on replacing the use of a low-level API though. Looking at the docker-py source code all it does to detect the build error is string match with the generator output:

https://github.com/docker/docker-py/blob/1fc62e6a32c2d3257d5d033fcf924fabb16190ac/docker/models/images.py#L285-L287

```python
        for chunk in internal_stream:
            if 'error' in chunk:
                raise BuildError(chunk['error'], result_stream)
```

If we wanted the go with the same functionality it would be a single string match in the generator parsing function:

https://github.com/PrefectHQ/prefect/blob/d06c578847a1455a7e11c71714151e6d07ed0cac/src/prefect/environments/storage/docker.py#L608-L620

**Comment by thomasfrederikhoeck** [comment]
@joshmeek Hmm I guess the benefit is that the docker-py community will maintain how to detect an error. Is there any features used in the low-level API that is need which are not present in the OO?

**Comment by thomasfrederikhoeck** [comment]
@joshmeek But I think it would be nice if Prefect would raise if it detects as `errorDetail`

**Comment by joshmeek** [comment]
IIRC the low level API was used because docker-py used to hide the build output generator and it was only accessible through the lower level client. It looks like this is no longer the case so we could look into a full change 🤔

**Comment by thomasfrederikhoeck** [comment]
I personally think that would be a good idea as it would help with raising errors. :-)  And maybe it would allow a bit of boiler-plate code to be removed and reduce complexity all little bit.

**Comment by madkinsz** [comment]
Thanks!
