### ISSUE TITLE
[Cloud UI] Restarting from failure does not restart all failed tasks

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/prefect#3047]
## Description
In the Cloud UI, restarting a failed run with two root nodes appears to only restart one of them. Even if the restarted DAG path succeeds, an orphaned root nodes remains in a failed state/not retried.

## Expected Behavior
All separate flow paths in failed status should restart from a single click when restarting from failed at the flow level.

## Reproduction
```
from prefect import Flow, task
from prefect.engine import signals


@task
def task1():
    raise signals.FAIL


@task
def task2():
    raise signals.FAIL

    return "input"


@task
def task3(input):
    print(input)


with Flow("restart-multiple-roots") as flow:
    task1()

    result1 = task2()
    task3(result1)

flow.register(project_name="test-flows")

# run once, then restart from failed--note only the task2 -> task3 path restarts
```

**Comment by joshmeek** [comment]
Thanks for opening @jnoynaert. This looks to be a Cloud bug here, will prioritize and get it fixed! 🙂

**Comment by cicdw** [comment]
This issue should now be resolved!
