### ISSUE TITLE
Ignore calls to flow.register when parsing a flow using file based storage

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#3051]
## Current behavior

If a flow script contains a reference to the `.register` method, it'll fail with this error:
```
Failed to load and execute Flow's environment: RuntimeError('Attempting to call `flow.register` during execution of flow file will lead to unexpected results.')
```

## Proposed behavior

Flow runner ignores calls to the `.register` method.

**Comment by sp1thas** [comment]
Hello @znicholasbrown , I would like to contribute on this issue. I tried to reproduce the issue without any success, probably, due to limited experience with prefect. Could you provide a minimal example of this case?

**Comment by joshmeek** [comment]
Hey @sp1thas you could reproduce this behavior with something like this:


```python
# my_flow.py
from prefect import Flow

f = Flow("my-flow")

f.register()
```

```bash
prefect register flow -f my_flow.py
```

Here is where the error is raised:
https://github.com/PrefectHQ/prefect/blob/35afc328a8273251f70cc4a48874df2c1b9cdb53/src/prefect/core/flow.py#L1555-L1559
