### ISSUE TITLE
Some SQL commands submittted to MySQL that are long running don't return as finished to Prefect

### ISSUE THREAD

**Issue by mmaldo** [PrefectHQ/prefect#3065]
## Description

Some SQL commands submitted to MySQL that are long running don't return as finished to Prefect.

One stored procedure that took longer than 30 mins. This stored procedure included one of the offending commands by itself which was
 `query_final_table = " CREATE TABLE ct_qty_filled AS SELECT a.Date as Date,a.Location as Location,a.IDxProd as IDxProd,COALESCE(b.QtyFilled,0) as QtyFilled,CONCAT(a.IDxProd,a.Location) AS IDxProd_Location \
                FROM (SELECT a.calendar_date as Date,c.Location, b.IDxProd as IDxProd \
                        FROM fiscal_calendar a \
                        CROSS JOIN (SELECT DISTINCT a.IDxProd as IDxProd \
                                    FROM ct_inventory a \
                                    WHERE a.IDxProd is not null) b \
                        CROSS JOIN(SELECT DISTINCT a.locationEntry as Location \
                                    FROM ct_invoices a\
                                    WHERE a.locationEntry IN ('FV','VN','LA','Tor','Ana','SD','SM','Pat','IE','Oak','Com','DC','Sac','DC2')) c \
                        WHERE a.calendar_date between date_sub(curdate(), interval 366 day) AND date_sub(curdate(), interval 1 day)) a \
                LEFT JOIN (SELECT a.dateCreated as Date,a.locationEntry as Location,b.IDxProd as IDxProd,SUM(b.QtyFilled) as QtyFilled \
                            FROM ct_invoices a \
                            INNER JOIN ct_iline b on a.IDxInvoice = b.IDxInvoice \
                            WHERE a.dateCreated >= date_sub(curdate(), interval 366 day) \
                            Group By 1,2,3) b  on a.Date = b.Date AND a.Location = b.Location AND a.IDxProd = b.IDxProd"
connection.execute('DROP TABLE IF EXISTS ct_qty_filled')
connection.execute(query_final_table)
`
There is a longer stored procedure involved. The stored procedure completes fine in MySQL. It doesnt return a success though. However when the commands were separate in a Prefect Task it would hang on connection.execute(query_final_table).  It would timeout at the two hour mark using sqlalchem and pymysql. Oracle connector would just keep on running. The Prefect task mysqlexecute would also timeout after two hours.

Other problems included 
`connection.execute('ALTER TABLE ct_iline ADD CONSTRAINT invoice_iline FOREIGN KEY (IDxInvoice) REFERENCES ct_invoices(IDxInvoice) ON DELETE CASCADE')`

and 

`connection.execute('ALTER TABLE ct_iline ADD PRIMARY KEY(IDxILine)')`

However, these same commands existed in other tasks on different tables. They executed fine. I also have long running pandas to_sql commands using sql alchemy that run fine.

I also built a stored procedure that took less time to execute that used the same commands that finished successfully.

The full stored procedure looks something like this 

`CREATE  PROCEDURE qty_filled()
BEGIN
    DROP TABLE IF EXISTS ct_qty_filled;
    CREATE TABLE ct_qty_filled AS SELECT a.Date as Date,a.Location as Location,a.IDxProd as IDxProd,COALESCE(b.QtyFilled,0) as QtyFilled,CONCAT(a.IDxProd,a.Location) AS IDxProd_Location
                                    FROM (SELECT a.calendar_date as Date,c.Location, b.IDxProd as IDxProd
                                          FROM fiscal_calendar a
                                          CROSS JOIN (SELECT DISTINCT a.IDxProd as IDxProd
                                                      FROM ct_inventory a
                                                      WHERE a.IDxProd is not null) b
                                          CROSS JOIN(SELECT DISTINCT a.locationEntry as Location
                                                     FROM ct_invoices a
                                                     WHERE a.locationEntry IN ('FV','VN','LA','Tor','Ana','SD','SM','Pat','IE','Oak','Com','DC', 'Sac', 'DC2')) c
                                  WHERE a.calendar_date between date_sub(curdate(), interval 366 day) AND date_sub(curdate(), interval 1 day)) a
                                  LEFT JOIN (SELECT a.dateCreated as Date,a.locationEntry as Location,b.IDxProd as IDxProd,SUM(b.QtyFilled) as QtyFilled
                                              FROM ct_invoices a
                                             INNER JOIN ct_iline b on a.IDxInvoice = b.IDxInvoice
                                             WHERE a.dateCreated >= date_sub(curdate(), interval 366 day)
                                             Group By 1,2,3) b  on a.Date = b.Date AND a.Location = b.Location AND a.IDxProd = b.IDxProd;
    ALTER TABLE ct_qty_filled ADD Id BIGINT PRIMARY KEY AUTO_INCREMENT;
    CREATE INDEX prod ON ct_qty_filled(IDxProd);
    CREATE INDEX date ON ct_qty_filled(Date);
    CREATE INDEX location ON ct_qty_filled(Location(4));
    CREATE INDEX prod_location ON ct_qty_filled(IDxProd,Location(4));
    CREATE INDEX date_prod ON ct_qty_filled(Date,IDxProd);
    CREATE INDEX date_location ON ct_qty_filled(Date,Location(4));
    CREATE INDEX date_location_prod ON ct_qty_filled(Date,Location(4),IDxProd);
    CREATE INDEX idxprod_location ON ct_qty_filled(IDxProd_Location(8));
END`

Current workaround is to put commands in jupyter notbook and run the jupyter notebook through nbconvert in a Prefect task

## Expected Behavior

I expected the task to finish.

## Reproduction

`connection.execute('ALTER TABLE ct_iline ADD CONSTRAINT invoice_iline FOREIGN KEY (IDxInvoice) REFERENCES ct_invoices(IDxInvoice) ON DELETE CASCADE')`

**Comment by joshmeek** [comment]
@mmaldo Could you post a reproducible example with information about the setup of your flow and tasks?

**Comment by mmaldo** [comment]
`from prefect import task, Flow
import pandas as pd
import jaydebeapi
from sqlalchemy.types import Integer,DateTime,VARCHAR,TEXT,BigInteger,Date
import numpy as np
from sqlalchemy import create_engine
import pymysql
import pyodbc
import pendulum
import datetime
from prefect.environments import RemoteEnvironment
from datetime import timedelta
from subprocess import check_output,CalledProcessError
import time
from multiprocessing import Process
import mysql.connector
from prefect.contrib.tasks.mysql.mysql import MySQLExecute


    
@task
def extract_ct_contacts():
    connectionString = 
    extract_connect = pyodbc.connect(connectionString)
    y = 'Contacts'
    z = ['ModTimeStamp','created']

    query_final = 'select * from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    return data
    

@task
def transform_ct_contacts(data):
    return data

@task
def load_ct_contacts(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_contacts'
    p = {'ModTimeStamp':DateTime(),'created':DateTime(),'IDxContact':BigInteger()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX contact ON ct_contacts(IDxContact)')
    connection.execute('CREATE INDEX compname ON ct_contacts(CoName(50))')
    connection.execute('CREATE INDEX compname_id ON ct_contacts(IDxContact,CoName(50))')
    connection.close()

@task
def extract_erf():
    connectionString = 
    extract_connect = pyodbc.connect(connectionString)
    y = 'Table'
    z = ['Date']

    
    query_final = 'select * from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    return data
    

@task
def transform_erf(data):
    return data

@task
def load_erf(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'erf_invoice_lines'
    p = {'Date':DateTime()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.close()
    
@task
def extract_ct_inventory():
    extract_connect = pyodbc.connect()
    y = 'Inventory'
    z = ['Modified','ModifiedPar','LastPoTransfer','gD1','gD2','dateCreate']

    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    for i in structure_name_type.index:
        if i == length-1:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '"'
        else:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '",'
    query_final = 'select ' + query + ' from ' + '"' + y + '"'
    
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_inventory(data):
    return data

@task
def load_ct_inventory(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_inventory'
    p = {'Modified':DateTime(),'ModifiedPar':DateTime(),'LastPoTransfer':DateTime(),'gD1':DateTime(),'gD2':DateTime(),'dateCreate':DateTime(),'IDxProd':BigInteger()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX prod ON ct_inventory(IDxProd)')
    connection.close()
    
@task    
def extract_ct_orders():
    extract_connect = pyodbc.connect()
    y = 'Orders'
    z = ['Date','maxDatePaid','ModTimeStamp','ProcessedTS','ValidatedTS','DateConfirmed','eta','wcdate']
    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
 
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    for i in structure_name_type.index:
        if i == length-1:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '"'
        else:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '",'
    query_final = 'select ' + query + ' from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_orders(data):
    return data

@task
def load_ct_orders(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_orders'
    p = {'Date':DateTime(),'maxDatePaid':DateTime(),'ModTimeStamp':DateTime(),'ProcessedTS':DateTime(),'ValidatedTS':DateTime(),'DateConfirmed':DateTime(),'eta':DateTime(),'wcdate':DateTime()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.close()
    
@task
def extract_ct_po():
    extract_connect = pyodbc.connect()
    y = 'PO'
    z = ['DateConfirmed','eta','wcdate']

    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    for i in structure_name_type.index:
        if i == length-1:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '"'
        else:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '",'
    query_final = 'select ' + query + ' from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_po(data):
    return data

@task
def load_ct_po(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_po'
    p = {'DateConfirmed':DateTime(),'eta':DateTime(),'wcdate':DateTime(),'log':TEXT(length=65535)}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.close()

    
@task
def extract_ct_invoices():
    extract_connect = pyodbc.connect()
    y = 'Invoices'
    z = ['dateCreated','dateAging','dateOrder','datePaid','ShipDate','TaxPaid']

    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index)
    for i in structure_name_type.index:
        if i == length-1:
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR)'
        elif (structure_name_type.loc[i,'FieldType'] == 'decimal') & (i == length-1):
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR)'
        elif structure_name_type.loc[i,'FieldType'] == 'decimal':
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR),'
        elif structure_name_type.loc[i,'FieldName'] == 'NoteInternal':
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR),'
        elif (structure_name_type.loc[i,'FieldName'] == 'NoteInternal') & (i == length-1):
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR)'    
        else:
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR),'
    query_final = 'select ' + query + ' from ' + '"' + y + '"'
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_invoices(data):
    data['locationEntry'] = data['locationEntry'].str.replace('ANA','Ana')
    data['locationEntry'] = data['locationEntry'].str.replace('SAC','Sac')
    return data

@task
def load_ct_invoices(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_invoices'
    p ={'IDxInvoice':BigInteger(),'IDxBilling':BigInteger(),'dateCreated':Date(),'dateAging':DateTime(),'dateOrder':DateTime(),'datePaid':DateTime(),'TaxPaid':DateTime(),'TaxPaid':DateTime(),'TaxPaid':DateTime(),'TaxPaid':DateTime(),'ShipDate':DateTime(),'TaxPaid':DateTime(),'TaxPaid':DateTime(),'NoteInternal':TEXT(length=65535,collation='utf8mb4_bin')}
    check_constraint = connection.execute("SELECT * \
                                           FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE \
                                           WHERE REFERENCED_TABLE_SCHEMA = 'TDRW' AND REFERENCED_TABLE_NAME = 'ct_invoices' \
                                           AND REFERENCED_COLUMN_NAME = 'IDxInvoice' AND CONSTRAINT_NAME = 'invoice_iline'")
    row = check_constraint.fetchone()
    if row == None:
        pass
    else:
        connection.execute('ALTER TABLE ct_iline DROP FOREIGN KEY invoice_iline')    
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX invoice ON ct_invoices(IDxInvoice)')
    connection.execute('DELETE a  from ct_invoices a WHERE a.IDxInvoice is null')
    connection.execute('ALTER TABLE ct_invoices ADD PRIMARY KEY(IDxInvoice)')
    connection.execute('CREATE INDEX date ON ct_invoices(dateCreated)')
    connection.execute('CREATE INDEX invoice_date ON ct_invoices(IDxInvoice,dateCreated)')
    connection.execute('CREATE INDEX billing ON ct_invoices(IDxBilling)')
    connection.execute('CREATE INDEX location ON ct_invoices(locationEntry(4))')
    connection.execute('CREATE INDEX sales_person ON ct_invoices(CreatedBy(50))')
    connection.execute('CREATE INDEX invoice_location ON ct_invoices(IDxInvoice,locationEntry(4))')
    connection.execute('CREATE INDEX date_location_invoice ON ct_invoices(dateCreated,locationEntry(4),IDxInvoice)')
    connection.close()    
    
@task
def extract_ct_supplier():
    extract_connect = pyodbc.connect()
    y = 'Supplier'
    z = []

    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index) 
    for i in structure_name_type.index:
        if i == length-1:
            query += structure_name_type.loc[i,'FieldName']
        elif (structure_name_type.loc[i,'FieldType'] == 'decimal') & (i == length-1):
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR)'
        elif structure_name_type.loc[i,'FieldType'] == 'decimal':
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR),'
        else:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '",'
    query_final = 'select ' + query + ' from ' + '"' + y + '"' 
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_supplier(data):
    return data

@task
def load_ct_supplier(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_supplier'
    p = {'_ContactID':BigInteger()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX supplier ON ct_supplier(_ContactID)')
    connection.close()
    
@task
def extract_ct_iline():
    extract_connect = pyodbc.connect()
    y = 'ILine'
    z = ['TimeStamp']

    
    sql_structure = "SELECT * FROM filemaker_fields where TableName = '"+ y +"'"
    structure = pd.read_sql(sql_structure,extract_connect)
    query = ''
    structure_name_type = structure[['FieldName','FieldType']]
    length = len(structure_name_type.index) 
    for i in structure_name_type.index:
        if i == length-1:
            query += structure_name_type.loc[i,'FieldName']
        elif (structure_name_type.loc[i,'FieldType'] == 'decimal') & (i == length-1):
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR)'
        elif structure_name_type.loc[i,'FieldType'] == 'decimal':
            query += 'CAST("' + structure_name_type.loc[i,'FieldName'] + '" AS VARCHAR),'
        else:
            query += '"' + structure_name_type.loc[i,'FieldName'] + '",'
    query_final = 'select ' + query + ' from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    columns = []
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        columns.append(structure_name_type.loc[i,'FieldName'])
    data.columns = columns
    structure_name_type = structure[['FieldName','FieldType']]
    for i in structure_name_type.index:
        if structure_name_type.loc[i,'FieldType'] == 'decimal':
            data.loc[:,structure_name_type.loc[i,'FieldName']] = pd.to_numeric(data.loc[:,structure_name_type.loc[i,'FieldName']],errors='coerce')
    return data
    

@task
def transform_ct_iline(data):
    return data

@task(max_retries=3,timeout=3600,retry_delay=timedelta(seconds=60))
def load_ct_iline(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_iline'
    p = {'TimeStamp':DateTime(),'IDxInvoice':BigInteger(),'IDxSup':BigInteger(),'IDxProd':BigInteger()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX invoice ON ct_iline(IDxInvoice)')
    connection.execute('CREATE INDEX supplier ON ct_iline(IDxSup)')
    connection.execute('CREATE INDEX prod ON ct_iline(IDxProd)')
    connection.execute('CREATE INDEX invoice_prod ON ct_iline (IDxInvoice,IDxProd)')
    connection.execute('CREATE INDEX sup_prod ON ct_iline (IDxSup,IDxProd)')
    connection.execute('DELETE a  from ct_iline a WHERE a.IDxInvoice is null')
    connection.close()
    
@task
def ct_iline_pk():
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    connection.execute('ALTER TABLE ct_iline ADD PRIMARY KEY(IDxILine)')
    connection.close()
    
@task
def extract_ct_transfer():
    extract_connect = pyodbc.connect("DSN=dbchef;UID=Matthew Maldonado;PWD=sealhawk2430")
    y = 'Transfer'
    z = ['ts']

    query_final = 'select * from ' + '"' + y + '"'
        
    data = pd.read_sql(query_final,extract_connect,parse_dates=z)
    extract_connect.close()
    return data
    
@task
def transform_ct_transfer(data):
    return data

@task
def load_ct_transfer(data):
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    w = 'ct_transfer'
    p = {'ts':DateTime(),'IDxProd':BigInteger()}
    data.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('CREATE INDEX prod ON ct_transfer(IDxProd)')
    connection.execute('CREATE INDEX prod_ts ON ct_transfer(IDxProd,ts)')
    connection.execute('CREATE INDEX prod_loc_ts ON ct_transfer(IDxProd,location(4),ts)')
    connection.execute('CREATE INDEX loc ON ct_transfer(location(4))')
    connection.execute('CREATE INDEX prod_loc ON ct_transfer(IDxProd,location(4))')
    connection.execute('CREATE INDEX type ON ct_transfer(transferType(8))')
    connection.execute('CREATE INDEX prod_location_ts_type ON ct_transfer(IDxProd,location(4),ts,transferType(8))')
    connection.close()
    
@task
def delete_non_matching_invoice_ilne():
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    connection.execute('DELETE a  from ct_iline a \
                        LEFT JOIN ct_invoices b on a.IDxInvoice = b.IDxInvoice \
                        WHERE b.IDxInvoice is null')
    connection.close()
    
@task
def create_foreign_key_invoice_iline():
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    connection.execute('ALTER TABLE ct_iline ADD CONSTRAINT invoice_iline FOREIGN KEY (IDxInvoice) REFERENCES ct_invoices(IDxInvoice) ON DELETE CASCADE')
    connection.close()
    
@task
def qty_on_hand():
    connection = create_engine(,connect_args={'connect_timeout': 36000,'charset':'utf8mb4'}).connect()
    y = "ct_inventory"
    z=[]
    query_final = "select IDxProd,QtyOnHandFV,QtyOnHandTor,QtyOnHandPat,QtyOnHandAna, \
                    QtyOnHandVN,QtyOnHandLA,QtyOnHandDC,QtyOnHandCom,QtyOnHandDC2,QtyOnHandSM,QtyOnHandOak,\
                    QtyOnHandSac,QtyOnHandIE,QtyOnHandSD from " + y
    data = pd.read_sql(query_final,connection,parse_dates=z)
    qtyonhand = data.melt(id_vars=["IDxProd"], 
                            var_name="Location", 
                            value_name="QtyOnHand")
    qtyonhand['Location'] = qtyonhand['Location'].replace({'QtyOnHandFV':'FV','QtyOnHandTor':'Tor','QtyOnHandPat':'Pat','QtyOnHandAna':'Ana',
                                                            'QtyOnHandVN':'VN','QtyOnHandLA':'LA','QtyOnHandDC':'DC','QtyOnHandCom':'Com','QtyOnHandDC2':'DC2',
                                                             'QtyOnHandSM':'SM','QtyOnHandOak':'Oak','QtyOnHandSac':'Sac','QtyOnHandIE':'IE','QtyOnHandSD':'SD'})
    qtyonhand['IDxProd_Location'] = qtyonhand['IDxProd'].astype(str) + qtyonhand['Location']
    w = 'ct_qty_on_hand'
    p = {'IDxProd':BigInteger()}
    qtyonhand.to_sql(name=w,con=connection,if_exists = 'replace',index=False,dtype=p)
    connection.execute('ALTER TABLE ct_qty_on_hand ADD Id BIGINT PRIMARY KEY AUTO_INCREMENT')
    connection.execute('CREATE INDEX prod ON ct_qty_on_hand(IDxProd)')
    connection.execute('CREATE INDEX prod_location ON ct_qty_on_hand(IDxProd,Location(4))')
    connection.execute('CREATE INDEX idxprod_location ON ct_qty_on_hand(IDxProd_Location(8))')
    connection.close()
    
@task
def qty_filled():
    connection = mysql.connector.connect(host=,
                             user=,
                             password=,
                             db=,
                             collation="utf8mb4_general_ci",
                            connect_timeout = 36000)
    
    cursor = connection.cursor()
    cursor.execute("CALL qty_filled()")
    connection.close()

@task
def copy_fm():
    try:
        stop = check_output(r"fmsadmin -y -u -p stop server -f", shell=True).decode()
    except CalledProcessError as e:
        stop = e
    print(stop)    
    copy = check_output(r'xcopy /y "C:\Users\Owner\Desktop\T-file\DbChef.fmp12" "C:\Program Files\FileMaker\FileMaker Server\Data\Databases"', shell=True).decode()
    print(copy)
    start = check_output(r"fmsadmin start server", shell=True).decode()
    print(start)
    
@task
def restart_xdbc():
    restart_xdbc = check_output(r"fmsadmin -y restart xdbc", shell=True).decode()
    time.sleep(120)

qty_filled_new = MySQLExecute(db_name=,user=,password=,host=,port=,query="CALL qty_filled()")


#contacts
#inventory
#orders
#po
#erf
#invoices
#supplier
#ilines
    
with Flow("Daily Data Load") as flow:
    filemaker = copy_fm()
    restart_x = restart_xdbc(upstream_tasks=[filemaker])
    e_ct_contacts = extract_ct_contacts(upstream_tasks=[restart_x])
    t_ct_contacts = transform_ct_contacts(e_ct_contacts)
    l_ct_contacts = load_ct_contacts(t_ct_contacts)
    e_ct_inventory = extract_ct_inventory(upstream_tasks=[restart_x])
    t_ct_inventory = transform_ct_inventory(e_ct_inventory)
    l_ct_inventory = load_ct_inventory(t_ct_inventory)
    e_ct_orders = extract_ct_orders(upstream_tasks=[restart_x])
    t_ct_orders = transform_ct_orders(e_ct_orders)
    l_ct_orders = load_ct_orders(t_ct_orders)
    e_ct_po = extract_ct_po(upstream_tasks=[restart_x])
    t_ct_po = transform_ct_po(e_ct_po)
    l_ct_po = load_ct_po(t_ct_po)
    e_erf = extract_erf(upstream_tasks=[restart_x])
    t_erf = transform_erf(e_erf)
    l_erf = load_erf(t_erf)
    e_ct_supplier = extract_ct_supplier(upstream_tasks=[restart_x])
    t_ct_supplier = transform_ct_supplier(e_ct_supplier)
    l_ct_supplier = load_ct_supplier(t_ct_supplier)
    e_ct_invoices = extract_ct_invoices(upstream_tasks=[restart_x])
    t_ct_invoices = transform_ct_invoices(e_ct_invoices)
    l_ct_invoices = load_ct_invoices(t_ct_invoices)
    e_ct_iline = extract_ct_iline(upstream_tasks=[restart_x,l_ct_invoices])
    t_ct_iline = transform_ct_iline(e_ct_iline)
    l_ct_iline = load_ct_iline(t_ct_iline)
    #create_iline_pk = ct_iline_pk(upstream_tasks=[l_ct_iline])
    e_ct_transfer = extract_ct_transfer(upstream_tasks=[restart_x,e_ct_invoices,e_ct_iline])
    t_ct_transfer = transform_ct_transfer(e_ct_transfer)
    l_ct_transfer = load_ct_transfer(t_ct_transfer,upstream_tasks=[l_ct_iline,l_ct_invoices])
    d_non_m_invoice_iline = delete_non_matching_invoice_ilne(upstream_tasks=[l_ct_iline,l_ct_invoices,l_ct_transfer])
    #c_fk_iline = create_foreign_key_invoice_iline(upstream_tasks=[l_ct_iline,l_ct_invoices,l_ct_transfer,create_iline_pk])
    c_qty_on_hand = qty_on_hand(upstream_tasks=[l_ct_iline,l_ct_invoices,l_ct_transfer,l_ct_inventory])
    #Not in use duplicate of below c_qty_filed = qty_filled(upstream_tasks=[l_ct_iline,l_ct_invoices,l_ct_transfer,l_ct_inventory,c_qty_on_hand,d_non_m_invoice_iline])
    c_qty_filed = qty_filled_new(name="qty_filled_new",upstream_tasks=[l_ct_iline,l_ct_invoices,l_ct_transfer,l_ct_inventory,c_qty_on_hand,d_non_m_invoice_iline])`


The tasks qty_filled(),qty_filled_new(), create_foreign_key_invoice_iline(),  and ct_iline_pk() cause problems.  

Below is the stored procedure called by qty_filled_new() and qty_filled()

`CREATE PROCEDURE `qty_filled`()
BEGIN
    DROP TABLE IF EXISTS ct_qty_filled;
    CREATE TABLE ct_qty_filled AS SELECT a.Date as Date,a.Location as Location,a.IDxProd as IDxProd,COALESCE(b.QtyFilled,0) as QtyFilled,CONCAT(a.IDxProd,a.Location) AS IDxProd_Location
                                    FROM (SELECT a.calendar_date as Date,c.Location, b.IDxProd as IDxProd
                                          FROM fiscal_calendar a
                                          CROSS JOIN (SELECT DISTINCT a.IDxProd as IDxProd
                                                      FROM ct_inventory a
                                                      WHERE a.IDxProd is not null) b
                                          CROSS JOIN(SELECT DISTINCT a.locationEntry as Location
                                                     FROM ct_invoices a
                                                     WHERE a.locationEntry IN ('FV','VN','LA','Tor','Ana','SD','SM','Pat','IE','Oak','Com','DC', 'Sac', 'DC2')) c
                                  WHERE a.calendar_date between date_sub(curdate(), interval 366 day) AND date_sub(curdate(), interval 1 day)) a
                                  LEFT JOIN (SELECT a.dateCreated as Date,a.locationEntry as Location,b.IDxProd as IDxProd,SUM(b.QtyFilled) as QtyFilled
                                              FROM ct_invoices a
                                             INNER JOIN ct_iline b on a.IDxInvoice = b.IDxInvoice
                                             WHERE a.dateCreated >= date_sub(curdate(), interval 366 day)
                                             Group By 1,2,3) b  on a.Date = b.Date AND a.Location = b.Location AND a.IDxProd = b.IDxProd;
    ALTER TABLE ct_qty_filled ADD Id BIGINT PRIMARY KEY AUTO_INCREMENT;
    CREATE INDEX prod ON ct_qty_filled(IDxProd);
    CREATE INDEX date ON ct_qty_filled(Date);
    CREATE INDEX location ON ct_qty_filled(Location(4));
    CREATE INDEX prod_location ON ct_qty_filled(IDxProd,Location(4));
    CREATE INDEX date_prod ON ct_qty_filled(Date,IDxProd);
    CREATE INDEX date_location ON ct_qty_filled(Date,Location(4));
    CREATE INDEX date_location_prod ON ct_qty_filled(Date,Location(4),IDxProd);
    CREATE INDEX idxprod_location ON ct_qty_filled(IDxProd_Location(8));
END`

Setup
Windows 10, Prefect 0..12.5 , using dask, local storage, ,mysql 5.7.26-0ubuntu0.18.10.1,pymysql 0.9.3, mysqlconnector 8.0.21,sql alchemy 1.3.16,dask 2.13.0, anaconda  custom    py37_1, python 3.7.3

**Comment by mmaldo** [comment]
Doesn't seem like the code blocks are working sorry
