### ISSUE TITLE
Windows pathing error when using Dockerfile method for Docker storage

### ISSUE THREAD

**Issue by aroder** [PrefectHQ/prefect#3066]
## Description
When using the Dockerfile method to create storage and then register a flow with prefect cloud, there is an error COPY step that copies the flow into the Docker image.

```
C:\dev\scratch>python register.py
[2020-07-31 20:35:20] INFO - prefect.Docker | Building the flow's Docker storage...
Step 1/10 : FROM python:3.8.3
 ---> 659f826fabf4
Step 2/10 : RUN pip install prefect
 ---> Using cache
 ---> 79ef06e51b9f
Step 3/10 : RUN pip install pip --upgrade
 ---> Using cache
 ---> a0b4e4dec623
Step 4/10 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.12.6#egg=prefect[kubernetes]
 ---> Using cache
 ---> 00faab6426bd
Step 5/10 : RUN pip install boto3 wheel
 ---> Using cache
 ---> 7dd663167bd5
Step 6/10 : RUN mkdir -p /opt/prefect/
 ---> Using cache
 ---> ffca70689d93
Step 7/10 : COPY C:\dev\scratch\tmpk7_nwvnd\prefect-windows-pathing-repro.flow /opt/prefect/flows/prefect-windows-pathing-repro.prefect
COPY failed: stat /var/lib/docker/tmp/docker-builder087651641/C:devscratchtmpk7_nwvndprefect-windows-pathing-repro.flow: no such file or directory
Traceback (most recent call last):
  File "register.py", line 16, in <module>
    flow.register(
  File "C:\dev\scratch\venv\lib\site-packages\prefect\core\flow.py", line 1575, in register
    registered_flow = client.register(
  File "C:\dev\scratch\venv\lib\site-packages\prefect\client\client.py", line 677, in register
    serialized_flow = flow.serialize(build=build)  # type: Any
  File "C:\dev\scratch\venv\lib\site-packages\prefect\core\flow.py", line 1429, in serialize
    storage = self.storage.build()  # type: Optional[Storage]
  File "C:\dev\scratch\venv\lib\site-packages\prefect\environments\storage\docker.py", line 327, in build
    self._build_image(push=push)
  File "C:\dev\scratch\venv\lib\site-packages\prefect\environments\storage\docker.py", line 391, in _build_image
    raise ValueError(
ValueError: Your docker image failed to build!  Your flow might have failed one of its deployment health checks - please ensure that all necessary files and dependencies have been included.
```

This appears to be due to the fact that a Windows path is assumed to be a Posix path, so the backslashes. See above in "Step 7/10." 

## Expected Behavior
The registration process should build the image without error, and finish the docker push and prefect registration processes.

## Reproduction
https://github.com/aroder/prefect-windows-pathing-repro

## Environment
Reproduced on 2 different Windows machines. Here are specs for one:

![image](https://user-images.githubusercontent.com/23650/89075619-d6e3b580-d33b-11ea-8159-6cbacd121310.png)

![image](https://user-images.githubusercontent.com/23650/89075645-e82cc200-d33b-11ea-8809-39f22d1a6d74.png)

Optionally run `prefect diagnostics` from the command line and paste the information here. -->
```
>prefect diagnostics
{
  "config_overrides": {
    "cloud": {
      "use_local_secrets": true
    },
    "context": {
      "secrets": false
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.19041-SP0",
    "prefect_version": "0.12.6",
    "python_version": "3.8.3"
  }
}
```

**Comment by joshmeek** [comment]
Thanks for opening @aroder! Yes this definitely looks like a path formatting issue. By "Dockerfile method" do you mean you are providing a custom Dockerfile to the flow's Docker storage?

**Comment by aroder** [comment]
Yes

--
Adam Roderick
303-335-9929

On Aug 3, 2020, at 06:20, Josh Meek <notifications@github.com> wrote:

﻿
Thanks for opening @aroder! Yes this definitely looks like a path formatting issue. By "Dockerfile method" do you mean you are providing a custom Dockerfile to the flow's Docker storage?

**Comment by joshmeek** [comment]
Quick q @aroder does this happen for you when running off of master? There are some Docker storage windows changes going out in the next release and I'm wondering if they solve it 🤔

**Comment by aroder** [comment]
@joshmeek make sure I did this the way you expected. I installed based on the latest commit hash from the master branch

```pip install -e git+git@github.com:PrefectHQ/prefect.git@f0a2056af0bcac28cca3554862dc0f2041b88b02#egg=prefect```

`pip list` then shows `prefect                 0.12.6+63.gf0a2056af`.

Running `python register.py` in the repro repository, which calls `flow.storage()` and `flow.register()`, does get past the copy step!

```Step 7/10 : COPY ./tmp92s4_1a_/prefect-windows-pathing-repro.flow /opt/prefect/flows/prefect-windows-pathing-repro.prefect```


(@klassenjr check it out)

**Comment by joshmeek** [comment]
Amazing! I thought the error looked a bit familiar haha, once the next release is out and the issue is resolved we can close 🙂

**Comment by sbreidbach-edr** [comment]
@joshmeek I'm seeing something sort of similar and wondering if maybe they are related?

```
Step 7/9 : COPY C:\<my_project_path>\tmp4tih0dcw\healthcheck.py /opt/prefect/healthcheck.py
COPY failed: stat /var/lib/docker/tmp/docker-builder873466440/C:Develprefect-servercontainersdata-platformtmp4tih0dcwhealthcheck.py: no such file or directory
```
Minimal example to reproduce:

**Dockerfile**
```
FROM prefecthq/prefect:latest-python3.8
```
**Build script**
```
storage = Docker(
    image_name="my-image-name",
    image_tag='latest',
    dockerfile='Dockerfile',
)

storage.build()
```

Everything is fine if I don't specify a `Dockerfile` in the storage constructor. (Glad to make a different ticket if you think these are unrelated, btw.)

**Comment by joshmeek** [comment]
Yeah @sbreidbach-edr that appears to be related. Do you think you could also install off of master and give it another shot like @aroder did?

**Comment by sbreidbach-edr** [comment]
Worked like magic @joshmeek .
