### ISSUE TITLE
Filter does not work on Flow error pane (Prefect Cloud)

### ISSUE THREAD

**Issue by mousetree** [PrefectHQ/prefect#3078]
## Description

When viewing a flow (i.e. https://cloud.prefect.io/xxx/flow/xxx), the filters on the error panel do not work. By default they are set to 24 hours but show all errors. When changing the filter there is no change.

<img width="918" alt="Screenshot 2020-08-02 at 20 16 20" src="https://user-images.githubusercontent.com/1752671/89180314-d17fa880-d591-11ea-852e-fbc1d12d14d0.png">

## Expected Behavior

The list of errors shown should be determined by the filter.

## Reproduction

Visit a flow with errors and change the report filter. Can DM you on Slack with the link to a flow on our instance

**Comment by joshmeek** [comment]
cc @znicholasbrown

**Comment by cicdw** [comment]
This has been addressed in the new UI (https://github.com/PrefectHQ/ui)
