### ISSUE TITLE
Prefect Slack Channel

### ISSUE THREAD

**Issue by bralbral** [PrefectHQ/prefect#3116]
Good day! I will face a problem connecting to the Slack channel. When specifying your mailbox, the letter with the invitation never arrives.
![image](https://user-images.githubusercontent.com/54455457/89695557-18b4c300-d91d-11ea-9028-9d155222e0ca.png)

**Comment by jlowin** [comment]
Hi @bralbral, the sign-up process for our Slack community is entirely managed by Slack and not something we have any control over, so unfortunately I'm not sure we can be helpful here. Perhaps the email went to a spam folder? [Here's](https://join.slack.com/t/prefect-community/shared_invite/enQtODQ3MTA2MjI4OTgyLTliYjEyYzljNTc2OThlMDE4YmViYzk3NDU4Y2EzMWZiODM0NmU3NjM0NjIyNWY0MGIxOGQzODMxNDMxYWYyOTE) a join link just in case there's an issue with the one you tried.
