### ISSUE TITLE
Passing result argument to GCS

### ISSUE THREAD

**Issue by Marlin-Na** [PrefectHQ/prefect#3123]
When running

```
GCS(bucket="....", result=prefect.engine.results.LocalResult())
```
I got the following error. Should be a easy fix by checking if `result` is present in `kwargs`.

```
  File "/home/xxx/.local/lib/python3.7/site-packages/prefect/environments/storage/gcs.py", line 58, in __init__
    super().__init__(result=result, stored_as_script=stored_as_script, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'result'
```

**Comment by joshmeek** [comment]
Hi @Marlin-Na what is your use case for passing a `result` directly into the storage class? The `result` kwarg on the default `Storage` interface is for setting a default result to use for all flows which utilize that storage class and in the case of GCS storage is it passing `GCSResult(bucket=bucket)`. To set a `result` you should specify it on a [`Task` or `Flow` directly](https://docs.prefect.io/core/concepts/results.html#pipeline-persisted-results).

**Comment by Marlin-Na** [comment]
@joshmeek Thanks for the tip that `result` can be passed via `Flow`. In my use case, I just want to use GCS for storing the flows but not results. So I use `LocalResult` to override the default.

**Comment by joshmeek** [comment]
Ah yes, set that local result on the Flow object 🙂
