### ISSUE TITLE
slack_notifier attempts to connect to prefect server in core only runs.

### ISSUE THREAD

**Issue by Fraznist** [PrefectHQ/prefect#3133]
## Description

Slack notifier attempts to supply the notification with a prefect server link to the task/flow. To check whether the flow run reports back to a server, the notifier checks for existence of `flow_run_id` in context. This worked well until `0.12.2`. Now, `flow_run_id`s are always included in context. This renders the current conditional in the Slack notifier old, always attempting to connect to a server, and receiving connection refused errors.

## Expected Behavior

Get a slack notification regardless, without a link to prefect server if the flow run is not backed by a server.

## Reproduction

Runs correctly in `0.12.1`, fails in `0.13.1`. Should fail in `0.12.2` and upper, based on commit history. Without an active prefect server, `0.13.1` throws an exception. With an active server, the flow runs, but the generated url for the slack notifications doesn't exist in the server.
```
from prefect import Flow, task
import prefect
from prefect.utilities.notifications import slack_notifier
@task
def log_run_id():
    prefect.context.get("logger").warning(prefect.context.get("flow_run_id"))
@task(state_handlers=[slack_notifier])
def get_1():
    return 1
with Flow("slack_example") as flow:
    log = log_run_id()
    result = get_1(upstream_tasks=[log])
flow.run()
```

**Comment by ludwigm** [comment]
I think this is related to this here: https://github.com/PrefectHQ/prefect/issues/2930

**Comment by joshmeek** [comment]
Yep @ludwigm @Fraznist it appears to be the same issue. What are your thoughts on this option becoming toggle-able based on an argument to the `slack_notifier`? Maybe something like `backend_info: bool = True`

**Comment by Fraznist** [comment]
@ludwigm @joshmeek sorry, didn't see #2930 . I am ok with a toggle, sounds simple. I was thinking more of a `try: except:` approach for attempting to connect to graphql. Toggle sounds way simpler though, and avoids roundtrips to graphql.
