### ISSUE TITLE
Build Server + UI images as part of Core release

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#3149]
## Current behavior

Server and UI are versioned independently of Prefect Core, and Core currently points at `latest` Docker image for each. This means that users can not easily specify that they want to use a version of Server or the UI that is a contemporary of a specific version of Core.

## Proposed behavior

Core should build its own versions of Server + the UI as part of its own release process, naming and tagging them appropriately (`prefecthq/core-server:0.13.2`). This way any given version of Prefect can run against either `prefecthq/core-server:latest` or a tagged version, and Prefect (not Server or UI) is in control of that versioning process.

Note this would explicitly be separate from Server/UI's own image building process (which is why I'm proposing prefecthq/core-server instead of prefecthq/server as the image name).

**Comment by joshmeek** [comment]
@jlowin What's the need for building separate DockerHub repositories when we could do a tagging convention like `prefecthq/server:core-0.13.2`?

**Comment by jlowin** [comment]
@cicdw and I discussed that and there was a specific reason I'm not recalling at the moment. Perhaps it wasn't a particularly good one.

**Comment by jlowin** [comment]
Never mind: I misunderstood our conversation. Your suggestion is the way to go 👍

**Comment by cicdw** [comment]
Closed by #3204
