### ISSUE TITLE
It would be nice if Client was robust to simplejson vs. json

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#3151]
## Description

Currently, `Client._request` only catches `json.decoder.JSONDecoderError`. However, if the `simplejson` library is present in the environment, `requests` defaults to using `simplejson` instead of `json`. https://github.com/psf/requests/issues/3052

Instead of catching and raising a useful message, Prefect will raise `simplejson.errors.JSONDecoderError`

## Expected Behavior

It would be very nice if the `Client` could handle both cases. I'll have a draft PR coming in a minute here.

## Reproduction

1. Install simplejson in your environment (`pip install simplejson`)
2. Make sure you log out of prefect via cli `prefect auth logout`
3. Run a hello world flow and try to register it

```
from prefect import task, Flow

@task
def say_hello():
    print("Hello, world!")

with Flow('test') as flow:
	say_hello()

flow.register(project_name='test')
```

Here, you'll see the `simplejson` error come through the stack trace instead of an error informing you about the actual issue.

## Environment

`pip install simplejson`

**Comment by joshmeek** [comment]
Closed by #3152
