### ISSUE TITLE
Provide Kubernetes Tasks Examples

### ISSUE THREAD

**Issue by gaby** [PrefectHQ/prefect#3194]
## Current behavior
Currently Prefect provides no code examples on how to use the different Kubernetes Tasks.

## Proposed behavior
Provide generic examples for the different Kubernetes Tasks for at least one kind of API.

**Deployments**
- CreateNamespacedDeployment
- DeleteNamespacedDeployment
- ListNamespacedDeployment
- PatchNamespacedDeployment
- ReadNamespacedDeployment
- ReplaceNamespacedDeployment

**Comment by amroakmal** [comment]
@joshmeek 
Can you please elaborate more on what's needed for this issue to be made?
Thanks !

**Comment by joshmeek** [comment]
@amroakmal Sure thing! In the docstrings for the Kubernetes tasks (seen [here](https://docs.prefect.io/api/latest/tasks/kubernetes.html)) it would be nice to have snippets of how they are used. Things like:

```python
from prefect.tasks.kubernetes import CreateNamespacedJob

yaml_template = ...

job_task = CreateNamespacedJob(body=yaml_template)

with Flow(...):
  t1 = job_task()
```

Pretty much filling in the `...` places with actual usable code. Hope this helps!

**Comment by amroakmal** [comment]
@joshmeek 
I currently don't have enough time, but I wanna take this issue and I'll try to make it.
Would you please assign it to me?

Thanks
