### ISSUE TITLE
Update note about storage requirements in orchestration tutorial

### ISSUE THREAD

**Issue by shaunc** [PrefectHQ/prefect#3200]
Hello!

I've found an issue here:`In order to deploy your flow to Kubernetes the flow is required to have a Docker Storage with the image pushed to a registry that your Kubernetes cluster has access to.`

Page reference: https://docs.prefect.io/orchestration/tutorial/k8s.html

Is it in fact true that a flow deployed to Kubernetes EKS can't use s3 storage? If so, an explicit affirmation of this limitation would be helpful, as it is a bit counterintuitive: `S3 storage is not supported even for Kubernetes clusters running on AWS.` Otherwise, the documentation should be amended.

**Comment by joshmeek** [comment]
The orchestration tutorial has been updated to account for the new run configuration pattern https://docs.prefect.io/orchestration/tutorial/flow_config.html#flow-configuration
