### ISSUE TITLE
Add config parameter for LocalDaskExecutor 'scheduler' argument

### ISSUE THREAD

**Issue by antosiv** [PrefectHQ/prefect#3205]
## Current behavior

LocalDaskExecutor 'scheduler' parameter [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/executors/dask.py#L389) can be set only with explicit LocalDaskExecutor initialization. In prefect server installation this leads to the inability to set the appropriate default executor for specific agent (explicit executor instance can only be attached to flow run or flow environment)
Note:  LocalDaskExecutor **kwargs are dask config parameters, and could be set with environment variables

## Proposed behavior

Section [engine.executor.local_dask] in [engine config](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/config.toml#L137) with one parameter 'scheduler'

## Example

This parameter could be useful for setting default LocalDaskExecutor with scheduler='processes' in agent

P.S. Sorry about my english, I am not sure in the quality of my language skills

**Comment by Marlin-Na** [comment]
I have a similar issue. I guess a more general solution is to provide something like `engine.executor.default_kwargs` in prefect config.
