### ISSUE TITLE
Specifying the job image for DaskKubernetesEnvironment when using S3 flow storage.

### ISSUE THREAD

**Issue by alexifm** [PrefectHQ/prefect#3232]
(Adapted from the Slack channel)

## Current behavior

On Python3.7 when using `DaskKubernetesEnvironment` and S3 flow storage, you likely will get a pickle error:
```
$ kubectl logs pod/prefect-job-e74114b4-26n6v 
[2020-08-21 21:55:08] INFO - prefect.S3 | Downloading simple-flow-8/2020-08-21t21-54-33-484226-00-00 from infima-etl-flows
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/execute.py", line 80, in cloud_flow
    raise exc
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/execute.py", line 69, in cloud_flow
    flow = storage.get_flow(storage.flows[flow_data.name])
  File "/usr/local/lib/python3.8/site-packages/prefect/environments/storage/s3.py", line 101, in get_flow
    return cloudpickle.loads(output)
TypeError: an integer is required (got type bytes)
```

As you can see in this traceback, prefect is is running with python3.8.   We detected this as a result of the K8s job using the image `prefecthq/prefect:all_extras-0.13.3` which we did not choose.  In fact, it turns out the job will always opt for this image unless you do something a bit esoteric.

Here is what we found:
1. Inside `execute`, Prefect needs to build a spec for the job and it uses the scheduler spec as a base.  The function `prefect.utilities.storage.get_flow_image` gets an image name from `flow.environment.metadata`.  It then uses this image name to override the image in the scheduler spec.  This is where `prefecthq/prefect:all_extras-0.13.3` comes from but we had no idea how it was set since we don’t do anything of the sort.
1. We detected that `flow.environment.metadata` was updated to the prefect all_extras image after calling `flow.register` and traced it to here:
https://github.com/PrefectHQ/prefect/blob/389eabd68238edda57c23f58c5907bc0edd6c443/src/prefect/client/client.py#L736-746

To solve this, we have to explicitly pass `{"image": image_name}` to the `metadata` argument in `DaskKubernetesEnvironment`
https://github.com/PrefectHQ/prefect/blob/0.13.3/src/prefect/environments/execution/dask/k8s.py#L72

## Proposed behavior

I don't have a good suggestion so I just have a few questions that can help hone in on something so others don't face the same issue.  

- Should the default behavior change?  I think I get why the scheduler’s image is overridden: there’s very little guarantee on the image for the scheduler that it would even have the dependencies for Prefect or the flow code.  
- Could there be prefect images for different versions of Python?
- Maybe it would be better to fall back on the worker’s image?  
- Perhaps a more explicit argument like `job_image` could be added to `DaskKubernetesEnvironment` about what image the K8s job should use?  Or perhaps a clarification on what `metadata` is (there is vert little description of it now) or how important one of the values could be?

**Comment by emcake** [comment]
@alexifm  I think this is related to the confusion between agents, environments and executors. Some of this comes up in #2928 which has some longer-term solutions. The way I am currently handling this is to use S3 storage and a Kubernetes agent, but with a local environment:

```python
with Flow(...) as flow:
    
    flow.storage = S3('your-s3-bucket')
    flow.environment =  \
        LocalEnvironment( \
            executor=...,\
            metadata={"image": "repo/image:tag"}\
        )
```

The kubernetes agent will launch the flow as a job using the image specified in the `metadata` property above, at which point it can just run like a normal flow in a `LocalEnvironment`.

**Comment by jcrist** [comment]
Specifying the image in the metadata was intentional and is by design. The docs on this are admittedly a bit scattered, but here's the reference: https://docs.prefect.io/orchestration/execution/storage_options.html#non-docker-storage-for-containerized-environments

We're in the middle of simplifying agent + environment + storage configuration options (there's far too many ways to configure the same thing), so hopefully this will will all shake out cleaner in the coming weeks.

An alternative for your specific case would be to not use the `DaskKubernetesEnvironment` at all, and instead use the local environment with a `DaskExecutor`. We're moving away from having dask-specific environments in favor of configuring dask things on the executor itself. For example:

```python
flow.environment = LocalEnvironment(
    executor=DaskExecutor(
        cluster_class="dask_kubernetes.KubeCluster",
        cluster_kwargs={"image": "image-used-by-dask-workers"},
        adapt_kwargs={"minimum": 0, "maximum": 10}
    ),
    metadata={"image": "image-used-by-prefect-job"},
)
flow.storage = S3(...)
```

`LocalEnvironment`, `FargateTaskEnvironment`, and `KubernetesJobEnvironment` all support configuring an executor on them, and the `DaskExecutor` should have all the config options needed to configure a dask cluster using any dask cluster manager.

**Comment by alexifm** [comment]
Hey, thanks for the clarification!  Ive covered a fair amount of the documentation but clearly not that part. I apologize if I sounded overly critical about this. The direction you all are taking it sounds good.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
