### ISSUE TITLE
Setting mapped task runs to a Pending state doesn't always run them

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#3246]
## Description

Setting mapped children to a `Pending` state after a run has failed doesn't re-submit them for execution and their states aren't counted against the flow run's final state.

## Expected Behavior

All pending runs are re-submitted for execution when a flow run is in a non-`Finished` state.

## Reproduction

This flow will randomly fail (can adjust the incidence in the `Node` class):
```
import prefect
from prefect import Flow, Task
import time
import random


class Version(Task):
    def run(self):
        self.logger.info(f"Running on Prefect v{prefect.__version__}")
        return


class Root(Task):
    def run(self):
        self.logger.info("Root running...")
        time.sleep(random.randint(1, 5))
        self.logger.info("Root complete.")
        return list(range(5))


class Node(Task):
    def run(self):
        self.logger.info(f"{self.name} running...")
        time.sleep(random.randint(1, 5))
        if random.random() > 0.98:
            raise ValueError(f"{self.name} failed :(")
        else:
            self.logger.info(f"{self.name} complete.")
            return list(range(15))

with Flow("Varying Durations") as flow:
    version = Version()

    root = Root()(upstream_tasks=[version])
    node1_1 = Node(name="Node 1_1").map(upstream_tasks=[root])
    node1_2 = Node(name="Node 1_2").map(upstream_tasks=[root])
    node2_1 = Node(name="Node 2_1").map(upstream_tasks=[node1_1, node1_2])
    node3_1 = Node(name="Node 3_1").map(upstream_tasks=[node2_1])
    node3_2 = Node(name="Node 3_2").map(upstream_tasks=[node2_1])
    node4_1 = Node(name="Node 4_1").map(upstream_tasks=[node3_1, node3_2])
```
when downstream mapped runs are "Restarted", meaning the failed runs are put in a `Pending` state and the flow run is re-scheduled, they're never run, leaving a run schematic like this (note the 2 pending runs):
![Screen Shot 2020-09-01 at 8 59 17 PM](https://user-images.githubusercontent.com/27291717/91920131-277d6400-ec96-11ea-9e2c-7285d4d97386.png)

## Environment

Core version: `0.13.2`
Running on Prefect Cloud
Docker Storage (base image: `python:3.8`)

**Comment by znicholasbrown** [comment]
cc @cicdw

**Comment by znicholasbrown** [comment]
A couple examples of this for the Prefect team:
http://cloud.prefect.io/prefect/flow-run/e78ab09a-a475-42fe-9267-d3d590fc4c2c
http://cloud.prefect.io/prefect/flow-run/6c6608cd-aeb7-4ce7-b35c-d4588fb79513

**Comment by cicdw** [comment]
Hey @znicholasbrown - I finally figured this one out: your Flow / Tasks don't store their results (because there is no configured result location), and therefore on reruns your Runners don't know how wide the mapped pipelines are (and so all children are effectively "hidden" from view).

I think I can use `n_map_states` (available and populated on newer versions of Core) to ensure all child tasks are actually visited.
