### ISSUE TITLE
TestLogger to Allow Tasks to Run Outside Flow Context

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#3256]
## Current behavior

Inspired by this thread: https://prefect-community.slack.com/archives/CL09KU1K7/p1599138897233900

When a user wants to run their flow with `flow.run()` and use the Prefect logger, they generally end up putting something like this in their task:
```python
@task
def extract():
  logger = prefect.context.get("logger")
  logger.debug("An informative message")
```

This works wonderfully in a flow context. However, if a user ever wants to call the `extract.run()` method outside of a flow context (like during development, testing, or notebooking) `logger.debug` will produce an error. Since, generally speaking, the rest of the code inside a task works just fine outside of a Flow context, this can be frustrating.

## Proposed behavior

It would be awesome if there were some sort of `TestLogger` that maintained the Prefect Logger API & just printed statements. That way, we wouldn't have to change/comment out the code inside our tasks when running unit tests or developing locally.

**Comment by cicdw** [comment]
Closed by #3266
