### ISSUE TITLE
Compression for S3 Upload / Download

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#3259]
## Current behavior

Inspired by: https://prefect-community.slack.com/archives/CL09KU1K7/p1599160102266700

The S3 tasks in the task library currently don't compress/uncompress data for you. It would be a lot cooler if they did.

## Proposed behavior

Add a `compression` argument to these tasks that could support different methods. Maybe start with `gzip`?

## Example

Sometimes we want to compress info before uploading to S3 to save on upload/download time.

**Comment by cicdw** [comment]
Closed by #3297
