### ISSUE TITLE
Change https://localhost:8080 in welcome message to http?

### ISSUE THREAD

**Issue by shunwen** [PrefectHQ/prefect#3270]
It took me a while to figure out that `https` doesn't work on port 8080. In the Prefect documents, `http` is used. Shouldn't it also generate `http` instead of `https` in the welcome message?

https://github.com/PrefectHQ/prefect/blob/f554d1313638286d4183b136f97b56bfbfae58db/src/prefect/cli/server.py#L375

**Comment by jcrist** [comment]
Fixed by #3271. Closing.
