### ISSUE TITLE
Show-flow-logs gives AttributeError with Docker agent

### ISSUE THREAD

**Issue by masonlr** [PrefectHQ/prefect#3288]
## Description

Starting a docker agent with `--show-flow-logs` can lead to a run error:

```
[2020-09-09 13:21:44,568] ERROR - agent | Error while deploying flow: AttributeError("Can't pickle local object 'Agent.run_heartbeat_thread.<locals>.run'")
```

This makes it difficult to debug custom images when, for example, flows are stuck in a Submitted state.

Initial Slack discussion was here: https://prefect-community.slack.com/archives/C014Z8DPDSR/p1599658959061800

## Expected Behavior

Flow log should allow a user to deterimine why a custom Docker image is broken.

## Reproduction

There are four reproduction cases here: https://github.com/masonlr/prefect-logging-issue

* [01-minimal-working](https://github.com/masonlr/prefect-logging-issue/tree/master/01-minimal-working): is a working minimal custom image using `prefecthq/prefect:0.13.5-python3.8`
* [02-minimal-with-flow-logs-BROKEN](https://github.com/masonlr/prefect-logging-issue/tree/master/02-minimal-with-flow-logs-BROKEN): illustrates the above AttributeError when `--show-flow-logs` is applied
* [03-python-custom-image](https://github.com/masonlr/prefect-logging-issue/tree/master/03-python-custom-image): is a working image using a customised `python:3.8-slim` base image
* [04-ubuntu-custom-BROKEN](https://github.com/masonlr/prefect-logging-issue/tree/master/04-ubuntu-custom-BROKEN): is an example that I am trying to troubleshoot using a customised `ubuntu:20.04` base image

## Environment

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.5-x86_64-i386-64bit",
    "prefect_version": "0.13.5",
    "python_version": "3.8.3"
  }
}
```

**Comment by jcrist** [comment]
Thanks for the issue report, this should be fixed by #3339. If you want to run things now before this fix is released, you can downgrade the python environment your agent is running in to python 3.7 (the default multiprocessing context changed on osx in python 3.8).
