### ISSUE TITLE
JSON needs escapes for passing params in prefect run cloud 

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#3295]
## Description
If I try to run a flow using the CLI and add params using the example in the help section (from calling prefect run cloud -h) I get an error message.  For example:
`prefect run cloud -n Params-New -p Jenny -ps {"c":3}`
Gives the following error:
_json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)_

If I enter the params as a string with an escape round other speechmarks, it works:
For example:
`prefect run cloud -n Params-New -p Jenny -ps "{\"c\":3}"`
works fine
## Expected Behavior

Best case scenario: 
`prefect run cloud -n Params-New -p Jenny -ps {"c":3}` works fine. 
Second best:
We update the docs to show an example with correct JSON formatting. 

## Reproduction
`prefect run cloud -n FLOWNAME -p PROJECT -ps {"c":3}`

**Comment by cicdw** [comment]
@zhen0 - if you put your parameters within single ticks it will work as you expect:
```
prefect run cloud -n FLOWNAME -p PROJECT -ps '{"c":3}'
```
you can even include spaces!
```
prefect run cloud -n FLOWNAME -p PROJECT -ps '{"c" : 3}'
```

I'll update the example documentation to clarify this point.

**Comment by zhen0** [comment]
Ah great. Thanks!
