### ISSUE TITLE
Heartbeat appears to fail due to virtual environment installation not being honoured

### ISSUE THREAD

**Issue by Lyalpha** [PrefectHQ/prefect#3313]
## Description

Heartbeat fails to start when `prefect` is installed as part of a virtual environment.

My task logs all look like the following, suggesting that the virtual environment is not being honoured in the subprocess call creating the heartbeat, for some reason.

![image](https://user-images.githubusercontent.com/12103194/93117183-593ef380-f6b6-11ea-9159-269b01193788.png)

I have run `source .venv/bin/activate` prior to starting `prefect agent`, `prefect server`, defining and registering the flow etc. As shown at the bottom I can recreate the error simply in the python cli, but only when the venv is not activated - I don't know why it wouldn't be activated when `prefect` internally makes the heartbeat subprocess call upon creating a flow run, unless I am missing something.

I may be way off with this, also let me know if there's more I can provide to help diagnose it.

## Expected Behavior

Heartbeat process runs correctly, finding the `prefect` binary in the virtual environment.

## Reproduction

Running with a distributed Dask cluster and local agent.

```
# install prefect and venv
python3.8 -m venv .venv
source .venv/bin/activate
pip install prefect
```

All following commands inside the virtual environment.

Prefect server/agent setup:
```
# running local server
prefect server start --ui-port 8081

# create project
prefect create project myproject

# start agent
prefect agent start local
```

Flow definition:
```
#test_flow.py

from prefect import Flow, task
from prefect.engine.executors import DaskExecutor
from prefect.environments import LocalEnvironment

@task
def extract():
    """Get a list of data"""
    return [1, 2, 3]

@task
def transform(data):
    """Multiply the input by 10"""
    return [i * 10 for i in data]

@task
def load(data):
    """Print the data to indicate it was received"""
    print("Here's your data: {}".format(data))

with Flow("ETL") as flow:
    e = extract()
    t = transform(e)
    l = load(t)

flow.environment = LocalEnvironment(
    executor=DaskExecutor(address="tcp://daskscheduleraddress:8786")
)
flow.register(project_name="myproject")
```
Reproduce:
```
$ python test_flow.py
Result check: OK
Flow URL: http://localhost:8080/flow/de47e16a-6f13-446f-816f-6d642f86a4e2
 └── ID: de47e16a-6f13-446f-816f-6d642f86a4e2
 └── Project: myproject
 └── Labels: ['host']

$ prefect run flow --name "ETL" --project "myproject"

# Check UI logs to see:
```Heartbeat failed to start.  This could result in a zombie run.
Traceback (most recent call last):
  File "/home/goto/.kabeiros/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 56, in inner
    p = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'prefect'
```

I can recreate the issue with:
```
# no venv activated
In [1]: import subprocess                                                       

In [2]: subprocess.Popen(["prefect", "heartbeat"])                              
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-58e4c46f4704> in <module>
----> 1 subprocess.Popen(["prefect", "heartbeat"])

/usr/lib64/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

/usr/lib64/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1362                         if errno_num == errno.ENOENT:
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)
   1366 

FileNotFoundError: [Errno 2] No such file or directory: 'prefect': 'prefect'
```
Compared to:
```
# venv activated
In [1]: import subprocess

In [2]: subprocess.Popen(["prefect", "heartbeat"])
Out[2]: <subprocess.Popen at 0x7fbf46754f70>

In [3]: Usage: prefect heartbeat [OPTIONS] COMMAND [ARGS]...

  Send heartbeats back to the Prefect API.

  Usage:
      $ prefect heartbeat [task-run/flow-run] -i ID

  Arguments:
      task-run   Send heartbeat for a given task run ID
      flow-run   Send heartbeat for a given flow run ID

Options:
  -h, --help  Show this message and exit.
```

## Environment

```
$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.18.0-147.5.1.el8_1.x86_64-x86_64-with-glibc2.28",
    "prefect_backend": "server",
    "prefect_version": "0.13.6",
    "python_version": "3.8.5"
  }
```

**Comment by cicdw** [comment]
Thanks for the detailed issue @Lyalpha !  This surprises me; we take care to pass down all OS environment variables to that subprocess, which I would have thought to include all relevant PATH variables for your virtual environment.  Here's the code: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/executors.py#L50-L61

I don't normally use `venv`, so maybe there's a quirk to that environment manager that needs to be handled explicitly?

**Comment by jcrist** [comment]
@Lyalpha, I've pushed a patch at #3361 that might fix your issue. Could you test it locally to see if your problem is resolved?

You can install the PR branch locally using:

```
pip install -U git+https://github.com/PrefectHQ/prefect.git@use-sys-executable-local-agent
```

If things continue to fail, the output of

```
python -m site
```

run from within the same directory you're running `prefect agent start local` would be useful.

**Comment by Lyalpha** [comment]
Thanks for the feedback and looking at this.

I've run through the replication steps after doing `pip install git+https://github.com/jcrist/prefect@use-sys-executable-local-agent` (note it failed to find the branch on the `PrefectHQ` org, as in your comment).
`pip freeze` gives:
`prefect @ git+https://github.com/jcrist/prefect@d04f904305253314389721f2d607cf64adc59fd0`

Unfortunately, I still see the same heartbeat error in the log.

```
$ pwd
/home/goto/.myproject
$ python -m site  # with venv activated
sys.path = [
    '/home/goto/.myproject',
    '/usr/local/lib/python38.zip',
    '/usr/local/lib/python3.8',
    '/usr/local/lib/python3.8/lib-dynload',
    '/home/goto/.myproject/.venv/lib/python3.8/site-packages',
]
USER_BASE: '/home/goto/.local' (exists)
USER_SITE: '/home/goto/.local/lib/python3.8/site-packages' (doesn't exist)
ENABLE_USER_SITE: False
```

This is in the same directory where I ran `prefect agent start local` manually to do the test above.

I've just done this quickly as currently distracted from this work - I will retry soon with more time to check everything over and reply if anything is different.

**Comment by jcrist** [comment]
Hmmm that's unfortunate. You wouldn't happen to have a directory or file named `prefect` in `/home/goto/.myproject`?

**Comment by Lyalpha** [comment]
Nope, no file/dir that I can see could cause a conflict anywhere.

The agent seems to run fine, and set-off everything appropriately, so I did initially think it would be related to the lines that were also linked above:

> https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/executors.py#L50-L61

I saw the environment is passed to `subprocess.Popen`, as mentioned, which I why I was puzzled it was not finding `prefect` command.

I will try to dig around what exactly ends up in `clean_env` - and make sure from that it should find `prefect` in its `PATH`.

**Comment by cicdw** [comment]
@Lyalpha it might be useful to print / log your `os.env` both right before the subprocess is called and within the subprocess command; I'm sure a diff of the env vars would be informative.

**Comment by Lyalpha** [comment]
So, a bit of digging: I have logged `os.environ` at various stages in the `executors.py` file, and do some basic `os.system("which prefect")` as well.

When the *flow run* calls heartbeat,  i.e. somewhere after the log entry `"Beginning Flow run for 'ETL'"`, it appears to perform successfully. My environment is fully populated and there is no exception raised about heartbeat.

However, when a *task run* reaches this code, i.e. sometime after `Task 'extract': Starting task run...`, it does fail. I see that my environment has changed - the most obvious being that `PATH` is change to a default value of only `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin`, and crucially is no longer prefixed by `/home/goto/.myproject/.venv/bin`, where `prefect` lives.

From comparing the "good" (flow run) and "bad" (task run) environments I see that only `PATH`, and `PREFECT__ENGINE__EXECUTOR__DASK__ADDRESS` change value (the latter from `'tcp://daskscheduleraddress:8786'` to `'tcp://${DASK__SCHEDULER__HOST}:${DASK__SCHEDULER__PORT}'`, which is how it is literally defined in my `.env` file I export prior to anything - note this is exporting to system env, not related to python virtual env activation - this seems a bit odd to me)

In addition, for completeness, the following entries are missing in the "bad" env:
```
'LS_COLORS',
 'SSH_CONNECTION',
 'HISTCONTROL',
 'HOSTNAME',
 'OLDPWD',
 'VIRTUAL_ENV',
 'XDG_SESSION_ID',
 'SELINUX_ROLE_REQUESTED',
 'PWD',
 'LINES',
 'SSH_CLIENT',
 'SELINUX_LEVEL_REQUESTED',
 'SSH_TTY',
 'COLUMNS',
 'MAIL',
 'TERM',
 'XMODIFIERS',
 'SELINUX_USE_CURRENT_RANGE',
 'SHLVL',
 'LANGUAGE',
 'DBUS_SESSION_BUS_ADDRESS',
 'XDG_RUNTIME_DIR',
 'PS1',
 'HISTSIZE',
 'LESSOPEN',
 '_',
 'PREFECT__CLOUD__AGENT__LABELS',
 'PREFECT__CONTEXT__FLOW_RUN_ID',
 'PREFECT__CONTEXT__FLOW_ID',
 'PREFECT__CLOUD__USE_LOCAL_SECRETS',
 'PREFECT__LOGGING__LOG_TO_CLOUD',
 'PREFECT__LOGGING__LEVEL',
 'PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS',
 'PREFECT__ENGINE__TASK_RUNNER__DEFAULT_CLASS',
 'PYTHONPATH'
```

**Comment by Lyalpha** [comment]
Suspicions confirmed. I am running `dask-worker` in a `systemd` service and had started it from inside the `.venv` (`/home/goto/.myproject/.venv/bin/dask-worker`), which is enough for `python`-executable programs. However, in this case hacking an explicit `.venv` activation prior, with:

```
. /home/goto/.myproject/.venv/bin/ && /home/goto/.myproject/.venv/bin/dask-worker
```
has just given me a full flow + tasks with no sign of the error. The worker now knows about the correct `PATH`.

My apologies for the goose chase - firstly suspecting the wrong program of misbehaving, and then finding out its actually looks like my own setup that is at fault anyway! Thanks for the time looking into it.
