### ISSUE TITLE
k8s agent should set environment variable name in job pod as upper case letters

### ISSUE THREAD

**Issue by raychen** [PrefectHQ/prefect#3314]
## Description

I installed a k8s agent using yaml generated by the following:

`prefect agent install kubernetes -e FOO=value-foo`

then in the generated yaml file I got:

```
Environment:
    PREFECT__CLOUD__AGENT__ENV_VARS__FOO: value-foo
```
Which looks reasonable (upper case)

However in the job pod spawned by the agent, 
the name of the environment variable becomes `foo` (lower case)

## Expected Behavior

The case of environment variable used in install command should be respected
or 
just stick to upper case because it's the convention

## Reproduction

as said in description

## Environment

{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-18.7.0-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.13.6",
    "python_version": "3.7.6"
  }
}

**Comment by cbowdon** [comment]
This surprised me too! @raychen why did you close this issue? I think it is good to raise it.

**Comment by cbowdon** [comment]
Nevermind, I think this is intentional behaviour:

https://docs.prefect.io/core/concepts/configuration.html#environment-variables
