### ISSUE TITLE
Schedule uses wrong time when timezone specified

### ISSUE THREAD

**Issue by 4d11** [PrefectHQ/prefect#3340]
## Description

I want to assign my flow to run weekly at 9AM EST. When the flow is deployed, the time is not consistent. On the flows page on the UI, the first 5 scheduled runs will be assigned to start at "10AM EDT". I'm running this locally using prefect server. My local timezone is EST. When daylight saving kicks in, the time is scheduled as 9AM

## Expected Behavior

* All future flow runs should be scheduled for 9AM instead of 10AM

## Reproduction

```
    def demo():
        time = pendulum.from_format('09:00', "HH:mm", tz='EST')
        return IntervalSchedule(
            start_date=time,
            interval=datetime.timedelta(days=7),
        )
flow = get_flow()
flow.schedule = demo()
flow.deploy()
```

**Comment by cicdw** [comment]
Hi @4d11 - interestingly, I believe you are seeing the correct timestamps!  9AM EST == 10 AM EDT.  

I don't believe you can configure the displayed Time Zone in Prefect Server, but in Prefect Cloud you can toggle the displayed Time Zone to match the one you expect.

**Comment by 4d11** [comment]
Ah I see, I assumed they would be the same, thanks for the quick reply!
