### ISSUE TITLE
ShellTask Powershell Compatibility

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#3375]
## Current behavior

ShellTask doesn't seem to work with powershell by default

## Proposed behavior

Update to accept `powershell` as a valid input.

**Comment by dylanbhughes** [comment]
Related: https://github.com/PrefectHQ/prefect/issues/1984

**Comment by jbowlen** [comment]
Is it foreseeable when powershell scripts can be executed?

**Comment by madkinsz** [comment]
I'd be happy to review a pull request adding this functionality, but cannot provide a timeline for our team looking into it.
