### ISSUE TITLE
Task Run Fails to Read Upstream Result the First Time a Flow is Run on Windows

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#3378]
## Description

![image](https://user-images.githubusercontent.com/2325367/94076056-4faa3f80-fdca-11ea-9269-56edfae373bf.png)
> it seems that the file is either getting cleaned up OR reading from the file has a bug that is specific to windows paths

## Expected Behavior

Result is read properly

## Environment

Windows

**Comment by cicdw** [comment]
@dylanbhughes I am unable to reproduce on a Windows machine; I'll need some example code + configuration.  Note that this could happen if you are using caching (`cache_for`) across multiple machines with a `LocalResult`

**Comment by dylanbhughes** [comment]
@cicdw https://prefecthq.slack.com/archives/C01B5EL5KMJ/p1600455977011400

**Comment by cicdw** [comment]
OK after attempting to reproduce this in a few different ways, I've concluded that _something_ external to Prefect must have deleted this file.  Based on the traceback, it's clear this Task used caching, and the non-existence of the file meant that this particular `Cached` state could not be used.  

I _do_ think Prefect should have more gracefully handled this situation by logging a warning that we were unable to read the result and therefore will not be using that particular cache.  Leaving this ticket open to track this UX enhancement.
