### ISSUE TITLE
Documentation fails to load a new page

### ISSUE THREAD

**Issue by justengland** [PrefectHQ/prefect#3398]
[##]( #url) Description

Javascript Error preventing navigation within the docs.
https://docs.prefect.io/orchestration/recipes/deployment.html#how-are-prefect-flows-stored-inside-docker-containers

app.78b37d40.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 409 failed.
(missing: https://docs.prefect.io/assets/js/409.d603e5b6.js)
    at Function.r.e (https://docs.prefect.io/assets/js/app.78b37d40.js:1:7708)
    at v-a676c1f8 (https://docs.prefect.io/assets/js/app.78b37d40.js:13:53977)
    at https://docs.prefect.io/assets/js/app.78b37d40.js:13:58101
    at o (https://docs.prefect.io/assets/js/app.78b37d40.js:3:16745)
    at Generator._invoke (https://docs.prefect.io/assets/js/app.78b37d40.js:3:16498)
    at Generator.forEach.e.<computed> [as next] (https://docs.prefect.io/assets/js/app.78b37d40.js:3:17102)
    at n (https://docs.prefect.io/assets/js/app.78b37d40.js:3:44207)
    at s (https://docs.prefect.io/assets/js/app.78b37d40.js:3:44410)
    at https://docs.prefect.io/assets/js/app.78b37d40.js:3:44469
    at new Promise (<anonymous>)

## Expected Behavior

When I click in the left hand navigation from from the above url a javascript error prevents navigation.

## Reproduction

It seems to be after using the documentation system this happens, I am not sure how I got it in this state exactly.

**Comment by joshmeek** [comment]
@justengland What browser are you using? Currently I am unable to reproduce

**Comment by zhen0** [comment]
Looks like a similar issue was raised as part of this discussion in the community slack: https://prefect-community.slack.com/archives/C014Z8DPDSR/p1602679132179900. Adding here to make sure we're tracking it.

**Comment by JGrubb** [comment]
Hi there, I've also had the same issue.  Pasting from Slack - 

> Hello documentation team.  I may have just solved the puzzle of why sometimes the doc site will not load the page I'm requesting from the sidebar nav.  I think this only happens when I've had the particular page open for a while - like since before the last docs rebuild and deploy maybe?  You're using some JS client framework to serve the site and the link or content that is requested once the site is rebuilt goes stale if I haven't reloaded the page.  Does this sound plausible?

It occurred to me later that some pages will work while others will not until I do a full reload of the docs site.  My guess is that the pages that are touched/rebuilt are the ones that won't load if you've left the docs site open for a while.

**Comment by zhen0** [comment]
Another [comment from the community slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1603802257185400):  Hello documentation team.  I may have just solved the puzzle of why sometimes the doc site will not load the page I'm requesting from the sidebar nav.  I think this only happens when I've had the particular page open for a while - like since before the last docs rebuild and deploy maybe?  You're using some JS client framework to serve the site and the link or content that is requested once the site is rebuilt goes stale if I haven't reloaded the page.  Does this sound plausible?
