### ISSUE TITLE
DaskKubernetesEnvironment to setup first container command same as KubernetesJobEnvironment

### ISSUE THREAD

**Issue by mgsnuno** [PrefectHQ/prefect#3401]
## Current behavior

`DaskKubernetesEnvironment:_populate_scheduler_spec_yaml` doesn't populate the first container the same way as `KubernetesJobEnvironment:_populate_build_time_job_spec_details`. The code bellow is missing:

```python
# set command on first container
yaml_obj["spec"]["template"]["spec"]["containers"][0]["command"] = [
    "/bin/sh",
    "-c",
]
# set args on first container
yaml_obj["spec"]["template"]["spec"]["containers"][0]["args"] = [
    'python -c "import prefect; prefect.environments.execution.load_and_run_flow()"'
]
```

Because this is not included automatically, `DaskKubernetesEnvironment` with a custom `scheduler_spec_yaml` will fail to execute.

## Proposed behavior

Add `/bin/sh -c "python -c 'import prefect; prefect.environments.execution.load_and_run_flow()'"` to `scheduler_spec_yaml` automatically, than the user doesn't have to worry about it.

Also: wouldn't it be possible to allow `KubernetesJobEnvironment` to have a default  `job.yaml` same as `DaskKubernetesEnvironment`?

**Comment by joshmeek** [comment]
Hi @mgsnuno the DaskKubernetesEnvironment does have a default scheduler job and worker pod yaml specs (see the files [here](https://github.com/PrefectHQ/prefect/tree/master/src/prefect/environments/execution/dask)). You can use these as inspiration for your custom spec as we have deliberately chosen not to overwrite custom user provided scheduler and worker specs for this environment.

**Comment by mgsnuno** [comment]
Hi @joshmeek. That is ok, it's a design decision, the issue is because `/bin/sh -c "python -c 'import prefect; prefect.environments.execution.load_and_run_flow()'" to scheduler_spec_yaml` is not included automatically, `DaskKubernetesEnvironment` with a custom scheduler_spec_yaml will fail to execute. 

Maybe we should add the following in `DaskKubernetesEnvironment`:
>When providing a custom YAML job spec the first container in the spec must be the container that the flow runner will be executed on. The following has to be part of the first container:
```python
containers:
  - command: ["/bin/sh", "-c"]
    args:
      [
        'python -c "import prefect; prefect.environments.execution.load_and_run_flow()"',
      ]
```

**Comment by joshmeek** [comment]
@mgsnuno Yeah adding that piece of documentation sounds like a great idea!

**Comment by jcrist** [comment]
`DaskKubernetesEnvironment` & `KubernetesJobEnvironment` are both now deprecated in favor of `KubernetesRun`.

With regards to above issue - empty job/pod templates are valid to pass to `KubernetesRun`, the agent manually adds any required fields needed by prefect. So this problem should be resolved when using `KubernetesRun`.

Closing.
