### ISSUE TITLE
DateParameter

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3425]
Building on #3327: a `DateParameter` class would also be very handy.

Obviously you can go from the datetime to date easily within a task, but we currently use string parameters like `date="2020-10-01"` for templating like `target="bucket/{date}/{task_name}"` which for a datetime doesn't really work the same way.

**Comment by cicdw** [comment]
@bnaul target / result templating (and soon task name templating as well!) allows you to use Python's built-in formatting syntax e.g.,

```python
target="bucket/{date:%Y-%m-%d}/{task_name}"
```

Does that work for your situtation?

**Comment by bnaul** [comment]
whoa..........🤯 

i would say that does pretty much meet my need; i do think a proper `DateParameter` is nice for all the same reasons that a `date` object is nice, but if you think it's not worth the clutter to the namespace then that makes sense. will leave it up to you if you want to close this, but I am generally curious to hear what the future of non-JSON parameters looks like (roll your own? a couple of built-ins? lots of built-ins?)
