### ISSUE TITLE
Make flow.register() work only on flows which are different from the latest one

### ISSUE THREAD

**Issue by snenkov** [PrefectHQ/prefect#3433]
## Current behavior
If a flow is unchanged and already register, when I register it again `flow.register(project_name="Some Name")` it produced a new version.

## Proposed behavior
Either not register a flow if it's identical to the latest or have a flag in `flow.register()` which will only register the flow if different from the latest version.

## Example
`flow.register(project_name="Some Name", validate_difference=True)`  or something like that :)

**Comment by cicdw** [comment]
This makes sense - we could store some type of hash of the JSON representation of the Flow in the backend, and only create a new Flow ID when the provided JSON payload doesn't match the old one.

**Comment by sp1thas** [comment]
Awesome idea @snenkov 

This is definitely a pain point because if you want to register your flows using a CI/CD tool, then, the flow versioning becomes meaningless 😕

**Comment by alex-hsp** [comment]
Yeah i would like to do the flow registration in my CI process. One way to handle this issue is to allow to pass some sort of ID of a flow, in CI case this can be a commit hash or md5 of flow source file.

**Comment by cicdw** [comment]
This was closed by https://github.com/PrefectHQ/prefect/pull/3590 and is now released!
