### ISSUE TITLE
Failing to run flows on 0.13.10

### ISSUE THREAD

**Issue by n-batalha** [PrefectHQ/prefect#3446]
## Description

With Prefect `0.13.10`, running the below locally:

```
prefect backend server
prefect server start

# and in another shell (anonymising the secret names)
prefect agent start --show-flow-logs --verbose --label local -e SECRET_ONE=${SECRET_ONE} -e SECRET_TWO=${SECRET_TWO}
```

And then registering a flow and triggering a run via the local server page, generates these errors on the agent logs (which means the flow never starts):

```
[2020-10-07 09:53:35,745] ERROR - agent | 400 Client Error: Bad Request for url: http://localhost:4200/
```

I can confirm that the above is the right address of the server, I can query it.

Just by reverting to `0.13.7` resolves this (repeating the exact process above).

**Comment by joshmeek** [comment]
Hi @n-batalha I have found the issue here and am resolving it now! 🙂  Looks like the server images haven't been updated for `0.13.10`

**Comment by joshmeek** [comment]
@n-batalha The server `core-0.13.10` images have been updated! Let me know if it is still not working for you

**Comment by n-batalha** [comment]
@joshmeek thanks, this is now working for me
