### ISSUE TITLE
Failed to load and execute Flow's environment: TypeError

### ISSUE THREAD

**Issue by n-batalha** [PrefectHQ/prefect#3447]
## Description

I get `Failed to load and execute Flow's environment: TypeError('an integer is required (got type bytes)') ` on the minimal flow below. 

This is locally on the same setup of Prefect Server and Agent as listed in https://github.com/PrefectHQ/prefect/issues/3446 (but with 0.13.7).

## Reproduction

Ignore some redundant lines, this was from a previous reproducible example and I'm running out of time:

```
# save as bug_minimal_reproduction.py
from datetime import timedelta
from typing import NamedTuple, Any

from prefect import Flow, task
from prefect.environments.storage import S3
from prefect.engine.results import S3Result
from prefect.environments import LocalEnvironment


@task
def extract_tables():

    return {"people": 1, "companies": 2}



with Flow("Bug-example") as flow:
    all_tables = extract_tables()
    people = all_tables["people"]
    companies = all_tables["companies"]

environment = "local"
register_params = {}
register_params["project_name"] = environment
register_params["labels"] = [environment]
flow.register(**register_params)
```

Then run `python ./bug_minimal_reproduction.py`. On the Prefect Server flow page, run this flow.

## Environment

```
{
  "config_overrides": {
    "server": {
      "telemetry": {
        "enabled": true
      }
    }
  },
  "env_vars": [
    "PREFECT__LOGGING__LEVEL",
    "PREFECT__CONTEXT__SECRETS__CRUNCHBASE_API_KEY",
    "PREFECT__CLOUD__AUTH_TOKEN",
    "PREFECT__LOGGING__EXTRA_LOGGERS"
  ],
  "system_information": {
    "platform": "Darwin-19.6.0-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.13.7",
    "python_version": "3.7.3"
  }
}
```

**Comment by jcrist** [comment]
Hi @n-batalha ,

The error you're running into here is due to a mismatch between your registration environment and your execution environment, likely due to a mismatch in versions (usually Python or Prefect versions). I suspect your agent is running a different version of Python (or Prefect) than you used to register the flow. Can you check and ensure that the versions align between your registration and agent environments?

**Comment by n-batalha** [comment]
Thanks @jcrist , indeed I used Poetry to lock the versions but something went wrong, they differ. I wouldn't expect this error, can't Prefect ship the Python version and warn the user? Or maybe make sure only compatible agents pick it up? Even if using labels.

**Comment by jcrist** [comment]
> I wouldn't expect this error, can't Prefect ship the Python version and warn the user?

We could add some metadata to the registered flow to check for this and raise a better error, but it wouldn't affect all agents. Most production runs use a separate execution environment from the agent (e.g. a docker container), so the prefect version of the agent doesn't have to match that of the flow execution.

Right now though, *when running with the local agent*, we require the registration and agent environments match.

I'm going to close this for now, and will open a more specific issue to provide a better error message here.

**Comment by flavienbwk** [comment]
Running into the same issue. I had my flows working perfectly (scheduled every minute and suddenly not working anymore).

![image](https://user-images.githubusercontent.com/14158127/95682119-dc833480-0be3-11eb-96ae-52cf9c001ecf.png)

```
State Message:
Failed to load and execute Flow's environment: HTTPError('403 Client Error: Forbidden for url: http://xxx.xxx.xxx.xxx:9000/prefect/e7619cd0-e299-4e89-aca0-e01d161c4b49')
```
