### ISSUE TITLE
FargateTaskEnvironment - containerDefinition's environment should be validated by sorting the list values

### ISSUE THREAD

**Issue by AlessandroLollo** [PrefectHQ/prefect#3451]
As described in this [Slack thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1602060735083800?thread_ts=1602003197.043500&cid=CL09KU1K7)
Since the `environment` of a task definition is a `list`, it should be checked using `sorted`, otherwise the validation fails even if the existing task definition and the flow task definition have the same values for `environment`

Changes should only touch the following lines of code

https://github.com/PrefectHQ/prefect/blob/f554d1313638286d4183b136f97b56bfbfae58db/src/prefect/environments/execution/fargate/fargate_task.py#L255-L256

https://github.com/PrefectHQ/prefect/blob/f554d1313638286d4183b136f97b56bfbfae58db/src/prefect/environments/execution/fargate/fargate_task.py#L268

I believe this is a **blocking** issue for all those who wants to use Prefect together with Fargate.

**Comment by jcrist** [comment]
Fixed by #3452. Thanks!
