### ISSUE TITLE
Officially Support Python 3.9

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#3453]
Now that Python 3.9 is released, we should determine whether we need to make any changes in order to officially support it.  I ran a very basic test in #3441 but the image seems corrupted in some way that I couldn't pinpoint from a quick glance.

We might also have to wait on certain dependencies to officially support 3.9 as well, so I'm opening this issue to track progress if it ends up being more difficult than it seems.

**Comment by madkinsz** [comment]
We will likely have tentative for support soon for Python 3.9 with just our core libs as some of our extra requirements are not quite there yet (additional details available in #3441). However, we are currently blocked by a bug in dask distributed. See https://github.com/dask/distributed/issues/4168

**Comment by madkinsz** [comment]
Note that we now support 3.9 for vanilla Prefect but extras will not work until their libraries also support 3.9

**Comment by tonal** [comment]
https://github.com/dask/distributed/pull/4460

**Comment by madkinsz** [comment]
Thanks @tonal -- that means we can remove our workaround for the dask bug but I still believe many of our 'extra' requirements do not fully support 3.9 yet.

**Comment by banuni** [comment]
hey what about this? `3.10` is already out :P

**Comment by madkinsz** [comment]
Hey @banuni we're publishing Python 3.9 docker images now #4896 and Prefect itself fully supports 3.9. We've retained a warning message in the documentation because task library requirements aren't guaranteed to be fully working with 3.9, but generally there should be no issue.

**Comment by dohki** [comment]
Why don't we update this [page](https://docs.prefect.io/core/getting_started/install.html#basic-installation) to avoid confusion?
