### ISSUE TITLE
Lazarus process fails flows 

### ISSUE THREAD

**Issue by snenkov** [PrefectHQ/prefect#3487]
## Description
Currently if a task is set to have a retry longer the Lazarus process, the retry is never triggered in practice, because the Lazarus process will fail it.

## Expected Behavior
Ideally one of these should happen:
- when creating the task, a warning should exist (at least)
- or it should not be possible to create such a flow
- or it should extend the Lazarus process to be longer somehow

## Reproduction
run a task with the following decorator:
`@task(max_retries=3, retry_delay=timedelta(minutes=30))`
It will never retry.

**Comment by cicdw** [comment]
Hi @snenkov - Lazarus's job is to _reschedule_ flow runs and task runs that are incomplete but still capable of finishing.  The most prominent use of Lazarus is to reschedule Flow Runs stuck in a `Submitted` state.  This does not affect or fail retries, and retry delays of arbitrary duration are fully supported.
