### ISSUE TITLE
Allow for scheduling flows every nth business day

### ISSUE THREAD

**Issue by marwan116** [PrefectHQ/prefect#3501]
## Current behavior
We would like to schedule a flow to run every fourth business day - as @jcrist has already confirmed, there is no way right to now to implement this currently using the available prefect scheduling utilities (Interval clocks + filters + adjustments ... ).

Our use-case is we need to consume certain financial reports that get published on a 4th business day lag every month, I would assume others working in the financial industry might face a similar problem, where they need to act on the data as soon as it is made available ...

## Proposed behavior
The simple workaround is to have a custom `is_nth_business_day` filter which should resolve this.

## Example
```
        flow.schedule = Schedule(
            # fire every day
            clocks=[IntervalClock(days=1)],
            # but only on the 4th business day
            filters=[
                is_nth_business_day(4),
            ],
        )
```

**Comment by madkinsz** [comment]
Hi!

Would business days here be defined as just M-F or are you trying to exclude holidays as well?

**Comment by marwan116** [comment]
Hi @madkinsz - Ideally I would like the option to exclude holidays as well -- so perhaps the `is_nth_business_day` filter can take an optional list of holiday dates

**Comment by jcrist** [comment]
To clarify, you're asking for every 4th business day, so if it started on the first of Oct this month (and ignoring holidays) you'd get:

Oct 1
Oct 7
Oct 13
...
?

Or are you asking for the 4th business day of every month?

The first option would be easiest to do with an interval clock, if we added support for business days as a period (configure a start date, and every period ticks a new event will fire). Filters would be harder here, as the start date where you tick off intervals also matters.

The latter would be much simpler, and could be done with a filter.

**Comment by madkinsz** [comment]
> Hi @madkinsz - Ideally I would like the option to exclude holidays as well -- so perhaps the `is_nth_business_day` filter can take an optional list of holiday dates

Handling holidays makes the implementation a bit more complicated and may be out of the scope of what we'd want to bake in. It seems like the easiest way to do it is with `pandas.tseries.offsets.BusinessDay` or https://github.com/sonntagsgesicht/businessdate — I'm not sure it would make sense for us to write an entire business day implementation and I'm hesitant to add additional requirements.

@jcrist Perhaps an `IntervalClock` which computes the next date with a passed in callable?

**Comment by jcrist** [comment]
Unfortunately we don't support custom callables in our schedules, since they have to run on the server as well as locally. 

Extending `IntervalClock` to support more semantic periods (e.g. business day), possibly using a pandas's-like shorthand notation for frequencies (e.g. support some of these: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) would be the cleanest interface IMO. No strong thoughts on what we'd use to compute the datetimes, pandas is a bit heavy of a dep, but I'd rather not implement this logic in prefect itself unless it's fairly straightforward.

**Comment by madkinsz** [comment]
> Unfortunately we don't support custom callables in our schedules, since they have to run on the server as well as locally.

Alas

> Extending `IntervalClock` to support more semantic periods (e.g. business day), possibly using a pandas's-like shorthand notation for frequencies (e.g. support some of these: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) would be the cleanest interface IMO. No strong thoughts on what we'd use to compute the datetimes, pandas is a bit heavy of a dep, but I'd rather not implement this logic in prefect itself unless it's fairly straightforward.

From looking at the `businessdate` package it looks doable in ~500 lines (I'm sure it could be less or more than that depending on our implementation) but if we want to provide a lot of value to users (e.g. loading a preset holiday calendar) it seems best to lean on `pandas` which has a robust cython implementation. Splitting it into a `PandasIntervalClock(IntervalClock)` could make it an optional dependency locally but I presume we'd still need it on our servers which is a bummer since it is such a heavy package.

**Comment by cicdw** [comment]
There is a lightweight way of achieving this today, and a way we could make it more configurable in the future:

- we're only talking about 12 dates, so you could list out the 12 dates and put them in a [`DateClock`](https://docs.prefect.io/api/latest/schedules/clocks.html#datesclock)
- with a minor adjustment to the [`next_weekday`](https://docs.prefect.io/api/latest/schedules/adjustments.html) adjustment to allow for multiple `next_nth_weekday`, you could achieve this via: `CronClock` on a weekday schedule + `next_nth_weekday` + `not_filters` that filter out a short list of holidays

**Comment by jcrist** [comment]
> There is a lightweight way of achieving this today, and a way we could make it more configurable in the future:

I don't see how this gets every 4th business day, but maybe I'm misunderstanding the request. If the request was for the 4th business day of every month, I see how that would work, but not every 4th business day.

**Comment by marwan116** [comment]
Sorry @jcrist  - just reading this,  I was asking for the 4th business day of every month ... so I suppose I could make use of DatesClock ... (I am sorry I wasn't aware of this option - should have read the documentation)

**Comment by madkinsz** [comment]
> > There is a lightweight way of achieving this today, and a way we could make it more configurable in the future:
> 
> I don't see how this gets every 4th business day, but maybe I'm misunderstanding the request. If the request was for the 4th business day of every month or of every week, I see how that would work, but not every 4th business day.

Just to jot down the thought while I have it, you could probably use the `pandas` time series handling to generate the list of dates to pass into the `DatesClock` which offloads the complex date handling to something built for it but prevents us from having to require it.
