### ISSUE TITLE
LocalDaskExecutor with threaded scheduler fails to run mapped tasks with timeout on linux

### ISSUE THREAD

**Issue by mianos** [PrefectHQ/prefect#3506]
## Description
The following example: https://github.com/mianos/pbug demonstrates prefect/dask not scheduling a trivial task.
python slow.py --range=10 --sleep_time=3 > ubuntu2004run.txt

https://github.com/mianos/pbug/blob/main/ubuntu/ubuntu2004run.txt
This is on a 8 core local physical machine with no load.

## Expected Behavior
The messages '==== IN TASK XX Sleeping 3' should appear for each item in the range.
Note that the task runner is scheduling the tasks from the lines 'Task 'slow_task[3]': Starting task run...'
The result set should include results for all items.
The task runner hits the timeout (30 seconds) and everything gives up

## Reproduction
https://github.com/mianos/pbug/blob/main/slow.py
checkout, make a venv, pip install -r requirements.txt, run as above.

Sometimes this works but it seems the faster the machine the more it fails.

## Environment
I have tested it on redhat, CentOS Linux release 7.7.1908 (Core)

The results provided above are from Ununtu 20.04
Run and all versions are provided here:
https://github.com/mianos/pbug/tree/main/ubuntu

Fails on python 3.85 and python 3.6.8

{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-48-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.13.3",
    "python_version": "3.8.5"
  }
}

I can provide SSH access to some machines demonstrating the failure if needed.

**Comment by madkinsz** [comment]
Linking to the community thread for reference https://prefect-community.slack.com/archives/CL09KU1K7/p1602728642497400

**Comment by madkinsz** [comment]
Running this locally failed for me and required #3511 first (if you do not see a pickling error, that should not be a concern)

Also, I got the following error with your code

```
[2020-10-15 17:42:59] ERROR - prefect.TaskRunner | Unexpected error: TypeError('Pickling context objects is explicitly not supported. You should always access context as an attribute of the `prefect` module, as in `prefect.context`')
Traceback (most recent call last):
  File "/Users/michaeladkins/code/prefect/src/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/michaeladkins/code/prefect/src/prefect/engine/task_runner.py", line 837, in get_task_run_state
    value = timeout_handler(
  File "/Users/michaeladkins/code/prefect/src/prefect/utilities/executors.py", line 239, in timeout_handler
    return multiprocessing_timeout(fn, *args, timeout=timeout, **kwargs)
  File "/Users/michaeladkins/code/prefect/src/prefect/utilities/executors.py", line 182, in multiprocessing_timeout
    kwargs["_fn_pkl"] = cloudpickle.dumps(fn)
  File "/Users/michaeladkins/code/prefect/.venv/prefect-3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/michaeladkins/code/prefect/.venv/prefect-3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/Users/michaeladkins/code/prefect/src/prefect/utilities/context.py", line 96, in __getstate__
    raise TypeError(
TypeError: Pickling context objects is explicitly not supported. You should always access context as an attribute of the `prefect` module, as in `prefect.context`
```

You should be accessing the context with `logger = prefect.context.get("logger")`

Once I made that change this ran without issue. It's worth noting that I was on the `master` branch of `prefect` with my fixes which is a different version than yours:

```
prefect-3.8 ❯ prefect diagnostics                     
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.7-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.11+40.g86bd14d9c",
    "python_version": "3.8.6"
  }
}
```

I can try to reproduce on `0.13.3` though.

**Comment by madkinsz** [comment]
Fun, I could reproduce this exactly as you described in a linux docker container -- I'll look into it more now.

**Comment by mianos** [comment]
I'll switch to processes for this at work. Probably a safer bet considering my real tasks have winrm in them and that's as flakey as anything else on windows msdos server.

**Comment by madkinsz** [comment]
I'm going to update the title of this to reflect the scope of the bug for other users.
