### ISSUE TITLE
Extend GCSUpload task to allow bytes/gzip data

### ISSUE THREAD

**Issue by andywaugh** [PrefectHQ/prefect#3507]
## Current behavior
Currently the GCSUpload task only allows upload of strings data.

## Proposed behavior
Allow the task to accept either strings or bytes data. If strings data, maintain existing behaviour. If bytes data, use the upload_from_file method instead.

## Example
Storing gzip data in GCS.

**Comment by joshmeek** [comment]
Closed by #3508
