### ISSUE TITLE
Worker spec fails to update on DaskKubernetes cluster

### ISSUE THREAD

**Issue by aimran-adroll** [PrefectHQ/prefect#3523]
## Description

I am using the DaskKubernetesEnvironment with a custome worker_spec_file. For whatever reason, I can _no_  longer update the actual spec on the cluster. The agent keeps spawning pods with an older version of the spec file. I am also using Docker storage (see setup below)

Slack thread:
https://prefect-community.slack.com/archives/CL09KU1K7/p1602816529127300

Thus far:
* I have updated the spec file
* Registered/pushed new version of the flow
* Verified that the actual docker image is up to date on the running pods
* Deleted the flow and re-registered it with the same name 

## Expected Behavior

Any update to the spec file should be immediately picked up at the next `flow.register(...)`

## Reproduction

<details>
<summary>job.py 🐍  -- This defines externals of the flow like storage, environment etc</summary>

```python
# flow is just any regular instance of a Flow
from flows.vanilla import flow  

from prefect.environments.storage import Docker
from prefect.environments import DaskKubernetesEnvironment

REGISTRY_URL = "somewhere-nice/aitest"

flow.storage = Docker(
    registry_url=REGISTRY_URL,
    dockerfile="Dockerfile",
    image_name="ksad-doodle",
    image_tag="0.1.0",
)

flow.environment = DaskKubernetesEnvironment(
    min_workers=1,
    max_workers=2,
    worker_spec_file="worker_spec.yaml",
    scheduler_logs=True,
)

flow.register("ksad-doodle")
```

</details>

<details>
<summary>worker_spec.yaml</summary>

Note I am using the `imagePullPolicy: Always`

```yaml
kind: Pod
metadata:
  labels:
    foo: spec-we-deserve
spec:
  nodeSelector:
    compute-type: memory
  replicas: 2
  restartPolicy: Never
  containers:
    - image: somewhere-nice/aitest/ksad-doodle:0.1.0
      imagePullPolicy: Always
      args: [dask-worker, --nthreads, "4", --no-bokeh, --memory-limit, 15GB]
      name: dask-worker
      resources:
        limits:
          cpu: 2
          memory: 16G
        requests:
          cpu: 2
          memory: 15G
```

</details>

<details>
<summary>Dockerfile 🐳  </summary>

```Dockerfile
FROM daskdev/dask

RUN pip install prefect[kubernetes] pyarrow s3fs

WORKDIR /opt/joy
ADD . /opt/joy
RUN pip install .
```
</details>

Then I do:

```shell
prefect backend cloud
python job.py
```

This gives me an output like so:

<details>
<summary>bewarrre of logs 🤖  </summary>

```shell
  registered_flow = client.register(
[2020-10-16 06:43:11] INFO - prefect.Docker | Building the flow's Docker storage...
Step 1/13 : FROM daskdev/dask
 ---> 4df6f7822952
Step 2/13 : RUN pip install prefect[kubernetes] pyarrow s3fs
 ---> Using cache
 ---> 337c2b8c035b
Step 3/13 : WORKDIR /opt/joy
 ---> Using cache
 ---> 8d32f27527a5
Step 4/13 : ADD . /opt/joy
 ---> a991a3029cd9
Step 5/13 : RUN pip install .
 ---> Running in 21af6110bfa3
Processing /opt/joy
Building wheels for collected packages: joy
  Building wheel for joy (setup.py): started
  Building wheel for joy (setup.py): finished with status 'done'
  Created wheel for joy: filename=joy-0.0.1-py3-none-any.whl size=9347 sha256=382439b3e2b2eb61eaa612df2a7ff24e19d24afbbaf828e45904062778d21693
  Stored in directory: /tmp/pip-ephem-wheel-cache-eoqrnurn/wheels/94/61/4d/0a3f6f60d6dd2c62eb3ec1b380aa7dbfe44f70007d8e963d6a
Successfully built joy
Installing collected packages: joy
Successfully installed joy-0.0.1
Removing intermediate container 21af6110bfa3
 ---> 05f30b9bb5ce
Step 6/13 : RUN pip install pip --upgrade
 ---> Running in b272deccf79c
Requirement already up-to-date: pip in /opt/conda/lib/python3.8/site-packages (20.2.3)
Removing intermediate container b272deccf79c
 ---> dcf8c9c64bd5
Step 7/13 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.13.10#egg=prefect[kubernetes]
 ---> Running in 81fc5856fe55
Name: prefect
Version: 0.13.10
Summary: The Prefect Core automation and scheduling engine.
Home-page: https://www.github.com/PrefectHQ/prefect
Author: Prefect Technologies, Inc.
Author-email: help@prefect.io
License: Apache License 2.0
Location: /opt/conda/lib/python3.8/site-packages
Requires: urllib3, marshmallow-oneofschema, pyyaml, toml, distributed, pendulum, croniter, python-dateutil, click, requests, mypy-extensions, python-box, cloudpickle, docker, marshmallow, pytz, msgpack, dask, tabulate, python-slugify
Required-by:
Removing intermediate container 81fc5856fe55
 ---> 8955a0c0fd5d
Step 8/13 : RUN pip install wheel
 ---> Running in 81b61fbff3fe
Requirement already satisfied: wheel in /opt/conda/lib/python3.8/site-packages (0.35.1)
Removing intermediate container 81b61fbff3fe
 ---> fe6c182c838d
Step 9/13 : RUN mkdir -p /opt/prefect/
 ---> Running in d08edf583928
Removing intermediate container d08edf583928
 ---> 1a6e96019da6
Step 10/13 : COPY ./tmpei3pn058/ksad-doodle.flow /opt/prefect/flows/ksad-doodle.prefect
 ---> 654b17188c43
Step 11/13 : COPY ./tmpei3pn058/healthcheck.py /opt/prefect/healthcheck.py
 ---> b63aa96e98fa
Step 12/13 : ENV PREFECT__USER_CONFIG_PATH=/opt/prefect/config.toml
 ---> Running in 1f5fe68b0c1e
Removing intermediate container 1f5fe68b0c1e
 ---> bf72f33e7a20
Step 13/13 : RUN python /opt/prefect/healthcheck.py '["/opt/prefect/flows/ksad-doodle.prefect"]' '(3, 8)'
 ---> Running in 70c7229afc0c
Beginning health checks...
System Version check: OK
Cloudpickle serialization check: OK
Result check: OK
Environment dependency check: OK
All health checks passed.
Removing intermediate container 70c7229afc0c
 ---> fc5974b49455
Successfully built fc5974b49455
Successfully tagged somewhere-nice/aitest/ksad-doodle:0.1.0
[2020-10-16 06:43:27] INFO - prefect.Docker | Pushing image to the registry...
Pushing [==================================================>]  12.47MB/11.81MB
Flow URL: https://cloud.prefect.io/praxis-etl/flow/ASKME-IF-YOU-NEED-IT
 └── ID: ASKME-IF-YOU-NEED-IT
 └── Project: ksad-doodle
 └── Labels: []


```

</details>

## Environment

environment details
```
>>> import dask
>>> dask.__version__
'2.30.0'


❯ docker --version                                                                 
Docker version 19.03.8, build afacb8b

❯ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}


```

```shell
❯ prefect diagnostics
{
  "config_overrides": {
    "cloud": {
      "agent": {
        "auth_token": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.3-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.10",
    "python_version": "3.8.5"
  }
}
```

**Comment by joshmeek** [comment]
@aimran-adroll Thanks for opening, I'll take a look at this but I don't think this functionality has changed recently. First thought, I wonder if the Docker build step is caching the layer where your flow is added:
```
Step 10/13 : COPY ./tmpei3pn058/ksad-doodle.flow /opt/prefect/flows/ksad-doodle.prefect
 ---> 654b17188c43
```

Could you try setting `build_kwargs={"nocache": True}` on your Docker storage and see if that does anything?

**Comment by aimran-adroll** [comment]
Good idea! I will give it a go and report back 👍🏽 

In the meantime, is there a way to dump out whats in the /opt/prefect/flows/blah.prefect

I poked at it last night .. seems some sorta picked file. There is at least references to `environment` etc. It would be nice to be able to dump it out to screen from the container itself

**Comment by joshmeek** [comment]
Hmm without modifying any code the way to print it out would be to exec into the container and run something like:

```
from prefect import Flow

Flow.load("blah")
```

**Comment by aimran-adroll** [comment]
Following up .... `build_kwargs={"nocache": True}` did not help

I am still seeing the job submitting the old spec. 

Is there anything else I can provide to chase it down on your end?

**Comment by joshmeek** [comment]
@aimran-adroll Is it possible that kubernetes is caching the image? i.e. if you provide a different tag for your Docker storage what happens.

**Comment by aimran-adroll** [comment]
Thanks @joshmeek 

Two bit of news
1. I used the builder_kwargs. I verified the image has new worker_spec_file.yaml. I even downloaded it in the k8s cluster (with a random pod just so I can `exec`). The resulting image had the update. 

Then I submitted a prefect job and still the same issue

2. Finally, the bumped the image tag as you recommended and it magically works 🚀 

Now, I am super confused. How should I bust the cache? I do not know enough on how the prefect-agent pulls down the info around what specs to be submitted.

**Comment by joshmeek** [comment]
Glad you got it working! This doesn't actually pertain to the prefect agent at all and it is actually kubernetes natively not pulling the updated image because [it has the same tag](https://kubernetes.io/docs/concepts/containers/images/#updating-images) 🙂

**Comment by aimran-adroll** [comment]
Thats puzzling ... here is the bit from my worker_spec_file. I do have the imagePullPolicy to be 'Always'. Usually thats enough

I even verified that the actual image on the node in my cluster has the right stuff (old tag but updated worker_spec) 

```yaml
  containers:
    - image: somewhere-nice/aitest/ksad-doodle:0.1.0
      imagePullPolicy: Always                                                    #<-----------------------
      args: [dask-worker, --nthreads, "4", --no-bokeh, --memory-limit, 15GB]
      name: dask-worker
      resources:
```

**Comment by joshmeek** [comment]
Yeah so the agent is responsible for creating the initial prefect-job that actually deserializes your flow and executes the DaskKubernetesEnvironment. That initial prefect job has a [default set to IfNotPresent](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/agent/kubernetes/job_spec.yaml#L14) which is why it is not pulling the updated image with the new spec. So your workers are updated with that spec however the pod that runs the Dask scheduler is not so it's spinning up with workers with the old spec (even though the spec file in the worker container is correct).

This is something that the new RunConfig pattern is seeking to alleviate (currently an _experimental_ feature but should be more widely used soon)

**Comment by aimran-adroll** [comment]
Thanks Josh. That makes so much sense now 😌 

I will have to remember that for now. I will checkout the RunConfig 

Please feel free to close out the ticket
