### ISSUE TITLE
Logging occurs twice when logging.basicConfig(level=logging.INFO) is set globally.

### ISSUE THREAD

**Issue by davidbernat** [PrefectHQ/prefect#3524]
## Description

PS: This workflow automation tool is wonderful! But...

The Flow/Task logging of Prefect prints the same messages twice.
<img width="1006" alt="Screen Shot 2020-10-16 at 3 24 07 PM" src="https://user-images.githubusercontent.com/5396131/96300758-1aa59d00-0fc4-11eb-985a-4980ab7e73ba.png">

This begins to occur when I set global Python logging configuration. In other instances of this problem, in other packages, setting the package logger (`prefect.utilities.logging.logger`) equal to the global logger solves this problem. In this case it does not. What does one do?
<img width="385" alt="Screen Shot 2020-10-16 at 3 24 16 PM" src="https://user-images.githubusercontent.com/5396131/96300892-593b5780-0fc4-11eb-900d-4b2be914299a.png">

Thank you!

**Comment by joshmeek** [comment]
@davidbernat Try setting `prefect.utilities.logging.prefect_logger = logger` to override the default Prefect logger.

**Comment by davidbernat** [comment]
That solves the problem. Thank you, Is there another solution you prefer
instead?

**Comment by joshmeek** [comment]
Hi @davidbernat there isn't something else I would recommend. We are actively looking in to other ways for overriding the default prefect logger and perhaps it would solve this issue in the future 👍
