### ISSUE TITLE
__file__ references inside flow module depend on cwd at registration

### ISSUE THREAD

**Issue by JacobHayes** [PrefectHQ/prefect#3529]
## Description
When running in Cloud, the `__file__` attribute in the flow's defining module will be set as relative to `cwd` _at register time_. For example with a folder structure like:
- code
  - /example
    - /flow.py

When registering from `code` and running in Cloud (using a slightly modified `dask_kubernetes.KubeCluster` + an image with `WORKDIR /src`), the `__file__` attribute will correctly be set to `example/flow.py`, but if registering from `code/example`, the `__file__` will simply be `flow`.

This is probably just a "normal" side effect of pickling the whole flow, but the difference between local execution when using `Path(__file__).absolute().parent` to reference relative files is unfortunate (ie: locally the "absolute" will resolve, but in Cloud it will be missing `/example`).

`__file__` of course still works in other imported modules.

Aside from perhaps extra documentation/warnings, I'm not sure what a solution on the Prefect side would be unless there was a way to identify the "package root" to resolve relative paths and override `__file__` or something, but that seems quite messy. I guess perhaps this could be an arg during flow registration?

## Expected Behavior
File relative references such as `Path(__file__).absolute().parent / "some_other_file.txt"` to work regardless of local vs cloud and/or registration folder.

## Reproduction
```python
from pathlib import Path

import prefect
from prefect import Flow, task

_file = __file__


@task(log_stdout=True)
def print_file():
    print(Path(_file).absolute())
    print(Path(__file__).absolute())


with Flow("Example") as flow:
    print_file()
```

When registering from `code` and running in Cloud (with `WORKDIR /src`) the output is:
```
2020-10-17T05:05:35.085388+00:00  INFO  /src
2020-10-17T05:05:35.086005+00:00  INFO  example/file_path.py
2020-10-17T05:05:35.086227+00:00  INFO  example/file_path.py
```

When registering from `code/example/` and running in Cloud (with `WORKDIR /src`) the output is:
```
2020-10-17T05:05:24.292992+00:00  INFO  /src
2020-10-17T05:05:24.294104+00:00  INFO  file_path.py
2020-10-17T05:05:24.294399+00:00  INFO  file_path.py
```

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.14.6-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.10+32.g9058a5695",
    "python_version": "3.8.5"
  }
}
```

**Comment by jcrist** [comment]
> This is probably just a "normal" side effect of pickling the whole flow, but the difference between local execution when using Path(__file__).absolute().parent to reference relative files is unfortunate (ie: locally the "absolute" will resolve, but in Cloud it will be missing /example).

Yeah, this has to do with pickling the file, there's not much we can do here. In my experience, using `__file__` isn't a reliable way to get the file path unless you're directly calling the script, or the file is part of an installed package.

Even with [file-based flow storage](https://docs.prefect.io/core/idioms/file-based.html), we can't really inject `__file__` into the module namespace, as not all files ever exist on disk (e.g. if we load from `Github` storage, what would `__file__` be?).

For your use case (referencing additional files), I'd recommend:

- Using absolute path if possible
- Use relative paths based off the `cwd`
- Install your flow as a module, and use `path="your.module.path"` in `Local` storage to load the flow from a module (which will give you a proper `__file__` path).

**Comment by JacobHayes** [comment]
> there's not much we can do here

That's understandable. Are there docs related to this topic that would be helpful to add/expand on? Perhaps this just falls under existing "pickle gotchas" warnings somewhere. 😄

> file is part of an installed package

It more or less is here. We don't formally `pip install` it, but our local env and containers all set the `PYTHONPATH` accordingly. Would `pip install`ing help here particularly or just as part of the `path="your.module.path"` suggestion below?

Re: the alternatives:

- > Using absolute path if possible
    - Unfortunately local paths != Docker/execution environment, so similar issues. I guess we could inject some config/env var/whatever with the "root".
- > Use relative paths based off the cwd
    - This could work, but gets frustrating to work with when the user has to be in the "correct" directory to get things to run.
- > Install your flow as a module, and use path="your.module.path" in Local storage [...]
    - This could be interesting. We currently use the GCS storage to separate the Docker execution/rebuilding.

On that last point and to your `Github` comment, perhaps these "remote fetching" Storage backends could all take a "path" or "target_path" arg that would point to where the flow should be saved, rather than just the execution environment's `cwd`?

**Comment by JacobHayes** [comment]
Closing since no good fix on the prefect side. Resolved by moving `__file__` references out of the registered module.
