### ISSUE TITLE
Change "PYTHONPATH" construct for local agent

### ISSUE THREAD

**Issue by dmitrii-dementevskii** [PrefectHQ/prefect#3544]
## Current behavior
Local agent has the "--import-path" feature, but its now availible only for unix enviroment, because PYTHONPATH is concatenated with ":"
current_env["PYTHONPATH"] = ":".join(python_path)

## Proposed behavior
Use  "os.pathsep" instead ":", to get the correct value aswell for Windows users

**Comment by madkinsz** [comment]
Thanks for the report @dmitrii-dementevskii 

This would be a really good thing to open a PR for if you have the time!

**Comment by madkinsz** [comment]
The change for this is pretty brief but I am concerned about how this would affect flows not being run locally? @joshmeek 

See https://github.com/PrefectHQ/prefect/compare/win-python-pathsep

**Comment by jcrist** [comment]
The local agent always runs flows locally, that fix looks fine
