### ISSUE TITLE
Update server telemetry config setting in docs

### ISSUE THREAD

**Issue by vlcinsky** [PrefectHQ/prefect#3547]
## Description
Starting `prefect server start` I have noticed "sending telemetry information..." message and tried to disable this.

The message looks like:
```shell
apollo_1    | Server ready at http://0.0.0.0:4200 🚀 (version: master)
apollo_1    | Sending telemetry to Prefect Technologies, Inc.: {"source":"prefect_server","type":"startup","payload":{"id":"d3037eea-7232-413f-b7bb-11fb0924993e","prefect_server_version":"master","api_version":"
0.2.0"}}
```

According to https://docs.prefect.io/orchestration/server/telemetry.html I created file `/home/javl/.prefect_server/config.toml` with content:

```toml
[telemetry]
enabled = false
```

and saved the file.

Next time with `prefect server start` I saw the "sending temeletry information..." message again.

The settings seem to be ignore.

## Expected Behavior
When I configure server not to send telemetry, I expect the message not to be shown with next `prefect server start`.

## Reproduction

Some time ago, installed prefect==0.13.1

Played with it few times, stopped.

Later started prefect again, noticed the "Sending telemetry..." message. Stopped the server.

Created the configuration file as instructed in .https://docs.prefect.io/orchestration/server/telemetry.html

Started the prefect server again, saw the "Sending telemetry ..." again, stopped the server.

Updated prefect to the latest version 0.13.11

Started `prefect server start` again, the message "Sending telemetry ..." message still apears there.

## Environment
```shell
$ prefect diagnostics
{
  "config_overrides": {
    "flows": {
      "checkpointing": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.0-11-amd64-x86_64-with-debian-10.6",
    "prefect_backend": "server",
    "prefect_version": "0.13.11",
    "python_version": "3.7.4"
  }
}
```

**Comment by joshmeek** [comment]
Hi @vlcinsky I think that doc needs to be updated. In your `~/.prefect/config.toml` try setting

```
[server]
    [server.telemetry]
        enabled = false
```

**Comment by vlcinsky** [comment]
Thanks @joshmeek , it works for me now.

It would be great to fix this information in docs too: https://github.com/PrefectHQ/prefect/blob/810e6f0557ba28b8dfd1dfd45b7d534f6c7b8bcb/docs/orchestration/server/telemetry.md
