### ISSUE TITLE
The import path option for Prefect agent does not work for Windows

### ISSUE THREAD

**Issue by vipulvisawadia** [PrefectHQ/prefect#3550]
## Description

I had encountered an error "ModuleNotFoundError" while running flow as script.
I realise that I need to start the Prefect Agent with "-p" option for importing new path where Agent can find flows but that did not help.

On looking further I found the code inside the LocalAgent
```
if self.import_paths:
    python_path += self.import_paths
current_env["PYTHONPATH"] = ":".join(python_path)
```

The colon as a separator would only work in Unix and not in Windows.

The code can be fix by 
```
from sys import platform as _platform
path_sep = ":"
if _platform.startswith('win'):
    path_sep = ";"

if self.import_paths:
    python_path += self.import_paths
current_env["PYTHONPATH"] = path_sep.join(python_path)
```

## Expected Behavior

The Agent should not complain that it could not find the Flow (ModuleNotFoundError)

## Environment

(venv) D:\1. Vipul\1. Tech\Python>prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.19041-SP0",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.11",
    "python_version": "3.8.5"
  }
}

**Comment by madkinsz** [comment]
Hi! There is already an open issue for this at https://github.com/PrefectHQ/prefect/issues/3544 if you don't mind I am going to close this so we have a single tracking issue.

**Comment by vipulvisawadia** [comment]
oh wonderful, please close it as I was not aware, thanks
