### ISSUE TITLE
state.cached_inputs argument inside cache_validator doesn't get populated

### ISSUE THREAD

**Issue by KrzysztofNawara** [PrefectHQ/prefect#3553]
## Description
- I have a mapped task with two inputs - one is unmapped, the other one returns a list over which I map
- all those tasks have caching enabled and use LocalResults
- dummy cache_validator prints cached/current inputs/hashed inputs

Behaviour differs depending on version on which I tested:
#### 0.12.2
- when executed locally it works fine - all cached_inputs are correctly populated
- when executed using prefect-server only one input is populated - for the other one the input is
- hashed_inputs are harder to verify, but they seem to follow the same pattern

Logs from the run in Prefect Server, notice that 1) the mapped input is None 2) only one result get's loaded:
![image](https://user-images.githubusercontent.com/5757040/96641928-b5d0a680-1325-11eb-841f-07703edfce42.png)

Logs from the local run, everything works as expected:
![image](https://user-images.githubusercontent.com/5757040/96641981-c41ec280-1325-11eb-8a92-27413be2fa27.png)
![image](https://user-images.githubusercontent.com/5757040/96642005-cda82a80-1325-11eb-848b-50b83129fd8c.png)

serialized_state extracted from task_run table from postgres (note location next to mapped1 being None)
![image](https://user-images.githubusercontent.com/5757040/96642037-da2c8300-1325-11eb-879e-86935e6a4977.png)

#### 0.13.10
- cached_inputs are not populated, even during the local run
- didn't look too closely, but hashed_input handling may have improved

from local run:
![image](https://user-images.githubusercontent.com/5757040/96642183-14962000-1326-11eb-8291-b10d42f2f210.png)

database contents (but for a different flow):
![image](https://user-images.githubusercontent.com/5757040/96642233-27a8f000-1326-11eb-941f-8342de610fae.png)

## Expected Behavior
Both cached_inputs and hashed_inputs are correctly populated with values from the run when the state got cached.

## Reproduction
https://gist.github.com/KrzysztofNawara/f12d4599ac822eebe8129b2139a5b719

## Environment
```
{
  "config_overrides": {
    "flows": {
      "checkpointing": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.4-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.13.11",
    "python_version": "3.8.3"
  }
}
```

**Comment by cicdw** [comment]
Hi @KrzysztofNawara - this is expected behavior; `cached_inputs` was causing issues in two ways:

- for users who were passing large objects, there were performance issues
- for users passing objects with complicated `__eq__` methods (e.g. `numpy` arrays and `pandas` dataframes), there were too many edge cases when comparing them directly

Now all caching logic that requires input checks use `hashed_inputs` which is more performant and has fewer edge cases. 
 The existence of the attribute is mainly for backwards compatibility but we will be removing it entirely at some point in the future.

**Comment by KrzysztofNawara** [comment]
Hi @cicdw thanks for the rapid response!
So if I need custom hashing behaviour I can rely on this and Prefect will respect that?
https://docs.dask.org/en/latest/custom-collections.html#implementing-deterministic-hashing

**Comment by cicdw** [comment]
Yup! We use `dask.base.tokenize` directly when creating the hashed inputs.

**Comment by madkinsz** [comment]
@KrzysztofNawara has this resolved your issue? :)

**Comment by KrzysztofNawara** [comment]
Yes, thank you for your assistance!
