### ISSUE TITLE
Imported tasks from different flows are executed under a False-case condition

### ISSUE THREAD

**Issue by AdeSantosSierra** [PrefectHQ/prefect#3559]
## Description

Given the following code:
`

      with Flow(...) as flow_A:

	# do stuff

	with case(False, True):
		# This is Skipped
		run_tasks_from_flow_A()

		# This is Scheduled
		# This flow_B is imported from a different file
		schedule_a_new_task_from_flow_B_different_from_flow_a()

`
When the case is False, the run_tasks_from_flow_A() is run and then Skipped. This is great.
However, the task schedule_a_new_task_from_flow_B_different_from_flow_a() is Scheduled AT THE SAME TIME the flow_a runs, so it even wait for the condition to be evaluated.

## Expected Behavior

I would expect schedule_a_new_task_from_flow_B_different_from_flow_a() to be skipped.

## Reproduction

Stated previously.

## Environment

`{
  "config_overrides": {
    "cloud": {
      "agent": {
        "auth_token": true,
        "labels": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-51-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.10",
    "python_version": "3.6.9"
  }
}`

**Comment by joshmeek** [comment]
@AdeSantosSierra is the `schedule_a_new_task_from_flow_B_different_from_flow_a` that you are importing from another file a standard python function or a task? I order for it to be respected by the case block it needs to be a task.

**Comment by AdeSantosSierra** [comment]
It is a task, in a different file, but a task.

**Comment by cicdw** [comment]
Hi @AdeSantosSierra would you mind running `flow.visualize()` and showing us what the output is?

**Comment by AdeSantosSierra** [comment]
![image](https://user-images.githubusercontent.com/4116133/96775667-25a76580-13e8-11eb-8b42-f7c07850d0bc.png)

**Comment by AdeSantosSierra** [comment]
Notice the case(True) only calls olimpo, which is the run_tasks_from_flow_A(), however the task schedule_a_new_task_from_flow_B_different_from_flow_a() doesn't appear.

Nonetheless, flow_B is scheduled.

**Comment by cicdw** [comment]
This suggests what @joshmeek said above - that your `schedule_a_new_task_from_flow_B_different_from_flow_a` is actually a function and not a Prefect task.  If it were a task, it would _necessarily_ show up in this visualization somewhere.

**Comment by AdeSantosSierra** [comment]
My mistake, apologies. I checked it for the n-th time, and it is true, it is not a task. It is a create_flow_run.
In that sense, I should use a standard if-else command right?

**Comment by cicdw** [comment]
Hard to say without knowing your use case; if you want to conditionally create a flow run at runtime using this `case` statement, I suggest using the built-in `StartFlowRun` task: https://docs.prefect.io/api/latest/tasks/prefect.html#startflowrun

**Comment by AdeSantosSierra** [comment]
Appreciate really your help. 
The more I use Prefect, the more I love it!
