### ISSUE TITLE
generated/created docker-compose.yml missing postgres volumes opton

### ISSUE THREAD

**Issue by Jesperrekuh** [PrefectHQ/prefect#3569]
## Description
Try persisting postgres db locally in /tmp/pg_data (because its not created in home/.prefect/pg_data
the generated/created docker-compose.yml (in tmp) does not contain:
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

.local/bin/prefect server start --volume-path /tmp/pg_data

## Expected Behavior
postgres db data stored outside container  /tmp/pg_data

 

## Environment
clean install under prefect user , upgraded python3.7-dev Ubuntu 18.04

Optionally run `prefect diagnostics` from the command line and paste the information here. -->
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.15.0-122-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "server",
    "prefect_version": "0.13.12",
    "python_version": "3.7.5"
  }
}

**Comment by joshmeek** [comment]
Hi @Jesperrekuh, in the part where you are calling `prefect server start --volume-path /tmp/pg_data` try also setting `--use-volume` to enable using a volume with the postgres instance.

So full command would look like:

```
.local/bin/prefect server start --use-volume --volume-path /tmp/pg_data
```

**Comment by Jesperrekuh** [comment]
Hi thanks for pointing this out, tried that too.
Doesn't work, again experiencing problems regarding (unset) environment variables. 

I dont understand why my docker-compose.yml in the working dir is generated rather copied from?

It all boils down to the way the config and environment is set. 
Whilst digging/scanning into the code in server.py and Configuration class... I really have to dive deep into it. 

But I will stop using server start, adjust my yml and run docker-compose up by hand.

**Comment by joshmeek** [comment]
I wonder if this could also be related to #3557 WRT the unset environment variables 🤔

**Comment by madkinsz** [comment]
Hi! I cannot reproduce this on either `0.13.12` or `master` and Ubuntu 18.04

```
michaeladkins@mz-testing-docker-compose:~/prefect$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1028-gcp-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "server",
    "prefect_version": "0.13.12+52.g1cc7eab4f",
    "python_version": "3.6.9"
  }
}
```

```
michaeladkins@mz-testing-docker-compose:~/prefect$ prefect server start --use-volume --volume-path /tmp/pg_data
````

```
michaeladkins@mz-testing-docker-compose:~/prefect$ sudo ls /tmp/pg_data
PG_VERSION    pg_dynshmem    pg_multixact  pg_snapshots  pg_tblspc    postgresql.auto.conf
base	     pg_hba.conf    pg_notify	  pg_stat	pg_twophase  postgresql.conf
global	     pg_ident.conf  pg_replslot   pg_stat_tmp	pg_wal       postmaster.opts
pg_commit_ts  pg_logical     pg_serial	  pg_subtrans	pg_xact
```

**Comment by Jesperrekuh** [comment]
pip3 install docker-compose did the trick... problem solved.
