### ISSUE TITLE
Error on creating a default tenant after first start

### ISSUE THREAD

**Issue by tx00g** [PrefectHQ/prefect#3572]
Basically the goal was to make a container with prefect to move it to the server which has no internet connection. After sorting .env issue and finally started the server It requires to create a tenant. I had experienced and error:
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:4200/graphql)` 
From which I moved from container idea to just copy all dependencies from `conda install prefect` which worked perfectly on local machine and services containers to run same `prefect server start` on server without downloading anything. 

And it almost worked except on RHEL7 I experienced same .env problem and same error on creating a tenant:

Full error of `prefect server create-tenant --name default --slug default` gives:

$ prefect server create-tenant --name default --slug default
&ensp; Traceback (most recent call last):
&ensp;&ensp;&ensp; File "/u/anaconda3/envs/prefect/bin/prefect", line 10, in <module>
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;sys.exit(cli())
&ensp;&ensp;&ensp; File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 829, in __call__
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;return self.main(*args, **kwargs)
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 782, in main
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;rv = self.invoke(ctx)
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;return _process_result(sub_ctx.command.invoke(sub_ctx))
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;return _process_result(sub_ctx.command.invoke(sub_ctx))
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;return ctx.invoke(self.callback, **ctx.params)
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 610, in invoke
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;return callback(*args, **kwargs)
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/cli/server.py", line 420, in create_tenant
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;client = prefect.Client()
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/client/client.py", line 124, in __init__
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;tenant_info = self.graphql({"query": {"tenant": {"id"}}})
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/client/client.py", line 281, in graphql
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;retry_on_api_error=retry_on_api_error,
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/client/client.py", line 237, in post
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;retry_on_api_error=retry_on_api_error,
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/client/client.py", line 401, in _request
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;session=session, method=method, url=url, params=params, headers=headers
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/client/client.py", line 333, in _send_request
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;response.raise_for_status()
&ensp;&ensp;&ensp;File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:4200/graphql

$ prefect diagnostics
{
&ensp;"config_overrides": {},
&ensp;"env_vars": [],
&ensp;"system_information": {
&ensp;&ensp;"platform": "Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-redhat-7.7-Maipo",
&ensp;&ensp;"prefect_backend": "server",
&ensp;&ensp;"prefect_version": "0.13.11",
&ensp;&ensp;"python_version": "3.7.4"
&ensp;}
}

Is there is any lower level command directly to graphql that may allow to create a tenant and/or debug it and move to the working prefect?

**Comment by joshmeek** [comment]
Hi @tx00g the CLI command calls the `create_tenant` function from the Client 

https://github.com/PrefectHQ/prefect/blob/73fe1eb57945fc13bdd36b361a6a17c3f324b1ba/src/prefect/client/client.py#L128-L159

**Comment by xaniasd** [comment]
@joshmeek I think the problem comes up during the creation of the Client object, there's a request to get the active tenant id, which fails

**Comment by xaniasd** [comment]
@tx00g I think the schema is missing, make sure to create it! Running `prefect-server database upgrade -y` in the graphql container should do the trick.

**Comment by joshmeek** [comment]
Yes that makes sense. When running the server code directly from source you will need to apply the migrations in order for the schema to be built.
