### ISSUE TITLE
shellTask logs all stdout when `ShellTask(return_all=True)`

### ISSUE THREAD

**Issue by hui-zheng** [PrefectHQ/prefect#3584]
**Context**
Currently, when `prefect.tasks.shell.ShellTask` is invoked with `return_all=True`, the shell task will not log the stdout through logger.debug.

This is defined in doc 
https://docs.prefect.io/api/latest/tasks/shell.html#shelltask
and implement in the code.
https://github.com/PrefectHQ/prefect/blob/73fe1eb57945fc13bdd36b361a6a17c3f324b1ba/src/prefect/tasks/shell.py#L107-L111

**Problem**

Sometimes, we execute a long-running shell process, for example, we are running dbt, which might take 20 to 40 minutes to run. the task would need to return the entire stdout log as its output, for the next task to parse and interpret the result. Meanwhile, We would also like to see the shell stdout logging out in real-time, which makes it easy for us to inspect issues and monitoring / debug shell runs on-the-go, instead of waiting for 20 minutes not knowing what is going on.

**proposed change**

```
                for raw_line in iter(sub_process.stdout.readline, b""):
                    line = raw_line.decode("utf-8").rstrip()
                    if self.return_all:
                        lines.append(line)
                    # we still log every line
                    self.logger.debug(line)
```

**Comment by madkinsz** [comment]
I think this is reasonable although it may be better implemented by adding a `stream_logs: bool = True` and having this behavior be entirely independent of `return_all`. @joshmeek would we be willing to accept a PR for this?

**Comment by hui-zheng** [comment]
yes, `stream_logs: bool = True` would be even better.

**Comment by joshmeek** [comment]
Yeah I'm game for a steam logs kwarg!

**Comment by hui-zheng** [comment]
We do need this fairly quickly. Please let me know how I could contribute to any.

**Comment by dcalde** [comment]
Hi, should the log level be configurable or set to INFO? Anyone setting `stream_output=True` is likely to actually want to see the shell outputs in their logs without having to configure their agent to DEBUG.
I was able to show the debug logs by configuring the ShellTask logger and adding a new StreamHandler when running locally, but not when deployed and running on the agent.

**Comment by madkinsz** [comment]
@dcalde The PR for this issue just left the old behavior. The debug logs will still be streamed to Cloud which I think is a more common use case than watching the agent. I don't think changing to a default of `INFO` or allowing configuration would be unreasonable though. cc @joshmeek

**Comment by joshmeek** [comment]
Hmm @madkinsz I like the idea of allowing the log level to be configurable for the streamed logs in the task and I would probably think that `DEBUG` should be the default although I do see how having to also set the log level for the run turns it into a double trigger type of scenario and the less knobs the better (but I don't feel too strongly about it IMO so no real preference).

**Comment by madkinsz** [comment]
Whilst it is less obvious, `stream_logs` could be a `Union[bool, int]` where any falsey value disables log streaming, a `True` value logs with the default of `DEBUG` and an `int` value logs with that level. This makes it a single configurable knob and `stream_logs=logging.INFO` isn't hard to read & understand.

**Comment by dcalde** [comment]
`stream_logs=logging.INFO` seems fairly straight forward.
As for your comment "debug logs will still be streamed to Cloud"... how? unless I configure the agent's logging threshold to DEBUG its not visible in the UI, but then I also get every other debugging message, spamming the logs.

**Comment by madkinsz** [comment]
> `stream_logs=logging.INFO` seems fairly straight forward. However if you are considering making it configurable, one could argue that the `log_level` should be part be `Task` or configurable via `config.toml`. In this particular instance, `ShellTask` having a configurable log_level is probably not helpful as it won't really impact how much logging is emitted by the actual shell command being executed, as shell scripts/executables will typically have their own way of controlling its log level / verbosity.

I'm not sure a global setting would make sense here. Task library task logs are quite dependent on the type of task.

If you want all of your shell tasks to have the same log level you'd just say `LoggedShellTask = ShellTask(stream_logs=logging.INFO)` then use the `LoggedShellTask` for all of your shell task definitions.

> Unless its a super simple command, you most likely want to see all of the stdout/stderr in the logs, i.e. default to INFO.

I think it's fair to say that streaming all of the logs from a command can be quite verbose and depending on the use-case is only helpful for debugging. I think we'll need it to be configurable to make everyone happy.

> As for your comment "debug logs will still be streamed to Cloud"... how? unless I configure the agent's logging threshold to DEBUG its not visible in the UI, but then I also get every other debugging message, spamming the logs.

I think we may be conflating agent log level (e.g. is it logging that is checking for runs every X seconds) and the prefect log level that an agent is run with (this is the log level of flows run by the agent). I think I get what you mean, but I'm not 100% sure what the default behavior is since as a Prefect dev I always use the debug logs :)

> Also, I appreciate you responding to my feedback so quickly... especially on a closed issue.

No problem! This should probably be a separate issue but since we're already this far here...

**Comment by dcalde** [comment]
@madkinsz thanks for the feedback. I have created a separate issue and referenced this discussion
