### ISSUE TITLE
task_run_name's kwargs referring to task inputs shadowed by Prefect's context instead

### ISSUE THREAD

**Issue by ArsTapatun** [PrefectHQ/prefect#3605]
## Description

Recently, a `task_run_name` parameter was added to the task constructors, and documentation was written on [how to dynamically set task Run Names dynamically based on inputs](https://docs.prefect.io/core/idioms/task-run-names.html).

At runtime, Prefect automatically populates `kwargs` with raw inputs and also prefect context:
https://github.com/PrefectHQ/prefect/blob/1bbefb71fa15cfc6bf6b6d766fe7591dafaa4717/src/prefect/engine/cloud/task_runner.py#L346

This leads to a hard-to-catch bug if you happen to use a task input variable under the same name as one of [the keys in the Prefect Context](https://docs.prefect.io/api/latest/utilities/context.html). Common variable names like `config` or `parameters` or even `map_index`, if used in task input, would be shadowed by the correspondent `context` value and lead to crashes or unexpected task run names.

## Expected Behavior
An exception could be raised if a duplicated name is detected... But most likely the existing behaviour just needs to be clearly explained in the documentation.

## Reproduction

```python
from prefect import task, Flow

@task
def generate_configs():
    return [{"value": 1}, {"value": 2}, {"value": 3}]


@task(task_run_name=lambda **kwargs: f"{kwargs['config']['value']}")
def parse_configs(config):
    print(config["value"])


with Flow("Task Run Names Bug") as flow:
    parse_configs.map(generate_configs())
```

## Environment
Reproducible in any environment with Prefect version `0.13.10+`, any Cloud deployment method.

**Comment by madkinsz** [comment]
@ArsTapatun thanks for the issue! I could see it being useful to display a `UserWarning` if we detect that the task function takes args that collide with the prefect context and the user is using `task_run_name` -- this does sound like a pain to track down otherwise. An exception feels too aggressive to me.

**Comment by jcrist** [comment]
Instead, perhaps we only add in the prefect-specific stuff (like `config`) if the task doesn't already have an argument of the same name (inverse of what we have now). If the user needs to access prefect's config for a task that also takes an argument named `config`, they can always access it via `prefect.contex.config` in the function-version of `task_run_name`.

I believe changing 

https://github.com/PrefectHQ/prefect/blob/1bbefb71fa15cfc6bf6b6d766fe7591dafaa4717/src/prefect/engine/cloud/task_runner.py#L346-L350

to

```
formatting_kwargs = {
                **prefect.context.get("parameters", {}),
                **prefect.context,
                **raw_inputs,
            }
```

should be sufficient.

**Comment by ArsTapatun** [comment]
Thanks for the quick responses!
@jcrist I personally think your proposal is optimal in terms of effort-result ratio, and I also think it wouldn't hurt to let the user know that some keywords are collided with a Warning, as suggested by @madkinsz. Perhaps that could be accomplished simply with:
```python
if duplicates := set(prefect.context).intersection(raw_inputs):
     raise UserWarning(f"The following Prefect context keywords " \
                        "will be overwritten with task inputs: {', '.join(duplicates)}. " \
                        "Note that you can still access prefect.contex.config.")
```

**Comment by jcrist** [comment]
IMO a library shouldn't issue a warning (note you want `warning.warn(...)`, not `raise` here) that can't be disabled by the user making some change to their code. The only way for a user to fix this is to change the argument names to their function, which seems drastic given that most users probably won't need to access `config` when generating a task name (most users only want the input arguments to the task). Forcing the user to change their argument names just to silence a warning that doesn't affect them seems like bad UX to me.

I think we should stick with the simple solution, and maybe add a small note in the `Task` docstring for the `task_run_name` argument mentioning how conflicts are handled.

**Comment by mashun4ek** [comment]
PR [#3622](https://github.com/PrefectHQ/prefect/pull/3622) closes the issue.
