### ISSUE TITLE
allow ShellTask to return stdout when it fails

### ISSUE THREAD

**Issue by hui-zheng** [PrefectHQ/prefect#3614]
**The context**
Currently, if the shell process returns non-zero exit code, It will raise a FAIL signal, without any result attached. 

https://github.com/PrefectHQ/prefect/blob/b939c7d043f5de910a54ad95e07873a835f48b31/src/prefect/tasks/shell.py#L113-L122

**The probem**
Sometime, the downstream task need to interpret the output of a failed shell task (might be from both stdout and stderr) to handle the the failure properly. 

In my use case, I use DBTShellTask (which is a subclass of ShellTask) for execute a  `dbt run` as shell sub-process. I then use another task, called `parse_dbt_result`, to take the output of the dbt task and handle both success and failure results, such as knowing which models in the dbt-run process failed.

When some models fails in a `dbt run`, those model errors are shown in the stdout, and  the shell subprocess returns non-zero exit code (1). The ShellTask raises a FAIL signal without any stdout result.  As a result, the `parse_dbt_result` task is not able to interpret the log of failed run and not know which model fails, hereby not be able to handle the failure properly. 

**Solution**
please provide a flag that allows ShellTask to return stdout(or/and stderror) result when the shell process fails and FAIL signal is raised.

**Comment by hui-zheng** [comment]
we do need this fairly quickly. Please let me know if I could contribute to any.

**Comment by madkinsz** [comment]
I think this would be best solved by a `raise_on_bad_exit_code: bool = True` kwarg that allows you to handle the result yourself. However, this would change the return type of the task since it'd have to pass the return code which is a breaking change. I'll talk with our team today about the best solution for this and #3584

**Comment by hui-zheng** [comment]
Hi @madkinsz, just to follow up on this.

I am fine with raising a failed signal on a bad exit code, because I do need to know if the shell execution is a success or a failure based on the Task State. 

My request is to include the stdout in the task result even if it is in the fail state. for example
```
 raise prefect.engine.signals.FAIL(msg, result= lines) from None  # add lines to FAIL.result.
```
