### ISSUE TITLE
Env Vars in Docker Storage cannot be used in the build process

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#3640]
## Description

From Community Slack: https://prefect-community.slack.com/archives/C014Z8DPDSR/p1605012711434000
env_vars in the Docker Storage, are variables that are added to the end of a Dockerfile. Since the ENV command is added to the end of the file, you cannot actually pass any variables that are used in the build process itself.

## Expected Behavior

variables can be used in the build or we better explain in the docs that they're added to the end of the dockerfile.

**Comment by cicdw** [comment]
👍 in this instance, we can easily rearrange the order of the internally-generated `Dockerfile` no problem, but in general users who need control of the `Dockerfile` commands should write their own and use the `dockerfile` kwarg.
