### ISSUE TITLE
Flow.replace sets reference tasks even if they weren't set previously in the flow

### ISSUE THREAD

**Issue by benfogelson** [PrefectHQ/prefect#3655]
## Description

`Flow.replace` manually sets a flow's reference tasks whether or not the flow actually had manual reference tasks set or not.  This means that new terminal tasks added to the flow after the call to `Flow.replace` won't become reference tasks.

I'm not actually sure this is a bug, because there is a test that seems to actually check for and enforce this behavior: https://github.com/PrefectHQ/prefect/blob/b085657965a9c483c2671e9cee6a66075f31a9fe/tests/core/test_flow.py#L1646-L1647

This behavior is so counter-intuitive that I can't help but wonder if enforcing it is an oversight.

## Expected Behavior

I would have expected that if a flow doesn't have specified reference tasks (i.e. if `Flow._reference_tasks` is empty), then it should default to terminal tasks being reference tasks, both before and after a call to `Flow.replace`.

## Reproduction

```python
from prefect import Flow, Task

with Flow(name="test") as f:
    t1 = Task(name="t1")()
    t2 = Task(name="t2")(upstream_tasks=[t1])
t3 = Task(name="t3")
f.replace(t1, t3)
t4 = Task(name="t4")
f.add_task(t4)
assert f.reference_tasks() == {t2, t4}
```

**Comment by cicdw** [comment]
Closed with #3656
