### ISSUE TITLE
Ability to log the logs when using prefect workflows to a log file.

### ISSUE THREAD

**Issue by gunarevuri** [PrefectHQ/prefect#3662]
## Current behaviour

If any logs occurring in the application when using prefect workflow were sent to stdout using fixed handler "streamhandler".  

## Proposed behaviour

Is there any way to log all the logs in my prefect workflow to a log file? using filehandler instead of streamhandler

**Comment by joshmeek** [comment]
Hi @gunarevuri I don't think there currently is a way to log all prefect workflow logs to a file without overriding the default logger (which you would do with something like `prefect.utilities.logging.get_logger() = new_logger`). However I'm not sure if that is something I would advise. The ability to make the default prefect logger more customizable has become increasingly requested and it is something we are looking in to!

**Comment by kvnkho** [comment]
This can now be done with something like the following code snippet:

```python
from datetime import timedelta, datetime
from prefect import task, Flow, Parameter
import prefect
import logging
from prefect.utilities.logging import get_logger
from pathlib import Path
import os

os.mkdir('log')
LOG_PATH = 'log'
class MyFileLogger(logging.FileHandler):
    def __init__(self, filename, mode='a', encoding=None, delay=False):
        filename = os.path.join(LOG_PATH, filename)
        super(MyFileLogger, self).__init__(filename, mode, encoding, delay)

@task
def pull_project(project_name):
    logger = prefect.context.get("logger")
    fh = MyFileLogger('auto_ai.log')
    fh.setFormatter(logging.Formatter("[%(asctime)s] %(levelname)s - %(name)s | %(message)s"))
    logger.addHandler(fh)
    logger.info(f"Pull latest {project_name} version from git.")
    logger.warning("A warning message....")
    return {'project_name': project_name}

def main():
    with Flow("test") as flow:
        project_info = pull_project(project_name='test')
    flow.run()

if __name__ == "__main__":
    main()
```

**Comment by jackdesert** [comment]
Here is an example for logging both to cloud (via stdout) and to a FileHandler.
(Uses a different FileHandler for each task)
Tested with prefect 1.2.2

    import logging
    import os

    import prefect
    from prefect import Flow, task

    LOG_DIR = os.path.join(os.getcwd(), 'log')
    os.makedirs(LOG_DIR, exist_ok=True)

    def log(msg):
        task_name = prefect.context.task_name
        logger = logging.getLogger(task_name)
        logger.setLevel('INFO')

        if not logger.handlers:
            # The first time the logger with this name is called, it will have no handlers associated
            # Note using absolute path to LOG_DIR
            handler = logging.FileHandler(os.path.join(LOG_DIR, task_name), encoding='utf-8')
            logger.addHandler(handler)

            # Formatter can be whatever you want
            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                                          datefmt='%Y-%m-%d_%H:%M:%S')
            handler.setFormatter(formatter)

        # Print to stdout so logs will arrive @ prefect cloud
        print(msg)

        # Log to FileHandler
        logger.info(msg)



    @task(log_stdout=True)
    def log_something():
        log('hello one')
        log('hello two')

    @task(log_stdout=True)
    def log_something_else():
        log('hello three')
        log('hello four')

    with Flow('log-test') as flow:
        log_something()
        log_something_else()

    flow.run()
