### ISSUE TITLE
DaskExecutor fails to load files when going from two to three workers

### ISSUE THREAD

**Issue by Winawer** [PrefectHQ/prefect#3667]
## Description

I'm trying to develop a flow locally using DaskExecutor.  It's a simple ETL flow that extracts some information from a json lines file and processes it.  When I run the file loading task, everything runs smoothly and the flow succeeds if there are **two** `dask` workers, but if I add a third, the third worker begins to throw errors about file loading:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/foobar.jsonl'
[2020-11-15 12:18:10+0000] ERROR - prefect.TaskRunner | Unexpected error: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/someone/.virtualenvs/someplace/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/someone/.virtualenvs/someplace/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 845, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/someone/.virtualenvs/someplace/lib/python3.8/site-packages/prefect/utilities/executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "someflow.py", line 25, in load_and_extract
  File "/Users/someone/.virtualenvs/someplace/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 328, in open
    fp = io.open(name, mode=mode + 't', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'data/foobar.jsonl'
```

The other two workers find and process files just fine from the same directory, but of course the overall flow now fails because one of the workers fails its tasks.

## Expected Behavior

I expected the third worker to find files correctly.

## Reproduction

I first create a scheduler and three workers using `dask-schedulder` and `dask-worker`.  I then run this flow locally using `python someflow.py`:

```
from prefect import task, Flow
import glob
import jsonlines
import os

@task
def get_file_list():
    fl = glob.glob("data/*.jsonl")
    return(fl)

@task
def load_and_extract(filename):
    from prefect import context
    logger = context.get("logger")

    extracts = []
    with jsonlines.open(filename) as reader:
            extract = ... # extract creation code here
            extracts.append(extract)

    logger.info(f"{len(extracts)} extracts creted")
    return extracts

with Flow("someflow") as flow:
    files = get_file_list()
    extracts = load_and_extract.map(files)
    
from prefect.engine.executors import DaskExecutor
executor = DaskExecutor(address="tcp://ADDRESS:8786")
flow.run(executor=executor)    
```

When I close the third worker and run the flow again with just two, it succeeds.

## Environment

```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__LOGGING__LEVEL"
  ],
  "system_information": {
    "platform": "macOS-10.15.5-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.14",
    "python_version": "3.8.5"
  }
}
```

**Comment by jcrist** [comment]
Hi @Winawer, I suspect your 3rd worker is running in a different working directory than the other 2? The file path you're passing in is a relative path, it probably isn't resolving appropriately on the new worker but does on the other workers. In general we recommend ensuring that all dask workers are running in uniform environments.

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if the issue persists.
