### ISSUE TITLE
visualize with filename rewrites one more file than needed

### ISSUE THREAD

**Issue by vlcinsky** [PrefectHQ/prefect#3671]
## Description
When trying to generate graphs for sample scripts, I used `filename` identical to the script name (thus `__file__`) expecting that only resulting file with added extension `.pdf` will be created.

However, the source script file was rewritten too.

## Expected Behavior
When I use `flow.visualize(name="some_file"), only the "some_file.pdf" is created and if there used to be any "some_file" before the call, it stays untouched.

## Reproduction
Save the following code as `selfdesctruct.py` and run it using `python selfdesctruct.py`
```python
from prefect import Flow, task
from pathlib import Path

# this scrip filename
this_script = Path(__file__)

# expected name of visualize PDF file after it is created
pdf_file = this_script.with_suffix(".py.pdf")
# make sure, it does not exist
if pdf_file.exists():
    pdf_file.unlink()

# check pre-conditions
assert this_script.exists(), "this python script shall exist"
assert not pdf_file.exists(), "resulting PDF file shall not exist yet"

@task
def work():
    pass

with Flow("Self Destroy") as flow:
    work()

# try to visualize into PDF having name of this script + .pdf
flow.visualize(filename=this_script, format="pdf")
assert  pdf_file.exists(), "PDF shall now exist"
assert this_script.exists(), "python script shall still exist"
```
The final assertion will fail.

## Environment
Debian 10, prefect 0.13.15

**Comment by cicdw** [comment]
Hi @vlcinsky - this is something to do with how Graphviz parses file names and handles them; to resolve your issue, you should strip the `.py` extension from your `filename`:

```python
this_script = Path(__file__).with_suffix('')
```
and everything works as expected.

**Comment by vlcinsky** [comment]
@cicdw thanks for simple workaround.

Anyway, I would propose either really fixing the issue to prevent file which is not considered to be overwritten or to update documentation and to inform about such fact.

Currently this is quite unexpected side-effect.
