### ISSUE TITLE
Docs Request: Flow Run Concurrency Limiting by Label

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#3673]
## Current behavior

Prefect Cloud can enforce global concurrency limits on Flow Runs by label & this feature is undocumented.

## Proposed behavior

Describe the feature in documentation similar to: https://docs.prefect.io/orchestration/concepts/task-concurrency-limiting.html#task-concurrency-limiting

**Comment by nchammas** [comment]
It's both undocumented and not exposed via the [`Client` API](https://docs.prefect.io/api/latest/client/client.html), correct?

**Comment by nchammas** [comment]
Related: https://github.com/PrefectHQ/server/issues/81

**Comment by madkinsz** [comment]
Yep! I updated that documentation with the release of 0.15.0.

Thanks for the note @th0ger
