### ISSUE TITLE
All data is removed after restart

### ISSUE THREAD

**Issue by tx00g** [PrefectHQ/prefect#3680]
## Description

After successful run prefect on host with some flows in it after restart all data has gone.

 Using special place to store doesn't help either `prefect server start --use-volume --volume-path /u/prefect/pg_data` - for some reason it still writes to `~./prefect/` and I can see my flows in `~./prefect/flows`, both new after all is cleaned up.

Running `prefect server start` without --use-volume gives an error:
```bash
$ prefect server start --skip-pull
Traceback (most recent call last):
File "/u/anaconda3/envs/prefect/bin/prefect", line 10, in <module>
sys.exit(cli())
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/u/anaconda3/envs/prefect/lib/python3.7/site-packages/prefect/cli/server.py", line 288, in start
del y["services"]["postgres"]["volumes"]
KeyError: 'volumes'
``` 

```bash
$ prefect diagnostics
{
"config_overrides": {},
"env_vars": [],
"system_information": {
    "platform": "Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-redhat-7.7-Maipo",
    "prefect_backend": "server",
    "prefect_version": "0.13.11",
    "python_version": "3.7.4"
    }
}
```

Since I want to store all compilated flows in special directory under /u/ -  correct way is to use --use-volume ?:)

To be sure I've created user config file with custom lines in:

```config
home_dir = "/u/prefect"

[server.database]
volume_path = "/u/prefect/pg_data"
```

and set `PREFECT__USER_CONFIG_FILE` to /u/prefect/config.toml

But still... new server run ends in empty prefect...

## Environment
<!-- Any additional information about your environment

**Comment by joshmeek** [comment]
Hi @tx00g I'm not sure if I fully follow. If you start the server with a volume then you will need to restart it with the same volume in order to maintain the history of your flow runs. In regards to storing your actual flows themselves (the pickled flow objects that get stored when you call `.register`) take a look into the Local storage object on the flow. There you can set the directory that you want to store your flows in.

Relevant links:
https://docs.prefect.io/api/latest/environments/storage.html#local
https://docs.prefect.io/orchestration/execution/storage_options.html

**Comment by tx00g** [comment]
Flows are stored well (I can see them in local folder I've specified) but on restart seems like db with links to that flows and run data is emptied every time. 
So, steps are like:
```bash
$ prefect server start --use-volume --volume-path /u/prefect/pg_data
```
It starts perfectly, then:
```bash
$ prefect create project "Hello, World!"
prefect create project "Hello, World"
Hello, World created
```
```bash
$ prefect get projects
NAME FLOW COUNT AGE DESCRIPTION
Hello, World 0 1 minute ago
```

Then I stop the server, start again with same command
```bash
$ prefect server start --use-volume --volume-path /u/prefect/pg_data
```
and by listing project I get empty answer (same with flows If I register and run some):

```bash
$ prefect get projects
NAME FLOW COUNT AGE DESCRIPTION
```

Issue with '["services"]["postgres"]["volumes"]' solved - line was missing in docker-compose, thanks.

**Comment by joshmeek** [comment]
Hmm interesting I am not observing the same behavior (but I'm on MacOS). @madkinsz Do you think you would be able to test this out on Ubuntu? Start server w/ volume -> create project -> tear down and restart server -> check existence of project

**Comment by tx00g** [comment]
> Hmm interesting I am not observing the same behavior (but I'm on MacOS). @madkinsz Do you think you would be able to test this out on Ubuntu? Start server w/ volume -> create project -> tear down and restart server -> check existence of project

Can confirm, tried on MacOS - workings just fine as expected. On RHEL it's clearing db for some reason.

**Comment by madkinsz** [comment]
> Hmm interesting I am not observing the same behavior (but I'm on MacOS). @madkinsz Do you think you would be able to test this out on Ubuntu? Start server w/ volume -> create project -> tear down and restart server -> check existence of project

Yeah I can try to do that today and report back here.

**Comment by madkinsz** [comment]
I cannot reproduce this on Ubuntu. Can you post some logs of `prefect server start` ? Is it rebuilding the database?

**Comment by madkinsz** [comment]
Perhaps this is related to your docker-compose installation as in https://github.com/PrefectHQ/prefect/issues/3557#issuecomment-717492719

**Comment by madkinsz** [comment]
Closing this as stale -- happy to re-open if this can be reproduced.

**Comment by UPetit** [comment]
Hi @madkinsz,
I'm experiencing the same issue as @tx00g.
I'm running `prefect server start`, then I create a project and even register a flow. Then I execute `prefect server stop` and when I'm starting the server again everything has been cleaned up...

I don't have any specific configuration exception the graphql host/port in `backend.toml`

Some postgres logs after restarting the server (after stopping):
OS: Ubuntu 18.04
```
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default timezone ... Etc/UTC
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | 
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2021-02-21 22:09:05.292 UTC [55] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-02-21 22:09:05.320 UTC [57] LOG:  database system was shut down at 2021-02-21 22:09:04 UTC
postgres_1  | 2021-02-21 22:09:05.337 UTC [55] LOG:  database system is ready to accept connections
postgres_1  | 2021-02-21 22:09:05.344 UTC [64] FATAL:  database "prefect_server" does not exist
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | 2021-02-21 22:09:05.844 UTC [55] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down....2021-02-21 22:09:05.853 UTC [55] LOG:  aborting any active transactions
postgres_1  | 2021-02-21 22:09:05.856 UTC [55] LOG:  background worker "logical replication launcher" (PID 63) exited with exit code 1
postgres_1  | 2021-02-21 22:09:05.861 UTC [58] LOG:  shutting down
postgres_1  | 2021-02-21 22:09:05.900 UTC [55] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2021-02-21 22:09:05.967 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-02-21 22:09:05.967 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-02-21 22:09:05.979 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-02-21 22:09:06.007 UTC [85] LOG:  database system was shut down at 2021-02-21 22:09:05 UTC
postgres_1  | 2021-02-21 22:09:06.017 UTC [1] LOG:  database system is ready to accept connections

```

**Comment by madkinsz** [comment]
Hi @UPetit -- how did you install docker-compose / what version do you have?

**Comment by UPetit** [comment]
> Hi @UPetit -- how did you install docker-compose / what version do you have?

I installed docker-compose by following the official documentation page [here](https://docs.docker.com/compose/install/).
The version I installed is: 1.28.4

**Comment by madkinsz** [comment]
There are a lot of different installation instructions there :D I presume you did the `curl` method? Can you try reinstalling with `pip` and see if you encounter the same issue?

**Comment by UPetit** [comment]
> There are a lot of different installation instructions there :D I presume you did the `curl` method? Can you try reinstalling with `pip` and see if you encounter the same issue?

I used the curl method indeed yes ;)
I'll try the pip version in a few hours and I'll let you know.
Thank you

**Comment by UPetit** [comment]
Hi @madkinsz,
I've run `prefect server start --use-volume --volume-path /u/prefect/pg_data` and it is working now after registering a flow and restarted thanks :)
Before I was using `prefect server start` without creating a flow after the project. Maybe if the project is empty and the server is stopped then the project is removed at the next launch?
