### ISSUE TITLE
Add Jython task

### ISSUE THREAD

**Issue by mgrabenstein** [PrefectHQ/prefect#3698]
## Current behavior
API calls within Python are limited to pure python. 

## Proposed behavior
To be able to import Java via Jython and make calls over to java classes.
https://www.jython.org

## Example
Like to see this work in Prefect:
from java.lang import System # Java import
print('Running on Java version: ' + System.getProperty('java.version'))
print('Unix time from Java: ' + str(System.currentTimeMillis()))

Doing that would allow me to integrate my custom Java libraries.

**Comment by jcrist** [comment]
Hi @mgrabenstein, I'm not sure what you're requesting here. Most (all?) of prefect should already work under Jython, you might try running prefect on Jython already (the snippet you've posted above may already work). If not, you may be able to write a task in Jython and shell out to it using the `ShellTask`.

Alternatively, you might try writing a task using [py4j](https://www.py4j.org/) or [pyjinius](https://pyjnius.readthedocs.io/en/stable/), both of which provide native integration between Python and Java while still running on the cPython interpreter. I've had good success using py4j this way in the past, and it's also heavily used in other projects (e.g. pyspark).

Beyond that, we're unlikely to add anything to Prefect core to support Jython directly.

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen/open a new issue if needed.
