### ISSUE TITLE
Workaround for race condition when registering and running flow

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3705]
Currently if two users try to register and run the same flow at the same time, there's a potential race condition where both users might end up running whichever registers last with no indication that anything went wrong. One workaround for this might be for the users to pass `version=...` when creating the flow run, so that at least if a new version has appeared the run will fail right away instead of silently "succeed"ing. But currently the version is not returned by the registration call, which requires a separate fetch which is yet another (albeit narrower) race condition.

I titled the issue as broadly as possible since I'm open to any solutions, but just returning the version ID on registration would be a good-enough workaround in my view.

**Comment by joshmeek** [comment]
Thanks for the suggestion @bnaul! By passing in `version` do you mean the _expected_ flow version for when it is created/registered? I wonder if you could actually make use of the `idempotency_key` kwarg when registering. If the key matches the most recent key provided for the registration prior then the flow isn't re-registered. I could see this being used in a way where two people pass in the same key (like the current date or something) and only one of them are actually registered.

**Comment by bnaul** [comment]
Hi @joshmeek, I had tried to think of a way to get `idempotency_key` to work but I don't really think it's possible since the problem occurs at run-time, not register time. The series of events is:
- User 1 registers
- User 2 registers
- User 1 runs
- User 2 runs

When User 1 registers, they have no way of knowing that User 2 is about to register also; similarly, when User 2 registers, they can't know that User 1 is about to run but hasn't yet.

It might sound like a narrow edge case but if you're registering and running a flow from CI then you're more or less guaranteed to run into this eventually (we started seeing it once a day or so for our workload).

**Comment by madkinsz** [comment]
@bnaul How are you running your flow? Registration returns a unique id for each version within the flow group.

**Comment by bnaul** [comment]
@madkinsz ah, good point.....I'm creating runs with `prefect.cli.run` which takes the name, but using `Client.create_flow_run` directly and passing the ID from the registered flow seems like it would solve this problem.

That feels like a good enough workaround for me so I'm going to close, thanks @madkinsz !
