### ISSUE TITLE
Duplicate PID during flow run

### ISSUE THREAD

**Issue by richard-hughes-tel** [PrefectHQ/prefect#3758]
## Description
When running a scheduled run in prefect the flow concurrently ran 2 PID's in parallel within the exact second of execution. This resulted in generating 2 files that caused issue upstream.

```
06:34:54  INFO  agent  Submitted for execution: PID: 16288
06:34:54  INFO  agent  Submitted for execution: PID: 10392
```

## Expected Behavior
The flow should only execute 1 PID for each flow.

## Reproduction
flow-run  a24b31dc-16ea-45ce-9816-1eccb4cbb34a
flow 64b15697-e80c-46c4-827f-9ac37f0dc45b
```
import pendulum
from prefect import task, Flow, Parameter, Client
from prefect.schedules import Schedule
from prefect.schedules.clocks import CronClock
from prefect.tasks.shell import ShellTask
from subprocess import Popen, PIPE
from prefect.engine import signals

ParameterSourceName = Parameter("SourceName", default=None, required=True)
ParameterDataSetName = Parameter("DataSetName", default=None, required=False)

@task
def BuildCommand(SourceName,DataSetName):
    MyToolsScript = []
    MyToolsScript += ["F:;"]
    MyToolsScript += ["cd \\Shares\\Powershell;"]
    MyToolsScript += ["Import-Module "".\\MyTools"";"]
    if SourceName == "CopyFile":
        MyToolsScript += ["Write-Host '"+SourceName+"' executing for '"+DataSetName+"';"]
        MyToolsScript += ["Copy-MyItem -DataSetName '"+DataSetName+"';"]
    else:
        MyToolsScript += ["Write-Host '"+SourceName+"' executing for '"+DataSetName+"';"]
        MyToolsScript += ["$RetrievedData = $null;"]
        MyToolsScript += ["$RetrievedData = Get-MyItem -SourceName '"+SourceName+"' -DataSetName '"+DataSetName+"';"]
        MyToolsScript += ["Write-MyDataSet -SourceName '"+SourceName+"' -DataSetName '"+DataSetName+"' -DataSetData $RetrievedData;"]
    return MyToolsScript

@task(log_stdout=True)
def Powershell(CommandArray):
    CreatedCommandArray = ["powershell.exe"] + CommandArray
    p = Popen(CreatedCommandArray, stdout=PIPE, stderr=PIPE, shell=True)
    output, error = p.communicate()
    if p.returncode != 0:
        message = "powershell failed %d %s %s" % (p.returncode, output.decode("utf-8"), error.decode("utf-8"))
        raise signals.FAIL(message=message)

    else:
        message = "powershell succeeded %d %s" % (p.returncode, output.decode("utf-8"))
        print(message)
        raise signals.SUCCESS(message=message)

GenericSchedule = Schedule(clocks=[
    CronClock(cron="31 6 * * *",start_date=pendulum.now("America/Chicago"),parameter_defaults={"SourceName": "SQLStatements","DataSetName":"Employee"})
])
with Flow(
        name="System.MyToolsExecution",
        schedule=GenericSchedule
) as flow:
    CreatedCommandArray = BuildCommand(ParameterSourceName,ParameterDataSetName)
    Powershell(CreatedCommandArray)

flow.register(project_name="<<PREFECT_PROJECT_NAME>>", version_group_id="<<PREFECT_PROJECT_NAME>>.System.MyToolsExecution", no_url=True)

```

## Environment
Flow’s Prefect Version  0.13.13
Agent Version 0.13.13
OS information Windows 10 Build 17763

**Comment by dylanbhughes** [comment]
@richard-hughes-tel Just to confirm, there's only one agent running on this machine, correct?

**Comment by richard-hughes-tel** [comment]
Yes, one agent per project in my environment.

**Comment by jcrist** [comment]
Thanks @richard-hughes-tel. This certainly is perplexing.

Just to clarify, are these logs:

> ```
> 06:34:54  INFO  agent  Submitted for execution: PID: 16288
> 06:34:54  INFO  agent  Submitted for execution: PID: 10392
> ```

from your agent? Or logs seen in the UI for the flow run?

The reason I ask is

> Yes, one agent per project in my environment.

One agent per "project" doesn't guarantee a flow won't be picked up by multiple agents simultaneously - prefect "projects" don't provide isolation between agents, only "tenants" do. Within a tenant, you'd need to use labels to differentiate between agents. We have additional safeguards at the backend level that should have prevented duplicate jobs for the same flow run from executing, still not sure why they didn't hit here.

We're looking into this bug (which we can confirm happened from looking at the database), just trying to narrow things down. Can you confirm one more time for us: did the same agent process submit both of those flow runs or not?

**Comment by richard-hughes-tel** [comment]
@jcrist 

Yes, these items are from the UI logs. 

> ```
>06:34:54  INFO  agent  Submitted for execution: PID: 16288
>06:34:54  INFO  agent  Submitted for execution: PID: 10392
>```

Also, just to clarify we are using labels on our projects and inside our flows. We are using one label per project which correlates to one label for the agent. We didn't mean to overlap any of our labels on agents nor projects.

> ~~Yes, one agent per project in my environment.~~ <- my mistake, we are using 2 agents on the server  

The UI only indicates or sees 1 agent. Now that I can think about this, we have 2 agents running on the same machine however, they are using the same label, I thinks this is causing the issue. When I look at the UI, I notice only 1 agent registered however, like I said there are 2 agents running as a service on the machine.  So the agents are the same but not. Hope this clarifies the issue. If I want to keep 2 agents on the same machine with use of the same label for the project. 

With this being said, how do I need a separate these agents? With a label to identify each unique agent on the machine? and to keep these identical however, with the same label to identify the project.

Let me know if I can provide any further details. If you want to jump on a call to see into our environment, I can share this with you. I am assuming the agents are picking up the job at the same exact moment and running the flow in parallel.

**Comment by cicdw** [comment]
Update here: we have some backend changes that should prevent this from happening regardless of the number of identical agents you have; it's scheduled to get released tomorrow - I'll comment back when it's live so you can run some tests and confirm!

**Comment by cicdw** [comment]
The fix has now been released 👍

**Comment by Eumenidies** [comment]
> The fix has now been released

hello，may I ask a question？
the newest release supports one more identical agents on one more machine？

**Comment by cicdw** [comment]
Hi @Eumenidies - yes, both Server and Cloud support multiple identical agents running on one or more machines.

**Comment by mr-tester-william-lo** [comment]
Version 0.15.1 testing:
Same problem exist, if i have more than one docker agents (without labels)(e.g. 2), when i schedule the task (again without label) 
**both docker agents will create the task and run the task. so duplicate run will be happened**

- May i know how to fix it by, if the (proj name+flow name + para name + time schedule) are same, no duplicate run allowed?

- How to enable active active agent, without trigger the flow twice

**Comment by cicdw** [comment]
@mr-tester-william-lo are you using Prefect Server? If so, this is [a known limitation](https://github.com/PrefectHQ/server/issues/203). We do not recommend horizontally scaling your agents when running Prefect Server.  If this is a requirement for some reason, Prefect Cloud automatically prevents duplicate submissions.

**Comment by mr-tester-william-lo** [comment]
So, may I know how to add labels to the schedule which created through graphql request?

I can only find these:

- https://github.com/PrefectHQ/prefect/blob/master/src/prefect/schedules/clocks.py#L237
- https://github.com/PrefectHQ/prefect/blob/master/src/prefect/backend/flow_run.py#L601

, which we can create label when we register the flow, but not the schedule task created by graphql query (https://docs.prefect.io/orchestration/flow-runs/scheduling.html#creating-flow-schedules)

I would like to add labels based on the scheduled task created from graphql mentioned by this:
https://github.com/PrefectHQ/prefect/discussions/4628
