### ISSUE TITLE
prefect.schedules.clocks.IntervalClock serialization results in `{'_schema': 'Unsupported object type: IntervalClock'}`

### ISSUE THREAD

**Issue by MichaMucha** [PrefectHQ/prefect#3765]
## Description

Hi! Thanks for making this great library available to everyone.

I've been trying to register a flow on prefect cloud, and unfortunately getting waylaid by serialization problems.

I narrowed it down to a strange problem with Clocks. Am I missing something simple?

```
schedule = prefect.schedules.clocks.IntervalClock(
    timedelta(days=1),
    start_date=datetime(2020,12,1, 11, 8)
)

with Flow('MyFlow', schedule=schedule) as flow:
...
```

Here is what the serialization results in:

```
In [2]: flow.serialize()
Out[2]: 
OrderedDict([('name', 'MyFlow'),
             ('type', 'prefect.core.flow.Flow'),
             ('schedule',
              (None, {'_schema': 'Unsupported object type: IntervalClock'})),
             ('parameters', []),

...
```

I will note that `prefect.utilities.debug.is_serializable`
returns True for the tasks and the flow.

## Expected Behavior

Serialization to happen and flow to get registered in the cloud UI.

## Reproduction

Quoted in "description"

## Environment

Miniconda Python 3.8 on Windows and on Linux

```
In [2]: prefect.__version__
Out[2]: '0.13.18'
In [4]: cloudpickle.__version__
Out[4]: '1.5.0'
```

**Comment by jlowin** [comment]
Hi @MichaMucha, Prefect is looking for you to pass a `Schedule` object (of which a `Clock` is one component) to your flow -- see https://docs.prefect.io/core/concepts/schedules.html for detail.

In your case, you could import the `prefect.schedules.IntervalSchedule()` convenience class, or add your `clock` to a new schedule like this:
```python
clock = prefect.schedules.clocks.IntervalClock(
    timedelta(days=1),
    start_date=datetime(2020,12,1, 11, 8)
)
schedule = prefect.schedules.Schedule(clocks=[clock])

```

**Comment by MichaMucha** [comment]
Thank you, missed this obvious note, just came back to close this.
Appreciate the quick response

**Comment by jlowin** [comment]
No problem, let us know how it goes!
