### ISSUE TITLE
TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by jackdesert** [PrefectHQ/prefect#3781]
## Description
When registering a task that calls a class with a redis instance as a class variable, the following error displays:

`TypeError: can't pickle _thread.lock objects`

## Expected Behavior

Expected it to register the flow

## Reproduction

    from prefect import task, Flow
    import redis

    class Thing:
        REDIS = redis.StrictRedis(host='localhost')

        @classmethod
        def run(cls):
            print('inside run')

    @task
    def run_the_thing():
        Thing.run()

    if __name__ == '__main__':
        with Flow('test-thing') as flow:
            run_the_thing()

        flow.register('test-pickle-error')  

## Environment

        $ prefect diagnostics
        {
          "config_overrides": {},
          "env_vars": [],
          "system_information": {
            "platform": "Linux-4.14.203-156.332.amzn2.x86_64-x86_64-with-glibc2.2.5",
            "prefect_backend": "server",
            "prefect_version": "0.13.18",
            "python_version": "3.7.9"
          }
        }

**Comment by jackdesert** [comment]
The error goes away if this line is commented out:

    REDIS = redis.StrictRedis(host='localhost')

**Comment by jackdesert** [comment]
Following this slack thread:
https://prefect-community.slack.com/archives/CL09KU1K7/p1599231648306900

Perhaps the `redis.StrictRedis` instance needs to be generated when the flow is executed, as opposed to when it is registered. 

That would doable. 

**Improved Error Message**

It took me a while to track down which line was breaking. I wonder what it would take to get the error message to say which object is not pickleable, such as:

`TypeError redis.StrictRedis instance is not pickleable.`

**Comment by cicdw** [comment]
These errors come from pickle internals and / or from custom messages within individual libraries, and would be a large undertaking to isolate the individual attributes that are not pickleable.
