### ISSUE TITLE
Allow naming tasks produced by `nout`

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3789]
The `nout` flag that @jcrist added in #3697 is a great new feature! But one thing that hampers its utility a little bit is the fact that every resulting task has the name `GetItem`; this means that for a flow that makes liberal use of this new feature, the Cloud UI is nearly useless as it's impossible to distinguish one task from another.
![image](https://user-images.githubusercontent.com/903655/101665448-98a98180-3a12-11eb-8ffa-6cceaee98036.png)

I'm guessing @jcrist or @cicdw might have a more general idea, but a couple of possible solutions could be:
a) rename `nout` (`out` ?) and accept either an int (like the current behavior) or an iterable of labels (the length would implicitly provide the number of tasks)
b) add a new optional arg just to label the tasks

Curious to hear people's thoughts; I can see an argument for keeping things simpler, but at least for me the lack of names will definitely keep me from using this exciting cool new feature which is too bad 🙂 .

**Comment by jcrist** [comment]
What kind of names would you want? What if we auto-named the tasks, but gave them a better name? Perhaps take the name of the generating task plus an index into it - like `my_task[0]`.

**Comment by madkinsz** [comment]
> What kind of names would you want? What if we auto-named the tasks, but gave them a better name? Perhaps take the name of the generating task plus an index into it - like `my_task[0]`, `my_task[1]`.

Adding the indexing makes sense as a first step. I'm not sure if we want to parse it but we could maybe inspect `NamedTuple` which is kind of a pain

```
>>> from typing import NamedTuple
>>> 
>>> def foo() -> NamedTuple('FooOut', [('a', int), ('b', int), ('c', int)]):
...         return 1, 2, 3
... 
>>> print(foo.__annotations__['return']._fields)
('a', 'b', 'c')
```

**Comment by bnaul** [comment]
> What kind of names would you want? What if we auto-named the tasks, but gave them a better name? Perhaps take the name of the generating task plus an index into it - like `my_task[0]`, `my_task[1]`.

that would be a good start! ideally I'd just want to use the same var names I'm using at unpacking time, just like your example has `double, triple = double_and_triple(inc)`; `double_and_triple[0]` is better than `GetItem` but not as good as `double` 🙂 

> we could maybe inspect NamedTuple which is kind of a pain

agree it looks gross but I personally would definitely use this in order to get a better UI experience....clean Cloud UI + messy code is a very worthwhile tradeoff for my use case

**Comment by jcrist** [comment]
With #4183 in, task names are now:

```python
@task(nout=2)
def my_task(x):
    return x + 1, x - y

a, b = my_task(x)
assert a.name == "my_task[0]"
assert b.name == "my_task[1]"
```

I'm not as enthused about the `NamedTuple` method, as it's not very clean to read. We could support it, but I'm not sure what benefit we'd get. Note that you can already rename output tasks manually, which gives you freedom to rename them however you'd like.

**Comment by bnaul** [comment]
Yeah I think you’re right that manual naming is a cleaner solution than messing with NamedTuple, thanks @JacobHayes and @jcrist !
