### ISSUE TITLE
Flow run fails with Unexpected error: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)

### ISSUE THREAD

**Issue by FranCao** [PrefectHQ/prefect#3790]
## Description
Using the sample found in the documentation here: https://docs.prefect.io/api/latest/tasks/shell.html#shelltask

Using VSCode:
```
from prefect import Flow, task
from prefect.tasks.shell import ShellTask

my_task = ShellTask(helper_script='cd ~')

with Flow('test') as f:
    contents = my_task(command='ls')

f.run()
```

This fails and returns the following:
```
ERROR - prefect.TaskRunner | Unexpected error: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\prefect\engine\runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\prefect\engine\task_runner.py", line 856, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "C:\Python\Python38-32\lib\site-packages\prefect\utilities\executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "C:\Python\Python38-32\lib\site-packages\prefect\utilities\tasks.py", line 449, in method
    return run_method(self, *args, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\prefect\tasks\shell.py", line 100, in run
    with Popen(
  File "C:\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Expected Behavior

With this being a basic example from the documentation, I was expecting it to work, so any insight is appreciated.
Another quick note here is that the below works without issues:
```
from prefect import task, Flow

@task
def say_hello():
    print("Hello, world!")

with Flow("testing") as f:
    say_hello()

f.run()
```

## Environment
Windows 10
Python 3.8.2
Prefect 0.13.16

**Comment by madkinsz** [comment]
The `ShellTask` writes a file then executes it with the given shell. The default shell is `bash` -- I'm guessing `bash` is not installed on your system.

**Comment by FrancesSun** [comment]
Hi @madkinsz, thanks for responding. Bash is installed on my system, running on GNU bash, version 4.4.19(1)-release (x86_64-alpine-linux-musl).

**Comment by madkinsz** [comment]
> Hi @madkinsz, thanks for responding. Bash is installed on my system, running on GNU bash, version 4.4.19(1)-release (x86_64-alpine-linux-musl).

Interesting! Could you try running `where bash` then pass that full path into `ShellTask` like `shell="C:\path\to|bash"`

**Comment by FrancesSun** [comment]
> > Hi @madkinsz, thanks for responding. Bash is installed on my system, running on GNU bash, version 4.4.19(1)-release (x86_64-alpine-linux-musl).
> 
> Interesting! Could you try running `where bash` then pass that full path into `ShellTask` like `shell="C:\path\to\bash"`

Yep, I'm running this:
```
from prefect import Flow, task
from prefect.tasks.shell import ShellTask

my_task = ShellTask(shell="C:\Windows\System32\bash.exe")

with Flow('test') as f:
    contents = my_task(command='ls')

f.run()
```
But getting the same error message

**Comment by madkinsz** [comment]
Alright, we'll try to reproduce this and get back to you!

**Comment by jakubvedral** [comment]
I had the same issue. 
The only option for me was to modify shell.py (where ShellTask is defined) and make NamedTemporaryFile to be closed before executing with POpen and deleting the temp file afterwards.

Also I had to disable shell parameter when executing on windows.
I can paste here the modification if you are interested.

**Comment by FrancesSun** [comment]
> I had the same issue.
> The only option for me was to modify shell.py (where ShellTask is defined) and make NamedTemporaryFile to be closed before executing with POpen and deleting the temp file afterwards.
> 
> Also I had to disable shell parameter when executing on windows.
> I can paste here the modification if you are interested.

That would be great, thank you!
