### ISSUE TITLE
Flow is not added to storage if build=False

### ISSUE THREAD

**Issue by alexkoay** [PrefectHQ/prefect#3810]
## Description
When using `stored_as_script=True`, if we manually build the Docker image and pass `build=False` to the registration call, the storage doesn't automatically add the flow into the Storage and will cause a KeyError to be raised when running the flow.

## Expected Behavior
`storage.add_flow` should be run even if `build=False`

**Comment by joshmeek** [comment]
Hey @alexkoay `add_flow` does not actually add the flow to the docker image but instead only adds the flow to the storage object. Calling `build` is the actual function to build a docker image and in that step all of the flows are added during the image build.

**Comment by alexkoay** [comment]
Yup @joshmeek, what I meant is that it doesn't add the flow into the storage object without calling `add_flow` manually, so if you `register(build=False)`, the resulting flow registered would actually fail with a KeyError. Of course I can still manually call `add_flow` but it seems to me that it should be automatically done regardless of whether `build` is True or False. Are there any scenarios in which we'd want to have it not added into the storage object when registering?

**Comment by joshmeek** [comment]
Ah I see what you mean. I believe this should actually be the intended behavior. The offending call is:

https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L1453-L1454

cc @cicdw If you think there is any reason why this shouldn't be the case. Otherwise I can make the change.

**Comment by cicdw** [comment]
I'm not necessarily opposed to it; however, usually we recommend registering a flow _after_ storage has already been built, so the assumption with `build=False` is that you've already done that yourself.  Additionally, the moment you aren't relying on Prefect to build your storage, you're doing things manually anyway.  So while I don't think this will have any negative downstream consequences and would most likely ✅ a PR, it also feels like encouraging an anti-pattern.

**Comment by alexkoay** [comment]
If `add_flow` is not automatically called, perhaps there should be a note linking it to `build=False`. The only location where this function appears (aside from the API docs) was in [Multi Flow Storage](https://docs.prefect.io/orchestration/recipes/multi_flow_storage.html), so I had the wrong assumption that it was magic (for single flows) since I personally wouldn't register a flow without ensuring that it can be located in the storage. Debugging the resulting KeyError was an interesting exercise due to my faulty model.

Just for context, my use-case is that I've built the Docker image outside and using it to register multiple flows (in different files), and hence never actually building it within code.
