### ISSUE TITLE
Unable to Set log_to_cloud to False

### ISSUE THREAD

**Issue by jackdesert** [PrefectHQ/prefect#3844]
@znicholasbrown 

## Description

Local agent is sending logs to the server, even with this ~/.prefect/config.toml 
`[logging]
log_to_cloud = false`

and with this environment variable set

PREFECT__LOGGING__LOG_TO_CLOUD=false

See this slack conversation:
https://prefect-community.slack.com/archives/C014Z8DPDSR/p1607999549294500

## Expected Behavior

Expected to only see local logs

## Reproduction

Here is a simple flow with a print statement

    from prefect import task, Flow

    @task(log_stdout=True)
    def simple_func():
        print('simple print statement')

    if __name__ == '__main__':
        with Flow('simple-print-statement') as flow:
            simple_func()

        flow.register('test-log')
        flow.run()    

## Environment

    $ prefect diagnostics
    {
      "config_overrides": {
        "logging": {
          "extra_loggers": true
        }
      },
      "env_vars": [],
      "system_information": {
        "platform": "Linux-4.14.203-156.332.amzn2.x86_64-x86_64-with-glibc2.2.5",
        "prefect_backend": "server",
        "prefect_version": "0.13.19",
        "python_version": "3.7.9"
      }
    }

**Comment by joshmeek** [comment]
Hi @jackdesert how are you starting the local agent? You should be able to disable logging to cloud by passing in the `--no-cloud-logs` flag to `prefect agent local start`. Or if starting the class directly you can pass it as `LocalAgent(no_cloud_logs=True)`.

**Comment by jackdesert** [comment]
@joshmeek This is how I'm starting the local agent:

    PREFECT__LOGGING__LOG_TO_CLOUD=false prefect agent local start

**Comment by joshmeek** [comment]
Okay, the agent does not pass that configuration setting to the processes it creates. Instead try

```
prefect agent local start --no-cloud-logs
```

**Comment by jackdesert** [comment]
@joshmeek My goal is to document the behavior of the log_to_cloud config variable.

**Comment by joshmeek** [comment]
So the `log_to_cloud` config variable _does_ disable sending logs to cloud but only in the process where the flow is running. Setting `no_cloud_logs` on the agent sets this value:

https://github.com/PrefectHQ/prefect/blob/6dd267d43d74abb3f7c412ead1440a7cadc8ab4f/src/prefect/agent/agent.py#L131

that is then used to set the `PREFECT__LOGGING__LOG_TO_CLOUD` value in the environment of the process where the flow inevitably runs:

https://github.com/PrefectHQ/prefect/blob/6dd267d43d74abb3f7c412ead1440a7cadc8ab4f/src/prefect/agent/local/agent.py#L225

**Comment by jackdesert** [comment]
I actually LIKE the logs going to the server. The slack workspace says log_to_cloud is required in order for logs to go to the server. But for me that does not seem to be the case.

To state the negative: I am NOT trying to prevent logs from going to the server. 

I did try what you asked: passing the --no-cloud-logs flag to the agent, and that gave very minimal log lines on the server (one log line instead of 5-6). But again, I'm just here to clarify what's supposed to happen and to document it.

**Comment by jackdesert** [comment]
So you are confirming that setting log_to_cloud in the config file has no effect?

**Comment by joshmeek** [comment]
> So you are confirming that setting log_to_cloud in the config file has no effect?

It has no effect on the processes that the agent creates (because the value is not propagated to the subprocesses). The value does still work in disabling sending logs to the server as long as it is set on the flow run's process.

**Comment by jackdesert** [comment]
So it only disables prefect logging for flows that are run from the terminal

But does not affect prefect logging for flows that are run from the browser?

**Comment by joshmeek** [comment]
Yes, to disable logs to cloud for your flow runs you use the CLI flag on the agent.
