### ISSUE TITLE
MySQL Tasks: support SSL connection

### ISSUE THREAD

**Issue by jacob-lester** [PrefectHQ/prefect#3845]
Since the MySQL task uses pymysql under the hood, is there a way you all can include the "ssl" named parameter in order to query/execute using secure connection? https://github.com/PrefectHQ/prefect/blob/076de76c4b7ba2c5c870230e1bfff0526e70aa84/src/prefect/tasks/mysql/mysql.py#L68-L75

**Comment by joshmeek** [comment]
Hey @jacob-lester I believe the `ssl` keyword argument could be added to this community contributed task and we welcome a PR to add it 🙂

**Comment by tchoedak** [comment]
@joshmeek @jacob-lester hey guys, is this what you're looking for? https://github.com/PrefectHQ/prefect/pull/4545
