### ISSUE TITLE
AzureResult read function not working

### ISSUE THREAD

**Issue by emilbbusch** [PrefectHQ/prefect#3846]
## Description

Using `AzureResult` to read a file, an exception is raised:

> TypeError: a bytes-like object is required, not 'StorageStreamDownloader'

Looking at the `read` function in `src/prefect/engine/results/azure_result.py` I see the following:

```python
content_string = client.download_blob()

try:
    new.value = new.serializer.deserialize(content_string)
```

`client.download_blob()` returns a `StorageStreamDownloader`, while `new.serailizer.deserialize(content_string)` expects a byte array.

## Expected Behavior
I would expect that the file would be read without raising an exception.

## Reproduction
```python
from prefect.engine.results import AzureResult

con_string = ""
azure_result = AzureResult(container="data", connection_string=con_string)

w = azure_result.write({"Test": "123"})
r = azure_result.read(w.location)
```

## Environment
```json
{
  "config_overrides": {
    "context": {
      "secrets": false
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.18362-SP0",
    "prefect_backend": "server",
    "prefect_version": "0.13.19",
    "python_version": "3.9.0"
  }
}
```

**Comment by joshmeek** [comment]
Hey @emilbbusch thanks for reporting! I know the fix and can submit a PR. 🙂
