### ISSUE TITLE
Add title argument for Artifacts

### ISSUE THREAD

**Issue by mitchbregs** [PrefectHQ/prefect#3854]
## Current behavior
Currently, Prefect Artifacts behave as such:

```python
from prefect.artifacts import create_markdown

create_markdown("# Something interesting")
```

and appear as such in Prefect Cloud:

![Screen Shot 2020-12-16 at 9 50 17 AM](https://user-images.githubusercontent.com/1377151/102364118-1d048300-3f84-11eb-91d7-b0462e1b849e.png)

The only available argument for `create_markdown` is the actual markdown text itself as type `str`.

## Proposed behavior

Include a `title` argument for the artifact creation.  Would look something as such:

```python
from datetime import datetime
from prefect.artifacts import create_markdown

create_markdown(title=f"Some validation: {datetime.now()}", markdown="# Some awesome validation results!")
```

Hence, on the UI you can see a dynamic title generated for each of your created artifacts.

## Example

The enhancement would be useful for quick ad-hoc type analysis work, creating basic run-time reports for individual tasks, organizes artifacts from complex workflows.

**Comment by joshmeek** [comment]
Great suggestion @mitchbregs!

@znicholasbrown Is this similar to the `name` suggestion you mentioned recently or was that for more metadata/organizational related enhancements?

**Comment by znicholasbrown** [comment]
They seem pretty on par - either would let us surface artifacts a little more readily 😄

**Comment by jcrist** [comment]
Similarly, I think it'd be good to have a title (or name or something) for links. I'm not sure if we'd want this to display as:

```
title: https://full-url-here
```

or (in markdown syntax)

```
[title](https://full-url-here)
```

`name` feels like the wrong word, but I'm not sure if `title` is the proper one either.

**Comment by madkinsz** [comment]
Just for additional context, at https://www.markdownguide.org/basic-syntax#links they refer to the components as
```
[text](url "title")
```
where "title" is for hover tooltips which I do *not* think we need to support but it makes `title` feel like a poor name.
