### ISSUE TITLE
Ignore PINs and Changelogs from results when searching docs

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#3868]
Sometimes certain phrases rank higher in the search when they come through in Changelog updates or PINs. These should not appear at the top of search (and may not need to appear at all).

Changelog in search:
![image](https://user-images.githubusercontent.com/40716964/102498570-2525f680-4048-11eb-872f-684f7211c261.png)

PINs in search:
![image](https://user-images.githubusercontent.com/40716964/102498413-f019a400-4047-11eb-9536-019cf171bee0.png)

**Comment by joshmeek** [comment]
@znicholasbrown I'm not sure if this is something we can accomplish in the algolia indexing (ignoring certain directories) or it needs to happen in post-processing

**Comment by znicholasbrown** [comment]
@joshmeek we can tweak the results on the Algolia side, that's probably best
