### ISSUE TITLE
Google Cloud Storage <= 1.31 no longer supported

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3870]
#3741 changed the GCS result to use a function that was only released a couple of months ago in 1.31.0 (see https://github.com/googleapis/python-storage/commits/master?after=9d5bb5622f17a0143fa6670406596e53d0068286+34&branch=master).

In my opinion it's a bit too aggressive to require a very new version of a low-level requirement like this, but regardless the listed requirement should be bumped correspondingly (right now it's at 1.13.0 https://github.com/PrefectHQ/prefect/blob/b133b44cffab79735a8fe86e16c81d3e6c74d1ab/setup.py#L35 which is from October 2018). Would a `try: ... except AttributeError:` block be acceptable as a way to maintain backwards compatibility?

**Comment by jcrist** [comment]
Ah, nice catch @bnaul. I think using `download_as_string` if `download_as_bytes` isn't available is fine. I'll push a patch to fix. Thanks!
