### ISSUE TITLE
Mapped tasks show null state even after completion

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3874]
For a flow with a large number of mapped tasks (~8000) I'm seeing a few (28) statuses remain "null" even after the task run/flow have completed. I guess "null" is considered failing so all downstream tasks TriggerFail as well.
![image](https://user-images.githubusercontent.com/903655/102624107-28cd8200-4109-11eb-9c9c-8b8bf974a7ca.png)

@cicdw mentioned that a change was made to defer some aspects of task run creation so maybe there's some uncaught error/race condition in the new logic? This is on prefect 0.13.18, dask 2.30.0.

- Most of the null tasks seem to have been created in the first "batch": we have 1200 worker threads, so the first 1200 tasks show up more or less right away, and that's where 25 of the 28 come from. The other 3 all showed up towards the end.
![image](https://user-images.githubusercontent.com/903655/102624014-09365980-4109-11eb-9cf5-93be70cb5359.png)

- The mapped results are `pd.Series` objects and all look fine; however, that task errors with `TypeError("cannot concatenate object of type '<class 'marshmallow.exceptions.ValidationError'>'; only Series and DataFrame objs are valid")`. Seems likely that this is just a symptom and not the root cause but I figured I'd mention it.

**Comment by bnaul** [comment]
Updates: the status is actually `ClientFailed`, but I guess the UI renders it as `null`.
```
Task 'generate_population_activities[173]': Finished task run for task with final state: 'ClientFailed'
```
Looks like a 500 server-side that is not being caught and/or sufficiently retried
```
Failed to set task state with error: ClientError([{'path': ['set_task_run_states'], 'message': "'NoneType' object has no attribute 'get'", 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 124, in call_runner_target_handlers
    state = self.client.set_task_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1450, in set_task_run_state
    result = self.graphql(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 318, in graphql
    raise ClientError(result["errors"])
prefect.utilities.exceptions.ClientError: [{'path': ['set_task_run_states'], 'message': "'NoneType' object has no attribute 'get'", 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]```

**Comment by znicholasbrown** [comment]
Thanks for the update @bnaul - it looks like @cicdw will investigate the potential source of the ClientError but I've opened [a separate ticket](https://github.com/PrefectHQ/ui/issues/514) to fix that display issue in the UI, thanks for bring this to our attention!

**Comment by bnaul** [comment]
@cicdw I think you mentioned that you had a lead on this issue, any updates? Still seeing it on about 1% of my mapped task runs (which is significant when there's 1000s).

**Comment by cicdw** [comment]
@bnaul this fix should now be live - I'm going to close this issue but definitely let us know if you run into it again!
