### ISSUE TITLE
AWS EKS Fargate : Warning Unhealthy kubelet  Liveness probe failed :8080/api/health" on  | 

### ISSUE THREAD

**Issue by sagungargs15** [PrefectHQ/prefect#3882]
I am getting this error "Warning Unhealthy kubelet Liveness probe failed :8080/api/health" on AWS EKS Fargate
I am receiving this error after running. @znicholasbrown @cicdw Please help 

`$ prefect agent kubernetes install -t <MY_TOKEN> --rbac | kubectl apply -f -`

Also the agent serverless kubernetes cluster is not showing up in the Prefect UI dashboard
Two potential reasons I think where I am struggling is since I am registering a Prefect Agent on a Private Subnet on AWS EKS?
Warning Unhealthy 43s (x2 over 83s) kubelet, .internal Liveness probe failed: Get http://10.0.28.4:8080/api/health : dial tcp 10.0.28.4:8080: connect: connection refused

So perhaps the other K8 deployments are issuing the liveness probe to localhost while AWS' EKS uses their VPC subnets for Pods and is attempting to access the actual IP of the Pod at port 8080 .. and because the service doesn't appear to be listening on all addresses, it's rejected

PREFECT__CLOUD__AGENT__AGENT_ADDRESS on the other K8 clusters, and it seems they were set to http://:8080 which appears to listen on all addresses of the Pod.

Manually changing this to http://0.0.0.0:8080 allowed it to pass the liveness probes!! HOW CAN I MAKE THIS CHANGE IN YAML FILE PLEASE CAN YOU GUIDE ME

Logs of the failing pod made to restart by K8s

```
Warning LoggingDisabled 48m          fargate-scheduler Disabled logging because aws-logging configmap was not found. configmap "aws-logging" not found
 Normal  Scheduled    48m          fargate-scheduler Successfully assigned default/prefect-agent-7bcdb4f975-pftnw to fargate-ip-10-0-231-193.ap-southeast-1.compute.internal
 Normal  Created     43m (x4 over 47m)   kubelet      Created container agent
 Normal  Started     43m (x4 over 47m)   kubelet      Started container agent
 Normal  Killing     42m (x2 over 45m)   kubelet      Container agent failed liveness probe, will be restarted
 Normal  Pulling     41m (x5 over 48m)   kubelet      Pulling image "prefecthq/prefect:0.14.0-python3.6"
 Normal  Pulled      41m (x5 over 47m)   kubelet      Successfully pulled image "prefecthq/prefect:0.14.0-python3.6"
 Warning Unhealthy    12m (x13 over 46m)  kubelet      Liveness probe failed: Get http://10.0.231.193:8080/api/health: dial tcp 10.0.231.193:8080: connect: connection refused
 Warning BackOff     3m3s (x113 over 43m) kubelet      Back-off restarting failed container
```

**Error Logs using the pod logs**

$ kubectl -n <namespace-name> logs -p <pod name>

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
  (self._dns_host, self.port), self.timeout, **extra_kw
 File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
  for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
 File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
  for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
  chunked=chunked,
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
  self._validate_conn(conn)
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
  conn.connect()
 File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 353, in connect
  conn = self._new_conn()
 File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
  self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbb61ef5fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
  timeout=timeout
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
  **response_kw
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
  **response_kw
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
  **response_kw
 [Previous line repeated 3 more times]
 File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
  method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
  raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.prefect.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbb61ef5fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/bin/prefect", line 8, in <module>
  sys.exit(cli())
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
  return self.main(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
  rv = self.invoke(ctx)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
  return callback(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line 282, in start
  start_agent(KubernetesAgent, image_pull_secrets=image_pull_secrets, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line 109, in start_agent
  agent.start()
 File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py", line 221, in start
  self._verify_token(self.client.get_auth_token())
 File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py", line 175, in _verify_token
  result = self.client.graphql(query="query { auth_info { api_token_scope } }")
 File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 303, in graphql
  retry_on_api_error=retry_on_api_error,
 File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 219, in post
  retry_on_api_error=retry_on_api_error,
 File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 445, in _request
  session=session, method=method, url=url, params=params, headers=headers
 File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 345, in _send_request
  response = session.post(url, headers=headers, json=params, timeout=30)
 File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
  return self.request('POST', url, data=data, json=json, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
  resp = self.send(prep, **send_kwargs)
 File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
  r = adapter.send(request, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
  raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.prefect.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbb61ef5fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by jcrist** [comment]
Hi @sagungargs15. I'm having a bit of trouble understanding your issue above - a few questions:

> Manually changing this to http://0.0.0.0:8080 allowed it to pass the liveness probes!!

Does this fully resolve all your issues? Or are there still other problems you're having?

> HOW CAN I MAKE THIS CHANGE IN YAML FILE PLEASE CAN YOU GUIDE ME

The `prefect agent kubernetes install` command is only a helper to generate an example deployment - you're free to edit this as needed. To do this, you might save the output to a `deployment.yaml` file, make the changes you need, then use `kubectl apply -f deployment.yaml` to create your deployment.

> Also the agent serverless kubernetes cluster is not showing up in the Prefect UI dashboard
> Error Logs using the pod logs

From the logs here, it appears the pod is failing to connect to `api.prefect.io`. If you're running with Prefect Cloud (instead of Prefect Server), you'll need to ensure that the agent pod has access to this address. This would explain why the agent isn't showing up in your agent's dashboard.

**Comment by sagungargs15** [comment]
Hi Jim,

Thanks for your reply and timely help.

*Here is the Situation. *
1. I followed your steps for deployment.yaml (I substituted
http://0.0.0.0:8080 as per your guidelines)
2. I double checked the security groups (Caveat I am using private vpc, but
security group(s) have Inbound/Outbound "all traffic" option enabled)
3. I checked prefect cloud again. I actually missed seeing the agent on
cloud last time it shows there (screenshot attached)
4. I checked the version of prefect(in light of new release) prefect
version prompts 0.14.0 on CLI (since we are doing cluster+node setup on K8
has anything changed in the new version ? As I am yet to run the flows
using RUN_CONFIG and EXECUTOR pattern introduced in latest release on
Friday)

*I am attaching some screenshots for your reference. Also I am reattaching
new logs here*

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line
170, in _new_conn

    (self._dns_host, self.port), self.timeout, **extra_kw

  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py",
line 73, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -3] Temporary failure in name resolution


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 706, in urlopen

    chunked=chunked,

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 382, in _make_request

    self._validate_conn(conn)

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 1010, in _validate_conn

    conn.connect()

  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line
353, in connect

    conn = self._new_conn()

  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line
182, in _new_conn

    self, "Failed to establish a new connection: %s" % e

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection
object at 0x7f0117b28048>: Failed to establish a new connection: [Errno -3]
Temporary failure in name resolution


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line
449, in send

    timeout=timeout

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 796, in urlopen

    **response_kw

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 796, in urlopen

    **response_kw

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 796, in urlopen

    **response_kw

  [Previous line repeated 3 more times]

  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py",
line 756, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line
573, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.prefect.io',
port=443): Max retries exceeded with url: / (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at
0x7f0117b28048>: Failed to establish a new connection: [Errno -3] Temporary
failure in name resolution',))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/bin/prefect", line 8, in <module>

    sys.exit(cli())

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in
__call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in
main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259,
in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259,
in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259,
in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066,
in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in
invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line
282, in start

    start_agent(KubernetesAgent, image_pull_secrets=image_pull_secrets,
**kwargs)

  File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line
109, in start_agent

    agent.start()

  File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py",
line 221, in start

    self._verify_token(self.client.get_auth_token())

  File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py",
line 175, in _verify_token

    result = self.client.graphql(query="query { auth_info { api_token_scope
} }")

  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py",
line 303, in graphql

    retry_on_api_error=retry_on_api_error,

  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py",
line 219, in post

    retry_on_api_error=retry_on_api_error,

  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py",
line 445, in _request

    session=session, method=method, url=url, params=params, headers=headers

  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py",
line 345, in _send_request

    response = session.post(url, headers=headers, json=params, timeout=30)

  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line
590, in post

    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line
542, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line
655, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line
516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='
api.prefect.io', port=443): Max retries exceeded with url: / (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at
0x7f0117b28048>: Failed to establish a new connection: [Errno -3] Temporary
failure in name resolution',))

(.venv) sagungargs@Saguns-MacBook-Pro ingress %

**Comment by sagungargs15** [comment]
@jcrist Here is my deployment.yaml for your reference


```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
          value: kXe_*#%#%#^$^$^$%^BdgULWw
        - name: PREFECT__CLOUD__API
          value: https://api.prefect.io
        - name: NAMESPACE
          value: default
        - name: IMAGE_PULL_SECRETS
          value: ''
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '[]'
        - name: JOB_MEM_REQUEST
          value: ''
        - name: JOB_MEM_LIMIT
          value: ''
        - name: JOB_CPU_REQUEST
          value: ''
        - name: JOB_CPU_LIMIT
          value: ''
        - name: IMAGE_PULL_POLICY
          value: ''
        - name: SERVICE_ACCOUNT_NAME
          value: ''
        - name: PREFECT__BACKEND
          value: cloud
        - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
          value: http://0.0.0.0:8080
        image: prefecthq/prefect:0.14.0-python3.6
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent-rbac
  namespace: default
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prefect-agent-rbac
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent-rbac
subjects:
- kind: ServiceAccount
  name: default


```

**Comment by madkinsz** [comment]
The important error here is likely `socket.gaierror: [Errno -3] Temporary failure in name resolution` which indicates something is wrong with either your firewall or kubedns.

**Comment by sagungargs15** [comment]
Hey @madkinsz Thanks for pointing it out 

PFA the screenshot of the kubedns

<img width="1118" alt="Screenshot 2020-12-23 at 3 00 49 PM" src="https://user-images.githubusercontent.com/75983174/102969001-dc7ea980-452f-11eb-98bb-b3e0d1f847a6.png">

**Comment by sagungargs15** [comment]
@madkinsz @jcrist Any recommendations or help would be really awesome it has been almost a week at this problem

**Comment by sagungargs15** [comment]
I found these resolution pages working with them one by one 

**https://docs.aws.amazon.com/eks/latest/userguide/coredns.html**
_To check if your cluster is already running CoreDNS, use the following command._
`$ kubectl get pod -n kube-system -l k8s-app=kube-dns`
_Fetch the coredns pod name from your cluster._
```
$ COREDNS_POD=$(kubectl get pod -n kube-system -l eks.amazonaws.com/component=coredns \
-o jsonpath='{.items[0].metadata.name}')
```
_Query the coredns pod to ensure that it's receiving requests._
```
kubectl get --raw /api/v1/namespaces/kube-system/pods/$COREDNS_POD:9153/proxy/metrics \
| grep 'coredns_dns_request_count_total'
```
_Scale down the kube-dns deployment to zero replicas_ 
`$ kubectl scale -n kube-system deployment/kube-dns --replicas=0`
_Scale up the kube-dns deployment to zero replicas_
`$ kubectl scale -n kube-system deployment/coredns --replicas=3`

**https://github.com/aws/aws-cdk/issues/6005 (It seems CoreDNS pods not starting automatically after eks.FargateCluster deployment)**

In my case all the pods of kube-dns i.e coredns are showing pending hence a restart is suggested
`$kubectl rollout restart -n kube-system deployment coredns`

**Comment by sagungargs15** [comment]
@madkinsz @jcrist Further diagnosis on missing dns endpoints shows this

<img width="1109" alt="Screenshot 2020-12-23 at 10 29 14 PM" src="https://user-images.githubusercontent.com/75983174/103007510-84b36300-456e-11eb-81ae-9c6c9485107b.png">
<img width="696" alt="Screenshot 2020-12-23 at 10 29 23 PM" src="https://user-images.githubusercontent.com/75983174/103007521-87ae5380-456e-11eb-9739-1c5e4ab9980f.png">

**Comment by madkinsz** [comment]
I appreciate that you're posting these updates here, they'll be helpful for others I'm sure. We presume the agent installation is on a healthy cluster so we can't really do much here, this is really a topic for AWS support. My best guess is that there is a K8s scheduling issue. Perhaps take a look at https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns

**Comment by sagungargs15** [comment]
@madkinsz You bring early Christmas for me. My man thankyou so much for being the guiding light. Merry Christmas to you and thank you for point this out. _The magic lies in this optional todo which is mandatory if you create a K8 cluster for fargate deployment i.e using fargate profiles for your pods using the AWS Console_

<img width="1080" alt="Screenshot 2020-12-24 at 4 39 55 PM" src="https://user-images.githubusercontent.com/75983174/103075478-a95b1980-4606-11eb-844d-2404ab2445e0.png"> 


**This resource you shared clearly highlights that if you create a K8 cluster using the AWS Console for Fargate based K8 deployment then you need to patch** 
https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns

**Steps I followed** 
1. Created a new coredns fargate profile from the AWS Console using these parameters
```
{
    "fargateProfileName": "coredns",
    "clusterName": "<dev>",
    "podExecutionRoleArn": "<arn:aws:iam::111122223333:role/AmazonEKSFargatePodExecutionRole>",
    "subnets": [
        "subnet-<0b64dd020cdff3864>",
        "subnet-<00b03756df55e2b87>",
        "subnet-<0418fcb68ed294abf>"
    ],
    "selectors": [
        {
            "namespace": "kube-system",
            "labels": {
                "k8s-app": "kube-dns"
            }
        }
    ]
}
```
then I ran using CLI

```
kubectl patch deployment coredns -n kube-system --type json \
-p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'

```

**_This finally changed the recurring issue (pending pods of coredns and no endpoint allocated)_**
<img width="782" alt="Screenshot 2020-12-24 at 4 01 59 PM" src="https://user-images.githubusercontent.com/75983174/103075311-4ec1bd80-4606-11eb-9a9c-59f71a8a8458.png">

 **_to an ideal scenario (Running coredns pods and with an endpoint for dns finally!!!)_**
<img width="784" alt="Screenshot 2020-12-24 at 4 33 18 PM" src="https://user-images.githubusercontent.com/75983174/103075368-6dc04f80-4606-11eb-9b8b-236081af2593.png">
 
**Now for prefect to go in business.**
