### ISSUE TITLE
Prefect serializes flows based on flow name ignoring project

### ISSUE THREAD

**Issue by jkknickerbocker** [PrefectHQ/prefect#3900]
Hi,

I searched the slack channel and did not find anything that pertained directly to this.  We use Prefect for two departments that have virtually the same flows, but different sources and different processing rules.  What we have found is that flows with the same name overwrite each other regardless of the project.  I am not sure if that is intended or if there is a way to work around this issue.

This is a minimal example that I confirmed in a fresh install of Prefect 0.14.0 running the server backend in docker with a local agent all on the same machine.

```
jaykae@DT-JKNICKERBOCKER: ~: ls -1 prefect_test prefect_test/proj*
prefect_test:
proj1
proj2

prefect_test/proj1:
WriteHello.py

prefect_test/proj2:
WriteHello.py
```
Just a folder with two subfolders, projects 1 and 2, each folder holds a file with nearly the same content.  Note the file paths are different and also the project names are different.

**proj1/WriteHello.py**
```
jaykae@DT-JKNICKERBOCKER: ~/prefect_test cat proj1/WriteHello.py
import prefect
from prefect import task, Flow

@task
def write_hello():
        with open("proj1/hello.txt","w") as hello_file:
                hello_file.write("Hello Project 1!!!")

with Flow("WriteHello") as flow:
        write_it = write_hello()

flow.register(project_name="Project1")
```

**proj2/WriteHello.py**
```
jaykae@DT-JKNICKERBOCKER: ~/prefect_test cat proj2/WriteHello.py
import prefect
from prefect import task, Flow

@task
def write_hello():
        with open("proj2/hello.txt","w") as hello_file:
                hello_file.write("Hello Project 2!!!")

with Flow("WriteHello") as flow:
        write_it = write_hello()

flow.register(project_name="Project2")
```

I register proj1/HelloWorld.py and then proj2/HelloWorld.py, I would expect that registering two flows with different file paths, as well as different project names would lead result in writing a text file in the directory for each flow when it is called.  However, when I run proj1/HelloWorld.py the file is written in the proj2 directory and says Hello Project 2!!!.

```
jaykae@DT-JKNICKERBOCKER: ~/prefect_test ls proj*
proj1:
WriteHello.py

proj2:
WriteHello.py
jaykae@DT-JKNICKERBOCKER: ~/prefect_test prefect run flow --name WriteHello --project Project1
Flow Run: http://localhost:8080/default/flow-run/e05b8f99-945d-4954-ab0d-7e5e89df0965
jaykae@DT-JKNICKERBOCKER: ~/prefect_test ls proj*
proj1:
WriteHello.py

proj2:
WriteHello.py  hello.txt
```

I tried changing the .py file name and that did not help at all, so I assume it has to do with the flow name.  Is there a way to have two flows with the same name, but different content, in separate projects and peacefully coexist?

**Comment by jkknickerbocker** [comment]
After more digging it looks like this code here is where the magic happens?
[prefect/src/prefect/storage/local.py](https://github.com/PrefectHQ/prefect/blob/98c46d0a3f96a9998c3460ad32b43a731a06341d/src/prefect/storage/local.py#L141
)
Would it be as simple as checking if the project is set and including that in the file name?  I'm happy to create a PR, but before I do, I would like to make sure I'm not heading in the wrong direction.

**Comment by madkinsz** [comment]
I'm not sure what the best solution for this is in the long run, I imagine one of the maintainers of this repo will have a stronger opinion.

In the meantime, you can definitely just change the flow storage directories so they don't overlap e.g.

```python
flow.storage = Local(directory=os.path.join(prefect.config.home_dir, "flows", "project1"))
```

**Comment by joshmeek** [comment]
Related to #1913. @jkknickerbocker we could make this change to use both the flow name and the project name as a default for the local storage. In the meantime, similar to what @madkinsz said you can specify different directories to store your flows or give your flows different names.

**Comment by jkknickerbocker** [comment]
Thank you both!

I went the route of updating my storage location (it was tedious for 50+ flows), but if we can include this as an enhancement (I might attempt to implement it) I think it would save some future headaches.
