### ISSUE TITLE
Turning off heartbeat setting doesn't work

### ISSUE THREAD

**Issue by nibrag** [PrefectHQ/prefect#3906]
## Description

When I turn off heartbeat in a flow settings page `CloudFlowRunner` still runs heartbeat process. Quick research showed that `CloudFlowRunner._heartbeat` always returns true.
Looks like that this graphql query
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/cloud/flow_runner.py#L78-L85

returns
```
{'data': {'flow_run_by_pk': {'flow': {'settings': {}}}}}
```
in both states.

## Expected Behavior

Heartbeat process doesn't run when it's turned off.

## Environment

LocalAgent + CloudFlowRunner

**Comment by cicdw** [comment]
Hi @nibrag - could you elaborate on why you want to turn off your flow run's heartbeat?  We are planning on removing this toggle altogether in the near future, as it was originally implemented as a stop-gap.

**Comment by nibrag** [comment]
Hi @cicdw. 

I use LocalAgent + CloudFlowRunner to run my flows. Today I saw that flow run process produced a lot of zombie processes.
Quick analyze and I saw that it's heartbeat processes became zombie.
So, I decided to turn off heartbeat but it doesn't work. It still runs heartbeat process.

```
ps aux | grep prefect
root        14  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root        26  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root        38  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root        58  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root        62  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root        72  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root       972  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1643  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1654  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1665  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1676  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1687  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1698  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1709  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1720  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1731  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1742  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1753  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1764  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
root      1775  0.0  0.0      0     0 ?        Z    Dec30   0:00 [prefect] <defunct>
```

```
ps aux | grep prefect | wc -l
199
```

**Comment by cicdw** [comment]
Do you have any insight into why your heartbeat process is dying?

**Comment by xuevin** [comment]
@cicdw Can you elaborate on why this toggle will be disabled? I have been disabling it in my flows because I have long running tasks which can hold onto the GIL. (ie. calls subprocess) Removing this feature would prevent my workflows from completing.

**Comment by cicdw** [comment]
For sure - this toggle was originally introduced for performance reasons: users who map over 1,000s of task runs had various issues with the number of subprocesses spawned, so we allowed them to turn the feature off.  It's worth noting though that turning this feature off is equivalent to turning off some of Prefect Server / Cloud's guarantees with regards to detecting dead runs / resurrecting incomplete runs.

As of 0.14.0, we no longer have individual task run heartbeats so the performance issues are gone, and consequently so is the need for this toggle.  The reason that we heartbeat from a subprocess is because subprocesses do _not_ hold the GIL (whereas a thread-based implementation would), so a task that holds the GIL for a long time is not an issue.

**Comment by jcrist** [comment]
Task run heartbeats are no longer a thing, closing.
