### ISSUE TITLE
Updated doc for DaskExecutor

### ISSUE THREAD

**Issue by vlcinsky** [PrefectHQ/prefect#3908]
The doc at https://docs.prefect.io/core/idioms/parallel.html shows few lines to run the flow in  distributed manner.

However, as mentioned in issue #2468, if the `flow.run` does not happen within `if __name__ == "__main__":` block, it fails to run in local mode.

The documentation shall show the way which works.

```python
if __name__ == "__main__":
    executor = DaskExecutor()
    state = flow.run(executor=executor)
```

_Originally posted by @vlcinsky in https://github.com/PrefectHQ/prefect/issues/2460#issuecomment-752740483_

**Comment by joshmeek** [comment]
@jcrist For suggestions on how to handle this in that idiom. The code works fine as is in an interactive session but would fail when running from a script. Perhaps we should add a tip/warning about he `__main__`?
