### ISSUE TITLE
Add docs on deploying a production ECS agent

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#3922]
We should add a docs section somewhere on how to deploy and manage a long running ECS agent on AWS (probably as part of an ECS service). While teams with deep dev-ops experience will likely have their own deployment method they'll want to use, a step-by-step guide would be useful in the general case. This question has come up in the support channel a lot recently, it'd be good to document a recommended solution.

**Comment by kingsleyb** [comment]
We have also seen several requests to understand the minimum set of policies required for using an ECS service, so it will be useful to include that detail in this doc.

**Comment by ciaranevans** [comment]
Hey folks, is there any news on the movement on this issue?

We're looking at deploying a production ECS agent 😅 

Or if there's a discussion going on somewhere (Slack/Other places) - I'd love to get involved! Cheers!
