### ISSUE TITLE
Dynamically construct N tasks to execute in sequence

### ISSUE THREAD

**Issue by hui-zheng** [PrefectHQ/prefect#3951]
## Current behavior

Prefect is great in dynamic mapping orchestration, which allows a flow to dynamically construct N tasks to execute in parallel. 

I have a different use case that requires dynamically constructing N tasks to execute in sequence. Currently, it requires some work-around to achieve this. I hope Prefect could support more natively in the future.

## Proposed behavior
A general concept
I have a task_A that generates N outputs. I would like the pipeline to dynamically construct N tasks_B for each of the N outputs that could then execute in sequence (not in parallel).
Those task_Bs need to be executed in sequence, that is, task_B_0 executes first, and then task_B_1 follows, and then task_B_2 follows. If a task_B_i failed, all the subsequence task_Bs could be skipped or failed.

Now each task_B_i returns an output, item_b. After all task_Bs execute, I have a list_B of task_B_i_output.
I could then define a task_c, which takes list_B , the results of all task_Bs, to carry some work. which is like a reduce operation of the upstream task_Bs.

## Example
**the real use case**
We have a pipeline that is backfilling some time-series data in BigQuery. Because the data is huge, it can not be done in one shot and have to divide the processing into several segments, and because of the time dependency, those segments need to be executed in sequence, one by one. In addition, because the period of backfill is provided as an input param which could be different every time, the flow won't be able to know the exact N number of the segments it need to process until at the run-time. 
So this pipeline first needs to (task A) generate a sequence of backfill commands, which are dbt runs against BigQuery, and run each dbt-run in sequence (task B), and finally to act on the success or failure result of overall backfill processing (task C).

Currently, we have to do it with a work-around, which is detailed in this slack thread. 
https://prefect-community.slack.com/archives/CL09KU1K7/p1603838678211000

**Comment by cicdw** [comment]
Hi @hui-zheng - after our conversation in Slack I realized another way to achieve this, that I believe is more streamlined than my previous suggestion, because it doesn't involve changing the structure of your Flow:

```python
import prefect
import time


def ordered_state_handler(task, old, new):
    flow_run_id = prefect.context.get("flow_run_id")
    task_id = prefect.context.get("task_id")
    map_index = prefect.context.get("map_index")
    if map_index is None:
        map_index = -1

    # if no flow run id this might be a local testing run
    # if map_index < 0 this isn't a mapped task
    # if map_index == 0, it's the first child and we're OK with that
    # if the proposed new state isn't a Running state, we don't care

    if not flow_run_id or map_index <= 0 or not new.is_running():
        return

    client = prefect.Client()

    while True:
        prev_state = client.get_task_run_info(flow_run_id, task_id, map_index - 1).state
        if prev_state.is_finished():
            return # the previous child is complete - we're good

        time.sleep(10) # 10 second sleep before we query again
```

You now need to put this state handler onto your mapped task via the `state_handlers=[ordered_state_handler]` kwarg.  Note that you can include multiple state handlers on a task and they will be called in order.
