### ISSUE TITLE
Flow stuck "Running" after all tasks have completed

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3952]
Recently (I believe starting today but I could be wrong) I'm seeing a number of flows that finish their terminal tasks but remain stuck in a "Running" state. So far I've checked that the `prefect-job` pod is healthy, and the Dask scheduler doesn't have any tasks pending (from the logs I can see that the Client disconnects right after the final task finishes, as expected).

I superstitiously thought that this might be related to the fix for #3874 since it seemed to coincide pretty much exactly with when I started noticing this behavior, but @cicdw says that's probably not it. cc @jcrist let me know if there's any other information I can provide for debugging (I've cancelled all the running flows but it seems pretty to happen pretty reliably; `34aaf390-bf0d-4795-a588-9853455bcbd0` was the last flow run, it stayed Running for over an hour before I killed it).

**Comment by bnaul** [comment]
Small update: this is still happening with nearly 100% of our flows but one of them (`2aca9a33-f782-449a-8a44-df615e8135a7`) finished overnight 🤔 
![image](https://user-images.githubusercontent.com/903655/104461712-4dd0db80-5575-11eb-8f62-7cec99f8b320.png)
The last task finished at 8:48pm (12 minutes), but the flow stayed Running for 7 more hours.

**Comment by bnaul** [comment]
I'm not sure what but I'm pretty convinced now that I did something weird with our `cluster_class` that's causing this, gonna close for now.

**Comment by BitTheByte** [comment]
I'm experiencing the same issue using Dask on Kubernetes, @bnaul could you please share if you managed to solve this?

**Comment by bnaul** [comment]
hmm wish I could be more helpful but all I remember is that it was an issue with our own wrapper around dask_kubernetes.KubernetesCluster that was causing problems; reverting back to the out-of-the-box version fixed it.

**Comment by vietnguyengit** [comment]
Same issue for me, Google brought me here.
