### ISSUE TITLE
File with multiple flows stored as script fails to run correct flow

### ISSUE THREAD

**Issue by alexkoay** [PrefectHQ/prefect#3961]
When declaring multiple flows (with different names) in a file with `stored_as_script=True`, running any of the flows via an agent seems to only pick up the first flow. I believe this is caused by the following line, as it doesn't pass the `flow_name` when running `get_flow()`.

https://github.com/PrefectHQ/prefect/blob/d4ad74a819eff585b0553b9479dd853e75089489/src/prefect/cli/execute.py#L67

The `get_flow()` function calls `extract_flow_from_file()` which supports an optional parameter for `flow_name`, so maybe this should be passed through.

My main use-case for this is running flows with a big time gap, e.g. running a long running task for 8 hours and then stopping it, where it doesn't make sense to keep the flow running with a `sleep()` for that amount of time. In this case, it is nicer to keep the flow code together instead of in separate files.

**Comment by joshmeek** [comment]
Thanks for opening @alexkoay! While a one-flow-per-file approach is generally recommended and more common I do think we should support this behavior. Would you be interested in contributing this change for your use case?

**Comment by jcrist** [comment]
Actually, this has some nuance to it (we'll want to change the signature of `get_flow` throughout to accomplish this). If you don't mind, I'll take this on.

**Comment by alexkoay** [comment]
Sure thing, yup, the Storage class' `get_flow()` function will all have to be updated to take the new parameter.
