### ISSUE TITLE
Possible memory leak when using DaskExecutor in Kubernetes

### ISSUE THREAD

**Issue by joelluijmes** [PrefectHQ/prefect#3966]
## Description

I’m running Prefect in Kubernetes. What I have is a flow which spawns 15 Kubernetes high CPU intense jobs. In order to do some parallelism, I have in the flow a DaskExecutor configured (6 workers, 1 thread).

What I see is the prefect-job which is created by the Kubernetes agent, uses quite some resources which grows over time. See attached screenshot.
![image](https://user-images.githubusercontent.com/4273556/104746448-97751e00-574f-11eb-8d25-a25d9346dde1.png)

Note: I’m talking about the job created by the prefect agent. The actual job executing code is only using 188MiB.

It seems like there is a possible memory leak in either Prefect or Dask. Is there a better alternative to deploy this? Which uses less resources? 

## Expected Behavior

Well first of all, I wouldn't expect this high memory usage. But most of all, not that it seems to be growing indefinitely. In this instance, the flow wasn't killed (yet) by Kubernetes due high memory usage, but that is something I was running into. 

## Reproduction

Reproduction is bit tricky as this flow is generated from a config file on running the script. I think I got all the relevant bits below:

```python
executor = DaskExecutor(cluster_kwargs={"n_workers": 6, "threads_per_worker": 1, "memory_limit": "1GB"})
schedule = CronSchedule(cron, start_date=datetime.utcnow())
handler = slack_notifier(only_states=[state.Failed])
storage_gcr = Docker(
    base_image="prefecthq/prefect:0.14.1-python3.8",
    registry_url="...",
    python_dependencies=["pandas"],
)
with Flow(
    f"CloudSQL to BigQuery ({cron})",
    storage=storage,
    executor=executor,
    schedule=schedule,
    run_config=KubernetesRun(
        # prefect_job_template contains a job spec describing resource limits, secrets, nodeselector..
        job_template=prefect_job_template
    ),
) as flow:
    # Class with @resource_manager which spawns off a pod and service to run CloudSQL Proxy
    with CloudSQLProxyManager(...) as service_name:
        # Job which calls RunNamespacedJob.run() on run
        job = CreateSyncJob(
            job_spec_template,
            state_handlers=[cleanup_on_failure, handler],
        )
        # Link the dependency of task to the CloudSQLProxyManager
        task = job(service_name)
```

Visualizing one of the flows show:
![image](https://user-images.githubusercontent.com/4273556/104746857-1cf8ce00-5750-11eb-8352-98556d66a22f.png)

## Environment

Running Prefect Server 0.14.0 on Kubernetes 1.18.x in Google Cloud.

_Originally reported on slack: https://prefect-community.slack.com/archives/CL09KU1K7/p1610706804087800_

**Comment by jcrist** [comment]
I think dask and kubernetes are unlikely to be the culprits here, rather I suspect your `CreateSyncJob` (or the `RunNamespacedJob`) task accumulates memory over time. Since these tasks are mostly IO bound, you might try running with a `LocalDaskExecutor` instead to eliminate `dask.distributed` from consideration.

```python
# Swapping out executor for this should do it
executor = LocalDaskExecutor(num_workers=6)
```

**Comment by joelluijmes** [comment]
I just tried it with the `LocalDaskExecutor`, and the initial results are much more promising. Although the job is only running for 10 minutes so far, the memory usage is much lower and actually constant.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4273556/104822362-2e220780-5842-11eb-9afc-d85d9d85bd84.png">

Here is another screenshot of flow which used DaskExecutor which ran for many hours until it finally was OOMKilled:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4273556/104822404-72ada300-5842-11eb-972c-809524da0a94.png">

So it does seem something may be off with dask?

--

Anyhow for reference here is my implementation of the `CreateSyncJob`. It takes in a templated Kubernetes job spec, which is filled in at `template_job_spec` (i.e. setting name of the job, environment variables etc), and then calls `RunNamespacedJob`. 

```python
class CreateSyncJob(Task):
    """
    Task which runs Kubernetes job which sync database from CloudSQL to BigQuery.

    Args:
      - job_spec_template (str): content of sql_to_bigquery.job.yaml.
      - spec (pd.Series): row of parse_specs_to_pandas containing sync variables.
    """

    def __init__(self, job_spec_template, spec, **kwargs):
        """
        Task which runs Kubernetes job which sync database from CloudSQL to BigQuery.

        Args:
        - job_spec_template (str): content of sql_to_bigquery.job.yaml.
        - spec (pd.Series): row of parse_specs_to_pandas containing sync variables.
        """
        self.job_spec_template = job_spec_template
        self.spec = spec

        super().__init__(
            name=spec["sourceDatabase"],
            **kwargs,
        )

    def run(self, cloudsql_name: Task):
        """
        Templates the job spec and creates the Kubernetes job using Prefect's RunNamespacedJob.

        Args:
          - cloudsql_name (Task): output of the CloudSQLProxyManager (or generate_cloudsql_name).
        """
        job_spec = template_job_spec(cloudsql_name, self.job_spec_template, self.spec)
        self.logger.info(f"Templated job_spec for {self.name}")
        self.logger.debug(job_spec)

        RunNamespacedJob(job_spec, namespace="prefect", kubernetes_api_key_secret=None).run()

```

Is there any benefit for using the DaskExecutor? Otherwise I'm fine with using the LocalDaskExecutor, which uses a ThreadPool instead of dask right?
if you need more information to diagnose this, I'm willing to research it 👍

**Comment by jcrist** [comment]
Hmmm, that's interesting. I'd still be surprised if this is a bug in dask. A larger reproducible example I could run locally would definitely help. If you drop the `with CloudSQLProxyManager` bit and only run some dummy jobs (say a long sleep task) are you still able to reproduce the issue? If so, that'd help me for debugging locally.

> Is there any benefit for using the DaskExecutor? Otherwise I'm fine with using the LocalDaskExecutor, which uses a ThreadPool instead of dask right?

For your flow above, I'd expect using a `LocalDaskExecutor` with threads to be sufficient. The tasks you're running are IO bound (so will run fine in threads), and *should be* low in memory usage. See https://docs.prefect.io/orchestration/flow_config/executors.html#choosing-an-executor for our docs on selecting an executor to use.

**Comment by novotl** [comment]
👋 We have a similar setup, running Prefect in Kubernetes and using DaskExecutor for our flow with 8 workers. All workers are eating more and more memory until all of them OOM. After a bit of trial and error, we added these env vars to Dask workers yaml, which slows down the leak considerably. Credits to https://stackoverflow.com/questions/63680134/growing-memory-usage-leak-in-dask-distributed-profiler/63680548#63680548
```
DASK_DISTRIBUTED__WORKER__PROFILE__INTERVAL=10000ms 
DASK_DISTRIBUTED__WORKER__PROFILE__CYCLE=1000000ms
```
Other related links:
- https://github.com/dask/distributed/issues/4091
- https://github.com/PrefectHQ/prefect/issues/3238

**Comment by charalamm** [comment]
When we use the flow without the `KubernetesRun` the flow gets completed

**Comment by cicdw** [comment]
Hi @charalamm - Prefect 1.x is no longer under active development; please upgrade to 2.x or 3.x.

**Comment by charalamm** [comment]
@cicdw Thanks for you response. Is this problem though a known problem with prefect 1.x and is there any known solution?
