### ISSUE TITLE
Cannot use apply_map in a ResourceManager context

### ISSUE THREAD

**Issue by JulianGoede** [PrefectHQ/prefect#3973]
## Description

Prefect version 0.14.2 introduced a bugfix #3920 which disallows the use of apply_map
within a ResourceManager context. We heavily rely on both ResourceManager and apply_map, e.g. we want to 
scale a presto/trino cluster using the setup/cleanup of the ResourceManager, and add tasks to the flow using apply_map.

## Expected Behavior

The following unittest must passed with latest prefect versions.
```
import pytest
from prefect import Flow, apply_map, task
from prefect.tasks.core.resource_manager import resource_manager


@resource_manager
class DummyResource:

    def cleanup(self, resource):
        pass


@task
def adder(x):
    return x + 1


def func(x):
    return adder(x)


@pytest.mark.parametrize("inputs, expected", [
    ([1], [2]),
    ([2, 3], [3, 4])
])
def test_apply_map_within_resource_manager(inputs, expected):
    with Flow(name='test') as flow:
        with DummyResource():
            y = task(fn=lambda x: x)(inputs)
            result = apply_map(func, y)
    assert flow.run().result[result].result == expected

```

## Reproduction

Test passes with prefect version 0.14.1. Test fails with exception `ValueError: Multiple flows cannot be used with the same resource block` with prefect version 0.14.2 and 0.14.3.

## Environment

Unittest works with
`pip install prefect==0.14.1`

Flow doesn't work with
`pip install prefect==0.14.2` or
`pip install prefect==0.14.3`

**Comment by jcrist** [comment]
Thanks for the excellent issue report, this is fixed in #3975.
