### ISSUE TITLE
GCSUpload task marks "Success" when trying to upload a non-string or byte type but does not upload anything

### ISSUE THREAD

**Issue by LoicEm** [PrefectHQ/prefect#3974]
## Description

Per the title,  a [prefect.tasks.gcp.storage.GCSUpload](https://docs.prefect.io/api/latest/tasks/gcp.html#gcsupload), when given a non string type to save, still marks "Success" without uploading anything.

## Expected Behavior

The documentation states that the data accepted must be either string or bytes.
I'd expect trying to feed another type of data should raise an error.

## Reproduction
I was able to reproduce the bug with this snippet of code:

```python
import prefect
from prefect.tasks.gcp.storage import GCSUpload
from prefect.run_configs import  LocalRun
from prefect.storage import Local

results_upload = GCSUpload(bucket="{your-bucket-here}")

run_config = LocalRun()
storage = Local()


with prefect.Flow("minimal_reproducible_example",
                  run_config=run_config,
                  storage=storage) as flow:
    results_upload("[1, 2, 3]", blob="test_file_str.txt")

    results_upload([1, 2, 3], blob="test_file_list.txt")

    results_upload({1: "2", 3: "4"}, blob="test_file_dict.txt")

flow.run()
```

With this run, only the "test_file_str.txt" appears, while all tasks are marked as success.

## Environment

I have set my GOOGLE_APPLICATION_CREDENTIALS to a path containing the needed service account key.

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by joshmeek** [comment]
Thanks for raising @LoicEm in the code for GCSUpload it looks like the if/else chain for checking the type of the data needs an `else` block that raises a ValueError if the type does not match either string or bytes. Would you like to make this change? 🙂

**Comment by LoicEm** [comment]
Created a PR #3978 ! First contribution to open source, your feedback is more than welcome :)
