### ISSUE TITLE
Docker storage defaults are broken on CircleCI

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#3987]
## Description

When building docker storage on CircleCI using a remote host, the default values in the Docker storage class cause errors and have to be updated to point to some defaults pulled from the docker client.

## Expected Behavior

Docker storage builds without error in any docker environment (within reason)

## Reproduction

Use `flow.storage = Docker(); flow.register()` in CircleCI with a remote docker host setup.

## Workaround/fix

```python
def DockerCircleCI(**kwargs):
    import docker

    default_client = docker.from_env()

    # This will break local builds / is only needed for remote docker hosts
    if default_client.api.base_url != "http+docker://localhost":
        kwargs.setdefault("base_url", default_client.api.base_url)

    kwargs.setdefault("tls_config", docker.TLSConfig(default_client.api.cert))

    return Docker(**kwargs)
```

**Comment by TylerWanner** [comment]
Can we ship this workaround into the Docker storage class or would it be breaking? @madkinsz
