### ISSUE TITLE
Support iframe on artifacts

### ISSUE THREAD

**Issue by ericholiveira** [PrefectHQ/prefect#4033]
## Current behavior
Would be really amazing to be able to add an iframe in the artifacts. I've tried to add it on a markdown artifact but it doenst work

## Proposed behavior
The markdown artifact could support iframe, or we can create a new artifact type for iframes

## Example
Currently we can create a link artifact and navigate to another window to see the results, if we have an iframe artifact this could be better...
For our use case, we use prefect to run jobs on databricks, currently we generate a link artifact to go to databricks to see the job result, and this means that the user seeing the result must click on the link, go to another page, put their databricks credentials and see the result... If we had a iframe artifact, we could host the html with the result in our infrastructure and put an iframe to see the results

**Comment by eiko4** [comment]
Unlock please. Iframe support
