### ISSUE TITLE
Some CLI commands do not work if the server is running on a non-default port

### ISSUE THREAD

**Issue by sm-Fifteen** [PrefectHQ/prefect#4049]
## Description
A number of prefect components behave in usual ways if the local core server isn't running on `localhost:4200`. Aside from the UI not being configured automatically, this is a problem for all the CLI commands that do not let you set an API address, such as `prefect server create-tenant` and `prefect register flow`. 

## Expected Behavior
I would assume `prefect backend` would let you specify a port that other commands are expected to use to connect to the local prefect server instead of only the default 4200, or at least that the base `prefect` command would have a global `--api` option that applies to all sub-commands. At any rate it's rather strange that `prefect server start` even lets you set a different port as a CLI option in the first place if the official server management tools have no way to be informed of what port to use.

## Reproduction

In one window, start the server using a non-standard port configuration.
```
prefect server start --ui-port=8888 --server-port=8080
```

In another window, try running a command that needs to communicate with the server.
```
`prefect server create-tenant --name default --slug default`
```

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Windows-10-10.0.17134-SP0",
    "prefect_backend": "server",
    "prefect_version": "0.14.5",
    "python_version": "3.8.2"
  }
}
```

**Comment by joshmeek** [comment]
@sm-Fifteen after you run `prefect backend server` you can set the host of your api by setting the config via:

```
[server]
host = "http://localhost"
port = "4200"
endpoint = "${server.host}:${server.port}"
```

or through the environment variable `PREFECT__SERVER__ENDPOINT=your_host:port`

**Comment by sm-Fifteen** [comment]
> @sm-Fifteen after you run `prefect backend server` you can set the endpoint of your server api by setting the config [...]

I'm assuming you mean in `~/.prefect/backend.toml`, the file created by `prefect backend server`? That seems to work, so it at least solves by issue, though it would still be convenient if `prefect backend` could take parameters to let it fill out that part of the configuration automatically.

It would also make it easy to [introduce early on in the core "Getting started" tutorial](https://docs.prefect.io/core/getting_started/installation.html#running-the-local-server-and-ui) rather than [relegating it to the orchestration FAQ](https://docs.prefect.io/orchestration/faq/config.html#connecting-to-a-different-api-endpoint) where that part of the configuration seems to currently be documented.

> Before running the server for the first time, run `prefect backend server`
>  
> This configures Prefect for local orchestration, and saves the configuration in your local ~/.prefect directory.
> 
> **If the server is not running on `localhost:4200` or if the server and the agent are on different machines, use `prefect backend server --host=10.0.0.10 --port=1234` so the agent and CLI client know how to communicate with it.**

**Comment by steph-ben** [comment]
If I understand well, the following PR https://github.com/PrefectHQ/prefect/pull/4081 might help.
Currently it can only configure the server host :

> prefect backend http://my-beautiful-prefect-server

**Comment by mwheeler01** [comment]
I'd like to echo the point that @sm-Fifteen made [in his mention](https://github.com/PrefectHQ/prefect/issues/4388#issuecomment-819709751). In fact, Prefect's `Client` class is hard-coded to look at the Cloud configuration for the server's URL, even if the command `prefect backend server` is run:

```
class Client:
    """
    Client for communication with Prefect Cloud  # <-- only?
    …
    """
    def __init__(self, api_server: str = None, api_token: str = None):
        self._access_token = None
        self._refresh_token = None
        self._access_token_expires_at = pendulum.now()
        self._active_tenant_id = None
        self._attached_headers = {}  # type: Dict[str, str]
        self.logger = create_diagnostic_logger("Diagnostics")

        # store api server
        self.api_server = api_server or prefect.context.config.cloud.get("graphql")  # <-- Problem code

        self._api_token = api_token or prefect.context.config.cloud.get(
            "auth_token", None
        )

        # Initialize the tenant and api token if not yet set
        if not self._api_token and prefect.config.backend == "cloud":
            self._init_tenant()
```

This became a problem for me when I tried to run `prefect server create-tenant` with the environment variable `PREFECT__SERVER__GRAPHQL__HOST` set to point to a hostname other than `localhost`. I'm more than happy to open a PR to fix this particular problem.

**Comment by madkinsz** [comment]
Hey @mwheeler01, I'd be happy to review a PR that addresses that.
