### ISSUE TITLE
DockerAgent on Prefect Server tries to pull secrets from API

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#4051]
## Description

If a secret is not available in the context the API is queried for the secret (when the backend is `cloud`) or an error is raised (when the backend is `server`). The configured backend is not passed from the agent environment into the docker container so a confusing graphql error is raised instead of the nicer 'Local secret not found' when you're using the `server` backend.

```python
# secrets.py
        try:
            value = secrets[self.name]
        except KeyError:
           # This is the code path we want to hit
            if prefect.config.backend != "cloud":
                raise ValueError(
                    'Local Secret "{}" was not found.'.format(self.name)
                ) from None
           # Query the API...
```

## Expected Behavior

The backend is passed through to the container so the helpful error is raised

## Reproduction

A `DockerRun` flow with a secret that is not passed to the agent environment explicitly

**Comment by steph-ben** [comment]
Meanwhile, how do you pass secret to agent explicitely ?
I tried :
```
$ cat ~/.prefect/config.toml
[context.secrets]
GITHUB_ACCESS_TOKEN = "xxx"

$ export PREFECT__CONTEXT__SECRETS__GITHUB_ACCESS_TOKEN=xxx
```

But none if this work, I still got the following error when my flow is launched:

```
[2021-02-03 16:52:19,221] DEBUG - agent | Docker container 3ab5279ffdd442a861d732f61d54f2a4090373f7728fdc4d6daa8bc788617468 started
[2021-02-03 16:52:19,305] DEBUG - agent | Completed flow run submission (id: 19b1eaad-fbd0-4cbf-b0f2-ffcbabc4c57d)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/client/secrets.py", line 137, in get
    value = secrets[self.name]
KeyError: 'GITHUB_ACCESS_TOKEN'
```

And then, the not-helpful error message that I guess you were mentionning :

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
400 Client Error: Bad Request for url: http://host.docker.internal:4200/graphql

The following error messages were provided by the GraphQL server:

    GRAPHQL_VALIDATION_FAILED: Cannot query field "secret_value" on type "Query".

The GraphQL query was:

    query($name: String!) {
                secret_value(name: $name)
    }

The passed variables were:

    {"name": "GITHUB_ACCESS_TOKEN"}

...

**Comment by madkinsz** [comment]
Secrets can be passed to the agent by setting the environment variable at agent-startup e.g. `prefect agent local start --env PREFECT__CONTEXT__SECRETS__GITHUB_ACCESS_TOKEN=xxx` (https://docs.prefect.io/api/latest/cli/agent.html) or in the `env` setting of a `RunConfig` (https://docs.prefect.io/orchestration/flow_config/run_configs.html)
