### ISSUE TITLE
unmapped fails in apply_map 

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#4054]
Hi - Below is a flow using `apply_map` that fails when a `task` is `unmapped`.  In the diagram below `sum_negate` is `unmapped`.  But that is not reflected in the visualization.
![image](https://user-images.githubusercontent.com/16763201/106679661-c6c6c000-6582-11eb-87c0-de0811d84e84.png)

### Failed Flow
![image](https://user-images.githubusercontent.com/16763201/106679450-4e5fff00-6582-11eb-9818-b929c5ed245d.png)

### Reproduce
```
from prefect import Flow, task, case, apply_map, Parameter, unmapped
from prefect.tasks.control_flow import merge

from prefect import Flow, task, case, apply_map
from prefect.tasks.control_flow import merge

@task
def inc(x):
    return x + 1

@task
def negate(x):
    return -x

@task
def is_even(x):
    return x % 2 == 0

@task
def sum_negate(negate_lst):
    summed = sum(negate_lst)
    print(summed)
    return summed

def inc_or_negate(x):
    cond = is_even(x)
    # If x is even, increment it
    with case(cond, True):
        res1 = inc(x)
    # If x is odd, negate it
    with case(cond, False):
        res2 = negate(x)
        summed = sum_negate(unmapped(res2))
    return merge(res1, summed)

with Flow("apply-map example") as flow:
    result = apply_map(inc_or_negate, range(4))
```
`prefect 0.14.5`

**Comment by jcrist** [comment]
It's hard to understand what you expect here, but I think this comes from a misunderstanding about how `apply_map` works.

The function you're mapping over must construct a valid flow on its own with the arguments as provided. Arguments to `apply_map` should be treated as mapped elements within the mapped function unless they're wrapped with `unmapped` before passing to `apply_map`:

```python
x = range(4)
apply_map(func, x)   # in `func`, `x` should be treated as as scalar
apply_map(func, unmapped(x))    # in `func`, `x` should be treated as an iterable
```

In your case, taking `inc_or_negate` on its own doesn't produce a valid flow (you're passing a scalar to something that expects an iterable). The error that prefect provides to you makes sense in this case (`TypeError: 'int' object is not iterable`), so I'm not sure what more we could do here.

Pulling your `inc_or_negate` function out into some top-level python code may make this more apparent:

```python
x = 1  # an example scalar, as passed in from `apply_map`

cond = is_even(x)  # a scalar bool

with case(cond, True):
    res1 = inc(x)    # a scalar int
with case(cond, False):
    res2 = negate(x)    # a scalar int
    unmapped_res2 = unmapped(res2)   # unmapped(scalar) is just a scalar
    summed = sum_negate(unmapped_res2)   # you're passing an int to `sum_negate` here, which will error
return merge(res1, summed)
```

This is not a bug in prefect, but a bug in your code. If you explain what you'd want the above to do we map be able to help you fix it. I'm not sure if there's any improvements we could make to docs or errors that would make this clearer.

**Comment by gryBox** [comment]
Hi - The expected behavior is that the result of `task` `negate` is passed an iterable to `sum_negate` ... because it is wrapped with `unmapped`.  However it looks like that is expected behavior from your explanation.  

> unless they're wrapped with unmapped **before** passing to apply_map:

It would be helpful to allow for unmapped task in `apply_map`.  In my case I have mapped case statement where one of the intermediary results needs to be reduced before continuing on.  Any thoughts on this?

**Comment by jcrist** [comment]
> The expected behavior is that the result of task negate is passed an iterable to sum_negate ... because it is wrapped with unmapped. However it looks like that is expected behavior from your explanation.

Yeah, don't think about the things passed around within a `apply_map` call as iterables (unless they were wrapped with `unmapped` before passing them to `apply_map`), think of them as scalars. We're unlikely to change this.

 It might help to think of `apply_map` as calling a separate "sub-flow" with a set of input parameters. The "sub-flow" can't (and doesn't) know about any possible parallel executions that are occurring, it only knows about the tasks in the sub-flow itself. `apply_map` is similar to mapping a `StartFlowRun` call, except all tasks run within the same flow.

> It would be helpful to allow for unmapped task in apply_map.

You can use `unmapped` in `apply_map`, but it's meaningless. You're not wrapping a list of values with `unmapped`, you're wrapping a single scalar value. `unmapped(1) == 1`.

>  In my case I have mapped case statement where one of the intermediary results needs to be reduced before continuing on. Any thoughts on this?

You should break this into two calls. You can't do a reduction within an `apply_map` call (it's a map, not a reduce).

I believe the following does what you wanted for the above example:

```python
from prefect import Flow, task, case, apply_map, Parameter, unmapped
from prefect.tasks.control_flow import merge

from prefect import Flow, task, case, apply_map
from prefect.tasks.control_flow import merge

@task
def inc(x):
    return x + 1

@task
def negate(x):
    return -x

@task
def is_even(x):
    return x % 2 == 0

@task
def my_sum(negate_lst):
    return sum(negate_lst)


def inc_or_negate(x):
    cond = is_even(x)
    # If x is even, increment it
    with case(cond, True):
        res1 = inc(x)
    # If x is odd, negate it
    with case(cond, False):
        res2 = negate(x)
    return res1, merge(res2, 0)


with Flow("apply-map example") as flow:
    res1, res2 = apply_map(inc_or_negate, range(4))
    summed = my_sum(res2)
    res3 = merge(res1, unmapped(summed), mapped=True)


state = flow.run()
```

![example](https://user-images.githubusercontent.com/2783717/106807279-94729c80-662e-11eb-912a-a8e1013ebbb7.png)

**Comment by gryBox** [comment]
@jcrist Nice.  Thanks for showing an alternative!
