### ISSUE TITLE
Relax the requirements on importlib_resources

### ISSUE THREAD

**Issue by felipemontefuscolo** [PrefectHQ/prefect#4065]
Hi team,

I've been trying Prefect in my personal environment and it looks great. I'd like to bring it to my company, but I have a requirement issue on the way:

### Current

Prefect has the following requirement:

`importlib_resources >= 3.0.0; python_version < '3.9'`

In my company's Python environment we use Python 3.7 and we can't install `importlib_resources`.

### Proposed

Can we relax the requirement of the Python version from 3.9 to 3.7?
```
- importlib_resources >= 3.0.0; python_version < '3.9'
+ importlib_resources >= 3.0.0; python_version < '3.7'
```

It seems that the only use of `importlib_resources` in this Prefect codebase is:
https://github.com/PrefectHQ/prefect/blob/a66e2a8ea923cc5af250e519db3a01128b0e5a88/src/prefect/tasks/aws/client_waiter.py#L3-L6
....
https://github.com/PrefectHQ/prefect/blob/a66e2a8ea923cc5af250e519db3a01128b0e5a88/src/prefect/tasks/aws/client_waiter.py#L128-L130

The `.open_text` functionality is already present in the standard lib `importlib.resources` for Python 3.7, is there any reason we can't use it?

Thanks.

**Comment by jcrist** [comment]
Good catch, thanks for opening the issue. Should be fixed by #4074.
