### ISSUE TITLE
Flow parameters should accept a type argument

### ISSUE THREAD

**Issue by Verun** [PrefectHQ/prefect#4080]
## Current behavior

Currently Prefect flow parameters do not allow specifying a flow parameter type, but this feature can be useful for some types of flow parameters passed in via the Prefect Server UI or through the command line. 

## Proposed behavior

Ideally one would be able to pass in a type argument, similar to the way argument parsers built with Python's argparse module support specifying the type: https://docs.python.org/3/library/argparse.html#type

## Example

Sometimes, we need the parameter to be an int, or a Path object instead of just a string.

**Comment by jcrist** [comment]
Hi Verun, thanks for the issue report! This is definitely something we want to do. 

Since there's already an open issue for typed parameters (#2254), I'm going to close this issue as a duplicate - you can subscribe to that issue if you want to see updates when they happen. Thanks!
