### ISSUE TITLE
Document how to deploy a Prefect Docker Agent in a docker container

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#4088]
I believe this works already (if not, we should make it work). It would be good to document how to deploy in this manner so users using docker for all deployments don't have to special case deploying the docker agent.

**Comment by Samreay** [comment]
One thing that would be *super* useful in this vein would be a docker-compose file ready to go that deploys both the prefect core services, but a prefect DockerAgent as well, so that this cmopose could be integrated into an existing swarm with minimal changes :)

**Comment by Trymzet** [comment]
Was researching this and [this](https://github.com/PrefectHQ/prefect/issues/3064) issue seems to be helpful.

**Comment by madkinsz** [comment]
Note that you can use `prefect server config` to get a docker-compose file that can easily be extended to add a docker agent -- I agree we should do this for you though eventually.
