### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by AndrewHannigan** [PrefectHQ/prefect#4117]
Hello!

I've found an issue here:`USER`

Should be TENANT

Page reference: https://docs.prefect.io/api/latest/client/client.html

**Comment by joshmeek** [comment]
Hi @AndrewHannigan what part of the docs are you referencing? If you're talking about the `api_token` argument that can be passed into the Client then that docstring is correct. A `USER` token can be provided and then the various tenants that that user has access to can be logged in to through the `login_to_tenant` route. A `TENANT` token is scoped to a single tenant.
