### ISSUE TITLE
Upstream tasks should not run if downstream is already cached?

### ISSUE THREAD

**Issue by ravwojdyla** [PrefectHQ/prefect#4123]
## Description

Code:

```python
import prefect
from prefect import Flow, task
from prefect.engine.results import LocalResult

@task
def bar():
    return 43

@task(target="foo.txt", checkpoint=True, result=LocalResult(dir="~/.prefect"))
def foo(bar):
    return bar

with Flow("foo") as flow:
    result = foo(bar)
```

After `foo` gets cached, `bar` should not be rerun in that case? Or at least that would be my expectation as a user. Tested on server prefect==0.14.7, `foo` uses cached result, but `bar` still gets run. I understand why Prefect might do that here, but it also arguable doesn't make sense from the user perspective.

## Expected Behavior
Upstream tasks should not run if downstream is already cached.

## Environment

```
{
  "config_overrides": {
    "cloud": {
      "agent": {
        "auth_token": true
      }
    },
    "server": {
      "telemetry": {
        "enabled": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.16-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.14.7",
    "python_version": "3.8.6"
  }
}
```

**Comment by joshmeek** [comment]
Hey @ravwojdyla this is an intentional behavior. Since you are not opting in to having the `bar` task cache its result then it will always rerun. Caching is opt-in by default and the engine doesn't want to make any assumptions of what should be cached based on other tasks. For example your `bar` task might perform some other computation besides returning 43 that you would still expect to happen on a rerun if not explicitly caching the result.

**Comment by ravwojdyla** [comment]
@joshmeek I understand that, and that might be a limitation in Prefect (or an artefact of the design), but assuming best practice standard data flow model, `bar` should be idempotent and just produce one piece of data consumed only by the downstream task. Otherwise as a user I would need to add caching to all tasks if one of the tasks in the flow has cache enabled?

**Comment by ravwojdyla** [comment]
Afaiu an example of an issue that might be hard to implement with the assumption above, is for example a canonical ETL that outputs date partitioned data. Let's call that pipeline `Foo`, and say it has 3 tasks: {extract, transform, load}, in this case only `load` produces data that is "cached" to the global "catalog", `extract` and `transform` uses local caching. And let's say I have a another developer working on a downstream pipeline (meaning it consumes results from `Foo` via `StartFlowRun`), say then depend on the Result of `load` for a particular date that is in the catalog already, in the case above they would still need to run the `extract` and `transform` right? Is there a mechanism in Prefect to easily handle this case?

I guess one idea that comes to my mind is marking all the tasks in `Foo` with the same exact caching spec with custom `Result` type, that is actually only materialising data on the `load` task and implicit local caching for the intermediate tasks. But this smells, and is hacky for such a idiomatic use case. Am I missing something?
