### ISSUE TITLE
KubernetesAgent overrides the 'image' and 'args' implied by 'job_template' in KubernetesRun

### ISSUE THREAD

**Issue by jameslamb** [PrefectHQ/prefect#4128]
## Description

I'm running a `KubernetesAgent` to run flows with the following configuration:

* `prefect` version for agent: 0.14.6
* `prefect` version for flow: 0.14.8
* storage: `Webhook`
* run config: `KubernetesRun`

I'm creating the run config object by passing in a dictionary describing a `k8s` job

```python
KubernetesRun(
    job_template=some_job_spec
)
```

## Expected Behavior

I expected that when a flow run was kicked off, the agent would create a single k8s job whose first container had the `image`, `command`, and `args` specified in the spec that I passed into the  `job_template` argument to `KubernetesRun`'s constructor:

```yaml
containers:
- command:
  - "/bin/bash"
  - "-ec"
  args:
  - |
    source some_setup_script.sh
    prefect execute flow-run
  image: my-custom-image:12345
```

Instead, the `image` on my flow run job is set to `prefecthq/prefect:0.14.8` and the `args` are overridden to just `prefect execute flow-run`.

## Reproduction

It's tough to provide a clean reproducible example given that a KubernetesAgent is involved, but I think I can get close. I can see exactly where the issue is happening.

* overriding `image` regardless of the content of `job_template`: https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/agent/kubernetes/agent.py#L571
    - `get_flow_image()` looks at the `image` property of the run config, but not in its template: https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/utilities/agent.py#L36-L37
* overriding `args` regardless of the content of `job_template`: https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/agent/kubernetes/agent.py#L574
    - `get_flow_run_command()` has no knowledge of k8s stuff at all and just returns the prefect CLI command to run the flow: https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/utilities/agent.py#L36-L37

I think I'm looking in the right place, because when I changed my run config definition like this:

```python
KubernetesRun(
    job_template=some_job_spec,
    image="my-custom-image:12345"
)
```

the first container in the job got that image I passed in.

## Environment

* `prefect` version for the flow: 0.14.8
* `prefect` version for the agent: 0.14.6
    - NOTE: I'm using a very very thin wrapper around `KubernetesAgent`, instrumented with some my-company-specific stuff. Based on the links I provided in `## Reproduction` above, I'm pretty confident that the fact that I'm using this other wrapper agent is not related. 
* I've observed this behavior using k8s `v1.16.15` in microk8s `v1.16.15` running on Ubuntu 18.04

## Notes for Reviewers

If you're open to the idea, I'd be happy to submit a pull request that changes https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/agent/kubernetes/agent.py#L570-L574 to respect values provided already in the RunConfig's template, like this:

```python
# treating "" as a special type of "None", since this is the documented
# default in https://docs.prefect.io/orchestration/execution/k8s_job_environment.html#job-spec-configuration
image_from_spec = container.get("image", None)
if image_from_spec is None or image_from_spec == "":
    container["image"] = image = get_flow_image(flow_run)

# treating [] as a special type of "None", since this is the documented
# default in https://docs.prefect.io/orchestration/execution/k8s_job_environment.html#job-spec-configuration
args_from_spec = container.get("args", None)
if args_from_spec is None or args_from_spec == []:
    container["args"] = [get_flow_run_command(flow_run)]
```

Thanks for your time and consideration!

**Comment by jcrist** [comment]
Thanks for the issue @jameslamb. Overriding of `args` and `image` is intentional (although we could revisit that decision on `image`). The exact command for running a flow in prefect isn't something we want users to have to mess with, and we also may change the command over time (so keeping the args in the container "private" is preferred). As such, I'm pretty against letting users override `args` here (we don't support this for other agents either). If your goal is to add a script on startup, you could add that as part of the image's entrypoint (or set the `cmd` in the job template), neither of which are overridden, and are the intended place for adding some setup steps. We currently do this as part of the provided prefect images, but you're free to extend or override this any way you want: https://github.com/PrefectHQ/prefect/blob/559330bb549b9c92c413948b615509b6c6d33620/Dockerfile#L35.

For `image`, we initially went with always setting it (matching the previous behavior). I could see a case for using the default value in the template if the image isn't provided via `Docker` storage or as part of the run config though, and would accept that change. Either way, we should better document this behavior.

Thoughts?

**Comment by jameslamb** [comment]
Thanks for the detailed comments!

**images**

> the image isn't provided via Docker storage or as part of the run config though

I thought of everything in the `job_template` I provided to `KubernetesRun`, including the `image` in the first container, as "part of the run config". I didn't understand that the other keyword arguments like `image` would take precedence over values in that template.

I think it would make sense to figure out the image for ` KubernetesRun` job based on the first matching item in this list

1. image on storage if using `Docker` storage
2. `run_config.image`  (value that was passed to `image=` keyword in `KubernetesRun`)
3. image in the first container in the spec provided by `job_template` / `job_template_path`

I think that's what you're saying above too, just restated it to be sure we're talking about the same thing. I'd be happy to submit a pull request that makes that change and adds language about it in the docs.

**args**

I totally understand why you'd be cautious about letting people mess with `args`. Let me explain a bit why the "add an entrypoint to the image" is not ideal for my use case.

I'm working on an integration (at Saturn Cloud) where users bring any image they want, and separately are able to specify a shell script with commands that run every time a pod for a resource like a Dask cluster, JupyterLab instance, or a prefect flow run starts. People do things in there like `apt-get install` packages or clone git repos. The contract is "as long as this is valid code that can be run with `bash`, we will just run this shell script for you inside the container at startup". This is just like how like the experience with [EC2 user data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) on AWS. If I changed the mechanism for running this to "every image you bring has to have this entrypoint defined that runs this script in this standard place", it would introduce some friction into the process.

In `prefect` 0.13.x world, with `KubernetesJobEnvironment`, I could hack around this in a client library by taking advantage of the fact that setting `args` happened at build time, not run time. I know this is a hack and that I was accessing stuff you consider private, so I'm not saying "wow you broke this in prefect 0.14.x ugh".

* https://github.com/PrefectHQ/prefect/pull/2950
* (this is bad, don't stare directly at it haha): https://github.com/saturncloud/prefect-saturn/blob/2fb73e0972fac4a7aeee67724f8e1e0cc5f982ae/prefect_saturn/core.py#L357-L368

But using `KubernetesRun`, that isn't possible because setting up `args` happens in `generate_job_spec_from_run_config()` , at run time https://github.com/PrefectHQ/prefect/blob/24ce11873005c4e6f4f4853b2ec3b107aef05039/src/prefect/agent/kubernetes/agent.py#L493.

All that said, I understand that my requested change for `args` might be open up the risk of other issues, so I'm ok with handling my use case in a custom extension of `KubernetesAgent`.

thanks for hearing me out!

**Comment by wreis** [comment]
hey @jameslamb  I actually don't think you need to modify `args` in template OR add `ENTRYPOINT` inside the image to achieve what you want...

> If your goal is to add a script on startup, you could add that as part of the image's entrypoint (or set the cmd in the job template), neither of which are overridden, and are the intended place for adding some setup steps.

you could set the `command` in job template since it is guaranteed to not be overriden by Prefect, something like:

```
containers:
- command:
  - "dumb-init"
  - "--"
  - "some_setup_script.sh"
```

then in `some_setup_script.sh` you would be able to handle the args provided to invoke prefect cmd (`prefect execute flow-run`).
