### ISSUE TITLE
Feature Request: MS Teams Cloud Webhook

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect#4129]
## Current behavior

Currently there is no support for MS Teams.

## Proposed behavior

We are using MS Teams for our internal communication and it would be nice to use the [Cloud Hooks](https://docs.prefect.io/orchestration/concepts/cloud_hooks.html) feature of Prefect to notify about failed task / flows. 

On Teams side there could be an incoming webhook connector configured. For more details about the messaging format (json) I [link the offical docs](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using).

Maybe a given lib like [pymsteams](https://github.com/rveachkc/pymsteams) could be used.

## Example

I think this should be implemented in some way like the SLACK implementation.

**Comment by madkinsz** [comment]
Hi @sti0 

Heads up that we're tracking this request already in our internal repos. I started to implement this a while back but didn't see that we could use connector cards as webhooks, that looks a lot easier than the hoops you have to jump through to send messages as an application. 

No promises on a timeline but we'll continue to look into this.

**Comment by sti0** [comment]
We use this [incoming webhook connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook) for other projects and its a simple post request as mentioned in [this](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#post-a-message-to-the-webhook-using-curl) chapter.

**Comment by madkinsz** [comment]
This is implemented but I'll leave this issue open until the public release :)

**Comment by sti0** [comment]
@madkinsz is there any release date for this feature?

**Comment by madkinsz** [comment]
Hey @sti0 -- it's being bundled with some other features we're excited about so it is not available yet but there should be an announcement in the next few weeks or so.

**Comment by madkinsz** [comment]
Tracking issue for the UI feature https://github.com/PrefectHQ/ui/issues/700

**Comment by kst83** [comment]
Looking forward to this!

**Comment by tharwan** [comment]
Really looking forward to this, without it prefect server is not really usable for us, as there is now automatic notification of failed flows.

**Comment by madkinsz** [comment]
This should now be available in the 'Automations' on Cloud.

@tharwan We do not intend to release this for Server (global automation is Cloud-only), but you can do this with a state handler in Core https://docs.prefect.io/core/concepts/notifications.html#sending-a-simple-notification

**Comment by tharwan** [comment]
@madkinsz thanks for the info. I would really like to go cloud anyway, but I have a hard time to convince IT so far.
