### ISSUE TITLE
Redesign StartFlowRun to avoid costly separate flow runs

### ISSUE THREAD

**Issue by ravwojdyla** [PrefectHQ/prefect#4137]
## Current behavior
Assuming idiomatic data pipelines implemented as `A` and `B` flows. `B` depends on results from `A`, afaiu right now the best practice is for `B` to use `StartFlowRun` to kick of `A`, if `B` uses the data from `A`, it likely should use `StartFlowRun(..., wait=True)` otherwise the data might not be ready in `B` to use. When `wait=True`, this means there are 2 concurrent flow runs, afaiu this is costly in the Prefect deployment, specifically it would create a deadlock in the free Cloud Prefect. It's easy to imagine that there might be multiple levels of dependencies between flows, each level would create a separate flow run. Would it be possible to create a light version of `StartFlowRun` or design a better mechanism? What do you think? Also `StartFlowRun` related issues: #4124 , #4122.

**Comment by madkinsz** [comment]
Hi! I believe this may be alleviated by the removal of concurrency based pricing recently announced at https://medium.com/the-prefect-blog/liftoff-fe5a117a94ff#2649

**Comment by ravwojdyla** [comment]
👋 @madkinsz , I appreciate your prompt response! I am happy to see that it might be alleviated in the future via new pricing model. Just to be clear, would you agree that there is still value in exploring a better design for `StartFlowRun`? I am asking because in my subjective opinion, it's one of the core use cases of an orchestrator? wdyt?

**Comment by madkinsz** [comment]
We're definitely interested in improving the "flow of flows" and flow relationship patterns that our users have started exploring! The intent of `StartFlowRun` was to put a basic (but powerful) tool in the hands of our users while we determine the best path forward here. Flow to flow dependencies are going to be quite technically complex and we don't want to rush into a wrong solution.

As far as this specific issue is concerned, it seems like the separate flow run is only costly because of concurrency limiting which will be removed so I'm not sure this makes sense to leave open. I think your other issues better capture things that still need resolution. Did you have another "cost" in mind that we should be addressing?

**Comment by ravwojdyla** [comment]
> Flow to flow dependencies are going to be quite technically complex and we don't want to rush into a wrong solution.

@madkinsz definitely agree, and full disclosure: the current limitations (this + other reported issues) of `StartFlowRun` is one of the blockers for us to adapt Prefect. I understand that they can be worked-around, but I hope you understand that it's a bit of a red flag. And I totally understand that you might want to stick with the current "basic" solution for some time, which would also be a valuable information to have as a potential user.

> As far as this specific issue is concerned, it seems like the separate flow run is only costly because of concurrency limiting which will be removed so I'm not sure this makes sense to leave open. I think your other issues better capture things that still need resolution. Did you have another "cost" in mind that we should be addressing?

@madkinsz "concurrency limiting" is certainly a major part of the "cost" right now, but even without that limitation in place, in my use case (which I would argue is a canonical data pipeline orchestration), say I have a number of pipelines (flows), that depend on each other (with data being exchanged via global object store), in the current design `StartFlowRun` requires `wait=True`, which means there might be potentially many flows just idling (waiting for upstream to finish), which afaiu depending on the deployment setup might mean wasted resources on just waiting. On top of that, it's not easy to see those dependencies in the UI https://github.com/PrefectHQ/prefect/issues/4122, or access the data https://github.com/PrefectHQ/prefect/issues/4124. These two issues can probably be solved without major redesign of the `StartFlowRun`. Feel free to close this issue if you believe there is no value in it, but in that case what would be a good issue for me to track regarding redesign/improvement of the `StartFlowRun`?

**Comment by madkinsz** [comment]
I think you have a good point as far as wasted resources where flow jobs are started just to idle. I'll leave this open issue to track an improvement of that case. An improvement of the flow-flow orchestration experience is a high priority on our roadmap.

**Comment by ravwojdyla** [comment]
👋 @madkinsz, anything I could help with in regards to the context of this issue? I'm curious if you have any idea on the timeline of this issue? I'm not asking about concrete dates etc :), just curious if this is something you plan to tackle in the near future (next 6 months)?

**Comment by madkinsz** [comment]
Hey @ravwojdyla -- sorry I missed your message. The design of subflow results is being addressed in #4563.

Regarding
> which means there might be potentially many flows just idling (waiting for upstream to finish), which afaiu depending on the deployment setup might mean wasted agent resources on just waiting

I believe the solution to this is to not create your subflow until the upstream data is ready which can be setting an upstream dependency on your flow run creation task.

**Comment by peterroelants** [comment]
@madkinsz Will #4563 eventually lead to `StartFlowRun` being deprecated? On a first look it seems like `create_flow_run`, `get_task_run_result`, `wait_for_flow_run` are a replacement for `StartFlowRun`.

**Comment by madkinsz** [comment]
@peterroelants Yes I plan to deprecate `StartFlowRun` -- the interface is a little too hard to use and I'm hoping to provide a simpler and more powerful set of tasks.
