### ISSUE TITLE
--env option in Agent CLI cannot parse values with '='

### ISSUE THREAD

**Issue by afterthought** [PrefectHQ/prefect#4138]
https://github.com/PrefectHQ/prefect/blob/559330bb549b9c92c413948b615509b6c6d33620/src/prefect/cli/agent.py#L100

I'm trying to set a connection string via the --env option. I.e.

start --env CONN=Driver=foo;host=sername;user=myuser

.split("=", 2) returns an array with 3 values which breaks the dict. I believe the intent was to set the max param to 1 resulting in an array with 2 values.

**Comment by joshmeek** [comment]
Ah yeah this is going to happen when a value has a `=` in it. We should implement a different/separate way for allowing env vars without reserved characters. Going to mark this as a `bug`.

In the meantime you can also set env vars through the config with:

```
export PREFECT__CLOUD__AGENT__ENV_VARS__YOURVAR=something
```

or through the `~/.prefect/config.toml`

```
[cloud.agent.env_vars]
YOUR_VAR = "something"
```
