### ISSUE TITLE
Broken docker-compose.yml

### ISSUE THREAD

**Issue by VincentAntoine** [PrefectHQ/prefect#4140]
## Description
`prefect server start` fails since 0.14.7 release.

## Expected Behavior
Prefect UI starting.

## Observed behaviour
Execution fails with 

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.ui.depends_on contains an invalid type, it should be an array
services.apollo.depends_on contains an invalid type, it should be an array
services.towel.depends_on contains an invalid type, it should be an array
services.graphql.depends_on contains an invalid type, it should be an array
services.hasura.depends_on contains an invalid type, it should be an array
Exception caught; killing services (press ctrl-C to force)
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.ui.depends_on contains an invalid type, it should be an array
services.apollo.depends_on contains an invalid type, it should be an array
services.towel.depends_on contains an invalid type, it should be an array
services.graphql.depends_on contains an invalid type, it should be an array
services.hasura.depends_on contains an invalid type, it should be an array
Traceback (most recent call last):
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/prefect/cli/server.py", line 346, in start
    subprocess.check_call(
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincentchery/miniconda3/envs/prefect_test/bin/prefect", line 10, in <module>
    sys.exit(cli())
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/site-packages/prefect/cli/server.py", line 384, in start
    subprocess.check_output(
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/vincentchery/miniconda3/envs/prefect_test/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 1.
```

## Reproduction
* Install prefect >= 0.14.7
* run
```
prefect backend server
prefect server start
```

## Environment
* Ubuntu 20.04
* Fresh virtualenv with only prefect installed, versions 0.14.7+ fail, versions <0.14.7 work as expected.

## Solution
I tested prefect versions 0.14.0 to 0.14.9 and observed that the bug was introduced in release 0.14.7 in `src/prefect/cli/docker-compose.yml`. 

`depends_on` should be an array (starting by hyphen "-") as stated in the error logs produced when running `prefect server start`, and the `diff` shows that hyphens were removed from `depends_on` options in 0.14.7.

See for instance :
https://github.com/PrefectHQ/prefect/pull/4041/files#diff-110ca811f8b6466bd56ed8607c3a94de6925d89f71acedafd1ee71c166ab831dR54

--> Put hyphens back in `depends_on` options of the `docker-compose.yaml` :)

**Comment by NoamGit** [comment]
Had the same problem. Had to manually fix the `depends_on` in the `docker-compose.yml` file.
Also had to remove the `condition:...`

**Comment by madkinsz** [comment]
Hi! Thanks for the report. This is the same issue as https://github.com/PrefectHQ/prefect/issues/4135 and is resolved by upgrading your docker-compose version. Perhaps we should switch to the old syntax to support a broader range of docker-compose versions, although upgrading docker-compose looks to be a simple fix.

**Comment by VincentAntoine** [comment]
Thanks @madkinsz!
I had docker-compose version 1.25.0, which failed. After upgrading to 1.28.4, it works.

Upgrading docker-compose is indeed an easy fix, so maybe simply adding a helpful error message "please upgrade docker-compose to version >xxx" would be enough.

**Comment by madkinsz** [comment]
I just went down the rabbit hole on this, capturing the output from the docker-compose up subprocess to check for this specific error is going to  be a huge pain in the butt so I don't think I can easily provide a nice error message :/ can investigate further in the future.

**Comment by frafra** [comment]
As `docker-compose` is a Python program and the `prefect` Python packages relies on that, I think it could be added as dependency, as any other Python package.

**Comment by madkinsz** [comment]
@frafra except `docker-compose` is not needed for most modes of prefect operation and doesn't fit our current pattern of 'extras' which is mostly tied to the task library. We don't even pin `docker-compose` internally because it unnecessarily limits versions of other libraries.

**Comment by frafra** [comment]
That is understandable.  I would suggest to make clear that docker-compose is an external dependency and which version should be installed. A first time user following the guide would be puzzled otherwise. It could also be an idea to avoid packing the compose file hidden in the prefect package.

**Comment by madkinsz** [comment]
> That is understandable. I would suggest to make clear that docker-compose is an external dependency and which version should be installed. A first time user following the guide would be puzzled otherwise. It could also be an idea to avoid packing the compose file hidden in the prefect package.

I agree that the version could be suggested but the docs are quite clear that docker-compose must be installed to deploy the Server. We have to package the compose file inside the python package because of how python package installation works, I think it's reasonable for it to live alongside the command that uses it. Users should not have to interact with the docker-compose file itself.

**Comment by NewbiZ** [comment]
I am strongly in favor of reverting the depends_on change until major distributions release newer versions of docker-compose.

I agree that the docker-compose dependency should not be part of prefect. I would even go further and consider that generating a docker-compose file and ensuring the containers are running is a complete separate concern that is more "infrastructure" than "development" and thus is likely to be handled by different people, with different constraints. That is to say, deploying and managing a prefect server is something a devops team would handle, and prefect developers would typically not care much as to how the server is managed. 

With this philosophy, I do find it more natural that prefect servers can be fully installed and administered using readily available OS packages, and not require a separate virtualenv. 

For instance, I would typically like to use the docker-compose OS package (rpm/deb) of my distribution and manage systemd services to ensure the containers are up and running. Having to rely on a docker compose that is not available yet on main Linux distributions is annoying, it requires the deployment of a custom, system level virtualenv containing the latest docker-compose and use this in systemd services.

**Comment by madkinsz** [comment]
Hey @NewbiZ, I've opened a PR that should address these concerns by lowering the required version to 1.18.0 at https://github.com/PrefectHQ/prefect/pull/4396.

1.18.0 appears to be a stable rpm on centos (https://centos.pkgs.org/7/epel-x86_64/docker-compose-1.18.0-4.el7.noarch.rpm.html)

If you'd like to give it a try and provide feedback in the PR, it's always appreciated.

**Comment by madkinsz** [comment]
Hey @daniel-davee can you share your docker-compose version? I've tested this with 1.18.0 on a mac without issues.

**Comment by daniel-davee** [comment]
Howdy Michael,
This the original version
`version: "3.5"
# Features driving version requirement
# - networks.name                 3.5
# - healthcheck.start_period      2.3
# - healthcheck                   2.1

services:
  # PostgreSQL: the backing database which stores flow metadata
  postgres:
    image: "postgres:11"
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - prefect-server
    command:
      - "postgres"
      # explicitly set max connections
      - "-c"
      - "max_connections=150"
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 2s
    restart: always

  # Hasura: automatically generates a GraphQL schema from Postgres, provides most of the 'query' API
  hasura:
    image: "hasura/graphql-engine:v1.3.3"
    ports:
      - "${HASURA_HOST_PORT:-3000}:3000"
    command: "graphql-engine serve"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DB_CONNECTION_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_SERVER_PORT: "3000"
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
    networks:
      - prefect-server
    healthcheck:
      test: wget -O - http://hasura:$${HASURA_GRAPHQL_SERVER_PORT}/healthz &>/dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
        -postgres

  # GraphQL: provides most of the 'mutation' GraphQL API
  graphql:
    image: "prefecthq/server:${PREFECT_SERVER_TAG:-latest}"
    ports:
      - "${GRAPHQL_HOST_PORT:-4201}:4201"
    command: bash -c "${PREFECT_SERVER_DB_CMD} && python src/prefect_server/services/graphql/server.py"
    environment:
      PREFECT_SERVER_DB_CMD: ${PREFECT_SERVER_DB_CMD:-"echo 'DATABASE MIGRATIONS SKIPPED'"}
      PREFECT_SERVER__DATABASE__CONNECTION_URL: ${DB_CONNECTION_URL}
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
      PREFECT_CORE_VERSION: ${PREFECT_CORE_VERSION:-"UNKNOWN"}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent "http://graphql:4201/health" &> /dev/null || exit 1
      interval: 20s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
        -hasura

  # Towel: runs a collection of simple services
  towel:
    image: "prefecthq/server:${PREFECT_SERVER_TAG:-latest}"
    command: "python src/prefect_server/services/towel/__main__.py"
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
        -graphql

  # Apollo: combines the hasura and graphql schemas into a unified schema, the primary API entrypoint
  apollo:
    image: "prefecthq/apollo:${PREFECT_SERVER_TAG:-latest}"
    ports:
      - "${APOLLO_HOST_PORT:-4200}:4200"
    command: bash -c "./post-start.sh && npm run serve"
    environment:
      HASURA_API_URL: ${HASURA_API_URL:-http://hasura:3000/v1alpha1/graphql}
      PREFECT_API_URL: ${PREFECT_API_URL:-http://graphql:4201/graphql/}
      PREFECT_API_HEALTH_URL: ${PREFECT_API_HEALTH_URL:-http://graphql:4201/health}
      PREFECT_SERVER__TELEMETRY__ENABLED: ${PREFECT_SERVER__TELEMETRY__ENABLED:-true}
      GRAPHQL_SERVICE_HOST: http://graphql
      GRAPHQL_SERVICE_PORT: 4201
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent "http://apollo:4200/.well-known/apollo/server-health" &> /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
      - graphql
      - hasura

  # UI: the user interface that provides a visual dashboard for mutating and querying metadata
  # The UI is a standalone web interface and only communicates with the Apollo GraphQL API via
  #  the host from which it is accessed (i.e. the user's browser) .
  ui:
    image: "prefecthq/ui:${PREFECT_UI_TAG:-latest}"
    ports:
      - "${UI_HOST_PORT:-8080}:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__APOLLO_URL: ${APOLLO_URL:-http://localhost:4200/graphql}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent --head "http://ui:8080/" &> /dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
        apollo

networks:
  prefect-server:
    name: prefect-server
`

The new version
`version: "3.5"
# Features driving version requirement
# - networks.name                 3.5
# - healthcheck.start_period      2.3
# - healthcheck                   2.1

services:
  # PostgreSQL: the backing database which stores flow metadata
  postgres:
    image: "postgres:11"
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - prefect-server
    command:
      - "postgres"
      # explicitly set max connections
      - "-c"
      - "max_connections=150"
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 2s
    restart: always

  # Hasura: automatically generates a GraphQL schema from Postgres, provides most of the 'query' API
  hasura:
    image: "hasura/graphql-engine:v1.3.3"
    ports:
      - "${HASURA_HOST_PORT:-3000}:3000"
    command: "graphql-engine serve"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DB_CONNECTION_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_SERVER_PORT: "3000"
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
    networks:
      - prefect-server
    healthcheck:
      test: wget -O - http://hasura:$${HASURA_GRAPHQL_SERVER_PORT}/healthz &>/dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
        postgres:
            condition: service_healthy

  # GraphQL: provides most of the 'mutation' GraphQL API
  graphql:
    image: "prefecthq/server:${PREFECT_SERVER_TAG:-latest}"
    ports:
      - "${GRAPHQL_HOST_PORT:-4201}:4201"
    command: bash -c "${PREFECT_SERVER_DB_CMD} && python src/prefect_server/services/graphql/server.py"
    environment:
      PREFECT_SERVER_DB_CMD: ${PREFECT_SERVER_DB_CMD:-"echo 'DATABASE MIGRATIONS SKIPPED'"}
      PREFECT_SERVER__DATABASE__CONNECTION_URL: ${DB_CONNECTION_URL}
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
      PREFECT_CORE_VERSION: ${PREFECT_CORE_VERSION:-"UNKNOWN"}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent "http://graphql:4201/health" &> /dev/null || exit 1
      interval: 20s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
        hasura:
            condition: service_healthy

  # Towel: runs a collection of simple services
  towel:
    image: "prefecthq/server:${PREFECT_SERVER_TAG:-latest}"
    command: "python src/prefect_server/services/towel/__main__.py"
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
        graphql:
            condition: service_healthy

  # Apollo: combines the hasura and graphql schemas into a unified schema, the primary API entrypoint
  apollo:
    image: "prefecthq/apollo:${PREFECT_SERVER_TAG:-latest}"
    ports:
      - "${APOLLO_HOST_PORT:-4200}:4200"
    command: bash -c "./post-start.sh && npm run serve"
    environment:
      HASURA_API_URL: ${HASURA_API_URL:-http://hasura:3000/v1alpha1/graphql}
      PREFECT_API_URL: ${PREFECT_API_URL:-http://graphql:4201/graphql/}
      PREFECT_API_HEALTH_URL: ${PREFECT_API_HEALTH_URL:-http://graphql:4201/health}
      PREFECT_SERVER__TELEMETRY__ENABLED: ${PREFECT_SERVER__TELEMETRY__ENABLED:-true}
      GRAPHQL_SERVICE_HOST: http://graphql
      GRAPHQL_SERVICE_PORT: 4201
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent "http://apollo:4200/.well-known/apollo/server-health" &> /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
      - graphql
      - hasura

  # UI: the user interface that provides a visual dashboard for mutating and querying metadata
  # The UI is a standalone web interface and only communicates with the Apollo GraphQL API via
  #  the host from which it is accessed (i.e. the user's browser) .
  ui:
    image: "prefecthq/ui:${PREFECT_UI_TAG:-latest}"
    ports:
      - "${UI_HOST_PORT:-8080}:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__APOLLO_URL: ${APOLLO_URL:-http://localhost:4200/graphql}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent --head "http://ui:8080/" &> /dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
        apollo:
            condition: service_healthy

networks:
  prefect-server:
    name: prefect-server
`

I'm pretty sure it's because docker changed something with version 3 that healthcheck works differently

**Comment by madkinsz** [comment]
Hey @daniel-davee -- I'm actually looking for the output of `docker-compose --version`

**Comment by JLHasson** [comment]
@madkinsz FWIW I hit the same error:
```bash
$ prefect server start
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Exception caught; killing services (press ctrl-C to force)
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Traceback (most recent call last):
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/prefect/cli/server.py", line 608, in start
    subprocess.check_call(
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 15.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/site-packages/prefect/cli/server.py", line 649, in start
    subprocess.check_output(
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/lancehasson/opt/miniconda3/envs/prefect_tutorial/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 15.
```

Here are my versions:
```bash
$ prefect version
0.15.1
$ docker-compose --version
Docker Compose version v2.0.0-beta.6
$ docker --version
Docker version 20.10.7, build f0df350
```

**Comment by madkinsz** [comment]
@JLHasson -- that looks like an OOM error; I think you'll need to bump the available memory in the Docker Desktop app.

**Comment by KrzysztofNawara** [comment]
@madkinsz I'm getting what I think it an identical error:
```(titanic_pipeline) knawara:~/fun/analytics $ prefect server start
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Exception caught; killing services (press ctrl-C to force)
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Traceback (most recent call last):
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/prefect/cli/server.py", line 608, in start
    subprocess.check_call(
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 15.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/prefect/cli/server.py", line 649, in start
    subprocess.check_output(
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 15.
```

I get a similar error if I try `prefect server config`:
```(titanic_pipeline) knawara:~/fun/analytics $ prefect server config
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Traceback (most recent call last):
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/site-packages/prefect/cli/server.py", line 480, in config_cmd
    subprocess.check_call(["docker-compose", "config"], cwd=compose_dir_path, env=env)
  File "/Users/knawara/Applications/miniconda3/envs/titanic_pipeline/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'config']' returned non-zero exit status 15.
```

Output of `prefect diagnostics`:
```
(titanic_pipeline) knawara:~/fun/analytics $ prefect diagnostics
{
  "config_overrides": {
    "flows": {
      "checkpointing": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.7-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.15.2",
    "python_version": "3.8.3"
  }
}
```

```
Docker Compose version v2.0.0-beta.6
```

I think it may have broke down after I installed a Docker 
It seems I'm getting this regardless of whether docker is running or not
Tested both with 0.15.0 and 0.15.2

**Comment by KrzysztofNawara** [comment]
Disabling docker-compose v2 appears to have solved the issue:
![image](https://user-images.githubusercontent.com/5757040/126862115-798b3487-d649-43e4-a84e-074efb12e96c.png)
