### ISSUE TITLE
"prefect server start  --detach" not terminate process, when server port other, than 4200

### ISSUE THREAD

**Issue by vfilon** [PrefectHQ/prefect#4147]
## Description
```
$ prefect server start --server-port 8100 --detach
Pulling postgres ... done
Pulling hasura   ... done
Pulling graphql  ... done
Pulling apollo   ... done
Pulling towel    ... done
Pulling ui       ... done
Creating network "prefect-server" with the default driver
Creating t_postgres_1 ... done
Creating t_hasura_1   ... done
Creating t_graphql_1  ... done
Creating t_towel_1    ... done
Creating t_apollo_1   ... done
Creating t_ui_1       ... done
``` 

Command does not terminate process, when server port other, than 4200

When run `prefect server start --server-port 4200 --detach` - all OK, welcome screen present.

## Reproduction
See description

## Environment
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.7-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.14.9",
    "python_version": "3.8.8"
  }
```

**Comment by UPetit** [comment]
Hi @vfilon,
Is there a documentation about the arguments you're using after `prefect server start`? I couldn't find anything related in the official doc... This is totally new to me.
Hope someone will help you solve your issue 🤞

**Comment by vfilon** [comment]
> Hi @vfilon,
> Is there a documentation about the arguments you're using after `prefect server start`? I couldn't find anything related in the official doc... This is totally new to me.
> Hope someone will help you solve your issue 🤞

```
prefect server start --help
....
      --detach, -d                Detached mode. Runs Server containers in the background
      --server-port       TEXT    Port used to serve the Core server, defaults to '4200'
....
```

**Comment by UPetit** [comment]
Thank you @vfilon!
Regarding your issue, what do you have in the `config.toml`.
Maybe it should be aligned with the parameter you're passing to the server start command?

**Comment by vfilon** [comment]
> Thank you @vfilon!
> Regarding your issue, what do you have in your `config.toml` file?
> Maybe it should be aligned with the parameter you're passing to the server start command?

empty config.toml
```
{
  "config_overrides": {},
  "env_vars": [],
   ....
}
```

Maybe the problem is here https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/server.py#L357

**Comment by madkinsz** [comment]
@vfilon that does indeed look suspicious. Does patching that resolve for issue? It doesn't make much sense for this to have something to do with `detach`, do you reach the ASCII welcome screen with `prefect server start --server-port 4201` ?

**Comment by vfilon** [comment]
> Does patching that resolve for issue? 

Yes

> do you reach the ASCII welcome screen with `prefect server start --server-port 4201` ?

No

```
$ prefect server start --server-port 4201
Pulling postgres ... done
Pulling hasura   ... done
Pulling graphql  ... done
Pulling apollo   ... done
Pulling towel    ... done
Pulling ui       ... done
Creating network "prefect-server" with the default driver
Creating t_postgres_1 ... done
Creating t_hasura_1   ... done
Creating t_graphql_1  ... done
Creating t_apollo_1   ...
Creating t_apollo_1   ... error
WARNING: Host is already in use by another container

ERROR: for t_apollo_1  Cannot start service apollo: driver failed programming external connectivity on endpoint t_apollo_1 (cda92d3d43e
Creating t_towel_1    ... done

ERROR: for apollo  Cannot start service apollo: driver failed programming external connectivity on endpoint t_apollo_1 (cda92d3d43ef8ab920138f6e9f74bd678f34f62d54df41b3ac11905787ea56a3): 
Bind for 0.0.0.0:4201 failed: port is already allocated
....
```

```
$ docker ps | grep 4201
b1aed8ae85c7   prefecthq/server:core-0.14.9   "bash -c 'prefect-se…"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:4201->4201/tcp   t_graphql_1
```

**Comment by madkinsz** [comment]
Hey @jeremySrgt 

4201 is in use by the graphql container. Setting the `--server-port` to something else (like 4202) works fine.

**Comment by jeremySrgt** [comment]
Hi @madkinsz, thanks for your quick reply
I’m setting the server port to 9000 but the problem is that the -d flag doesn’t work if the server port is set to something else that the  default one

**Comment by madkinsz** [comment]
Ah alright, the scope of this issue is a little unclear as the original user was encountering errors without `--detach` as well (due to port collision). Your issue is because we are attempting to make requests to the API to check if it is up but the client uses default settings for that instead of the custom port. I'll open a PR to fix this.

**Comment by vfilon** [comment]
Thanks all
