### ISSUE TITLE
prefect server start should offer to dump resulting docker-compose.yml and environment for standalone deployment

### ISSUE THREAD

**Issue by sm-Fifteen** [PrefectHQ/prefect#4151]
## Current behavior
`prefect server start` is currently just a wrapper around a few docker and docker-compose functions to create a custom docker-compose.yml based on [a reference file](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/docker-compose.yml) and run it. While this is convenient for local testing, it can make actual core server deployment a bit cumbersome. For instance, even though the entirety of the server is going to be running inside docker containers, one still needs to have python3 installed and either

* run `sudo pip install prefect` to install prefect globally (which pip even warns that you shouldn't do that) with a prefect config in the /root directory
* use a virtual environment and override `VIRTUAL_ENV` and `PREFECT__USER_CONFIG_PATH` when running `prefect server start` as a service
* use `pip install --user prefect` to install prefect in a user's home and have the service run `prefect server start` as that user, given that user is part of the `docker` group

In all cases, all of this is merely so a python program can slice together a YAML file at `/tmp/docker-compose.yml` and create a few environment variables before basically running `docker-compose up` on it. This isn't so great for standalone deployments.

I got the idea of putting together my own `docker-compose.yml` from [flavienbwk/prefect-docker-compose](https://github.com/flavienbwk/prefect-docker-compose), although going back and forth between [prefect/cli/docker-compose.yml](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/docker-compose.yml) and [prefect/cli/server.py](https://github.com/PrefectHQ/prefect/blob/559330bb549b9c92c413948b615509b6c6d33620/src/prefect/cli/server.py) to figure out what each one was doing and what each one needed was rather tedious.

## Proposed behavior

It seems to me like a pure docker-compose deployment is something that users of prefect core would have a number of reasons to be interested in (easier to compose with additional services, lots of environment variables to currently manage, avoids "polluting" the host machine, etc.) and have indeed shown interest towards in the past (PrefectHQ/prefect#2715, PrefectHQ/prefect#3557, among others). Given how `prefect server start` is already just a wrapper for that, I could see a `prefect server dump` or `prefect server generate` command taking the same options as `prefect server start`, but creating a `docker-compose.yml` and a `.env` file in the current directory (or anywhere else) instead, so that the same configuration can be launched later without having the prefect  client or even python installed.

## Additional information
This is the systemd unit file I had come up with when attempting to make `prefect server start` work as a service.

```ini
[Unit]
Description=Prefect Server (via docker)
AssertFileNotEmpty=/opt/python-prefect/prefect_home/config.toml # contains `home_dir = "/opt/python-prefect/prefect_home"`
AssertPathIsDirectory=/opt/python-prefect/python36-venv

[Service]
Environment=VIRTUAL_ENV="/opt/python-prefect/python36-venv"
Environment=PREFECT__USER_CONFIG_PATH="/opt/python-prefect/prefect_home/config.toml"

ExecStart=/opt/python-prefect/python36-venv/bin/prefect server start --version=core-0.14.5 --ui-version=core-0.14.5 --skip-pull --no-postgres-port --no-hasura-port --no-graphql-port --no-ui-port --no-server-port

[Install]
WantedBy=multi-user.target
```

I abandonned the idea after attempting to set a reverse proxy to work on the same virtual network (see also PrefectHQ/ui#620), because `prefect server start` deletes the virtual network upon quitting. I'm showing this to point out that running prefect server as a permanent service is by no means simple at the moment, and none of those acrobatics are actually needed given all this is doing is using docker-compose to start up five containers, and that docker-compose is already pretty good at setting up containers to monitor themselves without systemd being involved.

**Comment by madkinsz** [comment]
I like this idea. I'll look into a bit further and report back.

**Comment by madkinsz** [comment]
@sm-Fifteen Does this look like what you want?

**Comment by sm-Fifteen** [comment]
> @sm-Fifteen Does this look like what you want?

@madkinsz: That looks great!
