### ISSUE TITLE
Allow to add flow Readme when registering flow 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#4154]
## Current behavior
Currently a flow Readme is added through the UI (which is a really nice new feature).

## Proposed behavior
Allow the user to attach the Readme to the flow at registration time. This allows the readme to be bundle with the flow code in version control. This should then overwrite the readme in the UI.

## Example

```python
readme = """
## My markdown title
My markdown text
"""

flow.readme = readme
flow.register()
```

**Comment by cicdw** [comment]
This definitely makes sense but I want to highlight one thing: currently flow READMEs are actually _flow group_ READMEs.  Flow Groups are the persistent layer behind all the versions of a Flow, so there is no expectation that they change with incremental versions.  We do have a backend concept for individual version descriptions / READMEs as well, it just hasn't been exposed in the UI yet.  As a rule of thumb, flow group settings are editable post-registration and individual flow version settings are not -- this is essentially to ensure your code remains a source of truth for the version.

All of that being said, in the meantime you can set READMEs programmatically via GraphQL as follows:
```python
mutation = """
mutation($input: set_flow_group_description_input!){
   set_flow_group_description(input: $input){
      success
   } 
}
"""

from prefect import Client

client = Client()
client.graphql(mutation, variables=dict(input=dict(description=README_STRING, flow_group_id=FLOW_GROUP_ID)))
```

**Comment by thomasfrederikhoeck** [comment]
Thank you for the clear answer @cicdw :-) I will do it this way then.

**Comment by wvargas-ods** [comment]
Still waiting for this feature, the workaround is fine, but it should be easier to update the README from code.

**Comment by VincentAntoine** [comment]
Interested too :)

**Comment by cicdw** [comment]
We are working on some larger changes that include better Flow versioning and better description tracking, so this is on our radar; it will be a little while before it's out, but I'll provide updates here as they're available 👍

**Comment by thomasfrederikhoeck** [comment]
Wonderful! @cicdw

**Comment by bkkkk** [comment]
We just added this feature to our deployment pipeline so users can just add a README.md file in the same folder as the Flow file and it gets uploaded automatically.

**Comment by giorgiobasile** [comment]
Hi, I tried to use the described approach to programmatically set a flow readme, here is my implementation:

```python

def add_flow_readme(flow_id, readme: str):
    client = Client(api_server=config.PREFECT_API_SERVER)
    res = client.graphql(
        {"query": {with_args("flow_by_pk", {"id": flow_id}): {"flow_group_id": ...}}}
    )
    flow_group_id = res.get("data").flow_by_pk.flow_group_id
    mutation = """
        mutation($input: set_flow_group_description_input!){
            set_flow_group_description(input: $input){
                success
            }
        }
    """
    client.graphql(
        mutation,
        variables=dict(input=dict(description=readme, flow_group_id=flow_group_id)),
    )

```

This function is called right after the flow registration, passing the flow_id returned by `Flow.register()` and a readme string.
Unfortunately, although the readme is correctly set and visible in the Prefect dashboard, when I try to start a run I get the following error in the run logs:

```
ClientError(400 Client Error: Bad Request for url: http://localhost:4200

The following error messages were provided by the GraphQL server: 

GRAPHQL_VALIDATION_FAILED: Expected type uuid!, found null.
The GraphQL query was:
    query {
            flow_by_pk(id: null) {
                flow_group_id\n        }
    }

The passed variables were: null)
```

where localhost:4200 is my Prefect server address. The fact that I see this when I start a run and not when I register the flow and the readme confuses me... what am I doing wrong?

**Comment by lpravda** [comment]
Is there an option for pushing images along with the README? I know that README can link images using URL, but what if I've got images available locally and linked them from the README using relative paths?

**Comment by jacksund** [comment]
will prefect 2.0 (orion) use a flow's docstring at all?

For example...

``` python
from prefect import flow

@flow("Prefect 2.0 Flow"):
def marvin_flow():
    """
    This docstring can be used as the default readme for a flow!
    Advanced functionality would accept markdown-flavored
    text in this docstring too
    """
    say_hello()  # task defined elsewhere
```

**Comment by madkinsz** [comment]
This feature request is difficult to address because the readme is set at the flow _group_ level and registration just creates a new flow in the group. 

> Adding a README could be an option when registering a workflow using CLI:

This is a difficult option because registration can handle many flows while a README would typically be mapped to a single flow.

> Is there an option for pushing images along with the README?

Not currently, we don't really have a good place to store user's images like that.

> will prefect 2.0 (orion) use a flow's docstring at all?

Yes the description of the flow defaults to the docstring.
