### ISSUE TITLE
Document Sensor-like task idiom

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#4161]
## Current behavior

We've had a few questions about how to create a task similar to Airflow's sensor tasks.  (E.g. see slack thread here: https://prefect-community.slack.com/archives/CL09KU1K7/p1614100773159700 and github Q here: https://github.com/PrefectHQ/prefect/discussions/4156#discussioncomment-399063)

Such tasks are possible in Prefect but we don't have docs/idioms that show them. 

## Proposed behavior

We should add an idiom to the docs to show how to create a sensor-task - similar to Chris's example in https://github.com/PrefectHQ/prefect/discussions/4156#discussioncomment-399063

**Comment by GuillaumeDesforges** [comment]
Any ETA?
