### ISSUE TITLE
Support Discord cloud hooks (Webhooks)

### ISSUE THREAD

**Issue by UPetit** [PrefectHQ/prefect#4171]
Hi there :wave: 
## Current behavior
Discord is allowing webhooks to publish in a channel in a JSON format, however adding the webhook discord url as "Web" cloud webhooks in the UI doesn't fire anything to the desired Discord channel.
The Discord webhook accept the JSON format and works well with GitHub integration for instance.

## Proposed behavior
Support Discord webhooks in the Cloud Hooks section.

**Comment by madkinsz** [comment]
The generic "Web" cloudhook provides a dump of the event data and it needs to be in a specific format for discord. You might be able to setup a slack webhook and post to their slack-compatible interface https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook. 

We can definitely consider this as a first-class webhook item if that doesn't work though. It looks like a relatively straightforward API, linking to the docs here for future reference https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by UPetit** [comment]
Thanks for the details.
I can't make it work though. I am running Prefect "server" instance, not Prefect "cloud" but that should still work, right?

**Comment by sgoley** [comment]
In case anyone else lands on this thread via search, worth checking out this project for discord notifications: 

https://github.com/rpeden/prefect-discord
