### ISSUE TITLE
Modifying `task.name` can violate the assumption that slugs are unique

### ISSUE THREAD

**Issue by johnurbanik** [PrefectHQ/prefect#4185]
## Description
Dynamically modifying a task's name can result in overlapping slugs. This seems to be because https://github.com/PrefectHQ/prefect/blob/20cd7352705741628ff83789e779b7bdb5315969/src/prefect/core/flow.py#L473-L494 generates `slug_bases` each time that the tasks are added.

Better practice is to provide the task name when it is added to the flow, but there is no enforcement that `.name` is read only, and the use of `task_args` is less intuitive.

`_generate_task_slug` could be made more robust, or `.name` could be made read-only or raise a warning suggesting the preferred method.

## Expected Behavior
Slugs should always be unique.

## Reproduction
```python
from prefect import Flow, Parameter, task

@task
def identity(x):
    return x

with Flow('slug-overlap') as flow:
    with tags('test-tag'):
        a = Parameter('a', default=1)
        # b = identity(a, task_args=dict(name='better-practice'))
        b = identity(a)
        b.name = 'bad-practice'
        c = identity(a)
print(flow.slugs)
```
results in 
```python
{<Task: bad-practice>: 'identity-test-tag-1', <Parameter: a>: 'a', <Task: identity>: 'identity-test-tag-1'}
```

## Environment
n/a

**Comment by jcrist** [comment]
Thanks for the issue report, this should be fixed by #4189. You should be able to modify task names after adding them to a flow, the slug generating routine should now be robust to this behavior.

Running your above sample:

```
$ python test.py
{<Task: bad-practice>: 'identity-test-tag-1', <Parameter: a>: 'a', <Task: identity>: 'identity-test-tag-2'}
```
