### ISSUE TITLE
Add Architecture Diagram to Docs

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#4187]
## Current behavior

Could be better for visual learners in the documentation

![prefect-architecture-diagram](https://user-images.githubusercontent.com/2325367/109395831-7251fe80-78fc-11eb-9be7-9c27d96c1b23.png)

Not sure of the best place for it, maybe a "Getting Started" section in Orchestration?

cc: @jcrist

**Comment by eric-valente** [comment]
Would have been helpful in the early days when I was wrapping my head around everything!
