### ISSUE TITLE
Environment variables are not populated from run_config on local flow.run()

### ISSUE THREAD

**Issue by tothandor** [PrefectHQ/prefect#4196]
## Description

Environment variables are not populated from run_config on local flow run. This could be okay if it's by design, but I would expect that any settings would take effect either in production (agent execution) or in testing (local).

## Expected Behavior

Populate environment both from system environment and run_config.env on local flow.run() for any local executors (LocalExecutor, LocalDaskExecutor).

## Reproduction

The output of the following script should contain `GREETING: Earthlings!` instead of `GREETING: MISSING`.

```python
import os

import prefect
from prefect import task, Flow
from prefect.executors import LocalExecutor, LocalDaskExecutor
from prefect.run_configs.local import LocalRun

@task(log_stdout=True)
def print_env():
    print('GREETING: %s' % os.getenv('GREETING', 'MISSING'))

with Flow("Run Config Env Test") as flow:
    print_env()

flow.run_config = LocalRun(env=dict(GREETING='Earthlings!'))
flow.executor = LocalExecutor() # or LocalDaskExecutor
flow.run()
```

## Environment

`prefect diagnostics` output:
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.18.0-240.10.1.el8_3.x86_64-x86_64-with-centos-8.3.2011",
    "prefect_backend": "server",
    "prefect_version": "0.14.10",
    "python_version": "3.6.8"
  }
}
```

**Comment by madkinsz** [comment]
Hi @tothandor !

`run_configs` apply to flows orchestrated by a backend, not local `flow.run()` calls. The `LocalRun` corresponds to configuration for a run by a `LocalAgent`. You'd have to call `flow.register(...)` and run the flow from the UI.

See https://docs.prefect.io/orchestration/flow_config/overview.html#run-configuration

**Comment by tothandor** [comment]
My intention was to pass configuration (database connection string to be exact) that is to be consumed by the tasks in the flow. It's value would depend on if it's a development or production environment. What would you suggest to use then? Should it be context, parameters or what means of Prefect? Context is not included in the flow, so I have ruled it out, as well as parameters, which should be added explicitly. Should I have a task to set configuration in parameters from environment then? It seems to be convoluted.

**Comment by jcrist** [comment]
A flow's `run_config` and `storage` are only used for flows executed with a backend (Prefect Cloud/Prefect Server). Think of them as describing a remote execution environment. Local flow runs (done with `flow.run()`) ignore these attributes completely. We can't really do much with a specified `run_config` for a local run, as the fields can't really be applied. How would we set an `image` for something run in-process? Many libraries load environment variables at startup only, so mutating the process's environment variables isn't really an option either.

For your specific question, you might use a default if the environment variable isn't set:

```python
@task
def connect():
    address = os.environ.get("ADDRESS", "tcp://my-default-address-here:8080")
    ...
```

Or you might set the environment variables locally as needed before execution:

```python
$ export ADDRESS=...
$ python my_flow.py
```

**Comment by tothandor** [comment]
Thanks for clarifying!
Maybe `agent_config` or `backend_config` would be more apt name. `run_config` is a bit misleading as it's ineffective during flow.run().
