### ISSUE TITLE
Allow the terminal flow state handler to be overriden

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#4198]
## Current behavior

The terminal flow state handler is a `FlowRunner` function that cannot be overridden using the `Flow` api. While users can create `state_handlers` at the flow level which allow them to mutate states in-transition, the state handler is only given the flow object, the old flow state, and the new flow state. In contrast, the terminal flow state handler is given task state information which is very helpful for determining custom messages depending on the tasks that have failed. This is particularly useful to people using Hooks to notify on flow failure.

## Proposed behavior

- Add the attribute `terminal_state_handler: Optional[Callable]` to `Flow`
- At the end of `FlowRunner.determine_final_state` if the flow has `terminal_state_handler`, call it to mutate the final state and return its return value instead

*signature of terminal state handling in FlowRunner*
```python
    def determine_final_state(
        self,
        state: State,
        key_states: Set[State],
        return_states: Dict[Task, State],
        terminal_states: Set[State],
    ) -> State:
```

Alternative solutions include
- Using a normal state handler and encouraging the user to query GraphQL for their task state information (likely not performant)
- Adding task state data to the normal state handler (seems significantly more complex to collect)

## Example

This enhancement would allow custom messages such as iterating through the return states and indicating which tasks have failed.

**Comment by zangell44** [comment]
Do Server/Cloud need to know about the `terminal_state_handler` property as well?

(Attempting to answer my own question)
No.

The code associated with a Flow, such as existing state handlers, is packaged up with the rest of your Python code when the Flow is registered.

Anything outside of the Python code, such as run config, needs to be stored in the database.

Do I have that right?

**Comment by madkinsz** [comment]
> Do Server/Cloud need to know about the `terminal_state_handler` property as well?
> 
> (Attempting to answer my own question)
> No.

Not really.
 
> The code associated with a Flow, such as existing state handlers, is packaged up with the rest of your Python code when the Flow is registered.
> 
> Anything outside of the Python code, such as run config, needs to be stored in the database.
> 
> Do I have that right?

Roughly yes. The run config is included in the serialized flow because we allow it to be overridden by the backend afaik. @jcrist would have a better answer about what belongs in the serialized `FlowSchema`

**Comment by jcrist** [comment]
Yeah, there's no need to modify serializers here - this will all be handled core-side only.
