### ISSUE TITLE
Allow Prefect Storage to store config file along side the flow file in Storage

### ISSUE THREAD

**Issue by minakshikorad** [PrefectHQ/prefect#4210]
## Current behavior
Github storage will currently only apply to your my_flow.py file and cannot load other files/config files alongside.

## Proposed behavior
I am planning to store a config file on github using prefect github storage https://docs.prefect.io/api/latest/storage.html#github along with the flow file as below. The my_flow.py will refer to config params from the config file. I was wondering if the flow registers and runs will be able to handle this behavior and automatic updates to config file changes?
flows/
        my_flow.py
        config.json

## Example
Task runs can read config files along with flows and do not need to be updated on config/flow updates.

**Comment by mahiki** [comment]
I think the improvements from #4418 solves this problem.
Release .14.17 allows pulling whole repo
