### ISSUE TITLE
Using a task result as default parameter value

### ISSUE THREAD

**Issue by sm-Fifteen** [PrefectHQ/prefect#4216]
## Current behavior

`Parameter()` tasks currently only support constant values as their default, which makes for some surprising patterns when attempting to generate default values from a separate task instead.

```py
with Flow("Default-Parameter") as flow:
	default_out_path = generate_file_name()
	out_path_param = Parameter('out_path', required=False)
	
	# switch controls whether default_out_path is skipped or not
	switch(out_path_param, {None: default_out_path})
	# The first non-skipped task from the left is used as the result
	out_path = merge(default_out_path, out_path_param)
```

![image](https://user-images.githubusercontent.com/516999/110132411-23431800-7d99-11eb-975a-90d82cd5db4f.png)

## Proposed behavior
I would have expected `default` to work like most other constant values in Prefect, where it is transparently converted into a `Constant` task if it happens to be a flat value and run as an upstream dependency when the parameter value is left unspecified at runtime, allowing for uses like these:

```py
with Flow("Default-Parameter") as flow:
	#default_out_path = Constant('~/foo/bar.txt')
	default_out_path = generate_file_name()
	out_path = Parameter('out_path', required=False, default=default_out_path)

	data = generate_data()
	save_file(out_path, data)
```

I tried adding the edge manually on the graph for visualization purposes, but got this error:
`ValueError: Parameters must be root tasks and can not have upstream dependencies.`

**Comment by jcrist** [comment]
For now, I'd write the example you gave as:

```python
from prefect import Flow, task, Parameter, case
from prefect.tasks.control_flow import merge

with Flow("default parameter") as flow:
    out_path_param = Parameter("out_path", required=False)
    with case(out_path_param, None):
        out_path_default = generate_file_name()
    out_path = merge(out_path_param, out_path_default)
```

This makes use of `case` statements (which most users find clearer than `switch` or `ifelse`).

The interface you suggested is certainly something we could do. I'm hesitant to call this a default (since currently defaults are all static parameters), debating whether a method on the `Parameter` object would make more sense. Something like:

```python
out_path = Parameter("out_path", required=False).if_none(generate_file_name())
```

This makes it clear that `None` is the default parameter value, and if it's `None` then `generate_file_name` will be used instead. Not sure if this is better than what you suggested, but it's an option. If this was pure python, I'd use `out_path = out_path or generate_file_name()`, so `parameter.or_` might also be an intuitive interface. We do have an `or_` method that purports to be the same as `a or b`, but in reality it looks like both `a` and `b` run before determining the result (rather than using short circuit evaluation). Changing this now may require a deprecation cycle, but it's another option.

**Comment by sm-Fifteen** [comment]
> This makes use of `case` statements (which most users find clearer than `switch` or `ifelse`).

That does make things clearer, thank you.

> The interface you suggested is certainly something we could do. I'm hesitant to call this a default (since currently defaults are all static parameters)

Yeah, I understand why you would want to keep these static. One one hand, it's kind of a weird exception to everything inside the Flow context manager actually being a Task, but on the other hand static values can be extracted and shown on the UI, whereas using defaults as task results means the actual default value won't be known until the flow runs.

> ```python
> ```python
> out_path = Parameter("out_path", required=False).if_none(generate_file_name())
> ```
> 
> 
> This makes it clear that None is the default parameter value, and if it's None then generate_file_name will be used instead. Not sure if this is better than what you suggested, but it's an option.

This would work, but `None` just happens to be the "default default value" that Prefect will resolve `NoDefault` to, so I feel like some kind of `is_undefined` or `is_default` (and a separate `is_defined` for good measure) method might be most flexible. I understand that boolean methods wouldn't work for task flows, though.

One possible solution would be to allow parameters to report as skipped if left undefined, which would allow coalescing them with something like `merge(maybe_skipped1, maybe_skipped2, default)` (the name `merge` is arguably misleading, it really is more of a "skipped-task-coalescing" operation). It would also neatly solve the currently rather tricky issue of trying to skip parts of a flow if the parameters for that section are undefined, since `case(my_param, not None)` is obviously not valid.

Something like this?

```py
from prefect.tasks.control_flow import merge as coalesce

out_path_param = Parameter('out_path', on_undefined='skip')
default_out_path = generate_file_name()
out_path = coalesce(out_path, default_out_path)
```
