### ISSUE TITLE
Cryptic error message when getting mapping order wrong

### ISSUE THREAD

**Issue by sm-Fifteen** [PrefectHQ/prefect#4219]
## Description
When mapping a function over a list at the root of the flow, an easy mistake to do it to mix up the calling order by doing `data_list.map(transform_fn)` instead of `transform_fn.map(data_list)`. I'm used to the former from years of Javascript muscle-memory, and when inside the flow, both `transform_fn` and `data_list` would be considered `Task` objects with working `map` functions.

This means getting the order wrong is something the user won't realize until they try running the flow and get an error like this:

```
$ python prefect-mapping/map_demo.py 
Traceback (most recent call last):
  File "prefect-mapping/map_demo.py", line 14, in <module>
    squared_list_bad = mylist.map(square_num) # This isn't javascrpt!!
  File "python-env/lib/python3.8/site-packages/prefect/core/task.py", line 715, in map
    return new.bind(
  File "python-env/lib/python3.8/site-packages/prefect/core/task.py", line 644, in bind
    callargs = dict(signature.bind(*args, **kwargs).arguments)  # type: Dict
  File "/usr/lib/python3.8/inspect.py", line 3025, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.8/inspect.py", line 2946, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

## Expected Behavior
I would imagine there's a good reason for both "task functions" and "task results" to have a `map` method, so suggesting for it to be removed from the latter is probably out of question.

Having a check inside `map` with an error message along the lines of "The result of task X does not support being called to map over values" would certtainly make the error message a lot more helpful, though.

## Reproduction
```py
from prefect import task, Flow

@task
def new_list():
	return [1,2,3,4,5]

@task
def square_num(x):
	return x*x

with Flow('my-flow'):
	mylist = new_list()
	squared_list_good = square_num.map(new_list)
	squared_list_bad = mylist.map(square_num) # This isn't javascrpt!!
	show_result(square_sums)

if __name__ == '__main__':
	flow.run()
```

**Comment by jcrist** [comment]
Giving a better error here is rather tricky, as both task definitions and results are `Task` objects. I believe this was done originally to better support both class and functional styles of build workflows, but conflating the two sometimes results in confusing behaviors.

It's not easy for us to distinguish between a task definition and the result of calling a task, but we could augment the existing error to provide more context about what went wrong. For example, the error you got above might look like:

```python-traceback
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    squared_list_bad = mylist.map(square_num) # This isn't javascrpt!!
  File "/Users/jcristharif/Code/prefect/src/prefect/core/task.py", line 717, in map
    raise TypeError(msg)
TypeError("Error while mapping `new_list`: too many positional arguments")
```

This at least provides some context that the function that failed to map is `new_list` (while you were expecting `square_num`), which might clarify things.

**Comment by sm-Fifteen** [comment]
> It's not easy for us to distinguish between a task definition and the result of calling a task

I figured `TaskFunction` would make this easy, but now that I'm looking at it, that would only help with the functional API, not the class-based tasks.


> ```
> TypeError("Error while mapping `new_list`: too many positional arguments")
> ```

The wording is still somewhat obtuse, the user would have to know that "mapping `new_list`" means "running `new_list` on each element of `square_num`" (I think?) and not "turning `new_list` into a map with `square_num` as the mapping function". The "too many positional arguments" part only makes sense if one is familiar with how mapped parameters are passed to tasks, so it's more confusing than anything else to users that are likely to make that sort of mistake.
