### ISSUE TITLE
`prefect register flow` cannot register modules containing relative imports

### ISSUE THREAD

**Issue by sm-Fifteen** [PrefectHQ/prefect#4233]
## Description
Using the prefect CLI to register flows runs into issues when using modules (as in `storage.Module`) instead of scripts (like `storage.Local`, `storage.Github`, etc.) to as flow storage. Using modules enables flows to have tasks moved to other files to encourage task reuse either privately within a project or across the whole agent for more generic tasks.

The problem with using modules this way is that `prefect register flow` currently [only expects to recieve individual files](https://github.com/PrefectHQ/prefect/blob/20cca8a7491079053725526570c5289cf905a751/src/prefect/cli/register.py#L92-L100), so if I have a module like this:

```py
## my_prefect/flows/Module-import/foo.py
from .bar import bar

from prefect import Flow
from prefect.storage.module import Module

script_storage_location = Module("my_prefect.flows.Module-import.foo")

with Flow('my-flow') as flow:
	bar()

if __name__ == '__main__':
	flow.run()
```

```py
## my_prefect/flows/Module-import/bar.py
from prefect import task

@task
def bar():
	pass
```

I can run it in either of these manners:
```
$ python -m my_prefect.flows.Module-import.foo
```
```
$ python my_prefect/flows/Module-import/foo.py
```

But this fails at registration-time because of the way Prefect reads flow files:

```
$ prefect register flow -f my_prefect/flows/Module-import/foo.py -p Module-import
```
```
Traceback (most recent call last):
  File "C:\Program Files\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".pyenv\Scripts\prefect.exe\__main__.py", line 9, in <module>

  -- snip --

  File ".pyenv\lib\site-packages\prefect\cli\register.py", line 94, in flow
    flow = extract_flow_from_file(file_path=file_path, flow_name=name)
  File ".pyenv\lib\site-packages\prefect\utilities\storage.py", line 86, in extract_flow_from_file
    exec(contents, exec_vals)
  File "<string>", line 1, in <module>
KeyError: "'__name__' not in globals"
```

While it makes sense to register flows by reading them as standalone files like this for store-as-script backends, this is somewhat of an issue with modules when it comes to relative imports. A (local) agent is perfectly capable of working with this sort of module once it has been registered, assuming the module is on its search path. There simply is no way to register modules that don't turn out to be fully self-contained in a single script without rolling up your own `register flow` command.

## Expected Behavior
The simple fix for this would be to have a `-m` option that uses `extract_flow_from_module` when loading the flow for interpretation instead of `extract_flow_from_file` like `-f` does.

```
$ prefect register flow -m my_prefect.flows.Module-import.foo -p Module-import
```

## Reproduction
See code example in description.

## Environment
I'm using a LocalAgent to run this module, whose working directory is a git working tree that contains the `my_prefect` module, meaning that module is in the agent's search path once it is running.

```
PrefectAgentWorkDir
├── .git
├── .pyenv
├── my_prefect
│   ├── shared
│   └── flows
│       └── Module-import
│           ├── bar.py
│           └── foo.py
├── register_module.py
└── requirements.txt
```

As with a local agent, someone working on the flows is expected to run them from the root of `PrefectAgentWorkDir` in order to have visibility on the same modules.

I know it's a far cry from the nice and clean docker deployments most people probably use, but the flows I'm working on at the moment are ported from preexisting scripts and a number of them are far too complex to neatly fit in a single file.

**Comment by jcrist** [comment]
Thanks for the excellent bug report. I agree this is an issue, hopefully will get a fix out later today.

**Comment by jcrist** [comment]
We actually want to wrap this fix into a larger set of updates to `prefect register flow`, so a fix for this probably won't be out until the next release (sometime next week).

For now you can work around this by adding a `flow.register(...)` call at the bottom of your scripts within a `if __name__ == "__main__":` block, and register as `python -m my.module.name`:

```python
# build flow up here

if __name__ == "__main__":
    flow.register(project_name="my-project")
```
