### ISSUE TITLE
Cancelled Flows Bug

### ISSUE THREAD

**Issue by Kieranflock** [PrefectHQ/prefect#4246]
## Description
In this PR:

https://github.com/PrefectHQ/server/pull/185

A change in behaviour was introduced where if you registered an existing Flow any scheduled runs would become cancelled and appear in the UI.

Thanks to @nicholas in the Slack community for helping summarise this change and also sharing that if you passed `flow.serialized_hash()` to the call then Flows would only be registered if their Meta changed.

But the Run History visual on the homepage of the UI is now flooded with greyed cancelled Flows which are way out of date. Newer and successful Flows are no longer appearing in the UI making it pretty useless and also ugly! 

@nicholas did suggest using the `delete_flow_run` mutation to clear these Flows but that is both unnecessary code (surely) and also a bit cyclical.

There is a Slack thread in the community here --> https://prefect-community.slack.com/archives/CL09KU1K7/p1614955524319600

## Expected Behavior
Firstly, I wouldn't expect to see cancelled future Flows in the UI at all. I am not sure what the use case is here. 

Secondly, if the future runs were cancelled. I would expect the Run History visual to show them in chronological order and then superseded by later successful runs. 

## Reproduction
I haven't tried to re-create the issue but I imagine creating an empty Flow on a schedule, registering, changing the Meta, re-registering and then running a few successful Flows would re-create this.

## Environment
I am using Prefect Cloud for the scheduler. 

We are using Prefect version 0.13.18 elsewhere with Python 3.6.

**Comment by madkinsz** [comment]
Hi @Kieranflock 

The cancellation is a backup mechanism to slow deletions for large amounts of flow runs (since it is much faster) which was likely encountered in your case due to the many registrations. We're working on a more robust solution right now and there have already been some recent performance fixes https://github.com/PrefectHQ/server/pull/206

**Comment by cicdw** [comment]
Closing as the updates referenced above have been released
