### ISSUE TITLE
How do I use Secrets in State Handlers?

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#4257]
> Your message has been sent a long time ago but maybe there is a chance that we could use secrets in result handlers (in my case I'm looking for using the secrets in the custom state handler)?

_Originally posted by @UPetit in https://github.com/PrefectHQ/prefect/issues/1478#issuecomment-800517448_

@UPetit -- Just to clarify, state handlers are different than result handlers. To use a secret in one you can just load the secret at runtime

```python
def my_state_handler(task, old_state, new_state):
    secret = PrefectSecret("NAME").get()
```

and make sure that the secret is available by attaching it to your storage

```python
flow.storage = Local(..., secrets=["NAME"])
```

In the future, please open a new issue for questions, it'll make answers more discoverable for other users. The issue you posted in is for a documentation request.

**Comment by UPetit** [comment]
Thank you very much for the explanation. Will do next time!
