### ISSUE TITLE
Prefect Cloud:  Flow URL has wrong tenant upon flow registration

### ISSUE THREAD

**Issue by A121792** [PrefectHQ/prefect#4289]
## Description
We’re experiencing a little weirdness with flow registration and tenant token scoping.  We (now) have multiple tenants in use. 

Here’s the scenario:

- we build and register flows using a tenant token
- the output from the successful build shows a flow URL from a different tenant than the one the token was originally scoped for. 
- the url in that output is a deadlink
- however, the flow DOES end up in the right tenant and project.   Only the output from the registration seems wrong. 

## Example:  
```
Flow URL: https://cloud.prefect.io/pgr-dss-core/flow/74f0579b-e718-4314-b1dc-2531984cd869
 └── ID: 7624942d-724f-4f71-aef4-356fa4f79243
 └── Project: Telematics-DE-Dev
 └── Labels: ['dev', 'docker', 'dss', 'flowgen', 'telematics']
```

## Expected Behavior
```
Flow URL: https://cloud.prefect.io/pgr/flow/74f0579b-e718-4314-b1dc-2531984cd869
 └── ID: 7624942d-724f-4f71-aef4-356fa4f79243
 └── Project: Telematics-DE-Dev
 └── Labels: ['dev', 'docker', 'dss', 'flowgen', 'telematics']
```

**Comment by dylanbhughes** [comment]
@A121792 can you provide any further details on how you're authenticating with that token? For example, is it put in a `config.toml` file?

**Comment by A121792** [comment]
We have a custom class that creates a client connection from an empheral agent in a CI/CD pipeline.    Something like: 

```python
from prefect import Client

prefect_client = Client(api_token=tenant_token)

prefect_client.register(
    flow=flow,
    project_name=self.project_name,
    idempotency_key=filehash,
    build=True,
)
```

**Comment by dylanbhughes** [comment]
Perfect, thank you!
