### ISSUE TITLE
Old mutation example

### ISSUE THREAD

**Issue by Adam-D-Lewis** [PrefectHQ/prefect#4291]
I was wondering if the following example in the documentation (https://docs.prefect.io/orchestration/concepts/api.html#mutations) is still up to date as of prefect 0.14.12.  I was looking at the available mutations in the Interactive Docs on prefect server (running locally) and I couldn't find `Mutation.set_flow_run_state`.

If this isn't up to date could you update it please?  Also, if you could show an example of updating a task_run state (resuming paused task) here or in the docs that would be awesome, but if not no worries.

Below is the specific example in the docs that I'm referring to.
```
mutation($state: JSON!) {
  set_flow_run_state(
    input: {
      id: "61cab648-f09d-467d-b205-3892c8d55250"
      version: 1
      state: $state
    }
  ) {
    id
    start_time
  }
}
```

**Comment by cicdw** [comment]
Hey @Adam-D-Lewis - good catch; you are correct.  These routes are actually pluralized, so you'll want to look up `set_flow_run_states` which accepts lists of inputs in the form you have here.  If you would like, we'd gladly accept a PR with the updated syntax!

**Comment by Adam-D-Lewis** [comment]
@cicdw I'd be happy to put a PR in with updated syntax if I can figure out the proper query.  

So I've been working on trying to set a task_state, but I must be missing something.  The below is my best effort to change a task_flow_run_state.
```
mutation MyResumeTaskMutation {
  set_task_run_states(input: {
  	states: [
      {
        task_run_id: "0c8e9be9-6cba-40eb-863e-a87e0ff12a4b"
        version: 2
        state: "{\"state\": {\"type\": \"Resume\"}}"
        flow_run_version: 2
      }
    ]
  })
  {
  states {
      id
    }
  }
}
```

but I'm still getting an error

```
{
  "errors": [
    {
      "message": "{'type': ['Missing data for required field.']}",
      "locations": [
        {
          "line": 20,
          "column": 3
        }
      ],
      "path": [
        "set_task_run_states"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "{'type': ['Missing data for required field.']}"
        }
      }
    }
  ],
  "data": {
    "set_task_run_states": null
  }
}
```

I'm not how to determine the correct name, value pairs for the JSON state to resume the taskso I tried to copy the documentation at the bottom of https://docs.prefect.io/orchestration/concepts/api.html#mutations, ( ("{\"state\": {\"type\": \"Resume\"}}") ) but I'm stuck with that error.

**Comment by madkinsz** [comment]
Hey @Adam-D-Lewis -- you'll want to just do `state: "{\"type\": \"Resume\"}"}`. The deserializer cannot find the `type` field because you have it nested in an extra top-level `"state"` in `state: "{\"state\": {\"type\": \"Resume\"}}"`
