### ISSUE TITLE
Add ability to run Shell task via SSH

### ISSUE THREAD

**Issue by asmhack** [PrefectHQ/prefect#4299]
## Current behavior
Currently prefect has only [Shell Task](https://docs.prefect.io/api/latest/tasks/shell.html#shelltask), which able to run some commands locally.

## Proposed behavior
It would be nice to be able to run shell commands on remote servers via ssh (specifying server ip/url, port, username, pem-file)

## Example
For instance: run 100 EC2 servers via boto3 and then run some specific set of commands on each of them.

**Comment by Hongbo-Miao** [comment]
It would be useful to have something like Airflow's SSH Connection, thanks! 😃
https://airflow.apache.org/docs/apache-airflow-providers-ssh/stable/connections/ssh.html

**Comment by ahuang11** [comment]
We have implemented this for a couple cloud providers:
https://github.com/PrefectHQ/prefect-gcp#deploy-command-on-cloud-run
https://github.com/PrefectHQ/prefect-aws/blob/main/prefect_aws/ecs.py#L10
Azure is coming soon.

**Comment by Hongbo-Miao** [comment]
Thanks @ahuang11 ! 😃
However, in our case, it is not related clouds, it is using SSH for some on-premises IoT devices.

**Comment by Hongbo-Miao** [comment]
Activate.

**Comment by Hongbo-Miao** [comment]
(Activate as still a key feature that we need to switch from Airflow to Prefect)

**Comment by Hongbo-Miao** [comment]
Activate

**Comment by Hongbo-Miao** [comment]
Adding another way to handle this situation. I ended up by deploying Prefect agents on on-premises IoT devices. Then it can pick up work there. I think this way is quite good too 😃
