### ISSUE TITLE
Snowflake QueryFromFile Task

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4348]
## Current behavior

We have one SnowflakeQuery Task that accepts a query string and executes the query. There are users asking for functionality to query from SQL files `(query1.sql, query2.sql)`. Some of them have multiple SQL files and they want to loop through them and execute each one.

The current workaround users use is using the ShellTask and a Python script to run these one at a time. There are requests to read in a file and execute that directly.

## Proposed behavior
There are three possible ways to do this. 

1. Add a file parameter to the SnowflakeQuery Task. If file is provided, read it and use it to query.
2. Create a new SnowflakeQueryFromFile Task. This reads in the `.sql` file and executes the query with similar logic to the SnowflakeQuery Task. 
3. A possibly more general approach is a Task to read SQL files into strings. This is a general Task that can be used by all potential downstream SQL tasks (Postgres, MySQL, Snowflake, etc.)

**Comment by MaheshSankaran** [comment]
It would be helpful if we execute queries from files.

**Comment by AyyanarDevops** [comment]
Hey Team 

We are also expecting to fix this issue.
