### ISSUE TITLE
ECSAgent Custom Capacity Provider Strategy

### ISSUE THREAD

**Issue by potter420** [PrefectHQ/prefect#4356]
## Description
Hello , I have tried to run the task with customCapacityProviderStrategy on my run config, as per configuration guide from AWS, but I found out that ECS run automatically append launchType to the run configuration, which causing errors.

I'm also working on a fix on this too.

## Expected Behavior
I should have run my flow with customCapacityProviderStrategy.

## Reproduction
```
flow.run_config = ECSRun(
      run_task_kwargs={
          "capacityProviderStrategy": [
              {
                  'capacityProvider': 'AnalyticsETLJobCP',
                  'weight': 1,
                  'base': 0
              },
          ]
      }
  )

```

## Environment
Linux

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by madkinsz** [comment]
Hi @potter420 

I think this is reasonable to fix. We can drop defaults if they'll break passing in other options.

I believe the lines in your PR at #4361 

```
        if "capacityProviderStrategy" in out:
            del out['networkConfiguration'], out['platformVersion'], out['launchType']
```

are all that's necessary, although I'm curious why you have to drop these additional sections.

There should probably be a user-experience bit as well such as a log call

`logger.debug("Found user-provided 'capacityProviderStrategy', dropping 'networkConfiguration', 'platformVerison', and 'launchType'")`

**Comment by potter420** [comment]
Hi @madkinsz 

I think I panic and remove also the `networkConfiguration` since my use case mostly use bridge mode, which mostly never expose any ports to other services. But in that case, `networkConfiguration` should only be available if we specify `awsvpc` networking mode, other mode may cause errors.

PlatformVersion is also a Fargate exclusive configuration, so if we provide `capacityProviderStategy`, this also have to be remove to avoid possible errors.

Thank you.

**Comment by madkinsz** [comment]
I don't see `platformVersion` set anywhere so I don't think we should be dropping it.

Since the default networkConfiguration is `awsvpc` it seems like there would only be a problem if they overrode the default. I think we should not drop that either.

If all we're doing dropping the `launchType` this might be best implemented as an `if` where we set that instead.

**Comment by potter420** [comment]
I agree with you, we should do an `if` statement instead rather than terrible delete statements. But since there are many scenario that can go wrong with this. I take for example in my current configuration:
- I set a default config on my agent to run every job as Fargate Instance, with default network settings, launchType and `platformVersion` coming from run config on that Fargate agent. 
- Now, use the same agent to run a flow with custom run config, which specify custom `capacityProviderStategy` parameters.
Since what I saw in the code base is that the agent tried to merge the default configuration with the run configuration provided by the flow in order to fill in all the gap, so this may cause the behavior that I describe above.

So I suggest one way is to force users to specify the full configuration of the job rather than partial configuration, except for the environments and tagging of course. And only use default Agent configuration and sensible default if the flow run does not specify any `run_task_kwargs` in the flow run or flow.
That way, if users got an error on agent, they should know where to look for them in 1 place, their flow run configuration or their agent.

**Comment by potter420** [comment]
And for those who overwhelm with the sheer amount of configuration that AWS provides, perhaps we could write a function that produce a sensible defaults that they can start with, or we can already use the example task yaml template and start from there.

**Comment by madkinsz** [comment]
This is indeed a tricky situation. Perhaps in your custom run config you could provide explicit `None` values for the defaults you want to drop? Perhaps we should look into removing merging -- that would be a larger breaking change though.

**Comment by potter420** [comment]
Indeed that is a breaking change. I'm really sorry for suggesting so many breaking changes. 
By the way, leaving some parameters as `None` still raise errors for Boto3, since they validate the key and its value type before making an API calls. I have been looking at `run_task` API for a while and saw that there are two cases that will cause error cause of merging:
- `capacityProviderStrategy ` and `launchType `cannot be specified together.
- If the task definition speficy a network mode other than `awsvpc`, specify `networkConfiguration` will cause an errors.

In the end I decided to launch 2 different agents, with different labels for two type of run, to avoid further headache.

But overall, how about we add some doc on the ECS agent and potential pitfall. E.g. 
- Do not mix **Fargate** launch type agent and **EC2** launch type agent together, create an agent for each launch type with your sensible default to avoid incompatibility issues.
Or ..
- Run a specific ECS agent for the job type that you going to run,  Periodic-Light-Fargate, Heavy-ETL-EC2-m5 or ML-p5, cool-stuff-r5, each with sensible default for the EC2 instance type that you're going to run the job in, or no default at all and specify them per task.

**Comment by madkinsz** [comment]
Hey @potter420 -- just want to let you know that I haven't forgotten about this but it'll take a closer look at our ECS deployment patterns than I have time for at the moment. Is the two agent pattern going well for you?

**Comment by potter420** [comment]
Hey @madkinsz , It working well for us at least. We were able to launch daily jobs and some adhoc training job during the day without much fuss, and since agents don't require much resources it should be fine.

**Comment by yin-aven** [comment]
Got redirected from #5210 .  Just want to comment on the PR that we don't want to drop networkConfiguration because we want to launch jobs to specific subnets that give us static public IP addresses.  I don't think networkConfiguration is causing any conflict with capacity provider.  Only launch type does.

**Comment by wfclark5** [comment]
I am also running into this issue and was wondering if it was solved in the latest release?
