### ISSUE TITLE
Job templates aren't working

### ISSUE THREAD

**Issue by haf** [PrefectHQ/prefect#4359]
## Description

From https://prefect-community.slack.com/archives/CL09KU1K7/p1615327031065400

When trying to use job templates, they don't work. Even overwriting the file `job_template.yaml` file inside the pod works.

Ultimately I'd like to override the `command` and `args` for the pod, because I want to run a shell script before starting the actual work-load (that captures the exit signal of the workload and tells the envoy istio proxy that it should exit).

If this isn't possible due to more work being required to allow nice merges, it should at least be possible to attach annotations to the pod, so I can avoid istio injection.

## Expected Behavior

When configuring a job template, especially for the pod-spec annotations to be applied.

## Reproduction

Try to use the `--job-template` feature with rbac.

## Environment

- prefect 0.14.12

**Comment by TylerWanner** [comment]
Hi Haf.  I've spent some time going through your use case and reproducing some of the behaviour you've explained.  I can understand now the gap you're pulling on--there is no way to inform the CLI kubernetes agent install of the job-spec.yaml to use for downstream flow jobs that it creates, as far as I can tell.  
Your solution is solid and probably a first step to filling that gap, if desired.  I was able to follow your workaround to mount a configmap into my agent and use that job spec for the jobs created by the agent.  You haven't provided a configmap/ job spec or modified agent deployment yaml to test with, so I can't say for certain what's happening on your deployment.  
The first thing I would have you try is to change the agent's args in the deployment.yaml to `prefect agent kubernetes start --job-template /usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/job_template.yaml`.  I would also check your agent's file system to make sure that the configmap is properly mounted.

I can provide additional support if given the appropriate reproduction materials.

**Comment by haf** [comment]
Ok, here's a log as I'm trying to make this work.

- I noticed there's a logger https://github.com/PrefectHQ/prefect/blob/master/src/prefect/agent/kubernetes/agent.py#L596 that I want the output of, so I followed the docs https://docs.prefect.io/core/concepts/logging.html#logging-configuration and set
```
    - name: PREFECT__LOGGING__LEVEL
      value: DEBUG
```
but that doesn't work, there's no output from it

<img width="992" alt="image" src="https://user-images.githubusercontent.com/193115/115149735-c314e680-a065-11eb-8767-b9462626e87e.png">

**Comment by haf** [comment]
The seemingly undocumented env var is:

```
        - name: PREFECT__CLOUD__AGENT__LEVEL
          value: DEBUG
```

**Comment by haf** [comment]
Here's the deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: prefect-agent

      containers:
      - name: agent
        args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: prefect-agent
              key: prefect-cloud-token
        - name: PREFECT__CLOUD__API
          value: https://api.prefect.io
        - name: NAMESPACE
          value: flows
        - name: IMAGE_PULL_SECRETS
          value: ''
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '["dev"]'
        - name: JOB_MEM_REQUEST
          value: ''
        - name: JOB_MEM_LIMIT
          value: ''
        - name: JOB_CPU_REQUEST
          value: ''
        - name: JOB_CPU_LIMIT
          value: ''
        - name: IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: SERVICE_ACCOUNT_NAME
          value: prefect-agent
        - name: PREFECT__BACKEND
          value: cloud
        - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
          value: http://:8080
        - name: PREFECT__LOGGING__LEVEL
          value: DEBUG
        - name: PREFECT__CLOUD__AGENT__LEVEL
          value: DEBUG

        image: prefecthq/prefect:0.14.16-python3.8

        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40

        resources:
          requests:
            cpu: 200m
            memory: 40Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

        volumeMounts:
        - mountPath: /usr/local/lib/python3.8/site-packages/prefect/agent/kubernetes/job_template.yaml
          name: prefect-agent-conf
          subPath: flow-job.yaml 

      volumes:
      - name: prefect-agent-conf
        configMap:
          name: prefect-agent
```

**Comment by haf** [comment]
This is the job template I'm trying

```yaml
apiVersion: batch/v1
kind: Job
spec:
  metadata:
    labels:
      app: prefect-agent
      component: flow-job
  template:
    spec:
      containers:
      - name: flow
        # https://hub.docker.com/layers/prefecthq/prefect/0.14.12-python3.8/images/sha256-3f1912fbc6e45e7c5571b7ec4e4a829f655de7fbfc3aca523b0d01680fdc13bb?context=explore
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for Istio sidecar to become responsive..."
          trap "curl --max-time 2 -s -f -XPOST http://127.0.0.1:15000/quitquitquit" EXIT
          while ! curl -s -f http://127.0.0.1:15020/healthz/ready; do sleep 1; done
          echo "Finished waiting! Executing 'prefect execute flow-run'."
          prefect execute flow-run

        env:
        - name: PREFECT__LOGGING__LEVEL
          value: DEBUG

        - name: PREFECT__CONTEXT__SECRETS__DBT_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres.app-analytics-db.credentials
              key: username

        - name: PREFECT__CONTEXT__SECRETS__DBT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.app-analytics-db.credentials
              key: password

        - name: PREFECT__CONTEXT__SECRETS__SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: prefect-agent
              key: slack-webhook-url

        - name: PREFECT__CONTEXT__SECRETS__GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: prefect-agent
              key: github-access-token
```

This is the resulting job yaml:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-04-18T15:15:06Z"
  labels:
    prefect.io/flow_id: ca8cd88e-7759-4097-8acf-2ea3af3924d1
    prefect.io/flow_run_id: af5fcb9e-4e18-4e2c-be73-1e9e3fb5a948
    prefect.io/identifier: e6246a70
  name: prefect-job-e6246a70
  namespace: flows
  resourceVersion: "102422623"
  selfLink: /apis/batch/v1/namespaces/flows/jobs/prefect-job-e6246a70
  uid: 4375c321-d926-4cc6-adfd-685b39d3ab9d
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 4375c321-d926-4cc6-adfd-685b39d3ab9d
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 4375c321-d926-4cc6-adfd-685b39d3ab9d
        job-name: prefect-job-e6246a70
        prefect.io/flow_id: ca8cd88e-7759-4097-8acf-2ea3af3924d1
        prefect.io/flow_run_id: af5fcb9e-4e18-4e2c-be73-1e9e3fb5a948
        prefect.io/identifier: xxxxxxxxxxx
    spec:
      containers:
      - args:
        - prefect
        - execute
        - flow-run
        command:
        - /bin/sh
        - -c
        env:
        - name: PREFECT__BACKEND
          value: cloud
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '[''prod'']'
        - name: PREFECT__CLOUD__API
          value: https://api.prefect.io
        - name: PREFECT__CLOUD__AUTH_TOKEN
          value: xxxxxxxxxxxxx
        - name: PREFECT__CLOUD__USE_LOCAL_SECRETS
          value: "false"
        - name: PREFECT__CONTEXT__FLOW_RUN_ID
          value: xxxxxxxxxxxxxxxx
        - name: PREFECT__CONTEXT__FLOW_ID
          value: xxxxxxxxxxxxx
        - name: PREFECT__CONTEXT__IMAGE
          value: xxxxxxxxxxxxxxxxxxx
        - name: PREFECT__LOGGING__LOG_TO_CLOUD
          value: "true"
        - name: PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS
          value: prefect.engine.cloud.CloudFlowRunner
        - name: PREFECT__ENGINE__TASK_RUNNER__DEFAULT_CLASS
          value: prefect.engine.cloud.CloudTaskRunner
        - name: PREFECT__LOGGING__LEVEL
          value: DEBUG
        - name: PREFECT__CONTEXT__SECRETS__DBT_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: xxxxxxxxxxxxx
        - name: PREFECT__CONTEXT__SECRETS__DBT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: xxxxxxxxxxxxx
        - name: PREFECT__CONTEXT__SECRETS__SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: slack-webhook-url
              name: prefect-agent
        - name: PREFECT__CONTEXT__SECRETS__GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: github-access-token
              name: prefect-agent
        image: xxxxxxxxxxxx
        imagePullPolicy: IfNotPresent
        name: flow
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - {}
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prefect-agent
      serviceAccountName: prefect-agent
      terminationGracePeriodSeconds: 30

```

**Comment by haf** [comment]
It seems it's further missing the ability to set annotations
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/agent/kubernetes/agent.py#L610-L615

**Comment by haf** [comment]
So in summary:

- It's undocumented how to override the job template when using the yaml files (the docs section that mentions `start` would require you to understand the output of the templating process and that you can override the start command of that, as the template command does not support the `--job-template` argument)
- The section on how to enable logging is wrong for the agent (i.e. it's missing from the agent docs page)
- Only some, undocumented, subset of YAML is available to override with the job template
  - This does not include `args`
  - This does not include `annotations`
  - From the two above, I can't make this work with Istio
- Many YAML job template properties are 'hard coded' such that they will be overwritten despite being in the templates `job` variable in `kubernetes/agent.py`
- When you enable logging with the undocumented `PREFECT__CLOUD__AGENT__LEVEL` you get duplicate lines in the output: <img width="912" alt="image" src="https://user-images.githubusercontent.com/193115/115152288-d1b4cb00-a070-11eb-9b1a-27a2a89af953.png">
- My solution ended up being reading the source code, and overriding the `kubernetes/agent.py` on line 666 😈 with:
  ```py
  # Set flow run command
  container["args"] = container["args"] or get_flow_run_command(flow_run).split()
  ```
  which in turn had required me to exec into the pod and `ps` not being present, having to run the python interpreter, to find the path that Prefect executes via `import sys` and then mounting my patch into the container with: 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/193115/115152379-222c2880-a071-11eb-99b7-a3b2e8f14185.png">

**Comment by TylerWanner** [comment]
Glad to hear that you solved your use case.  Generally, these configurations should be done in the run config, especially if there is one, as it is difficult to predict all expectations when trying to merge run configs and agent configs that affect runs (like the custom job template).   In order to make your solution less hacky, you would need to design around this constraint.  I can understand why that would be difficult in the paradigm you're after.

Generally, it is generally preferable not to install curl and ps in the image.  To check the install location of prefect, you can use `pip show prefect`.  If you want to supply your own image for the flow job (for example, a prefect image with curl in it), you can do that also in the run config or you can use extra_dockerfile_commands as you have here.

**Comment by haf** [comment]
Hi Tyler,

I'm of another opinion. In my mind, having a side-car is a common use-case, and while waiting for k8s to mature w.r.t sidecars; job templates are the de-facto solution. In this case, the job template doesn't work for some, undocumented, subset of yaml properties. This is a real problem.

It is suggested that a run config is used, but this is not a good general solution. The flow file should be blissfully unaware of any shenanigans put up by operations next to it. I can't have my data scientists having to know how to call out to the envoy proxy to shut it down. It just doesn't make sense.

Further, I don't see any problems adding curl — if you look at it from a security perspective: there's already a fully fledged python interpreter installed, so adding curl makes no difference.

**Comment by haf** [comment]
Any way to get back to "standard"? It's been a month, and with the current hack I have to manually merge `agent.py` any time you make a release.
