### ISSUE TITLE
Alter GitHub Storage to support using deploy keys and personal access tokenss

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#4376]
## Intro
Several users have requested that we support passing Deploy Keys to GitHub storage. Example: https://prefect-community.slack.com/archives/CL09KU1K7/p1617659682480500

## Current behavior

We support passing a GitHub Personal Access Token.

## Proposed behavior

Also instead accept a Deploy Key as a way to authenticate to the repository where the Flow code lives.

## Example

Deploy Keys are scoped to a single repository and their use is in line with better security practices.

**Comment by madkinsz** [comment]
To clarify this: Using a deploy key does not work with our current model because we pull a single file from your repository with a PAT but you can only clone full repos with deploy keys; this doesn't mean we can't do it just that it's not a simple change.

**Comment by zhodowanec** [comment]
@madkinsz it's an odd observation that pulling a single file would require a PAT rather than a deploy key. As @dylanbhughes mentioned in the ticket submission 'Deploy Keys are more secure and where the industry is moving as they are limited to a single repository'.

The Prefect team supporting Deploy Keys is paramount to our team being able to adopt this tool.

**Comment by madkinsz** [comment]
> @madkinsz it's an odd observation that pulling a single file would require a PAT rather than a deploy key. As @dylanbhughes mentioned in the ticket submission 'Deploy Keys are more secure and where the industry is moving as they are limited to a single repository'.

It's simply how the Github API works. We'll have to move to a method that no longer uses the API. 

> The Prefect team supporting Deploy Keys is paramount to our team being able to adopt this tool.

We will support them, we're tracking this issue in combination with #4328 which seems like a logical first step (moving away from API based git storage retrieval)

**Comment by zhodowanec** [comment]
Thanks for the update. Any timeframe on release?

**Comment by zangell44** [comment]
@zhodowanec Core 0.14.17 supports the use of Deploy Keys with a new `Git` storage class. More info here https://docs.prefect.io/orchestration/flow_config/storage.html#git
