### ISSUE TITLE
Feature Request: Add Google Cloud Run as Agent

### ISSUE THREAD

**Issue by tarikki** [PrefectHQ/prefect#4379]
## Current behaviour

Currently Prefect has support for multiple agent types but unfortunately non are in the Google infrastructure realm. This is a hurdle for teams who have setup their infrastructure with Google.

## Proposed behaviour

Add Google Cloud Run as one of the agent types. Google Cloud Run is the Google equivalent of Amazon Fargate, ie. a serverless container running service. This would be perfect for running Prefect tasks that are wrapped inside docker. 

## Example

This will help all teams currently on Google infrastructure who are looking to Prefect for automation. It would be amazing to offload tasks to a pay-as-you-go service while still using Prefect for task orchestration AND not having to setup additional infra and billing with another cloud provider.

**Comment by madkinsz** [comment]
This is available in Prefect 2.
