### ISSUE TITLE
Duplicate Images on Docker Hub to AWS Public ECR

### ISSUE THREAD

**Issue by joe1981al** [PrefectHQ/prefect#4382]
## Current behavior
Docker images are only available on Docker Hub

## Proposed behavior
Images will be available on https://public.ecr.aws as official images to avoid Docker Hub rate limits when running from ECS or building from Prefect images in CodeBuild or EC2.

**Comment by jcrist** [comment]
We're going to avoid doing this for now. Users are free to copy over images to ECR themselves as needed.
