### ISSUE TITLE
More Detailed Warning Messaged Around Using Local Storage

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4386]
## Current behavior
LocalStorage saves flows by default in a local that looks like `Users/username`. LocalStorage and LocalRun work well together because Prefect will able to find the Flow in that default location. The issue is when we combine LocalStorage with other RunConfigs. Users will get an error that looks like `Failed to load and execute Flow's environment: ModuleNotFoundError("No module named '/Users/kevinkho/'")` and it's not descriptive.

This happens with ECSRun and DockerRun, based on the feedback from the Slack channel. We need warning messages that specify that LocalStorage is relative to the location in the Docker container when using LocalStorage and DockerRun together. This behavior also applies with ECSRun + LocalStorage.

**Comment by dpmccabe** [comment]
For anyone else who ends up here, this is the working demo from that Slack thread:
https://github.com/kvnkho/demos/tree/main/prefect/docker_with_local_storage

(Thanks for that, I found it really helpful.)

**Comment by chris-aeviator** [comment]
ok..this is very confusing. No need to build the docker image , but this is totally undocumented in the docs in the docker section.

You will need to mount the volume that has your tasks.py when starting the docker agent. Then you'll need to set that path in storage=Local

```
prefect agent docker start --api http://localhost:4200 --show-flow-logs --volume /home/me/Dev/mypipeline/:/work
```

/home/me/Dev/mypipeline/flow.py
```
 with Flow("hello-docker", run_config=DockerRun(), storage=Local(path='/work/flow.py', stored_as_script=True)) as flow:

```

**Comment by meehawk** [comment]
@kvnkho I'd like to take this up. However, I'm slightly confused by the nature of discussion as to what needs to be done. Any guidance would be awesome!

**Comment by kvnkho** [comment]
Hi @meehawk, thanks for the interest! I can scope this out better for you. There are just some variations of Storage and RunConfig I need to get straightened out (should not take too long for me). @jakekaplan , did you ever look into this? Just wanna make sure you didn't attempt yet.

**Comment by jakekaplan** [comment]
@kvnkho nope I hadn't yet!

**Comment by kvnkho** [comment]
Ok @meehawk I am honestly starting to doubt if this is a "good first issue", but we can try. I also sensed you found this from the label, so I added a couple more labels in the repo last night. The hard part with this one is that there isn't a simple place to change an error message. Not sure how much you've used Prefect, but if anything below does not make sense and you still want to pursue this, you can reach me at kevin@prefect.io or in the Prefect Slack channel at prefect.io/slack.

**Reproducing the Error**

Flows have Storage. When a Flow is registered, it gets stored in Github, S3, Docker, etc. During Flow Run execution, Prefect pulls the Flow from Storage and runs it. If users don't specify any storage, the default is Local storage, which is a serialized version of the Flow stored in the `.prefect` folder of your home directory.

The easiest way to reproduce this error is to register a Flow of Machine A with the default Local storage and then run it with an agent on Machine B. This error will be raised because the agent on Machine B will try to find the Flow file in the `.prefect` folder of the home directory but it won't be present.

The comments above had a variation of this issue. They registered with the default Local Storage. They then tried to run Flows with a Docker RunConfiguration. The Docker RunConfiguration spins up a new container to execute the Flow in. The issue is then that the Storage will still be "Users/kevinkho/.prefect/...". The Flow Run will look for this path inside the newly spun up container but it won't exist. That will lead to this error.

**Understanding the cause**

This happens because when Prefect runs the Flow from storage, it imports that file as a module and pulls the Flow. The import here breaks because the file does not exist, which is why we get `ModuleNotFoundError`

**Starting point**

I strongly suspect the error happens in [these lines](https://github.com/PrefectHQ/prefect/blob/d44b72a950ebda9f7bc6a9712fc71e2e9c680d25/src/prefect/storage/local.py#L91-L100). 

**Potential Solution**

I think you need to figure out the code path that raises this error, and then we can use a try-except to see if `ModuleNotFoundError` is raised, and then from here we can raise a better error.

**Comment by meehawk** [comment]
@kvnkho thank you so much. Trying to make a sense out of it. I think I am starting to understand it a bit. It does appear daunting for a first issue. However, you are OP given you've explained it so beautifully. Definitely hit you up on Slack to see if I get stuck
