### ISSUE TITLE
StartFlowRun Task project_name parameter behaviour differs from docstring

### ISSUE THREAD

**Issue by xyxz-web** [PrefectHQ/prefect#4390]
## Description
According to the docstring, StartFlowRun's project_name parameter should not be set for direct runs with prefect core.
However, there is no branch like this in the actual code - it always fails when project_name is empty.

Also see docs at https://docs.prefect.io/api/latest/tasks/prefect.html

## Expected Behavior
Either change the behavior or the docstring

**Comment by zangell44** [comment]
cc @madkinsz related to your flow run work, can we include either a docs fix or behavior change here?

**Comment by madkinsz** [comment]
#4563 adds a new task for creating flow runs entirely

**Comment by lukekentwell** [comment]
This documentation error stung me today. Is it possible at all to use StartFlowRun on the core server backend (i.e. without providing a project name)?

**Comment by madkinsz** [comment]
Prefect Server has projects as well, are you talking about `flow.run()`?
