### ISSUE TITLE
Datetime.now() doesn't update for scheduled flows

### ISSUE THREAD

**Issue by norangai** [PrefectHQ/prefect#4408]
# Description
Datetime.now() in tasks is not updating when the flow is scheduled to run everyday, instead, it is always the date that the scheduled flow first start. We also tried with prefect.context.today and prefect.context.scheduled_start_time, but these two also doesn't update. This flow is a subflow inside a master flow.

# Expected Behavior
The flow is scheduled to run everyday, we want to get the current date everyday so that we can retrieve updated information from a external API.

# Reproduction 
In Master flow:
```
schedule = IntervalSchedule(interval=timedelta(days=1))
```
```
flow_A = StartFlowRun(flow_name="flow-A", project_name="testing", wait=True)

with Flow("master-flow", schedule=schedule) as flow:
   flow_A()
```

In flow_A:
```
@task
def get_current_date():
    logger = prefect.context.get("logger")
    logger.info(f"Today's date is {datetime.now().strftime('%Y-%m-%d')}")
    return

with Flow("flow-A", executor=LocalDaskExecutor()) as flow:
    get_current_date()
 ```

**Comment by kvnkho** [comment]
Hey @norangai , I tried to replicate your issue but could not. The code I used is attached. I ran this flow every minute and saw the timestamp produce by `datetime.now` was changing as expected. Could you try it with the code I attached? Are you on Prefect Cloud or Server? I suspect this is specific to the way you are using `datetime.now` inside your Python script. 

```python
import prefect
from prefect import Flow, task
from prefect.schedules import IntervalSchedule
from prefect.executors import LocalDaskExecutor
from prefect.tasks.prefect import StartFlowRun

from datetime import datetime, timedelta

schedule = IntervalSchedule(interval=timedelta(minutes=1))

@task
def get_current_date():
    logger = prefect.context.get("logger")
    logger.info(f"Today's date is {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    return

with Flow("flow-A", executor=LocalDaskExecutor()) as flow_a:
    get_current_date()

flow_A = StartFlowRun(flow_name="flow-A", project_name="tutorial", wait=True)

with Flow("master-flow", schedule=schedule) as flow:
   flow_A()

flow_a.register('tutorial')
flow.register('tutorial')
```

**Comment by norangai** [comment]
We ran through more test and solve this issue by deleting and re-registering the flow.
