### ISSUE TITLE
Flow Register can result in invalid registration

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#4422]
## Description
When using flow.register(build=False) this will cause the flow location metadata to be populated as `{}` in the database, which makes it impossible to run the Flow. However, all the healthcheck.py tests will pass and register the flow as if it's good.

## Expected Behavior
If a flow cannot be ran, it should not pass healthchecks.py and/or not be allowed to be registered.

This seems related to this line:
https://github.com/PrefectHQ/prefect/blob/0.14.16/src/prefect/client/client.py#L797

Perhaps a warning or assertion should be included here to validate that `storage.flows` is not an empty dict.

Or maybe have some intelligent default that will parse the `/opt/prefect/flows` directory when/if nothing is provided?

## Reproduction
flow.register(build=False)

**Comment by zangell44** [comment]
Hi @szelenka, thanks for taking the time to write this up.

Passing `build` controls whether or not Prefect builds the storage associated with the flow when registering. 

`build=False` should not be passed if you want the flow to be added to storage.
