### ISSUE TITLE
"RUN pip install pip --upgrade" breaks Docker layer caching

### ISSUE THREAD

**Issue by lukeorland** [PrefectHQ/prefect#4425]
## Current behavior

When this Prefect base image was built, a 
```
Step 3/10 : RUN pip install pip --upgrade
 ---> Running in d60e29178e1f
Collecting pip
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-21.0.1
Removing intermediate container d60e29178e1f
```

If the above step didn't happen, then the subsequent step of running `pip install ...` wouldn't be re-run unless the list of packages to pip-install is altered. Rebuilding the pip packages layer is time-consuming and causes a big layer to be pushed to the registry on every rebuild.

Is there a concern that the extant version of pip in the Prefect base image could become incompatible with python package repositories over time?

## Proposed behavior
Proposal:
Remove the `RUN pip install pip --upgrade` step and just use the pip that was installed when the base image was created.

## Example
If I tweak the workflow definition without changing the `python_dependencies`, then the cached `RUN pip install ...` layer would be reused and not pushed to the registry.

**Comment by madkinsz** [comment]
Hey @lukeorland -- I'm under the impression that a `RUN` command only invalidates the cache if the contents of the command have changed. I don't think this line should invalidate your cache. Perhaps this is related to https://github.com/PrefectHQ/prefect/pull/4584 instead?
