### ISSUE TITLE
Docs Issue - Kubernetes agent CLI options

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#4431]
Hello!

I've found an issue here:`Generate a supervisord.conf file for a Local agent`

Page reference: https://docs.prefect.io/api/latest/cli/agent.html

it should read: 'Generate a deployment.yml file for a Kubernetes Agent`

**Comment by yashlad681** [comment]
Hey @zach-angell do you mind if I take up this issue?

**Comment by yashlad681** [comment]
Hey @zangell44 
I get below error while pushing code do I need any access ? if not can you help with this?

`remote: Permission to PrefectHQ/prefect.git denied to yashlad681.
fatal: unable to access 'https://github.com/PrefectHQ/prefect.git/': The requested URL returned error: 403`

Thank you.

**Comment by harshalchaudhari35** [comment]
@zangell44 is this still up for grabs? don't see much activity or PR for this...I can take it up if still open
