### ISSUE TITLE
Restarting mapped task which uses flatten from prefect cloud throws TypeError("object of type 'NoneType' has no len()")

### ISSUE THREAD

**Issue by jeremytee97** [PrefectHQ/prefect#4455]
## Description

When restarting a flow from Prefect Cloud, it fails when attempting to restart for my mapped task. I realized it happens when I am using `flatten` - in the `invoke_lambda` method.  I have all of my previous inputs, all cached in s3Result. 
![image](https://user-images.githubusercontent.com/37123816/116499492-d97d3680-a8de-11eb-96ef-e7a6f90f5517.png)

Here are the error logs from the cloud
![image](https://user-images.githubusercontent.com/37123816/116499169-139a0880-a8de-11eb-974d-7b3bd55b27c3.png)

It is weird because if I were to create a new flow run, it would be able to run without any issues. I have posted it on the slack channel and Kevin Kho was able to reproduce it!

link to our slack conversation - https://prefect-community.slack.com/archives/CL09KU1K7/p1619596538209400
## Expected Behavior

Since I have cached all the previous steps in s3Results, it is supposed to be able to rerun from where it failed. 

## Reproduction

```import json
import boto3
from prefect import Flow, flatten, task
from prefect.engine import signals
from prefect.engine.results.s3_result import S3Result
from prefect.executors import LocalExecutor
from prefect.run_configs import LocalRun
from prefect.storage import S3

@task(
    name="get_names",
    target="result/{flow_name}/{flow_run_name}/{task_full_name}",
    checkpoint=True,
    result=S3Result("prefect-flow"),
)
def get_names():
    return ["Peter", "James", "Gee"]

@task(
    name="get_skills",
    target="result/{flow_name}/{flow_run_name}/{task_full_name}",
    checkpoint=True,
    result=S3Result("prefect-flow"),
)
def get_skills(name):
    skills_mapping = {
        "Peter": ["IT", "Accounting"],
        "James": ["Mathematics", "English"],
        "Gee": ["Python", "SQL"],
    }
    return skills_mapping.get(name, [])

@task(
    name="invoke_lambda",
    target="result/{flow_name}/{flow_run_name}/{task_full_name}",
    checkpoint=True,
    result=S3Result("prefect-flow"),
)
def invoke_lambda(skill):
    print(f"invoking lambda with skill: {skill}")
    lambda_client = boto3.client("lambda", region_name="ap-southeast-1")
    response = lambda_client.invoke(
        FunctionName="prefect-test", Payload=json.dumps(skill)
    )
    payload = json.loads(response["Payload"].read())
    if payload.get("errorMessage"):
        raise signals.FAIL()
    return payload

with Flow(
    "pikachu",
    executor=LocalExecutor(),
    run_config=LocalRun(),
    storage=S3(
        bucket="prefect-flow",
    ),
) as flow:
    names = get_names()
    skills = get_skills.map(names)
    response = invoke_lambda.map(flatten(skills))

flow.register(
    project_name="jeremy",
    labels=["dev"],
)



## Environment
{
  "config_overrides": {
    "cloud": {
      "agent": {
        "auth_token": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.16-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.15",
    "python_version": "3.8.5"
  }
}

**Comment by novotl** [comment]
Thank you for writing up the issue 👍 , we're observing the same behaviour. Restarting failed run with S3Result that uses `map` and `flatten` operations leads to `object of type 'NoneType' has no len()` error.

**Comment by jeremytee97** [comment]
@novotl will this be fixed in the upcoming releases?

**Comment by novotl** [comment]
> @novotl will this be fixed in the upcoming releases?

@jeremytee97 Sorry for the late reply, I don't know. I was just saying that we're observing the same issue as you are. You may want to check https://github.com/PrefectHQ/prefect/issues/3631 or https://github.com/PrefectHQ/prefect/issues/4084 which seem to be related to this issue.

**Comment by madkinsz** [comment]
This should be resolved by https://github.com/PrefectHQ/prefect/pull/5337, let me know if there are additional issues.
