### ISSUE TITLE
Milvus - prefect integration? 

### ISSUE THREAD

**Issue by MayetG** [PrefectHQ/prefect#4456]
Currently using prefect server in with a Kubernetes agent - using prefect to ingest data from snowflake(SnowflakeQuery) and cosmosdb(CosmosDBQueryItems) and to be stored in Milvus.  https://milvus.io/docs/v0.11.0/milvus_operation.md

I am able run the flow locally and save to a milvus collection, when I attempt to register it, I get `ModuleNotFoundError: No module named 'milvus'` from the healthcheck

pymilvus==0.2.14 along with other tools is beining installed from the docker file.
https://milvus.io/docs/v0.11.0/milvus_operation.md

is there a way to integrate prefect with milvus for tasks(like the cosmosdb and snowflake integration)?

**Comment by madkinsz** [comment]
Hey @MayetG -- what storage are you using and how do you intend to run your flow?

https://docs.prefect.io/orchestration/flow_config/docker.html#installing-extra-dependencies-at-runtime and the docs that follow may be helpful; you can install this package for use with your tasks.
