### ISSUE TITLE
Timeout when trying to retrieve large logs with the command line tool.

### ISSUE THREAD

**Issue by j3pic** [PrefectHQ/prefect#4471]
## Description

I had a failed flow run. I wanted to know why. So I ran this command:

    prefect get logs --name spry-ringtail

The result was this error:

    Traceback (most recent call last):                                                                                                                                             
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request                                                   
        six.raise_from(e, None)                                                                                                                                                    
      File "<string>", line 3, in raise_from                                                                                                                                       
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request                                                   
        httplib_response = conn.getresponse()                                                                                                                                      
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 1321, in getresponse                                                                             
        response.begin()                                                                                                                                                           
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 296, in begin                                                                                    
        version, status, reason = self._read_status()                                                                                                                              
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/http/client.py", line 257, in _read_status                                                                             
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                                                                   
      File "/home/agent/.pyenv/versions/3.7.3/lib/python3.7/socket.py", line 589, in readinto                                                                                      
        return self._sock.recv_into(b)                                                                                                                                             
    socket.timeout: timed out                                                                                                                                                      

I tried running it with `strace`. I saw that the timeout happens in a call to [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html):

    munmap(0x7f6712a74000, 43116)           = 0                                                                                                                                    
    openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 6                                                                                                                         
    lseek(6, 0, SEEK_CUR)                   = 0                                                                                                                                    
    fstat(6, {st_mode=S_IFREG|0644, st_size=636, ...}) = 0                                                                                                                         
    read(6, "127.0.0.1 localhost\n\n# The follo"..., 4096) = 636                                                                                                                   
    lseek(6, 0, SEEK_CUR)                   = 636                                                                                                                                  
    read(6, "", 4096)                       = 0                                                                                                                                    
    close(6)                                = 0                                                                                                                                    
    socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 6                                                                                                                     
    setsockopt(6, SOL_TCP, TCP_NODELAY, [1], 4) = 0                                                                                                                                
    ioctl(6, FIONBIO, [1])                  = 0                                                                                                                                    
    connect(6, {sa_family=AF_INET, sin_port=htons(4200), sin_addr=inet_addr("10.128.0.229")}, 16) = -1 EINPROGRESS (Operation now in progress)                                     
    poll([{fd=6, events=POLLOUT|POLLERR}], 1, 30000) = 1 ([{fd=6, revents=POLLOUT}])                                                                                               
    getsockopt(6, SOL_SOCKET, SO_ERROR, [0], [4]) = 0                                                                                                                              
    poll([{fd=6, events=POLLOUT}], 1, 30000) = 1 ([{fd=6, revents=POLLOUT}])                                                                                                       
    sendto(6, "POST /graphql HTTP/1.1\r\nHost: pr"..., 243, 0, NULL, 0) = 243                                                                                                      
    poll([{fd=6, events=POLLOUT}], 1, 30000) = 1 ([{fd=6, revents=POLLOUT}])                                                                                                       
    sendto(6, "{\"query\": \"query {\\n    flow_run"..., 303, 0, NULL, 0) = 303                                                                                                    
    ioctl(6, FIONBIO, [1])                  = 0                                                                                                                                    
    poll([{fd=6, events=POLLIN}], 1, 30000) = 0 (Timeout)                                                                                                                          

This indicates that there's a long delay on the server side (which is Prefect Core) before any data is sent.

I edited /home/agent/.pyenv/versions/3.7.3/lib/python3.7/socket.py to set the timeout
on `self.sock` to 32767 seconds. Then I was able to retrieve a 276 MB log.

## Expected Behavior

I expected the command to work without any undue difficulty.

## Reproduction

Write a flow that generates hundreds of megabytes of logs. Then try to retrieve those logs with the command line tool.

## Environment
```
{
  "config_overrides": {
    "server": {
      "host": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1040-gcp-x86_64-with-debian-bullseye-sid",
    "prefect_backend": "server",
    "prefect_version": "0.14.2",
    "python_version": "3.7.3"
  }
}
```
Using a Kubernetes agent and Dask (deployed as a cluster of cloud VMs). Using GKE for Kubernetes. Using a dedicated server for Prefect Core. The command was run from the agent server.

**Comment by madkinsz** [comment]
See also https://github.com/PrefectHQ/prefect/issues/4719
