### ISSUE TITLE
Custom Tasks that have information that can be visualized/edited in the UI.

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4476]
## Current behavior

Prefect [Parameters](https://docs.prefect.io/core/concepts/parameters.html#parameters) are Tasks that result in special abilities in the Prefect UI. For example, they can be viewed and editited through the Prefect UI:

![Prefect UI Parameter](https://docs.prefect.io/orchestration/tutorial/hello-flow-run-parameter-config.png)

## Proposed behavior
Open up the ability for other Tasks to render information, or make information editable, in the Prefect UI by exposing an API that needs to be implemented by the Task that wants to render information

## Example
For example: I currently get most of my parameter variables from environment variables being set (and want to continue doing this). Ideally I want to group related parameters into groups (e.g. by using data classes) so the resulting groups can be passed around to wherever they are needed. For example, I currently fetch my parameters to communicate with my Kafka service via this custom task:
```python
class GetKafkaConfig(prefect.Task):
    """
    Get Kafka configuration
    """
    def run(
                self,
                timeout: timedelta
            ) -> KafkaConfig:
        return KafkaConfig(
            broker_address=os.environ['KAFKA_BROKER_ADDRESS'],
            topic_name=os.environ['KAFKA_TOPIC_NAME'],
            timeout=timeout
        )
```
I would like to visualize these parameters in my prefect UI (and ideally make them editable), similar to how Parameter tasks can be visualized.

Related Slack discussion: https://prefect-community.slack.com/archives/CL09KU1K7/p1620030246477000

**Comment by madkinsz** [comment]
I think this could be part of https://github.com/PrefectHQ/prefect/issues/2254 allowing for a "TypedParameter" to display nicely in the UI.

cc @zhen0 @znicholasbrown for UI roadmap consideration
