### ISSUE TITLE
[DOCS] dask_kubernetes.KubeCluster with a DaskExecutor Does Not Start If n_workers is Unspecified

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4484]
## Current behavior

@ciaranevans reported that using DaskExecutor with `dask_kubernetes.KubeCluster` on Azure Kubernetes service resulted in flows that were being pulled, but not being executed. The logs just show that the flow run starts and the cluster gets created and then is left hanging. Presumably what fixed it was specifying the maximum number of workers in `adapt_kwargs`.  This looks like it is dask_kubernetes specific, and might happen on all cloud providers.

```python
executor=DaskExecutor(
    cluster_class="dask_kubernetes.KubeCluster",
    cluster_kwargs={
        "pod_template": make_pod_spec(
            image=os.environ["AZURE_BAKERY_IMAGE"],
            labels={
                "flow": flow_name
            },
            memory_limit=None,
            memory_request=None,
        )
    },
    adapt_kwargs={"maximum": 10}
)
```

## Proposed behavior

Given this is an optional argument, it is not clear that the number of workers is needed for it to run. We may either provide a default that gets it running and/or specify this is needed in the docs to get dask_kubernetes.KubeCluster running flows.

**Comment by ciaranevans** [comment]
Thanks for raising this @kvnkho!

It's a tricky one to say where the solution lies, `KubeCluster` could require `n_workers`, but then that's not helpful if the end user wants to use `adapt_kwargs` on `DaskExecutor` 😅

**Comment by ShardPhoenix** [comment]
I just got bit by this one - was wondering why my jobs weren't starting. It seems `adapt_kwargs` overrides `n_workers` so it's ok to have both.

**Comment by madkinsz** [comment]
Gee, this is a tricky one indeed. I guess we could add a warning in Prefect but it seems like it is really the responsibility of `KubeCluster` to choose a reasonable default number of workers or warn if it's unset. Is there an issue on https://github.com/dask/dask-kubernetes ?
