### ISSUE TITLE
Rename states that don't fit pattern (RESUME, SUCCESS)?

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#451]
States are generally adjectives that end the sentence "the task is ____": pending, scheduled, failed, skipped, etc.

Two that break the pattern are RESUME and SUCCESS. 

Should we:
1. do nothing
1. consider renaming them RESUMING and SUCCESSFUL
1. consider renaming other states (FAIL, SKIP, RETRY) -- RETRYING has always bothered me, I prefer RETRY
1. none of the above

**Comment by dylanbhughes** [comment]
I vote for RESUMING and SUCCESSFUL.

**Comment by itsngansense** [comment]
RETRYING
FAILED
SKIPPED

**Comment by lauralorenz** [comment]
Closing as we consider the work to change it limited compared to the value we are aware we could get from it.
