### ISSUE TITLE
Docs Issue - Control Flow Tasks and skipped tasks

### ISSUE THREAD

**Issue by shaleh** [PrefectHQ/prefect#4518]
Hello!

I've found an issue here:`The task doesn't run is Skipped, as are all downstream tasks that don't set skip_on_upstream_skip=False.`

Page reference: https://docs.prefect.io/api/latest/tasks/control_flow.html

The language is not clear here. Is this meant to say "The task not run is marked 'Skipped', ......"?

**Comment by tpdorsey** [comment]
The language used at https://docs.prefect.io/api/latest/tasks/control_flow.html#functions seems most clear and could be re-used throughout the page (with edits as needed) for clarity.

**Comment by tpdorsey** [comment]
Specifically this applies to the `prefect.tasks.control_flow.conditional.ifelse` description.

Second paragraph of the description should be "If the condition evaluates True(ish), the `true_task` will run. If it evaluates False(ish), the `false_task` will run. The task that doesn't run is Skipped, as are all downstream tasks that don't set `skip_on_upstream_skip=False`."

**Comment by tpdorsey** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/8182
