### ISSUE TITLE
Agent start not respecting config id flag

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/prefect#4522]
## Description
Both Docker and k8s agents aren't respecting the `--agent-config-id` flag.

## Expected Behavior
An agent to come up with the correct id.

## Reproduction
1. Use the "automations" UI in Prefect cloud to set up an agent SLA (note: after doing this, as expected, I receive an alert that the SLA is not passing)
2. Copy the agent config id from the tooltip for that automation
3. Start an agent: `prefect agent docker start --token $PREFECT_AGENT_API_KEY --agent-config-id $PREFECT_AGENT_CONFIG_ID`
4. Agent ID in the UI is different, after after destroying all agents started with the --agent-config

## Environment
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.2.5",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.17",
    "python_version": "3.8.8"
  }
}
```

k8s agent is using `prefecthq/prefect:0.14.17-python3.8` image for the deployment

**Comment by madkinsz** [comment]
Hey @jnoynaert 

Just want to clarify here, agents all have unique ids even when a config id is passed. The config id _links_ that agent to a config in the backend that multiple unique agents can share. This is a little confusing as displayed in the UI currently and there's an in-progress PR to improve the agents page but we wanted to get this feature out for the users that need it.

You can confirm that the agent config id is set in the interactive API:
```graphql
query {
  agents {
    id
    agent_config_id
  }
}
```

**Comment by jnoynaert** [comment]
@madkinsz that's absolutely it. I was expecting the UI or agent log to show the config id and should have tested the actual functionality further. Thanks for the fast response as always!

**Comment by madkinsz** [comment]
@jnoynaert, you're welcome! Appreciate that you're catching things.

https://github.com/PrefectHQ/prefect/pull/4524 should help.
