### ISSUE TITLE
No logging in Debug if agent unable to access Internet

### ISSUE THREAD

**Issue by bmcollier** [PrefectHQ/prefect#4546]
## Description
If the agent cannot contact the server, it goes mute, doesn't log out an error message even in debug mode, and responds to health endpoint requests with a connection refused.

## Expected Behavior
The agent should log out INFO: Unable to contact server or similar, and return an HTTP error code with appropriate status in JSON to explain the fault. As it stands, the refused connection means that AWS health checks fail inexplicably with nothing appearing in Cloudwatch, making it difficult to isolate the source of the fault.

## Reproduction
Turn off wifi on your machine. Run the agent with debug-level logging on, watch the lack of a message, and then attempt to call the health check endpoint.

**Comment by madkinsz** [comment]
Hey @bmcollier

Thanks for sharing this issue. What version of Prefect are you using?
