### ISSUE TITLE
DaskExecutor RuntimeError and hangs on simple DFE example

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4555]
## Description

I'm getting the following error when trying to run a simple example of the [DFE functionality](https://medium.com/the-prefect-blog/map-faster-mapping-improvements-in-prefect-0-12-0-7cacc3f14e16):
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
```

[See full log here](https://github.com/PrefectHQ/prefect/files/6506390/flow_runtime_error.log)

Besides the error, the flow run also seems to hang indefinitely.

## Expected Behavior

RuntimeError not to happen.

## Reproduction
Run `❯ python flow.py`:
```python
import time
from prefect import task, Flow
from prefect.executors import DaskExecutor


@task
def times():
  return [1, 5, 10]


@task
def sleep(x):
  print(f'sleeping for {x}')
  time.sleep(x)
  print(f'done sleeping for {x}')
  return x


with Flow("mapping-test") as flow:
  sleep.map(sleep.map(times))


flow.run(executor=DaskExecutor())
```

- This runs fine when running the default LocalExecutor.
- This runs fine when using a threaded default `LocalDaskExecutor()`
- The same RuntimeError is shown when running with `LocalDaskExecutor(scheduler="processes")`. However, in this case I can still see my tasks running, and the flow actually finishes.

## Environment

Prefect installed via conda-forge in a clean conda environment.
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.8.0-53-generic-x86_64-with-glibc2.31",
    "prefect_backend": "server",
    "prefect_version": "0.14.19",
    "python_version": "3.9.4"
  }
}
```
- Dask version: `2021.05.0`
- I get the same issue on Python 3.8
- I get the same issue when installing Prefect via pip in a clean 3.8 environment

**Comment by madkinsz** [comment]
Hey @peterroelants -- that error is dask specific. You'll need to wrap your execution in a `__main__` check block

```python
if __name__ == "__main__":
    flow.run(executor=DaskExecutor())
```

**Comment by peterroelants** [comment]
I see, thanks, this solves the issue!
