### ISSUE TITLE
unittest with TaskRunner > AttributeError

### ISSUE THREAD

**Issue by therinz** [PrefectHQ/prefect#4564]
## Description

I'm trying to implement a simple unittest, and the output of TaskRunner is not as expecting (see below). I've tried searching the interwebs for what I'm doing wrong, but it seems to me this AttributeError shouldn't happen. 

## Expected Behavior
I expected the assertion to run and indicate test failed for a different reason.

## Reproduction
api.py
```python 
@task()
def calculate_pages(num, page_size):
    a = (num // page_size) + 1
    return range(1, 2)
```
test_api.py
```python 
import unittest
from prefect.engine import TaskRunner
from src.api import calculate_pages

class Test(unittest.TestCase):
    def test_calculate_pages(self):
        runner = TaskRunner(task=calculate_pages)
        state = runner.run(40000, 100)
        self.assertTrue(state.is_successful(), "Task calculate_pages failed")
```

Instead the code breaks and I get this traceback:
```
Traceback (most recent call last):
  File "C:\Users\***\projects\pipeline\venv\lib\site-packages\prefect\engine\task_runner.py", line 236, in run
    state, context = self.initialize_run(state, context)
  File "C:\Users\***\projects\pipeline\venv\lib\site-packages\prefect\engine\task_runner.py", line 143, in initialize_run
    run_count = state.context.get("task_run_count", 1)
AttributeError: 'int' object has no attribute 'context'
[2021-05-21 15:15:24+0200] INFO - prefect.TaskRunner | Task 'calculate_pages': Finished task run for task with final state: 'Failed'
```

## Environment
Python 3.9.1 in standard pip venv on Windows 10. This is run locally of course.

**Comment by zangell44** [comment]
Hi @therinz!

Testing with the task runner can be tricky, since it expects context from the Prefect API.

Would something like the following work for you?

```python
from prefect import task

@task()
def calculate_pages(num, page_size):
    a = (num // page_size) + 1
    return range(1, 2)

import unittest
from prefect.engine import TaskRunner

class Test(unittest.TestCase):
    def test_calculate_pages(self):
        result = calculate_pages.run(40000, 100)
        self.assertEqual(result, range(1,2))
```

If you're trying to get at something else in your test case, I'm happy to work through other approaches.

Unrelated to this failure - please keep in mind Python 3.9 support is still experimental.

**Comment by therinz** [comment]
Hey @zangell44, thanks for the quick reply! 

This means I would either need to reproduce the production code in the testing suite or have the tests within the production code, both is undesirable. However, from your answer I understand the context is not fully handed down by just using `TaskRunner`.

In the meantime I stumbled upon the tests in the Prefect Github and using the same format does work. So:
```python
def test_string_formatter_simply_formats():
    task = StringFormatter(template="{name} is from {place}")
    with Flow(name="test") as f:
        ans = task(name="Ford", place="Betelgeuse")
    res = f.run()
    assert res.is_successful()
    assert res.result[ans].result == "Ford is from Betelgeuse"
```

Thanks again!

**Comment by zangell44** [comment]
Nice!

**Comment by zangell44** [comment]
resolved
