### ISSUE TITLE
Restarting mapped child task restarts parent

### ISSUE THREAD

**Issue by itctraining** [PrefectHQ/prefect#4569]
The issues happen when:

1. flow starts
2. some tasks run successfully
3. a mapped parent task starts
4. one of the child tasks fail
5. enter the mapped child instance on the UI
6. press restart

This causes the parent task to restart instead of the specified child. BTW, changing states for child tasks work as intended.

**Comment by madkinsz** [comment]
@itctraining I think this has to happen because the mapped parent is dynamic and could create different children on restart. There's an open issue for improving the usability of caching for mapped tasks at https://github.com/PrefectHQ/prefect/issues/4507 which may resolve your problem.

**Comment by itctraining** [comment]
@madkinsz Isn't the whole point of mapped tasks is being dynamic? And how is it different from being able to change the state of a child task, which works perfectly?

**Comment by madkinsz** [comment]
Indeed it is the whole point. That's why the implication is that restarting it will restart the full mapping and you'll want to rely on caching to ensure that things are not re-run. Changing the state of a single task is very different than restarting a run, in that case, you're just manually assigning a new state in the backend.

Regardless, we can look into if there's a way to restart a mapped task in the way you're asking about.

**Comment by itctraining** [comment]
Gotcha. So for now I don't have a good way of doing this but to add the caching logic into the child tasks (bad from an engineering POV). Since each child runs for 6-12 hours, that's a big problem. Would be great to see this resolved.

Thanks

**Comment by madkinsz** [comment]
> but to add the caching logic into the child tasks 

Why is this bad? Prefect handles the caching for you with just a little configuration

**Comment by itctraining** [comment]
I was talking about adding the caching logic to the task itself, which is considered "bad engineering". If this is an external configuration I can simply add, I'll be happy if you'd point me to the relevant documentation.

**Comment by madkinsz** [comment]
See the example at https://github.com/PrefectHQ/prefect/issues/4507 and docs at https://docs.prefect.io/core/concepts/persistence.html
