### ISSUE TITLE
`state.results` is empty in `terminal_state_handler` when running through an agent

### ISSUE THREAD

**Issue by Kazy** [PrefectHQ/prefect#4570]
## Description

Following [this discussion](https://prefect-community.slack.com/archives/CL09KU1K7/p1621525420208300) on Slack, I tried to implement a `terminal_state_handler` to output the results of some of the tasks to Slack. This worked great locally (i.e. though `flow.run()`). But when moving to the Cloud, I kept getting an empty dictionary in `state.result` of the handler.

I looked into Prefect's code and the reason is that the `return_tasks` argument in `FlowRunner.run` function is always `None`, which means that in `get_flow_run_state` `return_states` is empty. If I'm understanding things correctly, this first go through [`cli/execute.py`](https://github.com/PrefectHQ/prefect/blob/7f80fb52a89947ef1aef0232047994403b3b77e1/src/prefect/cli/execute.py#L74) where we don't give any additional argument to the `run()` function. In `Flow._run` though, which is called when I'm developing locally, we have [`return_tasks=self.tasks`](https://github.com/PrefectHQ/prefect/blob/7f80fb52a89947ef1aef0232047994403b3b77e1/src/prefect/core/flow.py#L1083), giving the expected behavior.

## Expected Behavior

One of two things:
- Have access to `state.result` in `terminal_state_handler`. A lower requirements is to just have access to a mapping of tasks with their results.
- Or have an other way to implement what I'm trying to do, that is an handler run at the end of a flow, with access to the tasks and their associated tasks, in order to send a summary message on Slack.

## Reproduction
```python
from typing import Set

import prefect
from prefect import Flow, task
from prefect.engine.state import State


@task
def foo() -> None:
    return None


@task
def it_fails() -> None:
    raise RuntimeError()


def terminal_state_handler(
    flow: Flow, state: State, reference_task_states: Set[State]
) -> None:
    logger = prefect.context.get("logger")
    logger.info(state.result.items())


with Flow("test-flow", terminal_state_handler=terminal_state_handler) as flow:
    foo()
    it_fails()

WORKING_PATH = True

if WORKING_PATH:
    # state.result won't be empty
    flow.run()
else:
    # Adapt to your own environment, and then run the flow after registering it
    flow.register(project_name="dev")
```

**Comment by Kazy** [comment]
I got an answer from Kevin Kho on Slack the moment I posted this: this seems to be as excepted, and one should go through Prefect's API to obtain the tasks state. I'll let you decide if this should be closed or not !

**Comment by madkinsz** [comment]
I think we should clarify the documentation here or improve this state handler to meet expectations (or both).

**Comment by zangell44** [comment]
+1 @madkinsz I think we should do both. I was hoping to wait until your `flow.run` improvements were shipped to take another pass at both the state handler and the docs

**Comment by anna-geller** [comment]
Adding this issue here since it seems to be the same. A user asked [on Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1642165590031000) why a list of task run states can be accessed in a state handler in a local flow run, but not in a backend-triggered flow run.  Here is an example that shows the issue:

```python
import prefect
from prefect import task, Flow
from prefect.engine.state import Finished


@task
def say_hi():
    print("Hi")


@task
def say_hello():
    print("Hello")


def flow_state_handler(obj, old_state, new_state):
    if isinstance(new_state, Finished):
        logger = prefect.context.get("logger")
        logger.info(new_state)
        logger.info(new_state.result)
        logger.info(new_state.result.items())


with Flow("print_states_flow_level", state_handlers=[flow_state_handler]) as flow:
    t1 = say_hi()
    t2 = say_hello()
    flow.set_reference_tasks([t1, t2])


if __name__ == "__main__":
    state = flow.run()
```

The output:
```shell
[2022-01-14 15:00:19+0100] INFO - prefect.FlowRunner | Beginning Flow run for 'print_states_flow_level'
[2022-01-14 15:00:19+0100] INFO - prefect.TaskRunner | Task 'say_hi': Starting task run...
Hi
[2022-01-14 15:00:19+0100] INFO - prefect.TaskRunner | Task 'say_hi': Finished task run for task with final state: 'Success'
[2022-01-14 15:00:19+0100] INFO - prefect.TaskRunner | Task 'say_hello': Starting task run...
Hello
[2022-01-14 15:00:19+0100] INFO - prefect.TaskRunner | Task 'say_hello': Finished task run for task with final state: 'Success'
[2022-01-14 15:00:19+0100] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[2022-01-14 15:00:19+0100] INFO - prefect | <Success: "All reference tasks succeeded.">
[2022-01-14 15:00:19+0100] INFO - prefect | {<Task: say_hi>: <Success: "Task run succeeded.">, <Task: say_hello>: <Success: "Task run succeeded.">}
[2022-01-14 15:00:19+0100] INFO - prefect | dict_items([(<Task: say_hi>, <Success: "Task run succeeded.">), (<Task: say_hello>, <Success: "Task run succeeded.">)])
```
But running the same through Prefect Cloud results in an empty dictionary:
```shell
└── 15:00:02 | DEBUG   | Checking flow run state...
└── 15:00:02 | INFO    | Flow run SUCCESS: all reference tasks succeeded
└── 15:00:02 | DEBUG   | Flow 'print_states_flow_level': Handling state change from Running to Success
└── 15:00:02 | INFO    | <Success: "All reference tasks succeeded.">
└── 15:00:02 | INFO    | {}
└── 15:00:02 | INFO    | dict_items([])
└── 15:00:03 | DEBUG   | Exited flow run subprocess.
Flow run succeeded!
```
The same is true when attaching a terminal_state_handler instead of a normal flow-level state handler:
```python
import prefect
from prefect import task, Flow


@task
def say_hi():
    print("Hi")


@task
def say_hello():
    print("Hello")


def flow_state_handler(flow, state, reference_task_states):
    logger = prefect.context.get("logger")
    logger.info(state)
    logger.info(state.result)
    logger.info(state.result.items())


with Flow("print_states_terminal", terminal_state_handler=flow_state_handler) as flow:
    t1 = say_hi()
    t2 = say_hello()


if __name__ == "__main__":
    state = flow.run()
```
Local:
```shell
[2022-01-14 15:03:37+0100] INFO - prefect | <Success: "All reference tasks succeeded.">
[2022-01-14 15:03:37+0100] INFO - prefect | {<Task: say_hi>: <Success: "Task run succeeded.">, <Task: say_hello>: <Success: "Task run succeeded.">}
[2022-01-14 15:03:37+0100] INFO - prefect | dict_items([(<Task: say_hi>, <Success: "Task run succeeded.">), (<Task: say_hello>, <Success: "Task run succeeded.">)])
```
Cloud:
```shell
...
└── 15:04:54 | DEBUG   | Checking flow run state...
└── 15:04:54 | INFO    | Flow run SUCCESS: all reference tasks succeeded
└── 15:04:54 | INFO    | <Success: "All reference tasks succeeded.">
└── 15:04:54 | INFO    | {}
└── 15:04:54 | INFO    | dict_items([])
└── 15:04:54 | DEBUG   | Flow 'print_states_terminal': Handling state change from Running to Success
└── 15:04:55 | DEBUG   | Exited flow run subprocess.
Flow run succeeded!
```
