### ISSUE TITLE
Typo in agent config flag in CLI

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#4590]
## Description

In the help section of the agent start instructions of the CLI, there is a small typo for the agent config flag.  
<img width="527" alt="Screen Shot 2021-05-27 at 1 45 50 PM" src="https://user-images.githubusercontent.com/40272060/119872811-df703280-bef1-11eb-9dcf-a21ce51f80de.png">

It should be --agent-config-id

## Expected Behavior

When you enter --agent-confg--id in the cli it returns an error

**Comment by zhen0** [comment]
https://github.com/PrefectHQ/ui/pull/818 fixes this in the UI!

**Comment by Emeka-darthvader** [comment]
Hi has this being fixed on the CLI? I'm new to opensource and would love to work on this! Thanks

**Comment by madkinsz** [comment]
Hey @Emeka-darthvader -- I do not believe this has been fixed. Looking forward to your PR. No need to add a changelog entry for this one.

**Comment by tpdorsey** [comment]
Confirm this was fixed in CLI as of 0.15.6
