### ISSUE TITLE
Add a parameters option when registering a flow with the CLI 

### ISSUE THREAD

**Issue by fsaldana-rseg** [PrefectHQ/prefect#4598]
## Current behavior
As a quick refresher this is ultimately what I would like to do:

- define a single flow in a file
- register that flow to a dev Prefect project with dev specific parameters
- When ready to promote, I want to register that flow to a prod Prefect project with prod specific parameters

Issues I am running into

- CLI register command does not have a param option
- Manually setting in the UI is not viable
- clocks get me partially there but when I set them in code the dev params will get sent to prod when registering to prod
- Could use a convention based StartFlowRun approach: a base flow + [flow_name]_dev with params configured + [flow_name]_prod but this approach just doesnt feel right and will rely on some CI/CD magic to pick flows to register
- Custom GraphQL 

## Proposed behavior
Add an option in the register command to pass flow parameters 

## Example
This will allow me to decouple the flow and the params.
Meaning I can have a single flow and register in dev with dev specific params.
Then register that same flow in prod with prod specific params.

**Comment by madkinsz** [comment]
Hey @fsaldana-rseg 

Is the concern here that you want to have different parameter defaults for your two environments? Does something like

```python
with Flow(...) as flow:

    if os.environ.get("ENV") == "PROD":
        x = Parameter("x", default=1)
    else:
        x = Parameter("x", default=2)
```

work for your use case? (You could also do this with clocks) I'm not sure we want to complicate registration by adding parameter overrides to it. We've got some sketches of ways to support flow configuration "environments" like this in a first-class way and passing parameter defaults via the CLI and this is a case I'll keep in mind.

**Comment by fsaldana-rseg** [comment]
My use case is that my dev parameters are different than my prod parameters.
I would not have any default parameters as I cant let dev params make it to a prod run.

My flow is built using .map() to dynamically push data to multiple clusters. The dev clustering is different than the prod clustering. 

The current params looks something like this for prod

    mapped_run_name=["push1", "push2", "push3", "push4"],
    mapped_db_properties=[
        "/dbfs/mnt/blob/lab/spark-artifacts/cluster1.properties",
        "/dbfs/mnt/blob/lab/spark-artifacts/cluster2.properties",
        "/dbfs/mnt/blob/lab/spark-artifacts/cluster3.properties",
        "/dbfs/mnt/blob/lab/spark-artifacts/cluster4.properties",
    ],
    mapped_db_host=["123.123.123.123", "234.234.234.234", "333.333.333.333", "444.444.444.444"],

Dev would look something like this 

    mapped_run_name=["push_dev"],
    mapped_db_properties=[
        "/dbfs/mnt/blob/lab/spark-artifacts/dev.properties",
    ],
    mapped_db_host=["111.111.111.111"],

Does this above make sense? @madkinsz 

I suppose I could do the ENV condition to set the clock but we are trying to do all this in CI/CD and if I dev doesnt use the ENV condition then that would be a problem.
