### ISSUE TITLE
Unexpected behavior with Task slug being appended "-copy"

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4624]
## Description

I have a task with as `slug='test-slug'`. However, after running the flow, and checking the tasks in the result. I see that the slug of that specfic task has transformed into `'test-slug-copy'`, the `'-copy'` is appended.

## Expected Behavior

According to the [documentation](https://docs.prefect.io/api/latest/core/task.html#:~:text=Slugs%20provide%20a%20stable%20ID%20for%20tasks%20so%20that%20the%20Prefect%20API%20can%20identify%20task%20run%20states):
> Slugs provide a stable ID for tasks so that the Prefect API can identify task run states

I would expect the slug to be a stable ID and not to change.

## Reproduction

```python
import prefect

@prefect.task(slug='test-slug')
def task_a():
    print('Task A')

with prefect.Flow('test-flow') as flow:
    task_a()

result = flow.run()
result_task = list(result._result.value.keys())[-1]
print(result_task.slug)
# Prints: "test-slug-copy"
```

## Environment

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.10.0-1029-oem-x86_64-with-glibc2.31",
    "prefect_backend": "server",
    "prefect_version": "0.14.21",
    "python_version": "3.9.4"
  }
}
```

**Comment by madkinsz** [comment]
Thanks for the issue; I want to do some work with task slugs in the near future and I'll see if I can address this.

**Comment by anders-s** [comment]
What is the status on this?

**Comment by madkinsz** [comment]
> What is the status on this?

I have not been able to prioritize work of this and am hesitant to change the behavior as we're seeking stability. `-copy` should be always be appended.

**Comment by lanecodes** [comment]
Just to add that I've just bumped into this. Given the understandable desire to avoid breaking changes, might an acceptable workaround be to document the circumstances under which `-copy` is appended to a user specified slug in the [Task API docs](https://docs.prefect.io/api/latest/core/task.html#task-2)?
