### ISSUE TITLE
Task checkpointing creates differently behaves differently when using `signals`

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#4633]
## Description

Task checkpointing behaves differently when `SUCCESS` signals are manually raised. (see example below)

Task checkpointing is likely not the only feature that may behave differently when signals are manually raised.

We should do a quick audit of how raising signals manually will differ from actually running tasks, and either
1. Update documentation on Signals page to caution about this
2. Ensure minimal difference in function between raising signals manually and running tasks

(1) seems like the most reasonable fix here

## Expected Behavior

Without knowing the internals of Prefect, I might expect raising signals would preserve all task functionality.

## Reproduction

This if we change the task in this test case https://github.com/PrefectHQ/prefect/blob/master/tests/engine/cloud/test_cloud_task_runner.py#L529 

from
```python
@pytest.mark.parametrize("checkpoint", [True, None])
    def test_task_runner_sends_checkpointed_success_states_to_cloud(
        self, client, checkpoint
    ):
        @prefect.task(checkpoint=checkpoint, result=PrefectResult())
        def add(x, y):
            return x + y

        x_state, y_state = (
            Success(result=PrefectResult(value=1)),
            Success(result=PrefectResult(value=1)),
        )

        upstream_states = {
            Edge(Task(), Task(), key="x"): x_state,
            Edge(Task(), Task(), key="y"): y_state,
        }

        res = CloudTaskRunner(task=add).run(upstream_states=upstream_states)

        ## assertions
        assert client.get_task_run_info.call_count == 1
        assert (
            client.set_task_run_state.call_count == 2
        )  # Pending -> Running -> Successful

        states = [call[1]["state"] for call in client.set_task_run_state.call_args_list]
        assert states[0].is_running()
        assert states[1].is_successful()
        assert states[1]._result.location == "2"
```

to 

```python
@prefect.task(checkpoint=checkpoint, result=PrefectResult())
        def add(x, y):
            result = x + y
            raise SUCCESS(result=result)
```

The last line of the test will fail, since the result is never written to a location.

## Environment

N/A

**Comment by szubster** [comment]
Thread on community slack: https://prefect-community.slack.com/archives/CL09KU1K7/p1622643800313800
