### ISSUE TITLE
Schedule sub minute flows

### ISSUE THREAD

**Issue by bennnym** [PrefectHQ/prefect#4639]
I would like the ability to schedule flows every 15 seconds.

Is there a reason why you guys decided that this was not a feature that is viable?

Is there a roadmap to implement this?

The lack of this use case means that my company may not be able to adopt the service.

**Comment by bennnym** [comment]
Thanks for the response @cicdw. Much appreciated.

**Comment by kvnkho** [comment]
This effort has now been moved to Orion. At the time of this issue, Orion was not public. 

There is a good example of a blog [here](https://www.prefect.io/blog/you-no-longer-need-two-separate-systems-for-batch-processing-and-streaming/).

Will close this issue for now, but feel free to raise it again when Orion becomes stable.
