### ISSUE TITLE
Apollo GRAPHQL_VALIDATION_FAILED error on “get_or_create_task_run_info”

### ISSUE THREAD

**Issue by vikram-k** [PrefectHQ/prefect#4640]
I have several prefect flows running in a Kubernetes cluster. Recently, started getting this error when attempting to run any of the flows. Has anyone seen this before? Looks like it is happening based on the [following code in the prefect library](https://github.com/PrefectHQ/prefect/blob/1867f205405e1f68b828ce9dcf00bbd4969903bc/src/prefect/client/client.py#L1362)

> 
> Failed to retrieve task state with error: ClientError('400 Client Error: Bad Request for url: http://apollo.master:4200/graphql\n\nThe following error messages were provided by the GraphQL server:\n\n    GRAPHQL_VALIDATION_FAILED: Cannot query field "get_or_create_task_run_info" on\n        type "Mutation". Did you mean "get_or_create_task_run" or\n        "get_or_create_mapped_task_run_children"?\n\nThe GraphQL query was:\n\n    mutation {\n            get_or_create_task_run_info(input: { flow_run_id: "9b1b760e-eb6a-4014-82bf-573db2f9951e", task_id: "62e3eff8-9a22-41ce-91f4-6852aeaae382", map_index: -1 }) {\n                id\n                version\n                serialized_state\n        }\n    }\n\nThe passed variables were:\n\n    null\n')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 375, in _send_request
>     response.raise_for_status()
>   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://apollo.master:4200/graphql
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 154, in initialize_run
>     task_run_info = self.client.get_task_run_info(
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1399, in get_task_run_info
>     result = self.graphql(mutation)  # type: Any
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 298, in graphql
>     result = self.post(
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 213, in post
>     response = self._request(
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 459, in _request
>     response = self._send_request(
>   File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 388, in _send_request
>     raise ClientError(f"{exc}\n{graphql_msg}") from exc
> prefect.utilities.exceptions.ClientError: 400 Client Error: Bad Request for url: http://apollo.master:4200/graphql
> 
> The following error messages were provided by the GraphQL server:
> 
>     GRAPHQL_VALIDATION_FAILED: Cannot query field "get_or_create_task_run_info" on
>         type "Mutation". Did you mean "get_or_create_task_run" or
>         "get_or_create_mapped_task_run_children"?
> 
> The GraphQL query was:
> 
>     mutation {
>             get_or_create_task_run_info(input: { flow_run_id: "9b1b760e-eb6a-4014-82bf-573db2f9951e", task_id: "62e3eff8-9a22-41ce-91f4-6852aeaae382", map_index: -1 }) {
>                 id
>                 version
>                 serialized_state
>         }
>     }
> 
> The passed variables were:
> 
>     null

**Comment by zangell44** [comment]
Hi @vikram-k. The `get_or_create_task_run_info` route was added in Prefect Server release 2020-11-29 https://github.com/PrefectHQ/server/tree/2020-11-29.

What version of Prefect Core and Prefect Server are you using?

If you've recently upgraded Prefect Server, you may need to run migrations via the CLI `prefect-server database upgrade`

**Comment by vikram-k** [comment]
@zach-angell Thanks for your reply! We are using the helm chart for 
`prefecthq/server:core-0.13.17`

However, it looks like we recently upgraded our python library from from prefect==0.14.9 to prefect==0.14.21 - so maybe that could be it? Let me know what the recommended solution is.

**Comment by madkinsz** [comment]
Hey @vikram-k -- at the very least your prefect library should be the same minor as your server version. Patch versions are unlikely to break things so 0.13.17 is very likely compatible up to 0.13.19 but we do not ensure that the 0.14.x releases are compatible. I would recommend upgrading your Server to `core-0.14.21` to match your prefect library.
