### ISSUE TITLE
MyPy typing error when overriding Task.run()

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4649]
## Description

When overriding `Task.run()` method, e.g.:
```python
class RestTaskTest(prefect.Task):
    def run(self, string_val: str, int_val: int) -> TaskTestResult:
        return TaskTestResult(string_val=string_val, int_val=int_val)
```
And checking my code with MyPy, I get the following error:
```
error: Signature of "run" incompatible with supertype "Task"
```

## Expected Behavior

Since `Task.run()` needs to be overwritten for each task I expect the type to be compatible with all possible overrides.

[`Task.run`](https://github.com/PrefectHQ/prefect/blob/d1e4413f1fa18baef0db6dba0c053b04ce593577/src/prefect/core/task.py#L469) is defined as:
```python
def run(self) -> None:
```
At least the return type could be `Any`. However, I'm unsure if it's uberhaupt possible to type the method arguments in such as way that they are most general. I don't think `run(self, *args: Any, **kwargs: Any)` will work.

## Workarounds

- Ignore the error by adding `# type: ignore` on the line with the error.
- Annotating the overridden method with `@defaults_from_attrs()` (`from prefect.utilities.tasks import defaults_from_attrs`) somehow gets rid of the mypy error.
- Provide a default argument for all new parameters in the overridden `run` method: https://github.com/python/mypy/issues/7424#issuecomment-687143888

## Reproduction

Run [`mypy`](https://mypy.readthedocs.io/en/stable/index.html) on the code above.

## See Also

- [Relevant discussion on Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1623266045206800)

## Environment

```
mypy 0.901
prefect version 0.14.21
```

**Comment by madkinsz** [comment]
This is a bit of a limitation of mypy afaik, we can't do much about this without writing a custom mypy plugin. Happy to entertain any other solutions though. I think this could be largely resolved by writing your tasks as functions (instead of classes). We may provide a way to write your tasks as functions while still reference a custom task class in the future.
