### ISSUE TITLE
Logging inside of a python context doesn't work

### ISSUE THREAD

**Issue by AndrewHannigan** [PrefectHQ/prefect#4653]
Logging inside of a python context doesn't work

```
import prefect
import sqlalchemy as sa
from prefect.storage import S3

@prefect.task
def test():
    conn_string = "SOME_DB_CONN_STRING"
    engine = sa.create_engine(conn_string, echo=True)

    logger = prefect.context.get("logger")
    logger.info("OUTSIDE CONNECTION CONTEXT") # This will show up

    with engine.connect() as conn:
            logger.info("INSIDE CONNECTION CONTEXT")  # This won't show up
```

**Comment by madkinsz** [comment]
Hey @AndrewHannigan  -- this works fine with a generic context. Seems like this has something to do with `sqlalchemy`? Is it possible that the `engine.connect()` call is hanging?

**Comment by AndrewHannigan** [comment]
Yeah seems to work fine for me now too. Not sure what was happening earlier... if I see it again and can replicate I'll reopen.
