### ISSUE TITLE
Docs - Task Library Not Found

### ISSUE THREAD

**Issue by seanpwlms** [PrefectHQ/prefect#4679]
## Description

On this page, https://docs.prefect.io/core/tutorial/02-etl-flow.html, clicking the link "Task Library" towards the bottom of the page leads to https://docs.prefect.io/core/task_library/ which gives a 404 error.
However, pasting that link into a browser, redirects to https://docs.prefect.io/core/task_library/overview.html, which I believe is the correct link.

## Expected Behavior

I think the link should be https://docs.prefect.io/core/task_library/overview.html.

## Reproduction

https://docs.prefect.io/core/task_library/

## Environment

Tested in Chrome and Firefox

**Comment by tpdorsey** [comment]
Fixed by @fakela in https://github.com/PrefectHQ/prefect/pull/4765
