### ISSUE TITLE
Allow Overriding of Flow Version Number

### ISSUE THREAD

**Issue by robalar** [PrefectHQ/prefect#4682]
## Current behavior
Flows are versioned incrementally with each metadata change/`--force`

## Proposed behavior
At register time, allow the overriding of the version string - `prefect server register -m flows --version "prod.2021.07.21.0"`

## Example
This would be handy to align the version tags on our prefect flows to the version tags of our API deploys.

**Comment by madkinsz** [comment]
Hey @robalar -- these versions are integers in the database so we can't actually take arbitrary tags.

**Comment by robalar** [comment]
Ah I see, I assume it's not feasible to make them strings? 😄

**Comment by madkinsz** [comment]
Not in particular :D we use integer versions in quite a few places. There is a `description` field that you could use if you just want this metadata to exist. I'm happy to keep this feedback in mind as we think about the future of flow versions and flow metadata but I definitely can't provide a timeline for making this a feature.

**Comment by robalar** [comment]
Great thank you, will look into using the description. Cheers for the super speedy response and for taking the feedback onboard!
