### ISSUE TITLE
Docs Improvement Suggestion: Prettify URLs 

### ISSUE THREAD

**Issue by Bojne** [PrefectHQ/prefect#4684]
## Prettify Prefect Docs URLs with Netlify assets optimization feature  

Hey Prefect front-end team! 

I know Netlify supports assets optimization, which is handy to use when you wanna prettify URLs (i.e. remove the html ending: .../overview.html -> .../overview). 

In case you wanna enable it, just go to the Netlify platform and enable it.

![image](https://user-images.githubusercontent.com/8368609/122804427-7d40fc80-d2fa-11eb-8da1-1e2417f54db3.png)

More info on the [Netlify blog](https://www.netlify.com/blog/2019/08/05/control-your-asset-optimization-settings-from-netlify.toml/). You can also enable assets optimization, which will also speed up the doc site by some degree.

**Comment by znicholasbrown** [comment]
Done, great suggestion @Bojne 😄
