### ISSUE TITLE
Task with multiple states as list parameter doesn't work as expected

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4690]
## Description
I wanted to link multiple potential error states as a list into a state handler Task:
```python
@prefect.task(trigger=prefect.triggers.any_failed)
def task_error_handler(potential_errors: List[Any]):
    print(f"potential_errors: {potential_errors!r}")
```
However, when a list of multiple states/results was passed as `task_error_handler(potential_errors=[a, b])`, I got a `TRIGGERFAIL`

## Expected Behavior
I would have expected `potential_errors` in the example below to be a List of either Prefect states or results, not a `TRIGGERFAIL`. 

## Reproduction

Running the following:
```python
from typing import Any, List

import prefect


@prefect.task
def task_fail_a() -> str:
    raise RuntimeError("Expected Error A")
    return "a"


@prefect.task
def task_fail_b() -> str:
    raise RuntimeError("Expected Error B")
    return "b"


@prefect.task(trigger=prefect.triggers.any_failed)
def task_error_handler(potential_errors: List[Any]):
    print(f"potential_errors: {potential_errors!r}")


with prefect.Flow("test-flow") as flow:
    a = task_fail_a()
    b = task_fail_b()
    task_error_handler(potential_errors=[a, b])


result = flow.run()
```
results in:
```
potential_errors: TRIGGERFAIL('Trigger was "all_successful" but some of the upstream tasks failed.')
```
With full log: [log.txt](https://github.com/PrefectHQ/prefect/files/6696926/log.txt)

## Environment

```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.10.0-1029-oem-x86_64-with-glibc2.31",
    "prefect_backend": "server",
    "prefect_version": "0.14.22",
    "python_version": "3.9.4"
  }
}
```

**Comment by peterroelants** [comment]
I spend some time debugging this, and when looking at the flow result I found:
```python
{
  <Task: task_fail_a>: <Failed: "Error during execution of task: RuntimeError('Expected Error A')">,
  <Task: task_fail_b>: <Failed: "Error during execution of task: RuntimeError('Expected Error B')">,
  <Task: List>: <TriggerFailed: "Trigger was "all_successful" but some of the upstream tasks failed.">,
  <Task: task_error_handler>: <Success: "Task run succeeded.">
}
```
If I understand correctly the `[a, b]` list passed to `potential_errors` gets implicitly converted into a [List Task](https://github.com/PrefectHQ/prefect/blob/5de58efaba956b431335d99acab07eaf6a362e1b/src/prefect/tasks/core/collections.py#L53). 
However, this List Task fails because it doesn't inherit the `prefect.triggers.any_failed` trigger from `task_error_handler`.

I think there are two solutions to make this more intuitive:
- Clarify Prefect Signals to contain a reference to the originating task (in their message). It wasn't clear to me at all that the `TRIGGERFAIL` originated from the implicit List Task.
- Make the implicit Task (like the list task) inherit the triggers of their "parent task" (not sure if this would be easy to do).

**Comment by peterroelants** [comment]
I spend some time debugging this, and when looking at the flow result I found:
```python
{
  <Task: task_fail_a>: <Failed: "Error during execution of task: RuntimeError('Expected Error A')">,
  <Task: task_fail_b>: <Failed: "Error during execution of task: RuntimeError('Expected Error B')">,
  <Task: List>: <TriggerFailed: "Trigger was "all_successful" but some of the upstream tasks failed.">,
  <Task: task_error_handler>: <Success: "Task run succeeded.">
}
```
If I understand correctly the `[a, b]` list passed to `potential_errors` gets implicitly converted into a [List Task](https://github.com/PrefectHQ/prefect/blob/5de58efaba956b431335d99acab07eaf6a362e1b/src/prefect/tasks/core/collections.py#L53). 
However, I think this List Task fails because it doesn't inherit the `prefect.triggers.any_failed` trigger from `task_error_handler`, and none of its elements succeeds (and thus activates the default `all_successful` trigger)

I think there are two solutions to make this more intuitive:
- Clarify Prefect Signals to contain a reference to the originating task (in their message). It wasn't clear to me at all that the `TRIGGERFAIL` originated from the implicit List Task.
- Make the implicit Task (like the list task) inherit the triggers of their "parent task" (not sure if this would be easy to do).
- Not implicitly make List Tasks from Python lists.

**Comment by peterroelants** [comment]
I also found that swapping the list for `**kwargs` does seem to work, the following:
```python
import prefect


@prefect.task
def task_fail_a() -> str:
    raise RuntimeError("Expected Error A")
    return "a"


@prefect.task
def task_fail_b() -> str:
    raise RuntimeError("Expected Error B")
    return "b"


@prefect.task(trigger=prefect.triggers.any_failed)
def task_error_handler(**kwargs):
    print(f"kwargs: {kwargs!r}")


with prefect.Flow("test-flow") as flow:
    a = task_fail_a()
    b = task_fail_b()
    task_error_handler(a=a, b=b)


result = flow.run()
```

Results in:
```python
kwargs: {'a': RuntimeError('Expected Error A'), 'b': RuntimeError('Expected Error B')}
```
Although I am surprised that in this case the values are not Prefects Signals anymore.

**Comment by DomagojKorais** [comment]
I have the same issue, is there any working solution?
