### ISSUE TITLE
Azure Storage `stored_as_script=True` Should Upload File Similar to S3 Storage

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4706]
## Current behavior

When `stored_as_script=True`, Azure Storage simply takes in a file path where the file exists. This is inconsistent with S3 Storage where `stored_as_script=True` uploads the file. It would be nice if the interface was consistent and Azure storage uploads a file as well. The relevant code blocks are highlighted below

[S3](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/storage/s3.py#L159-L174)
[Azure](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/storage/azure.py#L128)

## Proposed behavior

Not sure yet if it's feasible, but Azure Storage should also upload a file to be consistent with S3 Storage.

## Example

It would be a lot easier to use Azure Storage because it would upload the file of the flow for the user at a specified path. This makes S3 easier and is a good standard for a consistent interface.

**Comment by jnxyp** [comment]
Yep, I was expecting the AzureStorage will also upload the flow file for me, but it didn't. It took me several hours to locate this problem.
