### ISSUE TITLE
Add MultiExecutor for executing tasks with several different executors

### ISSUE THREAD

**Issue by AlexanderVanEck** [PrefectHQ/prefect#4712]
## Current behavior

As mentioned in https://github.com/PrefectHQ/prefect/issues/4705 I'm looking for a way to express different resource requirements for different task, f.e. GPU or high-memory workloads. Currently we can only specify 1 executor for 1 flow. In the case of DaskExecutor this also means only defining 1 Dask worker specification. This can be resource inefficient if the tasks in a flow have large variance in resources requirements.

It is unlikely that Dask will soon support this usecase, the issues have been pending since 2018... Adding this functionality to prefect allows our users to cut down on resource utilization in the meantime.

## Proposed behavior

Let's add a MultiExecutor which allows tasks to be mapped to executors.

Several advantages:

1.  Fine-grained control over where/how tasks are executed, especially with DaskExecutor.
2. With DaskExecutor you can now use several cloud providers to split workload over more than 1 cloud provider. F.e. AWS for normal compute and GCP for TPU compute.
2.  Easy mix-and-match of executors, f.e. more workers for CPU intensive tasks and more RAM for memory intensive tasks.
3. Selection of which task goes to which executor is ignored by other executors, and thus tasks stay runnable by other executors.

Some disadvantages:

1. In the case of DaskExecutor there will be some overhead on running several schedulers, but these are very lightweight.

Open questions:

1. Can 2 DaskExecutors pass futures between them?
(initial testing shows **no** due to `ValueError: Inputs contain futures that were created by another client.`)
2. What happens when 1 task uses a DaskExecutor and 1 uses a LocalCluster, can one receive data from the other?
(turns out not a problem)

## Example

```
def say_hello():
    logger = prefect.context.get("logger")
    logger.info("Hello, Cloud!")
    logger.info(f"Hello, Core {__version__}!")
    logger.info(f"Hello, Torch CUDA {torch.cuda.is_available()}!")
    logger.info(f"Hello, Torch Devices {torch.cuda.device_count()}!")

@task(name='hello-task-cpu')
def say_hello_cpu():
    say_hello()

@task(name='hello-task-gpu', tags=['prefect-multi-executor:gpu'])
def say_hello_gpu():
    say_hello()

with Flow(
    "hello-flow",
    executor=MultiExecutor(executors={'gpu': DaskExecutor(..with gpu..), 'default': DaskExecutor(..with cpu..)}),
) as flow:
    say_hello_cpu()
    say_hello_gpu()
```

1. See the MultiExecutor taking in a dictionary of executors with at least 1 'default' key.
2. See the `tags` on the say_hello_gpu to indicate the gpu executor should be used.

## Potential implementation

```
class MultiExecutor(Executor):
    def __init__(self, executors: Dict[str, Executor]):
        if 'default' not in executors.keys():
            raise ValueError(
                'Dictionary of executors should include at least a "default" executor.'
            )

        self.executors = executors
        super().__init__()

    @contextmanager
    def start(self) -> Iterator[None]:
        with ExitStack() as stack:
            for executor in self.executors.values():
                stack.enter_context(executor.start())
            yield

    def _executor_from_tags(self, task_tags: List[str]) -> Executor:
        executor_tags = [
            tag.lstrip('prefect-executor:')
            for tag in task_tags
            if tag.lower().startswith("prefect-executor")
        ]
        if len(executor_tags) > 1:
            raise ValueError('One of the tasks in this flow has more than 1 executor specified.')

        if len(executor_tags) == 1:
            if executor_tags[0] not in self.executors.keys():
                raise ValueError(
                    f'{executor_tags[0]} could not be found in self.executors, was: {self.executors.keys()}'
                )

            executor_name = executor_tags[0]
        else:
            executor_name = 'default'

        return self.executors[executor_name]

    def submit(self, *args: Any, extra_context: dict = None, **kwargs: Any) -> Any:
        task_tags = extra_context.get("task_tags", [])
        executor = self._executor_from_tags(task_tags)
        return executor.submit(*args, extra_context=extra_context, **kwargs)

    def wait(self, futures: Any) -> Any:
        futures_by_executors: Dict[Executor, Dict[Task, Future]] = defaultdict(dict)
        for task, future in futures.items():
            executor = self._executor_from_tags(task.tags)
            futures_by_executors[executor][task] = future

        all_futures = {}
        for executor, future in futures_by_executors.items():
            all_futures.update(executor.wait(future))

        return all_futures
```

@madkinsz would love to hear your opinion on this. :) I did some testing with the code suggested above and it seems to work (except with 2 DaskExecutors), also the implementation would be easy to maintain as it's nothing more but a wrapper around several executors.

**Comment by AlexanderVanEck** [comment]
To solve the `ValueError: Inputs contain futures that were created by another client.` error we could either

1. Resolve the futures before they are passed off to the other client. I suppose this would be a codechange to flow_runner somehow. or could be coded into the Executor possibly?
OR
2. All DaskExecutors should share their dask-scheduler, although I'm not sure if that is possible.

**Comment by madkinsz** [comment]
Hey @AlexanderVanEck  -- sorry about the lack of reply here; I took a look then forgot I hadn't responded.

I think this is out of scope for what we would accept for executors right now. It is an interesting idea though and something that we'll hopefully be addressing later this year. Since executors aren't serialized I think you can roll this yourself still.
