### ISSUE TITLE
-r flag on prefect register CLI command

### ISSUE THREAD

**Issue by bennnym** [PrefectHQ/prefect#4726]
## Current behavior
Today I am unable to look in a nested folder structure for flows. I need to specify multiple folders and run multiple commands so that I can register these flows in CI.

This is frustrating because I then need to rebuild and push the same Docker image that I am using for Storage multiple times. It is inefficient.

My folder structure is like so

```
.
├── flows
│   ├── common
│   └── delete_markets
│       ├── flow.py
│       └── tasks.py
│   └── update_markets
│       ├── flow.py
│       └── tasks.py
 ```

## Proposed behavior
can we add a -pr flag or something to tell the CLI a path to recursively search for flows and only build the one Docker storage image?

**Comment by madkinsz** [comment]
I'm interested in this but I'm hesitant because of the implications of recursion when using the `--watch` flag. Is there a reason that `-p flows/delete_markets -p flows/update_markets` is infeasible for you?

**Comment by bennnym** [comment]
The reason is from a CI perspective.

If I'm registering multiple flows I don't want to just automate a huge register command with 10 x -p foo. 

I have got around it with this for now, but I see it being a common need potentially for others.
