### ISSUE TITLE
Can't register `kubernetes agent `: `[Errno -2] Name or service not known`

### ISSUE THREAD

**Issue by lowercase00** [PrefectHQ/prefect#4738]
## Description

I'm trying to deploy the server to a k8s cluster, I made the manifests as similar to the helm charts as possible: hasura, graphql and apollo seems to run fine: I can access the console, can query, have a https certificate, health checks are ok, liveness probe are ok.

I can't register the agent though. I tried referencing the apollo service as I normally would like: `prefect-apollo-service`, which is the name of my service, but I get `Name os service not known error`. I tried a few variations like using the `https` endpoint, using the ClusterIP, with and without the protocol, with and without port, different path variations, and nothing. I created a tenant manually in the database, because also couldn't make the `create-tenant` to work.

The weird thing is that if I curl the service from the agent pod, everything seems to work fine, like:

```
curl \
-X POST \
-H "Content-Type: application/json" \
--data '{ "query": "{ tenant { id } }" }' \
http://prefect-apollo-service:4200/graphql
```
and I get the data:
```
{"data":{"tenant":[{"id":"1696a6e5-58ad-476e-8285-9cf914c4200c"}]}}
```

I set the `prefect backend server`, and nothing. Tried different `env name` variations, and with the `--api` flag also.
Apollo's playground work, and I can make a `{tenant {id}}` query normally. So I'm running out of ideas on what I'm doing wrong.

The full traceback is:

```
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/agent.py", line 327, in start
    start_agent(KubernetesAgent, image_pull_secrets=image_pull_secrets, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/agent.py", line 136, in start_agent
    agent.start()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 189, in start
    self._setup_api_connection()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 910, in _setup_api_connection
    self.client.attach_headers({"X-PREFECT-AGENT-ID": self._register_agent()})
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 854, in _register_agent
    agent_id = self.client.register_agent(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1999, in register_agent
    result = self.graphql(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 549, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'message': '[Errno -2] Name or service not known', 'locations': [{'line': 2, 'column': 5}], 'path': ['register_agent'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': '[Errno -2] Name or service not known'}}}]
```

I also tried different tags `latest`, `0.15.0-python3.8` etc.
Other types of agents also gives me the same error.
I probably doing something wrong, but really can't find what.

## Expected Behavior
The agent to register.

## Environment
```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__API",
    "PREFECT__CLOUD__AGENT__LABELS",
    "PREFECT__CLOUD__AGENT__AGENT_ADDRESS",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-4.19.0-17-amd64-x86_64-with-debian-10.10",
    "prefect_backend": "server",
    "prefect_version": "0.15.0",
    "python_version": "3.7.10"
  }
}
```

**Comment by madkinsz** [comment]
Sorry you're having a tough time here. It looks like you've nearly got it all set up. What did you set `PREFECT__CLOUD__API` to? When using the Server backend you generally want to leave that untouched and change the the `PREFECT__SERVER__HOST` instead. Is there a reason you're not using the manifest from the helm chart?

`PREFECT__CLOUD__AGENT__AGENT_ADDRESS` is for a little server the agent hosts for healthchecks -- you shouldn't have to modify that.

**Comment by lowercase00** [comment]
Hey @madkinsz! 
I actually choose to make the manifests manually since I have had bad experiences maintaining external helm charts in the past, probably could've done differently, but since I'm almost done, I think I'll try a bit more :)

I tried quite a few variations for the cloud api:

`PREFECT__CLOUD__API=http://prefect-apollo-service:4200/graphql`
`PREFECT__CLOUD__API=https://mydomain.com/graphql`

I used that because in the helm chart I saw something like:
```
        env:
          - name: PREFECT__CLOUD__API
            value: {{ include "prefect-server.apollo-api-url" . }}
```
So i though it was the apollo URL.
I just tried using the `SERVER_HOST` also, and nothing.

If I make the `CLOUD__API` an empty string, and only define `SERVER__HOST`, it gives me an `empty_schema` error:
`requests.exceptions.MissingSchema: Invalid URL '/graphql': No schema supplied. Perhaps you meant http:///graphql?`

Also tried with `--log-level DEBUG` but no errors, it just crashes right after `Registering Agent...` message.
If I change the `CLOUD__API` to some trash string `fdjsklfds`, even though I have `prefect backend server`, it gives me `requests.exceptions.MissingSchema: Invalid URL 'fjdkslfjklds': No schema supplied. Perhaps you meant http://fjdkslfjklds?` so I'm thinking that it's probably ignoring `SERVER__HOST`, and using the `CLOUD__API` env instead.

What I can't understand is why the `curl` works with the `apollo` service name. Maybe something i'm doing wrong in interfering in the query? Or maybe I'm setting an `env_var` wrong... I don't know. Any other ideas?

**Comment by madkinsz** [comment]
Ah I see. Yeah we set the `PREFECT__CLOUD__API` directly in the chart to avoid any templating the config does by default.

Using `helm template prefect-server --set agent.enabled=true` I get this:
```yaml
# Source: prefect-server/templates/agent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-agent
  labels:
    app.kubernetes.io/name: prefect-server
    app.kubernetes.io/instance:  RELEASE-NAME
    helm.sh/chart: prefect-server-0.0.0
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: agent
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prefect-server
      app.kubernetes.io/instance:  RELEASE-NAME
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prefect-server
        app.kubernetes.io/instance:  RELEASE-NAME
        app.kubernetes.io/component: agent
    spec:
      imagePullSecrets: []
      serviceAccountName: RELEASE-NAME-serviceaccount
      containers:
      - name: agent
        image: "prefecthq/prefect:latest"
        imagePullPolicy: Always
        command:
          - bash
          - "-c"
          - "prefect agent kubernetes start"
        env:
          - name: PREFECT__CLOUD__API
            value: http://RELEASE-NAME-apollo.default:4200/graphql
          - name: NAMESPACE
            value: default
          - name: IMAGE_PULL_SECRETS
            value: "[]"
          - name: PREFECT__CLOUD__AGENT__LABELS
            value: "[]"
          - name: JOB_MEM_REQUEST
            value: ""
          - name: JOB_MEM_LIMIT
            value: ""
          - name: JOB_CPU_REQUEST
            value: ""
          - name: JOB_CPU_LIMIT
            value: ""
          - name: IMAGE_PULL_POLICY
            value: ""
          - name: SERVICE_ACCOUNT_NAME
            value: RELEASE-NAME-serviceaccount
          - name: PREFECT__BACKEND
            value: server
          - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
            value: http://0.0.0.0:8080
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
```

The only difference appears to be the inclusion of the namespace. That curl is working but the client is not is indeed peculiar. I don't see anything obviously wrong with what you're saying.

**Comment by lowercase00** [comment]
Yeah, indeed the template is pretty similar... only metadata and labels different, but shouldn't make a difference I guess.
The `client.api_server` gives me the `PREFECT__CLOUD__API` address. I found that if I add `/graphql` it gives me `.../graphql/graphql` but even without that, doesn't work. Maybe I could try to register the agent manually in the python terminal, and debug from there. Don't know if its too obvious since the class is faily long, but would have any ideas I could try? I'm guessing there must be something wrong with `_register_agent()`, maybe I could try running that on the pod.

**Comment by madkinsz** [comment]
You should be able to test the connection with `client.graphql("query { tenant { id } }")` directly. `_register_agent` shouldn't be changing the service it's hitting.

**Comment by madkinsz** [comment]
@lowercase00 

This should get you some more information
```bash
PREFECT__CLOUD__DIAGNOSTICS=true python -c "from logging import getLogger; getLogger('').level = 0; from prefect import Client; client = Client(); client.graphql('query { tenant { id } }')"
```

**Comment by lowercase00** [comment]
Hm, ok, so `client.graphql("query { tenant { id } }")` works.

**Comment by madkinsz** [comment]
It seems like perhaps the container is functional once it's running? What happens if you run `prefect agent local start` while in an interactive session?

**Comment by lowercase00** [comment]
To debug I've running the container with an infinite loop, like
```
command: [ "/bin/bash", "-c", "--" ]
args: [ "while true; do sleep 30; done;" ]
```
`prefect agent local start` also gives the same error while exec'ing into the pod.

**Comment by lowercase00** [comment]
`'path': ['register_agent']`
Maybe the `graphql` did not register this mutation?

**Comment by madkinsz** [comment]
Ah that makes a lot more sense. This would be an issue with Apollo or the GraphQL server. Since you can query for tenants, Apollo/Hasura are working together but the mutations are all registered in our GraphQL server and Apollo stitches the schemas together to present a unified API.

**Comment by lowercase00** [comment]
I'll give a second look at the `graphql` manifest, can't seem to find anything too weird at the moment, and health checks are ok. Accessing the server directly, I can see the `register_agent` in the mutations. And the logs just give that error on image above, something like:

**Comment by madkinsz** [comment]
Ah I see, this doesn't look like an issue with your agent pod but rather an error raised in the resolver function for the mutation on the GraphQL server itself. It looks like it's failing to contact Hasura correctly.

**Comment by lowercase00** [comment]
Hmm.. ok, so: 
Apollo playground works, Hasura console works, inseed I added an Ingress to GraphQL service, and ideed there's a problem. The same query that works in Apollo (`{ tenant{id} }`) does not work in GraphQL playground directly (`Cannot query field 'tenant' on type 'Query'.`) which even seem a similar error than the register_agent error. So I probably look for problem at GraphQL env vars I guess

**Comment by madkinsz** [comment]
`tenant { id }` is provided by Hasura not our GraphQL server so it'll only work in Apollo. This should be a connection issue from GraphQL -> Hasura from the traceback you've provided.

**Comment by lowercase00** [comment]
Got it, do you know a simple query I could use in the GraphQL server just to see whether the connection to Hasura is working? I tried `hello`, `api {backend}`, `  reference_data { state_hierarchy state_info }`, and they all work.

**Comment by lowercase00** [comment]
So I made it work, after long hours of trial and error, it seems that GraphQL receives the env var `PREFECT_SERVER__HASURA__HOST` which should be only `hasura-service` instead of `http://hasura-serice:3000` which is what I was doing. I though that, because it's normally how I reference services in k8s, and that's how apollo was referencing the GraphQL host:

```
- name: GRAPHQL_SERVICE_HOST
   value: http://prefect-graphql-service:4201/graphql/
```

Maybe the code is manyally adding the protocol and the path to the URL, I'm not sure.
@madkinsz  I don't know if it's interesting for you guys, but I could happily share the manifests with you guys, for people who might want to deploy the server manually (without Helm), let me know if you guys want that.

After the learning experience, I thought of a few things that maybe could make sense:
- a k8s job to check/diagnose the communication between services could help
- standardize how to pass references (trailing slash, `http` etc) also could help

Anyways, @madkinsz thanks a lot for your help a patience, really appreciate it!
Cheers

**Comment by lowercase00** [comment]
Closing that, again, thanks for the help!
