### ISSUE TITLE
Running dependent flows doc has the same example twice

### ISSUE THREAD

**Issue by pjanowski** [PrefectHQ/prefect#4770]
The [Running Dependent Flows](https://docs.prefect.io/core/idioms/flow-to-flow.html) doc presents the same code example for both the imperative and functional syntax.

**Comment by Bojne** [comment]
Great flag! I had fixed the change and submitted a PR for this. (update 15 files all at once, details in the PR)

**Comment by Bojne** [comment]
@madkinsz merged PR #4781 already took care of this, this issue is ready to close 👍🏻
