### ISSUE TITLE
prefect run flow --watch exits 0 on Failed state

### ISSUE THREAD

**Issue by TylerWanner** [PrefectHQ/prefect#4782]
## Description

prefect run flow --watch exits 0 on Failed final state

## Expected Behavior

expected a non-0 exit code

## Reproduction

run any flow with --watch and have it finish in Failed state

**Comment by madkinsz** [comment]
@TylerWanner `prefect run flow` is deprecated and won't be updated. `prefect run` exits with the proper error code when using `--watch`.

**Comment by TylerWanner** [comment]
oops that makes sense thanks
