### ISSUE TITLE
May I know how to add labels to the schedule created by graphql?

### ISSUE THREAD

**Issue by mr-tester-william-lo** [PrefectHQ/prefect#4784]
May I know how to add labels to the schedule created by graphql?

i can only find this:
https://github.com/PrefectHQ/prefect/blob/d61fa6aac9330c5817cc8e8b8f8cca2d634ea7e1/src/prefect/schedules/clocks.py#L255
, but it is not related to graphql query

_Originally posted by @mr-tester-william-lo in https://github.com/PrefectHQ/prefect/discussions/4628#discussioncomment-1011327_

**Comment by zhen0** [comment]
Thanks for the question @mr-tester-william-lo - I've responded in your original thread.
