### ISSUE TITLE
Column names for SnowFlakeQuery

### ISSUE THREAD

**Issue by jesperhemmingsson** [PrefectHQ/prefect#4789]
## Current behavior
When running a query with prefect.tasks.snowflake.snowflake.SnowFlakeQuery, only the results of `cursor.execute(query, params=data).fetchall()` will be returned. This results in column names being lost, which is a shame imo.

## Proposed behavior
One way of doing things instead would be for SnowFlakeQuery.run() to return an object:
`{ data: [ ['bob', '22', 'M'], ['jack', '30', 'M'] ], columns: ['name', 'age', 'sex'] }`

Or any other method of returning the column names and not only the raw data.

King regards,
Jesper

**Comment by madkinsz** [comment]
I think this may be addressed by #4786, but if not it could probably be implemented as done in #4414

**Comment by jesperhemmingsson** [comment]
Yes, I believe #4786 would solve this.

**Comment by kvnkho** [comment]
Will close this issue as it seems #4786 fixes it but feel free to reopen.
