### ISSUE TITLE
Expose networkConfiguration on ECSAgent CLI

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4803]
## Current behavior

A user requested on Slack that the networkConfiguration of the ECSAgent be exposed through the CLI. Currently, the only way to supply this is through a task definition. 

The AWS CLI has support for this where you can do something like:
```
aws ecs create-service 
    --network-configuration "awsvpcConfiguration={subnets=[subnet-12344321],securityGroups=[sg-12344321],assignPublicIp=ENABLED}" 
```

## Proposed behavior

It would be convenient if the agent could start with this flag as well.
```
prefect agent ecs start --network-configuration "awsvpcConfiguration={subnets=[subnet-12344321],securityGroups=[sg-12344321],assignPublicIp=ENABLED}" 
```

**Comment by madkinsz** [comment]
I think this may be out of scope for the run config. We would like to avoid exposing every option people may want, instead exposing the most necessary options at a top-level and allowing people that need more customization to use the task definition which exposes all of the options. When does someone want/need this?

**Comment by kvnkho** [comment]
Definitely understand the thought. They have specific subnets for their cluster that they need to attach to the ECSAgent.

**Comment by madkinsz** [comment]
Yeah I think we can make a task definition easier to use, but we probably won't be exposing things like this directly
