### ISSUE TITLE
Add dynamic run_name and label specification to create_flow_run()

### ISSUE THREAD

**Issue by pjanowski** [PrefectHQ/prefect#4807]
## Current behavior
`create_flow_run()` currently has the option to provide `run_name` and `labels` arguments for the child flow being spawned but unlike the `StartFlowRun` pattern, it interprets these arguments literally. It is not directly possible to provide dynamically interpreted at graph execution time labels or run names. 

For example here
``` python
@task(log_stdout=True)
def start_hd_subflows(experiment):
    parameters = {"id_or_label": experiment["experiment_label"]}

    with case (experiment['base'], 'baseA'):
        subflow_crispr = create_flow_run(flow_name="subflowA", project_name="myproject", parameters=parameters, run_name=f"{flow.name}_{experiment['experiment_label']}_{experiment['type']}")
    with case (inpt['base'], 'baseB'):
        subflow_sf = create_flow_run(flow_name="subflowB", project_name="myproject", parameters=parameters, run_name=f"{flow.name}_{experiment['experiment_label']}_{experiment['type']}")

    return merge(subflow_crispr, subflow_sf)
```
the run_name will be interpreted at as a string made up of class names at graph creation time not as the dynamically provided values at graph execution time.

## Proposed behavior
`run_name` should be dynamically interpreted just as it was for `StartFlowRun`. A work around to achieve this is to wrap `start_flow_run`

``` python
@task(max_retries=1, retry_delay=timedelta(minutes=3))
def wrap_create_flow_run(flow_name, project_name, parameters, experiment):
    x=prefect.context.get("flow_run_name")
    run_name = f"{x}_{flow_name}_{experiment['experiment_label']}"
    print(f'Creating child flow run {run_name}')
    flow_run = create_flow_run.run(flow_name=flow_name, project_name=project_name, run_name=run_name, 
                        parameters=parameters)
    wait_for_flow_run.run(flow_run)
    return flow_run

@task(log_stdout=True)
def start_hd_subflows(experiment):
    parameters = {"id_or_label": experiment["experiment_label"]}

    with case (experiment['base'], 'baseA'):
        subflow_crispr = wrap_create_flow_run(flow_name="subflowA", project_name="myproject", parameters=parameters, experiment=experiment)
    with case (inpt['base'], 'baseB'):
        subflow_sf = wrap_create_flow_run(flow_name="subflowB", project_name="myproject", parameters=parameters, experiment=experiment)

    return merge(subflow_crispr, subflow_sf)
```

## Example
see above

**Comment by madkinsz** [comment]
Hi! `StartFlowRun` just passes a `str` run name to the client in the same way, it doesn't do any templating that I can see. It looks like you're using a `task`, `start_hd_subflows`, to add tasks to your flow. For clarity, this should probably just be a function? I believe you just want to generate the run name at flow runtime, but I'm not quite sure when your variables are set.

I think the expected use pattern here is

```python
@task
def generate_flow_run_name(...):
   return f"..."

with Flow(...):
    params = ...
    create_flow_run(flow_name="foo", run_name=generate_flow_run_name(params))
```

**Comment by pjanowski** [comment]
The task decorator on `start_hd_subflows` was a copy paste mistake: you're right that that's just a function, in this case being passed to an `apply_map()` task. I like the pattern you propose, let me try that. I didn't realize you can call a task on an argument as it's passed to a function. 

Regarding `StartFlowRun`, maybe the difference is in how we were calling it, outside of the context of a flow. Eg

``` python
    flow_runs=[]
    flow_runs.append(
        StartFlowRun(
            flow_name=flow.name,
            parameters={
                "id_or_label": experiment["experiment_label"],
                "feature_allow_missing": True
            },
            project_name="myproject",
            run_name=f"{flow.name}_{experiment['experiment_label']}_{experiment['type']}",
            max_retries=1,
            retry_delay=timedelta(minutes=3),
            wait=True,
        ))

with Flow() as flow:
    flow_run_signals = [flow_run() for flow_run in flow_runs]
    ...

```

**Comment by madkinsz** [comment]
The big difference with `StartFlowRun` is that it's an unititialized `Task` class and not a `task` function (which is an initialized `Task` class -- this is confusing dichotomy that we're looking to resolve). So when you initialize it in your helper function, you're setting up a task "stub" that isn't added to your flow but has some default settings. Then, when you call it (`flow_run()`) you are adding the task to your flow. `create_flow_run` is just a `@task` decorated function like any task you'd write yourself. If you want to configure it in one place, then call it in another, you can use `functools.partial`. Generally, I'd set dynamic values with tasks as arguments though.

**Comment by pjanowski** [comment]
This makes sense, thanks for explaining! And the pattern that you provided works well enough. I still think, especially for the large-scale spawning of subflows, being able to directly provide the run_name argument the way it can be done outside of the flow context, would be nice sugar (also to help keep the graphs clean without excessive tasks). That's a bit of a side point: mapping over create_flow_run with case statements creates a LOT of additional tasks in the graph. It would be awesome to provide some sort of mechanism for collapsing tasks into "aggregate" tasks (either in the schematic visualization for easier introspection into the graph, i.e. you click and a single node expands into it's set of granular tasks, or on the object level where only a single task is created out of all those tasks used to map out the case statements). Just a general thought, we can dive into it more in the future maybe.
