### ISSUE TITLE
Reference tasks are not removed when flow update merge_parameters=True

### ISSUE THREAD

**Issue by pjanowski** [PrefectHQ/prefect#4832]
## Description
https://github.com/PrefectHQ/prefect/blob/a578124736007ab898c292f9848b440e60125bd4/src/prefect/core/flow.py#L713

When `merge_parameters` is set on updating flows, if a task is replaced and the task was a reference task, the new flow will still keep that task in it's list of reference tasks (even though the task is no longer in the flow). 

## Expected Behavior
Code should check reference tasks and remove the task being replaced from the list of reference tasks.

## Reproduction
Create two flows with the same task name in both and make the task in the first flow a reference task. Update first flow with second flow and `merge_parameters=True`. Resulting flow will still have the replaced task as a reference task.

cc: @johnurbanik

**Comment by madkinsz** [comment]
Thanks! This makes sense to me.

**Comment by pjanowski** [comment]
Actually it looks to me that this isn't an issue. Thanks to [this change](https://github.com/PrefectHQ/prefect/blob/1959eecf1bbbb8e3b194b288c197a6108deb8693/src/prefect/core/flow.py#L338) from @benfogelson the `_reference_tasks` set will get updated with the new task if the old task was a reference tasks. I'll close the issue.
