### ISSUE TITLE
Handling of Multiple Return Values in Mapped Tasks

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect#4839]
## Current behaviour
When a task that returns multiple values is mapped, the argument "nout" in the task declaration or the type annotation has no effect. When providing task_args={"nout": 2} in the task.map() call, the task can be unpacked. However, it has -in my opinion- not the desired effect compared to using "nout" in non-mapped tasks.

The result of a mapped task with task_args={"nout": 2} are just the ascending entries in the mapped list (here: list[0] and list[1]). This behaviour is unintuitive and quite different to the behaviour in non-mapped tasks when using "nout".

In cases where complex mapped tasks return multiple arguments which are also processed differently later in the flow, this behaviour leads to unnecessary handling of this mapped list in follow up tasks.

## Proposed behaviour
The .map() function should have its own "nout" argument such that multiple return values can be handled similar to non-mapped tasks. This can be achieved by using an intermediat task which reduces the result of the mapped task and uses `tuple(zip(*mapped_result))` to unpack the return values. See examples below. However, in complex parallelized flows it is desirable to not reduce each mapped task due to performance reasons. Therefore, the proposed behaviour should work on a deeper level without reducing to keep the benefit of consecutive mapped tasks. 

### Current behaviour:

    from prefect import task
    from typing import Tuple

    @task
    def task_nout(x: int):
        return x-1, x+1
    
    with Flow("nout") as flow:
        dec, inc = task_nout.map(x=[1, 2, 3, 4, 5], task_args={"nout": 2})
    
    result = flow.run()
    print(result.result[dec].result)  # This returns (0, 2)
    print(result.result[inc].result)  # This returns (1, 3)

### Proposed behaviour:
With intermediate task:

    @task
    def task_nout(x: int):
        return x-1, x+1
    
    @task(nout=2)
    def zip_task(lt: list) -> Tuple[int, int]:
        return tuple(zip(*lt))
    
    with Flow("flow_fit") as flow:
        mapped_task = task_nout.map(x=[1, 2, 3, 4, 5])
        dec, inc = zip_task(mapped_task)
    
    result = flow.run()
    print(result.result[dec].result)  # This returns [0, 1, 2, 3, 4]
    print(result.result[inc].result)  # This returns [2, 3, 4, 5, 6]

With proposed "nout" argument in .map()

    @task
    def task_nout(x: int):
        return x-1, x+1
    
    with Flow("nout") as flow:
        dec, inc = task_nout.map(x=[1, 2, 3, 4, 5], nout=2)
    
    result = flow.run()
    print(result.result[dec].result)  # This returns [0, 1, 2, 3, 4]
    print(result.result[inc].result)  # This returns [2, 3, 4, 5, 6]

**Comment by sm-Fifteen** [comment]
I'm interested in something like this as well. Returning tuples is a pretty conveinient thing to do when using ad-hoc tasks where the return values need to go in separate places, and it's kind of a bummer that #4206 made the previously incorrect behavior an error instead of implementing that feature.

**Comment by marcm-ml** [comment]
With prefect 2.0 this issue is solved, e.g:

```python
from prefect import task, flow

@task()
def test_tuple(x: int) -> tuple[int]:
    time.sleep(sleep)
    return x-1, x+1

@flow()
def flow(integers: list[int]):
    out = test_tuple.map(integers)
    a, b = list(zip(*[o.result() for o in out]))

    return a, b

a, b = flow([1,2,3])

print(a) # [0, 1, 2]
print(b) # [2, 3, 4]
```
