### ISSUE TITLE
DockerAgent --network host doesn't work as expected

### ISSUE THREAD

**Issue by AlexanderVanEck** [PrefectHQ/prefect#4840]
## Description

When starting the `prefect agent docker start --network host` the network gets added after the container is created (just before the container is started). Then we a flow is executed through the agent the container immediately crashes because it cannot connect to `PREFECT__SERVER__HOST` when the host is set to a private prefect server. The DNS lookup of the `PREFECT__SERVER__HOST` fails with ```Max retries exceeded with url: /graphql/graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4ff56015f8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))```

## Expected Behavior
 
One would expect when passing `--network host` that the container would be set to use the host network by default. However due to the use of docker-py's `connect_container_to_network` instead of adding it to host_config directly the resulting container has ` 'NetworkMode': 'default'` and `'Hostname': '1100502c3bf1'` (ID of container?) instead of NetworkMode=Host and Hostname=<Hostname>.

### What fails

1. Set up a private prefect server
2. Configure `PREFECT__SERVER__HOST` (and `PREFECT__SERVER__BACKEND`=server)
3. start `prefect agent docker start --network host`
4. Try to launch any DockerRun flow and see it fail

## Workaround

Starting the prefect DockerAgent without `--network host` but instead supply `host_config` to DockerRun configuration.

```
Flow(
    run_config=DockerRun(
        host_config={
            'network_mode': 'host',
        },
        ...
    )
)
```

This sets the host network as the default network.

## Questions

* When using `--network host` how would we instruct requests to use the host interface?
* How is `--network host` supposed to work?

## Environment

```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__SERVER__HOST",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-5.4.0-80-generic-x86_64-with-debian-bullseye-sid",
    "prefect_backend": "server",
    "prefect_version": "0.15.3",
    "python_version": "3.6.13"
  }
}
```

**Comment by AlexanderVanEck** [comment]
Just to let you know - this may also be caused when running an older version of prefect server which doesn't have DockerRun.host_config. Quite probable that this is what's causing the issue for us.

**Comment by vldbnc** [comment]
experience the same problem, your WA works but having an issue later to reach k8n pod name -- scheduler name tcp://dask-scheduler:8786 but IP works :/

Please mark that Docker version needs to be at least version v20.10.0+
```
class DockerAgent(Agent):
    """
    Agent which deploys flow runs locally as Docker containers. Information on using the
    Docker Agent can be found at https://docs.prefect.io/orchestration/agents/docker.html
    This agent requires Docker v20.10.0+
```

**Comment by madkinsz** [comment]
It looks like the issue here is that Docker does not automatically convert the network mode to “host” when you use a network that has the “host” network mode. Our “networks” option only connects your container to a network, we do not inspect the network to determine which network mode should be used. I find it confusing that their CLI automatically does this, but it looks like "host" is a special-case predefined network which means we could add a workaround that sets the network mode accordingly.

```
❯ docker network create test --driver host
Error response from daemon: only one instance of "host" network is allowed
                       
❯ docker network rm host                  
Error response from daemon: host is a pre-defined network and cannot be removed
                  
❯ docker network create host --driver bridge
Error response from daemon: operation is not permitted on predefined host network```
