### ISSUE TITLE
Feature Request: Azure Container Instances Agent (ACIAgent)

### ISSUE THREAD

**Issue by iRod3s** [PrefectHQ/prefect#4842]
## Current behavior
Currently Prefect has support for multiple agent types, most of them are "platform agnostic" like "DockerAgent". Also, you can use ECSAgent, which is designed to leverage the services of AWS. There isnt a similar Agent for Azure (Using Azure Container Instances)

## Proposed behavior
Add Azure Container Instances (ACIAgent?) as one of the agent types. Azure Container Instances is the Azure equivalent of Amazon Fargate, ie. a serverless container running service. This would be perfect for running Prefect tasks that are wrapped inside docker. While Amazon dominates the Cloud Ecosistem (44.6%), Azure is the second most used Cloud, with 17.4% of market share, so probably, a dedicated Agent will help a lot of teams to transition to Prefect and use it to the fullest.

## Example
This will help all teams currently on Azure infrastructure who are looking to Prefect for automation. It would be amazing to offload tasks to a pay-as-you-go service while still using Prefect for task orchestration AND not having to setup additional infra and billing with another cloud provider.

**Comment by madkinsz** [comment]
This is available in Prefect 2!

**Comment by iRod3s** [comment]
Yes it is! Thank you very much <3
