### ISSUE TITLE
"Skipped" state doesn't quite work for Flows

### ISSUE THREAD

**Issue by casey-green** [PrefectHQ/prefect#4864]
## Description
I have a flow that runs periodically. The first thing the flow does is check "is there any work to do?" It looks something like this:

```python
@task
def any_work_to_do(...) -> bool:
    # ...
    work_to_do: bool = ...
    return is_work

schedule = IntervalSchedule(interval=timedelta(minutes=15))
with Flow("Test", schedule=schedule) as flow:
    should_run = any_work_to_do(...)
    with case(should_run, True):
        # rest of tasks.    
```

I'd like to detect this scenario and explicitly set the **Flow** state to `Skipped`. There are several reasons for wanting to do this on our end. One concrete reason is to create a better visualization in the UI i.e. be able to differentiate between flows that "did work" (green success, red failure) and flows that "did not do work" (bluish skipped color).

To accomplish this behavior, I tried defining a terminal state handler that looked something like:

```python
def terminal_state_handler(
    flow: Flow,
    state: State,
    terminal_task_states: Set[State],
) -> Optional[State]:
    all_terminal_tasks_skipped = all([s.is_skipped() for s in terminal_task_states])
    if all_terminal_tasks_skipped:
        return Skipped("Skipping flow run.")
```

This sort of works!

<img width="440" alt="Screen Shot 2021-08-12 at 10 33 55 AM" src="https://user-images.githubusercontent.com/1815573/129215937-1498d574-073d-487e-ae2e-fed125c4571e.png">

**Except**, it doesn't appear that Prefect recognizes `Skipped` as a "finished" state because the `End time` (and `Duration`) continues to increase in the UI, even after the task has finished. Here's the same task ~2 min later.

<img width="410" alt="Screen Shot 2021-08-12 at 10 35 58 AM" src="https://user-images.githubusercontent.com/1815573/129216087-3f39eb07-12f9-49c1-a9c7-6941ce72e421.png">

## Expected Behavior
Given that `Skipped` is a sub-class of `Success`, I would expect Prefect to recognize `Skipped` as a "finished" state.

## Reproduction
```python
from typing import Set, Optional

from prefect import task, Flow, Parameter, case
from prefect.engine.state import Skipped, State

def terminal_state_handler(
    flow: Flow,
    state: State,
    terminal_task_states: Set[State],
) -> Optional[State]:
    all_terminal_tasks_skipped = all([s.is_skipped() for s in terminal_task_states])
    if all_terminal_tasks_skipped:
        return Skipped("Skipping flow run.")

@task
def should_run(i: int) -> bool:
    if i == 0:
        return False
    elif i == 1:
        raise Exception("FAIL!")
    else:
        return True

@task
def hello_world() -> None:
    print("Hello, world!")

with Flow("Test") as flow:
    run_type = Parameter("run_type", default=2, required=True)
    should_run_result = should_run(run_type)
    with case(should_run_result, True):
        hello_world()

flow.terminal_state_handler = terminal_state_handler
```

Then, you can repro this by running `Test` flow with `run_type` equal to `0`.

## Environment

```
$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.7-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.15.3",
    "python_version": "3.8.5"
  }
}
```

**Comment by casey-green** [comment]
This _seems like_ a prefect **server** bug... but let me know if this is a "feature request", UI bug, or simply something you don't think should be supported.

**Comment by madkinsz** [comment]
cc @znicholasbrown / @zhen0 this looks like a UI bug?

**Comment by casey-green** [comment]
Here's one additional data point... it looks like `end_date` is not set on the `Skipped` flow:

<img width="832" alt="Screen Shot 2021-08-12 at 11 08 09 AM" src="https://user-images.githubusercontent.com/1815573/129221280-03bcd537-0221-4fb2-ad73-7520fb08448f.png">

**Comment by madkinsz** [comment]
Thanks @casey-green -- that's helpful. I'll report back here with more information.

**Comment by zhen0** [comment]
Thanks @madkinsz and @casey-green - the UI uses that end_time to show an end time and stop the calculation of duration but given that a skipped state wouldn't really have an end time (since it doesn't run), we could update the UI to better handle skipped states.  Are you seeing the ongoing duration anywhere apart from the tooltip you show in your screenshot?

I've added a ticket in the UI: https://github.com/PrefectHQ/ui/issues/1000. feel free to add any more details there.

**Comment by casey-green** [comment]
> Are you seeing the ongoing duration anywhere apart from the tooltip you show in your screenshot?

I don't think so. The only other thing I noticed is that the `Run History` widget appears to sort runs by end_time, so the skipped runs are always to the right (even if additional runs are submitted and finished). Here's an example:

Ran two successful flows, then 1 skipped:
<img width="452" alt="Screen Shot 2021-08-12 at 4 30 31 PM" src="https://user-images.githubusercontent.com/1815573/129265696-f25efa95-0f00-4c75-b605-e2ddcc3e71f1.png">

Then I ran a third successful one, which pushes the "Skipped" to the right
<img width="415" alt="Screen Shot 2021-08-12 at 4 31 49 PM" src="https://user-images.githubusercontent.com/1815573/129265697-2c68a4f0-f819-4910-8f2c-99932fead8c1.png">
