### ISSUE TITLE
Add Context to Clock Inputs/Schedules

### ISSUE THREAD

**Issue by jbertman** [PrefectHQ/prefect#4878]
## Current behavior
Schedules may currently contain default parameters to emit when clock events are up for execution. But we cannot currently influence the `context` of the resultant flow run. 

## Proposed behavior
I propose adding `context` as an available input on clocks and relevant `*schedule*` APIs, so that flow runs executed via schedule can have customizable context according to a stored object.

## Example
We can of course use parameters to pass information around, but Prefect's context store is an easy and robust way to share information among tasks and flows. In our use case, flow context is populated via API for normal runs from a backend system, We're looking to expand usage into the scheduler - since we can't populate context via schedule, we can't use the scheduler for our purpose.

Looking forward to your feedback. Thanks in advance!

**Comment by madkinsz** [comment]
Hey @jbertman, thanks for the feedback. We don't intend for the context to be used for user data, the intent is to only provide static Prefect metadata. I would not recommend using the Prefect context for storing your data in either ad-hoc or scheduled runs. As you pointed out, parameters should suffice. Parameters are designed to be clear entry points for data that will affect a flow and are already well supported. Is there a reason you choose the context over parameters?

**Comment by jbertman** [comment]
@madkinsz Thanks for the quick response. We use context as a way for various tasks to have access to the same data in the same way (`prefect.context.whatever` as opposed to a parameter that a task may or may not receive positionally. aside: do named/kwarg parameters work in Prefect?).

In the same vein, we will be supporting various flows on behalf of other teams, and plan on scheduling for them as well. As parameters and schedules grow, this could get unruly when we want to insert or remove a particular schedule, since the API seems to be simply `set` whatever you give it (seems easy to accidentally blow away all the schedules). Are there plans to insert or delete a single schedule for a flow group via API?

**Comment by madkinsz** [comment]
Yep, keyword arguments work.

Whilst it can be a convenience to pull data from the context, implicitly consuming data from a semi-mutable global store is not something we'd encourage. If a task requires data, we think it should explicitly consume it. What kind of data are you passing and what are you doing with it? I may be able to recommend a better pattern.

We're interested in improving the schedule API and there's some planned work, but I can't promise a time frame.

**Comment by jbertman** [comment]
Our main use case is a handful of tasks that consume an identifier for a centralized logging platform. Several different clients have the ability to kick off tasks, so we front Prefect with an API, then kick off a flow with their information populated in context (since their target flows have varying parameters). Then from any subsequent task we basically read off the information we need to tie the action to the originator.

Without single inserts and removals, I think we'll probably go with an external scheduling solution anyway. Looking forward to further improvements though, Prefect is a great platform.
