### ISSUE TITLE
Allow debugging env setup errors

### ISSUE THREAD

**Issue by Trymzet** [PrefectHQ/prefect#4879]
## Current behavior

When running the flow locally it works as intended. After registering and running from the cloud, I get the following error:
```
Failed to load and execute Flow's environment: FileNotFoundError(2, 'No such file or directory')
```
It would be useful to be able to retrieve the traceback for env setup errors.

**Comment by Trymzet** [comment]
In my case it turned out I had a `flow.visualize()` line at the end of the flow I was registering (after the `flow.register()` line) because I was using a Jupyter notebook to develop the flow and automatically converting the `.ipynb` to a `.py` file.

**Comment by madkinsz** [comment]
I've done some work on this, but haven't "turned it on" yet. I can investigate doing this soon.
