### ISSUE TITLE
Git storage still requires repo even if provided full clone URL

### ISSUE THREAD

**Issue by Trymzet** [PrefectHQ/prefect#4882]
## Description

#4870 introduced support for custom URLs in `Git` storage. However, the `repo` parameter is still required, so user needs to pass a placeholder value for it even if choosing to use `git_clone_url_secret_name`. This however results in a warning:

```
Git storage initialized with a `git_clone_url_secret_name`. The value of this Secret will be used to clone the repository, ignoring `repo`, `repo_host`, `git_token_secret_name`,  `git_token_username`, `use_ssh`, and `format_access_token`
```

**Comment by madkinsz** [comment]
Thanks for the report @Trymzet - should be an easy fix.

**Comment by Trymzet** [comment]
Seems like this is broken again, this time due to a `ValidationError` upon registering the flow:
```python
ValueError: Flow could not be deserialized successfully. Error was: ValidationError({'storage': {'repo': ['Field may not be null.']}})
```
It seems like the `GitSchema` class is the culprit, making `repo`, as well as `repo_host` required again, even when passing `git_clone_url_secret_name`.

**Comment by Trymzet** [comment]
Same thing @ccueto36 , we get this annoying warning on all of our 300+ flows :D

**Comment by madkinsz** [comment]
I do not have the time to investigate this much, but https://github.com/PrefectHQ/prefect/pull/5877 may do it? Can you give it a try?
