### ISSUE TITLE
Trouble starting prefect agent under supervisor

### ISSUE THREAD

**Issue by fingoldo** [PrefectHQ/prefect#4898]
### Discussed in https://github.com/PrefectHQ/prefect/discussions/4895

<div type='discussions-op-text'>

<sup>Originally posted by **fingoldo** August 20, 2021</sup>
Hi, I'm having trouble trying to make a local prefect agent start with my Ubuntu 20.04.1 LTS server.

I'm going with supervisor, as outlined in the docs:
1) logged in as root
2) made sure command `prefect agent local start --key XXXX` is working when typed in the command line
3) created supervisord.conf as generated by
`prefect agent local install --key XXXX`

But now when I'm trying supervisorctl update, it's having problems:

`prefect-agent                    BACKOFF   can't find command 'prefect'`

OK, adding to the .conf file a line 
`environment=PATH=/usr/local/bin/anaconda3/bin/prefect`

Error changes:
`
prefect-agent                    BACKOFF   command at '/usr/local/bin/anaconda3/lib/python3.7/site-packages/prefect' is a directory
`
What should I do? Any advice welcome )</div>

**Comment by fingoldo** [comment]
I am surprised no one at Prefect cared to answer, even when asked directly in the Cloud dashboard. I was able to figure out by myself, that it's important to use

environment=PATH=/usr/local/bin/anaconda3/bin/

It would be good to add this to the documentation, at least...

**Comment by kvnkho** [comment]
Hey @fingoldo,

Really sorry we didn't get to this! Glad to see you resolved it. Where do you think this belongs in the docs? It looks specific to your Python environment and may be hard to generalize. We're always happy to review PRs that improve our documentation!"

**Comment by fingoldo** [comment]
Well, I have a pretty standard setup, I'm sure many can run into this issue...
I think this piece of information could be useful in [using-with-supervisor](https://docs.prefect.io/orchestration/agents/local.html#using-with-supervisor). I'm not very skilled in submitting PRs, unfortunately. Thanks a lot!
