### ISSUE TITLE
Add Soda Task to our API docs

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#4913]
It seems we have a user-contributed task for SodaSQL that we don't expose in our API documentation, making it very hard to discover; task definition and docstrings here: https://github.com/PrefectHQ/prefect/blob/5de58efaba956b431335d99acab07eaf6a362e1b/src/prefect/tasks/sodasql/sodasql_tasks.py

We should add this to our reference docs using [our development guidelines](https://docs.prefect.io/core/development/documentation.html).

**Comment by Arun-kc** [comment]
Can I help? @cicdw This will be my first contribution in perfect

**Comment by cicdw** [comment]
Hi @Arun-kc - absolutely!  All of the documentation is already written for this task, so in theory all you should need to do is explicitly reference the task in Prefect's [documentation outline](https://github.com/PrefectHQ/prefect/blob/master/docs/outline.toml).

All of the info should be present in this one section of the developer guidelines: https://docs.prefect.io/core/development/documentation.html#api-reference but let me know if you have any questions

**Comment by Arun-kc** [comment]
Sure thing @cicdw. I got the gist of what to do with [documentation outline](https://github.com/PrefectHQ/prefect/blob/master/docs/outline.toml). But this developer guidelines part, I'm not sure what I should do there.

**Comment by cicdw** [comment]
Maybe this section will help you get oriented: https://docs.prefect.io/core/development/overview.html#getting-started

**Comment by AlessandroLollo** [comment]
Hey @Arun-kc!
I contributed the SodaSQL Task some time ago so I'm more than happy to help you integrating the docs.
Feel free to reach out to me!

**Comment by Arun-kc** [comment]
I'm facing an issue while running `python generate_docs.py`

![image](https://user-images.githubusercontent.com/22231409/136693229-20ffd40b-c3db-49cd-a9fd-38452328859d.png)

I'm using gitpod as my env

**Comment by AlessandroLollo** [comment]
I'm not familiar with `generate_docs.py` 😓 
Can you provide the steps to reproduce it?

**Comment by Arun-kc** [comment]
I was just following the instructions in this [documentation](https://docs.prefect.io/core/development/documentation.html#api-reference) @AlessandroLollo 
@madkinsz I will try that, but doing a lot of PR's, won't that look bad?
