### ISSUE TITLE
Parameters used as inputs to `case` aren't added to flow

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/prefect#4919]
## Description
Parameters can't be used directly as inputs into `case`.

This results in a workaround that wraps the parameter in a dummy task returning the parameter's value.

## Expected Behavior
Passing a parameter into a case statement should add the Parameter to the flow.

## Reproduction
```python
from prefect import Flow, task, case, Parameter

@task
def return_something():
    return "yes"

with Flow("test") as f:

    test_case = Parameter("example", required=True)

    with case(test_case, True):
        return_something

# UserWarning: Tasks were created but not added to the flow: {<Parameter: dummy-param>}.
```

## Environment
Prefect 0.15.1

**Comment by kvnkho** [comment]
Hey @jnoynaert 

I think you get this error because `return_something` is not called. If you do `return_something()`, this error goes away.

Full code snippet:
```python
from prefect import Flow, task, case, Parameter
import prefect

@task
def return_something():
    l = prefect.context.get("logger")
    l.info("returned")
    return "yes"

with Flow("test") as f:

    test_case = Parameter("example", required=True)

    with case(test_case, True):
        return_something()

f.run(parameters={"example": True})
```

**Comment by jnoynaert** [comment]
@kvnkho 👍 , let's pretend this never happened
