### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by banuni** [PrefectHQ/prefect#4920]
Hello!

I've found an issue here:`unmapped` should be `mapped` in the "mapped section

Page reference: https://docs.prefect.io/api/latest/utilities/edges.html

**Comment by mashun4ek** [comment]
Hello @banuni! Thank you for opening the issue, indeed it should be mapped, also looks like on the same page a `flatten` example should be tweaked too (in Flow block it should be `ll = NestedListTask()`).


<img width="736" alt="Screen Shot 2021-08-31 at 7 43 49 AM" src="https://user-images.githubusercontent.com/22859719/131496830-c11a370a-5aca-4ac9-bfb4-0cdbef700aef.png">

Would you like to open a PR with a fix?

**Comment by banuni** [comment]
sure, will do :)

**Comment by mashun4ek** [comment]
Closed in #4921 
Thank you for contributing! :)
