### ISSUE TITLE
Found in the Documentation

### ISSUE THREAD

**Issue by RufusGladiuz** [PrefectHQ/prefect#4922]
## Description

It is not an actual bug but in the documentation here -> https://docs.prefect.io/orchestration/concepts/api.html#queries
flow_run actually needs to be flow_runs.
Otherwise it does not work for me.

## Expected Behavior

Documentation should be updated.

## Reproduction

Try using flow_run instead of flow_runs

**Comment by meehawk** [comment]
@kvnkho can I take this up. This is going to be my first at Prefect

**Comment by madkinsz** [comment]
Yep @meehawk feel free

**Comment by kvnkho** [comment]
Thanks for getting the contribution in @meehawk

**Comment by meehawk** [comment]
Thanks to you @kvnkho . Hopefully many more on the way
