### ISSUE TITLE
Kafka Task undocumented

### ISSUE THREAD

**Issue by chris-aeviator** [PrefectHQ/prefect#4950]
## Description
A kafka task is available since https://github.com/PrefectHQ/prefect/pull/4533 but remains undocumented

**Comment by AlessandroLollo** [comment]
Kafka tasks docs can be found at https://docs.prefect.io/api/latest/tasks/kafka.html
I think we can close this issue 😊

**Comment by th0ger** [comment]
Could not find docs for Kafka Tasks in Prefect 2.0.
Was is migrated, pending or dropped?
