### ISSUE TITLE
Task logged as both success and failure

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/prefect#4964]
## Description
https://cloud.prefect.io/crane-analytics/task-run/2a61b163-93c9-4ea2-9901-dcac56354db9 logged both a success and a failure during execution.

This is not a mapped task. Is this an issue with the UI or logging?

```
06:35:44
INFO
CloudTaskRunner
Task 'upload_xlsx_raw_archive': Finished task run for task with final state: 'Failed'
06:35:44
INFO
CloudTaskRunner
Task 'upload_xlsx_raw_archive': Finished task run for task with final state: 'Success'
```

## Expected Behavior
Task to unequivocally succeed or fail

**Comment by jnoynaert** [comment]
This was using `DaskExecutor` with a Kubernetes agent (pretty much the default run config, the only change is that we modify the job template to attach some secrets and config maps)

**Comment by madkinsz** [comment]
It seems likely that the task was run twice by a dask worker; we try to guard against double execution but worker teardowns can result in some weirdness. Are you seeing this frequently?

**Comment by jnoynaert** [comment]
No, we haven't seen it again. Since our flows are idempotent we'll just note this as a possible issue.
