### ISSUE TITLE
Flow with big (1.2MB) Parameter dictionary

### ISSUE THREAD

**Issue by webfrank** [PrefectHQ/prefect#4985]
## Description

I have several flows with a big dictionary (1.2MB) and I'm using DaskExecutor which complains about this:

`Warning: Large object of size 1.21 MiB detected in task graph: 
  {'task': <Parameter: orgid>, 'state': None, 'upstr ... ed_states': {}}
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)`

## Expected Behavior

I expect to be able to move around this kind of dictionary

## Reproduction

Start a simple flow on a Dask cluster with a big dictionary as parameter

**Comment by madkinsz** [comment]
Hi @webfrank -- that's quite the parameter dictionary. If you switch it to be a task, this warning should go away as it will be stored in dask. Is there a reason it needs to be a parameter?

**Comment by webfrank** [comment]
Hi, yes, it comes from the flow scheduler and can be any dimension up to about 2MB

**Comment by madkinsz** [comment]
Is this large value only being set at runtime or does it have a big default value as well?

**Comment by gcasella** [comment]
Hi everyone!

I have the exact same question, I have a remote dask cluster, I have static data that I'm gathering in a single task, I want to scatter this data across all workers one time before running my .map()

Dask Method, this works as expected. It scatters the big_future1 to all workers.
```
if __name__ == '__main__':
    client = Client(address="tcp://remote-dask.local:8786")
    variables = client.submit(set_initial_variables)

    return1, return2, return3, return4, return5 = client.gather(variables)

    submit_icmp = client.submit(icmp_multiping, return1)
    devices, alive_devices = client.gather(submit_icmp)

    big_future = (return2, return3)
    big_future1 = client.scatter(big_future)

    submit_snmp = client.map(task1, eai_ips, big_future1, oids, snmp_session)
```

Prefect Method
```
@task(nout=2)
def get_db_data():
    dbConn = TxDb(db='Prefetch')
    raw_data = dbConn.get_data()
    raw_market = dbConn.get_data_market()
    return raw_data, raw_market


@task(nout=3)
def set_initial_variables():
    ips = list()
    ips.append('10.10.10.1')
    ips.append('10.10.10.2')
    ips.append('10.10.10.3')
    return ips

@task()
def check_dask_executor(target, big_future):
    log.info(f"Device: {target}")
    log.info(print(big_future))

client = Client(address="tcp://remote-dask.local:8786")

with Flow('Dummy1 Flow', executor=DaskExecutor(address=client.scheduler.address)) as new_flow:
    var1 = set_initial_variables()
    db_var1 = get_db_data()
    mapped_res = check_dask_executor.map(var1, unmapped(db_var1))

new_flow.run()
```
The goal of the above would be to map() through my set_initial_variables() task, and pass in the results from get_db_data() 

the above prefect example would give the following
```
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
```

I had to re-arrange the code a bit to remove sensitive data. 
I'm not sure if i'm missing something either.
I even attempted to do a client.scatter() prior to doing the map() function in prefect, however the dask.map() is not the same as prefect.task.map() 

I could provide additional information if needed. 

I'm not sure if it's doable to pass in a big_future into the DaskExecutor() function that Prefect currently has.

Apologies for re-starting an old issue.

**Comment by gcasella** [comment]
Please disregard above, i think i have figured it out.

```
def get_db_data():
    dbConn = TxDb(db='Prefetch')
    raw_data = dbConn.get_data()
    raw_market = dbConn.get_data_market()
    return raw_data, raw_market


@task(nout=1)
def set_initial_variables():
    ips = list()
    ips.append('10.10.10.1')
    ips.append('10.10.10.2')
    ips.append('10.10.10.3')
    return ips

@task()
def check_dask_executor(target, big_future):
    log.info(f"Device: {target}")
    log.info(len(big_future))


client = Client(address="tcp://remote-dask.local:8786")

with Flow('Dummy1 Flow', executor=DaskExecutor(address=client.scheduler.address)) as new_flow:
    var1 = set_initial_variables()
    big_future = client.scatter(get_db_data(), broadcast=True)
    mapped_res = check_dask_executor.map(var1,
                                         upstream_tasks=[var1],
                                         big_future=unmapped(big_future))

new_flow.run()

```

My two workers report the following;
`Worker #1`
```
INFO:prefect.TaskRunner:Task 'check_dask_executor[0]': Starting task run...
INFO:__main__:Device: 10.10.10.1
INFO:__main__:2
```

`Worker #2`
```
INFO:prefect.TaskRunner:Task 'check_dask_executor[2]': Starting task run...
INFO:__main__:Device: 10.10.10.2
INFO:__main__:Device: 10.10.10.3
INFO:__main__:2
INFO:__main__:2
```

**Comment by Urahara** [comment]
@madkinsz 

I receive larger payload via webhook that i need to run through prefect pipeline that why it came via `Parameter`.

Is there a reason why we can't override this value? https://github.com/PrefectHQ/server/blob/master/src/prefect_server/graphql/states.py#L29

I did a hotfix in my environment because without my flow was always failing. Can we have the possibility to override this value or at least understand why is desgined like that? Thanks.

I also send a message in slack about this: https://prefect-community.slack.com/archives/CL09KU1K7/p1675126653486849

**Comment by madkinsz** [comment]
@Urahara see https://github.com/PrefectHQ/server/issues/349#issuecomment-1054399596
