### ISSUE TITLE
Support For Shutting Down Compute When Flow is Cancelled

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#4988]
## Current behavior

This issue is probably better as a Github Discussion, but it seems some people want an issue to keep track of so that they can get notified when it gets fixed. 

When a Flow is cancelled from the UI or API, the Flow just exits leading to hardware left running. This is most common in the case of running Kubernetes jobs or using a Dask cluster as a resource manager. When the flow is cancelled abruptly, the resource manager `cleanup` method is not called. Cancellation is currently a best effort to shutdown everything as soon as possible, without any options for users to describe the shutdown logic.

In these cases, the user has to manually shut down the compute themselves.

## Proposed behavior

Some users have tried Flow level state handlers to take care of shutting down the compute. Unfortunately, this does not work because the Flow is just exited and the state handler is not called. State handlers are only called before updating the state in the API. If this worked though, it would be a good solution to housing cleanup logic.

**Comment by luklss** [comment]
I have bumped exactly into this use case. Following is some code I wrote that illustrates it:

```python
import os
import uuid
import time
import prefect
from prefect import Task, Parameter
from prefect.executors.dask import LocalDaskExecutor
from prefect.utilities.edges import unmapped


def clean_up(task, old_state, new_state):
    logger = prefect.context.get("logger")
    task_full_name = prefect.context.get("task_full_name")
    # Below I tried catching different states, none of them worked.
    if isinstance(new_state, prefect.engine.state.Failed):
        logger.info(
            f"cleaning up job {task.run_id}-{task_full_name} due to new state being {new_state}"
        )
    elif isinstance(new_state, prefect.engine.state.Cancelled):
        logger.info(
            f"cleaning up job {task.run_id}-{task_full_name} due to new state being {new_state}"
        )
    elif isinstance(new_state, prefect.engine.state.Cancelling):
        logger.info(
            f"cleaning up job {task.run_id}-{task_full_name} due to new state being {new_state}"
        )


class DoSomeComputation(Task):
    def __init__(self, **kwargs):
        self.run_id = str(uuid.uuid4())[:8]
        super().__init__(**kwargs)

    def run(self, input, fail=True):
        logger = prefect.context.get("logger")
        logger.info(f"Started some computation task with input {input}")
        for i in range(0, 200):
            time.sleep(1)
        if fail:
            raise Exception("Something terrible happened")
        logger.info("Sucessful completed some computation task")


if __name__ == "__main__":
    project_name = "test-flows"
    flow_name = "test-cleanup"
    with Flow(...) as flow: # Using a k8s run, hidding the creds details here
        fail = Parameter("fail")
        do_some_comp = DoSomeComputation(
            state_handlers=[clean_up], task_run_name="{task_name}-job-name={input}"
        )
        inputs = ["input1", "input2", "input3"]
        do_some_comp.map(inputs, unmapped(fail))

    flow.executor = LocalDaskExecutor(num_workers=20)
    flow.register(project_name=project_name)
```

**Comment by luklss** [comment]
Another important factor here for our use case is that the state handler needs to be on the task level, as we are spawning a kubernetes job for each task using a task specific attribute (in the above `run_id` for instance).

**Comment by AlexanderVanEck** [comment]
# On flow cancellations, resource managers & state_handlers

Flow cancellations not triggering resource manager cleanup tasks seems logical if we remember that a resource manager is nothing more than a setup and a cleanup task. When the cancellation happens the cleanup task is never scheduled.

Task cancellations are similar as the state_handler tasks are required to be called after the task executes, and because the flow is interrupted no more tasks are scheduler (the state handlers are just tasks after all).

Perhaps we require a mechanism to signal FlowRunner to _always run_ certain tasks?

**Comment by chrishinds** [comment]
definitely +1. I also just went down the state handler route. Would love a cleanup solution!

**Comment by krasoffski** [comment]
Still valid.

**Comment by madkinsz** [comment]
Is this for Prefect 1? In Prefect 2 cancellation is enforced at the infrastructure level to ensure the flow infrastructure tears down.

**Comment by krasoffski** [comment]
I had problem with Prefect 2.

**Comment by vdytyniak-exos** [comment]
> Is this for Prefect 1? In Prefect 2 cancellation is enforced at the infrastructure level to ensure the flow infrastructure tears down.

I have this issue in Prefect 2:
```
@contextlib.contextmanager
def create_cluster(
    name: str,
    **kwargs: Any,
) -> Generator[Cluster, None, None]:
    cluster = Cluster(...)

    try:
        yield cluster
    finally:
        cluster.shutdown()
```

In case flow I cancelled `finally` block is not executed. Do you have any ideas how to shutdown the cluster on cancel?

**Comment by matankley** [comment]
@zanieb @vdytyniak-exos @krasoffski 
Hi guys, any workaround for that issue?

I have prefect flows running as kubernetes jobs. The k8 jobs are not cancelled when I cancel the flow from the UI.

This bug is very crtitical for us since we can not use prefect that way.

**Comment by krasoffski** [comment]
@matankley 
> Hi guys, any workaround for that issue?

**Comment by jamedge** [comment]
Idk if it fully fits your problem, but we use a state handler (for transitions to cancelling state iirc) that deletes all k8s jobs that have the flow run id label - and we set this label to all tasks running as k8s jobs during their creation. We still use prefect 1 though, but gonna migrate to v2 soon, so I'm also curious how is this handled there :)
