### ISSUE TITLE
Sphinx to use automodule directive to generate documentation from Tasks

### ISSUE THREAD

**Issue by lpravda** [PrefectHQ/prefect#4995]
Hi all, I was pointed here from the Prefect community slack channel. and I'd like to propose a possible feature/plugin for sphinx to be capable of generating documentation from Prefect tasks defined by a decorator, which is presently not possible in an automated fashion. 

## Current behavior
When is a Prefect task defined by a decorator, the resulting docstring cannot be automatically consumed by Sphinx `automodule` directive. Workarounds I'm aware of based on [this](https://github.com/PrefectHQ/prefect/issues/2551) and [this](https://github.com/PrefectHQ/prefect/pull/2602):

* use `autofunction` directive - cumbersome, as each task to be documented needs to be defined in the documentation manually, nevertheless the generated documentation has everything I need and looks good.
* define a task using Class/run method combination. `automodule` directive works in this case, but defining simple tasks through class/run is a bit of a pain and the documentation lists all Tasks parameters, which I don't think is necessary at that point.

## Proposed behavior
Would be great if the documentation works through `automodule` directive automatically, either out of the box (I know this may not be possible), or by implementing a sphinx plugin. I've come across a [celery solution](https://docs.celeryproject.org/en/stable/userguide/sphinx.html)

**Comment by madkinsz** [comment]
I'd be willing to review a community contribution of this but I am not sure it belongs in this repository and we will likely not be able to prioritize such a plug-in ourselves.

**Comment by ConstantinoSchillebeeckx** [comment]
@madkinsz I ended up [implementing](https://github.com/sphinx-contrib/prefecttask) this and submitting it to sphinx-contrib
