### ISSUE TITLE
Missing documentation for getting flow run logs

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#5036]
## Description
No text beneath header "Getting flow run logs" in documentation. [Getting flow run logs](https://docs.prefect.io/orchestration/flow-runs/inspection.html#getting-flow-run-logs)

## Expected Behavior
Text describing how to get flow run logs. Darren Pinder says it should be this:
`FlowRun.from_flow_run_id(...).get_logs()`

## Reproduction
[Getting flow run logs](https://docs.prefect.io/orchestration/flow-runs/inspection.html#getting-flow-run-logs)
![getting flow run logs](https://user-images.githubusercontent.com/8505845/136625410-d489d760-dde1-46d4-949a-7e3426e54c45.jpg)

**Comment by INVINCIalokk** [comment]
Can someone guide me how to solve this issue ? . I am willing to solve this issue.

**Comment by madkinsz** [comment]
You can describe how to use `FlowRunView.get_logs` and give an example.

**Comment by INVINCIalokk** [comment]
![Screenshot 2022-01-15 164008](https://user-images.githubusercontent.com/94790295/149619626-f03dc4a8-f328-44b9-bbab-2719a98423c2.png)
---
IT is already described in docs
