### ISSUE TITLE
Orion: prefect version command outputs '0+unknown'

### ISSUE THREAD

**Issue by mariushab** [PrefectHQ/prefect#5041]
## Description

The prefect version command does not work as expected

```
$ prefect version
0+unknown
```
## Expected Behavior

```
$ prefect version
2.0a1
```

## Reproduction

I executed the following commands

```
$ conda create -n prefect-playground python=3.9
$ conda activate prefect-playground
$ pip install prefect==2.0a1
```

## Environment

OS: macOS Big Sur 11.4 with M1 chip

**Comment by Bojne** [comment]
I ran into the same message when installing with `pip install prefect==2.0a1`. Seems like community has reported this problem before, hope this one is relevant. https://github.com/python-quantities/python-quantities/issues/122 @cicdw 

- My system is MacOS Catalina `10.15.2`.
- If I type `conda list prefect`, it shows version of `2.0a1`.
