### ISSUE TITLE
LocalDaskExecutor fails for > python 3.7 on AWS Lambda

### ISSUE THREAD

**Issue by jacques-** [PrefectHQ/prefect#5046]
## Description

Not sure if this is a bug or should be a feature request - but basically the `LocalDaskExecutor` does not work in AWS Lambda if python version is > 3.7.

We get an error msg like the following:
```
[Errno 38] Function not implemented: OSError

    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented
```

This is due to `multiprocessing.pool` relying on shared memory (`/dev/shm`) which is not available in Lambda. See https://forums.aws.amazon.com/thread.jspa?threadID=219962 for ref.

## Expected Behavior

Expected the `LocalDaskExecutor` work in python 3.8/3.9 like is does in 3.7

## Reproduction

Reproduction is fairly trivial if you run any flow using `LocalDaskExecutor` in Lambda with a 3.8 python runtime.

## Work around

Looked at the comments here: https://github.com/PrefectHQ/prefect/blob/a6988f64e0538a5e35270004b39658a757d9d01e/src/prefect/executors/dask.py#L642 and based on that we changed https://github.com/PrefectHQ/prefect/blob/a6988f64e0538a5e35270004b39658a757d9d01e/src/prefect/executors/dask.py#L540 from:

```
                    from multiprocessing.pool import ThreadPool

                    self._pool = ThreadPool(num_workers)
```

to:

```
                    from concurrent.futures import ThreadPoolExecutor

                    self._pool = ThreadPoolExecutor(num_workers)
                    self._pool.close = self._pool.shutdown
                    self._pool.join = self._pool.shutdown
```

This seems to work, but no idea if this is the proper way to do it of if it's going to subtly break things elsewhere?

**Comment by madkinsz** [comment]
Hi! We'll need to investigate if we can switch to the `futures` implementation. Thanks for bringing this to our attention!

**Comment by jacques-** [comment]
Cool, we've been testing this against a fair number of slightly complex flows for the last few hours in our dev environment and no errors jumping out yet, so that is at least some kind of datapoint.

**Comment by andywaugh** [comment]
Hey, small update but just an FYI that we've been using the change detailed above in our prod env for a couple weeks now and it seems to work without issue. Are you open to us cleaning it up a bit and submitting a PR?

**Comment by madkinsz** [comment]
Thanks @andywaugh — I'd be happy to review a PR.

**Comment by jacques-** [comment]
Got a first pass at a PR in, it's def not 100% yet, but if you could give me some idea how for this is from what you'd need?
