### ISSUE TITLE
Orion: remove requirement for `click <8.0'

### ISSUE THREAD

**Issue by esegal** [PrefectHQ/prefect#5058]
## Description
It seems click version must be 7.xx and doesn't support click 8.xx. An internal package I use forces click 8.xx - so I get a pip conflict trying to install it.

https://github.com/PrefectHQ/prefect/blob/master/requirements.txt#L1

It would be nice to drop the <8.0 requirement

**Comment by esegal** [comment]
Hi @zangell44, thanks for the quick reply. It's a dependency that comes from from an internal package I use, which doesn't use click directly (but as part of other imported packages). I'm also trying to ask that the internal package changes.

**Comment by madkinsz** [comment]
This will be in the next alpha release.
