### ISSUE TITLE
Pause/Resume

### ISSUE THREAD

**Issue by sletovsky** [PrefectHQ/prefect#5060]
I am trying to implement a "batching" class for services that accumulate a collection of work requests until a batch size is reached, and then process the batch as a unit. I want individual workflows not to have to know that batching is happening, so they should simply execute a task to get the work done, and behind the scenes logic should ensure that they wait for their task to be processed as part of a batch, and then resume. I don't want these individual tasks to waste cycles busy-waiting for batch completion. I thought pause/resume might work -- individual requests pause until the batch manager tells them to resume -- but  pause seems hardwired to only wait for user input, and I can't find a way to control pause/resume programmatically. Am I looking in the wrong place? I tried returning a paused state from a state handler but that has the same effect as raising a pause signal directly; there does not seem to be a state available to implement a programmatically controlled wait.
Also pause does not work as I expected, in that even when I enter y it does not resume but keeps asking for input. See sample code below.

import prefect
from prefect import task, Flow, Parameter
log=prefect.utilities.logging.get_logger(name=None)

def block() : 
    # time.sleep(.5)
    raise prefect.engine.signals.PAUSE() # message=None, *args, **kwargs)

@task
def testblock(id) :
    # prefect.tasks.prefect.flow_run.wait_for_flow_run(flow_run_id, stream_states=True, stream_logs=False)
    block()
    log.info(f'{id} Unblocked')

with Flow("test block") as flow: 
        id=Parameter('id')
        testblock(id)
    
r1=flow.run(id=1)

**Comment by cicdw** [comment]
Closing as stale
