### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [PrefectHQ/prefect#5064]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/src/prefect/backend/flow_run.py b/src/prefect/backend/flow_run.py
index 5a53ad6f9..0badb2a92 100644
--- a/src/prefect/backend/flow_run.py
+++ b/src/prefect/backend/flow_run.py
@@ -582,7 +582,7 @@ class FlowRunView:
             task_runs = []
 
         # Combine with the provided `_cached_task_runs` iterable
-        task_runs = task_runs + list(_cached_task_runs or [])
+        task_runs += list(_cached_task_runs or [])
 
         return cls._from_flow_run_data(flow_run_data, task_runs=task_runs)
 
diff --git a/src/prefect/schedules/clocks.py b/src/prefect/schedules/clocks.py
index 60fbb24eb..7df812aa1 100644
--- a/src/prefect/schedules/clocks.py
+++ b/src/prefect/schedules/clocks.py
@@ -308,7 +308,7 @@ class CronClock(Clock):
 
         # Respect microseconds by rounding up
         if after_localized.microsecond:
-            after_localized = after_localized + timedelta(seconds=1)
+            after_localized += timedelta(seconds=1)
 
         cron = croniter(self.cron, after_localized, day_or=self.day_or)  # type: ignore
         dates = set()  # type: Set[datetime]
```

**Comment by zangell44** [comment]
Hey @elfring, this is interesting, thanks for bringing this up! 

Any chance you could share a bit more about the source code analysis tools? I'm curious about what other suggestions they make and how/why they affect performance

**Comment by madkinsz** [comment]
Whilst I believe that new code should adhere to this, I do not see a significant benefit from changing existing code unless we are doing other work near it as we are trying to reach a stable version.

**Comment by elfring** [comment]
:thought_balloon: Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?

**Comment by madkinsz** [comment]
I'm entirely in support of this syntax and would insist that PRs follow the new patterns, but we have little to gain by changing existing working code.

**Comment by elfring** [comment]
:thought_balloon: Under which circumstances would you get into the mood to measure and reconsider the influence of two questionable statements on the software rum time characteristics?
