### ISSUE TITLE
Having 1 FAILED and 1 SKIPPED Upstream Task Returns SKIPPED and It's Hard to Make the Task FAIL

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5071]
## Current behavior

In the code snippet below, `task_b` will SKIP instead of FAIL.

```python
from prefect import Flow, task, case
from prefect.engine.signals import SKIP

@task
def task_a():
    raise ValueError()

@task(skip_on_upstream_skip=True)
def task_b():
    return 1

@task()
def task_get_test_value():
    raise SKIP

with Flow("...") as flow:
    a = task_a()
    test_value = task_get_test_value()
    b = task_b()
    b.set_upstream(a)
    b.set_upstream(task_get_test_value)

flow.run()
```

For this specific user, they were trying to propagate the error past a `case` task:

```python
from prefect import Flow, task, case

@task
def task_a():
    raise ValueError()

@task(skip_on_upstream_skip=False)
def task_b():
    return 1

@task()
def task_get_test_value():
    return 'test-against-tis'

with Flow("...") as flow:
    a = task_a()
    test_value = task_get_test_value()
    with case(test_value, 'test-against-this'):
        b = task_b()
        b.set_upstream(a)

flow.run()
```

There doesn't seem to be a good way to propagate the failure from `task_a` to `task_b`.

## Proposed behavior
I think there might have to be some way to prioritize FAILED over SKIPPED for tasks?

**Comment by d1manson** [comment]
I have solved my problems by subclassing the `case` class as follows:


```python
from prefect import task
from prefect.tasks.control_flow import case

__all__ = ("if_equal",)

@task(name='case:end', skip_on_upstream_skip=False)
def end_case():
    pass

class if_equal(case):
    def __enter__(self):
        self._end_case = end_case()
        super().__enter__()
        return self._end_case

    def __exit__(self, *args):
        super().__exit__(*args)

        for task in self._tasks:

            # If the task has no downstream tasks within the context, we consider it a final task (within this context)
            if not self._flow.downstream_tasks(task).intersection(self._tasks):
                self._end_case.set_upstream(task)

            # If the task has any upstream tasks outside of the context, we route their dependance around the context itself
            # This deals with the skip vs fail issue: https://github.com/PrefectHQ/prefect/issues/5071
            for upstream_task in self._flow.upstream_tasks(task).difference(self._tasks):
                self._end_case.set_upstream(upstream_task)



This can now be used as:


```python
a = task_a()
x = task_x()
with if_equal(x, '42') as conditional:
  b = task_b()
  b.set_upstream(a)
c = task_c()
c.set_upstream(conditional)
```

Task `c` will run after task `b`, whether or not `b` is skipped. And if `a` fails, the failure will propagate through to the end.

It's not beautiful, and the schematics certainly look rather confusing, but it seems to do what i want.

**Comment by d1manson** [comment]
**Update** I have forked (i.e. copy-pasted) the implementation of `case`. My control flow helper seems to work nicely for my use case.

I put it in a gist [here](https://gist.github.com/d1manson/81c5982b144671783b37b71de12c7be5)

Here's a screenshot of a bit of my flow where I first validate the existing data I have, and then either do some expensive work to update it, or skip it (in this case skip it). In either case we continue on afterwards. If anything fails the whole thing fails.

![Screenshot 2021-10-20 at 20 00 44](https://user-images.githubusercontent.com/4244876/138155221-85958525-aa97-48ae-8552-c9786e7976a7.png)

Note that this is actually nested within another block with a condition controlled by a `Parameter`.

**Comment by snikolakis** [comment]
An easy way to achieve transforming the `Skipped` state of a task into `Success` is by simply creating a new downstream task of the task we need to transform the state. The new task is not necessary to perform any actions but it can propagate the `Success` and `Failed` states and perform the transformation as stated above. A simple example follows:

```python
@task()
def skip_task():
    raise SKIP

@task(skip_on_upstream_skip=False)
def transform_states():
    pass
```
Set dependencies inside the `Flow` context block:

```python
...
a = skip_task()
b = transform_states()
flow.set_dependencies(b, upstream_tasks=[a])
...
```
The state of `b` will be `Success`.

This is a rather simple solution to the problem but it introduces an unnecessary task inside the flow. Please let me know if there is a better and not so complex way to solve this.

In any case, hope it will help someone else.
