### ISSUE TITLE
Task missing UUID in `get_or_create_task_run_info` in 0.15.5+

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#5075]
Users upgrading to 0.15.5+ are encountering empty task id or flow run id string task errors during flow runs.

For example:

```
prefect.exceptions.ClientError: [{'path': ['get_or_create_task_run_info'], 'message': 'Expected type UUID!, found ""; Could not parse UUID: '
```

If reporting a reproduction, please include:
- Does this reproduce on 0.15.5?
- Does this reproduce on 0.15.6 or 0.15.7?
- What agent are you using?
- What executor are you using?

A debug branch that can help us determine the source of the issue exists at https://github.com/PrefectHQ/prefect/pull/5076

This may be related to https://github.com/PrefectHQ/prefect/pull/4930 and has been reported in Prefect Server and Cloud.

See previous discussion at
- #4687
- https://prefect-community.slack.com/archives/CL09KU1K7/p1634853488119200
- https://prefect-community.slack.com/archives/CL09KU1K7/p1632735840323400

**Comment by madkinsz** [comment]
We cannot reproduce and have not seen additional cases.

**Comment by MrJack91** [comment]
FYI:
We guess this happens when you use a storage type that rebuilds a flow in a combination of a generic flow.
Then if the flow to run and the registered are not the same (e.g. additional dependencies) it will crash at the end of the flow with this error.

I'm not sure if there is an inbuilt check if the flow definition matches the one which is registered.
On top of that if you use generic flows you can create a different flow with the same hash but other content. Maybe this error occurs if this happens.

**Comment by zyzil** [comment]
I've had this happen a few times. The most recent was today. I made a change to a flow, and upon first registration I received this error:

```
Failed to retrieve task state with error: ClientError([{'path': ['get_or_create_task_run_info'], 'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'locations': [{'line': 2, 'column': 101}], 'path': None}}}])
Traceback (most recent call last):
  File "/opt/prefect-runner/pysetup/.venv/lib/python3.9/site-packages/prefect/engine/cloud/task_runner.py", line 154, in initialize_run
    task_run_info = self.client.get_task_run_info(
  File "/opt/prefect-runner/pysetup/.venv/lib/python3.9/site-packages/prefect/client/client.py", line 1479, in get_task_run_info
    result = self.graphql(mutation)  # type: Any
  File "/opt/prefect-runner/pysetup/.venv/lib/python3.9/site-packages/prefect/client/client.py", line 473, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'path': ['get_or_create_task_run_info'], 'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'locations': [{'line': 2, 'column': 101}], 'path': None}}}]
```

I re-registered the flow by running the same previous command in my shell without any other changes. The second attempt also failed with the same error message. I was pointed to a transient registration error on Slack and re-ran the process to register a third time and the third time the flow started running successfully.

Here are my environment details:

- Prefect Version: `1.2.1`
- Backend: `cloud`
- RunConfig: `KubernetesRun`
- Storage: `Docker`
