### ISSUE TITLE
Flow execution fails if performance_report_path is provided

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#5090]
## Description

#5032 tries to initialize the performance report context before initializing the dask client, which fails.

~Making the `performance_report()` call lazy, like~:
```
        performance_report_context = (
            performance_report
            if self.performance_report_path
            else lambda _: nullcontext()
        )
```
~almost fixes the issue~ (edit: this part was incorrect, see below), but because we pass `set_as_default=False` to `Client()`, the performance report still fails as it tries to look up the active client with `distributed.get_client()`. So we'd need to toggle that as well which may be a bit riskier.

## Reproduction

Running the example from the docs added in #5032 gives:
```
[2021-10-28 15:00:53-0400] ERROR - prefect.performance_report | Unexpected error occured in FlowRunner: ValueError('No global client found and no address provided')
```

## Environment

prefect 0.15.7

## cc
@zach-angell @madkinsz

**Comment by kvnkho** [comment]
I just ran into this trying to benchmark the Dask memory stuff. Did you have a workaround @bnaul ?

**Comment by bnaul** [comment]
yes, I just pass `client_kwargs=dict(set_as_default=True)` in my executor

**Comment by wangjoshuah** [comment]
@kvnkho and @bnaul I'm still running into this error on `prefect==1.2.2`

It's working with `client_kwargs=dict(set_as_default=True)`, so Brett thank you for the workaround! I'm wondering if that's the permanent solution going forward, or if there will be other solutions implemented to the `prefect` library.

Example snippet
```python
from prefect import Flow, task
from prefect.executors import DaskExecutor

@task
def hello_world():
    print("hello, world")

with Flow(
        "test",
        executor=DaskExecutor(
            performance_report_path="/tmp/performance_report.html"
        ),
    ) as flow:
        hello_world()


flow.run()
```

Logs:
```
ERROR - prefect.FlowRunner | Unexpected error: ValueError('No global client found and no address provided')
Traceback (most recent call last):
  File "prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "prefect/engine/flow_runner.py", line 442, in get_flow_run_state
    with self.check_for_cancellation(), executor.start():
  File "contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "prefect/executors/dask.py", line 252, in start
    with performance_report_context:
  File "distributed/client.py", line 5376, in __enter__
    get_client().sync(self.__aenter__)
  File "distributed/worker.py", line 4186, in get_client
    raise ValueError("No global client found and no address provided")
ValueError: No global client found and no address provided
DEBUG - prefect.FlowRunner | Flow 'test': Handling state change from Running to Failed
ERROR - prefect.test | Unexpected error occured in FlowRunner: ValueError('No global client found and no address provided')

Process finished with exit code 0
```

**Comment by bnaul** [comment]
I've just been passing `set_as_default=True`, it's baked into a helper that we use so I don't have to think about it. Don't know that there's a better option, I assume changing to always pass `set_as_default=True` by default in `prefect` would be pretty disruptive
