### ISSUE TITLE
Remove `required` kwarg from `Parameter`

### ISSUE THREAD

**Issue by schmidt-jake** [PrefectHQ/prefect#5091]
## Current behavior
Currently, `Parameter` supports a `default` value as well as a `required` boolean.
From the docstring:
- default (any, optional): A default value for the parameter. Must be a JSON-Serializable type.
- required (bool, optional): If True, the Parameter is required and the
            default value is ignored. Defaults to `False` if a `default` is
            provided, otherwise `True`.

## Proposed behavior
Seems to me that things should just work like a normal function: if you don’t set a default, the arg is “required” de facto. What am I missing?

## Example
```python
from prefect import Parameter


required_param = Parameter(name="required_param")
param_with_default = Parameter(name="param_with_default", default="my_default")


# the params defined above are equivalent to this python function signature
def my_func(required_param, param_with_default: str = "my_default"):
    pass
```

**Comment by schmidt-jake** [comment]
As of Nov 18, 2021, prefect says this is a `wontfix`.

**Comment by madkinsz** [comment]
> As of Nov 18, 2021, prefect says this is a `wontfix`.

Did someone else suggest this or just the lack of response?

I am willing to consider this change for 1.0, I'm just not sure of the origins of this choice and would need to check if it matters.

**Comment by schmidt-jake** [comment]
My company had a call with Prefect yesterday and they updated us saying this issue would be deferred — they seemed to feel it was more work than expected in a direction outside of their main scope for 1.0 🤷🏻

**Comment by madkinsz** [comment]
After checking in with the rest of the team, we're in agreement that this would be a primarily cosmetic change which is not worth breaking current user's workflows — we generally want to remain backwards compatible where feasible even as we move towards 1.0.
