### ISSUE TITLE
Support GraphQL API Mutation Calls in Automations

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5093]
## Proposed Behavior

This was a feature requested from Slack. This is currently not available. With it though, users will be able to create other Flow Runs based on the Cancelled state of Flow runs that already run. Successful and failed flows can already trigger GraphQL API calls with the Flow-level state handler. There is a gap though when it comes to Cancellations from the UI because the state handlers are not it.

Supporting this would also allow a late Flow to be a trigger to start another Flow run.

**Comment by madkinsz** [comment]
I think this is already possible with the custom webhook action.

There's also a `CreateFlowRunAction` that does not yet have UI support https://github.com/PrefectHQ/cloud/pull/3471
