### ISSUE TITLE
Doc Pages to Consider Removing

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5096]
## Description

First is this page:
https://docs.prefect.io/core/examples/overview.html#running-with-prefect-cloud-or-server

It doesn't really help users do anything with Prefect and causes confusion for people starting out.

At the bottom of the page it links to this:
https://docs.prefect.io/orchestration/tutorial/overview.html

which has the correct information, but is a bit lacking in context on the bigger picture.

It feels that the information there may belong in the quick-start here:
https://docs.prefect.io/orchestration/getting-started/quick-start.html

There is also some overlapping of content, and this page is more prominent. The second two links feel very close to each other in spirit.

**Comment by madkinsz** [comment]
I think https://github.com/PrefectHQ/prefect/pull/5086 is already addressing some of this?

**Comment by kvnkho** [comment]
Yes it is, but I was chatting with @tpdorsey anyhow and he asked I create an issue and assign it to him so he can take a look.

**Comment by tpdorsey** [comment]
Not overlap. This is additional work to bring other pages up to the standard of #5086

**Comment by tpdorsey** [comment]
Resolved by https://github.com/PrefectHQ/prefect/pull/5241
