### ISSUE TITLE
set_flow_run_name() fails on DaskExecutor

### ISSUE THREAD

**Issue by carderne** [PrefectHQ/prefect#5146]
## Description
`set_flow_run_name()` fails when run using `DaskExecutor` using `GCPCluster`. Other code (`prefect.context` etc) works fine, and the `set_flow_run_name()` *does* work when running locally.

I don't have any debugging information as the run just fails without any logging, and haven't found a way to get more info out of the Dask worker... But I have confirmed that it is this line alone that causes issues. Have tried also with `--run-name=foobar`, `--log-level=DEBUG` and `--watch` but no difference.

## Expected Behavior
Flow run to be renamed and finished successfully.

## Reproduction
```python
@task
def rename_flow_run():
    flow_id = prefect.context.get("flow_run_id")
    prefect.client.Client().set_flow_run_name(flow_id, "new_name")

executor = DaskExecutor(
    cluster_class=GCPCluster,
    cluster_kwargs={
        ...
    },
)
with Flow("test", executor=executor,) as flow:
    rename_flow_run()
```

```bash
prefect run -p flow.py
```

## Environment
Local environment: Python 3.9.7, prefect 0.15.9.

The `DaskExecutor` is using `GCPCluster` with a Packer image (nothing changed from defaults except to access private Docker repo) and a Docker image with `prefect==0.15.9` and latest versions of Dask, CloudProvider etc.

**Comment by madkinsz** [comment]
Hi! Here you note using `prefect run -p ...` to run this flow which is a local-only run so it has no representation in the API. In this case, I'd expect setting the flow run name to fail since the flow run id is random and meaningless. Is this occurring for registered flow runs?

**Comment by carderne** [comment]
Sorry yes just tested and it works with a registered flow run.

**Comment by carderne** [comment]
Just emphasising: this task *only* fails when running on a remote Dask cluster called from a non-registered flow. (i.e. the random Flow run id issue doesn't surface when running with a `LocalExecutor`)

**Comment by madkinsz** [comment]
You could try to get additional debugging info with

```python
@task
def rename_flow_run():
    flow_id = prefect.context.get("flow_run_id")
    try:
        prefect.client.Client().set_flow_run_name(flow_id, "new_name")
    except:
         prefect.context.logger.error("Error!", exc_info=True)
```

Are you using Server or Cloud when registering flows? What's the output of `prefect auth status`? What's the output of `prefect diagnostics`?

**Comment by carderne** [comment]
No logs make it back to my console, so with that code it just 'succeeds' silently. Btw this isn't particularly important for me, and maybe running Dask clusters from un-registered runs just isn't a supported/important use case for anyone? Not sure if this no-logs behaviour is expected or not.

I'm authed with Cloud, Prefect 0.15.9, Python 3.9.7, Ubuntu 20.04.

**Comment by madkinsz** [comment]
It seems quite likely that something wasn't being pickled so the task was failing on the worker but now that it's pip-installed it's available?

We value the use-case, but there aren't great ways to stream logs from dask and we already have a setup for distributed logging and introducing a new one for this specific case seems like a stretch. I think most people set up log collection on their infrastructure directly in this case (e.g. have dask print to standard out and collect it from there).

**Comment by carderne** [comment]
It was definitely only when `set_flow_run_name` was called, but yes it must have been something like that.

Sorry for the dead-end...
