### ISSUE TITLE
wait_for_flow_run(stream_logs=True) fails if running in Cloud

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#5147]
## Description

`wait_flor_flow_run(stream_logs=True)` raises a GraphQL exception if running inside Cloud:
```
Task 'wait_for_flow_run': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/brett/model/.venv/lib/python3.9/site-packages/prefect/tasks/prefect/flow_run.py", line 250, in wait_for_flow_run
  File "/usr/local/lib/python3.9/site-packages/prefect/backend/flow_run.py", line 146, in watch_flow_run
    logs = flow_run.get_logs(
  File "/usr/local/lib/python3.9/site-packages/prefect/backend/flow_run.py", line 472, in get_logs
    result = client.graphql(
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 569, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'path': ['flow_run'], 'message': 'field "logs" not found in type: \'flow_run\'', 'extensions': {'path': '$.selectionSet.flow_run.selectionSet.logs', 'code': 'validation-failed', 'exception': {'message': 'field "logs" not found in type: \'flow_run\''}}}]
```
My guess is this error is actually some kind of authentication/permissions failure related to the runner token (or whatever they're called now) that you inherit from the `CloudFlowRunner`. Not totally sure how to debug further but I did try putting in a debugger and running the exact same `client.graphql()` call from my worker but with the API key specified directly, and that worked fine.

## Reproduction

```
from prefect import Flow
from prefect.tasks.prefect import create_flow_run, wait_for_flow_run

with Flow("subflow") as f:
    wait_for_flow_run(
        create_flow_run(flow_name="hello-world", project_name=..., labels=...),
        stream_logs=True,
    )
```

## Environment

This is running on the #5138 branch but presumably that doesn't matter

**Comment by madkinsz** [comment]
The authentication method will matter here. Are you using an API key or (the older) authentication tokens on your agent?

**Comment by bnaul** [comment]
Thanks @madkinsz, I had thought I was using API keys everywhere now but in fact our old k8s agent got brought back from the grave by some automated job which switched us back to tokens there. After migrating that agent to API keys the logs show up properly now.

**Comment by madkinsz** [comment]
Thanks for investigating! It's good to know tokens will not work with this query. I don't think we'll bother adding support since we're removing client-side token support entirely (#5140).

**Comment by bnaul** [comment]
+1, in general it will actually be great to have an explicit "stop using tokens" exception, bc what's happened to me several times instead is a more obscure graphql exception like the one above
