### ISSUE TITLE
`.map` cannot be used with `sets` and does not warn when passed as a keyword argument

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [PrefectHQ/prefect#5148]
## Description
I don't know how it got missed, but when you try to pass a Set instead of a List in FunctionTask.map function. The flow run **straight up fails "silently" (This is insidious)**

## Example
```python
from prefect import Flow, task, unmapped
from prefect.executors import LocalDaskExecutor


@task(log_stdout=True)
def add(x, y):
    return x + y


with Flow("unmapped inputs") as flow:
    result = add.map(x=[1, 2, 3], y=unmapped(10))

state = flow.run(executor=LocalDaskExecutor())

print(state.result[result].result)
```

This works, but the following doesn't

```python
from prefect import Flow, task, unmapped
from prefect.executors import LocalDaskExecutor


@task(log_stdout=True)
def add(x, y):
    return x + y


with Flow("unmapped inputs") as flow:
    result = add.map(x={1, 2, 3}, y=unmapped(10))

state = flow.run(executor=LocalDaskExecutor())

print(state.result[result].result)
```

(Notice I just changed `add.map(x=[1, 2, 3], ...)` to `add.map(x={1, 2, 3}, ...)`

The fact that it fails silently without any warning or error message is excruciating, it took me hours just to figure this bug out.

**Comment by madkinsz** [comment]
I'm sorry to hear this took you a long time to figure out. When I run this locally I get a clear indication that the flow run has failed

```
[2021-11-16 10:03:04-0600] INFO - prefect.FlowRunner | Beginning Flow run for 'unmapped inputs'
[2021-11-16 10:03:04-0600] INFO - prefect.TaskRunner | Task 'add': Starting task run...
[2021-11-16 10:03:04-0600] INFO - prefect.TaskRunner | Task 'add': Finished task run for task with final state: 'Failed'
[2021-11-16 10:03:04-0600] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.
None
```

Inspecting the state, I can see the error message

```

In [3]: state.result
Out[3]: 
{<Task: add>: <Failed: "At least one upstream state has an unmappable result.">,
 <Task: Constant[set]>: <Success>}
```

Mapping requires objects that support `__getitem__` and are accessed by _index_. Sets are unordered and do not support this operator and therefore cannot be mapped over.

**Comment by Sinha-Ujjawal** [comment]
I can see in `map` function [here](https://github.com/PrefectHQ/prefect/blob/0464042e574c8187d0c344e52a4c39727f378867/src/prefect/core/task.py#L750) in the source code that it's been checked that the args have `__getitem__` function. But why is this error not shown in the logs?

**Comment by madkinsz** [comment]
This is because it only checks positional and not keyword arguments, which seems like an oversight.

Here's a fix: https://github.com/PrefectHQ/prefect/compare/fix-map-check

Feel free to add tests covering this case and open a pull request. Otherwise, we'll get to it when we have a chance.
