### ISSUE TITLE
Change the log level to Warning when raising signal from the Runner

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5149]
## Current behavior
```python
        # PrefectStateSignals are trapped and turned into States
        except signals.PrefectStateSignal as exc:
            self.logger.info(
                "{name} signal raised: {rep}".format(
                    name=type(exc).__name__, rep=repr(exc)
                )
            )
            if raise_on_exception:
                raise exc
            new_state = exc.state
```

## Proposed behavior
```python
        # PrefectStateSignals are trapped and turned into States
        except signals.PrefectStateSignal as exc:
            self.logger.warning(
                "{name} signal raised: {rep}".format(
                    name=type(exc).__name__, rep=repr(exc)
                )
            )
            if raise_on_exception:
                raise exc
            new_state = exc.state
```

The user explains it:
"I'm just thinking it might be useful to log it as a warning, for increased visibility in logs (especially when not running through a prefect server (locally or on CI).   (I can catch the exception during dev and the behavior is of the program is correct, this is only about making this more visible in log out)
Does that make sense?"

A full explanation is here https://prefect-community.slack.com/archives/CL09KU1K7/p1637062517192100

**Comment by madkinsz** [comment]
I'm not sure I buy that this should be a warning. Generally, we warn when something is not working as intended. The user raising a signal and it being caught and transformed into a state is expected behavior.

**Comment by anna-geller** [comment]
Got it, thx. That makes sense, I will communicate it back to the user 👍
