### ISSUE TITLE
Schedule details are not displayed for types other than `IntervalSchedule`

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#5196]
## Description

Deployments with other schedule types like `CronSchedule` will be created but not be displayed in the Deployments tab on the UI

## Reproduction / Example

```python
DeploymentSpec(
    flow_location="./orion-flow.py",
    name="my-first-deployment",
    parameters={},
    schedule=CronSchedule(cron="0 0 * * *"),
)
```

**Comment by madkinsz** [comment]
Tracking at https://github.com/PrefectHQ/orion/issues/658

**Comment by madkinsz** [comment]
The deployments will appear in the UI in the next alpha but the details of the schedule will not display nicely. Updating the issue to reflect adding a nice string description of the schedule.

**Comment by dylanbhughes** [comment]
@madkinsz I think this can be closed post-redesign. Do you agree?

**Comment by madkinsz** [comment]
I believe @znicholasbrown is working on this.

**Comment by discdiver** [comment]
This appears to be resolved.
