### ISSUE TITLE
Lack of a Descriptive Error When Logged In with Another API Key

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5204]
## Current behavior

If a user is current logged in with an API Key, and they try to do:

`prefect auth login --key <MY_KEY>`

They get an error

`Unauthorized. Invalid Prefect Cloud API key.`.

They need to do `prefect auth logout` before the new API key can be used.

## Proposed behavior

The error could suggest that maybe they need to use `prefect auth logout`.

**Comment by meehawk** [comment]
@kvnkho would love to take this up. Seems manageable (while I brainstorm over the #4386)

**Comment by kvnkho** [comment]
Actually sorry @meehawk, I tried to replicate this myself just now but could not. Let me know if you can.

You can try:
1. Creating an account with Prefect Cloud at cloud.prefect.io , we have a very generous free tier so you shouldn't have to put a credit card
2. Go to service accounts under Team in the navigation bar
3. Create a service account
4. Create an API Key
5. Login with `prefect auth login --key API_KEY`

After that, I tried the following to replicate but couldn't:
1. Logging in with a new key.
2. Logging in with a new key in a new service account while deleting the old one.

And these didn't seem to replicate it. I tried on 0.15.7 and 0.15.10 and saw nothing. Will ping the person to reported to chime in and add details.

**Comment by meehawk** [comment]
Ahh @kvnkho I'll try to follow the steps you've put 🤓

**Comment by kvnkho** [comment]
@meehawk ,

I talked to the person who reported it @TilakMaddy and I was able to replicate it. You need two different accounts.

1. Log-in with API key in account 1
2. Create API key with account 2
3. Try to log-in with account 2 API key

I don't know if you're familiar with `click` the Python library to create CLIs but the place to start would be [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/auth.py#L133-L154). You can see the error message.

I think you can check if the error caused has any difference. If it does, you can catch it and have a different error message. If it doesn't I get just add details to the current error that says "Consider trying prefect auth logout first" or something like that.

**Comment by madkinsz** [comment]
I think that it probably ought to just log them in with their new key. There shouldn't need to be a logout step here.

Is this reproducible on the `1.0.0-rc1` branch? It might have something to do with the token support.

**Comment by meehawk** [comment]
@kvnkho I was just going to ping you saying that I had difficulties replicating this. Totally missed your new comment on the issue

**Comment by TilakMaddy** [comment]
> @meehawk ,
> 
> I talked to the person who reported it @TilakMaddy and I was able to replicate it. You need two different accounts.
> 
> 1. Log-in with API key in account 1
> 2. Create API key with account 2
> 3. Try to log-in with account 2 API key
> 
> I don't know if you're familiar with `click` the Python library to create CLIs but the place to start would be [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/auth.py#L133-L154). You can see the error message.
> 
> I think you can check if the error caused has any difference. If it does, you can catch it and have a different error message. If it doesn't I get just add details to the current error that says "Consider trying prefect auth logout first" or something like that.

But sometimes you wanna be logged in, in 2 accounts. (1 Local agent servicing 2 different accounts in cases that involve shared execution environment)

**Comment by madkinsz** [comment]
We don't support being logged into two accounts at once. Agents are quite lightweight and running two local agents should not add significant overhead. You can use environment variables instead of the `login` command e.g. `PREFECT__CLOUD__API_KEY=foo prefect agent local start`

**Comment by dylanraithel** [comment]
I ran into this error (strangely) when passing the api key through as a bash variable. For whatever reason the key flag didn't like the standard POSIX env var replacement `${BRACKETED_THING}` but worked with `$UNBRACKETED_THING` Very strange, but the error didn't give me any info about why.

**Comment by Nitish36** [comment]
Just put prefect cloud logout 
To logout from the old API key


Then use prefect cloud login -k PREFECT_API_KEY
