### ISSUE TITLE
Mismatching imports in the docs

### ISSUE THREAD

**Issue by jeanluciano** [PrefectHQ/prefect#5207]
In the KV store and the artifacts section, the provided way of import is inaccurate.

For the KV_store it is missing the .kv_store in the import.

https://github.com/PrefectHQ/prefect/blob/master/docs/orchestration/concepts/kv_store.md?plain=1#L22

`from prefect.backend.kv_store import {funtion}`

For the artifacts the import comes from prefect.

https://github.com/PrefectHQ/prefect/blob/e9e3acdaf320a84c8005307a5af8b04f1d7c198c/docs/orchestration/concepts/artifacts.md?plain=1#L54

would be 
`from prefect.artifacts import {function}`

**Comment by tpdorsey** [comment]
@jeanluciano Can you confirm the artifacts import. As documented matches the current API docs and my code.

**Comment by madkinsz** [comment]
The kv store functions are indeed exposed at `prefect.backend`: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/backend/__init__.py

**Comment by tpdorsey** [comment]
PR to fix https://github.com/PrefectHQ/prefect/pull/5208

**Comment by tpdorsey** [comment]
On further research, while the imports in the docs are mismatched, the imports work as documented.

**Comment by tpdorsey** [comment]
Both long and short imports work, and imports work as documented. Tested against 0.15.10
