### ISSUE TITLE
Setting Flow storage will automatically update result storage, and turn on checkpointing

### ISSUE THREAD

**Issue by yin-aven** [PrefectHQ/prefect#5209]
## Description

`with Flow("test", storage=Local()) as flow:
      some_task_with_data_returned()
`

You will notice ~/.prefect/results/ have new files each time you run this test flow.

`with Flow("test", storage=S3("my-bucket")) as flow:
      some_task_with_data_returned()
`

you will notice s3://my-bucket/2021/<mo>/<day>/ with files uploaded each time you run the flow

You can't turn this checkpointing off with environment variable
`PREFECT__FLOWS__CHECKPOINTING=false`

or 

`with Flow(..., result=None) as flow:`

Only task-level checkpoint=false works.

## Expected Behavior

Ideally flow storage and result persistence should be independent settings, and there should be some way to turn checkpointing on and off globally.

**Comment by kvnkho** [comment]
Hey @yin-aven ,

You are exactly right on this one. Running with a backend such as Prefect Cloud or Prefect Server will override this environment variable and checkpoint, so this has to be set on every task. 

I will mention though that there is a nice solution here. Checkpoints are there to give you retries in the event of Flow failure. What I've seen some users do is specify the `location` of the checkpoint to the same file. This means you always have the checkpoints of the most recent run and the new runs will overwrite the old files. Doing this gives you retries from Failure while minimizing the data footprint.

**Comment by yin-aven** [comment]
Thanks for the tip @kvnkho .

I completely understand the benefits of checkpointing.  But automatically switching by flow storage can be very confusing.  I encountered two problems and it took me quite a while to figure out what's going on.

1. data processing tasks frequently return large data.  With home network it takes forever to upload the results to S3 but using local storage or running from office network is completely fine.   
2. the flow runs very well locally with either local or docker agents but start reporting S3 failure on ECS because execution role had only read permission.
