### ISSUE TITLE
API_ERROR when trying to delete an idle agent using UI and GraphQL API

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5216]
## Description
Reported via [this Community Slack thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1639051352191200)

The user gets the following API_ERROR:

![image](https://user-images.githubusercontent.com/86264395/145396504-8a0da622-f4b9-4fa8-9758-5a8ad6352c46.png)

![image](https://user-images.githubusercontent.com/86264395/145396469-f6fdb6aa-687c-45f1-ab95-85467431349b.png)

Used in the following environment:
```
{
  "config_overrides": {
    "context": {
      "secrets": false
    }
  },
  "env_vars": [
    "PREFECT__FLOWS__CHECKPOINTING"
  ],
  "system_information": {
    "platform": "macOS-10.16-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.10",
    "python_version": "3.8.12"
  }
}
```

**Comment by zangell44** [comment]
This should now be resolved, thanks all for the reports. If you're still seeing issues deleting agents, please feel free to reopen

**Comment by strojank** [comment]
This worked for me, thanks!

**Comment by thomasfrederikhoeck** [comment]
I'm still seeing this error when running it from the Interactive API in the UI:

```
{
  "errors": [
    {
      "path": [
        "delete_agent"
      ],
      "message": "Operation timed out",
      "extensions": {
        "code": "API_ERROR"
      }
    }
  ],
  "data": {
    "delete_agent": null
  }
}
```

**Comment by LoicEm** [comment]
Can confirm that the spamming method worked out for me, but it took 20+ tries  through the interactive API, so don't give up !

**Comment by hexinchi** [comment]
> I'm still seeing this error when running it from the Interactive API in the UI @zangell44 :
> 
> ```
> {
>   "errors": [
>     {
>       "path": [
>         "delete_agent"
>       ],
>       "message": "Operation timed out",
>       "extensions": {
>         "code": "API_ERROR"
>       }
>     }
>   ],
>   "data": {
>     "delete_agent": null
>   }
> }
> ```
> 
> ----- UPDATE ---- Running it a few times made it work. :-)

Second this, I had to run it several times, and it worked finally.

**Comment by ibabeo** [comment]
Please reopen the issue as the error keeps occuring. @anna-geller 

Not been able to succeed after 30+ tries.
Mostly the API_ERROR is returned and once in a while the following error appears as well.
```
{
  "errors": {
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch\n    at https://cloud.prefect.io/js/chunk-vendors~323f991a.dd7bce1a.js:37:764"
  }
}
```

**Comment by hexinchi** [comment]
> Please reopen the issue as the error keeps occuring. @anna-geller
> 
> Not been able to succeed after 30+ tries. Mostly the API_ERROR is returned and once in a while the following error appears as well.
> 
> ```
> {
>   "errors": {
>     "message": "Failed to fetch",
>     "stack": "TypeError: Failed to fetch\n    at https://cloud.prefect.io/js/chunk-vendors~323f991a.dd7bce1a.js:37:764"
>   }
> }
> ```

Can confirm this. It was working for the first time but later attempts never succeeded, we have to open a ticket with Prefect Cloud to have it manually removed.
