### ISSUE TITLE
Prefect merge checkpointing can't be turned off

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5217]
## Current behavior

If you use `merge` like this:

```python
@task(checkpoint=False)
def do_A():
    return something

@task(checkpoint=False)
def do_B():
    return something_else

with Flow("My flow") as flow:
    with case(cond1):
         result_A = do_A()
    with case(cond2):
         result_B = do_B()
    result=merge(result_A, result_B)
```

It will checkpoint result even if `result_A` and `result_B` have checkpointing turned off.

`merge` is actually not a Task. It calls the real `Merge` task [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/control_flow/conditional.py#L130-L169). This doesn't provide the user with a place to pass `kwargs` into the real `Merge` task to turn off checkpointing.

## Proposed behavior

`merge` can accept kwargs to be passed on to `Merge` like this:

```python
merged = merge(result_A, result_B, checkpoint=False)
```

**Comment by meehawk** [comment]
@kvnkho can I take this up?

**Comment by kvnkho** [comment]
You should be able to yep! Just pass through the kwargs and make a test that it was set. I can advice after a first attempt or if you have any questions.

**Comment by meehawk** [comment]
Looks like @cjmartian already fixed this. Can we close this issue @kvnkho ?

**Comment by kvnkho** [comment]
Thanks for flagging. Will close!
