### ISSUE TITLE
Docs Issue: misspelling in Server Overview

### ISSUE THREAD

**Issue by kgeis** [PrefectHQ/prefect#5222]
Hello!

I've found an issue here:`Ultimatey` should be `Ultimately`.

Page reference: https://docs.prefect.io/orchestration/server/overview.html

**Comment by meehawk** [comment]
Hi @tpdorsey can I take this up?

**Comment by tpdorsey** [comment]
@meehawk Yes, definitely! Thank you for your work on these doc issues. It's truly helpful.
