### ISSUE TITLE
AmazonECSTaskExecutionPolicy should be AmazonECSTaskExecutionRolePolicy in Docs

### ISSUE THREAD

**Issue by shearer12345** [PrefectHQ/prefect#5225]
Hello!

In the [ECS docs, on the Execution role arn](https://docs.prefect.io/orchestration/agents/ecs.html#execution-role-arn) `AmazonECSTaskExecutionPolicy` should be `AmazonECSTaskExecutionRolePolicy` - as given in [AWS ECS task execution docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html), and demonstrated in @anna-geller's [ECS gist](https://gist.github.com/anna-geller/45c99852c22cc44fa260156b47339c0f)

Thanks

**Comment by tpdorsey** [comment]
Resolved by https://github.com/PrefectHQ/prefect/pull/5243
