### ISSUE TITLE
Code blocks in the task library docs are not rendered correctly

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5239]
## Description
The code blocks from [this markdown file](https://github.com/PrefectHQ/prefect/blob/master/docs/core/task_library/overview.md) are not rendered correctly on [this documentation page](https://docs.prefect.io/core/task_library/overview.html#task-library-in-action).

![image](https://user-images.githubusercontent.com/86264395/146276115-4b83a262-310f-4b5a-b784-252f5f3c5445.png)

**Comment by zangell44** [comment]
This seems to only happen for me when navigating directly to https://docs.prefect.io/core/task_library/overview.html#task-library-in-action

If you navigate via Core Engine -> Task Library -> Overview, the code blocks will render correctly.

This exception in my Chrome console is likely related
```
80a7e0eb79499f829d532b4b5b725d3df2665ac6.js:3 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild
```

**Comment by anna-geller** [comment]
> This seems to only happen for me when navigating directly to https://docs.prefect.io/core/task_library/overview.html#task-library-in-action
> 
> If you navigate via Core Engine -> Task Library -> Overview, the code blocks will render correctly.
> 
> This exception in my Chrome console is likely related
> 
> ```
> 80a7e0eb79499f829d532b4b5b725d3df2665ac6.js:3 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
>     at Object.appendChild
> ```

Yup, I can confirm that.

**Comment by madkinsz** [comment]
cc @znicholasbrown if you have time

**Comment by znicholasbrown** [comment]
Hm, I can't reproduce this with a dev server so something seems to be happening during the build

**Comment by znicholasbrown** [comment]
I managed to reproduce this with the build as well as "fix" the issue. It seems these cells on the `task_library/overview` page are the problem but I can't figure out _why_:
```html
<td><img src="/logos/asana_logo.png" height="128" width="128" style="max-height: 128px; max-width: 128px;"> <a href="https://docs.prefect.io/api/latest/tasks/asana.html">Asana</a></td>
<td><img src="/logos/aws.png" height="128" width="128" style="max-height: 128px; max-width: 128px;"> <a href="https://docs.prefect.io/api/latest/tasks/aws.html">AWS</a></td>
<td><img src="/logos/azure.png" height="128" width="128" style="max-height: 128px; max-width: 128px;"> <a href="https://docs.prefect.io/api/latest/tasks/azure.html">Azure</a></td>
```
