### ISSUE TITLE
UI: PREFECT_SERVER__APOLLO_URL has no effect if a browser has saved a previous URL beforehand into localStorage

### ISSUE THREAD

**Issue by chris-aeviator** [PrefectHQ/prefect#5251]
## Description
When using docker-compose and setting `PREFECT_SERVER__APOLLO_URL`, the UI still tries to look for graphql on `localhost`

![image](https://user-images.githubusercontent.com/11522213/146742413-055f905c-8604-4002-9905-b3a2990b94d8.png)

## Expected Behavior

When setting `PREFECT_SERVER__APOLLO_URL=http://my-local-graphql.loc:4200/graphql` I expect the UI to take this address to look for graphql.

## Reproduction

![image](https://user-images.githubusercontent.com/11522213/146742119-fac3735e-c9a6-40f8-8eda-a59ea072e5e2.png)

## Environment
```

❯ prefect diagnostics                                                                                                                                         │
{                                                                                                                                                             │
  "config_overrides": {},                                                                                                                                     │
  "env_vars": [],                                                                                                                                             │
  "system_information": {                                                                                                                                     │
    "platform": "Linux-5.14.3-arch1-1-x86_64-with-glibc2.10",                                                                                                 │
    "prefect_backend": "server",                                                                                                                              │
    "prefect_version": "0.15.5",                                                                                                                              │
    "python_version": "3.8.10"                                                                                                                                │
  }                                                                                                                                                           │
}   
```

### EDIT

also the docs seem to be outdated. I cannot see any of the mentioned items like "Home" or "Connecting your infrastructure" in the UI

#### Docs
> You can set this directly from the browser. First click Menu > Home. In the Connecting your Infrastructure block, select the Prefect Server tab. Then you'll see this configuration option under Connect the UI:

#### Prefect UI
![image](https://user-images.githubusercontent.com/11522213/146743324-efec660a-0f3f-4150-ae35-9b4e1103fcbd.png)

## UPDATE 2

it seems to be prefect picks up the server URL correctly, but the UI persists the server URL in the browsers local storage. This prevents my browser to take the updated URL. As you see the entry is already 3 months old.

![image](https://user-images.githubusercontent.com/11522213/146743790-b5057822-1e4c-4bff-aab3-2e5a8e775e18.png)

After deleting the entry from my browser I can successfully connect. This is still a bug in my view since changing the server's config should result in the browser reliably connecting. The JS client could check for the apollo server variable set on the server be still the same and otherwise delete the localstorage entry.

**Comment by zhen0** [comment]
Thanks for the feedback @chris-aeviator.  The question of whether local storage or the  REFECT_SERVER__APOLLO_URL variable should take precedence seems like a subjective one to me and I can see cases where users who have updated via the UI would expect local storage to take precedence. 

That said - I can see this would be more confusing if you can not find where to update local storage in the UI and you are right that the location of that page has changed so the docs are outdated.  I've added a PR to update the docs to help any other users who come across this issue,
