### ISSUE TITLE
Typo in the online docs

### ISSUE THREAD

**Issue by jrich8573** [PrefectHQ/prefect#5283]
## Description
There is a typo in the online docs https://docs.prefect.io/orchestration/getting-started/set-up.html#prefect-cloud-and-serve

## Expected Behavior
It is my belief that this doc should read like this: 
*Prefect Cloud and the Prefect Server provide ready-to-use backend for maintaining task and flow state and inspecting their progress regardless of where your task and flow code runs.*

## Reproduction

<img width="931" alt="image" src="https://user-images.githubusercontent.com/8703618/147694716-2310c1ad-59fc-4187-92bc-73d9cc7f3c90.png">

## Environment
The docs are located on the __*Orchestration Layer*__ header within the online docs.

**Comment by me-so-weird** [comment]
Hey! Can I work on this?

**Comment by madkinsz** [comment]
Yep go for it!
