### ISSUE TITLE
Orion: REST API reference missing

### ISSUE THREAD

**Issue by cdeil** [PrefectHQ/prefect#5289]
At https://orion-docs.prefect.io/api-ref/rest-api/#orion-rest-api-reference I currently see
"No operations defined in spec!"

Is there a problem with the docs build? Should there be API docs in that section?

<img width="940" alt="Screenshot 2021-12-29 at 23 54 06" src="https://user-images.githubusercontent.com/852409/147709123-b7b1de13-cb49-417f-b5cb-7a29ceb9b817.png">

**Comment by madkinsz** [comment]
@cdeil thanks for the report! We broke the build process by accident. I believe this is already fixed in the next release but I'll leave this open until then.

**Comment by cicdw** [comment]
@cdeil apologies for that, @madkinsz raised this and we have now published a fix!
