### ISSUE TITLE
IntervalSchedule start_date now timezone flow start issue

### ISSUE THREAD

**Issue by cdeil** [PrefectHQ/prefect#5301]
## Description

I was scheduling a flow using [IntervalSchedule](https://github.com/PrefectHQ/prefect/blob/d527ab2af11956d0564efbd8543989eab5a981ee/src/prefect/schedules/schedules.py#L197) with a `start_date=now` and it didn't start.

## Expected Behavior

I expected the flow to start now.

## Reproduction

This should start the flow now, right?

```python
from prefect import task, Flow
import datetime
from prefect.schedules import IntervalSchedule

@task
def say_hello():
    print("Hello, world!")

now = datetime.datetime.now()
schedule = IntervalSchedule(
    start_date=now,
    interval=datetime.timedelta(seconds=10),
)

with Flow("Hello", schedule) as flow:
    say_hello()

flow.run()
```

## Explanation

What is happening is that `datatime.datetime.now()` creates a [naive datetime](https://docs.python.org/3/library/datetime.html) in my local time zone (which is "Europe/Berlin" with a UTC offset of `+01:00`), but then `IntervalSchedule` assumes that it's UTC and silently adds a `UTC` timezone.

```
>>> print(now)
2022-01-05 16:41:09.387806
>>> print(schedule.start_date)
2022-01-05T16:41:09.387806+00:00
```

Do you consider this a bug or a usage error?

I'm surprised I run into this "gotcha" now after many years of Prefect being used by many people.
Maybe that's because setting `start_date` is rare in the first place, or because only sometimes one notices, e.g. if you're in the US where you have a negative `tz_offset` maybe you won't for schedules that start immediately anyways?

This is one way to see what's going on with reproducible output:

```python
from prefect.schedules import IntervalSchedule
import datetime
import freezegun


with freezegun.freeze_time("2012-01-01 10:00", tz_offset=4):
    print(f"{datetime.datetime.now()=}")
    print(f"{datetime.datetime.utcnow()=}")

    start_date = datetime.datetime.now()
    print(f"{start_date=}")

    schedule = IntervalSchedule(
        start_date=start_date,
        interval=datetime.timedelta(seconds=10),
    )

    print(f"{schedule.start_date=}")
```

If still possible I would recommend some change - I guess the only one possible would be to raise an error or emit a warning when naive datetimes are passed?

Or if that isn't possible, maybe the [docstring](https://orion-docs.prefect.io/api-ref/orion/schemas/schedules/#prefect.orion.schemas.schedules.IntervalSchedule) could mention what happens when naive datetimes are passed?

I guess there's many other classes and functions in the code that have the same behaviour, so it would have to be applied in a consistent way?

**Comment by anna-geller** [comment]
@cdeil To solve it, you should use the pendulum package and pass the timezone to your start_date. Additionally, another gotcha is that Prefect cannot schedule flows every X seconds - minutely interval is the lowest we can go. 

```python
from datetime import timedelta
import pendulum
from prefect import task, Flow
from prefect.schedules import IntervalSchedule


@task
def say_hello():
    print("Hello, world!")


schedule = IntervalSchedule(
    start_date=pendulum.now(tz="Europe/Berlin"), interval=timedelta(minutes=1),
)

with Flow("Hello", schedule) as flow:
    say_hello()

```

LMK if this works for you. Otherwise, feel free to close the issue if this solves it for you.

**Comment by cdeil** [comment]
In our production code we're using [pd.Timestamp.now(tz="utc")](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.now.html) and [pandas.Timedelta](https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html) for the interval and that works fine. So yes, clearly using tz-aware datetime / pendulum / pandas timestamps is a good solution.

My question here was whether it would be better if Prefect gave an error or warning when a user passes a naive timestamp since implicitly assuming it represents UTC means some fraction of users will shoot themselves in the foot. Or alternatively if the docs should be improved.

If the answer is "we think it's fine as-is" OK, let's close.

> Prefect cannot schedule flows every X seconds - minutely interval is the lowest we can go

That doesn't seem to be the case. The example above with 10 second interval works just fine for me.

Where does this limitation 1 minute come from? Is there a real limit somewhere in the Prefect code?

Or is it just that if it's too short (e.g. every second) some triggers will be skipped if the computer isn't fast enough since as explained in the docs the scheduler never schedules runs from the past?

**Comment by kvnkho** [comment]
We haven't really seen people run into issues on the timestamp on Github and Slack, but I don't think we'd mind adding a small blurb about how timestamps are handled. Where do you think is a good place? The [Schedules]https://docs.prefect.io/core/concepts/schedules.html#schedules) page?

Yes there is a 1 minute limitation in the Prefect code. You will run into it when you register your Flow with `flow.register()`, not when using `flow.run()`. 

You will get an error: `ValueError: Interval can not be less than one minute when deploying to Prefect Cloud.`

**Comment by anna-geller** [comment]
it's documented [here](https://docs.prefect.io/core/concepts/schedules.html#clocks) 
![image](https://user-images.githubusercontent.com/86264395/148277102-1027b126-9444-4c9a-bf0d-a661de459605.png)

**Comment by madkinsz** [comment]
We can detect the combination of a naive datetime with non-utc timezone and throw a warning.
