### ISSUE TITLE
Docs: unresponsive navigation in API docs

### ISSUE THREAD

**Issue by tpdorsey** [PrefectHQ/prefect#5302]
## Description
Seeing an issue with the current docs where if you go directly to the API docs (https://docs.prefect.io/api/latest/) the navigation is unresponsive. If you click on another doc area (such as Core), it’s still not responsive, but if you then refresh, the navigation becomes responsive to clicks again.

## Expected Behavior
Page should change when clicking on any top or side navigation links.

## Reproduction
1. Go directly to this link in a new tab https://docs.prefect.io/api/latest/
2. Click any link in the left or top navigation. The page will not change.
3. Click "Core", then refresh the page. Core page should appear now and be responsive to clicks.
4. Navigate back to latest API docs in the same tab by clicking API > Latest in the top navigation. Page should be responsive.
5. If you put https://docs.prefect.io/api/latest/ in the address bar and navigate that way, even in the same tab, it will not be responsive.

## Environment
Chrome 96.0.4664.110 (Official Build) (x86_64) 
Safari Version 15.2 (16612.3.6.1.8, 16612)

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by pleek91** [comment]
There's a js error when loading that page. No idea what's causing it. Not familiar with how the docs are generated. 

![image](https://user-images.githubusercontent.com/6200442/148416585-248f0dd1-b12b-4cf6-a5cd-f3fe2e82ae13.png)

**Comment by discdiver** [comment]
This is fixed for me on Chrome Version 113.0.5672.92 (Official Build) (arm64)
