### ISSUE TITLE
Using Artifact with .map raises ClientError

### ISSUE THREAD

**Issue by nneuh07** [PrefectHQ/prefect#5309]
## Description
Hey everyone,
currently I am trying out the new artifact api. But when I am using the api in mapped tasks the following error is being thrown:

File "/../create-city-flow.py", line 44, in get_wikipedia_summary
    create_markdown_artifact(artifact_document)
File "/../python3.8/site-packages/prefect/backend/artifacts.py", line 85, in create_markdown_artifact
    return _create_task_run_artifact("markdown", {"markdown": markdown})
File "/../python3.8/site-packages/prefect/backend/artifacts.py", line 28, in _create_task_run_artifact
    return client.create_task_run_artifact(
File "/../python3.8/site-packages/prefect/client/client.py", line 2160, in create_task_run_artifact
    result = self.graphql(
File "/../python3.8/site-packages/prefect/client/client.py", line 570, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'message': '[{\'extensions\': {\'path\': \'$.selectionSet.insert_task_run_artifact.args.objects\', \'code\': \'constraint-violation\'}, \'message\': \'Not-NULL violation. null value in column "tenant_id" violates not-null constraint\'}]', 'locations': [{'line': 2, 'column': 5}], 'path': ['create_task_run_artifact'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': '[{\'extensions\': {\'path\': \'$.selectionSet.insert_task_run_artifact.args.objects\', \'code\': \'constraint-violation\'}, \'message\': \'Not-NULL violation. null value in column "tenant_id" violates not-null constraint\'}]'}}}]

## Expected Behavior

No error is being raised and artifacts for mapped tasks work like for unmapped tasks.

## Reproduction

```python
from prefect import Flow, task
from prefect.backend import create_markdown_artifact

@task
def add_ten(x):
    create_markdown_artifact(x)
    return x + 10

with Flow('simple map') as flow:
    mapped_result = add_ten.map([1, 2, 3])
```

## Environment

```json
{
  "config_overrides": {
    "backend": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-12.0.1-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.15.11",
    "python_version": "3.8.12"
  }
}

```

**Comment by madkinsz** [comment]
Is this specific to mapped tasks?

**Comment by nneuh07** [comment]
I guess so. I changed the task to a non mapped task and it just works as expected.

**Comment by madkinsz** [comment]
Thanks! We'll investigate and report back here.

**Comment by anna-geller** [comment]
The issue is that create_markdown_artifact expects a string and you pass a number. Casting it to a string should work:

```python
from prefect import Flow, task
from prefect.backend import create_markdown_artifact


@task
def add_ten(x):
    create_markdown_artifact(f"{x}")
    return x + 10


with Flow("artifacts") as flow:
    mapped_result = add_ten.map([1, 2, 3])
```

![image](https://user-images.githubusercontent.com/86264395/148857856-0ca4924e-2806-482a-8f4d-2e3d501fd38c.png)
![image](https://user-images.githubusercontent.com/86264395/148857879-3fc2f4c1-51b6-4dca-82f0-9226b2a588c9.png)

**Comment by nneuh07** [comment]
@anna-geller No, look at the error being raised. It has something to do with the tenantid not being found.

Also here is a reproducible example where the the error happens with a string:
```python

from prefect import Flow, task
from prefect.backend import create_markdown_artifact


@task
def add_ten(x: str):
    create_markdown_artifact(x)
    return x


with Flow('simple map') as flow:
    mapped_result = add_ten.map(["1", "2", "3"])
```

**Comment by anna-geller** [comment]
@nneuh07 perhaps you need to create a tenant first? Here is how you can do it: 

`prefect server create-tenant --name default --slug default`

I did the same on Server and the result is the same:

![image](https://user-images.githubusercontent.com/86264395/148932215-9a139e68-b318-4742-8c0b-703efe91957a.png)

![image](https://user-images.githubusercontent.com/86264395/148932277-fc6f40c4-bdc7-4f09-8539-f3b6b3d0e993.png)

**Comment by nneuh07** [comment]
I just tried adding a new tenant `prefect server create-tenant --name default --slug default` with the following message: 
prefect.exceptions.ClientError: [{'message': 'Uniqueness violation.', 'locations': [{'line': 2, 'column': 5}], 'path': ['create_tenant'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'Uniqueness violation.'}}}]

I believe this indicates that a tenant is already there, right? 
I think the prefect server start command is creating one at the start.

It is indeed interesting it works for you. I also tried starting it from the CLI with the same result: 
```
prefect.exceptions.ClientError: [{'message': '[{\'extensions\': {\'path\': \'$.selectionSet.insert_task_run_artifact.args.objects\', \'code\': \'constraint-violation\'}, \'message\': \'Not-NULL violation. null value in column "tenant_id" violates not-null constraint\'}]', 'locations': [{'line': 2, 'column': 5}], 'path': ['create_task_run_artifact'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': '[{\'extensions\': {\'path\': \'$.selectionSet.insert_task_run_artifact.args.objects\', \'code\': \'constraint-violation\'}, \'message\': \'Not-NULL violation. null value in column "tenant_id" violates not-null constraint\'}]'}}}]

```

**Comment by anna-geller** [comment]
You're 100% correct, the default tenant gets created on server start. Is it something running in production? Can you try the same flow in a brand new Server installation? 

It looks like your Server installation is somehow broken, can you register and run other flows? Have you migrated/upgraded your Server version recently? 

Fwiw, we could change the title of the issue because it doesn't seem related to artifacts and it's rather a tenant/Server issue.

**Comment by nneuh07** [comment]
Actually I installed it just yesterday and wanted to try out Prefect, if it does fit my use-case.
 
It is so strange, because if I am not using mappings I have no issues at all. One thing I noticed was that 0.15.11 and you 0.15.10. If it is not a big hassle for you, could you try updating and if it does change anything for you? 

I am also using pyenv, maybe it is somehow related to that. But I will also try out a few things with the installation and will report back, if I had any success.

**Comment by anna-geller** [comment]
Sure, no problem. The output is the same:
![image](https://user-images.githubusercontent.com/86264395/148943654-cbba42e3-9d6e-4f6d-b6f7-af5fa491f2e6.png)

![image](https://user-images.githubusercontent.com/86264395/148943682-f87f5518-ab5e-4d91-b5d2-ef6b37719537.png)
How did you start your Server?

**Comment by nneuh07** [comment]
[https://github.com/PrefectHQ/server/issues/308](url)

I just found an existing issue on the server repo. Should I close it then here?

**Comment by nneuh07** [comment]
But I am still curious, why it does work for you. I started the server by `prefect server start`. How do you start the server?

**Comment by anna-geller** [comment]
I started the server using the same command locally. Yes, I think we can close this issue then.

**Comment by madkinsz** [comment]
I do not mind leaving this issue open so we can track this in our primary repository.

**Comment by nneuh07** [comment]
So I reproduced all your steps @anna-geller and does indeed work.

What has changed is that I registered the component with the CLI. From my understanding this seems like there is a bug in the `flow.register()` function. Could this be the problem?

@anna-geller would you be so kind and try to delete it and register the flow with python like this:

```python
from prefect import Flow, task
from prefect.backend import create_markdown_artifact


@task
def add_ten(x: str):
    create_markdown_artifact(x)
    return x


with Flow('simple map') as flow:
    mapped_result = add_ten.map(["1", "2", "3"])

flow.register(project_name="abc")

```

**Comment by anna-geller** [comment]
Nice work! I can confirm that registering this way indeed causes that issue. 
![image](https://user-images.githubusercontent.com/86264395/149013020-90cacc12-d163-4458-b5f6-d8da5eaa260f.png)

This could indicate a storage issue because the CLI registers the flow with script storage while flow.register() pickles the flow. See [this page for more details on that](https://docs.prefect.io/orchestration/flow_config/storage.html#pickle-vs-script-based-storage). In any case, this looks like a bug.
