### ISSUE TITLE
DockerEnvironment prefect version

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#533]
Currently, `DockerEnvironment`s pull the bleeding edge version of Prefect from git, which might not agree with a user's local version, or might not be stable.  I think we should have a "prefect_version" init kwarg that (optionally) specifies a specific Prefect version to pull (defaults to pulling bleeding edge).

**Comment by joshmeek** [comment]
We currently can provide this https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/docker.py#L54 however just not for using user's local version

**Comment by cicdw** [comment]
@joshmeek only question I have is: what is the "right" thing to do if someone's version is `'0.5.3+114.g35bc7ba4.dirty'` (for example).  Should I:
- default to `0.5.3`
- assume that because they are ahead of `0.5.3`, default to `master`
- some third option I'm not seeing?

**Comment by joshmeek** [comment]
Really good question. My first thought is to use the truncated version of `0.5.3`. I'm not sure of an argument in either direction but truncating feels _safer_ to me

**Comment by cicdw** [comment]
Yea that makes sense; however, counterpoint: if someone has a `+` version, it means they necessarily installed directly from GitHub.  Which makes me think they could be utilizing some new tasks or something.  I think now that I've said that out loud I vote that particular situation defaults to `master` - what do you think?
