### ISSUE TITLE
Tutorial docs not working

### ISSUE THREAD

**Issue by palewire** [PrefectHQ/prefect#5364]
## Description
The installation section suggests this for pipenv install.

![Screenshot from 2022-01-24 16-29-48](https://user-images.githubusercontent.com/9993/150888002-9808979a-4460-4b6f-9e82-67a2adfd8aa3.png)

I ran that install, with `--pre`.

I then ran ...

```bash
pipenv run python
```

... to get to the Python shell.

The next step of the tutorial suggests the following:
![Screenshot from 2022-01-24 16-31-52](https://user-images.githubusercontent.com/9993/150888161-5a662a05-2970-4eed-b1cb-ce34bf5a6c0b.png)

But when I ran that I get an error, with the `Flow` import failing.

```python
>>> import prefect
>>> from prefect import task, Flow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Flow' from 'prefect' (/home/palewire/.local/share/virtualenvs/prefect-tutorial-budqYhom/lib/python3.9/site-packages/prefect/__init__.py)
>>> dir(prefect)
['State', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__module_path__', '__name__', '__package__', '__path__', '__root_path__', '__spec__', '__ui_static_path__', '__version__', '_os', 'client', 'context', 'exceptions', 'flow', 'flows', 'futures', 'get_run_logger', 'logging', 'orion', 'prefect', 'serializers', 'settings', 'setup_logging', 'tags', 'task', 'task_runners', 'tasks', 'utilities']
>>> prefect.__version__
'2.0a9'
```

**Comment by mrajancsr** [comment]
thats because you are using the latest version and not the 1.0 version.  uninstall ur version of prefect and do a pip install prefect

**Comment by prankymat** [comment]
can confirm removing the --pre flag works. I personally think that the pipenv instruction is still relevant?

**Comment by davidgacc** [comment]
you should install the version the version 1.2.1. Versions grater than 2.0 is not recommended for production 
https://orion-docs.prefect.io/
