### ISSUE TITLE
Error Running Shell Script on Prefect Task

### ISSUE THREAD

**Issue by eugenmihali** [PrefectHQ/prefect#5378]
Prefect task cannot run shell script 

Running a shell script with multiple parameters fails when done inside a prefect task. 

Python code used: 

`import subprocess`

`command = 'foo.sh param1 param2' `

`subprocess.run(command, shell=True)`

More specifically it fails when the following bit is ran (getting the path to a file. The following line is in the shell script):

![image](https://user-images.githubusercontent.com/48630548/151246875-a94649c0-499c-42fd-957e-6e93548da657.png)

**Error:** /foo.txt  No such file or directory

To me it looks like the prefect task cannot tell its running a shell script. The same code works perfectly fine and brings the expected results in: 

1- Python REPL
2- Terminal. Running the command on the terminal (same host + environment)

All environment variables required have been checked and they are correct.

What have I tried:
	- All sorts of combinations of subprocess commands
	- os.system instead of subprocess
	- Different hosts
        - Prefect Shell Task

**Comment by madkinsz** [comment]
Hi! `subprocess.run` expects a list not a string e.g.

```python

In [1]: import subprocess

In [2]: subprocess.run("echo foo")
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-25f5b8e9cd2c> in <module>
----> 1 subprocess.run("echo foo")

/opt/homebrew/Caskroom/miniconda/base/envs/prefect-dev-38/lib/python3.8/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    491         kwargs['stderr'] = PIPE
    492 
--> 493     with Popen(*popenargs, **kwargs) as process:
    494         try:
    495             stdout, stderr = process.communicate(input, timeout=timeout)

/opt/homebrew/Caskroom/miniconda/base/envs/prefect-dev-38/lib/python3.8/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    856                             encoding=encoding, errors=errors)
    857 
--> 858             self._execute_child(args, executable, preexec_fn, close_fds,
    859                                 pass_fds, cwd, env,
    860                                 startupinfo, creationflags, shell,

/opt/homebrew/Caskroom/miniconda/base/envs/prefect-dev-38/lib/python3.8/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1702                     if errno_num != 0:
   1703                         err_msg = os.strerror(errno_num)
-> 1704                     raise child_exception_type(errno_num, err_msg, err_filename)
   1705                 raise child_exception_type(err_msg)
   1706 

FileNotFoundError: [Errno 2] No such file or directory: 'echo foo'

In [3]: subprocess.run(["echo", "foo"])
foo
Out[3]: CompletedProcess(args=['echo', 'foo'], returncode=0)

In [4]:

**Comment by eugenmihali** [comment]
I have tried all sorts of combinations related to subprocess. I dont think the way I am passing the command is the issue. I have tried the list as well. Having:
`shell=True`
will accept a string as well I believe.

**Comment by madkinsz** [comment]
Ah yes I missed that, `shell=True` can allow a string to be passed.

Anyway, here's an example of it working in a task and flow. Do you have a reproducible example of the failure you're encountering?
```python

In [2]: subprocess.run("echo foo", shell=True)
foo
Out[2]: CompletedProcess(args='echo foo', returncode=0)

In [3]: from prefect import task

In [4]: @task
   ...: def sp(cmd):
   ...:     return subprocess.run(cmd)
   ...: 

In [5]: sp.run(["echo", "foo"])
foo
Out[5]: CompletedProcess(args=['echo', 'foo'], returncode=0)

In [6]: from prefect import Flow

In [7]: with Flow("test") as flow:
   ...:     sp(["echo", "foo"])
   ...: 

In [8]: flow.run()
[2022-01-26 15:25:21-0600] INFO - prefect.FlowRunner | Beginning Flow run for 'test'
[2022-01-26 15:25:21-0600] INFO - prefect.TaskRunner | Task 'sp': Starting task run...
foo
[2022-01-26 15:25:21-0600] INFO - prefect.TaskRunner | Task 'sp': Finished task run for task with final state: 'Success'
[2022-01-26 15:25:21-0600] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
Out[8]: <Success: "All reference tasks succeeded.">

In [9]:

**Comment by eugenmihali** [comment]
Hello, 

Thanks for your replies and trying to solve this. A simpler command such as 'echo foo' works for me as well. The problem comes when I try to run my shell script (a client script) and more specifically when the following line is executed (see the image). I doubt the backtick is causing some issue or the executer cannot tell its running a shell script. 

![image](https://user-images.githubusercontent.com/48630548/151250849-b59120c2-cd4a-4b86-ba85-0a4274a208c0.png)

**Comment by eugenmihali** [comment]
Hello madkinsz, 

Just wanted to bring this back to attention. I was hoping you had some suggestions I can try. The script I mention above works in every setup except the prefect setup. Any suggestions is valuable. 

Kind regards, 
Eugen

**Comment by anna-geller** [comment]
@eugenmihali Can you try a simple example from the docs such as this one? The ShellTask is the right way of doing this. 

```python
from prefect import task, Flow
from prefect.tasks.shell import ShellTask

# Will only return the listed files
ls_task = ShellTask(command="ls", return_all=True)

@task
def show_output(std_out):
    print(std_out)

with Flow("count_files") as flow:
    ls = ls_task()
    show_output(ls)

    # Override command to count listed files
    ls_count = ls_task(command="ls | wc -l")
    show_output(ls_count)
```

It may also be useful for you to investigate the output.

You can use a ShellTask's keyword argument `stream_output=True`. This will pass any logs from the ShellTask to the prefect logger at the INFO level.

Additionally, you can instead set stream_output to any string or integer value interpretable by logging as a valid log level (e.g. 50 → CRITICAL, 40 → ERROR, etc).

If you need to do something else with the stdout then you can get all of that as a List[str] return from the ShellTask by setting `return_all = True`.

**Comment by eugenmihali** [comment]
Hello, 
Thank you for your suggestions. I tried it and it failed with the following error: 

FileNotFoundError: [Errno 2] No such file or directory: 'bash'

**Comment by anna-geller** [comment]
Are you running this on Windows? If so, you can run PowerShell commands instead and add shell="powershell"

**Comment by madkinsz** [comment]
Note we do not support powershell, see https://github.com/PrefectHQ/prefect/issues/3375

**Comment by anna-geller** [comment]
> Note we do not support powershell, see #3375

sorry for confusing everyone, I saw it in an earlier Slack discussion. Good to know and thanks for clarifying

**Comment by eugenmihali** [comment]
Hello @anna-geller, 

I am running on a linux host. Strange enough the same code works perfectly fine when run with prefect LocalExecutor. Still it doesnt work for the above mentioned reasons when run in a DaskExecutor on Prefect Server. 

Hope this gives you a bit more insight. 

Eugen

**Comment by anna-geller** [comment]
Can you give a flow example to show what you try to accomplish? Do you persist some data to disk on your Dask's worker node and you try to modify this file with a subprocess/shell command? If you could provide more information about the problem you try to solve, we could figure out what's the best way to approach it and whether you need to use ShellTask at all.

**Comment by madkinsz** [comment]
When using a `DaskExector` your code isn't going to be executing from the same working directory as the `LocalExecutor`

**Comment by eugenmihali** [comment]
Hello @anna-geller , @madkinsz , 

What I am trying to do is:

Use a client script (the shell script failing) of another app from inside a prefect task. So I need to run the command inside a prefect task to communicate with the other app. The client will then download a file on the destination path I provide on the command. But the script doesnt make it to the point of downloading the file. It fails very early. 

So what I need to do:

1- Use a client shell script. Pass some arguments when running the script.
2- It must be Prefect Server using DaskExecutor. 
3- The client then will download a file. 

Eugen

**Comment by anna-geller** [comment]
Perhaps you can explore a flow of flows pattern? This way, you can run this shell script in a flow that executes in the right (non-Dask) environment, and the tasks that need to run in parallel can run on Dask. 

Here are more resources about the flow-of-flows orchestration pattern: https://discourse.prefect.io/tag/flow-of-flows
