### ISSUE TITLE
Adding stuff to context

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5380]
## Proposed behavior

This is to track requests of things to add to context. There is a user request to add two things:

1.flow_group_id
2.tenant_id

## Example

This would let you do:
`prefect.context.flow_group_id` 
and
`prefect.context.tenant_id`

**Comment by heyitskevin** [comment]
Made a PR for this issue here. I hope I followed all the contribution guidelines. Please correct me if I didn't.
https://github.com/PrefectHQ/prefect/pull/5604

**Comment by kvnkho** [comment]
Thanks for the PR! The core team will review it.

**Comment by cicdw** [comment]
Closing as stale, and in v2 we can add lazy-loading attributes like this via `prefect.runtime`
