### ISSUE TITLE
Prefect build should remove intermediate docker containers

### ISSUE THREAD

**Issue by th0ger** [PrefectHQ/prefect#5384]
## Description

When building Prefect flows for [Docker storage](https://docs.prefect.io/api/latest/storage.html#docker), all intermediate docker container/image layers are left dangling. This has resulted in our build server(s) running out of disk multiple times.

Normally, docker removes intermediate containers by default:

```console
$ docker build --help
	--rm   Remove intermediate containers after a successful build (default true)
```

But since Prefect utilizes [docker-py](https://docker-py.readthedocs.io), the default is to [NOT remove intermediates](https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.build):

> **rm** (*bool*) – Remove intermediate containers. The `docker` build command now defaults to `--rm=true`, but we have kept the old default of *False* to preserve backward compatibility.

This results in a lot of unnamed `<none>` images and a huge overlay folder `/var/lib/docker/overlay2`. If the server is running multiple docker services, it is not trivial to conclude that these anonymous `<none>` images comes from Prefect.

## Expected Behavior

The proposed fix is to let Prefect remove intermediates by default. Either by setting the default `build_kwargs={"rm": "True"}` in `prefect.storage.docker.Docker()` (I have tested that this works). Or by setting `rm=True` when calling `docker-py` `build()`, unless supplied by the user.

I think most users are expecing Prefect builds to work as `docker build`, not as the peculiar `docker-py` implementation.

There is typically no benefit of persisting all these intermediates. The build process is usually triggered by changed code or run on another build node, so the reuse of image layers seems minimal.

## Reproduction

Create a flow with storage like:

```python
flow.storage = Docker(
        dockerfile="Dockerfile",
        registry_url=DOCKER_REGISTRY,
        image_name=IMAGE_NAME,
        image_tag=VERSION,
        # build_kwargs={"rm": "True"}  # Fix
        )
```

```console
$ prefect build --path myflow.py
# Take note of the image ans container IDs in the build output.
```

```console
$ docker image ls -a
REPOSITORY                           TAG                 IMAGE ID       CREATED         SIZE
<none>                               <none>              51bb2a5722dd   5 minutes ago   1GB
<none>                               <none>              5cb129803c80   5 minutes ago   1GB
<none>                               <none>              e5ed9eed2b3d   5 minutes ago   1GB
<none>                               <none>              250419814322   5 minutes ago   1GB
<none>                               <none>              5630bb427883   5 minutes ago   1GB
<none>                               <none>              ffd49f061e13   5 minutes ago   1GB
<none>                               <none>              11aff0949948   5 minutes ago   993MB
<none>                               <none>              ae1092b23809   5 minutes ago   993MB
<none>                               <none>              f2b3be4848bf   5 minutes ago   655MB
<none>                               <none>              f365e6ac6feb   5 minutes ago   655MB
<none>                               <none>              6b8e01e5a5d3   5 minutes ago   655MB
<none>                               <none>              4506fd319523   5 minutes ago   655MB
<none>                               <none>              e41877b140e1   5 minutes ago   655MB
<none>                               <none>              0ff3e3359766   5 minutes ago   655MB
<none>                               <none>              91e6a03598e1   9 days ago      2.19GB
<none>                               <none>              1b632006ea37   9 days ago      958MB
<none>                               <none>              62e659b57581   9 days ago      958MB
<none>                               <none>              d19bc15e2db8   12 days ago     1.54GB
<none>                               <none>              104f684be30d   12 days ago     430MB
<none>                               <none>              7bd4a7da45d0   12 days ago     430MB
<none>                               <none>              1792a22ea46e   12 days ago     2.07GB
<none>                               <none>              ee2c907002b8   12 days ago     1.81GB
<none>                               <none>              c5eb1bc8d5a6   12 days ago     1.81GB
...

$ docker container ls -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                     PORTS     NAMES
dedc0868e3a6   51bb2a5722dd                               "/bin/sh -c 'python …"   5 minutes ago   Exited (0) 5 minutes ago             hardcore_johnson
b9d5243ecdea   250419814322                               "/bin/sh -c 'mkdir -…"   5 minutes ago   Exited (0) 5 minutes ago             fervent_thompson
2f8088c11fcf   5630bb427883                               "/bin/sh -c 'pip ins…"   5 minutes ago   Exited (0) 5 minutes ago             competent_murdock
05467920a3ba   ffd49f061e13                               "/bin/sh -c 'pip sho…"   5 minutes ago   Exited (0) 5 minutes ago             quizzical_lichterman
52ab2547fe92   11aff0949948                               "/bin/sh -c 'pip ins…"   5 minutes ago   Exited (0) 5 minutes ago             frosty_lumiere
26673b381118   ae1092b23809                               "tini -g -- entrypoi…"   5 minutes ago   Created                              inspiring_brattain
efe21c4b82d3   f2b3be4848bf                               "/bin/sh -c 'pipenv …"   5 minutes ago   Exited (0) 5 minutes ago             fervent_bhabha
0d816c8715d6   e41877b140e1                               "tini -g -- entrypoi…"   5 minutes ago   Created                              peaceful_wright
f84ec590b6b7   15edd37e51da                               "/bin/sh -c 'pip ins…"   6 minutes ago   Exited (0) 5 minutes ago             stoic_galois
...
```

**Comment by madkinsz** [comment]
Hi! At first glance I thought this made sense, but I want to make sure this works as intended. Removing these intermediate images doesn't invalidate layer caching does it? We want repeated builds locally to be quick still.

**Comment by th0ger** [comment]
Of couse caching should be discussed first. I'm no expert, but:

- According to this post, it's the intermediate containers that are removed, not the image layers. Feel free to challenge this in Prefect context. https://stackoverflow.com/questions/32315996/does-docker-rm-true-affect-caching-adversly
- In practice, I have seen the containers and images grow out of control and rarely reused. I could investigate this in more detail though.
- Even though this could affect cache performance in some situations, a cache that can grow unlimited is catastrophic (and does not deserve its name). The balance should be on the safe side, where unaware users are not hit by full disks, and experts can enable cache (at own risk).
- If `rm=True` is not set, what is the recommended  way of limiting the cache size.

**Comment by madkinsz** [comment]
👍 thanks that seems correct. I'm happy to review a change in default behavior here.
