### ISSUE TITLE
prefecthq/prefect docker image: arm64 support

### ISSUE THREAD

**Issue by neumann-nico** [PrefectHQ/prefect#5388]
## Current behavior
The current prefecthq/prefect docker images are only build for linux/amd64.

## Proposed behavior
It would be great to have a multi plattform image supporting arm64.

## Example
Systems running arm64 need to emulate x86_64 images which makes it slower to run. So native support would be awesome!

**Comment by neumann-nico** [comment]
I created a PR which is unfortunately not working yet: https://github.com/PrefectHQ/prefect/pull/5394

**Comment by ddelange** [comment]
Just noting that spinning up the prefect helm chart on an ARM cluster has more blockers than just `prefecthq/prefect`, none of these have `linux/arm64` images:

- docker.io/hasura/graphql-engine:v2.0.9
- docker.io/prefecthq/apollo:2022.01.25
- docker.io/prefecthq/prefect:1.0rc0
- docker.io/prefecthq/server:2022.01.25
- docker.io/prefecthq/ui:2022-01-14

**Comment by neumann-nico** [comment]
@ddelange Yes you are right, there are more images that need to be updated to arm64.
* `ui` and `appollo` use `node` images which are arm64 compatible
* `prefect` and `server` use `python` images which are arm64 compatible
* newer `graphql-engine` images are arm64 compatible

I would be happy to help with the arm64 support

**Comment by ddelange** [comment]
From the helm side, it's also cool if we can set (global/per-service) `nodeSelector` and `tolerations`.

In our case, we're running a mixed amd/arm k8s cluster with hard taints on the arm nodes, to avoid scheduling incompatible services on the arm nodes.

**Comment by ddelange** [comment]
For multi-arch docker manifests, you cant use the `docker pull; docker tag; docker push` pattern that this repo [currently](https://github.com/PrefectHQ/prefect/blob/1.2.4/.circleci/config.yml#L10) uses to re-tag the `ui, apollo, server` images.

The multi-arch way is using [`regctl`](https://github.com/regclient/regclient):
```
curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
chmod 755 regctl
regctl image copy prefect/server:master prefect/server:42
```

**Comment by ddelange** [comment]
@madkinsz now that orion is GA, do you have an update on when this will be uncommented? :)

https://github.com/PrefectHQ/prefect/blob/2.3.1/.github/workflows/release.yaml#L127-L129

**Comment by ddelange** [comment]
the can of worms you mention in #6216 is actually pretty OK to manage as i mentioned above. also ref https://stackoverflow.com/a/68576882/5511061

**Comment by madkinsz** [comment]
`regctl` isn't on a stable version, we may want another utility for working with the images.

The primary problem is that we have split build and push sections. We persist the images to files, which is not well supported by buildx.

**Comment by ddelange** [comment]
hi @madkinsz 👋 what is the current outlook here?

**Comment by ddelange** [comment]
@madkinsz the pattern
```
regctl image copy prefect/server:master prefect/server:42
```
would fit within the current release flow without too much hassle (using master/commit-sha on docker hub instead of using gha artifacts).

I asked the maintainer why there's no 1.0.0 (see above), turns out it's because of the api, not because of the cli. I think the chances of the basic syntax above changing at this point are very small.

I would love to help here if possible, as we would really like to migrate to our cost efficient arm64 cluster :)

**Comment by madkinsz** [comment]
@ddelange that makes sense — I think we'd need to add image pushes on `main` builds and include a tag with the commit hash then refer to that during the copy during release.

I'm going to do some investigation into ways to improve our release process in general e.g. we can't rerun the release process with workflow changes if the workflow is broken. I don't have the time to tackle it at the moment though, so perhaps it's worth moving forward with these changes beforehand. It may be worth creating new a workflow that can be triggered from within another workflow i.e. "workflow dispatch" for composability.  

If you're interested in opening a pull request, I can review. Preferably, if there are going to be a lot of changes, it'd be several pull requests.

cc @jawnsy who has also been thinking about solutions here.

**Comment by ddelange** [comment]
> while waiting for approval

is this mechanic still in place? or is the separation of the push just to avoid a push when some image builds fail?

**Comment by madkinsz** [comment]
We still wait for approval before pushing releases out — I don't think we need to do so for builds from `main`.

**Comment by vishnu-anil** [comment]
Hi when can we expect this?

**Comment by ddelange** [comment]
I'm currently testing on my fork, will open a PR ASAP.

Just to make sure we're in sync @madkinsz plz correct if I misunderstood:

- on every commit to `main`, we dont want to build pypi/docs, just docker images: 
  ```
  prefecthq/prefect:main-python3.10
  prefecthq/prefect:sha-dc8b727-python3.10
  # etc for conda and python matrix
  ```
- same for `workflow_dispatch` triggered by a repo maintainer from the Actions tab, e.g. for branch `feature/cool-pr`:
  ```
  prefecthq/prefect:feature-cool-pr-python3.10
  prefecthq/prefect:sha-dc8b727-python3.10
  # etc for conda and python matrix
  ```
- when a Github release is published, docker images for latest main are already green at this point, we use `cache-from ...main...,mode=max` like always, and we push all the docker tags, plus pypi and docs

**Comment by ddelange** [comment]
[`dockersize`](https://stackoverflow.com/a/73108928/5511061) looks good:

```console
$ dockersize ghcr.io/ddelange/prefect:sha-dc8b727-python3.7
linux/amd64  181.79M
linux/arm64  166.01M
$ dockersize ghcr.io/ddelange/prefect:sha-dc8b727-python3.11
linux/amd64  194.15M
linux/arm64  174.99M
$ dockersize ghcr.io/ddelange/prefect:sha-dc8b727-python3.10-conda
linux/amd64  397.02M
linux/arm64  324.28M
$ dockersize ghcr.io/ddelange/prefect:sha-dc8b727-python3.11-conda
manifest unknown
```

**Comment by ddelange** [comment]
@madkinsz a solution without regctl :) https://github.com/PrefectHQ/prefect/pull/7740
