### ISSUE TITLE
Memory issues with Dask

### ISSUE THREAD

**Issue by carderne** [PrefectHQ/prefect#5428]
## Description
Using `DaskExecutor` causes tasks to run out of memory well before they should.

## Expected Behavior
Dask workers should be able to use as much memory as is provided to them by their host infrastructure.

### Running a Flow with Dask runs out of memory
If I run the code below (local machine, 32GB memory, 32GB swap) without the DaskExecutor, it gets to 40/50GB before being Killed because of OOM. However, if I run it as-is (on DaskExecutor), it fails at 10GB, tries three times, and then gives a `distributed.scheduler.KilledWorker`. Does Prefect do anything to the Dask [worker memory limits](http://distributed.dask.org/en/latest/worker.html#memory-management)?

(In production, I'm facing this issue running with KubernetesRun and a DaskExecutor with a KubeCluster backend, where the worker spec has 50GB of memory for both k8s and the dask worker limit. It still fails around the 10GB mark.)

```python
import numpy as np
import prefect
from prefect.executors import DaskExecutor
from prefect import Flow, task

@task
def test_memory_limits():
    logger = prefect.context.get("logger")
    for size in [1, 2, 5, 10, 20, 30, 40, 50]:
        logger.warning(f"Creating array with {size=} GB")
        a = np.ones((size * 1000, 1000, 1000), dtype=np.uint8)
        logger.warning(f"Created with size {a.nbytes/1e9=} GB")

with Flow("test-memory", executor=DaskExecutor()) as flow:
    _ = test_memory_limits()
```

### It _seems_ to be caused by Prefect
The code below works (with some memory warnings).

```python
from dask.distributed import Client
import numpy as np

def test_memory_limits():
    a = np.ones((23 * 1000, 1000, 1000), dtype=np.uint8)

client = Client(memory_limit="25G")
futures = client.submit(test_memory_limits)
client.gather(futures)
client.close()
```

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.13.0-28-generic-x86_64-with-glibc2.31",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.13",
    "python_version": "3.9.10"
  }
}
```

**Comment by carderne** [comment]
@kvnkho for reference from the Slack discussion.

**Comment by madkinsz** [comment]
Thanks for investigating! I'm sure this will help someone.
