### ISSUE TITLE
Add `RTask` to the Task Library

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5449]
We've got a great user contribution via Discourse: https://discourse.prefect.io/t/running-r-scripts-with-prefect/293/2 

Would be nice if we can add this task to the task library - @desertaxle it may be a good issue for Andrew @ahuang11

**Comment by ltieman** [comment]
Any updates on when this might be included?  Looking at prefect but have a few R scripts maintained by a couple teams that we would hopefully be able to support.

**Comment by madkinsz** [comment]
Hey @ltieman this is a user-contributed task for Prefect 1. Are you looking to use Prefect 2 with RScript?

**Comment by madkinsz** [comment]
@ltieman this issue is not for Prefect 2. However, it seems like you could easily adopt the utilities at https://gitlab.com/alping/prefect-r/-/blob/main/src/r.py#L69-115 for your own purposes.

cc @billpalombi / @desertaxle we may want a separate tracking issue for a `prefect-r` collection.
