### ISSUE TITLE
AWS Secret Manager can't retrieve non key-value secrets

### ISSUE THREAD

**Issue by raymonds-backyard** [PrefectHQ/prefect#5451]
## Description

Currently secret values on AWS secret can exist as either a plain text or a key value pair. However the current aws secret_manager.py is not able to retrieve a `plain text` secret and errors with a 

> json.decoder.JSONDecodeError: Expecting ':' delimiter: line 3 column 1

while trying to decode the secret as a json.

## Expected Behavior

For the secret manager to retrieve the string value of the secret value.

## Reproduction

Store an AWS secret with a non key-value secret value and try retrieve it with AWSSecretsManager

## Environment

  "system_information": {
    "platform": "macOS-12.0.1-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.13",
    "python_version": "3.8.6"
  }

**Comment by AlessandroLollo** [comment]
Fixed in https://github.com/PrefectHQ/prefect/pull/5458
I think this can be closed 😊
