### ISSUE TITLE
Mention Discourse on the Community section in the docs

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#5454]
https://docs.prefect.io/core/community.html Prefect v1.0 docs only mention Slack, but not https://discourse.prefect.io/

But I do see it in the footer of https://www.prefect.io/
<img width="558" alt="image" src="https://user-images.githubusercontent.com/15331990/154383977-bf8c38c1-f30e-4eaa-a5e4-c501415d8d8d.png">

Prefect v2.0 docs mention both, but unclear which one to use (https://github.com/PrefectHQ/prefect/issues/5455).

**Comment by tpdorsey** [comment]
Fixed by #5396
