### ISSUE TITLE
Allow multiple flow storage with Docker Storage when storing flows as scripts

### ISSUE THREAD

**Issue by MrKriss** [PrefectHQ/prefect#5491]
## Current behavior

With Docker Storage, you can either serialize the flow at registration time or store it as a script to be evaluated at runtime of the flow. I tend to prefer the later option as settings/config can be loaded dynamically at runtime based on the environment much easier. e.g. from environment variables 

If you wish to store multiple flows per docker storage, you can [use this pattern](https://docs.prefect.io/orchestration/recipes/multi_flow_storage.html). However this only works with flows that have been serialized. 

This is because serialized flows are each written out to a different file based on the flows name. But with flows stored as scripts, you only get the option to reference a single file when you set the `store_as_script` flag in Docker Storage.

One workaround is to have all your flows you want to define in a single file, and then use store as script.  However to keep things modular and better organized I prefer to write one flow per file.

## Proposed behavior

Allow a way to store multiple flows as separate scripts when using Docker Storage. 

One way would be to add an extra argument referencing a directory in which these flows would be stored on the docker image, and then saving them to individual .py files based on their flow name, much like the serialized flows. 

It would also help if these Python scripts be automatically added to the Docker file that's generated too, as they are for the serialised flow at current. 

## Example

I'd see the end result being something like the following:

```python
from prefect.storage import Docker

# Import flow modules from a package of flows
from flows import myflow_a, myflow_b, myflow_c

# Setup the storage object
storage = Docker(
    registry_url="<docker-registry-url>",
    image_name="multi-flow-example",
    stored_as_script=True,
    script_dir='/opt/prefect/flows',
)

# Add all Flows to storage
workflows = [
    myflow_a.flow,
    myflow_b.flow,
    myflow_c.flow,
]
for flow in workflows:
    storage.add_flow(flow)

# Build the docker image for our storage
storage = storage.build()

# Reassign the new storage object to each Flow
for flow in workflows:
    flow.storage = storage

# Register each flow without building a second time
project_name = "Examples"
for flow in workflows:
    flow.register(project_name=project_name, build=False)
```

**Comment by thomasfrederikhoeck** [comment]
We get around this with having each flow in a seperat file and then have a file called `flow_collection.py`. We then use this as the `path` variable  in the docker storage class `Docker`. This file of course needs to be copied inside the image too.

**Comment by MrKriss** [comment]
Thanks @thomasfrederikhoeck, good idea. Sounds like the best way for the time being.

**Comment by cicdw** [comment]
This issue can stay closed but we will be making this more streamlined with projects here: https://github.com/PrefectHQ/prefect/issues/9168
