### ISSUE TITLE
Orion: explore adding manual approval step similar to the `manual_only` trigger in Prefect 1.0

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5524]
## Description
From Community user: Tobias Rahloff  via https://prefect-community.slack.com/archives/CL09KU1K7/p1646814097306319:

Hi, we are currently evaluation Prefect Orion (and we are pretty amazed to be honest).
One challenge I cannot wrap my had around at the moment is manual interaction (e.g., "wait for approval"). We are crunching large visual data sets that often have unexpected features. Because of this, we need some kind of manual sanity check by a human expert before we start the compute/time intensive tasks.
[In Prefect 1.0 this was possible](https://docs.prefect.io/core/idioms/pause-for-approval.html) via the manual_only trigger. Is it possible to do the same with Orion (in the future)?

**Comment by madkinsz** [comment]
Pause / approval should cover this use case!
