### ISSUE TITLE
create_flow_run should show name of started flow in UI

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#5529]
## Current behavior
Currently the `create_flow_run` is shown as the name of the task in the UI (see picture). This makes it hard to spot which subflow it has started.
![image](https://user-images.githubusercontent.com/44194839/157853533-95ae31fe-3d9c-4748-83fb-11f48f35ae63.png)

Currently you can achieve a bit hacky with:

```
child_flow_name = "child_run_flow"
child_run_id = create_flow_run(
            flow_name="child_run_flow"
        )
child_run_id.task_run_name = f"create_flow_run: {child_flow_name}"

```

## Proposed behavior
Change the defintion of `create_flow_run` to automacly show the name of the flow. This can be done by simply changing the decorator(https://github.com/PrefectHQ/prefect/blob/7deed9896e4afa136276696b2df9d1b4f005603f/src/prefect/tasks/prefect/flow_run.py#L62) from: 

```
@task
```
to

```
@task(task_run_name="create_flow_run: {flow_name}"
```

**Comment by anna-geller** [comment]
There's actually a very easy way of setting this in your flow by using `task_args` so there is no need for any extra feature here IMO. This will change the task name in the DAG which looks like what you try to do. 

Here is how you can use it in a parent flow:

 ```python
from prefect import Flow, task
from prefect.tasks.prefect import create_flow_run, wait_for_flow_run

FLOW_NAME = "parent_flow_example"


@task(log_stdout=True)
def hello_world():
    print(f"Hello from {FLOW_NAME}!")
    return FLOW_NAME


with Flow(FLOW_NAME) as flow:
    normal_non_subflow_task = hello_world()
    first_child_flow_run_id = create_flow_run(
        flow_name="child_flow_name",
        project_name="PREFECT_PROJECT_NAME",
        task_args=dict(name="Name it as you like and this will show in the DAG"),
        upstream_tasks=[normal_non_subflow_task],
    )
    first_child_flowrunview = wait_for_flow_run(
        first_child_flow_run_id,
        raise_final_state=True,
        stream_logs=True,
        task_args=dict(name="Wait for the first subflow"),
    )
```

If the above :point_up: works for you, feel free to close the issue.

And if you're looking for a way to change the flow run name of a child flow you can use the run_name argument on the create_flow_run task and this thread shows how you can even set it dynamically via a separate task: https://discourse.prefect.io/t/how-to-dynamically-change-the-run-name-in-the-create-flow-run-task/97

**Comment by thomasfrederikhoeck** [comment]
Thank you for the quick reply @anna-geller ! 🐇 That definitely solves it for me. I will close the issue.
