### ISSUE TITLE
Prefect flows won't start after maor release 1.0?

### ISSUE THREAD

**Issue by th0ger** [PrefectHQ/prefect#5530]
## Description
We have a flow that won't start after upgrading them to version `1.1.0`. They wait in the scheduled state and are not picked up by any agents.
Agents are in versions `0.14.13`, `0.14.16`, `0.15.11` and all have labels matching the flow.
If we downgrade the flow to `0.15.11`, it is picked up again by agents.

## Expected Behavior

If it is a known or expected breaking change that agents `<1.0` can´t start flows `=>1.0`, it should be added to the [CHANGELOG](https://github.com/PrefectHQ/prefect/blob/master/CHANGELOG.md)

**Comment by madkinsz** [comment]
Hey @th0ger, we always recommend having agents / flows run on versions that do not mix major versions. That said, I'd expect the agent to still pick up work here. If you run your v1+ flow with `prefect run --name <flow-name> --watch` it should display some warnings if it is not picked up by an agent, could you share those?

**Comment by th0ger** [comment]
Hey,
> we always recommend having agents / flows run on versions that do not mix major versions

Is that documented? I assume that by major version you mean X.y.y as in semver.org ? Since 1.0.0 is the first major, I'm not sure how to understand "always" :-)
It is not clear if flows & agents are forward and/or backwards compatible with each other.
Should we upgrade agents or flows first?
Or do we need to use explicit labels v0/v1/v2 to prevent major mix?
