### ISSUE TITLE
1.1.0 docs are not yet available

### ISSUE THREAD

**Issue by multimeric** [PrefectHQ/prefect#5535]
## Description
1.1.0 docs are not yet available

## Expected Behavior
1.1.0 changes to be visible on the website, e.g. the API docs, and my pipe docs under [prefect idioms](https://docs.prefect.io/core/idioms/idioms.html).

## Reproduction

* https://docs.prefect.io/core/idioms/idioms.html
* https://docs.prefect.io/api/latest/

**Comment by madkinsz** [comment]
Fixed! Thanks.
