### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by VikalpRusia** [PrefectHQ/prefect#5538]
Hello!

I've found an issue here:`Because Prefect flows are not executed at runtime`
This can be a little misleading it's better to rename it to when created. 

Page reference: https://docs.prefect.io/core/concepts/tasks.html

**Comment by anna-geller** [comment]
So true, thanks for the PR!

**Comment by VikalpRusia** [comment]
change reflected hence closing the issue

**Comment by VikalpRusia** [comment]
@anna-geller How much time will it take to be reflected in docs https://docs.prefect.io/core/concepts/tasks.html#indexing ?

**Comment by anna-geller** [comment]
In the next release, likely next month. Thanks for contributing!
