### ISSUE TITLE
Orion: as a user, I would like to set defaults, such as default `max_retries`, that can be optionally overridden on a per-task basis

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5540]
## Description
In Prefect 1.x a user can set some defaults using:
```
prefect.config.tasks.defaults.max_retries=3
```
The same can be configured using environment variables or be set in config.toml:
```
export PREFECT__TASKS_DEFAULTS_MAX_RETRIES=3
```

Is something like that already possible in Orion? If not, can this be added to the backlog for later? So far I couldn't find any task defaults in Profile Settings: https://orion-docs.prefect.io/concepts/settings/

**Comment by madkinsz** [comment]
This wouldn't persist to non-local runs and providing environment variables to change this behavior seems painful. I'd rather encourage people to use a custom decorator. Perhaps we can create a decorator factory function that lets you change the defaults easily.

**Comment by anna-geller** [comment]
> This wouldn't persist to non-local runs and providing environment variables to change this behavior seems painful. I'd rather encourage people to use a custom decorator. Perhaps we can create a decorator factory function that lets you change the defaults easily.

I wasn't suggesting any concrete solutions/implementations (such as environment variables - this was only to show how this worked in 1.0 to explain what was meant). This issue is only to show that this is an extremely commonly reported problem - many users would like to have some way of specifying defaults that make sense for most use cases (but not all) to avoid boilerplate. 

Many users currently use a custom task decorator but this requires them to package and install this custom code into their execution environment every time which is a bit tedious/adds unnecessary complexity. 

If anything, I was thinking more if this could be configurable globally on the backend side (not only for local runs), e.g. via CLI or UI like other settings/profiles

**Comment by madkinsz** [comment]
The settings/profiles are all local-only. The only setting configurable from the API is the "default storage" which is persisted to the database. Introducing API backed settings for some of these may be possible though. If we do, we have to deal with expectations where:
- The server value should always be used
- The client value should always be used
- The server and client values should be merged (e.g. tags)

This kind of resolution has proven tricky in the past.

**Comment by anna-geller** [comment]
@madkinsz thanks so much for explaining this in detail. The problem here may be simpler - what users often ask is to allow defaults that can be optionally overridden client-side (in the flow code). So only this use case (your second bullet point) would be expected "The (default) server value should be used if there is not a client value". 

@cicdw mentioned an interesting idea recently to set such defaults on a per tag basis which would make a lot of sense (tasks talking to a database may need different retries or concurrency limits than tasks talking to some third party API).
