### ISSUE TITLE
Agent sends logs to the Cloud API, yet LOGS tab on flow runs does not display any logs on Cloud UI

### ISSUE THREAD

**Issue by shaybensasson** [PrefectHQ/prefect#5546]
## Description

When using `UniversalRun`, logs are always empty in flow-run `LOGS` tab on the Prefect Cloud UI. They are `graphql http posted` to the prefect API (_I validated this using the debugger_), yet when I navigate to the running flow, the logs tab is always empty.
I made sure nothing is preventing them to be sent in the `config.toml`. As you can see in the MWE below I tried the `context logger` and the `log_stdout=True` options. 
I also tried many different configurations in the `config.toml`, non of them seem to display any logs in the UI.

## Expected Behavior

Just as the logs appear in the console when using `Prefect Server`, they should appear in the Cloud UI. I also tried `flow.run_agent(log_to_cloud=True, show_flow_logs=True)`. The logs are written to the console, yet I can't find them on UI.

## Reproduction

```python
import prefect
from prefect import task, Flow


@task()
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("=" * 50 + f" Hello world, Prefect: {prefect.__version__}! " + "=" * 50)


@task(log_stdout=True)
def log_std_out_test():
    print("hello world")


with Flow(
        "quick-and-dirty-prefect-log-print",
) as flow:
    ht = hello_task()
    lsot = log_std_out_test()

    ht.set_downstream(lsot)

# flow.run()  # We could run our flow locally using the flow's run method but we'll be running this from Cloud!

flow.register(project_name="prefect-quick-start")
flow.run_agent(log_to_cloud=True, show_flow_logs=True)
```

~/.prefect/config.toml:
```toml
[logging]
# The logging level: NOTSET, DEBUG, INFO, WARNING, ERROR, or CRITICAL
level = "INFO"
# level = "DEBUG"
```

## Environment

```python
{
  "config_overrides": {
    "cloud": {
      "agent": {
        "api_key": true
      },
      "api_key": true
    },
    "context": {
      "secrets": false
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-99-generic-x86_64-with-glibc2.27",
    "prefect_backend": "cloud",
    "prefect_version": "1.0.0",
    "python_version": "3.8.2"
  }
}
```

**Comment by madkinsz** [comment]
@shaybensasson Hi! Are these logs still missing? Sometimes during periods of high load they can take time to propagate through the system.

**Comment by shaybensasson** [comment]
Thanks for the quick reply.

Just checked, unfortunately, LOGS are still empty. I recall that the same code worked a week ago, did you change something on the UI mechanism or on the graphql query mechanism that fetches the LOGS?
Tried this again with prefect `0.15.13` and `1.1.0`, but LOGS are empty.

**Comment by madkinsz** [comment]
Thanks for looking. Can you share an affected flow run id? You've said that you confirmed via debugger that the logs are being posted to the API at runtime?

**Comment by shaybensasson** [comment]
Sure, here you go:
https://cloud.prefect.io/flow/d26b18f7-d15d-4cf5-928c-3d4b565513ce

There are two runs over there, they should both have LOGS, yet they don't.

**Comment by shaybensasson** [comment]
Just for convenience, could you please paste here a `graphql` query that I can sanity check if logs were stored in the Cloud db.
I tried my best to compose one. Is this the place where the logs should be stored at?
```graphql
{
  flow(where: {name: {_eq: "quick-and-dirty-prefect-log-print"}, version: {_eq: 2}}) {
    name
    version
    
    tasks {
      id
      name
      task_runs {
        id
        details {
          id
          current_state {
            id
            message
          }
        }
        logs {
          message
        }
      }
    }
  }
}

```

**Comment by shaybensasson** [comment]
And yes I found that they are `http-posted` to the API (did a step-by-step run using the debugger).

**Comment by madkinsz** [comment]
We can confirm that there are no logs in the database for that run.

Can you reproduce this without using the `run_agent` method? e.g.

```
prefect run --name quick-and-dirty-prefect-log-print --execute
```

**Comment by shaybensasson** [comment]
Runs as expected, i.e., writes logs to console:

<pre>Looking up flow metadata...<font color="#4E9A06"> Done</font>
Creating run for flow &apos;quick-and-dirty-prefect-log-print&apos;...<font color="#4E9A06"> Done</font>
└── Name: whispering-owl
└── UUID: d463faa3-b520-4936-aff4-e6d409ea913a
└── Labels: [&apos;agentless-run-df595583&apos;]
└── Parameters: {}
└── Context: {}
└── URL: https://cloud.prefect.io/neurohelp/flow-run/d463faa3-b520-4936-aff4-e6d409ea913a
Executing flow run...
└── 08:28:38 | INFO    | Creating subprocess to execute flow run...
└── 08:28:40 | INFO    | Beginning Flow run for &apos;quick-and-dirty-prefect-log-print&apos;
└── 08:28:42 | INFO    | Task &apos;hello_task&apos;: Starting task run...
└── 08:28:43 | INFO    | ================================================== Hello world, Prefect: 1.0.0! ==================================================
└── 08:28:44 | INFO    | Task &apos;hello_task&apos;: Finished task run for task with final state: &apos;Success&apos;
└── 08:28:44 | INFO    | Task &apos;log_std_out_test&apos;: Starting task run...
└── 08:28:45 | INFO    | hello world
└── 08:28:46 | INFO    | Task &apos;log_std_out_test&apos;: Finished task run for task with final state: &apos;Success&apos;
└── 08:28:46 | INFO    | Flow run SUCCESS: all reference tasks succeeded
<font color="#4E9A06">Flow run succeeded!</font>
</pre>

**Comment by madkinsz** [comment]
And these logs are sent to the API/UI as expected as well?

**Comment by shaybensasson** [comment]
Yes, exactly.

Let me describe the debugger steps:
- Using `CloudHandler.emit()` it invokes `LOG_MANAGER.enqueue(log)`
- Later the loop pull it from the queue and the prefect `Client.write_run_logs()` it sends the `graphql` message and returns 
```python
{'write_run_logs': {'success': True}}
```

It looks like it reaches the `'https://api.prefect.io'` server and returns a successful result.
I wonder why you can't see anything on the server.
