### ISSUE TITLE
Ban calling `flow.run()` from within its own context

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#5556]
## Current behavior

You are allowed to call a flow in its context manager

```python
with Flow(...) as flow:
    flow.run()
```

This can lead to poor behavior, e.g. https://github.com/PrefectHQ/prefect/issues/5555

## Proposed behavior

`flow.run` should not be callable from within the the flow context. If called, an error should be raised explaining that the flow must be called outside of the context block.

## Example

This prevents errors and aligns user expectations with the internal behavior of Prefect.

**Comment by Fraznist** [comment]
it seems `flow.run` employs a similar check to detect if it is being called while it is being loaded to storage:
```python
if prefect.context.get("loading_flow", False):
    warnings.warn(
        "Attempting to call `flow.run` during execution of flow file will lead to "
        "unexpected results.",
        stacklevel=2,
    )
    return None
```
Similarly, being in a `with Flow()` context manager sets a key named `flow` in the `prefect.context`. See:
https://github.com/PrefectHQ/prefect/blob/96183e95ad069c927799a6a272bc3d9a9cce3197/src/prefect/core/flow.py#L357

In short, I think the following should work:
```python
if "flow" in prefect.context:
    raise ValueError("flow.run cannot be called from within a flow context.")
```
I just slapped `ValueError` in there but what would be a sensible exception @madkinsz ?

**Comment by madkinsz** [comment]
Yeah that's a reasonable implementation. I'd raise a `RuntimeError` and perhaps include a minimal example in the error message indicating how run should be called e.g.

```python
with Flow(...) as flow:
   # wrong
   flow.run()

# right
flow.run()
```

**Comment by tirkarthi** [comment]
I guess this can be closed with https://github.com/PrefectHQ/prefect/pull/5588 merged

**Comment by madkinsz** [comment]
Yep thanks!
