### ISSUE TITLE
Add the executor object (or executor class) to the context

### ISSUE THREAD

**Issue by multimeric** [PrefectHQ/prefect#5557]
## Current behavior
Currently it's not possible to determine which executor is being used at runtime. The context object contains no information that can be used to obtain it.

## Proposed behavior
We simply attach the flow's executor to the config object. For example:

```python
import prefect
from prefect.executors import DaskExecutor

@prefect.task()
def foo():
    if isinstance(prefect.context.executor, DaskExecutor):
        # Do something dask specific
```

## Example
A user may want to write a flow that can work on any executor, but that makes use of specific executor features if they are available. For example, the `DaskExecutor` allows for a progress bar for tasks, and requires a call to `worker_client()` to allow the worker to submit sub-tasks. If the above feature is implemented we could do the following:

```python
import prefect
from prefect.executors import DaskExecutor
from dask.distributed import progress, worker_client
import dask.dataframe as ddf

@prefect.task()
def foo(df: ddf.DataFrame):
    if isinstance(prefect.context.executor, DaskExecutor):
        with worker_client():
            with progress():
                df.apply(...).compute()
    else:
        df.apply(...).compute()
```

**Comment by madkinsz** [comment]
Thanks for continuing to raise well written issues :) I can definitely see this being a useful pattern.

The context needs to be copied many times so we can't put the executor in it directly. We could put an `executor_type` string though.
