### ISSUE TITLE
Generate a script to calculate the number of billable tasks ran by Prefect Server over a period of time

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5559]
## Problem
Many users considering migrating to Prefect Cloud would like to estimate their future pricing based on the past usage patterns. For that reason, many users requested a script or query computing the number of monthly billable task runs. 

## GraphQL query we have so far
One can leverage `task_run_aggregate` query:

```graphql
 query {
  task_run_state_aggregate(where: {
      timestamp: { _gte: "2022-03-01T00:00:00.000000+00:00" }
      state: { _in: ["Success"] }
    }) {
    aggregate {
      count
    }
  }
}
```
But this query includes all successful tasks, even though that took **less than a second**, and those need to be excluded (you will need to use the start and end time of a task run to calculate the task run duration). 

In the same way, **retries** need to be excluded.

## Cloud
In Prefect Cloud there is a query:

```
{
  billing_usage(order_by: {timestamp: desc}) {
    runs
    timestamp
  }
}
```

We may use this internally or perhaps even add this API route to Prefect Server.

## Postgres query?
One could write a Postgres query to calculate it more elegantly - adding this option in case someone from the community has a query they may share.

**Comment by hazardsy** [comment]
Here's an attempt at a Postgres query, I think it's pretty close to accurate : 
```sql
WITH
        task_runs_with_duration AS (SELECT *, end_time-start_time as duration FROM prefect.public.task_run)
SELECT 
       COUNT(*) 
FROM 
       task_runs_with_duration 
WHERE 
     state='Success' 
     AND
     duration>'00:00:01' 
     AND 
     start_time >= NOW() - interval '30 days'
```
