### ISSUE TITLE
How is Average time calculated in Prefect Orion UI?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [PrefectHQ/prefect#5576]
## Description
How come the average run time is ~2mins when none of the flow runs exceeds 1min?

![image](https://user-images.githubusercontent.com/32126716/159042209-da1081a6-2370-4034-9254-e2401456c068.png)

**Comment by pleek91** [comment]
@Sinha-Ujjawal that sure doesn't seem correct. I will investigate and see what's going on here. Thanks for bringing this to our attention

**Comment by pleek91** [comment]
@Sinha-Ujjawal confirmed it is not correct. Currently that average is the average of the chart intervals. Essentially its averaging the bars on the chart. But it's supposed to be the average of all the runs like you mentioned. 

We will address this. Thank you for pointing it out!

**Comment by manterfield** [comment]
I'm seeing another error with most of the duration based fields in Orion when I look at the logs for the API. There's a long stack trace on requests to the `/flow_runs/history` endpoint, but the interesting bit is:

```
pydantic.error_wrappers.ValidationError: 5 validation errors for ParsingModel[List[prefect.orion.schemas.responses.HistoryResponse]]
__root__ -> 22 -> states -> 0 -> sum_estimated_run_time
  invalid duration format (type=value_error.duration)
__root__ -> 22 -> states -> 0 -> sum_estimated_lateness
  invalid duration format (type=value_error.duration)
__root__ -> 26 -> states -> 0 -> sum_estimated_run_time
  invalid duration format (type=value_error.duration)
__root__ -> 26 -> states -> 0 -> sum_estimated_lateness
  invalid duration format (type=value_error.duration)
__root__ -> 28 -> states -> 0 -> sum_estimated_run_time
  invalid duration format (type=value_error.duration)
```

I've followed this code as much as I'm able to given I've not used SQLAlchemy much and couldn't really get to the bottom of it. Everything I could think to check looked correct, but obviously at some point the data type expected by Pydantic for these fields isn't what it ends up getting. This is on `2.0b3-python3.9`

**Comment by zhen0** [comment]
@manterfield - if you are still seeing this would you mind opening it as a separate issue?  Although it's time related I don't think it's the same root cause and risks getting lost.

**Comment by dylanbhughes** [comment]
@zhen0 I think this is no longer relevant due to the redesign

**Comment by zhen0** [comment]
Correct @dylanbhughes Thanks!
