### ISSUE TITLE
Add mapping (`.map()` operator)

### ISSUE THREAD

**Issue by anmyachev** [PrefectHQ/prefect#5582]
Is it worth writing workloads as it is written [here](https://orion-docs.prefect.io/faq/#does-orion-support-mapping), or there will be a release with `map` operator support in the near future?  Is there an estimated date?

**Comment by madkinsz** [comment]
We'll likely support a map operator in the future, but it's a complex feature and there is no target date.

**Comment by tekumara** [comment]
Looks like this is now available, see [Does Prefect 2.0 support mapping?](https://docs.prefect.io/faq/?h=task+map#does-prefect-20-support-mapping)

**Comment by cicdw** [comment]
We overlooked closing this issue when mapping was released, closing now
