### ISSUE TITLE
Orion: Wrong conversion of integer to bytes in stable_hash function

### ISSUE THREAD

**Issue by vovanbo** [PrefectHQ/prefect#5590]
## Description
Integer in `stable_hash` function will be converted to zero-filled bytes object instead of byte representation of integer. Also it will be potential memory leak in case of big integers (e.g. `10**10`).

## Reproduction / Example
https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/utilities/hashing.py#L25

```python
        elif isinstance(a, int):
            a = bytes(a)
```

In this case conversion to bytes should be `a.to_bytes(...)` or `bytes(str(a))`.

**Comment by madkinsz** [comment]
Thanks! I'll patch this immediately.
