### ISSUE TITLE
context.get("logger") and self.logger behave differently on mapped task runs (possibly more)

### ISSUE THREAD

**Issue by Fraznist** [PrefectHQ/prefect#5592]
## Description
For a class based task, `self.logger` is a snapshot of a prefect logger instance during task initialization time. While the logger within prefect context (`prefect.context.get("logger")`) changes throughout the lifecycle of a flow build/run/etc. This causes the two methods of logging within a task run to behave differently. 

One instance is mapped task runs, where the loggers name indicates both the task name and the map index. Keep in mind that differing behavior may not be limited to mapped tasks, this is just the example I could find.

## Expected Behavior

Using self.logger within `task.run` and deriving the logger from context to behave the same.

## Reproduction

```python
class MyTask(prefect.Task):
    def run(self):
        map_index = prefect.context.get("map_index")
        self.logger.warning("{}".format(map_index))

@prefect.task
def myrun():
    logger = prefect.context.get("logger")
    map_index = prefect.context.get("map_index")
    logger.warning("{}".format(map_index))

with prefect.Flow("Logger_Compare") as f:
    MyTask().map(upstream_tasks=[list(range(1))])
    myrun.map(upstream_tasks=[list(range(1))])
f.run()
```

**Comment by Fraznist** [comment]
## Proposal
Within `prefect.Task`:
```python
@property
def logger(self):
    return prefect.context.get("logger")
```
This way `self.logger` still returns a logger, and both options boil down to `context.logger`

**Comment by madkinsz** [comment]
I'm not entirely sure of the implications of this without digging in, but if you want to give it a go I'm willing to review it.
