### ISSUE TITLE
Custom filtered dashboard cannot be saved

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5606]
## Description
I tried to save a custom dashboard that would include more than last day and wouldn't include Scheduled runs. But the dashboard couldn't be saved:
![image](https://user-images.githubusercontent.com/86264395/160499744-a8a3f5d5-29b7-49ea-a249-27a188a334f8.png)

## Reproduction
Tested using Cloud 2.0 and:

```shell
Version:             2.0b2
API version:         0.3.0
Python version:      3.9.7
Git commit:          b2a048c2
Built:               Thu, Mar 17, 2022 2:24 PM
OS/Arch:             darwin/x86_64
Profile:             cloud
Server type:         hosted
```

**Comment by madkinsz** [comment]
cc @zhen0

**Comment by zangell44** [comment]
It looks like the UI is trying to send a filter with a `.value` attribute of type `list` (in this particular case a list of flow run state types). In the backend this value type is defined as a `string`.

Happy to work with the UI team to clarify what the correct behavior is

**Comment by zhen0** [comment]
Also tracked in Monday #2492173365

**Comment by joeclayallday** [comment]
**Tiny UI tweak - Adjust buttons styling**
Can we style the cancel button in our secondary-button style & make them both 50% width padding all around?

<img width="566" alt="Screen Shot 2022-03-31 at 7 14 11 PM" src="https://user-images.githubusercontent.com/4295811/161170475-9b7ed51a-f920-4446-93f3-81cd4337e393.png">

**Comment by anna-geller** [comment]
@pleek91 installing from main doesn't seem to fix it - can you cross-check?
![image](https://user-images.githubusercontent.com/86264395/161653737-a3813d55-c3cc-4e31-9756-1667ab1bc966.png)

**Comment by pleek91** [comment]
@anna-geller I wasn't testing this correctly, I'm reproducing it now

**Comment by pleek91** [comment]
Related to https://github.com/PrefectHQ/orion/issues/1280
