### ISSUE TITLE
Add toggle for automatic concurrency limit of one run per deployment

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5623]
## Description
Currently, if a user wants to ensure that there is no more than one active flow run from a specific deployment, they have to create a work queue with a concurrency limit of 1 and spin up a separate agent process for each such work queue. Implementing this for many flows becomes unmanageable.

## Excerpt from the request made via Slack

[**View in #prefect-community on Slack**](https://slack.com/archives/CL09KU1K7/p1648631937216979)

![Jacobo_Blanco] **@Jacobo_Blanco:** One pattern that emerges very often for us is Singleton flows (For the sake of clarity, only one run of this specific flow can ever be active at any one time). The other hidden constraint is that due to Change Management/Security/Auditing requirements that are in place it’s not a simple procedure to log into the EC2 instance and execute commands.

First assumption check: I assume that the agent commands have to be executed on the instance, is that right?

![Anna_Geller] **@Anna_Geller:** correct, they must be executed on the agent

regarding singleton-flow-runs: I believe we may add a feature allowing to have only one active flow run of each specific flow without having to explicitly set a work-queue concurrency limit of 1 for each of them

![Jacobo_Blanco] **@Jacobo_Blanco:** If that is the case then this covers the biggest pain point. It would be very unproductive to have to create 50 queues and agents for 50 singleton flows.

Thanks for the quick response.

[Jacobo_Blanco]: https://avatars.slack-edge.com/2019-12-03/857109811792_877584fe7c70c84fc3d2_24.png
[Anna_Geller]: https://avatars.slack-edge.com/2021-10-04/2585679938480_3d7e8c7969cc36b0c7ca_24.jpg

**Comment by anna-geller** [comment]
With the changes to work-queues introduced in 2.1 - [link](https://discourse.prefect.io/t/prefect-2-1-0-has-just-arrived-it-includes-python-based-deployments-improvements-to-work-queues-tons-of-new-integrations-and-features/1422#simplified-agents-work-queues-rocket-2) work queues are automatically created if they don't yet exist and are provided on agents or deployments

with that, this story is satisfied - the user can provide a unique work queue per deployment and this way, run each deployment agent in a separate work queue easily and optionally also set a concurrency limit of 1 with a single command:
```shell
prefect work-queue create x --limit 1
```

**Comment by madkinsz** [comment]
This still requires a distinct agent per work queue, yes? I'm not sure this fully satisfies the request here, although it sounds like we've made it easier.

**Comment by anna-geller** [comment]
that's true - I believe given how easy it is now to do it and manage the work queues, we may not any separate feature for this, but if you feel like I closed it prematurely and we can handle it nicer, please reopen

thanks Michael!

**Comment by anna-geller** [comment]
actually, you're right, it may not be optimal if the user needs to spin up 50 agents to ensure their 50 deployments are all singletons - reopening this

**Comment by imsurat** [comment]
@anna-geller  Can you give a rough ETA/timeline for addressing this need? We are impacted by this and this is a Major Blocker to the launching of our revamped workflows based on Orion and being able to truly retire our Prefect 1.0 workflows.

**Comment by madkinsz** [comment]
We don't have a design for this feature yet so there's no timeline we can provide yet. I'll bring this to the attention of our product team.

**Comment by anna-geller** [comment]
Michael, I pinged Bill about it

**Comment by anna-geller** [comment]
Nitpick from the product team: the conclusion on the issue is a bit imprecise -- the user can have a single agent with potentially 50 or more queue names attached to it 

But correct, this is not the best UX if adding one more singleton deployment requires redeploying the agent t attach an additional queue name to the agent start command, so the issue should still be open

**Comment by abrookins** [comment]
@imsurat It sounds like the current workflow to support this is for you to create one deployment per singleton flow and then run as few as one agent process pointing at every work queue associated with those deployments (because an agent can pull from multiple queues). Does that remove the blocker you have?

**Comment by imsurat** [comment]
Hi @abrookins,

Yes but this approach is not scalable/desirable since it needs us to either restart the prefect-agent or launch a new instance of prefect-agent for each flow that we want to be serialized. We are okay with using this short-term workaround for our new flows.  I am not sure if there is a metric that determines what is the max limit on the number of queues an instance of an agent can handle.

FYI we will hold off to migrate our old flows running on Prefect 1.0 Cloud until there is a more dynamic way to do this. E.g.  As a suggestion 
- being able to mark a deployment as singleton or 
- designating a queue for this functionality that allows flow-runs of different deployments to run in parallel, but not the flow-runs of the same deployment.

**Comment by abrookins** [comment]
Thank you for the detailed feedback, @imsurat! I'll talk to our product team about this.
