### ISSUE TITLE
Add wildcard and negation filters to dashboard

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5625]
## Description
When trying to filter for specific flows, tasks, flow runs or task runs, it would be great if one could filter for only names that:
- contain specific words e.g. "etl" or "ml"
- start with a specific name e.g. "stage*" allowing to filter for all staging area tables e.g. `stage_salesforce`
- end with a specific name e.g. "*report" allowing to filter for reporting tasks e.g. `sales_report`
![image](https://user-images.githubusercontent.com/86264395/161129026-efede792-47d6-45be-8cfc-cd0734bb3d66.png)

Similarly, sometimes you may have a task such as tasks executed with Dask that generate potentially thousands of tasks and clutter the dashboard, it would be great to allow NOT filters e.g. here I have over 700 tasks that contain a name "test" because those were test tasks created on Dask - a filter like `trn:<>test` or `trn:!=test` would be great in filtering those out:
![image](https://user-images.githubusercontent.com/86264395/161128626-a724c396-f0c9-4c51-90f4-4e3a163e279b.png)

**Comment by zhen0** [comment]
Thanks @anna-geller - I believe this would require API changes as we currently need an exact string for each filter and we wouldn't want to do this client side. @zangell44 might be able to add some more detail.

**Comment by zangell44** [comment]
Correct Jenny this requires API changes, we will probably do something like this for fuzzy searching.
The best solution in the meantime is using tags https://orion-docs.prefect.io/concepts/tasks/#tags

**Comment by dylanbhughes** [comment]
Requires followup post-redesign

**Comment by zangell44** [comment]
Fuzzy matching support was added in this PR https://github.com/PrefectHQ/orion/pull/1960
