### ISSUE TITLE
Can't install in Conda

### ISSUE THREAD

**Issue by spireitepaul** [PrefectHQ/prefect#5645]
## Description
Following the instructions for installation (using Conda)

conda create --name prefect
conda activate prefect
pip install -U "prefect>=2.0b"

I receive the following error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
snowflake-connector-python 2.5.1 requires cryptography<4.0.0,>=2.5.0, but you have cryptography 36.0.2 which is incompatible.

running the following in Conda prompt 

python --version

returns

Python 3.9.8

## Reproduction / Example
The above steps should recreate it.

**Comment by madkinsz** [comment]
I not believe we require `snowflake-connector`, so I presume something is wrong with your environment here.

If I try to run the commands you've provided, I get `zsh: command not found: pip`. Running `conda install pip` then `pip install -U "prefect>=2.0b"` works without error.
