### ISSUE TITLE
Add to docs that functions must be wrapped with @task for it to be submitted in parallel to Dask/RayTaskRunner?

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#5667]
**Update**: the function has to be decorated with `@task` for it to run automatically in parallel

## Description

I see that four workers have been spawned, but the CPU utilization is negligible.
![image](https://user-images.githubusercontent.com/15331990/162659673-b9c68865-68c0-4191-b957-45fcea1e31ea.png)

Using native dask, I was able to drop the serial version runtime from 2 min 39 seconds down to 46 seconds, but there was no speed up using DaskTaskRunner; full benchmark here.
https://discourse.prefect.io/t/why-is-dasktaskrunner-slower-than-dask-compute/729/8?u=ahuang11

## Expected Behavior

100% CPU utilization on every process spawned.

## Reproduction

```
import dask
import xarray as xr
import matplotlib.pyplot as plt
from cartopy import crs as ccrs
from cartopy import feature as cfeature
import cartopy.crs as ccrs
import matplotlib.textpath
import matplotlib.patches
from matplotlib.font_manager import FontProperties
import numpy as np
from prefect import flow, task, get_run_logger
from prefect.task_runners import DaskTaskRunner


def plot(ds, time):
    plt.figure()
    ax = plt.axes(projection=ccrs.Orthographic())
    ax.add_feature(cfeature.LAKES.with_scale("10m"))
    ax.add_feature(cfeature.OCEAN.with_scale("10m"))
    ax.add_feature(cfeature.LAND.with_scale("10m"))
    ax.add_feature(cfeature.STATES.with_scale("10m"))
    ax.add_feature(cfeature.COASTLINE.with_scale("10m"))
    ax.pcolormesh(ds["lon"], ds["lat"], ds["air"], transform=ccrs.PlateCarree())

    # generate a matplotlib path representing the word "cartopy"
    fp = FontProperties(family='Bitstream Vera Sans', weight='bold')
    logo_path = matplotlib.textpath.TextPath((-175, -35), 'cartopy',
                                             size=1, prop=fp)

    # add a background image
    im = ax.stock_img()
    # clip the image according to the logo_path. mpl v1.2.0 does not support
    # the transform API that cartopy makes use of, so we have to convert the
    # projection into a transform manually
    plate_carree_transform = ccrs.PlateCarree()._as_mpl_transform(ax)
    im.set_clip_path(logo_path, transform=plate_carree_transform)

    # add the path as a patch, drawing black outlines around the text
    patch = matplotlib.patches.PathPatch(logo_path,
                                         facecolor='none', edgecolor='black',
                                         transform=ccrs.PlateCarree())
    ax.add_patch(patch)
    ax.set_global()

    plt.savefig(str(time)[:16])
    plt.close()

ds = xr.tutorial.open_dataset('air_temperature').isel(
    time=slice(0, 100))

@flow(task_runner=DaskTaskRunner(cluster_kwargs={"n_workers": 4, "processes": True}))
def process():
    for time in ds['time'].values:
        plot(ds.sel(time=time), time)

process()
```

## Environment
prefect>=2.0

**Comment by madkinsz** [comment]
Why would you expect normal functions to run as Prefect tasks? :D 

I'm not sure where the best place to add clarity on this is.

**Comment by ahuang11** [comment]
Or maybe warn users if there are no tasks detected in the flow?

**Comment by madkinsz** [comment]
> Maybe there can be a new logging level named "logging.TASK_RUN" or "logging.FLOW_RUN" in between DEBUG and INFO so one can easily suppress these logs?

You can already adjust the log level for the loggers independently e.g.

`PREFECT_LOGGING_LOGGERS_PREFECT_FLOW_RUNS_LEVEL="WARNING"`

> Append a warning saying "functions must be decorated with @task to be submitted in parallel"

We can note that in the task runner documentation that only _tasks_ will be used with the task runner, not undecorated functions.
I don't think we should throw a warning if there are no tasks, that's a totally viable use-case.

**Comment by ahuang11** [comment]
Cool I got it to suppress some logs with:
```
%set_env PREFECT_LOGGING_LOGGERS_PREFECT_FLOW_RUNS_LEVEL=DEBUG

import logging

import xarray as xr
import matplotlib.pyplot as plt
from prefect import flow, task, get_run_logger
from prefect.task_runners import DaskTaskRunner

@task
def plot(ds, time):
    logger = get_run_logger()
    logger.info(time)
    plt.figure()
    ds['air'].plot()
    plt.savefig(str(time)[:16])
    plt.close()


@flow(task_runner=DaskTaskRunner(cluster_kwargs={"n_workers": 4}))
def prefect_process():
    logger = get_run_logger()
    logger.setLevel(logging.WARNING)

    ds = xr.tutorial.open_dataset('air_temperature').isel(
        time=slice(0, 3))
    [plot(ds.sel(time=time), time) for time in ds['time'].values]

prefect_process()
```

However, I was wondering where did you get `PREFECT_LOGGING_LOGGERS_PREFECT_FLOW_RUNS_LEVEL="WARNING"`?

I couldn't find it in https://orion-docs.prefect.io/concepts/logs/ or https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/logging/logging.yml


> I don't think we should throw a warning if there are no tasks, that's a totally viable use-case.
Right, for ConcurrentTaskRunner I think so, but perhaps a warning if DaskTaskRunner / RayTaskRunner then? Because if no tasks are defined, then there's no point using DaskTaskRunner + RayTaskRunner if I am not mistaken?

**Comment by madkinsz** [comment]
Well you'd suppress task run logs with `PREFECT_LOGGING_LOGGERS_PREFECT_TASK_RUNS_LEVEL`

**Comment by ahuang11** [comment]
If I am not mistaken,
```
%set_env PREFECT_LOGGING_LOGGERS_PREFECT_FLOW_RUNS_LEVEL=DEBUG
%set_env PREFECT_LOGGING_LOGGERS_PREFECT_TASK_RUNS_LEVEL=DEBUG
```
Did not suppress the task run logs
```

12:18:57.697 | DEBUG   | Flow run 'primitive-marmoset' - Beginning execution...
12:19:00.275 | DEBUG   | Task run 'plot-f5265e9c-0' - Beginning execution...
12:19:00.276 | INFO    | Task run 'plot-f5265e9c-0' - 2013-01-01T00:00:00.000000000
12:19:00.349 | DEBUG   | Task run 'plot-f5265e9c-1' - Beginning execution...
12:19:00.350 | INFO    | Task run 'plot-f5265e9c-1' - 2013-01-01T06:00:00.000000000
12:19:00.354 | DEBUG   | Task run 'plot-f5265e9c-2' - Beginning execution...
12:19:00.355 | INFO    | Task run 'plot-f5265e9c-2' - 2013-01-01T12:00:00.000000000
12:19:00.380 | INFO    | Task run 'plot-f5265e9c-0' - Finished in state Completed(None)
12:19:00.465 | INFO    | Task run 'plot-f5265e9c-1' - Finished in state Completed(None)
12:19:00.470 | INFO    | Task run 'plot-f5265e9c-2' - Finished in state Completed(None)
```

**Comment by madkinsz** [comment]
If you set the level to DEBUG it'll include DEBUG level logs and higher which is all messages

**Comment by ahuang11** [comment]
Aha, I thought it mistaked it for the threshold! Thanks for the clarification.

**Comment by madkinsz** [comment]
> But then this also suppresses my personal calls too?

Yes, since you're using the Prefect task run / flow run loggers for your logs.

You could create your own logger and add it as an extra logger for shipping things to Orion. I'll try to think of a good way to make this easier.
