### ISSUE TITLE
prefect (re)create project fails

### ISSUE THREAD

**Issue by mgsnuno** [PrefectHQ/prefect#5668]
## Description

Create a previously deleted prefect project causes an error, both in UI, CLI and python.

```
prefect.exceptions.ClientError: [{'path': ['create_project'], 'message': 'Uniqueness violation.', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]
```

## Expected Behavior

Deleting and recreating a project should not create an error.

## Reproduction

- create a prefect project (UI/CLI/python)
- delete the project
- recreate the project (error)

**Comment by madkinsz** [comment]
We might be able to handle this case better. cc @zangell44
