### ISSUE TITLE
Make wait_for_flow_run task max duration configurable

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5669]
## Current behavior

`wait_for_flow_run` currently times out after 12 hours. This value is hardcoded in `watch_flow_run` [here](https://github.com/PrefectHQ/prefect/blob/40e2e2bd1c1de5651bc7fb484c823e43cfc69877/src/prefect/backend/flow_run.py#L95-L99). 

so for subflows greater than 12 hours, this task will exit unexpectedly

## Proposed behavior

Make it configurable by passing a value of max duration to `wait_for_flow_run`.

**Comment by gtasegerberg** [comment]
I brought this issue up, and have the code in place for the change. Will modify tests as needed and open a PR.
