### ISSUE TITLE
Remove Kubernetes flow_id label from job spun up by the agent

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5670]
## Current behavior

The Kubernetes agent adds 3 labels [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/agent/kubernetes/agent.py#L485-L489) for the jobs.

`flow_run_id` and `flow_identifier` are used to manage jobs but `flow_id` does not seem to be used. A user on Slack is saying they are trying to trim labels because they are hitting the maximum amount on Grafana.

## Proposed behavior

If the label is unused for Flow job management, we could look at removing it.

**Comment by madkinsz** [comment]
I'm hesitant to remove labels by default, perhaps we can include a way to customize which labels are added instead.
