### ISSUE TITLE
orion: support s3 compatible object stores like minio

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5686]
## Description

Support S3 compatible objects stores like MinIO. This would make remote storage usable in on-prem or sandbox environments without access to AWS S3.

I think this could be done by making [endpoint_url](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html) configurable on `S3StorageBlock`.

**Comment by tekumara** [comment]
Closing as a dupe of #5658

**Comment by madkinsz** [comment]
This is fully supported by the `FileStorageBlock` in the current version.

**Comment by chris-aeviator** [comment]
@madkinsz 
unfortunately not documented properly. When adding a `RemoteFileStorage` block, the UI presents me with a settings window which does not contain any more info other than a reference to fsspec.

Fsspec is using python dicts for configuration, whereas https://github.com/PrefectHQ/prefect/blob/4ebe727b89d78a0bb19d81878b104ddafc80382a/docs/concepts/filesystems.md#remotefilesystem-examples suggests to use JSON. Whatever I put into the settings window,  upon saving orion re-formats my setting to an escaped string.

**Comment by madkinsz** [comment]
@chris-aeviator perhaps you're looking for https://prefecthq.github.io/prefect-aws/s3/ ?

Can you open a separate issue for the string/dict formatting? That sounds like a UI bug.

**Comment by chris-aeviator** [comment]
right now I'm extremely short in time and the issue templates are asking for many things, I'll make a todo.

Thanks for the hint with prefect-aws, somehow the UI (pip install prefect version of today) doesn't show most of those options regarding minio or endpoint (guess second issue then)

**Comment by madkinsz** [comment]
Your local UI? Did you install `prefect-aws`?

**Comment by chris-aeviator** [comment]
I used the installed one - guess this is not `prefect-aws` then 

![grafik](https://user-images.githubusercontent.com/11522213/193849722-5aa0ff16-4aab-4b8d-99a9-c1e51b5995e7.png)
