### ISSUE TITLE
Allow class-based workflows and subclassing

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect#5689]
This feature request pertains to Prefect Orion and workflow generation

# Current behavior

The current behavior allows workflows to be generated via...
1. a context via `with Flow(...) as flow:`
2. a function decorator via `@flow`

Here is a simple example of `@flow` that I'll use to help outline this feature request:
``` python
@task
def say_hello(person):
    print(f"Hello, World! I'm {person}!")

@flow(name="Prefect 2.0 Flow")
def example_flow(person="Marvin"):
    say_hello(person)
```

If we wanted a complex task, we could subclass the `Task` class. However, we are unable to subclass the `Flow` class in a similar manner:
``` python
# This would NOT work
class ExampleFlow(Flow):

    def __init__(self, person, **kwargs):
        self.person = person
        super().__init__(**kwargs)

    def run(self, person):  # overwrites internal method and doesn't act as intended
        say_hello(person)
```

# Proposed behavior

Using the same example flow from above, I propose a process for subclassing `Flow`. Here, we do not specify a `run` method (as this is reserved for the core Flow api), but instead supply a `run_context` method that (when present) is used to initialize a flow context:

``` python
class ExampleFlow(Flow):
    
    def __init__(name="Prefect 2.0 Flow"):
        ...  # other user-based logic
        super().__init__(...)  # uses self.run_context to generate the workflow object (if set)
        
    def run(...):
        # reserved for the built-in method. should not be overwritten by user
        ...
    
    @defaults_from_attrs("person")
    def run_context(person):
        # The user defines their function here.
        say_hello(person)
```

# Example

## basic example

Here we can see extra logic applied when generating the workflow. This effectively creates a dynamic workflow -- this is a workflow where default values vary and/or tasks are dynamically created.

``` python
class ExampleFlow(Flow):
    
    def __init__(name="Prefect 2.0 Flow", person="Marvin"):
        self.person = person.upper()  # not very exciting, but shows we dynamically set default values
        ...  # other user-based logic
        super().__init__(...)  # uses self.run_context to generate the workflow object
        
    def run(...):
        # reserved for the built-in method. should not be overwritten by user
        ...
    
    @default_from_attribute
    def run_context(person):
        # The user defines their Flow here.
        self.example_dynamic_task(person)  # uses a dynamically created task!
        
    @property
    def example_dynamic_task(self):
        # Can have advanced logic that dynamically creates a Prefect Task class.
        # For now, I just return a static Task.
        return say_hello
```

## real-world example

In my own package, I dynamically create Prefect workflows! These workflows also have attributes to enable higher-level functionality. The full example can be found [here](https://github.com/jacksund/simmate/blob/5eaf30d21afc46ca38a7da59703ec7b505165769/src/simmate/workflow_engine/utilities.py). This approach works, but makes it very difficult for users/contributors to understand what I'm doing -- it's very unpythonic.

For example, after initializing my workflow, I need to dynamically set attributes:
``` python

task1 = ExampleTask(...)  # initializes a complex task

with Flow(...) as flow:
    x = Parameter(...)
    task1(...)  # uses dynamically-created task from above

# After the context, I need to set attributes manually.
# For things like docstrings, this is counter to typical python use.
flow.storage = ModuleStorage(module)
flow.__doc__ = "...." 
```

It'd be MUCH easier to do the following instead:

``` python
class DynamicFlow(Flow):
    """
    Normal docstring that can be overwritten when subclassing
    """
    # not shown: init and run_context methods defined as shown in the proposed behavior section

    @property
    def task_generator(...):  # includes logic used to generate dynamic task
          return ExampleTask(...)

    @property
    def storage(...):  # a fixed property that can be inherited / overwritten in subclasses
          return ModuleStorage(self.__module__) 
```

**Comment by jacksund** [comment]
As a temporary alternative, I'm trying out a class method to dynamically create workflows:

``` python
class DynamicFlow(Flow):
    """
    Normal docstring that can be overwritten when subclassing
    """
    
    def __init__(self, ...):
        ...
        super().init(...)    

    @property
    def task_generator(...):  # includes logic used to generate dynamic task
          return ExampleTask(...)

    @property
    def storage(...):  # a fixed property that can be inherited / overwritten in subclasses
          return ModuleStorage(self.__module__) 
     
    @classmethod
    def get_workflow(cls, ...):
        """ temporary alternative to init """
        @cls
        def dynamic_workflow():
            f"""{self.__doc__}"""  # inherit docstring
            self.task_generator()
        
        return dynamic_workflow

# don't use DynamicFlow() to init. Instead always use the method
workflow = DynamicFlow.get_workflow()
```

**Comment by jacksund** [comment]
Any thoughts from the core devs? No harm done if you think this is a bad idea lol.

**Comment by madkinsz** [comment]
I don't think we'll undertake such a large API change/addition for v1. For v2, I'm not sure if this applies in the same way. I'm generally hesitant to include first-class support for class based tasks/flows because it can create some unrealistic expectations around statefulness.

**Comment by madkinsz** [comment]
> I'm proposing this for v2

Some of these examples don't quite make sense for v2 since flows are decorated functions and not defined with a context anymore. I'm curious to see how your dynamic workflow process changes with v2 :)

> v2 is going to continue to allow class-based tasks though

Not currently. I'm sure someone will use classes in a way we do not expect, but we intend for decorated functions to be the primary way to define tasks. One of the major reasons a class is used in v1 is to allow the parameters to be set before runtime, and we'll have a simple API for doing that without classes in v2.

**Comment by jacksund** [comment]
> v2 since flows are decorated functions

Yeah, I was shooting for flows as a decorated method by default, but it's probably too obtuse.

> Not currently. 

oh man... my entire package is based on [an abstract base Task](https://github.com/jacksund/simmate/blob/ab880d33516e886bf232c699ed1b1a623279ee19/src/simmate/workflow_engine/supervised_staged_shell_task.py). I'll find some way to get v2 working though :sweat_smile: 

Anyways, thanks for reading through and giving your thoughts!
