### ISSUE TITLE
Browser refresh after navigation causes not found error

### ISSUE THREAD

**Issue by zyzil** [PrefectHQ/prefect#5719]
## Description

Refreshing the browser after navigating to Flows, Work Queues, or Settings causes a "Not found" error.

## Reproduction / Example
Prefect Orion version: 2.0b3
Reproduced in Google Chrome, Chromium, and Firefox

1. Start Orion with `prefect orion start`
2. Navigate to `localhost:4200`
3. Navigate on `Flows`, `Work Queues`, or `Settings` on the left side-bar
4. Refresh the page with the browser
5. Observe the error `{"detail":"Not Found"}`

![prefect_orion_not_found_on_reload](https://user-images.githubusercontent.com/3661304/165435886-539a5d66-1414-4584-b0df-ae6d93a4d487.gif)

## Expected Behavior
Page should refresh without errors

**Comment by zhen0** [comment]
Thanks Zyzil.  On our latest version I can't replicate.  Can you try again after our latest release and let us know if you still have issues?  Thanks!

https://user-images.githubusercontent.com/40272060/167919908-ba426527-21e1-40c0-80aa-5fe4af76d92b.mov

**Comment by zyzil** [comment]
@zhen0 - I just gave it a try with the latest Orion code and I believe the problem is related to how the UI is built for distribution. If I setup everything for dev with `prefect dev` which exposes the UI on port `3000` then it appears to work. However, if I build the ui with `prefect dev build-ui` and then start the ui with `prefect orion start` which exposes port `4200` I can reproduce the error on browser refresh.

**Comment by zhen0** [comment]
Ah - thanks for the extra detail @zyzil - we'll take a look.

**Comment by dylanbhughes** [comment]
@zhen0 I believe this is no longer relevant after the redesign

**Comment by zhen0** [comment]
Actually I think think it is still relevant and that @znicholasbrown is looking into it in https://github.com/PrefectHQ/orion/issues/2002

**Comment by phildum** [comment]
I'm seeing this exact issues on a fresh install of 2.0b7 on k8s using the official helm chart. Tried both firefox and edge and same on both.

**Comment by andreas-ntonas** [comment]
I confirm that I am also experiencing this in 2.0b8

**Comment by zhen0** [comment]
Removing the high label only because this is being tracked in https://github.com/PrefectHQ/orion/issues/2002 and I don't want to have duplicate tickets. Still a high priority.

**Comment by znicholasbrown** [comment]
This should be fixed in the next release 👍🏻

**Comment by sm-Fifteen** [comment]
> Removing the high label only because this is being tracked in https://github.com/PrefectHQ/orion/issues/2002 and I don't want to have duplicate tickets. Still a high priority.

I'm getting 404 errors from that link, is the orion repository supposed to be private?
