### ISSUE TITLE
UI won't display on Firefox

### ISSUE THREAD

**Issue by dylanmcreynolds** [PrefectHQ/prefect#5733]
## Description (edit, hist comment too quickly)
I am running on a fresh install of orion in a brand new conda environment.

When I run in Chromium, I see the web page.

When I run in Firefox, the page stays blank and throws some javascript errors:

```Exception { name: "NS_ERROR_STORAGE_CONSTRAINT", message: "", result: 2153971715, filename: "http://localhost:4200/assets/index.af9a7d5e.js", lineNumber: 14, columnNumber: 0, data: null, stack: "Iv@http://localhost:4200/assets/index.af9a7d5e.js:14:27915\n@http://localhost:4200/assets/index.af9a7d5e.js:14:27852\n" }
[index.af9a7d5e.js:14:27971](http://localhost:4200/assets/index.af9a7d5e.js)
Uncaught 
Exception { name: "NS_ERROR_STORAGE_CONSTRAINT", message: "", result: 2153971715, filename: "http://localhost:4200/assets/index.af9a7d5e.js", lineNumber: 22, columnNumber: 0, data: null, stack: "@http://localhost:4200/assets/index.af9a7d5e.js:22:70471\n" } 
```

and

```
Error during service worker registration: Error: Service worker not found at /service-worker.js
```

In both cases, there is a 404 when loading server-worker.js

Here are my settings:

```
Version:             2.0b3
API version:         0.3.0
Python version:      3.9.12
Git commit:          58a401bc
Built:               Wed, Apr 13, 2022 11:21 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.38.2
```

When I open the ui at http://127.0.01:4200 in Firefox

**Comment by zhen0** [comment]
Hey @dylanmcreynolds I can't replicate on firefox 98.0.2 (64-bit).  The service worker error is one I also see but I do not think is related to your issue.  Have you tried clearing local storage?

**Comment by dylanmcreynolds** [comment]
@zhen0 Interesting. I cleared all the storage and cookies for the orion site, same error. However, when I open in a private window, the UI paints.

**Comment by dylanmcreynolds** [comment]
Oh, and clearing the cache for this host worked in a regular window. No more error, and it paints. 

There is still the error about service-worker.js and the corresponding error in the console:

**Comment by dylanmcreynolds** [comment]
Sure, but I will point out that in both browsers, I refreshing the page provides a 404 error trying to get `service-worker.js`

**Comment by dylanbhughes** [comment]
We need to verify this is still happening after the UI redesign

**Comment by dylanmcreynolds** [comment]
@dylanbhughes  I just upgraded to 2.0b6, and yes, the 404 for service-worker.js is still happening.

**Comment by zhen0** [comment]
Thanks @dylanmcreynolds for the update.  To keep things neat (since this has a different title etc) and so the team don't get confused by duplicates, I'm going to close this in favor of https://github.com/PrefectHQ/prefect/issues/5719 which covers the browser refresh issue

**Comment by dylanmcreynolds** [comment]
@zhen0 this is getting complex, but the service-worker.js 404 issue is still happening, and is not covered in #5719
