### ISSUE TITLE
[Orion] Parameters Incorrectly appear as "--" in Flow Run Deployments

### ISSUE THREAD

**Issue by ColeMurray** [PrefectHQ/prefect#5742]
## Description

When viewing parameters for given deployment, parameters are not properly displayed and appear to show "--"
When inspecting the network, the object does appear to have the parameters, but is not being injected into the view correctly.

The DeploymentPanel component appears to be closed-source, so it is not clear where the misbind is occurring.

![Screen Shot 2022-05-02 at 11 38 23 PM](https://user-images.githubusercontent.com/2492022/166413376-936b37d7-c3b2-4aae-a670-e8fb185341ff.png)

## Expected Behavior

Parameters to be visualized.

## Reproduction

```
from prefect import flow
from prefect.flow_runners import SubprocessFlowRunner
from prefect.orion.schemas.schedules import CronSchedule

@flow
def hello_world(name="world", taco='del'):
    print(f"Hello {name} {taco}!")

from prefect.deployments import DeploymentSpec


for i in range(2):
    DeploymentSpec(
        flow=hello_world,
        name="hello-world-daily-{}".format(i),
        parameters={ 'taco': 'bell{}'.format(i)},
        flow_runner=SubprocessFlowRunner(),
        schedule=CronSchedule(cron="0 0 * * *")
    )
```

## Environment

`prefect diagnostics` appears no longer working in 2.0

```
Usage: prefect [OPTIONS] COMMAND [ARGS]...
Try 'prefect --help' for help.

Error: No such command 'diagnostics'.
```

**Comment by zhen0** [comment]
This should be fixed in the new UI - please let us know if your parameters still aren't displayed.

**Comment by ColeMurray** [comment]
Confirming issue is resolved. Thanks team!
