### ISSUE TITLE
Request: Warning for mismatch between backend and API

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5747]
## Current behavior

It's very hard to debug when the backend is set to Server but the endpoint is pointed to `api.prefect.io`. There is a bunch of weirdness. For example, flows will be picked up by agents and executed, but secrets will only pull locally because `Secrets` only pull locally for Server.

## Proposed behavior

The proposal is to check two configurations:

PREFECT__BACKEND = "server"
PREFECT__SERVER__ENDPOINT = "api.prefect.io"

And raise a warning on agent start or flow start if it's configured like this. It's not a configuration that makes sense in any scenario and leads to behavior incredibly hard to debug.

**Comment by madkinsz** [comment]
The `Client` can throw a warning on initialization in this case.

**Comment by cicdw** [comment]
Closing as stale and because Prefect 1.x is no longer under active development.
