### ISSUE TITLE
Navigate from single flow run back to all flow runs

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5758]
## Description

I'd like to be able to navigate from a single flow run back to a page with all the flow runs, as is currently possible in prefect 1 by clicking on the flow name at the top of the flow run page. 

## Reproduction / Example

For example, clicking here could navigate back to a page for all of the `main-flow` flow runs (and other flow details).

<img width="1152" alt="Screen Shot 2022-05-07 at 11 12 13 pm" src="https://user-images.githubusercontent.com/125105/167256050-a15c7ae3-dcd3-401e-9cbb-d5fb43eb73e1.png">

**Comment by zhen0** [comment]
Thanks for the suggestion @tekumara

**Comment by dylanbhughes** [comment]
@zhen0 with the redesign I think this is no longer relevant. Agree?

**Comment by pleek91** [comment]
@dylanbhughes @zhen0 i think we can close this.
