### ISSUE TITLE
No parameter named "wait_for"

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5762]
## Description

When using `wait_for` vscode and pyright produce the type error:
```
17:7 - error: No parameter named "wait_for" (reportGeneralTypeIssues)
```
<img width="564" alt="Screen Shot 2022-05-08 at 4 00 11 pm" src="https://user-images.githubusercontent.com/125105/167283921-88d8a4b3-9ec9-4f1e-a647-b2e4e1b81890.png">

## Reproduction / Example

```python
from prefect import flow, task


@task
def a() -> None:
    ...


@task
def b() -> None:
    ...


@flow
def flowy() -> None:
    a_future = a()
    b(wait_for=[a_future])


if __name__ == "__main__":
    flowy()
```

prefect 2.0b3

**Comment by madkinsz** [comment]
Unfortunately [PEP 612 opted not to include support for concatenation of keyword arguments](https://peps.python.org/pep-0612/#concatenating-keyword-parameters). Consequently, we cannot support type-checking for your function _and_ our own keyword arguments here. We considered changing the specification of settings like `wait_for` to avoid this issue, but the convenience of the current interface is really nice. Considering mypy doesn't support _any_ of PEP 612, our type suggestions here will likely be "best effort" for the foreseeable future.
