### ISSUE TITLE
Runs do not show up on the cloud

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#5767]
## Description

1. I followed the tutorial and did the setup for prefect 1.2.1
2. I logged in with prefect auth login --key mykey
3.  I ran the example with python3 example.py
4. The Flow does not show up in the cloud

Auth status confirms that i am logged in.

How can i fix this?

**_example.py_**
```python
import prefect
from prefect import task, Flow


@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Hello world!")


with Flow("hello-flow") as flow:
    hello_task()

flow.run()
```

## Expected Behavior
The run shows up on the cloud

## Reproduction
install prefect login run example

## Environment
m1 mac
[poetry.lock.zip](https://github.com/PrefectHQ/prefect/files/8654991/poetry.lock.zip)

**Comment by kvnkho** [comment]
Hey @felix-ht,

`flow.run()` is for local testing and really does not appear on Prefect Cloud. To register and deploy a Flow after local testing, check [this part of the tutorial](https://docs.prefect.io/orchestration/getting-started/quick-start.html). There is a step-by-step guide to run a Flow against Prefect Cloud

**Comment by felix-ht** [comment]
Thanks that worked!

I had tried this tutorial:

https://orion-docs.prefect.io/ui/cloud/#run-a-flow-with-prefect-cloud

but the interface that exposed with 1.2.1 didn't expose the required functions. I also tried 2.0 but with that the authentication failed.

In general the Documentation is quite confusing as most of the code snippets did not work - as they where for an other version.
