### ISSUE TITLE
`prefect register` bumps up the flow version when there are no code changes

### ISSUE THREAD

**Issue by carpetmaker** [PrefectHQ/prefect#5777]
## Description

In some cases, `prefect register` command does not work as intended.
It is a direct side-effect of #5776 

## Expected Behavior

`prefect register` should only increment flow version when the flow code changes

## Actual Behavior

`prefect register` increments flow version on each run

## Reproduction

See #5776 

## Proposed solution

See #5776 

## Environment

Versions (irrelevant for this issue):
- prefect version: 1.2.1
- python version: 3.8.x
- platform: darwin

**Comment by tirkarthi** [comment]
@madkinsz I guess this also can be closed with https://github.com/PrefectHQ/prefect/pull/5785 since the serialisation is deterministic and the hash of the serialized value should be too.
