### ISSUE TITLE
Putting tasks in a list produces a phantom `List` task that complicates the DAG and confuses logging 

### ISSUE THREAD

**Issue by multimeric** [PrefectHQ/prefect#5801]
## Description
Whenever you use the expression `[a]` in a `Flow`, where `a` is some task, prefect sees this as a new task called `List`.

## Expected Behavior
I expect the list call to be ignored by Prefect. It's not actually a task, because it wasn't defined using the `Task` class or `@task` decorator. It doesn't even operate on task data. As mentioned, I feel that this makes the logging confusing, because it adds a significant amount of `List` tasks that run and succeed instantly, even though the user doesn't care about these at all. As you will see below, it also complicates the DAG visualizations.

I'm actually curious what is even causing this behaviour, because I can't work out how an object (`Task`) would even know when it's being put in a list. If I were calling `list(task)` that would be one thing, because it would call `__iter__()` on the task, but `[task]` isn't doing that. I'm truly perplexed.

## Reproduction
```python
@prefect.task
def foo(x):
    return x

@prefect.task
def bar(x):
    return len(y)

with prefect.Flow() as flow:
    a = foo(1)
    b = foo(2)
    c = foo(3)
    d = bar([a,b,c])

flow.run()
```

Outputs:
```
[2022-05-18 13:05:23+1000] INFO - prefect.FlowRunner | Beginning Flow run for 'flow'
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Starting task run...
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Finished task run for task with final state: 'Success'
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Starting task run...
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Finished task run for task with final state: 'Success'
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Starting task run...
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'foo': Finished task run for task with final state: 'Success'
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'List': Starting task run...
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'List': Finished task run for task with final state: 'Success'
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'bar': Starting task run...
[2022-05-18 13:05:23+1000] INFO - prefect.TaskRunner | Task 'bar': Finished task run for task with final state: 'Success'
[2022-05-18 13:05:23+1000] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```

Also, calling `flow.visualize()` results in:

![graph](https://user-images.githubusercontent.com/5019367/168949447-c30490b6-a61e-4928-832a-0122a76874e2.png)

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.11.0-49-generic-x86_64-with-glibc2.33",
    "prefect_backend": "cloud",
    "prefect_version": "1.2.1",
    "python_version": "3.9.0"
  }
}
```

**Comment by cicdw** [comment]
Hi @multimeric - this is a great question and before I explain what's happening here I want to emphasize that we also are not enthusiastic about this behavior.  Originally we wanted Prefect to manage the complete graph of task manipulations, but as you are encountering it's not ideal in practice.  For that reason we are removing this sort of task auto-generation in Prefect 2.x.

With all of that said, here is how that phantom task is generated:
- when you call a task, that binds task dependencies within the flow, i.e. an edge is added to your flow
- edges require that their upstream and downstream references are tasks, so in the case of a `list` Prefect decides to inject this new task to keep the edge pure
- anytime Prefect needs to convert something to a task, the `as_task` function is called which ultimately lands you at [these lines](https://github.com/PrefectHQ/prefect/blob/d0ece591c713840af8873b60e9d14a34628c57f9/src/prefect/utilities/tasks.py#L273-L274) that do additional binding (and consequently creates the edges between the list and its individual elements)

As you can see in that function, the same is true for dictionaries and other Python collections.  So its not the task that knows it's being put in a list, it's the downstream task `bar` that has been provided a list as an input and triggers additional manipulation.

Hope that helps!

**Comment by multimeric** [comment]
> edges require that their upstream and downstream references are tasks

Right I think this is the key thing here. It makes perfect sense but it didn't occur to me. Honestly I think the behaviour of converting my list of tasks to a task returning a list of values is fine, I just kind of wish it were hidden from me, because like I said, it's confusing my monitoring.

I wonder, if you aren't doing this in 2.X, whether it will still be possible to do this kind of thing (putting tasks into a list etc).

**Comment by madkinsz** [comment]
>  I wonder, if you aren't doing this in 2.X, whether it will still be possible to do this kind of thing (putting tasks into a list etc).

Yep! In 2.0 we actually crawl all built-in collection types and resolve any upstream task futures into values. This means that you can include upstream tasks in sets, dictionaries, lists, tuples, and dataclasses in the parameters to downstream tasks or flows and we will track the dependency and ensure your function receives the result. We've also included support for Pydantic models since we use them heavily.

**Comment by multimeric** [comment]
That sounds like ideal behaviour! It would be great to have a "Changelog for Prefect 1.x Users" to browse through for stuff like that.
