### ISSUE TITLE
ValueError: 'sens-o-matic.prefect.io' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by ashitabh** [PrefectHQ/prefect#5807]
When I run 
prefect orion start
I get the following error 
ValueError: 'sens-o-matic.prefect.io' does not appear to be an IPv4 or IPv6 address

Can I disable this remote 'sens-o-matic.prefect.io ?

**Comment by madkinsz** [comment]
You can set `PREFECT_ORION_ANALYTICS_ENABLED=0` or run `prefect orion start --analytics-off`

**Comment by dylanbhughes** [comment]
@ashitabh does your Prefect instance have access to the public internet?

**Comment by ashitabh** [comment]
No, it's behind Corporate firewall


 
  On Fri, 20 May 2022 at 20:08, Dylan ***@***.***> wrote:   


@ashitabh does your Prefect instance have access to the public internet?

**Comment by ashitabh** [comment]
This worked for me
prefect orion start --analytics-off

**Comment by ashitabh** [comment]
Thanks
