### ISSUE TITLE
`prefect agent kubernetes install` still creates deprecated/removed `IMAGE_PULL_POLICY` env var

### ISSUE THREAD

**Issue by martin-schulze-e2m** [PrefectHQ/prefect#5808]
## Description
When creating a new k8s deployment manifest via `prefect agent kubernetes install`, the environment variable `IMAGE_PULL_POLICY` is still generated although it has been removed in #5072.
This is due to the template https://github.com/PrefectHQ/prefect/blob/d0ece591c713840af8873b60e9d14a34628c57f9/src/prefect/agent/kubernetes/deployment.yaml#L44 still containing this entry which is even populated via the `--image-pull-policy` flag by https://github.com/PrefectHQ/prefect/blob/d0ece591c713840af8873b60e9d14a34628c57f9/src/prefect/agent/kubernetes/agent.py#L712

I spent a lot of  time trying to find out, why the imagePullPolicy was not picked up on my jobs. I'd recommend looking for other variables that might be deprecated/removed and are still generated.

## Expected Behavior

Since this environment variable is ignored by the agent, it should not be generated anymore.

## Reproduction
Run `prefect agent kubernetes install` and look for `-name: IMAGE_PULL_POLICY` in the output.

**Comment by desertaxle** [comment]
Closing because this issue pertains to the legacy version of Prefect, which is no longer under active development.
