### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by ashitabh** [PrefectHQ/prefect#5812]
Getting the following error "socket.gaierror: [Errno -3] Temporary failure in name resolution" 

for sample code 
import prefect
from prefect import flow, task
from typing import List
import httpx

@task(retries=3)
def get_stars(repo: str):
    url = f"https://api.github.com/repos/{repo}"
    count = httpx.get(url).json()["stargazers_count"]
    print(f"{repo} has {count} stars!")

@flow(name="GitHub Stars")
def github_stars(repos: List[str]):
    for repo in repos:
        get_stars(repo)

# run the flow!
github_stars(["PrefectHQ/Prefect", "PrefectHQ/miter-design"])

**Comment by tirkarthi** [comment]
This looks like a network issue while using `httpx.get` than an issue with prefect.

**Comment by ashitabh** [comment]
Looks like telemetry to prefect cloud . How can I disable it in code ? The sample code is already added to this issue
 
 
  On Fri, 20 May 2022 at 17:11, Karthikeyan ***@***.***> wrote:   


This looks like a network issue while using httpx.get than an issue with prefect.

**Comment by tirkarthi** [comment]
telemetry seems to be enabled only for server : https://docs.prefect.io/orchestration/server/telemetry.html

**Comment by madkinsz** [comment]
Can you please share the full traceback and the output of `prefect version`? Make sure to put these in markdown code blocks for readability.

**Comment by ashitabh** [comment]
(base) ashitabh@IBMWL21L00335:/mnt/c/Ashitabh/Code/wsl$ prefect version
Version:             2.0b5
API version:         0.3.1
Python version:      3.9.7
Git commit:          7b27c7cf
Built:               Tue, May 17, 2022 4:54 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted

**Comment by ashitabh** [comment]
Ok, my corporate firewall is blocking this httpx
