### ISSUE TITLE
Compatibility issue with cloudpickle

### ISSUE THREAD

**Issue by cybermatt** [PrefectHQ/prefect#5818]
## Description
When building the Docker image on 20th step (`RUN python /opt/prefect/healthcheck.py`) I see the same traceback:

`
Traceback (most recent call last):
  File "/opt/prefect/healthcheck.py", line 152, in <module>
    flows = cloudpickle_deserialization_check(flow_file_paths)
  File "/opt/prefect/healthcheck.py", line 44, in cloudpickle_deserialization_check
    flows.append(cloudpickle.loads(flow_bytes))
AttributeError: Can't get attribute '_make_function' on <module 'cloudpickle.cloudpickle' from '/usr/local/lib/python3.9/site-packages/cloudpickle/cloudpickle.py'>
`

Cloudpickle version 2.10 was released on May, 20: https://pypi.org/project/cloudpickle/#history

## Expected Behavior
Successful build 

## Possible solution:
Fix 2.0.0 version of the сloudpickle library in the requirements file (https://github.com/PrefectHQ/prefect/blob/master/requirements.txt#L2) to disable automatic upgrade.

## Environment
Prefect version = 0.15.12

**Comment by kvnkho** [comment]
Hello, see this thread: https://discourse.prefect.io/t/cloudpickle-version-mismatch-causing-errors/938

Basically the version of cloudpickle does not match the version inside the base image.
