### ISSUE TITLE
Visualize task graphs using ipycytoscape

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#5822]
Inspired by https://github.com/dask/dask/pull/9091; the same reasons given there make sense to me here as well:
>1. The ability to run in pyodide without compiling graphviz to WASM (cf. https://github.com/dask/dask/pull/9053)
>2. More interactivity, especially with different coloring schemes and layouts.
>3. The possibility to add richer tooltips/popups (cf. https://github.com/dask/dask/issues/9069)

I actually don't know if Orion has a `.visualize` implementation yet, could be easier to add it there if starting from scratch?

**Comment by bnaul** [comment]
Yeah it seems like a whole lot of work *unless* you can hijack the existing dask visualize functionality somehow, which seems doable to me...?

> Since the flow is discovered dynamically 

I know this is true in the general case but it seems like there are still cases where the flow is all declared statically, right? I know at least I can't easily break out of the DAG mindset so even my Orion flows still have all their tasks declared up front. So maybe "visualize whatever you already know about" would at least partly cover both cases?

**Comment by zareami10** [comment]
I would also find this very useful.

Also see the [Kedro case](https://demo.kedro.org/) for a very well done example.

**Comment by felix-ht** [comment]
I love this idea as well. 

It would even be better to have it integrated into orion (with https://js.cytoscape.org/) - i **really** dislike the current radar view.
