### ISSUE TITLE
The agent is always in the submit state

### ISSUE THREAD

**Issue by duxiaoyu555** [PrefectHQ/prefect#5858]
## Description

The agent is always in the submit state
![image](https://user-images.githubusercontent.com/90017789/171410397-3ab3741e-0bc7-4f08-a53c-10cc02b1b48d.png)

and we can generate job 
![image](https://user-images.githubusercontent.com/90017789/171410469-1c7d13f3-c9ef-43cc-9118-a63b5de2930c.png)
but we cannot generate pods

**Comment by madkinsz** [comment]
Hi! Can you share a description of the job? We'll need more details from your Kubernetes cluster about why the job isn't creating pods.
