### ISSUE TITLE
Add error messages when searching for flow tags that don't exist rather than returning to the homepage

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5863]
[**View in #prefect-ui on Slack**](https://slack.com/archives/C0192RWGJQH/p1654094352767999)

![Tim_Helfensdörfer] **@Tim_Helfensdörfer:** Hi, when filtering the Flows in Prefect 2 by tag and the tag doesn't exist, I get the "empty flow" view without any possibility to remove the filter. I have to reload the page again.

![Anna_Geller] **@Anna_Geller:** is it when using Cloud 2.0 or a specific Orion version?
if a specific version, it would help if you can share `prefect diagnostics` - asking to collect more info before creating an issue

![Tim_Helfensdörfer] **@Tim_Helfensdörfer:** Cloud. 

![Anna_Geller] **@Anna_Geller:** thanks - this is weird and I couldn't replicate - trying to look for Flows with the tag "prefect" of which I have none - can you explain a bit more where exactly do you see the issue here so that I can create a GitHub issue?

![Tim_Helfensdörfer] **@Tim_Helfensdörfer:** Sure, this is the tag search on the right, not the name search on the left. I will send you a quick screencast via dm because it contains senstive data.
While we are at it:
![image](https://user-images.githubusercontent.com/86264395/171491023-074e5c04-40f1-4c77-ac1e-94351109d18e.png)

![image](https://user-images.githubusercontent.com/86264395/171491052-9775769e-b945-4e93-b0ef-70fec1b21178.png)

[Tim_Helfensdörfer]: https://avatars.slack-edge.com/2022-04-14/3384446280198_7facbd7bc0203cdae1b1_24.jpg
[Anna_Geller]: https://avatars.slack-edge.com/2022-05-01/3466755334708_dc6796b776c6f927b8f8_24.jpg

**Comment by thelfensdrfer** [comment]
![image](https://user-images.githubusercontent.com/699106/171990369-ba4bffa5-e9f6-403b-8801-50ce0e73aa21.jpeg)

Can you please delete the video?
