### ISSUE TITLE
The command `prefect cloud login -k API_KEY -w workspace_name` doesn't work unless selecting workspace interactively

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5869]
## Description
For CI/CD pipelines, users need to be able to automatically select a workspace programmatically

## Problem
The current command returns: "Workspace X not found" because it needs to be first authenticated to browse through workspaces
![image](https://user-images.githubusercontent.com/86264395/171773281-066936fa-f592-4073-b302-b70faf40dac4.png)

Same on main:
![image](https://user-images.githubusercontent.com/86264395/171773325-2141a50d-b4c3-468a-82f4-b472182e0392.png)

**Comment by zangell44** [comment]
@anna-geller does this work if you specify `-w annaprefect/prod` instead of just `-w prod`?

The workspace handle on its own is not unique, only within an account.

**Comment by anna-geller** [comment]
Thank you so much! Works like a charm
