### ISSUE TITLE
Feature Request: PrefectFuture object does not support item assignment

### ISSUE THREAD

**Issue by sdittmar** [PrefectHQ/prefect#5873]
## Description

While testing Prefect 2.0b5 I have been running into an issue that I would not have running similar code in Jupyter. When adding an additional column to a Pandas data frame in the flow I get the following error:

TypeError: 'PrefectFuture' object does not support item assignment

Not sure if there is a bug or if this would be an added feature. Traceback is added at the very end.

Please be nice, this is my first-ever report... Let me know if there is something else I am missing and how to fix the problem in that case.

## Reproduction / Example

```
from prefect.deployments import DeploymentSpec
from prefect.task_runners import SequentialTaskRunner
from prefect.flow_runners import SubprocessFlowRunner
from prefect import flow, task
import pandas as pd


@task(name='MyTask')
def MyTask():
    
    df = pd.DataFrame(data=[['Alex',10],['Bob',12],['Clarke',13]],columns=['Name','Age'])
    
    return df

@flow(name='MyFlow')
def MyFlow():

    df = MyTask()
    df['region'] = 'EU'


DeploymentSpec(
    flow=MyFlow,
    flow_runner=SubprocessFlowRunner(),
    name="Test",
    tags=["Test"],
)
```

## Traceback

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 468, in orchestrate_flow_run
    result = await run_sync_in_worker_thread(flow_call)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 54, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/tmp/flow-script-MyFlows85zby61.py", line 23, in MyFlow

**Comment by kvnkho** [comment]
I think this is not a bug because that's really how futures work. This is true across other libraries that have Futures interfaces like Dask. The object is not a Python object until the operation is completed. If you need to do such an operation, you can always call `.result()` on the task to make it a Pandas DataFrame in this case.

For example,
```python
@flow(name='MyFlow')
def MyFlow():

    df = MyTask().result()
    df['region'] = 'EU'
```

And the same is true for all tasks. You can also put the assignment logic in a Task. The assignment operation is not possible until it becomes a Python object with the respective methods.

**Comment by sdittmar** [comment]
That makes complete sense! Thank you for your response.

Because Prefect is a tool that will likely attract many junior data scientists (because it is so good and easy to use) it could be worthwhile to leave a note in the Flow section of the manual pointing to the use of Futures and the .result() method.
