### ISSUE TITLE
Shut down PowerShell session to release server port

### ISSUE THREAD

**Issue by tpdorsey** [PrefectHQ/prefect#5880]
## Description

With 2.0b6, prefect server instance does not release port when shut down.

## Reproduction / Example

When running a Prefect server instance on Windows 10 in PowerShell:

- With 2.0b6
- If you stop the server with Ctrl-C, the port is not released 
- If you try to start a new server instance, it fails 
- You must close the PowerShell console instance (or tab in Windows Terminal) and launch another server instance in a new PowerShell console.

**Comment by sm-Fifteen** [comment]
I'm not using PowerShell, but I'm getting a similar problem with git bash on Windows. The uvicorn subprocess is not shut down when closing `prefect orion start` using Ctrl-C (on beta 13) and will prevent the Orion server from being re-launched.

**Comment by sm-Fifteen** [comment]
Actually, I'd be curious to know why the prefect orion CLI starts up the uvicorn server by running it as a subprocess command instread of spinning up an event loop and setting up uvicorn as a python module to run in that loop? I don't think it would work any differently and would avoid dealing with this kind of subprocess management. This is pretty much what [uvicorn's CLI interface](https://github.com/encode/uvicorn/blob/master/uvicorn/main.py) does anyway.

**Comment by barskern** [comment]
I've also encoutered this issue on Windows. For me the process doesn't stop after the first `ctrl-c` sent, however `Stopping Orion...` is logged. Hence it seems as though it's trying to shutdown but not following through. I'm running version 2.2.0.

**Comment by barskern** [comment]
Based on reading the code a bit and doing some light research, I think the issue might be a lack of SIGTERM on Windows. The following code is used to shut down the process, while I found the following article regarding SIGTERM on Windows.

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/orion.py#L149-L152

https://maruel.ca/post/python_windows_signal/

I don't know where to go further here to be honest, but I figured this might be a help if someone feels like attacking this issue.

**Comment by bunchesofdonald** [comment]
That's really helpful... also frustrating. Thanks for that research @barskern! The SIGTERM logic was added as a response to a bunch of anyio 'errors' traces being output to the terminal when doing a CTRL-C. But given the apparent lack of support for SIGTERM, that might be better behavior for windows.
