### ISSUE TITLE
Add a CLI feature to delete storage blocks 

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5889]
## Description
Currently, it's very easy to create new storage blocks e.g. via CLI command `prefect storage create` or via Deployments. But this may lead to a lot of storage configurations as shown in this image:

![image](https://user-images.githubusercontent.com/86264395/172960167-3d12a0a8-2c44-4ec1-941f-1c65899e82c8.png)

It would be great to have a command:

```
prefect storage delete UUID
```

**Comment by madkinsz** [comment]
I believe we'll want to implement this as a `prefect block delete <uuid>` command but I have no clue what our plans are for a blocks CLI

**Comment by anna-geller** [comment]
Makes sense. I thought "prefect storage delete" would be intuitive given that there is already:
- prefect storage create
- prefect storage ls
- prefect storage set-default

**Comment by mkarbo** [comment]
+1 for storage delete functionality
