### ISSUE TITLE
Snowflake ImportError raises NameError

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#5901]
## Description
When importing SnowFlake tasks without having the snowflake extras installed, an ImportError should be raised. However, it is supposed to be raised from "err", which is not defined. This causes a NameError.

## Expected Behavior
Only the ImportError to be raised

```python
try:
    from prefect.tasks.snowflake.snowflake import (
        SnowflakeQuery,
        SnowflakeQueriesFromFile,
    )
except ImportError:
    raise ImportError(
        'Using `prefect.tasks.snowflake` requires Prefect to be installed with the "snowflake" extra.'
    ) from err
```
The err variable was removed in this commit: https://github.com/PrefectHQ/prefect/commit/c72096215cf2002e68f8bcdd5a5fa7896d5c1a3b

## Environment
Prefect 1.2.2

**Comment by kvnkho** [comment]
Thanks for the write-up! Should be fixed when this https://github.com/PrefectHQ/prefect/pull/5846 gets merged.
