### ISSUE TITLE
Enable migration from jenkins (pipeline support or migration script?)

### ISSUE THREAD

**Issue by MattMacGillivray** [PrefectHQ/prefect#5911]
## Current behavior

As a current jenkins user, I am heavily invested in the platform and would have to rewrite my 200+ jobs to migrate to prefect.

## Proposed behavior

Support basic jenkins pipeline syntax, or create a script that would translate a pipeline to prefect compatible jobs.

**Comment by qmnonic** [comment]
Migrating an existing base of users from Jenkins to prefect would be a quick win for you - they are all using a job engine, but just can't figure out how to get to prefect.

**Comment by malcojus** [comment]
+1, this is a must have for users such as us who are heavily reliant on Jenkins.

**Comment by madkinsz** [comment]
Hi! It seems unlikely that this is something we can pursue in the Prefect core library. It'd probably be better implemented in a Prefect collection or extension.

It'd be a helpful first step if you could share some examples of simple Jenkins jobs that you'd like to have automatically ported to Prefect.

**Comment by MattMacGillivray** [comment]
Huge opportunity lost here.
