### ISSUE TITLE
2.0b6 refresh browser routing issue

### ISSUE THREAD

**Issue by dylanmcreynolds** [PrefectHQ/prefect#5914]
## Description
In a fresh install of 2.0b6, navigating to `http://127.0.0.1:4200` opens the browser app. This instantly change the URL in the address bar to `http://127.0.0.1:4200/runs`. If I refresh the browser at that point, the browser requests `/runs` from the server, returning a `404`. 

The same is true for other routes like `/flows`, `/deployments`, and `/work-queues`.

Tested on Firefox/Linux

## Reproduction / Example

1. Open `http://127.0.0.1:4200` -> Observe the browser loads the app
2. Click `Refresh` -> Observe the browser displays `{"detail":"Not Found"}` and in the network tab of the dev tools, the response was `404`

**Comment by madkinsz** [comment]
Thanks for the report, this is a known issue that we are hoping to resolve.

**Comment by zhen0** [comment]
I believe this is a duplicate of https://github.com/PrefectHQ/prefect/issues/5719?

**Comment by dylanmcreynolds** [comment]
Sorry, I searched but missed that one. Closing.
