### ISSUE TITLE
 reload button -> json page instead of the UI in prefect 2.0

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#5915]
## Description

Reloading any non-root page in firefox (ex: http://127.0.0.1:4200/runs) returns a json page, not the UI.

## Expected Behavior

I would expect to get the UI, as any normal reload

## Environment

prefect 2.0b6
firefox

**Comment by zhen0** [comment]
Thanks for reporting this. It's already tracked in #5719 and we're looking into it.

**Comment by zhen0** [comment]
Should be fixed in the next release - see #5719 for details.
