### ISSUE TITLE
refresh of in flow run reset the page scroll in prefect 2.0b6

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#5916]
## Description

flow run page (http://127.0.0.1:4200/flow-run/) is refreshed every ~2s which is ok, but unfortunately it resets the scroll (in firefox). It is impossible to inspect the end of long logs.

## Reproduction / Example

Start a flow producing a long log (more than a screen page) and try to inspect the messages at the end. After a couple of seconds the page is reset to the beginning of the page

**Comment by pleek91** [comment]
@ghislainp I believe this was fixed by [this PR](https://github.com/PrefectHQ/prefect-ui-library/pull/1146). Can you verify you're no longer experiencing this issue?
