### ISSUE TITLE
improvments of the UI and a few useful features during debugging.

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#5917]
## Description

I'm new to prefect, migrating from Airflow, and I like it very much, but there are a few annoying things in the UI and I've a few suggestions for (easy) features. I'm using ! v2.06b

UI features:
- the filters are not kept during navigation. e.g. setting filter in Flow runs, then going to deployments and back to Flow runs -> filters are reset. Use case: ex: filtering out scheduled runs is most often wanted because they appear first and are usually no so interesting. This setting should be permanent during a (cookie?) session.

- filters would be needed in the deployments page as in the flow runs page.

- the deployments page show: "flow name /deployment name", which is redundant and clutters the interface. Choosing a short name for the deployment that do not repeat the flow name is not feasible in my case because the deployment name must be unique (for all flows). Because this is a question of personal preference, I suggest to add a configurable format (in the options).  e.g. using jinja templates.  DEPLOYMENT_TITLE_FORMAT="{{flow_name}}/{{deployment_name}}" for the default as it is right now, and I could use {{deployment_name}} only.

- the flow runs page does not show the deployment name which is really a problem when a unique flow is used with different parameters (my case). I'd suggest to use the deployment name instead, which is unique, or better to implement the configurable format as proposed above for the deployments page.

- run button in deployments should automatically forward to flow run (configurable?).

- add the current (server) time in the header of all pages. Useful to know if/when the refresh is running.

- when running a flow of subflows, it would be very useful to group the subflows in the flow runs page (e.g. collapsable tree). I've not use subflows a lot up to now, but the UI might be impractical if a lot of subflows are generated.

- ideally I'd like to see a graph of the executed tasks (as in Airflow). I know, this can not be done before the execution in prefect, by design, but it would be an added-value for inspecting the logs and quickly identifying where the failure is. Important when a lot of task/subflows are generated.

OTHER NON-UI FEATURES:

- why running a task directly from python is not possible although it is possible for a flow ? For debugging I've to create a flow for each task to test them independently...

- I like the deployment system very much, it is very easy to "push" changes to the server and make rapid tests. But unfortunately it does not deploy modules which prevent to use modularity. Having to use a git repo in parallel to push the dependencies cancels the benefit of this nice deployment system. I can understand the difficulty to determine automatically which module to upload or not, but it could be declarative, in a list of files in DeploymentSpec. Something like this:

DeploymentSpec(
    flow_location="../tasks/download_amsr2.py",
    flow_name="get-recent-amsr2",
    additional_files=["../lib/common.py"]
)

Of course, this requires some decision for the paths where the module ends up... but it would be really useful for the development.

- I can understand the log size limit per flow runs, but it is often more useful to keep the last messages in case of error. A possible approach is to limit the number of messages (and the size of each message) and to add a rotation system to remove the oldest messages.

**Comment by zhen0** [comment]
Thanks for the feedback. All points we can consider for future iterations of the ui.

**Comment by zhen0** [comment]
When you say you'd like a graph of the executed tasks, did you check out the radar view?
