### ISSUE TITLE
Prefect vertex-ai agent-jobs failing

### ISSUE THREAD

**Issue by DivyashaAgrawal** [PrefectHQ/prefect#5940]
## Description

Since yesterday the jobs have been failing.
Here is the error:

`400 List of found errors:	1.Field: job_spec.worker_pool_specs[0].container_spec.env[6].value; Message: Env vars cannot contain any unescaped apostrophe character '	 [field_violations {
  field: "job_spec.worker_pool_specs[0].container_spec.env[6].value"
  description: "Env vars cannot contain any unescaped apostrophe character \'"
}
]`

## Expected Behavior
Jobs should run successfully

Optionally run `prefect diagnostics` from the command line and paste the information here. -->
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.0-18-cloud-amd64-x86_64-with-glibc2.28",
    "prefect_backend": "cloud",
    "prefect_version": "1.2.2",
    "python_version": "3.9.7"
  }
}
```

**Comment by ejakait** [comment]
> 

Any resolution to this yet? I am encountering the same error

**Comment by mittalsuraj18** [comment]
The error happens if add tags to your agents. The temporary fix is to remove tags from you agents and the jobs

**Comment by madkinsz** [comment]
This seems resolvable by escaping the environment variables in the container spec. It might be as simple as `.replace("'", "\\'")` on each variable value. It'd be great if someone with a Vertex setup could give it a go.

**Comment by madkinsz** [comment]
cc @ahuang11 for the v2 implementation.
