### ISSUE TITLE
Hide  password in PREFECT_ORION_DATABASE_CONNECTION_URL in Prefect 2.0 UI setting page

### ISSUE THREAD

**Issue by gq1** [PrefectHQ/prefect#5941]
PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:***********@tol-prefect-postgresql.prefect:5432/orion

We don't have any restriction to use UI page, and the database password shown in the setting page.

**Comment by zhen0** [comment]
Thanks for the request. That info is there because we think it could be useful to users. I'm wary of removing it since that would affect others. I'm ok to leave this ticket open to see if others share your use case or have other preferences or ideas.

**Comment by gq1** [comment]
The problem is we don't have a user name and password to protect the UI pages, and then everybody can see your database's password.

**Comment by madkinsz** [comment]
We can update the settings routes to handle secrets the same way we do for blocks now that we've added a workaround to our Pydantic models.

**Comment by austinnichols101** [comment]
> we think it could be useful to users

Yes - **_malicious users_**
I can think of no good reason why the DB password should EVER be displayed in the UI.

**Comment by voycey** [comment]
Wouldn't it be simpler to simply create authentication for the Orion Server UI?

**Comment by madkinsz** [comment]
Unfortunately adding authentication is vastly more complicated than obfuscating our settings. For some users, that may be the preferred path though.

**Comment by voycey** [comment]
Couldn't it be as simple as:

- start docker container and pass token into env
- require the same token for all requests if it exists?

That way the implementation falls to the users and is flexible enough to be handled as they wish

**Comment by jannekeskitalo** [comment]
A new setting PREFECT_ORION_DATABASE_PASSWORD was added to allow injecting the password from a secret to the connection url, but then the password setting itself is shown in cleartext on the settings -page. Would be really good to hide it. For now I need to block access to the settings -path completely.

https://github.com/PrefectHQ/prefect/pull/5759

**Comment by madkinsz** [comment]
We are going to hide it, we just need to duplicate secret handling from blocks -> settings. If anyone is interested in taking that on, feel free to chime in. Otherwise it's on our backlog and we'll get to it as soon as possible.
