### ISSUE TITLE
"Prefect Action Failed Notification" when using PagerDutyNotificationAction with FlowSLAFailedEvent 

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5955]
[**View in #prefect-community on Slack**](https://slack.com/archives/CL09KU1K7/p1656608745281479)

![Jessica_Smith] **@Jessica_Smith:** I'm getting false notifications from Prefect Cloud, from the PagerDuty Automation I have enabled. The notification says "Prefect Action Failed Notification", but the details show that HTTP response code was 202 (Accepted). So these probably should not be causing a failure notification.

The `PagerDutyNotificationAction` (`24dfaasdfe-93dd-4b11-8dddc-4xxxxxx3d23`) has failed with 'HTTPError: 202 Accepted 'PagerDuty did not provide error details.' while contacting service API. Check your action configuration. See [the Pagerduty docs](https://developer.pagerduty.com/docs/rest-api-v2/errors/) for more details on error handling.' during execution triggered by `FlowSLAFailedEvent` event from hook `b625xx8-d3x-4xxe-bxx6-1xxxxxx67f2`.

![Anna_Geller] **@Anna_Geller:** Could you check and perhaps screenshot your Pager duty Automation setup? The error suggests you are using a Cloud hook rather than Automation? Not sure, I might be misinterpreting this error message

There is also a test option to validate Automation actions - can you check if that works?

![Jessica_Smith] **@Jessica_Smith:** Here are the screenshots
![image](https://user-images.githubusercontent.com/86264395/176942345-e47fff11-8c4b-4deb-9413-17b46e3b8ac0.png)
![image](https://user-images.githubusercontent.com/86264395/176942358-ce2a4b01-0c2b-4c0c-bf70-ed1804c8be90.png)

The test notification comes through fine, no error notifications from Prefect. It does come through twice though, it has every time I've ever tested it

https://files.slack.com/files-pri/TL09B008Y-F03NR4A836U/image.png

[Jessica_Smith]: https://avatars.slack-edge.com/2022-05-18/3528945439639_e85063e7a443bd33a4e9_24.jpg
[Anna_Geller]: https://avatars.slack-edge.com/2022-05-01/3466755334708_dc6796b776c6f927b8f8_24.jpg

**Comment by NodeJSmith** [comment]
Tenant id: 4c7668ef-985b-415d-a97b-9819d0e57ab2
Flow run: 536f5b3a-d2c0-4e63-a96c-17232093eff9

**Comment by madkinsz** [comment]
Thanks for the report! I've got a fix open to our development cluster.

**Comment by ccueto36** [comment]
I'm having the exact same issue but with `WebHookAction`. I'm sending a WebHook HTTP POST upon flow state change which always returns an HTTP 202 status as success. Prefect seems to think this 202 is a failure and spams me with "Action Failed" notifications even though they're not failures at all.

Has this been fixed?

**Comment by anna-geller** [comment]
@ccueto36 this seems like a different problem - could you open a separate issue and describe how you get that error exactly? thanks in advance

**Comment by ccueto36** [comment]
> 

I will open a new issue, but I beg to differ than this is a different problem. It's the exact same issue, with a different Action. HTTP 202 seems to be treated as a failure across the board.

**Comment by anna-geller** [comment]
I'm sorry, I must have misunderstood. Thank you so much for creating a new issue!
