### ISSUE TITLE
Make it easier to configure extra loggers when using Dask or Ray task runners

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5960]
[This user](https://discourse.prefect.io/t/how-to-use-logging-in-orion-a-tutorial-by-andrew-brookins/197/11) had to add quite a lot of boilerplate code to configure extra loggers when using Dask task runner. Is there some easier way?

cc @ahuang11 since you know a lot about that

**Comment by madkinsz** [comment]
Related to #5850, logging does not seem to be setup as intended on workers.

**Comment by anna-geller** [comment]
Ahh true, thx for linking the issue
