### ISSUE TITLE
`FileStorageBlock` vs `LocalStorageBlock` in orion

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect#5961]
@anna-geller This issue is to follow up on the local storage "bug" that I mentioned in #5893. There's a good chance I just misunderstand the difference between "File Storage" and "Local Storage" -- if so, this issue can just serve for documentation improvements :sweat_smile:.   

## Description

In the [introductory tutorial for orion deployment](https://orion-docs.prefect.io/tutorials/deployments/#configuring-storage), local file storage fails with "LocalStorage" but works properly with "FileStorage". 

## Expected Behavior (Recommendations)

- storage on a local file system should be consistent between both `LocalStorageBlock` and `FileStorageBlock`
- to help with beginners (like me :smile:), change the introductory tutorial to use local storage instead of S3 storage
- either merge or clarify the difference between local and file storage. The `LocalStorageBlock` docstring says "Store data in a run's local file system" while `FileStorageBlock` says "Store data as a file on local or remote file systems". I know I want to store on a local file system but it's unclear which I should use based on these docstrings.

## Reproduction

1. run `prefect orion database reset` and confirm
2. create a file name `leo_flow.py` with contents
``` python
from prefect import flow, task, get_run_logger

@task
def log_message(name):
    logger = get_run_logger()
    logger.info(f"Hello {name}!")
    return

@flow(name="leonardo_dicapriflow")
def leonardo_dicapriflow(name: str):
    log_message(name)
    return
```
2. create a file name `leo_deployment.py` with contents
``` python
from prefect.deployments import DeploymentSpec

DeploymentSpec(
    name="leonardo-deployment",
    flow_location="./leo_flow.py",
    tags=['tutorial','test'],
    parameters={'name':'Leo'}
)
```
3. in a separate terminal run `prefect orion start` and leave running
4. run `prefect storage create`, select option 3 (Local storage), and set storage path to `~/Documents/test_orion`. Agree to setting it as the default storage
5. run the command `prefect deployment create leo_deployment.py` and receive the following error:
```
Deployment specification 'leonardo_dicapriflow/leonardo-deployment' failed validation: You have configured local storage but this deployment is using a Universal
flow runner which requires remote storage.
Failed to create 1 out of 1 deployments.
```

NOTE: You can get local storage to work if you repeat all steps above where step 4 is changed to...
4. run `prefect storage create`, select option **1 (File storage)**, and set base path to `~/Documents/test_orion`. Agree to setting it as the default storage

## Environment

output of `prefect version`:
```
Version:             2.0b7
API version:         0.6.0
Python version:      3.10.5
Git commit:          eb9f17a8
Built:               Wed, Jun 22, 2022 12:07 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.0
```

**Comment by madkinsz** [comment]
Thanks for the nice write-up! These are likely to be replaced entirely in the next few weeks and this confusion should be resolved.

**Comment by jacksund** [comment]
Awesome! I look forward playing with the updates. Feel free to close this issue if you'd like :smile:
