### ISSUE TITLE
Issues with prefect and really small tasks

### ISSUE THREAD

**Issue by jordandroid** [PrefectHQ/prefect#5977]
## Description
I am using prefect Orion version 2.0b7

For a project we require to preprocess a lot of files in input and processing of each is really quick but we wanted to see each processing to a file as task using prefect.

Unfortunately without task the program take around 7 second originally  (100file) and around 50 second with each processing being a task.

We tried using Dask, it can reduce a bit but we were around 30s still far away from the 7 seconds of the basic sequential python code.

I made a basic synthetic test code without files just using a list and I got same problem. 

I ran it both using an agent-work-queue and server  or directly from CLI and got the same behaviour.

Thank you for your help with this issue.

Here are the test synthetic code.
[basetest.zip](https://github.com/PrefectHQ/prefect/files/9065246/basetest.zip)

**Comment by KMDgit** [comment]
Hello, 
I'm running on the same issue. 
Before implementing prefect I was running my python functions using [multiprocessing](https://docs.python.org/3/library/multiprocessing.html). I thought it was a good idea to implement Prefect with all the benefits they presented on the website. This is not the case.
The same code I was able to run in 6 sec is now running in 34 s. 
How are we supposed to increase such performance @madkinsz ?
@jordandroid, did you find a proper way ?

Thank you,

**Comment by jordandroid** [comment]
Hello,

In our case we ended up by not tasking processing of each image.
However even with that (so reducing drastically the number of tasks), we noticed that we should avoid returning some types of obects (I think it was a really large list that gived us issues for example)
