### ISSUE TITLE
Stream logs via CLI

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5987]
## Description

Whilst it's possible to access the logs for a flow run via the API, it would be super nice to be able to continuously stream them to stdout via the CLI.

## Reproduction / Example

 eg:
```
prefect flow-run logs [flow-run-id]
```

**Comment by tekumara** [comment]
This would mimic the behaviour in Prefect 1 of `prefect run --watch`.

**Comment by nbatchelder** [comment]
I'd also love this feature!

**Comment by AMontgomerie** [comment]
I want to trigger a prefect flow run from inside a CI/CD pipeline and monitor the flow until it completes. Streaming the logs using the CLI would be the ideal way to do this.

**Comment by serinamarie** [comment]
Closing this, but feel free to open a new issue if using `prefect flow-run logs <id>` does not solve your use case.

**Comment by serinamarie** [comment]
Closing this, but feel free to open a new issue if using `prefect flow-run logs <id>` does not solve your use case.
