### ISSUE TITLE
Segmentation fault when using matplotlib in a flow context

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect#5991]
## Description
Running a prefect unit test that uses `matplotlib.plot` will lead to a segmentation fault. The test itself will complete successfully, but depending on the operating system either (1) a segmentation fault will be printed and/or (2) the test suite will crash. For example, this causes my CI to crash on MacOS and print errors in Linux+Windows.

## Expected Behavior
If this can't be fixed within prefect's core, then maybe prefect can (i) warn/prevent users trying to use matplotlib or (ii) simply add a section to the documentation that discusses proper matplotlib use. 

## Reproduction

1. create a python env with Prefect (2.0b8), matplotlib, and pytest are required. This minimal test was done on linux (ubuntu 22.04). I used the following commands to create the env:
``` bash
conda create -n test_env -c conda-forge pytest matplotlib
conda activate test_env
pip install -U "prefect==2.0b8"
```
2. create a file named `test_matplotlib.py` with contents:
``` python
from prefect import flow
from prefect.testing.utilities import prefect_test_harness

import matplotlib.pyplot as plt
import numpy as np


@flow
def make_a_plot():
    """
    This code is from MatPlotLib's tutorials and just makes a simple plot
      https://matplotlib.org/stable/tutorials/introductory/usage.html#coding-styles

    I've removed axis/title naming and subplots to condense the example
    """

    x = np.linspace(0, 2, 100)  # Sample data.
    fig, ax = plt.subplots(figsize=(5, 2.7), layout="constrained")
    ax.plot(x, x, label="linear")
    ax.legend()


def test_matplotlib_prefect():
    """
    This test results in a segmentation fault
    """
    with prefect_test_harness():
        state = make_a_plot()
        assert state.result() == None


def test_matplotlib_normal():
    """
    This test will not cause an error
    """
    x = np.linspace(0, 2, 100)  # Sample data.
    fig, ax = plt.subplots(figsize=(5, 2.7), layout="constrained")
    ax.plot(x, x, label="linear")
    ax.legend()
```
3. in the terminal, run `pytest test_matplotlib.py`
4. You will see the test (and pytest) complete successfully, but `Segmentation fault (core dumped)` will be present at the bottom. Here is a screenshot example:
![Screenshot from 2022-07-11 12-34-25](https://user-images.githubusercontent.com/47992949/178313781-33e9ce3a-1b41-4916-8866-e358ea42c9b6.png)
And the warning:
``` python
  /home/jacksund/anaconda3/envs/test_env/lib/python3.10/site-packages/pymatgen/util/plotting.py:48: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
    fig, ax = plt.subplots(figsize=(5, 2.7), layout="constrained")
```

## Environment
Env is also described in step 1 above
```
Version:             2.0b8
API version:         0.7.0
Python version:      3.10.5
Git commit:          4b8dfc35
Built:               Fri, Jul 8, 2022 8:53 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.0
```

**Comment by jacksund** [comment]
I should add that this is obviously a problem on the user-end, but I opened an issue here because of how common matplotlib is. It's likely others who automate plot creation will run into this bug too. Nearly all of my workflows are file-based calculations that write plots to png files at the end -- and building unit tests for these flows is I came across this issue.

**Comment by madkinsz** [comment]
Switching to the non-GUI backend should resolve this

```python
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
```

Additionally, if you write an async flow we'll run it in the main thread.

I'm not sure where the best place for documentation on this is, cc @tpdorsey. I think the workaround in this issue will suffice for a while.

Unfortunately matplotlib segfaults and crashes the Python interpreter so we can't even can't even catch this error and provide a helpful message.

I can explore running sync flows in the main thread, but it'll be hard.

**Comment by tpdorsey** [comment]
Thx @madkinsz IIRC we talked about this at some point and I have some example code to include in the docs.

**Comment by madkinsz** [comment]
Should be closed by https://github.com/PrefectHQ/prefect/pull/8702
