### ISSUE TITLE
Prefect UI connects to localhost:4200 when deployed using Helm

### ISSUE THREAD

**Issue by amitza** [PrefectHQ/prefect#5998]
## Description
I'm trying to install the Prefect server in air-gapped Openshift cluster using Helm.
When I open the UI in the left corner of the screen I see that the UI pod is trying to connect to `localhost:4200`  despite configuring the env var `PREFECT_SERVER__APOLLO_URL`.

## Expected Behavior
The UI will connect to the real value of `PREFECT_SERVER__APOLLO_URL`

## Reproduction
Install the [Helm chart](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server)

## Environment
Unfortunately the bug occurred in air-gapped Openshift cluster so no screenshots or logs.
Openshift version: 4.6

**Comment by liqwid** [comment]
you need to set `api.env` to `[{ "name": "PREFECT_API_URL", "value": "https://<your_prefect_host>/api"}]`
