### ISSUE TITLE
CronSchedule `day_or` as optional

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6006]
## Description
```python
class CronSchedule(PrefectBaseModel):
    """
    Cron schedule
    ...

    Args:
        day_or (bool, optional): ...
    """

    day_or: bool = Field(
        True,
        description="Control croniter behavior for handling day and day_of_week entries.",
    )
    ...
```

`day_or` is stated as optional in the docstring but not in the type hint.

## Expected Behavior
`day_or` to be typed as `Optional[bool]`

**Comment by mikkelduif** [comment]
prefect orion 2.0b8

**Comment by madkinsz** [comment]
Is `None` a meaningful or valid value for this field? I believe the intention here is to indicate that it's optional to provide because it has a default value of `True`.

**Comment by mikkelduif** [comment]
I guess it can either be optional or mandatory. Since it cannot be `None` I would suggest to specify an explicit default value (i.e., make it optional to pass an explicit value).


Changed example:

```python
class CronSchedule(PrefectBaseModel):
    """
    Cron schedule
    ...

    Args:
        day_or (bool): ...
    """

    day_or: bool = Field(
        default=True,
        description="Control croniter behavior for handling day and day_of_week entries.",
    )
    ...
```

otherwize pylance will complain, since it does not understand True is the default value unless it is marked with `default=`.
It's slightly annoying without passing day_or=True since the CronSchedule appears frequently in the code and raises `reportGeneralTypeIssues` everywhere, which is slightly annoying. Otherwize no functional change.

**Comment by madkinsz** [comment]
Ah this is related to https://github.com/samuelcolvin/pydantic/issues/3617

We'll likely want to address all use of `Field` consistently to fix this type-hint behavior.

**Comment by mikkelduif** [comment]
yes, could probably also be related to some other baseclasses, would recommend to put it on an unprioritized ticket to address all in one. makes it convenient with the typechecking working properly.
