### ISSUE TITLE
Postgres database errors when using pgbouncer connection pool

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect#6014]
From slack @anna-geller. [link](https://prefect-community.slack.com/archives/CL09KU1K7/p1658066396418239) 

## Description

When `PREFECT_ORION_DATABASE_CONNECTION_URL` connects to a Postgres database using a connection pool built by pgbouncer, `prefect orion database reset` will behave normally, but all other calls to the database will fail. The error traces back to a known issue from sqlalchemy+asyncpg, and there is an open issue [here](https://github.com/sqlalchemy/sqlalchemy/issues/6467).

So while this isn't a bug on Prefect's end, this issue is to track the sqlalchemy fix and also follow-up on implementing the fix within prefect's [sql engine configuration](https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/orion/database/configurations.py#L194-L215). Once the sqlalchemy issue is closed, I can open a PR to allow passing extra `connection_args` to `create_async_engine` (such as `statement_cache_size`)

**Comment by madkinsz** [comment]
cc @jakekaplan did we implement a workaround for this in Cloud when we were exploring pgbouncer that we can backport?

**Comment by jakekaplan** [comment]
I'm not 100% sure this works since we ended up not using pgbouncer due to general compatibility issues, but in Cloud we are explicitly passing `statement_cache_size` to the connect args like this:

```python
kwargs={
  "connect_args": {
      "statement_cache_size": 0
      }
  }
engine = create_async_engine(
   connection_url,
   ...,
   **kwargs
 )
```
I think this was mentioned in one of the comments in the issue thread, although unclear if it resolves everything

**Comment by jacksund** [comment]
I've been messing with this issue and finally got a working version. Right before `create_async_engine` is called...

https://github.com/PrefectHQ/prefect/blob/1d4dfa5055c46d7769c571b6a66aaec8e6cdfc13/src/prefect/orion/database/configurations.py#L215

... I added the following code ...

``` python
# This connect_args setup is in my local 2.0b8 install
# but looks removed in most recent orion branch
if connect_args:
    kwargs["connect_args"] = connect_args

## START FIX ###################
PREFECT_USE_PGBOUNCER = True  # Maybe add as a new env variable...?

if PREFECT_USE_PGBOUNCER:

    from uuid import uuid4
    from asyncpg import Connection

    connect_args["statement_cache_size"] = 0
    connect_args["prepared_statement_cache_size"] = 0

    class CConnection(Connection):
        def _get_unique_id(self, prefix: str) -> str:
            return f"__asyncpg_{prefix}_{uuid4()}__"

    connect_args["connection_class"] = CConnection

## END FIX ###################

engine = create_async_engine(
    self.connection_url, echo=self.echo, **kwargs
)
```

**Comment by jacksund** [comment]
Would a PR for my fix be accepted? I can open one if so -- not sure how I would unittest it though. 

Or is there another recommended approach that I can use in future releases?

**Comment by madkinsz** [comment]
I don't think we're going to be able to review a PR for a few weeks, we're moving towards a stable release and our team is pretty busy with that. For what it's worth, we are not using pgbouncer for Cloud since it did not improve performance. I'd be happy to review a contribution in the next month or so though.

**Comment by jacksund** [comment]
Sounds good. In case there are up-stream changes to orion, I'll wait to open a PR and just check back in later.

Good luck prepping the stable release!
