### ISSUE TITLE
prefect_test_harness does not ignore PREFECT_API_URL

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6055]
## Description

When PREFECT_API_URL is set and a flow is run using `prefect_test_harness` then the test tries to use PREFECT_API_URL. I was expecting the harness would ignore PREFECT_API_URL because it creates a temporary database.

## Reproduction / Example
```python
from prefect import flow
from prefect.testing.utilities import prefect_test_harness
import os


@flow
def my_favorite_flow():
    return 42


def test_my_favorite_flow():
    os.environ["PREFECT_API_URL"] = "http://foobar:4200/api"
    with prefect_test_harness():
        # run the flow against a temporary testing database
        assert my_favorite_flow() == 42
```

Fails with:

```
RuntimeError: Cannot create flow run. Failed to reach API at http://foobar:4200/api/.
```

prefect 2.0b12

**Comment by zangell44** [comment]
Thanks for the clear write up, we'll get this fixed shortly!
