### ISSUE TITLE
Using the create_flow_run() breaks when sending in a flow with no version field

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#6066]
## Description

prefect==2.0b13

Using the create_flow_run() function with a flow model that has no version field results in the following error:
```
flow_version=flow.version,
AttributeError: 'Flow' object has no attribute 'version'
```
This is incorrect behaviour as the docs state this for a flow:

version ---> An optional version string for the flow; if not provided, we will attempt to create a version string as a hash of the file containing the wrapped function; if the file cannot be located, the version will be null.

## Reproduction / Example

```
flow_id = "47672281-5f80-4749-b896-aeb9385408d6"
flow_model = await client.read_flow(flow_id)
response = await client.create_flow_run(flow=flow_model, name="testing_this")
print(response) 
   ```

**Comment by bunchesofdonald** [comment]
Hi @rjhawar `create_flow_run` returns an instance of `prefect.orion.schemas.core.Flow`, and the `flow` argument for `create_flow_run` expects a `prefect.flows.Flow` (the decorated flow function itself) which has a version. Can you provide more information about what you're trying to accomplish?

**Comment by rjhawar** [comment]
@bunchesofdonald 
This was just confusion on my part about object that function took in. 
You can go ahead and close out this issue.
