### ISSUE TITLE
Failed to create a project with CLI

### ISSUE THREAD

**Issue by pipat-flowacc** [PrefectHQ/prefect#6071]
## Description

I was following the [getting started guide](https://docs.prefect.io/core/getting_started/more-resources.html#examples), but I failed to create a project with CLI. 
There was no `create` in available commands. 

```
(.venv) pipat@AAAAAAAA:~/Documents/airbyte-prefect$ prefect create project "Prefect Examples"
Usage: prefect [OPTIONS] COMMAND [ARGS]...
Try 'prefect --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'create'.                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

## Reproduction / Example

Ubuntu 20.04 on WSL2, Windows 11 21H2, 
Python 3.8

```sh
python -m venv .venv
source .venv/bin/activate
pip install "prefect>=2.0b"
prefect create project "Prefect Example"
```

**Comment by FulcronZ** [comment]
The example intends for v1. The link was moved to v1 doc when v2 released. 
Please close this issue.

**Comment by pipat-flowacc** [comment]
The example intends for v1. The link was moved to v1 doc when v2 released.
