### ISSUE TITLE
Support a broader range of databases

### ISSUE THREAD

**Issue by dhirschfeld** [PrefectHQ/prefect#6077]
It appears that only sqlite and postgres are supported?
https://github.com/PrefectHQ/prefect/blob/ea6f062d5005096ff890aab9595cecc1e4bde9ed/src/prefect/orion/utilities/database.py#L4-L5

Since Prefect appears to be using `sqlalchemy` it should be possible to support other databases too. Is that something which is at all on the roadmap? If not, would it just be a case of implementing the helper functions/classes in the above file?

**Comment by bunchesofdonald** [comment]
@dhirschfeld SQLIte and Postgres are the only supported databases and, at the moment, additional database support is not on the roadmap.

Unfortunately, while Prefect does use `sqlalchemy`, it would be more involved than just adding some helpers to the database utilities, there are migrations for each database type, connection handling, etc. that likely isn't feasible without changes to Prefect itself.

**Comment by dhirschfeld** [comment]
Thanks for letting me know. I'm happy for this to be closed as asked & answered unless you want to keep it open as a feature request.

**Comment by bunchesofdonald** [comment]
Thank you!
