### ISSUE TITLE
UI: Block schema union properties displaying as JSON

### ISSUE THREAD

**Issue by pleek91** [PrefectHQ/prefect#6087]
# Description
The ui isn't handling properties that are unions. Specifically a property like this produces a JSON field rather than letting the user select either of the two nested blocks

```json
{
  "credentials": {
    "title": "Credentials",
    "anyOf": [
      {
        "$ref": "#/definitions/MinIOCredentials"
      },
      {
        "$ref": "#/definitions/AwsCredentials"
      }
    ]
  }
}
```
![image](https://user-images.githubusercontent.com/6200442/181619424-bf969ffa-cc26-44b7-b481-b5bef0fe984a.png)

**Comment by anna-geller** [comment]
Looks good now 

![image](https://user-images.githubusercontent.com/86264395/190383229-b79c3a37-874e-48cc-9a59-dea829e78484.png)


![image](https://user-images.githubusercontent.com/86264395/190383165-3c9b4866-6c8d-4803-a76d-50e8c3133d4f.png)
