### ISSUE TITLE
Hanging On Windows - (conda environment - python 3.10)

### ISSUE THREAD

**Issue by sanjithramesh** [PrefectHQ/prefect#6119]
### Describe the bug

It seems to hang when running python for some reason. Spent time with Chris and jeff trying to solve it during the pacc course on 07/29/2022. 

Tried it on 3.7 and 3.10, still gives us the error. 

![image](https://user-images.githubusercontent.com/52591382/181825669-d98e9cf5-a734-458b-ab25-5e9419c0c44f.png)

### To Reproduce

```python
...
```

### Error

```
# Copy complete stack trace and error message here, including log output if applicable.
``` 

No stack trace because it just hangs

### Versions

- OS: Windows 10
- Python: 3.7, 3.8 and 3.10
- Prefect: 2.0

**Comment by sanjithramesh** [comment]
Tried running it locally - Did not work.

**Comment by johnkangw** [comment]
I wonder if this is similar to the error I am experiencing after the Prefect agent is running for a long time on my local machine (Windows). 

![image](https://user-images.githubusercontent.com/72617548/182227493-984ddd1f-f35d-4957-b477-3a6045725ff9.png)
