### ISSUE TITLE
Deployments Scheduling Button Interval Changes when Value is first edited in Orion

### ISSUE THREAD

**Issue by nygeog** [PrefectHQ/prefect#6133]
### Describe the bug

When I go to first edit the Deployments Scheduling Button to modify the Value, the Interval (time unit) changes as well.

This is what it first looks like:
<img width="589" alt="Screen Shot 2022-07-29 at 2 58 07 PM" src="https://user-images.githubusercontent.com/2790599/181848336-d750f8a8-29bc-45d0-952a-c12e9cbf26ac.png">

Then I edit to 1 and the Interval (Minutes) switches down to Seconds units. 
<img width="556" alt="Screen Shot 2022-07-29 at 2 43 49 PM" src="https://user-images.githubusercontent.com/2790599/181848247-b2e281a2-7b1c-4423-b7c4-be9b45d7c3d2.png">

 

### To Reproduce

```python
Click the 3 dots on the Deployments page, click Edit, go to Scheduling (remove if anything is already there), hit Edit, and then change the Value and keep an eye on the unit.
```

### Error

```
# Copy complete stack trace and error message here, including log output if applicable.
``` 

### Versions

- OS:
- Python:
- Prefect:

**Comment by zhen0** [comment]
I can replicate on app.prefect.cloud
