### ISSUE TITLE
Ignore files specified in .gitignore when uploading to remote storage

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6174]
### Prefect Version

2.x

### Describe the proposed behavior

Ignore files specified in .gitignore when uploading to remote storage.

This improves the speed of `prefect deployment build` and prefect flow run startup time by avoiding transfer of unnecessary files.

### Describe the current behavior

`prefect deployment build` with a remote file system will upload the entire contents of the current directory to storage  (excluding hidden files/directories) 

### Additional context

Our repos have non-flow code in them (eg: _node_modules/_ and _terraform/_). Ignoring these folders would reduce the number of files, and hence speed of upload and download, by 10x.

**Comment by discdiver** [comment]
Good thought. [This PR](https://github.com/PrefectHQ/prefect/pull/6143) was just merged, so something similar will be in the next release, which should drop very soon.
