### ISSUE TITLE
Prefect register with remote docker registry does not cache layers on 1.2.4

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#6187]
### Describe the bug

When running prefect register to build the docker image, layers are not cached when using a remote registry in Prefect 1.2.4

The expectation is the first build registers and populates the layers.
Any subsequent registration should use the cached layers.

As it currently stands - no prefect register uses cache for remote registry configurations, unless a registration was first done without a remote registry.

https://docs-v1.prefect.io/orchestration/recipes/configuring_storage.html
https://docs-v1.prefect.io/orchestration/execution/storage_options.html#codecommit

### To Reproduce

```python
A minimal example:

FROM --platform=linux/amd64 python:3.8
ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VIRTUALENVS_CREATE=false

WORKDIR /code

RUN pip install requests
```
```
import prefect
from prefect import Flow, task
from prefect.storage import Docker


@task
def say_hello():
    logger = prefect.context.get("logger")
    logger.info("hello")


storage = Docker(
    dockerfile="Dockerfile",
    image_name="cache-example",
    registry_url="<replace with registry url>",
)


with Flow("cache-example", storage=storage) as flow:
    say_hello()
```

### Error

The first execution will build from scratch as expected.
Re-running the build afterwards, rebuilds entirely without using cached layers.

If a registration is first done without a remote registry, the layers are cached.
Updating with the remote registry after a local cache exists, any following builds then successfully use the local cache.

### Versions

- OS: macOS
- Python: 3.9.13
- Prefect: 1.2.4

### Additional context

This is opened on behalf of a customer experiencing this issue. 
More details can be requested as necessary.
A much older version of prefect (0.15.13) was used and did not exhibit this same behavior.

**Comment by prefectcboyd** [comment]
Working on building a complete re-production of this issue using my own registry to illustrate the behavior.

**Comment by prefectcboyd** [comment]
I reproduced this issue on my own, I can provide logs as necessary.

The relevant content:
`Prefect version
1.2.4

#Initial register no cache available
prefect register --path ./boyd_flow.py --project Apollo 0.91s user 0.41s system 0% cpu 9:19.30 total
#2nd run, cache should be available
prefect register --path ./boyd_flow.py --project Apollo 0.67s user 0.35s system 0% cpu 5:30.59 total


prefect version
0.15.13

#Initial run, no cache available
prefect register --path ./boyd_flow.py --project Apollo 1.05s user 0.39s system 0% cpu 7:35.49 total
tee -a remote1.txt 0.00s user 0.01s system 0% cpu 7:35.49 tota
#2nd run, cache is available
prefect register --path ./boyd_flow.py --project Apollo 0.47s user 0.24s system 3% cpu 21.841 total
tee -a remote2.txt 0.00s user 0.00s system 0% cpu 21.840 total`

**Comment by prefectcboyd** [comment]
Files included logging the output of each of the above commands.
They have been renamed to determine easier - names are like  remote-1-01513 indicating run 1 using prefect version 0.15.13.
[remote-1-01513.txt](https://github.com/PrefectHQ/prefect/files/9291799/remote-1-01513.txt)
[remote-2-01513.txt](https://github.com/PrefectHQ/prefect/files/9291800/remote-2-01513.txt)
[remote-1-124.txt](https://github.com/PrefectHQ/prefect/files/9291806/remote-1-124.txt)
[remote-2-124.txt](https://github.com/PrefectHQ/prefect/files/9291807/remote-2-124.txt)

**Comment by prefectcboyd** [comment]
This issue persists through version 1.3.0 as well; I can provide logs for these two runs on 1.3.0 as well if necessary.

```
(prefect130) (base)  christopherboyd@Christophers-MacBook-Pro  ~/block/130  prefect version
1.3.0

prefect register --path ./boyd_flow.py --project Apollo  0.98s user 0.37s system 0% cpu 6:00.06 total
tee -a remote1.txt  0.00s user 0.01s system 0% cpu 6:00.06 total

prefect register --path ./boyd_flow.py --project Apollo  0.55s user 0.29s system 0% cpu 3:48.61 total
tee -a remote2.txt  0.00s user 0.01s system 0% cpu 3:48.61 total

```

**Comment by cicdw** [comment]
Closing as stale and because Prefect 1.x is no longer under active development.
