### ISSUE TITLE
Provide Slack blocks for SlackWebHook

### ISSUE THREAD

**Issue by neumann-nico** [PrefectHQ/prefect#6199]
### Prefect Version

2.x

### Describe the proposed behavior

It should be possible to not only send text trough SlackWebHook but also Slack blocks. This would allow to send images, gifs, formatted text/code, etc. to Slack. Example of a Slack image block: https://api.slack.com/reference/block-kit/blocks#image

This functionality is already implemented in the underlying `AsyncWebhookClient.send` method. Just the `blocks` parameter needs to be provided.

Might be a little confusion between Prefect blocks and Slack blocks.

### Describe the current behavior

Currently you can only send text as string

### Example Use

```python
slack_webhook_block = SlackWebhook.load("slack-fun-channel")
# Example block taken from https://api.slack.com/reference/block-kit/blocks#image
blocks = [
    {
        "type": "image",
        "title": { "type": "plain_text", "text": "Please enjoy this photo of a kitten" },
        "image_url": "http://placekitten.com/500/500",
        "alt_text": "An incredibly cute kitten."
    }
]
slack_webhook_block.notify("text", blocks=blocks)
```

**Comment by desertaxle** [comment]
Thanks for the issue @neumann-nico! If you're interested in use Slack blocks in your messages, `prefect-slack` has couple of tasks that support that now!

**Comment by neumann-nico** [comment]
@desertaxle Thank you for pointing to `prefect-slack`. I currently only see the old way using WebHooks through prefect Blocks in the UI. Will the new way be inlcuded soon in the Block section?

**Comment by neumann-nico** [comment]
Just found out how it works with prefect-slack:

```python
import asyncio
from prefect import task
from prefect_slack.credentials import SlackWebhook

@task
async def send_slack_message():
    client = SlackWebhook(url="SLACK_WEBHOOK_URL").get_client()
    client.send(blocks=...)

@flow
async def run_flow():
    await send_slack_message()

if __name__ == "__main__":
    asyncio.run(run_flow())
```
