### ISSUE TITLE
Give cloud provider storage blocks consistent names

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#6221]
### Prefect Version

2.x

### Describe the proposed behavior
Block schema names are consistent with each other:
- The "Azure" block schema is named "Azure Bucket" 
- The "GCS" block schema is named "GCS Bucket"
- The "S3" block schema is named "S3 Bucket"

### Describe the current behavior

Cloud provider storage blocks have inconsistent names

**Comment by zhen0** [comment]
Is this still high priority @billpalombi - should it be added to the product orchestration product or can we close as stale?
