### ISSUE TITLE
prefect flow-run ls --state-type on a state that produces no result errors out

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#6229]
### Describe the bug

When using the `prefect flow-run ls` with the `--state-type` flag on a state that produces no results errors out. This is minor issue, but it should just either provide a sensible empty result or a suitable message. 

### To Reproduce

```python
prefect flow-run ls --state-type <ANY STATE> 
NOTE: pick any state that you know will produce no results
```

### Error

```
# Copy complete stack trace and error message here, including log output if applicable.

flow_runs = await client.read_flow_runs(
File "/Users/comp/prefect/.venv/lib/python3.9/site-packages/prefect/client.py", line 1506, in read_flow_runs
return pydantic.parse_obj_as(List[schemas.core.FlowRun], response.json())
File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List[prefect.orion.schemas.core.FlowRun]]
__root__
  none is not an allowed value (type=type_error.none.not_allowed)
``` 

### Versions

- OS: Mac 11.6
- Python: 3.9.13
- Prefect: 2.0.2

**Comment by bunchesofdonald** [comment]
@rjhawar This turned out to be an issue with Prefect Cloud and we have since released an update there. Testing locally this is now working as expected for me.

**Comment by rjhawar** [comment]
@bunchesofdonald Works for me now! Thanks for the update.

**Comment by bunchesofdonald** [comment]
🎉 That's great, I'm glad it's working for you!
