### ISSUE TITLE
Download / Export Flow Run Logs

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#6235]
### Prefect Version

2.x

### Describe the proposed behavior

I would like to be be able to download / export logs from a flow run from the flow run page in the UI.

### Describe the current behavior

There is no way to export logs

**Comment by madkinsz** [comment]
Will `prefect flow-run logs <run_id>` suffice? Is this a UI or CLI request? Your logs are already accessible via the API.

**Comment by WillRaphaelson** [comment]
Updated to reflect this is a UI request. Not urgent, we can prioritize accordingly.

**Comment by dylanbhughes** [comment]
+1 to this

**Comment by dylanbhughes** [comment]
For more context: when I encounter an error, I often log a bunch of related information. I want to be able to sift through, reorganize, reformat, copy/paste, and share these logs. The place I'd like to do that is my text editor

**Comment by WillRaphaelson** [comment]
cc @anna-geller tracking

![Image](https://user-images.githubusercontent.com/26799928/201158213-58ab96c7-301c-48dc-bf58-453657d7b3aa.png)

**Comment by dylanbhughes** [comment]
Also for the record, the "download the logs displayed on this page"  without a "download all of the logs" can be pretty frustrating. I can see myself holding CMD+⬇️ after filtering on some search term to wait for logs to load, which wouldn't be ideal either
