### ISSUE TITLE
API_ERROR in GraphQL Interactive API

### ISSUE THREAD

**Issue by hemantmehra14** [PrefectHQ/prefect#6248]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When running the following GraphQL query in Interactive UI

```graphql
{
  log (
    where: {
      timestamp: {_gt: "2022-08-03T10:24:25.062468+00:00"}
    },
    order_by: {timestamp: asc},
    offset: 70,
    limit: 100
  ) {
    created,
    flow_run_id,
    id,
    info,
    is_audit_log,
    is_loaded_from_archive,
    level,
    message,
    name,
    object_id,
    object_table,
    task_run_id,
    tenant_id,
    timestamp,
    updated
  }
}
```

I got the following output:
```graphql
{
  "errors": [
    {
      "path": [
        "log"
      ],
      "message": "Operation timed out",
      "extensions": {
        "code": "API_ERROR"
      }
    }
  ],
  "data": null
}
```

### Reproduction

```graphql
{
  log (
    where: {
      timestamp: {_gt: "2022-08-03T10:24:25.062468+00:00"}
    },
    order_by: {timestamp: asc},
    offset: 70,
    limit: 100
  ) {
    created,
    flow_run_id,
    id,
    info,
    is_audit_log,
    is_loaded_from_archive,
    level,
    message,
    name,
    object_id,
    object_table,
    task_run_id,
    tenant_id,
    timestamp,
    updated
  }
}
```

### Error

```graphql
{
  "errors": [
    {
      "path": [
        "log"
      ],
      "message": "Operation timed out",
      "extensions": {
        "code": "API_ERROR"
      }
    }
  ],
  "data": null
}
```

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

### Prefect version

```

# Copy output of `prefect version` here if hosting your own UI

```

**Comment by madkinsz** [comment]
Hi! Generally v1 UI issues should be opened at PrefectHQ/ui, but this is actually an API limit. We enforce timeouts on queries to avoid slowdowns for other users. It looks like the query you're using isn't fast enough. Generally reducing the scope with the `where` clause will help.

**Comment by hemantmehra14** [comment]
Is there a way to get the count of records before running the actual query ? So that I can request data in batch using limit and offset.

**Comment by madkinsz** [comment]
You can use `aggregate` calls e.g.

```graphql
{
  flow_run_aggregate(
    where: {start_time: {_gt: "2022-08-03T10:24:25.062468+00:00"}}
  ) {
    aggregate {
      count
    }
  }
}
```

I'd recommend scoping your log queries to a single flow run at time.
