### ISSUE TITLE
Notification Block ( capability "notify" ) added with register fails

### ISSUE THREAD

**Issue by corris** [PrefectHQ/prefect#6273]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I want to add my own blocks that have the "notify" capability on self-hosted server for emailing, Teams notifications, and Jira Issue creation.

When I copy the Slack Webhook notification from prefect.blocks.notifications, then edit it to be bare bones just to print something to the orion server stderr, and then register with prefect block register --file myemail.py, I get an error:

KeyError: "No class found for dispatch key 'myemail' in registry for type 'Block'."

The code below ( myemail.py ) works fine when I append it to prefect.blocks.notifications after the Slack Webhook definition in the module code.

### Reproduction

```python
pip3 install prefect # 2.0.2

prefect orion server start --host 0.0.0.0

#------ on another shell in the same dir.

prefect block register --file myemail.py

#### Go add "MyEmail" as a notification to any flow that has "Completed"

python3 test.py

# See error in logs.
```

### Error

prefect orion start --host 0.0.0.0

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api

View the API reference documentation at http://0.0.0.0:4200/docs

The dashboard is not built. It looks like you're on a development version.
See `prefect dev` for development commands.

INFO:     Started server process [1021760]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4200 (Press CTRL+C to quit)
INFO:     10.166.12.149:62047 - "GET /runs HTTP/1.1" 404 Not Found
INFO:     10.166.12.149:62047 - "GET /runs HTTP/1.1" 404 Not Found
INFO:     10.166.12.149:62047 - "GET /ui-settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:57152 - "POST /flow_runs/count HTTP/1.1" 200 OK
INFO:     127.0.0.1:57154 - "POST /flow_runs/count HTTP/1.1" 200 OK
INFO:     127.0.0.1:57158 - "POST /ui/flow_runs/history HTTP/1.1" 200 OK
INFO:     127.0.0.1:57156 - "POST /flow_runs/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57156 - "POST /flow_run_notification_policies/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57156 - "POST /block_types/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57156 - "POST /block_schemas/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57160 - "POST /block_documents/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:57160 - "POST /flow_run_notification_policies/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:57164 - "OPTIONS /api/block_schemas/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57162 - "GET /block_documents/c3ae5f2d-d6e7-438e-a25b-213c6f7a3d02 HTTP/1.1" 200 OK
INFO:     127.0.0.1:57160 - "POST /block_schemas/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57164 - "POST /flow_run_notification_policies/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:57164 - "GET /block_documents/c3ae5f2d-d6e7-438e-a25b-213c6f7a3d02 HTTP/1.1" 200 OK
Error sending notification for policy 590d1ef8-31c2-4edf-8b85-3769280f0910 on flow run 87529d3d-e8ce-4592-82fe-ec8b21929d51
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect-2.0.2+56.g117584e1c-py3.10.egg/prefect/orion/services/flow_run_notifications.py", line 88, in send_flow_run_notification
    block = Block._from_block_document(
  File "/usr/local/lib/python3.10/dist-packages/prefect-2.0.2+56.g117584e1c-py3.10.egg/prefect/blocks/core.py", line 460, in _from_block_document
    else cls.get_block_class_from_schema(block_document.block_schema)
  File "/usr/local/lib/python3.10/dist-packages/prefect-2.0.2+56.g117584e1c-py3.10.egg/prefect/blocks/core.py", line 491, in get_block_class_from_schema
    return lookup_type(cls, block_schema_to_key(schema))
  File "/usr/local/lib/python3.10/dist-packages/prefect-2.0.2+56.g117584e1c-py3.10.egg/prefect/utilities/dispatch.py", line 186, in lookup_type
    raise KeyError(
KeyError: "No class found for dispatch key 'myemail' in registry for type 'Block'."
^C
Stopping Orion...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
^C
Killing Orion...
Orion stopped!

### Versions

Version:             2.0.2+56.g117584e1c
API version:         0.8.0
Python version:      3.10.4
Git commit:          117584e1
Built:               Fri, Aug 5, 2022 11:03 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2

### Additional context

myemail.py and test.py included below:

#### contents of myemail.py #####

`
from typing import Optional
from prefect.utilities.asyncutils import sync_compatible
from prefect.blocks.notifications import NotificationBlock

class MyEmail(NotificationBlock):
    """
    Sends notifications via email 

    Args:
        NONE

    """

    _block_type_name = "MyEmail"
    _block_type_slug = "myemail"
    _block_schema_capabilities = ["notify"]

    def block_initialization(self) -> None:
        print("MyEmail block initializing")

    @sync_compatible
    async def notify(self,body: str,subject: Optional[str] = None):
        print( f"In my email notify subject: {subject}\nbody: {body}" )
`

#### contents of test.py #####
`
from prefect import flow,task

@task()
def bar():
    print("BAR")
    return "bar"

@flow()
def foo():
    bar()
        
if __name__ == "__main__":
    foo()
`

**Comment by desertaxle** [comment]
Hey @corris! Thanks opening this issue!  The notification block has to be discoverable by the Orion server in order to be used for sending notifications, otherwise the server will fail to instantiate the block subclass. That's the error that you're seeing. A block is discoverable if it has been imported within the current runtime, which is why this works when you directly edit `prefect.blocks.notifications`, but not when your block is declared in a separate file.

I think that it's worthwhile for us to create a mechanism that allows custom blocks to be loaded from a file so that they can be available on the server and enable your use case. In the short term, if you need a workaround to unblock you use case, let me know.

**Comment by ghpu** [comment]
I would be interested by a short-term work around which doesn't require me to edit prefect source code, or create a public prefect-collection.

**Comment by madkinsz** [comment]
@ghpu it does not need to be public, it just needs to be installed locally.

Regardless, https://github.com/PrefectHQ/prefect/pull/7179 adds a setting to import your block modules.
