### ISSUE TITLE
Prefect deployment build changes underscore to dashes when flow name not given

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#6284]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When you have a flow with no name variable, prefect will automatically use the function name as the flow name. However if there is an underscore in the function name it will get converted to a dash when using `prefect deployment build` to generate the manifest and deployment.yaml files.

### Reproduction

```python
from prefect import flow, get_run_logger

@flow
def test_underscore():
    logger = get_run_logger()
    logger.info(f"Hello World")

if __name__ == "__main__":
    main()

Then use prefect deployment build to create the manifest and deployment yaml.
```

### Error

```
{
    "flow_name": "test-underscore", ---> name is incorrectly changed to a version without underscores.
    "import_path": "test_underscore_test.py:test_underscore",
    "parameter_openapi_schema": {
        "title": "Parameters",
        "type": "object",
        "properties": {},
        "required": null,
        "definitions": null
    }
}

```

### Versions

```
Version:             2.0.3
API version:         0.8.0
Python version:      3.9.13
Git commit:          2f1cf4ac
Built:               Fri, Aug 5, 2022 3:57 PM
OS/Arch:             darwin/x86_64
Profile:             cloud
Server type:         hosted

```

**Comment by madkinsz** [comment]
Hi! Thanks for the well written issue. We intentionally replace the `_` in function names with `-` when generating the flow name for display elsewhere. We may consider changing this behavior if it is confusing.

cc @WillRaphaelson

**Comment by rjhawar** [comment]
@madkinsz 
It is both confusing and a potential issue for automated builds.
I am working with quite a few folk who are the ones authoring the different scripts and I can foresee them forgetting to add name variable to there flow decorator.

I use poetry as my package manager and grab the script name from the TOML file that how I automate deployment build process. If the name is being changed on Prefect end this is going break some API calls for me, namely get deployment_by_name.

**Comment by rjhawar** [comment]
issue is resolved
