### ISSUE TITLE
Allow flow run state transition from the following two terminating states: crashed and failure

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#6373]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

Typically when I create flow run i get the parameters for said flow run from a webhook.
Now when a failure/crash situation occurs it typically to do with the environment or the actual script needs fixing. 
This is always going to be some kind of manual interaction in order to fix the issue. 

Once the issue is fixed I would like to programmatically grab a list of flow runs that are in a failed/crashed state for a particular flow or deployment (you can do this currently). Then using said list I would like to simply change the flow run state back to "scheduled" (currently you cannot do this).

The workaround you need to take is that you need find that specific flow run, grab its parameters and recreate it. Recreating a flow run is very cumbersome especially if you have the infrastructure that would enable a state transition from a terminated state (k8 cluster, image in a CR and flow code in remote storage). 

Currently there no intelligent way to handle failure/crashed states dynamically without recreating the flow run. You could keep retrying the flow, but you don't have the ability add an exponential backoff either. 

### Describe the current behavior

You currently cannot state transition from crashed or failure state even if your infrastructure would support doing so.

**Comment by madkinsz** [comment]
I was under the impression that you could transition out of terminal states by passing the `force` boolean to the set state routes, bypassing our typical orchestration rules. Have you given this a try?

Transitions out of terminal states are complicated. You need to deal with any failed task runs as well or the existing state will be loaded and the flow will just fail again. I wouldn't recommend attempting to manually orchestrate your flow like this. Ideally we can provide a robust and simple way for users to trigger retries after fixing the flow.

**Comment by rjhawar** [comment]
@madkinsz 
Thanks for the prompt response as always. Great work on the new release as well.
I wasn't aware of the `force` boolean, I will give that a try.

`Ideally we can provide a robust and simple way for users to trigger retries after fixing the flow.` 
 Would this feature be easy to implement I am just wondering about timelines and priorities on your end.

**Comment by madkinsz** [comment]
> Would this feature be easy to implement? 

Possibly. We're doing similar logic for our automated flow run retries. See https://github.com/PrefectHQ/prefect/blob/main/src/prefect/orion/orchestration/core_policy.py#L250

User expectations for this feature are generally not all aligned, so we're still collecting information about how people expect it to work. I can't promise any particular timeline.

**Comment by madkinsz** [comment]
I believe `force` addresses this and more complex actions (like resetting inner task run states) should be tracked separately.
