### ISSUE TITLE
Regression in 2.0.4 in the UI when editing/adding a scheduler with cron

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#6374]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Adding or editing a schedule with cron in a deployment does not work anymore. It was working in 2.0.2.

### Reproduction

```python
In the edit deployment page, scheduling section, click "add or edit". Select cron. Click Save, this closes the popup with success. Then click Save 
-> get a "Error updating deployment"  and the deployment is not updated.
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```

### Versions

```
Version:             2.0.4
API version:         0.8.0
Python version:      3.9.13
Git commit:          39db6fb1
Built:               Wed, Aug 10, 2022 1:19 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.2
```

**Comment by madkinsz** [comment]
Hi @ghislainp — in the future please use the UI issue template.

Which browser did you produce this on? Could you include any of the output from the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)?

**Comment by ghislainp** [comment]
Firefox on Linux 103.0.1
I get a warning (no error)

TypeError: e is undefined
    PG http://127.0.0.1:4200/assets/index.b58d3601.js:20
    map http://127.0.0.1:4200/assets/index.b58d3601.js:27
    BZ http://127.0.0.1:4200/assets/index.b58d3601.js:27
    map http://127.0.0.1:4200/assets/index.b58d3601.js:27
    UG http://127.0.0.1:4200/assets/index.b58d3601.js:20
    map http://127.0.0.1:4200/assets/index.b58d3601.js:27
    updateDeployment http://127.0.0.1:4200/assets/index.b58d3601.js:27
    y http://127.0.0.1:4200/assets/DeploymentEdit.85f50ff9.js:1
    Yr http://127.0.0.1:4200/assets/index.b58d3601.js:4
    Xn http://127.0.0.1:4200/assets/index.b58d3601.js:4
    W7 http://127.0.0.1:4200/assets/index.b58d3601.js:4
    x http://127.0.0.1:4200/assets/index.b58d3601.js:31
    ce http://127.0.0.1:4200/assets/index.b58d3601.js:31
    promise callback*ce/< http://127.0.0.1:4200/assets/index.b58d3601.js:31
    Yr http://127.0.0.1:4200/assets/index.b58d3601.js:4
    Xn http://127.0.0.1:4200/assets/index.b58d3601.js:4
    n http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ko http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ix http://127.0.0.1:4200/assets/index.b58d3601.js:4
    cx http://127.0.0.1:4200/assets/index.b58d3601.js:4
    E http://127.0.0.1:4200/assets/index.b58d3601.js:4
    M http://127.0.0.1:4200/assets/index.b58d3601.js:4
    _ http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ae http://127.0.0.1:4200/assets/index.b58d3601.js:4
    run http://127.0.0.1:4200/assets/index.b58d3601.js:1
    update http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ne http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ee http://127.0.0.1:4200/assets/index.b58d3601.js:4
    H http://127.0.0.1:4200/assets/index.b58d3601.js:4
    _ http://127.0.0.1:4200/assets/index.b58d3601.js:4
    B http://127.0.0.1:4200/assets/index.b58d3601.js:4
    U http://127.0.0.1:4200/assets/index.b58d3601.js:4
    _ http://127.0.0.1:4200/assets/index.b58d3601.js:4
    B http://127.0.0.1:4200/assets/index.b58d3601.js:4
    E http://127.0.0.1:4200/assets/index.b58d3601.js:4
    M http://127.0.0.1:4200/assets/index.b58d3601.js:4
    _ http://127.0.0.1:4200/assets/index.b58d3601.js:4
    B http://127.0.0.1:4200/assets/index.b58d3601.js:4
    E http://127.0.0.1:4200/assets/index.b58d3601.js:4
    M http://127.0.0.1:4200/assets/index.b58d3601.js:4
    _ http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ae http://127.0.0.1:4200/assets/index.b58d3601.js:4
    run http://127.0.0.1:4200/assets/index.b58d3601.js:1
    update http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ne http://127.0.0.1:4200/assets/index.b58d3601.js:4
    ee http://127.0.0.1:4200/assets/index.b58d3601.js:4
    H http://127.0.0.1:4200/assets/index.b58d3601.js:4
[DeploymentEdit.85f50ff9.js:1:636](http://127.0.0.1:4200/assets/DeploymentEdit.85f50ff9.js)

**Comment by madkinsz** [comment]
Thanks! cc @znicholasbrown I recall you worked on this?

**Comment by drfraser** [comment]
I am getting "Failed to create schedule" in a popup window in the UI and with logging to set to DEBUG everywhere, no exceptions or ERROR info...  Things were working on my mac, but prod is linux

Linux
```
Version:             2.0.4
API version:         0.8.0
Python version:      3.8.10
Git commit:          39db6fb1
Built:               Wed, Aug 10, 2022 1:19 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

Mac
```
Version:             2.0.4
API version:         0.8.0
Python version:      3.8.13
Git commit:          39db6fb1
Built:               Wed, Aug 10, 2022 1:19 PM
OS/Arch:             darwin/x86_64
Profile:             dryrun
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.0
```

**Comment by bjorhn** [comment]
I'm getting the same problem. Tried in Chrome and also tried in a fresh install of Brave. I'm on Windows.
