### ISSUE TITLE
prefect deployment build should not upload data to the block 

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6376]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

Prefect deployment build should not upload data to the storage block. Instead this should be done by apply. 

```bash
prefect deployment build flow/test.py:test -ib s3/some_block
prefect deployment apply hello_world-depolyment.yaml  #updates the flow on prefect an uploads to s3 block
```
The yaml holds all the required information anyhow.

### Describe the current behavior

```bash
prefect deployment build flow/test.py:test -ib s3/some_block # uploads to s3
prefect deployment apply hello_world-depolyment.yaml #updates the flow on prefect
```

This feels very unintuitive - build should not deploy anything. 

With the current state it even feels like there is not even a need for two separate commands. As you always **have** to run apply after build - otherwise you end up with an inconsistent deployment.

**Comment by bunchesofdonald** [comment]
Thanks for the idea @felix-ht! I just wanted to let you know that this feature is available as of 2.3.0, you can now pass `--skip-upload` to the `build` command to have it skip uploading. The `--apply` option was added as well which lets you do  build and apply at the same time. https://docs.prefect.io/concepts/deployments/
