### ISSUE TITLE
DockerContainer block doesn't display all attributes

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6377]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

This could be some DB migration issue or block schema versioning issue, not sure

the problem is that the attributes in the Block definition don't match what's displayed in the UI - e.g. image pull policy is missing 
![image](https://user-images.githubusercontent.com/86264395/184162625-e43110fa-a50c-4dfe-b791-c046ecfbed0d.png)

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/infrastructure/docker.py#L166 

### Reproduction

N/A

### Error

N/A

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

2.0.4

### Additional context

n/a

**Comment by desertaxle** [comment]
Backend bug is being tracked in #6163

**Comment by desertaxle** [comment]
With the backend bug fix and blocks UI refactor, all fields for the DockerContainer block are now showing correctly.
