### ISSUE TITLE
Cannot change Workspace name

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6381]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I cannot change the name of my workspace.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/24698503/184171529-bbdf68b1-514d-460c-b72f-a47b4b919860.png">

### Reproduction

Try changing workspace name

### Error

Sorry, something went wrong updating workspace

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

cloud

**Comment by jakekaplan** [comment]
Hi @felix-ht, thanks for reporting this! It is now resolved. I'm going to close this this but please let us know if you still have issues.
