### ISSUE TITLE
Login information for a docker container should be stored in the block

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6396]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

Include the registry and login information in the docker container block.

### Describe the current behavior

Currently the assumption seems to be that one adds a separate `DockerRegistry` Block and uses that to login.

```
test_reg = await DockerRegistry.load("test_reg")
test_reg.login()
```

This however requires the flow to hold information about its deployment context - which usually is abstracted out into the `<flow_name>_deployment.yaml`

The current situation breaks this abstraction.

Instead of adding the password to the container block another option might be to add an option to the `build` command that allows adding a login block. 

`prefect deployment build ... --login-block docker-registry/foo`
or even
`prefect deployment build ... --storage-login-block docker-registry/foo`

### Additional context

@anna-geller follow up to slack

**Comment by felix-ht** [comment]
so if i have two registry blocks which one would get used?

**Comment by anna-geller** [comment]
you need to specify the relevant registry block on your docker-container block 

![image](https://user-images.githubusercontent.com/86264395/184343441-b137b1c9-c5a0-42dd-a068-6c561a569f8f.png)

**Comment by felix-ht** [comment]
ah thanks thats great - the option did not exist yesterday!
