### ISSUE TITLE
Diagnostics Rate Limit JSONDecode Error

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#6399]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If diagnostics are turned on and you get a rate limit, it ends up triggering a JSONDecodeError because the response is empty.

https://github.com/PrefectHQ/prefect/blob/4c363a2cde15d411bace54b8bb3d315c100f3807/src/prefect/client/client.py#L512-L517

<img width="373" alt="image" src="https://user-images.githubusercontent.com/104510333/184370948-8478d055-3dec-4593-9c9b-2999d76b93d4.png">

### Reproduction

```python
This happens when diagnostics are turned on and the rate limit for the GraphQL API gets hit.
10,000 req per 90 seconds
3,000 req per 3 seconds
```

### Error

```

File "/usr/local/lib/python3.9/site-packages/prefect/engine/cloud/flow_runner.py", line 188, in interrupt_if_cancelling
    flow_run_info = self.client.get_flow_run_info(flow_run_id)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 1246, in get_flow_run_info
    result = self.graphql(query).data.flow_run_by_pk  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 443, in graphql
    result = self.post(
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 398, in post
    response = self._request(
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 647, in _request
    response = self._send_request(
  File "/usr/local/lib/python3.9/site-packages/prefect/client/client.py", line 514, in _send_request
    self.logger.debug(f"Response: {response.json()}")
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

```
[2022-08-08 16:34:05+0000] WARNING - Diagnostics | Rate limit encountered (attempt 1); sleeping for 187.4598413938345s...
```

### Versions

```
Prefect 1.0

```

**Comment by johnurbanik** [comment]
Because this [gets called](https://github.com/PrefectHQ/prefect/blob/4c363a2cde15d411bace54b8bb3d315c100f3807/src/prefect/engine/cloud/flow_runner.py#L169-L188) within `check_for_cancellation`, which is used as a [context manager](https://github.com/PrefectHQ/prefect/blob/4c363a2cde15d411bace54b8bb3d315c100f3807/src/prefect/engine/flow_runner.py#L442) within `get_flow_run_state` , and the finally of `check_for_cancellation` contains
```
            done.set()
            thread.join()
```
it becomes the case that if there is an unhandled exception while running the flow or the flow finishes,  hit the finally and the threading event flag gets set (so it will exit immediately even if the wait timeout has not passed).

```

This puts the thread into an nearly infinite while loop
```
                while True:
                    exiting_context = done.wait(
                        prefect.config.cloud.check_cancellation_interval
                    )
                    try:
                        self.logger.debug("Checking flow run state...")
                        flow_run_info = self.client.get_flow_run_info(flow_run_id)
                    except Exception:
                        self.logger.warning(
                            "Error getting flow run info", exc_info=True
                        )
                        continue
```
Until the rate limit resets, we continuously hit `self.client.get_flow_run_info(flow_run_id)` which exacerbates the problem (unless requests while rate limited don't count toward the rate limit).

**Comment by madkinsz** [comment]
@abrookins we should fix this soon as it exacerbates rate limiting issues, I think we can probably just catch exceptions in the client during diagnostics?

Contributions on this are welcome.

**Comment by johnurbanik** [comment]
The screenshot that @robfreedyprovided  isn't quite correct - I realized later in digging in that the diagnostic logger doesn't have a CloudHandler so it's not directly exacerbating the rate limit. 

Catching exceptions seems like a good bandaid, but I think the additional issue with `check_for_cancellation` should also be addressed.

**Comment by cicdw** [comment]
Closing as stale and because Prefect 1.x is no longer under active development.
