### ISSUE TITLE
Documentation for virtual-environments is outdated 

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6410]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

https://docs.prefect.io/tutorials/_virtual-environments/  shows how to run code in a venv in a deployment 

### Describe the current behavior

https://docs.prefect.io/tutorials/_virtual-environments/#specifying-environment-paths references old removed code

**Comment by tpdorsey** [comment]
This outdated page has been removed from the docs.

**Comment by jeffsdata** [comment]
> This outdated page has been removed from the docs.

Is there new documentation for this? I can’t seem to find anything about this topic other than old docs and change notes.

**Comment by felix-ht** [comment]
Its actually pretty simple - for my poetry usecase

```python
DockerContainer(
        image=image_name,
        image_registry=image_registry,
        command=["poetry", "run", "python", "-m", "prefect.engine"],
        volumes=volumes,
)
```
Use can specify the command in Orion as well if you are not using python to build your blocks.

In the docker file do:
```dockerfile
RUN mkdir /workdir
COPY ./poetry.lock /workdir
COPY ./pyproject.toml /workdir
WORKDIR /workdir
RUN poetry env use 3.9
RUN poetry install --no-root --without dev
```


This will create a venv and only install the dependencies. The code will get pulled from whatever storage used use.
