### ISSUE TITLE
Prefect 1.0 DatabricksSubmitMultitaskRun uses flow id as idempotency token if not set causing unexpected behavior

### ISSUE THREAD

**Issue by edmondo1984** [PrefectHQ/prefect#6411]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

1.x

### Describe the proposed behavior

When submitting two tasks via DatabricksSubmitMultitaskRun in the same Prefect job, if the idempotency_token is not set, only the first one will be effectively executed because of this line:

https://github.com/PrefectHQ/prefect/blob/1.x/src/prefect/tasks/databricks/databricks_submitjob.py#L1066

Instead, the most natural behavior is to execute both

### Describe the current behavior

Only one of the two tasks is executed.

**Comment by edmondo1984** [comment]
This will be fixed with the first 1.x release

**Comment by madkinsz** [comment]
This is released in 1.3.1. Thanks!
