### ISSUE TITLE
client.create_deployment not working in master (API not accepting work_queue_name)

### ISSUE THREAD

**Issue by MiniEggz** [PrefectHQ/prefect#6440]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to use the apply function on a Deployment object created using Deployment.build_from_flow() method. When I try this, I get a 422, invalid request received with the exception details `[{'loc': ['body', 'work_queue_name'], 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}]`. 

I removed the work_queue_name argument from prefect.orion.schemas.actions.DeploymentCreate (line 64), prefect.client.OrionClient (lines 1292 and 1329), and prefect.deployments.Deployment (line 419) and everything works.

I'm assuming work_queue_name is a desired argument though. I will add the fix I got working for now that doesn't mess with the api but I don't think this is the optimal fix?

### Reproduction

```python
"""Create prefect deployments."""
from prefect import flow
from prefect.deployments import Deployment


@flow
def flow_method():
    """flow method."""
    print("hello")


deployment = Deployment.build_from_flow(
    flow=flow_method,
    name="flow-deployment",
)

deployment.apply()
```

### Error

```

Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['body', 'work_queue_name'], 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}],

```

### Versions

```

# Copy output of `prefect version` here
2.0.4+240.g6f6384d62

```

**Comment by MiniEggz** [comment]
I thought I could add a PR to get a quick fix in, didn't realise I couldn't. All the lines I commented out are still highlighted above for something that works quickly though. I also realise this isn't actually in a release yet so something might be on the way anyway :)

**Comment by zangell44** [comment]
Thanks for the report @MiniEggz!

As you mentioned, this functionality hasn't been released yet and is not yet available in Cloud 2. It will be available shortly! In general, I would advice against using `main` because of incompatibilities like this.

If you weren't using Cloud 2, then this sounds like a bug.
