### ISSUE TITLE
Customization for KubernetesJob Block are getting quoted as string and thus cannot be set correctly via UI

### ISSUE THREAD

**Issue by imsurat** [PrefectHQ/prefect#6460]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Tried with prefecthq/prefect:2.0.4-python3.9.

Might be related to Related https://github.com/PrefectHQ/prefect/issues/6079

Was able to PATCH it with API.

### Reproduction

1. Click on Blocks 
2. Click on + to Create New
3. Select KuberetesJob
4. Add name
5. Add customization
6. e.g `{"op": "add", "path": "/spec/ttlSecondsAfterFinished", "value": 600}`
7. Click save
8. Notice the customizations on the page, an additional quote has been added around the dict
9. Trying to create a deployment will fail with this Infrastructure Block

### Error

<img width="567" alt="image" src="https://user-images.githubusercontent.com/98421382/185275886-09d00917-2c55-4f75-b413-82bb0400a995.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/98421382/185275933-7b838a04-6b6b-4ad4-8b63-66889bfd3bea.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/98421382/185275999-eaf0286a-8610-4728-89d2-c4ead2b313a0.png">

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```

# Copy output of `prefect version` here if hosting your own UI

Version:             2.0.4                                                                                                                                                            
API version:         0.8.0                                                                                                                                                            
Python version:      3.9.13                                                                                                                                                           
Git commit:          39db6fb1                                                                                                                                                         
Built:               Wed, Aug 10, 2022 1:19 PM                                                                                                                                        
OS/Arch:             linux/x86_64                                                                                                                                                     
Profile:             default                                                                                                                                                          
Server type:         hosted                     

```

**Comment by anna-geller** [comment]
looks good now 
![image](https://user-images.githubusercontent.com/86264395/190382634-206e85ab-bf89-44bc-aad9-2fb31ec08f34.png)
