### ISSUE TITLE
Support flat mapping

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6462]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

We'd like to [flat map with DFE](https://medium.com/the-prefect-blog/map-faster-mapping-improvements-in-prefect-0-12-0-7cacc3f14e16) using Dask.

### Describe the current behavior

We currently do this in Prefect 1.x using [flatten](https://docs-v1.prefect.io/core/concepts/mapping.html#flat-mapping).

**Comment by madkinsz** [comment]
We don't support DFE yet and I don't think this will be meaningful until we do. At this point, it'd be equivalent to just unpack the result into your next mapping operation dynamically.

**Comment by madkinsz** [comment]
Separately, please provide a simple code example of how you'd like this feature to work to help us understand your use case.
