### ISSUE TITLE
Run state filter sometimes doesn't work

### ISSUE THREAD

**Issue by thelfensdrfer** [PrefectHQ/prefect#6480]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I have one "late" flow run but it is not displayed when I want to display only "late" flow runs.

![Screen Shot 2022-08-19 at 16 24 51](https://user-images.githubusercontent.com/699106/185640389-25a3413e-7956-429f-a5d1-aa8ecbc0afb3.png)
![Screen Shot 2022-08-19 at 16 25 17](https://user-images.githubusercontent.com/699106/185640394-8eaa39eb-ddd8-40bc-8855-f5503da7c48a.png)

Just as a side note: Would be great to get uniform colors/label for the run states in the dropdown and in the list below.

### Reproduction

/

### Error

/

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment]
Thanks @thelfensdrfer -a fix for the filter will be in the next release (which is today for Cloud UI).

**Comment by zhen0** [comment]
Nice point on the color match - Let's keep this ticket open for that request.
