### ISSUE TITLE
Orion UI Array not interpreted correctly

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#6481]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] #6882
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Currently, there is no way to add multiple values to the Array parameter neither it being interpreted as an array 

![image](https://user-images.githubusercontent.com/16452985/185641503-eb05d094-4a63-4fa3-aa74-98ef58ff76f5.png)

### Reproduction

```python
@flow 
def test(param: list[str]):
    pass
````

### Error

-

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Prefect version

```

Version:             2.1.0
API version:         0.8.0
Python version:      3.9.6
Git commit:          30ca715c
Built:               Wed, Aug 17, 2022 5:13 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.35.5
```

**Comment by zhen0** [comment]
Although perhaps not immediately clear this is a duplicate of https://github.com/PrefectHQ/prefect/issues/6287 - we're actively working on some updates to types in the blocks and parameter forms

**Comment by zhen0** [comment]
Actually - this has a fix incoming.

**Comment by i-sepulveda-reden-solar** [comment]
Hello,

Any update on this?

thanks
