### ISSUE TITLE
`prefect deployment build` silently accepts wrong block types 

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#6487]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deployment build silently completes but `flow-script-storage` is not an infrastructure block:

```sh
❯ prefect deployment build ./project/flow.py:my -n someflow -ib s3/flow-script-storage
Found flow 'my'
Deployment YAML created at '/Users/.../project/my-deployment.yaml'.
```

... so when the deployment's flow runs are submitted

we get an `AttributeError` in agent logs, 

`S3 object has no attribute env`

### Reproduction

```python
# create an s3 storage block `flow-script-storage`
# create a minimal flow `my`

prefect deployment build ./project/flow.py:my -n someflow -ib s3/flow-script-storage
```

### Error

not applicable, the issue is that there is no error

### Versions

```

Version:             2.1.1
API version:         0.8.0
Python version:      3.10.5
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             darwin/x86_64
Profile:             myplace
Server type:         hosted
```

**Comment by madkinsz** [comment]
Thanks for the issue! We need to introduce some utilities for block capability validation and enforcement.
