### ISSUE TITLE
Migration failure when connecting orion to a postgres database.

### ISSUE THREAD

**Issue by YasmineHamdy** [PrefectHQ/prefect#6499]
### Bug summary

i have followed this doc: [https://docs.prefect.io/concepts/database/](database) to change the database to Postgress. it failed to start the orion server and gives the following error.
<img width="1344" alt="Screen Shot 2022-08-20 at 5 36 53 PM" src="https://user-images.githubusercontent.com/17936964/185755048-58a8cc4a-2410-4300-88be-0c88cecc76ab.png">

### Reproduction

```python
export PREFECT_ORION_DATABASE_CONNECTION_URL="postgresql+asyncpg://postgres:yourTopSecretPassword@localhost:5432/orion"

prefect orion start
```

### Versions

Version:             2.1.1
API version:         0.8.0
Python version:      3.10.4
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         <client error>

**Comment by bunchesofdonald** [comment]
Hi @YasmineHamdy! I'm trying to re-create your issue locally and have been unable to do so. I'm spinning up a fresh Postgres 14 database in docker, setting the environment variable as shown and am able to connect to the db, run migrations and have a working Orion instance.

Can you provide details about the postgres server you're using?

**Comment by YasmineHamdy** [comment]
Hi @bunchesofdonald  thanks for your reply,

here are my database details,

`PostgreSQL 11.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit`

**Comment by bunchesofdonald** [comment]
Unfortunately, as noted in [our docs](https://docs.prefect.io/concepts/database/#database-versions) only Postgres 13.0 and newer are supported.
