### ISSUE TITLE
Navigate from the flow page to a flow's runs

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6502]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

A navigation path from a flow on the flow page to all its runs.

### Describe the current behavior

The flow page is useful because it provides a list of flows. But for a specific flow on the flow page there isn't a way to navigate to its flow runs.

Here's a video of a first time Prefect 2 user trying to get to flow runs via the flows page.

The user clicks on `increment` more than once expecting to see flow runs.
They later click on the activity section, again trying to see flow runs.

https://user-images.githubusercontent.com/125105/185791008-353cc06a-cf1e-460a-82dd-05af4fe511de.mp4

**Comment by zhen0** [comment]
Thanks for the feedback @tekumara and for the useful video! This gives us some good material to discuss.

**Comment by tekumara** [comment]
Resolved by [#6721](https://github.com/PrefectHQ/prefect/pull/6721) thank you! 🥳
