### ISSUE TITLE
Scheduler tries to run same task on all k8s pods with Process Infrastructure

### ISSUE THREAD

**Issue by AndrewRichardsCode** [PrefectHQ/prefect#6522]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

An auto-scheduled flow run will try to run a task on all Kubernetes agent pods simultaneously when using Process Infrastructure.   Each agent pod is running on its own node.  When manually running the flow through the UI, it properly schedules the task to one pod.  When auto-scheduling the flow run,  the UI thinks it is only running one task but attempts to run it on all pods as seen in the screenshots.  This occurs when using SequentialTaskRunner with Prefect Shell Task and Process Infrastructure.

<img width="811" alt="Screen Shot 2022-08-22 at 10 01 01 AM" src="https://user-images.githubusercontent.com/39568026/186173736-873c66aa-b7c9-46f6-bfe9-36e2fc52e95f.png">
<img width="792" alt="Screen Shot 2022-08-22 at 9 44 13 AM" src="https://user-images.githubusercontent.com/39568026/186173739-44cd0dc3-b085-4392-817d-94775e9c9e1b.png">

### Reproduction

```python
from prefect import flow, task, get_run_logger
from prefect_shell import shell_run_command
from prefect.task_runners import SequentialTaskRunner

@flow(name="test",task_runner=SequentialTaskRunner())
def hello_world():
    shell_cmd=shell_run_command.with_options(retries=10, retry_delay_seconds=600)
    shell_cmd(command="echo hello world!")
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```

### Versions

```
Version:             2.1.1
API version:         0.8.0
Python version:      3.7.13
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             linux/x86_64
Profile:             devops
Server type:         hosted

prefect shell version 0.1.1

```

**Comment by madkinsz** [comment]
Thanks for the report! This should be prevented by some orchestration rules, but it looks like something has gone awry.

**Comment by madkinsz** [comment]
This should be resolved in the latest release.

**Comment by AndrewRichardsCode** [comment]
This issue still occurs in version 2.4.2

**Comment by madkinsz** [comment]
@AndrewRichardsCode did you upgrade your server as well?

**Comment by AndrewRichardsCode** [comment]
Yes my agents are on version 2.4.2.  I'm using process infrastructure and replicating the agent pods in a single k8s deployment.  Each pod runs on it's own node.  The pods race to run the same task simultaneously.
