### ISSUE TITLE
Add test coverage for `prefect version` CLI command

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#6524]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

`prefect version` is currently not tested thoroughly. https://github.com/PrefectHQ/prefect/pull/6523 adds some tests for the output of "Server type". These tests can be used as a model for adding additional test coverage.

### Describe the current behavior

There are not comprehensive tests for this CLI command.

### Example Use

This will allow us to ensure that the version command behaves as expected in most circumstances. This is important for issues and bug reports.

**Comment by amrutha1098** [comment]
Hi @madkinsz , can i work on this issue ? I would like to contribute .

**Comment by madkinsz** [comment]
@amrutha1098 Definitely! Please use our `invoke_and_assert` utility. Let us know if you have questions.
