### ISSUE TITLE
Settings are missing from the API reference

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#6549]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The API reference for settings at https://docs.prefect.io/api-ref/prefect/settings/#prefect.settings.Settings should include all of the settings and their descriptions but they are not present. I believe this is also breaking all links to specific settings, e.g. https://docs.prefect.io/faq/?h=postgres#what-external-requirements-does-prefect-have

The original implementation at https://github.com/PrefectHQ/orion/pull/1014 was careful to ensure that settings were visible in the API reference.

### Reproduction

```python
See Prefect documentation build steps.
```

### Error

No error.

### Versions

N/A

**Comment by dylanmcreynolds** [comment]
Just another note, I was following this [document](https://docs.prefect.io/faq/?h=postgres#how-do-i-choose-between-sqlite-and-postgres). It would be pretty handy if this had a reference back to this documentation about construction the database connection string.

**Comment by madkinsz** [comment]
Yep that document is supposed to have a link but it's broken due to this issue.

**Comment by madkinsz** [comment]
@tpdorsey can you look into this? It's not easy to see setting help strings otherwise. If not, let me know and I'll find someone with some time.

**Comment by tpdorsey** [comment]
I think the issue is that the docstring for settings assignments needs to be specified as an attribute docstring. The parser can't read the description directly. I'll have a PR to demonstrate shortly.

https://peps.python.org/pep-0258/#attribute-docstrings
