### ISSUE TITLE
Adding additional parameters to flows and recreating the deployments does not reflect the new param in the UI

### ISSUE THREAD

**Issue by andnig** [PrefectHQ/prefect#6563]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When one creates a flow + deployment and afterwards adds an additional parameter to this flow and recreates the deployment, the new parameter is NOT reflected in the UI. 

### Reproduction

1. Create a flow with one or more parameters
2. Run ``prefect deployment build``
3. Add the parameter value to the deployment.yaml (this step can also be done with the UI - the bug is not related to adding the parameter here)
4. Run ``prefect deployment apply``
--> Up until here, everything is fine. The deployment is shown in the UI, with parameters + param values.

5. Add an additional parameter to the flow
6. Run ``prefect deployment build``
7. Add the new parameter value to the deployment.yaml
8. Run ``prefect deployment apply``
--> The deployment in the UI still only shows the old parameters - the newe parameter is not visible and you can't set values for it

### Error

The deployment in the UI still only shows the old parameters - the newe parameter is not visible and you can't set values for it

### Versions

```
Version:             2.2.0
API version:         0.8.0
Python version:      3.9.13
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             rm_dwh_200
Server type:         hosted
```

### Additional context

As a workaround, one can delete the first deployment and fully recreate one from scratch then the parameter is available.

**Comment by discdiver** [comment]
Noted by another user in community Slack and I was able to replicate.
