### ISSUE TITLE
Deployment builds in Windows have incorrect file paths for S3 storage

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#6580]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running the prefect deployment build command in Windows with an S3 storage block, the directory path for the flow files isn't recognized by S3 because of the backslash in the file path instead of the forward slash. 

![image](https://user-images.githubusercontent.com/104510333/186934291-f9f580d1-f536-49bc-8dc1-96fbf820b2e5.png)

### Reproduction

```python
prefect deployment build ./hello-world.py:flow_main --name "Robs test flow 2" -sb s3/robs-s3-block

Was able to reproduce this error on Windows 11 using Parallels.
```

### Error

```

No errors are thrown, see screenshot above

```

### Versions

```

Version:             2.2.0
API version:         0.8.0
Python version:      3.9.10
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         hosted

```
Also appears on 2.0.4

**Comment by madkinsz** [comment]
See also issue for GCS: https://github.com/PrefectHQ/prefect/issues/6276
