### ISSUE TITLE
Flow Runs Intermittently Failing Immediately After Launch w/ No Error Message

### ISSUE THREAD

**Issue by ilya-galperin** [PrefectHQ/prefect#6586]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We’re experiencing really strange behavior when creating a storage block and deployment using the Python Deployment object. When launching flow runs from the Cloud UI, some runs are picked up and run on our Kubernetes-hosted agent (using image `prefecthq/prefect:2.2.0-python3.10`), but subsequent flow runs will seemingly randomly go into a failed state almost instantly with no error message and never get picked up by the agent. I notice when our flow does successfully run, we get this warning message in the container’s log although I'm not sure this is related to the bug or something else entirely:

`/usr/local/lib/python3.10/site-packages/prefect/deployments.py:48: UserWarning: Block document has schema checksum sha256:0ec43f8010cee4adbf73aebcc58f1e45986d765c2a224dfc9cd5428f98c516f8 which does not match the schema checksum for class 'S3'. This indicates the schema has changed and this block may not load.
  storage_block = Block._from_block_document(storage_document)`

Deleting and re-creating the block and deployment will sometimes cause it to work again but again, only on an intermittent basis. The flow code itself does not touch or interact with Prefect block storage.

We started noticing this behavior when building deployments from an environment running Prefect version 2.1.1. After updating Prefect in this environment to 2.2.0, we receive the following error from the CLI (intermittently) and are seeing the same behavior.

`/my/local/path/.venv/lib/python3.8/site-packages/prefect/blocks/core.py:584: UserWarning: Block document has schema checksum sha256:0ec43f8010cee4adbf73aebcc58f1e45986d765c2a224dfc9cd5428f98c516f8 which does not match the schema checksum for class 'S3'. This indicates the schema has changed and this block may not load.`

I've attached images showing four flow runs being created within 5 seconds of each other from the same deployment using the Orion UI with 2 instantly failing and 2 running and completing.

![Screen Shot 2022-08-26 at 2 23 38 PM](https://user-images.githubusercontent.com/65326615/186997207-a81c1548-6e4c-4a6b-872f-01fc66230f0a.png)
![Screen Shot 2022-08-26 at 1 31 33 PM](https://user-images.githubusercontent.com/65326615/186997218-41ab8b2c-0d86-425e-9bda-8d94e322e13e.png)

### Reproduction

```python
# flow code
from prefect import flow, get_run_logger
@flow(name="flow_a")
def entrypoint(param1: str = "Goodbye", param2: str = "friends!"):
    """
    This flow does cool stuff.
 
    Args:
        - param_1: a closing statement
        - param_2: a subject to address
    """
    logger = get_run_logger()
    logger.info(f"{param1} {param2}")
if __name__ == "__main__":
    entrypoint()

# storage block code
def create_storage_block(bucket: str, flow: str) -> str:
    path = flow.replace("_", "-")
    block_name = f"{path}-code"
 
    AWS_ACCESS_KEY_ID = "XYZ"
    AWS_SECRET_ACCESS_KEY = "XYZ"
 
    block = S3(
        bucket_path=f"{bucket}/flows/{path}",
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    )
    block.save(block_name, overwrite=True)
    print(f"Storage block {block_name} created.")

# deployment code
def apply_deployment(config):
    name = config.get("name")
    description = config.get("description")
    tags = config.get("tags")
    infrastructure = _set_infrastructure(config)
 
    deployment = Deployment.build_from_flow(
        flow=entrypoint,
        name=name,
        description=description,
        version=GIT_SHA,
        work_queue_name=WORK_QUEUE,
        # tags=tags,
        storage=S3.load("flow-a-code"),
        infrastructure=infrastructure,
    )

    deployment.apply()
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```

### Versions

```

Version:             2.1.1
API version:         0.8.0
Python version:      3.8.9
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted

Version:             2.2.0
API version:         0.8.0
Python version:      3.8.9
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted

```

**Comment by madkinsz** [comment]
Thanks for the report! cc @desertaxle, I'm a little behind on the state of block checksums.

**Comment by ilya-galperin** [comment]
Just wanted to leave a comment that I am not positive this is related to block storage necessarily. Even when we create a brand new storage block, flow, and deployment for a flow we are seeing the same behavior on this new set of objects immediately. We kick off 5 flow runs from the new deployment/storage block, 3 succeed (they will create pods and execute normally) and 2 fail instantly even before the "progress wheel" in the Cloud UI completes -- they do not even seem to get into a scheduled state at all meaning the agent never has an opportunity to pick them up.

**Comment by ilya-galperin** [comment]
I've done some more testing and wanted to provide additional documentation.

For this test, I did not use the Python deployment or storage objects at all. I've created a brand new S3 storage block using the Cloud UI, then created a new flow and new deployment using the following CLI command:

`prefect deployment build flow.py:entrypoint -n another-dep -i kubernetes-job --storage-block s3/flow-d-code --override image=xxx.dkr.ecr.us-east-1.amazonaws.com/xxx:latest  --override namespace=xxx`

I then ran this deployment twice within 5 seconds. The first flow has been picked up by the agent and successfully runs and the second fails silently and immediately. There is no reference to the second flow run on in the agent logs, and the Warning message I was receiving yesterday on block schema checksum is no longer showing up in the successful flow run's container logs.

This is also making me think this issue is independent of storage blocks and also independent of building a deployment from Python vs. the CLI.

**Comment by anna-geller** [comment]
posting here for reference https://linen.prefect.io/t/2443544/MRE-minimal-reproducible-example-Thanks-for-the-GitHub-issue

**Comment by zangell44** [comment]
Is it possible the flow script is calling the flow function when attempting to run the deployment? (And therefore starting a bad flow run)

The failed run from 8/26, `quizzical-bustard`, for example, does not have a `deployment_id` associated with it and was not auto-scheduled. Did someone start this run manually?

**Comment by zangell44** [comment]
Thanks for clarifying!

> The first flow has been picked up by the agent and successfully runs and the second fails silently and immediately. There is no reference to the second flow run on in the agent logs,

Hmmm that's puzzling. It seems like the failures are happening when an agent tries to submit the flow run. An agent should produce a log indicating either successful or unsuccessful submission of a flow run. `vivid-avocet`'s error state has message indicating `"Submission failed."`.

Is there another agent running somewhere that's capable of picking up these runs?

**Comment by ilya-galperin** [comment]
@zangell44 I think you're onto something. We only have one agent running on Kubernetes and it uses the default work queue. I just restarted that agent and assigned a named queue to it `-queue2`. I then created a new deployment that also specifies this queue, and all flow runs seem to be succeeding now. Flows in the default work queue are continuing to fail silently. Would it be possible for an agent that is not on the Kubernetes infrastructure to try to pick up these flow runs? If so, the only other place we could have an agent with knowledge of our workspace's API key is on my own local dev environment which is authenticated with Prefect cloud through the CLI, but has never had a local agent running.

**Comment by anna-geller** [comment]
> Would it be possible for an agent that is not on the Kubernetes infrastructure to try to pick up these flow runs?

In theory yes, but if you e.g. start your agent as a local process and have a deployment with KubernetesJob block, it will not work, the agent would need to run on Kubernetes too. 

feel free to close this GitHub issue, If an explicit work queue solves it for you
