### ISSUE TITLE
Blocks: RemoteFilesystems `local_path` of `put_directory` has no effect

### ISSUE THREAD

**Issue by MarcelPa** [PrefectHQ/prefect#6603]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I created a RemoteFilesystem Block in the Prefect UI pointing to a local Minio Storage. I can read files from this Block without issues, the code snippet `load_data` posted below does give me a list of files contained in the bucket (as expected). However, writing to a block does not work as expected. When I execute the task `upload_data` as shown below, it will upload the current working directory instead of the path given to `local_path`. Given the description of `prefect.filesystems.RemoteFilesystem.put_directory()`, this is unexpected.

I think that I tracked down the bug in the code as well. The [glob to get a list of files to upload](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L324) has `'**'` hard-coded into it, where it should actually do something like `os.path.join(local_path, '**')`.

If interested, I can provide a PR - if this is a bug and not intentional. (the change is minimal however, so the whole process of opening an PR is maybe too much as well).

### Reproduction

```python
# Example task to read data from a bucket, works perfectly
@task
async def load_data():
    path = '/tmp/input'
    os.makedirs(path, exist_ok=True)
    remote_block = await RemoteFileSystem.load('input-data')
    await remote_block.get_directory(local_path=path)
    return os.listdir(path)

# Example task to write data to a bucket, does not work as expected
@task
async def upload_data():
    path = '/tmp/output'
    remote_block = await RemoteFileSystem.load('input-data')
    await remote_block.put_directory(local_path=path, to_path='s3://test-input-data/output/')
```

### Error

```

# there is no error output
```

### Versions

```
Version:             2.2.0
API version:         0.8.0
Python version:      3.10.6
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by bunchesofdonald** [comment]
Thanks for the report @MarcelPa!
