### ISSUE TITLE
Allow deployment build/apply without installing extra dependencies of the flow

### ISSUE THREAD

**Issue by andnig** [PrefectHQ/prefect#6613]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

It would reduce complexity, if for ```prefect deployment build/apply```, we only need the prefect package (and maybe prefect collections?) installed in the build environment. No external dependencies of the flow itself should be required. 

### Describe the current behavior

Currently, with ```prefect deployment build/apply```, you need ALL the external dependencies of the flow in the build environment. 
For example, if the flow uses the pip package ``sendgrid``, we need ``sendgrid`` installed in the build environment. It would reduce complexity of build/CI environments, if only the prefect package (+ maybe collection packages?) are needed during build.

**Comment by thomasfrederikhoeck** [comment]
In prefect 1.0 we managed to do this by building the docker image that run the flow and make it self-aware of the tags that we use for it with ARG and ENV. We then registered the flow/flows from inside that image. We also use it for running pytest inside the image. That way we can use the image as cache for fast CI/CD

**Comment by madkinsz** [comment]
Generally we need to inspect the flow to understand what parameters it accepts which requires executing the module it lives in — this tends to require most of the dependencies to be installed and is likely not changing anytime soon. We may explore this in the future.
