### ISSUE TITLE
REST API api/deployments/{id}/create_flow_run - Work Queue not getting from response to prefect

### ISSUE THREAD

**Issue by anat-medcase** [PrefectHQ/prefect#6619]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

REST API api/deployments/{id}/create_flow_run - Work Queue not getting from response to prefect

### Reproduction

1.create basic minimal flow
2.build and apply deployment
3.run deployment via rest api with empty body {} -> http://localhost:4200/api/deployments/aa64fe41-a2f2-43c3-80f8-38e9d5c1ad26/create_flow_run

### Error

Flow Run missing "Work Queue" (blank) thus will never run, remains PENDING
The work queue exist in the response but doen't make it back to prefect.

(Same deployment runs fine via python api)

### Versions

# Copy output of `prefect version` here

```Version: 2.2.0
API version: 0.8.0
Python version: 3.9.12
Git commit: https://github.com/PrefectHQ/prefect/commit/e3651362de734fd4a1e1816b465e0a8b0283039c
Built: Tue, Aug 23, 2022 2:18 PM
OS/Arch: linux/x86_64
Profile: default
Server type: hosted


### Additional context

_No response_

**Comment by anat-medcase** [comment]
21:40:59.317 | DEBUG   | prefect.client - Connecting to API at http://0.0.0.0:4200/api/
Version:             2.2.0
API version:         0.8.0
Python version:      3.10.4
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted

**Comment by madkinsz** [comment]
Hi! Could you please edit your original post to contain
- A minimum reproducible example. We need to have a simple way to recreate your issue to fix it.
- The error that you are seeing. We need the full output of the error in order to diagnose the issue
- The version blurb you posted in a follow-up comment

Can you also include the `prefect version` output on your hosted server?

**Comment by anat-medcase** [comment]
Reproduce:
1.create basic minimal flow
2.build and apply deployment 
3.run deployment via rest api with empty body {} -> http://localhost:4200/api/deployments/aa64fe41-a2f2-43c3-80f8-38e9d5c1ad26/create_flow_run

Error: 
Flow Run missing "Work Queue" (blank) thus will never run, remains PENDING
![image](https://user-images.githubusercontent.com/104829353/187610820-6e1b46ee-fe94-4b9b-abd7-36f01bc58b4f.png)

prefect version in docker image:
Version:             2.2.0
API version:         0.8.0
Python version:      3.9.12
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted

**Comment by anat-medcase** [comment]
FYI - same deployment runs fine via python api

**Comment by anat-medcase** [comment]
done

Anat Tal
Data Team
+972-51-2121375

**Comment by artem-extern** [comment]
@madkinsz the same issue is for this API call `POST http://localhost:4200/api/flow_runs/`. Checked in versions 2.3.0 and 2.3.1.

This API call doesn't accept anything related to a working queue so when it called a new `flow_run` is created with its `work_queue_name` field set to `null` and if an agent was started with `-q some_queue` parameter the created `flow_run` never runs.

The only workaround I found at the moment is using the deprecated `tags` mechanism.

**Comment by madkinsz** [comment]
@artem-extern The `flow_runs` route is for creating flow runs that are not associated with deployments (and consequently not work queues. As noted in @anat-medcase's descriptions, you need to use the deployment specific flow run creation route.

@anat-medcase we have explicit test coverage for the case you mention at https://github.com/PrefectHQ/prefect/blob/e842b0642834e1579de68a9f7a14af8f54cdd46c/tests/orion/api/test_deployments.py#L1184-L1186 with the assertion https://github.com/PrefectHQ/prefect/blob/e842b0642834e1579de68a9f7a14af8f54cdd46c/tests/orion/api/test_deployments.py#L1194

Can you please construct an _executable_ example that we can run to reproduce the issue against a local API?
