### ISSUE TITLE
UI task run input page is misleading

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#6627]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the proposed behavior

The task run inputs page should include a description of what contents are expected to appear. For example, clarifying that only relationships between tasks are tracked here.

In the future, Prefect should do some sort of minimal tracking of the actual data passed between tasks so it can be displayed in the UI. However, that feature should be a separate ticket.

Until then, we should explain what a user should expect to see on this page.

### Describe the current behavior

The task run page added in https://github.com/PrefectHQ/nebula-ui/pull/1538 / https://github.com/PrefectHQ/prefect/pull/6570 includes a task inputs tab. This tab does not include the input values to my task.

For a simple flow:
```python
import prefect
from prefect import flow, task, get_run_logger

@task
def log_task(name):
    logger = get_run_logger()
    logger.info("Hello %s!", name)
    logger.info("Prefect Version = %s 🚀", prefect.__version__)

@flow()
def log_flow(name: str):
    log_task(name)

log_flow("Marvin")
```

My task receives the value "Marvin" for the`name` parameter but this is not captured by the API.

<img width="932" alt="Screen Shot 2022-08-30 at 5 01 31 PM" src="https://user-images.githubusercontent.com/2586601/187551995-48c81e8c-1a47-4535-8c69-122ccacb32ed.png">

**Comment by zhen0** [comment]
I worry this might get overlooked as it has a ui label but the issue is actually coming from the api.  So updating the labels.  Let me know if you think it needs any ui action @madkinsz

**Comment by deklund-xilis** [comment]
Can someone clarify what the expected behavior is here? Is it expected in general that the Task Inputs should show the actual values that were passed into a task? Similarly, if a task has an output, is its value expected to show up in the interface?

**Comment by kelvindecosta** [comment]
The expected behavior would be for the API to account for the `dynamicKey` for the task.
AFAIK, this value identifies each mapped task, and as such could index the input values passed to the task

**Comment by madkinsz** [comment]
@zhen0 I feel like tracking the other types of inputs is a separate ticket. This is explicitly about the lack of context for what this is expected to contain. Notably https://github.com/PrefectHQ/prefect/issues/7547 incorrectly says

> Currently the task run page task input tab shows the correct keys but all values are empty. 

The values should not be empty if the task was passed a value from one or more upstream tasks. In that case, the upstream task run ids would be referenced in the list.

**Comment by madkinsz** [comment]
For example

```python

from prefect import flow, task


@task
def identity(x):
    return x


@flow()
def exampleflow():
    # Create some futures
    one = identity.submit(1)
    two = identity.submit(2)
    three = identity.submit(3)

    identity(one)
    identity([two, three])
    identity(1)
    identity([2, 3])


exampleflow()
```

Here's the task run that receives one upstream future for `x`

<img width="1342" alt="Screen Shot 2023-01-05 at 4 51 10 PM" src="https://user-images.githubusercontent.com/2586601/210895280-36c62abb-325f-4791-ba07-726d96152ddb.png">

Here's the task run that receives two upstream futures for `x`:

<img width="1342" alt="Screen Shot 2023-01-05 at 4 50 46 PM" src="https://user-images.githubusercontent.com/2586601/210895219-b478b2d6-cad6-4151-a662-bb7625cb40a4.png">

**Comment by zhen0** [comment]
Thanks @madkinsz - I'm adding back the needs triage label so that I can come back and triage this tomorrow.

**Comment by toro-berlin** [comment]
This topic came up in our team in a production debug scenario today. It would be a nice quick win to have a description here.

People, not that familiar with the internal Prefect mechanism get confused. In our case, the Prefect flow operators execute business deliveries with the flows. These are our primary stakeholders beneath the engineers implementing flows.

Thank you!

**Comment by madkinsz** [comment]
https://github.com/PrefectHQ/prefect/pull/8295 should have addressed this
