### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6628]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Unfortunately I do not have more information than what is provided in the "Error" section.

### Reproduction

```python
N/A
```

### Error

```bash
Crash detected! Execution was interrupted by an unexpected exception.
10:08:13 PM
Crash details:
Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 1237, in report_flow_run_crashes
    yield
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 360, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 556, in orchestrate_flow_run
    flow_run = await client.read_flow_run(flow_run.id)
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 1517, in read_flow_run
    response = await self._client.get(f"/flow_runs/{flow_run_id}")
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 280, in send
    response.raise_for_status()
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 226, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Server error '500 Internal Server Error' for url 'https://api.prefect.cloud/api/accounts/.../workspaces/.../flow_runs/...'
Response: {'exception_message': 'Internal Server Error'}
For more information check: https://httpstatuses.com/500
```

### Versions

```bash
Version:             2.2.0
API version:         0.8.0
Python version:      3.10.6
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by abrookins** [comment]
Hello, @mikkelduif! Thanks for opening an issue. I'd like to try and track down more information about this error. To do that, I'll need an exact date and time with the timezone. I see that the time of the error is in the output you posted ("10:08:13 PM"). Do you know which timezone that time is in, and the date?

**Comment by mikkelduif** [comment]
@abrookins :

`Aug 30th, 2022 10:08:13 PM Europe/Copenhagen`

**Comment by abrookins** [comment]
Thank you, @mikkelduif! I am investigating.

**Comment by abrookins** [comment]
This HTTP request failed due to what appears to be a rare (in the sense that we haven't seen it before or since) network condition that affected one of our API servers during the request. We are testing a change to make the server more resilient to this condition should it arise again.

I want to make sure you get timely support as a Prefect customer, and while you are welcome to open issues in this repository, I also want to share our support email address (help@prefect.io) as another avenue that you can use to reach out. Engineers actively work to triage issues in this repository, but we may not be able to reply promptly in all cases.
