### ISSUE TITLE
RuntimeError after running 'prefect deployment apply' on Windows with Azure Storage

### ISSUE THREAD

**Issue by rpeden** [PrefectHQ/prefect#6638]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running `prefect deployment apply` to apply deployment YAML on Windows 11, I got a RuntimeError as the CLI was exiting. It happened _after_ the deployment was applied, so the deployment completed as expected. However, since the error is the last thing the user sees, it may cause them to think the deployment failed.

Note that although I checked the box above, it appears that the issue _is_ related to one of Prefect's dependencies, specifically [this aiohttp issue](https://github.com/aio-libs/aiohttp/issues/4324). However, it looks like something we can address because per that issue discussion thread, it appears that there are some workarounds available.

### Reproduction

```python
* Create an Azure blog storage block via the Prefect Cloud UI (named "azure-blob-storage" in this example)
* Add the following code to flow.py:

from prefect import flow, task

@task
def say_hello(name):
    print(f"hello {name}")

@task
def say_goodbye(name):
    print(f"goodbye {name}")

@flow(name="test flow")
def greetings(names=["arthur", "trillian", "ford", "marvin"]):
    for name in names:
        say_hello(name)
        say_goodbye(name)


* Then, run the following command:

prefect deployment build -sb "azure/azure-blob-storage" -q testing --name "windows test deployment" "flow.py:greetings"

* Then, run:

prefect deployment apply greetings-deployment.yaml
```

### Error

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021BE1E174C0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Versions

```
Version:             2.3.0
API version:         0.8.0
Python version:      3.9.7
Git commit:          8d9316c0
Built:               Tue, Aug 30, 2022 5:30 PM
OS/Arch:             win32/AMD64
Profile:             ryan
Server type:         cloud
```

**Comment by bunchesofdonald** [comment]
This is also happening with the `prefect deployment run` command.

**Comment by rpeden** [comment]
Fixed upstream in aiohttp. I don't see this error on Windows anymore.
