### ISSUE TITLE
Prefect 2 agents running on Windows cannot download flows that use GitHub storage

### ISSUE THREAD

**Issue by rpeden** [PrefectHQ/prefect#6642]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running a Prefect 2.3.0 agent on Windows, any deployed flows that use GitHub storage will fail when the agent tries to pull the flow code from GitHub with the following message: `OSError: Failed to pull from remote:
 'g' is not recognized as an internal or external command,
operable program or batch file.`

I tested and verified that this occurs on Windows 10 and 11. Due to the cause of the problem (noted in the additional context section below), I expect it will also occur on any Windows version where a Prefect-compatible Python version will run, i.e. Windows Vista to Windows 11, and Windows Server 2016 to 2022. 

### Reproduction

```python
* Create a GitHub storage block in Prefect Cloud named 'example' using Python or via the UI in Prefect Cloud or Orion.
* Add the following to flow.py:

from prefect import flow

@flow
def test_flow(name="GitHub Storage Flow"):
  print("A Windows agent won't be able to pull this code.")


Next, create a deployment by running:

prefect deployment build -sb "github/example" -q github --name "GitHub storage deployment" "flow.py:test_flow"

Then, apply the deployment:

prefect deployment apply test_flow-deployment.yaml

Then, on a Windows machine, start a Prefect agent:

prefect agent start -q github

Then, use the Cloud UI to manually trigger a flow run and you will see the error described in the previous section.
```

### Error

```
19:13:38.217 | ERROR   | Flow run 'tangible-polecat' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\prefect\engine.py", line 256, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "C:\Python39\lib\site-packages\prefect\client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\Python39\lib\site-packages\prefect\deployments.py", line 54, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "C:\Python39\lib\site-packages\prefect\filesystems.py", line 797, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 'g' is not recognized as an internal or external command,
operable program or batch file.
```

### Versions

```
Version:             2.3.0
API version:         0.8.0
Python version:      3.9.7
Git commit:          8d9316c0
Built:               Tue, Aug 30, 2022 5:30 PM
OS/Arch:             win32/AMD64
Profile:             ryan
Server type:         cloud
```

### Additional context

It appears the error on Windows begins on [line 789](https://github.com/PrefectHQ/prefect/blob/f9d609ae80a7e166ccd4a8f69ea111d4a999c6c3/src/prefect/filesystems.py#L789) of `filesystems.py` when we pass a string as the first argument to `run_process` instead of a list of strings:

```
768   cmd = "git clone"
...   append additional things to string
789   process = await run_process(cmd, stream_output=(out_stream, err_stream))
```

This ultimately leads to a call to `open_process` in `utilities/processutils.py`, which does the following starting on [line 22](https://github.com/PrefectHQ/prefect/blob/f9d609ae80a7e166ccd4a8f69ea111d4a999c6c3/src/prefect/utilities/processutils.py#L22):

```
# Passing a string to open_process is equivalent to shell=True which is
# generally necessary for Unix-like commands on Windows but otherwise should
# be avoided
if sys.platform == "win32":
    command = " ".join(command)
```

This runs if you give it a string instead of a list of strings, but does not have the intended effect. Instead of combining a list containing a command and arguments into a string, it adds an extra space between every character in the string. 

So, for example, 
```
git clone https://github.com/person/myrepo
```
becomes:
```
g i t   c l o n e   h t t p s : / / g i t h u b . c o m / p e r s o n / m y r e p o
```
which causes the error observed when the agent tries to pull a GitHub flow on Windows.

**Comment by peytonrunyan** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/7372
