### ISSUE TITLE
Add `ttlSecondsAfterFinished` support to `KubernetesJob`

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#6658]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

No jobs created by the `KubernetesJob` infrastructure type are cleaned up yet.

### Describe the proposed behavior

Infrastructure blocks should generally allow automated cleanup of created resources.

Adding `ttlSecondsAfterFinished` to the job `spec` will facilitate automatic removal of completed jobs. This is especially nice as we do not need to manage removal ourselves.

Users can already add this via a `customizations`. Separately, this feels important enough to add a top-level shortcut for. Perhaps as `finished_job_ttl: int`.

### Example Use

```python
KubernetesJob(finished_job_ttl=300)
```

### Additional context

Replaces https://github.com/PrefectHQ/prefect/issues/5857

**Comment by meehawk** [comment]
@madkinsz can I take this up?

**Comment by madkinsz** [comment]
Yeah definitely! Let me know if you have any questions. One minor concern is that I'm not sure which Kubernetes versions support this.; it'd be good to include that as a note in the pull request and docstring if it's not the current lts version.

**Comment by madkinsz** [comment]
@hallenmaia great thanks! Looks like this is the ideal hook for us then.

**Comment by meehawk** [comment]
@madkinsz can you guide me through what would be a good step to start

**Comment by madkinsz** [comment]
Sure, you'll want to:

- Add a `job_ttl_finished_seconds` field like https://github.com/PrefectHQ/prefect/blob/c2a76aa57fee8326de0883f1ed708878072eeba9/src/prefect/infrastructure/kubernetes.py#L102-L104 
    - We'll want it to be `Optional[int]` to allow it to be null. When null, the field should be excluded from the template.
- Add a handler to set it in the job specification at https://github.com/PrefectHQ/prefect/blob/c2a76aa57fee8326de0883f1ed708878072eeba9/src/prefect/infrastructure/kubernetes.py#L262
- You may need to add a value for it in the base template to allow it to be patched, but probably not https://github.com/PrefectHQ/prefect/blob/c2a76aa57fee8326de0883f1ed708878072eeba9/src/prefect/infrastructure/kubernetes.py#L165-L172
- Add a test demonstrating that the value is set, similar to https://github.com/PrefectHQ/prefect/blob/c2a76aa57fee8326de0883f1ed708878072eeba9/tests/infrastructure/test_kubernetes_job.py#L317-L331
- Add a test demonstrating that the field is gone when `None`.

**Comment by hallenmaia** [comment]
@meehawk I have this in my dev env. Do you mind if I send the PR?
@madkinsz I can contribute to this?

**Comment by meehawk** [comment]
> @meehawk I have this in my dev env. Do you mind if I send the PR? @madkinsz Can I contribute to this?

sure @hallenmaia happy to toss it over if you've already have it working
