### ISSUE TITLE
Add https_proxy support for prefect agent

### ISSUE THREAD

**Issue by gabcoyne** [PrefectHQ/prefect#6661]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There is no documentation for proxy configuration on prefect. Proxy configuration can be implemented outside of prefect. As prefect is often the only service on an instance that requires internet, especially open internet access it is common to require HTTPS traffic to use a proxy. 

### Describe the proposed behavior

Implementing Proxy configuration would be advantageous to enterprise customers. Clear proxy support for Prefect agents that would

**Comment by madkinsz** [comment]
Can you add some additional details about what this would look like in practice? Can't you just set the `PREFECT_API_URL` to point to your proxy?

**Comment by gabcoyne** [comment]
httpx supports a bunch of proxy settings, so I think we cover this but need documentation, will get with Terry on it.
