### ISSUE TITLE
GitHub Storage for Private Repos

### ISSUE THREAD

**Issue by samgarvis** [PrefectHQ/prefect#6669]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, 2.0 GitHub Storage Block provides read-only for only public repos. 
In 1.0, you can pass in a token when registering the flow, so that the agent has proper access to read from the private git repo.

### Describe the proposed behavior

I would like this to be available for private repos as well. 
I would imagine that many other companies have this same issue due to privacy concerns.

### Example Use

Our company will not make our Git repositories public. We would prefer to use GitHub storage over GCS, so if this feature is added, we can start using GitHub storage again.

### Additional context

I know this is a feature in 1.0, so hopefully, adding it to 2.0 won't be too difficult.

**Comment by madkinsz** [comment]
Hi! I believe this work is planned for the near future.

**Comment by acookin** [comment]
We have temporarily enabled this by using a repo url that looks like `https://${PERSONAL_ACCESS_TOKEN}@github.com/projslug/repo.git`

The access token shows up in plaintext in the UI which is not great, but it "works"
