### ISSUE TITLE
Secret is partially visible

### ISSUE THREAD

**Issue by emkademy** [PrefectHQ/prefect#6707]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I used Secret Block on Prefect Cloud to store a secret, and its value is partially visible.

### Reproduction

1. Sign in to Prefect Cloud
2. Click "Blocks" from side menu
3. Click "+" button in order to add a new Block
4. Click "Add +" button under "Secret"
5. Write Block name
6. Write Value

### Error

![image](https://user-images.githubusercontent.com/83173240/188316397-1ae63fcc-0102-43c0-bb05-4398d53520bf.png)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by madkinsz** [comment]
Hi! For long secrets we include a small portion of the value to help with identification.

**Comment by jefflaporte** [comment]
I concur with [emkademy](https://github.com/emkademy).

This is really bad for multiple reasons.

1. Secrets are secret. I don't need help with remembering what they're set to but I do need them to stay secret.
2. Why does the UI have permission to load a decrypted secret at all?
3. This is a problem for several flavours of audit compliance.

As-is, the standard Secret block is unusable.

Also potentially worrying:

The documentation on creating new block types [advises to use SecretStr to prevent displaying values in the UI](https://docs.prefect.io/concepts/blocks/#secret-fields). It’s not clear to me if the same issue of partial secret disclosure will arise for custom blocks using SecretStr values…

Question: For custom blocks using SecretStr:
1. Will these values ever display even partially in the UI or in logs?
2. Does the UI code have unencrypted access to these values?

**Comment by madkinsz** [comment]
> Why does the UI have permission to load a decrypted secret at all?

This is not a UI feature. This representation is returned by the API and is implemented for all block documents (which includes custom blocks). See the implementation in [schemas/core.py](https://github.com/PrefectHQ/prefect/blob/0c14eefc6b1a4bf438035277c5b8a5b322beddde/src/prefect/orion/schemas/core.py#L577-L592).

The UI is running in your browser and I believe it is making requests with the permissions of your account. The UI code isn't running on Prefect's servers per-say. @abrookins and @cicdw  can address any further questions on the security aspects of this.

@billpalombi leads our product team and will use the feedback here and other channels to decide if we want to keep this behavior, remove it, or make it configurable per workspace.

Original change in https://github.com/PrefectHQ/orion/pull/2359

**Comment by madkinsz** [comment]
After much internal discussion we are going to obfuscate the entire secret for now. See #6846. We believe that partial views of the secret will be helpful to some users and are very likely to add an option to enable this feature again in the future.

**Comment by jefflaporte** [comment]
@madkinsz Thanks to you and the Prefect team for addressing this 🙏
