### ISSUE TITLE
Add a SecretJson / SecretDict type similar to SecretStr in Pydantic

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#6735]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, we have this implementation in prefect-gcp:
```
class GcpCredentials(Block):
    ...
    service_account_info: Optional[Union[Dict[str, str], Json]] = None
```

Logging/printing the credentials shows the entire secret.

Han also asked about this when he was developing prefect-fugue:
https://github.com/fugue-project/prefect-fugue/blob/master/prefect_fugue/blocks.py#L43-L47

Although it's a SecretStr, it still shows in the UI
![image](https://user-images.githubusercontent.com/15331990/188993341-5377101a-1e35-49f7-aa6a-98d31e9c0a02.png)

### Describe the proposed behavior

Ideally:
```
class GcpCredentials(Block):
    ...
    service_account_info: Optional[Union[SecretDict[str, str], SecretJson]] = None
```
Or:
```
    secret_conf: Optional[SecretDict[str, str]] = Field(
        default=None,
        alias="secret_config",
        description="A JSON-dict-compatible value",
    )
```
And the secret values would be obscured.

**Comment by goodwanghan** [comment]
Thank you!

**Comment by billpalombi** [comment]
Thank you for addressing this. This behavior looks good to me.

**Comment by jakekaplan** [comment]
I am pretty certain this has been fixed already, could someone confirm>?

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L514-L517

<img width="440" alt="Screen Shot 2022-10-31 at 1 16 56 PM" src="https://user-images.githubusercontent.com/40362401/199068920-75e48c40-410c-4008-bb7e-5d4dca6b7f92.png">

**Comment by ahuang11** [comment]
Thanks for checking in.

However, I think although [GCS uses `SecretStr`](https://github.com/PrefectHQ/prefect/blob/55d77b5f93dfeb5e87c0f27e93a8a403e277d9b1/src/prefect/filesystems.py#L514), this issue is requesting a new data type like `SecretDict`, for like [`GcpCredentials`](https://github.com/PrefectHQ/prefect-gcp/blob/main/prefect_gcp/credentials.py#L88) and [Fugue](https://github.com/fugue-project/prefect-fugue/blob/master/prefect_fugue/blocks.py#L43).
