### ISSUE TITLE
Markdown for deployment description

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6738]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently anything passed as the description of a flow is treated as plain text. 

### Describe the proposed behavior

It would be great if you would support markdown for the description of deployments. This enables descriptions that are much easier to read - thanks to the rich formatting provided by markdown.

### Example Use

```python
@flow(..., description="""
<!-- format: markdown -->

# My Great Flow

Some text ...

""")
def some_flow():
    ...

```

adding some tag like the` <!-- format: markdown -->` might be useful to indicate that the following text is to be treated as markdown

**Comment by bunchesofdonald** [comment]
Thanks for the idea @felix-ht!

**Comment by madkinsz** [comment]
I think we could probably default to rendering descriptions as markdown? I believe this is what we did in v1.

**Comment by zhen0** [comment]
Updating to medium as it's one we've been discussing (but adding the caveat that it's not a simple piece of work).

**Comment by Ogaday** [comment]
I'd prefer to have an additional option in the API/UI describing how to render the flow description rather than inline tags in the docstring. That way we can check a box and the whole docstring is parsed as markdown.

As most descriptions are drawn from docstrings, it would be really nice if sphinx/numpydoc rst was supported too :) Initially I think a "raw" representation (where the description is presented monospaced without newline stripping) would be useful to a lot of users too.

**Comment by madkinsz** [comment]
I think we will default to markdown and if we support other types in the future we ca add a `description_content_type` or something. rst support in the UI is unlikely, we may be able to convert to markdown client-side though.

**Comment by Wingmore** [comment]
Just curious, what is the status on this? It doesn't seem intuitive to have newlines and tabs stripped...

**Comment by corris** [comment]
I concur.  Please parse markdown in flow/deployment description.

**Comment by tadejsv** [comment]
Would be great if this was enabled.

**Comment by discdiver** [comment]
Closing as works on 2.10. Thanks @bowstopher!
