### ISSUE TITLE
Orion UI hide scheduled runs by default or add shortcut to select all

### ISSUE THREAD

**Issue by LukasK13** [PrefectHQ/prefect#6788]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently by default all run states are shown in the orion UI. When a flow is scheduled, the UI is spammed by a lot of scheduled flows and prevents to see the latest run results on a first glimpse. Selecting all but `scheduled` as run results to show takes 7 clicks and is reset as soon as the page is reopened.

### Describe the proposed behavior

Either hide runs with the state `scheduled` by default or add an option to select all run states such that all run states can be selected at once and afterwards `scheduled` can be unselected (saves at least some clicks). I prefer the first option.

**Comment by voidel** [comment]
Just bumping to show my support for a resolution to this. We're pretty heavy users of Prefect 1.0 with hundreds of scheduled flow runs for day. 1.0 had a great landing page which showed currently running flow runs separate to those scheduled. Now during the migration to Orion, the 2.0 UI has no such dashboard, and it takes a bunch of clicks to see what we really want to.

1. Currently running flows.
2. Recent flows that failed.
3. The next 5 or so upcoming flows.

Currently there is a massive list of scheduled runs extending to 24hrs ahead above what we really want to see when we land on the homepage.

**Comment by zhen0** [comment]
Saved views in the ui should allow you to customize what is shown in the flow runs page - you can filter by only running, only certain flows etc. We plan to add the ability to set relative time filters there too.

**Comment by voidel** [comment]
That looks very useful, thank you for the insight.
