### ISSUE TITLE
Add the ability to edit the flow run notification message template from the UI

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#6807]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently notifications created by the UI only offer the ability to send the default message. 

### Describe the proposed behavior

#6798 adds the ability to add a flow run url to a flow run notification message and also updated the default message.  We should make use of that default message to add the ability to template a message from the UI using the default message as a placeholder/example. 

### Example Use

Users could decide they want to add different information using the available inputs at https://github.com/PrefectHQ/prefect/pull/6798/commits/09ee1b8a6dcd5204f40541db598d4ce269007381 or they could simply change the wording of the message that gets sent as part of their notification.

**Comment by pleek91** [comment]
@zhen0 i think the slack block could be updated to add a message field couldn't it? Idk that this is a UI specific problem.

**Comment by madkinsz** [comment]
The API separates the notification block from the policy that sends the notification. This allows a single notification block to be reused for different types of notification policies. The message is specific to the policy, e.g. a failed flow run is a different message than a stalled agent.

**Comment by zhen0** [comment]
As Michael notes, this ticket is to make the most of the message option in the create-flow-run-notification-policy api route.

**Comment by zhen0** [comment]
I think the need for this will be removed with upcoming updates to notifications/
