### ISSUE TITLE
Use a Different API for Docker-Based Deployment

### ISSUE THREAD

**Issue by khuyentran1401** [PrefectHQ/prefect#6812]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I’m trying to use GitHub as a storage and Docker container as an infrastructure. It works when using Prefect Cloud, but doesn’t work when using Prefect Orion. 
<details>
  <summary>Full error</summary>

  ```bash
17:02:46.645 | INFO    | prefect.agent - Submitting flow run '7fd49764-045f-4c68-a071-2470a1cf2070'
17:02:46.835 | INFO    | prefect.infrastructure.docker-container - Creating Docker container 'zircon-ant'...
17:02:46.906 | INFO    | prefect.infrastructure.docker-container - Docker container 'zircon-ant' has status 'created'
17:02:47.230 | INFO    | prefect.agent - Completed submission of flow run '7fd49764-045f-4c68-a071-2470a1cf2070'
17:02:47.286 | INFO    | prefect.infrastructure.docker-container - Docker container 'zircon-ant' has status 'running'
22:03:16.533 | ERROR   | prefect.engine - Engine execution of flow run '7fd49764-045f-4c68-a071-2470a1cf2070' exited with unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/client.py", line 1516, in read_flow_run
    response = await self._client.get(f"/flow_runs/{flow_run_id}")
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/prefect/client.py", line 279, in send
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/prefect/client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '404 Not Found' for url 'http://ephemeral-orion/api/flow_runs/7fd49764-045f-4c68-a071-2470a1cf2070'
Response: {'detail': 'Flow run not found'}
For more information check: https://httpstatuses.com/404
  ```
</details>
This is because Prefect uses an ephemeral API by default, and a docker-based deployment can't run with an ephemeral API. 

The error disappears when we set `PREFECT_API_URL=http://127.0.0.1:4200/api` with:
```bash
prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
````
This behavior confuses users who use Prefect Orion and creates a deployment with Docker. 

### Describe the proposed behavior

The default `PREFCT_API_URL` for docker-based deployment should be `http://127.0.0.1:4200/api` if no value is set.

**Comment by madkinsz** [comment]
I do not believe this would solve the user-experience issue. If they're using the ephemeral API, it will still fail to contact an API on localhost. I think this should primarily be addressed through documentation, but we could also update the `Infrastructure.prepare_for_flow_run` to throw an error if the `PREFECT_API_URL` is not set for these infrastructure types.

**Comment by ahuang11** [comment]
Any ideas if this is related?
https://github.com/PrefectHQ/prefect-dask/issues/26#issuecomment-1246043380

**Comment by madkinsz** [comment]
> "Is it expected that using Prefect Orion locally would have trouble scheduling tasks on a remote cluster? On a high-level that makes sense, but I didn't see anything in the docs to this point."

If your local API cannot be contacted by tasks on a remote cluster, they will not be able to run as they cannot be orchestrated. This is also expected but not clearly documented yet.
