### ISSUE TITLE
Prefect orion start throws error on Windows 11

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#6817]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running `prefect orion start` on Windows 11, an error is thrown ending with "Orion stops"

### Reproduction

```python
prefect orion start <-- running that on Windows Command Prompt
```

### Error

```

C:\Users\rob.freedy>prefect orion start

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



INFO:     Started server process [3388]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 4200): only one usage of each socket address (protocol/network address/port) is normally permitted
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
Orion stopped!


```

### Versions

```

Version:             2.4.0
API version:         0.8.0
Python version:      3.9.10
Git commit:          513639e8
Built:               Tue, Sep 13, 2022 2:15 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud

```

**Comment by madkinsz** [comment]
@robfreedy the error is

> [Errno 10048] error while attempting to bind on address ('127.0.0.1', 4200): only one usage of each socket address (protocol/network address/port) is normally permitted

Looks like you've already got a service on that port. Did you make sure that your old Orion processes were killed? There was a recently fixed bug fix for that in #6672

**Comment by discdiver** [comment]
Looks like we can close this, no?

**Comment by robfreedy** [comment]
Yep we can close this! Apologies for not responding
