### ISSUE TITLE
Only one default parameter is deployed when multiple are specified (in deployment.py)

### ISSUE THREAD

**Issue by rainermensing** [PrefectHQ/prefect#6827]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am scheduling a dbt flow with Prefect. I tried to specify two parameters in my deployment.py file, but only the first of them is stored in the database after deployment. I have not tried deployment via CLI/yaml yet, but though this is already worth mentioning.

### Reproduction

```python
# deployment.py

from dbt_debug import dbt_debug_flow
from prefect.deployments import Deployment

deployment = Deployment.build_from_flow(
    flow=dbt_debug_flow,
    description ="Testing a prefect-based dbt workflow.",
    name="dbt-debug-test",
    parameters={'file_path': 'C:/Users/Public/File',
                'project_dir':'C:/Users/User/Documents/Git/Project/dbt_dev'},
    infra_overrides={"env": {"PREFECT_LOGGING_LEVEL": "DEBUG"}},
    work_queue_name="test",
)

if __name__ == "__main__":
    deployment.apply()


# deploy via python deployment.py
```

### Error

# On Prefect Orion
![image](https://user-images.githubusercontent.com/31634583/190200767-2055bc90-a4fe-4c14-921c-6066850e9a92.png)

```
Flow run 'cuddly-lyrebird' - Validation of flow parameters failed with error: SignatureMismatchError("Function expects parameters ['file_path'] but was provided with parameters ['file_path', 'project_dir']")
```

### Versions

```


Version:             2.4.0
API version:         0.8.0
Python version:      3.10.7
Git commit:          513639e8
Built:               Tue, Sep 13, 2022 2:15 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by madkinsz** [comment]
It'd be great to know if this is a UI or API issue by checking if the deployment has all of the parameters in the API. 

You should be able to look at the deployment by running (substitute your names)

```
prefect deployment inspect {flow_name}/{deployment_name}
```

Or by running the server then navigating to [the URL](https://docs.prefect.io/api-ref/rest-api/#/Deployments/read_deployment_by_name_deployments_name__flow_name___deployment_name__get) for your deployment:

```
http://localhost:4200/api/deployments/name/{flow_name}/{deployment_name} 
```

**Comment by rainermensing** [comment]
> 


> Hi! It'd be great to know if this is a UI or API issue by checking if the deployment has all of the parameters in the API.
> 
> You should be able to look at the deployment by running (substitute your names)
> 
> ```
> prefect deployment inspect {flow_name}/{deployment_name}
> ```
> 
> Or by running the server then navigating to [the URL](https://docs.prefect.io/api-ref/rest-api/#/Deployments/read_deployment_by_name_deployments_name__flow_name___deployment_name__get) for your deployment:
> 
> ```
> http://localhost:4200/api/deployments/name/{flow_name}/{deployment_name} 
> ```

@madkinsz 
Hi, please see the output below. It seems like it's missing in parameter_openapi_schema


```json
{
    'id': 'd263988e-8598-4914-9fa3-54f0214418a0',
    'created': '2022-09-14T14:58:27.685148+00:00',
    'updated': '2022-09-14T15:20:42.922332+00:00',
    'name': 'dbt-debug-test',
    'version': '933233a73a71bf3a1a99097ce6bd5ab6',
    'description': 'Testing a prefect-based dbt workflow.',
    'flow_id': 'd63d7e3b-af86-414d-bb7c-487b66426215',
    'schedule': None,
    'is_schedule_active': True,
    'infra_overrides': {'env': {'PREFECT_LOGGING_LEVEL': 'DEBUG'}},
    'parameters': {
        'file_path': 'C:/Users/Public/File',
        'project_dir': 'C:/Users/User/Documents/Git/Project/dbt_dev'
    },
    'tags': [],
    'work_queue_name': 'test',
    'parameter_openapi_schema': {
        'title': 'Parameters',
        'type': 'object',
        'properties': {'file_path': {'title': 'file_path'}},
        'required': ['file_path']
    },
    'path': 'C:\\Users\\User\\Documents\\Git\\Project\\Prefect',
    'entrypoint': 'dbt\\dbt_debug.py:dbt_debug_flow',
    'manifest_path': None,
    'storage_document_id': None,
    'infrastructure_document_id': '052a4e08-0356-444b-9d5d-f2c9db7d7328',
    'infrastructure': {
        'type': 'process',
        'env': {},
        'labels': {},
        'name': None,
        'command': None,
        'stream_output': True,
        'block_type_slug': 'process'
    }
}

```

**Comment by rainermensing** [comment]
@madkinsz Sorry I found the error! It was totally on me. I did not specify the 'project_dir' parameter in my dbt_debug_flow function in dbt_debug.py.
