### ISSUE TITLE
Add tags to environments and/or flows

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#683]
Following a discussion with @cicdw, it would be useful to add tags to environments which would allow more selective pulling by various agents.

For example, a `Agent` looking for Kubernetes-compatible environments could only pull environments with tags matching `kubernetes`, which is a better approach than forcing the agent to match Environment class names (especially because that prevents creating new environments after the agent is launched).

Furthermore, this could be overloaded for resource / cluster selection -- an environment might be tagged with "GPU", and an agent on a GPU-enabled cluster might pull that environment.

This GPU example leads to a follow up:
- tags can be used inclusively (an agent only pulls environments with "GPU")
- can tags be used exclusively (an environment refuses to be pulled by an agent not looking specifically for GPU?)

Lastly, can Flows be tagged regardless of the environment?

cc @joshmeek

**Comment by cicdw** [comment]
Closed via https://github.com/PrefectHQ/prefect/issues/1438 and https://github.com/PrefectHQ/prefect/pull/1442
