### ISSUE TITLE
UI: Reports about past and scheduled flow runs

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#6830]
**Why**
It's helpful for users and managers to see and share reports and data about past and scheduled flows.

**What**
As a user I want to be able to see aggregate information about flows in the UI. For example:
- how many flows succeeded and failed?
- what percentage of flows succeeded?
- filter by flow run, tag, and time period

- how many flows are scheduled (filterable by flow run, time period, and tag?

Data could be exportable as .csv. 
Report could be exportable as pdf.

**Notes**
Requested by user at PACC SJ

**Comment by WillRaphaelson** [comment]
There are two issues here - users ability to reason about aggregates in the ui, and the ability to export them. The former is to be addressed in the upcoming activity page work, the latter is not planned at this time.
