### ISSUE TITLE
Subflow task retrying causes main flow to appear failed

### ISSUE THREAD

**Issue by samgarvis** [PrefectHQ/prefect#6834]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If a task in a subflow fails and then retries and succeeds, then the main flow will show failed. This is frustrating because I have a main flow that continually calls a subflow, and even though it is still successfully running, it shows as failed in the UI and the runtime does not increase.

### Reproduction

```python
`
@task(retries=3, retry_delay_seconds=5)
def query():
    select * from

@flow(name='subflow')
def subflow():
    df = query()
    slack(df, wait_for=[df])
        
@flow(name='mainflow')
def mainflow():
    while True:
        subflow()`

If the subflow ever breaks, then the mainflow is shown as failed in the UI. Like if the task query() fails and then retries and succeeds, the mainflow will show as failed in the UI. So even if the entire flow recovers from the failure, the mainflow will still show as failed and not be switched back to Running.

I want this flow to always be running, and it would be really nice to continue seeing it in the UI and it's runtime increase, but instead it goes to failed and it's hard to go back and find.
```

### Versions

```

2.4.0

```

**Comment by madkinsz** [comment]
To avoid failing the flow on subflow failure, you'll want to call it with `return_state=True`.
