### ISSUE TITLE
Cant import `Parameter` and `IntervalSchedule` as the docs suggest

### ISSUE THREAD

**Issue by asafalina** [PrefectHQ/prefect#6856]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I cant really do:
```python
from prefect import Parameter
```
as it states [here](https://docs-v1.prefect.io/core/concepts/parameters.html).

And same goes for this:
```python
from prefect.schedules import IntervalSchedule
```
as it states [here](https://docs-v1.prefect.io/core/concepts/schedules.html#overview)

I have a feeling that this is true for most, if not all, of the schedulers.

### Reproduction

.

### Error

.

### Versions

```
2.4.0
```

**Comment by madkinsz** [comment]
Hi! It looks like you're reading the `v1` docs from those links? Have you looked at https://docs.prefect.io/ ?

**Comment by asafalina** [comment]
indeed @madkinsz , it seems so.
thank you!
