### ISSUE TITLE
DaskTaskRunner on KubeCluster drops some logs

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6872]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using DaskTaskRunner with class_cluster=dask_kubernetes.KubeCluster the prefect logger drops logs. The number of logs dropped varies per run. Sometimes all logs are present.

In this particular run 5 of 8 logs are captured.

<img width="1064" alt="Screen Shot 2022-09-18 at 10 48 03 pm" src="https://user-images.githubusercontent.com/125105/190902876-1dc49d10-7794-4b3d-8c6b-0289148a2647.png">

The full set of 8 looks like this:

<img width="1066" alt="Screen Shot 2022-09-18 at 10 50 06 pm" src="https://user-images.githubusercontent.com/125105/190902924-e43a726f-873e-4334-ab37-c7fb087c1e66.png">

### Reproduction

```python
from typing import List

import dask_kubernetes
from dask_kubernetes import make_pod_spec
from kubernetes.client import V1Pod
from prefect import flow, get_run_logger, task
from prefect_dask.task_runners import DaskTaskRunner


@task
def say_hello(name: str) -> None:
    logger = get_run_logger()
    logger.info(f"hello {name}")


@task
def say_goodbye(name: str) -> None:
    logger = get_run_logger()
    logger.info(f"goodbye {name}")


def dask_pod_spec() -> V1Pod:
    return make_pod_spec(
        image="ghcr.io/dask/dask:latest",
        env={"EXTRA_PIP_PACKAGES": "prefect==2.4.0."},
        memory_limit="1G",
        memory_request="1G",
        cpu_limit=1,
        cpu_request=1,
        extra_pod_config={"serviceAccountName": "prefect-flows"},
    )


@flow(
    task_runner=DaskTaskRunner(
        cluster_class=dask_kubernetes.KubeCluster,
        cluster_kwargs={"pod_template": dask_pod_spec()},
        adapt_kwargs={"minimum": 1, "maximum": 2},
    )
)
def greetings(names: List[str]) -> None:
    for name in names:
        say_hello.submit(name)
        say_goodbye.submit(name)


if __name__ == "__main__":
    greetings(["arthur", "trillian", "ford", "marvin"])


```

For a complete reproduction on kubernetes see [dask_kubes_flow.py in tekumara/orion-demo](https://github.com/tekumara/orion-demo/blob/0885cec/flows/dask_kubes_flow.py)

### Versions

Version:             2.4.0
API version:         0.8.0
Python version:      3.9.13
Git commit:          513639e8
Built:               Tue, Sep 13, 2022 2:15 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted

**Comment by tekumara** [comment]
Bump

**Comment by madkinsz** [comment]
👍 I triaged the issue so it will not be marked as stale anymore.

**Comment by tekumara** [comment]
Resolved by 7626
