### ISSUE TITLE
Radar plot ignores dependencies

### ISSUE THREAD

**Issue by binste** [PrefectHQ/prefect#6892]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The radar visualization in the Prefect Cloud UI does not show the task dependencies when using code from [this Prefect Tutorial](https://discourse.prefect.io/t/how-can-i-define-state-dependencies-between-tasks/69).

### Reproduction

```python
@task
def task_1():
    pass
 
@task
def task_2():
    pass
 
@task
def task_3():
    pass
 
@flow(name="flow_with_dependencies")
def main_flow():
    t1 = task_1()
    t2 = task_2(wait_for=[t1])
    t3 = task_3(wait_for=[t2])


main_flow()
```

### Error

Output from console:
```
09:26:46.154 | INFO    | prefect.engine - Created flow run 'cerulean-narwhal' for flow 'flow_with_dependencies'
09:26:47.301 | INFO    | Flow run 'cerulean-narwhal' - Created task run 'task_1-1619c4ff-0' for task 'task_1'
09:26:47.302 | INFO    | Flow run 'cerulean-narwhal' - Executing 'task_1-1619c4ff-0' immediately...
09:26:47.871 | INFO    | Task run 'task_1-1619c4ff-0' - Finished in state Completed()
09:26:48.043 | INFO    | Flow run 'cerulean-narwhal' - Created task run 'task_2-49f2f021-0' for task 'task_2'
09:26:48.045 | INFO    | Flow run 'cerulean-narwhal' - Executing 'task_2-49f2f021-0' immediately...
09:26:48.867 | INFO    | Task run 'task_2-49f2f021-0' - Finished in state Completed()
09:26:49.037 | INFO    | Flow run 'cerulean-narwhal' - Created task run 'task_3-a26ef110-0' for task 'task_3'
09:26:49.038 | INFO    | Flow run 'cerulean-narwhal' - Executing 'task_3-a26ef110-0' immediately...
09:26:49.621 | INFO    | Task run 'task_3-a26ef110-0' - Finished in state Completed()
09:26:49.778 | INFO    | Flow run 'cerulean-narwhal' - Finished in state Completed('All states completed.')
[Completed(message=None, type=COMPLETED, result=None),
Completed(message=None, type=COMPLETED, result=None),
Completed(message=None, type=COMPLETED, result=None)]
```

Screenshot from Cloud UI:
![image001](https://user-images.githubusercontent.com/23366411/191223278-e2ad3f0d-333c-4769-9b66-80e408eefe5a.png)

### Browers

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [X] Edge

### Prefect version

Using Prefect Cloud

**Comment by madkinsz** [comment]
These tasks do not return data and you are passing `None` to `wait_for`. We cannot track relationships in this case. These tasks will run linearly without `wait_for` as is. If you submit the tasks, e.g. `t1 = task_1.submit()` then you will get futures back which would allow these tasks to run concurrently. Then, passing the future to `wait_for` will create a relationship between the tasks and cause them to run in-order.

**Comment by binste** [comment]
The relationship also does not show up if the tasks do return data, see code below. Is this expected? Are relationships therefore only tracked if a future is passed to a task as an argument or in `wait_for`?

```python
from prefect import flow, task


@task
def task_1():
    return 1

@task
def task_2(x):
    return 2

@task
def task_3(x):
    return 3

@flow(name="flow_with_dependencies")
def main_flow():
    t1 = task_1()
    t2 = task_2(t1)
    t3 = task_3(t2)


main_flow()
```

Thanks for your help!

**Comment by madkinsz** [comment]
Unfortunately you've encountered a bit of an edge case there :) We can track relationships when data is passed, but some types of data are not distinguishable as unique in Python. For example, Python stores the integers -5 through 256 as singletons and if we attempted to track passage of those as dependencies we'd have false-positive relationships. Futures are a definite way to track relationships between tasks that return otherwise untrackable types. If you updated your example to return a uniquely identifiable object like `{}` we should track the dependencies as you'd expect.

**Comment by binste** [comment]
Got it, that works for me, thanks :) Maybe this was not always the case and in a previous version tasks returned prefect futures by default? Parts of the documentation do not properly reflect the current behaviour. For your convenience but probably not complete:

* Good examples
  * This looks updated and has good examples of the behaviour: [Task Runners - Prefect 2](https://docs.prefect.io/concepts/task-runners/?h=wait_for#using-results-from-submitted-tasks)
  * [FAQ Does Prefect 2 Support Mapping - Prefect 2](https://docs.prefect.io/faq/?h=constant#does-prefect-2-support-mapping)
* Describes a different behaviour
  * [FAQ How do I enforce ordering between tasks that dont share data](https://docs.prefect.io/faq/?h=#how-do-i-enforce-ordering-between-tasks-that-dont-share-data)
  * [prefect.futures - Prefect 2](https://docs.prefect.io/api-ref/prefect/futures/)  -> "When tasks are called, they are submitted to a task runner which creates a future for access to the state and result of the task." Also examples in the docstrings seem to refer to a previous implementation

**Comment by madkinsz** [comment]
> Maybe this was not always the case and in a previous version tasks returned prefect futures by default?

Yeah we had futures by default in the beta but it moved away from that pattern. 

Thanks for the notes! cc @tpdorsey
