### ISSUE TITLE
Add pagination to list of blocks in the UI

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#6915]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

![image](https://user-images.githubusercontent.com/7703961/191601562-b677d33c-355c-4e7d-92ab-921ae27dcdf5.png)

### Reproduction

```python
Make 200+ blocks and view in the GUI. :)
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```

### Versions

```

# Copy output of `prefect version` here
2.x 
```

### Additional context

<img width="616" alt="Screen Shot 2022-09-21 at 4 13 53 PM" src="https://user-images.githubusercontent.com/7703961/191601430-1276d530-2e85-4661-bc1f-892082a4a870.png">

**Comment by pleek91** [comment]
Looked into this a little. We're using a table to display blocks which we currently don't have any pagination support for. So we'll need to either work on table data virtualization or change the design of the block lists to not use a table so we can use our existing list virtualization/pagination.

**Comment by zhen0** [comment]
Discussed - Craig is going to look into virtualization in a table. If you want to take this one on, check in with him!

**Comment by zhen0** [comment]
@zangell44 - do we need a separate ticket for the api work?

**Comment by zangell44** [comment]
Depends how we'd like to track these things?

**Comment by zhen0** [comment]
@zangell44 - any update on the api side of this?

**Comment by zhen0** [comment]
Discussed with @pleek91 and @billpalombi - this is harder than it sounds without removing current/expected functionality such as the ability to search by block capability and type.  To enable pagination and maintain the ability to search by capability and type will require API changes that are non trivial (which is why this ticket has been open for so long).  We plan to revisit blocks and the blocks page at some point in the near future and feel that will be the best time to address this.

**Comment by ryantbrennan1** [comment]
+1

I have ~90 blocks in one of my workspaces and it takes about 5 seconds for the page to load

**Comment by j-tr** [comment]
when filtering for type or capability or searching by name, only those blocks are shown that are initially displayed in the list of 200 blocks.
so given that I have 10 secrets but only 5 show up as part of the 200 first blocks, a selection by type will also only display these 5 blocks but not the remaining 5 secrets.
we have more than 200 blocks and this makes a good amount of blocks completely inaccessible from the UI.
Our current workaround to get the block page and be able to edit the block via the UI is querying the `Read Block Document By Name For Block Type` API endpoint and then pasting the id to the URL, but this is really inconvenient.

**Comment by zangell44** [comment]
The API portion of this work is finished. Re-opening to reflect there's still UI work remaining

**Comment by pleek91** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/11214
