### ISSUE TITLE
Prefect 1.0. Create_flow_run.map() creates the mapped task but never executes subtasks

### ISSUE THREAD

**Issue by KarimZS** [PrefectHQ/prefect#6918]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to execute a flow that triggers a few other flows, waits for them to finish, gets results, then proceeds with downstream tasks. This used to work as of ~1 month ago and we have a registered flow that showed has been running/shows execution logs. This flow has stopped working locally (while it was working when we first developed it). Here are the difference in logs

log from Prefect UI from a run on our fargate machine
```
16 September 2022,01:33:41 	prefect.CloudTaskRunner	INFO	Task 'create_ingestion_params': Starting task run...
16 September 2022,01:33:41 	prefect.CloudTaskRunner	INFO	Task 'create_ingestion_params': Finished task run for task with final state: 'Success'
16 September 2022,01:33:41 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run': Starting task run...
16 September 2022,01:33:41 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run': Finished task run for task with final state: 'Mapped'
16 September 2022,01:33:42 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run[0]': Starting task run...
16 September 2022,01:33:42 	prefect.create_flow_run[0]	INFO	Creating flow run 'fierce-flounder-Tome Ingestion' for flow 'Tome Ingestion'...
16 September 2022,01:33:42 	prefect.create_flow_run[0]	INFO	Created flow run 'fierce-flounder-Tome Ingestion': https://cloud.prefect.io/tome/flow-run/8d5af013-baa8-4830-be75-7d212a4f3e74
16 September 2022,01:33:42 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run[0]': Finished task run for task with final state: 'Success'
16 September 2022,01:33:43 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run[1]': Starting task run...
16 September 2022,01:33:43 	prefect.create_flow_run[1]	INFO	Creating flow run 'fierce-flounder-Tome Ingestion' for flow 'Tome Ingestion'...
16 September 2022,01:33:43 	prefect.create_flow_run[1]	INFO	Created flow run 'fierce-flounder-Tome Ingestion': https://cloud.prefect.io/tome/flow-run/7729a5c3-5fb3-474f-bfbc-7d2fbce841d8
16 September 2022,01:33:44 	prefect.CloudTaskRunner	INFO	Task 'create_flow_run[1]': Finished task run for task with final state: 'Success'
```

log from my local python execution
```
[2022-09-19 23:44:08+0000] INFO - prefect.CloudTaskRunner | Task 'create_ingestion_params': Starting task run...
INFO     [task_runner.py:241] Task 'create_ingestion_params': Starting task run...
[2022-09-19 23:44:14+0000] INFO - prefect.CloudTaskRunner | Task 'create_ingestion_params': Finished task run for task with final state: 'Success'
INFO     [task_runner.py:335] Task 'create_ingestion_params': Finished task run for task with final state: 'Success'
[2022-09-19 23:44:14+0000] INFO - prefect.CloudTaskRunner | Task 'create_flow_run': Starting task run...
INFO     [task_runner.py:241] Task 'create_flow_run': Starting task run...
[2022-09-19 23:44:14+0000] INFO - prefect.CloudTaskRunner | Task 'create_flow_run': Finished task run for task with final state: 'Mapped'
INFO     [task_runner.py:335] Task 'create_flow_run': Finished task run for task with final state: 'Mapped'
[2022-09-19 23:44:15+0000] INFO - prefect.CloudTaskRunner | Task 'get_task_run_result': Starting task run...
INFO     [task_runner.py:241] Task 'get_task_run_result': Starting task run...
```
### Reproduction

```python
executed using python3.10


def print_flow(flows,x,y):
    print(flows)


with Flow("Tome DocumentSet Ingestion") as flow:

    documentset_id = Parameter('documentset_id', required=True)
    report_id = Parameter('report_id', required=False)

    #clause_snapshot_id = get_clause_snapshot_id()

    #documents = get_documents_from_set(documentset_id)

    #params = create_ingestion_params(documents, clause_snapshot_id, report_id)

    ingestion_flows = create_flow_run.map(flow_name=unmapped("Tome Ingestion"),
                                          project_name=unmapped("development"),
                                          parameters=[])
    print_flow(ingestion_flows, documentset_id, report_id)

    #asserted_ingestion_flows = assert_results(ingestion_flows)

    #drrs = get_task_run_result.map(flow_run_id=asserted_ingestion_flows, 
                                   task_slug=unmapped("get_drr-1"))
    #dsrr = create_dsrr(drrs, documentset_id)
    #dsrr = dsrr_saver(dsrr)
    #update_report(report_id, dsrr)
```

### Error

Log of the above run with the commented out parts

```
[2022-09-21 22:51:23+0000] INFO - prefect.FlowRunner | Beginning Flow run for 'Tome DocumentSet Ingestion'
INFO     [flow_runner.py:245] Beginning Flow run for 'Tome DocumentSet Ingestion'
[2022-09-21 22:51:23+0000] INFO - prefect.TaskRunner | Task 'report_id': Starting task run...
INFO     [task_runner.py:241] Task 'report_id': Starting task run...
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'report_id': Finished task run for task with final state: 'Success'
INFO     [task_runner.py:335] Task 'report_id': Finished task run for task with final state: 'Success'
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'documentset_id': Starting task run...
INFO     [task_runner.py:241] Task 'documentset_id': Starting task run...
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'documentset_id': Finished task run for task with final state: 'Success'
INFO     [task_runner.py:335] Task 'documentset_id': Finished task run for task with final state: 'Success'
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'create_flow_run': Starting task run...
INFO     [task_runner.py:241] Task 'create_flow_run': Starting task run...
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'create_flow_run': Finished task run for task with final state: 'Mapped'
INFO     [task_runner.py:335] Task 'create_flow_run': Finished task run for task with final state: 'Mapped'
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'print_flow': Starting task run...
INFO     [task_runner.py:241] Task 'print_flow': Starting task run...
[]
[2022-09-21 22:51:24+0000] INFO - prefect.TaskRunner | Task 'print_flow': Finished task run for task with final state: 'Success'
INFO     [task_runner.py:335] Task 'print_flow': Finished task run for task with final state: 'Success'
[2022-09-21 22:51:24+0000] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
INFO     [flow_runner.py:710] Flow run SUCCESS: all reference tasks succeeded
```
### Versions

1.4.0

### Additional context

@mtconger97 and @anna-geller recommended I reach out on GitHub. Happy to have a call as well to investigate! Were there any 1.0 changes recently that would break this? or any prefect cloud changes such that making the call to create flows is silently failing?

**Comment by madkinsz** [comment]
Here's the changelog: https://github.com/PrefectHQ/prefect/blob/1.x/CHANGELOG.md

In what way is it not working? It all looks successful from those logs.

Can you confirm if this issue occurs on Prefect 1.3.0?

**Comment by anna-geller** [comment]
I can also confirm that everything seems to be working now that you upgraded to 1.4 -- if you believe something is still now right, could you share a full flow code of the child and parent flow so that we could run and reproduce the issue, if some issue still exists?

thanks for opening the issue

**Comment by KarimZS** [comment]
So the previous runs show that after "'create_flow_run': Finished task run for task with final state: 'Mapped'" we would get "'create_flow_run[0]': Starting task run..." which would then kick off the flow and give the flow id it kicked off. 

In the recent runs you can see that it just creates the mapped parent and never executes the 2 tasks which kick off the flow. I would expect that 'create_flow_run[0]' would run and produce a flow ID (which would then get printed in print_flow() or can be used downstream to get result of the flow. You can see the result from the log that print flow() returns []

**Comment by anna-geller** [comment]
You should have default values when using required parameters. I believe what you want to accomplish is to not use any Parameter tasks in this parent flow but instead have a separate task that returns a list of parameter values to map over and pass that so that you are mapping over the same flow, but each run uses a different parameter value. So only the child flow has any Parameter tasks. 

I think that this blog post may clarify some confusion about using parameters in 1.0 in general: https://www.prefect.io/guide/blog/how-to-make-your-data-pipelines-more-dynamic-using-parameters-in-prefect/

**Comment by KarimZS** [comment]
Thanks for responding Anna. That’s what we have in the full flow. I truncated it for the example to get at the root cause. 

If any execution was happening of the create_flow_run task we would see an error. The logs are showing that no errors happen and that the child flows of the create_flow_run map are not running at all anymore. (independent of parameters or not). We get no output from the execution of the create_flow_run map (which should be the flow run ID of the launched flows). This is proven by the print out of the results.

**Comment by anna-geller** [comment]
I was using this pattern before and I suspect this might be some small misconfiguration, can you share a full minimal reproducible example that would allow me to run and reproduce your full example?
