### ISSUE TITLE
Type-check error when using .map

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6922]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Type error when using `.map`

### Reproduction

```python
from prefect import flow, task


@task
def count_rows(batch: str) -> int:
    return 1


@flow
def map_flow() -> None:
    counts = count_rows.map(["a"]) # <-- type error here


if __name__ == "__main__":
    map_flow()
```

### Error

pyright:
```
Argument of type "list[str]" cannot be assigned to parameter "batch" of type "str" in function "map"
"list[str]" is incompatible with "str"
```

mypy:
```
No overload variant of "map" of "Task" matches argument type "List[str]"
```

### Versions

prefect 2.4.0

**Comment by williamjamir** [comment]
@madkinsz How about using the same approach as the typeshed for `map`?
https://github.com/python/typeshed/blob/main/stdlib/builtins.pyi#L1420

Basically, an overload for at least X arguments (for `map` is 5), and any call with more than this threshold is automatically treated as `Any`.

I know that this solution does cover all the cases, but I think it's good enough for the users (at least they will not face a type error for every case).
