### ISSUE TITLE
Reenable the backward compatible container test

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#6936]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

We disabled [a test](https://github.com/PrefectHQ/prefect/blob/4fe044728b1888efe3306af618d535ed1c117592/tests/infrastructure/test_base.py#L189-L188) that validated that an old version of Prefect could run a flow run scheduled by a new version of Prefect. 

### Describe the proposed behavior

Enable this test and mark it as flaky rather than skipped.

### Example Use

The test should run and work reliably if retried a few times. If that isn't the case, we'll need to keep it disabled.

**Comment by madkinsz** [comment]
Work in progress at #6615

**Comment by zhen0** [comment]
Replaced by integration tests
