### ISSUE TITLE
Notification for runs that do not complete after duration

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6939]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In Prefect 1 we use automations to notify when a flow run takes too long eg:

```
When any run from my-flow does not finish after 3600 seconds, then Slack SLA overdue.
```

This doesn't appear to be possible in Prefect 2.

### Describe the proposed behavior

Notification for runs that do not complete after duration

### Example Use

To identify runs that are stuck in running and not completing in the expected time.

**Comment by cicdw** [comment]
This is released under a beta flag currently: https://docs.prefect.io/ui/automations/ and will be GA in January 👍
