### ISSUE TITLE
slugify() got an unexpected keyword argument if unicode-slugify is installed

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#6945]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect actively uses [python-slugify](https://github.com/un33k/python-slugify).
There also exists a reasonably popular Mozilla-mantained library [unicode-slugify](https://github.com/mozilla/unicode-slugify)
Unfortunately, both those libraries chose `slugify` as the package name.

If one was to install `unicode-slugify` after `python-slugify`, pip would add `unicode-slugify`'s files to `site-packages/slugify`, where `python-slugify`'s files are already located.
`slugify` methods have different signatures, which leads to an exception when `prefect:docker:get_prefect_image_name` tries to call `slugify.slugify` with `lowercase=False`.

Seems like switching to `from slugify.slugify import slugify` would sidestep this.

### Reproduction

```python
pip install prefect
prefect version
# Version:             2.4.1
# ...

pip install unicode-slugify
prefect version
# TypeError: slugify() got an unexpected keyword argument 'lowercase'
```

### Error

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\prefect.exe\__main__.py", line 4, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\prefect\cli\__init__.py", line 15, in <module>
    import prefect.cli.kubernetes
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\prefect\cli\kubernetes.py", line 36, in <module>
    get_prefect_image_name(),
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\prefect\docker.py", line 56, in get_prefect_image_name
    tag = slugify(
TypeError: slugify() got an unexpected keyword argument 'lowercase'

```

### Versions

```
Version:             2.4.1
API version:         0.8.0
Python version:      3.10.4
Git commit:          e941523d
Built:               Thu, Sep 22, 2022 12:26 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by madkinsz** [comment]
Oof, this one is a bit awkward. Generally, I'd just recommend using virtual environments. I'm down to update our imports to allow side-by-side installations. I'd probably create a `prefect.utilities.slugify` module and import it _once_ there using this syntax (including a comment explaining the reason) then update all of our internal imports to reference our internal module.
