### ISSUE TITLE
UI strips new-line characters for Secret block

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#6949]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Pasting a value with new line characters into the `Value` field of the `Secret` strips the new line characters.

### Reproduction

1. Create a new Secret block in the UI with `Block Name` as `from-ui` and `Value` as,

```
line one
line two
```

2. Create a new Secret block with Python as,

```py
from prefect.blocks.system import Secret

data = """
line one
line two
"""

s = Secret(value=data)
s.save("from-code")
```

### Error

```py
>>> from prefect.blocks.system import Secret
>>> Secret.load("from-code").get()
'\nline one\nline two\n'
>>> Secret.load("from-ui").get()
' line one line two'
```

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```
Version:             2.4.2
API version:         0.8.0
Python version:      3.9.13
Git commit:          65807e84
Built:               Fri, Sep 23, 2022 10:43 AM
OS/Arch:             darwin/arm64
Profile:             emil-default
Server type:         cloud
```

**Comment by pleek91** [comment]
Curious what the use case is here? 

For reference this is the schema generated for the secret block's value property

```json
{
  "type": "string",
  "title": "Value",
  "format": "password",
  "writeOnly": true,
  "description": "A string value that should be kept secret."
}
```

We're (I think logically) displaying a `<input type="password" />` input for interacting with that property. Which doesn't support newline characters at the browser level.

**Comment by zhen0** [comment]
I think this might best be answered by https://github.com/PrefectHQ/prefect/issues/6735

**Comment by systembell** [comment]
> Curious what the use case is here?

We're running into this, too. Our use case is an SSH key and we're having to use AWS Secrets as a workaround until Prefect retains newlines.

**Comment by MatthieuToulemont** [comment]
I am also facing this issue, any news ?

**Comment by cicdw** [comment]
Hi @MatthieuToulemont - we do plan to work on this very soon! I don't have a timeline to offer quite yet but we will add this issue to a Milestone once we know (should be within the next few releases)
