### ISSUE TITLE
`Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'`

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6960]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running `prefect version` on 3.9 ✅ 

![image](https://user-images.githubusercontent.com/86264395/192122056-111f9016-96be-48fa-b3af-a974b42c9e84.png)

Running the same on 3.10 shows those warnings:

![image](https://user-images.githubusercontent.com/86264395/192122077-9cc4dab1-eb36-4512-9f16-45789d49621a.png)

The same happens when running flows on Python 3.10:

![image](https://user-images.githubusercontent.com/86264395/192122124-13e2d5b6-be89-4f62-8429-7bf37baf9747.png)

Nothing critical - all runs etc work, just likely some difference in type annotations in 3.10

### Reproduction

```python
prefect version # or run some flow on Python 3.10
```

### Error

```
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Subscript' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Subscript' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Subscript' node: 'NoneType' object has no attribute 'resolve'

```

### Versions

```
Version:             2.4.2
API version:         0.8.0
Python version:      3.10.4
Git commit:          65807e84
Built:               Fri, Sep 23, 2022 10:43 AM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud

```

**Comment by madkinsz** [comment]
These warnings are from the latest version of `griffe` from #6075

Some of these were fixed but clearly there are more. We may want downgrade until #6947 is tackled.

**Comment by anna-geller** [comment]
yup you're 100% correct - everything works despite those messages, that's why I added in the issue "nothing critical"

**Comment by madkinsz** [comment]
Yeah this has nothing to do with Python version. You may downgrade `griffe` to fix.

**Comment by jmrobbins13** [comment]
I had this bug on prefect 2.4.1, but it disappeared on 2.4.2

**Comment by anna-geller** [comment]
I can confirm that using 0.21.0 fixes the issue: `pip install griffe==0.21.0`

@madkinsz could we pin to this version for now?

**Comment by madkinsz** [comment]
We had previously pinned that that version but we were under the impression the issues with upgrading were fixed. We can restore the pin but I'd rather the integrations team took the time to fix the problems here.

**Comment by anna-geller** [comment]
cc @desertaxle

**Comment by pawamoy** [comment]
I see you already went with disabling the loggers, but if you find time and motivation to open an issue on Griffe's bugtracker with a reproducible example, I'd be very happy to look into it :slightly_smiling_face: From the logs, it looks like there's no parent object attached to the parsed docstring, which seems odd to me, but hard to know without actual code!

**Comment by madkinsz** [comment]
Thanks for chiming in! I'll make sure someone follows up with a reproducible example.

If it's helpful, https://github.com/PrefectHQ/prefect/pull/6937 resolved some of these issues.
