### ISSUE TITLE
Wrong data in input fields while creating blocks

### ISSUE THREAD

**Issue by thelfensdrfer** [PrefectHQ/prefect#6970]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I wanted to create a docker infrastructure block. I filled everything out and wanted to create a registry block via the "Docker Registry (Optional)" "Add" button. I decided against it, clicked cancel and was back again in the infrastructure block. So far everything was normal.

What I failed to see was that the docker registry form had overwritten the input fields (e.g. the name field) of my infrastructure block. So now my infrastructure block was named "aws-registry" instead of "docker-infra" or something like that.

And since you cannot rename your blocks, I have to delete it again.

* I did NOT check if this error still occurs if I refresh the page
* I did NOT test in a different browser

### Reproduction

/

### Error

/

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment]
Hi @thelfensdrfer - thanks for the report.  I can see a similar issue.  For now I recommend creating a docker registry block before creating a docker container block while we look into the issue.

**Comment by pleek91** [comment]
@zhen0 I have a fix in progress for this 👍  Fixes the data issue and hoping to improve the user experience for creating nested blocks as well.
