### ISSUE TITLE
Add `prefect server start --detach` and `prefect server stop`

### ISSUE THREAD

**Issue by zanieb** [PrefectHQ/prefect#6989]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The `prefect server start` command blocks until a keyboard interrupt is sent, then it is stopped.

### Describe the proposed behavior

Including a `--detach` command will allow the server to be run in the background. Then `prefect server stop` can be used to stop it.

### Example Use

```
prefect server start --detach
# Do some work with server...

prefect server stop
```

This would be useful in our compatibility tests e.g. #6988 

### Additional context

To facilitate this, we'll need to store the PID in `~/.prefect/` so during a start. We may want to do this in the server itself so that `prefect server stop` can interrupt servers that have been started without `--detach`.

We may want to take the `prefect server start` command and change it to be synchronous. It doesn't need to run multiple services in parallel anymore and it'd be easier to maintain that way. Our `open_process` implementation doesn't have a clear path to backgrounding a process.

**Comment by hallenmaia** [comment]
@madkinsz Something like that?

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.daemon

**Comment by madkinsz** [comment]
Oh sweet!

**Comment by desertaxle** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/15013 (2.x) and  https://github.com/PrefectHQ/prefect/pull/15024 (3.0)
