### ISSUE TITLE
Missing `await` in the Blocks code snippet

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect#6994]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Missing `await` in the Blocks code snippet.

### Reproduction

Create an AWS credentials block, then you will see the code snippet that misses an `await`:

![image](https://user-images.githubusercontent.com/3375461/192634523-b4a35270-7853-4ab5-99fb-c91483753076.png)

It should be:

```python
aws_credentials_block = await AwsCredentials.load("aws-credentials-block")
```

### Versions

2.4.2

### Additional context

Originally asked at https://stackoverflow.com/questions/73864125/how-to-use-blocks-correctly-to-load-aws-s3-credentials-in-prefect

**Comment by madkinsz** [comment]
Hi! `await` is only needed if you're writing an async flow or task. For users writing synchronous code, an `await` is not needed (and not possible).

**Comment by Hongbo-Miao** [comment]
Got it, thanks @madkinsz !
