### ISSUE TITLE
Auto build Prefect docker image upon merge

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#700]
Add a latest development build (untagged, master prefect) to the CircleCI workflow

**Comment by cicdw** [comment]
Question: should we build images for all 3 supported major python versions (3.5, 3.6, 3.7)?

**Comment by joshmeek** [comment]
I think we should

**Comment by cicdw** [comment]
I'm happy to do post-merge cutting edge builds for all PRs TBH.  Is that excessive?

**Comment by joshmeek** [comment]
I really don't think so, it'll just have the be tagged with some incrementing version of master builds

**Comment by jlowin** [comment]
Let's publish Prefect with 3.7, in order to ensure that code that runs in one official image runs in any other. If there's a clamor for other versions we can address it at that time.

**Comment by cicdw** [comment]
Per offline discussion w/ @joshmeek and @TylerWanner :
- on DockerHub, we will have an "official" Prefect image with base image `python:3.7` and another with Alpine base
- we will have one tag per official release, with the latest release having the "latest" tag
- we will also use `prefect.__version__` on bleeding edge master to tag "bleeding edge" images with _every merge to master_
- these images will all install Prefect + graphviz (including the DOT scripts) + kubernetes extras

We plan to `pip` install straight from `git` for all these prefect installations.  I need to provide @TylerWanner with a few of these commands and he'll take care of the rest.

**Comment by cicdw** [comment]
Closed in #954
