### ISSUE TITLE
Block Document has different schema

### ISSUE THREAD

**Issue by KayJey-Krayen** [PrefectHQ/prefect#7002]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I run my code on my cloud instance. Just once I deployed the code through python file locally . 
Now when I run my agent again in my aws instance, it says block document check sum has chnaged.

### Reproduction

```python
Deploy from system A .
Run agent in system B.
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```
UserWarning: Block document has schema checksum sha256:d28332d78ac90882bfeeef79f98cd26c99cda6a7c6d3a48d56a6bd67d7360648 which does not match the schema checksum for class 'Process'. This indicates the schema has changed and this block may not load.
  self.infrastructure = Block._from_block_document(

### Versions

```

# Copy output of `prefect version` here

```
Prefect 2.0

**Comment by madkinsz** [comment]
> Copy output of `prefect version` here

Can you run the `prefect version` command and share the output of that?

Are you running the same versions at both locations?

**Comment by rachtsingh** [comment]
Ran into the same issue when running `prefect deployment build`. Here's the `prefect version` on my local dev machine and on the remote machine (server with Orion and agent):

Local:
```
Version:             2.6.4
API version:         0.8.2
Python version:      3.10.4
Git commit:          51e92dda
Built:               Thu, Oct 20, 2022 3:11 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted

**Comment by discdiver** [comment]
Warning `UserWarning: Block document has schema checksum` should be able to be safely ignored.

**Comment by jmprovencher** [comment]
@discdiver Why should this warning be ignored. Why is it a warning in the first place ?

**Comment by discdiver** [comment]
To quote from another issue response: https://github.com/PrefectHQ/prefect/issues/6265#issuecomment-1239442552

> ... as long as your blocks are loading correctly that warning can be safely ignored. We've updated the block schema for many blocks, but they should still be backwards-compatible with older block documents. Please open an issue if you encounter a scenario where you are not able to load an older block document with a newer version of Prefect.

This warning should go away with the latest Prefect versions, I believe.
