### ISSUE TITLE
BUG: Orion version header is misaligned

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#7016]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The version tag is misaligned (should be on the right) on the settings page:

![Screen Shot 2022-09-29 at 12 35 09 PM](https://user-images.githubusercontent.com/27291717/193088705-5c07da04-0107-4569-ba2c-5397b45ae880.png)

### Reproduction

```python3
Visit the settings page
```

### Error

```python3
N/A
```

### Versions

```Text
2.4.3
```

**Comment by pleek91** [comment]
@space-age-pete wanna take this on?
