### ISSUE TITLE
The Value of Block is Not Updated After Clicking Save

### ISSUE THREAD

**Issue by khuyentran1401** [PrefectHQ/prefect#7043]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In the Docker Container block, after deleting the value for Networks, the value didn’t change after I clicked Save. I’m using Prefect Cloud.

![Sep-30-2022 15-05-34](https://user-images.githubusercontent.com/49108771/193350564-f3154a62-706d-4b41-83bf-72f4912a3586.gif)

I saw the same issue when changing the values of other blocks such as AWS

### Reproduction

```python3
- Add a value to the Networks section in the Docker Container block
- Click Save
- Update the value of the Networks section
- Click Save
```

### Versions

```Text
Version:             2.4.4
API version:         0.8.1
Python version:      3.9.12
Git commit:          cd649212
Built:               Thu, Sep 29, 2022 2:01 PM
OS/Arch:             darwin/arm64
Profile:             cloud
Server type:         cloud
```

**Comment by pleek91** [comment]
https://github.com/PrefectHQ/nebula-ui/pull/1762
https://github.com/PrefectHQ/prefect/pull/7096
