### ISSUE TITLE
prefect 2 Orion does not load - white screen

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7049]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If i visit https://app.prefect.cloud/ i just see a white page with no content. 

![image](https://user-images.githubusercontent.com/24698503/193406985-d27ddd29-ae35-4fe2-af0e-15208d3d9010.png)

### Reproduction
Happens after i login - close the page an revisit it. Sporadic issue that does not happen all the time.

Clearing the Cache Storage fixes the issue. Clearing local storage and session storage does not resolve the issue.

![image](https://user-images.githubusercontent.com/24698503/193407188-14df8209-8d39-49c8-837b-76410e4454be.png)

### Error

```python3
/index.794e5129.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Versions

```Text
2.?
Chrome Version 105.0.5195.127 (Offizieller Build) (64-Bit)
```

### Additional context
Happend to a coworker yesterday as well - should should be somewhat common.  Yesterday was also the first time i happend.

**Comment by billpalombi** [comment]
@felix-ht did this fix resolve your issue? If so, we'll close this.

**Comment by felix-ht** [comment]
yeah its fine clearing the cash fixed it - didn't show up since a while as well!
