### ISSUE TITLE
Ability to change flow state from UI

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#7080]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Not Implemented

### Describe the proposed behavior

Add the ability to change flow final state from prefect UI

**Comment by madkinsz** [comment]
Hi! Please provide an example of how this would be useful. Including things like "I'd like to change a flow from failed to completed because _____". Also, we'll need to determine if we should support changing the state _type_ here or just the state _name_.

**Comment by BitTheByte** [comment]
I'd like to see this implemented as I'm using `prefect-dask` with Kubernetes and some of the flow runs stuck at running state while the pod is finished or for some reason or killed so I believe it would be useful to be able to change the state to "Failed" or "Completed" as required rather than having it stuck as "Running"

**Comment by zhen0** [comment]
I think https://github.com/PrefectHQ/prefect/issues/7148 should help with this use case. 

Also adding https://github.com/PrefectHQ/prefect/issues/7364 to handle terminal state runs.

**Comment by billpalombi** [comment]
As @zhen0 suggested, #7364 will address this.
