### ISSUE TITLE
Prefect UI - logs sorting / ability to jump to the most recent logs

### ISSUE THREAD

**Issue by garrrikkotua** [PrefectHQ/prefect#7082]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently Prefect UI does not allow to **quickly scroll through logs** to get to the most recent ones. I have long running tasks which generate hundreds of thousands of logs during each run and it's absolutely impossible to scroll to the last logs.

### Describe the proposed behavior

I propose adding ability to sort logs (e.g by time), search for them or simply add a **"scroll to the very bottom"** button for the beginning. It would really make my life easier. 

### Example Use

Well, to be able to monitor the current state of the run :)

**Comment by zhen0** [comment]
I think the simplest way to address this would be to add a sort select (similar to the one we have for flow runs) to the top of the logs tab - next to the level select - and to add a sort the to the logs filter -  "sort": "TIMESTAMP_ASC" or "TIMESTAMP_DESC"
