### ISSUE TITLE
Deployment.build_from_flow does too many things (and is not pure)

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7088]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I was using `Deployment.build_from_flow` to control deploying my flows from python.
I noticed that build_from_flow was very slow. 

The reason for this is that it first syncs any blocks currently set to the deployment and then by default automatically directly redeploys to the storage. The last step takes time. 
If you want to build multiple flows it will upload the data/context to the storage multiple times.

(This feels related to #6560)

Now you can deactivate it, but the idea that build_from_flow would immediately upload to storage as a **default side effect**, feels very counterintuitive to in general. In general the issue is that `build_from_flow`, the only method to create a deployment from a flow, has many side effects.

To me was quite hard to understand. I had to read the code of the function a couple of time until i got what it is doing. After wondering why it is so slow i decided to implement my own builder so i no longer had to deal with the method (that i didn't understand at that time).

### Describe the proposed behavior

Add a new method `Deployment.from_flow` that creates a Deployment from a flow. This method should be **pure** - no side effects.

After this the user can make their own choice how to call **load**, **to_yaml** and **apply** to interact with the object.

### Example Use
```python
Deployment.from_flow(my_flow, storage=my_storage)
```

> edit wording

**Comment by jmg-duarte** [comment]
+1 on this proposal
