### ISSUE TITLE
Task run dependency view

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7089]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently we only have the radar view. 

### Describe the proposed behavior

I would much rather have a dag view - similar to what we had with v1. 

However v1 was quite bad at layouting. Even pretty simple dags would look quite poor if you compare them to graphviz output we had for v1.

><img width="300" alt="image" src="https://user-images.githubusercontent.com/24698503/194356700-cc7aade3-30b8-40e5-9644-56f571db9802.png">
>
>_With this v1 dag view it was pretty much impossible to figure out the connections between nodes as edges were bundled up._

> <img width="300" alt="image" src="https://user-images.githubusercontent.com/24698503/194357178-5188697f-ba00-440d-a972-16ea69a234bc.png">
>
>_Even worse ..._

Something like https://observablehq.com/@erikbrinkman/d3-dag-sugiyama might be great.

**Comment by yusuf-jkhan1** [comment]
Also curious about this. The radar view takes a lot of brain power to interpret for 90% of my dags. Sales engineer sold us on Prefect 2 saying there would be better support for traditional dags and radar view would see enhancements. I've scrolled through the open issues but don't really see any that would support showing traditional (non-async) dags in a natural manner.
