### ISSUE TITLE
Allow tasks to wait_for any terminal state, not just Completed

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#7098]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

A task's `wait_for` argument only allows it to run when all of its upstream tasks have succeeded, or more specifically reached a `Completed` state.

### Describe the proposed behavior

There should exist a way to declare that a task should wait for its upstream tasks to reach any [terminal state](https://docs.prefect.io/concepts/states/#state-types).

### Potential Solution
```python
@task
def task_one():
    pass

@task
def task_two():
    raise ValueError()

@task(wait_for=[task_one, allow_failure(task_two)]):
def task_three():
    pass
```

**Comment by david-elliott-deliveroo** [comment]
Huge ➕ 1 on this please, we have a blocking use-case whereby we _need_ to be able to run tasks downstream of other failed tasks!!
