### ISSUE TITLE
Stream print statements as logs similarly to the `log_stdout` in v1

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7117]
The key value prop of Prefect is that users don't need to rewrite their code. Their code is workflow. But to get any logs streamed to the backend, we **do** require users to change their code to use the Prefect logger or to configure extra loggers. Simple print statements are currently ignored by Prefect.

This gets asked a lot and is important to support incremental adoption 

![Image](https://user-images.githubusercontent.com/86264395/194860461-741f568f-b701-43d2-afb6-976e0aa37fbe.png)

**Comment by anna-geller** [comment]
@anticorrelator for more context, this is how it was done in v1: we were redirecting stdout to "log_stdout" logger https://github.com/PrefectHQ/prefect/blob/1.x/src/prefect/engine/task_runner.py#L873-L877 and then using this utility: https://github.com/PrefectHQ/prefect/blob/1.x/src/prefect/utilities/logging.py#L375

**Comment by billpalombi** [comment]
We'll need to consider the implications of encouraging users sending us more logs. We may need to invest in backend improvements to support greater volume.

**Comment by anna-geller** [comment]
Workaround from a SO user struggling with [the same issue](https://stackoverflow.com/questions/74138833/forwarding-stdout-and-stderr-to-logger-in-prefect-2-flows/74138948#74138948)

**Comment by zangell44** [comment]
Fwiw I don't think this issue should be blocked by log volume scaling concerns. Seems like a great user win that has only a modest increase in risk.

**Comment by gabcoyne** [comment]
This issue is blocking some significant migration from 1-2

**Comment by anna-geller** [comment]
cc @anticorrelator 🙏

**Comment by madkinsz** [comment]
After further thought this is much easier if we require it to be a global setting rather than at the flow or task level. This is still quite challenging though and is certain to result in unexpected behavior.

I think we'd be much better off focusing on https://github.com/PrefectHQ/prefect/issues/6767#issuecomment-1242484405 if that would unblock usage.

**Comment by WillRaphaelson** [comment]
https://github.com/PrefectHQ/prefect/pull/7580
