### ISSUE TITLE
Radar view does not show task dependency if a cached result is used

### ISSUE THREAD

**Issue by mathijscarlu** [PrefectHQ/prefect#7126]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When a task depends on another task but the result of this upstream task was cached, this dependency is not shown in the radar view of the flow run.

### Reproduction

Create a flow with the following content:
1. A first task where the result is cached.
2. A second task, dependent on this first task.
3. Execute the flow two times, make sure the cached result is used the second time.

### Error

![image](https://user-images.githubusercontent.com/92080919/195023556-735c3002-5463-4078-b8ac-b37713367558.png)

In the executed flow, all capture_get_data tasks are dependent on the capture_token task. This dependency is clearly shown when executing the flow for the first time: all dependent tasks are one ring further from the center than the capture_token task. When running for the second time however (picture above), because a cached result is used for the capture_token task, this dependency seems not to be detected and thus not shown in the radar view

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
Version:             2.4.5
API version:         0.8.1
Python version:      3.8.14
Git commit:          dbe27317
Built:               Thu, Sep 29, 2022 3:05 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

**Comment by bunchesofdonald** [comment]
Thanks @mathijscarlu!

**Comment by TimoVink** [comment]
Just in case this helps: I'm seeing the same behaviour when using `persist_result` and retries (so without  the `cache_key_fn` mechanism).

**To Reproduce**
1. Run flow below. One of the branched tasks should fail.
2. Remove the `raise` in `branched_task`, redeploy flow.
3. Click 'Retry' in Prefect UI. Flow picks up where it left off and completes successfully.

This results in the following incorrect graph (`merged_task` should have 2 inputs)
![image](https://user-images.githubusercontent.com/694180/214360863-3d45ea61-2eba-4377-a9f5-7191fa04e17b.png)

**Flow Code**
```python
# PREFECT_RESULTS_PERSIST_BY_DEFAULT = true

@task
def initial_task():
    return ['A', 'B']

@task
def branched_task(x):
    if x == 'B':
        raise ValueError('Oh no, not B!')
    return x.lower()

@task
def merged_task(xs):
    return [x + x for x in xs]

@flow(result_storage='s3/results')
def main():
    data1 = initial_task()
    data2 = [branched_task(x) for x in data1]
    data3 = merged_task(data2)
    print(data3)
```

**Comment by discdiver** [comment]
Closing as radar view is no longer present.
