### ISSUE TITLE
Restart Flow Runs from Failed Tasks

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#7127]
**User Story**
As a Prefect 2 user with a flow run that has completed in a failed state, I want to retry the flow run, from either the UI or the CLI, perhaps because I know that something about the flow run context has changed. I expect that any task run in that flow run that finished in a failed state will be restarted with all of its retries reset to zero.

**Implementation Considerations**
- This change may require updates to orchestration rules
- We should consider the tradeoffs of using the existing `/api/task_runs/{id}/set_state` route or creating a new route, such as `/api/flow_runs/{id}/restart`.
- Caching must be enabled to achieve this. The design must account for scenarios in which there is no cache. In particular, the UI would ideally know whether it is possible to retry before inviting the user to do so.

**Prompts**
- Is "Restart" the best name for this feature? To me, "Restart" implies that the flow run will start at the beginning. "Retry" might be more appropriate. Or "Restart from Failure" might be more precise.

**Resources**
- [Prefect 1 implementation](https://docs-v1.prefect.io/orchestration/ui/flow-run.html#restarting)

**Comment by billpalombi** [comment]
@zhen0 this is the back end issue for flow run restarts, we'll need to create a separate front end ticket.

**Comment by billpalombi** [comment]
@anticorrelator, @madkinsz believes that the work that we've already done for flow run retries may be relevant to this problem. @madkinsz could you point @anticorrelator to that work?

**Comment by anticorrelator** [comment]
@billpalombi @madkinsz Yeah! I was wondering about whether or not flow run retries satisfies the issue: my understanding of the difference is the chance to manually restart given a change in the flow run context that might have had to be manually adjusted

**Comment by madkinsz** [comment]
Ah that's really interesting to consider! My intuition is that it should be able to work the same way. It'd be good to chat through the specific parts you're worried about.

Additional context in https://github.com/PrefectHQ/orion/pull/2205 may be helpful.
