### ISSUE TITLE
Allocate more space to display block capabilities column

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7137]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, not all capabilities are displayed

![image](https://user-images.githubusercontent.com/86264395/195345017-fc0907e6-0d52-44d5-842d-3bd03ef18816.png)

### Describe the proposed behavior

Use the free space to display block capabilities - cc @zhen0

**Comment by coisnepe** [comment]
Thanks Anna! The problem is the same on the deployments' page, as seen here on a 13" laptop, if not worse because I now have to scroll horizontally to reach the last columns…

<img width="1089" alt="screenshot_113" src="https://user-images.githubusercontent.com/13304454/198589441-d39fe279-2762-4e72-8f60-626377a77b56.png">

**Comment by anna-geller** [comment]
thanks for adding more info!

**Comment by coisnepe** [comment]
Hi team, I see both this and the link issue have been closed, however the original problem remains: on a 13" screen the "Schedule" column takes up most of the space, and even a single tag cannot be displayed and has to be "abbreviated", which in my opinion makes no sense… But maybe it's a deliberate choice of yours?
<img width="1439" alt="screenshot_161" src="https://user-images.githubusercontent.com/13304454/209808229-6926c4f1-fe79-4636-8dac-c50c7625b5d6.png">

**Comment by anna-geller** [comment]
@zhen0 - should we reopen?
