### ISSUE TITLE
Research spike: Flow run cancellation

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#7148]
Under what conditions can we enforce a state transition from PENDING or RUNNING to CANCELLED such that the flow run infrastructure is actually torn down as it would be when the flow run reached a FAILED or COMPLETED state.

**Comment by madkinsz** [comment]
This should already occur roughly correctly. The big concern is that "cancellation" implies interruption of running items but the flow run will not be interrupted until it attempts to set a new state.

To resolve this, we'd likely need to create a listener background job that reads the flow run state every once and a while. If it sees "CANCELLED" it can attempt to interrupt the flow run.

**Comment by zhen0** [comment]
UI button added here: https://github.com/PrefectHQ/orion-design/pull/806

**Comment by abrookins** [comment]
@madkinsz Now that we shipped Cancellations, can we close this issue?
