### ISSUE TITLE
Improve handling of block schema upgrades

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7157]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently every now an than there seem to be some schema changes for some of the blocks. This recently caused my `DockerContainer` block to silently fail the login. (not so silently considering the image was no longer pulled)

The only option to fix the schemas was to delete the blocks. Re-uploading them without deleting did not fix the issue.

### Describe the proposed behavior

Add an option to upgrade the schema of block. 

```python
block = String.load("my_string_block")
block.upgrade_schema()
```
`upgrade_schema` would recreate the block with the most up to date schema. `upgrade_schema` should fail if the upgrade is impossible, given the data and defaults present in the local block.

With this one could just add new required options to the block to enable the upgrade. 

```python
block = String.load("my_string_block")
# block.upgrade_schema() would fail here
block.new_required_value = 42 # new required field for the new schema version
block.upgrade_schema() # works
```

### Example Use

With this i can just add an `upgrade_schema` into my cd scripts - and the deployment will fail on any big schema change - which i can fix easily afterwards.

**Comment by desertaxle** [comment]
I believe that this issue was addressed by https://github.com/PrefectHQ/prefect/pull/8056. @felix-ht feel free to re-open this issue if https://github.com/PrefectHQ/prefect/pull/8056 does not satisfy your use case.
