### ISSUE TITLE
Missing logs and flows marked as completed when logger encounters errors

### ISSUE THREAD

**Issue by matmiad** [PrefectHQ/prefect#7175]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Setup is local agent with prefect cloud, prefect `2.5.0`. A flow with a task with syntax issue in `logger.info` parameters errors out. The flow is finishes as completed based on agent logs. UI in prefect cloud shows flow as completed with logs not pulled for any of the errors or logs after the error. 

**Expected behavior** 
- Flow finishes with state `Failed`
- Logs and state in UI reflects the issues including Traceback and Failed state.

Issue might be both UI and Prefect

### Reproduction

Flow:
```
import os

from prefect import task, flow, get_run_logger


@task
def read_env(input: str):
    logger = get_run_logger()
    tester = os.getenv('tester')
    logger.info(tester, input)  # intentional syntax issue
    return tester


@flow
def pipe(input: str):
    read_env(input)
```

Manually created process block in UI:
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/30066655/195887643-a805359f-c683-429d-bd7f-d1eac200910d.png">

Deployment command from cli:
```
prefect deployment build pacc/flows/infra_flow.py:pipe -n blockenv
```

Local agent:
```
prefect agent start -q default
```

### Error

Local agent logs:
```
--- Logging error ---
Traceback (most recent call last):
...

...
10, in read_env
    logger.info(tester, input)  # intentional syntax issue
Message: 'yes'
Arguments: ('aa',)
10:42:42.736 | INFO    | Task run 'read_env-14fddeff-0' - Finished in state Completed()
10:42:42.835 | INFO    | Flow run 'mu6-yed-terminus' - Finished in state Completed('All states completed.')
10:42:43.113 | INFO    | prefect.infrastructure.process - Process 'mu6-yed-terminus' exited cleanly.
```

Prefect cloud UI:
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/30066655/195889061-8c7edf68-7e51-4e63-9119-70638bcc6f74.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by madkinsz** [comment]
Hi! Can you please include the full traceback? 

I believe this is intentional. In Python, logging errors do not crash your application. If you call `logger.info` incorrectly in such a way that it throws an error in your task, your task would fail, but it looks like what you've done here raises an error during formatting of the log message.

> logs are not pulled for any of the errors or logs after the error.

If the logger cannot process a log message, it will always share that output locally rather than sending it to the server. 

Your example does not include additional logging after the failed message, do additional correct log messages fail to send?

**Comment by matmiad** [comment]
That is correct the issue is "Missing logs...". No logs after the logging errors occurs are sent to the cloud nor displayed in the cloud UI. The screenshots represent the end state with agent showing logs after error and cloud UI cutting off at the last log before the error.

**Comment by madkinsz** [comment]
I see. The "Finished in state" logs intended not to be sent to the server since you can see the state transitions already.
