### ISSUE TITLE
Flow Runs search on Dropdowns should search full text, rather than prefix

### ISSUE THREAD

**Issue by kevin868** [PrefectHQ/prefect#7176]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The Deployments page allows you to search a substring starting in the middle of the deployment name.

When searching the deployments list on the Flow Runs page the behavior is different, and your search only matches strings with the same exact start prefix.

(a blur between feature request and bug)

### Reproduction

1. Try a search from the /deployments page
2. Try a search from /runs page (using either Flows or Deployments dropdown). the substring result does not come up
Ex. full deployment name: *abc_deployment_123*
- On the deployments page, searching "_deployment_" or "_123_" will find that result
- On Flow Runs page, searching those will not work. it needs to be "_abc_" or "_abc_dep..._" to find that result

### Error

Expected a result, if I did have a deployment with this substring.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/15519577/195893939-bd0403c7-d23a-4784-932b-ab0f2b74b235.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.6.0
```

### Additional context

Somewhat related to https://github.com/PrefectHQ/prefect/issues/7135

**Comment by zhen0** [comment]
This has now been added.
