### ISSUE TITLE
Custom blocks cannot be used in deployments CLI

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#7177]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a custom storage block (such as [this one](https://gist.github.com/EmilRex/3674ad9016932bf5e1e15c8ad9a92896)) with `prefect deployment build` or `prefect deployment apply`, the command fails with the error below. This occurs even after registering the block. It's possible to work around this by either:

1. Importing the block into the flow as described in https://github.com/PrefectHQ/prefect/issues/6273
2. Installing the block into `prefect.collections` which is [how collections work](https://github.com/PrefectHQ/prefect/blob/9c6cc59/src/prefect/plugins.py)

Though perhaps this is not an outright bug, it's at least a misalignment of expectations.

### Reproduction

With the following as `hello.py`,

```python3
from prefect import flow, get_run_logger


@flow
def hello(name: str = "Marvin"):
    logger = get_run_logger()
    logger.info(f"Hello {name}!")
```

Run,
```shell
prefect deployment build hello.py:hello -n hello-test -sb <custom-block> -q default
```

### Error

```python3
'<deployment name>-deployment.yaml' did not conform to deployment spec: KeyError("No class found for dispatch key '<custom block>' in registry for type 'Block'."
```

### Versions

```Text
Version:             2.6.0
API version:         0.8.2
Python version:      3.9.14
Git commit:          96f09a51
Built:               Thu, Oct 13, 2022 3:21 PM
OS/Arch:             darwin/arm64
Profile:             emil-default
Server type:         cloud
```

**Comment by madkinsz** [comment]
Solved by https://github.com/PrefectHQ/prefect/pull/7179
