### ISSUE TITLE
Create a Settings guide  that includes common use cases

### ISSUE THREAD

**Issue by tpdorsey** [PrefectHQ/prefect#7188]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Concepts page shows some examples, but we could use a tutorial with examples of common use cases.

### Describe the proposed behavior

Create a tutorial for configuring settings and profiles. Include:

- setting and changing api url
- setting environment variables
- configuring deployment-specific settings and environment variables
- explain commonly used settings, how to find settings documentation in the API docs

### Example Use

Settings can be cryptic and inscrutable to new users. This will raise awareness.

In addition, the ability to set deployment-related settings and envars is not well documented at present.

### Additional context

Raised from internal discussion of potentially new ways to leverage settings. Let's get ahead of that.

**Comment by discdiver** [comment]
Closing in favor of the similar #10697.
