### ISSUE TITLE
Local docker images should be available as base images for environments

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#722]
Currently, it appears that building an image locally and specifying that as a base image for Docker-based environments does not work (it attempts to pull from remote registries).

We should find a way to fix this.

**cc:** @joshmeek

**Comment by joshmeek** [comment]
@cicdw We should revisit this

**Comment by cicdw** [comment]
Yea agreed @joshmeek ; I'm thinking this won't actually be possible without pushing to a registry, and instead we might just revisit offering a keyword argument for custom docker files?  Either way it'd be nice to wrap this issue up.
