### ISSUE TITLE
Regression - Manually returning state (Failed/Cancelled etc) in Flow Run doesn't terminate run with that state

### ISSUE THREAD

**Issue by voidel** [PrefectHQ/prefect#7220]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Manually setting state in Flow Run doesn't end run with that state. This used to work in 2.4.5, now that I've updated to 2.6.1, no longer works.

The [documentation](https://docs.prefect.io/concepts/states/#final-state-determination) states...

> If a flow returns a manually created state, it is used as the state of the final flow run. This allows for manual determination of final state.

The flow now ends as **Completed** regardless of the state that I return.

### CODE

```python3
from prefect import flow, get_run_logger
from prefect.orion.schemas.states import Failed, Cancelled

@flow
def test_flow():
    logger = get_run_logger()
    
    return Failed(message="Time to die")

    logger.info("Do stuff") # Basically just making sure this doesn't run and the flow run has stopped

test_flow()
```

### OUTPUT

```Text
16:16:49.931 | INFO | prefect.engine - Created flow run 'naughty-skunk' from flow 'test-flow'
16:16:50.069 | INFO | Flow run 'naughty-skunk' - Finished in state Completed()
```

### EXPECTED RESULT

Final state should be **Failed** not **Completed**

### Versions

```Text
2.6.1
```

**Comment by discdiver** [comment]
Closed by #7189, released in 2.6.2.
