### ISSUE TITLE
Error reading flow runs with async Orion python client

### ISSUE THREAD

**Issue by erikamundson** [PrefectHQ/prefect#7256]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using the Orion async python client to read flow runs raises a cloudpickle error attempting to load the byte data. This occurs both running the client method with asyncio directly and in an asyncio python console.

### Reproduction

```python3
import asyncio
from prefect.client.orion import get_client

client = get_client()
resp = client.read_flow_runs()
res = asyncio.run(resp)
print(res)
```

### Error

```python3
Traceback (most recent call last):
  File "my_workflow.py", line 50, in <module>
    print(res)
  File "pydantic/utils.py", line 411, in pydantic.utils.Representation.__repr__
  File "pydantic/utils.py", line 390, in genexpr
  File "pydantic/utils.py", line 390, in genexpr
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python-batch-service-template/lib/python3.8/site-packages/prefect/orion/schemas/states.py", line 167, in __repr__
    result = self.data.decode()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python-batch-service-template/lib/python3.8/site-packages/prefect/deprecated/data_documents.py", line 115, in decode
    data = lookup_serializer(self.encoding).loads(self.blob)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python-batch-service-template/lib/python3.8/site-packages/prefect/deprecated/data_documents.py", line 184, in loads
    return cloudpickle.loads(base64.decodebytes(blob))
TypeError: __init__() missing 1 required positional argument: 'path'
```

### Versions

```Text
Version:             2.6.3
API version:         0.8.2
Python version:      3.8.13
Git commit:          9e7da96e
Built:               Tue, Oct 18, 2022 1:55 PM
OS/Arch:             darwin/arm64
Profile:             test
Server type:         cloud
```

### Additional context

Other endpoints are working fine, all of these run just fine and return the expected results:

```python
client.api_healthcheck()
client.read_deployments()
client.read_block_documents()
client.read_logs()
```

Also, running `prefect flow-run ls` in terminal works and returns the correct results.

**Comment by madkinsz** [comment]
Thanks for the issue!

Note we do not expect the client to be used in this way. Does this reproduce if you do

```python
async def main():
   async with get_client() as client:
       return await client.read_flow_runs()

result = asyncio.run(main())
print(result)
```

**Comment by erikamundson** [comment]
> Thanks for the issue!
> 
> Note we do not expect the client to be used in this way. Does this reproduce if you do
> 
> ```python
> async def main():
>    async with get_client() as client:
>        return await client.read_flow_runs()
> 
> result = asyncio.run(main())
> print(result)
> ```

Hi, yes unfortunately that does reproduce the same error.

![Screen Shot 2022-10-24 at 10 08 39 AM](https://user-images.githubusercontent.com/67119169/197584858-59640858-79d4-4a54-8dbf-2031c0b76deb.png)

**Comment by erikamundson** [comment]
Interestingly, the `result` contains a real value (expected list of flow runs) in the debugger although the error still raises.

The value of `self.data` is an instance of `DataDocument(encoding='cloudpickle')`

If it helps, this is on a bare-metal conda install on an M1 Mac (using ARM-compiled version of packages).

**Comment by madkinsz** [comment]
Ah `ScriptError` requires a `path` on `__init__` which means that it cannot be pickled/unpickled. If you delete this run your problem should be resolved. Separately, we've removed this behavior from the `repr` for new results and this decoding error will only happen when using old versions.
