### ISSUE TITLE
Orion - add search functionality in block selection.

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7270]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If I define a block as an input for a flow or as a attribute of another block, I get a drop-down in Orion. If the list is long I have to scroll through lots of options.

### Describe the proposed behavior

Add search functionality to the drop-down. If I click a field in Orion that is of any block type, I can search through that list by typing.

The behavior would be similar how the search for issues here in GitHub works.

<img src="https://user-images.githubusercontent.com/24698503/197032103-1248981b-0436-4ebd-8783-24b1fb01b095.jpg" width="300">

### Example Use

This is especially helpful if one has lots of blocks of the same type. Say I have a custom Block called `ObjectDetectionModel`.

Each of these contains one trained and published model. If I have 100 of these the pure drop-down becomes a pain to use.

**Comment by zhen0** [comment]
To investigate - could we now use a combobox instead of a select here:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/40272060/201124097-bfefcad0-238e-461b-88bd-0203cfe0eed8.png">

**Comment by pleek91** [comment]
Needs https://github.com/PrefectHQ/prefect-design/pull/675
