### ISSUE TITLE
Login possible but not able to access content

### ISSUE THREAD

**Issue by thelfensdrfer** [PrefectHQ/prefect#7278]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This happened after a successful login:

https://user-images.githubusercontent.com/699106/197199540-c53ca4ef-46bf-4750-b9f1-780d13e2face.mov

Edit: After a force refresh (Cmd+Shift+R) I am immediately logged out. After a normal refresh, it just doesn't load the content. If I visit an old workspace URL that works for other people, I get a 404 error.

Edit 2: The audio is not important, was on a call during the screencast.

### Reproduction

```python3
/
```

### Versions

```Text
/
```

**Comment by discdiver** [comment]
Does it work ok in another browser?

**Comment by thelfensdrfer** [comment]
I tried in FF and Chrome.

**Comment by zhen0** [comment]
Hi @thelfensdrfer - I'm sorry to see you're having this issue.  I'm not certain but it's possible this is coming from a caching issue we're seeing in the UI.  I'm going to ask you to remove your service workers and see if that clears it out:
- Open the dev console
- Go to Application
- Select Storage
- Make sure 'Unregister service workers' is selected
- Click 'Clear site data' and then refreshing the screen.

I made a video to help with that: https://www.loom.com/share/dafeab2bab59436b8f724a420820a3f9

Can you let me know if that works for you. Thanks!

**Comment by thelfensdrfer** [comment]
> Click 'Clear site data' and then refreshing the screen.

This did work, so how can I help to fix this?

**Comment by zhen0** [comment]
Thanks for the question @thelfensdrfer - we have been doing investigation over the last week and have some PRs in the works that should tackle this from our side.

**Comment by zhen0** [comment]
@thelfensdrfer - we added some cache busting in our latest release so you should not see this again.  If you do, please can you let us know!  Thanks for reporting and keeping us updated.
