### ISSUE TITLE
Environments -> Build serializers + ExecutionEnvironments

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#728]
I believe (from first hand experience working with a user) that our current environment setup leads to frictions whenever a user wants to build a highly customized Docker image and also specify how / where their flow should run.  

After a conversation w/ @jlowin, I'm opening this issue to discuss splitting up our logic in a cleaner way so that our current notion of "Environment" becomes:

1.  a collection of routines / API routes for specifying how a flow should be serialized to an immutable location that a Prefect agent can access
2. our current setup / execute Environment classes become "ExecutionEnvironments", meaning they specify where and how the flow should run (e.g., Dask on Kubernetes)

I think this creates a cleaner separation of concerns and gives us the ability to expose a better API to users.  Additionally, we'll have to figure out how to express the compatibility restrictions between "build serializers" and "execution environments"

**cc:** @joshmeek

**Comment by joshmeek** [comment]
Discussion in #869

**Comment by jlowin** [comment]
Could we close this issue for #869?

**Comment by joshmeek** [comment]
👍
