### ISSUE TITLE
Prefect 2.0 Radar diagram to have a holistic view of all child tasks/sub-flow to the master flow

### ISSUE THREAD

**Issue by wbt-offcial** [PrefectHQ/prefect#7292]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

At the moment, when you have 3 layers of flows/tasks you can only click into them, and you are not able to see them all displayed in a single radar diagram.

### Describe the proposed behavior

Being able to have a option to see all tasks and flows in a single radar diagram.

**Comment by discdiver** [comment]
Closing as radar view is no longer present.
