### ISSUE TITLE
When using Safari, the UI hides the sidebar menu or it's in the wrong orientation

### ISSUE THREAD

**Issue by drfraser** [PrefectHQ/prefect#7297]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

This may be more of a complaint than a bug, but it was unexpected. When viewing localhost:4200 in Safari, I am getting a screen where the top banner bar (icon plus the hamburger menu) is along the left side, not the top. Clicking on the hamburger does nothing. One can change the URL manually to get to different screens, but things obviously are broken.

Clicking Safari's hide/show sidebar menu item/icon reveals the sidebar of "Flow runs", "Flows" etc but now you have the sidebar open and so screen real estate is wasted. The top banner bar is now at the top and clicking on the hamburger reveals a dropdown of the different menu items. 

I usually use Firefox so all that seems a lot more usable (the menu is open and displayed on the left). Safari ought to be initially putting the top banner at the top so things are immediately usable.

### Reproduction

View the UI using Safari 13.1.2

### Error

![InitialView](https://user-images.githubusercontent.com/611599/197485946-7d2e6222-83a1-4970-b868-43e281226c80.png)
![opensidebar](https://user-images.githubusercontent.com/611599/197485961-1876c00a-d5e6-4ba0-8f00-63701d3e62bd.png)

### Browers

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.3
API version:         0.8.2
Python version:      3.8.14
Git commit:          9e7da96e
Built:               Tue, Oct 18, 2022 1:55 PM
OS/Arch:             darwin/x86_64
Profile:             dryrun
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.3
```
```


### Additional context

_No response_

**Comment by zhen0** [comment]
Hi @drfraser - Thanks for the feedback. I tried this on Safari Version 16.0 (17614.1.25.9.10, 17614) and can't replicate.  Can you try a later version of safari and see if it's still an issue for you?

**Comment by drfraser** [comment]
I'm sorry, I completely forgot I'm on 10.13. I keep procrastinating to upgrade my iMac...  I will close this issue.
