### ISSUE TITLE
Cloud UI wrong mime type

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#7298]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

UI is failing to reload on refresh on chrome "Version 106.0.5249.119 (Official Build) (64-bit) - Windows 10".  this problem is gone on hard reset "CTRL SHIFT R"

### Reproduction

Load prefect cloud UI then refresh the page

### Error

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. 

![image](https://user-images.githubusercontent.com/16452985/197510120-bb33eec1-4b82-401f-9bfe-45e32f4e3790.png)

```
Request URL: https://app.prefect.cloud/index.debc182b.js
Request Method: GET
Status Code: 200 
Remote Address: 52.28.22.142:443
Referrer Policy: same-origin
age: 0
cache-control: public, max-age=0, must-revalidate
content-encoding: br
content-length: 502
content-security-policy: default-src 'self'; connect-src 'self' https:; font-src 'self' data:; frame-ancestors 'self'; frame-src https://js.stripe.com https://hooks.stripe.com https://auth.prefect.io; img-src 'self' data: https:; media-src 'none'; object-src 'none'; script-src 'self' 'unsafe-eval' blob: https://js.stripe.com https://cdn.redoc.ly; style-src 'self' 'unsafe-inline'
content-type: text/html; charset=UTF-8
date: Mon, 24 Oct 2022 10:50:25 GMT
etag: "a03837908d6c01496dd048beeabbce73-ssl-df"
permissions-policy: accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(self "https://js.stripe.com"), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()
referrer-policy: same-origin
server: Netlify
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-nf-request-id: 01GG4STXC3YZ30QYHJTN9KC4J7
x-permitted-cross-domain-policies: none
```

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
prefect cloud
```

**Comment by zhen0** [comment]
Hi @BitTheByte 

We believe this is from a bad service worker so although a hard refresh should clear it, to remove the problem we advise also unregistering service workers.  To do that you can:
1. Open the dev console
2. Go to Application
3. Select Storage
4. Make sure 'Unregister service workers' is selected
5. Click 'Clear site data' and then refreshing the screen.

I made a video to help with that: https://www.loom.com/share/dafeab2bab59436b8f724a420820a3f9
