### ISSUE TITLE
Add `host_config` dictionary to `DockerContainer` infrastructure block

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7301]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Some users want to set per-container memory limits using `mem_limit` and `memswap_limit`. This was possible on v1 `DockerRun` and some user expect the same on `DockerContainer` infra block

Links:
- https://docs-v1.prefect.io/api/latest/run_configs.html#dockerrun
- https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config
- user request for memory limits: https://linen.prefect.io/t/3229546/trying-to-migrate-to-prefect-2-using-the-flows-defined-in-do 

### Describe the proposed behavior

Expose `host_config` as a dictionary, the same way as it worked in v1

**Comment by madkinsz** [comment]
Let's focus on the use-case requirements here, I'm not sure exposing a `host_config` dictionary as in v1 will be the best solution.

**Comment by anna-geller** [comment]
fully agree, I cross-checked all these attributes and those two are the only ones that seem necessary: `mem_limit` and `memswap_limit`

the rest is either too niche or already included (`auto_remove`, `image_pull_policy` etc)

**Comment by thuyt001** [comment]
I also want to set a memory limit on the docker container so that it will terminate instead of consuming all the memory on the server and crashing the server. Per the docker documentation, I would need to set `--memory="[memory_limit]"` argument to enable this. Currently don't see a way to do this with Prefect 2.0 docker container block.

**Comment by davidssand** [comment]
Adding the `privileged` flag would also be very helpful (it is part of the `host_configs` argument). I cannot run a flow using the `docker:dind` image, as it requires this flag.
