### ISSUE TITLE
Hidden files are not uploaded to remote storage

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#7309]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using `RemoteFileSystem` as deployment storage block hidden files (filenames starting with a period) do not get uploaded.
This is the [line](https://github.com/PrefectHQ/prefect/blob/51e92dda965431c5f1beb486f0bcc4058035a868/src/prefect/filesystems.py#L345) that filters them out.
`glob.glob` does not list hidden files by default ([ref](https://docs.python.org/3/library/glob.html)).

```shell
touch .hidden
python -c 'import glob; print(glob.glob("./**", recursive=True))'
# ['./']
python -c 'import glob; print(glob.glob("./.**", recursive=True))'
# ['./.hidden']
```

### Reproduction

```python3
1. Create a file with filename that starts with a `.`
2. Create a deployment from a folder that contains the hidden file and uses RemoteFileSystem as storage
3. File is not uploaded
```

### Versions

```Text
Version:             2.6.4+13.g6d567ec3b
API version:         0.8.2
Python version:      3.10.6
Git commit:          6d567ec3
Built:               Mon, Oct 24, 2022 12:38 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

**Comment by madkinsz** [comment]
Thanks for the report! Seems like we ought to include hidden files by default.
