### ISSUE TITLE
Add type-casts for Parameters

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#733]
Since parameter values are going to be loaded from context (which is JSON-compatible), we should allow passing type-casting functions when creating a parameter.

Something like (arg name debatable):
```python
dt = Parameter('dt', type_cast_fn=lambda dt: pendulum.parse(dt))
```

We could also use output typing to do this automatically?

**Comment by jlowin** [comment]
I've implemented this functionality, but I'm not sure how to solve for the JSON result issue in the general case @cicdw. If a non-JSON compatible result is checkpointed as a repr, then the repr value is going to be passed to future runs.

**Comment by cicdw** [comment]
@jlowin in my mind our result-handler mechanism already provides all the machinery to get this working (it provides a way to go back and forth between JSON <-> something else efficiently and at the right times), so I'd vote to re-use that as much as possible.  The only piece you'd have to write custom is the initialization / initial casting of the Parameter.

**Comment by lauralorenz** [comment]
There's some ideas here that with PIN 16 we could implement this with result type subclasses. Can we revisit with the new PIN 16 designs?
- For example: `TypedResult` that takes a function to convert to and from JSON in the type that you want?
