### ISSUE TITLE
Extend test coverage for Postgres 14

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7333]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The docs say that Orion can run on [Postgres 13.0 or newer](https://docs.prefect.io/concepts/database/?h=postgres#database-versions) but we currently only test against Postgres 13 https://github.com/PrefectHQ/prefect/blob/main/.github/workflows/python-tests.yaml#L176

### Describe the proposed behavior

Extend test coverage for Postgres 14

**Comment by scottwalshqs** [comment]
Related, when I upgraded our prefect orion server from 2.4.5 to 2.6.7, I saw database related errors and the orion server went down.  We are running postgres 14.

```
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.DuplicateColumnError'>: column "state_timestamp" of relation "flow_run" already exists
```

**Comment by scottwalshqs** [comment]
I see the same error when I run `prefect orion database upgrade`

```
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.DuplicateColumnError'>: column "state_timestamp" of relation "flow_run" already exists
[SQL: ALTER TABLE flow_run ADD COLUMN state_timestamp TIMESTAMP WITH TIME ZONE]
```

**Comment by anna-geller** [comment]
maybe try a new environment entirely from scratch and specify Postgres before starting orion for the first time?

**Comment by scottwalshqs** [comment]
I believe that is what I did.  I am deploying Orion to kubernetes.  I was unable to login to the pod to run the database upgrade because it was failing, so I redeployed without starting the orion server, logged into the pod, and tried to run the database upgrade.  So the new pod should be a fresh environment.

**Comment by anna-geller** [comment]
did you consider using Prefect Cloud? there is a free version (no trial), you wouldn't have to deal with any of those DB migrations: https://app.prefect.cloud

**Comment by scottwalshqs** [comment]
I can definitely see the benefits of using Prefect Cloud.  But for now, we are planning to run on our own infrastructure as we migrate some of our first workflows to Prefect and evaluate it more broadly on all of our use cases.  We already had a couple rounds of calls with your Customer team and decided on this path for now.  I'll give the free version more thought, but I don't think it will work for us.  

I am in a dev environment now, so I can easily just reset the database and start fresh.  But I would like to understand how I can upgrade Prefect versions in the future once we are running in production.

**Comment by madkinsz** [comment]
@scottwalshqs Thanks for raising this. Do you see the same behavior with Postgres 13? We don't test our migrations on Postgres 14, but I'm surprised there's a difference. I'm giving this a test in https://github.com/PrefectHQ/prefect/pull/7553

**Comment by scottwalshqs** [comment]
@madkinsz I am not using Postgres 13 anywhere so I don't know if it's an issue there.  Thanks for looking into it.

**Comment by madkinsz** [comment]
With a higher database timeout, tests pass on Postgres 14 — it seems likely that something went wrong in the middle of your migrations causing the error you saw. It should not happen normally. cc @jakekaplan

**Comment by jakekaplan** [comment]
@scottwalshqs My guess is that you're in an intermediate state where part of a migration seemed to have committed but the other part did not. If you manually remove the part of the migration that succeeded (i.e. drop the new column) and try again with a larger timeout, it could succeed
