### ISSUE TITLE
Use a decorator to alert when a flow fails

### ISSUE THREAD

**Issue by khuyentran1401** [PrefectHQ/prefect#7338]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Many users like to add a decorator to a flow to send an alert when a flow fails. Thus, I created the package [prefect-alert](https://github.com/khuyentran1401/prefect-alert) to add this functionality.

```python
from prefect import flow, task 
from prefect.blocks.notifications import SlackWebhook
from prefect_alert import alert_on_failure

@task
def may_fail():
    raise ValueError()

@alert_on_failure(block_type=SlackWebhook, block_name="test")
@flow
def failed_flow():
    res = may_fail()
    return res

if __name__=="__main__":
    failed_flow()
```

However, this doesn't work when running flow through a deployment. 

When running `prefect deployment build`, I got the error: 
```bash
Found object of unexpected type 'function'. Expected 'Flow'
```

This is because adding the `@alert_on_failure` decorator returns an object of type `function` rather than type `Flow`. 

### Describe the proposed behavior

When building a deployment, Prefect will run either a flow or a function that wraps around a flow. This will make adding any decorators to a flow possible. 

To make this possible, @ahuang11 suggested that we can turn the block in [deployment.py](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/deployment.py#L757):

```python
        flow = prefect.utilities.importtools.import_object(entrypoint)
        if isinstance(flow, Flow):
            app.console.print(f"Found flow {flow.name!r}", style="green")
        else:
            exit_with_error(
                f"Found object of unexpected type {type(flow).__name__!r}. Expected 'Flow'."
            )
```
into
```python
    while hasattr(flow, "__wrapped__"):
        if isinstance(flow, Flow):
            break
        flow = flow.__wrapped__
```

This requires more testing to make sure it doesn't break anything.

**Comment by ahuang11** [comment]
If we do recursively find the flow, not sure if the alert would actually be deployed since it's outside the flow.

**Comment by billpalombi** [comment]
This is a cool idea! We should explore if/how this relates to automations.
