### ISSUE TITLE
Add mark state functionality for flow run and task runs in the UI 

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#7364]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently there is no way for users to change the state of a finished flow or task run for book-keeping purposes. 

### Describe the proposed behavior

Add an option in the three dot menu on the flow run and task run pages to change the state of a terminal state (crashed, completed or failed) run to another terminal state.  

### Example Use

I have a run that says it failed but it provided the information it needed.  For bookkeeping reasons I want to mark it as complete.

**Comment by zhen0** [comment]
@brigidgliwa @billpalombi - another one - could we get low fi designs here too?

**Comment by brigidgliwa** [comment]
@zhen0 @billpalombi I was looking at 1 to see what we had before do we need to include the checkboxes about mapped/non-mapped task runs?
![Uploading Screen Shot 2022-11-02 at 2.49.16 PM.png…]()

**Comment by billpalombi** [comment]
No, we do not need to design for explicitly mapped runs for the scope of this ticket. We can design for setting state for multiple task runs at once at a later time.

**Comment by brigidgliwa** [comment]
Here is a link to the figma designs: https://www.figma.com/file/WQwcuqBAxug8JqLigWaztu/Designs?node-id=2121%3A25028

Open to feedback on these designs 
![01-Mark State](https://user-images.githubusercontent.com/104096908/199585801-09c88565-89fc-4425-9957-ec515e7d3cf3.jpg)
![02-Mark State](https://user-images.githubusercontent.com/104096908/199585821-2b0b2704-0790-4757-b3f9-75a6eab27d49.jpg)
![03-Mark State](https://user-images.githubusercontent.com/104096908/199585843-eb0c8212-f284-4965-ab71-002117eb2019.jpg)

and I have 2 questions
1. Do we need a field for them to indicate why they are changing the state?
2. Do we need to have some sort of indicator after the state has been changed to show that it has been marked a different state?

**Comment by billpalombi** [comment]
> Do we need a field for them to indicate why they are changing the state?
@zhen0, We don't have anywhere to store a note that users give us, right? If so, I think we should cut that from scope.

> Do we need to have some sort of indicator after the state has been changed to show that it has been marked a different state?
This would be ideal, but again, I'm not sure we have any way of storing and retrieving that info at the moment.
 
I think we should change all references of "Mark" state to "Change" state.

**Comment by brigidgliwa** [comment]
I am good with changing Mark to Change...I used Mark because of the wording in this ticket https://github.com/PrefectHQ/orion-design/issues/598

If Jenny doesn't have any opposition to using Change rather than Mark, I will make the update

**Comment by billpalombi** [comment]
@brigidgliwa its your call, choose whatever you think is clearest "Mark", "Change", or something else.

**Comment by madkinsz** [comment]
@billpalombi We can store notes in the `State.message` field.

FWIW I think "Change" makes more sense than "Mark"

**Comment by brigidgliwa** [comment]
I updated it from Mark to Change. @billpalombi Let me know if you want me to add the note/indicator or keep the scope as it is now.

**Comment by billpalombi** [comment]
Thanks @madkinsz! If we have a place to store it, yes we should include a "note" field to be stored in `State.message`

**Comment by zhen0** [comment]
@brigidgliwa - would we add the note field to the modal?

**Comment by brigidgliwa** [comment]
<img width="1326" alt="01-Mark State" src="https://user-images.githubusercontent.com/104096908/201124750-f004f3c4-9faf-4ab8-83f6-d81154cb0d65.png">
<img width="1326" alt="02-Mark State" src="https://user-images.githubusercontent.com/104096908/201124777-26a47a4a-77fc-48b5-ab71-82337c7b4351.png">
<img width="1326" alt="03-Mark State" src="https://user-images.githubusercontent.com/104096908/201124798-6ba5cda0-c1b2-4b61-a6c3-a4bd8c776017.png">

Here are the updated images
