### ISSUE TITLE
Configuration of task concurrency limits in the UI

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#7366]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Task concurrency limits (by tag) are currently configurable in the CLI and API, but not the UI ([docs](https://docs.prefect.io/concepts/tasks/#configuring-concurrency-limits)).

### Describe the proposed behavior

Task concurrency limits are configurable in the UI.

**Comment by zhen0** [comment]
@billpalombi @brigidgliwa - would it be possible to get a design for this?

**Comment by brigidgliwa** [comment]
@billpalombi just to confirm...task concurrency is workspace scoped? and would the default be unlimited?

**Comment by billpalombi** [comment]
Yes, thats correct. [The docs describe the behavior in greater detail](https://docs.prefect.io/concepts/tasks/?h=task+conc#task-run-concurrency-limits).

**Comment by zhen0** [comment]
@brigidgliwa @billpalombi - checking in on this one

**Comment by brigidgliwa** [comment]
This is on my list of things to do this week

**Comment by WillRaphaelson** [comment]
So the [endpoint](https://github.com/PrefectHQ/prefect/blob/bdc7a19153a7551e32535ec0dd0b5231a33c0ae6/src/prefect/orion/api/concurrency_limits.py#L66) that gets task run concurrency limits by tag is going to get us the task ids occupying concurrency slots for free. Lets do this and https://github.com/PrefectHQ/prefect/issues/7536 at the same time as we'll be in the right context. We should also have a record for the global concurrency limit and its occupied slots. So the design punchlist for this IMO is

- designs for global and tag based concurrency limits
- designs for how t o display the task ids that are occupying concurrency slots
- stretch: from the display of occupying task runs, we should link to the task run page
