### ISSUE TITLE
Only show next scheduled run in Prefect UI for scheduled flows

### ISSUE THREAD

**Issue by kyledemeule** [PrefectHQ/prefect#7368]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently in "Flow Runs" for scheduled flows it shows all scheduled flow runs for the next 1-2 days in a scheduled state. For flows that run hourly this can be 20+ flow runs, which covers the screen. The "Runs" subtab on the "Flows" and "Deployments" page also has the same issue.

There is the view "No Scheduled", which will hide these. But:
1. I usually don't want them completely hidden, just not so many.
2. It’s not the default view so I constantly need to select it
3. It’s not available on the “Runs” tab view on “Flows” or “Deployments” pages (have to use the run states filter, and then select everything except scheduled, which is 7 states)

### Describe the proposed behavior

I would prefer to see (or have the option to see) only the **next** scheduled flow run for each flow, and ideally with a text description of the scheduled (e.g. "Every hour, between 06:00 AM and 10:00 PM, Monday through Friday", like is shown in the deployments table).

Another possibility would be to "stack" or "collapse" the scheduled flow runs for the same flow, and expand if desired.

### Additional context

[asked in slack](https://prefect-community.slack.com/archives/C0192RWGJQH/p1666959856284049?thread_ts=1666895769.939619&cid=C0192RWGJQH)

**Comment by zhen0** [comment]
Resolved by https://github.com/PrefectHQ/prefect/pull/7433
