### ISSUE TITLE
Record/show warnings/errors/critical log count in flow run list view in Prefect 2 UI

### ISSUE THREAD

**Issue by kyledemeule** [PrefectHQ/prefect#7370]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the flow runs list view (i.e. `https://app.prefect.cloud/account/<id>/workspace/<id>/flow-runs`) shows the following for each flow:

- flow run status
- runtime
- start time
- task run count
- flow name
- work queue
- tags

While knowing my flow completed/failed is good, sometimes my flow will complete but have warnings logged that I should probably action. Right now to notice this I have to click each flow run, go to logs, and then filter the log level to warning or above.

### Describe the proposed behavior

It would be nice if the flow run list view indicated if a flow run logged any warnings/errors/critical. It would be very nice if it had the number (e.g. "4 warnings"), but even just a boolean indication would be very helpful (e.g. "Completed - with warnings")

### Example Use

I scroll through "Flow Runs" tab for past 24 hours, and easily find a flow run that completed with warnings. I look into it's logs and see what the warning is, and notice my flow could be improved to better handle incoming data.

### Additional context

I didn't see anything like this mentioned on https://docs.prefect.io/ui/flow-runs/

**Comment by madkinsz** [comment]
I'm not sure this is feasible from a performance perspective, it's non-trivial to aggregate data from logs like this.

cc @WillRaphaelson for consideration as an events / observability feature.
