### ISSUE TITLE
prefect agent on kubernetes Deployment does not receive logs from KubernetesJob pods

### ISSUE THREAD

**Issue by popkir** [PrefectHQ/prefect#7371]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running an agent in kubernetes, the agent does not receive logs from workers... among other things, this means I can not see if flow run succeeded/failed from agent logs!

Here is my setup:
- all flows are stored in S3
- all flows run on the same infra block which is a KubernetesJob - new pod is spun up for each flow
- using Prefect Cloud to orchestrate

Everything was great when i was running prefect agent locally -- agent produces logs (output in CLI) similar to:

```
19:41:45.583 | INFO    | prefect.agent - Submitting flow run 'd03564b9-ad4e-4310-8662-184616d6406f'
19:41:47.416 | INFO    | prefect.agent - Completed submission of flow run 'd03564b9-ad4e-4310-8662-184616d6406f'
19:41:48.471 | INFO    | prefect.infrastructure.kubernetes-job - Job 'expert-lyrebird-xjq42': Pod has status 'Pending'.
19:41:49.155 | INFO    | prefect.infrastructure.kubernetes-job - Job 'expert-lyrebird-xjq42': Pod has status 'Running'.
19:41:52.098 | INFO    | Flow run 'expert-lyrebird' - Created task run 'My Example Task-c06c9343-0' for task 'My Example Task'
19:41:52.098 | INFO    | Flow run 'expert-lyrebird' - Executing 'My Example Task-c06c9343-0' immediately...
19:41:52.345 | INFO    | Task run 'My Example Task-c06c9343-0' - Finished in state Completed()
19:41:52.443 | INFO    | Flow run 'expert-lyrebird' - Finished in state Completed()
```

When running the agent locally but in docker container, the logs look similar.

Now I want the agent to run in a kubernetes deployment to automatically manage its uptime. Only 1 replica of agent pod is used.
However I only receive part of the log in the agent cli output -- it looks like no info is coming back from the worker pods back to the agent pod...

```
19:59:58.687 | INFO    | prefect.agent - Submitting flow run 'a510b13d-b0b5-4067-8610-518e6a2b45a8'
19:59:59.268 | INFO    | prefect.agent - Completed submission of flow run 'a510b13d-b0b5-4067-8610-518e6a2b45a8'
19:59:59.305 | INFO    | prefect.infrastructure.kubernetes-job - Job 'secret-iguana-zlm4f': Pod has status 'Pending'.
20:00:01.349 | INFO    | prefect.infrastructure.kubernetes-job - Job 'secret-iguana-zlm4f': Pod has status 'Running'.
```

What is going on ? how can I make the agent running on K8S produce a complete log ?

### Reproduction

```python3
see description & additional context
```

### Error

```python3
logs in the agent cli do not show info from the worker pods e.g. job statuses after 'Running'
```

### Versions

```Text
Version:             2.6.5
API version:         0.8.3
Python version:      3.9.15
Git commit:          9fc2658f
Built:               Thu, Oct 27, 2022 2:24 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

dockerfile I am using for the agent image
(installing prefect via pip because there is no official prefect arm64 image for testing locally on mac m1)

```
FROM python:3.9-slim
WORKDIR /app
RUN pip install prefect s3fs
EXPOSE 8080
COPY . .
CMD ./launch_prefect_agent.sh -k $PREFECT_API_KEY -u $PREFECT_API_URL
```

contents of launch_prefect_agent.sh

```
while getopts k:u: flag
do
    case "${flag}" in
        k) key=${OPTARG};;
        u) url=${OPTARG};;
    esac
done

prefect config set PREFECT_API_URL=$url
prefect config set PREFECT_API_KEY=$key
prefect agent start -q default
```

worker image dockerfile

```
FROM prefecthq/prefect:2-python3.9
WORKDIR /app
RUN apt -y update
RUN apt -y install python3-dev default-libmysqlclient-dev build-essential
RUN pip install --upgrade pip
COPY . .
RUN pip install -r requirements.txt

```

**Comment by Jaunson** [comment]
Having a similar issue with a nearly identical setup - notice the job pod dies, without sending any state or error info out so the Prefect cloud UI gets stuck with no way of knowing the pod is dead. This behavior makes it seem like the flow is running forever from the Prefect UI. 

Running on GKE + GCS

**Comment by rajeshwar-nu** [comment]
I am having a similar issue as well. Here is my setup --

- A prefect agent running in k8s pod on a work queue configured on prefect
- A simple flow which loops and logs current_time and sleeps for 1 second
- The flow is built and deployed as a KubernetesJob

When the k8s pod which is running the flow is terminated (either manually or due to k8s operation), the prefect server is unaware of this entirely. The flow status remains in `Running` state indefinitely. This issue https://github.com/PrefectHQ/prefect/issues/7116 suggests that restarted flows are not ran again as a design choice, in which case the expectation is that prefect should mark the flow as `Crashed` or `Failed`, and in no case it should be shown as `Running` indefinitely.

**Comment by madkinsz** [comment]
Are ya'll still encountering this on the latest version?

"Does not receive logs" sounds very different from "pod dies, without sending any state or error info" or "does not update the flow status"

**Comment by popkir** [comment]
sad you closed it
the issue is still there
