### ISSUE TITLE
Deployment tags not visible in cloud

### ISSUE THREAD

**Issue by pleek91** [PrefectHQ/prefect#7386]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

With the addition of the Created and Updated by columns there’s not much room to display tags and frequently tags are not visible at all. 

![8CB537A2-EDE9-4B6E-BD51-DFA9760A4017](https://user-images.githubusercontent.com/6200442/199019471-43ab9a44-716c-47e1-a027-b5c216307a79.png)

### Reproduction

In cloud view workspace deployments. 

### Error

N/A

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

**Comment by billpalombi** [comment]
@brigidgliwa could you help us think through a solution here? Maybe we could combine the two columns into a single “last updated by” column?

**Comment by WillRaphaelson** [comment]
Per a separate thread, I think if there's no opposition we like the column title of "Applied by" which should show the last user / SA to apply it regardless of whether it was the first or nth time.

**Comment by brigidgliwa** [comment]
@WillRaphaelson would "Applied by" replace both created by and updated by? or just updated?

**Comment by WillRaphaelson** [comment]
Would replace both, in my thinking.
