### ISSUE TITLE
Include Deployment count column on the Flows page in the Prefect UI

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#7401]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There are three columns in the table on the Flows page "Name", "Created" and "Activity." I don't know how many deployments each Flow has. In particular, I don't know which flows don't have any deployments. I may want to consider deleting those flows.

### Describe the proposed behavior

There are four columns on the Flows page "Name", "Deployments", "Created" and "Activity." I see a simple count of how many deployments each Flow has. If we can't fit the additional column, I believe this information is more important than the created datetime.

### Example Use

One of Prefect's workspaces has 58 Flows, but only 8 deployments. Figuring out which Flows don't have any deployments requires tediously visiting each flow page. While we could add a filter for this, its more general purpose to include, a deployment count for each flow.

### Additional context

Open questions:
- Should the count be a hyperlink directly to the "Deployments" tab for that flow? I like that idea.

**Comment by marichka-offen** [comment]
@billpalombi We don't have functionality built to go to a specific tab on a different page. I can add the deployment count to fulfill this ticket, but router-link to a specific place on a different page is a heavier lift and would be better as its own issue

**Comment by billpalombi** [comment]
Understood, thank you @marichka-offen!
