### ISSUE TITLE
Submitting sync task in async flow using the Dask TaskRunner results in error

### ISSUE THREAD

**Issue by peytonrunyan** [PrefectHQ/prefect#7422]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Submitting sync task in async flow using the Dask TaskRunner results in an error:
```
...
line 253, in _get_dask_future
    return self._dask_futures[key]
KeyError: UUID('18c9f158-ce2c-44aa-ac24-7d8438e753d3')
...
```
The error is resolved by adding `await asyncio.sleep(1)` after the task submission.

From a discussion in the internal slack:

> basically the future hasn’t been registered yet since it wasn’t actually submitted and the flow is exiting and attempting to wait for it
> 
> We need to close the task group used for submission before waiting for task runs to be completed
> 
> I think this will require the task group to move from `background_tasks` to somewhere else… I can add this to the engine reliability work

### Reproduction

```python3
import asyncio
from prefect import flow, task

from prefect_dask.task_runners import DaskTaskRunner

@task
def my_task():
    print("woof!")

@flow(task_runner=DaskTaskRunner)
async def my_flow():
    my_task.submit()
    # asyncio.sleep(1) # fixes error

if __name__ == "__main__":
    asyncio.run(my_flow())
```

### Error

```python3
...
line 253, in _get_dask_future
    return self._dask_futures[key]
KeyError: UUID('18c9f158-ce2c-44aa-ac24-7d8438e753d3')
...
```

### Versions

```Text
2.6.5
```

**Comment by zzstoatzz** [comment]
closed by https://github.com/PrefectHQ/prefect-dask/pull/131
