### ISSUE TITLE
UI:  Visual Indicator of Network Failure

### ISSUE THREAD

**Issue by dcupp** [PrefectHQ/prefect#7431]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When my laptop loses its connection to the internet while I am using the Prefect UI, the UI appears to continue to work, but says that there are no flows or flow runs in existence.  I noticed this the first time when my VPN client started acting up, but I am able to repro this by disabling WIFI on my browser.

To Reproduce:
1. navigate browser to the Prefect Cloud UI
2. go to the flow runs page, and see runs visible
3. disable WIFI
4. in the nav bar, click on "Flows" and then "Flow Runs" to navigate away from and back to the flow runs page
5. The UI shows a page that appears to be functioning normally, but with no runs.

### Describe the proposed behavior

Display some kind of visual indicator anywhere on the page, to indicate that the client-side code is having trouble connecting to the server, so that the user knows why their flows disappeared.  Something as simple as "Connecting...."   or some icon would be great.

### Example Use

While using the Prefect Cloud UI, my laptop loses connection to the internet for a few minutes.   I see all of my runs disappear, but I don't get confused because the UI indicates there might be a connection issue.

Later, someone deletes all of my runs.  The Prefect UI is empty, but there is no indicator telling me its having network issues, so I start looking for the person who deleted all my work.

**Comment by serinamarie** [comment]
Hi, @dcupp, thanks for the issue! I'm unable to reproduce your error but will add a UI tag to this in case someone else can. Are you still having this issue?
