### ISSUE TITLE
Including `env` in `customizations` for the `KubernetesJob` infrastructure block removes existing environment variables

### ISSUE THREAD

**Issue by rpeden** [PrefectHQ/prefect#7434]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using the `customizations` field of the `KubernetesJob` block to add environment variables to a container removes all existing environment variables including `PREFECT__FLOW_RUN_ID`. As a result, the job container is unable to run the flow.

I believe this happens because `KubernetesJob` sets env [here](https://github.com/PrefectHQ/prefect/blob/87767cdaa16afed2c7457ed6f7cccd79b220d113/src/prefect/infrastructure/kubernetes.py#L347) inside `_shortcut_customizations` and then patches in user-supplied customizations [immediately afterward](https://github.com/PrefectHQ/prefect/blob/87767cdaa16afed2c7457ed6f7cccd79b220d113/src/prefect/infrastructure/kubernetes.py#L295). 

`KubernetesJob` provides `env` field for user-supplied environment variables, but experienced Kubernetes users may provide their own `env` JSON patch out of habit (we saw this come up in a thread in community Slack). 

Perhaps `KubernetesJob` could check if `customizations` includes an `add` op with a path ending in `/env` and if so, merge it with other environment variables and then remove it from `customizations`. 

### Reproduction

```python3
Create a KubernetesJob block as you normally would, but use the following in the customizations field:


customizations=[
        {
            'op': 'add',
            'path': '/spec/template/spec/containers/0/env',
            'value': [
                {
                    'name': 'PROJECT_ID',
                    'value': 'cats-are-amazing'
                }
            ]
        }
    ]
```

Deploy, and initiate a flow run, and notice that the job container is unable to run the flow.

### Error

```python3
Invalid flow run id. Recieved arguments: ['/usr/local/lib/python3.10/site-packages/prefect/engine.py']
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1594, in <module>
    flow_run_id = UUID(
  File "/usr/local/lib/python3.10/uuid.py", line 171, in __init__
    raise TypeError('one of the hex, bytes, bytes_le, fields, '
TypeError: one of the hex, bytes, bytes_le, fields, or int arguments must be given
```

### Versions

```Text
Version:             2.6.6
API version:         0.8.3
Python version:      3.10.6
Git commit:          87767cda
Built:               Thu, Nov 3, 2022 1:15 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.3
```

**Comment by madkinsz** [comment]
You need to use `/-` to append an item to the end of a list:

```python
{
    'op': 'add',
    'path': '/spec/template/spec/containers/0/env/-',
    'value': {
        'name': 'PROJECT_ID',
        'value': 'cats-are-amazing'
    }
}
```
