### ISSUE TITLE
Manually retrying a flow doesn't work as expected

### ISSUE THREAD

**Issue by khuyentran1401** [PrefectHQ/prefect#7440]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In theory, the entire flow run is retriggered but only failed task runs are really rerun. However, from the logs, it seems like Prefect reruns the entire flow when manually trying in the UI.

This seems to be an unexpected behavior.

### Reproduction

```python3
import random
from prefect import flow, task, get_run_logger


@task(name="Long task")
def long_task():
    logger = get_run_logger()
    logger.info("I run successfully as expected!")
    return random.choices([0, 1], weights=[10, 1])[0]


@task(name="May Fail")
def may_fail(outcome: int):
    if outcome == 0:
        raise ValueError("The outcome can't be 0.")
    logger = get_run_logger()
    logger.info("I'm glad I didn't fail")
    return outcome


@flow(name="Main Flow")
def main():
    res = long_task()
    return may_fail(res)


if __name__ == "__main__":
    main()
```

### Error

`Long task` ran successfully the first time. Thus, this task shouldn't be run when manually retrying and the line `I run successfully as expected` shouldn't be in the logs. 
 
```bash
Created task run 'Long task-bcc3df51-0' for task 'Long task'
Executing 'Long task-bcc3df51-0' immediately...
I run successfully as expected!
Long task-bcc3df51-0
Created task run 'May Fail-e9dbd0ea-0' for task 'May Fail'
Executing 'May Fail-e9dbd0ea-0' immediately...
ValueError: The outcome can't be 0.
```

### Versions

```Text
Version: 2.6.6
API version: 0.8.3
Python version: 3.9.15
Git commit: 87767cda
Built: Thu, Nov 3, 2022 1:15 PM
OS/Arch: darwin/arm64
Profile: cloud
Server type: cloud
```

**Comment by madkinsz** [comment]
Are the logs duplicated? The logs from the first run are not going to be removed.

**Comment by khuyentran1401** [comment]
Ah you are right. My mistake. I'll close this issue.
