### ISSUE TITLE
Easily set task & flow run names

### ISSUE THREAD

**Issue by tothandor** [PrefectHQ/prefect#7463]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Tasks & flow runs get random names, which makes it hard to track correct behavior, and identify problem sources. Although the metadata of those runs contain the required information (e.g. name of processed item, time of execution, sequence number), those should be checked out separately. 

### Describe the proposed behavior

With Prefect v1 one could use `RenameFlowRun` and `task_run_name` to rename a flow or task run by a template. Prefect v2 provides `update_flow_run` for the former, but it's usage is quite complicated for this basic task. Also, for tasks `.with_options(name=...)` could not be applied when mapping is used.

I propose to have `task_run_name` again for tasks, and `flow_run_name` for flows, which would define a naming template for the respective entities. 

### Example Use

Processing collections of items could be a frequent use case. Usually each item has an own name or identifier. For example a directory of files, a list of queries, a batch of urls, a set of clients read from a database, where the list of items to be processed is not known in advance. A natural way of processing these would be to use mapping or a loop, but random (cool)names doesn't help to know what's going on, but a `task_run_name` template could.

Flow runs may be bound to a period of time (e.g. Monday, August, 45th week), or a sequence number (1,2,3,4,5...). If there was a problem, and those values could show up in the name, then it would be immediately obvious what was affected. A `flow_run_name` parameter of the flow containing a naming template could help with this.

**Comment by shaybensasson** [comment]
It would be great if that `task_run_name` will be used as `dask` future.key when `DaskTaskRunner` is used. This allows us to easily identify the task (run name) in dask's dashboard. Currently, all the futures have the same key ( the task name).

**Comment by AleksandrLiadov** [comment]
Hello, 

We are switching to Prefect 2 from 1 one.

And we have met the same problem. 
We'd like to have `@task(task_run_name="write_{feature.name}_results").`

Any news when it could be available?

**Comment by madkinsz** [comment]
@shaybensasson note using the task run name as the sole content of the Dask key is probably not acceptable as keys must be unique or Dask will not run it again. We can get around this though by append content after a `-` in the key to ensure it remains unique so like... `{slugify(task_run.name)-{task_run_key}`

**Comment by tothandor** [comment]
It's enough if the prefix could be specified, a unique suffix would do no harm.
