### ISSUE TITLE
Jump to the Logs tab rather than Subflow Runs page when navigating between subflows

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7475]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When navigating from parent to child flow:
![image](https://user-images.githubusercontent.com/86264395/200700412-a5505e81-f9c2-40c2-9ca9-90539ba1f165.png)

it would be great if we would jump to a Logs tab rather than Subflow Runs:
![image](https://user-images.githubusercontent.com/86264395/200700540-2371acad-efe4-4a94-a2f8-1094fc717342.png)

### Reproduction

```python
from prefect import flow, get_run_logger


@flow
def subflow1():
    logger = get_run_logger()
    logger.info("I'm a subflow 1")


@flow
def subflow2():
    logger = get_run_logger()
    logger.info("I'm a subflow 2")


@flow
def parent():
    logger = get_run_logger()
    logger.info("I'm a parent")
    subflow1()
    subflow2()


if __name__ == "__main__":
    parent()
```

### Error

it's not a bug

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.6
API version:         0.8.3
Python version:      3.10.6
Git commit:          87767cda
Built:               Thu, Nov 3, 2022 1:15 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
```

**Comment by zhen0** [comment]
I think this should be done by https://github.com/PrefectHQ/nebula-ui/pull/1892

**Comment by zhen0** [comment]
And https://github.com/PrefectHQ/prefect/pull/7439

**Comment by anna-geller** [comment]
ty Jenny!
