### ISSUE TITLE
S3 storage does not delete old files on deploy

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7476]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If i use  ` deployment.upload_to_storage()` the current files in the workspace are uploaded. If a file was deleted localy it is not removed from S3. I did not test this but i would assume that this effects all blocks with put_directory not just the S3 one.

### Reproduction

```python3
* deploy a flow with S3 storage
* delete a local file 
* deploy a flow with S3 storage
* file will still be in S3
```

### Versions

```Text
2.6.6
```

### Additional context

I use this workround to delete the content of the bucket before uploading it.

```python
s3_storage.filesystem.filesystem.rm(
            s3_storage.bucket_path + "/*", recursive=True
        )
```

**Comment by bunchesofdonald** [comment]
Thanks for the report @felix-ht! I feel like not deleting files is the proper behavior here. I understand that in your use case you're uploading these files to an S3 bucket and expect the local and remote filesystems to be synced. But if we begin assuming that's always the case we could accidentally delete files that weren't being managed by a prefect deployment. 

Maybe a better approach would be to add something like a `clear` bool argument to `upload_to_storage` that cause the remote storage to be cleared before uploading?

**Comment by bunchesofdonald** [comment]
That's a nice way of doing it, and it's probably the method I would suggest, but I also don't think we should restrict users to this specific method. I'm very hesitant to perform deletion by default, it could lead to a lot of unexpectedly lost data, especially for people new to Prefect. 

I agree that we should have some way of deleting files or clearing out remote storage. I'll write up an issue to implement some sort of file 'sync', which will _probably_ end up being some sort of a `clear` option.

**Comment by quassy** [comment]
@bunchesofdonald Is there any update on this? 

Not deleting files leads to unexpected behaviour for us with imports, e.g. you accidentally created a module called `os` once and now have to wonder why all usages of `os` (you'd expect stdlib) result in errors even though you have already renamed your own module to something sensible.

**Comment by bunchesofdonald** [comment]
Hi @quassy I created a separate issue to track it over here: https://github.com/PrefectHQ/prefect/issues/7486 @madkinsz mentioned some movement on it in that issue, but I'm unaware of the current state.
