### ISSUE TITLE
Better management of Notifications in Cloud 2.0 UI 

### ISSUE THREAD

**Issue by teherin** [PrefectHQ/prefect#7483]
**Why**

It would be ideal to better manage multiple teams web-hook notification configurations directly in the cloud UI where they are created. Currently there isn't a useful way of metadata tagging webhooks to know what Team + Channel the webhook belongs to.

**What**

* Allow a webhook notification to have a name that is displayed at the top level list of notifications
* show type of notification on main listing (teams vs slack vs email) - the bell icon seems to be used for BOTH teams + email. Could be solved by using email icon for email.
* add metadata for team name - could be visible at top level or on 'edit' page
* add metadata for channel name - could be visible at top level or on 'edit' page

**Notes**

example of what the notification main page could look like (grey is user defined name - purple is inherited from the notification)
![image](https://user-images.githubusercontent.com/11359389/200913066-2ded3d0d-9fcd-4986-99a4-a0a23b406ca8.png)
example of what the edit page could look like
![image](https://user-images.githubusercontent.com/11359389/200914079-27c2d069-f7d4-4a73-8f58-f92292b60045.png)

**Comment by madkinsz** [comment]
Hi @teherin! The PrefectHQ/ui is for v1, in v2 the UI is managed in the https://github.com/PrefectHQ/prefect

**Comment by WillRaphaelson** [comment]
Thanks for this submission @teherin - we're working on a wholesale expansion of notifications in Cloud (will be called automations), which should address some if not all of these concerns. I'm going to close this out, but I'll follow up once our first automations features are released in December.
