### ISSUE TITLE
Deleting a notification removes the wrong row from the table

### ISSUE THREAD

**Issue by teherin** [PrefectHQ/prefect#7488]
***If your bug is related to Cloud 2.0 or Prefect 2.0, please submit your issue in the [Prefect Repo](https://github.com/PrefectHQ/prefect)***

**Bug Description**

When deleting a notification from the notifications page the LAST notification row is aways shown as deleted in the UI. If the page is refreshed the correct notification is shown to be removed

**Steps To Reproduce**

1. Have 3 different notifications configured - helpful if they are all different methodologies so its easy to keep track of
2. Right click the 3 dots menu to delete the FIRST notification
3. On automatic page refresh observe the LAST row is the one that is removed in the UI
4. Manually refresh the page to see the correct notification removed from the list.

**Browsers Tested:**
* Chrome [ 107.0.5304.87 (Official Build) (arm64)] 

----------
**Notes**

**Comment by zhen0** [comment]
Hi @teherin - thanks for flagging this.  I'm moving to the 2.0 repo so that we can track correctly.

**Comment by zhen0** [comment]
Hi @teherin - can you confirm which version of Prefect you are on?  I can't replicate and wonder if this was something that was fixed by some api updates we made.  If you can confirm you're on the latest release (or cloud) I can dig in further.
