### ISSUE TITLE
Logs on UI are not synced with the logs on kubernetes worker

### ISSUE THREAD

**Issue by dimamovic-exos** [PrefectHQ/prefect#7494]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Logs on kubernetes worker and on UI are not synced after some point.

Logs on the worker
![image](https://user-images.githubusercontent.com/117183151/201174124-86b9c200-3c59-4c41-a51a-4618994ea0f0.png)

Logs on UI
![image](https://user-images.githubusercontent.com/117183151/201174291-d010c2a9-ddfe-4d84-a144-b4a8ae1a9c96.png)

### Reproduction

simplified code:
deployment task:
```python
@task
def run_deployment_task(
    flow_name: str,
    parameters: dict,
    flow_run_name: str,
    scheduled_time: datetime.datetime,
) -> FlowRun:
    return run_deployment(
        name=flow_name,
        parameters=parameters,
        flow_run_name=flow_run_name,
        scheduled_time=scheduled_time,
    )
```

main flow
```python
@flow
def main_flow(parameters:dict)
    for run_params in parameters:
        flow_run = run_deployment_task.submit(
            flow_name=flow_name + '/' + deployment_name,
            parameters=run_params['run_params'],
            flow_run_name=run_params['flow_run_name'],
            scheduled_time=run_params['schedule'],
        )
```

### Error

Logs on kubernetes worker
![image](https://user-images.githubusercontent.com/117183151/201174124-86b9c200-3c59-4c41-a51a-4618994ea0f0.png)

Logs on UI
![image](https://user-images.githubusercontent.com/117183151/201174291-d010c2a9-ddfe-4d84-a144-b4a8ae1a9c96.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

_Prefect cloud 2.6.5_

**Comment by BitTheByte** [comment]
+1 on this

**Comment by zhen0** [comment]
@madkinsz - any ideas where this one might be coming from?  Could it be connected to https://github.com/PrefectHQ/prefect/issues/6872?

**Comment by zhen0** [comment]
@dimamovic-exos - does Michael's response answer your question?  Is there a use case your concerned about here?

**Comment by dimamovic-exos** [comment]
Hey, thanks for response,
So if I understood correctly, information about submitting/creating task is not redundant while info about it's final status is? 
Any document which describe what will be logged or not?

And use case would be:
If we fire 100 tasks, with current approach we don't see any progress after submission.
