### ISSUE TITLE
Add documentation for agent `--match` argument

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#7511]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

https://docs.prefect.io/concepts/work-queues/#agent-configuration does not include coverage for the `--match` option.

### Impact

Users should get a full overview of agent capabilities in this document.

**Comment by ranbir7** [comment]
can i help with this?

**Comment by madkinsz** [comment]
Hey @ranbir7 looks like this is already in progress at https://github.com/PrefectHQ/prefect/pull/7768
