### ISSUE TITLE
Alternate graph of Flow Runs Page

### ISSUE THREAD

**Issue by dcupp** [PrefectHQ/prefect#7515]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

This is about the "dashboard" or "flow run history" graph on the "Flow Runs" page.   Same problem as #7458 but a different suggestion.

When we are running 100,000+ flows in Prefect, this dashboard graph becomes misleading.   It only seems to graph a tiny fraction of the runs, so depending on which filters you have set, you will see entirely different shapes ( a cluster of blue running dots on the right turns into a string of red failed at the bottom just by changing a filter).

Due to the graph's prominence I would assume that it is meant to give the operator an overall picture of the activity on the system, but it doesnt do this because it doesnt graph all of the data.

Also, graphing execution time on the Y-axis is not particularly helpful for our use case.   Our flows can have wildly different flow lengths, which are determined by which customer and which data they are running on.  Abnormal situations are caught by alarms.  Seeing a spike in runtimes vs lots of flows with short runtimes doesnt really tell us anything about the health of the system.

### Describe the proposed behavior

I propose giving us the option to show a different graph:
1. just boxes showing instantaneous counts of each flow state.  e.g.   Running=2300, Pending=23, Crashed=0, Failed=123, etc (this is with the expectation that operators will sit there refreshing the page to see if the numbers change)
2. A line graph of the counts of flows in each state over time (x axis is time, y axis is count of flows in the state).  
  2a.   A granularity of 5-10min would be necessary to be helpful in oncall situations
  2b. We would really want to be able to mouseover data points on each graph to see the exact number at that time.

Note:  I can kind of mimic the first one by setting filters and looking at the summation ("X flow runs") in the top left portion of what you call the "Flow run details" [1] -- the list of runs below the graph

[1] [Flow run details](https://docs.prefect.io/ui/flow-runs/

### Example Use

Use Cases
1. an operator gets paged by alarm showing something very strange going on with our k8s cluster.  She glances at the dashboard graph on the Flow Runs page on Prefect's cloud UI first.  She sees high numbers of flows currently in the Pending, Late and Crashed states, and escalates the alarm immediately.

2.   There are 3 times as many as many flows in the Running state as we expect.   Looking at the line graph of flows in the running state over time, we see that there is a spike just after a code deployment, and decide to roll back.

**Comment by ricardogaspar2** [comment]
Nice suggestion @dcupp ! 
I'd like to see a similar dashboard as existed previously on version 1, see: https://docs-v1.prefect.io/orchestration/ui/dashboard.html#overview

For observability purposes and at large scale, this is great to **visually** understand at a high-level how your pipelines are behaving, how many failures there are.

**Comment by ccueto36** [comment]
I second this. We are currently in the process of migrating to 2.0 after using 1.0 for many months and this is one of the things I miss around the 1.0 UI. The ability to see an overview of all flows is pretty essential, and I'm surprised it's not a thing in 2.0 Orion UI.

**Comment by zhen0** [comment]
A dashboard has now been added in Prefect and Cloud 2.  Closing as complete!
