### ISSUE TITLE
Block attribute cannot be reverted to a default empty value from the UI

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7516]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I was trying to remove the family name attribute on this block and it wasn't possible - the old name is kept

![bug](https://user-images.githubusercontent.com/86264395/201480891-dad54e36-38c4-4159-a929-31af37759b73.gif)

### Reproduction

```python3
see above
```

### Versions

```Text
Version:             2.6.7
API version:         0.8.3
Python version:      3.9.12
Git commit:          9074c158
Built:               Thu, Nov 10, 2022 1:07 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
```

**Comment by kielnino** [comment]
I have the same problem with the `auto-remove` option for the docker-infrastructure block (prefect 2.6.7). Can't set it back to false via the UI, once I enabled it.

**Comment by pleek91** [comment]
I believe this PR allows us to fix this in the UI https://github.com/PrefectHQ/prefect/pull/7470

**Comment by zhen0** [comment]
Add to the service method for update block document
