### ISSUE TITLE
UI does not display the flow run duration until the flow run finishes

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7525]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Duration should be updated during flow runtime, rather than only at the end

Currently, here is how we display duration during the entire runtime:

![image](https://user-images.githubusercontent.com/86264395/201680089-37a30aa7-95e2-4f6f-a454-a372d4b48224.png)

### Reproduction

```python3
import time
from prefect import flow, get_run_logger


@flow
def myflow(sec: int = 30):
    logger = get_run_logger()
    logger.info("Sleeping for %d s... 💤", sec)
    time.sleep(sec)


if __name__ == "__main__":
    myflow()
```

### Versions

```Text
Version:             2.6.7
API version:         0.8.3
Python version:      3.10.6
Git commit:          9074c158
Built:               Thu, Nov 10, 2022 1:07 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
```

**Comment by zhen0** [comment]
Adding to the UI backlog.  I think we're missing reactivity for the duration.

**Comment by zhen0** [comment]
Closed by https://github.com/PrefectHQ/orion-design/pull/802
