### ISSUE TITLE
Pausing deployment schedule in UI does not alter updated_by

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#7533]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When pausing or resuming a deployment schedule in the UI, the `updated_by` information does not get updated, whereas doing the same thing with the CLI does.

### Reproduction

With the following code in a file called `hello.py`,

```py
from prefect import flow, get_run_logger


@flow
def hello(name: str = "Marvin"):
    get_run_logger().info(f"Hello {name}!")

if __name__ == "__main__":
    hello()
```

As **User 1**: Create a deployment and inspect it,
```sh
prefect deployment build hello.py:hello -n test --apply

prefect deployments inspect hello/test | grep updated
```

As **User 2**: Toggle the deployment schedule on or off, then inspect the deployment to see there are no changes to `updated_at`, but `updated` does reflect a change,
```sh
prefect deployments inspect hello/test | grep updated
```

Again, as **User 2**: Toggle the deployment schedule on or off using the CLI, then inspect the deployment to see that both the `updated` and `updated_at` fields have changed,
```sh
prefect deployments pause-schedule hello/test

prefect deployments inspect hello/test | grep updated
```

### Error

```bash
# As User 1:

(default) ➜  examples prefect deployment build hello.py:hello -n test --apply
Found flow 'hello'
Deployment YAML created at '/Users/emilchristensen/github/examples/hello-deployment.yaml'.
Deployment storage None does not have upload capabilities; no files uploaded.  Pass --skip-upload to suppress this warning.
Deployment 'hello/test' successfully created with id '5003e6d4-dfec-454f-af5a-9bca86e4d370'.

To execute flow runs from this deployment, start an agent that pulls work from the 'default' work queue:
$ prefect agent start -q 'default'

(default) ➜  examples prefect deployments inspect hello/test | grep updated  
    'updated': '2022-11-14T22:05:03.338542+00:00',
    'updated_by': {'id': '88e3900b-8b60-4715-8c37-91f675113e46', 'type': 'USER', 'display_value': 'emil'},


# As User 2, toggle the deployment in the UI, then inspect:

(default) ➜  examples prefect deployments inspect hello/test | grep updated
    'updated': '2022-11-14T22:05:12.548231+00:00',
    'updated_by': {'id': '88e3900b-8b60-4715-8c37-91f675113e46', 'type': 'USER', 'display_value': 'emil'},


# As User 2, toggle the deployment with the CLI, then inspect:

(default) ➜  examples prefect deployments pause-schedule hello/test
Paused schedule for deployment hello/test

(default) ➜  examples prefect deployments inspect hello/test | grep updated   
    'updated': '2022-11-14T22:05:34.371740+00:00',
    'updated_by': {'id': 'a3a6e84c-d1d5-4973-8986-112bc18ee657', 'type': 'USER', 'display_value': 'emilrexco'},
```

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.7
API version:         0.8.3
Python version:      3.9.14
Git commit:          9074c158
Built:               Thu, Nov 10, 2022 1:07 PM
OS/Arch:             darwin/arm64
Profile:             emil-default
Server type:         cloud
```

**Comment by jakekaplan** [comment]
This is an issue purely on the Cloud side. Cloud is missing `set_schedule_active`/`set_schedule_inactive` from the routes it is changing `updated_by` for. Adding those there should remedy this.

I am unsure why the CLI uses `PATCH - /:id` but the UI uses `POST - /:id/set_schedule_active/inactive` to update the schedule. Is there a difference? Does it make sense to consistently use one over the other?

**Comment by madkinsz** [comment]
> I am unsure why the CLI uses PATCH - /deployments/:id but the UI uses POST 

Seems like the CLI should be updated to use the dedicated routes. Perhaps we should deprecate `is_schedule_active` on the `DeploymentUpdate` action and encourage use of the dedicated routes.
