### ISSUE TITLE
Add support for pickled files in importtools utilities

### ISSUE THREAD

**Issue by thomafred** [PrefectHQ/prefect#7545]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

It is currently not possible to import pickled files.

### Describe the proposed behavior

It would be cool if we were able to load flows from pickled-files in the same fashion Prefect 1 did it.

### Example Use

If an object has been pickled:

```python
import cloudpickle

class MyClass:
  def __init__(self, a: int, b: str):
    self.a = a
    self.b = b

mc = MyClass(123, "foo")
open("mc.pickle", "wb+").write(cloudpickle.dumps(mc))
```

It should be possible to load it using the `importtools::import_object`-function:

```
from prefect.utilities.importtools import import_object

mc = import_object("mc.pickle")
```

### Additional context

By adding pickle-support to `import_object`, deployments can specify pickled flows as entrypoint instead of python-files, similar to how flows were stored in Prefect 1.

The `.pickle` file-extension references that the file is a pickled python-object, however the extension `.flow` was used in Prefect 1.

**Comment by anna-geller** [comment]
We discussed alternative solutions with Thomas via Slack - for posterity, see the [discussion here for details](https://github.com/PrefectHQ/prefect/pull/7546#issuecomment-1331849093)
