### ISSUE TITLE
'name' and 'version' arguments for the @flow decorator are not optional

### ISSUE THREAD

**Issue by biancaines** [PrefectHQ/prefect#7550]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A user took note that the specification for 'name' and 'version' were of type 'str', however they are intended to be optional and should be of type 'Optional[str]' instead: see [flow.py](https://github.com/PrefectHQ/prefect/blob/a24c725629e1a6aef31bcb577d4a853a86fc1cbe/src/prefect/flows.py#L122).

### Reproduction

```python3
A reproducible example was not created for this specific bug.
User reported that they were providing the "version" from environment with "os.getenv()" which is of type "Optional[str]", causing their mypy type check to fail.
```

### Error

```python3
No error provided for this bug.
```

### Versions

```Text
2.6.7
```

### Additional context

PR for fix was opened here: https://github.com/PrefectHQ/prefect/pull/7549.

**Comment by madkinsz** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/7549
