### ISSUE TITLE
Low code task scheduling

### ISSUE THREAD

**Issue by ChenpiDog** [PrefectHQ/prefect#7561]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Now create task scheduling in the form of yaml.

### Describe the proposed behavior

Graphically create task and taskflow and such through interface elements (buttons, forms).
Configure the task timing scheduling policy on the user interface.

### Example Use

Users do not need to write any task scheduling code (for example, airflow needs to write python code) to implement task scheduling.

**Comment by peytonrunyan** [comment]
Hi @ChenpiDog could you add a few more details to what you envision this might look like? 

Would these tasks be defined by the user somewhere in python code, and then other users could create flows in a low-code manner by arrange the already-defined tasks? 

Or would the ability to create new tasks also be part of this?

Is there an existing interface in another tool that you feel does what you are envisioning?

**Comment by ChenpiDog** [comment]
@peytonrunyan This is a draft idea. I will try my best to describe my ideas clearly. Maybe it would be better to discuss some details.
![Prefect任务调度沟通 drawio](https://user-images.githubusercontent.com/55483982/202482445-84b2f736-68f4-4a89-92c0-7c5d103c24db.png)

**Comment by ChenpiDog** [comment]
> Hi @ChenpiDog could you add a few more details to what you envision this might look like?
> 
> Would these tasks be defined by the user somewhere in python code, and then other users could create flows in a low-code manner by arrange the already-defined tasks?
> 
> Or would the ability to create new tasks also be part of this?
> 
> Is there an existing interface in another tool that you feel does something like what you are envisioning?
> 
> I imagine a feature like this would be quite a ways in the future, but it's great to start getting thoughts in early.

I hope to provide a visual way to arrange and schedule tasks by dragging and dropping task types. Of course, Prefect can generate the corresponding Yaml when I arrange the task flow in this way.

**Comment by peytonrunyan** [comment]
Awesome, thanks for the detailed explanation!
