### ISSUE TITLE
Add ability to conditionally retry tasks on Error class 

### ISSUE THREAD

**Issue by jpidugu** [PrefectHQ/prefect#7576]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When using the `@task` decorator to specify retries, the only retry behavior that can be configured is number of retries and the delay between them (using `retries` and `retry_delay_seconds`).

### Describe the proposed behavior

In Prefect 1.x, a `retry_on` parameter is available that allows you to limit task retries to specific types of exceptions. It would be great if this parameter was also available on the `@task` decorator in Prefect 2.x.

### Example Use

```python
from prefect import flow, task

@task(retries=3, retry_on={ValueError})
def my_task_that_occasionally_fails(my_num):
    if my_num % 2 == 0:
        raise ValueError()
    else:
        raise KeyError()

def my_flow(a_number):
    my_task_that_occasionally_fails.submit(a_number)

if __name__ == '__main__':
    my_flow(2)  # retries three times
    my_flow(1)  # does not retry
```

### Additional context

The PR that added this functionality to Prefect 1.x is located [here](https://github.com/PrefectHQ/prefect/pull/5634) and the original issue is [here](https://github.com/PrefectHQ/prefect/issues/5139).

**Comment by madkinsz** [comment]
Right now, retry settings are passed to the API and the API makes the decision on whether a retry should be attempted. That design makes implementation of this feature a little tricky — the API can't unpickle an exception to check if it is an instance of given types. 

For example, currently:
- Client runs user code
- User code fails, exception is captured
- Client proposes a FAILED state to the server
- Server REJECTS the FAILED state and returns a SCHEDULED state instead
- Client proposes a RUNNING state at the scheduled retry time

To implement this as a "client-side feature" this would require us to modify proposal of the failed state:
- Client proposes FAILED state to the server, forcing the server to ignore retry rules

We don't have mechanisms in place to bypass a subset of orchestration rules, it's currently all or nothing (`force=True`). We probably don't want to use the force mechanic here. Instead we may want to hint to the API when a state is not retryable. A possible implementation:

- Extend `State.state_details` to include a `retryable: bool = None`
- Client sets `retryable` on proposed FAILED states depending on the exception type
- Server retry rules are extended to check for `retryable` before applying retry logic

**Comment by austinweisgrau** [comment]
Overlaps with #5611

**Comment by dominictarro** [comment]
Going to try and implement @zanieb's approach. 

One issue I see happening is the `retriable` detail prevents a deliberate rerun of the flow by the user (e.g. they fix the issue that caused the failure and want to rerun using the persisted results). I haven't checked yet, but is there an easy way of discriminating user retry requests from the automatic retry?

**Comment by maitlandmarshall** [comment]
+1 support for this. I am throwing an error if the result of an MSSQL statement affected more than one row. I would like the task to only retry on unexpected errors.

```
@task(
    on_completion=[_log_result_to_database],
    on_failure=[_log_result_to_database],
    retries=3,
    retry_delay_seconds=exponential_backoff(10),
    retry_jitter_factor=1,
)
def upsert_apvm_deltas(apvm_deltas: dict):
<snip>
 stmt = table.insert().values(
        # readd the VendorGroup and Vendor as we're creating it now
        {**values_to_update, "Vendor": vendor, "VendorGroup": vendor_group}
    )

    result = c.execute(stmt)

if result.rowcount != 1 and not result.is_insert:
    raise Exception(
        f"Unexpected row count when updating/inserting record: {result.rowcount}"
    )
```

**Comment by spedersen** [comment]
+1 for this feature, at times we tend to have connection issues with some of the services, being able to retry in these situations makes sense, however, if the exception can't be recovered from there is no point in retrying and we would just prefer to fail the task

**Comment by mattalhonte-srm** [comment]
+1 One particular use case for us is that we want it to Retry if it just went into a `Crashed` state due to AWS API Throttling limits, but if it's an actual Exception we want it to fail.  Here's how we did it it in Prefect 1.  

```
def make_restart_state_handler(no_restart_condition: t.Callable[[str], bool]):
    def fn(task, old_state, new_state):
        logger = prefect.context.get("logger")
        if new_state.is_failed():
            logger.info("FAILED")
            failure_message = new_state.message
            logger.info(failure_message)
            if no_restart_condition(failure_message):
                logger.info("END RUN!")
                raise ENDRUN(new_state)
            else:
                logger.info("RESTARTING!")
        return new_state

    return fn

no_restart_condition = lambda failure_message: "RESOURCE:" not in failure_message
only_restart_on_memory_error = make_restart_state_handler(no_restart_condition)
```
and then pass `state_handlers=[only_restart_on_memory_error]`  to the task in question.

**Comment by rbarrette** [comment]
+1. The ability to pass in a list of error classes to retry_on would be great, the inverse behavior might also be useful in particular situations. skip_retry_on or retry_unless?
