### ISSUE TITLE
Prefect UI uses external CSS, this delays UI for minutes in air-gapped environments

### ISSUE THREAD

**Issue by pbchekin** [PrefectHQ/prefect#7582]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Prefect UI uses an external CSS, specifically https://rsms.me/inter/inter.css. When using Prefect is air-gapped environments that do not have direct access to the Internet, Prefect UI takes several minutes to show, because a browser tries to fetch that resource from the Internet and eventually times out. Unfortunately, a browser does not show any elements until that timeout. 

### Reproduction

Reproduced in Chrome and Firefox. To reproduce open Prefect UI for the first time in air-gapped environment. It takes several minutes to show the UI elements on the page.

### Error

![image](https://user-images.githubusercontent.com/1797803/202614738-6f24e098-fa39-48bf-9db8-83633f21156b.png)
<img width="125" alt="image" src="https://user-images.githubusercontent.com/1797803/202614924-007ad6c2-5110-4d52-8ae6-b3313ef4d37c.png">

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.5
API version:         0.8.3
Python version:      3.8.10
Git commit:          9fc2658f
Built:               Thu, Oct 27, 2022 2:24 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

### Additional context

It would be nice for Prefect UI to avoid requesting resources from the Internet. It will allow using Prefect self-hosted deployment in air-gapped environments.

**Comment by znicholasbrown** [comment]
Hi @pbchekin  - thanks for the report. Opened a PR [here](https://github.com/PrefectHQ/prefect/pull/7586) if you want to give that a try. I didn't see any other 3rd party calls that were failing but if you see any let us know.
