### ISSUE TITLE
Environments need to install the correct "extras"

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#759]
After the requirements refactor, Environments which rely on kubernetes need to explicitly install the `"kubernetes"` extras for prefect.

~Additionally, if users are working on an install of Prefect with, say, `"templates"` extras, users will most likely expect that Prefect picks up on that and installs the correct dependencies into their docker containers.~

^^ addressed by the healthcheck feature of docker containers now

**cc:** @jlowin

**Comment by joshmeek** [comment]
In our newer model of a default Dockerfile vs user provided do you think the default should install all extras and in the user specified Dockerfile it is up to them?

Besides just installing all extras by default or the users specifying their own dependencies I'm not sure how we would introspect the flow to determine if and which tasks it uses from the task library.

**Comment by cicdw** [comment]
@joshmeek well that was the purpose of the healthcheck that I included.  The flow won't deserialize if all the correct python packages aren't available.

**Comment by joshmeek** [comment]
So should this be closed?
