### ISSUE TITLE
Make creating an API Key from the UI easier

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#7599]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

As a user who wants to create an API key so I can connect my computer to Prefect Cloud I must take the following steps from app.prefect.cloud to create a key

1. Click on the head icon in the bottom of the page (and know to look here)
1. Click on my bolded username (and know this is clickable)
1. Click on  _API Keys_ in the side bar menu

### Describe the proposed behavior

Make this workflow more intuitive and/or cut out steps.

Perhaps the easiest option would be to add a key icon to the far left menu, as in the attached image mockup, that would be a link to https://app.prefect.cloud/my/api-keys

<img width="50" alt="menu-key" src="https://user-images.githubusercontent.com/7703961/202914834-b210a480-2c3c-4e54-884b-fa9390cf867c.png">

### Example Use

An always-present key icon would provide a quick, intuitive way for users looking to create an api key to access the page to create one. The icon wouldn't be too obtrusive. 

### Additional context

Many users at PACC Boston struggled with finding where to create an API key in the current API key creation workflow. In an informal poll nearly half of the participants had difficulty with the current workflow.

**Comment by madkinsz** [comment]
See also: #7332 which creates an API key for the user from the CLI.

**Comment by zhen0** [comment]
Adding this to needs design because I'm not certain that adding the link in the side bar is the right way forward and we had a few ideas when reviewing this ticket. I think #7332 is definitely a big and better step forward for resolving this.

**Comment by discdiver** [comment]
One other related suggestion from PACC Boston was to make it more clear that  the username is a link. Now it looks like it just might be a heading and not also a link. Underlining the username might helpful. 

All of three changes might be valuable and not mutually exclusive.

**Comment by zhen0** [comment]
Agreed with the comment about user name. I'll add a separate ticket in the cloud ui to track that.
