### ISSUE TITLE
Populate `examples/` folders

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#760]
@joshmeek @jlowin please add to this list as much as you want:

Examples we should have:
- [x] example with state handler
- [x] example which requires retry and succeeds on second run
- [x] example with mapping
- [x] example showing scheduling (possibly both cron and interval)
- [x] example with a simple parameterized flow (running it multiple times gives multiple outputs due to the parameters)
- [ ] an example of a cool flow that uses the imperative API

These examples should be "bite-sized", and be ~3 tasks per Flow and easily readable.

Updated w/ suggestions

**Comment by aeroaks** [comment]
Maybe not the perfect place to ask, but is there a way to create a Flow out of distributed Tasks?

**Comment by joshmeek** [comment]
@aeroaks What do you mean by _distributed Tasks_? Are you referencing Dask.distributed or distributed in regards to a Task that is distributed over a system?

**Comment by aeroaks** [comment]
Hi, Currently looking into task that are distributed over a system.

**Comment by joshmeek** [comment]
Yes, creating a flow of tasks that are distributed over a system is completely possible! We, currently in the default Task Library, have some [tasks](https://docs.prefect.io/guide/task_library/kubernetes.html) for running jobs on Kubernetes (where each job is a task) but expanding the paradigm to support any other system should be straightforward. It just really depends on what that system is and it comes down to how you think it should be implemented.

**Comment by cicdw** [comment]
Additionally, if you are referring to execution of tasks in a distributed setting, you can create your own Dask cluster and then use the [`DaskExecutor`](https://docs.prefect.io/api/engine/executors.html#daskexecutor) to submit tasks to it.

**Comment by aeroaks** [comment]
Thanks @joshmeek and @cicdw .

**Comment by joshmeek** [comment]
Suggestion for the imperative API example. How about an example that shows a semi-complicated flow (e.g. not easy ETL) in various paradigms. functional / imperative / combination of both / etc...
