### ISSUE TITLE
ECSTask page on Prefect cloud displays incorrectly 

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#7612]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using the latest version of prefect as of today (2.6.8) when using the cloud UI and creating ECSTask the page does load correctly. Running the local UI displays the ECSTask page correctly 

<img width="847" alt="Screen Shot 2022-11-17 at 4 55 01 AM" src="https://user-images.githubusercontent.com/82345018/203147797-ecb84b56-c3e9-4ffe-9809-135e2f7f2d68.png">

### Reproduction
I am not sure if it is just a bug with the cloud UI since the local UI looks correct.
```python3
prefect register -m prefect_aws.ecs
```
I ran the above command on an older version of prefect where the ECSTask block was not being displayed on the cloud UI (version 2.6.4 or 2.6.5). When the block was registered this issue started to occur

### Versions

```Text
Version:             2.6.8
API version:         0.8.3
Python version:      3.9.15
Git commit:          68044e28
Built:               Thu, Nov 17, 2022 3:19 PM
OS/Arch:             darwin/x86_64
Profile:             cloud
Server type:         cloud
```

**Comment by zhen0** [comment]
Should be closed by https://github.com/PrefectHQ/prefect/issues/7612
