### ISSUE TITLE
Make the `job_watch_timeout_seconds` optional to watch Kubernetes resources as long as required

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7614]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

User request: "The default for job watch timeout is really short at 5 seconds, shouldn't this be bumped up?"

The docstring is misleading - this timeout doesn't only apply to job startup, but also to job completion

```python
class KubernetesJob(Infrastructure):
...
    # controls the behavior of execution
    job_watch_timeout_seconds: int = Field(
        default=5,
        description="Number of seconds to watch for job creation before timing out.",
    )
    pod_watch_timeout_seconds: int = Field(
        default=60,
        description="Number of seconds to watch for pod creation before timing out.",
    )
```

### Describe the proposed behavior

There's no reason to enforce a timeout during the watch

Behavior proposed by @madkinsz: user can add it if they want to, but it shouldn’t be the default. If there’s no state change in N seconds, there are no events and it looks like things have timed out. 

### Example Use

any deployment that uses `KubernetesJob` infra block

**Comment by discdiver** [comment]
Do we want to do the same with the `pod_watch_timeout_seconds`?

**Comment by anna-geller** [comment]
you got my intention right, Jeff

**Comment by zzstoatzz** [comment]
> @zzstoatzz would you be able to look at this one?

Yes! I'll look at this today
