### ISSUE TITLE
Error while using deployment.apply(): AttributeError: 'coroutine' object has no attribute 'apply'

### ISSUE THREAD

**Issue by megha120** [PrefectHQ/prefect#7616]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

While creating a deployment of a flow, I am getting an error in apply().
**AttributeError: 'coroutine' object has no attribute 'apply'**

prefect version: 2.6.7

### Reproduction

```python3
deployment_new = Deployment.build_from_flow(
    flow=train_flow, 
    name="example-deployment", 
    version=1, 
    work_queue_name="demo",
)
deployment_new.apply()
```

### Error

```python3
AttributeError: 'coroutine' object has no attribute 'apply'
```

### Versions

```Text
Version:             2.6.7
API version:         0.8.3
Python version:      3.9.7
Git commit:          9074c158
Built:               Thu, Nov 10, 2022 1:07 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.36.0
```

**Comment by madkinsz** [comment]
@megha120 can you please include a brief definition of the flow in the MRE? This is not an executable example.

**Comment by thatdevsherry** [comment]
I have come across the same error now. Created an example flow as first requested in this issue.

[Example repo](https://github.com/thatdevsherry/prefect_lsp_bug)

**Comment by thatdevsherry** [comment]
have come across the same error now. Created an example flow as first requested in this issue by @zanieb .

Should I create a new issue?

[Example repo](https://github.com/thatdevsherry/prefect_lsp_bug)

**Comment by zanieb** [comment]
@thatdevsherry since that's a type-checking error and this is a runtime error a new issue seems reasonable, however I think that https://github.com/PrefectHQ/prefect/issues/9688 the solution and your report is likely a duplicate.

**Comment by thatdevsherry** [comment]
@zanieb Thank you for pointing towards the potential solution. I'll take a look it. 👍🏼
