### ISSUE TITLE
Create a wrapper to run pre-existing functions as Tasks

### ISSUE THREAD

**Issue by jasonho-lynx** [PrefectHQ/prefect#7617]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Hi team, thank you for working on Prefect. I'd like to make a suggestion to make onboarding easier for new users.

To use Prefect, we must convert functions into Tasks by doing 2 things:
- Add a `@task` decorator to the function definition (https://docs.prefect.io/concepts/tasks/#tasks-overview)
- Create a Prefect logger with `get_run_logger()` and use it (https://docs.prefect.io/concepts/tasks/#tasks-overview)

Toy example:
```py
# from:
def add(a, b):
  # assume logger was created at top of module
  logger.info(a + b)
  return a + b

# to:
@task
def add(a, b):
  logger = get_run_logger()
  logger.info(a + b)
  return a + b
```

This means:
- If there are many pre-existing functions, every one of them has to be manually converted
- Functions that are shared by multiple users and used outside of Prefect's context (notebooks / other scripts) also require changes since the task code now has to be invoked with `.fn()` :
```py
@task
def add(a, b):
  ...

# other users that rely on this function must now use:
add.fn(3, 4)
```

This is definitely doable, though it presents a considerable barrier for newcomers.

### Describe the proposed behavior

Instead of converting existing functions into Tasks, it would be helpful to have a wrapper that enables running them as Tasks. Here is a suggestion:

```py
def run_prefect_task(function, has_logger=True, **kwargs):
    """Executes a function as a Prefect task. Enables logs to be captured in the Prefect UI.
    
    Parameters
    ----------
    function : callable
        The function to be executed.
    has_logger : bool = False
        Whether the function uses a logger and accepts it as a parameter. If True, a Prefect
        logger will be passed in.
    kwargs : any
        Arguments to be passed to the function.
    """
    # use the function's name as task name
    @task(name=function.__name__)
    def run(function, **kwargs):
        if has_logger:
            # init prefect logger. takes precedence over any other loggers defined in the function
            logger = get_run_logger()

            return function(logger=logger, **kwargs)
        
        return function(**kwargs)
    
    return run(function, **kwargs)
```

### Example Use

If we have some existing functions, we should first add a `logger` parameter if we want to pass in a Prefect logger:
```py
import logging

logging.basicConfig(level=logging.INFO)
module_logger = logging.getLogger(__name__)

# add a logger param
def add(a, b, logger=module_logger):
    logger.info(a + b)
    return a + b

# unchanged
def add_without_logger(a, b):
    return a + b

# add a logger param
def subtract(a, b, logger=module_logger):
    logger.info(a - b)
    return a - b
```

Then, we can use them in a flow like this:
```py
@flow
def run_flow():
    run_prefect_task(add, a=3, b=4)
    run_prefect_task(add_without_logger, has_logger=False, a=3, b=4)
    run_prefect_task(subtract, a=100, b=90)

run_flow()
```

Output:
```
... | INFO    | prefect.engine - Created flow run 'accomplished-longhorn' for flow 'run-flow'
... | INFO    | Flow run 'accomplished-longhorn' - Created task run 'add-d74e1ce5-0' for task 'add'
... | INFO    | Flow run 'accomplished-longhorn' - Executing 'add-d74e1ce5-0' immediately...
... | INFO    | Task run 'add-d74e1ce5-0' - 7
... | INFO    | Task run 'add-d74e1ce5-0' - Finished in state Completed()
... | INFO    | Flow run 'accomplished-longhorn' - Created task run 'add_without_logger-d74e1ce5-1' for task 'add_without_logger'
... | INFO    | Flow run 'accomplished-longhorn' - Executing 'add_without_logger-d74e1ce5-1' immediately...
... | INFO    | Task run 'add_without_logger-d74e1ce5-1' - Finished in state Completed()
... | INFO    | Flow run 'accomplished-longhorn' - Created task run 'subtract-d74e1ce5-2' for task 'subtract'
... | INFO    | Flow run 'accomplished-longhorn' - Executing 'subtract-d74e1ce5-2' immediately...
... | INFO    | Task run 'subtract-d74e1ce5-2' - 10
... | INFO    | Task run 'subtract-d74e1ce5-2' - Finished in state Completed()
... | INFO    | Flow run 'accomplished-longhorn' - Finished in state Completed('All states completed.')
```

### Additional context

We are exploring Prefect as an orchestrator for a repo that already has some code and notebooks created by others, and we'd like to minimize any changes required on their part. The suggested function above currently lives in a helpers module, but it would be nice it makes it into the official package:
```py
from prefect import run_prefect_task
...
```

I hope it is a feasible solution, but if there are other recommended approaches, please let me know. Thanks.

**Comment by madkinsz** [comment]
Hey @jasonho-lynx — thanks for the thorough writeup!

Why not just

```python
@flow
def run_flow():
    task(add)(a=3, b=4)
    task(add_without_logger)(has_logger=False, a=3, b=4)
    task(subtract)(a=100, b=90)

run_flow()
```

Interestingly, for the issue outlined here:
> Functions that are shared by multiple users and used outside of Prefect's context (notebooks / other scripts) also require changes since the task code now has to be invoked with .fn() :
```
@task
def add(a, b):
  ...

# other users that rely on this function must now use:
add.fn(3, 4)
```

We _could_ just allow tasks to be called outside of flows and call the underlying function for you. I'm not sure it's a great idea, but it is a possibility.

**Comment by jasonho-lynx** [comment]
Thanks for the reply @madkinsz!

Actually, I had no idea you could use tasks in the way you suggested 😅 That does indeed let us use existing functions as-is (requirement 1), but it seems that there wouldn't be task-level logging (requirement 2)? An alternative might be to create a logger at the flow-level and pass it in:

```py
@flow
def run_flow():
    logger = get_run_logger()  # create a flow logger here and pass it into tasks
    task(add)(a=3, b=4, logger=logger)
    task(add_without_logger)(a=3, b=4)
    task(subtract)(a=100, b=90, logger=logger)

run_flow()
```
Which would work, but since there isn't task-level logging, it can get unwieldy if there are multiple tasks involved.

On your second point about calling tasks outside flows, that would be neat! Although I imagine there may be some complexity in ensuring the logger behaves correctly in both contexts:
- Outside of flows, the task should use the module-level logger
- Inside flows, the task should use the logger from `get_run_logger()`

Which sounds similar to the discussion in issue 6767. If it is implemented, I'd be happy to use it, since it would only require decorating existing functions with `@task`.

Side note: a wrapper function like the one defined above has the slight benefit of keeping all the original Prefect code untouched, which may be less likely to break any existing functionality.

Will definitely defer to you and the team to determine what makes sense for the product! Let me know if there's anything I can help with.

**Comment by madkinsz** [comment]
Thanks for beingunderstanding!

The decorator syntax is actually just shorthand for `your_func = decorator(your_func)` :)

I'm going to mark this issue as "deferred" — I think your second requirement can be tracked in that logging issue and your first requirement is available with the existing `task` decorator. We'll have to think a bit longer on the idea of calling tasks outside of flows.
