### ISSUE TITLE
Ability to pass a YAML file of parameters to create multiple deployment runs 

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#7618]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

A user at PACC Boston requested the ability to use a YAML file of parameter key-value pairs to run a deployment multiple times with different parameter key-value pairs.

### Describe the proposed behavior

Flows would then be scheduled to run with the various parameter values.

**Comment by peytonrunyan** [comment]
Double checking - you're talking the equivalent of 
```python
params=[1,2,3,4,5,6]

for p in params:
    d = Deployment.build_from_flow(
        ...
       parameters={"dog": p}
    )
    d.apply()
    ...
```
but with the YAML file?

**Comment by discdiver** [comment]
Sorry @peytonrunyan Just saw this now. Yep, guess a user could just do that and read in the yaml file

```python

import yaml
from pathlib import Path

yaml_dict = yaml.safe_load(Path("data.yml").read_text())
```

from this [SO answer](https://stackoverflow.com/a/70488834/4590385)

Closing as this functionality seems adequate.
