### ISSUE TITLE
Deleting an existing value in a Block from the UI doesn't update the value to the default value

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#7621]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

After editing a block field in the UI to remove a value (so that it has no value), the change is not saved.

### Reproduction

In the Prefect Cloud UI:

1. Create a block and enter a value into a form field 
1. Edit the block to delete the value
1. Press save
1. Inspect the block - the value that was present before editing the block is still present

### Error

Observed with Docker and Kubernetes blocks.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.8
API version:         0.8.3
Python version:      3.10.5
Git commit:          68044e28
Built:               Thu, Nov 17, 2022 3:19 PM
OS/Arch:             darwin/arm64
Profile:             jeffmshale
Server type:         cloud
```
```


### Additional context

_No response_

**Comment by zhen0** [comment]
Thanks @discdiver - I believe this should be fixed by https://github.com/PrefectHQ/orion-design/pull/818 so should be fixed in today's release. Please let us know if you see this again.
