### ISSUE TITLE
Editing a deployment, whether via UI, code or YAML, the deployment no longer appears in the Scheduled state

### ISSUE THREAD

**Issue by esdrasnani** [PrefectHQ/prefect#7651]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When editing a deployment, whether via UI, code or YAML, the deployment no longer appears in the Scheduled state and the deployment is not submitted to the work queue. For it to work, I would have to delete the deployment and resubmit it with the changes already made.

### Reproduction

```python3
When editing a deployment, whether via UI, code or YAML, the deployment no longer appears in the Scheduled state and the deployment is not submitted to the work queue. For it to work, I would have to delete the deployment and resubmit it with the changes already made.
```

### Versions

```Text
Version:             2.6.9
API version:         0.8.3
Python version:      3.8.12
Git commit:          014d093e
Built:               Tue, Nov 22, 2022 2:14 PM
OS/Arch:             linux/x86_64
Profile:             prod_cloud
Server type:         cloud
```

**Comment by peytonrunyan** [comment]
Thanks for the issue! I believe that this is related to https://github.com/PrefectHQ/prefect/issues/7657. 

We currently have some work underway that should standardize how schedules behave after deployment updates.
