### ISSUE TITLE
CLI tooling to test Orion health

### ISSUE THREAD

**Issue by tjgalvin** [PrefectHQ/prefect#7655]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

It would be nice to have a method in the `prefect` cli to perform a simple 'hello world' type test to evaluate the health of the Orion service. Something like

`prefect cloud hello` and `prefect orion hello`

If the hello is successful, the CLI tool should produce a successful return code that a script (e.g. bash) could test against. 

### Describe the proposed behavior

A simple CLI tool to provide a basic health check of the Orion server to ensure it is available, and subsequent pipeline workflows could run. 

### Example Use

```
prefect orion hello

if [[ $? -eq 0 ]]
then
    echo "Running pipeline"
    long_running_prefect_flow.py
else
    echo "Prefect health check failed. Not running pipeline."
fi
```

**Comment by jawnsy** [comment]
Thanks for creating this issue! It looks like the design in https://github.com/PrefectHQ/prefect/issues/6990 might solve this use case as well -- is this a duplicate?

**Comment by tjgalvin** [comment]
Yes this is definitely exactly that! Sorry for missing it. I will close this now :)
