### ISSUE TITLE
Missing schedule after redeploying flow using Azure storage

### ISSUE THREAD

**Issue by toby-coleman** [PrefectHQ/prefect#7657]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When **re-deploying** an existing deployment using Azure storage, the upcoming auto-scheduled flow runs get removed, and do not reappear until after the first scheduled run should have happened, i.e. **the first flow run gets skipped**.

Step-by-step process to reproduce this issue is below. I have also tried to reproduce both using AWS S3 storage and with locally stored code (no storage). In both cases all flow runs get scheduled correctly, so I think this issue is **specific to Azure storage**.

1. Start with an empty workspace on Prefect Cloud. Create an Azure block named `storage` configured using the Azure connection string for a blob storage container. Setup a Prefect agent on the `test` work queue.
2. Save the `hello_world` flow below into `main.py`.
3. Deploy from the CLI using `prefect deployment build ./main.py:hello_world -n test-hello -sb "azure/storage" -q test -a`
4. In the web interface, attach a cron schedule to the deployment, e.g. `0 * * * *`.
5. Shortly after, some scheduled runs will appear in the web interface, see screenshot 1 below.
6. Re-deploy the same flow again using `prefect deployment build ./main.py:hello_world -n test-hello -sb "azure/storage" -q test -a`
7. The auto-scheduled flow runs disappear from the web interface, and do not reappear. See screenshot 2, taken a few minutes after I redeployed the flow at 2:54PM.
8. In this example, I would have expected the flow to execute at 3PM. Instead, at 3PM the auto-schedules reappear in the web interface, starting from 4PM, see screenshot 3.
9. At 4PM the flow gets run successfully, see screenshot 4. **The expected flow run at 3PM never took place.**

**Screenshot 1: Initial deployment**
![image](https://user-images.githubusercontent.com/13170610/204098187-ec202255-f677-47f7-b8c5-c740ba373714.png)
**Screenshot 2: After re-deployment (no schedules)**
![image](https://user-images.githubusercontent.com/13170610/204098271-01f26557-11d5-452b-9290-601e64650de3.png)
**Screenshot 3: Schedules reappear**
![image](https://user-images.githubusercontent.com/13170610/204098377-69d42b95-8dbd-4993-8e1c-05f602562e82.png)
**Screenshot 4: Working correctly from 4PM onwards**
![image](https://user-images.githubusercontent.com/13170610/204098545-f76d9981-2f2f-45b6-b7bf-779befdc4779.png)

### Reproduction

```python3
from prefect import flow, get_run_logger


@flow(name="hello-world")
def hello_world():
    logger = get_run_logger()
    logger.info("Hello World")
```

### Versions

```Text
Version:             2.6.9
API version:         0.8.3
Python version:      3.9.15
Git commit:          014d093e
Built:               Tue, Nov 22, 2022 2:14 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by peytonrunyan** [comment]
Hey there - thanks for the issue! I think it's probably related to https://github.com/PrefectHQ/prefect/issues/7651.

I actually see this same behavior when using local storage, so it's interesting that it's differing by platform. We currently have some work underway that should standardize how schedules behave after deployment updates.
