### ISSUE TITLE
Radar UI should update automatically as a flow run progresses

### ISSUE THREAD

**Issue by james-tisato** [PrefectHQ/prefect#7660]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When a flow is running and I navigate to the radar view, it shows the state of the flow run at the point in time that the radar was loaded. As the flow progresses (tasks complete, new tasks start etc.), the view does not update automatically. The user needs to refresh the page to see the latest state.

### Describe the proposed behavior

The radar view would update automatically to show the latest state of the flow run as the flow progresses. 

### Example Use

This change would allow the user to more easily visualise the running flow, get a clearer understanding of its progress and more quickly realise if a task is taking longer than it usually does / is stuck for some reason. You already get a feel for this from watching the logs update automatically on the flow run page, but I think it would be easier for most people to understand if they could see it graphically.

### Additional context

This change would also align with the automatic updating that happens on the logs view for a flow run. In fact, because the logs automatically update, I just assumed the radar view would as well (and subsequently thought it was a bug when that wasn't happening).

**Comment by znicholasbrown** [comment]
Confirmed this is an issue, will look into getting it resolved, thanks for reporting @james-tisato !
