### ISSUE TITLE
UI show SecretStr in nested blocks

### ISSUE THREAD

**Issue by tonal** [PrefectHQ/prefect#7675]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

UI show SecretStr in nested blocks.

### Reproduction

blocks.py:
```python
from prefect.blocks.core import Block
from pydantic import SecretStr

class MySqlConf(Block):
  host:str
  user:str
  password:SecretStr|None
  db:str

class ConfigBannerDrop(Block):
  mysql_read:MySqlConf
  mysql_write: MySqlConf
```
Save script:
```python
from pydantic import BaseSettings

from .blocks import ConfigBannerDrop, MySqlConf

class Settings(BaseSettings):
  mysql_read:MySqlConf
  mysql_write:MySqlConf

  class Config:
    case_sensitive = False
    env_prefix = 'BD_'
    env_file='.env'
    env_file_encoding='utf-8'

def main():
  sett = Settings()
  conf = ConfigBannerDrop(
    mysql_read=sett.mysql_read, mysql_write=sett.mysql_write)
  conf.save('epool-banner-drop', overwrite=True)

if __name__ == '__main__':
  main()
```

### Error

On page Blocks / epool-banner-drop show all passwords.
![image](https://user-images.githubusercontent.com/316216/204437540-9e7aa013-e6f3-4f1d-bf64-6001265422fb.png)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.9
API version:         0.8.3
Python version:      3.10.8
Git commit:          014d093e
Built:               Tue, Nov 22, 2022 2:14 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by zhen0** [comment]
Hi @tonal - thanks for creating the issue.  This is actually as designed - you can see more background in a similar previous issue https://github.com/PrefectHQ/prefect/issues/7562#issuecomment-1320078664

**Comment by tonal** [comment]
#6735
