### ISSUE TITLE
Allow the task run to get cache when attempting to enter a Running state again

### ISSUE THREAD

**Issue by anqilu** [PrefectHQ/prefect#7676]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Background: I would like to control the task run concurrency based on dynamic task input.

For below flow, `expensive_task` should only be run for 1 time, and the latter `expensive_task` should wait until the former `expensive_task` finishes, and read the cache.
```python
@task(cache_key_fn=task_input_hash)
async def expensive_task(x):
    # I would like this expensive_task to only enter Running state when there is no other Running expensive_task with same input
    print(x)

@flow
async def dummy_flow():
    await expensive_task.submit(1)  # This task should enters Running state
    await expensive_task.submit(1)  # This task should wait until the above task terminates, and then it should try to retrieve cache
```

I have looked into `cache_key_fn` and `concurrency-limit`. But both of them could not achieve my goal.

So I have introduced a redis lock to limit the concurrency of the task by doing:
```python
import pendulum
import redis_lock

from prefect.context import TaskRunContext
from prefect.engine import propose_state
from prefect.states import Pending, Scheduled
from prefect.tasks import task_input_hash


@task(cache_key_fn=task_input_hash)
async def expensive_task(x):
    task_run_ctx = TaskRunContext.get()

    client = task_run_ctx.client
    task_run_id = task_run_ctx.task_run.id
    task_run = await client.read_task_run(task_run_id)

    task_run_states = await client.read_task_run_states(task_run_id)
    logger.info(f'task_run_states={task_run_states}')

    running_states = list(filter(lambda state: state.is_running(), task_run_states))
    if running_states:
        cache_key = running_states[0].state_details.cache_key
    else:
        cache_key = ''
    # I would like this expensive_task to only enter Running state when there is no other Running expensive_task with same input
    task_run_lock = redis_lock.Lock(REDIS_CONN, cache_key)

    # Only allow 1 task run to acquire the lock
    if task_run_lock.acquire(blocking=False):
        print(x)
    else:
        scheduled_state = Scheduled(
            scheduled_time=pendulum.now('utc').add(seconds=20),
            message='Scheduled for 20 seconds later because of unavailable lock',
        )
        pending_state = Pending(name="PendingForLock", message='Lock not acquired')

        # Because of `prefect.orion.orchestration.core_policy::PreventRedundantTransitions`, we have to force change to Scheduled state
        await propose_state(
            client,
            task_run_id=task_run_id,
            state=scheduled_state,
            force=True,
        )

        # Then return a Pending state to allow the later second attempt to enter Running state in engine
        return pending_state
```

This however would not satisfy my goal. The second time when the `expensive_task` enters `RUNNING` state, it would not check whether the result is cached. Because `cache_key` is not passed to it during state transition from `PENDING` to `RUNNING`.

The reason is: inside `prefect.engine`, we have below logic to handle non-terminal state: (https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py?#L1366)
```python
if not state.is_final():
    logger.info(
        f"Received non-final state {state.name!r} when proposing final state {terminal_state.name!r} and will attempt to run again...",
        extra={"send_to_orion": False},
    )
    # Attempt to enter a running state again
    state = await propose_state(client, Running(), task_run_id=task_run.id)
```

When the task run enters `RUNNING` state at second time, it does not respect the cache key.

### Describe the proposed behavior

The task should check cache key even if it's the second time when it tries to enter `RUNNING` state.
Is that possible we fix this by doing:

```python
# Attempt to enter a running state again
state = await propose_state(
    client,
    Running(state_details=StateDetails(cache_key=cache_key)),
    task_run_id=task_run.id,
)
```

So we can keep the logic inline with when task run enters `RUNNING` state at first time (https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py?#L1277)

**Comment by madkinsz** [comment]
Hi! Thanks for the issue.

I'm not sure if it will be particularly easy, but I agree it'd be great to check the cache key on transition to RUNNING.

**Comment by cicdw** [comment]
This is now the standard behavior in 3.0 - caches are checked with every transition into a `Running` state
