### ISSUE TITLE
1.0: Setting Task State to Skipped does not skip task and it continues to run

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#7695]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running a flow with a couple tasks from the UI, setting one task to the "Skipped" state in the UI does not skip the and the task continues to run without actually skipping. 

### Reproduction

```python3
import time
from prefect import Flow, task
from prefect.executors import LocalDaskExecutor
import prefect

@task
def log_and_wait(message):
    run_count =0
    while run_count <= 20:
        prefect.context.get('logger').info(f"log: {message}\nrun_count: {run_count}")
        time.sleep(10)
        run_count += 1

@task()
def log_and_wait2(message):
    run_count =0
    while run_count <= 20:
        prefect.context.get('logger').info(f"log: {message}\nrun_count: {run_count}")
        time.sleep(10)
        run_count += 1

with Flow("messages", executor=LocalDaskExecutor()) as flow:
    wait = log_and_wait("message1")
    wait2 = log_and_wait2("message2")
    wait2.set_upstream(wait)
```

### Error

```python3
When "Set State" for log_and_wait is set to "Skipped" in the Cloud 1 UI, the task continues to run. 

log_and_wait2 also runs (which is expected since "Skipped" is treated like Success").
```

### Versions

```Text
1.4.0
```

**Comment by madkinsz** [comment]
I'm not sure this is supported since SKIP is handled client-side with a signal exception. Perhaps we should not allow this in the UI for clarity.

**Comment by zhen0** [comment]
Checked with @robfreedy and we think removing the Skipped option from the UI is the simplest option for now.  I'll see if I can dig into the 1.0 code for it.
