### ISSUE TITLE
Upgrade VuePress to 1.0

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#770]

**Comment by itsngansense** [comment]
@jlowin did you already upgrade to vuepress 1.0 and run into this? just need to know the steps i need to take here :)

**Comment by jlowin** [comment]
Yes, I actually have a branch that I just pushed called `vuepress-1.x` which has some of my upgrade changes (and probably some unwanted code bc i was messing around) -- we can pair on that later this week maybe to see what's up

**Comment by jlowin** [comment]
The only remaining blocker is the syntax highlighting, I've solved the rest (though a couple class names changed so we'll need to review for some that aren't picking up our styles)

**Comment by jlowin** [comment]
Just walked through with @dylanbhughes and our conclusion is that VuePress is not ready at this time. The dev server and actual build give very different output right now. Ironically, the built output is close to "correct" but the dev server is not. We will stick to pre-1.0 until this is resolved, as the UX of working with a dev server that doesn't reflect reality is terrible. In particular, the syntax highlighting is illegible.

Dev server:
![image](https://user-images.githubusercontent.com/153965/56248317-8b899300-6075-11e9-8ed0-276d89bbc91e.png)

Built:
![image](https://user-images.githubusercontent.com/153965/56248321-8f1d1a00-6075-11e9-9e8a-5cfe8fb95b41.png)


Dev server:
![image](https://user-images.githubusercontent.com/153965/56248329-9512fb00-6075-11e9-9b93-2e3e700919ee.png)

Built:
![image](https://user-images.githubusercontent.com/153965/56248332-993f1880-6075-11e9-8e5e-d98721bf0ccd.png)

**Comment by itsngansense** [comment]
looks like they recently made a fix with the latest vuepress release 1.0.0-alpha.47 — see [changelog](https://github.com/vuejs/vuepress/blob/master/CHANGELOG.md) for more info. 

went ahead and upgraded along with few changes to get syntax highlighting to work on dev so it should match production build now!

pushed to your `vuepress-1.x` branch via commit [9dc521f](https://github.com/PrefectHQ/prefect/commit/9dc521f4124f72b8a59e4e7487a32b53bf3647c5)  but didn't want to create a PR until we're all on board.

**Comment by jlowin** [comment]
Thanks @itsngansense! Confirm we're now unblocked by that issue. Unfortunately it looks like `sidebarDepth: 0` is no longer respected, trying to understand if that's a bug or a feature.

**Comment by jlowin** [comment]
In addition, the top-level sidebar name for all API references is wrong, it appears not to look through the HTML at the top of the README.md
