### ISSUE TITLE
Artifacts not supporting some Github-flavored markdown

### ISSUE THREAD

**Issue by bradleyhurley** [PrefectHQ/prefect#7711]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The documentation for [artifacts](https://docs-v1.prefect.io/orchestration/concepts/artifacts.html#artifacts) indicates it supports Github-flavored Markdown, but `<details>` are not rendering properly.

### Reproduction

```python3
from prefect import Flow, task
from prefect.backend.artifacts import create_markdown_artifact


@task
def make_artifact():
    create_markdown_artifact(
        """# Example1\n\n<details><summary>Toggle me!</summary>Peek a boo!</details>\n\n# Example2\n\n<details open>
<summary>Shopping list</summary>

* Vegetables
* Fruits
* Fish

</details>\n\n# Example3\n\n<details open>\n<summary>Shopping list</summary>\n* Vegetables\n* Fruits\n* Fish\n</details>"""
    )

def create_flow() -> Flow:

    with Flow() as flow:

        make_artifact()
        return flow

FLOW = create_flow()
```

You can also verify this behavior by using the built-in README editor in the UI.

Sample Mark Down

```
# Example 1
<details>
<summary>Toggle me!
</summary>
Peek a boo!
</details>


# Example 2
<details open>
<summary>Shopping list</summary>

* Vegetables
* Fruits
* Fish
</details>
```

[Prefect UI Example](https://imgur.com/CrSCo9C)

Markdown rendered via [JBT](https://imgur.com/HAc0yqw)

### Versions

```Text
prefect version
1.4.0
```

```
prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__BACKEND",
    "PREFECT__CLOUD__API",
    "PREFECT__CLOUD__AGENT__LABELS",
    "PREFECT__CLOUD__AGENT__AGENT_ADDRESS"
  ],
  "system_information": {
    "platform": "Linux-5.4.204-113.362.amzn2.x86_64-x86_64-with-glibc2.31",
    "prefect_backend": "server",
    "prefect_version": "1.4.0",
    "python_version": "3.9.13"
  }
}
```

### Additional context

I first reported this issue via[ Prefect Community Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1669781847469399).

**Comment by madkinsz** [comment]
cc @znicholasbrown :)

**Comment by znicholasbrown** [comment]
Thanks for the report @bradleyhurley - you're correct that we don't currently support this feature. I expect that we won't expand markdown support for 1.0 but I'll keep this open so we can use it to inform 2.0's markdown renderer.

**Comment by cicdw** [comment]
Closing as stale and because Prefect 1.x is no longer under active development.
