### ISSUE TITLE
Cancellation of a flow can leave subflows and tasks in RUNNING state

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#7732]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When cancelling a flow, the children can be left in a RUNNING state. This is misleading to users and can result in unreleased concurrency slots.

Edit Dec 3: Added tasks to report

### Reproduction

```python3
from prefect import flow, pause_flow_run


@flow
def other_flow():
    time.sleep(100)


@flow
def my_flow():
    other_flow()
```

### Error

```python3
No error — just incorrect state in the UI.
```

### Versions

```Text
2.7.0 / main.
```

**Comment by giorgiobasile** [comment]
I noticed a similar issue with tasks being kept in a `RUNNING` state on flow cancellation. This is particularly critical for tasks that have tag-based concurrency limits, as the slot occupied by the task will not be correctly released.

Should I create a dedicated issue for this?

**Comment by madkinsz** [comment]
@giorgiobasile I can update this one to reflect the issue for cancellation, for the timed out problem can you open a separate one?

**Comment by giorgiobasile** [comment]
Sure, I just created #7752 :)
