### ISSUE TITLE
Create test harness for new additions to the task library

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#774]
There are a few very common test patterns for new tasks in the task library, such as: 
- does initialization work
- does initialization set attributes
- do additional kwargs get passed to the base task init method
- do certain attributes raise runtime errors if not provided
- can certain attributes be provided either at init or at runtime

We should create a test harness that addresses these generic tests and makes it easier for new additions to get tested without reproducing a bunch of boilerplate.

Clearly new additions will have unique tests as well, but this will help test the high-level functionality.

**Comment by dshahid380** [comment]
Can I take this issue?

**Comment by joshmeek** [comment]
Go right ahead! If you take a look at the tests for the kubernetes, google, aws, etc... tasks under `tests/tasks` it should become evident that there is a pattern emerging of testing the things that @cicdw initially outlined in this issue.
