### ISSUE TITLE
Add a feature allowing to manually change task run state

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7744]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Prefect 1 had a feature allowing to set task run state e.g. mark a task run as Failed from the UI. This allows to rerun that task using the manual **Restart** from failure functionality

some users request the same behavior in v2

### Describe the proposed behavior

Add a backend utility allowing to take a task run ID and manually change its state, for example, to mark that task run as e.g. Failed

Then as a follow-up, add a UI feature in a task run tab of a Flow Run allowing to change the state e.g. mark as Failed

### Example Use

https://linen.prefect.io/t/8045444/in-prefect-v1-is-there-an-option-to-re-run-a-single-task-we-

**Comment by madkinsz** [comment]
We can also add a mechanism to retries to rerun completed tasks — would that make sense?

**Comment by anna-geller** [comment]
This would solve the problem, but how would we know where to start? Currently, we only reset the state of failed task runs and rerun, correct?

**Comment by madkinsz** [comment]
We always start from the top of the flow. Completed runs are just cached. Failed runs are allowed to transition back to a running state during retries.

**Comment by zhen0** [comment]
Is this what you mean @anna-geller - https://www.loom.com/share/c1ecf53658994a05a8a9473da1a50671 - we just added to the UI. 

Note - it's only possible from a terminal state to a terminal state (as you noted other changes involve more complexity).

**Comment by anna-geller** [comment]
@zhen0 the video is not available for me somehow (404). 

@madkinsz the user request was to restart a single task, essentially **cherry-picking which tasks should rerun** and which shouldn't. I don't know what's the right way to approach it. Perhaps the issue title/body is confusing because I immediately thought about the solution equivalent to v1, which was **marking specific task run states to a different state (e.g. Failed)** and then once those are marked as Failed, the restart from UI would "just work". But there might be a better way - feel free to change the issue title if this one suggests a specific solution too much

**Comment by zhen0** [comment]
Well that's no good! Hopefully you can see this one: https://www.loom.com/share/5bf652ec34c543baa36178b1c1bea67f
