### ISSUE TITLE
Consider using a trigger to implement the flow's final state determination

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#775]
In a sense, `FlowRunners` apply an `all_successful` trigger to their reference task to determine their final state. The logic for that call is [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/flow_runner.py#L466). It might be simplifying to actually use the `all_successful` trigger here.

This leads to a rabbit hole: should we allow flows to use other reference triggers?

**Comment by lauralorenz** [comment]
As of today, a similar effect can be achieved with a terminal task that has its own trigger that meets whatever arbitrary logic criteria the user wants.

However, we are still leaving this issue open for consideration at this time.
