### ISSUE TITLE
Connection pool error while submitting flow runs in prefect agent

### ISSUE THREAD

**Issue by imsurat** [PrefectHQ/prefect#7754]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We upgraded our Orion server and prefect agent to version 2.6.9 on Nov 29. We were using version 2.4.2 before that. Since then we have seen 3 occurrences of this issue, the symptom is that a deployment's flow runs start going into late run state. Two of these deployments are assigned to singleton queues. These deployments are scheduled to fire every 5 minutes.

From the logging, it was not clear for the first occurrence as to why this happened, but we can see that one of the flow runs was in "pending state" and all others were getting queued in the "Late state". If we delete the flow run that is stuck in Pending state, then the deployment flow runs start running normally again.

Today while combing through the logs I noticed this line again, which was there yesterday as well.

`RuntimeError: The connection pool was closed while 11 HTTP requests/responses were still in-flight
`

On searching for text `RuntimeError: The connection pool was closed while` I found 3 occurrences in last 2 weeks, all after Nov 29 2022. This indicates a likely regression as 3 different flows ran into this issue, and all of these have been running for over 2 months without any changes. We did not notice the first error as it happened to a flow not assigned to a singleton queue. 

  | Time | stream | message
-- | -- | -- | --
  | Dec 3, 2022 @ 14:16:59.665 | stderr | RuntimeError: The connection pool was closed while 11 HTTP requests/responses were still in-flight.
  | Dec 2, 2022 @ 11:11:29.722 | stderr | RuntimeError: The connection pool was closed while 18 HTTP requests/responses were still in-flight.
  | Nov 29, 2022 @ 22:36:54.736 | stderr | RuntimeError: The connection pool was closed while 1 HTTP requests/responses were still in-flight.

### Reproduction

```python3
At this time we do not know how to reproduce this issue, it has happened 3 times so far for 3 different flows.
```

### Versions

```Text
Version:             2.6.9                                                                                                                                                               
API version:         0.8.3                                                                                                                                                               
Python version:      3.9.15                                                                                                                                                              
Git commit:          014d093e                                                                                                                                                            
Built:               Tue, Nov 22, 2022 2:14 PM                                                                                                                                           
OS/Arch:             linux/x86_64                                                                                                                                                        
Profile:             default                                                                                                                                                             
Server type:         hosted
```

### Additional context

We are using Kubernetes infrastructure Block. Flows are packaged in the docker image.

Today we see two more deployments with flows-runs stuck in the pending state, that are not assigned to the singleton queue.  They were all slated to start within minutes of the flow run that we deleted I will leave them as is in case there is some data that can be pulled for them.

The flow run for singleton queue was scheduled to start at 2:16 pm PST. We had to delete this flow run as it is assigned to a singleton queue.
One flow was scheduled to start at 2:17 pm PST and another for 2:18 pm PST. These two are still stuck in a pending state.

**Comment by imsurat** [comment]
By any chance is this addressed by this PR - https://github.com/PrefectHQ/prefect/pull/7593 ?

**Comment by madkinsz** [comment]
@imsurat I believe the error

> RuntimeError: The connection pool was closed while 11 HTTP requests/responses were still in-flight.


is **always** the result of another error closing the connection pool. It is not an error that is meaningful on its own.

The error

> assert self.connection is None

is a bug in httpcore (https://github.com/encode/httpcore/issues/615) that was fixed in their latest release. Upgrading that package should resolve that issues.

**Comment by madkinsz** [comment]
Other HTTP errors are likely covered by the existing issue at #7512 and should be helped by https://github.com/PrefectHQ/prefect/pull/7593 :)
