### ISSUE TITLE
PREFECT_LOGGING_EXTRA_LOGGERS not registering logs to OrionHandler

### ISSUE THREAD

**Issue by tjgalvin** [PrefectHQ/prefect#7755]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It seems after #7569 that extra modules described by `PREFECT_LOGGING_EXTRA_LOGGERS` are not being registered with an `OrionHandler` correctly. The `incremental` check is somehow preventing this from being registered. 

### Reproduction

```python3
N/A
```

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.9.13
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         <client error>
```

### Additional context

I have been relying on the `PREFECT_LOGGING_EXTRA_LOGGERS` mechanism to capture the logs from external python modules my pipeline relies on. This was working fine up until prefect `2.6.9`. I believe the regression was introduced somehow in #7569 . At this version the logs from my external module were no longer being recorded to the `Orion` server / UI (which I am self hosting). 

However -- I could see these logs in the console output that my `slurm` cluster was recording. These logs were being handled by the prefect `ConsoleHandler` as they were formatted inline with the prefect logger formatter style. 

I went digging and eventually ended up in `prefect/logging/configuration.py` and noted that the check against the `incremental` boolean is somehow blocking the `OrionHandler` from being added to the `logger` of the external module. Specifically, this check

```
            if not config["incremental"]:
                logger.addHandler(handler)
```

I am very confused by this though, as I see that `incremental` is merely dependent on the state of `PROCESS_LOGGING_CONFIG`, and is set to `False` so long as (1) `PROCESS_LOGGING_CONFIG` is `None`, or (2) `setup_logging` has previously been called (thereby making `PROCESS_LOGGING_CONFIG` not `None`).

As a test I have explicitly omitted this `if not config['incremental']` check so that the `OrionHandler` defined by the default `logging.yml` is attached to the logger of my extra modulde, and as expected my external module logs are now being presented to the `Orion` service and available in its UI. But again, I am not entirely clear how this is happening. 

The furthest I have gotten with understanding how has been by adding a large collection of `print` statements to `setup_logging`, and using the new `PREFECT_LOGGING_LOG_PRINT` feature. At this point, I can trace the passage of flow through `setup_logging` through the `orion` UI -- which implies that `setup_logging` as already been run. Indeed, the value of `PROCESS_LOGGING_CONFIG` reported in the UI is not empty:

```
alue of PROCESS_LOGGING_CONFIG={'version': 1, 'disable_existing_loggers': False, 'formatters': {'simple': {'format': '%(asctime)s.%(msecs)03d | %(message)s', 'datefmt': '%H:%M:%S'}, 'standard': {'()': 'prefect.logging.formatters.PrefectFormatter', 'format': '%(asctime)s.%(msecs)03d | %(levelname)-7s | %(name)s - %(message)s', 'flow_run_fmt': '%(asctime)s.%(msecs)03d | %(levelname)-7s | Flow run %(flow_run_name)r - %(message)s', 'task_run_fmt': '%(asctime)s.%(msecs)03d | %(levelname)-7s | Task run %(task_run_name)r - %(message)s', 'datefmt': '%H:%M:%S'}, 'json': {'class': 'prefect.logging.formatters.JsonFormatter', 'format': 'default'}}, 'handlers': {'console': {'level': 0, 'class': 'prefect.logging.handlers.PrefectConsoleHandler', 'formatter': 'standard', 'styles': {'log.web_url': 'bright_blue', 'log.local_url': 'bright_blue', 'log.info_level': 'cyan', 'log.warning_level': 'yellow3', 'log.error_level': 'red3', 'log.critical_level': 'bright_red', 'log.completed_state': 'green', 'log.cancelled_state': 'yellow3', 'log.failed_state': 'red3', 'log.crashed_state': 'bright_red', 'log.flow_run_name': 'magenta', 'log.flow_name': 'bold magenta'}}, 'orion': {'level': 0, 'class': 'prefect.logging.handlers.OrionHandler'}}, 'loggers': {'prefect': {'level': 'INFO'}, 'prefect.extra': {'level': 'INFO', 'handlers': ['orion']}, 'prefect.flow_runs': {'level': 'NOTSET', 'handlers': ['orion']}, 'prefect.task_runs': {'level': 'NOTSET', 'handlers': ['orion']}, 'prefect.orion': {'level': 'WARNING'}, 'prefect.client': {'level': 'INFO'}, 'prefect.infrastructure': {'level': 'INFO'}, 'uvicorn': {'level': 'WARNING'}, 'fastapi': {'level': 'WARNING'}}, 'root': {'level': 'WARNING', 'handlers': ['console']}, 'incremental': True}
``` 

All in all -- I am confused by this. Is there some order of operations here? Is it possible that somehow the modules described by `PREFECT_LOGGING_EXTRA_LOGGERS` that are attached to `prefect.extras` and are retrieved by `logging.getLogger('prefect.extras')` are only attached after `setup_logging` has been called once already, and therefore `PROCESS_LOGGING_CONFIG` is not `None` when `setup_logging` is called a second time? In my digging and toying I was able to see some situations where `setup_logging` was called twice (for example `prefect versions` reported my `print` outputs twice). Given what I know of prefect and its logging (which is next to nothing), I do not see how else my one liner modification worked to restore the previous `PREFECT_LOGGING_EXTRA_LOGGERS` behavior.

**Comment by madkinsz** [comment]
Hm with

> PREFECT_LOGGING_EXTRA_LOGGERS="foo" python example.py

**example.py**
```python
from logging import getLogger
from prefect import flow


@flow
def foo():
    getLogger("foo").info("test")

if __name__ == "__main__":
    foo()
```

I see logs in the console and UI as expected. How are you configuring the setting?

**Comment by tjgalvin** [comment]
That is really interesting. 

So I have been setting things up as:

```
export PREFECT_API_URL="${APIURL}"
export PREFECT_LOGGING_EXTRA_LOGGERS="aces"

process_workflow.py
```

To add some complexity to this, I am using a `DaskTaskRunner` with a `dask_jobqueue.SLURMCluster` backend.  

Are there any other tests I can try to do? I will give your example a whirl and report back shortly. I'll try a similar test with a `DaskTaskRunner`.

**Comment by madkinsz** [comment]
Hm perhaps I can reproduce with

```python
from logging import getLogger
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner


@task(log_prints=True)
def bar():
    getLogger("foo").info("bar")
    print("hi")


@flow(task_runner=DaskTaskRunner)
def foo():
    bar()
```

**Comment by madkinsz** [comment]
Are you running against an existing cluster?

**Comment by tjgalvin** [comment]
That is interesting. When I run

```
export PREFECT_LOGGING_EXTRA_LOGGERS="foo"
python test_script4.py
```

with the script being

```
from logging import getLogger
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner
from prefect import get_run_logger

@task
def bar():
    getLogger("foo").info("bar")
    print("hi")
    get_run_logger().info("hello world")


@flow(task_runner=DaskTaskRunner)
def foo():
    get_run_logger().info("Flow starting")
    bar()
    get_run_logger().info("Flow wrapping up")

```

I get nothing registered in the orion UI, and I am also not seeing any console output. 

I am starting up a `SLURMCluster` as part of the workflow. Specifically, I am using `cluster_class` and `cluster_kwargs` parameters in `DaskTaskRunner` to spin up the dask-works when the task runner is created.
