### ISSUE TITLE
Task runs number includes subflow runs

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7756]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The task runs number should only display task runs, but it currently also includes subflow runs - it could be confusing

![image](https://user-images.githubusercontent.com/86264395/205489693-353bfe2e-1321-46c2-8600-54b66e12c5b9.png)
![image](https://user-images.githubusercontent.com/86264395/205489705-2c0fe0da-0830-4fe1-89a8-28e1d07efada.png)

### Reproduction

```python3
from prefect import flow


@flow
def extract_data():
    return 42


@flow
def transform_data(x: int) -> int:
    return x * 2


@flow(log_prints=True, name="ETL with subflows")
def main():
    x = extract_data()
    y = transform_data(x)
    print(x)
    print(y)


if __name__ == "__main__":
    main()
```

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.10.8
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted
```

**Comment by madkinsz** [comment]
I agree we should not include these in the count and it should be easy to avoid doing so.

**Comment by madkinsz** [comment]
@zhen0 can you just pass a filter to the `task_run_count` route to exclude task runs that link to a flow run?

**Comment by zhen0** [comment]
Add `subflow_exists: false ` to our task run count queries (apart from where we are explicitly filtering for sub flows)
