### ISSUE TITLE
Name mapped task runs after the input from iterable

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7760]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Given this example flow:

```python
from prefect import task, flow


@task
def upstream_task(item):
    if item == "c":
        raise Exception("this upstream task failed")
    return str(item) + "+1"


@task
def downstream_task(item):
    return str(item) + "+2"


@flow
def demo():
    items = ["a", "b", "c", "d"]
    first = upstream_task.map(items)
    downstream_task.map(first)  # runs only for a, b, and d. c is in NotReady state


if __name__ == "__main__":
    demo()
```

When viewing the info from the UI, it's hard to know for which input the mapped "chain" failed - here, it failed for "c" input, but it's not possible to know.

![image](https://user-images.githubusercontent.com/86264395/205602155-4d441c28-a81b-4ca8-be67-5b38227b31ec.png)

Even task inputs don't provide that information:
![image](https://user-images.githubusercontent.com/86264395/205602626-dce557e0-b630-452d-a0d7-3beb0ccdf99d.png)

I would assume 0 means "a" etc, but even if it's true, it would be better UX if this would be displayed directly, e.g. if I map over 50 countries as input, I'd love to see mapped task for each country as a separate task run name for easy troubleshooting

### Describe the proposed behavior

Concatenate the input argument provided to mapped child task run to the task run name to distinguish between e.g. "upstream_task" for a, b, c, or d

it could be: `{task_name}_{input_from_iterable}_{random_suffix_as_is_today}`

### Example Use

use case from the community

**Comment by anna-geller** [comment]
gotcha, thx for clarifying. It's really hard to use mapping otherwise. I was able to easily use `.with_otpions` to provide custom names when submitting tasks in a for loop and felt a bit frustrated that I couldn't do the same with mapping. Example:

For loop:
```python
@flow
def generate_thumbnails(
    in_dir: str = "small", extension: str = "png", size: Tuple[int, int] = (128, 128)
):
    img_dir = Path(".", in_dir)
    out_dir = Path(".", in_dir, "thumbnails")
    images = get_images.submit(img_dir, extension)
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    for img in images.result():
        img_ = str(img).replace(f"{in_dir}/", "")
        process_image.with_options(name=img_).submit(img, out_dir, size, extension)
```
![image](https://user-images.githubusercontent.com/86264395/205674979-10845e6f-11bc-446f-b7ad-4c484fafe38c.png)


Mapping:
```python
@flow
def generate_thumbnails(
    in_dir: str = "small", extension: str = "png", size: Tuple[int, int] = (128, 128)
):
    img_dir = Path(".", in_dir)
    out_dir = Path(".", in_dir, "thumbnails_mapped")
    images = get_images.submit(img_dir, extension)
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    process_image.map(
        images.result(), unmapped(out_dir), unmapped(size), unmapped(extension)
    )
```
![image](https://user-images.githubusercontent.com/86264395/205675178-25fd383a-c8b4-4520-909f-b7741b8bb156.png)

**Comment by PiotrSiejda** [comment]
This is done IMHO. If we change code from example into:
```
from prefect import task, flow


@task(task_run_name="Task_for_{item}")
def upstream_task(item):
    if item == "c":
        raise Exception("this upstream task failed")
    return str(item) + "+1"


@task(task_run_name="Task_for_{item}")
def downstream_task(item):
    return str(item) + "+2"


@flow(flow_run_name="Our_demo_flow")
def demo():
    items = ["a", "b", "c", "d"]
    first = upstream_task.map(items)
    downstream_task.map(first)  # runs only for a, b, and d. c is in NotReady state


if __name__ == "__main__":
    demo()
```

It produces correct results. Another shorter example:
```
from prefect import flow, task


@task(task_run_name="Task_for_{in_str}")
def task1(in_str: str):
    return in_str+'bb'


@flow(flow_run_name="My_flow_name2")
def ff():
    ss = ["ww", "aa", "pp"]
    task1.map(ss)
```

This was fixed in: https://github.com/PrefectHQ/prefect/pull/8378 / https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-2712

**Comment by madkinsz** [comment]
Thanks!
