### ISSUE TITLE
Data dependencies between tasks are not correctly visualized unless tasks are submitted to a task runner

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7777]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

Given this flow:

```python
from prefect import task, flow


@task
def extract() -> int:
    return 42


@task
def transform(x: int) -> int:
    return x * 2


@task
def load(x: int) -> None:
    print(x)


@flow(log_prints=True)
def etl():
    e = extract()
    t = transform(e)
    load(t)


if __name__ == "__main__":
    etl()
```

We get this lineage:
![image](https://user-images.githubusercontent.com/86264395/205918093-87e30a95-fb6c-4a27-aeb0-e926b8812ad4.png)

The correct one, based on data dependencies, is reflected only when tasks are submitted to a task runner:
```python
@flow(log_prints=True)
def etl():
    e = extract.submit()
    t = transform.submit(e)
    load.submit(t)
```
![image](https://user-images.githubusercontent.com/86264395/205918358-dab0bb98-961a-42ad-8238-fdae290093ba.png)

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.10.8
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted
```

**Comment by anna-geller** [comment]
looks like this can be easily circumvented using `return_state=True` as well (still not using task runners unless needed):
```python
from prefect import task, flow


@task
def extract() -> int:
    return 42


@task
def transform(x: int) -> int:
    return x * 2


@task
def load(x: int) -> None:
    print(x)


@flow(log_prints=True)
def etl():
    e = extract(return_state=True)
    t = transform(e, return_state=True)
    load(t, return_state=True)


if __name__ == "__main__":
    etl()
```

@madkinsz feel free to close the issue 
![image](https://user-images.githubusercontent.com/86264395/205937692-8a2f0559-ef21-4a3b-932b-c5d96597523b.png)

**Comment by madkinsz** [comment]
@anna-geller we can't track small integers because Python uses the same memory address for every instance.
