### ISSUE TITLE
Prefect Agent 2.6.3 did not recover from 500 errors after several days

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect#7782]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A Prefect Cloud customer reported that their Agent failed to recover after receiving a series of 500 errors during a brief outage/configuration issue on Prefect Cloud.  The agent experienced these 500 errors in the period between 2022-12-01 3:30pm ET and 3:41pm ET, and then customer discovered the Agent hadn't recovered by 12/3.  The agent stopped emitting logs during the outage, but did not crash.

### Reproduction

```python3
# n/a
```

### Error

@EmilRex has provided a sanitized agent log attached to this issue

### Versions

```Text
Version:             2.6.3
API version:         0.8.2
Python version:      3.10.8
Git commit:          9e7da96e
Built:               Tue, Oct 18, 2022 1:55 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by EmilRex** [comment]
@chrisguidry Here are the logs: [prefect-orion-69747cc755-v6vq6.log](https://github.com/PrefectHQ/prefect/files/10169396/prefect-orion-69747cc755-v6vq6.log)

**Comment by zhen0** [comment]
Marking as stale and closing after discussion with @madkinsz and @billpalombi
