### ISSUE TITLE
Flow state filter does not filter for `Subflow Runs`

### ISSUE THREAD

**Issue by bennnym** [PrefectHQ/prefect#7795]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When I filter for specific states - the UI does not filter.

### Reproduction

***Before Filtering***
<img width="985" alt="Screen Shot 2022-12-07 at 2 23 23 pm" src="https://user-images.githubusercontent.com/46942903/206080563-07591c97-aa52-4efd-abca-4d641a1bd502.png">

**After Filtering***
<img width="1063" alt="Screen Shot 2022-12-07 at 2 23 30 pm" src="https://user-images.githubusercontent.com/46942903/206080592-32705954-ddcd-4d75-a47f-1090718e5463.png">

### Error

n/a

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment]
Thanks for flagging @bennnym
