### ISSUE TITLE
Having PREFECT_API_KEY as env var prevent from login to cloud

### ISSUE THREAD

**Issue by Andarius** [PrefectHQ/prefect#7797]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When having `PREFECT_API_KEY` set as an environment variable, the `prefect cloud login` command will exit with `This profile is already authenticated with that key.` without being actually logged in.

### Reproduction

```python3
PREFECT_API_KEY=foo prefect cloud login -k foo
```

### Error

```python3
We are not actually logged in.
```

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.10.5
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.38.5
```

**Comment by bunchesofdonald** [comment]
Thanks for the bug report @Andarius!

**Comment by madkinsz** [comment]
We've already got a utility to check if the key actually works so this should be a quick fix.

**Comment by ahadmushir** [comment]
Hello @madkinsz and @bunchesofdonald,
I would like to look into this issue if it's not being worked on!

**Comment by madkinsz** [comment]
Great! Let us know if you have any questions :)

**Comment by sonikagoyal84** [comment]
RUN prefect profile use default
RUN prefect cloud login -k abc --workspace cdf

**Comment by VeraZab** [comment]
ay, I thought just giving the key a different name could be a temporary fix, but it turns out this environment variable (with this exact name) has to be set, if not I'm getting errors like: `RuntimeError: Cannot create flow run. Failed to reach API` and so no flows can run
