### ISSUE TITLE
Investigate Prefect 2 Agent Memory Consumption 

### ISSUE THREAD

**Issue by masonmenges** [PrefectHQ/prefect#7805]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The Agent memory requirements for running flows in prefect 2 seem significantly larger than in prefect 1. 

Example User Scenario:
Prefect 1 Agent Configuration on ECS Fargate:
 -- 512 CPU
 -- 256 Memory

Prefect 2 Agent Configuration on ECS Fargate:
 -- 2048 CPU
 -- 16384 Memory
 -- "PREFECT_AGENT_PREFETCH_SECONDS": "120",
 -- "PREFECT_AGENT_QUERY_INTERVAL": "10"
 -Additional Configurations on Workqueue
 -- Concurrency limit 15

Several Flows exist across multiple repositories, When using the ECSRun config in prefect 1 the flows are all able to complete successfully with the Prefect 1 Agent Configuration. When Migrating the Flows to Prefect 2 using the ECStask block from prefect-aws the Agent Needs to be configured with the Prefect 2 Agent configuration in order to run the equivalent flows in Prefect 2. Not doing so results in several flow runs getting stuck in a pending state.

An example flow is included to trigger multiple deployments within the same time frame in Prefect 2, this flow will run successfully but at a certain point without the extra resources assigned on the prefect 2 agent the agent "crashes" and has to be restarted before the flows will continue.

### Reproduction

```python3
import time

from prefect import flow, get_run_logger
from prefect.deployments import run_deployment


@flow
def test_flow_orchestrator():

    for num in range(0, 50):
        run_deployment(
            name="test-flow/default",
            flow_run_name=f"test_flow_{num}",
            timeout=0,
        )
        get_run_logger().info(f"Started deployment #{num}")
        time.sleep(25)


@flow
def test_flow():
    get_run_logger().info("I am going to sleep for 1200 seconds")
    time.sleep(1200)
    get_run_logger().info("I am awaking from my 1200 second sleep")
```

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.10.8
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             darwin/x86_64
Profile:             staging
Server type:         cloud
```

**Comment by madkinsz** [comment]
@masonmenges When I talked to Ben memory utilization was only at 3% — we'll need a graph of memory utilization with demonstration of peak usage and corresponding counts of flow runs in progress to figure out what the issue is here.

**Comment by kevingrismore** [comment]
Here's a couple of flows that demonstrate the issue, assuming they're both deployed:

```python
import random
import time

from prefect import flow, get_run_logger, task, unmapped
from prefect.deployments import run_deployment


@task
def run_task(word: str, replica: int):
    logger = get_run_logger()
    logger.info(f"Running subflow for {word} on replica {replica}")


@flow(name="ecs-memleak-child")
def child(word):
    get_run_logger().info("Mapping some tasks!")
    return run_task.map(unmapped(word), [1])


@task
def run_subflow(word):
    logger = get_run_logger()
    time.sleep(random.uniform(0, 60))
    logger.info(f"Starting subflow")
    run_deployment(
        name="ecs-memleak-child/memleak-child",
        parameters={"word": word},
        poll_interval=30,
    )


@flow(name="ecs-memleak-parent")
def parent():
    words = [f"string_{i}" for i in range(100)]
    run_subflow.map(words)
```

This is just a quick way to run 100 subflows that each start a deployment after a few seconds of waiting. An ECS worker running as an ECS service with 1GB of memory OOMs sometime during the startup of those child deployments.
