### ISSUE TITLE
Allow sending a notification when a work queue is marked as unhealthy

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7811]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The Work queue health page is a great tool for troubleshooting (e.g. to validate that a work queue is unhealthy if you already suspect that) but it's **not actionable** in practice. Users request a feature to **get an alert** when a work queue becomes unhealthy as soon as this happens. 

This seems very doable given this endpoint already exists and the UI already has a page for each work queue to which the notification can be easily configured from the UI using the notifications block. 

The entire use case/problem is: instead of only displaying the information that a work queue is unhealthy, make it possible to send a notification when this happens. 

### Describe the proposed behavior

Add an option to the Work Queue Health page to 

![image](https://user-images.githubusercontent.com/86264395/206331574-36922599-d12b-4497-8bdd-0e1fa6a61e0e.png)

### Example Use

requested during LiveEO session

### Additional context

Automations will allow that functionality as well

![image](https://user-images.githubusercontent.com/86264395/206332673-dffd96b0-8e18-45fa-bdec-752c19ba3aec.png)

**Comment by madkinsz** [comment]
I think this will be doable after some changes to the work queue design that is planned for the next few months.
