### ISSUE TITLE
Celery/Dramatiq Integration for task runner

### ISSUE THREAD

**Issue by FluffyDietEngine** [PrefectHQ/prefect#7813]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently we have DaskRunner and RayRunners along with the queue and agent features at Prefect. In our recent interaction with Prefect Engineers, the tasks when throttles in higher number, the probability of crashing is higher and we are facing it in our development also. 

### Describe the proposed behavior

Celery/Dramatiq, which is a stable framework in managing the distributed tasks in higher volume can be extended as task runners can be a stable solution along with the prefect native queue/agent system. 

### Example Use

![Celery_dramatiq integration proposal drawio](https://user-images.githubusercontent.com/91061721/206350920-db2c25f3-bd1f-4964-99a0-a98f317d77ba.png)

### Additional context

I understand the complication of managing the task feedback from celery workers back into prefect layer, as it is complete asynchronous behaviour. But connecting to the backend of celery (task queue) can help big time here.

**Comment by madkinsz** [comment]
It seems like you could implement this in a collection and just conform to our `TaskRunner` interface. I don't think this belongs in the core library though.

**Comment by FluffyDietEngine** [comment]
Is there an update here?

**Comment by ritiek** [comment]
has anyone been able to integrate celery as a task runner for prefect?
