### ISSUE TITLE
Get flow's logs using command line

### ISSUE THREAD

**Issue by MaheshSankaran** [PrefectHQ/prefect#7814]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Based on the below conversation,
https://prefect-community.slack.com/archives/CL09KU1K7/p1670480537109379

It would be good if we get flow logs with command line

### Describe the proposed behavior

 In prefect1 we can use the `prefect get` command to get logs. expecting similar feature in prefect2 as well.

**Comment by ohadch** [comment]
Hey everyone, it is my first time contributing here :) I hope I'm following the rules. I can't neither assign myself nor edit the issue tags, so here is my PR: #7982 

I tried to follow the contribution guidelines as much as I could. Please let me know if I had to do something differently.

**Comment by serinamarie** [comment]
Hi @ohadch, thanks so much for contributing to Prefect! When reading the logs we would want to handle paginated queries as well, something like 

```python
offset = 0
more_logs = True
all_logs = []

while more_logs:

    logs = await client.read_logs(
        log_filter=log_filter, offset=offset
        )
    if len(logs) > 0:
        all_logs.extend(logs)
        offset += 200
    else:
        more_logs = False
```
