### ISSUE TITLE
K8s: Flow run infrastructure exited with non-zero status code -1.

### ISSUE THREAD

**Issue by vdytyniak-exos** [PrefectHQ/prefect#7854]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We use KubernetesJob infra block to execute flow runs, but we spin up new nodes on demand. It leads to `Crashed` flow run after upgrade to 2.7.0.

As I understand Prefect agent interprets 'Pod never started' error from k8s as crashed infrastructure, but actually scheduler requested new node and pod is in `Pending` status.

### Reproduction

```python3
-
```

### Error

```python3
10:08:00.674 | INFO    | prefect.infrastructure.kubernetes-job - Job 'omega353-durenia-terminus-h6vs6': Pod has status 'Pending'.                                                            │
10:08:00.684 | INFO    | prefect.agent - Completed submission of flow run '043d249c-4db1-4e74-af7e-1c7f77ea8902'                                                                             │
10:09:00.669 | ERROR   | prefect.infrastructure.kubernetes-job - Job 'omega353-durenia-terminus-h6vs6': Pod never started.                                                                   │
10:09:00.773 | INFO    | prefect.agent - Reported flow run '043d249c-4db1-4e74-af7e-1c7f77ea8902' as crashed: Flow run infrastructure exited with non-zero status code -1.
```

### Versions

```Text
2.7.0,2.7.1
```

**Comment by vdytyniak-exos** [comment]
I tested with 2.7.1, still fails. What can I provide additionally to help?

**Comment by madkinsz** [comment]
Can you share your Kubernetes client version from `pip freeze | grep kubernetes` and your cluster version with `kubectl version`?

@zzstoatzz is it possible that `None` is being treated as an immediate timeout?

**Comment by vdytyniak-exos** [comment]
@madkinsz Your comment helped me to understand the reason. Last release updated client code, so I had to redeploy the flow and it worked. Thanks, closing the issue.

**Comment by zzstoatzz** [comment]
> Can you share your Kubernetes client version from `pip freeze | grep kubernetes` and your cluster version with `kubectl version`?
> 
> @zzstoatzz is it possible that `None` is being treated as an immediate timeout?

I don't think `None` would mean immediate timeout, I'm pretty sure (since watch stream calls `list_namespaced_job` like  [this](https://github.com/kubernetes-client/python/blob/master/kubernetes/base/watch/watch.py#L163), where [it checks](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api/batch_v1_api.py#L1698) whether to pass along a timeout) that it means the timeout is not enforced.

**Comment by lucienfregosibodyguard** [comment]
Hi I have the same issue with prefect 2.7.6, could you help me ?

**Comment by madkinsz** [comment]
Hi @lucienfregosibodyguard — you will need to provide more details. See related issues at #8050 and #7743.
