### ISSUE TITLE
Scheduled runs won't show when filtering on a single day

### ISSUE THREAD

**Issue by yuvital-render** [PrefectHQ/prefect#7917]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi (-:

In Prefect Cloud, when filtering on a single day, scheduled runs won't show:

![CleanShot 2022-12-16 at 13 56 49@2x](https://user-images.githubusercontent.com/89977727/208093349-4f80aa83-0558-49cb-a01d-18de13a854d9.jpg)

But when you filter on more than a day it shows:

![CleanShot 2022-12-16 at 13 59 12@2x](https://user-images.githubusercontent.com/89977727/208093644-133fcac1-175a-4498-85ed-7635d0e0ef0d.jpg)

### Reproduction

```python3
Just filter on a single day.
```

### Versions

```Text
Prefect Cloud
```

**Comment by jars** [comment]
From our experience, this issue impacts All run states, and not just Scheduled. It's clear why it happens by observing the URL. Setting the same start and end date in the datepicker searches for Flow Runs with no range.

![image](https://github.com/PrefectHQ/prefect/assets/757192/08930a7a-f02d-4f3c-bf38-9d022a9c15ac)

As a user,  I would expect setting start and end dates to the same date to return all Flow runs from `YYYY:MM:DDT00:00:00` to `YYYY:MM:DDT23:59:59`

The chart also has a `.999` artifact in this case.

**Comment by ghomem** [comment]
This happens on the Prefect cloud account of a project that I am involved with. Not only we can't filter for a single day but also the date format in the date selector is something I never saw before (MM:DD:YYYY) and inconsistent with the format used elsewhere.
![error-filter-for-one-day](https://github.com/PrefectHQ/prefect/assets/3352900/607c1880-d54b-4888-a034-d48029effccd)
![error-dates-inconsistencies](https://github.com/PrefectHQ/prefect/assets/3352900/073e32b0-3f78-4bb2-bb32-7f70e70e12cf)
