### ISSUE TITLE
Orion server ignores SIGTERM termination signal from docker/k8s

### ISSUE THREAD

**Issue by ddelange** [PrefectHQ/prefect#7938]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A running orion process in docker/k8s does not respect SIGTERM

### Reproduction

- start a single-pod Deployment in k8s with command `["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "INFO", "--port", "4200"]`
- pod goes in state Running
- pod starts logging heartbeats (INFO)
- scale Deployment to 0
- pod goes in state Terminating (k8s sends SIGTERM)
- pod keeps logging heartbeats like nothing happened
- k8s kills the pod after `terminationGracePeriodSeconds: 60`

### Error

```python3
# delete k8s Pod, logs continue like normal
12:57:00.421 | INFO | prefect.orion.services.recentdeploymentsscheduler - Scheduled 0 runs.
12:57:00.422 | INFO | prefect.orion.services.marklateruns - Finished monitoring for late runs.
12:57:05.422 | INFO | prefect.orion.services.recentdeploymentsscheduler - Scheduled 0 runs.
12:57:05.422 | INFO | prefect.orion.services.marklateruns - Finished monitoring for late runs.
12:57:10.422 | INFO | prefect.orion.services.recentdeploymentsscheduler - Scheduled 0 runs.
12:57:10.422 | INFO | prefect.orion.services.marklateruns - Finished monitoring for late runs.
12:57:15.359 | INFO | prefect.orion.services.scheduler - Scheduled 0 runs.
...
# log stream disconnects
```

### Versions

```Text
Version:             2.7.3
API version:         0.8.4
Python version:      3.11.1
Git commit:          26c145b3
Built:               Fri, Dec 16, 2022 12:08 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

### Additional context

```
docker pull prefecthq/prefect:2.7.3-python3.11
```

**Comment by madkinsz** [comment]
Hm we convert SIGINT to SIGTERM at https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/orion.py#L148, perhaps this as simple as adding SIGTERM forwarding to the subprocess.

**Comment by ddelange** [comment]
similar for agent: https://github.com/PrefectHQ/prefect/issues/7938
