### ISSUE TITLE
prefect deployment execute giving no such command found

### ISSUE THREAD

**Issue by devanshdoshi9** [PrefectHQ/prefect#7939]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Tried executing:
`prefect deployment execute <flow-name/deployment-name>`
but it is giving the following error: 
`No such command 'execute'.`

`prefect deployment --help` also doesn't list `execute` in the list of commands
If execute is no longer being used then it should be removed from the below docs as well:
[https://docs.prefect.io/concepts/deployments/](https://docs.prefect.io/concepts/deployments/)

### Reproduction

```python3
prefect deployment execute <flow-name/deployment-name>
```

### Error

```python3
No such command 'execute'.
```

### Versions

```Text
Version:             2.7.3
API version:         0.8.4
Python version:      3.9.4
Git commit:          26c145b3
Built:               Fri, Dec 16, 2022 12:08 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         hosted
```

**Comment by madkinsz** [comment]
Thanks for the report! I think we removed this command during beta, we'll probably want to remove it from the docs.

**Comment by devanshdoshi9** [comment]
Let me raise a PR addressing this.
