### ISSUE TITLE
Orion UI Nested blocks Array Field not interpreted correctly.

### ISSUE THREAD

**Issue by coolbreeze2** [PrefectHQ/prefect#7950]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Orion UI Nested blocks Array Field not interpreted correctly.
```python
class Foo(Block):
    name = str


class FooList(Block):
    foos: List[Foo]
```

### Reproduction

1. create `my_block.py`
```python
class Foo(Block):
    name = str


class FooList(Block):
    foos: List[Foo]
```
   
2. prefect block register --file my_block.py
3. open Orion UI
4. add new blocks

### Error

Orion UI Nested blocks Array Field not interpreted correctly.
![1](https://user-images.githubusercontent.com/43947544/208624793-a2c7857f-af4e-43a9-b962-0c081eca96e0.png)

### Browers

- [X] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

### Prefect version

```Text
Version:             2.7.2
API version:         0.8.4
Python version:      3.8.15
Git commit:          5fb17cec
Built:               Thu, Dec 15, 2022 4:24 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

**Comment by zhen0** [comment]
Hi @coolbreeze2 - thanks for the ticket.  Can you give a bit more information about what you were expecting to see there?

Also, not sure if this is related to your issue (and I am a UI engineer so not making great claims to be an expert with pydatic) but do you need to update how you're setting foo's type:

```
from prefect.blocks.core import Block
from typing import List

class Foo(Block):
    name: str

class FooList(Block):
    foos: List[Foo]
    
```

**Comment by zhen0** [comment]
Another note - currently we don't have specific handling for a list of classes/objects. We'd currently expect this to be a json input as it gives flexibility for entries.

**Comment by Wingmore** [comment]
It seems lists in general are not interpreted correctly.

I cannot successfully run a list of integers as input without getting an error.

See https://discourse.prefect.io/t/flow-run-received-invalid-parameters-value-is-not-a-valid-list/2310/2

**Comment by coolbreeze2** [comment]
> Another note - currently we don't have specific handling for a list of classes/objects. We'd currently expect this to be a json input as it gives flexibility for entries.

Can we add specific handling for lists of classes/objects? Correct **view** and **add** on ui.

The information returned by the backend should be sufficient. We can get block_type_slug by  `Respons.fields.definitions.Foo.block_type_slug` and url `/api/block_types/slug/{slug}`.

URL: http:/127.0.0.1:4200/api/block_schemas/filter

request payload: 
```json
{
    "block_schemas": {
        "block_type_id": {
            "any_": [
                "8aa20844-c6bb-4ca8-aac8-c3ac0647e578"
            ]
        }
    }
}
```

response:

```json
[
    {
        "id": "01e11493-30a4-45b3-91e9-ea95e2bf3162",
        "created": "2023-02-21T09:32:48.366394+00:00",
        "updated": "2023-02-21T09:32:48.366415+00:00",
        "checksum": "sha256:38cb60fcd66131c06f8b4b92d4d5fb7b5e97ee5c83bfc6daac9358f8c2d5dd75",
        "fields": {
            "type": "object",
            "title": "FooList",
            "required": [
                "foos"
            ],
            "properties": {
                "foos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Foo"
                    },
                    "title": "Foos"
                }
            },
            "secret_fields": [],
            "block_type_slug": "foolist",
            "block_schema_references": {
                "foos": {
                    "block_schema_checksum": "sha256:365281119e2cda60672d3e4730f0f218dad85bc5350a4ca8987c7bbd419448f4",
                    "block_type_slug": "foo"
                }
            },
            "definitions": {
                "Foo": {
                    "type": "object",
                    "title": "Foo",
                    "required": [
                        "name"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "title": "Name"
                        }
                    },
                    "secret_fields": [],
                    "block_type_slug": "foo",
                    "block_schema_references": {}
                }
            }
        },
        "block_type_id": "8aa20844-c6bb-4ca8-aac8-c3ac0647e578",
        "block_type": {
            "id": "8aa20844-c6bb-4ca8-aac8-c3ac0647e578",
            "created": "2023-02-21T09:32:48.329794+00:00",
            "updated": "2023-02-21T09:32:48.329828+00:00",
            "name": "FooList",
            "slug": "foolist",
            "logo_url": null,
            "documentation_url": null,
            "description": null,
            "code_example": "```python\nfrom __prefect_loader__ import FooList\n\nfoolist_block = FooList.load(\"BLOCK_NAME\")\n```",
            "is_protected": false
        },
        "capabilities": [],
        "version": "non-versioned"
    }
]
```
