### ISSUE TITLE
Notifications for Failed / Crashed states are not triggering

### ISSUE THREAD

**Issue by kaliserichmond** [PrefectHQ/prefect#7964]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Create a notification for Failed state and run a flow run that fails. Notification does not trigger. Tested with slack webhook in Prefect Cloud. [Users are reporting for Failed and Crashed State and self-hosted. 
](https://prefect-community.slack.com/archives/CL09KU1K7/p1671602813111169)

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/91492272/209000631-70b4385e-5bd9-463c-98a0-7b3e61b59031.png">

### Reproduction

```python3
from prefect import flow

@flow()
def always_fails_flow():
    raise ValueError("This flow immediately fails")

if __name__ == "__main__":
    always_fails_flow()
```

### Versions

```Text
2.7.3
```

**Comment by madkinsz** [comment]
@kaliserichmond that thread is confusing to me, it looks like there's a report of missing notifications for self-hosted Prefect Server (v1) and separately a report for Prefect Cloud (v2)?

**Comment by neumann-nico** [comment]
@madkinsz Sorry for the confusion!

Yesterday the notifications somehow stopped working, but later it worked again.
I use prefect 2.6.9 and prefect cloud. 

I just tried it again and Slack notifications are working fine for me:

```
Prefect flow run notification
Flow run fail-flow/glossy-coot entered state Failed at 2022-12-22T09:10:50.174351+00:00.
```

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/33637944/209097974-e97ae958-6ac3-4b02-a6d2-a0bfe8456c56.png">

**Comment by peytonrunyan** [comment]
@kaliserichmond can you confirm that this is working for you too?

**Comment by madkinsz** [comment]
I believe this was confirmed to be working in an internal slack thread. Feel free to reopen if there are additional issues.

**Comment by ankit-cy** [comment]
Hi, I have configured hook in Notification section to send alerts for failures but not getting it. Is there anything else needed apart from configuring hook?
