### ISSUE TITLE
Add flow name to the email subject in the `PrefectCloudEmail` block

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7966]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

All email notifications currently have the same subject

![image](https://user-images.githubusercontent.com/86264395/209032599-e9d0ce7d-a19c-446b-9139-c03a18fcb65e.png)

### Describe the proposed behavior

Add a flow name to the subject to prevent all email notifications from landing in the same email thread

Request https://discourse.prefect.io/t/show-the-flow-name-in-the-email-subject-in-a-notification/2087 

it would be great to potentially template that (e.g. date, flow run tag) + allow more customization but adding the flow name would already solve the problem requested by the user

**Comment by serinamarie** [comment]
Hi @anna-geller, thanks for the issue. @WillRaphaelson Would you be able to take a look at this to decide on its status, and if accepted, its priority?

**Comment by WillRaphaelson** [comment]
Going to close this out as we support this in a more robust way via automations. Can reopen it if we reach a critical mass. thanks @serinamarie
