### ISSUE TITLE
Add GH Action to remove status labels when closed

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#7967]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

When issues are closed, the status label should be removed. No reason to leave "status:triage" on a closed issue.

### Impact

This will simplify counts of issues in various states and avoid misleading statuses on archived issues.

### Additional context

This will also put us in a good place to make other changes to issue labels with automations, e.g. we can remove `status:triage` when `status:accepted` is applied or add `status:in-progress` when someone is assigned / a pull request is opened.

**Comment by mohitsaxenaknoldus** [comment]
I am working on this, I'll raise a PR for this soon.

**Comment by mohitsaxenaknoldus** [comment]
@madkinsz PR: https://github.com/PrefectHQ/prefect/pull/7980
