### ISSUE TITLE
prefect kubernetes manifest agent limits to only one queue

### ISSUE THREAD

**Issue by scottwalshqs** [PrefectHQ/prefect#7992]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The `prefect kubernetes manifest agent` command seems to only take in one queue.  Although I can resolve this after the manifest is created, the manifest command should have the ability to take in multiple queues in the same way the `prefect agent start` command works.

### Reproduction

```python3
(scott/**) prefect kubernetes manifest agent -q test1 -q test2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: default
  labels:
    app: prefect-agent
spec:
  selector:
    matchLabels:
      app: prefect-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: agent
        image: prefecthq/prefect:2.6.7-python3.9
        command: ["prefect", "agent", "start", "-q", "test2"]
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PREFECT_API_URL
```

### Versions

```Text
2.6.7
```

**Comment by madkinsz** [comment]
Hi! Thanks for the issue. Note this is an enhancement request not a bug — we're working on a new experience for agents and queues so we're unlikely to accept changes to this interface but we'll try to address it in the new one!
