### ISSUE TITLE
Add --head option to the prefect flow-run logs CLI

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#7998]
Follow-up to https://github.com/PrefectHQ/prefect/pull/7982

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The CLI command: `prefect flow-run logs <flow_run_id>` shows all logs.

### Describe the proposed behavior

It would be great to add a `--head` option to show only the first N logs:

```bash
prefect flow-run logs <flow_run_id> [--head [numlines=50]]
```

**Comment by ohadch** [comment]
Hey @serinamarie and @madkinsz , although the priority is low, as I am already into this feature I'll try to take the linked issues that @serinamarie opened one by one. I still can't assign myself, can either of you assign me to this one first?

**Comment by madkinsz** [comment]
Thanks!
