### ISSUE TITLE
Add --tail option to the prefect flow-run logs CLI

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#7999]
Follow-up to https://github.com/PrefectHQ/prefect/pull/7982

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The CLI command: `prefect flow-run logs <flow_run_id>` shows all logs.

### Describe the proposed behavior

It would be great to add a `--tail` option to show only the last N logs:

```bash
prefect flow-run logs <flow_run_id> [--tail [numlines=50]]
```

**Comment by Gairick52** [comment]
@serinamarie Hello mam ,can you please assign this issue to me,i would like to work on this

**Comment by serinamarie** [comment]
Hi @Gairick52, that sounds great, thanks!

**Comment by SlackJordan** [comment]
Does this issue still need to be worked on?

**Comment by serinamarie** [comment]
Hi, @SlackJordan, it does 🙂

**Comment by Shubhamparashar** [comment]
Has this issue been resolved and if not I would like to work on this

**Comment by serinamarie** [comment]
@Shubhamparashar I don't believe anyone has picked up this issue. It hasn't been assigned to anyone.

**Comment by Shubhamparashar** [comment]
@serinamarie please assign this issue to me, I would like to work on this

**Comment by Shubhamparashar** [comment]
@serinamarie here is the PR link https://github.com/PrefectHQ/prefect/pull/9028
