### ISSUE TITLE
Add --reverse option to the prefect flow-run logs CLI

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#8000]
Follow-up to https://github.com/PrefectHQ/prefect/pull/7982

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The CLI command: `prefect flow-run logs <flow_run_id>` shows all logs in chronological order.

### Describe the proposed behavior

It would be great to add a `--reverse` option to show logs in reverse chronological order (print most recent log first). 

```bash
prefect flow-run logs <flow_run_id> [--reverse]
```

**Comment by madkinsz** [comment]
@bakhtiarcr7 Yeah this one still needs a contribution! You'll need to add a flag to the CLI command then pass the correct sorting option during the log read request.
