### ISSUE TITLE
Potential bug - Deployment filter is not working in Prefect cloud dashboard

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8005]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi (-:
Suddenly the deployment filter stopped working. Please look at the GIF here:
https://discourse.prefect.io/t/potential-bug-deployment-filter-is-not-working-in-prefect-cloud-dashboard/2109
Maybe due to a high number of deployments?

### Reproduction

https://global.discourse-cdn.com/business7/uploads/prefecthq/original/2X/3/37e929f26ba5d8b175800707dc8b19da52a45dff.gif

### Versions

```Text
Prefect Cloud
```

**Comment by zhen0** [comment]
Hi @yaronlevi - this is interesting as I can't reproduce the issue you mention but I can see it clearly in your GIF.  Are you still seeing this issue?  Can you let me know how many deployments you have so I can see if that might be related. Thank you!
