### ISSUE TITLE
Block names saved with underscore results in a cryptic exception

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#8036]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`credentials.save(name='first_aws_creds', overwrite=True)`

results in

```
  raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 
'[https://api.prefect.cloud/api/accounts/../](https://api.prefect.cloud/api/)
```

Originally from https://prefect-community.slack.com/archives/CM28LL405/p1672756772034579?thread_ts=1672663639.940449&cid=CM28LL405

### Reproduction

```python3
from prefect_aws.credentials import AwsCredentials
credentials = AwsCredentials(
        aws_access_key_id="acccess_key_id",
        aws_secret_access_key="secret_access_key"
    )
credentials.save(name='first_aws_creds', overwrite=True)
```

### Error

```python3
raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 
'[https://api.prefect.cloud/api/accounts/../](https://api.prefect.cloud/api/)
```

### Versions

```Text
Version:             2.7.5+12.g2c04fe1ac.dirty
API version:         0.8.4
Python version:      3.9.15
Git commit:          2c04fe1a
Built:               Mon, Jan 2, 2023 11:02 PM
OS/Arch:             darwin/arm64
Profile:             integrations-cloud
Server type:         cloud
```

**Comment by madkinsz** [comment]
@ahuang11 can you fix the formatting?

Is this something you can triage?

**Comment by ahuang11** [comment]
Can you elaborate on what formatting?

Sure, I can take this on.
