### ISSUE TITLE
Migrate to SQLAlchemy 2.0

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#8052]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

Tracking issue for migrating to SQLAlchemy 2.0 [using the migration guide](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html). When migrating, the changes in #8042 can be removed.

**Comment by tadejsv** [comment]
Perhaps work on this can begin - SQLAlchemy 2.0 is already on rc2. I am using SQLAlchemy 2.0 in my application, and incompatibility of prefect with it means I have to use some hacks to install prefect - would be great if I prefect was compatible with SQLAlchemy 2.0

**Comment by madkinsz** [comment]
Contributions are welcome here, but I think each change should be scoped to a step of SQLAlchemy's migration guide so this isn't all done in one-shot.

**Comment by etsvetanov** [comment]
Has work began on this?

**Comment by madkinsz** [comment]
@etsvetanov not yet!

**Comment by blakete** [comment]
Would really like this migration to be made!

**Comment by ehutzle** [comment]
Using SQLAlchemy 2.0 for my codebase & ORM definitions, unfortunately can't run prefect flows with SQLAlchemy 2.0 installed.

Would be wonderful to be able to use SA2

**Comment by madkinsz** [comment]
Sorry to hear this is blocking some people — we're probably going to need to support both versions of SQLAlchemy for a bit which is going to be complicated as just "upgrading" will cause this same problem in reverse for SQLAlchemy 1.x users.

I think the best hope for separating the server dependencies (i.e. if you're using Cloud or self-hosting elsewhere) is drafted in https://github.com/PrefectHQ/prefect/pull/8849 but it's going to require more work to defer imports.

I'm happy to review contributions that make progress on the migration.

**Comment by Richard-Otterli** [comment]
Would also like to request the upgrade of Prefect 2.0 to use SQLAlchemy 2. Was looking forward to adopting Prefect, but it won't work with my current repository.

**Comment by madkinsz** [comment]
Please do not comment with upgrade requests. Feel free to 👍 the first comment if this would help you. I'd like to keep the discussion in the issue focused on implementation of these changes.

**Comment by michael-czyz** [comment]
#8849 is marked as closed, so I think this is the right issue for this.  

I would like to get 100% clarity on the scope of the issue as my team was planning to start porting an established analytics SaaS app from airflow to Prefect 2 and this appears to be blocking.

In production we intend to use Prefect cloud, though in development we are able to stand up a local server in a separate container to keep the server distinct from our app code.  

With either cloud or local server, we can successfully run a minimal flow with tasks from a simply python script.

However, we are unable to deploy any workers, as the `prefect deployment apply` command fails trying to use a SQLAlchemy 1.x `bind` argument, which 2.x doesn't have: `TypeError("MetaData.__init__() got an unexpected keyword argument 'bind'")`

We are also unable to run any pytest tests - with or without the `prefect_test_harness`.  We get the same error, and in these cases it looks like the error comes from trying to do Prefect alembic migrations to setup the temporary SQLite database.

So, is SQLAlchemy 1.x a base dependency for workers and using pytest, as well as for the local server?  Or are we (hopefully) missing something to allow Prefect testing and workers using our 2.x app codebase?

**Comment by madkinsz** [comment]
https://github.com/PrefectHQ/prefect/pull/8849 is the best path forward for your use-case. We'll need to update it to defer all imports of SQLAlchemy so they do not occur unless the server is used.

**Comment by michael-czyz** [comment]
understood, thanks.

**Comment by ddelange** [comment]
does the scope of this ticket include a migration from `psycopg2-binary` to `psycopg[binary]`? 

psycopg3 has [native asyncio support](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#what-s-new-in-psycopg-3) and [much less memory consumption](https://www.spherex.dev/psycopg-2-vs-psycopg3/) among many other improvements
