### ISSUE TITLE
Guard against foreign key issues in SQLite migrations

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#8060]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently we allow alembic to generate migrations the same way for SQLite and Postgres.
This causes issues with foreign key constraints described here that can result in data loss: https://alembic.sqlalchemy.org/en/latest/batch.html#dealing-with-referencing-foreign-keys

### Describe the proposed behavior

Automatically turn off foreign keys during SQLite migrations

**Comment by madkinsz** [comment]
It seems like we can just not issue this PRAGMA ON during connection when a migration is running? Or always issue the PRAGMA OFF during migrations?
