### ISSUE TITLE
Revisit functions for generating local task ids

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#807]
These functions are currently unused, but well tested. However, they predate task ids, so they may be unnecessary now.

**Comment by lauralorenz** [comment]
The current definition of the work to complete here is to
1. check if there are any unused functions for generating task ids
2. delete them and their tests entirely

If we are not using them now but need them later, we can pull them from the git history.

**Comment by cicdw** [comment]
Closed w/ the slugs refactor #2531
