### ISSUE TITLE
add vue-tsc validate:types

### ISSUE THREAD

**Issue by stackoverfloweth** [PrefectHQ/prefect#8070]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

like in nebula-ui, orion-ui should add vue-tsc as a dependency with a `validate:types: "vue-tsc --noEmit"` script in package.json along with a pull request check of types

**Comment by pleek91** [comment]
This was added as part of https://github.com/PrefectHQ/prefect/pull/8955
