### ISSUE TITLE
2.7.6 - Only two blocks available and not able to create notification

### ISSUE THREAD

**Issue by zelterNN** [PrefectHQ/prefect#8079]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

![image](https://user-images.githubusercontent.com/110698373/210896463-40071b64-224c-4105-9426-7cec767c5419.png)
Only two blocks available in Blocks tab

![image](https://user-images.githubusercontent.com/110698373/210896450-5e59157f-139e-4461-9882-2505fca56893.png)
Notification doesn't have available apps to select

### Reproduction

Simply click on accroding tabs

### Error

Not applicable

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.7.6
API version:         0.8.4
Python version:      3.11.1
Git commit:          528c8300
Built:               Wed, Jan 4, 2023 5:27 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         hosted
```

**Comment by konwiddak** [comment]
I have the same problem which appeared with prefect 2.8.2 - just installed, no configuration done yet and these are the only blocks available.

**Comment by konwiddak** [comment]
There are blocks here that can be registered via command line:
env\Lib\site-packages\prefect\blocks

To register:
prefect block register --module prefect.blocks.system

For some reason these aren't being registered on install.

**Comment by rpeden** [comment]
Do the blocks appear if you follow the steps in [this message](https://github.com/PrefectHQ/prefect/issues/8118#issuecomment-1377235878)?

**Comment by desertaxle** [comment]
@konwiddak Prefect currently stores a hash of installed blocks in a file named `memo_store.toml` in the PREFECT_HOME directory. If you delete that file then it will cause block auto-registration to run the next time the server starts up. We are looking to move the memo store out of that file and into the database to better manage block auto-registration. You can follow this issue for updates: https://github.com/PrefectHQ/prefect/issues/8157
