### ISSUE TITLE
Time can't be adjusted inside schedule dialog

### ISSUE THREAD

**Issue by tibuch** [PrefectHQ/prefect#8081]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When configuring a schedule for a deployment it is not possible to change the time. One can only choose the time-zone and it sets the time to the current time.

### Reproduction

Edit a deployment in the UI and add/edit a schedule. Try to change the schedule time.

### Error

![Screenshot from 2023-01-06 15-30-29](https://user-images.githubusercontent.com/5450869/211034057-b7dcf074-c66f-41e4-a893-7e94706501cf.png)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment]
The time display is potentially confusing as it's not a selector but an indicator of time in that timezone. Time can be selected from the date picker.  We'll make some changes to update the UX here.

**Comment by zhen0** [comment]
Thanks for flagging @Phrytes - I think that's a separate bug. I've written it up here:  https://github.com/PrefectHQ/prefect/issues/8294. Feel free to add to it.
