### ISSUE TITLE
Submitting task with `asyncio.sleep` consumes 100% of CPU

### ISSUE THREAD

**Issue by tadejsv** [PrefectHQ/prefect#8115]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A simple async task that only uses `asyncio.sleep` consumes 100% of CPU if I run it with `.submit()`

### Reproduction

```python3
import asyncio
import prefect


@prefect.task
async def sleepy():
    while True:
        print("Hi")
        await asyncio.sleep(10)


@prefect.flow
async def sleepy_flow():
    await sleepy.submit()

asyncio.run(sleepy_flow())
```

### Versions

```Text
Version:             2.7.7
API version:         0.8.4
Python version:      3.11.0
Git commit:          e8ca30b8
Built:               Fri, Jan 6, 2023 4:25 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```
```


### Additional context

_No response_

**Comment by madkinsz** [comment]
This is pretty weird — you're right that it must be an issue with the task runner. Probably how it is waiting for the task result. I hope this will be resolved by https://github.com/PrefectHQ/prefect/pull/8014. I'll report back here when it is.

**Comment by madkinsz** [comment]
This looks resolved now
