### ISSUE TITLE
Cannot create new blocks due to missing block types

### ISSUE THREAD

**Issue by kajen3** [PrefectHQ/prefect#8118]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I cannot create a new block type since UI (`http://127.0.0.1:4200/blocks/catalog`) and CLI (`prefect block type ls`) are empty. However after creating a deployment via `prefect deployment build log_flow:log_flow -n log_flow2 -q test --infra docker-container --apply` Icons and CLI for docker are available.
<img width="1728" alt="Screenshot 2023-01-09 at 20 52 30" src="https://user-images.githubusercontent.com/82041909/211396241-06446e42-9e82-4513-bb5b-249103dac4c4.png">
<img width="1038" alt="Screenshot 2023-01-09 at 20 55 20" src="https://user-images.githubusercontent.com/82041909/211396251-694f3279-4398-4ae6-8798-876cc4b2cbc4.png">
<img width="922" alt="Screenshot 2023-01-09 at 21 14 36" src="https://user-images.githubusercontent.com/82041909/211399525-18b95dc8-e2c5-40e5-95ed-fdcd93d786ab.png">
<img width="1724" alt="Screenshot 2023-01-09 at 21 14 09" src="https://user-images.githubusercontent.com/82041909/211399545-bbe17390-86eb-4ec5-8df9-e045ac2ed252.png">

### Reproduction

```python3
`prefect block type ls`
```

### Versions

```Text
Version:             2.7.6
API version:         0.8.4
Python version:      3.9.15
Git commit:          528c8300
Built:               Wed, Jan 4, 2023 5:27 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted
```

**Comment by zhen0** [comment]
Looks similar to https://github.com/PrefectHQ/prefect/issues/8079?  @anticorrelator - might be useful as you look into that?

**Comment by madkinsz** [comment]
Thanks for the report!

@desertaxle I want to make sure this is on your radar as well.

**Comment by kajen3** [comment]
@desertaxle 

>     1. What type of database are you using for your Orion server?
I've not configured a database. I think then it is the `orion.db`, from `~/.prefect/` right?
>     2. Did you see block types previously and they disappeared, or have you never seen block types for this Orion instance? 
Yes, I saw them before.
>     3. Have you ever reset the database for this Orion instance?
Yes.

**Comment by desertaxle** [comment]
This is most likely because we try to avoid running auto-registration of blocks unless the set of blocks that need to be registered has changed. In your case, you can trigger block auto-registration by deleting `~/.prefect/memo_store.toml` and then running `prefect block types ls`.

We may want to explore moving storage of the block auto-registration memo key into the DB to prevent this unexpected behavior for users. I can look into that.

**Comment by kajen3** [comment]
@desertaxle Thanks. That solved the problem. Should I close?

**Comment by madkinsz** [comment]
Thanks!

**Comment by Konzisam** [comment]
Lets say you want to register prefect_gcp block: 
With the Prefect Orion up & running, execute the following:

```
prefect orion database reset 
prefect block register -m prefect_gcp
```
With this method you loose all blocks that were registered before.
