### ISSUE TITLE
Prefect Agent CLI: --api flag is not working

### ISSUE THREAD

**Issue by MrSyee** [PrefectHQ/prefect#8123]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have two machine(Ubuntu Desktop and M1 Mac book). I ran server on Ubuntu Desktop and agent on M1 Mac book. When run server, `PREFECT_API_URL` is set `0.0.0.0` and create a queue named "test".
I want the agent to pool at the queue in Ubuntu Server (e.g. IP: 192.168.0.10)
According to [Prefect Agent Docs](https://docs.prefect.io/concepts/work-queues/#agent-overview), Agent run command is `prefect agent start -q test --api 192.168.0.10:4200/api`.

But `--api` flag is not working. To be exact, the log shows the changed URL, but it does not actually connect to the queue.
When I checked the code, it seems that it is simply console logging. (Reference [Prefect CLI agent Github](https://github.com/PrefectHQ/prefect/blob/94983c4339c5d93823bf31cc1178a0ee588fc5c5/src/prefect/cli/agent.py#L135-L143))

I figured out to change PREFECT_API_URL in prefect config but I think the document or code needs to be modified.

### Reproduction

```python3
# Server
prefect orion start --host "0.0.0.0"
prefect work-queue create test

# Agent (the other machine such as docker container)
prefect agent start -q test --api "http://0.0.0.0:4200/api"
```
```


### Error

```python3
Starting v2.7.1 agent connected to http://0.0.0.0:4200/api...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from queue(s): test...
06:26:08.341 | INFO    | prefect.agent - Created work queue 'test'.
```
But status of work queue is unhealthy (not connected).
![image](https://user-images.githubusercontent.com/17582508/211477993-a71f4fef-1e3a-434f-acae-1b54dacc8a2d.png)
```


### Versions

```Text
Version:             2.7.1
API version:         0.8.3
Python version:      3.9.15
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

**Comment by madkinsz** [comment]
Thanks for the report!

**Comment by serinamarie** [comment]
I'm going to close this as completed. Feel free to open a new issue if that is not the case for you.
