### ISSUE TITLE
Enhancement - Add string search inside run logs in Prefect Cloud UI

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8150]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This is a weird one.
I have this run finished and I hit Command+F to search for something in the logs. Searching for "daily_steps":

![CleanShot 2023-01-11 at 22 36 06@2x](https://user-images.githubusercontent.com/5398977/211912412-0ab98c8d-96fc-414a-914b-210e97ee2dbc.jpg)

As you can see it found 6 results.
But if I scroll further and then hit "enter" again to search, it finds another 5 results which are different from the previous one:

![CleanShot 2023-01-11 at 22 37 57@2x](https://user-images.githubusercontent.com/5398977/211912790-17e06f6f-3ad7-42d9-bdbf-91b041948f58.jpg)

So currently there is no clear way of searching the entire log reliably.
Is it a Chrome bug?
Maybe we should add a dedicated search box?
I would prefer a that the native Command+F will work...

Thanks!  🙏

### Reproduction

```python3
Run a job and look inside the logs with a Command+F from the browser.
```

### Versions

```Text
cloud prefect ui
```

**Comment by voidel** [comment]
Pretty sure this is because the logs are streamed/dynamically loaded as you scroll through them, the entire logs are not loaded in the page DOM from the start. It's not a browser issue, more just how the front end has been designed to be performant.

Perhaps something similar could be done as per the Prefect 1 logs UI that had a searchbox that did actually query the whole log once you hit enter?

**Comment by yaronlevi** [comment]
@voidel Yes, I agree, a dedicated search box would be great...

**Comment by zhen0** [comment]
@yaronlevi - would you mind adding a new issue or updating this one to reflect that it's a feature enhancement request for searching in logs?

**Comment by yaronlevi** [comment]
@zhen0 What should I do in order to turn this issue into a "feature enhancement request"?

**Comment by zhen0** [comment]
Thanks @yaronlevi - I updated the title and removed the bug label for now.

**Comment by yaronlevi** [comment]
Any updates on this issue?
