### ISSUE TITLE
Add a way to rename existing flows/deployments

### ISSUE THREAD

**Issue by taljaards** [PrefectHQ/prefect#8154]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There is no way to rename flows/deployments already "registered" to Prefect Cloud (or I guess, Orion as well, without changing it in the database).
Currently, you can change the names inside your flow definition and re-run/re-deploy, but that will "register" a brand-new flow+deployment, with a separate run history.

### Describe the proposed behavior

It would be useful to have a mechanism to rename existing flows/deployments. Sometimes you need to rename a flow/deployment, e.g. a naming convention change, **and not lose flow run history**.
Currently, the only way is to register a new flow. If you need run history, you will have to keep both flow versions, cluttering the UI and creating points of confusion.

Alternatively, it could be useful to transfer flow run history from one flow/deployment to another.

### Example Use

At first, I planned to use this API endpoint. I assumed it would do what I required, but it seems it only updates tags on a flow (which seems a slightly unintuitive, but that is beside the point).
![image](https://user-images.githubusercontent.com/6089256/212134026-b245bef0-a150-4f2e-a927-b79b749b3985.png)

Of course, this will also require some paying attention on the user's end - they have to rename the flow in the backend, and then make sure when they run/deploy it again, that this new run/deploy uses the new name, otherwise they will end up with two versions anyway.

**Comment by madkinsz** [comment]
Thanks for the issue! We'll need to have some discussion about the how this should work. The PATCH route for flows could probably be updated to support changing the name, we just have not added support for updating fields that we have not had an explicit need for in a feature.

**Comment by AleksandrLiadov** [comment]
Hello @madkinsz, thanks for your work, we also need this feature.
