### ISSUE TITLE
Specify schema for Prefect Postgres database

### ISSUE THREAD

**Issue by solumnsilence** [PrefectHQ/prefect#8170]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When I want to save Prefect data to [external Postgres database](https://docs.prefect.io/concepts/database/#configuring-a-postgresql-database), it will be saved to default "public" schema.

### Describe the proposed behavior

I would like to save this data in different schema because I have my own tables in "public" schema and I want to split them with Prefect data. So the idea is to set schema for Postgres database.

### Example Use

After setting Postgres url like:
`prefect config set PREFECT_ORION_DATABASE_CONNECTION_URL="postgresql+asyncpg://postgres:yourTopSecretPassword@localhost:5432/orion?currentSchema=my_own_schema"`
prefect will save data to specified schema.

### Additional context

I found this discussion https://github.com/PrefectHQ/prefect/discussions/4583, but no one fixed it.

**Comment by mister-fahrenheit** [comment]
This might be helpful: https://stackoverflow.com/questions/73068830/alembic-postgres-how-to-switch-to-another-schema

**Comment by im-max** [comment]
@madkinsz hey! 
Thanks for your answer 😄 

We could use separate db for perfect, but it would be really more convenient to keep all the data in the same place. If it is hard to implement and support, we will use separate db.
