### ISSUE TITLE
Flow run timeline view formatting bug

### ISSUE THREAD

**Issue by Ewande** [PrefectHQ/prefect#8172]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The gap between the timeline view and the bottom content (logs/task runs) changes when I switch between tabs

### Reproduction

Go to the flow run view of a completed run and switch between tabs (e.g. Logs > Task Runs > Logs)

### Error

Logs (correct):
![image](https://user-images.githubusercontent.com/4641333/212397170-c07264b6-3582-4283-ae64-50d7887a1e88.png)

Task runs (incorrect):
![image](https://user-images.githubusercontent.com/4641333/212397188-6d7f9bee-6822-49bf-bf96-cd3361d03356.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.7.8, self-hosted on EKS
```

**Comment by zhen0** [comment]
Thanks @Ewande 

@brandonreid - would you be able to look into this one as part of your ongoing timeline work?

**Comment by Ewande** [comment]
I don't seem to experience this bug anymore as of 2.7.12. Was it fixed? 🙂

**Comment by Ewande** [comment]
Closing as I don't see the bug anymore
