### ISSUE TITLE
Pending flow run (5 min) delay on local storage

### ISSUE THREAD

**Issue by richard-alexander** [PrefectHQ/prefect#8178]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I asked this question previously I haven't been able to solve it yet:  https://app.slack.com/client/TL09B008Y/C03D12VV4NN/thread/C03D12VV4NN-1671463734.213749

In short, every one of my flows is delayed by at least 5 minutes.

- The flow is stored on the local file system (local storage)
- The flow is deployed to a work queue with a concurrency limit of 3
- The flow is submitted by calling `run_deployment` with `timeout=0`
- The flow enters a `pending` state very quickly
- The log populates `Downloading flow code from storage at '/path/to/my/code'`  within 1s
- The flow stays in a pending state for at least 5 minutes before entering a `running` state

### Reproduction

```python3
# Set up a work queue with concurrency limit of 3
# Deploy a flow to local storage

# Start flow by calling `run_deployment` with `timeout=0`
run_deployment(
        name="dev/test_flow", 
        parameters=dict(param1=param1, param2=param2),
        timeout=0,  # Schedule the flow and return immediately
)
```

### Error

```python3
No error is thrown.

The flow is submitted, but stays in a `pending` state for 5 minutes before running.
```

### Versions

```Text
Version:             2.7.8
API version:         0.8.4
Python version:      3.10.4
Git commit:          75d2e146
Built:               Thu, Jan 12, 2023 1:41 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

### Additional context

The VERY first thing that the script does is to print the parameters to the prefect log. That log entry is always delayed for at least 5 minutes. Even though I see the initial log entry "Downloading flow code from storage at '/path/to/my/code'" immediately, the flow's start time also always displays as late:

![image](https://user-images.githubusercontent.com/25615654/212721254-7ffea869-41d7-4d5e-a432-2b54916e67c3.png)

There is nothing happening on the server to conflict with this flow. The server CPU has 4 cores with utilization at nearly 0%. To troubleshoot I stopped every other prefect flow and every other server service. When I submit the flow to test, it is the only thing that prefect should be doing. No other flows are submitted, but there is still a 5 minute wait time.

I have watched `htop` after submitting the flow and I can see my agents polling for new work every 10 seconds. Past that, I don't know how to troubleshoot why the flow would be stuck in a pending state for 5 minutes before running.

I had this problem on an older version as well, then upgraded to the latest, but the problem persisted.

If you have troubleshooting ideas, I'm more than happy to try them!

**Comment by Ayowel** [comment]
I'm not familiar with Prefect, but this looks like a scheduling issue. Are you sure that both hosts' clocks are synced ? Check the `date` on both sides in case they don't use the same time servers

**Comment by richard-alexander** [comment]
There's only one host, so yes it is synced

**Comment by madkinsz** [comment]
@richard-alexander can you share DEBUG level logs? From what you've shared so far, it sounds like syncing the deployment code is slow. 

Note that we also provide a "prefetch" setting to ensure your flows start on time when the startup time is long: https://docs.prefect.io/concepts/work-queues/#configuring-prefetch

**Comment by richard-alexander** [comment]
Here are the debug logs @madkinsz :
-----------------------------------

Downloading flow code from storage at 'some/location'
05:53:20 AM
Importing flow code from 'some/location'
06:00:36 AM
Starting 'SequentialTaskRunner'; submitted tasks will be run sequentially...
06:00:37 AM
Executing flow 'Organize Claim' for flow run 'neat-deer'...
06:00:37 AM
Beginning execution...
06:00:37 AM
CLAIM DETAILS
                claim_id:  206
                 user_id:  2
              user_email:  ******
                root_dir:  /some/location
              claim_name:  exam2
06:00:37 AM
Created task run 'db_processing-67730e5f-0' for task 'db_processing'
06:00:37 AM
Executing 'db_processing-67730e5f-0' immediately...
06:00:37 AM
Beginning execution...
06:00:37 AM
db_processing-67730e5f-0
Finished in state Completed()
06:00:37 AM
db_processing-67730e5f-0

-----------------------------------------
Notice the 7 minute delay between downloading and importing the flow code.  I can understand why there might be a delay on the very first run of the flow  (if deployment syncing is needed), but this happens on every single run. I'm also not sure why any type of syncing would take so long when all of the files are stored locally. It shouldn't take 7 minutes to open a file on the local hard drive.

Unfortunately setting "prefetch" won't help in this situation because of the way I am submitting the flow (with `run_deployment` and `timeout=0`).

**Comment by madkinsz** [comment]
From those logs, this time is almost definitely spent copying files. We copy the deployment's folder to a temporary directory so each flow runs in isolation. You're likely copying a bunch of files that you do not intend to.

**Comment by madkinsz** [comment]
Perhaps have your flow print the current directory name then sleep forever on start then go there and look at the files? It's also just going to be a copy of "some/location". Do you have large files there? We recursively copy directories, do you have a lot of files in nested directories? Do you have a `.git` directory there? What's included in your `.prefectignore`?

**Comment by richard-alexander** [comment]
It looks like you're right about long file copy time! To answer your questions, my directory structure looks like this:

```
home/
|  project/
|     |  prefect_files/
|     |  big_files/
|     |  .git/
|     |  other_stuff
```

I would expect only `/home/project/prefect_files` to be copied, but I'm seeing that everything in `/home/project` is being copied (including **big_files**).

Where should I put `.prefectignore` within this structure? I can't find one, perhaps because I use deployment files as in [this issue](https://github.com/PrefectHQ/prefect/issues/7207).

Once I create  `.prefectignore`, will I need to restart prefect? Or will it automatically be read when the deployment starts?

**Comment by madkinsz** [comment]
The deployment's directory is the current working directory when you create the deployment. If you switch to the `prefect_files` folder to register your deployment instead of `project` it should reduce the scope.

The `.prefectignore` file should be in the root directory of the deployment (i.e. the working directory during creation). I'm actually not sure when it's applied. @peytonrunyan is a better resource here. In the source, it looks like it's done during `put_directory` https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L341 so it may only apply when your code is being pushed somewhere on deployment creation.

**Comment by richard-alexander** [comment]
Hmm... I created a `systemd` service that starts prefect so it will be resilient to server restarts. But I don't specify a path anywhere other than to the python environment, so I'm not sure exactly where it is being started from.

Some of my  prefect flows do need to read from the `big_files` directory. (Within the script at execution time, not the deployment.) Does that have any bearing on where I should start prefect from?

**Comment by madkinsz** [comment]
> Hmm... I created a systemd service that starts prefect so it will be resilient to server restarts.

Note I'm talking about when you _create_ the deployment. Not when you run it with an agent.

> Some of my prefect flows do need to read from the big_files directory.

This is a bit tricky. You'll probably want to limit your deployment to the code necessary to run your flows. Then, you can read from `big_files` using an absolute path rather than path relative to the code. This will avoid the overhead of copying `big_files` around.

**Comment by richard-alexander** [comment]
> Note I'm talking about when you create the deployment. Not when you run it with an agent.

I can see that would hold true when using the CLI, but what about python deployment files? I just tried redeploying with my python deployment file from within the `prefect_files` directory and I'm seeing the same behavior (long wait time). Is there a flag I can set in this scenario?

> You'll probably want to limit your deployment to the code necessary to run your flows. Then, you can read from `big_files` using an absolute path 

Agreed. I will do this!  :-)

**Comment by peytonrunyan** [comment]
`and I'm seeing the same behavior (long wait time).`

So we've got two steps that happen with storage - upload on deployment creation and download on deployment run. If a given storage block has a ton of files uploaded, they're going to always be downloaded on each run, no matter what the `.prefectignore` says.

The trick is to not upload the big files in the first place, and this is where the `.prefectignore` comes in handy. 

The paths in the `.prefectignore` are relative to wherever you run your CLI command from, or from your current working directory when calling the python script containing the deployment file.

**Comment by richard-alexander** [comment]
I understand that this is expected behavior, but from an end user perspective, this was extremely hard to debug. Might I suggest some kind of Info or Debug level log message pointing the user to `.gitignore` if deployment file load times exceed a certain threshold?

I had no idea that `.gitignore` existed or that I might need to use it.  ;-)

**Comment by madkinsz** [comment]
That's a great idea! We can track that in a separate issue, thanks :)
