### ISSUE TITLE
Timeline view shows incorrect subflow names

### ISSUE THREAD

**Issue by barys-rutman-ef** [PrefectHQ/prefect#8180]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The timeline view shows incorrect subflow names - - they mismatch with the actual subflow names. See the screenshot attached

### Reproduction

1. Open Prefect Cloud UI app.prefect.cloud/
2. Go to Flow Runs, click on the specific flow
3. observe the subflow names on the timeline view - they mismatch with the actual subflow names. See the screenshot attached

### Error

<img width="335" alt="Screenshot 2023-01-17 133542" src="https://user-images.githubusercontent.com/96241187/212890135-711e58b0-0c3f-46cf-b9de-7194a5084001.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Additional context

a link to the impacted flow - https://app.prefect.cloud/account/69511c67-969d-4734-9ebb-f6bb65c7a16a/workspace/7be7bebd-181e-4a8e-8561-356f9889755a/flow-runs/flow-run/36007ec1-ff54-4001-aa7f-00335457d705

**Comment by madkinsz** [comment]
cc @brandonreid

**Comment by galtman5** [comment]
Is it possible to also have the option of using the hardcoded subflow names instead of the random nicknames in the timeline visual?

**Comment by madkinsz** [comment]
@galtman5 can you expand on that a little? Are you talking about the _flow name_ which is different than the _flow run name_?

**Comment by galtman5** [comment]
Yea, sorry for that. You were right, I was referring to having the flow names in the timeline view as opposed to the flow run names.

**Comment by madkinsz** [comment]
@galtman5 how are you imagining distinguishing between multiple runs of the same subflow in that case? We probably want to leave that as-is and just provide better client-side functionality for setting the run name.

**Comment by galtman5** [comment]
@madkinsz good point. That works too.

**Comment by zhen0** [comment]
Thanks for flagging @barys-rutman-ef. This is kind of odd but we'll dig in and figure out what's going on.

**Comment by barys-rutman-ef** [comment]
Thanks @zhen0 . This is a recurring error, I continue seeing it in new flow runs :(

**Comment by zhen0** [comment]
Looks like what you are seeing in the timeline is strictly correct but not great UX/ is something we can improve on.  The timeline is displaying the name of the task run that kicks off your sub flow run. We'll need to add a query to get the sub flow run name and replace the task run name with it.

**Comment by komodovaran** [comment]
I'd like to add to this that the newly introduced `flow_run_name` is also wholly ignored by the timeline (but not in the subflows tab).

**Comment by sti0** [comment]
MRE:
```python
from prefect import flow
import time

@flow
def sub():
    time.sleep(10)

@flow
def main():
    sub()

main()
```
![image](https://user-images.githubusercontent.com/18382402/218677137-4648d5c5-2bcf-4329-b5e0-f5d99dfd300b.png)

**Comment by madkinsz** [comment]
@brandonreid I think the tracking task that is linked to the subflow does not ever need to be displayed, it's always a dummy right now.

**Comment by brandonreid** [comment]
Thanks @madkinsz , so we'll probably update the graphs endpoint so that it calls for the actual sub-flow in those instances and skips the dummy ever getting to the front end. Dig it. So this is essentially what I'm working toward next and maybe first iteration will simply be the name.

**Comment by brandonreid** [comment]
This has been resolved in the latest [release](https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-287).

I do plan to add the flow name to the graph as well, so instead of `sneaky-creature`, the sub flow name would display as `My Actual Flow Name / sneaky-creature`.

@barys-rutman-ef thanks for reporting this!
