### ISSUE TITLE
Deployments from python files do not respect .prefectignore

### ISSUE THREAD

**Issue by richard-alexander** [PrefectHQ/prefect#8195]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Given the following project structure we should be able to deploy from any directory and use `.prefectignore` to ignore the `big_files/` directory.

```
home/
|  project/
|     |  prefect_files/
|     |      |  test_flow.py
|     |      |  test_flow_deploy.py
|     |  big_files/
```

If the deployment is run from `home/project/`, the `big_files` directory will be copied by default, causing long file load wait times during deployment.

I have tried placing `.prefectignore` in `home/project/` as well as `home/project/prefect_files/`. No matter where I put `.prefectignore` the `big_files/` directory still gets copied during the deployment process.

To test this, I have deleted the deployment and remade it many times. I have also manually checked `/tmp` to make sure that existing file copies have been deleted.

### Reproduction

```python3
# Create the above folder structure
# Create a python deployment file
# Create a `.prefectignore` containing the line `big_files/'
# Place `.prefectignore` anywhere you wish
# Deploy from `/home/project`
# `big_files/` will still be copied to the deployment
```

### Error

```python3
# `.prefectignore` is not respected and `big_files/` is copied to the deployment
```

### Versions

```Text
Version:             2.7.8
API version:         0.8.4
Python version:      3.10.4
Git commit:          75d2e146
Built:               Thu, Jan 12, 2023 1:41 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

### Additional context

Related to #8178
And possibly #7207

**Comment by madkinsz** [comment]
Hey @richard-alexander — just to clarify, you mix `.gitignore` and `.prefectignore`  a few times above — which one did you use?

**Comment by richard-alexander** [comment]
Whoops! I fixed it. I always used `.prefectignore` in practice, but I'm apparently a lot more used to typing .gitignore!  ;-)

**Comment by madkinsz** [comment]
I believe that the issue here is that `.prefectignore` is only used during `put_directory` (i.e. upload) but here the files ar copied from a local directory to the runtime directory using `get_directory`.

**Comment by peytonrunyan** [comment]
What does your `.prefectignore` contain?

**Comment by richard-alexander** [comment]
.prefectignore
```
big_files/
```

**Comment by richard-alexander** [comment]
@peytonrunyan and I were able to recreate this issue in a slack huddle last week. I'm not sure what the final findings were though...

**Comment by peytonrunyan** [comment]
I think it might have a been a typo on my part. I sent you a follow up message that same day, but the issue disappeared and I re-typed the contents of my `.prefectignore`.

**Comment by FeryET** [comment]
I have this issue. My prefect ignore starts with this copied from my gitignore file:

```
# .gitignore section
.docker/volumes/
.docker/log/

log/*

**/makefile

**/*.secret*

!**/.gitkeep
```

The folders in the volumes folder are created by docker so the current user does not have the required permissions to access them, and during the upload the `put_directory` method cannot ignore these files.

**Comment by nick-amplify** [comment]
> I believe that the issue here is that `.prefectignore` is only used during `put_directory` (i.e. upload) but here the files ar copied from a local directory to the runtime directory using `get_directory`.

@madkinsz Is this by design? Why is the prefectignore not used for local copying?
