### ISSUE TITLE
Add a short blurb on the Prefect Blocks UI page linking to Collections Catalog

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#8211]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

At the moment, users may see the default listing and think that's all the blocks available
![image](https://user-images.githubusercontent.com/15331990/213576079-55065085-11fd-4167-b3a3-499bf28d734d.png)

### Describe the proposed behavior

We should make it clear that there are more blocks available for registration to improve visibility on Collections
![image](https://user-images.githubusercontent.com/15331990/213576182-6df8aea9-2394-434a-bba9-499dc1e7e1a4.png)

The html:

`<p>Below are all the Block types you have <strong>currently registered</strong>. Don't see a block for the service you're using? Click <a href="https://orion-docs.prefect.io/collections/catalog/" class="p-link">here</a> to view a catalog of integrations and their corresponding Blocks, available for installation!</p>`

### Additional context

We can also do the same when users try searching for a non-existent block
![image](https://user-images.githubusercontent.com/15331990/213576257-956431fa-983e-451b-a65e-639018f675ca.png)

Another idea is if we have a dropdown to link to specific collections' blocks catalogs
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15331990/213576357-3d2847ec-fb16-4291-b7e0-4af2f6117528.gif)

**Comment by madkinsz** [comment]
@nathanielaldon does this have a priority?

**Comment by nathanielaldon** [comment]
@ahuang11 is digging into this one, I've added a low comparative priority for this. Thanks for catching that @madkinsz!

**Comment by zhen0** [comment]
Given that is very low lift for the potential gain, I've added to the ui backlog quick wins section.
