### ISSUE TITLE
automation dependency tree view

### ISSUE THREAD

**Issue by efranksrecroom** [PrefectHQ/prefect#8220]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

automations do not seem to have a visual that shows a high level view of what happens in a given automation or which flows/events have dependencies

### Describe the proposed behavior

Ideally, the UI would show the entire "tree" of what happens in an automation. Thus a "pretty" visual that has:

event -> action 1
          -> action 2
          -> action 3
          
Taking this to the next level would be an automations tree view that shows each event and ALL actions from any Automation. This would mean, if I have a flow and that completion of that flow triggers 3 other flows to run through a single automation and I have another automation that also triggers something via a separate automation, I have a way to see this full "dependency tree" in one visual. This view would allow us to easily see the full scope of dependencies on a given flow/event.

The perfect world would have a prettier view that looks something like the attached.
<img width="1459" alt="automation-feature-request" src="https://user-images.githubusercontent.com/119447048/213791228-a9ba546b-f282-4c3e-a76b-b5c109202a77.png">

### Example Use

As an Analytics Engineer, I would like to be able to easily see the full set of dependencies on a given flow/event so that I know what subsequent flows/processes will be affected by a change to a given flow/event.

**Comment by WillRaphaelson** [comment]
@efranksrecroom - thanks for filing this. Not to sound like a broken record, but I think we'll be considering adding representations of these dependencies in the next few months. Would love to get on and chat more about how you'd use an enhancement like this.

**Comment by efranksrecroom** [comment]
Same as the other, happy to chat and help!

Thanks,
-E
