### ISSUE TITLE
"prefect agent start" won't respect PREFECT_EXTRA_ENTRYPOINTS

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8225]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to write a new infrastructure type (A [Render](https://render.com/) Task).
For that to work, I need to use the PREFECT_EXTRA_ENTRYPOINTS to be able to tell Prefect to load the python module that contains the new Infrastructure class I've created.

Following this [PR](https://github.com/PrefectHQ/prefect/pull/7179), we can see that PREFECT_EXTRA_ENTRYPOINTS do work for the specific scenario:
`PREFECT_EXTRA_ENTRYPOINTS=foo python -c "import prefect"`
In this scenario, we set the env var to foo, and then run a python code with "import prefect". This works, meaning the foo module is being imported and if you'd put a print() command in it, it will run.

But doing the same in combination with the Prefect agent, won't work:
`PREFECT_EXTRA_ENTRYPOINTS='render_job_infrastructure' prefect agent start --work-queue "default"`
You will get the error:
`Warning! Failed to load extra entrypoint 'render_job_infrastructure': ModuleNotFoundError: No module named 'render_job_infrastructure'`

It seems like when the agent starts, it does unserstand that you've set the PREFECT_EXTRA_ENTRYPOINTS, and tries load the module, but probably there is something wrong with the default path it look in.

Being able to set:
`PREFECT_EXTRA_ENTRYPOINTS='render_job_infrastructure'`
and then start the agent, is a must for us (and anyone trying to develop a custom Infrastructure Block) as the agent must know the render_job_infrastructure, and it needs to be loaded.      

### Reproduction

```python3
Clone this repo:
https://github.com/yaronlevi/prefect-PREFECT_EXTRA_ENTRYPOINTS/blob/main/some_module.py
and run:
PREFECT_EXTRA_ENTRYPOINTS=some_module prefect agent start --work-queue "default"
```

### Error

```python3
Warning! Failed to load extra entrypoint 'some_module': ModuleNotFoundError: No module named 'some_module'
```

### Versions

```Text
Version:             2.7.7
API version:         0.8.4
Python version:      3.10.9
Git commit:          e8ca30b8
Built:               Fri, Jan 6, 2023 4:25 PM
OS/Arch:             darwin/x86_64
Profile:             yaron
Server type:         cloud
```

**Comment by madkinsz** [comment]
@yaronlevi have you ensured that the given module is on the python path? Invoking a script with `python ...` will add the current direct to the path but calling it from the CLI probably does not. I'd recommend:

- Adding the relevant directory to the python path via an environment variable
- or Installing the module as a package so it is available on the path

**Comment by yaronlevi** [comment]
@madkinsz Thanks! I'll try both of your suggested solutions and come back with results.

**Comment by yaronlevi** [comment]
@madkinsz 
Success! 🎊🎊🎊
This will work:

`PYTHONPATH=$PYTHONPATH:/Users/yaron/dev/rumble_server PREFECT_EXTRA_ENTRYPOINTS=some_module prefect agent start --work-queue "default"`

So we should the path of the folder that some_module.py sits in to the PYTHONPATH. In this case, to /Users/yaron/dev/rumble_server,

**Comment by jeremy-thomas-roc** [comment]
As a note on a closed issue, since I just ran into this: in a Docker container, when you run `prefect agent start`, the directory you run that command from is not added to path. This means that even if you run `start` from the directory with the `.py` file you want to include, it is possible that it will not be read properly. 

Updating the PYTHONPATH ENV in the Dockerfile to make sure it will include any `.py` files you want to include this way fixed it.
