### ISSUE TITLE
Increase visibility of task cache runs, Allow users to manage their caches better

### ISSUE THREAD

**Issue by wendytang** [PrefectHQ/prefect#8239]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.7.7+

### Describe the current behavior

Currently users can implement a cache key and input a cache expiration in order to cache task run results and reuse them for later task runs. 

However there is not much visibility into when a task cache gets used and also not much functionality in managing the cache itself. Improving the **cache management functionality** would be incredibly helpful for long-running data pulling tasks which can be cached and skipped. 

Cache management mechanisms we are interested in include (in order of priority):
1. Viewing list of cache keys, which task + task run they trace back to
2. Deleting caches
3. Detecting when cache was last used, eg various cache usage metadata

Currently detecting task cache runs is not ideal:

```
@task(cache_key_fn=task_input_hash, cache_expiration=timedelta(days=1))
def hello_task(name_input):
    return "hello " + name_input

@flow
def hello_flow(name_input):
    # Flow Level Work
    logger = get_run_logger()
    rc = context.get_run_context()

    rs = hello_task(name_input, return_state=True)
    logger.info(f'RETURNED STATE: {rs}')
    logger.info(f'RETURNED STATE RESULT: {rs.result}')
    logger.info(f'RETURNED STATE DETAILS 1: {rs.state_details.cache_key}')

    logger.info("TASK RUN: ")
    if rs.result is not None and ("Cached" in str(rs)):
        logger.info("Task returned cached result")
    elif rs.result is not None:
        logger.info(f'Task caching result to {rs.state_details.cache_key}')
    return 0, 0

```
### Describe the proposed behavior

I'm not a stickler to how the solution has to be - any form of improvement + increased reliability to the current way of detecting cached result retrieval would be great.

I am wondering if the product roadmap would consider this direction:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/7952060/214177309-001cf8a4-9e0a-4a1d-b177-7090f0072ed1.png">

### Additional context
For ++visibility and discussion

**Comment by peytonrunyan** [comment]
Thanks for submitting the issue!

In the short term, there's definitely an easier way to access whether or not a task was run cached. I'll include a code snippet below. 

For the UI updates, we have access to the information about whether or not a task was completed and cached in the `task_run_state` table. The UI and product teams will have to give that look.

For the comprehensive state information, we might be able to add a client method that returns that information. I'll need to check with the backend team to see if that works.

```python
import time
from datetime import timedelta

from prefect import task, flow, get_run_logger
from prefect.tasks import task_input_hash

@task(cache_key_fn=task_input_hash, cache_expiration=timedelta(seconds=5), name="Meow")
def dog():
    logger = get_run_logger()
    logger.info("woof!")

@flow
def f():
    state1 = dog(return_state=True)
    print(state1.name)
    time.sleep(2)
    state2 = dog(return_state=True)
    print(state2.name)

if __name__ == "__main__":
    f()
``` 
results in 
```
(orion-dev) ➜  orion-dev python current-work/is-schedule-active/f.py 
14:06:40.994 | INFO    | prefect.engine - Created flow run 'ultramarine-mustang' for flow 'f'
14:06:41.049 | INFO    | Flow run 'ultramarine-mustang' - Created task run 'Meow-64b6a0ac-0' for task 'Meow'
14:06:41.050 | INFO    | Flow run 'ultramarine-mustang' - Executing 'Meow-64b6a0ac-0' immediately...
14:06:41.070 | INFO    | Task run 'Meow-64b6a0ac-0' - woof!
14:06:41.078 | INFO    | Task run 'Meow-64b6a0ac-0' - Finished in state Completed()
Completed
14:06:43.099 | INFO    | Flow run 'ultramarine-mustang' - Created task run 'Meow-64b6a0ac-1' for task 'Meow'
14:06:43.100 | INFO    | Flow run 'ultramarine-mustang' - Executing 'Meow-64b6a0ac-1' immediately...
14:06:43.117 | INFO    | Task run 'Meow-64b6a0ac-1' - Finished in state Cached(type=COMPLETED)
Cached
14:06:43.132 | INFO    | Flow run 'ultramarine-mustang' - Finished in state Completed('All states completed.')
```

**Comment by wendytang** [comment]
@madkinsz - wonder if you have any advice currently to answering the question: what's in my cache? 

Long-term solution is cache management as detailed above, but for the interim solution, I want to be able to match the cache key produced by the task run to what's seen in cache storage. 

In the above example which prints the cache key of a task run, I tried to match it with the hashes seen in local storage but don't see a match (looking for `fb97a05c3e408a2bb70f464de4cb944b`). Is it supposed to match? If not, is there a way to determine what task run produced key `5662e125ec774c82adbb5c30a0eb92b4`?

Logs:
```
11:21:46.018 | INFO    | Flow run 'wandering-stallion' - Task returned cached result
11:21:46.018 | INFO    | Flow run 'wandering-stallion' - Cache key: 
11:21:46.018 | INFO    | Flow run 'wandering-stallion' - fb97a05c3e408a2bb70f464de4cb944b
```

File storage:
```
ls -lat ~/.prefect/storage | head -10
total 600
-rw-r--r--@  1 wendytang  staff   190 Jan 23 14:54 5662e125ec774c82adbb5c30a0eb92b4
drwxr-xr-x@ 77 wendytang  staff  2464 Jan 23 14:54 .
-rw-r--r--@  1 wendytang  staff   190 Jan 23 14:20 4b9216177afc4abab65fb599614a16db
```

**Comment by madkinsz** [comment]
The cache keys are linked to states, not result files. 

The cache key table looks like this https://github.com/PrefectHQ/prefect/blob/main/src/prefect/orion/database/orm_models.py#L215-L225

To determine the task that created the cache key, you'd need to look up the state referenced by `task_run_state_id` which should have a `state_details.task_run_id` attached to it. The location of the result would also be present on the state in the `data` attribute.

**Comment by wendytang** [comment]
Thanks @madkinsz; @peytonrunyan last thought here.. given the storage hash is represented by task run id, the feature that would provide the most value to users would be a way to reverse lookup the task run hash and get the task name. Eg hash storage key `5662e125ec774c82adbb5c30a0eb92b4` maps to hello_task_{run_id}.

**Comment by madkinsz** [comment]
@wendytang sorry I'm not sure I follow, what's your goal? Are you trying to determine which _task name_ a given _result file_ relates to?

**Comment by wendytang** [comment]
Yes, I may not have the terminology right, but essentially I want to determine the task name which generated a given results file (or is this task_run_state.storage_key?) 

`fa7309a8da7d4ec7afc76d57fdfb8130` here.

Query orion db for `task_run_state.storage_key` 
```
{'id': '7e06c189-f540-4274-b568-2e112c45000b', 'created': '2023-01-27 20:21:09.257473', 'updated': '2023-01-27 20:21:09.257478', 'type': 'COMPLETED', 'timestamp': '2023-01-27 20:21:09.257015', 'name': 'Cached', 'message': None, 'state_details': '{"flow_run_id": "6c9092f1-7098-48a2-868a-505e59dbf220", "task_run_id": "494feaf2-67d2-4f04-8910-969aec930857", "child_flow_run_id": null, "scheduled_time": null, "cache_key": "static cache key", "cache_expiration": "2023-01-28T20:21:09.033199+00:00", "untrackable_result": false, "pause_timeout": null, "pause_reschedule": false, "pause_key": null}', 'data': '{"type": "reference", "serializer_type": "pickle", "storage_block_id": "6f0f8719-692e-483f-895e-8d8ac276f70e", "storage_key": "**fa7309a8da7d4ec7afc76d57fdfb8130**"}', 'task_run_id': '494feaf2-67d2-4f04-8910-969aec930857'}
```

```
ls -lat ~/.prefect/storage | head -10
total 760
-rw-r--r--@  1 wendytang  staff  5724 Jan 27 12:21 **fa7309a8da7d4ec7afc76d57fdfb8130**
```

**Comment by madkinsz** [comment]
Yes so the `storage_key` is present on the `data` attribute of the task run state if the result has been persisted somewhere. What you're seeing at the `State.data` attribute is a `PersistedResult` object.

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/results.py#L390-L405


The `storage_key` is the path to the file in storage. Right now, results are a client-side concept. We're working to create a dedicated server-side concept for them which might help with this. It's not feasible for the server to provide information about results at this time because, to the server, the `data` attribute is just a JSON blob.

**Comment by wendytang** [comment]
@peytonrunyan I wanted to follow up on this feature - were you able to get an answer from the backend team? We would be very interested in using this feature for our workflows.

`For the comprehensive cache information, we might be able to add a client method that returns that information. I'll need to check with the backend team to see if that works.`

**Comment by billpalombi** [comment]
While we don't have a solution design in mind at the moment, this is a need that we will address in the future.

**Comment by madkinsz** [comment]
A short-term solution here may be to add the ability to customize generation of result storage keys.

**Comment by PiotrSiejda** [comment]
I might be wrong, but it seems to me that possibility to remove the cache (long term solution) got lost. It was kind of meant to be done in #8892 but that ticket got closed as this was supposed to be the main one. This one got closed with the possibility to name the cache: #8949

**Comment by EmilRex** [comment]
@PiotrSiejda does #10494 track the functionality you're looking for?
