### ISSUE TITLE
Add setting env variable to alter the default sidebar background color

### ISSUE THREAD

**Issue by corris** [PrefectHQ/prefect#8241]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There is no way to alter the sidebar background color via a setting/environment variable.

### Describe the proposed behavior

There should be an environment variable / setting named something like PREFECT_ORION_UI_SIDEBAR_BACKGROUND_COLOR, which, when set, changes the background color of the sidebar.  I think it's p-context-sidebar - background-color

### Example Use

We run a number of instances of the orion server to maintain strict separation of dev/staging/production environments.  There's no easy way ( apart from the URL ) to tell the difference.  Having the sidebar be able to be set to a specific background color would let us easily, quickly distinguish between the environments.  ( e.g. default for dev, green for staging, red for production ).

While you're in there, it'd be great if we could add a custom nav-item text above "Flow Runs" so we could specify Development, Staging, or Production as a "title" of sorts.... PREFECT_ORION_UI_SERVER_TITLE or something.

**Comment by peytonrunyan** [comment]
Thanks for submitting the enhancement request! Somebody from the frontend team will give it a look in the next week.

**Comment by corris** [comment]
Re open please?
