### ISSUE TITLE
Change default sort order for logs to newest to oldest

### ISSUE THREAD

**Issue by TimoVink** [PrefectHQ/prefect#8242]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When a user looks at the Flow Run Logs page, the logs can be sorted "Newest to Oldest" or "Oldest to Newest", with the default being "Oldest to Newest".

While there's uses for both, I personally almost always want to use Newest to Oldest, so have to change the dropdown every time I visit the page.

### Describe the proposed behavior

It would be nice if it was possible to set a default on the Settings page, similar to the Theme and Color Mode.

**Comment by zhen0** [comment]
Thanks for the suggestion @TimoVink. @billpalombi - any thoughts? For something like this we'd need to add to user settings in the api but it could be a simple add on.

**Comment by TimoVink** [comment]
Wasn't expecting such a fast response to such a minor request!

One (possibly simpler?) suggestion could also be to simply remember the last-used sort order (e.g. save in localstorage) instead of dedicating space for this configuration on the settings page.

**Comment by billpalombi** [comment]
I don't think we need a configurable default for this.

That said, we seem to be out of step with the convention. Datadog, Kibana, and Splunk all default to sorting newest to oldest. Only New Relic sorts to oldest to newest. I think we should globally change sorting from newest to oldest.

**Comment by madkinsz** [comment]
@billpalombi GitHub Actions notably sorts from oldest -> newest

**Comment by billpalombi** [comment]
The plot thickens. Github actions is somewhat more analogous to us. This behavior should probably also apply to the task run and subflow runs tab as well for consistency.

**Comment by TimoVink** [comment]
Perhaps the issue I filed suffers a bit from an XY problem: I don't _really_ care if I'm reading oldest-to-newest or newest-to-oldest. What I'm actually struggling with is getting to the logs I care about quickly.

Specifically, most of the time when I want to look at the logs, it's because something went wrong and I'm starting my debugging journey. Maybe some tasks will have failed, and I want to see the exception and the messages leading up to that exception. In the current UI that basically means "scroll to the bottom of the page" or perhaps "click on task runs, click on the task that failed, and _then_ scroll to the bottom of the page".

Contrasting with GitHub Actions: If I go to an action that failed (e.g. https://github.com/PrefectHQ/prefect/actions/runs/4191956088/jobs/7266947695) you'll notice a few things:
 (1) Logs are searchable (I believe there's already open feature requests for this for prefect)
 (2) Logs are collapsible allowing me to quickly drill down to the subsets of logs I'm interested in
 (3) Log messages are denser: On my screen GitHub actions fits a little over 1.5x more lines of logs on the screen at once) and the amount of space "above the fold" for logs is about 2x as much (bottom 2/3 of the page, vs bottom 1/3 for prefect)
 (3) Most importantly: On page load the page auto-uncollapses relevant sections and autoscrolls to where the error occurred, so just by opening the page it takes me straight to what I came there for.

Again, I really appreciate all the responses. Love the tool, and enjoy seeing it get better with every release!

**Comment by billpalombi** [comment]
We have some changes to the flow run page as a whole coming, but we'll still want to act on some of this feedback.

**Comment by IAL32** [comment]
I am also interested in this feature. I would love to configure this as a setting, but any other way that is permanent would be prefect.

**Comment by pleek91** [comment]
The log sort is now saved in local storage. So once you change the sort it will use that as your default. So I'm going to close this issue. If this doesn't meet your needs please let us know
