### ISSUE TITLE
Concurrency limits not being released by tasks showing as complete

### ISSUE THREAD

**Issue by konwiddak** [PrefectHQ/prefect#8251]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have the following setup:
Windows
Prefect 2.7.9
Concurrency limit called "test" with a limit of 8 tasks
Using Prefect Orion, running locally.

I have a flow that spawns a reasonable number of tasks (although not particularly excessive, it's up to 100 tasks spawned in batches of 3 every 10-20 seconds), these tasks are highly variable in how long they run. Some of these tasks wait for prior tasks to complete. Upon execution, sometimes the concurrency limit is not released (takes about 10 minutes to run). This is despite the fact that the tasks are completing successfully and shown as successfully completed in Orion. 

I have generated an example flow that is structured very similarly to my production flow in structure and timing behavior. After running, there are usually a few tasks stuck in the concurrency limit.
![image](https://user-images.githubusercontent.com/48279914/214588166-63e85b35-a0c4-4263-a87f-91bd32d519bf.png)

### Reproduction

```python3
from prefect import flow, task, get_run_logger
import time
import random

@task
def generaterandomtime():
    rando = random.randint(2,9)
    time.sleep(rando)
    return rando**2

@task(tags=["test"])
def randomtime1(i, t):
    logger = get_run_logger()
    logger.info(f"Task {i} sleeping for {t} seconds")
    time.sleep(t)
    logger.info("Complete")
    return generaterandomtime.fn()

@task(tags=["test"])
def randomtime2(i, t):
    logger = get_run_logger()
    logger.info(f"Task {i} sleeping for {t} seconds")
    time.sleep(t)
    logger.info("Complete")
    return generaterandomtime.fn()

@task(tags=["test"])
def randomtime3(i, t):
    logger = get_run_logger()
    logger.info(f"Task {i} sleeping for {t} seconds")
    time.sleep(t)
    logger.info("Complete")
    return generaterandomtime.fn()
    
@flow(name="Test concurrency limits")
def ctest(n_runs=25):

    for i in range(n_runs):
        t1 = generaterandomtime()
        t2 = randomtime1.submit(i, t1)
        t3 = randomtime2.submit(i, t2, wait_for=[t2])
        randomtime3.submit(i, t3, wait_for=[t3])
        

if __name__=="__main__":
    ctest()
```

### Versions

```Text
Version:             2.7.9
API version:         0.8.4
Python version:      3.10.6
Git commit:          42b80f18
Built:               Thu, Jan 19, 2023 4:59 PM
OS/Arch:             win32/AMD64
Profile:             prod
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```

**Comment by konwiddak** [comment]
I have written a workaround flow that periodically purges zombie tasks from the concurrency limit. It does this by forcing a state change to the same state via the Orion API for completed tasks within the concurrency limit. I believe this causes the checks that occur upon task completion to be re-ran but by the Orion server instead of the agent. Currently this has only been written for "Completed" tasks, but it could be trivially adapted to other statuses. It's also possible to extend this method to check parent flows and see if their status is complete/crashed - and therefore force still running tasks to be deleted should the parent task have crashed.

```
import asyncio
from httpx import HTTPStatusError
from prefect import flow, task, get_run_logger
from prefect.client import get_client
from prefect.orion.schemas.states import State, StateType
  
#This flow checks the concurrency limit and purges zombie tasks
#It does this by setting the task state again, this appears to force the correct cleanup  
@flow
async def reset_concurrency_limits():

    logger = get_run_logger()
    
    async with get_client() as client:
        #Get concurrency limits
        limits = await client.read_concurrency_limits(None, None)
        
        for lim in limits:
            tag = lim.tag
            logger.info(f"Tag = {tag}")
            limit = lim.concurrency_limit
            for act in lim.active_slots:
                uuid = str(act)
                print(uuid)
                try:
                    #Get the task info
                    task = await client.read_task_run(uuid)
                except HTTPStatusError:
                    # If the task doesn't exist - 
                    # these can only be removed by deleting the concurrency_limit
                    continue
                              
                
                if task.state_name == 'Completed':
                
                    state = State(type=StateType.COMPLETED, name="Completed")
                    #If the task isn't running
                    logger.warning(f"Completed task still holding limit {uuid}")
                    response = await client.set_task_run_state(
                                                                uuid,
                                                                state,
                                                                force=True,
                                                               )
```

**Comment by vp-walter** [comment]
We've encountered a similar issue, I'm not a prefect expert but here is the gist of what we've experienced.

we are mapping a function over a list (returned from a task). 500 tasks spawned in batches of 2-4 (we tried different concurrency limits). Eventually it will hang after 0-30 successful tasks. We also tried using a sequential task runner but, as shown in another issue #7763 , sequential task runner doesn't work with .map. For now we are explicitly looping over the list and spawning tasks using sequential runner which works.

**Comment by yaronlevi** [comment]
We see the same behavior here.
We defined a limit of 5 tasks, and the UI reports that there are 5 tasks running, but the list is empty:

![CleanShot 2023-02-06 at 23 22 19](https://user-images.githubusercontent.com/5398977/217090975-0aa914d4-91a6-484c-a18a-ac7752cd531e.jpg)

It seems those concurrency slots are being used, and never freed, but there are actually no flows that run with that tag.
This causes all the other Tasks wait forever:

![CleanShot 2023-02-06 at 23 24 16](https://user-images.githubusercontent.com/5398977/217091351-aeeb399b-61eb-41d0-8a55-dbef105dd4cc.jpg)

To only way out is to delete the concurrency limit from the UI and create it again.

**Comment by madkinsz** [comment]
Work in progress at #8408

**Comment by yaronlevi** [comment]
@madkinsz Thanks. I just want to mention, that in our case, no Tasks were failing. All of them always finish in SUCCESS state. But still, the "zombie slots" appear. Would love to send you any other info needed to debug the issue. Could also ping you just as it happens so a backend engineer could observe it in real time. Happens, each 3-4 hours in our case.

**Comment by njthompson-viv** [comment]
@madkinsz I can reproduce using prefect server with a default database. Note that in the reproducing example I had to bump `n_runs` up to 100

```
Version:             2.10.6
API version:         0.8.4
Python version:      3.10.8
Git commit:          d7a8f6bf
Built:               Thu, Apr 27, 2023 2:23 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by EmilRex** [comment]
Saw another user report of this today. Limit was set to 8, 3 slots were occupied, but no active tasks shown in the UI, nor any active related flow runs. This was happening against Cloud and the specific concurrency limit has ID `ecd6d13d-b1f6-4678-96a1-0abfc7e66ab3`.

**Comment by OptimeeringBigya** [comment]
> Work in progress at #8408

Hi @madkinsz , I see that the linked issue has been merged into the main. Does that PR solve the bug described in this page?

**Comment by madkinsz** [comment]
@OptimeeringBigya it resolves some of the bugs but there are still some cases we want to address
