### ISSUE TITLE
Docs should have a section on re-registering blocks from collections after a collection upgrade

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#8323]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There are no docs on reregistering a block from a collection.

There are no docs in the collections on reregistering a block.

This action will become increasingly common as Prefect 2 matures.

### Describe the proposed behavior

- Probably documentation in the Integrations/Collections section on reregistering blocks from a collection. 
- A link in the Blocks section of the docs to that documentation.
- A link in each collection's documentation to that documentation.

### Additional context

Common situation for users. We should give them instructions.

**Comment by serinamarie** [comment]
@discdiver Can this issue be closed as completed? Either way, I think the status label should probably change.

**Comment by discdiver** [comment]
Closing as completed by https://github.com/PrefectHQ/prefect/pull/8333
