### ISSUE TITLE
Prefect PREFECT_LOGGING_EXTRA_LOGGERS doesnt work in deployments

### ISSUE THREAD

**Issue by Wingmore** [PrefectHQ/prefect#8340]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I try set PREFECT_LOGGING_EXTRA_LOGGERS using `prefect config set PREFECT_LOGGING_EXTRA_LOGGERS=mtt`, the outputs are not shown in Orion Cloud deployments only. They appear to be fine when run locally though.

### Reproduction

```python3
from prefect import flow, get_run_logger, tags, task
from prefect import settings
from mtt import mtt_logger

@flow
def test():
    log = get_run_logger()

    # Check that the variable really was set
    log.info(settings.PREFECT_LOGGING_EXTRA_LOGGERS.value())

    mtt_logger.info(message="this is a test from mtt")
    log.info(mtt_logger.logger.handlers) # Should see Orion Handler and whatever existing handlers here
```

### Error

```python3
When run from a deployment


Loading flow for deployment 'run_corpus'...
Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
Executing flow 'create mtt' for flow run 'copper-caiman'...
Beginning execution...
['mtt']
[<RotatingFileHandler /home/adw/.mtt_logs/mtt.log (NOTSET)>]
Finished in state Completed()
```
```


### Versions

```Text
Version:             2.7.1
API version:         0.8.3
Python version:      3.9.15
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

When run normally `python file.py`:

```
16:09:51.782 | DEBUG   | Flow run 'rare-tiger' - Executing flow 'create mtt responses' for flow run 'rare-tiger'...
16:09:51.782 | DEBUG   | Flow run 'rare-tiger' - Beginning execution...
16:09:51.784 | INFO    | Flow run 'rare-tiger' - ['mtt']
[<RotatingFileHandler /home/adw/.mtt_logs/mtt.log (NOTSET)>, <OrionHandler (NOTSET)>]
16:09:52.098 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
16:09:52.100 | INFO    | Flow run 'rare-tiger' - Finished in state Completed()
```
I can see that both PREFECT_LOGGING_EXTRA_LOGGERS and OrionHandler has been set correctly here.

**Comment by Wingmore** [comment]
My bad, seems like I searched the wrong thing, this seems to be similar of #7755, but their example is a bit lacking, so here we are

**Comment by madkinsz** [comment]
Hey @Wingmore  — `prefect config set` only changes your local profile. To change the setting in a deployment, you'll need to set it as an environment variable.

**Comment by Wingmore** [comment]
@madkinsz I've also tried setting it inside the infrastructure block, however information on the correct syntax is lacking: I keep getting the following error:
```
1 validation error for Process
env
  value is not a valid dict (type=type_error.dict)
```

when I try put
```
{"PREFECT_LOGGING_EXTRA_LOGGERS":"mtt","PREFECT_LOGGING_LEVEL":"info"}
```
into the infrastructure block on Orion UI.

**Comment by serinamarie** [comment]
Hi @Wingmore, I agree that we could have more documentation around this. Could you try and see if one of these methods works for you?

```python
deployment = Deployment.build_from_flow(
    flow=my_flow,
    name="s3-example",
    version="2",
    tags=["aws"],
    storage=storage,
    infra_overrides=dict("env.PREFECT_LOGGING_LEVEL"="DEBUG"),
)
deployment.apply()
```

Alternatively, nested dictionary example:
```python
infra_overrides={"env": {"PREFECT_LOGGING_LEVEL": "DEBUG", "EXTRA_PIP_PACKAGES":"s3fs"}},
```
Finally,
```bash
prefect deployment build -n prod -q prod -ib process/prod -a flows/parametrized.py:parametrized --override env.PREFECT_LOGGING_LEVEL=DEBUG`
```

**Comment by Wingmore** [comment]
Hi @serinamarie, your 2nd example seems to work only for overriding the `PREFECT_LOGGING_LEVEL`, but NOT the `PREFECT_LOGGING_EXTRA_LOGGERS` which was the root of this issue.

When trying through CLI, I get `Submission failed. KeyError: 'env'`. FYI, this is what is inside my deployment.yaml after trying your 3rd suggestion:
```
infra_overrides:
  env.PREFECT_LOGGING_EXTRA_LOGGERS: '[''mtt'']'
```

Compared to the 2nd suggestion, (which doesnt seem to create the extra loggers though sadly :( ):
```
infra_overrides:
  {"env":
    {
      "PREFECT_LOGGING_LEVEL": "DEBUG",
      "PREFECT_LOGGING_EXTRA_LOGGERS": "mtt",
    }
  }
```

**Comment by serinamarie** [comment]
> I've also tried setting it inside the infrastructure block, however information on the correct syntax is lacking: I keep getting the following error:
> 
> ```
> 1 validation error for Process
> env
>   value is not a valid dict (type=type_error.dict)
> ```
> 
> when I try put
> 
> ```
> {"PREFECT_LOGGING_EXTRA_LOGGERS":"mtt","PREFECT_LOGGING_LEVEL":"info"}
> ```
> 
> into the infrastructure block on Orion UI.

I may have misread this before thinking you were referring to logging level.
When you set it on the block like this:

```python
process_job = Process(
    name="my-process-job",
    env={"PREFECT_LOGGING_EXTRA_LOGGERS": "my_logger"},
)

process_job.save("my-process-job")
```

```python
k8s_job = KubernetesJob(
    name="my_ks8_job",
    namespace="prefect-orion",
    image="prefecthq/prefect:2.7.11-python3.10",
    env={"PREFECT_LOGGING_EXTRA_LOGGERS": "my_logger"},
)
```

or build it in the UI:
![Screenshot 2023-02-14 at 12 13 28 AM](https://user-images.githubusercontent.com/42048900/218654382-34d78cc0-9015-4b91-bd87-9faefedb50bc.png)
and then run
`prefect deployment build local_work/my_flow.py:flow_log --name "process_flow" -ib "process/my-process-job" --aply`

Can you provide a UI screenshot or code of the input and output/error?

**Comment by namedgraph** [comment]
@Wingmore have you solved this issue? We can't get our library logs to show up in the UI :/
