### ISSUE TITLE
Default parameters do not get overwritten on scheduled runs

### ISSUE THREAD

**Issue by nasonovandrey** [PrefectHQ/prefect#8343]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I change parameter defaults during flow registration, they do not change. This problem persists only if the following conditions are met:
1. Default parameter changed to one of the following: dict(), list(), "", 0, False. I suppose any expression which is logically evaluated to False will do.
2. Flow is stored in GitLab storage. It might also be the case with the other types of external storage, but I checked it only in conjunction with GitLab storage.
3. Flow run is scheduled. When I start the flow manually, the default parameter value does change.

### Reproduction

```python3
import prefect
from prefect import Flow, Parameter, task
from prefect.schedules.clocks import CronClock
from prefect.schedules import Schedule
from prefect.storage import GitLab

@task
def output_param(param):
    logger = prefect.context.get("logger")
    logger.info(param)
    return param

with Flow("test-none-param") as flow:
    input_param = Parameter("input", default="value")
    output_param(input_param)

if __name__ == "__main__":
    # Configure schedule
    schedule = Schedule(clocks=[CronClock("*/1 * * * *")])
    flow.schedule = schedule

    # Configure storage
    flow.storage = GitLab(repo="repo.url", path="flow.py", ref="main")

    # Set defaults to empty dictionary
    for param in flow.parameters():
        param.default = {}

    # Register
    flow.register(project_name="project_name")
```

### Error

```python3
If param.default is changed to an empty dictionary (like in the code example above), the following output is produced:
Submitted for execution: PID: 16447
Beginning Flow run for 'test-none-param'
Task 'input': Starting task run...
Task 'input': Finished task run for task with final state: 'Success'
Task 'output_param': Starting task run...
value
Task 'output_param': Finished task run for task with final state: 'Success'
Flow run SUCCESS: all reference tasks succeeded

If param.default is changed to "another value" (one of the values, on which this bug doesn't persist), the following output is produced:
Submitted for execution: PID: 16666
Beginning Flow run for 'test-none-param'
Task 'input': Starting task run...
Task 'input': Finished task run for task with final state: 'Success'
Task 'output_param': Starting task run...
another value
Task 'output_param': Finished task run for task with final state: 'Success'
Flow run SUCCESS: all reference tasks succeeded
```

### Versions

```Text
❯ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-6.1.8-arch1-1-x86_64-with-glibc2.36",
    "prefect_backend": "cloud",
    "prefect_version": "1.2.4",
    "python_version": "3.10.9"
  }
}
```

**Comment by serinamarie** [comment]
Hi @nasonovandrey, thank you for reaching out to us regarding this issue. This particular pattern is outside the scope of our current support. However, we would review a pull request to our repository if you were interested in [contributing](https://docs.prefect.io/contributing/overview/) 🙂

**Comment by cicdw** [comment]
I'm closing this issue as stale and because Prefect 1.x is no longer under active development.
