### ISSUE TITLE
JSON deployment parameter input is not visible

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#8348]
Looks like something regressed in the json input parameter, I cant see the text im writing. 

![image](https://user-images.githubusercontent.com/26799928/216096559-e6ad932f-0e8c-41f5-a3ce-b8961c47ea63.png)

A note, this popped up in automations run-deployment action, so we should ensure that works as expected as well as the general run custom experience.

**Comment by madkinsz** [comment]
@WillRaphaelson Cloud? If not, what versions?

**Comment by WillRaphaelson** [comment]
Sorry yes prefect cloud, I didn't get the nice menu of options because I transferred the issue.

**Comment by znicholasbrown** [comment]
I'm working on a full replacement of this component in the base design library so I'll make sure this is addressed there (currently this component is bespoke in the orion component library).
