### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by dhirschfeld** [PrefectHQ/prefect#835]
As a `conda` user wanting to try out `prefect` I've started the work to add it to `conda-forge` over at https://github.com/conda-forge/staged-recipes/pull/8042

**Comment by dhirschfeld** [comment]
Please comment over in that PR if anyone would like to be added as a maintainer. 

A maintainer will get notifications about updates and can merge the auto-generated PRs from the update-bot (after reviewing them for correctness of course!)

**Comment by jlowin** [comment]
Thanks @dhirschfeld! @cicdw and I were just talking about getting this ball rolling, so we appreciate the effort! He's on Pacific Time but I'm sure he'll get involved once he's online.

**Comment by dhirschfeld** [comment]
The `staged-recipes` PR actually got merged before you had a chance to comment whether or not you wanted to be added as maintainers so I opened a new PR https://github.com/conda-forge/prefect-feedstock/pull/1 so that you can comment there.

**Comment by cicdw** [comment]
This is great @dhirschfeld thank you!

**Comment by cicdw** [comment]
@dhirschfeld I'm displaying my ignorance here, but what is the typical workflow for maintaining / updating a `conda-forge` package?

**Comment by dhirschfeld** [comment]
`conda-forge` run the [`cf-regro-autotick-bot`](https://justcalamari.github.io/jekyll/update/2018/06/11/introduction.html) which monitors pypi for new versions published. When it notices a new version published it automatically opens a PR in the feedstock repo. 

As a maintainer you'll get a GitHub notification of a new PR, and if everything is in order you can simply hit the green merge button.

The bot doesn't update dependencies though so the job of a maintainer is to check that no dependencies have changed for the new version and if they have to update the `meta.yaml` appropriately before merging.

**Comment by cicdw** [comment]
Ah ok cool, and then PR merges into the feedstock repo trigger auto-deploys to the `conda-forge` channel I suppose?

 💯 thank you!

**Comment by dhirschfeld** [comment]
Yep - the CI automatically uploads to `conda-forge`. It's a pretty amazing infrastructure they've set up!

https://anaconda.org/conda-forge/prefect/files
