### ISSUE TITLE
Parameters tab of flow run page uses dark mode highlighting in light mode

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#8352]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The parameters tab of flow run page uses dark mode highlighting in light mode

![image](https://user-images.githubusercontent.com/26799928/216118028-fbc4445d-2a46-40c5-ac50-b6156406e73e.png)

### Reproduction

```python3
Run a flow with parameters, navigate to that flow run page's parameters tab
```

### Error

```python3
![image](https://user-images.githubusercontent.com/26799928/216118028-fbc4445d-2a46-40c5-ac50-b6156406e73e.png)
```

### Versions

```Text
Cloud
```

### Additional context

Thanks!

**Comment by zhen0** [comment]
Thanks! Should be fixed in the latest release.
