### ISSUE TITLE
Prefect 2 "EXTRA_PIP_PACKAGES" on Docker Blocks 

### ISSUE THREAD

**Issue by jasonnoxon** [PrefectHQ/prefect#8356]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, in order to have python packages installed into a docker block, the user enters the following into the "environment" area:

{ 
    "EXTRA_PIP_PACKAGES": "package1, package2==1.0.0, package3"
}

### Describe the proposed behavior

It would be cleaner if EXTRA_PIP_PACKAGES accepted a string for a single package, and an array if there are multiple packages. For example:

{ 
    "EXTRA_PIP_PACKAGES": package2==1.0.0"
}

{ 
    "EXTRA_PIP_PACKAGES": ["package1", "package2==1.0.0", "package3"]
}

### Example Use

This would be used in a Docker Block on the server (Orion).

### Additional context

The only thing this would really do (which is important) is clean up the UI. When the user has a long list of packages to be installed, as we do, the list stretches out the UI.

**Comment by madkinsz** [comment]
Hey @jasonnoxon — `EXTRA_PIP_PACKAGES` is not something we came up with so I'm hesitant to change it from the standard. The implementation is also very simple right now:

https://github.com/PrefectHQ/prefect/blob/main/scripts/entrypoint.sh#L12
