### ISSUE TITLE
Update header fonts in docs

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#837]
- On https://docs.prefect.io, the subtitle and buttons:
![image](https://user-images.githubusercontent.com/153965/54917041-48eaf580-4ed1-11e9-97a5-4965a0bf5dd9.png)

- And on https://docs.prefect.io/guide/ the block quote:
![image](https://user-images.githubusercontent.com/153965/54917068-57d1a800-4ed1-11e9-8b5d-b75c5f717a50.png)

**Comment by lauralorenz** [comment]
Closing this -- reopen with the specific way you want them to be updated if this is still necessary.
