### ISSUE TITLE
Make tags clickable to add to filter on deployments page

### ISSUE THREAD

**Issue by corris** [PrefectHQ/prefect#8412]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

On the deployments page, the tags next to each deployment look like clickable buttons but they sadly are not.  When you click on them nothing happens.

### Describe the proposed behavior

When you click on a tag, it should add that tag to the list of tags filtered on that page ( and load/filter the page immediately, as if you had added that tag name to the tag field in the upper right corner ).

### Example Use

if I'm looking at the deployments page, I want to quickly see all the other deployments that are related to the one I'm looking at.  it would be easiest to just click on the tag and boom.    Right now, it takes too much effort ( I know, first world problem ) to click in the tag field and type out the name.

**Comment by zhen0** [comment]
Thanks @corris!

**Comment by zhen0** [comment]
@billpalombi - this looks simple but would be complex from a UI perspective.  Any views on whether we should do this?

**Comment by billpalombi** [comment]
Thank you for this submission @corris. We would like make the tags clickable at some point, but instead of having each tag apply a filter to the list when clicked, we may link to a central view of all objects with that tag (deployments, tasks, etc.). We'll update you once we've done that.

**Comment by corris** [comment]
That works too!
