### ISSUE TITLE
Psycopg2 timeout does not kill the prefect task 

### ISSUE THREAD

**Issue by ytl-liva** [PrefectHQ/prefect#8432]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Added 
```cur.execute("SET statement_timeout = '45min';")``` 
to psycopg2 running in a prefect task writing to postgresdb.

The timeout did not work and the task just continue to run without any errors or terminating

### Reproduction

Code snippets as follow:
We have a list of sql queries that is read and fed into the function where they create new tables

```python3
def task_name:
  conn = psycopg2.connect()
      cur = conn.cursor()
      for path, query in queries:
          logger.info(f"Applying query {path} on {dbname}")
          cur.execute("SET statement_timeout = '45min';")
          cur.execute(f"SET ROLE '{dbrole}';")
          cur.execute(query)
          conn.commit()
      cur.close()
      conn.close()
```

multiple flows likely running on the same table that is trying to be selected

one of the query actually run over 45 mins and never stops and just lingering in the task until it is killed manually.

checking `pg_stat_activity` does not show any query running at all.

### Versions

prefect-agent:

Kernel Version: 5.15.0-1028-aws
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64

python-versions = "~3.9"
psycopg2-binary (2.9.5)
prefect (0.15.13)

the backend is running on prefect cloud

**Comment by peytonrunyan** [comment]
Hi there! Thanks for submitting the issue. Are you certain that the hanging is only happening with the prefect flow? I can't think of a way that we would be suppressing an error. Is there a chance you try setting a much shorter timeout (like 1 second) to confirm that a timeout is definitely occurring, and try running it both in a script and a flow to confirm that the behavior is different within Prefect?

**Comment by peytonrunyan** [comment]
An executing task is not being run on or by Prefect Cloud. Prefect Cloud just orchestrates it. The task itself is just code being executed wherever you've designated it to execute. If your task will fail correctly in response to a psycopg2 timeout in development, then that same task will fail under the same error conditions when using Prefect Cloud. 

The sounds like psycopg2 is hanging for reasons that our out of our control. It looks like there are several situations that can cause this e.g. https://github.com/psycopg/psycopg2/issues/944 . It's probably worth digging into the open issues to see if something else is prevent psycopg2 from properly timing out.

I probably won't be able to provide any additional assistance without an MRE at this point.

**Comment by taljaards** [comment]
I believe this is fixed by https://github.com/PrefectHQ/prefect/pull/8425#issuecomment-1425995162?

https://prefect-community.slack.com/archives/CL09KU1K7/p1676051970044899?thread_ts=1675449149.527989&cid=CL09KU1K7:
![image](https://user-images.githubusercontent.com/6089256/218396621-cf6cd253-790c-44c4-a6bd-2bc96f591fcc.png)

**Comment by ytl-liva** [comment]
https://prefect-community.slack.com/archives/CL09KU1K7/p1675449149527989 slack discussion
#8425 pr

**Comment by madkinsz** [comment]
We've fixed that in Cloud now.
