### ISSUE TITLE
Ability to pause task runs, similar to 1.0

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#8442]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently tasks are unable to be paused and flows cannot be paused from within a task.

### Describe the proposed behavior

The proposed behavior would be that a task could be moved to a Paused state using a pause_task_run function.  There would be a similar 'reschedule' argument as there is with pause_flow_run.  When the flow has finished all available task runs that aren't downstream of the paused task, infrastructure spins down (assuming reschedule=True).

When the task is resumed infrastructure spins up and flow execution continues.  Since the paused task never reached a terminal state (it was paused) and no result was produced, the task that was paused is re-run when resumed.

Flow remains in a Running state for the duration of the process.

This is all similar behavior to 1.0.

### Additional context

In 1.0 a task could be paused by using ``raise PAUSE`` but so far in 2.0 only flows can be paused.   Also a flow cannot be paused from within a task, only from within the code of a flow.  We have dozens of flows in 1.0 that utilize task pausing and its our single biggest hurdle in migrating to 2.0.  In 1.0 we could pause a task and then the flow remains in a running state but infrastructure (ECS Tasks in our case) deprovisioned when there were no tasks left to run and then provisioned a new task upon the task being resumed.  If we could match this use case in 2.0 it would make for a much smoother transition.

For context we have flows in 1.0 that have multiple tasks that call pauses.  Reducing the pause to the task level rather than just the flow level is helpful to us to determine on which task the flow was on when it paused...  i.e. was this the pause on task 1 or the pause on task 2.  In 2.0 if pausing is only at the flow level we need to employ some logic by looking at the states of all the tasks in the flow to try to triangulate where the pause occurred.

We also found the pausing of tasks useful in long running processes that were reliant on some piece of data coming from a remote source.  For example we had a flow that would submit a request to an outside service that would generate a file and then save it to an s3 bucket.  Sometimes that would be minutes, sometimes hours.  What we developed in 1.0 was a task that checked if the file was present, and if it wasn't it would pause.  We then had another flow that would run on an interval and unpause the first flow's task (and other flows within a similar structure) and it would check for the file again.  This would continue until the file was found or a timeout defined in the task was hit which would raise an exception and move the task to a failed state.

It was a great solution for us as it meant that compute wasn't running for the entire time we were waiting for the file, which could be several hours.  From an engineering standpoint its easy to suggest that this should just be two flows, one to request the file and the second triggered by the object being created in the bucket, but for various business purposes it was important to have this tied as a single flow so we could view the process from end to end in a single place, which is really the value proposition that brought us to Prefect in the first place.

**Comment by madkinsz** [comment]
Thanks for the thorough explanation of your use case. I'm not sure how challenging this would be from an implementation standpoint, but my gut says it's a big addition with much more complexity than pausing a flow. @anticorrelator is best suited to weigh in on that. 

I think it's likely to be quite a bit more complicated since task runs can be executing on remote infrastructure where their PAUSE signal may not propagate to the flow. This may not be how you're using tasks, but delivering a feature that only works for local execution of tasks is not ideal since it'll be confusing to our other users. Perhaps we could mitigate this by transitioning the flow into a PAUSED state at the same time as the task. It'd then abort execution or pause at the next task call.

**Comment by kielosz** [comment]
We had a similar use case described here https://github.com/PrefectHQ/prefect/issues/7989 and this is also something we have been struggling with in Orion. In our case pausing tasks in Prefect v1 enabled us to easily wait for some external conditions to be met before continuing the flow (e.g. JIRA ticket is resolved). The ability to not to block the infrastructure was important here as those flows could last for days in our case.

**Comment by jbnitorum** [comment]
@madkinsz I don't see an issue with moving the flow to a paused state when a task pauses.  I only mention the running state while tasks are paused because that is the behavior in 1.0.  I do think that its important to note though that the flow moves to pause AFTER all tasks that have begun execution have entered either a terminal or paused state.  There may be tasks running concurrently and a pause in one should interrupt execution of another.

I agree on the local/remote aspect.  Honestly we are similar to @kielosz in that we have many long running flows and for that reason remote infrastructure spinning up/down is really crucial.  Glad to see I'm not the only one struggling with this change in v2.  I understand that its a logistically complex issue but it really puts some of us using v1 in a tough spot when it comes to migration as there isn't full parity around features like this.

**Comment by anticorrelator** [comment]
Hi @jbnitorum out-of-process pausing, I believe, is *already possible* from within task runs—we can call the out-of-process pause utility from anywhere. This might suit your use case better too, as infrastructure will stop running using this method

**Comment by jbnitorum** [comment]
@anticorrelator 

This flow below returns the error: RuntimeError: Pausing a flow run out of process requires the `reschedule` option set to True.

This is obviously illogical.  I had discussed with @EmilRex and the response we eventually got to was that pausing is not supported within tasks.  Interestingly enough I tried removing the argument and then it seems to work.  I hadn't done that before.  Unfortunately, I can't test this to completion because of [this](https://github.com/PrefectHQ/prefect-aws/issues/206) issue that remains unresolved.

It appears that it calls for the pause on the flow and then the task which called the pause continues running until complete.  We need the task to rerun when resumed (persist_result=False) but we have found we get errors resuming flows where results were not persisted.  This is on another post [here](https://github.com/PrefectHQ/prefect/issues/8360) but the crux of the question keeps getting side-stepped.

Hacking around this a bit if I resume the flow before the time.sleep(30) finishes (before the infrastructure spins down) so that I avoid the 'Crashed' state above then I get this error:

MissingResult: State data is missing. Typically, this occurs when result persistence is disabled and the state has been retrieved from the API.

This is what I am asking for on the [other](https://github.com/PrefectHQ/prefect/issues/8360) thread.  Make it possible for this to be resumed and the tasks without persisted tasks results rerun.  Perhaps a different way to ask the same question... can I manually have a task set itself to 'pending' upon completion?  Something that would make it run again.

At the end of the day we are just trying to get to a similar result to what we are doing in 1.0 without reinventing the wheel around how we use Prefect.


```python
from prefect import get_run_logger
from prefect import flow, task, pause_flow_run
from prefect.context import get_run_context
from datetime import datetime
import time

@task()
def some_taska(persist_result = True):
    logger = get_run_logger()
    logger.info('task a')
    return None


@task
def pause_task(persist_result = False):
    logger = get_run_logger()
    logger.info('Lets pause if its after 12pm')
    hour = int(datetime.now().strftime("%H"))
    logger.info(f'hour is: {str(hour)}')
    if hour>12:
        task_context = get_run_context()
        pause_flow_run(flow_run_id=task_context.task_run.flow_run_id, reschedule=True)
    time.sleep(30)
    logger.info('This prints after pause')
    return None


@task
def some_taskb(persist_result = True):
    logger = get_run_logger()
    logger.info('task b')
    return None

@flow
def test_pause_flow(name='Pause flow', result_storage='s3/prefect-results'):

    task_a = some_taska()
    pause_result = pause_task(wait_for=[task_a])
    some_taskb(wait_for=[pause_result])

```

**Comment by kielosz** [comment]
> The key difference between the pause of task and pause of the flow is that in pause of the task you don't get a task result so the task re-runs after the pause.

Totally agree. Again this is exactly what I mentioned in https://github.com/PrefectHQ/prefect/issues/7989. We tried this code as a workaround for this:
```
    while True:
        ready = isReady()
        if not ready:
            pause_flow_run(reschedule=True)
        else:
            break
```
In this case we create a new task run of `isReady` task  whenever we resume the flow. It works, but the proper mechanism of pausing and rerunning tasks would be more handy.

**Comment by kielosz** [comment]
> @kielosz May I ask why an arbitrary number of pause cycles are required? This implies to me a flow might be resumed before it is ready, only for the check to put it back in the paused state. I think we'll get a much more powerful way to express this idea soon with pause/resumes via automation. Events triggering a resume action can be powered in many more flexible ways without the need for a "polling" style pause.

Sorry for the delayed response. The sample flow scenario is super simple here: a flow creates a Pull Request, then waits for it to be Closed, then does action X (e.g. Slack user). Because it can takes minutes/hours/days before the PR is closed, we want the flow to pause and do not block the infrastructure. These are the functional requirements.
In Prefect v1 it could be achieved easily by having three tasks: A (create PR) -> B (check status of the PR, if not Closed then raise PAUSE state with`start_time` param and wake up in the future) -> C (do action X). The code was clean, simple and super easy to understand.
Switching to Orion, I know we can try to achieve the same functionality using the snippet I posted in my previous comments. But the problem is this is not clean, nor simple, and it requires to put the pause/resume logic in the main flow, what is not acceptable from the composability point of view. I am also not convinced that it should be done using any other concepts like 'automations'. The ability to wait for an external factor to happen (long-pulling: pausing and resuming) is a simple concept that lies within the flow logic and flow code. It should not require any other entities, components to be set up or configured.

**Comment by jbnitorum** [comment]
> 

I agree with all of this.  We have found work arounds to adjust our flows to 2 by putting pause logic inside the flow code (not in tasks) its not quite as elegant and simple as in 1.  I get that automations and events will make for some powerful and dynamic integrations but in the case of this above its a little overkill to have so many pieces and entities to configure to achieve something simple.

The polling pause task (if condition met complete, if condition not met pause and allow for rerunning) is also a little more robust as the triggering mechanism for the unpause may not be the same as the condition being met to complete the task.  If someone or something unpauses by mistake before the condition is met no harm no foul.  Excess triggering of an unpause has no consequence.

In the automation/event scenario the condition that allows the task to finish essentially has to be the same set of conditions that trigger the unpause.  If the condition triggering the unpause is met but the condition allowing the task to complete is not then the task likely fails or behaves unexpectedly.
