### ISSUE TITLE
Hierarchical work queues

### ISSUE THREAD

**Issue by goaaron** [PrefectHQ/prefect#8455]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Work queues can be set with a concurrency limit on all flows running in the queue.

In addition, (with the existence of the new custom [templated flows](https://discourse.prefect.io/t/prefect-2-7-12-is-out-with-custom-templatable-flow-and-task-run-names/2357)) it would be great to be able to impose concurrency limits on all flows in a queue matching a **pattern**.

### Describe the proposed behavior

Queue A has a concurrency limit of 5 (max 5 running flows at a time).

I submit templated flows to queue A with some ****prefix**/tag.**

I want to impose a secondary limit that all flows in the queue with a matching ****prefix**/tag** have a concurrency limit of 1. 

In this way, for a specific subset of flows, I may submit multiple to the work queue, but all flows with the same prefix must wait until others with their prefix enter a completion state.

### Example Use

Optionally add some additional concurrency limit on flows with matching tags/prefix.
These are dynamic.

### Additional context
https://github.com/PrefectHQ/prefect/pull/7099
Addressed this issue for the **per-deployment** issue.

This problem is basically at the level of **per-flow-with-some-parameter-inputs in a deployment**

It's not clear to me how to do this dynamically outside of modifying the work queue. 

You'd have to create new queues on the fly for a given flow_run and subscribe to them with agents. 

1. Something like wrapping the invocation of a flow in another flow that calls `create_flow_run_from_deployment`, 
2. Creating a work queue of concurrency 1 for flows matching the given pattern
3. Overriding the flow's deployment work-queue, 
4. Submits the flow. 

This would require cleanup after and the agents would have to be dynamically listening to queues matching a pattern (possible)

This capability exonerates the need for that.

**Comment by zhen0** [comment]
I believe the new global concurrency limits should solve this use case so am closing this issue.  If you have feedback or still want to advocate for this feature, please feel free to re-open or open a new issues.
