### ISSUE TITLE
get error when doing pip install on windows 10

### ISSUE THREAD

**Issue by dannyb2018** [PrefectHQ/prefect#847]
running windows 10, anaconda python 3.6.5 and do pip install prefect, i get an error message 

> Collecting pendulum<3.0,>=2.0.4 (from prefect)
>   Using cached https://files.pythonhosted.org/packages/5b/57/71fc910edcd937b72aa0ef51c8f5734fbd8c011fa1480fce881433847ec8/pendulum-2.0.4.tar.gz
>   Installing build dependencies ... error
>   Complete output from command c:\ana3\python.exe c:\ana3\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\Danny\AppData\Local\Temp\pip-build-env-9ret197s\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- poetry>=0.12:
>   Traceback (most recent call last):
>     File "c:\ana3\lib\runpy.py", line 193, in _run_module_as_main
>       "__main__", mod_spec)
>     File "c:\ana3\lib\runpy.py", line 85, in _run_code
>       exec(code, run_globals)
>     File "c:\ana3\lib\site-packages\pip\__main__.py", line 16, in <module>
>       from pip._internal import main as _main  # isort:skip # noqa
>     File "c:\ana3\lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
>       import locale
>     File "c:\ana3\lib\locale.py", line 16, in <module>
>       import re
>     File "c:\ana3\lib\re.py", line 142, in <module>
>       class RegexFlag(enum.IntFlag):
>   AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by joshmeek** [comment]
Do you by any chance have the package `enum34` installed? It has compatibility issues with Python 3.6 and it looks like you are having this issue raised in the standard library's `re` package.

Here's a stack overthrow thread I found on this issue: https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by dannyb2018** [comment]
That fixed it.. ironically airflow is what installed enum34!
