### ISSUE TITLE
Complex optional parameters are not treated as optional for custom runs

### ISSUE THREAD

**Issue by knl** [PrefectHQ/prefect#8479]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Sometimes I need to pass complex parameters to flows. I noticed that if I try a custom run, where initially one of the optional complex parameters was None, I am forced to enter the parameter. There is simply no way to select it as None.

### Reproduction

Run the following code:

```py
from typing import Any, Dict, List, Optional, Pattern, Union

from prefect import flow
from prefect.deployments import Deployment
from prefect.logging import get_run_logger
from pydantic import AnyHttpUrl, BaseModel


class Reporter(BaseModel):
    endpoint: AnyHttpUrl
    name: str
    category: str = "Bug"
    source: Optional[AnyHttpUrl] = None
    alert_regex: Optional[Pattern] = None
    alert_text: str = "Alert!"
    override_existing: bool = True


@flow
def prefect_demo_bad_optionals(
    name: str,
    notebook_url: AnyHttpUrl,
    parameters: Optional[Dict[str, Any]] = None,
    email_to: Union[List[str], str, None] = None,
    reporter: Optional[Reporter] = None,
):
    logger = get_run_logger()
    logger.info(f"Executing with parameters {parameters}")

    if email_to:
        logger.info(f"Will now send an email to {email_to}")

    if reporter is not None:
        logger.info(f"Will report execution to the reporter {reporter}")


Deployment.build_from_flow(
    flow=prefect_demo_bad_optionals,
    parameters={
        "notebook_url": "http://localhost/foo/bar.ipynb",
        "parameters": {"date": "today"},  # what we pass to the notebook
        "email_to": "alert@example.com",
        "reporter": None,
    },
    name="demo run",
    version=1,
    work_queue_name="amsperformance",
    tags=["demo"],
    skip_upload=True,
    apply=True,
)
```

Select the deployment in the UI, then "Run", then "Custom Run". At the bottom of the page, under "Parameters" click on "Custom". Click on "Run".

I would expect to be able to run the flow. Instead, I am forced to enter the values for reporter fields, even though this parameter is marked as `Optional`.

### Error

![Screen Shot 2023-02-10 at 12 58 31](https://user-images.githubusercontent.com/361496/218087140-065f5e7f-319c-4413-a292-6a886bf1c546.png)

### Browers

- [ ] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.7.8
API version:         0.8.4
Python version:      3.9.16
Git commit:          75d2e146
Built:               Thu, Jan 12, 2023 1:41 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         hosted
```

**Comment by zhen0** [comment]
I believe this should be fixed by https://github.com/PrefectHQ/prefect-ui-library/pull/1130.  Would you mind updating and seeing if this is still an issue @knl?

**Comment by knl** [comment]
> I believe this should be fixed by [PrefectHQ/prefect-ui-library#1130](https://github.com/PrefectHQ/prefect-ui-library/pull/1130). Would you mind updating and seeing if this is still an issue @knl?

Hi @zhen0 I would gladly update, but I don't know how. I tried `pip install -U prefect` which updated me to 2.8.0. However, I still see the problem there. Should I update `prefect-ui-library`? If so, how does one do that?

**Comment by zhen0** [comment]
My apologies @knl - I can see that your issue comes from nested parameter inputs and can reproduce your issue. I can add to the backlog.  In the meantime, I wonder if you could make name and endpoint optional?  (Though I am guessing that you've already considered that option.)

**Comment by pleek91** [comment]
@knl looked into this today cause it sounded familiar and I can no longer reproduce. Using your reproduction flow/deployment I'm able to run the deployment without populating the reporter parameter. 


![Image](https://github.com/PrefectHQ/prefect/assets/6200442/4e24c6aa-bda3-4c46-b716-b83894bd6aee)

Please let me know if you're still having issues.
