### ISSUE TITLE
Setting Flow Concurrency

### ISSUE THREAD

**Issue by ismailcenik** [PrefectHQ/prefect#8508]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

There is no feature to set the flow concurrency. Task level and queue level concurrency are not efficient/scalable/desirable. 

### Describe the proposed behavior

There should be a screen to set flow concurrency like in Prefect v1. The developers should be able to set flow concurrency via tagging. 

Task level concurrency is a good enhancement in Prefect v2 but clients need also flow level concurrency. 

### Example Use

Assume there is a data loading project which uses AWS Kinesis Data Analytics (KDA) for hosting data loading jobs. A KDA cannot be run by multiple clients, so it must run one at a time. Our flow simply starts KDA, checks the job status, and finally stops KDA. If there is another data loading request and tries to start the flow, the flow concurrency should not allow to run the flow while there is a running flow. The second request must be put into a queue, so when the existing run finishes, the flow will be run for the second request.

**Comment by jmg-duarte** [comment]
As a _workaround_, what I've done in the project I'm working on is creating a queue per flow and then set the concurrency at the queue level.

**Comment by billpalombi** [comment]
Thanks for submitting this issue @ismailcenik.

We recommend using [work queue concurrency limits](https://docs.prefect.io/concepts/work-pools/#work-queues) to achieve the desired behavior. In the case of your example use, you can create a work queue for AWS Kinesis Data Analytics and submit all flow runs that need a KDA client to it.

**Comment by ismailcenik** [comment]
Thank you for the recommendation. I put the description "Task level and queue level concurrency are not efficient/scalable/desirable." because we have many jobs and KDAs. That's why we try to get the v1 feature.
