### ISSUE TITLE
Setting deployment custom parameters in UI not correctly parsed when flow param type hint uses `Union`

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#8519]
### Discussed in https://github.com/PrefectHQ/prefect/discussions/8342

<div type='discussions-op-text'>

<sup>Originally posted by **Wingmore** February  1, 2023</sup>
I cant enter lists/array into the Orion UI Custom Parameters of deployments. Get an error if I try:

```
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - capsule_ids: value is not a valid integer
 - capsule_ids: value is not a valid list
```

**Comment by pleek91** [comment]
This works as expected in the new enhanced deployment parameters ui. Using the MRE from the discussion I get the following form

<img width="744" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/fc2b5599-f10e-4277-a55a-d502dc7c9098">

I'm also able to enter lists of numbers via the form
<img width="752" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/dda8a946-51b1-464b-8d83-ab9592e4944e">

And via json
<img width="749" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/6c3d7c03-7354-4d28-8528-650102946e8f">

I was able to submit a run for all 3 different examples and saw the correct parameters passed when running the flow.
