### ISSUE TITLE
Create Docker Tasks for Task Library

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#852]
Add initial tasks to the task library relating to Docker.

- Containers: create, kill, logs, exec
- Images: list, pull, push, remove, tag, build

Any other tasks are more than welcome. These are just the initial ones I feel are most important / commonly used

**Comment by cicdw** [comment]
You'll need to test that these work when executed from _within_ a docker container for deployment purposes.

**Comment by joshmeek** [comment]
Ultimately I think that falls onto the user and the image they provide during deployment. While it is definitely possible to run a container which these tasks can point to something like `unix:///var/run/docker.sock` on, I feel as if it is not on the responsibility of the engine to make sure it can handle running inside of an image. All we can do for assurance (without testing every docker image) is provide users with a way of specifying the location of the docker server and make sure they are aware of the steps involved in running Docker in Docker. The low level API can even point to a `tcp` address so it can (for example) be running on the same cluster somewhere else.

**Comment by ma7dfa7d** [comment]
https://github.com/PrefectHQ/prefect/issues/859#issuecomment-477398113
