### ISSUE TITLE
Unable to create notifications after database reset

### ISSUE THREAD

**Issue by MartinDupont** [PrefectHQ/prefect#8536]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

We have a prefect orion server running. Initially I was able to successfully configure a webhook to send a slack message if a flow run failed. 

Our prefect server was having some very strange issues, in that every flow run seemed to get stuck for no reason. So I decided to simply wipe the database and restart it using
`prefect orion database reset -y`

After that, I redeployed all of our flows and they started running again. However, upon trying to recreate the slack notifications, I found that the UI is broken. 

It doesn't look like it does in the [guide](https://docs.prefect.io/ui/notifications/). I can only select run states and tags, but there is no option to select which service to use (slack, email, microsoft etc.) There is simply a greyed-out textbox with the title 'Review your notification', that I can't type anything into. 

### Reproduction

Install a prefect server, create a slack notification, run `prefect orion database reset -y`, then try to create a notification via the orion UI.

### Error

<img width="1512" alt="Screen Shot 2023-02-15 at 10 53 09 am" src="https://user-images.githubusercontent.com/36166749/219080280-22b91d76-54c3-424e-aff4-5bcaebf80c09.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.7.1
API version:         0.8.3
Python version:      3.10.8
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

### Additional context

I would also be happy if somebody pointed me to a way that I could create a notification with a webhook via the CLI or an API call. I searched the docs but didnt find anything

**Comment by zhen0** [comment]
Hi @MartinDupont - sorry to hear you're having issues.  It looks as though somehow your blocks have been removed as that page should show notification options. I reset my database to check if this is an issue I can replicate and I can't.  If you're able to re-intsall prefect that may help, otherwise you may be able to get some help in the community slack.

**Comment by MartinDupont** [comment]
What do blocks have to do with notifications? I didn't have to create a block the first time I created a notification. 

Is there a resource that tells me what blocks should be in the DB or how I could configure them? I'd rather not reinstall prefect again as it is currently running production jobs and I don't want more downtime.l
