### ISSUE TITLE
Show cached tasks on timeline

### ISSUE THREAD

**Issue by carlosjourdan** [PrefectHQ/prefect#8537]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, when a task is finished with state Cached(type=COMPLETED), it doesn`t get displayed on the timeline.

### Describe the proposed behavior

It would be helpful to see cached task runs on the timeline, maybe in a different color.

**Comment by zhen0** [comment]
@brandonreid @WillRaphaelson - this is a request that came up at PACC

**Comment by sakce** [comment]
FWIW works in Cloud, but not locally :))

**Comment by cicdw** [comment]
We currently display the state name `Cached` on inspection of any state within the timeline; going to close this as complete but if I'm misunderstanding the request feel free to chime in.
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/2ba7046a-78ad-49db-95ec-d6435588c46a">
