### ISSUE TITLE
UI - date filters do not work on mobile (iOS) 

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#8540]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The date filters on the flow run page do not work on iphone. (Not checked on other mobile).  The week filter set my saved filters can still be applied. 

### Reproduction

```python3
Use date filters on mobile.
```

### Versions

```Text
Cloud
```

**Comment by pleek91** [comment]
@zhen0 i can reproduce this. I was able to filter my flow runs on my iOS device. 

![image](https://github.com/PrefectHQ/prefect/assets/6200442/1b765e11-2a3d-45f5-b735-ac0398ea6abf)
