### ISSUE TITLE
Runs tab inside the Flows screen is very slow to load

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8549]
### First check

- [x] I added a descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi,
Then navigating to the Runs tab inside the Flows screen, it take around 1 minute, and sometimes several page refreshes to get something to show:

![CleanShot 2023-02-16 at 11 32 00](https://user-images.githubusercontent.com/5398977/219330073-94f7c017-b294-4766-83de-7ddf8e6d3e29.gif)

### Reproduction

```python3
I assume that in order to reproduce the issue you need to have around 4000 runs. Maybe that is what is causing the problem.
```

### Versions

```Text
prefect cloud
```

**Comment by zhen0** [comment]
Thanks for the issue @yaronlevi. I've tried hard to replicate this but the maximum load time I'm seeing is way below your minute. The api returns a max of 200 runs (and we load more if you scroll or filter) so I don't think the 4000 run count should affect things. 

Would you be able to provide any more details? 

https://user-images.githubusercontent.com/40272060/219485008-c769b978-498b-49ef-9e98-99243af3bb55.mov

**Comment by yaronlevi** [comment]
Sure, I can see that we get a 503 on the count and filter routes:

![CleanShot 2023-02-17 at 12 23 15](https://user-images.githubusercontent.com/5398977/219618691-e03b72b7-d805-49a7-b29b-8ff62b628fef.gif)

**Comment by zhen0** [comment]
A ha!  Thanks @yaronlevi - then the 4000 runs is affecting things.  Thank you for that extra detail.

**Comment by zhen0** [comment]
For info, we're looking into this.

**Comment by jakekaplan** [comment]
@yaronlevi we deployed some changes that should help. Could you give it another look and let us know if you still see any 503s?

**Comment by yaronlevi** [comment]
@jakekaplan @zhen0 YES! The issue is solved 🙂
