### ISSUE TITLE
"wait_for" dependencies between tasks not being shown on timeline 

### ISSUE THREAD

**Issue by carlosjourdan** [PrefectHQ/prefect#8551]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If a task has a wait_for parameter set to make sure it runs after a previous task is finished, the bars for the tasks on the timeline view are not connected

### Describe the proposed behavior

There should be a line connecting the upstream tasks to the task that has the wait_for parameter. Maybe a different line style could be used to differentiate traditional input/output dependencies from wait_for dependencies.

**Comment by madkinsz** [comment]
@brandonreid I presume this is resolved now?

**Comment by batuhanfaik** [comment]
No, I don't think it has been resolved. A flow with subflows/tasks do not draw the dependency arrows between subflows/tasks unless a 'dummy' return value is used.
