### ISSUE TITLE
Default .prefectignore should include .git/

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#8561]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deployments can take a while - my case the reason was that prefect was pushing all the files in the .git folder to S3

### Reproduction

```python3
add to the default .prefectignore
# git folder
.git/
```
Push is much faster

### Versions

```Text
Version:             2.7.9
API version:         0.8.4
Python version:      3.10.4
Git commit:          42b80f18
Built:               Thu, Jan 19, 2023 4:59 PM
OS/Arch:             darwin/arm64
Profile:             ocell
Server type:         cloud
```

**Comment by seanpwlms** [comment]
It looks like this might have already been addressed, [here](https://github.com/PrefectHQ/prefect/commit/57e0082684fe339e19ad91e733bd6a63fe02cf91).

**Comment by madkinsz** [comment]
Thanks @seanpwlms !
