### ISSUE TITLE
Azure credential block requires tenant ID and Client Secret

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect#8567]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Referencing this issue [here](https://github.com/PrefectHQ/prefect-azure/issues/68). As per release 0.2.4, the Azure Container Instance Credentials block is supposed to use the `DefaultAzureCredential` if any of the client id, tenant id, and client secret are left empty, but Tenant ID and Client Secret are required fields when attempting to create the credentials block in the UI. The Azure Container Instance Job still requires the credentials block, but I cannot create the credentials block without directly passing in creds
![image](https://user-images.githubusercontent.com/69161193/219506467-df507f06-b8aa-45cc-90a2-b2e6a6003bd8.png)

### Reproduction

Attempt to create a Azure container instance credentials block without passing in credentials so that the Azure container instance job will use the default creds

### Error

`Tenant ID is required` `Client Secret is required`

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

**Comment by ahuang11** [comment]
Thanks for reporting. Have you tried re-registering the prefect-azure blocks?
`prefect block register -m prefect_azure`
I was able to create a credentials block without specifying tenant ID and client secret
![image](https://user-images.githubusercontent.com/15331990/219512186-33424838-e717-4e4d-b83b-4c6609b61d22.png)

**Comment by Bada-S** [comment]
Thanks for getting back to me @ahuang11 so quickly. In hindsight I should have tried this first. I'm going to close this issue

**Comment by ahuang11** [comment]
No problem!

**Comment by ahuang11** [comment]
On second thought, perhaps we should highlight this somewhere (maybe display the version) and mention somewhere re-registering blocks on update.
