### ISSUE TITLE
Difficulties submitting 3700 tasks in one go

### ISSUE THREAD

**Issue by david-elliott-deliveroo** [PrefectHQ/prefect#8579]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

TL;DR: We can't loop over a DAG and submit all the tasks in one go. The only way that it seems to work is to add time.sleep() between each task submission, and we want to know a) why that's the case and b) if that's a legit solution, or if there's a better / more "Prefect" way to do this 🙂 

-------

MRE: [prefect2-task-submission-MRE.zip](https://github.com/PrefectHQ/prefect/files/10769370/prefect2-task-submission-MRE.zip)

We have a pre-defined static DAG of 3700 tasks, whose dependencies we know in advance of running a flow. We struggle to submit all of these tasks in one go (sync or async) at the start of a Flow run, and would like to understand what errors we're hitting, and what the right solution / workaround might look like. We'd like to have confidence that whatever solution is reliable / robust, given this is a critically important production flow for us.

### Submitting Synchronously 
We'd like to be able to submit the 3700 tasks in a synchronous flow if possible. They are submitted using `.submit()` and the flow run is executed with the `DaskTaskRunner()` (running 4x ephemeral Dask Workers on k8s).

**Observed behaviour**

Please see the attached MRE file for more specifics, but essentially when looping over the DAG and calling `task.submit()` on each task, if there's no `time.sleep()` between task submissions, the flow gets to around ~600-700 task runs submitted and just stops submitting tasks. I suspect it might be a thread lock issue under the hood, but no idea how to confirm or debug if this is the case...? Or indeed what the right solution / workaround might be if this is the issue?

If we add a time.sleep() after each `task.submit()`, we can usually get all the tasks to submit (over the course of a few minutes). From trial & error, the sleep needs to be at least around `0.04`s, though we've seen the same above error happen with `0.05` set as well - it doesn't seem to be totally deterministic. I'd love to understand what's happening to cause the task submissions to stop if there's no sleep between submissions, and why the sleep seems to work as a workaround (albeit not entirely reliably). And is the sleep the right solution, or should we be taking a different approach here?

Any help / guidance would be hugely appreciated!

### Context on what this flow is
The flow is a pre-defined, static DAG of 3700 SQL tasks. There is only one task function - it is a synchronous "run Snowflake SQL script" function, and the sql path is passed as the function argument. We basically want our flow to run this DAG in the pre-defined order.

### Submitting Async
Ideally we don't want to change the flow to async, as we'd need to change the SQL task and the snowflake connector to async, which is a tonne of rework. Either way, we tried mass-submission using async and hit what appears to be a 250 thread locking issue.

### Reproduction

```python3
"""
Please see attached zip file with MRE
Main file to run is python sync_dask_submission.py
The DAG of 3700 tasks is in dag_file.yml and is read to a dict on flow start.
""
```

### Versions

```Text
Version:             2.7.11
API version:         0.8.4
Python version:      3.8.7
Git commit:          6b27b476
Built:               Thu, Feb 2, 2023 7:22 PM
OS/Arch:             darwin/x86_64
Profile:             bi-p
Server type:         cloud
```

### Additional context

_(Side note - I also worry about staying under the Cloud API rate limit of 2k task submissions per minute, though I've yet to run into that issue given the above sleep required keeping it under 2k tasks submitted per minute)_

**Comment by david-elliott-deliveroo** [comment]
Update on this - even with a `time.sleep(0.06)`, it's still not reliable - sometimes we'll get all tasks submitted ok, other times it'll hang at some arbitrary number and we'll have to cancel and restart the run. 

It feels like it's probably something along the lines of 
- when task.submit() is called it submits async to the cloud API, and I suspect the 250 thread limit is in play here
- that process takes a couple of seconds (there's definitely latency there)
- if the cloud API latency is low, then the submission completes fairly quickly and releases a thread
- if the cloud API latency is high, submissions take longer, and we end up in a thread locked scenario

The above is just a theory but _feels_ like what's happening. I guess it could be avoided if there were a way to synchronously submit tasks, so as to wait for them to be submitted to the backend prior to moving onto the next one..? 

Note - we get the futures back, but we don't await them on task submission, we await them only once all the tasks have been submitted. I've seen instances where we get all the futures back from the submission loop, but there's only a subset of task runs actually created in the backend. I almost want to be able to await the creation of the task run prior to submitting the next task..?

**Comment by madkinsz** [comment]
I've been working on problems in this area for a few months now, it's very complicated but we're approaching some solutions.

> I almost want to be able to await the creation of the task run prior to submitting the next task..?

This is actually how it worked originally :D then people complained that the task runs were not being created fast enough so we moved task run creation to happen asynchronously.

**Comment by david-elliott-deliveroo** [comment]
Nice, thanks for the update! Do you reckon I'm likely hitting a thread lock issue? That's what it feels like, although it's not deterministic - I think due to the varying cloud response time. Is the time.sleep() a legit workaround in the interim, whilst you continue with the broader solutions? If yes I might just have to go conservative on the .sleep() to make it more reliable, eg `sleep(0.1)` or something

**Comment by haddon-korinek-ent** [comment]
If you're open to breaking up those 3.7k into sharded subflows, you can get some big speedups by making the parent flow initialize the dask cluster and then having the subflows use their own task runner objects initialized using the dask scheduler address of the parent.

**Comment by madkinsz** [comment]
@david-elliott-deliveroo Sorry I don't have a lot of insight into what issue you're encountering and what a good workaround is. It's probably better for me to focus on delivering a fundamental fix.

Want to give the #8702 a try?

**Comment by madkinsz** [comment]
I'm going to close this as it should be resolved my the latest release. Please let me know if you encounter issues.
