### ISSUE TITLE
flow.visualize() fails on windows

### ISSUE THREAD

**Issue by mblye** [PrefectHQ/prefect#858]
A simple flow.visualize() command fails when running on Windows.  Looks like it's due to the way that windows creates tempfiles (see this thread: https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file)

Traceback (most recent call last):
  File "C:\Dev\source\python\prefecttesting\dostuff.py", line 34, in <module>
    flow.visualize()
  File "C:\Dev\source\python\prefecttesting\venv\lib\site-packages\prefect\core\flow.py", line 1106, in visualize
    graph.render(tmp.name, view=True)
  File "C:\Dev\source\python\prefecttesting\venv\lib\site-packages\graphviz\files.py", line 183, in render
    filepath = self.save(filename, directory)
  File "C:\Dev\source\python\prefecttesting\venv\lib\site-packages\graphviz\files.py", line 155, in save
    with io.open(filepath, 'w', encoding=self.encoding) as fd:
PermissionError: [Errno 13] Permission denied: 'c:\\dev\\temp\\tmpn3cczj0a'

**Comment by cicdw** [comment]
Thanks for the issue and the helpful pointer @mblye ! 

It looks like `graphviz` is attempting to open the temporary file a _second_ time here: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L1105-L1106 and Windows doesn't like that. 

It should be possible to work around this by creating a temporary _directory_ and then using an arbitrary filename in the call to `graph.render` 👍

**Comment by cicdw** [comment]
@mblye would you be comfortable doing the following in a fresh environment?
```
git clone -b windows-viz https://github.com/PrefectHQ/prefect.git
pip install "./prefect[viz]"
```
and checking your visualization example? 

I don't currently have an easy way to test if my update works on windows.

**Comment by mblye** [comment]
Just stepped away, but I'll check it out tomorrow.

**Comment by mblye** [comment]
This looks good.  Works as expected.  TY for the quick turnaround.

**Comment by cicdw** [comment]
Awesome!  I'll PR it then.
