### ISSUE TITLE
Inheritance with Flows

### ISSUE THREAD

**Issue by camsmith** [PrefectHQ/prefect#8581]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Right now a prefect task/flow has to be a top level function

```
@task
def specific_thing_1():
    return 'a'

@task
def specific_thing_2():
    return 'b'

@flow
def do_it_all():
    return specific_thing_1() + specific_thing_2()
```

But let's say I want to write a hundred different scripts, all doing something with the exact same flow structure, but possibly with slight variations to their underlying tasks. I have to write the `do_it_all()` flow a hundred different times, even though it is the exact same in every case.

### Describe the proposed behavior

In a pythonic world, I would write
```
class GenericThingDoer(object):

    @task
    def specific_thing_1():
        return 'a'

    @task
    def specific_thing_2():
        return 'b'

    @task:
    def super_specific_thing():
        raise NotImplementedError("This must be changed for every flow")

    @flow
    def do_it_all():
        return a() + b() + super_specific_thing()
```
Then, in my specific flows, I would just have to override the specific method.
```
class SpecificThingDoer(GenericThingDoer):

    @task
    def super_specific_thing():
        return 'c'

class EvenMoreSpecificThingDoer(GenericThingDoer):

    @task
    def super_specific_thing():
        return 'cde'
```
This means I don't have to write the `do_it_all()` flow a hundred times, as it is the same it every scenario. 

**I understand that flows are functions and the way I have written this would not work because class methods and instance methods have state**. I do not necessarily need the state of the class to complete the method. I just want the _flow_ to be able to inherit its _definition_ from somewhere else, so that if I change the definition of the flow, I don't have to do it a hundred times, but rather one time. 

### Example Use

See above

### Additional context

Does this exist in any capacity? I saw [this issue](https://github.com/PrefectHQ/prefect/issues/5689) was essentially rejected for v1, but it seems like functionality other folks would want.

**Comment by madkinsz** [comment]
Why not something like

```python

class MyTasks:
    @task
    @staticmethod
    def specific_thing_1():
        return 'a'

    @task
    @staticmethod
    def specific_thing_2():
        return 'b'

@flow
def do_it_all(tasks: MyTasks):
    return tasks.specific_thing_1() + tasks.specific_thing_2()
    
do_it_all(tasks=MyTasks())


class MyOverrideTasks(MyTasks):
    @task
    @staticmethod
    def specific_thing_2():
        return 'b'
 
do_it_all(tasks=MyOverrideTasks())
```

**Comment by camsmith** [comment]
Am I understanding correctly that you have `do_it_all()` as a global method here? If so, I would still need to define it in each of my hundred scripts. This is basically what I am doing now, so it's ok if that's the best we can do with existing functionality. Just want to make sure I am not missing something that would allow me that extra bit of inheritance

**Comment by madkinsz** [comment]
You could just define it once and import it?

Maybe you're looking for something like this?

```
from prefect import flow, task

class MyTasks:
    @task
    @staticmethod
    def specific_thing_1():
        return 'a'

    @task
    @staticmethod
    def specific_thing_2():
        return 'b'

    @classmethod
    def do_it_all(cls):
        return cls.specific_thing_1() + cls.specific_thing_2()


class MyOverrideTasks(MyTasks):
    @task(name="2-override")
    @staticmethod
    def specific_thing_2():
        return 'b'
 
 
my_flow = flow(MyTasks.do_it_all)
my_other_flow = flow(name="other-flow")(MyOverrideTasks.do_it_all)

my_flow()
my_other_flow()
```

**Comment by camsmith** [comment]
that's an interesting syntax I hadn't thought of. Thanks for taking the time
