### ISSUE TITLE
GitHub block does not support fine-grained PATs

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#8583]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The `GitHub` storage block does not work with GitHub's new fine grained access tokens. Using a fine-grained token results in password prompt with the example below. More details in [this SO post](https://stackoverflow.com/questions/74493073/using-a-github-fine-grained-token-with-git-pull-over-https).

### Reproduction

```python3
from prefect.filesystems import GitHub

GITHUB_TOKEN = "<PAT GOES HERE>"

block = GitHub(
    repository="https://github.com/<owner>/<repo>.git",
    reference="main",
    access_token=GITHUB_TOKEN
)

block.get_directory(local_path="./gh_pat_test")
```

### Error

```python3
Password for 'https://<PAT GOES HERE>@github.com':
```

### Versions

```Text
Version:             2.8.2
API version:         0.8.4
Python version:      3.9.16
Git commit:          afbed19d
Built:               Fri, Feb 17, 2023 10:02 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment]
It sounds reasonable to me to support the new fine-grained PATs if possible 👍

**Comment by discdiver** [comment]
Closing as fine-grained PAT format is now shown in the UI with #8929 and confirmed with @zzstoatzz that it works.
