### ISSUE TITLE
Add warning to prefecthq/prefect:latest Docker image

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#8585]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

1.x

### Describe the current behavior

Official images with the `latest` tag contain Prefect version 1.x. As seen at PACC NYC, this leads to confusion for new users as they expect `latest` to contain version 2.x.

### Describe the proposed behavior

There's a discussion to be had about whether (or when) we should publish version 2 code in `latest`, but separately, could we add a warning to the `latest` image to help users in the meantime?

### Example Use

```sh
$ docker run prefecthq/prefect:latest bash

!!! WARNING: This image contains Prefect v1 code. Are you looking for prefecthq/prefect:2-latest? !!!

```

**Comment by madkinsz** [comment]
I think we'll want to warn for a couple months that `latest` is going to change to v2 then start tagging v2 as `latest`.
