### ISSUE TITLE
Allow agent to dynamically match on work pool

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#8589]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently a single agent can only pull flow runs from a single work pool.

### Describe the proposed behavior

It would be nice if an agent can pull flow runs from multiple work pools using syntax similar to what was done for work queue regex. 

This makes it lot easier to spin up and scale a single agent that can track multiple work pools. Currently you have to spin up a new agent for each work pool.

### Example Use

prefect agent start -mp "test"
where mp is match pool

similarly  
prefect agent start -mq "test"
where mp is match queue

**Comment by desertaxle** [comment]
Thanks for opening this issue @rjhawar! Could you share some more about your use case where having an agent pull from multiple work pools is needed? Since work pools can have multiple work queues, you could create multiple work queues in a single work pool if you want to run only one agent.

**Comment by rjhawar** [comment]
@desertaxle 
Sure i can share my use case with you:
In my case each queue is connected to specific project (a flow is connected to a project in my company's platform). Going off this assumption it doesn't make sense to group all queues together since some of the queues will need to have the same priority. It would be more useful if I could have multiple work pools so I could assign different priorities to each queue independently. However at the agent level all queues effectively have the same regex scheme (ex: <fixed keyword>_project_name) . Currently the agent can only pull flow runs from a specific work pool which is not ideal for my use case.

Here is a more concrete example of what i am trying to achieve:
PRO1 (workpool 1) ---> sub-PRO1 (queue 1, pri: 1) --> sub-PRO2 (queue 2, pri: 2)
PRO2 (workpool 2) ---> sub-PRO2 (queue 1, pri: 1) --> sub-PRO1 (queue 2, pri: 2)

Required change in agent behaviour:
agent --> regex match on queue name (checks all work pools) OR  agent --> regex match on work pool

**Comment by billpalombi** [comment]
Thanks for the feedback @rjhawar - its helpful to understand how you're using work pools and queues.

Our design intent is that a work pool represent a single execution environment (e.g. a Kubernetes cluster, a single virtual machine, a staging environment, etc.) and that a work queues represent a priority level within that environment.

We recommend deployment tags to categorize deployments and their runs into projects and sub-projects. We've seen users denote both projects and sub projects by effectively nesting tags, for example:

Deployment 1 (tags: PRO1, sub-PRO1) ---> work pool A ---> work queue 1 (pri: 1)
Deployment 2 (tags: PRO1, sub-PRO2) ---> work pool A ---> work queue 2 (pri: 2)
Deployment 3 (tags: PRO2, sub-PRO1) ---> work pool A ---> work queue 1 (pri: 1)
Deployment 4 (tags: PRO2, sub-PRO2) ---> work pool A ---> work queue 2 (pri: 2)

**Comment by rjhawar** [comment]
@billpalombi What happens in the case where you want two work queues in the same work pool to have the same priority?
What if I have multiple criterial, but distinct queues for a single deployment --> this is reasonable request if i want to be able to pause for a specific project, but don't want to create multiple deployments which would mean multiple infra setups to maintain
