### ISSUE TITLE
Do not automatically generate API reference as part of docs:dev due to "all_extras"

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#859]
Because the API reference generation script visits all files, it requires users to install `all_extras`, which means simply running dev concept docs requires a relatively heavy install. 

Currently, there are three docs scripts:
```json
"scripts": {
    "docs:generate-api": "cd docs && python generate_docs.py",
    "docs:dev": "yarn docs:generate-api && vuepress dev docs",
    "docs:build": "yarn docs:generate-api && vuepress build docs"
}
```

Because `docs:generate-api` is part of the other two, they require `all_extras`. I think that we could safely remove it from the other two, with some proper documentation, and make editing the docs a less intense process for some users.

**Comment by cicdw** [comment]
Q: Will `vuepress` successfully build if the api docs folder doesn't exist?

**Comment by ma7dfa7d** [comment]
https://github.com/PrefectHQ/prefect/issues/859#issuecomment-476958821

**Comment by cicdw** [comment]
Closed with https://github.com/PrefectHQ/prefect/pull/1063
