### ISSUE TITLE
Many of the images in docs are not showing 

### ISSUE THREAD

**Issue by dshahid380** [PrefectHQ/prefect#860]
Many of the images of docs are not showing there.
https://github.com/PrefectHQ/prefect/tree/master/docs/guide/tutorials

- advanced-mapping.md
- calculator.md
- etl.md
- slack-notifications.md
- visualization.md
Should we update this?

**Comment by joshmeek** [comment]
Hey @dshahid380 I believe the images are meant to be displayed on `docs.prefect.io`

see here: https://docs.prefect.io/guide/tutorials/

**Comment by cicdw** [comment]
Yea, all of those image links are only meant to be rendered by `vuepress`.  You can see them locally if you want by installing `prefect` with `all_extras` and running `yarn docs:dev` (see here: https://docs.prefect.io/guide/development/documentation.html#previewing-docs-locally)
