### ISSUE TITLE
Organize metadata in well on task run page

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#8632]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, in the well on the task run page, metadata about a particular task run is interspersed among task configuration data: 
![Screenshot 2023-02-23 at 12 07 03 PM](https://user-images.githubusercontent.com/3407835/220981692-0a5ec6f8-a966-4586-8828-72741b2ee616.png)

### Describe the proposed behavior

The metadata in the well should be organized into two seperate sections after the flow run link at the top:
- Flow run link
----------
**Task run**
- Start time
- Duration
- Run Count
- Estimated run time
- Created
- Last updated
- Cache key
- Cache expiration
- Dynamic key
- ID
----------
**Task configuration**
- Version
- Retries
- Retry delay
- Tags

The flow run ID should be removed entirely - the user can click through to the flow run page to get it if they need it.

Related to #8635

**Comment by brandonreid** [comment]
Ideally, there is some level of consistency between this well and the Flow Run well, which has a number of fields in common. @billpalombi, maybe you could provide a similar audit of that well? Otherwise it can be inferred from this one. They are both pretty easy to modify and in the same repo.

**Comment by billpalombi** [comment]
Agreed, I'll create another ticket for that now.
