### ISSUE TITLE
Hyperlinks in Events under Automations not loading

### ISSUE THREAD

**Issue by jmmizerany** [PrefectHQ/prefect#8671]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When trying to view the events under an Automation, the page that loads results in a blank page. The underlying network traffic when using developer tools with Google Chrome shows a 403 - Forbidden response when clicking into the events, even though I created the automation and can see a list of events

### Reproduction

1. Go to automations page
2. Click on the desired automation
3. Switch to the "events" tab
4. After seeing the list of events, click on any event
5. A blank page will be shown and nothing will be loaded

### Error

<img width="1378" alt="Screen Shot 2023-02-28 at 9 24 11 AM" src="https://user-images.githubusercontent.com/97474773/221898933-a57d2f5b-ccd5-401c-b50e-d0918b82692e.png">
<img width="1667" alt="Screen Shot 2023-02-28 at 9 24 23 AM" src="https://user-images.githubusercontent.com/97474773/221898980-a426edc8-ed7d-483a-9d9e-c52e27d358a0.png">
After clicking on the first event in the first screenshot, the second image is the result of that action

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Prefect version

```Text
2.8.3 - we are on prefect cloud
```

**Comment by rpeden** [comment]
I see this too, with the following error: 
![image](https://user-images.githubusercontent.com/228762/221915941-670ff836-14c9-4667-b646-d0ae5fbb5df8.png)

The response body is `{"detail":"Audit events not enabled"}`

**Comment by jmmizerany** [comment]
@rpeden If you are getting `Audit events not enabled` could that be our tier with prefect cloud? We are on the free tier at the moment, but I still get a `Forbidden` response instead of what you are getting

**Comment by chrisguidry** [comment]
@jmmizerany is this still happening for you, and if so, can you share your workspace URL with me?

**Comment by chrisguidry** [comment]
Note to any Prefect folks following up on this.  This log query: 

```
httpRequest.status=403
httpRequest.requestUrl=~"https://api.prefect.cloud/api/accounts/.+/workspaces/.+/events/filter/?"
```

Only had three instances in the last month, so this _may_ be resolved.  Waiting for confirmation from jmmizerany.

**Comment by jmmizerany** [comment]
@chrisguidry I believe this is resolved! Thanks!

**Comment by chrisguidry** [comment]
Great to hear!  Thanks for confirming!
