### ISSUE TITLE
Proposal PIN: Build Serializer and Environment Separation

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#869]
# Status
Proposed

# Context

Currently environments contain all of their own building and execution logic. This leads to frictions in customizability of environments. For example, the current Kubernetes based environments all implement the same `build` function which takes in specifications around building a Docker image that is used as a means of storing and retrieving the serialized flow. This leads to confusion and lock-in for the environments.

This new separation of moving the build step away from the execution environment itself will make it increasingly easier for users to supply their own Docker image.

# Decision

Break out the build aspect of an environment into its own segment that becomes an aspect of the environment itself.

An example environment definition would now look something like:
```python
from prefect.environments.kubernetes import DaskOnKubernetesEnvironment
from prefect.environments.build_serializers import DockerBuildSerializer

build_serializer = DockerBuildSerialized(registry_url="url", custom_dockerfile="dockerfile_info")
env = DaskOnKubernetesEnvironment(build_serializer=build_serializer)

with Flow("my flow", env=env) as f:
  flow tasks here

f.deploy(project_id="id")
```

The build serializer would contain the information for building/serializing/storing the Flow. Once `flow.serialize(build=True)` happens it will take the environment and call the build serializer's build function which will return the relative information needed to retrieve it and then that will be serialized and populated in the environment's metadata.

In the context of a Docker build serializer with a k8s related environment the build serializer will have values such as `image_name`, `image_tag`, `registry_url`, etc... and once the k8s related environment ingests that metadata on setup it expects the build serializer metadata to contain the fields related to creating resources on k8s.

# Consequences

The only immediate consequence is the need to change some of the setup and execute functionality of the environments.

**REQUEST FOR COMMENTS HERE**
The name _Build Serializer_ makes sense from the serialization standpoint but the actual build related classes need a better name.

_This is ongoing, I am going to update this over the next few hours, just currently organizing thoughts._

**Comment by joshmeek** [comment]
@cicdw @jlowin What do you think of this so far?

**Comment by cicdw** [comment]
I think for "context" you could also add a blurb about making the interface easier for users who want to provide their own Docker image?  I think this separation of "serializing the flow into a known location" from "defining its execution environment" well make that much simpler.

**Comment by jlowin** [comment]
I think a cleaner identification of "what problem does this solve" would be helpful here.

In a minimal sense, this proposal looks like separating `Environment.build()` and `Environment.run()` into `BuildSerializer.build()` and `Environment.run()`, which doesn't immediately feel DRY because it sounds like `Environments` and `BuildSerializers` are still tightly coupled. For example, I can't use any `BuildSerializer` with any `Environment`, right?

On the other hand, the build process and the run process are very clearly "different" from each other, so I endorse the idea of spitting them up from that perspective.

Is there a way to more loosely couple them -- could a DockerBuildSerializer work with any Environment? Could a (theoretical) S3Serializer or GitHubserializer be introduced and "just work" with an environment? I'd like to understand more about how they interact -- if there's only one BuildSerializer for one Environment, then the advantage over subclassing isn't as clear.

Is it true that the `BuildSerializer` holds on to a lot of the metadata that currently has to be provided (somewhat awkwardly) to the `Environment` class?

**Comment by joshmeek** [comment]
The problem it _solves_ is adding modularity with the idea of separating out the build layer from the environment itself. I want it into the abstraction of "here is the flow" and "here is where and how to run it". For example, I may want to run my flow on k8s but I don't want to use Docker and instead use something like CoreOS's rkt or containerd.

The more I think about it the more I believe it won't be possible to use any build serializer with any environment. So moving forward from that it could be beneficial to put the build serializers into groupings where they would be applicable for an type of environment (at the platform level). Since we are going to start thinking of environments more as "Use EXECUTOR on PLATFORM" it should have some standard to how the build serializers metadata looks. For example, all environments where the platform is k8s it will expect the build serializer metadata to contain the registry url, image name, and image tag.

I'm going to devote more thought to the idea of more loosely coupled build serializers and environments and I welcome any and all input on the matter. I like the idea of some serializers "just working" on any environment but that is a tricky problem. For example, the k8s platform specific environments still require to know about the image and the registry it comes from so that it can spin it up and I'm not sure how that would work in unison with a GitHubSerializer for example.

And yes the build serializers become responsible for a lot of the metadata that is currently passed to the environments.

----

In looking at the types of metadata that the build serializers return here are some examples (in theory):

Docker Build Serializer: `image_name`, `image_tag`, `registry_url`

S3 Build Serializer: `bucket_name`, `key`, `region`

GitHub Build Serializer: `repository_name`, `organization_name`, `file name`, `personal access token`

Here's a thought experiment: If I want to use a github build serializer with a k8s related environment, how would I go about getting that running?

**Comment by jlowin** [comment]
This makes a lot of sense. To be clear, even just refactoring for clarity is a good enough reason -- I just wanted to understand the succinct motivation better.

I don't think we require a loose coupling between serializers and environments -- it makes sense that some only work with others. I do think we want a good way to clearly create that expectation. I like this pattern you tossed out - run EXECUTOR on PLATFORM. If we can use a simple description like that to motivate behavior, I think it will be great

**Comment by joshmeek** [comment]
Can we close this proposal pin as it has changed directions?

@cicdw @jlowin

**Comment by jlowin** [comment]
Yes, but let's link to this issue in the new PIN as a record of other considerations.
