### ISSUE TITLE
Retry flow submission when Prefect has an internal error

### ISSUE THREAD

**Issue by aloysius-lim** [PrefectHQ/prefect#8690]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

1.x

### Describe the current behavior

We are running Prefect Server 1.4 in Kubernetes, using the official Helm chart. There are replicas for all components, including graphql. But occassionally, we find that a scheduled flow (using cron schedule) fails to even start because one of the graphql pods was terminated in Kubernetes. Even though there are multiple (2) replicas of graphql running, the other pod does not pick up the request from Prefect.

There is only one line in the flow run logs:

```
[{'message': 'request to http://prefect-graphql.prefect:4201/graphql/ failed, reason: socket hang up', 'locations': [{'line': 2, 'column': 5}], 'path': ['set_flow_run_states'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'request to http://prefect-graphql.prefect:4201/graphql/ failed, reason: socket hang up', 'type': 'system', 'errno': 'ECONNRESET', 'code': 'ECONNRESET'}}}]
```

### Describe the proposed behavior

If Prefect Server itself is not able to start a flow run for any reason (graphql failure in this case, but it could be any other cause), then it should retry the initiation of the run. This is not covered by the built-in retry mechanism of Tasks, since the flow could not even be initiated, and therefore has to be handled at the Server level.

**Comment by madkinsz** [comment]
Perhaps you would be interested in trying https://github.com/PrefectHQ/server/pull/385
