### ISSUE TITLE
Proposal PIN: rename "decision"

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#870]
This almost seems silly to make a PIN, because it's very minor, but it has to do with PINs themselves, so it will need to be noted as a change to PIN-1. /shrug

# PIN: Updated PIN Format

Date: March 28, 2019
Author: Jeremiah Lowin

## Status
Proposed; expands [PIN-1]

## Context
Right now PINS have four sections: **Status, Context, Decision, and Consequences**. This was modeled on a popular format for ADRs. However, in reading our PINs as a narrative, [PIN-5](https://docs.prefect.io/guide/PINs/PIN-5-Combining-Tasks.html) is very confusing, because it was declined. As such, a new reader reads down the page, *maybe* notices that it was declined, and is suddenly confronted with a section called **Decision** which implies that a decision was, in fact made. Only at the end is there a section called **Reason for declining** which, to be clear, is good to have.

## Proposal

The section of each PIN formerly called **"Decision"** will be instead called **"Proposal"**, to better enhance the narrative of each PIN. This will be more appropriate no matter whether it was accepted and implemented, or just debated and declined.

In addition, a new section will be added to end of the PIN called **"Responses"** (or possibly **"Actions"**) which can link to discrete actions created in response PIN (for example, PRs) or explain the decision to decline it. This section is optional, but helpful.

## Consequences
Former PINs will be tweaked and the narrative structure of each PIN will be enhanced.

**Comment by cicdw** [comment]
+1 on this but it feels too heavy to include this as a PIN.  I vote just reword the old PINs / first PIN.

**Comment by jlowin** [comment]
Ok I'm totally fine with that, felt silly. Just wanted to make sure that was ok.
