### ISSUE TITLE
Add a warning message when the default work queue is paused

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#8703]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If I pause my default work queue and the try to run an agent, there's no warning that the work queue is paused.  I just spent a while debugging the issue before looking in the UI and realized the queue was paused. 

### Describe the proposed behavior

If I run prefect agent start -p testt and the default work queue in the testt work pool is paused. I get an warning message saying the default work queue is paused.  (We had this for work queues and it was very helpful). 

### Example Use

I create a work pool in the UI (e.g. name `testt`) and pause my default work queue.  Later I start my (local) agent using the cli (`prefect agent start -p testt`) and try to kick off a run from a deployment.  Because the work queue is paused, no runs are picked up but I do get a message in the CLI so I know to go unpause my work queue.

**Comment by madkinsz** [comment]
@zhen0 

> I get an error message saying the default work queue is paused.

A warning or an error? Seems like the agent should probably continue to run.

**Comment by madkinsz** [comment]
@billpalombi could you triage this?

**Comment by billpalombi** [comment]
Hmm, this is tricky. The agent (and workers) will successfully find the work pool, but I don't think it has any way of knowing whether that work pool or its queues are paused or not. Lets keep this issue open to reflect the UX issue, but circle back to it once we've rolled out the forthcoming agent enhancements (workers).
