### ISSUE TITLE
Logs not showing in Cloud UI: Created and completed

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#8707]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The Cloud UI running a single flow via `python my_flow.py` (not in a deployment) doesn’t show any logs, even if the CLI does show the Created and Completed logs.

### Reproduction

```python
from prefect import flow

@flow
def hi():
    print("hi")

if __name__ == "__main__":
    hi()
```
Run via:
```
$ python my_flow.py
```

### Error

The UI displays:

```
This run didn't generate Logs
```

```
# Terminal Output

17:18:16.416 | INFO    | prefect.engine - Created flow run 'burrowing-goose' for flow 'hi'
hi
17:18:17.132 | INFO    | Flow run 'burrowing-goose' - Finished in state Completed()
```

### Versions

```
Version:             2.8.4
API version:         0.8.4
Python version:      3.10.8
Git commit:          f09ccc32
Built:               Thu, Mar 2, 2023 12:34 PM
OS/Arch:             darwin/arm64
Profile:             jeffmshale
Server type:         cloud
```

### Additional context

Seems to only happen in Cloud for flow runs with a single log.

**Comment by zhen0** [comment]
Extra note: `prefect flow-run logs <FLOWRUNID>` displays nothing

**Comment by madkinsz** [comment]
@discdiver I don't think I expect this to generate logs? The `engine` log is local only. We don't send "finished in state" logs to to the API because it's redundant. You don't have `log_prints` enabled.

**Comment by madkinsz** [comment]
Hm I actually think we should expect to see see "Finished in state" log https://github.com/PrefectHQ/prefect/blame/main/src/prefect/engine.py#L419-L422 — perhaps this is a bug in log flushing when there are very few messages?

**Comment by discdiver** [comment]
Thank you @madkinsz. I expect the local logs to match the logs in Prefect Cloud. I think, based on the Slack conversation around this issue, that most folks do. Would it be tricky to do so? 

Tagging @billpalombi and @zhen0 to the extent there's opinions/work on their ends.

**Comment by billpalombi** [comment]
As @madkinsz said, the engine logs should not be recorded in the database, regardless of whether its self hosted or cloud. 

However, flow run creation and finished logs provide useful "bookend" context for other logs when they are present, so they should be recorded, again regardless of whether its self hosted or cloud. Sounds like we need:
- One ticket to add a logged message for flow run creation like the one we have for finished
- One ticket to investigate log flushing for the finished in log
