### ISSUE TITLE
Proactive wq health automations firing inconsistently

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#8713]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Proactive wq health automations are firing inconsistently. At least one user [reported](https://prefect-community.slack.com/archives/CL09KU1K7/p1677786111857489) this.

### Reproduction

```python3
Post an automation with the following trigger

{
    "match": {
        "prefect.resource.id": [
            "prefect.work-queue.8188300b-6621-4eaa-8b1f-6c93018d6b34"
        ]
    },
    "match_related": {},
    "after": [
        "prefect.work-queue.unhealthy"
    ],
    "expect": [
        "prefect.work-queue.healthy"
    ],
    "for_each": [
        "prefect.resource.id"
    ],
    "posture": "Proactive",
    "threshold": 0,
    "within": 30
}```
Start an agent to get the queue healthy, kill the agent after 60 seconds or so, observe no reaction from the system.
```

### Error

```python3
No action executed, no record of a failed action execution.
```

### Versions

```Text
Version:             2.8.4
API version:         0.8.4
Python version:      3.10.4
Git commit:          f09ccc32
Built:               Thu, Mar 2, 2023 12:34 PM
OS/Arch:             darwin/x86_64
Profile:             prod
Server type:         cloud
```

### Additional context

@chrisguidry I believe this is a good test case for the reliability work you are working on re the triggers system.

**Comment by chrisguidry** [comment]
I believe this was caused by the same underlying problem as https://github.com/PrefectHQ/prefect/issues/8871 and should be resolved now.
