### ISSUE TITLE
Create logger after task_run_name calculated

### ISSUE THREAD

**Issue by tothandor** [PrefectHQ/prefect#8726]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It was great news for me that `task_run_name` parameter was added to Prefect 2 ([PR#8373](https://github.com/PrefectHQ/prefect/pull/8378)), I have anticipated it very much, and I am sorry to say, but it has failed its mission in some way. As @sibbiii mentioned [in his comment](https://github.com/PrefectHQ/prefect/pull/8378#issuecomment-1428797100) on the PR, there are now two IDs track in the logs instead of one. The main use of this ID (or any other IDs for that matter) is to be able to trace a process from its start to the the end. @madkinsz [suggested](https://github.com/PrefectHQ/prefect/pull/8378#issuecomment-1428910350) in a follow up, that run names may be hidden from the default log, if I understand correctly, this would just hide the problem, and we would even lose the IDs that we could follow. @madkinsz could you please explain what you meant by that?

This example is limited to 3 names, but it's already enough to lose track of what's happening. When did each task is started and finished executing.
I know it may seem like a little thing, but it becomes really important when things go wrong.

### Reproduction

```python3
Here's a toy example that demonstrates the problem:

# task_run_name_map_test.py
from prefect import flow, task

@task
def get_names():
    return ["Amber", "Barbara", "Charlie", "Denise", "Ebony", "Fiona", "Georgia", "Helen", "Irene", "Julia"][:3]

@task(task_run_name='say_hello-{name}')
def say_hello(name):
    print(f"Hello {name}!")

@flow
def hello_flow():
    names = get_names()
    say_hello.map(names)

if __name__ == '__main__':
    hello_flow()


This is the output after execution:
```
10:56:37.994 | INFO    | prefect.engine - Created flow run 'artichoke-mamba' for flow 'hello-flow'
10:56:38.222 | INFO    | Flow run 'artichoke-mamba' - Created task run 'get_names-0' for task 'get_names'
10:56:38.224 | INFO    | Flow run 'artichoke-mamba' - Executing 'get_names-0' immediately...
10:56:38.320 | INFO    | Task run 'get_names-0' - Finished in state Completed()
10:56:38.388 | INFO    | Flow run 'artichoke-mamba' - Created task run 'say_hello-0' for task 'say_hello'
10:56:38.391 | INFO    | Flow run 'artichoke-mamba' - Submitted task run 'say_hello-0' for execution.
10:56:38.429 | INFO    | Flow run 'artichoke-mamba' - Created task run 'say_hello-1' for task 'say_hello'
10:56:38.431 | INFO    | Flow run 'artichoke-mamba' - Submitted task run 'say_hello-1' for execution.
10:56:38.476 | INFO    | Flow run 'artichoke-mamba' - Created task run 'say_hello-2' for task 'say_hello'
10:56:38.478 | INFO    | Flow run 'artichoke-mamba' - Submitted task run 'say_hello-2' for execution.
Hello Amber!
Hello Barbara!
10:56:38.963 | INFO    | Task run 'say_hello-Amber' - Finished in state Completed()
10:56:38.987 | INFO    | Task run 'say_hello-Barbara' - Finished in state Completed()
Hello Charlie!
10:56:39.156 | INFO    | Task run 'say_hello-Charlie' - Finished in state Completed()
10:56:39.199 | INFO    | Flow run 'artichoke-mamba' - Finished in state Completed('All states completed.')
```
```

### Versions

```Text
Prefect 2.8.4
```

**Comment by iolbr** [comment]
Any news on this? We'd like to use custom flow run names in our project, but this bug prevents us from using this functionallity.
