### ISSUE TITLE
Ability to add a Discord webhook url while creating a new notification

### ISSUE THREAD

**Issue by Ishankoradia** [PrefectHQ/prefect#8727]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently there are options for Mattermost, Microsoft Teams, Opsgenei, Pager Duty and Slack webhook to receive notifications. 

### Describe the proposed behavior

User will be able to select "Discord webhook" and paste the webhook url for it to create notification. The user will also be able to select "Run states" and "Notify Type (Optional)".

### Additional context

I am working on this feature and any suggestions / feedback / ideas are welcomed.

**Comment by serinamarie** [comment]
Hi @Ishankoradia, welcome to the community and thanks for the issue! Did you want to be assigned to this enhancement?

**Comment by Ishankoradia** [comment]
@serinamarie yes please.Thanks

**Comment by Sam-ScottLogic** [comment]
May I work on this?

**Comment by shindodkar** [comment]
Hi. @Ishankoradia I made a PR on this . I am new to open source so if there are any changes needed let me know amd help me walk me through it.

**Comment by vishalsanfran** [comment]
Created the above PR for this. Please review.
