### ISSUE TITLE
Unable to create work pool from GUI using self-hosted orion server

### ISSUE THREAD

**Issue by jackdesert** [PrefectHQ/prefect#8736]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

From the GUI (self-hosted Orion, version 2.8.4), click "Work Pools", the "+". Add a name, then click "Create". Nothing happens.

### Reproduction

From the GUI (self-hosted Orion, version 2.8.4), click "Work Pools", the "+". Add a name, then click "Create". Nothing happens.

### Error

This output exists in the javascript console:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/791315/223548168-6eb9a7bf-b809-4f25-a1b7-0bd9ef8ea446.png">

### Browers

- [ ] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.8.4
```

**Comment by desertaxle** [comment]
Thanks for reporting this issue @jackdesert! We recently released a new version of our UI library that contains a fix for this issue and that fix will be included in our next release.

**Comment by zhen0** [comment]
Should be resolved by recent releases.
