### ISSUE TITLE
[Self-Hosted] Clicking on a Deployment Gives Javascript ReferenceError

### ISSUE THREAD

**Issue by jackdesert** [PrefectHQ/prefect#8743]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When I click Deployments -> then click the right hand link to a deployment, the javascript console shows this error:

ReferenceError: can't access lexical declaration 't' before initialization

And the page goes mostly blank. 

### Reproduction

Set up a self-hosted server.
Create a deployment.
In the GUI, click Deployments -> 
  Then click the right-hand part of the link that points to https://xxxxxxxxxx.com/deployments/deployment/xxxxx

You will see a blank screen

### Error

This is what the screen looks like:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/791315/223789763-85744088-cf5a-4913-bb2b-a402d107f553.png">

This is the javascript error:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/791315/223789540-5a7665ed-35f6-4840-b39a-5f73cece444a.png">

### Browers

- [ ] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
self-hosted server using prefect v2.8.4
```

**Comment by znicholasbrown** [comment]
Hi @jackdesert - this looks like the same issue as #8712 and is resolved by #8716 - that fix will end up in tomorrow's release.  If that fix doesn't work for you feel free to re-open this issue and we can investigate further 👍🏻
