### ISSUE TITLE
[UI] Flow-runs date range defaults

### ISSUE THREAD

**Issue by Samreay** [PrefectHQ/prefect#8749]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Right now the date filtering on the flow runs page defaults to 7 days, and cannot be less than one day. Unfortunately, this choice makes the UI incredibly slow and the plot not usable for us, given we have flows that operate almost on a minute by minute time frame.

### Describe the proposed behavior

It would be amazing if, when saving out a view of the Flow Runs pae, we could configure the default lookback time as well. I'd be tempted to draw inspiration from how Grafana has their quick ranges as the closest industry-pervasive analogue:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6748505/223884782-13b35485-945b-4e26-8dea-19f4dd73cd94.png">

Even if that amount of options is deemed excessive, having the ability to select a time range less than a day would be ideal. For our use case if we were able to explicitly pick a range in the UI, we'd pick something like "3 hours in the past and one hour in the future"

You can see in the screenshot below, that even if we manually change the date range to just a single day, theres still such an enormous amount of overlap on the points the graph is very hard to use.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/6748505/223885188-4bc8740a-a85c-44af-9e29-02f8b7f9c408.png">

You can see how cluttered this gets on the week-long view (snippet of it below), and the UI lags due to the number of data points.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/6748505/223885365-61b31fd7-410a-4be0-ac48-b75c1799976b.png">

**Comment by zhen0** [comment]
Thanks @Samreay - I think we could separate this into two issues, one which I think we have reflected [here](https://github.com/PrefectHQ/prefect-design/issues/498) and which I think we could make higher priority.

**Comment by EmilRex** [comment]
@zhen0 I believe we can close this now with the new date filters, right?

**Comment by pleek91** [comment]
@EmilRex I agree. @Samreay please let us know if this is still an issue for you.

**Comment by Samreay** [comment]
Thanks team <3
