### ISSUE TITLE
[UI] Add x-range selection/zooming to the Flow Runs graph

### ISSUE THREAD

**Issue by Samreay** [PrefectHQ/prefect#8750]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In the Flow Runs time plots (screenshot below), you can click and drag to move the plot, and scroll in and out to zoom.

<img width="2274" alt="image" src="https://user-images.githubusercontent.com/6748505/223885790-1d41ee0a-c142-48ee-8294-9b5e2a7a910f.png">

This functionality does not exist in the Flow Runs plot, but you can see from the screenshot below with a very crowded graph, that it would be very useful to be able to zoom in and investigate the runs.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/6748505/223885874-7ab80368-0bd7-4ff0-8aa4-fd5bd364bda4.png">

### Describe the proposed behavior

Flow Run task plot functionality added to the Flow Runs history plot

**Comment by zhen0** [comment]
@justabill - flagging as product feedback on the flow runs chart.

**Comment by Samreay** [comment]
Nooooo don't go stale, this would be really cool

**Comment by jars** [comment]
Our team would love to see this re-opened and worked-on alongside other datepicker issues!

**Comment by TheoMathurin** [comment]
Also interested in this feature!
