### ISSUE TITLE
Sort task run IDs before output, from `prefect concurrency-limit inspect ...`

### ISSUE THREAD

**Issue by digitalronin** [PrefectHQ/prefect#8754]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

`prefect concurrency-limit inspect [limit name]` will output a list of "Active Task Run IDs" for tasks which are currently using any of the "concurrency slots". These are UUIDs.

The list currently appears in a random order. This makes it hard to identify whether or not the list of task IDs is changing, and whether any tasks might be in a hung state.

### Describe the proposed behavior

Sort the list of task IDs alphabetically before outputting them.

**Comment by zmwaris1** [comment]
@digitalronin I would like to work on this issue. Can you please give some details and assign this to me?

**Comment by madkinsz** [comment]
@zmwaris1 they are not a maintainer of this repository. You're welcome to work on this though. It's in the `src/prefect/cli/concurrency_limit.py` file at `inspect`. Probably adding sorting on this line https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/concurrency_limit.py#L85

**Comment by zmwaris1** [comment]
@madkinsz Thanks for the info. I will start working on it right away.

**Comment by rito-sixt** [comment]
Since this was open for a while, I took a stab at it. Looking forward to suggestions for improvements.
