### ISSUE TITLE
The text is not visible when entering the value of the flow parameters

### ISSUE THREAD

**Issue by mikri2017** [PrefectHQ/prefect#8769]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [ ] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The text is not visible when entering the value of the flow parameters. On custom run.
![image](https://user-images.githubusercontent.com/25917800/224214561-95a09c3b-55ac-42c6-a320-1d0d80d3e3d7.png)

### Reproduction

Deployments -> Menu on someone -> Custom run -> Parameters -> Custom

### Error

![image](https://user-images.githubusercontent.com/25917800/224214561-95a09c3b-55ac-42c6-a320-1d0d80d3e3d7.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
2.8.0
```

**Comment by zhen0** [comment]
Hi @mikri2017 - I believe this was fixed in https://github.com/PrefectHQ/prefect-ui-library/pull/1159 so I'm closing this issue.  Could you try updating to the latest version of prefect and if you still see a problem, come back and open a new issue.
