### ISSUE TITLE
Warn users with misconfigured API URLs

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#8774]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Users will occasionally misconfigure their `PREFECT_API_URL`. This is generally not a problem when the URL is constructed for the user - such as when logging in with `prefect cloud login` - but when manually constructing there can be some confusion. In particular we've seen users refer to app.prefect.cloud, rather than api.prefect.cloud, and we've seen users with `account` and `workspace` instead of `accounts` and `workspaces`. These often lead to 404 errors and it is unclear to new users what's happening.

### Describe the proposed behavior

It would be wonderful if we could display a warning when these common misconfigurations happen,

```
Warning: Your API URL points to app.prefect.cloud. Did you mean api.prefect.cloud?

Warning: Your API URL uses */account/* but should use */accounts/*

Warning: Your API URL uses */workspace/* but should use */workspaces/*
```

**Comment by xinlifoobar** [comment]
@madkinsz Could you please assign this to me? Trying to start with this first issue.

**Comment by serinamarie** [comment]
@EmilRex Thanks for this issue! Is there a use case other than when running `prefect config set PREFECT_API_URL` that you have seen users run into this issue?

**Comment by EmilRex** [comment]
@serinamarie Absolutely! It's not just when setting the config, but even more often when just populating the environment variable. My preference would be for there to be a runtime check when the setting is actually loaded.

**Comment by EmilRex** [comment]
The other common path is when doing `prefect cloud login`... not sure if that also uses the config CLI methods or not.

**Comment by cicdw** [comment]
It seems like we could provide a simpler interface for users using Cloud as well, something like:
```
prefect config set ACCOUNT_ID="..."
prefect config set WORKSPACE_ID="..."
```
and we handle the rest.  The current approach is nice because it's compatible with both OSS and Cloud, but I don't see any reason why we can't have a different convenience interface for Cloud only.

**Comment by zanieb** [comment]
In theory that should be covered by the `prefect cloud ...` commands but maybe there still could be some additional conveniences?

**Comment by cicdw** [comment]
Yea, having a light convenience for configuring a profile's API seems worthwhile (and simple)
