### ISSUE TITLE
Flow's runs screen won't load in Safari

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8777]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The [flow's runs screen](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flows/flow/151c048b-1d38-4dd9-bd25-c4960bf8650b) is blank in Safari:

![CleanShot 2023-03-11 at 11 17 05@2x](https://user-images.githubusercontent.com/5398977/224476108-e516aeb0-d581-4b83-bf84-737eb8a90a1d.jpg)

In contract, in Chrome it loads:

![CleanShot 2023-03-11 at 11 18 57@2x](https://user-images.githubusercontent.com/5398977/224476146-f853fb62-37f3-445f-b1e2-0d41e9e0b599.jpg)

### Reproduction

```python3
Browse to the URL in Safari
```

### Versions

```Text
Prefect cloud
```

**Comment by pleek91** [comment]
@yaronlevi can you please share what version of safari and also check to see if there are any errors in your safari console? I'm unable to reproduce on Safari 16.3

**Comment by zhen0** [comment]
Hi @yaronlevi - are you able to update your version of safari?  I also can't reproduce. 

Can you also see if there's any info in the developer tools console? Thanks!
