### ISSUE TITLE
Inaccurate naming warnings

### ISSUE THREAD

**Issue by peaky76** [PrefectHQ/prefect#8778]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Pytest reports a number of inaccurate naming `UserWarning`s when testing my tasks/flows. In each case the name given to the flow is not shared with any other flow or task in the project and specifying a unique name parameter as suggested does not correct the issue.

### Reproduction

This is what I have in this particular file, `rapid_horseracing_extractor.py` ...
```python3

@flow
def rapid_horseracing_extractor():
   ...

if __name__ == "__main__":
    rapid_horseracing_extractor()
```

Without copying the entire project, I cannot show that there is no other flow named this, but there isn't.
### Error

This is the output from pytest...
```python3

.venv\Lib\site-packages\prefect\flows.py:214
  C:\<my_project>\.venv\Lib\site-packages\prefect\flows.py:214: UserWarning: A flow named 'rapid-horseracing-extractor' and defined at 'C:\<my_project>\src\extractors\rapid_horseracing_extractor.py:115' conflicts with another flow. Consider specifying a unique `name` parameter in the flow definition:

   `@flow(name='my_unique_name', ...)`
    warnings.warn(
```

The problem persists after giving a unique name:
```
@flow(name="nothing_else_is_called_this_for_sure")
def rapid_horseracing_extractor():
    ...
```

Error:
```
.venv\Lib\site-packages\prefect\flows.py:214
  C:\<my_project>\.venv\Lib\site-packages\prefect\flows.py:214: UserWarning: A flow named 'nothing_else_is_called_this_for_sure' and defined at 'C:\<my_project>\extractors\rapid_horseracing_extractor.py:115' conflicts with another flow. Consider specifying a unique `name` parameter in the flow definition:

   `@flow(name='my_unique_name', ...)`
    warnings.warn(
```

### Versions

```Text
$ poetry run prefect version
Version:             2.8.3
API version:         0.8.4
Python version:      3.11.1
Git commit:          07de1ac4
Built:               Thu, Feb 23, 2023 4:31 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```
And I'm using poetry 1.3.2 with the following deps:
```
[tool.poetry.dependencies]
boto3 = "^1.26.88"
prefect = "^2.8.5"
python = "^3.10.0"
python-dotenv = "^1.0.0"
pendulum = "^2.1.2"
pymongo = "^4.3.3"
petl = "^1.7.12"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-mock = "^3.10.0"
black = "^23.1.0"
coverage = "^7.2.1"
mypy = "^1.1.1"
```

**Comment by madkinsz** [comment]
That's a weird one. Can you take a peek at the global object registry we use to track these kinds of things?

```python
from prefect import Flow
from prefect.context import GLOBAL_OBJECT_REGISTRY

print(GLOBAL_OBJECT_REGISTRY.get_instances(Flow))
```

**Comment by johnkangw** [comment]
@madkinsz I just experienced this issue on 2.10.2, but I think it is because I might have a circular import issue (I am testing a task on one file but importing over a function from another file that has an import from the previous file). 

Example:
File1.py contains Function1 and imports Function2 from File2.py
File2.py contains Function2. I am running a test by using (`if __name__== "__main__":`) and importing Function1.

**Comment by peaky76** [comment]
Sorry, it's taken me a while to get round to looking into this. I can confirm that the issue was as suggested by @johnkangw. A circular import in my test file.
