### ISSUE TITLE
Deployment tags are not loaded into tag filtering

### ISSUE THREAD

**Issue by Samreay** [PrefectHQ/prefect#8791]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The tags filtering input does not populate tags in the deployment screen.

### Reproduction

Add tags to deployments. Refresh deployments screen.

### Error

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/6748505/224893755-44b5c8db-d81e-4d83-aa5b-5d051533745f.png">

You can manually type in a tag.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/6748505/224894418-da6cf378-7b35-4a2a-a59f-cd5eb6a5ba9e.png">

If you type an actual tag, it *will* filter:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/6748505/224894469-3100cab1-4559-418e-87f3-9d4e663dd65e.png">

But when you refresh, it wont remember it. Given the UI already has a list of tags displayed to the user, I am assuming it not pre-loading those tags into the forms are a UI bug.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.8.3
API version:         0.8.4
Python version:      3.9.12
Git commit:          07de1ac4
Built:               Thu, Feb 23, 2023 4:31 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.38.2
```
```


### Additional context

_No response_

**Comment by zhen0** [comment]
Ah - we added an enhancement to the tags filter on the runs page and I think we could do the same on the deployment page.

**Comment by sgbaird** [comment]
Just a fly-by note that I tried adding a tag in Prefect Cloud, it didn't populate in the dropdown immediately (within a few dozens of seconds to a couple mins, maybe longer?) and so I thought that there might be a bug or it might not be a supported feature. Eventually came across here and then went back to look, and saw that the tag had populated.

Also just a side note that the `onboarding` tag from an onboarding tutorial (I think) is grayed out and doesn't populate and can't be used for filtering. Just a passing comment in case someone tries to use that tag to filter, and mistakenly thinks that filtering isn't working as expected.
