### ISSUE TITLE
Add prefect version information to azure marketplace listing

### ISSUE THREAD

**Issue by keshavksingh** [PrefectHQ/prefect#8800]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

![image](https://user-images.githubusercontent.com/41631964/225198453-f2158e56-6c3f-4e91-b4a2-b337574e7977.png)

### Reproduction

Go to Azure Portal +Create Market Place, add Prefect and configure with Prefect Cloud's Generated API Key

### Error

The Value is not accepted - error message "The value must be 1-22 characters long"

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Prefect version

```Text
Current Prefect Cloud Version
```

**Comment by WillRaphaelson** [comment]
Thanks for raising this @keshavksingh - we'll get this looked into asap.

**Comment by WillRaphaelson** [comment]
@keshavksingh one other point worth making, the marketplace offering is for prefect 1. To get the prefect 2 agent on a azure box, you'll need to install the open source package.

**Comment by keshavksingh** [comment]
In that case I wouldn't call the 2.0 or the latest release successful.

**Comment by madkinsz** [comment]
@keshavksingh please be respectful. See our [code of conduct](https://docs.prefect.io/contributing/overview/#prefect-code-of-conduct) for details on our expectations.

We understand that you're frustrated that we have not provided a way to install a Prefect 2 agent from the Azure marketplace. However, we are a small team and the marketplace is not a deployment pattern that has seen significant historical usage. We are excited to work on more comprehensive integrations with cloud providers this year.

**Comment by keshavksingh** [comment]
There is a absolutely nothing disrespectful about my last statement. I would appreciate if you could add a disclaimer on the Azure agent on Marketplace about its compatibility with 1.0
These are basics of a software release. Thank you! Hope you find my comments constructive and in the right spirit. I love Prefect for several of its features are unparalleled! Let's bring it to the Azure customers.
