### ISSUE TITLE
Option to log progess and duration estimations

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#8820]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Some long running tasks have a clear estimation of their progess as well as their remaining duration. Curretnly the only way to track this is to conntect the logger to say tqdm. This tends to spam the logs, as long as one doesn't throttle the logging.

### Describe the proposed behavior

It would be great if the progess could be logged to prefect so the gui could show how long the current task will still take. 

```python
@task
def foo():
    logger =  get_run_progress_logger()
    for i in logger(range(100), total=100):
        sleep(1)
```

**Comment by billpalombi** [comment]
Thanks for submitting this issue @felix-ht! We have a feature in the works that will support this use case. It should ship in a few weeks. I'll circle back once its released.

**Comment by hubsbendang** [comment]
Any update on this?

**Comment by billpalombi** [comment]
@hubsbendang, this proved to be a greater design challenge than we anticipated. While we do want to address this need, we don't have a timeline for doing so.

**Comment by thebuchanan3** [comment]
tqdm can be configured to output progress in an interval rather than "spam" every x ms using the min/max interval options -> `https://tqdm.github.io/docs/tqdm/#tqdm-objects`
this can be combined with using the prefect logger as output using this recipe -> `https://github.com/tqdm/tqdm/issues/313#issuecomment-267959111`

no native integration ofc, but works nice for us

**Comment by thebuchanan3** [comment]
tqdm can write though a logger like [solved here](https://github.com/tqdm/tqdm/issues/313#issuecomment-267959111) in larger intervals by setting `mininterval` and `maxinterval` accordingly. 

Works well with prefect loggers too, e.g. update ~ every minute:
![Snapshot_2024-05-27_12-43-36](https://github.com/PrefectHQ/prefect/assets/11337527/f4ad8f07-61b0-410b-bcdc-68358c9c0ea9)
