### ISSUE TITLE
UI: Clickable Links in Flow Run Logs

### ISSUE THREAD

**Issue by trahloff** [PrefectHQ/prefect#8828]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

URLs that are logged to Prefect UI can not be clicked in the browser.

### Describe the proposed behavior

URLs that are logged to Prefect UI can be clicked in the browser and open a new tab with the URL.

### Example Use

Prefect often spins up dynamic infrastructure (e.g., Dask or Ray clusters) that have dashboards for monitoring. 
Currently, we log these dashboard URLs at the beginning of our flow and need to copy-paste them to access the dashboard. 

Similar use case: Prefect Flow with manual approval. If you want to manually check the output of a flow run before continuing the execution, the result you want to check is often reachable via an URL (S3, website, etc.). Having this clickable from the UI would be a nice UX improvement.

**Comment by zhen0** [comment]
Thanks for the suggestion!  I think this is already tracked in https://github.com/PrefectHQ/prefect/issues/8448

**Comment by batuhanfaik** [comment]
I am looking forward to this feature! Colourful texts would also be a great addition, especially for URLs

**Comment by trahloff** [comment]
Still relevant from my point of view

**Comment by batuhanfaik** [comment]
Still relevant

**Comment by j-tr** [comment]
just noticed that this is already fixed in Prefect Cloud. can this be closed?

**Comment by zhen0** [comment]
Closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1997
