### ISSUE TITLE
Javascript Client Library

### ISSUE THREAD

**Issue by thatcort** [PrefectHQ/prefect#8863]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The Prefect dashboard interacts with the system from Javascript. There is also a REST API. There isn't a well documented Javascript client, though.

### Describe the proposed behavior

A Typescript client with well defined data structures would greatly aid in integrating Prefect with Javascript back-ends (NodeJS, Deno) as well as web front-ends. This is a missing piece for integrating Prefect into stacks that are not just Python-based and would also ease integration in the browser.

### Additional context

It is very common to have a NodeJS back-end on a web application. The ability to launch and synchronize jobs between the Javascript back-end and the Python runtime would be a huge help when coordinating jobs across the stack.

**Comment by thatcort** [comment]
Hi, can this issue be re-opened, please? Still waiting to hear about a JS library for integrating with Prefect! @WillRaphaelson

**Comment by WillRaphaelson** [comment]
Thanks @thatcort - my colleague @abrookins will be in touch about this.

**Comment by abrookins** [comment]
Hey @thatcort! I'd love to talk to you about your use case. Can you DM me in the [Slack community](https://prefect-community.slack.com/)?

**Comment by bdeporteadditi** [comment]
Hey @abrookins 👋 !
Do you have any update on this ? We're very interesed on a Typescript SDK 👀
