### ISSUE TITLE
Unexpected behavior with logging when migrated to prefect2

### ISSUE THREAD

**Issue by StructNode** [PrefectHQ/prefect#8865]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When migrating from Prefect1 to Prefect2 I encountered a problem. Basically I call methods in Tasks and in those methods, I log my outputs to local .txt files.
When I run the flow with Prefect1 cloud, it works perfectly fine. But when I migrated to Prefect2 cloud, It doesn’t write logs to my local .txt files.
I tried so many things but none of them worked. Is there any possible solutions?

For example: I have some methods in task1.py in those methods I create some logs and I write those logs to a txt.

### Reproduction

```python3
# task1.py

import logging

logging.basicConfig(handlers=[logging.FileHandler(filename="DailyBase.txt",
                                                  encoding='utf-8', mode='a+')],
                    format="%(asctime)s | %(name)s:%(levelname)s | %(message)s",
                    datefmt="%F %A %T",
                    level=logging.WARNING)
logger = logging.getLogger()

class log_test():
    def __init__(self) -> None:
        pass

    def push_log(self):
        logger.warning('testing log')



# prefectfile.py

from prefect import flow,task
from task1 import log_test

@task()
def task1():
    Log = log_test()
    Log.push_log()

@flow(name='test_flow')
def log_flow():
    tassk = task1(return_state=True)
```

### Versions

```Text
Version:             2.8.5
API version:         0.8.4
Python version:      3.8.10
Git commit:          81a67202
Built:               Thu, Mar 9, 2023 4:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

![image (2)](https://user-images.githubusercontent.com/62254389/226644771-06133475-7449-46af-85c4-643246faa021.png)

**Comment by madkinsz** [comment]
Hi! `logging.basicConfig` is intended for simple scripts only and notes that it will not configure logging if logging has been configured already. Prefect configures logging through the Python-standard `logging.yml` file, I'd recommend configuring your file handler there. (https://github.com/PrefectHQ/prefect/blob/main/src/prefect/logging/logging.yml)

**Comment by StructNode** [comment]
Hi! Thank you for your replies.

logging.yml worked just fine but I have multiple .py files and in each file I save my logs to different .txt files. Because of that, I couldn't use logging.yml solution.

So I tried second solution like this;

```
import logging

logFormatter = logging.Formatter("%(asctime)s | %(name)s:%(levelname)s | %(message)s",datefmt="%F %A %T")
logger = logging.getLogger()
fileHandler = logging.FileHandler(filename=r"DailyBase.txt", encoding="utf-8", mode="a")
fileHandler.setFormatter(logFormatter)
logger.addHandler(fileHandler)

class log_test():
    def __init__(self) -> None:
        pass

    def push_log(self):
        logger.warning('testing log')
```


Unfortunately this solution doesn't worked either. I have also tried with `logger.setLevel(logging.WARNING).`
 Here is my log output;

```
14:55:46.351 | INFO    | prefect.agent - Submitting flow run '6e1d7362-d195-44f0-8cef-51a6b5ec1edd'
14:55:47.228 | INFO    | prefect.infrastructure.process - Opening process 'glossy-ostrich'...
14:55:47.429 | INFO    | prefect.agent - Completed submission of flow run '6e1d7362-d195-44f0-8cef-51a6b5ec1edd'
*\appdata\local\programs\python\python38\lib\runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
14:55:49.935 | INFO    | Flow run 'glossy-ostrich' - Downloading flow code from storage at 'C:\\Users\\BSandikci\\Desktop\\prefectlogging'
14:55:52.589 | INFO    | Flow run 'glossy-ostrich' - Created task run 'task1-0' for task 'task1'
14:55:52.590 | INFO    | Flow run 'glossy-ostrich' - Executing 'task1-0' immediately...
14:55:53.145 | INFO    | Task run 'task1-0' - Task run '64804aec-668f-4631-baa5-b3abc406bf57' already finished.
14:55:53.369 | INFO    | Flow run 'glossy-ostrich' - Finished in state Completed('All states completed.')
14:55:53.903 | INFO    | prefect.infrastructure.process - Process 'glossy-ostrich' exited cleanly.
```

**Comment by madkinsz** [comment]
You'll need to `import prefect` before you configure your loggers or we will override the handler you've added when we setup loggers.
