### ISSUE TITLE
Docker images after Prefect 2.8.2 may not work correctly with Azure Container Instances

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#8888]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Images built after Prefect version 2.8.2 appear not to work with some container services, in particular Azure Container Instances. The images also don't work with Docker's `docker manifest inspect` command.

I began investigating this issue after a user reported that Azure Container Instances would not run any of our images after `prefecthq/prefect:2.8.2-python3.10`. The user was able to run `prefecthq/prefect:2.8.2-python3.10`.

Docker's own `manifest inspect` command didn't work with these images when I tried to inspect them:
```
$ docker manifest inspect prefecthq/prefect:2.8.3-python3.10
no such manifest: docker.io/prefecthq/prefect:2.8.3-python3.10
```

Yet the same command works fine for earlier images -- the same ones that work on ACI:
```
$ docker manifest inspect prefecthq/prefect:2.8.2-python3.10
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3065,
         "digest": "sha256:c53148436b101a2f2d2c3aa8a8fca75ba1be2a168656ef1659bd95eb3828a422",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3065,
         "digest": "sha256:9dee956417cca7b62a8cf159d6f04587e24794b24d7f3aca761091be56ae066f",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

This led me to suspect that our build system started generating a different image artifact (in some way) after 2.8.2. [Docker's API](https://hub.docker.com/v2/repositories/prefecthq/prefect/tags/2-python3.10/) shows a new media type for the new, problematic images:

```
application/vnd.oci.image.index.v1+json
```

[Earlier images](https://hub.docker.com/v2/repositories/prefecthq/prefect/tags/2.8.2-python3.10/) use the V2 manifest type:

```
application/vnd.docker.distribution.manifest.list.v2+json
```

So, what could be going on here? 🤔 

Some spelunking led me to [this Ubuntu issue](https://bugs.launchpad.net/cloud-images/+bug/2004474) that sounded very similar. That issue led me to recent changes in `buildx`.

The [0.10.2 version](https://github.com/docker/buildx/releases/tag/v0.10.2) of `buildx` turns on SLSA attestation by default. As mentioned in the release notes, this attestation can cause problems with container services like Lambda, Google Cloud Run, and Azure Container Instances.

Ubuntu resolved their issue by disabling this new attestation, which I propose that we also do.

### Reproduction

```python3
# WIP
```

### Error

```python3
The error occurs when the container service tries to use one of our images. E.g., Azure Container Instances reports "the image... is not accessible."
```

### Versions

```Text
All Docker images after version 2.8.2 that I've tested look affected.
```

**Comment by madkinsz** [comment]
Oof. Thanks for the investigation!
