### ISSUE TITLE
Filter by work pool not filtering the "dot" graph

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8891]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When filtering by "work pool" in the flows screen, the "dots graph" is not filtered.
The "main-pool" is a pool I've just created, and there are no runs associated to it.

![CleanShot 2023-03-23 at 08 02 45@2x](https://user-images.githubusercontent.com/5398977/227117523-885b8337-37cc-4c87-80a4-f58b8c5e2526.jpg)

### Reproduction

```python3
Create a new "work flow".
Make sure it's empty and has no runs in it.
Go to the flows screen, and filter by this work pool.
You'll see that all the dots on the graph remain although they are not related to that work pool.
```

### Versions

```Text
Prefect cloud
```

**Comment by yaronlevi** [comment]
Hi,
Bumping this issue.
Would it be possible to take a look?
Maybe I am missing something and it's not an issue at all?

**Comment by zhen0** [comment]
Thanks for bumping @yaronlevi - I've added this to our backlog
