### ISSUE TITLE
Remove task_run_state_cache entry if result no longer exists

### ISSUE THREAD

**Issue by limx0** [PrefectHQ/prefect#8892]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If a task which is cached has its result removed from storage, prefect just throws an exception:

```python
File "lib/python3.10/site-packages/prefect/engine.py", line 1114, in get_task_call_return_value
    return await future._result()
  File "lib/python3.10/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "lib/python3.10/site-packages/prefect/states.py", line 98, in _get_state_result
    result = await state.data.get()
  File "lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "lib/python3.10/site-packages/prefect/results.py", line 446, in get
    blob = await self._read_blob(client=client)
  File "lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "lib/python3.10/site-packages/prefect/results.py", line 458, in _read_blob
    content = await storage_block.read_path(self.storage_key)
  File "lib/python3.10/site-packages/prefect/filesystems.py", line 202, in read_path
    raise ValueError(f"Path {path} does not exist.")
  ValueError: Path ~/.prefect/storage/6cd004d80de84e66b6ee075dfc620d68 does not exist.
```

### Describe the proposed behavior

It would be great if prefect would purge the task_run_state_cache entry from the database. If the result no longer exists, there isn't much point keeping the entry, and we could continue with the flow in this instance.

### Additional context

To replicate, run the following

```python

@prefect_task(persist_result=True, cache_key_fn=task_input_hash)
def get():
    return 1

@flow
def myflow():
    return get()

if __name__ == '__main__':
    myflow()
```

Then delete the key in `~/.prefect/storage` and re-run.

**Comment by rsampaths16** [comment]
I'm not sure if this behaviour should be supported in a naive way. An exception would occur even when the storage is (~temporarily) down.

**Comment by limx0** [comment]
^ That is a very good point @rsampaths16.

Safer proposals:
- opt-in clear-on-miss or 
- expose a REST api endpoint to allow deleting up the task_run_state_cache keys.

**Comment by billpalombi** [comment]
Yes, I we believe that that best solution ultimately comes down to exposing better cache management tools. Please follow along with #8239 for our progress. I'm going to close this ticket since we've had more discussion there.

**Comment by PiotrSiejda** [comment]
This possibility was never exposed and #8239 was closed while fixing another thing. I guess that this ticket should be reopened or a new ticket should be created.
