### ISSUE TITLE
[Review] Accept `functions` and `objects` to `flow_run_name` and `task_run_name`

### ISSUE THREAD

**Issue by rsampaths16** [PrefectHQ/prefect#8895]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently we can set a `flow_run_name` for a flow run and a `task_run_name` for a task run via template strings. The template string is limited to the parameters passed.

### Describe the proposed behavior

Accept a `Callable[Any] -> str` for `flow_run_name` and `task_run_name`. It will enable us to provide some dynamisim to naming the runs. Additionally apart from the parameters, even flow run context and task run context can be passed to them.

Even a type / subtype can be accepted whose constructor accept context and the generator function accept the parameters

### Example Use

```python
def flow_run_name_generator(flow_run_context, **kwargs):
    ... fetch useful context from flow run context
    ... fetch useful information from parameters
    ... fetch other useful context
    ... generate a run name and return string


@flow(flow_run_name=flow_run_name_generator)
def my_flow(arg1):
    pass
```

or

```python
# FlowRunNameGenerator base provided by prefect
class CustomFlowRunNameGenerator(FlowRunNameGenerator):
    def __init__(self, flow_run_context):
        super().__init__(flow_run_context)
    
    # overrides base method
    def generate(self, **kwargs) -> str:
        ... fetch useful context from flow run context
        ... fetch useful information from parameters
        ... fetch other useful context
        ... generate a run name and return string

@flow(flow_run_name=CustomFlowRunNameGenerator)
def my_flow(arg1):
    pass
```

similar support for `task_run_name`

### Additional context

I believe a function can be monkey-patched if we send an object with `format(**kwargs)` method, but an official support will be more appreciated. It should be possible to support both a function and subclasses for the same argument by using isinstance checks `e.g. isinstance(flow_run_name, str), isinstance(flow_run_name, Callable), isinstance(flow_run_name, type)`

**Comment by billpalombi** [comment]
Thanks for submitting this enhancement request! We would definitely like to do this, though it may be some time before we get to it.

**Comment by rsampaths16** [comment]
Hi @billpalombi it'd be really helpful if the proposal is reviewed to know if it is good enough for implementation, or if some modifications are needed.

**Comment by madkinsz** [comment]
I think that we would probably want to rely on the `prefect.runtime` module for injection of contextual information now. I don't think we should support object-based configuration. I think the type would be `Callable[[Dict[str, Any]], str]`.

**Comment by rsampaths16** [comment]
Hey, can this be reviewed please: https://github.com/PrefectHQ/prefect/pull/8933 Thanks!
