### ISSUE TITLE
New flow UI does not show in browser Brave for new Prefect 2.8.7 

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect#8916]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

New flow UI does not show in browser Brave which is Chromium based browser for new Prefect 2.8.7

(BTW, really nice new UI 😃)

Brave Version 1.49.120 Chromium: 111.0.5563.64 (official Build) (arm64)

<img width="1756" alt="image" src="https://user-images.githubusercontent.com/3375461/227418418-deed18c2-3eac-415a-b3a6-6ba5f5911cc6.png">

Chrome, Firefox, Safari have no issues

<img width="1821" alt="image" src="https://user-images.githubusercontent.com/3375461/227419156-58e1c870-4daf-4b20-8a7e-fcba63b669ce.png">

### Reproduction

Download [Brave](https://brave.com/), and open one workflow chart.

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.11.2
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             darwin/arm64
Profile:             hm-kubernetes
Server type:         server
```

**Comment by brandonreid** [comment]
@Hongbo-Miao Could you try again? I can't seem to reproduce.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/6776415/227602641-73a8956a-a493-407d-82be-d21bffe7eda9.png">

**Comment by brandonreid** [comment]
Ahh, thank you for discovering that @Hongbo-Miao! This uses WebGL, so rely's on the GPU. I should at least add a message to the UI about that.

Thanks again!
