### ISSUE TITLE
Add documentation for checkpointing

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#892]
We currently don't mention checkpointing in the docs, we should add a blurb about this (possibly to https://docs.prefect.io/guide/core_concepts/execution.html#caching)

**cc:** @TylerWanner for pointing this out

**Comment by yozlet** [comment]
Not sure if this is the best place to mention this, but: as a newcomer, I've been trying to work out where/how the cache (or anything else) is stored, and I can't find anything in the docs. Presumably there's some kind of storage system in use (files? DB?) but I seem to be missing the documentation that talks about it. (And no, I've not installed Prefect yet, but I hope you'll agree that the docs should be talking about this _somewhere_.)

**Comment by cicdw** [comment]
Hi @yozlet - fair question.  This release of Prefect contains our workflow _engine_, so all storage of state information / caching will occur _in memory_.   Of course, all of the hooks are there for more persistent storage of states and we will document these hooks better in the very near future.

**Comment by cicdw** [comment]
Closed with #1555
