### ISSUE TITLE
Rendering thousands of tasks causes UI to consume alot of memory or crash

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#8934]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

As a user who runs a large workflows which usually consists of thousands of tasks. UI visuals start to cause problems as it can't handle the huge number of tasks. however, Dask can handle the same number of tasks easily as shown below 

![image](https://user-images.githubusercontent.com/16452985/227762127-3336a483-f36f-43f5-87b9-4c6ae6240269.png)

### Reproduction

Any workflow with a large number of tasks >= 5K

### Error

-

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Prefect version

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.11.2
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by brandonreid** [comment]
@BitTheByte the latest release includes some improvements that should help a lot with this scenario. Could I ask you to take another look and let me know how the graph performance is now? It may still be slow to start, but hopefully doesn't crash anything and is usable.

**Comment by brandonreid** [comment]
Going to close this for now. We'll continue to monitor and improve performance of this graph. Thanks for reporting @BitTheByte!
