### ISSUE TITLE
SQLite database backend stability during large flows

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#8935]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm aware that using prefect cloud should resolve this problem however, I feel like it shouldn't be a problem running a flow consisting of 1k tasks on modern hardware. Running the code below will result in several different errors 
```
asyncio.exceptions.CancelledError
sqlite3.OperationalError: no active connection
sqlite3.OperationalError: database is locked
RuntimeError: Event loop is closed
```

### Reproduction

```python3
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner


@task
def dummy_task():
    from time import sleep
    sleep(1)
    return 1


@flow(
    task_runner=DaskTaskRunner(
        cluster_class="dask.distributed.LocalCluster",
        adapt_kwargs={
            "minimum": 1,
            "maximum": 1,
        },
        cluster_kwargs={
            "processes": False,
            "n_workers": 1,
            "threads_per_worker": 1,
        }
    )
)
def test_flow():
    futures = []
    for i in range(1_000):
        futures.append(
            dummy_task.submit()
        )


if __name__ == "__main__":
    test_flow()
```

### Error

```python3
-
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4                    
Python version:      3.10.8                   
Git commit:          a6d6c6fc                 
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             linux/x86_64             
Profile:             default                  
Server type:         ephemeral                
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

**Comment by madkinsz** [comment]
Hey @BitTheByte we're intending to improve stability here (e.g. #8903) but SQLite is not designed to handle this level of concurrent writers and I would highly recommend switching to a different database backend if you are running tasks at scale.

**Comment by dyspr0sium** [comment]
I am using both the prefect server and postgresql with prefect 2.8.7, i.e.
```
PREFECT_API_URL=http://127.0.0.1:4200/api
PREFECT_API_DATABASE_CONNECTION_URL="postgresql+asyncpg://postgres:password@localhost:5432/prefect"
```
and with a large flow (more than 10,000 tasks), it's still a dice roll if I am able to get all the tasks successfully submitted without crashing, with `PrefectHTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:4200/api/task_runs` seeming to be the most common one, but I do recall  `asyncio.exceptions.CancelledError` and `sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00` appearing as well, so the issue is not simply SQLite. 

Happy to make a separate issue if necessary, but just wanted to add extra information to this one since it does relate to stability of large flows.

**Comment by madkinsz** [comment]
On this issue, the main error is the "database is locked" — the rest is just the process tearing down from what I've seen.

**Comment by justquick** [comment]
Also seeing this issue trying to load +4M rows from 612 CSV files  and writ them to a pystore collection. im using  the following flow.

prefect==2.10.11
Python 3.10.8

```python
@task
def load(fn):
    df = pd.read_csv(fn)
    df['Date'] = pd.to_datetime(df['Date'].apply(custom_date_parser))
    df.set_index('Date', inplace=True, drop=True)
    coll.write(fn.stem, df, overwrite=True)


@flow
def my_flow():
    for fn in Path('../data/sheets').glob('*.csv'):
        load.submit(fn)
```

Working fine for the first few hundred flows but then it's been throwing the following:

```pytb
Traceback (most recent call last):
  File "/Users/jquick/.local/share/virtualenvs/pre-osrBzrNz/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in rollback
    self.await_(self._connection.rollback())
  File "/Users/jquick/.local/share/virtualenvs/pre-osrBzrNz/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/Users/jquick/.local/share/virtualenvs/pre-osrBzrNz/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 187, in greenlet_spawn
    value = await result
  File "/Users/jquick/.local/share/virtualenvs/pre-osrBzrNz/lib/python3.10/site-packages/aiosqlite/core.py", line 170, in rollback
    await self._execute(self._conn.rollback)
  File "/Users/jquick/.local/share/virtualenvs/pre-osrBzrNz/lib/python3.10/site-packages/aiosqlite/core.py", line 75, in _conn
    raise ValueError("no active connection")
ValueError: no active connection
```

**Comment by madkinsz** [comment]
@justquick Can you share the full traceback?

@jakekaplan This appears to be a new error now that we've resolved the other ones :) Let's try to get a 503 response for this case.

**Comment by madkinsz** [comment]
@BitTheByte fyi I've made loads of progress on this in
- #9594
- https://github.com/PrefectHQ/prefect/pull/9633
- https://github.com/PrefectHQ/prefect/pull/9632

**Comment by justquick** [comment]
@madkinsz that is the whole traceback

**Comment by madkinsz** [comment]
@justquick that's unfortunate I'd expect a bunch more context to be there. Would you mind opening a new issue with an MRE?
