### ISSUE TITLE
Add ping and health endpoints on the Server

### ISSUE THREAD

**Issue by davzucky** [PrefectHQ/prefect#8940]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

At the moment, the deployment of the Prefect server on Kubernetes doesn't have any liveness or readiness probe enabled. An issue has been opened here to get them added after the server supports new endpoints
https://github.com/PrefectHQ/prefect-helm/issues/132

### Describe the proposed behavior

Prefect Server should have two extras endpoints
- ```/ping```, which allows liveness to be checked
- ```/health``` which would allow the readiness state to be checked, ensuring the db was updated

 ### Example Use

At the moment, the health endpoint exists under ```/api/health``` and the ping doesn't exist, however the ```/api/hello``` could be used as a proxy

_No response_

**Comment by parkedwards** [comment]
thanks for this suggestion, @davzucky.  after #9701 + the corresponding server release, we'll now have a `GET /api/ready` endpoint that will perform a db check; you can use this endpoint for any readiness probes (which we will also add to the helm chart shortly)

in terms of the liveness check, please continue to use `GET /api/hello` (or `GET /api/health`).  the `/metrics` endpoint is one we're currently discussing internally, but agree that it's something we'll want to do

**Comment by davzucky** [comment]
Thank you, @parkedwards, for all the updates and work. I will update Prefect in the coming weeks
