### ISSUE TITLE
Automations are not triggered on tagged local flow runs

### ISSUE THREAD

**Issue by tsteijvers** [PrefectHQ/prefect#8943]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When executing a flow run from my local dev machine, an automation based on flow run tags is not triggered. See also https://prefect-community.slack.com/archives/CL09KU1K7/p1679396644710099.

### Reproduction

1. Create an automation on "Flow run state" for "All flows" based on Flow Run Tags = "local" and "Flow Run enters Any state".
2. Create a myflow.py:
    ```python3
    @flow
    def myflow():
        get_run_logger().info("Hello Myflow")

    if __name__ == "__main__":
        with tags(["local"]):
            myflow()
    ```
3. Run the flow `python myflow.py` from your local dev machine.

**The automation is not triggered, although the flow run is visible in the Prefect UI.**

4. Create and register a deployment for the flow. You can now see the deployment in the Prefect UI.
5. Start a flow run from the deployment in the Prefect UI.

**The automation is triggered as expected.**

### Error
Automation is not triggered when running a flow locally (step 3).

### Versions
```Text
Version:             2.7.9
API version:         0.8.4
Python version:      3.9.13
```

**Comment by bunchesofdonald** [comment]
The fix for this has been deployed to production and I was able to trigger an automation using `tags`. @tsteijvers if you're still seeing issues feel free to re-open this issue.
