### ISSUE TITLE
`on_completion` and `on_failure` are not discussed in the docs

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#8967]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`on_completion` and `on_failure` are not discussed in the docs.

### Reproduction

```python3
Searched in the docs and discussed in OH.
```

### Versions

```Text
Noted in 2.8.3 release notes, but not in docs as of 2023-03-28.
```

**Comment by discdiver** [comment]
@rpeden has a WIP here :)

**Comment by sckott** [comment]
Some docs would be great :)
