### ISSUE TITLE
Flow Cancelling not transitioning to Cancelled

### ISSUE THREAD

**Issue by Samreay** [PrefectHQ/prefect#8972]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I cancel flows, they transition into cancelling. They do not transition into cancelled.

Heres a screesnhot of my flow runs filtered by cancelling.

<img width="2256" alt="image" src="https://user-images.githubusercontent.com/6748505/228398540-f307b233-206a-4b3c-9d1e-a00de2a3787c.png">

If I take the oldest flow cancelled and click through, you can see that all the task runs are cancelled.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/6748505/228398640-035e6b2c-4abd-4214-a157-a60e4ea1cf1b.png">

Im not sure what exactly transitions from cancelling to cancelled, but I would expect that all task runs being cancelled would have been the kicker.

### Reproduction

```python3
I cancel any flow.
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.9.12
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
```

**Comment by zhen0** [comment]
Thanks for the issue @Samreay Can you add a bit more info about how you're canceling your runs - for example:

Are you using the cancel button in the UI? 

Are the runs ones kicked off from a deployment or a locally run flow?

**Comment by Samreay** [comment]
I'm using the cancel button in the UI, and the flows originate from a scheduled RRule deployment

**Comment by zhen0** [comment]
@Samreay sorry for all the questions - can you also add what state those runs were in before they were cancelled?

Possibly related - https://github.com/PrefectHQ/prefect/issues/8194

**Comment by cumulus-nrussell** [comment]
We have an automation set up that is designed to cancel flows that have been running for too long, and it rarely works because the flows simply transition from being stuck in "Running" to being stuck in "Cancelling".

**Comment by madkinsz** [comment]
@cumulus-nrussell Can you please include some agent logs for the given flow run especially around the time when it gets cancelled?

**Comment by Samreay** [comment]
> @Samreay sorry for all the questions - can you also add what state those runs were in before they were cancelled?
> 
> Possibly related - #8194

Sorry didn't have a chance to go through the logs in the agent yet, but can confirm they were Running, not scheduled.

**Comment by Samreay** [comment]
Okay, I've just tested this one with the AWS logging up, and literally nothing looks wrong. I cancel the flow "mu2-cuello-h" (autogenerated name), and a moment later I see:

`05:22:01.508 \| INFO \| prefect.infrastructure.process - Process 'mu2-cuello-h' exited cleanly.`

in the logs. 

![image](https://user-images.githubusercontent.com/6748505/229418760-5c0abe9f-7249-4a00-a5cd-510dd1567535.png)

And the tasks cancel properly, but the flow itself stays in "cancelling", both in the flow run page and the flow page itself:

![image](https://user-images.githubusercontent.com/6748505/229418853-4677bf8d-39d1-416d-8992-0018fe1dfd59.png)
