### ISSUE TITLE
Support `MySQL` and `MsSQL` as a backend databases for Prefect

### ISSUE THREAD

**Issue by rsampaths16** [PrefectHQ/prefect#8975]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently `sqlite` and `postgresql` are the only supported backend databases;

https://github.com/PrefectHQ/prefect/blob/7c35fade3353971ff90ef8f4f7c20f75063162bb/src/prefect/server/database/dependencies.py#L77-L86

### Describe the proposed behavior

Support for using `mysql` and `mssql` as backend databases ( or ) provide a way to hotwire support to additional backends or at-least the ones supported by `sqlalchemy`

### Example Use

```
prefect config set PREFECT_API_DATABASE_CONNECTION_URL="mysql+asyncmy://mysql:yourTopSecretPassword@localhost:5432/prefect"
```

**Comment by madkinsz** [comment]
Unfortunately I cannot find the other issue where we discussed this, but adding another database backend would require maintenance of the database migrations which we cannot do at this time as maintaining two sets of database migrations currently is quite a bit of work.

**Comment by charmby** [comment]
ValueError: Unable to infer database configuration from provided dialect. Got dialect name 'mysql'
cannot use mysql
