### ISSUE TITLE
Improve error message when deploying a flow to an unknown or missing project

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#898]
Right now we say "Project not found, run client.create_project() to create it"

It would be a big UX improvement to also show the projects the user DOES have, so they don't have to go look up the name if they mistyped it or didn't provide it at all.

**Comment by cicdw** [comment]
@jlowin would you consider this closed with the CLI `prefect get projects`?

**Comment by jlowin** [comment]
👍
