### ISSUE TITLE
Submitting many concurrent tasks causes the flow to be stuck

### ISSUE THREAD

**Issue by lucawork** [PrefectHQ/prefect#8982]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If is submit many tasks at the same time the tasks and thus the flow never finishes. The limit when this starts to happen seems to depend on the machine.

* on windows with WSL 10 submits is enough to lock up the flow
* on most other machines more tasks are needed (the 1000 in the example does the trick)
* on our production machine the flows gets stuck every so often (~20 concurrent tasks)

### Reproduction

```python3
import time
from prefect import task, flow, get_run_logger

@task
def my_task(i):
    logger = get_run_logger()
    logger.info(f"Task start {i}")
    time.sleep(0.5)

@flow
def my_flow():
    for i in range(1000):
        my_task.submit(i)

my_flow()
```

### Error

```python3
The execution get stuck, the status of the flow is running but it persist in that state without proceeding.
```

### Versions

```Text
prefect 2.8.7
```

### Additional context

The issue on the production machine only showed up after upgrading from Prefect 2.7.9 (might be a coincidence tho)

**Comment by madkinsz** [comment]
What is the last log message the flow run emits before hanging?

**Comment by felix-ht** [comment]
@madkinsz we are using prefect cloud if that is what you are asking

```
19:07:05.413 | INFO    | Flow run 'mellow-groundhog' - Created task run 'my_task-998' for task 'my_task'
19:07:05.413 | INFO    | Flow run 'mellow-groundhog' - Submitted task run 'my_task-998' for execution.
19:07:05.598 | INFO    | Flow run 'mellow-groundhog' - Created task run 'my_task-993' for task 'my_task'
19:07:05.599 | INFO    | Flow run 'mellow-groundhog' - Submitted task run 'my_task-993' for execution.
19:07:05.654 | INFO    | Flow run 'mellow-groundhog' - Created task run 'my_task-994' for task 'my_task'
19:07:05.654 | INFO    | Flow run 'mellow-groundhog' - Submitted task run 'my_task-994' for execution.
19:07:05.867 | INFO    | Flow run 'mellow-groundhog' - Created task run 'my_task-999' for task 'my_task'
19:07:05.868 | INFO    | Flow run 'mellow-groundhog' - Submitted task run 'my_task-999' for execution.
```

Turns out that if you wait long enough the tasks start finishing (on my mac). In Production we had flows stuck for hours tho.

**Comment by madkinsz** [comment]
@felix-ht I've run the code successfully with more tasks than that. I'm seeing some behavior where the log worker is stuck shutting down, I'll investigate a fix for that but from the logs you've shared that does not appear to be the issue here.

**Comment by madkinsz** [comment]
Can you share the Python version you are using as well?

**Comment by felix-ht** [comment]
@madkinsz  Python 3.10.4

**Comment by madkinsz** [comment]
Thanks for the additional details!

> In the example on my machine, none of the tasks finish until all of them are submittted. After all of them are submitted it takes ~ 1 minute until the first one starts and an other 1 minute until one of them completes.

Yeah this is an interesting problem that I believe is because the requests are queued on the client so all of the task run creation requests happen before the requests proposing transition to a running state happen. 

Are you seeing high CPU consumption on WSL while it's stuck?

**Comment by felix-ht** [comment]
How it looks on my machine

https://user-images.githubusercontent.com/24698503/228621096-51a9fc89-f2ec-4f52-91da-dba51fdf9fbc.mp4

**Comment by BitTheByte** [comment]
I do also experience this, from time to time but I figured it it's from event loop being busy with another tasks as it will eventually will start submitting again

**Comment by BitTheByte** [comment]
Hey @madkinsz I'll be able to confirm this after `2.10.2` our pipelines are now on `2.10.1` once the deployment issue is fixed we'll be ready to go, we experience this issue daily.

**Comment by BitTheByte** [comment]
`2.10.2` works like a charm!

**Comment by BitTheByte** [comment]
does seem to be related to https://github.com/PrefectHQ/prefect/pull/8983

**Comment by BitTheByte** [comment]
```python
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner


task_runner = DaskTaskRunner(
    cluster_class="dask.distributed.LocalCluster",
    cluster_kwargs={
        "processes": False,
        "n_workers": 1,
        "threads_per_worker": 1
    }
)


@task
def dummy_task(x):
    return x


@flow(task_runner=task_runner)
def test_flow():
    dummy_task.map(range(1000))


if __name__ == "__main__":
    test_flow()
```

**Comment by madkinsz** [comment]
@BitTheByte thanks for the report — that is actually related to #9048 and #9045. We'll investigate.
