### ISSUE TITLE
EXTRA_PIP_PACKAGES not respected for custom image on Kubernetes Job

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#8988]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have the following configuration for a flow: 
- KubernetesJob infrastructure block with custom public image passed in that does not have the gcsfs package installed initially. Environment variable with EXTRA_PIP_PACKAGES is passed in. 
- GCS storage block that requires gcsfs package to be installed. 

The flow run fails and says that the gcsfs module cannot be found, even though it was included in the EXTRA_PIP_PACKAGES environment variable. 

### Reproduction

```python3
Extra Pip Packages Config: 

{
  "EXTRA_PIP_PACKAGES": "gcsfs"
}

Dockerfile: 

FROM python:3.10-slim
RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

RUN apt-get install git -y

COPY requirements.txt .
RUN pip install -r requirements.txt --trusted-host pypi.python.org --no-cache-dir
```

### Error

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 266, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 174, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 557, in get_directory
    return await self.filesystem.get_directory(
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 314, in get_directory
    return self.filesystem.get(from_path, local_path, recursive=True)
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 398, in filesystem
    raise RuntimeError(
RuntimeError: File system created with scheme 'gcs' from base path 'gcs://rf-cs-test-bucket' could not be created. You are likely missing a Python module required to use the given storage protocol.
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.10.10
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             darwin/arm64
Profile:             radiant
Server type:         cloud
```

### Additional context

The flow runs correctly when using the base Prefect image with EXTRA_PIP_PACKAGES or by including the gcsfs package in the custom image, but fails when there is a custom image without gcsfs and the package is defined in the EXTRA_PIP_PACKAGES.  

Not sure if this is expected behavior for EXTRA_PIP_PACKAGES when running with a custom image, but might be worth a discussion about best practices in terms of where to import packages for this infrastructure pattern/including in the documents.

**Comment by robfreedy** [comment]
For reference as well, this is the custom image that I passed into my KubernetesJob block: https://hub.docker.com/repository/docker/robfreedy1/robfreedy1-test-image/general

**Comment by rpeden** [comment]
`EXTRA_PIP_PACKAGES` works on Prefect images because they use [this entrypoint script](https://github.com/PrefectHQ/prefect/blob/main/scripts/entrypoint.sh) as an entrypoint. 

Custom images would need to use that script or something equivalent to read the `EXTRA_PIP_PACKAGES` environment variable and install any needed pip package before running the command passed to the container.

**Comment by rpeden** [comment]
We note this [in the docs](https://docs.prefect.io/concepts/infrastructure/#installing-extra-dependencies-at-runtime), but if you run into any _other_ places in the docs that are ambiguous about this aspect of `EXTRA_PIP_PACKAGES` please feel free to open a docs issue so we can fix it. 😄

**Comment by robfreedy** [comment]
Makes sense. Is there somewhere we could add in the docs that the EXTRA_PIP_PACKAGES is only configured for Prefect base images?

**Comment by rpeden** [comment]
I'm updating the parts of the docs where it is missing 😄
