### ISSUE TITLE
Auto-generate example documentation

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#900]
Examples like #897 are fantastic, but only visible in the source code. It would be great to create a utility function in Vuepress' `config.js` that would automatically turn the Python code into a markdown file so that examples could be displayed in the docs without having to duplicate the code (and therefore maintain two versions of it). By doing this on a file-by-file basis, it would allow more "full" markdown files to be included in the examples directory if users desired.

**Comment by ntaylorwss** [comment]
Just a thought: is there room for writing examples as Jupyter Notebooks? It might allow for more discussion/explanation and a clearly documented thought process for more involved Flows. I have no idea how Vuepress works, but it might also display nicely. Particularly with the cell output showing logging and allowing for inspection of the results (such as showing the shape of the Numpy arrays that result from the Flow in #897).

**Comment by jlowin** [comment]
That's a pretty awesome idea, and absolutely. We've actually got a utility for transforming our tutorials into notebooks automatically, though it might be dormant at the moment. We can use VuePress to render out any markdown/html export, or potentially we could use something like Binder to allow live execution in-browser...

cc @cicdw

**Comment by hoangthienan95** [comment]
[Jupytext](https://github.com/mwouts/jupytext) provides the ability to convert notebooks to and from many extensions, including markdown/`.py`!

**Comment by cicdw** [comment]
Closing as stale given our migrations to new doc tooling
