### ISSUE TITLE
Handle "unsupported callables" for task arg introspection

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#901]
Follow up from https://github.com/PrefectHQ/prefect/pull/897#discussion_r272286805

Builtin functions and functions like `np.dot` are "unsupported callables" because `inspect` can't determine their signature, which means we can't build arguments automatically. For example, this fails:

```pytyon
prefect.task(np.dot)(x, y)
```

Currently, functions like this need to be nested in a pure-Python function:

```python
@task
def mydot(x, y):
    return np.dot(x, y)
```

**Comment by ntaylorwss** [comment]
How strange. I tried just about every inspection library I could think of:
`inspect.signature(np.dot) --> ValueError: no signature found for builtin <built-in function dot>`
`dis.dis(np.dot) --> TypeError: don't know how to disassemble builtin_function_or_method objects`
`dill.source.getsource(np.dot) --> OSError: could not find class definition`

Nothing seems to be able to get at the source of Numpy's builtins.

Looking into Numpy source, it seems like something even they haven't found a way around: https://github.com/numpy/numpy/blob/master/numpy/core/multiarray.py#L66

So the signature is right there in the file, and the file would no doubt be on the machine / in the container of the user. Which makes it seem like there has to be some way to at least get the signature as a string. But I haven't found it yet.

**Comment by cicdw** [comment]
Purely for informational purposes: the way Python interfaces with CPython is via "code objects" which describe how a block of Python code should be executed by CPython.  For standard Python objects (like the ones we all create), Python creates a code object for you:
```python
def f(x, y):
    pass

f.__code__
# code-object

f.__code__.co_varnames
# ('x', 'y')
```
As you can see, the code object contains information about the call signature.  I'm fairly certain all of these "inspection" packages inspect this code object.  

However, for built-ins (and also numpy) which themselves are basically just interfaces to C / CPython code, Python doesn't do this nice step for us (the step has already been done behind the scenes, in a sense).  Consequently there's no nicely packaged code object to inspect, and they error out.

[the-more-you-know.jpg]
