### ISSUE TITLE
make user config should create default

### ISSUE THREAD

**Issue by TylerWanner** [PrefectHQ/prefect#904]
User configurability may be unclear to the user, so I think `prefect make-user-config` should give the user more guidance about their options than an empty file

I propose that it should copy the defaults to the user config location

However, I could just as easily see doing both of the following, instead of this PR--
1) adding a note to the `prefect make-user-config` part of the docs (docs/guide/core_concepts) about where to find the default file 
2) adding "the default configuration is located at src/prefect/config.toml" to the auto-generated settings file

**Comment by joshmeek** [comment]
I'm not sure what this is saying? You want to put those two options in to overwrite the prefect config by default?

**Comment by TylerWanner** [comment]
Sorry.  It's not just those two options.  It copies the default config from src/prefect/config.toml to the user config location

**Comment by joshmeek** [comment]
Why does it need to copy the default config? This is only for overriding config options.

**Comment by cicdw** [comment]
Hey @TylerWanner for posterity / documentation purposes, would you mind reformatting the statement of this issue and include some additional details:
- what is the current issue (in this case, I think you don't know the structure of a Prefect user config file and you think `prefect make-user-config` should give you more guidance than an empty file, which I agree with)
- what is your proposal to fix it (e.g., it should copy all defaults to your user config location)

**Comment by cicdw** [comment]
I personally prefer option 2 [adding the default file location to the auto-generated settings file (as it exists now)] because it requires less back-and-forth on the user's end.  It's also the way I have my user config setup.  There's very little cost to copying the whole file.

**Comment by TylerWanner** [comment]
Option 2 is just adding the LOCATION of the file (like "the default file is located at src/prefect/config.toml") AND to the configuration.md
Option 1 is what is in this PR now

**Comment by cicdw** [comment]
comment: _updated_

**Comment by cicdw** [comment]
Per the conversation in https://github.com/PrefectHQ/prefect/pull/905 + a short conversation offline, we have reached consensus to delete the `make-user-config` endpoint all together and host the most up-to-date `config` file in the API reference docs.
