### ISSUE TITLE
Allow artifacts to be viewed from flow run or task run page.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9042]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, there is a single “artifacts” page that contains ALL artifacts generated by all flow/tasks. I can understand why this may be helpful if an artifact (e.g. a list of items that is useful for user) is updated by multiple flow/tasks, but it makes our specific use case (creating 1 markdown artifact per task run, put custom logging/metadata in there) a bit awkward.

### Describe the proposed behavior

You can imagine with hundreds of flows, each having tens of tasks running, this will swarm the shared artifacts page:

User will need to navigate many steps if they want to check the artifact generated by a specific task run in the UI:

o   Copy the flow run, task run name

o   Replace any whitespace with dashes to conform with the artifact key format

o   Search in the artifacts page

(Whereas in Prefect 1 this is really simple, people can directly see artifacts created by each task run in a flow run)

Is it possible to have a similar artifacts tab in the flow run (even task run) page? Since the new artifact function actually records which flow/task run it is originating from, I feel like this is more an UI/UX problem.

**Comment by zhen0** [comment]
I think this should be resolved by updates from @znicholasbrown - tracked separately in https://github.com/PrefectHQ/prefect/issues/9087

**Comment by zhen0** [comment]
Closing as complete as the cloud and oss ui now have artifacts tabs on the flow run page
