### ISSUE TITLE
Flow canceled for no reason (maybe related to Automation)

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#9053]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I've got an email for the flow being canceled but when looking at it, everything is good.

![CleanShot 2023-04-04 at 09 22 34@2x](https://user-images.githubusercontent.com/5398977/229705342-c497e044-32de-4a4f-aa50-ac7632bb2b62.jpg)

But the flow is perfectly fine:

![CleanShot 2023-04-04 at 09 23 05@2x](https://user-images.githubusercontent.com/5398977/229705442-77d57bac-38fe-4bbe-b1c3-35f55ecc6c11.jpg)

Link to the flow:
https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/263c3aa8-a416-41c1-8ae1-180faa674278

### Reproduction

```python3
Not sure, there was nothing special about this flow.
```

### Versions

```Text
Prefect cloud.
```

**Comment by yaronlevi** [comment]
Just to add more context. We have this automation defined:

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/automations/automation/680f2cc6-4ad7-4d3f-9d8f-23b35fabc627

![CleanShot 2023-04-04 at 09 27 14@2x](https://user-images.githubusercontent.com/5398977/229706313-cdbb09f6-6089-49d0-85cb-1eeef8df8f3f.jpg)

![CleanShot 2023-04-04 at 09 27 28@2x](https://user-images.githubusercontent.com/5398977/229706359-cc063664-22ce-4316-9d1b-61f382955d35.jpg)

It should trigger after 12 hours of being in RUNNING mode.

**Comment by WillRaphaelson** [comment]
Thanks @yaronlevi, I'll look into this and let you know if I have any questions.

**Comment by WillRaphaelson** [comment]
Hi @yaronlevi, this is related to the partial service degradation we experienced yesterday. Sorry about that. This should just be a one off and shouldn't happen again, so I'm going to close this out, but please feel free to reopen or file another if it reoccurs. Thanks for filing.

**Comment by yaronlevi** [comment]
@WillRaphaelson This seems to still happen:

![CleanShot 2023-04-04 at 19 37 32@2x](https://user-images.githubusercontent.com/5398977/229859215-97e874e4-196d-4364-a900-ecd55487c102.jpg)

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/af027312-a52a-497b-8b97-7ee85c32379d

**Comment by WillRaphaelson** [comment]
Thanks @yaronlevi, and sorry about that. I spoke too soon before but I actually think that the fallout from the incident is now over. I am looking into ways to ensure the quick processing of automations moving forward, even under load/service degradation.

**Comment by yaronlevi** [comment]
Hi (-:

Just updating you that the issue still happening. For example, for this flow, an automation was fired when it shouldn’t:

https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/e2af482e-e5df-428f-99b1-4cc40c1891e7

![CleanShot 2023-04-22 at 09 10 28@2x](https://user-images.githubusercontent.com/5398977/233766141-e828910c-f30e-445c-888e-af4bfb0e5f8c.jpg)

![CleanShot 2023-04-22 at 09 11 11@2x](https://user-images.githubusercontent.com/5398977/233766166-7897dc67-d48e-4968-8767-10b7ae7c91d7.jpg)

![CleanShot 2023-04-22 at 09 12 21@2x](https://user-images.githubusercontent.com/5398977/233766215-b44dbb0e-7721-4b2e-ab33-2a4f759e208d.jpg)

@WillRaphaelson Maybe there was a second outage?
