### ISSUE TITLE
Add support for `tags` in Flow/flow similar to Task/task.

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#9078]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

`prefect.flow` does not support `tags` arguments. Currently, to add tags to flow, we have to use `prefect.tags` context managers ; however this takes the control of tagging away from the developers.

E.g. usecase: There is not means for a developer to set tags as follows.
```
Deployment with tags: `author:USER_EMAIL_HERE`
Deployed Flow with tag: `flow_type:deployed,scheduled`
Dynamic Sub flows with tags: `flow_type:dynamic`
Task tags: `some_task_concurrency_tag`
```

### Describe the proposed behavior

Add `tags` argument that accepts an iterable object to `prefect.flow` that overwrites the tags provided under `prefect.tags` context.

### Example Use

```
from prefect import flow, task
from prefect.deployments import Deployment


def get_country_with_new_stats():
    # Calls API to get only countries with new stat
    # from last call and return it
    return []  # suppose result from api


@task(tags=["api_limit_tag"])
def do_something_with_the_country(country: str):
    pass


@flow(tags=["flow_type:dynamic", "origin:country_flow"])
def sub_flow(country: str):
    do_something_with_the_country(country)
    # other tasks here
    return


@flow(tags=["flow_type:static"])
def main():
    country_list = get_country_with_new_stats()
    for country in country_list:
        sub_flow(country)


if __name__ == "__main__":
    Deployment().build_from_flow(
        main, name="country_flow", tags=["author:usernamehere"]
    ).apply()

```

### Additional context

This will allow for some granularity in filtering options on the API and UI.

**Comment by madkinsz** [comment]
This was intentionally removed during our beta period as it was unclear how flow tags should be treated by the API. We'll need our product team to consider this again.

**Comment by mahiki** [comment]
I'm puzzled by this behavior. I assign tags to flows in the `deployment build` process, and I find these tags very useful for filtering in the UI.

Most importantly, tags are how you can configure Notifications for failed runs. Its a strange place to stumble, I'm searching around how to test a notification alert from a flow, and I get a tag on the flow except by deploying my test flow.

**Comment by madkinsz** [comment]
You can do that with `with TagsContext(current_tags={...})` — we could consider adding a boolean toggle to the `tags` utility that does not include parent tags as well.

**Comment by mahiki** [comment]
> You can do that with `with TagsContext(current_tags={...})` — we could consider adding a boolean toggle to the `tags` utility that does not include parent tags as well.

Can you show example of this usage? I don't know how to do this one.

As @OptimeeringBigya notes, the `with tags():` idiom is really no help at all, because the calling flow still does not have any tags.  I'm dealing with a lot of pain on this issue running tests against my production server DB. Without flow tags its is very cluttered with flow runs.

**Comment by madkinsz** [comment]
```python
from prefect.context import tags, TagsContext


with tags("foo", "bar"):
    print(TagsContext.get().current_tags)

    with tags("a", "b"):
        print(TagsContext.get().current_tags)

    with TagsContext(current_tags=["a", "b"]):
        print(TagsContext.get().current_tags)
```

> idiom is really no help at all, because the calling flow still does not have any tags.

What do you mean?

**Comment by mahiki** [comment]
@madkinsz thanks!  For example, in order to tag a flow I created a subflow:

```py
@flow
def notifications_alert_task():
    return Failed(message="Intentionally Failed flow to test failure notification.")

@flow
def test_notification_alert():
    with tags("test", "test-alarm"):
        try:
            notifications_alert_task()
        except FailedRun as ex:
            return Completed(message="FailedRun exception caught, pass test and check slack channel.")
```

I don't need two flows for this, what I'd like for `test_notifications_alert` to carry the tags so I can filter all tests from my Prefect UI.

(Put aside that I can use pytest fixtures to run tests on the ephemeral prefect DB)

**Comment by madkinsz** [comment]
Why not

```python
from prefect import flow, tags

@flow
def parent_flow():
    pass

with tags("foo", "bar"):
    parent_flow()
```

or

```python
from prefect import tags
import pytest

@pytest.fixture(autouse=True)
def add_test_tags():
    with tags("test"):
        yield
```

**Comment by mahiki** [comment]
@madkinsz In the context of pytest, I don't see how `with tags("foo", "bar"):\n  parent_flow()` is a solution. The entrypoint has to be a parent flow.

I get that deployed flows can be tagged from the deployment build, but the syntactically consistent solution would be to define the tag in the @flow decorator just like with the @task decorator.

**Comment by madkinsz** [comment]
> but the syntactically consistent solution would be to define the tag in the https://github.com/flow decorator just like with the @task decorator.

This does not follow as simply as you'd think. We did this in beta and removed it because it _confused_ people.

>  In the context of pytest, I don't see how with tags("foo", "bar"):\n  parent_flow() is a solution. The entrypoint has to be a parent flow.

I see.. so if you set up a test like:


```
from prefect import tags, flow, get_client, task, runtime
import pytest

@pytest.fixture(autouse=True)
def add_test_tags():
    with tags("test"):
        yield

def test_flow():
    @flow
    def foo():
        asserts()
        
    @task
    async def asserts():
        async with get_client() as client:
            flow_model = await client.read_flow_by_name(runtime.flow_run.flow_name)
            assert flow_model.tags == ["test"]

    foo()
```

It does indeed fail. We do not assign tags to _flows_ at runtime because otherwise they could be updated on _each run_ of the flow and we do not want tags to be so unstable.

However I'm a bit confused by what you've been saying because using a subflow also does not include the tags

```python

def test_flow():
    @flow
    def foo():
        bar()

    
    @flow
    def bar():
        asserts()
    
    ...
```

At https://github.com/PrefectHQ/prefect/blob/ab65a08b2646c3607dc4b9a6dfe84dfd89355b76/src/prefect/client/orchestration.py#L502-L511 you can see we only include tags on the flow run not the flow.

**Comment by mahiki** [comment]
Thanks for the detailed attention to this. Unfortunately I'm just a data scientist and inadvertent data engineer, so the computer science evaluation is a bit beyond me. 

As a Prefect user, I want any test flows that show up in the DB to be tagged. Based on the above, it is impossible, there will be test flows that cannot have an tag. 

Perfectly reasonable explanation that beta users were confused by it...but, do I have this right:

"Only flows that are called by another flow can get a tag (except deployed flows)."

**Comment by madkinsz** [comment]
> "Only flows that are called by another flow can get a tag"

From the code I showed this should not be true. It looks like the tag is added to the subflow run but not the subflow itself.

**Comment by serinamarie** [comment]
@billpalombi I think this needs product feedback to escape the stalebot (one way or another).

**Comment by billpalombi** [comment]
As @zanieb laid out in they're comments, there is no straightforward, consistent way to support this that we can conceive of. I'm marking as-designed.
