### ISSUE TITLE
Allow additional env values in `kubernetes manifest agent` command

### ISSUE THREAD

**Issue by ToneyAlexander** [PrefectHQ/prefect#9092]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Running `prefect kubernetes manifest agent --help` shows that the `--api-url` and `--api-key` flags can be used, but there's other env settings that do not have flags.

### Describe the proposed behavior

I'm specifically hoping for a way to set `PREFECT_KUBERNETES_CLUSTER_UID` and `PREFECT_AGENT_QUERY_INTERVAL`, although perhaps there's a more general solution that would pull in all of the environment variables.

### Example Use

Running `prefect kubernetes manifest agent` would generate a yaml file that contains settings for environment variables besides just `PREFECT_API_URL` and `PREFECT_API_KEY`, or a user could manually specify them with

`prefect kubernetes manifest agent --cluster-uid <CLUSTER> --query-interval <INTERVAL>`

### Additional context

The main relevant files for this change are https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/kubernetes.py and https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/templates/kubernetes-agent.yaml

**Comment by jawnsy** [comment]
Hey there, thanks for your report!

We also [publish a Helm chart for the agent](https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-agent), which is what I'd recommend if you need more customization than we offer with this command.

This command is meant for simple use cases, and we'd prefer not to add too many flags to it.
