### ISSUE TITLE
Add the `variables` module

### ISSUE THREAD

**Issue by jakekaplan** [PrefectHQ/prefect#9108]
Adds `Variables` to be used in and outside of flows

variables should be able to be accessed in 3 ways

```python
from prefect import variables

@flow
async def my_flow():
    variables.get("my_var")
    variables["my_var"]
    await variables.get("my_var")
```

**Comment by cicdw** [comment]
Should this be `prefect.runtime.variables`?

**Comment by jakekaplan** [comment]
@cicdw We decided to move it out of runtime because it can be accessed at anytime and doesn't need to be within the context of anything https://github.com/PrefectHQ/prefect/pull/9008#discussion_r1157325654

**Comment by jakekaplan** [comment]
done in https://github.com/PrefectHQ/prefect/pull/9104
