### ISSUE TITLE
Not setting the current date by `datetime.today()`

### ISSUE THREAD

**Issue by djagoda881** [PrefectHQ/prefect#9115]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In flow I have to specify the `start_date` parameter. If I not specified it assumes today's date by default which is done by `datetime.today().strftime("%Y-%m-%d")`. When I creating deployment and schedule, I do not pass any date to the `start_date` parameter because I want flow to run daily and `start_date` to set the date on which it runs. So every day the date will be different. However, once the deployment is created, the `start_date` argument permanently takes the date the deployment was created. So if I create a deployment on 03.04.2023 then `start_date` will take the date 03.04.2023 and it will always start on this date. This means that if the flow starts tomorrow, next week or next month it will still take the default `start_date=03.04.2023`.

Below I have mapped this mechanism on a simple flow:
`from datetime import datetime
from prefect import flow, task

@task
def test_task(date: str):
    return f"Todays date is {date}"

@flow
def test_flow(start_date=datetime.today().strftime("%Y-%m-%d")):
    date = test_task(start_date)
    print(date)
`
Once a deployment and schedule have been created, the `start_date` parameter will be assigned the date the deployment was created and will not change. 
![image](https://user-images.githubusercontent.com/114922270/230375464-ca29e1dd-1e0c-48e7-a3f2-682919d957cf.png)

### Reproduction

```python3
@task
def test_task(date: str):
    return f"Todays date is {date}"


@flow
def test_flow(start_date=datetime.today().strftime("%Y-%m-%d")):
    date = test_task(start_date)
    print(date)

`
```

### Versions

```Text
2.7.12
```

**Comment by billpalombi** [comment]
Hi @djagoda881, this is expected behavior. The `datetime.today().strftime("%Y-%m-%d")` method is being evaluated when you create the deployment rather than each time the code runs. If you'd like it to be evaluated each time the flow code runs, you'll need to include it in the flow itself.
