### ISSUE TITLE
Document full deployment.yaml spec

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect#9147]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

It would be beneficial to have the full spec of the deployment.yaml documented somewhere so that users could reference it when defining different (non default) parameters.

For example - the autogenerated deployment.yaml file contains the following block:
```
# base metadata
name: my-flow
version: null
tags: []
description: null
schedule: null
```

### Describe the proposed change

I would like to be able to reference a spec doc to determine what appropriate fields can be supplied under `schedule`:
```
schedule:
  cron: 0 0 * * *
  timezone: UTC
```

An example of something similar would be [this](https://fluxcd.io/flux/components/kustomize/api/v1/) reference document for a fluxcd kubernetes object.

**Comment by madkinsz** [comment]
Do we parse this with a Pydantic model? We could publish the schema?

**Comment by discdiver** [comment]
Similarly, is the prefect.yaml spec fully documented somewhere? It’s partially documented in the concepts docs - e.g. pull section.
