### ISSUE TITLE
Unable to create Automation for sending notifications via slack

### ISSUE THREAD

**Issue by devdasgupta** [PrefectHQ/prefect#9155]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I am trying to create a automation that would send slack notifications when any of the flows with a `prod` tag enters to any of the failed status (`Crashed, Failed, TimeOut`)

### Reproduction

Following are the steps for replicating the error
- Add Automation: Click on the add automation in the add automation step
- Select Trigger (`Flow run state) -> for all flows -> Flow run tags prod  -> Fow Run enters (Crashed, Failed, TimeOut) state
- Select Action (Send Notification) -> Block selected as slack-webhook that was created separately
- Automation Name -> Provided an automation name and description. -> Ht Save

### Error

```
Sorry Something went wrong creating your automation
```
![image](https://user-images.githubusercontent.com/42590106/230667753-3f650765-b1d6-416e-be24-0463e9bf545d.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

**Comment by pleek91** [comment]
@devdasgupta I'm unable to reproduce using the steps provided. Would you mind checking browser devtools for the network error and share the payload and response?

**Comment by devdasgupta** [comment]
Hi @pleek91 
Following is the POST request and its response
```
index.18a938b4.js:1150          POST https://api.prefect.cloud/api/accounts/c9895aba-86e7-4125-b345-04f28d0e4fdd/workspaces/5a876ce4-403c-42d6-93e5-4a73ac8a063c/automations/ 403
Tt @ index.18a938b4.js:1150
h @ index.18a938b4.js:1151
(anonymous) @ index.18a938b4.js:19
Qg @ index.18a938b4.js:19
ySt @ index.18a938b4.js:19
Lb.request @ index.18a938b4.js:19
(anonymous) @ index.18a938b4.js:19
(anonymous) @ index.18a938b4.js:18
post @ index.18a938b4.js:19
createAutomation @ index.18a938b4.js:1123
A @ WorkspaceAutomationCreate.7447ac44.js:1
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
kat @ index.18a938b4.js:1
r @ AutomationWizard.vue_vue_type_script_setup_true_lang.9ec22266.js:12
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
kat @ index.18a938b4.js:1
R @ index.18a938b4.js:10
await in R (async)
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
i @ index.18a938b4.js:1
T @ index.18a938b4.js:1145
index.18a938b4.js:1151 Yb {message: 'Request failed with status code 403', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
h @ index.18a938b4.js:1151
A @ WorkspaceAutomationCreate.7447ac44.js:1
await in A (async)
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
kat @ index.18a938b4.js:1
r @ AutomationWizard.vue_vue_type_script_setup_true_lang.9ec22266.js:12
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
kat @ index.18a938b4.js:1
R @ index.18a938b4.js:10
await in R (async)
Fd @ index.18a938b4.js:1
js @ index.18a938b4.js:1
i @ index.18a938b4.js:1
T @ index.18a938b4.js:1145
```

**Comment by pleek91** [comment]
@devdasgupta thanks for the stack trace. Would you mind providing the actual network payload for the request thats failing?  If you go to the network tab there should be a failed network request that you can inspect and see the payload for. Thanks!
