### ISSUE TITLE
Error while opening `Flows & tasks` link on Introduction Tutorial Page

### ISSUE THREAD

**Issue by krishnaglodha** [PrefectHQ/prefect#9165]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm on prefect tutorial page and when I try to click on `Flows & tasks` page, it is redirecting me to same page rather than going to new page.
<img width="1386" alt="Screenshot 2023-04-10 at 9 44 52 AM" src="https://user-images.githubusercontent.com/47075664/230824605-cc6cdc3c-bbaf-42d1-81ae-6b0adb549c03.png">

### Reproduction

```python3
It's not code issue but documentation issue
```

### Versions

```Text
2.10.2
```

**Comment by rpeden** [comment]
Thanks for the report! This happens for me, too.

**Comment by rpeden** [comment]
It looks like we need to remove [a redirect](https://github.com/PrefectHQ/prefect/blob/a5d08d1ecaf773c5b12047dba56ee80c53dca3de/netlify.toml#L112).
