### ISSUE TITLE
Kubernetes Job block fields are incorrectly sized

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#9186]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Fields are too small

<img width="1267" alt="Screenshot 2023-04-11 at 2 26 22 PM" src="https://user-images.githubusercontent.com/82345018/231280744-9ca0afa4-4d0b-47fc-94cf-4f6370bcefee.png">

### Reproduction

1. Log into Prefect cloud
2. Create a new kubernetes job
3. Verify above issue

### Error

All the fields that have a "copy" symbol next to them are too small. This issue did not occurred in past versions of prefect. 

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.10.2
API version:         0.8.4
Python version:      3.11.2
Git commit:          16747be2
Built:               Fri, Apr 7, 2023 10:19 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by rjhawar** [comment]
Not sure if this designed to fit the size of the text, but the change adds way to much extra white space.
It also changes the default behaviour in past versions of Prefect

**Comment by pleek91** [comment]
@rjhawar this definitely is a bug and the change was not intentional. Thanks for calling it out!
