### ISSUE TITLE
add "to top" and "to bottom" buttons in the flow run page to navigate the logs more easily

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#9196]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When logs are long in the flow run page, I have to scroll down a long time to reach the bottom. To come back to the top (eg too look at the progress graph), I have to scroll again.

### Describe the proposed behavior

add a "to bottom" at the top of the flow run page and add a "to top" at the bottom of the flow run page. Any other option that help navigate vertically in the flow run logs will be useful

**Comment by batuhanfaik** [comment]
Would be really nice to have

**Comment by batuhanfaik** [comment]
Do we have any updates on this?
