### ISSUE TITLE
Docker tasks need better logging

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#920]

**Comment by alexisprince1994** [comment]
Was looking at contributing on this issue, and looked through the PR referenced. It looks like those were debug logs added when some kind of default variable or value was being provided, or a special action was being taken due to arguments into the task. The docker tasks don't seem to follow this same pattern. Thoughts on where to put additional logging?

**Comment by joshmeek** [comment]
Ah yeah this issue isn't very descriptive. On each of the Docker tasks they use the [Docker low-level API ](https://docker-py.readthedocs.io/en/stable/api.html#) and each function generally comes with a flag for some type of output (e.g. default to `stream=False`). Each of these Docker API calls should have some better logging attached!

Example: in the [`PullImage`](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/docker/images.py#L123) task the end of the function  returns the string output from pull but with stream=True we could watch the output, live log it using the prefect logger, and then once the generator is complete return the output.

Another example in the [`BuildImage`](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/docker/images.py#L393) task we capture the output and return it but some better logging could be added to notify users of the Tasks what is actually happening 

Another another example (not relating to images but to containers) something like the [`StartContainer`](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/docker/containers.py#L251) task doesn't have any Docker API output that the function returns but an extra log such as `Docker container started with ID ...container_id...`

**Comment by cicdw** [comment]
Yea I vote we log a good portion of the output streams from the various Docker API calls, specifically with a focus on debug logs that help users see how / when things go wrong.

**Comment by melvisglez** [comment]
La fusión exitosa de una solicitud de extracción puede cerrar este problema.
