### ISSUE TITLE
Proposal PIN: Storage & Execution

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#921]
# Status
Proposed

# Context

Our current environments setup contains multiple classes, some of which can be deployed, others which can't.  Moreover, the environment classes tightly couple _storage_ of a flow with _execution platform_ details.  This leads to an unsatisfactory interface, and a spreading out of documentation.  Additionally, it makes it hard to delineate which environments are appropriate for which use cases and also requires a large number of highly specific classes.

# Decision

Separate out the storage component of an environment into its own module and attach it to the flow as an argument.

# Consequences

All current environments will need to be reworked or removed and PIN-3 will be partially voided.

@cicdw Let's keep this pin proposal here and update as needed

**Comment by jlowin** [comment]
@joshmeek let's fill this out and publish as accepted
