### ISSUE TITLE
Make run-once option for prefect agent settable via argparse

### ISSUE THREAD

**Issue by Zyntogz** [PrefectHQ/prefect#9222]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, the CLI for the agent (https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/agent.py) has no possibility to set the run_once flag explicitly. 

### Describe the proposed behavior

However, this would be quite easy to implement and may be useful in dockerized use cases (as ours) where we sometimes suffer from connection problems which the agent container is not able to recover from automatically. If we would orchestrate it correctly the agent should be restarted after every execution and would likely recover.

Alternatively, a settable ci-parameter that results in raising an exception and breaking the loop if the agent is not able to connect to the server would probably be the best solution but likely harder to implement.

### Example Use

Run-Once active:
prefect agent start --work-queue default --limit 10 --run-once
Run-Once not active (using default value false):
prefect agent start --work-queue default --limit 10

Alternatively:
prefect agent start --work-queue default --limit 10 --fail-on-connection-loss

**Comment by madkinsz** [comment]
Hey @Zyntogz — `--run-once` should work fine?

```
❯ prefect agent start --run-once --work-queue test
Starting v2.10.4 agent with ephemeral API...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from queue(s): test...
Agent stopped!
```

**Comment by Zyntogz** [comment]
Ok, some stuff went wrong on our side and we misinterpreted results. Everything works fine, sorry :)
