### ISSUE TITLE
prefect deploy should create a work pool with a process type if work pool does not exist

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9224]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If a project is deployed with prefect deploy and a pool of the specified name does not exist, it errors. 

### Describe the proposed behavior

`prefect deploy` should create a work pool with a process type if work pool does not exist.

### Additional context

@desertaxle says "Seems reasonable to me. That would mirror the current functionality where a process infra block is created for deployments that don’t explicitly specify a infra block."

**Comment by serinamarie** [comment]
This seems like a duplicate of https://github.com/PrefectHQ/prefect/issues/9225 (which was technically after but I've already responded to that issue)

**Comment by Shubhamparashar** [comment]
@discdiver I would like to work on this, can you please assign this issue to me

**Comment by discdiver** [comment]
Closing this as 2.10.13 added interactive prompts for creating a work pool with `prefect deploy` if no work pool is specified.
