### ISSUE TITLE
Automations are not triggering webhooks properly

### ISSUE THREAD

**Issue by valleybay** [PrefectHQ/prefect#9230]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary
Running on Prefect Cloud.

Automations are not running properly. I have activated automations on when the flow run is entering: Pending, Scheduled, Late, Failed, Crashed, Completed and only some of them come through. It is different everytime on which level it stops. Sometimes it will only send 'Pending' sometime it will only send 'Running'.

There is not an issue on the receiving end, I have both tested with Actions for Slack and a separate webhook. There is no pattern to which one it will «get stuck» on.

**Aside: your join Slack URL everywhere is no longer active (expired) and does not work.**

### Reproduction

```python3
# There is no code. Configured through the webUI.

1. Create a new automation with trigger:
- Trigger Type: Flow run state
- Flows: All flows
- Flow Run tags: All
- Flow Run: Enters: Crashed, Completed, Failed, Scheduled, Pending, TimedOut

2. Add Actions
- Call a webhook
- Body contains data
```

### Versions

```Text
2.10. Running Prefect Cloud.
```

**Comment by valleybay** [comment]
Hi @bunchesofdonald,

Here you go: https://app.prefect.cloud/account/396e0007-95ab-490f-bc1f-fef3801207f6/workspace/b5cf6a47-7c86-410c-90f3-d861dd942cbd/automations/automation/bf17e26a-fb24-4cec-a185-b597484a83d8

Christian

**Comment by chrisguidry** [comment]
@polivbr Do you mind sharing the automation ID you're referring to?

Also @valleybay, I see we haven't had an update in 2 weeks, are you still having trouble with your automations?

**Comment by polivbr** [comment]
Sure thing:

https://app.prefect.cloud/account/487b399b-4973-40f5-8234-1cd9798fd21f/workspace/f6c9095d-03e1-4f4c-9cbf-8d03212f23ef/automations/automation/7837c0aa-f54b-4778-a1d0-5c73c07ba1b8

**Comment by chrisguidry** [comment]
Thanks for that, @polivbr.  So there are a few things to note here:

1. This automation has a `Reactive` trigger with a `within` set to `10` (seconds).  This means that you will get at most one notification every 10 seconds.  If your flow run is going through states rapidly (like going `Pending` -> `Running` -> `Completed` within a few seconds), you'll only get the first event.  You can reduce the `within` period to `0` to get a callback for every event.

2. Yes, our default template uses some shortcuts like `{{ flow_run }}` which reach out to the Prefect Cloud API and get the state of the flow run _at the point in time the notification is sent_.  This is a convenience and simplification that helps us migrate folks from the previous notification system.  You have access to the event that triggered your Reactive automation in the variable `{{ event }}` where you'll have access to the labels and state captured in the event.  I encourage you to check out what's available by looking at the Event Feed in Prefect Cloud and expanding one of the events.  You'll see we have a lot of information available.

**Comment by polivbr** [comment]
@chrisguidry, thank you!!

Applying both of those suggestions worked perfectly.

**Comment by chrisguidry** [comment]
Woo great news!

**Comment by valleybay** [comment]
@chrisguidry The `within` has to be what has affected us as well but we have since moved to just using the Prefect API to poll the status from there instead. Works well!
