### ISSUE TITLE
Work Pool created with a trailing space in name can't be viewed or deleted via UI

### ISSUE THREAD

**Issue by rpeden** [PrefectHQ/prefect#9232]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If I create a new work pool via the UI with a trailing space in the name, Prefect creates the work pool in the database, but it cannot be viewed or deleted via the UI. 

After creation, Prefect tries to redirect to the newly-created work pool with the trailing space replaced by a URI encoded space (`%20`) in the URL, but this returns a 404. Removing the `%20` also results in a 404.

It shows up as expected in the list of work pools in the UI and via `prefect work-pool ls`, however neither contains a visual cue that the name contains a trailing space: 
<img width="718" alt="Screenshot 2023-04-16 141437" src="https://user-images.githubusercontent.com/228762/232333245-487d4054-f19c-4126-8efc-21cb58f781c7.png">
<img width="600" alt="Screenshot 2023-04-16 140448" src="https://user-images.githubusercontent.com/228762/232332878-1ad264d4-5779-40b5-bdfd-fa4d3d2befb0.png">

`Test ` has a trailing space in its name. But since I can't see the space, my first attempt to delete the work pool failed without any indication that it failed, just a blank output line:

<img width="600" alt="Screenshot 2023-04-16 141120" src="https://user-images.githubusercontent.com/228762/232333079-b923e023-dae9-4c12-97b7-be38997bb574.png">

Similarly, trying to delete via the UI fails:

<a href="https://www.loom.com/share/5474007f8c7140a5a44f549a3952af32">
    <img width="300" src="https://cdn.loom.com/sessions/thumbnails/5474007f8c7140a5a44f549a3952af32-with-play.gif" />
</a>

[Watch video](https://www.loom.com/share/5474007f8c7140a5a44f549a3952af32)

Deleting via the CLI works _if_ you realize there's a trailing space and use quotes to include it: 

<img width="600" alt="Screenshot 2023-04-16 143757" src="https://user-images.githubusercontent.com/228762/232334483-18c96794-2f7f-4f60-84bb-d786ec670a89.png">

### Reproduction

```python3
- Create a work pool with a trailing space in the name via the UI and verify the things noted in the bug description are true.
```

### Versions

```Text
Version:             2.10.4
API version:         0.8.4
Python version:      3.7.13
Git commit:          b6d0433a
Built:               Thu, Apr 13, 2023 5:34 PM
OS/Arch:             win32/AMD64
Profile:             local
Server type:         server
```

### Additional context

I didn't create this as a UI bug because I'm not sure it's exclusively a UI issue. 

The UI should be probably be able to view existing work pools with trailing spaces, but it might be useful to remove trailing spaces server-side upon work pool creation to avoid confusion - because there's no easy way for CLI users to know a work pool they see when running `prefect work-pool ls` has a trailing space (or spaces), leading to frustration when they try to run `work-pool` commands against the pool.

**Comment by serinamarie** [comment]
> If I create a new work pool via the UI with a trailing space in the name, Prefect creates the work pool in the database, but it cannot be viewed or deleted via the UI.

Testing in 2.10.11 I cannot reproduce this.

Creating via the command line we receive the following error:
```bash
pydantic.error_wrappers.ValidationError: 1 validation error for WorkPoolCreate
name
  Name 'slashy/workpool' contains an invalid character. Must not contain any of: ['/', '%', '&', '>', '<']. (type=value_error.invalidname)
```

Creating via the UI: 
"Failed to create work pool" error popup. We could use clarity here but that's a separate issue.
