### ISSUE TITLE
Deployment Parameters do not show and cannot be overridden in Prefect Cloud UI

### ISSUE THREAD

**Issue by jiriklein** [PrefectHQ/prefect#9240]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Deployment Parameters do not show and cannot be overridden in Prefect Cloud UI, despite the fact that they are present when retrieving the flow with 

```python
server_deployment = Deployment(name="uat", flow_name="dbt.dbt_run.py")
server_deployment.load()
```
or
```bash
prefect deployment inspect 'dbt.dbt_run.py/uat'
```

Both of these show parameters field with correctly populated parameters. The Flow Run -> Parameters shows this:
<img width="802" alt="Screenshot 2023-04-14 at 15 29 17" src="https://user-images.githubusercontent.com/44288863/232554308-1009bcdb-a5b3-444d-98ff-81679b05ca30.png">

The Parameters in Deployment shows this:
![image](https://user-images.githubusercontent.com/44288863/232554460-da41b202-e619-4c7e-9f2d-2f9778700771.png)

### Reproduction

The flows are deployed with a CI/CD script with:
```python
def create_deployment_for_flow(
    environment: str,
    filename: str,
    sub_dir: str,
    infrastructure: ECSTask,
    overrides: Dict[str, str],
    parameters: Optional[Dict[str, Any]] = None,
    schedule: Optional[str] = None,
    src_part: str = SRC_PART,
) -> Deployment:
    """Create a Deployment object for a flow.

    Args:
        environment: where we want to deploy to
        filename: flow filename
        sub_dir: flow sub directory
        infrastructure: a loaded prefect 2 infrastructure block
        overrides: overrides for the infrastructure block
        parameters: optional set of flow parameters
        schedule: a cron schedule for the flow run
        src_part: the root src where the flows will be stored (see Dockerfile)

    Returns:
        A Deployment object for the flow
    """
    return Deployment(
        name=environment,
        flow_name=f"{sub_dir}/{filename}".replace("/", "."),
        # We assume that a flow will be defined via def flow() in the code
        entrypoint=f"{filename}:flow",
        path=f"/{src_part}/flows/{sub_dir}",
        infrastructure=infrastructure,
        work_pool_name=environment,
        work_queue_name=environment,
        infra_overrides=overrides,
        # If `schedule` then use a `CronSchedule`, else use `schedule` as it's `None` anyway
        schedule=CronSchedule(cron=schedule, timezone="Etc/UTC")
        if schedule
        else schedule,
        parameters=parameters,
    )
```
which is run in loop and applied with 
```python
for deployment in deployments:
    deployment.apply(upload=False)
```

### Error

The Deployment parameters do not show, and therefore cannot be viewed, edited or selected for ad-hoc Flow Runs. 

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Prefect Cloud
```

**Comment by znicholasbrown** [comment]
Hi @jiriklein - can you include your flow code (or a min example of it) here? From your deployment code alone it looks like you're passing `None` as the default parameters for your deployment but then your flow has runtime defaults which are (correctly) being passed to the run.

**Comment by jiriklein** [comment]
Apologies @znicholasbrown, I missed a small part of the code where the deployment object gets created via `create_deployment_for_flow`.

We create a dictionary called `deployment_args` and populate it with relevant config from a TOML file, such as:
```python
if deployment_params := flow_config.pop("parameters", None):
  env_deployment_params = deployment_params["uat"]
  deployment_args["parameters"] = env_deployment_params
```
Which are then provided as:
```python
deployments.append(create_deployment_for_flow(**deployment_args))
```
The TOML file looks like:
```toml
[flows.dbt."dbt_run.py"]
schedule = "0 1 * * *"
parameters.uat = { foo = 3, bar = 4 }
```

**Comment by cicdw** [comment]
@jiriklein the reason your parameters aren't being displayed is because you are hand-creating your deployment without setting the `parameter_openapi_schema`, which is what the UI needs to know what parameters are available and what their types are.

From your CLI output (copied from Slack), you can see this field is empty here:
```
'parameter_openapi_schema': {'type': 'object', 'title': 'Parameters', 'properties': {}}
```

May I ask - why are you creating this deployment yourself instead of using one of the public APIs for creating it, such as `build_from_flow` or `deployment build` CLI?  We have a beta version of a new way to build and run deployments ([tutorial here](https://docs.prefect.io/latest/tutorials/projects/)) that may be a more natural fit for your use case.
