### ISSUE TITLE
Verbose logs due to log_prints capturing non-std prints

### ISSUE THREAD

**Issue by aeisenbarth** [PrefectHQ/prefect#9251]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Libraries may use print for other purposes than printing to stdout/stderr, for example building strings or writing to files.

Our situation is that we use an upstream library which uses the very common `numba`, and `numba` uses `print` to build a string, causing our Prefect logs to be polluted with _thousands_ of lines, and affected tasks occasionally take a multiple of the expected run time.

The cause is that Prefect's [`print_as_log`](https://github.com/PrefectHQ/prefect/blob/f1cf1109e2db279f16f8257405c80482e21359c0/src/prefect/logging/loggers.py#L203) does not handle an existing `file=` keyword argument but overrides it. When other Python code uses the `file` keyword argument like in `print(something, file=some_file_handle)`, it may expect the prints neither to end up on stdout/stderr nor in any logs.

### Reproduction

```python3
import logging
from io import StringIO

from prefect import flow, task


@task(log_prints=True)
def get_string() -> str:
    with StringIO() as sb:
        print(
            "What is not printed to stdout/stderr should not be logged by Prefect",
            file=sb,
        )
        print("Returning task result, this should be logged")
        return sb.getvalue()


@flow
def mcve():
    return get_string()


def test_log_prints_should_exclude_printing_to_file():
    logger = logging.getLogger("prefect.task_runs")
    with StringIO() as logger_stream:
        handler = logging.StreamHandler(stream=logger_stream)
        logger.addHandler(handler)
        # Run the flow
        mcve()
        log = logger_stream.getvalue()
    assert "should be logged" in log
    assert "should not be logged" not in log
```

### Error

```python3
17:20:05.481 | INFO    | prefect.engine - Created flow run 'amazing-heron' for flow 'mcve'
17:20:05.585 | INFO    | Flow run 'amazing-heron' - Created task run 'get_string-0' for task 'get_string'
17:20:05.586 | INFO    | Flow run 'amazing-heron' - Executing 'get_string-0' immediately...
17:20:05.627 | INFO    | Task run 'get_string-0' - What is not printed to stdout/stderr should not be logged by Prefect
17:20:05.628 | INFO    | Task run 'get_string-0' - Returning task result, this should be logged
17:20:05.644 | INFO    | Task run 'get_string-0' - Finished in state Completed()
17:20:05.665 | INFO    | Flow run 'amazing-heron' - Finished in state Completed()
Traceback (most recent call last):
  File "/home/user/project/src/debug_logging_issue.py", line 31, in <module>
    assert "should not be logged" not in log
AssertionError
```

### Versions

```Text
Version:             2.8.4
API version:         0.8.4
Python version:      3.9.16
Git commit:          f09ccc32
Built:               Thu, Mar 2, 2023 12:34 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

This only happens when running the task in a flow (not stand-alone `get_string.fn()`) and only if annotated with `log_prints=True`.

For reference, a code sample from the original use case, producing very verbose logs:
```python
import anndata, numpy as np, scanpy as sc

@task(log_prints=True)
def original_task():
    adata = anndata.AnnData(np.random.random(100).reshape((10, 10)).astype(np.float32))
    sc.pp.neighbors(adata)
    sc.tl.umap(adata)
```

And a minimal numba code causing this issue. The numba JIT compiler invokes [`dump_to_string`](https://github.com/numba/numba/blob/288a38bbd5a15418a211bf067878dfdf3c139509/numba/core/interpreter.py#L1342) which should only be logged with debug level.
```python
import numba

@task(log_prints=True)
def numba_example():
    @numba.njit("i4(i8[:])")
    def tau_rand_int(state):
        return 0
```

**Comment by madkinsz** [comment]
Thanks for the report! We can definitely check if the target file is stdout/err/null — this should be an easy contribution if you're interested.

**Comment by aeisenbarth** [comment]
A possible solution would be to not override `file` if it is found in `kwargs`, basically using the original implementation without logging to prefect. The reasoning would be that prints only end up on stdout (which we want to capture with `print_as_log`) if the file argument is not used, otherwise we can assume a library uses print for other purposes, or will later send the printed string through another way again into logging infrastructure where it should be captured by Prefect.

I was wondering whether there are legitimate cases when the `file` keyword is already used, but logging to Prefect is still desired. I that case we would have to replace it by an object that sends to both the original file argument and the Prefect StringIO buffer.

**Comment by madkinsz** [comment]
I think if `file == sys.stdout or file == sys.stderr` I'd expect it to log to Prefect otherwise I think it's safe to just bypass our logging entirely. Sending the message to the existing file kwarg and our logger seems sensible but I think we'll end up capturing things we shouldn't (as you've encountered) and I agree there probably aren't many use cases where a user would expect that behavior.
