### ISSUE TITLE
Realtime stream for prefect log in API

### ISSUE THREAD

**Issue by code1704** [PrefectHQ/prefect#9252]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

there's no log before task completed, and is there a way to stream the log (SSE or websocket)?

### Reproduction

1. vi hello.py
```
import threading
import time

from prefect import flow, task


@task(log_prints=True)
def print_values(values):
    for value in values:
        time.sleep(3)
        print(value, threading.current_thread().ident)


@flow
def my_flow():
    print_values.submit(["AAAA"] * 15)
    print_values.submit(["BBBB"] * 10)


if __name__ == "__main__":
    my_flow()
```

2. prefect server start

3. python3 hello.py

and there are logs:

```
01:54:31.358 | INFO    | prefect.engine - Created flow run 'free-turaco' for flow 'my-flow'
01:54:31.502 | INFO    | Flow run 'free-turaco' - Created task run 'print_values-0' for task 'print_values'
01:54:31.503 | INFO    | Flow run 'free-turaco' - Submitted task run 'print_values-0' for execution.
01:54:31.576 | INFO    | Flow run 'free-turaco' - Created task run 'print_values-1' for task 'print_values'
01:54:31.579 | INFO    | Flow run 'free-turaco' - Submitted task run 'print_values-1' for execution.
01:54:34.793 | INFO    | Task run 'print_values-0' - AAAA 6230962176
01:54:34.841 | INFO    | Task run 'print_values-1' - BBBB 6285455360
01:54:37.848 | INFO    | Task run 'print_values-0' - AAAA 6230962176
01:54:37.851 | INFO    | Task run 'print_values-1' - BBBB 6285455360
01:54:40.889 | INFO    | Task run 'print_values-0' - AAAA 6230962176
01:54:40.901 | INFO    | Task run 'print_values-1' - BBBB 6285455360
```

4. web UI: no log (expect: logs in realtime)
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/110730540/232863230-8e6a4e69-14a7-4590-a398-3316c7610443.png">

5. api: no log (expect: logs in realtime)
```python3
curl -X 'POST' \
  'http://127.0.0.1:4200/api/logs/filter' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 0,
  "logs": {
    "operator": "and_",
    "task_run_id": {
      "any_": [
        "d7c83ce6-75eb-4300-8430-894f91d3a14e"
      ]
    }
  },
  "sort": "TIMESTAMP_ASC",
  "limit": 110
}'
```

### Versions

```Text
Version:             2.10.2
API version:         0.8.4
Python version:      3.9.6
Git commit:          16747be2
Built:               Fri, Apr 7, 2023 10:19 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```

**Comment by madkinsz** [comment]
Hey @code1704 this issue does not meet our requirements for a reproducible example. Can you please include more details about the behavior you expect vs the behavior you see as well as an example that we could run to see the behavior?

**Comment by madkinsz** [comment]
Separately

>  and is there a way to stream the log (SSE or websocket)?

We don't support this yet. We'd recommend using pagination (offset) and polling at this point.

**Comment by code1704** [comment]
> Separately
> 
> > and is there a way to stream the log (SSE or websocket)?
> 
> We don't support this yet. We'd recommend using pagination (offset) and polling at this point.

But there are no logs when the task is running

**Comment by code1704** [comment]
> @code1704 is it possible you're affected by #9180 / #9172?

Not sure. when i install from git and prefect server start, there's no dashboard (returns json says not found)
```
pip3 install git+https://github.com/PrefectHQ/prefect  -U
```

**Comment by madkinsz** [comment]
@code1704 that fix is published in our latest version. The UI needs to be manually built when using the development install i.e. `prefect dev build-ui`.

**Comment by code1704** [comment]
> @code1704 that fix is published in our latest version. The UI needs to be manually built when using the development install i.e. `prefect dev build-ui`.

pip3 install prefect -U
Successfully installed prefect-2.10.4

this works for me. thanks
