### ISSUE TITLE
log_prints incompatible with numba

### ISSUE THREAD

**Issue by aeisenbarth** [PrefectHQ/prefect#9253]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When a task is annotated with `log_prints=True` and calls a numba function which contains `print`, a type error is raised. The numba compiler in nopython mode (njit instead of jit) cannot handle Prefect's `print` override, probably because it knows the (typed) signature of the built-in, but not of the override.

Typically, most numba functions contain only mathematical code but no print. An example of a print is in [pynndescent](https://github.com/lmcinnes/pynndescent/blob/0.5.8/pynndescent/pynndescent_.py#L252). This issue is related to #9251 with the difference that there, print was outside of a JIT-compiled function.

Work-arounds
- Do not use `log_prints=True`
- Or if possible, annotate the numba function as `@jit` (not `@njit`), avoiding nopython mode. This allows the function to call `print` through the Python interpreter, thus using Prefect's print override.
- Or ensure numba is not imported earlier than within the task.

### Reproduction

```python3
import numba
from prefect import flow, task


@task(log_prints=True)
def numba_task_with_print() -> int:
    @numba.njit()
    def numba_function(verbose: bool = True) -> int:
        if verbose:
            print("something")  # Compiles with Python built-in, not with Prefect's print_as_log
        return 1

    return numba_function()


@flow
def mcve():
    return numba_task_with_print()


def test_log_prints_should_not_break_print_in_numba():
    mcve()
    # It should not raise numba.core.errors.TypingError("Untyped global name 'print'")
```

### Error

```python3
Traceback (most recent call last):
  File "/home/user/project/venv/lib/python3.9/site-packages/prefect/engine.py", line 1533, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/home/user/project/venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/home/user/project/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/user/project/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/project/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/project/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/project/venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/home/user/project/debug_scanpy_numba_issue.py", line 13, in numba_task_with_print
    return numba_function()
  File "/home/user/project/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/user/project/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'print': Cannot determine Numba type of <class 'function'>
```

### Versions

```Text
Version:             2.8.4
API version:         0.8.4
Python version:      3.9.16
Git commit:          f09ccc32
Built:               Thu, Mar 2, 2023 12:34 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

Possibly this does not happen when jit-compiled numba functions are imported outside of a Prefect task. In our specific case, an upstream library imports the numba function at run time, thus it is compiled within the Prefect task and sees only the patched `print`.

**Comment by madkinsz** [comment]
Thanks for another well written issue!

Do you have a suggested resolution here?

**Comment by aeisenbarth** [comment]
Looking into numba, it seems to make functions compatible they need to have a specific numba-type signature (it doesn't use something more generic like Python type hints). Adding a numba signature in Prefect is not an option.

Also, numba has its own [implementation of a subset of `print`](https://github.com/numba/numba/blob/2e825b000e609e090005f8fb3d567999f1f1940c/numba/cpython/printimpl.py#L34).

I would suggest not to close the issue, but leave it as reference for anyone bumping into the same. I documented a couple of work-arounds of which the last should always be feasible:

Even if a user cannot modify a library which uses `njit`, the user can move the import statements of that library into the Prefect task.

**Comment by madkinsz** [comment]
Is there a way we can detect that numba is being used and skip patching / warn the user that it won't work?

We can add a numba signature in Prefect with a conditional import i.e. if numba is installed we can support it but otherwise we use our current implementation.

> Even if a user cannot modify a library which uses njit, the user can move the import statements of that library into the Prefect task.

This does seem like a reasonable workaround.
