### ISSUE TITLE
Deployments UI should suggest existing tags

### ISSUE THREAD

**Issue by tharwan** [PrefectHQ/prefect#9272]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently any tag, existing or not can be entered as filter in the deployments UI page.

### Describe the proposed behavior

Existing tags should be used as suggestions as in the flow runs page.

**Comment by billpalombi** [comment]
Agreed, we have some ideas for how to improve the utility of tags themselves as well as the experience of adding them.

**Comment by zhen0** [comment]
Duplicate of #8791

**Comment by zhen0** [comment]
This has come up a few times and it's a quick win so I've added. The suggested tags should be visible after the next release.  Thanks for raising it @tharwan
