### ISSUE TITLE
Service 'EventsWorker' failed.

### ISSUE THREAD

**Issue by bribroder** [PrefectHQ/prefect#9275]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a very basic test flow which sets `cache_result_in_memory=False` and fails with python 3.10 and prefect>2.10 but works with prefect==2.9.0. I am testing with a local-only setup so there is no server involved. If I either downgrade to prefect 2.9 or remove `cache_result_in_memory=False`, it works--everything looks the same except for the EventsWorker service error

### Reproduction

```python3
@task
def say_hello():
    print("hello!")


@flow(cache_result_in_memory=False)
def testflow() -> None:
    logger = get_run_logger()
    logger.info("START FLOW")
    say_hello()
    logger.info("END FLOW")

$ py -c 'from testflow import testflow; testflow()'

11:14:22.447 | INFO    | prefect.engine - Created flow run 'umber-nyala' for flow 'testflow'
11:14:22.569 | INFO    | Flow run 'umber-nyala' - START FLOW
11:14:22.659 | INFO    | Flow run 'umber-nyala' - Created task run 'say_hello-0' for task 'say_hello'
11:14:22.661 | INFO    | Flow run 'umber-nyala' - Executing 'say_hello-0' immediately...
hello!
11:14:22.920 | INFO    | Task run 'say_hello-0' - Finished in state Completed()
11:14:22.924 | INFO    | Flow run 'umber-nyala' - END FLOW
11:14:24.174 | INFO    | Flow run 'umber-nyala' - Finished in state Completed('All states completed.')
11:14:24.615 | ERROR   | prefect._internal.concurrency.services - Service 'EventsWorker' failed.
```

### Error

```python3
Traceback (most recent call last):
  File "/opt/conda/envs/testflow/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 114, in _run
    await self._main_loop()
  File "/opt/conda/envs/testflow/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 127, in _main_loop
    item: T = await self._queue.get()
  File "/opt/conda/envs/testflow/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

### Versions

```Text
2.9.0 or 2.10.4
```

**Comment by madkinsz** [comment]
Hey @bribroder thanks for reporting this. When you say your flow fails, does it actually end up in a failed state? The service failure you shared just looks like a log message. While we'd like to resolve that, it shouldn't fail your flow :)

**Comment by bribroder** [comment]
Yes I think you're correct that the flows don't actually end up in failed states

**Comment by madkinsz** [comment]
This occurs when events are emitted outside of a flow. This happens in your example because a block is used to retrieve the result of the flow (since it is not cached in memory) which emits block usage events. The issue is that we flush events on interpreter exit, but we also shutdown the event loop on interpreter exit. The event loop does not wait for its tasks so the event worker task is cancelled. For example:


```python
import asyncio
import traceback

task = None


async def sleeper():
    try:
        await asyncio.sleep(5)
    except BaseException as exc:
        print("Task failed")
        traceback.print_exception(exc)
        raise


async def test():
    global task
    # stash this bad boy in global memory so it's not gc'd
    task = asyncio.create_task(sleeper())
    # exit


asyncio.run(test())
```

We'll need to track tasks / calls in the event loop thread and wait for them to complete at https://github.com/PrefectHQ/prefect/blob/f5d2cd1f6fa59f10d4d71ca7172d9a58b4870a98/src/prefect/_internal/concurrency/threads.py#L204
