### ISSUE TITLE
Allow customising notification messages

### ISSUE THREAD

**Issue by domzae** [PrefectHQ/prefect#9291]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the notifications that are triggered on run states, use a static template which cannot be changed. This means the message may be missing critical information to help quickly understand what triggered a notification. For example, deployment parameters and flow tags are not included in the message.

### Describe the proposed behavior

**Option 1: A toggle-able list of attributes to include in the message, for example:**

* [X] Deployment name
* [X] Deployment parameters
* [X] Flow name
* [ ] Flow ID
* [X] Flow run name
* [ ] Flow run ID
* [X] Flow tags
* [X] URL
* [X] State message

**Option 2: A text editable template, for example:**
```
Flow run {flow_name}/{flow_run_name} entered state `{flow_run_state_name}` at {flow_run_state_timestamp}.
Deployment: {deployment_name}
Deployment parameters: {deployment_params}
Flow tags: {flow_tags}
Flow run URL: {flow_run_url}
State message: {flow_run_state_message}
```

### Example Use

Users could tailor notifications to contain information that is specifically useful to them.

### Additional context

Here is an example of what the current notification looks like for me on slack. The only useful information I get is the name of the flow and the state. Flow tags are super important for me to understand whether the notification requires investigation. (Side-note: the URL is incorrect and should ideally point to `localhost:4200` here)
<img width="550" alt="image" src="https://user-images.githubusercontent.com/40212333/233650544-1ef3040b-471f-4fec-91d1-a43151c78a89.png">

This is an example of a good notification that I construct and "manually" send mid-flow, giving me the info I need:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/40212333/233651747-c2feb7cf-b530-41e7-b49a-51f354e7d8c8.png">

**Comment by serinamarie** [comment]
Hi @domzae, thanks for the issue! It looks like we have a method for creating a custom template here:

https://github.com/PrefectHQ/prefect/blob/a643e79d95356d6336057935a8da26c2469c9f7b/src/prefect/client/orchestration.py#L1942-L1981

where the `message_template` kwargs are here: https://github.com/PrefectHQ/prefect/blob/d48dfbbcecc2c42ec96ad98245ef236d2cb9ee39/src/prefect/server/schemas/core.py#L24-L36 It looks like you can specify `tags` as well when creating a flow run notification policy. I'm wondering if that would solve for your use case? I could see there being an enhancement where new kwargs are added to `FLOW_RUN_NOTIFICATION_TEMPLATE_KWARGS`, such as tags.

**Comment by domzae** [comment]
Hi @serinamarie , thanks for the response!

Ah I missed this when looking for it! Passing a custom message template `create_flow_run_notification_policy` seems to work well to customise the format. With that said, I would then ask for 2 enhancements:

1. Add more kwargs to `FLOW_RUN_NOTIFICATION_TEMPLATE_KWARGS`: The main one missing for me is `tags`, but maybe depoloyment name/id/params etc. could be useful too
2. Allow the customisation of the template within the UI.

If agreed, should I update the original post with these or close this and open one (or two) new issue(s)?

**Comment by discdiver** [comment]
Thank you @domzae. I would open two separate issues.
