### ISSUE TITLE
Links to individual PINs are broken in docs

### ISSUE THREAD

**Issue by maxalbert** [PrefectHQ/prefect#930]
First of all, many thanks to the entire team for building Prefect and making it available to the community! 👏 

Just a quick heads-up that the links to individual PINs are broken in the docs. While the [PIN Contents](https://docs.prefect.io/guide/pins/) page loads fine, clicking on an individual link results in a 404.

It looks like there is some implicit redirect. For example, the link address for PIN 1 is https://docs.prefect.io/guide/PINs/PIN-1-Introduce-PINs.html. However, when I click on the link it redirects me to the non-existing URL https://docs.prefect.io/guide/pins/pin-1-introduce-pins/. (But if I manually replace the trailing slash with `.html` the page loads correctly.)

P.S.: As a tangential aside, the link to the "issue board" in the [Community > Contributing](https://docs.prefect.io/guide/welcome/community.html) section points to https://github.com/PrefectHQ/prefect but should probably point to https://github.com/PrefectHQ/prefect/issues

**Comment by joshmeek** [comment]
Thanks for raising this issue!

Interesting @cicdw there seems to be two different URLs https://docs.prefect.io/guide/PINs/ and https://docs.prefect.io/guide/pins/ . Clicking a link on the `PINs` page works fine however the `pins` page fails.

**Comment by jlowin** [comment]
@maxalbert thanks so much for pointing this out - I actually observed this once before when pasting a link to the PIN here (in a GitHub issue). After refreshing the page, the link magically started working and I concluded it was fine -- but without a doubt, it is real. I wonder if this is something to do with our VuePress configuration -- we'll figure it out ASAP.

**Comment by jlowin** [comment]
Interestingly, @joshmeek both of your URLs work for me...

**Comment by cicdw** [comment]
Yea it's weird --> I can't recreate locally _or_ in the build preview.  However, I do have a wild guess as to what's going on that I'm going to PR in a sec.

**Comment by joshmeek** [comment]
Just tried again and it doesn't seem to be happening this time around

**Comment by cicdw** [comment]
@maxalbert I believe this has now been fixed with #931 - I just tested your links (which used to be broken for me) and they work now.  I'll close if others can replicate.

**Comment by jlowin** [comment]
Seem to be working for me too, thanks!

**Comment by maxalbert** [comment]
Thanks for the quick replies everyone! I can confirm that it works now. 👍

**Comment by joshmeek** [comment]
Great to hear @maxalbert! Thanks for raising the issue
