### ISSUE TITLE
"Cancel" button does not appear for subflows started using ECSTask

### ISSUE THREAD

**Issue by maciejb** [PrefectHQ/prefect#9320]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When a subflow is running on a separate ECSTask infrastructure block, it is not Cancellable via the Prefect Cloud UI

### Reproduction

Apologies, I do no have the ability to provide a simplest possible reproduction. I am running a parent-orchestrator pattern based loosely on the recipe here: https://github.com/PrefectHQ/prefect-recipes/tree/main/flows-advanced/parent-orchestrator

The subflows are deployed using ECSTask blocks, running in AWS Fargate.

### Error

When navitating to the Flow Run page, the "Cancel" button is visible for <100ms, and then disappears. 
![image](https://user-images.githubusercontent.com/2573696/234133566-216a1294-a4bd-486b-851c-fbbbb3e8d153.png)

Expectation: that the Cancel button be visible and usable. If there is a reason why the task is not cancellable, the reason should be shown.

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Additional context

I was directed to submit this Issue after [asking in Slack](https://prefect-community.slack.com/archives/C048K0MGHNK/p1681772739510329)

**Comment by madkinsz** [comment]
Thanks! I presume this would affect any subflow created with `run_deployment` but I'm not sure. Additional reports would be helpful!
