### ISSUE TITLE
Trigger for Mapped Task that resolves to "failed" only if more than x tasks fail

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#933]
For a particular mapped task, I may not expect 100% of the generated tasks to succeed. Further, I may not care if they don't.

It would be great to have a trigger that allowed me to specify this. For example:

```python
from prefect import task, Flow
from prefect.triggers import some_failed

@task(trigger=some_failed('>', 3))
def a_mapped_task(some_input):
    pass
```

**Comment by jlowin** [comment]
Love this idea. Maybe `at_least_failed(0.3)` and `at_most_failed(0.3)` and same for successes?

**Comment by jlowin** [comment]
Decimal: percent of tasks
Integer: number of tasks

**Comment by dylanbhughes** [comment]
Love that ☝️

**Comment by jlowin** [comment]
and `some_successful()` equivalently.
