### ISSUE TITLE
Prefect 2.10.3 introduces write access requirement for deployment creation

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#9332]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

After upgrading to `2.10.3`, some users have found that their CI pipelines are breaking. The issue appears to be caused by an attempt to write a file during the creation of a deployment via Python. Specifically, the problematic line of code is here: https://github.com/PrefectHQ/prefect/blob/490b7ab55b6667e45ed845c87326c9bb23fbd1c8/src/prefect/deployments.py#L788-L789

In the flow registration step, if the environment doesn't have write access, creating the `.prefectignore` file fails.

### Reproduction

```python3
prefect deployment build path/to/file.py:entrypoint
```

### Versions

```Text
2.10.3
```

### Additional context

A potential solution would be to improve the default handling for cases where the `.prefectignore` file does not exist. Instead of attempting to create the file and causing an error in environments with restricted write access, the code could proceed with a default behavior, such as using an empty ignore list or a pre-defined set of ignore patterns.

**Comment by tharwan** [comment]
Please note that the touch also updates the modification time if the file [exists](https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch). So just placing the .prefectignore in the repo is not a workaround!

**Comment by tharwan** [comment]
From our perspective this is a breaking change and quite easy to fix in prefect but hard to workaround from our end. If you can point me to a where to add an appropriate text I might even be able to submit a PR myself.
