### ISSUE TITLE
Artifact download through Prefect UI

### ISSUE THREAD

**Issue by davidsmfreire** [PrefectHQ/prefect#9335]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, the Artifacts page in the Prefect UI has the following set of features: text-based filtering, copy id and show raw data.

### Describe the proposed behavior

My proposal is to add a button/interface in the UI that allows downloading the file associated with markdown or table Artifacts. The download formats could be ".md" for markdown and ".csv" for tables.

**Comment by billpalombi** [comment]
@discdiver I have accepted this and added it to the backlog
