### ISSUE TITLE
Tasks are not run when `PREFECT_DEBUG_MODE` is enabled

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9340]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We recently discovered a bug with prefect.engine’s “orchestrate_task_run” function if env variable“PREFECT_DEBUG_MODE” is True.

In prefect.engine:

Here, as you can see, the task run result is only created if PREFECT_DEBUG_MODE = False:

![image](https://user-images.githubusercontent.com/68969861/234694251-a83207ed-bcb8-44d3-b566-44fc0627e265.png)

However, the variable “result” is used universally in the try…except…else statement:

![image](https://user-images.githubusercontent.com/68969861/234694379-715f4638-9d36-4eed-bd93-0e48904971e6.png)

This would lead to UnboundLocalError: local variable 'result' referenced before assignment at runtime.

**Proposed Fix:**

If I am not mistaken by the purpose of the debug mode, I believe line 1551 should always be run agnostic to if DEBUG_MODE is true or false. Only the log’s verbosity should be affected. Therefore, moving “result = await call.aresult()” outside of the if-else statement should fix the problem.

To prevent future bugs like this, maybe it is worth having integration tests that covers all the different Prefect run modes listed in:  https://docs.prefect.io/latest/api-ref/prefect/settings/#prefect.settings.PREFECT_DEBUG_MODE

 

### Reproduction

```python3
I cannot supply MRE but can reach out to get one if necessary.
```

### Error

```python3
Not seeing the result.
```

### Versions

```Text
Version:             2.10.5
API version:         0.8.4
Python version:      3.9.16
Git commit:          d48dfbbc
Built:               Thu, Apr 20, 2023 4:06 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by madkinsz** [comment]
The minimal reproduction for this is

```python
# example.py
from prefect import flow, task


@task
def test_task():
    return 1


@flow
def test_flow():
    assert test_task() == 1


test_flow()
```

```
$ PREFECT_DEBUG_MODE=1 python example.py
```

Please try to include references to the actual code instead of screenshots in the future. Relevant lines are https://github.com/PrefectHQ/prefect/blob/70ca8f1e7ba19fc0bda1fc0bde0b02572964be30/src/prefect/engine.py#L1559-L1562
