### ISSUE TITLE
`on_crashed` flow run state change hook

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#9348]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, I cannot initiate arbitrary logic when a flow run enters a CRASHED state.

### Describe the proposed behavior

With an `on_crashed` state change hook, I could define a function to be executed if the flow run transitions to a CRASHED state.

### Example Use
```
def my_crashed_hook(flow: Flow, flow_run: FlowRun, state: State):
   print("Oh noooooooo!")
       ...

@flow(
  on_running=[my_crashed_hook]
)
def my_flow():
   ...
```
### Additional context

This would be very helpful for cleaning up infrastructure in the event of a crash.

**Comment by madkinsz** [comment]
Crashes often indicate an exit _outside_ of Prefect's control. It seems dangerous to promise that we can call a hook safely during this case. As long as we put it _after_ reporting the crashed run, I think it's okay as it won't block our own reporting but the reason we didn't add this in the first place was concerns about expectations.

**Comment by billpalombi** [comment]
Thanks for the context. I saw it in the "Easily supported" category in our [internal design doc](https://www.notion.so/prefect/State-Change-Hooks-a2a382a3a4ab4c929f787bc4c6908952) and didn't think much about the implementation beyond that.

Do you think naming it `after_crash` would set the appropriate expectation? If so, should we also call the cancellation hook `after_cancellation`?

**Comment by madkinsz** [comment]
I think in general we should only call these handlers _after_ the state is reached — otherwise we're mixing the role of the local client and orchestrator so `on_...` is fine and matches our existing semantics.

> Thanks for the context. I saw it in the "Easily supported" category...

Ah funny :) perhaps we can change this issue to say "flow run state change hook"? Task runs are the more complicated case. With flow runs, we'll just need to be sure to document that we _cannot_ capture all crashes as some crashes are reported at the infrastructure level.

**Comment by billpalombi** [comment]
Agreed regarding the need to document the conditions under which this will work.

I will update all the state change hook issues to reflect that they are specific to flow runs.
