### ISSUE TITLE
`resolve_futures_to_data` should raise on failure by default 

### ISSUE THREAD

**Issue by zanieb** [PrefectHQ/prefect#9361]
`resolve_futures_to_data` should raise on failures by default and expose a `raise_on_failure` option that is passed to result retrieval from futures.

This behavior changed unintentionally in #9336 

See https://github.com/PrefectHQ/prefect/pull/9336#discussion_r1178815870

**Comment by Sage-2001** [comment]
Hey @madkinsz I want to work on this. Can you assign this to me?

**Comment by Sage-2001** [comment]
Hey, I made a pull request check it out whenever you are free, Thanks.
