### ISSUE TITLE
Resume flow run not working on Prefect Cloud

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#9364]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Only on Prefect Cloud! Could not reproduce locally.

Resuming any paused flow run via the UI fails with the error popup "Failed to resume flow run".

![image](https://user-images.githubusercontent.com/11021147/235142069-d6d12759-5c8f-44ad-8bb8-9fbffd8b544d.png)

Resuming any paused flow via the API fails with `404 Not Found`

```
$ curl --request POST 'https://api.prefect.cloud/api/accounts/<account_id>/workspaces/<workspace_id>/flow_runs/<flow_run_id>/resume' \       
--header 'Authorization: Bearer <api_key>'

{"detail":"Not Found"}                                           
```

This functionality worked with the exact same deployments yesterday. Possibly related to 2.10.6 release.

### Reproduction

```python3
- Deploy any flow to Prefect Cloud
- Run flow
- Pause flow run
- Try to resume flow run
```

### Versions

```Text
Version:             2.10.6
API version:         0.8.4
Python version:      3.8.15
Git commit:          d7a8f6bf
Built:               Thu, Apr 27, 2023 2:23 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

**Comment by zangell44** [comment]
Thanks for the writeup! We'll get this resolved today

**Comment by jbnitorum** [comment]
I am experiencing the same issue and I am still experiencing it within the last minute

**Comment by zangell44** [comment]
We deployed a fix today at approximately 2:05 pm EST. Could you check to see if this resolves your issue?

**Comment by serinamarie** [comment]
A user in the community mentioned this is now resolved for them:
https://prefect-community.slack.com/archives/CM28LL405/p1682703608787029

**Comment by jbnitorum** [comment]
I see this as now resolved.
