### ISSUE TITLE
Register Custom Project Recipes 

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/prefect#9375]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently all project creation recipes are hardcoded in a directory within the Prefect package, located here:

https://github.com/PrefectHQ/prefect/tree/main/src/prefect/projects/recipes

This is inflexible and does not easily allow for rapid startup in non-standard environments.

### Describe the proposed behavior

Ideally, new recipes would be installable as addon plugins (similar to how collections like Prefect-Dask add new runtime features) and/or through the CLI or UI (similar to how blocks and block types are registered). This would allow bespoke recipes to be deployed widely across a developer organization, streamlining and tailoring to a specific environment project creation.

### Example Use

My organization uses an self-hosted Prefect instance with a somewhat complicated environment. Currently, to start a new prefect project, users need to create a project and copy paste a series of configurations and settings and minorly adjust those settings for their particular project (typically to insert a specific Git repository Block and arguments to a Docker build step).  This is time-consuming, error prone, and inhibits user adoption. If we were able to provide recipes tailored to our environment as part of our standard developer build that would simplify the process for deploying new project based workflows to our self-hosted Prefect.

### Additional context

This feature would solve (or at least provide a general workaround) for https://github.com/PrefectHQ/prefect-gitlab/issues/18.

**Comment by serinamarie** [comment]
Projects has been deprecated, so we do not plan to work on this.
