### ISSUE TITLE
Proposal: Create new `ClientFailed` state

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#938]
This state will be a new `MetaState` which Tasks can enter into whenever `client.set_state` fails.

 This is designed specifically for the following situation: imagine a Flow with two tasks: Task A -> Task B.  Task B has an `all_failed` trigger.  Task A requests retries.

Task A tries to run but an error is raised; Task A enters a Failed state first, but for _some reason_ Task A fails to set its state in Cloud.  This produces an `ENDRUN` signal and Task A _ends in a `Failed` state_.  Task B now sees this and runs successfully.  I don't think this is intended behavior.

If instead, a bad client call produced a `ClientFailed` meta state which:
- is not considered finished
- _wraps_ the previous state

We could avoid the incorrect execution of Task B.

**cc:** @jlowin

**Comment by joshmeek** [comment]
@cicdw Just for clarification, this state is only valid when in context of cloud?

**Comment by jlowin** [comment]
Handling erroneous state handlers leads to recursive logic very quickly (who should handle the resulting state handler state?), so while this state is broadly applicable, at this time we will only introduce it for a set of known Cloud issues.
