### ISSUE TITLE
serialization error for dask-yarn as executor

### ISSUE THREAD

**Issue by fvannee** [PrefectHQ/prefect#939]
I'm trying to run Prefect with a custom executor using dask-yarn. I use the DaskExecutor class for this and pass as argument the cluster object from dask-yarn.

Eg.
cluster = YarnCluster(environment='venv:///home/florisvannee/my_env',
                      worker_vcores=2,
                      worker_memory="2GiB")
\# create flows etc.
executor = DaskExecutor(address=cluster)
flow.run(executor=executor)

But this yields an exception. Any way this can be worked around? It looks like the custom executor can't be serialized, because I'm passing the cluster object rather than a string. If I look at the usual Dask documentation, this normally doesn't seem to be a problem though. Why should the executor itself be serialized anyway?

```
[2019-04-17 21:38:38,926] INFO - prefect.FlowRunner | Beginning Flow run for 'dask-example'
[2019-04-17 21:38:38,926] INFO - prefect.FlowRunner | Starting flow run.
[2019-04-17 21:38:38,926] DEBUG - prefect.FlowRunner | Flow 'dask-example': Handling state change from Scheduled to Running
distributed.protocol.pickle - INFO - Failed to serialize {'task': <Task: Constant[range]>, 'state': None, 'upstream_states': {}, 'context': {'flow_name': 'dask-example', 'scheduled_start_time': DateTime(2019, 4, 17, 21, 38, 38, 926218, tzinfo=Timezone('UTC')), 'date': DateTime(2019, 4, 17, 21, 38, 38, 926242, tzinfo=Timezone('UTC')), 'today': '2019-04-17', 'yesterday': '2019-04-16', 'tomorrow': '2019-04-18', 'today_nodash': '20190417', 'yesterday_nodash': '20190416', 'tomorrow_nodash': '20190418', 'task_id': '6114ec9e-67e5-47f6-a449-69c429d68818', 'task_name': 'Constant[range]', 'task_slug': None}, 'task_runner_state_handlers': None, 'executor': <prefect.engine.executors.dask.DaskExecutor object at 0x7f5ca42668d0>}. Exception: no default __reduce__ due to non-trivial __cinit__
[2019-04-17 21:38:38,948] INFO - prefect.FlowRunner | Unexpected error: TypeError('no default __reduce__ due to non-trivial __cinit__',)
[2019-04-17 21:38:38,948] DEBUG - prefect.FlowRunner | Flow 'dask-example': Handling state change from Running to Failed
[2019-04-17 21:38:38,948] ERROR - prefect.Flow | Unexpected error occured in FlowRunner: TypeError('no default __reduce__ due to non-trivial __cinit__',)
```

**Comment by cicdw** [comment]
Hi @fvannee - thanks for the issue!  Also happy to see you're trying out interesting Dask configurations with Prefect :D 

Prefect's `DaskExecutor` accepts a _string_ for the scheduler address of your cluster; the `DaskExecutor` is Prefect's custom interface to Dask, so for interacting with it you should reference [Prefect's documentation](https://docs.prefect.io/api/unreleased/engine/executors.html#daskexecutor) over Dask's.

In your case, I believe the following change should work:
```python
executor = DaskExecutor(address=cluster.scheduler_address)
```

Let me know if that solves your problem!

**Comment by fvannee** [comment]
Thanks for your quick reply! I'm not sure if that solves it though. If I execute it how you specify, it does serialize, but I'm getting a timeout after that while connecting to the scheduler (I'm running everything locally in a pseudo-distributed fashion).
If I make it a bit simpler, and just do this:

cluster = YarnCluster(environment='venv:///home/florisvannee/my_env',
                      worker_vcores=2,
                      worker_memory="2GiB")
client = Client(cluster.scheduler_address) # just Client(cluster) works fine
print(client.get_versions(check=True))

I'm already getting errors about version mismatches while doing the get_versions check. So, I do think we can't connect directly there, but have to do it through the cluster object.

**Comment by fvannee** [comment]
Apologies - the version mismatches was something wrong on my side. And it looks like there was also something going wrong with the timeout, but I am not sure what exactly. I tried again and now it works fine. Thanks for the help!
