### ISSUE TITLE
Environment Variables in infra overrides are ignored with workers

### ISSUE THREAD

**Issue by eudyptula** [PrefectHQ/prefect#9397]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Setting "image" in infrastructure override on a deployment works as expected when using the new docker worker.

However, setting environmental variables like "env.SOMETHING": "ELSE" does not seem to be applied when using the docker worker.

### Reproduction

```python3
{
"image": "some image",
"env.VAR": "some var"
}
```

### Versions

```Text
Prefect 2.10.6
Prefect-docker 0.2.2
```

**Comment by desertaxle** [comment]
Thanks for the issue @eudyptula! When setting environment variables via `infra_overrides` you need to specify an object for the `env` key like so:

```json
{
  "image": "some image",
  "env": {
    "VAR": "some var"
  }
}
```

Can you give that a try and see if that works for you?

**Comment by eudyptula** [comment]
@desertaxle Yes that fixed it. But it also means that this is a change which breaks backward compatibility between agents and workers.

We have been running with the env.VAR notation for quite a while now, and it worked fine on agents. Can't remember what part of your documentation/guides it came from though.
