### ISSUE TITLE
Improve documentation around use of GitHub auth for Projects for SSH, classic PAT, fine-grained PAT 

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9401]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Users were observed having difficulty providing the correct format for different authentication methods at PACC SF and in other situations

### Describe the proposed change

TBD

### Additional context

@gabcoyne @desertaxle @jamiezieziula @zzstoatzz @jawnsy  have had some involvement here and might be able to add context.

**Comment by jmesterh** [comment]
The UI hint is confusing. We were entering the token as shown in the GUI, eg: 
```
{jdoe}:{github_pat_xyz...}
```
when this is what actually worked:
```
jdoe:github_pat_xyz...
```
