### ISSUE TITLE
Failure to register SIGTERM signal handler for flow cancellation

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#9403]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When cancelling a flow run, the `report_flow_run_crashes()` function may encounter an ignored `ValueError` raised by the `signal.signal()` function because only the main thread can set a signal handler, but the `report_flow_run_crashes()` function is executed in a non-main thread.

This causes issues where the function does not properly set the SIGTERM signal in order for the flow run to be marked as cancelled. 

https://github.com/PrefectHQ/prefect/blob/b7bf2538cbd08438bf05cf6b2d85d01922c8ba54/src/prefect/engine.py#L1712-L1728

### Reproduction

```python3
import os
from prefect import flow
from time import sleep

@flow
def my_flow():
    pid = os.getpid()
    print(f"pid: {pid}"
    sleep(100)

if __name__ == '__main__':
    my_flow()
```

Once the flow begins, copy the pid and run:
```bash
kill -15 <pid>
```

### Error

```python3
It terminates after hitting the `ValueError` in `report_flow_run_crashes()`.
```

### Versions

```Text
2.10.6
```

**Comment by madkinsz** [comment]
Note this does not raise a `ValueError`, we fail to register the signal handler which raises a value error which we swallow/ignore. The issue here is that we do not successfully register a SIGTERM handler for cancellation.

**Comment by serinamarie** [comment]
Oh good point about the `ValueError` being swallowed. I'll update the title.
