### ISSUE TITLE
Work pool UI does not show volumes for docker pools

### ISSUE THREAD

**Issue by eudyptula** [PrefectHQ/prefect#9406]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When volumes is set on a work pool for docker containers, it is not shown in the UI.

The volumes is neither shown on the right side pane when viewing the work pool, nor when editing the work pool. When editing the the volumes block just show the default example.

However, volumes are set correctly. They are visible when browsing the DB directly, and all our flows runs as expected.

### Reproduction

```python3
1. Create a docker work pool.
2. Set volumes.
3. View or edit the work pool, volumes are not visible.
```

### Versions

```Text
Version:             2.10.6
API version:         0.8.4
Python version:      3.10.6
Git commit:          d7a8f6bf
Built:               Thu, Apr 27, 2023 2:23 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

**Comment by desertaxle** [comment]
Thanks for reporting this issue @eudyptula! I was able to replicate and we'll start working on identifying a fix soon!
