### ISSUE TITLE
Cloud UI - List/Tuple Input Field changed: Item -> Code

### ISSUE THREAD

**Issue by toro-berlin** [PrefectHQ/prefect#9409]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Item input fields for list and tuple parameter types are shown as code input fields.
Before (last week or the week before), we could enter list/tuple items one after another into a dedicated input field for the item types. Perhaps also the set type should have the item input field type. 

### Reproduction

1. Deploy this flow to prefect cloud
2. Create a custom flow run

```
import datetime
from typing import Dict, List, Optional, Set, Tuple

from prefect import flow, get_run_logger
from pydantic import UUID4, BaseModel, Json

class PureTypes(BaseModel): 
    bool_type: Optional[bool]
    int_type: Optional[int]
    float_type: Optional[float]
    str_type: Optional[str]
    list_type: Optional[List[str]]
    tuple_type: Optional[Tuple[str, str]]
    dict_type: Optional[Dict[str, str]]
    set_type: Optional[Set[str]]
    date_type: Optional[datetime.date]
    time_type: Optional[datetime.time]
    datetime_type: Optional[datetime.datetime]
    uuid_type: Optional[UUID4]
    json_type: Optional[Json]

@flow(name="Pure Types Example")
def main(pure_types: PureTypes, pure_types_defaults: PureTypes = PureTypes()) -> None:
    logger = get_run_logger()
    logger.info(f"{pure_types=}")
    logger.info(f"{pure_types_defaults=}")
```

### Error

![image](https://user-images.githubusercontent.com/120258756/235875023-91e3ff60-864f-4ec3-b310-424651a06674.png)

![image](https://user-images.githubusercontent.com/120258756/235875124-ae69dbea-fa90-4446-b7d2-e0269434d9ae.png)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Prefect Cloud
```

**Comment by quassy** [comment]
Can confirm. This is an issue for us because it makes it impossible to pass nothing to optional parameters like `parameter_optional_list: Optional[list[str]] = None,`
```
Validation of flow parameters failed with error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 304, in retrieve_flow_then_begin_flow_run
    parameters = flow.validate_parameters(flow_run.parameters)
  File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 351, in validate_parameters
    raise ParameterTypeError.from_validation_error(exc) from None
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - parameter_optional_list: value is not a valid list
 ```

**Comment by toro-berlin** [comment]
Thanks for your feedback @znicholasbrown.
I understand your point regarding complex types and the hassle of catching them in the items.
Also, I was not aware of the duplication issue. 

Nonetheless, this is a step back for our flow operators: With Prefect, we aim to provide a human-friendly interface for our flows that even business people can use without training or a separate handbook. After the change, I must train them to enter the items in a technical representation not designed for humans again.
So I would appreciate it if you could put human-friendly input forms for these parameter types on your roadmap. It already would help us to have them for simple types (string, int).

Two follow-up questions:
- We expect JSON input for those types, not Python-like representation. Is this correct?
- Are there release notes for such Cloud (UI) changes? Then I have a chance to catch such changes before our internal users run into them.

BTW: As a tech person, I like the new tab to enter all parameters as a JSON you just released!

**Comment by znicholasbrown** [comment]
Hi @toro-berlin - chatting with the product teams about how we could support this better. In the meantime, to answer your questions:

1. That's correct - JSON-compatible inputs, not Python
2. We don't have formal release notes for the Cloud UI - generally releases follow the same cadence as the open source but for more specific UI-related changes, most everything is tracked in the [UI library changelog](https://github.com/PrefectHQ/prefect-ui-library/blob/main/CHANGELOG.md)

**Comment by lucawork** [comment]
We have also faced this change in UI behavior and, like @toro-berlin, we are also providing Prefect as an interface to non-technical people, so we would like to have a more user-friendly interface. 

We don't need anything fancy, but having the ability to visualize a list/tuple as it was before will be greatly appreciated.

**Comment by quassy** [comment]
Still a bug.

**Comment by pleek91** [comment]
In the new enhanced deployment parameters ui lists have a much better experience. This is available in cloud and will soon be available in open source. Using the example from the OP I get the following

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/a0cdd39c-6a98-4077-bd75-8e958434d86a)

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/a745e900-e21e-480f-967d-747e0a36efac)

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/0b70f5f3-b967-4bb4-a10c-26d14e2bd9df)

And when I add some values it looks like this

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/84998ca7-d0fc-43db-8aa7-8b53cedfe7e2)

You can still use json if you prefer 

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/d5246d28-07e2-4f60-a617-1ca2252481f6)

**Comment by toro-berlin** [comment]
Hey @pleek91, I really like the new interface for lists/tuples/sets. It is an improvement compared to the input options we had before.
For us, especially the support for lists of Pydantic Models (more than one field per list item) is a significant step forward!

Appreciate your work - I will close this bug now

**Comment by quassy** [comment]
Now the JSON input is completely missing the default values, is that already a known issue somewhere?
