### ISSUE TITLE
List of tutorials inconsistent between nav sidebar and Tutorials-Contents page

### ISSUE THREAD

**Issue by maxalbert** [PrefectHQ/prefect#942]
Small issue, but the tutorials listed on the [Tutorials > Contents](https://docs.prefect.io/guide/tutorials/) page are slightly different from the ones which appear in the navigation sidebar (the order is different, and a couple of them are missing on the Contents page).

The sidebar contains the following items:

- Advanced Features
- Using Prefect as a Calculator
- Deployment: Logging
- Deployment: Dask
- ETL
- Local Debugging
- Slack Notifications
- Flow Visualization

Whereas the Contents page contains the following items:

- ETL
- Using Prefect as a Calculator
- Flow Visualization
- Advanced Features
- Prefect Slack Integration
- Prefect Deployment: Dask

**Comment by jlowin** [comment]
Thanks @maxalbert - we were hoping to use Vuepress 1.0 to autogenerate the contents but now that #770 is delayed we will need to keep them in sync the old fashioned way :)

**Comment by maxalbert** [comment]
Hmm, somehow I'm still seeing this issue:
<img width="1420" alt="Screen Shot 2019-06-16 at 21 12 42" src="https://user-images.githubusercontent.com/2692805/59569006-8a77e080-907b-11e9-9e87-71df256a4f98.png">

As another consequence of the wrong order, the "previous" and "next" links at the bottom of each tutorial also point to the wrong pages.

For example, on the "ETL" tutorial page they point to "Deployment: Dask" and "Local Debugging" (when instead they should be pointing to "Contents" and "Using Prefect as a Calculator"):
<img width="1410" alt="Screen Shot 2019-06-16 at 21 13 49" src="https://user-images.githubusercontent.com/2692805/59569047-efcbd180-907b-11e9-98b8-b7c18a1678cc.png">
