### ISSUE TITLE
Remove built-in Kubernetes manifest command

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/prefect#9421]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

We currently provide a way for users to generate Kubernetes manifests via the Prefect CLI. 

### Describe the proposed behavior

In general, Helm is the preferred way to install software on Kubernetes, and we recommend using our Helm chart instead.

This proposes that we deprecate the original installation method and recommend that users use the Helm chart instead. Alternatively, we could replace the current manifest command with a script that installs Helm and runs `helm template` on users' behalf.

Our documentation will describe how to install with Helm, and can replace the existing command with a compatibility shim that runs `helm` commands instead.

**Comment by enriched-h** [comment]
Hi @jawnsy I am new to open source and I would like to be assigned this issue. Can you please provide guidance on how I can resolve this issue

**Comment by madkinsz** [comment]
Similar to the deprecation of the `prefect orion` CLI command group at https://github.com/prefecthq/prefect/blob/2a90c5efdb4bc5c6b137396952bcdc823fd5c138/src/prefect/cli/server.py#L50-L54 you can deprecate the `prefect kubernetes manifest` section at https://github.com/PrefectHQ/prefect/blob/2a90c5efdb4bc5c6b137396952bcdc823fd5c138/src/prefect/cli/kubernetes.py#L27-L30 and recommend users use the Helm charts instead.

**Comment by enriched-h** [comment]
Hi @madkinsz super thanks, I created a pull request for the commit, I'll wait for you guys to review

**Comment by shindodkar** [comment]
Hi, @jawnsy is this issue is open?

**Comment by madkinsz** [comment]
Hey @shindodkar there are two open pull requests for this already.
