### ISSUE TITLE
Add `Retrying` to flow and task run state filters

### ISSUE THREAD

**Issue by KESilverTide** [PrefectHQ/prefect#9430]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Task Runs tabs does not allow to filter for Retrying state. The only "running" states are Running, Pending or Paused 

### Reproduction

Accurses after applying retry on the failed or crashed flow.  

### Error

![image](https://user-images.githubusercontent.com/92714068/236137035-c1907c07-e65d-4ffd-970e-ca1e64345ceb.png)

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

**Comment by billpalombi** [comment]
Hi @KESilverTide. Currently, we only support filtering by [state type](https://docs.prefect.io/latest/concepts/states/#state-types). `Retrying` has a `Running` type , so it should be included when you filter for running.

I'm going to generalize your request a bit to allow for filtering by any state name.

**Comment by KESilverTide** [comment]
Well, if this is the case, the Retrying state is not picked up by Running filter

**Comment by billpalombi** [comment]
OK I will attempt to replicate that.

**Comment by billpalombi** [comment]
I was mistaken. A `retrying` filter should be included. I've triaged this accordingly. Thank you for submitting this.
