### ISSUE TITLE
Blocked request for logger-1.min.js (coming from logrocket) because CSP is not mentioning cdn.lr-ingest.com

### ISSUE THREAD

**Issue by yumedzi** [PrefectHQ/prefect#9436]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I see the request to https://cdn.lr-ingest.com/logger-1.min.js is blocked:
![SCR-20230504-pted](https://user-images.githubusercontent.com/3896505/236247915-fcaa8f65-60af-469a-aed7-b16ccbfabc1d.png)

The error in the console:
`Refused to load the script 'https://cdn.lr-ingest.com/logger-1.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' blob: https://js.stripe.com https://cdn.redoc.ly https://fast.trychameleon.com https://*.googletagmanager.com https://cdn.segment.com https://cdn.segment.prefect.io https://cdn.logrocket.io https://cdn.lr-ingest.io https://cdn.lr-in.com https://cdn.lr-in-prod.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

I think it is coming from the fact that cdn.lr-ingest.com is not included in CSP, only cdn.lr-ingest.io is.

### Reproduction

In Prefect Cloud open the running deployment run and check Network panel and Console of browsers' Dev tools.

### Browsers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

**Comment by znicholasbrown** [comment]
Thanks @yumedzi - this'll be fixed shortly and I'll close the ticket when it's done

**Comment by jawnsy** [comment]
Looks like we updated the incorrect CSP (connect-src instead of script-src), so reopening. I'll work on fixing this
