### ISSUE TITLE
Ideas for a pre-built dependency graph visualization (aka DAG view)

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9465]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

In Prefect 1.0, we were able to get a projection of a flow before running it by calling [visualize()](https://docs-v1.prefect.io/core/advanced_tutorials/visualization.html) on the flow object and seeing a graph visualization of the DAG. We understand that with the dynamic nature of flows and tasks in Prefect 2.0 this is harder to achieve; the DAG is resolved at runtime and may vary under different data conditions.

### Describe the proposed behavior

We propose adding a dry-run mode in which:

a.       The flow is run without actually running the tasks

b.       Prefect projects how the resolved DAG of the flow would look with some heuristics such as:

   i.      If a task is always run, then it will be included in the DAG visualization
   ii.      If a task consumes the result of another task or waits for another task, that dependencies would be drawn in the DAG visualization

   iii.      If there is an if-else condition, then the tasks conditionally run could be marked distinctly in gray, or something like that.

   iv.      We can even start by ignoring some more complex dynamic DAGs if the logic to determine how the flow run will be resolved is too complex.

c.       The projected DAG can be visualized as a PNG DAG (like in 1.0) / in the server UI

### Additional context

This recipe may be relevant:

https://github.com/PrefectHQ/prefect-recipes/tree/main/flows-advanced/declarative-graph-orchestrator

**Comment by batuhanfaik** [comment]
As someone with a somewhat static DAG, I would love to see these implemented as well. DAG visualisation is also the main reason I opened #9194 a while back.

**Comment by billpalombi** [comment]
We will address this need with a solution along similar lines.

**Comment by mbgrabbe** [comment]
This feature would be valuable for my team.  At the moment, we need to examine the last successful flow run to visualize what a flow is attempting to do.
