### ISSUE TITLE
prefect 2.10.7 docker image unable to use DockerContainer block

### ISSUE THREAD

**Issue by kuiber** [PrefectHQ/prefect#9474]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

prefect 2.10.7 docker image unable to use `DockerContainer` block.

### Reproduction

```python3
docker run -it -v /var/run/docker.sock:/var/run/docker.sock prefecthq/prefect:2.10.7-python3.11 python -c "import docker; print(docker.from_env())"
```

### Error

```python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/docker/client.py", line 96, in from_env
    return cls(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

### Versions

```Text
Version:             2.10.7
API version:         0.8.4
Python version:      3.11.3
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

### Additional context

Running the same command with the `2.10.6` docker image returns a working docker client.

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock prefecthq/prefect:2.10.6-python3.11 python -c "import docker; print(docker.from_env())"
<docker.client.DockerClient object at 0x40021d6410>
```

I believe the issue is related to this bug in the [docker-py](https://github.com/docker/docker-py/pull/3114#issuecomment-1531399614) project.

I've confirmed that the version of requests is upgraded in `2.10.7` from `requests==2.28.2` to `requests==2.30.0`. Installing the older version of requests (which also downgrades `urllib3` from `2.0.2` to `1.26.15`) in the `2.10.7` image allows `docker-py` to work again.

```
pip uninstall requests
pip install requests==2.28.2

python -c "import docker; print(docker.from_env())"
<docker.client.DockerClient object at 0x4002273d10>

prefect version
Version:             2.10.7
API version:         0.8.4
Python version:      3.11.3
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

**Comment by madkinsz** [comment]
See https://github.com/docker/docker-py/issues/3113 — this is fixed in the latest docker-py version. Our next release will have the latest docker-py version. In the meantime, you can install it on container start with the environment variable `EXTRA_PIP_PACKAGES="docker>=6.1.0"`

**Comment by swestrum-rii** [comment]
I don't think this was fixed, at least in the container tagged`prefecthq/prefect2.10.8-python3.9` - will this be fixed in the next release?
