### ISSUE TITLE
Rerunning subflows with same idempotency key is not reflected in UI

### ISSUE THREAD

**Issue by PiotrSiejda** [PrefectHQ/prefect#9483]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If we rerun flows with same idempotency key they are not registered in the UI. This is due to the fact that on a given flow (subflow) there is literally field parent_task_run_id so there can not be multiple tasks pointing to one subflow.

### Describe the proposed behavior

We should be able to create subflows that are being created from different subflows. In my opinion there should be additional many to many relation table between tasks and flows. This way any time we reference subflow it would be correctly displayed.

### Example Use

Run following code many times:

```
import time

from prefect import task, flow, get_run_logger
from prefect.deployments import Deployment, run_deployment


@flow(persist_result=True)
def subflow_sync_ok():
    get_run_logger().info('Here I am!')
    time.sleep(2)
    return 'done processing'


@task
def my_run_deploy(deployment_name):
    f1 = run_deployment(
        name=deployment_name,
        parameters={},
        flow_run_name='My_run',
        idempotency_key='My_run',
    )
    res = f1.state.result()
    get_run_logger().info(f'Results ready! {res=}')
    return res


@flow
def main_flow_sync_ok(deployment_name):
    get_run_logger().info('Starting subflow! So excited')
    rsp = my_run_deploy.submit(deployment_name)
    rsp2 = my_run_deploy.submit(deployment_name)
    get_run_logger().info(rsp.result())
    get_run_logger().info(rsp2.result())


if __name__ == '__main__':
    dep = Deployment.build_from_flow(subflow_sync_ok, name="test_subfows")
    dep_id = dep.apply()
    main_flow_sync_ok(f'{subflow_sync_ok.name}/test_subfows')
```

### Additional context

We have a heavy (sub) flow which is central part of many flows
We want to rerun the top flow with different idempotency key (clean run), but we want to interface it's subflows as they were (for example because they were computationally heavy).

This issue is related to: https://github.com/PrefectHQ/prefect/issues/7288

**Comment by PiotrSiejda** [comment]
No, https://github.com/PrefectHQ/prefect/pull/8796 would imho introduce in this case just a race condition. The problem is that there is 1:many relation implemented, while it can be many:many. If we have 2 flows pointing to one subflow with idempotency key then we have race condition on setting the "parent_task_run_id".

**Comment by madkinsz** [comment]
@PiotrSiejda I do not follow. If you are creating a child flow run with an idempotency key, then only the first call to `create_flow_run_from_deployment` will succeed and the second will do nothing. In that case, the second call _should not_ link the child flow run to the current flow run because it has already been created by another flow run.

**Comment by PiotrSiejda** [comment]
Why the second call should not link the child flow run to the current flow run? If it does not then the API won't show the relation and the relation won't appear on the GUI (or will appear based on race condition). It's just that in many cases it is more effective (shorter code, more intuitive code or faster execution) to share a subflow between two flows than any other alternative.

> In that case, the second call _should not_ link the child flow run to the current flow run because it has already been created by another flow run.

This relation _should not_ be about race condition - who first created the subflow but about flow-subflow relationship where each flow can have multiple subflows and each subflow (with idempotency key) can have multiple parent flows.

**Comment by PiotrSiejda** [comment]
Because of the limitations above of `create_flow_run_from_deployment ` I use directly REST API and observe id the `deployments/xxx/create_flow_run` created new subflow (201) or the subflow was there (200). If I see 200 I am forced to do the workaround I have described above. If `create_flow_run_from_deployment` was not prone to the race condition (always recorded the new relation) then I would much rather just use the function rather then use rest api + some workarounds.

Nevertheless I understand that recording all the relations and removing this race condition would require rewriting the db, and big parts of code so I know it's nothing to be expected in near future. All I'm asking is information if this might be done in distant future or won't be done.

**Comment by PiotrSiejda** [comment]
> Thanks for sharing some more details! Unfortunately, I don't really see this as a race condition. An idempotency key says "do not create this run if it has already been created".

Yes exactly this is what I want. I want to have exactly one subflow. The only problem is that I want it to have many parents. Now although subflow is not created again it is not recording the fact that it was called by another flow again. Hence the GUI is broken in this situation and doing top-down search becomes non trivial.

> Perhaps you're looking for some other method of preventing your child flow run from duplicating work? Maybe you want to use task cache keys and always spawn the child flow run?

The problem is that I have some heavy computations that can triggered multiple times, but should be calculated just once. That is why I love the idea of idempotency key as then I have the same object (subflow) returned in another place. I have to protect myself with idempotency key as from my point of view if subflow is called with same idempotency key - it is just one subflow. I can not use caching as this is another race condition. If I understand correctly if the task is triggered with same parameters second time before first one completes - it will be run twice if I use caching and not idempotency key.

I understood that the whole purpose of idempotency key on flow is that no mater how many times creation of flow is called - we always return the same object/flow. I would just want to have it extended to subflows. As we have to store/track the flow-subflow relations I would love to have this relation to be stored for all the pairs and not only the random first one.

**Comment by akhil-elucidata** [comment]
@PiotrSiejda I've the same requirement, where I'd like to have the same child flow-run mapped to multiple parent task-runs.
Can you please help out, in case you've found a workaround?

**Comment by PiotrSiejda** [comment]
@akhil-elucidata We have not found a workaround. We have redesigned our flow so that multiple parent relation would not be needed. I must admit that this had a side benefit of simpler and better code on our side.
