### ISSUE TITLE
Removing Schedules from Deployments not easy aside from using API calls.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9488]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

From a User:

We create deployments programmatically by calling `deployment = Deployment.build_from_flow(...)` followed by `deployment.apply()`. When we have a schedule we want to set for a deployment we first set `deployment.schedule = <the schedule>`. When we don’t have a schedule we leave `schedule` at its default value of `None`. This works for the first deployment, but when we’ve published a deployment with a schedule, and then publish it again without the schedule (ie publish to the same deployment name but with `schedule=None` this time), the schedule is not removed from the UI and continues running. We’ve worked around this by setting `prefect_deployment.is_schedule_active = False` when we don’t have a schedule anymore. This removes the scheduled runs, but leaves the schedule itself sitting on the right side. This could be confusing for people from our team.
Is this a bug, or is there a way to fully remove schedules when updating deployments programmatically like this? Basically we want to programmatically do the equivalent of pressing the schedule’s 🗑️ `Remove` button on the UI.

### Reproduction

```python3
# A workaround using our API is as follows:

    existing_deployment: DeploymentResponse = await prefect_client.read_deployment(deployment_id)
    deployment_model: schemas.core.Deployment = schemas.core.Deployment.parse_obj(existing_deployment.dict())
    deployment_model.schedule = None
    deployment_model.is_schedule_active = False
    await prefect_client.update_deployment(
        deployment=deployment_model,
        schedule=None,  # type: ignore
        is_schedule_active=False)
```

### Versions

```Text
2.9
```

**Comment by billpalombi** [comment]
My apologies for allowing this to go stale. It's definitely worth exploring improvements to the UX here. I've added it to our backlog.

**Comment by WillRaphaelson** [comment]
So i did some digging on this, pasing none into the yaml file for schedule works as expected, so I think this is just. flag for @cicdw to have this as a piece of acceptance criteria for new python deployments ux? note that this is not asking for a request with NO schedule field to remove the schedule, but for a use to be able to explicitly get schedule as none and see the schedule removed.

**Comment by mahiki** [comment]
I am building deployments with the shell client, and it appears there is no way to remove a schedule from deployment that had a schedule except for deleting the deployment and rebuilding it.

```sh
poetry run prefect deployment build \
    "src/deployments/bulk_extracts.py:bulk_extracts"  --name "daily"
     # etc

poetry run prefect deployment set-schedule --cron '00 9 * * MON-WED'
```
Now the deployment exists, and I can turn off the schedule in the UI. However rebuilding with a command like this doesn't remove the CRON:

```sh
poetry run prefect deployment set-schedule --cron ''
```
The `set-schedule` command help doesnt show any option that could help.

**Comment by cicdw** [comment]
@taylor-curran can you try this and confirm whether it works for you:

```python
deployment = Deployment.build_from_flow(..., load_existing=False)
```

That should help with the Python case.  For the CLI, you may need to manually edit the generated YAML file before applying it.  

Neither solution is ideal, so I'll look into better ways of exposing this behavior.

**Comment by Bada-S** [comment]
I had another user mention this. They are updating deployments via CI/CD and manually updating the YAML file every time isn't ideal. It would be nice if there was a command to deploy with no schedule set explicitly. A flag for this would be helpful for their use case

**Comment by ymtricks** [comment]
We would like to see it fixed as we are using the CLI in a CI flow as well.

**Comment by zacharymostowsky** [comment]
Hello, we have a similar issue. We specify deployments in a prefect.yaml file. When I change the slug of a schedule for some deployment, the new schedule is created but the old one also remains. How to get the schedule removed automatically?
