### ISSUE TITLE
Github source code PrefectHQ/graphs not found

### ISSUE THREAD

**Issue by code1704** [PrefectHQ/prefect#9506]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Where is the source code of PrefectHQ/graphs? [github.com/PrefectHQ/graphs](https://github.com/PrefectHQ/graphs) 404

### Reproduction

- https://github.com/PrefectHQ/prefect/blob/main/ui/package.json#L14
- https://www.npmjs.com/package/@prefecthq/graphs

```python3
visit [github.com/PrefectHQ/graphs](https://github.com/PrefectHQ/graphs)
```

### Error

```python3
page not found
```

### Versions

```Text
2.x
```

**Comment by znicholasbrown** [comment]
Hi @code1704. This was an oversight; we'll make that repo public shortly and close this ticket when it's complete - thanks for letting us know.
