### ISSUE TITLE
Make codebase the source of truth of deployed flows with Projects

### ISSUE THREAD

**Issue by MattDelac** [PrefectHQ/prefect#9514]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The current deployment logic is
- Create a new flow in your codebase (eg github)
- Deploy that flow in Prefect Cloud
- Delete the flow in the codebase
- The flow still shows up in Prefect Cloud

So we need to manually (or programmatically) delete those ghost flows that do not exist in our codebase anymore

### Describe the proposed behavior

The current deployment logic is
- (same) Create a new flow in your codebase (eg github)
- (same) Deploy that flow in Prefect Cloud
- (same) Delete the flow in the codebase
- The flow has been deleted in Prefect Cloud

### Example Use

Also in Prefect 1.0 there was concepts of "Projects" so here it would be nice to also have conditions per tags.

For example

### Codebase A
- Deploy flows with tags "group=A"
- Use a flag like `prefect deploy --sync` to tell prefect that the codebase should be mirrored in Cloud
- Delete flows with tag "group=A" that do not exist anymore in the codebase A

### Codebase B
Do the same logic as codebase A but the way to "isolate"/differentiate the 2 codebase is through tags

**Comment by madkinsz** [comment]
Hey @MattDelac — how do you expect us to know that the flow has been deleted from GitHub? We currently have no pattern where we are actively monitoring your repository for changes — this is generally something that we avoid as it violates the hybrid model.

**Comment by MattDelac** [comment]
> how do you expect us to know that the flow has been deleted from GitHub?

No that's not the expectation. I expect Prefect to look at all the flows currently in Github and compare them against all the flows in Cloud.
Also, this does not have to be the default behavior. Just a flag to make it work that way. Like the [`--sync` flag from poetry](https://python-poetry.org/docs/managing-dependencies#synchronizing-dependencies)

> this is generally something that we avoid as it violates the hybrid model

I don't understand how the approach I am proposing would do that. Can you please expand?

**Comment by MattDelac** [comment]
> I see I got confused about the GitHub part — you want to perform a `prefect deploy --sync` that deploys all of the flows in a directory tree and deletes flows that were previously deployed for that directory tree but that are not present anymore?

Yes something like that.


For example, this is the wrapper I had to write for Prefect 1.0 (simplified)
```python
@prefect.command()
def register_flows(
    project_name: str = PROJECT_NAME,
    ...
) -> None:
    """ Register Prefect flows in https://cloud.prefect.io/ for the current project """
    flows = find_all_flows()
    print(f"Found {len(flows)} flows\n{' '.join([f.name for f in flows])}")

    for f in flows:
        register_flow_to_prefect(flow=f, project_name=project_name, environment=environment)

    flows_delete = flows_to_delete(
        project_name=project_name, directory=project_folder, environment=environment
    )
    print(f"Found {len(flows_delete)} flows to delete\n{' '.join([f.name for f in flows_delete])}")
    for flow in flows_delete:
        delete_flow(flow=flow, environment=environment)
```

The logic was more or less 1 GH repository == flows for a given Prefect project.
The concept of projects do not exist in Prefect 2.0 so we might need to filter some flows from the Cloud using tags.


For reference, this was other part of the code (simplified)
```python
def get_prefect_projects_with_flows(project_name: str, environment: ENVIRONMENTS) -> PrefectProject:
    """Get all the flows that are registered in Prefect Cloud for the current project. A new version of a Flow in prefect results with a new Flow ID. Thus this query return only the latest version of each Flow.
        If the project_name is used multiple times, it will raise an error.

    params:
        project_name: The name of the project.
        environment: The environment to get the flows from.

    returns:
        A PrefectProject object where List[PrefectFlow] contains the flows with their latest version.
    """
    client = get_client(environment=environment)
    query = f"""
    query{{
        project (where: {{
            tenant_id: {{_eq: "{client.tenant_id}"}},
            name: {{_eq: "{project_name}"}}
        }}){{
            id
            name
            flows (
                order_by: {{
                    name: asc_nulls_last
                    version: desc_nulls_last
                }},
                distinct_on: name
            ) {{
            id
            name
            version
            is_schedule_active
            run_config
            }}
        }}
    }}
    """
    result = client.graphql(query=query)["data"]["project"]
    if len(result) == 0:
        raise ValueError(f"There is no Prefect project with the name '{project_name}'")
    elif len(result) > 1:
        raise ValueError(f"There are multiple Prefect projects with the name '{project_name}'")

    return parse_obj_as(PrefectProject, result[0])

def delete_flow(flow: PrefectFlow, environment: ENVIRONMENTS) -> None:
    """Delete a flow in Prefect Cloud.

    params:
        flow: The flow to delete.
    """
    query = f"""
    mutation{{
        delete_flow(input: {{
            flow_id: "{flow.id}"
        }}) {{
            success
            error
        }}
    }}
    """
    client = get_client(environment=environment)
    client.graphql(query=query)
```

Hope that helps
