### ISSUE TITLE
JSON serializing for `create_table_artifact` should not allow NaNs

### ISSUE THREAD

**Issue by tmthyln** [PrefectHQ/prefect#9524]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A table saved with `create_table_artifact` that contains NaNs of any sort will be serialized via [`json.dumps`](https://github.com/PrefectHQ/prefect/blob/93c41a0a656944881115c5616a6b004a1d0d333d/src/prefect/artifacts.py#LL127C28-L127C33), but this is not properly displayed in the Prefect UI. Tables will appear empty showing "No results" although the raw data shows the full JSON. (JSON parsing fails since `JSON.parse` in the browser does not accept NaNs whereas `json.dumps` in Python will default to encoding them.)

Without knowing this, it looks like there was some issue with the table, but it's really an issue of incompatible encodings.

Possible fixes?:
- Maybe it would be nice to at least throw an error on the Python side (e.g. set `allow_nan=False` for `json.dumps`) so the user is aware that these saved table artifacts are not visible in the UI. However, I see how this could cause issues for those who don't care about viewing certain artifacts in the UI and just want to persist results.
  - Relatedly, could also automatically replace NaNs with e.g. nulls, but changing the value of the user's artifact is probably worse.
- Custom/different parser for JSON in the UI: I'm not a prefect developer, but I imagine this is more work than necessary or desired.
- No code change, but a note is put in the docs for `create_table_artifact` that tables with NaNs can be saved as artifacts, but will not display properly in the UI. That way users can do their own processing beforehand (just like we should be doing for non-JSON serializable objects in tables too?).

### Reproduction

```python3
from prefect.artifacts import create_table_artifact

sample_table = [
    {'key': 'ae165d', 'numeric': 0.85},
    {'key': '55dy7e', 'numeric': float('nan')},
]

create_table_artifact(
    key='some-table',
    table=sample_table,
    description='This table contains NaN',
)

# then see artifacts page on Prefect UI
```

### Error

```python3
No stack trace; table artifact is shown as "No results" in Prefect UI.
```

### Versions

```Text
Version:  2.10.0
API version: 0.8.4
Python version: 3.9.16
Git commit: 6115fd2c
Built: Thu, Apr 6, 2023 3:12 PM
OS/Arch: linux/x86_64
Profile: default
Server type: server
```

**Comment by tmthyln** [comment]
Actually, checking back through the issue templates, this might make some sense as a Bug for the Prefect UI (although it maybe should be handled before it hits the UI).

**Comment by znicholasbrown** [comment]
Hi @tmthyln - thanks for the great write up; this is on our radar and we'll use this as the tracking ticket moving forward.
