### ISSUE TITLE
Prefect cli has poor performance for even basic commands like --help

### ISSUE THREAD

**Issue by AutumnSun1996** [PrefectHQ/prefect#9529]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The prefect cli is slow(takes several seconds) for even most basic commands (like `prefect --help`).

### Reproduction

```python3
Run `prefect --help` or `prefect --version`, and get result in like several seconds to more than 10 seconds.

These commands takes more than 10 seconds in one of my vps(linux), and around 7 seconds in my windows machine(i7-9700 CPU, 32GB mem, with python installed at SSD).
```

### Versions

```Text
In the Linux vps:
Version:             2.10.4
API version:         0.8.4
Python version:      3.7.3
Git commit:          b6d0433a
Built:               Thu, Apr 13, 2023 5:34 PM
OS/Arch:             linux/x86_64
Profile:             dev
Server type:         server

In Windows Machine:
Version:             2.10.7
API version:         0.8.4
Python version:      3.7.6
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

### Additional context

Guess there are too many imports with some time-consuming side affects.
Should get some improvement if we can isolate the cli so that there will be no imports into server or agent codebase when not necessary.

Does any one have similar problems? I'll try to investigate this problem further, and find the real cause.

**Comment by madkinsz** [comment]
We definitely see that the CLI is slow. There seems to be relatively high variance depending on the setup. It's a priority of mine to look into this. If you want to look into it too and share any findings here it'd definitely be appreciated!

**Comment by madkinsz** [comment]
The CLI is a lot faster now! See 


- https://github.com/PrefectHQ/prefect/pull/9558
- #9557
- #9571 
- #9577
