### ISSUE TITLE
Default and Favorite Views for Flow Runs Page

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#9533]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the only way to access filtered views on the Flow Runs page is through the drop down.  When you visit the page you always start with the 'Default View' which shows all flows in all states.

### Describe the proposed behavior

There should be a way to make one of your saved views be the default when you first pull up the page.  This could be a simple addition to the options for a view (in addition to Share View and Delete View).

Secondly I think it would be really helpful if you could quickly flip through your most used views (favorite views).  This could be a toggle at the top of the page.  This could be a tag you look at frequently or something like all failed flows or all running flows.  It's a little quicker than going through and selecting the exact states.

### Additional context

![image](https://github.com/PrefectHQ/prefect/assets/9852181/b4ee06d0-9dcf-4ea5-8f57-57635ebef44c)

**Comment by madkinsz** [comment]
Related to (but not a duplicate of) https://github.com/PrefectHQ/prefect/issues/9468
