### ISSUE TITLE
Force timeout during flow execution

### ISSUE THREAD

**Issue by angelika233** [PrefectHQ/prefect#9548]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

1.x

### Describe the current behavior

There is an option in flow to specify max_runtime. After flow runs longer than the specified amount of time final state of the flow will be Failed - flow is executed till the end.

### Describe the proposed behavior

Option similar to max_runtime, but instead of waiting for flow to finish it could force flow fail after certain time.

### Example Use

It doesn't "waist" the time while tasks are executing after specified time.

**Comment by madkinsz** [comment]
Hey @angelika233 — this feature is added in Prefect 2 but we won't be adding new features in Prefect 1.
