### ISSUE TITLE
Lack of documentation on how to use PREFECT_API_KEY

### ISSUE THREAD

**Issue by NicholasFiorentini** [PrefectHQ/prefect#9549]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

I'm trying to use `PREFECT_API_KEY` to protect my Prefect server (a test server). It seems the UI is not using this value to call the APIs. Am I missing something?

### Describe the proposed change

Clarify how to use `PREFECT_API_KEY` to protect Prefect server APIs.

**Comment by NicholasFiorentini** [comment]
Thanks for the workaround. In my case, I'm using the helm chart, and I would avoid using custom code.

**Comment by flapili** [comment]
how do you ensure the api is not accessed without authorization header then ? with a reverse proxy config ?

**Comment by flapili** [comment]
I would recommand few custom lines of codes instead of your setup, but just a personnal preference 😅

**Comment by NicholasFiorentini** [comment]
> I would recommand few custom lines of codes instead of your setup, but just a personnal preference 😅

Yeah, but then at every upgrade, I have to keep the code aligned, considering it is modifying the internals of Prefect server. This is obviously for test environment, not a production one, where it seems the only sensible choice is to use Prefect Cloud.

**Comment by flapili** [comment]
you could also use your reverse proxy to redirect to a custom app which set cookies, or are you using nginx as proxy ? you could add the Authorization token to proxied requests with `proxy_set_header authorization "Bearer abcd"`

**Comment by madkinsz** [comment]
To clarify, `PREFECT_API_KEY` is only used for Prefect Cloud. You are welcome to extend the open source server to support authentication, but we are unlikely to do so.

**Comment by discdiver** [comment]
Closing as PREFECT_API_KEY is only for Prefect Cloud.
