### ISSUE TITLE
Documentation search shows API reference results first

### ISSUE THREAD

**Issue by zanieb** [PrefectHQ/prefect#9553]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

When searching in the docs, the API reference results are often shown before our actual documentation e.g. search for `return_state`

### Describe the proposed change

The API reference search results should _always_ be shown after other documentation results even if it is a worse match.

**Comment by discdiver** [comment]
I will make a PR that will deemphasize the API search results - may not always show after other docs, but will reduce their prevalence.
