### ISSUE TITLE
Allow configuration of a work pool's base job template via the CLI

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9576]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Prefect allows the creation of work pools via:
- the UI
- the `prefect work-pool create` command
- Starting a worker pointed at a work pool that hasn't been created yet

Only when creating a work pool via the UI can the user edit the base job template for the work pool. The base job template of an existing work pool can also only be edited via the UI.

### Describe the proposed behavior

Add an option to the `prefect work-pool create`, `prefect work-pool update`, and `prefect worker start` CLI commands that allows users to specify the path to a JSON or YAML file that defines a base job template for a work pool. This will allow users to manage their work pool configuration via CI/CD pipelines alongside their deployments.

The API would need to support the validation of submitted base job templates to avoid a bad base job template from breaking a work pool.

To assist users in creating custom base job templates, it would also be useful to be able to fetch a default base job template for a worker and write it to a file as a starting point.

### Example Use

Start a worker with a custom base job template:
```bash
prefect worker start --type kubernetes --pool my-k8s-pool --base-job-template ./path/to/template.yaml
```
If the work pool already exists, then the worker would print a warning to notify the user that the work pool already had a base job template and the one provided via the CLI will not be used.

Create a work pool with a custom base job template:
```bash
prefect work-pool create my-k8s-pool --type kubernetes --base-job-template ./path/template.yaml
```

Update the base job template of a work pool:
```bash
prefect work-pool update my-k8s-pool --base-job-template ./path/template.yaml
```

**Comment by marcm-ml** [comment]
This is pretty crucial to have a "infrastructure-as-code" deployment for our use case. Is there progress on that?

**Comment by jawnsy** [comment]
Pull requests implementing these features:

* https://github.com/PrefectHQ/prefect/pull/10776
* https://github.com/PrefectHQ/prefect/pull/10780
* https://github.com/PrefectHQ/prefect/pull/10784

**Comment by marcm-ml** [comment]
Thanks for working on this 👍

Can you show me how these PRs implement the ability to specify a different base job template when creating/updating a work pool?

**Comment by jawnsy** [comment]
@marcm-ml Sorry I'm still working on it 😄 I've been doing these in separate PRs to make reviewing easier.

The ability to create a work pool with a template is here: https://github.com/PrefectHQ/prefect/pull/10793

I'll be working on the feature to support updating work pools with a new job template next!

**Comment by serinamarie** [comment]
@desertaxle I think it would be good if we can get a documentation PR on configuring a work pool's base job template via the CLI before closing this

**Comment by zhen0** [comment]
@serinamarie / @desertaxle - do we still need docs for this?

**Comment by desertaxle** [comment]
Docs were added in https://github.com/PrefectHQ/prefect/pull/10844. All items for this issue have been completed.
