### ISSUE TITLE
When creating an automation notification from the UI, don't abandon work after coming back from block creation

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9593]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When creating a notification automation from the UI, if I create a new notification block, I lose all work on the automation. 

### Describe the proposed behavior

Return to the previous automation screen without losing data.

### Example Use

They wouldn't lose their work.

### Additional context

We discussed this elsewhere earlier, maybe Slack. I believe @desertaxle was involved and agreed this was a change worth making. 

We had a user at PPCC comment on the need for this change.

**Comment by discdiver** [comment]
Yep, sure thing. It is. Maybe that's where it went :)

**Comment by zhen0** [comment]
@pleek91 - I think we did this for blocks using local storage?  Could we add the same here?
