### ISSUE TITLE
Flows Rerunning without Retries

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9613]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Passing this information from a user that I am working with:

> I am having an issue where the flows re run on their own after completing. Even when they complete successfully.
> 
> I need to prevent them from rerunning. They are scheduled every 15 minutes but when they re run on their own it drags out the time and it doesn’t finish within that 15 minutes.
> 
> In the attached photo you can see the run count is 7. It has been running 7 times for all of the flows that I am seeing this issue with.
> 
> Retries are not configured, and you can see them as 0 in the details.

![image](https://github.com/PrefectHQ/prefect/assets/68969861/8afff7d7-4b35-4d5c-bc62-ef1c7e737d1e)

### Reproduction

```python3
Flows are scheduled every 15 minutes.

The flows are using sequential task runner currently, same issue happened with concurrent and dask task runners though.

The infra block is Kubernetes.

Retries are not configured, and you can see them as 0 in the attached photo.
```

### Versions

```Text
2.10.9
```

**Comment by RafalBielickiIM** [comment]
I've encountered this lately. The k8s job has backoff limit set to 6 by default. And the additional retries are coming from k8s job rather from prefect itself.

**Comment by madkinsz** [comment]
A run can reach a FAILED state and the pod will restart repeatedly on Kubernetes if the flow run image is  <2.10.3 but the server is Cloud or a recent OSS version. Upgrade the flow run image to resolve or disable the `backoffLimit` in the Kubernetes job configuration. We're looking at updating the default backoff limit in workers and agents.

This is due to an interaction between #9175 and #9152
