### ISSUE TITLE
Broken Link in UI under Notifications Tab

### ISSUE THREAD

**Issue by digitalghost-dev** [PrefectHQ/prefect#9620]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When clicking on the "View Docs" link on notifications tab, I get a 404 message.

### Reproduction

Use Prefect UI

### Error

![404-error](https://github.com/PrefectHQ/prefect/assets/86637723/1c190ffd-881b-42b2-ae28-22b6bff21fe8)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.10.10
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```

**Comment by zhen0** [comment]
Thanks for flagging @digitalghost-dev
