### ISSUE TITLE
Ability to remove deployment using python

### ISSUE THREAD

**Issue by djagoda881** [PrefectHQ/prefect#9623]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I use the Deployment.build_from_flow() function in the python file to create deploymets. To create a deployemt I run the file with the` python3 my_deployments.py` command.  Deployment builds up and everything works correctly.

### Describe the proposed behavior

There may be several deployments in the file and when I want to delete them I have to find them using prefect cli or inside prefect cloud. If there are only a few deployments it is not a big problem, but if there are a lot of them it becomes problematic. I think a good solution would be to add a flag to the file I want to delete. For example, when I want to remove all deployments from prefect cloud using python file,  I run the command:

`python my_deployments.py --delete`

and if I want to create deployments I run 

`python my_deployments.py`

### Example Use

It would allow automation with CI/CD, for example. You could create a large number of deployments or you could delete deployments with a single command.

**Comment by billpalombi** [comment]
Thanks for the feedback @djagoda881! We're thinking about how to best address the deployment deletion need. We'll provide any updates here.

**Comment by dansola** [comment]
Wondering if any progress has been made here. 

Is there a way to delete a deployment in python? For example, one may want to make a deployment with `Deployment.build_from_flow()`, call it within another flow using `run_deployment`, and then delete it since it is no longer needed.

**Comment by MaleicAcid** [comment]
really need this, hope can support
