### ISSUE TITLE
Add documentation on how to build the docs locally

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#9638]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

I was looking to make a change to the Prefect docs, and I noticed that the contributing page doesn't mention the best way to build the docs locally.

### Describe the proposed change

Let's add a short section describing:
* What we use to generate our docs (mkdocs)
* How to build the docs locally
* How to make simple updates to the documentation

**Comment by billpalombi** [comment]
Agreed we should do this for sure
