### ISSUE TITLE
File-based cache and easy loading of prefect pickle files to python objects

### ISSUE THREAD

**Issue by marcoBmota8** [PrefectHQ/prefect#9644]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Right now prefect does not have a "fully" out-of-the-box way to allow users to define tasks that they want to run once, save the result Python object/data to a file and skip that task to be run if the result file exists. Besides, the current functionality to save result files with python objects usign the available serializers (mostly pickle) does not allow to load suck files and retrieve the python object.

### Describe the proposed behavior

I have writen functions and complementary code (aided by a wonderful guy from prefect Nate Nowack) that I have put together in a GitHub repo called `prefect_utils` ([link](https://github.com/marcoBmota8/prefect_utils))

For simplicity I will just add what the two main features 1)`cache_file_based_fn` and 
2)`load_pickle` do here:

1)Running a task with the following decorator
```python
@task(
        cache_key_fn=cache_file_based_fn,
        persist_result=True, 
        result_storage=LocalFileSystem(basepath='~/results'), 
        result_storage_key='results.pkl',
        result_serializer="pickle",
        cache_result_in_memory=False
       )
``` 
Saves the object returned by the task as a pickle file `'result.pkl'`. If the task is called again and the file exists it will not run but retrieve the data stored in the file.

2)As a user I would like to retrieve the object that`'result.pkl'` saved at a later date in a separate file or even just inspect it using python tools like pandas, etc. 
Thus, it is imperative that the files saved by the task can be loaded much like one will do by calling `pickle.dump(object, 'whatever/path/result.pkl')` and `object = pickle.load('path/to/result.pkl')`.
As of now, the files saved by prefect tasks are saved as json even when using pickle serializers.

To be able to load the pickle files into python objects, Nate Nowack from prefect and I designed `load_pickle`.

### Example Use

1)
``` python
import numpy as np
from prefect import task
from prefect.filesystems import LocalFileSystem
from prefect_utils.cache_functions import cache_file_based_fn

@task(cache_key_fn=cache_file_based_fn,
      persist_result=True, 
      result_storage=LocalFileSystem(basepath='~/results'), 
      result_storage_key='result.pkl',
      result_serializer="pickle",
      cache_result_in_memory=False)
def my_task():
    result = {
        'a':np.array([1,1]),
        'b':np.array[2,2]()
    }
    
    return result

@flow  
def pipeline():
   my_task()

pipeline()
```
2)
``` python
from prefect_utils.utils import load_pickle

result_dict = load_pickle('path/to/pickle/file')
```

### Additional context

```python
None
```

**Comment by zzstoatzz** [comment]
just to note, this issue came out of a discussion in community where this was a workable solution, where some similar convenience method might make sense

## example

if a task is using pickle `result_serializer` and uses a `result_storage_key=test.pkl` then

```python
In [51]: import base64
         from pathlib import Path
         from prefect.results import PersistedResultBlob
         
In [52]: pickle.loads(
            base64.b64decode(
               PersistedResultBlob.parse_raw(
                  Path("~/.prefect/storage/test.pkl").read_bytes()
               ).data
            )
         )
Out[52]: {'a': 1}
```
