### ISSUE TITLE
Prefect Cloud: Automations - Work queue health filters queue by name

### ISSUE THREAD

**Issue by taljaards** [PrefectHQ/prefect#9673]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A `Work queue health` automation will trigger when any queue with a matching name meets the trigger criteria (similar to #9433). I suspect they automation filters by name instead of by ID, with the fix probably being similar to 4230db3b03dd168b126bcac75a6772d622aaa5cf.

### Reproduction

Create two work pools, each with a queue inside that has the same name as the other. Set an automation to trigger on queue health, and notice that at fires whenever any one of the two queues becomes unhealthy.

### Versions

```Text
n/a
```

**Comment by chrisguidry** [comment]
Thanks @taljaards, I'll take this to the team to diagnose.  Thank you!

**Comment by chrisguidry** [comment]
Hi @taljaards, I need a bit more information before I can diagnose this.  Do you mind visiting your automation, switching the "Trigger Type" to "Custom" on step 1, then pasting the JSON you see there?  You don't need to save it, I'd just like to see how your automation is configured.

**Comment by taljaards** [comment]
Hi @chrisguidry. Find below:
```json
{
  "match": {
    "prefect.resource.id": [
      "prefect.work-queue.2aa024db-13b8-4203-a89b-2db6487959ad",
      "prefect.work-queue.1b8a1a01-e2b8-402d-a51e-9682d044bda2"
    ]
  },
  "match_related": {},
  "after": [
    "prefect.work-queue.unhealthy"
  ],
  "expect": [
    "prefect.work-queue.healthy"
  ],
  "for_each": [
    "prefect.resource.id"
  ],
  "posture": "Proactive",
  "threshold": 1,
  "within": 540
}
```
![image](https://github.com/PrefectHQ/prefect/assets/6089256/7fe23144-c09b-4c44-940e-62aec444255e)

I have a few different pools and each of them have a `default` queue.

**Comment by chrisguidry** [comment]
Thanks, @taljaards!  I'm puzzled because this is referring to the work queues by their IDs (the resource IDs in the "match" section).  I'll dig in a bit more to see if I can reproduce this on my end, thanks!

**Comment by taljaards** [comment]
Chris identified I probably misdiagnosed. The timing seems very tight - my queue went unhealthy and then healthy again two seconds after the automation fired. By the time I got the the work pools/queues in the UI, the state had already changed.

I'm closing this for now. When this happens again, I'll closely examine the event feed and re-open if required.
