### ISSUE TITLE
Incorrect description of image parameter of DockerContainer.

### ISSUE THREAD

**Issue by AjeelAhmed1998** [PrefectHQ/prefect#9678]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

[Link to the page](https://docs.prefect.io/latest/api-ref/prefect/infrastructure/#prefect.infrastructure.DockerContainer)

The image parameter takes the whole link/name of the image, not just the tag, the documentation makes it sound like you only have to put in the tag of the image which is not true.

### Describe the proposed change

Rewrite the description so it's clear you have to enter the whole name/link of the image and not just the tag.

**Comment by madkinsz** [comment]
@AjeelAhmed1998 please provide an example of what you tried to provide and what needs to be provided, thanks!

**Comment by AjeelAhmed1998** [comment]
Here's what I provided: 
`registry.gitlab.com/toystory/sandcastle/project-daydreamers/daydream:latest`
The documentation implies that I provide something like: 
`latest`
which would not make sense because now the DockerContainer only knows the tag of the image I'm talking about not the actual image.

**Comment by rkscodes** [comment]
Does this looks good ? 
image : An optional string specifying the name of a Docker image to use. Defaults to the Prefect image.

**Comment by AjeelAhmed1998** [comment]
Yeah that looks good to me. 

Although now that I think about it when I don't pass the `image` parameter I just see a None there(in the dashboard) instead of the Prefect image the documentation is talking about. Might be worth investigating into.

**Comment by rkscodes** [comment]
Yeah sure that would be a nice touch but maybe a separate issue is good to track it.

**Comment by madkinsz** [comment]
I don't think the dashboard can show the default because it's generated dynamically depending on your Prefect and Python versions.
