### ISSUE TITLE
Handle single callables passed as state change hooks

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#9679]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Right now, we require passing state change hooks as a list, even a single hook. We should decide whether or not to passing single callables and either raise or allow.

Note that this confusion could be partially due to https://github.com/PrefectHQ/prefect/issues/9391

### Reproduction

```python3
@flow(on_completion = on_completion_flow_logger, on_failure = on_failure_flow_logger)
```

### Error

```python3
File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2219, in _run_flow_hooks

    for hook in hooks:

TypeError: 'function' object is not iterable
```

### Versions

```Text
Reported issue from user. Unclear but probably since 2.8.3

https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-283
```

**Comment by rkscodes** [comment]
I am working on this issue. 

As suggested I will add code to throw exceptions in both flow/task files.
