### ISSUE TITLE
Create image artifacts through the SDK and render them in the UI

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#9681]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, users can only create link, markdown, and table artifacts with Prefect.

### Describe the proposed behavior

Users can create an image artifact with a `create_image_artifact()` function that accepts either a `.png` or a `.jpeg`. The image is rendered in the artifact record in the UI.

### Example Use

I want to publish a histogram of my data set produced during workflow execution to the UI so that I can more quickly troubleshoot execution errors related to the data my workflow is processing.

**Comment by billpalombi** [comment]
@discdiver FYI

**Comment by madkinsz** [comment]
Is the expected implementation here that the user specifies a file path of a local image and we write the bytes of that image to our database for display?

**Comment by billpalombi** [comment]
I hadn't considered the implementation. I'm definitely happy to discuss the trade offs around particular implementations when we pick this up.
