### ISSUE TITLE
Github Credentials for Private Repo not usable with Prefect Projects

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#9683]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using a Github Credentials block with Projects in the pull step fails with exit code 128.

Note - this is distinctly possibly using a Secret block, so there is a viable solution / workaround.
It is confusing based on what the expectation is to provide however - I'd anticipate using a GitHub Credentials block to pull from a GitHub repository. 

### Reproduction

```python3
git clone https://github.com/prefectcboyd/test-private-repo.git

cd test-private-repo

prefect work-pool create -t process test-pool

prefect project init

########
# Update Pull Section like:
pull:
- prefect.projects.steps.git_clone_project:
    repository: https://github.com/prefectcboyd/test-private-repo.git
    branch: main
    access_token: "{{ prefect.blocks.github-credentials.github-boyd }}"
########

prefect deploy ./hello_world.py:hello_world -n private-repo-deploy -p test-pool


from prefect import task, flow
from prefect import get_run_logger
import time

def this_is_not_a_task(logger):
    logger.info("I am not a task context")

@task
def log_platform_info():
    logger = get_run_logger()
    logger.info("hello world")
    this_is_not_a_task(logger)


@flow(log_prints=True)
def hello_world():
    logger = get_run_logger()
    log_platform_info()


if __name__ == "__main__":
    hello_world()
```

### Error

```python3
Cloning into 'test-private-repo'...
fatal: unable to access 'https://github.com/prefectcboyd/test-private-repo.git/': URL using bad/illegal format or missing URL
16:24:28.114 | INFO    | prefect._internal.concurrency.threads - Exiting worker thread 'WorkerThread-0'
16:24:28.117 | ERROR   | Flow run 'cherubic-ostrich' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/engine.py", line 294, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/deployments.py", line 204, in load_flow_from_flow_run
    output.update(await run_step(step))
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/projects/steps/core.py", line 78, in run_step
    return await from_async.call_soon_in_new_thread(
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/christopherboyd/virtualenvs/prefect2/lib/python3.9/site-packages/prefect/projects/steps/pull.py", line 120, in git_clone_project
    raise RuntimeError(
RuntimeError: Failed to clone repository 'https://github.com/prefectcboyd/test-private-repo.git' with exit code 128.
```

### Versions

```Text
Version:             2.10.10
API version:         0.8.4
Python version:      3.9.16
Git commit:          8159450b
Built:               Thu, May 18, 2023 3:43 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         cloud
```

### Additional context

I can update documentation [here](https://docs.prefect.io/latest/concepts/projects/) and [here](https://docs.prefect.io/latest/tutorial/projects/#dockerized-deployment) to provide working examples. That said, I still feel like it's either a bug or requires more details regarding the expected inputs here - Secrets vs GitHub Credentials.

**Comment by prefectcboyd** [comment]
As mentioned above, providing a secret like follows does work:
```
pull:
- prefect.projects.steps.git_clone_project:
    repository: https://github.com/prefectcboyd/test-private-repo.git
    branch: main
    access_token: "{{ prefect.blocks.secret.secret-github-boyd }}"

**Comment by discdiver** [comment]
See similar for GitLab: https://github.com/PrefectHQ/prefect/issues/10282

**Comment by serinamarie** [comment]
I'm closing this as I believe this issue is completed. Feel free to reopen if another issue arises.

**Comment by razvanvilceanu** [comment]
I am having the same issue. In my case I create the deployment via CLI and my yaml file pull looks like this:
`
pull:
- prefect.deployments.steps.git_clone:
    repository: https://xxx/private_repo.git
    branch: dev
    access_token: '{{ prefect.blocks.secret.deployment-private_repo-repo-token }}'
`

Is there anything else I could try to make this work?

**Comment by gorbondiga** [comment]
I've found a complication when setting the credentials for GitLab. In the organization where I work, we host our own Gitlab instance, and the repositories are under the url: https://git.<Organisation>.com/<group>/<project>.git.

In the file `prefect/runner/storage.py` line 710 we see how the code checks for a `gitlab` prefix in the url in order to parse the username to the url, which in our case `gitlab` prefix is not contained:

```
    elif "gitlab" in netloc:
        return (
            f"oauth2:{user_provided_token}"
            if not user_provided_token.startswith("oauth2:")
            else user_provided_token
        )
``` 

Thus, when creating the block on the prefect server, the string should already contain the username, for example:
`oauth2:<token>` instead of just `<token>`

**Comment by luciano200x** [comment]
I had this issue, adding {username}: in front of the PAT did the trick for cloning my gitlab repo.

**Comment by kp-leadinfo** [comment]
@luciano200x not with `oauth2` ?
I tried to set the url with `oauth2` but does not work properly. Keep getting 128 error

What is your working URL ? I have been trying the following:
`https://oauth2:<token>@gitlab.corp/group/project.git` but does not work

**Comment by gorbondiga** [comment]
@kp-leadinfo If the gitlab server you are trying to clone from has the `gitlab` prefix in the url, as you show; `gitlab.corp...`. Then, you do not need to add `oauth2` to the PAT. Only the token

**Comment by kp-leadinfo** [comment]
@gorbondiga it also does not work
```
Failed to clone repository 'https://<token>@gitlab.group/group/project-something.git' with exit code 128.
```
