### ISSUE TITLE
Flow run timeline crashes with custom state names

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#9689]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Using states with custom names breaks the timeline view.

Even tasks without custom names do not render if this occurs.

### Reproduction

Run the following flow and view the flow run page

```python
from prefect import flow, task
from prefect.states import Completed


@task
def my_task():
    return Completed(name="Skipped")


@flow
def mre():
    my_task()


mre()
```

### Error

Timeline appears without content. Error in developer console:

<img width="1658" alt="Screenshot 2023-05-22 at 6 45 12 PM" src="https://github.com/PrefectHQ/prefect/assets/2586601/a740f00e-c1b8-4f3d-89f4-5cd1e7e9b9c1">

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.10.10+17.g9e1179a7b
API version:         0.8.4
Python version:      3.11.2
Git commit:          9e1179a7
Built:               Mon, May 22, 2023 12:50 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.5
```

**Comment by pleek91** [comment]
> If I understand #1448 correctly, it doesn't address this issue. The issue here is that _any_ custom state name breaks the timeline view, this just reintroduces one particular custom state name - _skipped_.

@billpalombi its possible its still not working but the intent of https://github.com/PrefectHQ/prefect-ui-library/pull/1448 was to allow it to fallback to "unknown" which the ui has logic and colors for. It did introduce "Skipped" as a "prefect state name" when maybe it shouldn't have. But it should also account for any state names that we don't associate with a state type. 

Again, possible that isn't working quite right.

**Comment by billpalombi** [comment]
Ok that's great, thank you! Then it's just a matter of removing the skipped state.
