### ISSUE TITLE
Add Flow/Deployment Resource Filtering on Event Feed

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9713]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A user has reported:

We find the “Event Feed” tab in Prefect server quite helpful, but it seems like the filtering mechanism is buggy:

a.       We name all our flow’s deployment by the Gitlab branch the deployment is based on

b.       This design works fine in the “Flows” Tab, as the deployments are named with “{flow_name}/{deployment_name}”

c.       However, the “Resource” filtering in “Event Feed” displays all deployments only by its deployment name. This makes it impossible for us to distinguish which flow a deployment is from:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/3ccd2e8b-8e7b-48b2-9404-ab5db4334c11)

d.       Also, it seems like if we only select a deployment (one of the “main”s), but not select any flow, we will get no result:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/6cfdc552-8868-4500-b6b6-550f34334649)

e.       But if we select a flow from the “Flows” section, it appears that no matter if we select 1 or many “main” from the “Deployment” section, we can see the expected event feeds:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/710a985d-4c5b-489a-b0de-0547f1d47a62)

f.        We believe the correct behavior here is to either show the deployments by “{flow_name}/{deployment_name}”, de-duplicate the Deployment names options, or to integrate the deployments fields with the “Flows” field in the same resource filter (like what is done in the “Flows” tab)

### Reproduction

```python3
Go to events page and reproduce in UI.
```

### Versions

```Text
In Cloud UI
```

**Comment by pleek91** [comment]
Closing in favor of https://github.com/PrefectHQ/nebula-ui/issues/2792
