### ISSUE TITLE
Task run’s retry state naming inconsistencies

### ISSUE THREAD

**Issue by PPPSDavid** [PrefectHQ/prefect#9730]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We noticed that during flow run retry, the normal tasks and tasks that create subflow run via run-deployment have different retry state names:

normal task is in a “rerunning”state
Start flow run task is in a “retrying” state. 

### Reproduction

```python3
import time
import random
from prefect import task, flow, runtime

@task
def some_task():
    if random.randint(0,1):
        raise ValueError()

@task
def some_subflow_task():
  run_deployment(some_flacky_deployment)

@flow
def some_flow():
    some_task.submit()
    some_subflow_task.submit()

# deploy and run this flow,
```

### Versions

```Text
2.10.7
```

**Comment by madkinsz** [comment]
I'm presuming you're rerunning the flow manually from the UI?

By "Start flow run task" do you mean "some_subflow_task"? 

This logic comes from https://github.com/PrefectHQ/prefect/blob/bce4777b64172a06d87b45f010273c5c59b2eda5/src/prefect/server/orchestration/core_policy.py#L402-L405
