### ISSUE TITLE
Enable deleting blocks with python SDK

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect#9755]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Blocks can be created or edited using the python SDK but cannot be deleted.

### Describe the proposed behavior

A delete method is added to blocks which enables deleting blocks from the Prefect workspace.

### Example Use

```python3
my_block = Block()
my_block.save('my-block')

my_block = Block.load('my-block')
my_block.delete()
```

**Comment by serinamarie** [comment]
Hi @austinweisgrau, thanks for the issue!

You can currently delete blocks via the CLI:
```bash
prefect block ls
```
to get the block slug, then
```bash
prefect block delete <slug>
```


Alternatively, you can use the Prefect client:
```python
from prefect.client import get_client

async with get_client() as client:
      block_document = await client.read_block_document_by_name(
          name="my-block", block_type_slug="string"
      )
      await client.delete_block_document(block_document.id)
```

**Comment by austinweisgrau** [comment]
Ah great thanks! Is this in the documentation? I couldn't find it.

**Comment by zzstoatzz** [comment]
@austinweisgrau its not highlighted in the block concept docs but its in the API docs [here](https://docs.prefect.io/latest/api-ref/prefect/client/orchestration/#prefect.client.orchestration.PrefectClient.delete_block_document)

**Comment by serinamarie** [comment]
Thanks @zzstoatzz!

@austinweisgrau, we're accepting the issue. Whoever implements this would want to add a `.delete()` method to the Block class: https://github.com/PrefectHQ/prefect/blob/main/src/prefect/blocks/core.py#L898-L905

such that you could delete like so:
```python
my_block = Block('my-block')
my_block.save()
```
```python
Block.delete('my-block')
```

**Comment by rito-sixt** [comment]
Took a stab at this in the linked PR. Would be grateful for any feedback / suggestions.
