### ISSUE TITLE
On parent flow cancellation allow subflows to continue running

### ISSUE THREAD

**Issue by gabcoyne** [PrefectHQ/prefect#9756]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently if a subflow is cancelled all child flows are also cancelled.

### Describe the proposed behavior

In the event that an attribute is set, skip the cancellation of subflows.

**Comment by PPPSDavid** [comment]
Hi Prefect, bumping this, has there been any update?
