### ISSUE TITLE
Parameter Bookmarking

### ISSUE THREAD

**Issue by trahloff** [PrefectHQ/prefect#9775]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Input parameters cannot be saved. The only available behavior is the create multiple deployments with different default parameters.

### Describe the proposed behavior

(Based off https://github.com/PrefectHQ/prefect/issues/7808#issuecomment-1396988627) 

A "saved flow params" feature analogue to the "saved views" feature that the flow-runs view has
I mocked something together:
https://www.loom.com/share/11036cc62edc4ea09d2122b0ec8e549b

No idea why Loom didn't catch the dropdown menu items. Normally looks like this: 
![image](https://user-images.githubusercontent.com/16914641/213456627-2d56c31d-5030-40cf-a520-4c341ccfbca7.png)

### Example Use

Users can save parameter inputs on-the-fly with a single click without creating a completely new deployment.

We have highly complex flows (>30 nested input parameter groups), and it would help our Ops/Project Management folks extremely to save their input parameters for later use. 

Creating new deployments with different default parameters is not a valid option for us, since every deployment needs to go through our CI/CD process and we do not want to have Ops/PM committing code to trunk just to save their parameters.

**Comment by trahloff** [comment]
Still relevant from my perspective

**Comment by trahloff** [comment]
Still relevant.

**Comment by trahloff** [comment]
Hi folks, is this something that you might take into consideration?

**Comment by pleek91** [comment]
@trahloff this is not something we have planned. Closing this issue but may revisit in the future.
