### ISSUE TITLE
@flow and @task decorated functions fail when encapsulated

### ISSUE THREAD

**Issue by EkinsMatthew** [PrefectHQ/prefect#9788]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When decorating functions within a class, execution of a function decorated with either prefect flow or task fails. 

I have taken [one of the most simple examples from the prefect tutorial](https://docs.prefect.io/latest/tutorial/first-steps/#:~:text=08%20PM%27%7D-,Run%20a%20basic%20flow%20with%20tasks,-%C2%B6) (_Run a basic flow with tasks_), and converted it to an object oriented example to show how this problem manifests.

I am able to execute the code as it appeared in the tutorial just fine, however my conversion provided below breaks. As you will see, I made no changes to the functionality, I just changed the context to one that might benefit from encapsulation.

### Reproduction

```python3
import requests
from prefect import flow, task


class ApiCaller:
    def __init__(self, url):
        self.url = url

    @task
    def call_api(self):
        response = requests.get(self.url)
        print(response.status_code)
        return response.json()

    @flow
    def api_flow(self):
        fact_json = self.call_api()
        return fact_json


obj = ApiCaller(url="https://catfact.ninja/fact")

obj.api_flow()
```

### Error

```python3
Traceback (most recent call last):
  File "C:\[redacted]\AppData\Local\miniconda3\envs\prefect\Lib\site-packages\prefect\utilities\callables.py", line 37, in get_call_parameters
    bound_signature = inspect.signature(fn).bind(*call_args, **call_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[redacted]\AppData\Local\miniconda3\envs\prefect\Lib\inspect.py", line 3211, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[redacted]\AppData\Local\miniconda3\envs\prefect\Lib\inspect.py", line 3126, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\[redacted]\prefect_oo_test\basic_test_object.py", line 23, in <module>
    obj.api_flow()
  File "C:\[redacted]\AppData\Local\miniconda3\envs\prefect\Lib\site-packages\prefect\flows.py", line 514, in __call__
    parameters = get_call_parameters(self.fn, args, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\[redacted]\AppData\Local\miniconda3\envs\prefect\Lib\site-packages\prefect\utilities\callables.py", line 39, in get_call_parameters
    raise ParameterBindError.from_bind_failure(fn, exc, call_args, call_kwargs)
prefect.exceptions.ParameterBindError: Error binding parameters for function 'api_flow': missing a required argument: 'self'.
Function 'api_flow' has signature 'self' but received args: () and kwargs: {}.
```

### Versions

```Text
Version:             2.10.11
API version:         0.8.4
Python version:      3.11.3
Git commit:          8c651ffc
Built:               Thu, May 25, 2023 2:59 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

### Additional context

This issue arose from me trying to start using prefect in an existing class based data workflow. For my workflow, I found that it made sense to encapsulate much of the data. I could flatten my workflow out of a class definition, but this would require significant refactoring and loss of functionality.

**Comment by madkinsz** [comment]
Related https://github.com/PrefectHQ/prefect/issues/7198
