### ISSUE TITLE
Prefect Automations: Support "CloudEvents"

### ISSUE THREAD

**Issue by trahloff** [PrefectHQ/prefect#9804]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, Prefect Automations only support event sources that are native to the Prefect ecosystem (e.g., Flow Run States, Work Queue Health, etc.)

### Describe the proposed behavior

Prefect Automations can be triggered from every event source that is compliant with the [CloudEvents](https://cloudevents.io/) spec.

### Example Use

A new file on GCP triggers an event on Google Cloud Eventarc, which in turn activates a Prefect Automation to execute a Flow Run that processes the new file automatically.

**Comment by trahloff** [comment]
What a timing! :tada: Happy to hear that @chrisguidry. Thanks for the fast response.

**Comment by zhen0** [comment]
@trahloff - following up to say the new cloud webhooks feature accepts cloudEvents: https://docs.prefect.io/2.10.17/cloud/webhooks/?h=cloudevent#accepting-cloudevents

**Comment by chrisguidry** [comment]
Oo yes, thanks, @zhen0 for the reminder about @trahloff's request!  Tobias, let us know what you think and if you have any problems or confusions with accepting CloudEvents.  Feel free to ping me in the Prefect community slack!

**Comment by trahloff** [comment]
Thank you, @zhen0 & @chrisguidry! This is really amazing and comes with at a great time for us :) We will certainly give it a spin soon and take you up on the offer to connect via Slack if any questions or blockers come up.
