### ISSUE TITLE
All the flows not being shown under the filter selection in UI when large number of flows exist

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#9805]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It seems that the flows filter in Flow Runs page has a limit of 50 flows in it and are sorted in ascending order.
If we have more that 50 flows deployed, we are unable to select the 51th flow in the drop down selection.

Even typing in the name of the flow in the search bar does not bring up the flow.

### Reproduction

```python3
1. Deploy over 50 flows; name not starting with `z`
2. Deploy another flow; name starting with `z`
3. On the UI, move to "/flow-runs" page
4. Attempt to filter to the flow which had the name starting with `z`
```

### Versions

```Text
Version:             2.10.7
API version:         0.8.4
Python version:      3.10.8
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
```

**Comment by billpalombi** [comment]
Thank you for bringing this to our attention, @OptimeeringBigya. I can replicate it on my end. We'll look into how to best address it.

**Comment by zhen0** [comment]
Same theme but different issue as #7581 and #7481 - we may need to redesign how we're using the combobox for filters?

**Comment by billpalombi** [comment]
Good catch, sounds like it.

**Comment by zhen0** [comment]
@pleek91 - I think you're working on this one or something very similar?

**Comment by OptimeeringBigya** [comment]
Does https://github.com/PrefectHQ/prefect-ui-library/pull/1732 solve the issue?

**Comment by pleek91** [comment]
@zhen0 yes! Assigned myself to this

@OptimeeringBigya thats just fixes this for deployments specifically but a step toward fixing this as whole! https://github.com/PrefectHQ/prefect-ui-library/pull/1751 get's us most of the way there. Will be a follow up PR after that to address flows and the others.
