### ISSUE TITLE
Retrying a flow rerun successful tasks

### ISSUE THREAD

**Issue by john-jam** [PrefectHQ/prefect#9814]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Not sure if this is the intended bahvior but when a flow containing failing tasks is retried, all the tasks are run once again and not only the failing task as the UI message indicates: `This will retry flow run {flow_name}. Any task runs in a failed, cancelled or crashed state will be run again.`

### Reproduction

```python3
import time
import random
from prefect import task, get_run_logger, flow


@task(retries=0)
def fail_randomly(task_id: int):
    logger = get_run_logger()
    if random.randrange(10) > 7:
        logger.info(f"FAIL {task_id}")
        raise RuntimeError("This failure is expected")
    else:
        logger.info(f"SUCCESS {task_id}")
        time.sleep(10)
        return task_id


@flow
def random_failure():
    for i in range(10):
        fail_randomly.submit(task_id=i)
```

### Error
Initial flow run (1 failing task):
![retry-flow-01](https://github.com/PrefectHQ/prefect/assets/37172224/266b863c-4f71-49c6-8867-3ee72776e2d9)

Retry (2 failing tasks and all other are run once again):
![flow-retry-02](https://github.com/PrefectHQ/prefect/assets/37172224/c077b602-138b-4a4c-b6fd-fa8738a2b4f4)

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.10.11
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

- We are using a `KubernetesJob` infrastructure on a K8S cluster.
- I tried to persist results with `@flow(persist_result=True, result_storage=get_result_storage("test-flow"), cache_result_in_memory=False)` but it does not change the bahavior.

**Comment by madkinsz** [comment]
@john-jam You'll need to enable `persist_result` on your task or it'll re-run — otherwise we'd throw an exception as soon as you attempted to retrieve the result of the successful task.

**Comment by john-jam** [comment]
Thanks for your response @madkinsz 

This indeed works when I enable `persist_result` on the task. I thought the behavior of `persist_result` on the flow decorator would be similar to `result_storage` (set by default to all the tasks the flow uses). Is there a way to have this behavior and define `persist_result` for all taks a flow uses?

And it works also when the task does not return anything so if I understand properly, a task won't be retried if it is completed and if its state (with or without value returned) is persisted.
