### ISSUE TITLE
Add a guide on migrating from agents to workers

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#9819]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

As workers are not necessarily backwards compatible with agents, we should ensure users who use agents can make the shift to workers seamlessly.

### Describe the proposed change

Add a tip to the workers overview section of the docs that links out to a guide on migrating from agents to workers.

### Additional context

> @eudyptula Some changes between agents and workers make workers not backwards compatible with agents. We can highlight this change when working on a guide on migrating from agents to workers.

_Originally posted by @desertaxle in https://github.com/PrefectHQ/prefect/issues/9397#issuecomment-1574017230_

**Comment by chrisguidry** [comment]
One path through this.  I had a preexisting repo with flows sitting in the root.  I'd run a traditional agent listening to a migrated "default-agent-pool" work pool.

To migrate, here's what I did:

I followed the [existing tutorial](https://docs.prefect.io/2.10.13/tutorial/projects/) to initialize a project and register a new flow to it.  I then used `prefect deploy ...` to get that flow deployed, and the CLI very awesomely let me know that I couldn't use my prior agent pool and that I needed to make a new one.  The CLI experience here was awesome.

From there I registered and deployed some of my pre-existing flows.  The process was the same and the CLI walked me through scheduling and choosing the right work pool.  Pretty flawless.

Caveat: this is all using a local process worker, and I don't have an example with real infrastructure yet.
