### ISSUE TITLE
Prompt for deployment schedule in `prefect deploy` interactive CLI

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9823]
### Summary

When running `prefect deploy`, and a schedule is not provided via the CLI or `deployment.yaml`, prompt the user to select a schedule type. Available schedule types are Interval, Cron, and RRule. After selecting a schedule type, the user should be prompted for the schedule details. Those details correspond to the configuration available for each schedule type. Once all the details are collected from the user, the created deployment should be created with a schedule matching the details provided.

**Comment by EmilRex** [comment]
@desertaxle Working off of main right now (`2.10.12+18.g3bdd5ac57`) and it seems like the `--ci` command is ignored for schedules. In other words, when I run `prefect deploy -n <my-deployment> --ci` I'm still prompted to provide a schedule.

**Comment by desertaxle** [comment]
@EmilRex That's interesting, I'm not seeing that behavior on main right now. Can you share the structure of your `deployment.yaml` file?

**Comment by EmilRex** [comment]
All the files are in this repo: https://github.com/EmilRex/kubernetes-worker-demo
