### ISSUE TITLE
Docker conda image does not execute flow 

### ISSUE THREAD

**Issue by not-Karot** [PrefectHQ/prefect#9849]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deploying a prefect agent on Google Cloud Run on docker image built `FROM prefecthq/prefect:2-python3.10-conda` starts the agent but cannot execute any flow. Same configuration, with a non conda prefect image works well as expected.

Something does not work with prefect-conda image.

I followed this [guide](https://medium.com/the-prefect-blog/gcp-and-prefect-cloud-from-docker-container-to-cloud-vm-on-google-compute-engine-2dffa026d16b)  and created a repo for template.

When running the original dockerfile (with pip image) everything works fine.
Change dockerfile to: #reproduction

### Reproduction

```python3
FROM prefecthq/prefect:2-python3.10-conda

COPY requirements.txt .
COPY setup.py .
COPY prefect_utils .

# Use the prefect environment by default
RUN echo "conda activate prefect" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]
RUN pip install --upgrade pip setuptools --no-cache-dir
RUN pip install --trusted-host pypi.python.org --no-cache-dir .

ARG PREFECT_API_KEY
ENV PREFECT_API_KEY=$PREFECT_API_KEY

ARG PREFECT_API_URL
ENV PREFECT_API_URL=$PREFECT_API_URL

ENV PYTHONUNBUFFERED True

COPY flows/ /opt/prefect/flows/

ENTRYPOINT ["/bin/bash", "--login", "-c", "prefect agent start -q default"]
```

### Error

```python3
/opt/conda/bin/python: Error while finding module specification for 'prefect.engine' (ModuleNotFoundError: No module named 'prefect')
```

### Versions

```Text
prefecthq/prefect:2-python3.10-conda
```

### Additional context

opened also a discussion on slack at https://prefect-community.slack.com/archives/CL09KU1K7/p1685978620562239
Please read that for additional content.

**Comment by madkinsz** [comment]
The command `docker run -it prefecthq/prefect:2-python3.10-conda python -m prefect.engine` finds Prefect.

Building a derived image

```Dockerfile
FROM prefecthq/prefect:2-python3.10-conda

RUN conda install --name prefect pandas
```

Also has `pandas` available `docker run -it 7dd70f86cfd69a9a83dc23effec12164891b51d2d77b750ffee195cbd3047f98 python -c "import pandas"`
and can find Prefect `docker run -it 7dd70f86cfd69a9a83dc23effec12164891b51d2d77b750ffee195cbd3047f98 python -m "prefect.engine"`

Can you reproduce this outside of Cloud Run?

**Comment by not-Karot** [comment]
Actually when I execute the following commands on my local machine:
`docker build -t myimage -f myDockerfile .`
`docker run -it myimage python -m "prefect.engine" `
the agent starts as expected. However, when I access the container via:

`docker exec -it mycontainer /bin/bash`
`$ python -m "prefect.engine"`

Of course, the Prefect module isn't found because the shell defaults to the base environment.

So my hypothesis is that when the agent on GCP VM creates a job in Cloud Run and executes the command `python -m prefect.engine`, it's actually running in the base environment. But why is this the case? As far as I know docker image used for cloud run is the same that for VM.

So, what exactly is happening when prefect.infrastructure.cloud-run-job is called? How does it run the container? Is there a way to make it activate the 'prefect' environment via `conda activate prefect` before running anything else?

<img width="1525" alt="gcp log" src="https://github.com/PrefectHQ/prefect/assets/52074617/37371f8d-2623-4d9c-9856-079b9ec7e516">

**Comment by not-Karot** [comment]
As I understand it, the CloudRunJob block is initiated with a null command as the default and then in gcp executes, as a default, `python -m prefect.engine`

I saw the source code and passed the command to CloudRunJob as:
```
block = CloudRunJob(
    image=args.image,
    region=args.region,
    credentials=GcpCredentials.load(args.block_name),
    cpu=1,
    timeout=3600,
    command=["conda activate prefect && prefect agent start -q default"]
)
```
and the error is now:
`terminated: Application failed to start: "conda activate prefect && prefect agent start -q default" not found (PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)`


So, from UI or source code, which command should I add to make it run? Everything I found on the internet works for pip images, what about conda images?

**Comment by madkinsz** [comment]
You need to use `bash -c` if you want to use `&&` in a command e.g. `command=["bash", "-c", "do thing && other thing"]`

**Comment by not-Karot** [comment]
Ok, that's fine, but which is the command to run the flow?
I sent `bash -c source /opt/conda/etc/profile.d/conda.sh conda activate prefect && python -m prefect.engine`
and the job completes successfully, but the flow is actually stuck in pending. 
Which is the command to make the Job actually execute the flow and get back results and log from prefect UI?
