### ISSUE TITLE
Deleting a flow on Prefect Cloud does not delete deployments

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#9856]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are finding that if we delete a flow from the Prefect cloud UI or from the API that we do not see the associated deployments for that flow deleted.  In fact, if there are scheduled deployments for that flow they will continue to trigger based on their schedule.  The flow run created errors saying it is unable to find the flow (see image below).  There is no way to navigate to this orphaned deployment in the UI unless you know the id or there is a flow run associated with it.  When accessing the flow run or the deployment you see that the flow name is missing.  I'm not sure what the expected behavior is for this, perhaps these flows and deployments are never supposed to actually go away and just hide in the background when deleted?  If so, then the bug is that the deployment didn't unschedule on deletion (We saw multiple future runs of the deployment still scheduled despite the flow being deleted).  If not, then there is just an issue with the deployments not deleting when the associated flow is deleted. 

![image](https://github.com/PrefectHQ/prefect/assets/9852181/5123eeea-ea6a-487a-a17a-17e92b3350a6)
![image](https://github.com/PrefectHQ/prefect/assets/9852181/dedd5ac1-d20a-463e-ac7d-1dc44bb22927)

### Reproduction

```python3
Add a flow.  Add a deployment and schedule it.  Delete a flow.  The scheduled deployment will still run.
```

### Versions

```Text
This is the error we get when the orphaned deployment runs:

Submission failed. PrefectHTTPStatusError: Client error '404 Not Found' for url 'https://api.prefect.cloud/api/accounts/XXXXXXXXXXXXXXXXXX/workspaces/XXXXXXXXXXXXXXXXX/flows/XXXXXXXXXXXXXX' Response: {'detail': 'Flow not found'} For more information check: https://httpstatuses.com/404
```

**Comment by serinamarie** [comment]
Maybe it's best that we simply have the ability to hide the flow or have some way to organize the flows page more, because "deleting" the flow doesn't actually do anything to the corresponding deployments.

**Comment by ondramie** [comment]
I'm still seeing this issue
