### ISSUE TITLE
Should introduce a very small "link" icon for linking directly to methods in docs

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#987]
Currently, you have to know how our linking scheme works to create links directly to methods / functions within the API docs.  We should add a basic "link" icon for creating these links.

**Comment by lauralorenz** [comment]
Probably some kind of vuepress icon and generation of the deterministic link would be necessary here.

For example the linking scheme is such that if you want to jump link to `prefect.core.flow.Flow.diagnostics`
the url should be
https://docs.prefect.io/api/latest/core/flow.html#prefect-core-flow-flow-diagnostics

**Comment by joshmeek** [comment]
Closing in favor of #2966
