### ISSUE TITLE
Add additional flag for non-interactive mode

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9876]
Add a `--no-prompt` flag that, in addition to `--ci`, is capable of disabling the interactive deployment UX.

**Comment by chrisguidry** [comment]
Another thing that might be useful in detecting this (to automatically toggle the behavior or otherwise warn, etc):

```
import sys

print(sys.stdout.isatty())
```

```
$ python -c "import sys; print(sys.stdout.isatty())"
True
$ python -c "import sys; print(sys.stdout.isatty())" > test.txt; cat test.txt
False
```

**Comment by madkinsz** [comment]
This would probably be easiest to implement as a `PREFECT_CLI_NO_PROMPT` setting with a lookup at https://github.com/PrefectHQ/prefect/blob/0100cfae00ba2d7974cafe8f11b0070ffcfaf18d/src/prefect/cli/root.py#L36-L37

**Comment by chrisguidry** [comment]
I like the CLI `--no-prompt` paired with and envvar `PREFECT_CLI_NO_PROMPT`, that feels a lot like other CLI tools.

**Comment by EmilRex** [comment]
> I like the CLI `--no-prompt` paired with and envvar `PREFECT_CLI_NO_PROMPT`, that feels a lot like other CLI tools.

+1
