### ISSUE TITLE
`run_shell_script` does not expand environment variables to values set in step parameter `env:`

### ISSUE THREAD

**Issue by Kevin-Grismore** [PrefectHQ/prefect#9890]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In order for environment variables to be expanded in a subprocess, `shell` should be `True`, but at least trying this on MacOS, it seems not to be.

I think this is associated with the behavior across `prefect.utilities.processutils.open_process` and `anyio.open_process`.

From [prefect 2.10.13](https://github.com/PrefectHQ/prefect/blob/2.10.13/src/prefect/utilities/processutils.py#L189):
```
    # Passing a string to open_process is equivalent to shell=True which is
    # generally necessary for Unix-like commands on Windows but otherwise should
    # be avoided
    if not isinstance(command, list):
        raise TypeError(
            "The command passed to open process must be a list. You passed the command"
            f"'{command}', which is type '{type(command)}'."
        )

    if sys.platform == "win32":
        command = " ".join(command)
        process = await _open_anyio_process(command, **kwargs)
    else:
        process = await anyio.open_process(command, **kwargs)
```

Since `prefect.utilities.processutils.open_process` requires the command to be a `list`, and that list is not rejoined into a single `str` before being passed to `anyio.open_process`, `shell` is `False`.

From [anyio 3.7.0](https://github.com/agronholm/anyio/blob/3.7.0/src/anyio/_core/_subprocesses.py#LL125C1-L135C6):
```
    shell = isinstance(command, str)
    return await get_asynclib().open_process(
        command,
        shell=shell,
        stdin=stdin,
        stdout=stdout,
        stderr=stderr,
        cwd=cwd,
        env=env,
        start_new_session=start_new_session,
    )
```

I fixed this locally by invoking `open_process` from within `prefect.projects.steps.utility.run_shell_script` like so:
```
        async with open_process(
            split_command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=directory,
            env=current_env,
            shell=True,
        ) as process:
```

Then, in `prefect.utilities.processutils.open_process` I handled the `shell` kwarg as follows, joining the command into a single string:
```
    if sys.platform == "win32":
        command = " ".join(command)
        process = await _open_anyio_process(command, **kwargs)
    elif kwargs.pop("shell"):
        command = " ".join(command)
        process = await anyio.open_process(command, **kwargs)
    else:
        process = await anyio.open_process(command, **kwargs)
```

I'd be happy to open a PR with these changes, but I'm not sure if there'd be any side effects.

### Reproduction

```python3
build:
    - prefect.projects.steps.run_shell_script:
        script: echo "Hello $NAME"
        env:
            NAME: World
```
```
>>> prefect deploy --all
Hello $NAME
```
```


### Error

_No response_

### Versions

```Text
2.10.13
```

**Comment by serinamarie** [comment]
Hi @Kevin-Grismore, thanks for creating an issue! It sounds like if we wanted to do this, users could opt-in to expanding env vars via a setting or something, as it could potentially be unsafe.

**Comment by Kevin-Grismore** [comment]
I agree, but I do want to point out that I had initially believed this would work because of [this](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/deployments/steps/utility.py#L119) example in the docstring for `run_shell_script`

**Comment by zzstoatzz** [comment]
hi @Kevin-Grismore - I think that example you reference is slightly different in the sense that the [`env` value is provided directly to the step](https://github.com/PrefectHQ/prefect/blob/5dde6060247ed464a62e7bf092d931e0e0057489/src/prefect/deployments/steps/utility.py#L75) as opposed to being expanded within the step

a solution that should work for each OS would be:
```
async def run_shell_script(...):
...
    for command in commands:
        expanded_command = os.path.expandvars(command)
        split_command = shlex.split(expanded_command)
 ```
 
 then with
 ```
 ❯ cat ~/.zshrc | rg PREFECT_ENV
export PREFECT_ENV=local
```
and this
```
pull:
- prefect.deployments.steps.run_shell_script:
    script: |
        echo "$PREFECT_ENV"
```
we'd get this from the agent logs
```
 > Running run_shell_script step...
local
```
