### ISSUE TITLE
Consolidate Projects tutorial with Deployments tutorial

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9914]
Once https://github.com/PrefectHQ/prefect/issues/9860 is complete, the 'project' concept will be removed from the Prefect lexicon. We must update the projects tutorial to reflect this change, and merge the projects tutorial with the deployments tutorial. This merge will emphasize that the new deployment UX is the suggested way to create deployments and should only be released when the new UX is ready to be taken out of beta.

**Comment by serinamarie** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/9940
