### ISSUE TITLE
Flow Runs graph is not responding well for sub-flow arrow button clicks

### ISSUE THREAD

**Issue by ChrisPaul33** [PrefectHQ/prefect#9915]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Under Flow Runs tab the graph is not responding well for sub-flow arrow button clicks - the graph is refreshing, the green line of the flow turns to white and almost invisible and the data is not shown.
We are running prefect 2.10.13 on OCP cluster.
It happens both on Chrome and Firefox

It didn't happen when we used version 2.10.4

Furthermore, the name of the subflow is written in white on a bright green background and it is hard to read.

### Reproduction

Deploy the server on OCP
Run a deployment with a parallel flow that runs as k8s job.

### Error

.

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version: 2.10.13
API version: 0.8.4
Python Version: 3.8.17
Git commit: 179edeac
Built: Thu, Jun 8, 2023 4:10 PM
OS/Arch: linux/x86_64
Profile: default
Server type: ephemeral
Server:
    Database: postgresql
```

**Comment by madkinsz** [comment]
Thanks for the report! cc @brandonreid / @zhen0

**Comment by AmanSal1** [comment]
@zanieb is this issue solved ?

**Comment by zhen0** [comment]
@ChrisPaul33 - are you still seeing this issue?  If so, could you perhaps provide a loom video or screen shot as I'm not exactly sure what you're you're referring to / can't recreate when I run a parent/sub flow run.  

I'll add a needs:design label here too for your comments about the legibility of the text.

**Comment by ChrisPaul33** [comment]
The issue got fixed! It looks great.
The legibility of the text also got fixed.
Thanks!!
