### ISSUE TITLE
Add support for service-specific credentials to `git_clone`

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9918]
Currently, the `git_clone` step only accepts a `token` field for credentials. This supports various authentication schemes, but it requires the user to understand the correct format for their service and store it correctly in a `Secret` block. This has proven unintuitive for users who often reach for a `GitHubCredentials` block and are unpleasantly surprised when it doesn't work.

We should add a `credentials` field to the `git_clone` step, which can accept credentials for GitHub, BitBucket, or GitLab repositories. The implementation of credentials handling should be extensible to include other SCM providers in the future.

**Comment by prefectcboyd** [comment]
Just adding my own observations to tack on here - 
Each provider has a slightly different flavor of authentication, and I've seen different behaviors between a repo token, and a personal access token.
In some cases it can just simply be `x-auth-token:<token>` and others `user:token`.

Then in the pull step what goes in the access_token? Is it just the access token, or the user:access token?

There are a large number of variables here depending on what SCM flavor is being used, but I think from what I have been able to see:

#1 - Adding an option for a user field 
#2 - A few visual examples with various providers
#3 - Perhaps we even include some references to major providers of 'expected' tokenized behavior? We can just link documents, but enough so we don't have to re-invent the wheel of how it should be done for their vendor, just point them to vendor docs, and provide a contrived example.

----- I'd be happy to help on this
