### ISSUE TITLE
`prefect deploy --all` only needs to run build steps once - does it for each deployment

### ISSUE THREAD

**Issue by jonaslb** [PrefectHQ/prefect#9921]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I'm trying to set up a project with multiple flows/deployments which will use the `prefect_docker.projects.steps.build_docker_image` build step in the project level `prefect.yaml` file.

But as I am testing it now, it seems that the build (and push) of the docker image is performed for each deployment, in spite of being project level defined? 

Fortunately docker does know one or two things about caching, but it still seems to take several seconds to go through all the steps and attempt to do a push to the registry - for each deployment. This hardly makes sense since the image is project-wide, so it'll be the same for each deployment.

### Describe the proposed behavior

Currently the build steps are executed in `prefect.cli.deploy._run_single_deploy` which is executed for every deployment. Here I would probably move it into `prefect.cli.deploy.deploy` and call it only once either before or after actually creating the deployments.

### Example Use

This would just be a pain relief, saving time for anyone (e.g. CD) running `prefect deploy --all`

**Comment by jacob-r-g** [comment]
+1

**Comment by jonaslb** [comment]
I decided the prefect build/push etc steps were inappropriate for docker-based projects due to this bug, so build/push in my project now happens with separate commands and a Dockerfile *before* running `prefect deploy --all` (those steps are just left empty in prefect). So I haven't seen the behaviour you describe, since I stopped using that part of it.

**Comment by zzstoatzz** [comment]
closed by https://github.com/PrefectHQ/prefect/pull/14894
