### ISSUE TITLE
Flow run submission failure by a Prefect Worker should result in `Crashed` state

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect#9939]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Following from #9523, we should make the same adjustment for Workers, where if a flow run can't be submitted to the infrastructure, then it would be regarded as `Crashed` rather than `Failed`.

### Reproduction

```python3
n/a
```

### Versions

```Text
n/a
```

### Additional context

See #9523 for the original context, and #9691 for the change to the agent.

**Comment by bunchesofdonald** [comment]
This was fixed by https://github.com/PrefectHQ/prefect/pull/9691
