### ISSUE TITLE
New storage blocks created on every flow run instead of using saved block

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#9950]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a saved storage block, a new block document is being generated for every flow run instead of referring to the block created prior. 

Issue created from conversation in Prefect Slack channel : https://prefect-community.slack.com/archives/CL09KU1K7/p1686212575760679

### Reproduction

```python3
import asyncio

import prefect
from prefect import flow, task
from prefect.filesystems import LocalFileSystem 
from prefect.serializers import JSONSerializer


# CREATES A NEW BLOCK IF IT DOES NOT EXIST
try:
    LocalFileSystem(basepath="./prefect_storage").save("a")
except ValueError:
    pass

# LOADS THE BLOCK
storage = LocalFileSystem.load("a")
# ENSURE THAT "_block_document_id" exists
assert "_block_document_id" in storage.__dict__


@task(result_storage=storage, persist_result=True, result_serializer=JSONSerializer())
async def task1():
    prefect.get_run_logger().info("Task run.")
    return "Success."


@flow
async def flow1():
    await task1()


if __name__ == "__main__":
    asyncio.run(flow1())
```

### Error

Running the code for the first time on a fresh server generates two blocks: 
1. Block named a [Expected]
2. An block created anonymously.

Every time, this flow is executed a new block is added to the block_document table.

### Versions

```Text
Version:             2.10.12
API version:         0.8.4
Python version:      3.10.6
Git commit:          ec55abdf
Built:               Thu, Jun 1, 2023 3:51 PM
OS/Arch:             linux/x86_64
Profile:             local_db
Server type:         server
```

### Additional context

We are having space issues on our database as we use flows that run large numbers of other deployments. We are generating over ~700MB of data (rough estimate) in this table alone on a daily basis.

For simplicity, Ive opted to using LocalFileSystem in the replication code. The isuue is the same with Azure block.

**Comment by cicdw** [comment]
I believe the created block is actually for storing your _flow's_ results, so you might be able to workaround this behavior by doing:

```python
@flow(result_storage=storage) # same block as for tasks
async def flow1():
    await task1()
```

This is still undesirable behavior, so I'm going to look at ways to prevent this, but hopefully the workaround at least stops your DB from filling up!
