### ISSUE TITLE
Documentation for Deployments Python SDK not created for 2.10.14

### ISSUE THREAD

**Issue by 1beb** [PrefectHQ/prefect#9964]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

https://docs.prefect.io/2.10.14/api-ref/prefect/deployments/ displays an empty page with no content. Looks like a problem with netlify deployment. The previous version has the expected content.

https://docs.prefect.io/2.10.13/api-ref/prefect/deployments/

### Describe the proposed change

Ideally the documentation would be available. This isn't a change, rather than just debugging why it didn't deploy properly.

**Comment by serinamarie** [comment]
Hi @1beb, thanks so much for raising this!
