### ISSUE TITLE
Missing default value for "work_pool_id" in FlowRun

### ISSUE THREAD

**Issue by ShardPhoenix** [PrefectHQ/prefect#9967]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The object FlowRun defines several fields, most of which are optional. The optional ones all set a default value of `None`, except for `work_pool_id`, which is missing a default. This causes type checkers (in my case Pyright) to demand we explicitly pass in `work_pool_id=None` to the constructor.

This seems like an oversight and would be simple to fix by adding `default=None` to that field.

### Reproduction

```python3
Have `FlowRun(id=flow_run_id, name=flow_run_name, state=Running(), flow_id=flow_id)` in the code and validate with PyRight
```

### Error

```python3
error: Argument missing for parameter "work_pool_id"
```

### Versions

```Text
Version:             2.10.13
API version:         0.8.4
Python version:      3.11.3
Git commit:          179edeac
Built:               Thu, Jun 8, 2023 4:10 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.42.0
```

**Comment by N3XT14** [comment]
Can I take this issue?

**Comment by rkscodes** [comment]
Alright you got it, just a sec.
