### ISSUE TITLE
Prefect deployment API ref page is missing

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#9973]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

API reference page is missing in the docs for 2.10.14.

https://docs.prefect.io/2.10.14/api-ref/prefect/deployments/

### Reproduction

```python3
Go to https://docs.prefect.io/2.10.14/api-ref/prefect/deployments/ and see that page is missing
```

### Versions

```Text
2.10.14
```

**Comment by desertaxle** [comment]
Thanks for the issue @rjhawar! We're working on a fix in https://github.com/PrefectHQ/prefect/pull/9974 and will get that out as soon as possible. In the meantime, you should be able to use the 2.10.13 deployments API reference.
