### ISSUE TITLE
`prefect deploy entrypoint` errors with "Conflicting entry found" if create a deployment and then move the directory with the flow and try to create deployment again

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9983]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

flows.json file in the root ~./prefect directory has the incorrect absolute value if you move your entrypont file and run prefect deploy again. This was tricky to debug because I didn't know where the old file path was stored.

Rerunning

`prefect deploy 104/flows.py:pipe` 

after changing the file path where you flow code exists results in:

```Conflicting entry found for flow with name 'pipe':
pipe: 
Desktop/prefect/demos/certification_courses/pacc/pacc-june-demos
/104/flows.py:pipe
```

The indicated directory no longer exists. I'm not sure why it would matter if it did exist. There is no other `flow.py` file in the directory where I run the command.
 

Relevant section of the [codebase](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/deployments/base.py):

### Reproduction

```python3
`prefect deploy my_file.py:my_flow`
```

### Error

```python3
entry found for flow with name 'pipe':
pipe: 
Desktop/prefect/demos/certification_courses/pacc/pacc-june-demos
/104/flows.py:pipe
```

### Versions

```Text
Version:             2.10.15
API version:         0.8.4
Python version:      3.10.8
Git commit:          49205e57
Built:               Fri, Jun 16, 2023 1:29 PM
OS/Arch:             darwin/arm64
Profile:             prod
Server type:         cloud
```
```


### Additional context

_No response_

**Comment by discdiver** [comment]
resolution

somehow there was a flows.json file in my root ~./prefect folder that was then found when the tree was searched for ~./prefect file. This led to the error. I'm not sure if the file was written there by my own error or not. Disadvantage of use ~./prefect for both folder names. In the future ~./prefect in the root of the project folder shouldn't be a thing so maybe won't be an issue.

**Comment by discdiver** [comment]
flows.json reappeared in the ~/.prefect directory when I ran prefect deploy. 


`    Given a path, recurses upward looking for .prefect/ directories.`  - it recursed all the way up. :)

I don't think we need either of the functions below with the move to entrypoint only deploys. If we do need them for some reason, we don't want to recurse all the way to the ~.prefect in the home directory (or wherever someone may have moved it).

```
def find_prefect_directory(path: Path = None) -> Optional[Path]:
    """
    Given a path, recurses upward looking for .prefect/ directories.

    Once found, returns absolute path to the ./prefect directory, which is assumed to reside within the
    root for the current project.

    If one is never found, `None` is returned.
    """
    path = Path(path or ".").resolve()
    parent = path.parent.resolve()
    while path != parent:
        prefect_dir = path.joinpath(".prefect")
        if prefect_dir.is_dir():
            return prefect_dir

        path = parent.resolve()
        parent = path.parent.resolve()


def set_prefect_hidden_dir(path: str = None) -> bool:
    """
    Creates default `.prefect/` directory if one does not already exist.
    Returns boolean specifying whether or not a directory was created.

    If a path is provided, the directory will be created in that location.
    """
    path = Path(path or ".") / ".prefect"

    # use exists so that we dont accidentally overwrite a file
    if path.exists():
        return False
    path.mkdir(mode=0o0700)
    return True

**Comment by discdiver** [comment]
Post deployment creation here's my ~/.prefect folder: 
<img width="369" alt="Screenshot 2023-06-16 at 8 07 31 PM" src="https://github.com/PrefectHQ/prefect/assets/7703961/53ef9d74-e014-4e40-93d1-40de81f8ed20">

**Comment by discdiver** [comment]
@desertaxle or @serinamarie - probably of interest to you.

**Comment by discdiver** [comment]
Somewhat related - flows.json also gets created and populated in ~/.prefect directory even if the `prefect deploy entrypoint` is aborted during the guided creation experience.

**Comment by discdiver** [comment]
Ideally flows.json would not be created at all

**Comment by taylor-curran** [comment]
I had the same issue but then I deleted `/.prefect/flows.json` and that fixed it 🎉

**Comment by jeremytanjianle** [comment]
> Ideally flows.json would not be created at all. We saw an error resulting from hard-to-find flows.json at PACC London.
I agree with this comment regarding `flows.json`... and that actively deleting `~/.prefect/flows.json` is quite a troublesome fix.

**Comment by johnkangw** [comment]
@discdiver @taylor-curran I have an issue where I run prefect deploy --all on my local machine (Windows), which works and populates the flow.json. The problem is that I have a GitHub action that runs the same command but errors out because the pathing is different using a Ubuntu runner. Not having a flows.json would be nice.

**Comment by discdiver** [comment]
@desertaxle fyi - passing along, @johnkangw
