### ISSUE TITLE
Change language when run `prefect deploy` to not recommend running a deployment by name

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9984]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running `prefect deploy` provides a tip to create a deployment. Part of that tip is no longer correct now that you can only call deployments by their full entrypoint.

```
Deploy a flow by name:

        prefect project register-flow path/to/file.py:flow_function
        prefect deploy --flow registered-flow-name
```

### Reproduction

```python3
`prefect deploy`
```

### Versions

```Text
2.10.15
```

**Comment by AmanSal1** [comment]
@desertaxle @discdiver Can I give it a shot ?

**Comment by discdiver** [comment]
Sounds good, @AmanSal1.

**Comment by AmanSal1** [comment]
@discdiver can I get a brief overview of what has to done ?

**Comment by AmanSal1** [comment]
![432](https://github.com/PrefectHQ/prefect/assets/121633121/aeeb1945-b81c-454d-8042-48c355f5d9f9)


@discdiver The text next to the '--flow' should be changed . What changes should be made? What should the language be corrected to

**Comment by desertaxle** [comment]
@AmanSal1 within the `prefect deploy --help` output that you posted, we want to update the `--flow` option description to be prefixed with `DEPRECATED:` to communicate that using the `--flow` option with `prefect deploy` is deprecated.

There's also a tip that is printed when `prefect deploy` is run without an entrypoint in non-interactive mode that currently says:
```
An entrypoint or flow name must be provided.

Deploy a flow by entrypoint:

        prefect deploy path/to/file.py:flow_function

Deploy a flow by name:

        prefect project register-flow path/to/file.py:flow_function
        prefect deploy --flow registered-flow-name

You can also provide an entrypoint or flow name in this project's prefect.yaml file.
```

Because the `--flow` option is deprecated it should say:
```
An entrypoint must be provided:

        prefect deploy path/to/file.py:flow_function

You can also provide an entrypoint in a prefect.yaml file located in the current working directory.
```

**Comment by AmanSal1** [comment]
@desertaxle @discdiver I have published  the PR can you review it ?

**Comment by AmanSal1** [comment]
@serinamarie I guess we can close this now as it has been resolved.

**Comment by th0ger** [comment]
> we want to update the `--flow` option description to be prefixed with `DEPRECATED:` to communicate that using the `--flow` option with `prefect deploy` is deprecated.

@desertaxle Which issue is this deprecation discussed in? (It has some usecase downsides I would like to discuss.)
