### ISSUE TITLE
Prefect incorrectly schedules job multiple times with only seconds apart (RRULE schedule)

### ISSUE THREAD

**Issue by chris-aeviator** [PrefectHQ/prefect#9995]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When scheduling a deployment via rrule I'm seeing the schedule being generated multiple times.

![grafik](https://github.com/PrefectHQ/prefect/assets/11522213/4040df37-c746-479b-a72b-85d59aadec5b)

Prefect further schedules **ANOTHER** run once the run runs. This leads to catastrophic cascading effects since with every run another run is scheduled at the same time (seconds apart). Before the scheduled flow runs the schedule is presented correctly (one run per hour). After the first scheduled flow runs, the next run is duplicated and so on.

![grafik](https://github.com/PrefectHQ/prefect/assets/11522213/1034ded2-e0b9-44b7-9a20-88504ecb5ca9)

### Reproduction

```python3
@flow(name="trigger_job")
def trigger_job(actions):
    for step in actions:
        execute_spark_job(step['filename'])

deployment = await Deployment.build_from_flow(
            flow=trigger_job,
            name=name,
            schedule=RRuleSchedule(rrule='FREQ=DAILY;BYDAY=MO;BYHOUR=13,14,15,16;BYMINUTE=36', timezone=timezone),
            parameters={
               "actions" : [ ... ]
            }
)
await deployment.apply()
```

### Versions

```Text
Version:             2.7.10
API version:         0.8.4
Python version:      3.8.10
Git commit:          f269d49b
Built:               Thu, Jan 26, 2023 3:51 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

### Additional context

I'm deploying the flow from within another flow

**Comment by chris-aeviator** [comment]
After the second subflow is finished, i end up with another duplicate for the next hour
![grafik](https://github.com/PrefectHQ/prefect/assets/11522213/a65495b2-5a5d-40cb-a853-424711a324ad)

**Comment by zhen0** [comment]
Hi @chris-aeviator - thanks for the issue.  Can you try updating to 2.10.15 and see if the issue persists.  We had reports of this in earlier versions but it should now be fixed.  Thanks!

**Comment by chris-aeviator** [comment]
@zhen0 it looks like an update to 2.10.15 solves the issue. I can also see that my runs are now always scheduled at second zero (04:45:00 PM) and does not conflict anymore.

This was only the first test, I will kepe watching this for the rest of the day and close accordingly if solved also after multiple scheduled runs.

**Comment by zhen0** [comment]
Thanks for the update @chris-aeviator
